### ISSUE TITLE
Open Performance dashboard results blank page pointing to localhost rather ingress endpoint

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#1]
I have application deployed from codewind-che on  IBM Cloudprivate. When I try to access performance dashboard, I am getting blank page and the URL pointing to "localhost" rather ingress endpoint. 

![image](https://user-images.githubusercontent.com/713849/59977599-02c13300-95a1-11e9-850d-b0b48ca3b913.png)

![image](https://user-images.githubusercontent.com/713849/59977611-2b492d00-95a1-11e9-9f95-31831371a6ac.png)

Logs 
[che.txt](https://github.com/eclipse/codewind/files/3317997/che.txt)
[che-machine.txt](https://github.com/eclipse/codewind/files/3317998/che-machine.txt)
[codewind.txt](https://github.com/eclipse/codewind/files/3317999/codewind.txt)
[editor.txt](https://github.com/eclipse/codewind/files/3318000/editor.txt)
[sidecar.txt](https://github.com/eclipse/codewind/files/3318001/sidecar.txt)

**Comment by tobespc** [comment]
Thanks for raising this, will investigate asap

**Comment by tobespc** [comment]
This is an environment we have not tested yet so I'm not surprised it doesn't work though

**Comment by tetchel** [comment]
Jag, do you mean the 'performance dashboard'? This doesn't work because the performance container is not deployed by the che sidecar. 

The URL is correct now, but it is a 404 because there's no server running.

I removed Performance Dashboard action in https://github.com/eclipse/codewind-vscode/pull/83

**Comment by tobespc** [comment]
this is now landed and resolved
