### ISSUE TITLE
Typo in install instructions

### ISSUE THREAD

**Issue by rtaniwa** [eclipse/codewind#10]
Minor typo in the install instructions for VS Code:

Click Install **whem** prompted. The download is approximately 1 GB.

**Comment by sishida** [comment]
@rtaniwa Hi, Rob, I have created a pull request to fix this typo: https://github.com/eclipse/codewind-vscode/pull/101 Thank you!

**Comment by rajivnathan** [comment]
It's now merged. Thanks!
