### ISSUE TITLE
Template without a projectStyle should default to "other" rather than "Codewind"

### ISSUE THREAD

**Issue by james-wallis** [eclipse/codewind#1010]
**Codewind version:** Master

**Description of the enhancement:**

When we make a GET API request to `/api/v1/templates` we are able to specify a `projectStyle` query parameter which will get the templates for a given style.

Currently, if a template doesn't have a `projectStyle` property it is defaulted to "Codewind" here in the code: 
```
function getTemplateStyle(template) {
  // if a project's style isn't specified, it defaults to 'Codewind'
  return template.projectStyle || 'Codewind';
}
```
https://github.com/eclipse/codewind/blob/master/src/pfe/portal/modules/Templates.js#L502

I think (and have checked with @tobespc) that it would be better to default to "Other".
We are in control of the Codewind templates and should add our own `projectStyle` property as "Codewind".

**Proposed solution:** 

* Change the Codewind templates to have a `projectStyle` property and set it to "Codewind". https://github.com/kabanero-io/codewind-templates/blob/master/devfiles/index.json
* Change the `getTemplateStyle` function to default to "Other" https://github.com/eclipse/codewind/blob/master/src/pfe/portal/modules/Templates.js#L502

**Comment by tobespc** [comment]
going forwards, style is going to mean the style of project we can build - so 'appsody' 'codewind' 'odo'

If the project is not one of these styles then we can't build it

**Comment by tobespc** [comment]
closing as default of codewind fits in with the current design going forwards
