### ISSUE TITLE
Cannot remove projects

### ISSUE THREAD

**Issue by yangcao77** [eclipse/codewind#1012]
**Codewind version:** master
**OS:** MacOS

**Che version:**
**IDE extension version:** VSCode plugin 0.6.0(master)
**IDE version:** 
**Kubernetes cluster:**

**Description:**
Not able to remove a  project. 

![image](https://user-images.githubusercontent.com/22285490/68328540-7fab0000-009d-11ea-92fb-4b40b77cd791.png)

The project directory still exist as well. 

**Steps to reproduce:**
1. create a project in vscode
2. click "remove project"

**Workaround:**

**Comment by makandre** [comment]
I'll look into this

**Comment by makandre** [comment]
The `/api/v1/projects/:id/unbind` route appears to be removed.

https://github.com/eclipse/codewind/pull/1004/files#diff-2aedf9823dfed0c38b88651bff30110dL148

This affects all projects, not just appsody

**Comment by tetchel** [comment]
Confirmed the project removal endpoint is gone now
```
[INFO: 14:19:56.330 Requester.js:388]: Doing Unbinding request to http://127.0.0.1:34000/api/v1/projects/76510c80-ffd9-11e9-ae28-b75f9ce21e39/unbind
Logger.js:140
[WARN: 14:19:56.337 Requester.js:401]: Error doing Unbinding project request for nodep: StatusCodeError: 404 - "Not Found"
	at new StatusCodeError (/Users/tim/programs/codewind-vscode/dev/node_modules/request-promise-core/lib/errors.js:32:15)
```

**Comment by sujeilyfonseca** [comment]
**Codewind version:** codewind-0.6.0-201911061850.vsix
**OS:** VM with Windows 10

**IDE extension version:** 0.6.0
**IDE version:** 1.39.2

I noticed this problem too, with projects not disabled in Windows:

![Screen Shot 2019-11-06 at 2 44 12 PM](https://user-images.githubusercontent.com/49531960/68331973-efbc8480-00a3-11ea-9afa-ed83d1b3ec37.png)

**Comment by yangcao77** [comment]
Yes. This is a common issue for all projects, and happens on both che & local. 
It's because the route is gone as mentioned in https://github.com/eclipse/codewind/issues/1012#issuecomment-550461010

**Comment by rajivnathan** [comment]
Put up a PR and verified using Eclipse. https://github.com/eclipse/codewind/pull/1022 Can someone from portal please review and merge if it's acceptable. Thanks.

**Comment by stalleyj** [comment]
This should be fixed now, thanks @rajivnathan

**Comment by malincoln** [comment]
@yangcao77 pls verify.  Thanks

**Comment by yangcao77** [comment]
Verified this issue has been fixed in latest master branch.
