### ISSUE TITLE
Can projects be rebind to Codewind after Che workspace restarts?

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#1018]
**Codewind version:** 0.6.0
**OS:**

**Che version:** 7.3.0
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Question synopsis:**

Noticing that if the Che workspace is stopped and then restarted, projects previously bound to Codewind needs to be rebind to Codewind.  To make matters worst, in Che 7.3.0 there seems to be an `activity-checker` that stops my workspace after a period of inactivity

**Comment by makandre** [comment]
PFE's volume (i.e. `/codewind-workspace` where `.inf` files reside) is released when PFE is shutdown.  Therefore when PFE come's back there are no `.inf` files for it to know what to rebind

**Comment by tetchel** [comment]
from @jagraj, this is a regression from 0.5. it makes sense since the workspace, and therefore `.projects/*.inf` would have been persisted, but that has changed in the new architecture

**Comment by makandre** [comment]
The `CHE_WORKSPACE_AGENT_DEV_INACTIVE__STOP__TIMEOUT__MS: '0'` property suggested by @johnmcollier does seem to disable the `activity-checker` at least

**Comment by johnmcollier** [comment]
Removing tech-topic as I was able to find a relatively simple fix for this

**Comment by rajivnathan** [comment]
@makandre Can you please verify and close?

**Comment by makandre** [comment]
Verified
