### ISSUE TITLE
Failed to create Codewind Keycloak route on ROKS due to host length

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#1019]
My `cwctl install` got stuck at the "Waiting for Keycloak to start" step.

```
[ /tim/programs/codewind ] 30 (master) $ k get po
kNAME                                         READY   STATUS    RESTARTS   AGE
codewind-keycloak-k2nsm9mj-8d7dc7f48-hk9mt   1/1     Running   0          3m
[ /tim/programs/codewind ] 30 (master) $ k get route
NAME                         HOST/PORT     PATH   SERVICES                     PORT   TERMINATION     WILDCARD
codewind-keycloak-k2nsm9mj   InvalidHost          codewind-keycloak-k2nsm9mj   8080   edge/Redirect   None
[ /tim/programs/codewind ] 31 (master) $ k describe route codewind-keycloak-k2nsm9mj
Name:         codewind-keycloak-k2nsm9mj
Namespace:    codewind
Labels:       app=codewind-keycloak
              codewindWorkspace=k2nsm9mj
Annotations:  <none>
API Version:  route.openshift.io/v1
Kind:         Route
Metadata:
  Creation Timestamp:  2019-11-06T21:27:18Z
  Resource Version:    9497528
  Self Link:           /apis/route.openshift.io/v1/namespaces/codewind/routes/codewind-keycloak-k2nsm9mj
  UID:                 360350f5-00dc-11ea-baff-b2019f2f024b
Spec:
  Host:  codewind-keycloak-k2nsm9mj-codewind-ide-7674b4bd9abbdeea0be228236d5275c9-0001.tor01.containers.appdomain.cloud
  Port:
    Target Port:  8080
  Tls:
    Insecure Edge Termination Policy:  Redirect
    Termination:                       edge
  To:
    Kind:           Service
    Name:           codewind-keycloak-k2nsm9mj
    Weight:         100
  Wildcard Policy:  None
Status:
  Ingress:
    Conditions:
      Last Transition Time:  2019-11-06T21:27:18Z
      Message:               host name validation errors: spec.host: Invalid value: "codewind-keycloak-k2nsm9mj-codewind-ide-7674b4bd9abbdeea0be228236d5275c9-0001.tor01.containers.appdomain.cloud": must be no more than 63 characters
      Reason:                InvalidHost
      Status:                False
      Type:                  Admitted
    Host:                    codewind-keycloak-k2nsm9mj-codewind-ide-7674b4bd9abbdeea0be228236d5275c9-0001.tor01.containers.appdomain.cloud
    Router Name:             router
    Wildcard Policy:         None
Events:                      <none>
```

and here we see the error:
>       Message:               host name validation errors: spec.host: Invalid value: "codewind-keycloak-k2nsm9mj-codewind-ide-7674b4bd9abbdeea0be228236d5275c9-0001.tor01.containers.appdomain.cloud": must be no more than 63 characters

From @johnmcollier, ROKS will nearly always have a hostname that is too long. The suggested fix is to **not** set the `Host` in this line: 
https://github.com/eclipse/codewind-installer/blob/master/pkg/utils/remote/deploy_keycloak.go#L214

**Comment by markcor11** [comment]
I can pick this up.  The change will need to capture the auto-generated hostname at the time the route is added (or look it up before creating the config-map) and use that version instead of the pre-determined version.  A similar change will also be required for the codewind-gatekeeper route too.

**Comment by markcor11** [comment]
suggested fix of removing the host did not work, researching other ways

**Comment by markcor11** [comment]
Seems that the 63 char limit is **per component** of the hostname where the hostname can be up to 256 chars long. In the example provided the violation would be in this part of the hostnamename coming in at 78 characters:

```codewind-keycloak-k2nsm9mj-codewind-ide-7674b4bd9abbdeea0be228236d5275c9-0001```

By using a dot separator after codewind-keycloak-k2nsm9mj we could get the size down to 27 + 51 (both below 63) and can further reduce the impact by reducing the characters in the phrase codewind-keycloak-k2nsm9mj to just 14.  We also don't really need to see the namespace in the URL so could remove that further reducing the overall length.

**Comment by markcor11** [comment]
Seems that the 63 char limit is **per component** of the hostname where the hostname can be up to 256 chars long. In the example provided the violation would be in this part of the hostname coming in at 78 characters:

```codewind-keycloak-k2nsm9mj-codewind-ide-7674b4bd9abbdeea0be228236d5275c9-0001```

By using a dot separator after codewind-keycloak-k2nsm9mj we could get the size down to 27 + 51 (both below 63) and can further reduce the impact by reducing the characters in the phrase codewind-keycloak-k2nsm9mj to just 14.  We also don't really need to see the namespace in the URL so could remove that further reducing the overall length.

**Comment by markcor11** [comment]
PR https://github.com/eclipse/codewind-installer/pull/204

**Comment by tetchel** [comment]
verified
