### ISSUE TITLE
Keycloak data does not persist after cluster restart

### ISSUE THREAD

**Issue by markcor11** [eclipse/codewind#1024]
When deploying Remote + Keycloak into Kubernetes,  the Keycloak container uses the internal H2 Java database to store configuration of realms / clients / users / roles / keys etc.  If the pod is re-scheduled the configuration is lost and must be re-configured from scratch 

Possible options :

1.  Move the H2 Java database files to a R/W persistent volume claim that will survive the restart

2. Adopt the Keycloak recommended method and use an external SQL database (Che uses Postgres which itself has a persistent volume claim)

Raising on tech topics to discuss options

**Comment by jopit** [comment]
2. has caused Che multiple problems, they are moving away from this architecture.
1. better than #1 but it requires yet another persistent volume

Mark will investigate if there's a better solution.

**Comment by markcor11** [comment]
Closing - code merged into master
