### ISSUE TITLE
Can't access app on Che

### ISSUE THREAD

**Issue by rajivnathan** [eclipse/codewind#1034]
**Codewind version:** latest
**OS:** Mac OS

**Che version:** 7.1
**IDE extension version:** latest
**IDE version:** 7.1
**Kubernetes cluster:** OKD

**Description:**
```
Name:			cw-nodejstestprojectforjag-c138afd0-0184-11ea-bc01-fd092e0jthxb
Namespace:		che
Created:		10 minutes ago
Labels:			projectID=c138afd0-0184-11ea-bc01-fd092e013ee4
Annotations:		<none>
Requested Host:		nodejstestprojectforjag-codewind-workspace61vfgz89tr2n0jlx-che-che.x.x.x.x.nip.io
			  rejected by router router: InvalidHost (10 minutes ago)
			    host name validation errors: spec.host: Invalid value: "nodejstestprojectforjag-codewind-workspace61vfgz89tr2n0jlx-che-che.x.x.x.x.nip.io": must be no more than 63 characters
Path:			/
TLS Termination:	<none>
Insecure Policy:	<none>
Endpoint Port:		3000

Service:	cw-nodejstestprojectforjag-c138afd0-0184-11ea-bc01
Weight:		100 (100%)
Endpoints:	10.129.1.247:3000
```

**Steps to reproduce:**
Create a project with a fairly long name, in my case I used `nodejstestprojectforjag`.

To see the error you can describe the route:
`oc describe route`

It should show the error above.

**Workaround:**

**Comment by tetchel** [comment]
similar to https://github.com/eclipse/codewind/issues/1019

**Comment by johnmcollier** [comment]
I can't reproduce on OCP 4, must be differences in the router between OCP 3 and 4.

**Comment by rajivnathan** [comment]
Verified fixed. Thanks!
