### ISSUE TITLE
Blank notifications seen in Theia

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#1035]
https://github.com/eclipse-theia/theia/issues/6506

It looks like we are seeing this on theia 7.1 which was used for our 0.5 release, which did not have this issue. so it is possible that this issue is being caused by a change in the codewind extension. The most common message we are seeing blank is the "fetching project types" message.

labelled as hot because it looks bad and everyone is seeing it

**Comment by tetchel** [comment]
It looks like updating to theia 7.3.1 fixes the issue. Also, it looks like withProgress `cancellable` is now respected (https://github.com/eclipse-theia/theia/issues/5578) so maybe this was fixed at the same time

**Comment by jagraj** [comment]
We can move to theia 7.3.1 for 0.6.0 release.?

**Comment by tetchel** [comment]
nevermind, it has to be resolved on my end https://github.com/eclipse-theia/theia/issues/6506#issuecomment-553211707

**Comment by tetchel** [comment]
should be fixed now @jagraj
