### ISSUE TITLE
SVT:[Windows]:Failed to create appsody project on windows and error is coming from codewind-installer

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#1036]
**Codewind version:** 0.6
**OS:** WIndows

**Che version:**
**IDE extension version:** 0.6
**IDE version:** Eclipse 2019-09
**Kubernetes cluster:**

**Description:**
Failed to create appsody microprofile java project on Windows and I get following failure.

![image](https://user-images.githubusercontent.com/713849/68418935-4212a980-0167-11ea-85b9-dbb4aaa9f5b1.png)

[pfe.txt](https://github.com/eclipse/codewind/files/3821261/pfe.txt)
[.log](https://github.com/eclipse/codewind/files/3821262/default.log)

```
An error occurred trying to create Codewind project appsodyempcwlatestsvt
panic: Post http://127.0.0.1:10000/api/v1/projects/c1509910-018e-11ea-97e7-572a69bbc417/bind/end: EOF

goroutine 1 [running]:
github.com/eclipse/codewind-installer/pkg/utils/project.completeBind(0xc00020e000, 0x24, 0xc0002f1be0, 0x1e, 0xc0002f1be0, 0x1e, 0x0)
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/pkg/utils/project/bind.go:164 +0x21c
github.com/eclipse/codewind-installer/pkg/utils/project.Bind(0xc000072060, 0x55, 0xc00007e140, 0x15, 0xc0000800f8, 0x4, 0xc000080130, 0x10, 0x143a5b0, 0x5, ...)
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/pkg/utils/project/bind.go:145 +0xa74
github.com/eclipse/codewind-installer/pkg/utils/project.BindProject(0xc0004da6e0, 0x1439f34, 0x4)
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/pkg/utils/project/bind.go:68 +0x232
github.com/eclipse/codewind-installer/pkg/actions.ProjectBind(0xc0004da6e0)
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/pkg/actions/project.go:64 +0x7b
github.com/eclipse/codewind-installer/pkg/actions.Commands.func2(0xc0004da6e0, 0x0, 0xc0004ceaf0)
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/pkg/actions/commands.go:86 +0x32
github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli.HandleAction(0x1275e80, 0x14cdc78, 0xc0004da6e0, 0xc0004da6e0, 0x0)
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli/app.go:514 +0xc5
github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli.Command.Run(0x1439e40, 0x4, 0x0, 0x0, 0xc000162130, 0x1, 0x1, 0x147d84b, 0x3b, 0x0, ...)
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli/command.go:171 +0x4ab
github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc0002f3340, 0xc0004da420, 0x0, 0x0)
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli/app.go:395 +0x87e
github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli.Command.startApp(0x143b77d, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x144c873, 0x18, 0x0, ...)
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli/command.go:383 +0x80f
github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli.Command.Run(0x143b77d, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x144c873, 0x18, 0x0, ...)
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli/command.go:103 +0x8f6
github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli.(*App).Run(0xc0002f3180, 0xc0000bc000, 0xb, 0x10, 0x0, 0x0)
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli/app.go:265 +0x712
github.com/eclipse/codewind-installer/pkg/actions.Commands()
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/pkg/actions/commands.go:652 +0x5353
main.main()
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/cmd/cli/main.go:26 +0x33
```

**Steps to reproduce:**
1. Get latest eclipse plugin and install codewind with the latest tag.
2. After codewind started I tried to create appsody eclipse microprofile project and then it fails to create project with above stack trace.

**Workaround:**

**Comment by jagraj** [comment]
@sujeilyfonseca @eharris369 

I got into this problem with the latest eclipse and pfe images on my windows. I see you verified and closed similar problem (https://github.com/eclipse/codewind/issues/997) yesterday. 

Erin, can you give it a try when you get a chance.?

**Comment by johnmcollier** [comment]
Adding stopship as requested by Jag

**Comment by eharris369** [comment]
It worked for me.  Took a while to go into started state because it initially times out:
```
[27/10/19 02:20:13 appsodyMP1] [INFO] Emitting event
 message: projectStatusChanged
 data: {
  "projectID": "ee9d2b50-f85f-11e9-9d19-730ff5657778",
  "appStatus": "stopped",
  "appErrorStatus": "Failed to ping application due to timeout."
}
```

![image](https://user-images.githubusercontent.com/9484320/68430004-3df18680-017d-11ea-9dde-8c6486f0dc4d.png)

**Comment by jagraj** [comment]
I have this eclipse plugin and pfe image on my system..

```  Codewind tech preview	0.6.0.v201911071125	org.eclipse.codewind.feature.group	Eclipse.org

codewind-performance-amd64                                  latest                 3fc9a769d1e9        6 hours ago         85.3MB
eclipse/codewind-pfe-amd64                                  latest                 8390e419db81        6 hours ago         781MB

```

**Comment by sujeilyfonseca** [comment]
**OS:** VM with Windows 10

**[Visual Studio Code]**
**Codewind version:** codewind-0.6.0-201911071935.vsix 
**IDE extension version:** 0.6.0
**IDE version:** 1.39.2

**[Eclipse IDE for Enterprise Java Developers ]**
**Codewind version:** codewind-0.6.0-201911071125.zip
**IDE extension version:** 0.6.0
**IDE version:** 2019-06 (4.12.0)

I deleted all the files (e.g., .codewind, .appsody), volumes and images, and performed `docker system prune -a` on my machine. After that, I tested this GitHub issue, and I couldn't reproduce the problem in VS Code or Eclipse using the latest plugins:

![Screen Shot 2019-11-07 at 5 21 25 PM](https://user-images.githubusercontent.com/49531960/68434965-3e434f00-0188-11ea-88b2-afb723bb6838.png)

<img width="1514" alt="Screen Shot 2019-11-07 at 5 45 56 PM" src="https://user-images.githubusercontent.com/49531960/68434966-3edbe580-0188-11ea-8b7c-83b2ee96faa8.png">

**Comment by makandre** [comment]
Is it possible that the `bind/end` is actually throwing a legitimate error, but it is hidden and we get an `EOF` because we're not returning a response body here?

https://github.com/eclipse/codewind/blob/master/src/pfe/portal/routes/projects/remoteBind.route.js#L375

**Comment by mattcolegate** [comment]
Looking into this

**Comment by mattcolegate** [comment]
Windows 10
VSCode: http://download.eclipse.org/codewind/codewind-vscode/master/178/codewind-0.6.0-201911071935.vsix
PFE: codewind-pfe-amd64                   latest                 sha256:c641dd7f23b7f422d5d1c02caf6e7073d5bb7883fd333c4156bda12f187f6ec3

Unable to recreate. Appsody Microprofile Java project is created successfully and starts successfully, although I did see the timeout @eharris369 saw.

Logs:
[1036PFELogAppsodyMicroprofileJavaCreate.txt](https://github.com/eclipse/codewind/files/3824243/1036PFELogAppsodyMicroprofileJavaCreate.txt)
[1036ContainerLogAppsodyMicroprofileJava.txt](https://github.com/eclipse/codewind/files/3824244/1036ContainerLogAppsodyMicroprofileJava.txt)

@jagraj Can this be retested on latest versions please?

**Comment by jagraj** [comment]
I uninstalled codewind, eclipse plugin, removed workspace volume and got all latest this morning and I no longer see this problem. Thanks to everyone who tried to recreate this problem. I am all good now and closing this issue.
