### ISSUE TITLE
Screen captures/animated gifs for the news pages

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind#1037]
This issue comes from https://github.com/eclipse/codewind/issues/712.

@deboer-tim states, "It would be great to start including small screen caps or animated gifs to show the feature. This is both easier to read and understand and shows the user where the change is. See https://code.visualstudio.com/updates/v1_39 as an example."

**Comment by beccabau** [comment]
That would be more engaging. We'll look to incorporate them in the future!
