### ISSUE TITLE
Docs: remove a line in appsody troubleshooting

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#1038]
**Codewind version:** 0.6.0
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**

For this section: https://www.eclipse.org/codewind/troubleshooting.html#appsody-mount-errors-on-windows-enterprise

Remove the line which is no longer accurate:

`You might receive an error message in the appsody.log file when you try to create an Appsody project:`

The rest of the section can stay as-is

**Steps to reproduce:**

**Workaround:**

**Comment by makandre** [comment]
FYA @sishida

**Comment by sishida** [comment]
Hi, @makandre, I have created the PR (https://github.com/eclipse/codewind-docs/pull/217), but if users don't receive the error message in the `appsody.log` file anymore, should we tell them where the message will appear instead?

**Comment by makandre** [comment]
Good point, I think you'll now get similar message from `cwctl`, which on VSCode is available from the Codewind log

![image](https://user-images.githubusercontent.com/17596240/68428495-51e7b900-017a-11ea-828c-48a40ad4a221.png)

I don't know if we expose `cwctl` messages in Eclipse, @eharris369?

**Comment by eharris369** [comment]
The cwctl messages are only shown to the user if the cwctl command fails (non-zero return code).

**Comment by sishida** [comment]
@makandre, @eharris369, OK, sounds like the users won't need to dig around to find the message and that it appears as needed. I have removed the line that was obsolete. Closing this issue.
