### ISSUE TITLE
Codewind-resources templates are missing helm charts

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#1040]
The codewind-resources project templates (https://raw.githubusercontent.com/codewind-resources/codewind-templates/master/devfiles/index.json) are missing Helm charts and won't properly deploy (or cause issues) on Codewind on Che / Kube.

For example:
- https://github.com/codewind-resources/goTemplate
- https://github.com/codewind-resources/springJavaTemplate
- https://github.com/codewind-resources/lagomJavaTemplate

The templates on https://github.com/microclimate-dev2ops **do** have Helm charts.

**Comment by tobespc** [comment]
I took the helm charts out deliberately, will put them back in

**Comment by tobespc** [comment]
charts have been put back in

**Comment by johnmcollier** [comment]
Verified, fixed.
