### ISSUE TITLE
Improve table of contents on mobile devices

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind#1043]
When you view https://www.eclipse.org/codewind/ on a mobile device, the table of contents obscures the page itself. Could we get the table of contents to expand/retract on the side when you swipe the screen or get it to collapse in a way that's less intrusive on the page?

Note: This is a low priority enhancement. Other issues take priority.

**Comment by sishida** [comment]
@beccabau If you find an example of a website that has a table of contents that collapses nicely on mobile devices, could you please include the link here? Thanks!

**Comment by jcockbain** [comment]
This has been duplicated here https://github.com/eclipse/codewind/issues/3172 @sishida. 

That one refers to the the new landing page though, and why this is now more important. Should we close this one in favour of that issue?

**Comment by sishida** [comment]
@jcockbain Thank you for letting me know. Closing this issue.
