### ISSUE TITLE
SVT:Creating lagom project display error "BAD_REQUEST:watchedFiles is not a configurable setting" to the user 

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#1044]
**Codewind version:** 0.6 
**OS:** Mac/Windows 

**Che version:**
**IDE extension version:** 0.6
**IDE version:** Eclipse 2019-09
**Kubernetes cluster:**

**Description:**
Create lagom project with the latest images and plugin, I get this failure message.
"BAD_REQUEST:watchedFiles is not a configurable setting"

![image](https://user-images.githubusercontent.com/713849/68433618-f4a53500-0184-11ea-8769-4cbef6e5ea43.png)

**Steps to reproduce:**

**Workaround:**

**Comment by tobespc** [comment]
fixed, the lagom template had a .cw-settings files in there that had the watchedFiles setting which is no longer valid

**Comment by malincoln** [comment]
@jagraj pls verify and close if resolved.  Thanks

**Comment by jagraj** [comment]
I do not see this problem now.
