### ISSUE TITLE
Create a new doc for upgrading Codewind on Che installs

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#1045]
Currently the Codewind on Che docs only provide instructions for installing a new Codewind workspace in Che, and not on upgrading a Codewind workspace from release `0.x.0` to `0.y.0`

We need a doc to tell users how:
- They can upgrade a Che workspace
    - Once we're onboarded to the Che plugin registry, this'll be especially important, as Che provides an easy mechanism to upgrade plugins in the registry
- Any additional steeps needed before upgrading a workspace

**Comment by j-c-berger** [comment]
@sishida , I'm good to work on this issue, so please add me, thanks!

**Comment by j-c-berger** [comment]
@johnmcollier where would I go to learn how to upgrade the Codewind workspace so I can document those steps? I tried to install Eclipse Che so I could upgrade the Codewind workspace myself, and document those steps, but that didn't get me too far. Thank you.

**Comment by johnmcollier** [comment]
@j-c-berger I'll write the steps, I'll just need you guys edit it for ID

**Comment by j-c-berger** [comment]
Cool, thank you, John.

**Comment by j-c-berger** [comment]
@johnmcollier wanted to follow up on the progress of the steps. Let me know if you need/want my help with anything now during the drafting of them. Thanks.

**Comment by johnmcollier** [comment]
@j-c-berger Working on it today, I'll send you a draft when it's ready.

**Comment by johnmcollier** [comment]
# Updating Codewind on Eclipse Che

1. Determine which Che version you are running
    - Navigate to the Che dashboard and the version of Che will be visible at the bottom
       <img width="1358" alt="Screen Shot 2019-11-14 at 9 13 11 AM" src="https://user-images.githubusercontent.com/6880023/68864705-91089380-06bf-11ea-9068-de12c5f42b36.png">

2. Download the newest devfile from Github.
    - The devfile for Codewind 0.6.0 can be found at https://raw.githubusercontent.com/eclipse/codewind-che-plugin/master/devfiles/0.6.0/devfile.yaml

3. If your Che version is backlevel, update Che
    - Codewind 0.6.0 requires Che 7.3.1 or higher.
    - Run `kubectl get checluster`. Find the name of your Che install:
      ```
      sh$ johncollier$ kubectl get checluster
      NAME          AGE
      codewind-che   19h
      ```
    - Run `kubectl edit checluster <che>`, where `che` is the name of your Che install found in the previous step
    - Change the image tags on `spec.server.cheImage`, `spec.server.devfileRegistryImage`, `spec.server.pluginRegistryImage`, and `spec.auth.identityProviderImage` to `7.3.1` (or the version of Che that you desire)

2. Apply new roles for Codewind
    - The roles that Codewind requires may have been updated from release to release. To be safe, it's best to update the Codewind roles as well
    - Run the following command:
       ```
       kubectl apply -f https://raw.githubusercontent.com/eclipse/codewind-che-plugin/master/setup/install_che/codewind-clusterrole.yaml && \
       kubectl apply -f https://raw.githubusercontent.com/eclipse/codewind-che-plugin/master/setup/install_che/codewind-clusterrole.yaml
       ```
    
3. Once Che has been updated, update your Codewind workspace:
    - Click on the 'gear' tab next to your workspace in the Che dashboard to open its settings page
    - In the settings, navigate to the `Devfile` tab
       <img width="934" alt="Screen Shot 2019-11-14 at 8 29 53 AM" src="https://user-images.githubusercontent.com/6880023/68865008-13915300-06c0-11ea-9482-b2206b1e7467.png">
    - Copy and paste the devfile that was downloaded earlier into the text box. Hit `Save` and then `Run` to restart the workspace.

**Comment by j-c-berger** [comment]
@johnmcollier, thank you. I have a couple of meetings coming up, but will start to work on this issue later this afternoon into tomorrow morning. I'll make sure it's done by tomorrow afternoon to meet our deadline.

**Comment by j-c-berger** [comment]
@johnmcollier, thank you for your patience as this issue took longer than expected to complete. It's on top priority when I return to the office on Mon., Nov. 18th!

**Comment by jagraj** [comment]
@johnmcollier 

I am verifying these upgrade instructions.. We are recommending this to the users now `--che-operator-image=quay.io/eclipse/che-operator:7.3.1`. Do you think it makes sense to include this in these instructions.?

**Comment by j-c-berger** [comment]
@johnmcollier and @jagraj 

I'm checking on the status of this issue and to see if there's any ID work that still needs to be done? Thanks!

**Comment by johnmcollier** [comment]
@j-c-berger Nothing currently, but I'll keep you in the loop regarding changes.

**Comment by j-c-berger** [comment]
@johnmcollier and/or @jagraj , do we think this issue is still for 0.7.0? ID team just did iteration planning today and thought if this issue is best to be postponed?

**Comment by sishida** [comment]
Jag, John, and ID agreed to not include this issue in 0.7.0. Release to be determined.

**Comment by sishida** [comment]
Jag, John, and ID agreed to not include this issue in 0.8.0. Release to be determined.
