### ISSUE TITLE
[Local] Swift Projects do not pick up changes

### ISSUE THREAD

**Issue by maysunfaisal** [eclipse/codewind#1047]
**Codewind version:** latest
**OS:** ~Win~ All local

**Che version:**
**IDE extension version:**
**IDE version:** latest
**Kubernetes cluster:**

**Description:**
Download vsix from latest, get the latest cwctl & PFE. Create Swift project, make change, wait for build to finish.

The application does not pick up the change.

~Needs to be confirmed for Mac local~. Does not work on Mac as well

Confirmed works for Che.

**Steps to reproduce:**

**Workaround:**

**Comment by tobespc** [comment]
@rwalle61 please take a look

**Comment by rwalle61** [comment]
I'll pick this up

**Comment by rwalle61** [comment]
So on my Mac local, Swift Projects do not appear to pick up changes. 

Changing the code locally triggers a sync with the code in the project container. However, the project does not appear to behave according to the source code - e.g. when I comment out `app.run` locally and wait for the project to rebuild and restart, the app still runs.

I'm unsure why this is. I'm not familiar with Swift, but perhaps our build somehow ignores the new source code when it rebuilds?

**Comment by rajivnathan** [comment]
I believe swift is doing a container rebuild even on update scenarios so the source would need to be synced to the pfe workspace instead of directly to the project container.

**Comment by rwalle61** [comment]
I should have specified - the source is synced to the `codewind-workspace` in pfe too. (which baffles me as to how the build isn't reflecting the source)

**Comment by maysunfaisal** [comment]
MAY have found the issue

`Step 11/11 : CMD [ "sh", "-c", "cd /swift-project && .build-ubuntu/release/swwwiiii1" ]` is the docker application step for Swift container

But between all the copying from "swiftproject-build" container to "PFE workspace" and then to "swift" container; it seems like `.build-ubuntu/release/swwwiiii1` is not updated on PFE between updates.

### Before update in PFE container
```
[root@390aaeaea55a swwwiiii1]# ls -la
total 80
drwxrwxr-x  6 root root 4096 Nov  8 14:59 .
drwxrwxrwx 13 root root 4096 Nov  8 14:54 ..
drwxr-xr-x  6 root root 4096 Nov  8 15:01 .build-ubuntu
-rw-rw-r--  1 root root  118 Nov  8 14:59 .cw-settings
-rw-rw-r--  1 root root   28 Nov  8 14:59 .dockerignore
-rw-rw-r--  1 root root   96 Nov  8 14:59 .gitignore
-rw-rw-r--  1 root root    6 Nov  8 14:59 .swift-version
-rw-rw-r--  1 root root    0 Nov  8 14:59 .swiftservergenerator-project
-rw-rw-r--  1 root root 1133 Nov  8 14:59 Dockerfile
-rw-rw-r--  1 root root 1305 Nov  8 14:59 Dockerfile-tools
-rw-rw-r--  1 root root 1077 Nov  8 14:59 LICENSE
-rw-rw-r--  1 root root 6644 Nov  8 14:59 Package.resolved
-rw-rw-r--  1 root root  930 Nov  8 14:59 Package.swift
-rw-rw-r--  1 root root 4323 Nov  8 14:59 README.md
drwxrwxr-x  4 root root 4096 Nov  8 14:54 Sources
drwxrwxr-x  3 root root 4096 Nov  8 14:59 Tests
drwxrwxr-x  3 root root 4096 Nov  8 14:54 chart
-rw-rw-r--  1 root root 2009 Nov  8 14:59 cli-config.yml
-rw-rw-r--  1 root root 2627 Nov  8 14:59 iterative-dev.sh

[root@390aaeaea55a swwwiiii1]# ls -la .build-ubuntu/release/swwwiiii1
-rwxr-xr-x 1 root root 5313592 Nov  8 14:58 .build-ubuntu/release/swwwiiii1
```

### After update on PFE container
```
[root@390aaeaea55a swwwiiii1]# ls -la
total 80
drwxrwxr-x  6 root root 4096 Nov  8 14:59 .
drwxrwxrwx 13 root root 4096 Nov  8 14:54 ..
drwxr-xr-x  6 root root 4096 Nov  8 15:01 .build-ubuntu
-rw-rw-r--  1 root root  118 Nov  8 14:59 .cw-settings
-rw-rw-r--  1 root root   28 Nov  8 14:59 .dockerignore
-rw-rw-r--  1 root root   96 Nov  8 14:59 .gitignore
-rw-rw-r--  1 root root    6 Nov  8 14:59 .swift-version
-rw-rw-r--  1 root root    0 Nov  8 14:59 .swiftservergenerator-project
-rw-rw-r--  1 root root 1133 Nov  8 14:59 Dockerfile
-rw-rw-r--  1 root root 1305 Nov  8 14:59 Dockerfile-tools
-rw-rw-r--  1 root root 1077 Nov  8 14:59 LICENSE
-rw-rw-r--  1 root root 6644 Nov  8 14:59 Package.resolved
-rw-rw-r--  1 root root  930 Nov  8 14:59 Package.swift
-rw-rw-r--  1 root root 4323 Nov  8 14:59 README.md
drwxrwxr-x  4 root root 4096 Nov  8 14:54 Sources
drwxrwxr-x  3 root root 4096 Nov  8 14:59 Tests
drwxrwxr-x  3 root root 4096 Nov  8 14:54 chart
-rw-rw-r--  1 root root 2009 Nov  8 14:59 cli-config.yml
-rw-rw-r--  1 root root 2627 Nov  8 14:59 iterative-dev.sh


[root@390aaeaea55a swwwiiii1]# ls -la .build-ubuntu/release/swwwiiii1
-rwxr-xr-x 1 root root 5313592 Nov  8 14:58 .build-ubuntu/release/swwwiiii1
```

**Comment by rajivnathan** [comment]
Upgraded to stopship because swift update is essentially broken.

**Comment by maysunfaisal** [comment]
This line is the culprit https://github.com/eclipse/codewind/blob/master/src/pfe/file-watcher/scripts/swift-container.sh#L321

All builds are broken - auto and manual

**Comment by rwalle61** [comment]
Was it caused by the last change (https://github.com/eclipse/codewind/pull/1004/files#diff-fcbabad6dc400c5ba51a1a7718671571L321) or a previous one? I am totally unfamiliar with this code

**Comment by maysunfaisal** [comment]
I got the root cause, I will put up a PR to fix it.

Essentially, docker cp does not overwrite. Need to `rm -rf ` before doing a docker cp to PFE workspace. 

Testing my fix on Win, if everything is ok, will open a PR

**Comment by maysunfaisal** [comment]
Can someone assign this to me, I can verify and close this as well. PR is up.
