### ISSUE TITLE
Win VSCode: Project overview local path click-through gives unexpected result

### ISSUE THREAD

**Issue by mattcolegate** [eclipse/codewind#1050]
**Codewind version:** 'latest' sha256:c641dd7f23b7f422d5d1c02caf6e7073d5bb7883fd333c4156bda12f187f6ec3
**OS:** Windows 10

**Che version:** NA
**IDE extension version:** 0.6.0-201911071935.vsix
**IDE version:** VSCode 1.40.0
**Kubernetes cluster:** N/A

**Description:** The local path in the project overview is clickable, but clicking it opens Windows Explorer in the root directory rather than the expected one e.g. displays c:\cq-projs\friNode1 but when clicked takes me to C:\. Tested with both Appsody Microprofile Java project and default Node project creation

**Steps to reproduce:** Create a project, open it's project overview and click on the Local Path value

**Workaround:** Manually navigate to the project directory from the root directory

**Comment by mattcolegate** [comment]
@tetchel Tried with latest development VSCode plugin and the situation has improved - I now get taken to the directory above e.g. clicking on c:\cq-projs\friNode1 takes me to C:\cq-projs. If that is the designed behaviour, then all I would ask is that can we make the drive letter a capital rather than a lowercase?

**Comment by tetchel** [comment]
I tried getting it to go to `c:\cq-projs\friNode1` but Explorer would always open to the parent directory, even with a trailing slash. It looks like I'd have to select a particular file under `c:\cq-projs\friNode1\` to get it to open the directory, and I didn't want to do that.

I'll capitalize the drive letter, added that to https://github.com/eclipse/codewind/issues/1834
