### ISSUE TITLE
Update Codewind on Kube install docs for the Tekton integration

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#106]
The Tekton integration in PFE that was recently delivered introduced new setup steps if installing Codewind on Che:
```
oc apply -f tekton/codewind-che-plugin/setup/install_che/codewind-tektonrole.yaml
oc apply -f tekton/codewind-che-plugin/setup/install_che/codewind-tektonbinding.yaml
```

Our manual install docs on https://www.eclipse.org/codewind/installoncloud.html need to be updated to reflect that.

**Comment by sishida** [comment]
@johnmcollier and @tetchel 
Hi, team, I'm looking at these new commands as well as the installoncloud doc and was wondering if I could please get more info. For example, where within the installoncloud doc page do we want to include the new commands? I'm guessing we should create a new section? Thanks!

**Comment by johnmcollier** [comment]
@tobespc @markcor11 Can you please help Sarah with the new install instructions for the Tekton integration? Thanks!

**Comment by sishida** [comment]
@tobespc and @markcor11 
This is the only Tekton info that we currently have in Codewind documentation: https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/codewindandtektonpipelines.md
I am happy to add more details if we want to. Please just let me know. Thank you!

**Comment by sishida** [comment]
@johnmcollier, @tobespc: Now that https://github.com/eclipse/codewind-docs/pull/67 has been merged, is this issue good to close? If so, could you please close it? (I'm not a committer yet.) Thank you!

**Comment by johnmcollier** [comment]
@sishida Yup!
