### ISSUE TITLE
Doc: add troubleshooting for appsody bind failure scenario

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#1061]
**Codewind version:** 0.6.0
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description of the enhancement:**

We should document this scenario where appsody bind may fail:

1. An Appsody repository is added in Codewind via template manager
2. User tries to bind the project to a stack from that repository
3. Project is created in Codewind, but `appsody.log` has this error:
```
[Error] The current directory is not a valid appsody project. Run `appsody init <stack>` to create one. Run `appsody list` to see the available stacks.
```
4. And we get this error from `cwctl` in the Codewind log (VSCode):
```
2019/11/08 11:07:29 Please wait while the command runs... 
2019/11/08 11:07:31 [Error] Repository 77b94c9b-0daf-5426-98b8-83eb8ee63e3c is not in configured list of repositories
```

**Reason:**

The Appsody respository was already added in the user's local appsody CLI with a different name/ID

**Workaround:**

1. Remove the repository from local appsody CLI (i.e. run `appsody repo remove`)
2. Remove and add back the repository in Codewind via the template manager
3. Rebind the project to Codewind

**Comment by makandre** [comment]
FYA @sishida

**Comment by sishida** [comment]
@makandre Are we planning to eventually fix this issue, or is this issue something beyond our control?

If we plan to fix the issue, the Troubleshooting update will become obsolete, and I'd rather just leave this issue open instead of updating the Troubleshooting. :)

**Comment by makandre** [comment]
It's beyond our control because user could have added the repo in their local appsody CLI

**Comment by sishida** [comment]
@makandre OK, ID will plan to add it in. Thanks for the clarification!

**Comment by sishida** [comment]
@makandre I have created a PR for this issue: https://github.com/eclipse/codewind-docs/pull/220
Could you please review and let me know if you'd like any changes? Thanks!

**Comment by sishida** [comment]
@makandre I have merged the PR and am closing this issue. Thanks!
