### ISSUE TITLE
Kabanero repo in Codewind is outdated

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#1068]
**Codewind version:** 0.6.0
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**

The Kabanero repo that comes pre-configured in Codewind is old, it's `0.1.2` and they are up to `0.3.0` now

The way we hardcode it is also incorrect now due to Codewind's architectural change in `0.6.0`.  The repo needs to be added "programmatically" via Template Manager, so that the repo will propagate to the local and appsody extension's `appsody` CLIs

**Steps to reproduce:**

**Workaround:**

**Comment by tobespc** [comment]
The architecture change has not modified this area at all.  The question here is do we hardcode the default set of templates that we ship with or, have some clever install that will use the template manager to inject them at that time ?

**Comment by makandre** [comment]
So users enabling this may run into problem and not realize it's outdate.  For `0.6.0`, should we remove this from the pre-configured repos until we can do it properly?

@tobespc @deboer-tim

**Comment by deboer-tim** [comment]
Kabanero wasn't tagging a latest release when we started, but now they are. I've confirmed that we should switch to it, and doing so will mean that (like Appsody) we don't actually need a different URL every time they have a new release. Here's the correct URL to use:
https://github.com/kabanero-io/collections/releases/latest/download/kabanero-index.json

**Comment by tobespc** [comment]
we need to have the git redirect work complete first on this

**Comment by tobespc** [comment]
the redirect work is not going to complete in time for 0.6.0 so I have manually upgraded the collections version to be 0.2.1

**Comment by tobespc** [comment]
the redirect code is now in so closing as this is now resolved

**Comment by makandre** [comment]
@tobespc But we are not using the latest link it seems: https://github.com/eclipse/codewind/blob/master/src/pfe/portal/modules/Templates.js#L38

Also, we still have to address the other issue: if we hardcode the repo link here, that doesn't add the corresponding `index.yaml` url to the appsody CLI

**Comment by stalleyj** [comment]
@makandre I don't understand the issue you describe around the index.yaml and appsody CLI. Can this be raised as a separate issue to updating the repo link ?

**Comment by makandre** [comment]
@stalleyj I have opened #1645

**Comment by stalleyj** [comment]
https://github.com/eclipse/codewind/pull/1651

**Comment by tobespc** [comment]
I have retested and can verify its good
