### ISSUE TITLE
Fix Codewind.dev home page icons

### ISSUE THREAD

**Issue by maysunfaisal** [eclipse/codewind#1069]
**Description of the enhancement:**

Fix the icon labels

<img width="1655" alt="Screen Shot 2019-11-08 at 3 24 36 PM" src="https://user-images.githubusercontent.com/31771087/68508293-0564b200-023c-11ea-87a0-bfbcf8636284.png">
<img width="1673" alt="Screen Shot 2019-11-08 at 3 24 50 PM" src="https://user-images.githubusercontent.com/31771087/68508294-0564b200-023c-11ea-8221-d5c26074629f.png">
<img width="1675" alt="Screen Shot 2019-11-08 at 3 24 58 PM" src="https://user-images.githubusercontent.com/31771087/68508295-05fd4880-023c-11ea-8f2c-0b51ebb06bdf.png">
<img width="1667" alt="Screen Shot 2019-11-08 at 3 25 05 PM" src="https://user-images.githubusercontent.com/31771087/68508296-05fd4880-023c-11ea-98fc-f70bee511a29.png">

**Comment by maysunfaisal** [comment]
Should not be "twitter icon" "youtube icon" 😆

**Comment by sghung** [comment]
Kabanero-io uses alts like "Kabanero Twitter" or "Kabanero GitHub". Please use https://kabanero.io/ as an example and make the same changes for Codewind

**Comment by travis1111** [comment]
@sghung please assign to me :-)

**Comment by sghung** [comment]
Changes were made into 0.8.0, @maysunfaisal please verify or check the live site when 0.8.0 is released

**Comment by maysunfaisal** [comment]
https://www.eclipse.org/codewind/ still has the old labels

**Comment by stevencoc** [comment]
@travis1111 can you fix this on the 0.8.0 stream?

**Comment by sghung** [comment]
@travis1111 can you make this change for the 0.8.0 branch? Thank you

**Comment by malincoln** [comment]
> @travis1111 can you make this change for the 0.8.0 branch? Thank you

@travis1111 is this complete or still in progress?

**Comment by travis1111** [comment]
We are going to have a release this week, the new release contains the fix.  Maybe we just wait for the new release and Steven will publish?

**Comment by malincoln** [comment]
@travis1111 is the fix now ready to be verified?

**Comment by sghung** [comment]
Confirmed on behalf of Travis
