### ISSUE TITLE
Put back install remote

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind#1082]
PR https://github.com/eclipse/codewind-installer/pull/199 removed the ability for cwctl to install PFE into a kube cluster.

We need that function to be added back to cwctl.

**Comment by jopit** [comment]
Does PR https://github.com/eclipse/codewind-installer/pull/205 resolve this issue, or is there more work to do?

**Comment by tetchel** [comment]
the command is back now, but it tries to pull images that don't exist

```
 Normal   Pulling    17s (x2 over 33s)  kubelet, docker-desktop  Pulling image "eclipse/codewind-keycloak-amd64:latest"
  Warning  Failed     16s (x2 over 32s)  kubelet, docker-desktop  Failed to pull image "eclipse/codewind-keycloak-amd64:latest": rpc error: code = Unknown desc = Error response from daemon: pull access denied for eclipse/codewind-keycloak-amd64, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

I don’t see that image, is it supposed to be on dockerhub? I know it used to point to marko11/codewind-keycloak-amd64

**Comment by jopit** [comment]
Moving back to 'in progress' based on Tim's comment above

**Comment by tetchel** [comment]
https://github.com/eclipse/codewind-installer/commit/9995fd99eef4d7a27afeffb6218cc9ee5f03c85d#diff-1e2874a3b32881d0dcc9e311046cc0b2

**Comment by tetchel** [comment]
https://github.com/eclipse/codewind/issues/1158
