### ISSUE TITLE
[ODO] OpenShift projects get stuck on Starting state

### ISSUE THREAD

**Issue by GeekArthur** [eclipse/codewind#1083]
**Codewind version:** 0.6.0
**OS:** MacOS

**Che version:** 7.2.0
**IDE extension version:** 0.6.0
**IDE version:** 7.1.0
**Kubernetes cluster:** OKD 3.11.0

**Description:**

Currently OpenShift projects get stuck on Starting state when using ODO extension to build. We need to upgrade odo CLI to v1.0.1 and update `getPodName` function to fix this.

**Comment by GeekArthur** [comment]
Please assign this issue to me.

**Comment by malincoln** [comment]
@GeekArthur pls verify and close if resolved.  Thanks

**Comment by GeekArthur** [comment]
Verified, close this issue
