### ISSUE TITLE
Can't communicate with remote WebSocket

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind#1084]
This is likely related to issue #975 but any attempt by the IDEs to connect to the remote web socket is blocked by the Gatekeeper.  Do we need to wait until #975 is delivered before this works?  It's a major blocker for our hybrid work

**Comment by markcor11** [comment]
This should be solved now with #975 merged

/pipeline Verify

**Comment by tetchel** [comment]
Works for me

**Comment by malincoln** [comment]
@jopit pls confirm and close.  Thanks
