### ISSUE TITLE
Remove limitations.md from docs

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind#1087]
Remove the limitations page that doesn't appear on the website and no longer applies: https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/limitations.md

Received confirmation from @johnmcollier that the issues in this file no longer apply.

**Comment by micgibso** [comment]
@sishida I'll take this one please, thx!

**Comment by sishida** [comment]
PR is merged. Closing this issue.
