### ISSUE TITLE
SVT : Eclipse : language shown as unknown for Appsody Starter sample 

### ISSUE THREAD

**Issue by mmulholl** [eclipse/codewind#1093]
**Codewind version:**    Codewind Base	1.4.0.v201911081450	
**OS:** Mac/OS

**Che version:**
**IDE extension version:**
**IDE version:**Eclipse IDE for Enterprise Java Developers. Version: 2019-09 R (4.13.0), Build id: 20190917-1200
**Kubernetes cluster:**

**Description:**
After creating a Appsody Starter sample the language for the project is shown as "Unknown" in the overview page, was expecting to see bash. Same after import.

**Steps to reproduce:**

**Workaround:**

**Comment by makandre** [comment]
That actually probably "correct", since the `starter` stack is not a real working stack, but a template for people to use when creating new stacks.

A `starter` project only contains 1 placeholder `hello.sh` script, hence there's no language

**Comment by eharris369** [comment]
But the language listed in the template is bash.  Is that incorrect as well?

**Comment by makandre** [comment]
I'm guessing when appsody team generated the `index.json`, they just put `bash` based on the 1 bash script in it and because Codewind needed a language value.

I don't think `bash` is one of the language that `cwctl` detects, hence it shows as Unknown

**Comment by jgwest** [comment]
(Taking a guess on which `area`s to add, feel free to update)

**Comment by sghung** [comment]
Since this is assigned to Erin, I am moving back to new issues, so it can be added to the correct pipeline

**Comment by stalleyj** [comment]
@makandre Is there anything to do here ? I don't think we want to start identifying bash as a language so it seems like it's all working as expected.

**Comment by makandre** [comment]
I agree we should not identify bash as a language in `cwctl`

@eharris369 on IDE side however, if `cwctl` returns unknown language, can IDE just use the language value in the template in that case?

**Comment by eharris369** [comment]
The language is showing as Bash now in the overview page.  It is picking up the language from the project listing (we don't keep track of what template was used to create a project in the IDEs).

```
[
  {
    "projectID": "07aeed50-2e74-11ea-a573-91259047069a",
    "name": "appsodyStarter1",
    "codewindVersion": "latest",
    "language": "bash",
    "creationTime": 1578494346269,
```

![image](https://user-images.githubusercontent.com/9484320/71986855-2c6b4000-31fb-11ea-8c14-a5dba078ff91.png)

**Comment by malincoln** [comment]
@mmulholl pls verify and close. Thanks

**Comment by mmulholl** [comment]
Verified
