### ISSUE TITLE
Hybrid: could not bind an existing project

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#1095]
Trying to bind an existing go project fails.  Calls to the REST API from within Eclipse are working fine - it gets the environment, can refresh the project list, etc.

The connections list is:
```
 ./cwctl connections list
{"schemaversion":1,"connections":[{"id":"local","label":"Codewind local connection","url":"","auth":"","realm":"","clientid":""},{"id":"K2W5AOGU","label":"cwtest1112","url":"https://codewind-gatekeeper-k2w3pr3i-10.99.133.215.nip.io","auth":"https://codewind-keycloak-k2w3pr3i-10.99.133.215.nip.io","realm":"codewind","clientid":"codewind"}]}
```

And the bind call:
```
./cwctl --insecure project bind --name go1 --language go --type docker --path /Users/wdt/work/codewind/runtime-devtest1/go1 --conid K2W5AOGU
{"error":"proj_response","error_description":"unable to connect to Codewind server"}
```

**Comment by jcockbain96** [comment]
Mine's succeeding with the latest CLI, and the default local conid. 
```
go run cmd/cli/main.go --insecure project bind -p /Users/james.cockbain@ibm.com/Documents/work/codewind/codewind/codewind-workspace/go-james -n james-go-10 -l go -t docker --conid local

Project ID: ce8122a0-0619-11ea-9926-1377d6a09dc4
Status: 200 OK
```
I believe the error is happening in call to `/bind/start` on PFE, as that's the only place the error message is used. (https://github.com/eclipse/codewind-installer/blob/master/pkg/utils/project/bind.go#L106). 

@markcor11 has a PR up for review (https://github.com/eclipse/codewind-installer/pull/208) which updates the way we wrap the bind and sync PFE API's. This also enhances the logging, so should be clearer as to what is going wrong here. If this

**Comment by jopit** [comment]
To be clear, this is failing in the true hybrid scenario, not a local scenario.

**Comment by tetchel** [comment]
this works for me now since https://github.com/eclipse/codewind/issues/941 was fixed

**Comment by eharris369** [comment]
This is working for me now too.
