### ISSUE TITLE
Hybrid: no version in the result from the environment API

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#1096]
The IDE code checks the version of Codewind to make sure it is compatible but the output of api/v1/environment does not contain the version for the hybrid case:

{
  "running_in_k8s": true,
  "user_string": null,
  "socket_namespace": "/default",
  "workspace_location": "/projects",
  "os_platform": "Linux",
  "tekton_dashboard": {
    "status": false,
    "message": "not-installed",
    "url": ""
  }

**Comment by jopit** [comment]
Not currently blocking, but still required for 0.7.0

**Comment by tobespc** [comment]
Closing as a dupe of #578
