### ISSUE TITLE
SVT:Spring project failed to build and says "Maven build failed" but I can not access Maven build log

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#1098]
**Codewind version:** 0.6
**OS:** RHEL

**Che version:** 7.2
**IDE extension version:** 0.6
**IDE version:** Theia 7.1
**Kubernetes cluster:**
OKD cluster 3.11 

**Description:**
Spring project build failed and the message says "Maven build failed" but I can not access maven log for the build. 

```
Build Status:	Build Failed - Maven build failed
Last Image Build:	11/11/2019 at 3:30:15 PM
Last Build:	11/11/2019 at 3:30:48 PM
```

![image](https://user-images.githubusercontent.com/713849/68706015-1a538500-055d-11ea-8470-b2290660fd8c.png)

pfe log 
[pfe.txt](https://github.com/eclipse/codewind/files/3838335/pfe.txt)
[Theia-a.txt](https://github.com/eclipse/codewind/files/3838336/Theia-a.txt)
[Theia-b.txt](https://github.com/eclipse/codewind/files/3838337/Theia-b.txt)
[Theia-c.txt](https://github.com/eclipse/codewind/files/3838338/Theia-c.txt)
[Theia-d.txt](https://github.com/eclipse/codewind/files/3838339/Theia-d.txt)

**Steps to reproduce:**
1. Create multiple projects.
2. Create default spring project as well.
3. Spring project failed to build with Maven build failure.
4. Can not access maven log anymore.

**Workaround:**

**Comment by jagraj** [comment]
@tetchel 
When you get a chance, can you take a look at the Theia logs and I see bunch of errors.?

**Comment by tetchel** [comment]
I see loads of ` Error: Unknown actor TreeViewsMain` but that error is not being generated by my extension, I don't see any pertinent errors in the theia logs.

**Comment by maysunfaisal** [comment]
I would exec into the app container and go to the project dir; maybe it is `/root/app`? and check the maven logs there..

**Comment by ssh24** [comment]
I just tried it out with the latest 0.6.0 and it worked for me. Both the app started and I can see the logs. Anything particular in the PFE logs you noticed?

**Comment by jagraj** [comment]
I was creating bunch of projects one by one for each templates we support and I have seen similar issue with lagom project as well. I did manual build again after all builds completed and lagom project built successfully. Looks like there are timing issues when multiple builds submitted. Here is another issue we opened (https://github.com/eclipse/codewind/issues/1099) and we are not sure if this is same issue.

**Comment by rajivnathan** [comment]
I could not reproduce this. But I did reproduce #1099. I don't think they're related. #1099 appears to be related to the status reporting but this appears to be an actual failure with the build.

Looking at the pfe logs I see
```
[32m[11/11/19 15:30:47 springcw06svt] [INFO][39m Running kube command: kubectl exec,-i,cw-springcw06svt-d88a01b0-0496-11ea-b101-569b6565c5-mjn2w,--,sh,-c,ls --full-time /root/logs/ | tail -n +2
[91m[11/11/19 15:30:47 springcw06svt] [ERROR][39m executeBuildScript : 313 | command terminated with exit code 137
```

Exit code 137 for docker means out of memory so I don't think this is an issue with the build but rather a cluster resource issue.

**Comment by rajivnathan** [comment]
@jagraj Despit my best efforts I was unable to reproduce this. Are you able to reproduce this?

**Comment by jagraj** [comment]
This seems to be an issue in one of my OKD 3.11 cluster and it fails to build in this cluster intermittently. I am wondering this might be issue with resources but why this fails only with spring projects. I usually create project for each template.

**Comment by jagraj** [comment]
I can not reproduce this in my new 4.2 cluster. Closing this for now. Thanks for debugging this problem.I can not recover one of my glusterfs client in 3.11 cluster. If I see this problem again, I will reopen this. I can not reproduce this on my 4.2 cluster.
