### ISSUE TITLE
Codewind dockerhub images - move to https://hub.docker.com/r/eclipse

### ISSUE THREAD

**Issue by ericdylanpeters2** [eclipse/codewind#11]
We've some codewind docker images on dockerhub that should move to https://hub.docker.com/r/eclipse (e.g. https://hub.docker.com/r/ibmcom/codewind-pfe-amd64)

This will minimally require changes to the codewind installer.

**Comment by josephca** [comment]
Opened a bugzilla ticket : https://bugs.eclipse.org/bugs/show_bug.cgi?id=549354

**Comment by josephca** [comment]
codewind-che-plugin is now being published to Eclispe dockerhub : https://hub.docker.com/r/eclipse/codewind-che-sidecar/tags 

Issue: https://github.com/eclipse/codewind-che-plugin/issues/33

**Comment by josephca** [comment]
related issue: https://github.com/eclipse/codewind/issues/26
