### ISSUE TITLE
SVT: [Che] File watcher status 404 and Error loading remote connections

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#1100]
**Codewind version:** 0.6.0
**OS:** Red Hat Enterprise Linux 7 (64 bit)

**Che version:** 7.2.0
**Kubernetes cluster:** OKD/Openshift (Gluster FS)

**Description:** I was creating some projects in Eclipse Che and, suddenly, I received many errors: `File watcher status 404` and `Error loading remote connections`

![Screen Shot 2019-11-12 at 2 54 31 PM](https://user-images.githubusercontent.com/49531960/68714730-75da3e80-056e-11ea-948c-6a34a5ef0740.png)

![Screen Shot 2019-11-12 at 2 52 47 PM](https://user-images.githubusercontent.com/49531960/68714733-77a40200-056e-11ea-83e2-6b3cea392781.png)

**Log:**
[codewind-workspacepxf7uwuk1elupipa-5885467d48-q7n2h.txt](https://github.com/eclipse/codewind/files/3838427/codewind-workspacepxf7uwuk1elupipa-5885467d48-q7n2h.txt)

@jagraj

**Comment by tetchel** [comment]
the 404 errors are the same as https://github.com/eclipse/codewind/issues/1073, but for non-appsody projects too 

the `ETXTBSY` is a bug in my extension
