### ISSUE TITLE
Persist username in connections.json (CLI)

### ISSUE THREAD

**Issue by markcor11** [eclipse/codewind#1104]
**Codewind version:** latest

When creating a connection, the only information requested is a name (label) and the gatekeeper URL.  Followup commands such as bind / sync etc then require passing the username each time.   Since the CLI is already saving the password in the keychain, it would reduce the number flags on each command by persisting the username per connection too. The CLI will then be able to use the username and password (which it already knows) to automatically authenticate.

**Proposed solution:** 

* Store the username in connections.json during the connections add command
* Update the username in connections.json during the connections update command
* Return the username with connection get and connection list
* Remove username flags from PFE apis such as bind/sync (but not from the sec* or install remote commands)

**Comment by james-wallis** [comment]
I'll pick this up, @tobespc can you assign me.

**Comment by james-wallis** [comment]
As part of this issue I'm going to be changing `cwctl connection add` to take the `username` and `password` as flags (in addition to `conid` and `url`).
This is following a discussion with @markcor11 regarding the fact that `cwctl seckeyring update` must be called every time `cwctl connection add` is run.

I'll be leaving the `cwctl seckeyring update` command in the CLI but when adding a connection it won't need to be called anymore. 

When the `connection update` command is implemented it'll need to take `username` and `password` as optional parameters to update them. When a `username` is given the `password` must be accompanied and when just a `password` is given then the CLI should error.

**Comment by james-wallis** [comment]
Leaving the commands separate to remove the risk of circular dependencies.
The `--username` field will be kept for `seckeyring` which adds the credentials to the keyring and `sectoken` which uses the username and password to get the access token and refresh token.

**Comment by james-wallis** [comment]
PR raised for this: https://github.com/eclipse/codewind-installer/pull/223

**Comment by james-wallis** [comment]
I'll be completing the work to use the authentication wrappers once this PR is in https://github.com/eclipse/codewind/issues/1143

**Comment by james-wallis** [comment]
@markcor11 the PR has been accepted for this piece of work: https://github.com/eclipse/codewind-installer/pull/223 please close if you're happy.
