### ISSUE TITLE
Project-types API sometimes fails to include AppsodyExtension

### ISSUE THREAD

**Issue by james-wallis** [eclipse/codewind#1105]
**Codewind version:** Master
**OS:** MacOS

**Description:**
Project types API test is intermittently failing for unknown reasons and when it does it makes all the PR builds to fail.
I made attempts to find the issue but did not get anywhere.

**Steps to reproduce:**
Sorry, no idea. Couldn't reproduce locally.
Failing Jenkins log: https://ci.eclipse.org/codewind/job/Codewind/job/codewind/job/PR-1088/6/consoleText

**Current "fix"**
I've made a PR which removes the "appsodyExtension" check from the test. I'd like it to be put back but it as it stands when it fails it is holding up PR's from going in to Codewind even when they do not touch the templates/extensions.
PR: https://github.com/eclipse/codewind/pull/1103

**Comment by tetchel** [comment]
This is the expected behaviour if there are no template sources/repositories enabled which have Appsody style projects in them.

I think it is bad behaviour, though.

**Comment by makandre** [comment]
The recent failure may have something to do with us updating the version after branching off for `0.6.0`

But now the code will dynamically set the version based on the git branch, and hopefully that will mean less disruption going forward.

https://github.com/eclipse/codewind/pull/1090

**Comment by tobespc** [comment]
@james-wallis can resolve this one please and test if it is better based on the comments above

**Comment by james-wallis** [comment]
@makandre is this fix stable enough for the `AppsodyExtension` to be re-added to the test?

**Comment by makandre** [comment]
I think we can add it back

**Comment by james-wallis** [comment]
The PR I opened for adding the AppsodyExtension is still failing the test in Jenkins, locally it passes.
https://github.com/eclipse/codewind/pull/1174

**Comment by james-wallis** [comment]
Still failing: https://github.com/eclipse/codewind/pull/1644

**Comment by tobespc** [comment]
@james-wallis please retest and close/fix

**Comment by james-wallis** [comment]
https://github.com/eclipse/codewind/pull/2066

**Comment by james-wallis** [comment]
This is still failing, @hhellyer is making a change to the way that template repositories are working so I am going to keep this issue open and re-test once that change is in.

**Comment by james-wallis** [comment]
The cause of this bug was that the extension download was silently failing in Jenkins and so the extension was not in the PFE container for the tests (PR build only). 
PR: https://github.com/eclipse/codewind/pull/2133

**Comment by james-wallis** [comment]
Pr accepted into master: https://github.com/eclipse/codewind/commit/57838b61e9fcead6f6285376b4e8af98f89dcb1e
