### ISSUE TITLE
Product Overview content on Docs Landing Page

### ISSUE THREAD

**Issue by MelHopper** [eclipse/codewind#1106]
**Description of the enhancement:**
Content required for the Documentation Landing Page to enhance the Discovery Phase experience of the user. Further detail than the main codewind.dev landing page is required so that Codewind's main value propositions are put into context of a user's workflow.

**Proposed solution:** 
Create product overview and FAQ content for a new user learning about the product for the first time. Take into account different user stories and pain points found by UX testing.

This content will sit in the Table of Contents, but will also eventually be exposed explicitly on the Docs Landing Page when we have one.

**Comment by MelHopper** [comment]
Consider the following github issue content when creating the more verbose and user-story-orientated Product Overview content for the Docs Landing Page: 

"Improve [product overview] write-ups for Codewind marketplace entries"
https://github.com/eclipse/codewind/issues/596

**Comment by MelHopper** [comment]
Add info on additional codewind plugins in the next iteration of this work.

**Comment by MelHopper** [comment]
Changes commited via PR https://github.com/eclipse/codewind-docs/pull/287

**Comment by MelHopper** [comment]
Blocked by https://github.com/eclipse/codewind/issues/1744

**Comment by MelHopper** [comment]
Blocked by confirmation of proposed terminology for the 3 codewind configurations. @deboer-tim current proposal sent to you via Slack.

**Comment by micgibso** [comment]
Currently being drafted.
