### ISSUE TITLE
Hold weekly community playback and techtopic calls

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#1109]
As we continue to grow and evolve Eclipse Codewind, we need to be holding regular playback and techtopic calls in the open that the community can also participate in. In my opinion, our existing internal playback and tech-topic calls would be a good fit to hold in the open, as the vast majority of the content on these calls is related Codewind.

ToDo:
- [ ] Set up public call(s) to hold for Codewind playbacks and techtopics
- [ ] Ensure both Codewind members and the community can participate
- [ ] Communication:
   - On the day of the meeting(s), communicate on Mattermost and codewind-dev that the meeting is being held and when

**Questions:**
1) Should we have two separate calls, one playback and one techtopic? Or have a merged open playback/techtopic call
    - I'm in favour of keeping two separate calls. Frequently we run out of time on the playback and techtopic calls, so I don't think a condensed call would work

2) At what time should we hold the calls?
   - Currently they're held at 9am on Tues & Thurs, which I think is good, especially if folks in Europe want to participate

3) How should we host the calls?
   - Stick to the WebEx we use or look at Zoom / Bluejeans / etc?

4) Where to host the playback call agenda / notes?
   - We currently have a playback call agenda on IBM box, but this isn't publicly accessible. We either need to open it up or host it on Google docs or something else public (where community members can add their own agenda item)

**Comment by rtaniwa** [comment]
+1 to keeping separate calls, and keeping them where they are currently scheduled. Given most of our calls are WebEx, I would prefer to stay consistent unless there is a compelling reason to switch. Re: hosting notes and storing recordings, if we can't find a way to make it work with Box can we follow the lead of the Che team and use the GitHub wiki, or something similar?

**Comment by cccanderson** [comment]
WTP puts its agendas on wiki.eclipse.org, see https://wiki.eclipse.org/WTP_Development_Status_Meetings

WTP also has a Google calendar for its meeting schedules.

**Comment by jopit** [comment]
We'll keep separate calls
Same time as current
Use webex
Open up a section of Box to the public
For IBM only discussions, we could keep it on an ad-hoc basis.  If we need such a discussion frequently, we could schedule a meeting after the open one.

**Comment by johnmcollier** [comment]
After some further discussion:
- Will set up a scheduled Webex link and share it
- Can't use box for the meeting agenda, as it doesn't allow anonymous people to edit shared box notes
    - @tetchel suggested we could use git issues for the agenda (perhaps on a `codewind-resources/community` repo?
    - Will still use box to share the meeting recordings

**Comment by deboer-tim** [comment]
Tech topics: use google docs for agenda with shared link.

**Comment by johnmcollier** [comment]
Closing this out, both the playback and techtopics are being held publicly.
