### ISSUE TITLE
[odo] Create a new file for ODO extension related information for landing page

### ISSUE THREAD

**Issue by GeekArthur** [eclipse/codewind#1111]
We should create a new file for ODO extension related information for landing page, the section name on the landing page sidebar should be `OpenShift Do (odo) support in Codewind`, the contents should include:
- [x] OpenShift Do (odo) support in Codewind overview
- [x] Adding additional rules to support building OpenShift projects
- [x] Bind case
- [x] odo java component/builder setup (image stream configuration)
- [x] Update troubleshooting page

**Comment by GeekArthur** [comment]
Please assign this issue to me.

**Comment by micgibso** [comment]
@GeekArthur Is this for 0.7.0? Thanks

**Comment by GeekArthur** [comment]
@micgibso Yes, this is for 0.7.0, I am working on that and will finish soon.

**Comment by GeekArthur** [comment]
@micgibso Jonathan's bot doesn't support add `milestone`, I will be the committer soon, please help add `0.7.0` milestone, thanks.

**Comment by sishida** [comment]
Documentation needs:
- Separate odo documentation, including limitations and configuration.
- @GeekArthur will draft a PR, which the docs team can review.

**Comment by sishida** [comment]
Hi, @GeekArthur, It looks like the PR is merged, and this issue is good to close. :) If so, could you please close it? Thank you!

**Comment by GeekArthur** [comment]
Verified, close the issue.
