### ISSUE TITLE
Unable to create Appsody loopback project

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#1119]
Trying to create an Appsody loopback project on the latest master branch of vscode gives me the following error

Running development environment...
[Error] The current directory is not a valid appsody project. Run `appsody init <stack>` to create one. Run `appsody list` to see the available stacks.

**Comment by makandre** [comment]
Are you using the loopback stack from the Appsody repo or the Kabanero repo?

In the project, is there a `.appsody-config.yaml` file?  What's inside?

**Comment by tobespc** [comment]
changing to use 'https://github.com/kabanero-io/collections/releases/download/0.3.0-rc.3/kabanero-index.json fixes loopback

**Comment by makandre** [comment]
So this can be closed?
