### ISSUE TITLE
Unable to create Appsody Liberty project

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#1121]
I get the following error trying to create an Appsody Liberty project in vscode using the latest master branches

Pulling docker image kabanero/java-microprofile:0.2
Running command: docker pull kabanero/java-microprofile:0.2
0.2: Pulling from kabanero/java-microprofile
Digest: sha256:cb6928768d89d77e9dcf85fb798c7830700ddded3d18ec9a5d0932573d903d13
Status: Image is up to date for kabanero/java-microprofile:0.2
[Warning] Could not mount /root/.m2/repository:/mvn/repository because the local file was not found.
Running docker command: docker run --rm -P --name cw-appsodylib-7fefde70-06c2-11ea-8d00-7730a0d5a86e --network codewind_network -v /Users/tobes/codewind-data/appsodyLib/src:/project/user-app/src -v /Users/tobes/codewind-data/appsodyLib/pom.xml:/project/user-app/pom.xml -v /Users/tobes/codewind-data/.extensions/codewind-appsody-extension/bin/appsody-controller:/appsody/appsody-controller -t --entrypoint /appsody/appsody-controller kabanero/java-microprofile:0.2 --mode=run
[Container] Running APPSODY_PREP command: ../validate.sh && mvn -B -Dmaven.repo.local=/mvn/repository install -DskipTests && /project/install-dev-deps.sh
[Container] Installing parent dev.appsody:java-microprofile:0.2.17
[Container] [[1;34mINFO[m] Scanning for projects...
[Container] [[1;34mINFO[m] 
[Container] [[1;34mINFO[m] [1m-------------------< [0;36mdev.appsody:java-microprofile[0;1m >--------------------[m
[Container] [[1;34mINFO[m] [1mBuilding java-microprofile 0.2.17[m
[Container] [[1;34mINFO[m] [1m--------------------------------[ pom ]---------------------------------[m
[Container] [[1;34mINFO[m] 
[Container] [[1;34mINFO[m] [1m--- [0;32mmaven-enforcer-plugin:3.0.0-M2:enforce[m [1m(enforce-versions)[m @ [36mjava-microprofile[0;1m ---[m
[Container] [[1;34mINFO[m] Skipping Rule Enforcement.
[Container] [[1;34mINFO[m] 
[Container] [[1;34mINFO[m] [1m--- [0;32mmaven-install-plugin:2.4:install[m [1m(default-install)[m @ [36mjava-microprofile[0;1m ---[m
[Container] [[1;34mINFO[m] Installing /project/user-app/../pom.xml to /mvn/repository/dev/appsody/java-microprofile/0.2.17/java-microprofile-0.2.17.pom
[Container] [[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[Container] [[1;34mINFO[m] [1;32mBUILD SUCCESS[m
[Container] [[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[Container] [[1;34mINFO[m] Total time:  1.191 s
[Container] [[1;34mINFO[m] Finished at: 2019-11-14T09:39:09Z
[Container] [[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[Container] [INFO] Scanning for projects...
[Container] [INFO] Downloading from central: https://repo.maven.apache.org/maven2/dev/appsody/java-microprofile/0.2.11/java-microprofile-0.2.11.pom
[Container] [ERROR] [ERROR] Some problems were encountered while processing the POMs:
[Container] [FATAL] Non-resolvable parent POM for dev.appsody.starter.java-microprofile:starter-app:1.0-SNAPSHOT: Could not find artifact dev.appsody:java-microprofile:pom:0.2.11 in central (https://repo.maven.apache.org/maven2) and 'parent.relativePath' points at wrong local POM @ line 8, column 13
[Container]  @ 
[Container] [ERROR] The build could not read 1 project -> [Help 1]
[Container] [ERROR]   
[Container] [ERROR]   The project dev.appsody.starter.java-microprofile:starter-app:1.0-SNAPSHOT (/project/user-app/pom.xml) has 1 error
[Container] [ERROR]     Non-resolvable parent POM for dev.appsody.starter.java-microprofile:starter-app:1.0-SNAPSHOT: Could not find artifact dev.appsody:java-microprofile:pom:0.2.11 in central (https://repo.maven.apache.org/maven2) and 'parent.relativePath' points at wrong local POM @ line 8, column 13 -> [Help 2]
[Container] [ERROR] 
[Container] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[Container] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
[Container] [ERROR] 
[Container] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[Container] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[Container] [ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
[Container] [Error] FATAL error APPSODY_PREP command received an error.  The controller is exiting: exit status 1
[Error] Error in 'appsody run': exit status 1

**Comment by makandre** [comment]
@tobespc Are you using the pre-configured kabanero repo?  That's outdated, see https://github.com/eclipse/codewind/issues/1068 (and there's a question in there for you)

**Comment by makandre** [comment]
Can close this @tobespc ?

**Comment by sghung** [comment]
Closing on behalf of Toby, since this is old, has no additional activity by Toby, and has not come up during 0.7.0 SVT.
