### ISSUE TITLE
Document "Codewind" output stream for troubleshooting

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#1126]
In 0.6 we now have the "Codewind" output stream in VS Code which logs cwctl commands and their output. This should help users debug unusual problems, especially when starting codewind (https://github.com/eclipse/codewind/issues/411). 

We should point users to opening this Output stream as a place to look when troubleshooting. Some errors will also give the user a button to open this Output stream.

We should document this in the VS Code Troubleshooting page. It _may_ be worth mentioning in the news, too.

**Comment by tetchel** [comment]
![image](https://user-images.githubusercontent.com/8888438/68875079-39265880-06d0-11ea-8a83-0d83cfe749bd.png)

![image](https://user-images.githubusercontent.com/8888438/68875086-3b88b280-06d0-11ea-802e-5b2e126de2ad.png)

**Comment by micgibso** [comment]
@tetchel Please assign me and I'll take a look

**Comment by micgibso** [comment]
Documented, approved, and merged. @tetchel @sishida this can now be closed. thanks.
