### ISSUE TITLE
Create a feature in a minute video for Appsody + Che

### ISSUE THREAD

**Issue by sghung** [eclipse/codewind#1128]
Create a feature in a minute video for appsody on che. Andrew can reach out to Becca to have the video created.

Adding the docs tag because the content needs ID review.

**Comment by beccabau** [comment]
I'm happy to work on this FIUM. @makandre, just let me know who I need to work with from the Appsody squad  to get this done :).

**Comment by makandre** [comment]
@beccabau I can work with you on this

**Comment by beccabau** [comment]
can pull content from: https://www.youtube.com/watch?v=yMynpzZF6V8

**Comment by sishida** [comment]
This issue is no longer a priority. @micgibso and I agree to close it.
