### ISSUE TITLE
[ODO] App log doesn't work for OpenShift projects

### ISSUE THREAD

**Issue by GeekArthur** [eclipse/codewind#1130]
**Codewind version:** 0.6.0
**OS:** MacOS

**Che version:** 7.3.1
**IDE extension version:** 0.6.0
**IDE version:** 7.3.1
**Kubernetes cluster:** OKD

**Description:**
The app log doesn't work for OpenShift projects, issue is due to container log tailing is failed.

**Comment by jgwest** [comment]
@GeekArthur FWIW you can put commands together in the same comment, or even put them in the body!

**Comment by GeekArthur** [comment]
@jgwest Thanks Jonathan, I was thinking about the same thing then verified `put commands together` works perfect on my next issue: https://github.com/eclipse/codewind/issues/1131

**Comment by elsony** [comment]
Code merged. moving to verify

**Comment by GeekArthur** [comment]
Verified, app log works.
