### ISSUE TITLE
Project folder in PFE not world writable

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#1133]
**Codewind version:** 0.6.0
**OS:**

**Che version:** 7.3.1
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:** OCP 4.2

**Description:**

This would address issue https://github.com/kabanero-io/kabanero-foundation/issues/129, where the Kabanero springboot stack is failing to run in Codewind on Che.  We narrowed it down to a permissions problem:

- kabanero stacks run as non-root (they run as `java_user`)
- when project is created in PFE, it is owned by root and has 775 permissions (user/group write only)
- when the project dir is mounted to the app container (as `/project/user-app`), that folder has the same ownership and permissions as in PFE
- therefore, `java_user` cannot write to `/project/user-app`

Tested that if the project dir is made world writable in PFE, then the project can run

**Steps to reproduce:**

**Workaround:**

**Comment by johnmcollier** [comment]
Marking as stopship since the corresponding Kabanero issue is a stopship.

**Comment by maysunfaisal** [comment]
We solved this for Liberty by changing the owners of the created Liberty project during project build. Like here for example, where liberty applications were running as user `1001`. This worked out because it didnt create any issues on the Theia container. https://github.com/eclipse/codewind/blob/master/src/pfe/file-watcher/scripts/liberty-container.sh#L138

Perhaps the same can be done for Appsody but you need to check if `java_user` uid is a different user in the Theia container

**Comment by makandre** [comment]
I think in appsody case however, we have no control over what user stacks will choose to run as, and Codewind has no straightforward way to predetermine what that user will be.  So we may have no choice but to be make it world writable

**Comment by BarDweller** [comment]
Note that the intent for the Kabanero Spring Stack isn't for it to run as `java_user`, but to run with the uid/gid of the appsody user. (as required by the `ENV APPSODY_USER_RUN_AS_LOCAL=true` flag set on the stack.) Thus when the stack writes files (say .class files created during compilation), the appsody user will still be able to access & delete them locally. (similarly for dependencies added to the shared m2 cache folder, they will be correctly owned by the appsody user).

You can see this if you test by exec'ing into a running stack.. If I use `appsody run` to run a project based on the kabanero spring stack I see the following docker command...
```
Running docker command: docker run --rm -p 5005:5005 -p 8080:8080 -p 8443:8443 -p 35729:35729 --name ktest-dev -u 1001:1001 -e APPSODY_USER=1001 -e APPSODY_GROUP=1001 -v /home/myuser/Appsody/new-local-build/kabtest/test/ktest/.:/project/user-app -v /home/myuser/.m2/repository:/mvn/repository -v /home/myuser/.appsody/appsody-controller:/appsody/appsody-controller -t --entrypoint /appsody/appsody-controller kabanero/java-spring-boot2:0.3 --mode=run
```

When I exec into the running container, I see `/project` is owned by java_user, and `/project/user-app` is owned by id 1001:1001 (aka 'myuser` on my system, but the userid has no name inside the container). Similarly, the `/mvn/repository` dir is owned by 1001:1001 

The `id` command tells me I'm running as user/group 1001/1001 (which corresponds to my local uid/gid for `myuser`)

Not this is *not* java_user, who has the uid/gid 1000/1000

**Comment by tobespc** [comment]
@james-wallis could you take a look please

**Comment by makandre** [comment]
I have a pr up for this

**Comment by tobespc** [comment]
reviewed and merged

**Comment by makandre** [comment]
Was able to verify this using latest 0.6.0 image on OCP4.2 cluster: Kabanero springboot project built and ran.
