### ISSUE TITLE
Project Types Obstructs the "Template Sources" View

### ISSUE THREAD

**Issue by naveenkaratekid** [eclipse/codewind#1137]
**Codewind version:**0.6.0
**OS: **OKD 3.1
**Che version:**7.3.1

**Description of the enhancement:**
When you create a project, and you click the icon where you open the "Template Sources" tab, the menu for the list of available templates under the menu title ```[Local Codewind] Create a New Project (1/2)``` to create projects with it doesn't disappear. I have to click on a template to make the menu go away so I can then see the Template sources view.

<img width="1502" alt="Screen Shot 2019-11-14 at 4 13 43 PM" src="https://user-images.githubusercontent.com/19738071/68896631-e06bb580-06f9-11ea-9633-7d7754bcaef4.png">

**Comment by tetchel** [comment]
this is by design, you can close the dropdown with the escape key

**Comment by naveenkaratekid** [comment]
For some reason, pressing the Escape key on my machine doesn't close the dropdown.

**Comment by naveenkaratekid** [comment]
Somehow it fixed itself...
