### ISSUE TITLE
[SVT][Che] Error message flickering under certain circumstances when naming new project

### ISSUE THREAD

**Issue by DavidG1011** [eclipse/codewind#1138]
**Codewind version:** 0.6.0 
**Che version:** 7.3.1
**Kubernetes cluster:** OCP 4.2/OKD 3.11

**Description:** Not sure if a user would ever hit this bug, but: If you press Space and Backspace at the same time when naming a new project, you can cause the string below the project name input field to rapidly switch between "Enter a name..." and "Invalid project name".

**Steps to reproduce:**
1. Click create new project.
2. Select a project language.
3. Enter a ~10 character project name.
4. Press Space and Backspace simultaneously a few times.

**Workaround:** 

Don't press Space and Backspace at the same time.

FYI: @jagraj

**Comment by tetchel** [comment]
that makes sense to me, you can't put a space in project names

**Comment by DavidG1011** [comment]
The main issue is that the string will continue to switch even when you stopped pushing any keys. Seems as if it just continues entering keystrokes on its own.

**Comment by tetchel** [comment]
does it do that forever, or does it do it as many times as it takes to process all the keystrokes you sent it when holding the keys down?

**Comment by DavidG1011** [comment]
Seems to just do it forever until you exit out of the menu.

**Comment by tetchel** [comment]
I'm still not convinced this is a valid bug, you can always "do" the workaround...

**Comment by DavidG1011** [comment]
True. I just figured I would bring it up in case it was a symptom of something else that's more likely to effect users.
