### ISSUE TITLE
Update CLI to use authentication wrappers for PFE api calls

### ISSUE THREAD

**Issue by markcor11** [eclipse/codewind#1143]
**Codewind version:** latest

**Description of the enhancement:**
For true hybrid calls the CLI makes to PFE apis need to be authenticated.  This has been done for Project bind and sync only.

**Proposed solution:** 
Update CLI and activate security on other PFE remote API requests.

**Comment by markcor11** [comment]
Functions which will need updating : 

- [ ] GetExtensions
- [ ] GetTemplates
- [ ] GetTemplateStyles
- [ ] GetTemplateRepos
- [ ] AddTemplateRepo
- [ ] DeleteTemplateRepo
- [ ] BatchPatchTemplateRepos

**Comment by james-wallis** [comment]
Project-types too

**Comment by james-wallis** [comment]
Keeping track here:

### Summary
* Changed API routes to talk to PFE using @markcor11's HTTPS request wrapper for remote deployments.
- [x] GetTemplates
  * Tested using `cwctl --insecure templates ls --conid K34MCHAO` worked as expected.
- [ ] GetTemplateStyles
- [ ] GetTemplateRepos
- [ ] AddTemplateRepo
- [ ] DeleteTemplateRepo
- [ ] BatchPatchTemplateRepos
- [ ] GetExtensions
- [ ] ProjectTypes

### Testing
Manual tests completed as detailed above.

**Comment by james-wallis** [comment]
All that is left for this item is further testing and to double check that no other functions call the PFE API without being wrapped in the `sechttp` call.

**Comment by markcor11** [comment]
Verified
