### ISSUE TITLE
Containers built from Node.js template have a copy of the project at /app/{project_name}

### ISSUE THREAD

**Issue by jcockbain96** [eclipse/codewind#1144]
**Codewind version:** 0.6.0
**OS:** Mac

**IDE extension version:** vscode 0.6.0

**Description:**

When creating from the default `node.js express` template, files are being copied to both `/app` and `/app/{project_name}`. 

PFE does its `docker cp` to `/app` 9https://github.com/eclipse/codewind/blob/master/src/pfe/portal/routes/projects/remoteBind.route.js#L249), so it seems to me like when turbine are building and running the container, the project is also written to `/app/{project_name}`(
https://github.com/eclipse/codewind/blob/master/src/pfe/portal/routes/projects/remoteBind.route.js#L368).

I've tested this on all of the standard projectTypes and only see the issue for projects created from this templates. 

**Steps to reproduce:**

Create a Node.js project, using the default Codewind node.js express template (e.g this one called nodd). Once built, exec into the cw-nodd container. The following directory structure exists: 

```
root@f486cbd4284b:/app# ls
Dockerfile        chart   node_modules       package.json  test
Dockerfile-tools  images  nodemon.json       public
README.md         nodd    package-lock.json  server
root@f486cbd4284b:/app# ls nodd
Dockerfile        README.md  images        package-lock.json  public  test
Dockerfile-tools  chart      nodemon.json  package.json       server
```

If the `nodd` dir inside `/app` is deleted and the project rebuilt, the directory is recreated.

**Comment by ssh24** [comment]
Turbine copies the files to `/app` only on create here https://github.com/eclipse/codewind/blob/ed9494b0ba76c80fbca8909112cb77912f9922bf/src/pfe/file-watcher/scripts/nodejs-container.sh#L279. Is it portal that it is copying it under `/app/{project_name}` for updates? If so, it should be a portal bug then.

**Comment by rajivnathan** [comment]
Sounds like this is related to the usage of the docker cp command as we've seen in another issue (https://github.com/eclipse/codewind/issues/1112).

Would changing that line to
`docker cp "$WORKSPACE/$projectName/." $project:/app` resolve the problem?

See https://docs.docker.com/engine/reference/commandline/cp/#parent-command

**Comment by jcockbain96** [comment]
I can test now, that is what I was about to say too

**Comment by ssh24** [comment]
Ah, that makes sense. Let me try it out and confirm

**Comment by jcockbain96** [comment]
Fixes it for me

**Comment by ssh24** [comment]
Yes, please. Thank you

**Comment by elsony** [comment]
Changing this to portal since the fix looks like to be on the portal layer.

**Comment by ssh24** [comment]
The fix was actually on iterative-dev side but was fixed by James from portal.
