### ISSUE TITLE
[SVT] Codewind Che (on OKD) does not automatically refresh when all the pods are running

### ISSUE THREAD

**Issue by beccabau** [eclipse/codewind#116]
**Codewind version:** latest (dev)
https://raw.githubusercontent.com/eclipse/codewind-che-plugin/master/devfiles/latest/devfile.yaml
**OS:** OKD

**Che version:** 4ef1d89
**IDE extension version:** 
**IDE version:** Eclipse Che
**Kubernetes cluster:** OKD

![image](https://user-images.githubusercontent.com/13971834/62570096-55a72f00-b85d-11e9-959a-ad342e943038.png)

**Description of the bug:**
(Not sure if this is as designed) In the initial page where the che workspace comes up, the codewind explorer does not refresh when all the pods are in running state, so it looks like you still can't create projects or anything. 
![image](https://user-images.githubusercontent.com/13971834/62571523-91db8f00-b85f-11e9-9a14-64226945fd62.png)

```
[root@okd-rbau-master codewind-che-plugin]# k get pod
NAME                                                              READY     STATUS    RESTARTS   AGE
che-2-8wlhf                                                       1/1       Running   0          4h
codewind-performance-workspacex02beyouod2nmkan-5c7b4d6588-fc7k2   1/1       Running   0          7m
codewind-workspacex02beyouod2nmkan-64664566bb-x4gtq               1/1       Running   0          7m
tiller-deploy-59cc8cfcf4-wpszv                                    1/1       Running   0          7m
workspacex02beyouod2nmkan.che-workspace-pod-78654ff9f5-g4xqk      3/3       Running   0          7m
[root@okd-rbau-master codewind-che-plugin]# 
```
As shown here, the pods have been running for at least a few minutes already.

**Workaround:** 
 I had to refresh the che workspace in order to get to the codewind explorer. 
![image](https://user-images.githubusercontent.com/13971834/62571591-bdf71000-b85f-11e9-869b-0213521721e8.png)
If this is as designed, I would like to raise an enhancement issue where the codewind-che plugin will refresh when the pods are in running state. (If possible).

Thanks!

**Comment by johnmcollier** [comment]
Seeing this too on Che regularly

**Comment by tetchel** [comment]
I'm quite certain this is a theia bug but I will see if there is anything I can do.

**Comment by tetchel** [comment]
dupe https://github.com/eclipse/codewind/issues/67
