### ISSUE TITLE
[Doc] update Codewind on Che and Codewind Docker registry doc 

### ISSUE THREAD

**Issue by tam512** [eclipse/codewind#1163]
**Codewind version:** 0.6.0
**OS:**
**Che version:** 7.3.1
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:** OCP 4.2

**Description:**
Update `Installing Codewind on Eclipse Che` doc https://www.eclipse.org/codewind/installoncloud.html with the following:
- Include OpenShift 4.x in step `3. Install Che:`
- Under `Creating the Codewind workspace with a Devfile` section, update link https://raw.githubusercontent.com/eclipse/codewind-che-plugin/master/devfiles/0.4/devfile.yaml to `https://raw.githubusercontent.com/eclipse/codewind-che-plugin/0.6.0/devfiles/0.6.0/devfile.yaml` or point user to get the latest version
- Remove `Checking for the Codewind pod` section
- Add a section on how to uninstall Che 
- Add a section on how to update Che version
- Add a section on how to configure `source control` such as Gtihub in Che workspace so we can check in project code after creating/developing from the workspace

Update `Codewind Docker registry guidance` https://www.eclipse.org/codewind/dockerregistry.html to 
- update OpenShift Registry section to have the 3.x and 4.x version.  For 4.x, the registry is
  `image-registry.openshift-image-registry.svc:5000/<project>`

**Steps to reproduce:**

**Workaround:**

**Comment by micgibso** [comment]
@tam512 fyi, https://www.eclipse.org/codewind/installoncloud.html no longer exists and has been superseded by https://www.eclipse.org/codewind/mdt-che-overview.html and https://www.eclipse.org/codewind/mdt-che-installinfo.html. Looking through the new install topic, enhanced for 0.6.0, the above changes are still required.
