### ISSUE TITLE
Update template names and descriptions

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind#117]
**This issue was originally opened by @tetchel in an archived repo. I am opening it again in this repo because it's still relevant.**

The templates could benefit from more useful names and updated descriptions so that they can be helpful and consistent with one another.

Info is pulled from https://github.com/microclimate-dev2ops/codewind-templates
and stored in a meta.yaml per-template https://github.com/microclimate-dev2ops/codewind-templates/blob/master/devfiles/pythonTemplate/meta.yaml,
which is then aggregated into https://github.com/microclimate-dev2ops/codewind-templates/blob/master/index.json.

- The descriptions should not use the world "template" or "for building". The Python description could be used as an example.
- "Java Microprofile Template" should probably have "Java" removed from the name because Spring is also Java.
- The Swift template should also have "microcservice" removed for consistency with the others. (It's also typo https://github.com/microclimate-dev2ops/codewind-templates/issues/4.)
- We should add tags.

**Comment by tobespc** [comment]
being resolved as part of the work for #727
