### ISSUE TITLE
SVT : Eclipse : Slow/delayed updates for projects, especially appsody

### ISSUE THREAD

**Issue by mmulholl** [eclipse/codewind#1179]
**Codewind version:**  Codewind tech preview	0.6.0.v201911181652	
**OS:** MAC/OS

**Che version:**
**IDE extension version:**
**IDE version:**Eclipse IDE for Enterprise Java Developers. Version: 2019-09 R (4.13.0) Build id: 20190917-1200
**Kubernetes cluster:**

**Description:**
Appsody projects can be slow to appear after creation and even slower to disappear after removal. In test runs I have had to increase the timeout when waiting for newly created project to appear in codewind , and I am also seeing failures in project removal because a project may only disappear after the next project is created or not at all. Most typical offenders are Appsody Kitura and Appsody Starter. The exact same test runs fine with the basic project types. 

**Steps to reproduce:**

**Workaround:**

**Comment by jagraj** [comment]
I also tried this manually on local where it takes lot of time to appear in the project list, If we create another project or refresh screen then we will see project in the list. We do not see same behavior on Eclipse Che.

**Comment by sghung** [comment]
Laven and myself are taking a look at this one.

**Comment by sujeilyfonseca** [comment]
**Codewind version:** codewind-0.6.0-201911151544.vsix
**OS:** VM with Windows 10

**IDE extension version:** 0.6.0
**IDE version:** 1.40.1

I have seen this problem as well in my Windows VM with Codewind for VS Code.

**Comment by mmulholl** [comment]
Now seeing this a lot with basic project types too. Projects do disappear after a refresh.

**Comment by GeekArthur** [comment]
I can try to reproduce to see if I can find the issue on non-Appsody projects

**Comment by elsony** [comment]
We can take a look at when the notification has been sent out to decide if the delay is coming from PFE layer or on the IDE side (or the communication channel).

**Comment by tetchel** [comment]
the `Creating <projectname>...` notification should last longer in vs code/theia now. the delay between that progress going away and the project appearing in the codewind view should be very short.

**Comment by GeekArthur** [comment]
In order to test PFE layer and non-Appsody projects, I try to create multiple non-Appsody projects using VS Code since PFE layer is not IDE specific, I am using MacOS. Create and delete non-Appsody projects appear and disappear in the project list very fast ~ 1 sec.

**Comment by GeekArthur** [comment]
For folks can reproduce this issue, suggest turn on the TRACE log level for PFE then post PFE log here, then I can take a look if the delay is from notification sent by PFE layer or communication channel.

**Comment by elsony** [comment]
@mmulholl ^^ It looks like Jingfu can't reproduce the problem on Codewind style application on his machine. Can you provide the PFE log and also the details on your test, e.g. detailed steps, platform, Eclipse/VSCode, etc.?

**Comment by GeekArthur** [comment]
I tested the non-Appsody projects for Eclipse as well, I don't hit the slowness issue but the IDE extension that I use is below, the version is newer than the description in this issue.
![Screen Shot 2019-11-20 at 3 58 29 PM](https://user-images.githubusercontent.com/15131537/69278408-4780e280-0bb0-11ea-877c-937f89dd7bda.png)

**Comment by mmulholl** [comment]
Still seeing the issue on   Codewind tech preview	0.6.0.v201911181940	

Often the remove project stays listed until the view is refreshed or a new project is created -presumably causes a refresh. It really kills automated tests.

Steps are 1. create a project, wait for it to finish building and starting. 2. remove the project.

**Comment by GeekArthur** [comment]
I share a video to my personal box note: https://ibm.box.com/s/jdt6363rhcmj53parer4uq48st7bxf83
Anyone can download and view it, there is no delay issue for deleting non-Appsody project for me.

Also in the mean time I check the PFE log:
```
[20/11/19 22:00:58 User.js] [INFO] Removing project directory at /codewind-workspace/python
[20/11/19 22:01:05 nodejs] [INFO] operationId: 5f20ec1fcdbe5cf9b9cab1f970bf0523
[20/11/19 22:01:05 nodejs] [INFO] containerDelete: Kill running processes and remove container... 
[20/11/19 22:01:05 nodejs] [INFO] Project ID:        ff517610-0be0-11ea-adba-0188e0b71eaa
[20/11/19 22:01:05 nodejs] [INFO] Project Location:  /codewind-workspace/nodejs
[20/11/19 22:01:05 nodejs] [INFO] Project Type:      nodejs
[20/11/19 22:01:05 nodejs] [INFO] Project Container: cw-nodejs-ff517610-0be0-11ea-adba-0188e0b71eaa
[20/11/19 22:01:05 nodejs] [INFO] projectInfo.deploymentRegistry: undefined
[20/11/19 22:01:07 nodejs] [INFO] Project info cache is {}
[20/11/19 22:01:07 nodejs] [INFO] Successfully deleted ff517610-0be0-11ea-adba-0188e0b71eaa
[20/11/19 22:01:07 Turbine] [INFO] Removing project logs directory
[20/11/19 22:01:07 Turbine] [INFO] Log directory removed from: /codewind-workspace/.logs/nodejs-ff517610-0be0-11ea-adba-0188e0b71eaa
[20/11/19 22:01:07 Turbine] [INFO] ff517610-0be0-11ea-adba-0188e0b71eaa: Emitting event 
 message: projectDeletion
 data: {
  "operationId": "5f20ec1fcdbe5cf9b9cab1f970bf0523",
  "projectID": "ff517610-0be0-11ea-adba-0188e0b71eaa",
  "status": "success"
}
[20/11/19 22:01:07 User.js] [INFO] Removing project directory at /codewind-workspace/nodejs
```
I can confirm there is no delay from PFE layer, project delete notification has been sent immediately. From Martin's description, seems like refresh can resolve the issue, given that and my PFE log, I think the delay issue is not from PFE layer since refresh can't help boost the notification sending/receiving and improve the communication. May need to let IDE folks to double check if the project list doesn't display properly when corresponding actions have been trigger.

My environment:
OS: MacOS
IDE: Eclipse
IDE extension: Eclipse for Codewind 0.6.0.v201911181940
FYI @elsony

**Comment by eharris369** [comment]
I tried this on my machine and here are the results.  The project appears on the first project status change event even though the create event comes much later (I have raised this as an issue in the past).  The project goes away instantly when the delete event is received.

Create requested: 1574352083334
Bind requested: 1574352089345
Got project status change event: 1574352089657
Got project status change event: 1574352089742
Got project status change event: 1574352089814
Got project status change event: 1574352090816
Got project status change event: 1574352094692
Got project status change event: 1574352112698
Got project create event: 1574352120927
Request remove: 1574352178403
Got project delete event: 1574352183836

**Comment by makandre** [comment]
When we say "slow to appear", I'm guessing we're talking about the project creation process as a whole, i.e. from the moment you click `Finish` to the moment the project appears in the explorer, is that right?

My first creation of an appsody Kitura project was indeed slow (tho there's progress indication).  The reason for that is the Kitura stack image is 1.5 GB!  So, during the init it has to pull that image down for the first time.  All my subsequent Kitura projects were much faster.

I haven't noticed any delays when removing appsody projects however, it does take a sec or 2 (tho there's no progress indication)

**Comment by mmulholl** [comment]
I am still seeing the odd remove issue when running my test. Problem is I don't have any code right now to capture the logs when it happens.

**Comment by jopit** [comment]
In both vscode and eclipse, I created an appsody kitura project, and I see the same behaviour.

If the appsody/kitura docker image hasn't already been pulled, it takes approx 40 seconds before the project shows up in the view.  Looking at the vscode log file, I see that the call to `cwctl project create` took about 40 seconds, and we don't get any notifications on the socket.  We then call `cwctl project bind`, at which point we receive a socket notification and the project appears.
```
[INFO: 11:24:09.808 CLIWrapper.js:103]: Running CLI command: cwctl --json --insecure project create /Users/jsp/Develop/eclipse/codewind/kitura --url https://github.com/appsody/stacks/releases/download/kitura-v0.2.2/incubator.kitura.v0.2.2.templates.default.tar.gz
[DBUG: 11:24:48.110 CLIWrapper.js:160]: Successfully ran CLI command cwctl --json --insecure project create /Users/jsp/Develop/eclipse/codewind/kitura --url https://github.com/appsody/stacks/releases/download/kitura-v0.2.2/incubator.kitura.v0.2.2.templates.default.tar.gz, Output was:
{"status":"success","projectPath":"/Users/jsp/Develop/eclipse/codewind/kitura","result":{"language":"swift","projectType":"appsodyExtension"}}
[INFO: 11:24:48.111 CLIWrapper.js:103]: Running CLI command: cwctl --json --insecure project bind --conid local --name kitura --language swift --type appsodyExtension --path /Users/jsp/Develop/eclipse/codewind/kitura
[WARN: 11:24:48.307 MCSocket.js:163]: Received socket event for nonexistent project
6f9fb630-0c7b-11ea-b5fa-0779966da779
[DBUG: 11:24:48.349 Connection.js:230]: Updating projects list from http://127.0.0.1:10000/ 0.6.0
[DBUG: 11:24:48.364 CLIWrapper.js:160]: Successfully ran CLI command cwctl --json --insecure project bind --conid local --name kitura --language swift --type appsodyExtension --path /Users/jsp/Develop/eclipse/codewind/kitura, Output was:
```
When I delete the appsody kitura project, it takes six seconds for the delete to complete
```
[INFO: 11:45:02.644 Requester.js:388]: Doing Unbinding request to http://127.0.0.1:10000/api/v1/projects/6f9fb630-0c7b-11ea-b5fa-0779966da779/unbind
[DBUG: 11:45:08.816 MCSocket.js:94]: Project deleted
6f9fb630-0c7b-11ea-b5fa-0779966da779
[DBUG: 11:45:08.817 DebugUtils.js:107]: Requested to delete launch for kitura, but no launch was found
[INFO: 11:45:08.818 RemoveProjectCmd.js:72]: Deleting project directory: file:///Users/jsp/Develop/eclipse/codewind/kitura
[INFO: 11:45:08.817 Project.js:330]: kitura was deleted
[DBUG: 11:45:08.838 Connection.js:230]: Updating projects list from http://127.0.0.1:10000/ 0.6.0
[DBUG: 11:45:08.845 Connection.js:270]: Done projects update
```
If I then create the project again, with the appsody/kitura image already on my machine, it takes five seconds
```
[INFO: 11:45:28.178 CLIWrapper.js:103]: Running CLI command: cwctl --json --insecure project create /Users/jsp/Develop/eclipse/codewind/kitura --url https://github.com/appsody/stacks/releases/download/kitura-v0.2.2/incubator.kitura.v0.2.2.templates.default.tar.gz
[DBUG: 11:45:33.565 CLIWrapper.js:160]: Successfully ran CLI command cwctl --json --insecure project create /Users/jsp/Develop/eclipse/codewind/kitura --url https://github.com/appsody/stacks/releases/download/kitura-v0.2.2/incubator.kitura.v0.2.2.templates.default.tar.gz, Output was:
{"status":"success","projectPath":"/Users/jsp/Develop/eclipse/codewind/kitura","result":{"language":"swift","projectType":"appsodyExtension"}}
[INFO: 11:45:33.565 CLIWrapper.js:103]: Running CLI command: cwctl --json --insecure project bind --conid local --name kitura --language swift --type appsodyExtension --path /Users/jsp/Develop/eclipse/codewind/kitura
[WARN: 11:45:33.793 MCSocket.js:163]: Received socket event for nonexistent project
55fce0b0-0c7e-11ea-b5fa-0779966da779
[DBUG: 11:45:33.842 Connection.js:230]: Updating projects list from http://127.0.0.1:10000/ 0.6.0
[DBUG: 11:45:33.845 CLIWrapper.js:160]: Successfully ran CLI command cwctl --json --insecure project bind --conid local --name kitura --language swift --type appsodyExtension --path /Users/jsp/Develop/eclipse/codewind/kitura, Output was:
```
So the long delay is caused by the time it takes to pull the appsody/kitura image during the create, and PFE is not sending any notifications until after that's complete and we've called `cwctl bind`.   

In both vscode, we are displaying a progress indicator while the project create is running,.

I am not seeing equivalent delays for non-appsody codewind projects.

At this point, I don't see what the IDEs can do to 'fix' this.

**Comment by mmulholl** [comment]
@jopit @makandre just reproduced the problem and added a huge sleep in test case when it happened so I get chance to collect diag. Pfe log:

[21/11/19 17:38:45 SVTGoProject1] [INFO] Extension absolute path is: undefined
[21/11/19 17:38:45 SVTGoProject1] [INFO] Build completed for c1d33710-0c85-11ea-ac8a-1762054ee892
[21/11/19 17:38:53 SVTGoProject1] [INFO] operationId: 4496f15e24dae031af9582a733f81b13
[21/11/19 17:38:53 SVTGoProject1] [INFO] Extension absolute path is: undefined
[21/11/19 17:38:53 SVTGoProject1] [INFO] removeProject: Kill running processes and remove container... 
[21/11/19 17:38:53 SVTGoProject1] [INFO] Project ID:        c1d33710-0c85-11ea-ac8a-1762054ee892
[21/11/19 17:38:53 SVTGoProject1] [INFO] Project Location:  /codewind-workspace/SVTGoProject1
[21/11/19 17:38:53 SVTGoProject1] [INFO] Project Type:      docker
[21/11/19 17:38:53 SVTGoProject1] [INFO] Project Container: cw-svtgoproject1-c1d33710-0c85-11ea-ac8a-1762054ee892
[21/11/19 17:38:53 SVTGoProject1] [INFO] Removing container
[21/11/19 17:38:54 SVTGoProject1] [INFO] Removing docker image
[21/11/19 17:38:54 SVTGoProject1] [INFO] Extension absolute path is: undefined
[21/11/19 17:38:54 SVTGoProject1] [INFO] Project info cache is {}
[21/11/19 17:38:54 SVTGoProject1] [INFO] Successfully deleted c1d33710-0c85-11ea-ac8a-1762054ee892
[21/11/19 17:38:54 Turbine] [INFO] Removing project logs directory
[21/11/19 17:38:54 Turbine] [INFO] Log directory removed from: /codewind-workspace/.logs/SVTGoProject1-c1d33710-0c85-11ea-ac8a-1762054ee892
[21/11/19 17:38:54 Turbine] [INFO] c1d33710-0c85-11ea-ac8a-1762054ee892: Emitting event 
 message: projectDeletion
 data: {
  "operationId": "4496f15e24dae031af9582a733f81b13",
  "projectID": "c1d33710-0c85-11ea-ac8a-1762054ee892",
  "status": "success"
}
[21/11/19 17:38:54 User.js] [INFO] Removing project directory at /codewind-workspace/SVTGoProject1

My test case log shows the removal happening (timestamps match)

[21.11.2019_12.38.48.803]
==> [FINE] CodewindContainerEclipse.selectMenuItem ->  Remove

[21.11.2019_12.38.48.813]
	[FINE] CodewindTreeEclipse.getTreeItem ->  found : true
	[FINE] LocalTreeEclipse.getTreeItem ->  result : true

[21.11.2019_12.38.48.818]
	[FINE] CodewindTreeEclipse.getTreeItem ->  found : true

[21.11.2019_12.38.48.820]
	[FINE] LocalTreeEclipse.getTreeItem ->  result : true

[21.11.2019_12.38.52.536]
<== [FINE] CodewindContainerEclipse.selectMenuItem ->  Remove : result = true

[21.11.2019_12.38.52.537]
[FINE] CodewindProjectEclipse.delete ->  click OK on the pop-up


However my logs show the project still in codewind just over a minute later much later:

21.11.2019_12.39.54.825]
[FINE] CodewindUtilsEclispe.isProjectPresentInCodewind ->  project : SVTGoProject1, Found Node :SVTGoProject1 [Running] [Build successful]

The test case then takes a screenshot and the file has the timestamp in its name and shows the project still there:

/codewind-svt-eclipse-bot/target/cw-output/thread_47/screenshots/thread_47-screenshot-on-error-21.11.2019_12.39.55-ID_0.png

![thread_47-screenshot-on-error-21 11 2019_12 39 55-ID_0](https://user-images.githubusercontent.com/16086270/69363205-0c3ced00-0c5e-11ea-942c-7cab3420a9ff.png)

**Comment by mmulholl** [comment]
The test case is still sleeping so if you need more info let me know.

**Comment by mmulholl** [comment]
Here is a snippet form the filewatcher log:

Nov 21 12:38:41.243 PM [21.620] Updating timestamp to latest: 1574357921165
Nov 21 12:38:54.778 PM [35.155] Received watch change message from WebSocket: {"type":"watchChanged","projects":[{"changeType":"delete","projectID":"c1d33710-0c85-11ea-ac8a-1762054ee892"}]}
Nov 21 12:38:54.778 PM [35.155] Watch list update received for { [c1d33710-0c85-11ea-ac8a-1762054ee892 in null] }
Nov 21 12:38:54.778 PM [35.155] Examining received file watch state from WebSocket
Nov 21 12:38:54.778 PM [35.155] Removing project from watch list: c1d33710-0c85-11ea-ac8a-1762054ee892 /Users/mmulholl@us.ibm.com/junit-workspace/SVTGoProject1
Nov 21 12:38:54.778 PM [35.155] Path '/Users/mmulholl@us.ibm.com/junit-workspace/SVTGoProject1' removed from EclipseResourceWatchService
Nov 21 12:40:29.859 PM [130.236] Initiating GET request to http://127.0.0.1:10000/api/v1/projects/watchlist
Nov 21 12:40:29.866 PM [130.242] GET request completed, for http://127.0.0.1:10000/api/v1/projects/watchlist. Response: {  "projects": []}
Nov 21 12:42:39.894 PM [260.271] Initiating GET request to http://127.0.0.1:10000/api/v1/projects/watchlist
Nov 21 12:42:39.900 PM [260.277] GET request completed, for http://127.0.0.1:10000/api/v1/projects/watchlist. Response: {  "projects": []}

**Comment by mmulholl** [comment]
I also note that although the pfe logs output:

[21/11/19 17:38:54 User.js] [INFO] Removing project directory at /codewind-workspace/SVTGoProject1

the workspace directory is actually "junit-workspace"  and /junit-workspace/SVTGoProject1 still exists

**Comment by eharris369** [comment]
All I can think of in that case is that the events are getting lost somehow.  It could be that the java implementation of socket.io is not very robust.  I could try modifying the code to handle every event on a separate thread but I would not want to do this for 0.6.0.  The user does have an easy workaround which is to do a refresh.

**Comment by jopit** [comment]
I'm thinking we should raise a separate issue raised for this intermittent deletion issue, since it's unrelated to the Appsody Kitura slow creation issue.

I have not seen this behaviour when deleting projects manually, ever.  I don't believe it's stop-ship.

**Comment by mmulholl** [comment]
@jopit I actually opened this issue for delete issue ha ha.

**Comment by jopit** [comment]
So in eclipse, I created and deleted ten appsody kitura projects in a row with no problems... and then I thought I'd try one more time, and this time the project didn't get removed from the UI.

As I said above, I don't believe this deletion issue is stop ship.  If the user gets into this situation, doing a refresh on the connection in the codewind view will clean up the UI.

**Comment by mmulholl** [comment]
@jopit pleased you saw it too to show it is not a figment of my imagination. Agree not stop ship.

**Comment by GeekArthur** [comment]
Agree with JohnP, I don't think this intermittent deletion issue is stop ship either, because majority of folks can't reproduce this and we don't see obvious delay caused by production code from IDE layer log and PFE layer log (except large image pulling time), and we find workaround is to refresh the IDE.

Regarding SVT test automation, for the time being you may try to either pull large image in advance on testing environment to boost the process speed or increase the timeout to tolerate this intermittent deletion delay issue.

**Comment by malincoln** [comment]
@jagraj will open a separate issue for the refresh.

**Comment by mmulholl** [comment]
@GeekArthur increasing timeout doesn't help, once it sticks it never goes away until a refresh. If codewind refreshed every few seconds maybe no problem. Also not as intermittent as you think, anybody who used the product seriously is bound to see it in the end. It is a problem and needs a fix.

**Comment by mmulholl** [comment]
just saw it again, doing light manual testing

**Comment by GeekArthur** [comment]
@mmulholl 
> increasing timeout doesn't help, once it sticks it never goes away until a refresh.

If that the case, that's different issue which is "hang", not "delay". "delay" is performance issue and can be resolved by increasing timeout but "hang" can be potential bug (either from our code or from dependencies), and definitely we need to fix it. Once you hit the "hang" again, you can check PFE log and IDE log, those logs have timestamp so that we will know the "hang" is from which layer and which step (eg. notification sending/receiving, project deletion on PFE, project display on IDE, etc).

**Comment by eharris369** [comment]
I have seen this too but only when debugging and I have breakpoints in the code that handles the socket events - which is what leads me to believe that the java socket.io code is not very robust and I will have to run the event handlers on separate threads.  I agree that this should be fixed.

**Comment by mmulholl** [comment]
This problem seemed to largely clear up in 0.6.1 but is now back being a big problem using latest to SVT automated tests which fail because projects are not being removed from the codewind list of projects.

**Comment by mmulholl** [comment]
On my latest test run with 0.7.0 5 of 8 projects created remained in the codewind list after removal.

**Comment by mmulholl** [comment]
I have also seen some projects apparently stuck in starting state (for over 5 minutes), change state to running immediately after I hit refresh.

**Comment by jagraj** [comment]
I also see this problem when running tests manually. I have to refresh tree to change the status of the projects.

**Comment by malincoln** [comment]
@eharris369 ^^^

**Comment by eharris369** [comment]
I have investigated this and the Java socket.io code is using the same thread for all of the events.  If I put a breakpoint on the code to handle the project status changed event it stops on the breakpoint for build started event.  If I leave it on the breakpoint for a while and then run it, it stays in build started state.  It never hits the breakpoint for any other events after that on the same thread or on a different thread.  So it looks like I would have to rewrite how the socket events are handled (create my own queue of events and process them in order).  I also looked at polling to keep the projects up to date but this caused problems.  While creating a project it would show up as disabled while the progress monitor is still showing that it is being created.  Also I hit some deadlocks.  So I would have to redo the synchronization.  I don't think the IDEs should be polling anyway.  The first fix is easier as well though it is still a rewrite of a main piece of code so would require full re-testing.

**Comment by eharris369** [comment]
Tried setting IO.Options.timeout to -1 to disable it but it did not help.

**Comment by jopit** [comment]
Setting OkHttpClient's readTimeout to 0, however, does stop the timeout exceptions.  Need to do more testing to ensure it doesn't break anything.

**Comment by jgwest** [comment]
I'm curious, how do we handle the case where the connection drops for network reasons? Would we lose events in this case too? I imagine it may be slightly different with socket.io, but with the filewatchers my solution to this question is:
- Every ~20 seconds, send an empty packet on the WebSocket to make sure it is still open
- If we get an unexpected 'WebSocket closed' event on the client side, then issue a GET request to do a full watch state refresh (my guess is the equivalent for Codewind would be whatever the 'Refresh' menu item does), and simultaneously attempt to reopen the socket
- Otherwise, every 60 seconds, automatically issue a GET request to refresh the watch state. 

(@jopit)

**Comment by jopit** [comment]
In the local scenario, if the 'network' drops you probably have bigger problems than missing a few events.  In the hybrid scenario, if the network drops, the connection will go into 'disconnected' state.  When you reconnect, the status is fully refreshed.  It's no different from the user explicitly disconnecting and the later reconnecting.

**Comment by jgwest** [comment]
@jopit I see, does the user have to manually reconnect (invoke a menu item) after disconnect occurs?

**Comment by mmulholl** [comment]
Have ran my test twice now, it would normally see around 4 failures per run and now it is none. Thank you!!!!!!
