### ISSUE TITLE
SVT : Eclipse : install fails without docker system prune

### ISSUE THREAD

**Issue by mmulholl** [eclipse/codewind#1181]
*Codewind version: Codewind tech preview 0.6.0.v201911181652
OS: MAC/OS

Che version:
IDE extension version:
**IDE version:**Eclipse IDE for Enterprise Java Developers. Version: 2019-09 R (4.13.0) Build id: 20190917-1200

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**
To install the latest driver I uninstalled my previous version of 0.6.0 and installed a new version. However the install failed (download image stage) because of a problem finding images. Docker system prune fixed things and download started working. Had the same experience with the previous uninstall re-install for 0.6.0,

**Steps to reproduce:**

**Workaround:**

**Comment by malincoln** [comment]
@tetchel or @jopit can you review this one?  Thanks

**Comment by jopit** [comment]
Likely the same as https://github.com/eclipse/codewind/issues/411

**Comment by malincoln** [comment]
@tobespc @james-wallis pls review.  If it's the same, we would need a fix for 0.6.0.

**Comment by rtaniwa** [comment]
I think we need to understand the risk of the fix before we decide if this is a stop ship for 0.6 given this has been there since 0.4. That being said, it is a very ugly issue so if we can fix it, I do think it should be considered.

**Comment by liamchampton** [comment]
@jopit What was the actual output when there was a problem finding images? Its important to capture this info in the issue before doing a docker prune as that wipes it clean. Im currently working on the fix i have described at the bottom of #1148 to check the image digest before and after a download.

**Comment by tobespc** [comment]
Not sure what to suggest here.   Has this happened before?  Can you recreate it ?  The fact that you have blown all the images away and its now working doesn't give us much to work with

**Comment by jopit** [comment]
@liamchampton that's a question for @mmulholl, who opened this issue.

**Comment by tetchel** [comment]
while this is a bad issue we have been seeing variations of it since we first introduced cwctl in 0.3, I don't think it's fair to call this a stopship.

**Comment by malincoln** [comment]
I just discussed with @mmulholl and @jagrag and they will try recreating and gather logs.  We can then have a quick meeting to discuss next steps.

**Comment by tetchel** [comment]
we have https://github.com/eclipse/codewind/issues/436 to document workaround / suggestions for this too but it never got actioned

**Comment by malincoln** [comment]
Discussed today and it was decided to continue to investigate, get logs from failure, and determine fix for the next release.  Not required for 0.6.0.

**Comment by mmulholl** [comment]
I just moved to the latest version of the eclipse plugin on mac and did not see an issue. Same scenario in which I previously saw the problem.

**Comment by malincoln** [comment]
@tobespc pls move to verify if code is merged per discussion today.  Thanks

**Comment by mmulholl** [comment]
Closing as have not been able to reproduce the issue
