### ISSUE TITLE
use npm clean install instead of regular install in dockerfiles 

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#1186]
When working on https://github.com/eclipse/codewind/issues/1180 I noticed that `package-lock.json` is gitignored at the top level of the codewind repository, which is definitely wrong, npm is pretty clear about this:
```
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN gatekeeper@1.0.0 No description
npm WARN gatekeeper@1.0.0 No repository field.
```

We have to commit this file so that in our prod builds, we can then use `npm ci` instead of `npm i` and make sure that the package versions we are shipping are the same ones we're developing against.

https://docs.npmjs.com/cli/ci.html#description

**Comment by rajivnathan** [comment]
FWIW, portal and turbine both make use of package-lock.json

https://github.com/eclipse/codewind/blob/master/src/pfe/portal/package-lock.json
https://github.com/eclipse/codewind/blob/master/src/pfe/file-watcher/server/package-lock.json

**Comment by tetchel** [comment]
okay, then it should be easy to un-gitignore it

**Comment by hhellyer** [comment]
package-lock.json is git ignored at the top level top prevent accidental commits from other locations but it is un-ignored in both portal, turbine, gatekeeper and performance:

https://github.com/eclipse/codewind/blob/master/src/pfe/portal/.gitignore#L4
https://github.com/eclipse/codewind/blob/master/src/pfe/file-watcher/server/.gitignore#L5
https://github.com/eclipse/codewind/blob/master/src/gatekeeper/.gitignore#L4
https://github.com/eclipse/codewind/blob/master/src/performance/.gitignore#L1

All four seem to be using npm ci for builds in their Dockerfiles as well so I'm not sure there's anything to do here. (Unless I've missed something.)

@tetchel - If that's right can this be closed? (If not let us know what we've missed.)

**Comment by tetchel** [comment]
It is done
