### ISSUE TITLE
SVT:[che]:Appsody projects status stuck in "starting" after workspace restart due to user session timeout 

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#1187]
**Codewind version:** 0.6.0
**OS:** RHEL

**Che version:** 7.3.1
**IDE extension version:** 0.6
**IDE version:** 7.3.1
**Kubernetes cluster:** 

OS 3.11 cluster

**Description:**
All appsody projects "status" is in "starting" state after workspace restart due to session timeout. 
I do not see this problem with default codewind projects. 

**Steps to reproduce:**

1. Install Codewind Che from 0.6.0 plugin 
2. After creating all appsody and default codewind projects and wait until all projects up and running.
3.  After session timeout, the workspace is restarted the entire workspace is being rebuilt.
4. The status for all appsody projects stuck in starting state but not for default codewind templates.

![image](https://user-images.githubusercontent.com/713849/69095702-e676d480-0a20-11ea-9e84-1a57dc5489eb.png)

Logs 
[pfe.txt](https://github.com/eclipse/codewind/files/3860802/pfe.txt)
[theia.txt](https://github.com/eclipse/codewind/files/3860803/theia.txt)

**Workaround:**

**Comment by sghung** [comment]
I asked Andrew to take a look at this one.

**Comment by makandre** [comment]
Where are the appsody logs?

**Comment by makandre** [comment]
```
[32m[18/11/19 20:39:11 appsodynodejscw06svt] [INFO][39m Emitted event: projectCreation
{"operationId":"0b156bcda276ddff33c8363ca4f59627","projectID":"2a822900-0a0c-11ea-86f6-a532b5f1f0f8","isHttps":false,"status":"success","ports":{},"logs":{"build":[],"app":[{"origin":"workspace","files":["/codewind-workspace/.logs/appsodynodejscw06svt-2a822900-0a0c-11ea-86f6-a532b5f1f0f8/appsody.log"]}]},"error":{}}
[91m[18/11/19 20:39:11 appsodynodejscw06svt] [ERROR][39m Unable to retrieve project deployment or service
[32m[18/11/19 20:39:11 appsodynodejscw06svt] [INFO][39m Emitting event 
 message: projectCreation
 data: {
  "operationId": "0b156bcda276ddff33c8363ca4f59627",
  "projectID": "2a822900-0a0c-11ea-86f6-a532b5f1f0f8",
  "isHttps": false,
  "status": "success",
  "ports": {},
  "logs": {
    "build": [],
    "app": [
      {
        "origin": "workspace",
        "files": [
          "/codewind-workspace/.logs/appsodynodejscw06svt-2a822900-0a0c-11ea-86f6-a532b5f1f0f8/appsody.log"
        ]
      }
    ]
  },
  "error": {}
}
[32m[18/11/19 20:39:12 swiftcw06svt] [INFO][39m Pod name was not found while looking up service information for project.
[32m[18/11/19 20:39:48 appsodyspringcw06svt] [INFO][39m pingInTransitApplications: Application state error message: could not retrieve the port for the project
```

This part in the log is telling.  At least for this particular case, it seems Codewind can't find the application port, and it's because it can't find the appsody deployment/service.

There's a wait we do here https://github.com/eclipse/codewind-appsody-extension/blob/master/scripts/wait-for-container.sh#L20 for the pod to come up.  With so many projects/pods/services being created at the same time, it's possible the wait times out before the appsody pod comes up.

**Comment by jagraj** [comment]
I got into cluster issues and I could n't install che. After rebooting cluster, I am able to install che on my cluster. I will try to recreate and update my results here.

**Comment by makandre** [comment]
@jagraj looks like we need a new build of PFE to pick up the new change anyways @sghung or @josephca do we have other fix going into PFE?

**Comment by johnmcollier** [comment]
@makandre I can kick off a jenkins build for the codewind master branch

**Comment by josephca** [comment]
@makandre I believe this new build already picked up the new changes. Please let me know otherwise.
https://ci.eclipse.org/codewind/view/Codewind/job/Codewind/job/codewind/job/0.6.0/13

**Comment by jagraj** [comment]
I got the latest images and verified this fix after workspace restart and projects are no longer stuck in "Starting" state.  Thanks for the fix.
