### ISSUE TITLE
Improvements for test automation scripts

### ISSUE THREAD

**Issue by rajivnathan** [eclipse/codewind#119]
**Codewind version:**
All
**OS:** 
Mac/Linux

**Description of the enhancement:**

There still seems to be a few issues with the test scripts:

- Projects get cloned with the indices in the PROJECT_URLS array, eg. codewind-workspace/0
- Only the swift project appears to be cloned
- Think we can still make some improvements related to cronjob vs test scripts

**Proposed solution:** 

- [x] Fix project cloning during test setup
- [x] Add option to delete project workspace if it's not empty
- [x] Move cronjob scripts to test/cronjob directory
- [x] Change TEST_CONFIGURATION option to CLEAN_RUN, so that user and test automation has the option to test against latest Codewind

**Comment by GeekArthur** [comment]
@rajivnathan You can assign this issue to me

**Comment by GeekArthur** [comment]
Since @ssh24 test cases cover the Kube case, I can add setup code to enable Kube case for test automation scripts

**Comment by ssh24** [comment]
Will this story also include enabling the cronjob into the VM?

**Comment by GeekArthur** [comment]
Issue of enabling cronjob into the VM is here: https://github.com/eclipse/codewind/issues/137
