### ISSUE TITLE
Codewind VS Code Marketplace Extensions - move to an eclipse namespace

### ISSUE THREAD

**Issue by ericdylanpeters2** [eclipse/codewind#12]
Currently published codewind extensions should be published under an eclipse namespace (might need to work with the eclipse webmaster to create the namespace if it doesn't already exist) 

https://marketplace.visualstudio.com/items?itemName=IBM.codewind-java-profiler
https://marketplace.visualstudio.com/items?itemName=IBM.codewind-openapi-tools
https://marketplace.visualstudio.com/items?itemName=IBM.codewind
https://marketplace.visualstudio.com/items?itemName=IBM.codewind-node-profiler

**Comment by josephca** [comment]
Opened Eclipse bugzilla ticket : https://bugs.eclipse.org/bugs/show_bug.cgi?id=549405

**Comment by josephca** [comment]
Update from Eclipse team :
 
Unfortunately, the Microsoft Visual Studio Marketplace Publisher Agreement[1] contains an unlimited indemnity clause which prevents the Eclipse Foundation from being able to enter into the agreement.

We are extremely sorry to not have better news as we were excited to support this initiative.

Thank you for understanding our position.  Should you have any other questions related to this, please contact license@eclipse.org.

[1] https://cdn.vsassets.io/v/M146_20190123.39/_content/Visual-Studio-Marketplace-Publisher-Agreement.pdf

**Comment by deboer-tim** [comment]
I've asked them to clarify whether there's another option via bugzilla, we'll have to wait and see.

**Comment by tetchel** [comment]
based on the bugzilla, this is not going to happen.
