### ISSUE TITLE
SVT: Open Liberty project doesn't start after the migration from 0.5.0 to 0.6.0

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#1204]
**Codewind version:** 0.5.0 / 0.6.0 (codewind-0.6.0-201911151544.vsix)
**OS:** VM with Windows 10

**IDE extension version:** 0.5.0 / 0.6.0
**IDE version:** 1.40.1

**Description:** Default Open Liberty project doesn't start after the migration from 0.5.0 to 0.6.0. The application is displayed as [Running] (https://github.com/eclipse/codewind/issues/1203), but it could not be accessed when using its endpoint URL (default server shown).

![Screen Shot 2019-11-19 at 10 38 26 AM](https://user-images.githubusercontent.com/49531960/69163923-11af0180-0abd-11ea-9940-7437394a7622.png)

![Screen Shot 2019-11-19 at 10 38 39 AM](https://user-images.githubusercontent.com/49531960/69163930-14115b80-0abd-11ea-9ce1-2682330e3672.png)

**Steps to reproduce:**
1. Clean VM from any Codewind installation
2. Install Codewind 0.5.0
3. Create some projects, including a Default Open Liberty
4. Migrate to Codewind 0.6.0
5. Default Open Liberty project will not start, even when manual build is clicked

**Logs:**
[cw-default-open-liberty.docker.build.log](https://github.com/eclipse/codewind/files/3864720/cw-default-open-liberty.docker.build.log)
[cw-default-open-liberty.app.log](https://github.com/eclipse/codewind/files/3864722/cw-default-open-liberty.app.log)
[codewind.log](https://github.com/eclipse/codewind/files/3864727/codewind.log)
[filewatcherd-1.log](https://github.com/eclipse/codewind/files/3864728/filewatcherd-1.log)
[codewind-pfe.txt](https://github.com/eclipse/codewind/files/3864729/codewind-pfe.txt)

@jagraj

**Comment by makandre** [comment]
That’s not an appsody project. Does it contain a .appsody-config.yaml?

**Comment by sujeilyfonseca** [comment]
@makandre sorry for that. I corrected the title of this Github issue.

**Comment by ssh24** [comment]
So I just tried reproducing this with a 0.5.0 OL app migrated to 0.6.0 in VSCode Mac and it worked for me. Both apps came up and running:
**0.5.0**
![Screen Shot 2019-11-21 at 4 05 02 PM](https://user-images.githubusercontent.com/15173354/69376755-e07b3080-0c78-11ea-8cf1-e14fbfb9581e.png)
**0.6.0**
<img width="749" alt="Screen Shot 2019-11-21 at 3 53 08 PM" src="https://user-images.githubusercontent.com/15173354/69376770-e709a800-0c78-11ea-954c-61e4d3f74d39.png">

I was also able to open the app both times

**Comment by ssh24** [comment]
I just tried it out on windows as well, and the migration worked as well and the app also came up:
This is after migration from **0.5.0** to **0.6.0**
![Screen Shot 2019-11-21 at 5 33 03 PM](https://user-images.githubusercontent.com/15173354/69382397-fee72900-0c84-11ea-8a01-4cc5ccaa1be1.png)
![Screen Shot 2019-11-21 at 5 31 24 PM](https://user-images.githubusercontent.com/15173354/69382401-01498300-0c85-11ea-9960-0640e08e7cd6.png)

**Comment by ssh24** [comment]
@sujeilyfonseca Any updates? If you cannot reproduce this anymore, can this be closed?

**Comment by sujeilyfonseca** [comment]
Thanks @ssh24 for verifying this issue! I can no longer reproduce this problem with the latest images.
