### ISSUE TITLE
Re-enable templates test

### ISSUE THREAD

**Issue by rajivnathan** [eclipse/codewind#1207]
**Description:**
The templates tests were disabled in https://github.com/eclipse/codewind/pull/1206 because it was failing the master builds. The failure appears to be due to a slight mismatch of the json returned from the kabanero repo. There was also some discussion about whether this test could be more flexible. eg. Tim's suggestion was to check array length and key existence and not have to copy over the entire file’s contents into our tests every time it changes

**Comment by johnmcollier** [comment]
I think a prerequisite to re-enabling the tests is either:
- Ensuring changes in the template repo can't break the tests on Codewind so easily, or
- Some sort of CI build running on the templates repo ensuring that changes to it don't break Codewind

**Comment by ssh24** [comment]
I like the second idea better. We can have the same PR tests in Codewind (or subset of it) running in the templates repo to catch this.

**Comment by james-wallis** [comment]
/assign 
I don't think that we should test for the Appsody templates or the Kabanero templates at all as they are out of our control when they change. 
I'm creating a PR which will change the tests to only test that:
* The response contains the default Codewind templates as we control them.
* The length of the list of templates is at least as long as the expected Codewind templates.

I also think that if we want tests for the Kabanero and Appsody templates these should be external to the Codewind repository as they are out of our control, I think that this is what is outlined in the conversation above. 

Branch for this work: https://github.com/james-wallis/codewind/tree/re-enable-template-tests

**Comment by james-wallis** [comment]
Forgot to add to this issue, the PR for this is up. I changed branch mid-way for development so the above branch link is redundant.
PR is https://github.com/eclipse/codewind/pull/1292

**Comment by james-wallis** [comment]
The templates tests have been enabled.
