### ISSUE TITLE
cwctl should create the namespace and the service account for remote PFE

### ISSUE THREAD

**Issue by maysunfaisal** [eclipse/codewind#1211]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**
cwctl is currently deploying PFE for remote.

so cwctl should be ensuring the namespace exist and the service account is created. The users should not do this themselves.

**Steps to reproduce:**

**Workaround:**

**Comment by maysunfaisal** [comment]
@markcor11 FYI, for cwctl deploying remote PFE.

**Comment by tetchel** [comment]
The namespace is minor, the serviceaccount is mandatory for building projects. the SA name also has to be exported into the PFE environment as `SERVICE_ACCOUNT_NAME`

**Comment by johnmcollier** [comment]
Relevant lines here (and below): https://github.com/eclipse/codewind-installer/blob/master/pkg/remote/deploy.go#L119

Currently being hardcoded to `codewind`

**Comment by markcor11** [comment]
- [x] add namespace : 

```
INFO[0000] Checking if namespace marktest99 exists         
INFO[0000] Creating marktest99 namespace                
INFO[0000] Using namespace : marktest99                 
INFO[0000] Container images :                           
INFO[0000] eclipse/codewind-pfe-amd64:latest            
INFO[0000] eclipse/codewind-performance-amd64:latest    
INFO[0000] eclipse/codewind-keycloak-amd64:latest       
INFO[0000] eclipse/codewind-gatekeeper-amd64:latest     
```

- [ ] add service account

**Comment by markcor11** [comment]
The changes for the namespace are merged,  for the second part of this what should we call the service account?  For a Che deployment we use che-workspace I had a placeholder in of just "codewind" since we might not have a che service account and need to create something.   Any preferences ?

**Comment by maysunfaisal** [comment]
probably call it `codewind-sa`/`codewind-workspace`?

**Comment by johnmcollier** [comment]
@markcor11 @maysunfaisal I'm concerned about uniqueness here - If multiple remote Codewind instances can be installed on a cluster (which is a use case we need to support), then either the namespace used needs to be unique or the service account name needs to be unique.

**Comment by markcor11** [comment]
I've been primarily installing Codewind remote 1 per namespace just because its easier to clean up the ingress/service/secrets.  Each Codewind deployment has a unique "workspace" name used between all 4 pods and that's also true for the keycloak secrets and configmaps. Would creating  the service account with the same "workspace" identifier work? My gut feeling is 1 PFE per namespace would be best though.

**Comment by johnmcollier** [comment]
Yup, adding the `workspace` identifier to the service account would work.

And agreed, 1 Codewind per namespace is probably the general scenario that will be used and that multiple Codewinds per namespace is unlikely, but we either need to:
- Don't support it, and have `cwctl` error out if Codewind is already installed in a namespace, or
- Support, and ensure all resources have unique names

**Comment by jopit** [comment]
There's a number of comments made after this was moved to verify.  It sounds like there's more work to be done and it should be moved back to in progress?

**Comment by tetchel** [comment]
it is definitely not ready to verify because the serviceaccount has not been added yet

**Comment by markcor11** [comment]
Will raise on tech topics to discuss if should support multiple PFE remotes per namespace or enforce a single one.

**Comment by jopit** [comment]
We will support multiple PFEs per namespace, since we need to support this for Che anyway

**Comment by markcor11** [comment]
CWCTL PR: Set codewind permissions #235

/pipeline Verify

**Comment by malincoln** [comment]
@maysunfaisal pls verify and close if resolved.  Thanks

**Comment by malincoln** [comment]
@maysunfaisal @elsony pls verify and close if resolved. Thanks
