### ISSUE TITLE
[Cwctl] Add 'INGRESS_PREFIX' env var to remote PFE deployment

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#1212]
PFE requires that `INGRESS_PREFIX` be set in order to expose applications over ingress. If it is not set, applications will not deploy properly on OCP4. This field is not currently being set for remote PFE deployments via Cwctl.

On Codewind on Che, we set it to the Che ingress domain (e.g. `che-che.9.1.2.3.nip.io`), for Hybrid it can just be the raw ingress domain that we discover or have passed in (so just `9.1.2.3.nip.io`)

@markcor11 FYI

**Comment by johnmcollier** [comment]
This is a requirement for Hybrid in 0.7.0, as it prevents apps from properly deploying on OCP4, so marking as hot.

**Comment by markcor11** [comment]
Set INGRESS_PREFIX to the determined domain name (or parameter defined domain) to PFE during hybrid remote deploy. From inside pfe container : 

sh-4.2# printenv | grep -i  ingress
INGRESS_PREFIX=apps.<someserver>.<someip>.nip.io

PR with change :  https://github.com/eclipse/codewind-installer/pull/229

**Comment by johnmcollier** [comment]
Closing out, looks good.
