### ISSUE TITLE
Rebuild codewind and codewind-che-plugin when repos they depend on are updated

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#1214]
Terrible title, but currently `codewind` consumes the `codewind-appsody-extension` and `codewind-odo-extension`. When the repo for those extensions are updated, it requires a rebuild of Codewind to pull down the updated extensions.

Similarly, the `codewind-che-sidecar` image depends on the Golang filewatcherD binary (from https://github.com/eclipse/codewind-filewatchers) and Cwctl (https://github.com/eclipse/codewind-installer). Updates to either of those requires a rebuild of the `codewind-che-sidecar image before it consumes the updated binaries.

Currently when changes to the extensions, CLI, or filewatcher occur, the `codewind` and `codewind-che-sidecar` images will be out of date / sync until a rebuild occurs, which either requires another PR to be merged or a build to be kicked off manually via Jenkins.

Speaking with @tetchel it's possible for a Jenkins build in one repo to trigger a build in another repo. For example, a Jenkins build in the Codewind VS Code extension is triggered whenever changes to the matching branch in the CLI repo are merged. 

We need to do the same for `codewind` and `codewind-che-plugin`:
- If a change is merged into `codewind-appsody-extension` or `codewind-odo-extension`, kick off a Jenkins build for the corresponding branch in the `codewind` repo
- If a change is merged into `codewind-filewatchers` or `codewind-installer`, kick off a Jenkins build for the corresponding branch in the `codewind-che-plugin` repo

**Comment by johnmcollier** [comment]
CC @josephca @GeekArthur @makandre

**Comment by tetchel** [comment]
[example](https://github.com/eclipse/codewind-vscode/blob/master/Jenkinsfile#L37)

**Comment by GeekArthur** [comment]
PRs are merged for both `codewind` and `codewind-che-plugin` and verified, close the issue.
