### ISSUE TITLE
 Codewind Eclipse does not detect file changes (and trigger build) if the Eclipse project name is different from the Codewind project name.

### ISSUE THREAD

**Issue by jgwest** [eclipse/codewind#1217]
Codewind Eclipse appears not to detect file changes (eg the filewatcher is never informed of new changes) if the Eclipse project name is different from the Codewind project name.

In Eclipse, the name of the project can differ from the directory that it is contained in. This appears to cause issues with Codewind, which expect them to be the same.

Since I initially thought it might be a Filewatcher issue, I did some digging, and it actually appears to be an issue with the `ICodewindProjectTranslator` implementation in `CodewindConnection.java`. This interface is used by the filewatcher to ask Eclipse what the project ID is for a particular IProject:
```java
filewatcher = new CodewindFilewatcherdConnection(baseUri.toString(), cwctl, new ICodewindProjectTranslator() {
	@Override
	public Optional<String> getProjectId(IProject project) {
		if (project != null) {
			CodewindApplication app = getAppByName(project.getName());
			if (app != null) {
				return Optional.of(app.projectID);
			}
		}
		return Optional.empty();
	}
```

Here the name of the project (from IProject) is being used to attempt to find the corresponding Codewind app by name, but since the two values differ, an empty optional is returned.

Tested on Windows against latest Eclipse Codewind 0.6 (commit id 1e5a5f2e481130ebebccf86e47c2568441721c30).

This isssue is similar to, but not the same as, this one: https://github.com/eclipse/codewind/issues/862 , for instance, 862 did not appear to prevent file changes from being detected.

#### Steps to reproduce:

*Here I reproduce using the `Refactor > Rename` functionality of Eclipse. This is just one way (the easiest to reproduce) that the project names can get out of sync. I was also able to reproduce with the [Rogue Cloud Codewind client](https://github.com/microclimate-dev2ops/rogue-cloud-client-codewind) where the names are out of sync because the project is being cloned from a GitHub repository that differs from the Eclipse project name. I'm sure there are other ways to reproduce this as well.*

Right click on Codewind menu item, select 'Create New Project...'.
Give the project a name (eg newproj1)
Select WebSphere Liberty MicroProfile, and click Finish.

Wait for the project to build and start.
Remove the project from Codewind (don't delete the file contents).
(You can restart the workbench at this point if you want, in order to make sure there are no lingering connections to this old project)

Right click on the project and select Refactor > Rename.
Specify a new project name (eg newproj2) and click OK.

Note that the project is still in a directory named `newproj1` (eg `C:\codewind-eclipse-0.6\workspace\newproj1`), because in Eclipse the name of the project, and the name of the directory that it is contained in, are separate values.

Right click on Codewind menu item, select 'Add Existing Project", and select your renamed project (eg newproj2).

Note that the project is still named `newproj1` in Codewind.

The project should build successfully. 

Edit a file (for example, `Example.java`), and save the change. Note that the build never triggers.

**Comment by eharris369** [comment]
PR: https://github.com/eclipse/codewind-eclipse/pull/527

**Comment by jgwest** [comment]
Happy to report it is fixed! 🎉
