### ISSUE TITLE
create 'latest' folder to store the latest build in download area

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#1218]
@josephca commented on [Thu Jun 27 2019](https://github.com/eclipse/codewind-installer/issues/43)

For master branch build, it would be convenient if we copy and preserve the latest build in 'latest' directory in download area. i.e. _https://download.eclipse.org/codewind/codewind-installer/master/lastest_. Especially, it will help test automation and SVT. 
Currently, this has been done for plugins and vscode builds. 

---

@tobespc commented on [Fri Jun 28 2019](https://github.com/eclipse/codewind-installer/issues/43#issuecomment-506679572)

Hi @josephca Can you provide some more info as to what this issue it for please and what it will solve ?  thanks

---

@josephca commented on [Thu Jul 11 2019](https://github.com/eclipse/codewind-installer/issues/43#issuecomment-510605614)

Hi @tobespc, sorry for the late response. I updated the summary accordingly. 

---

@liamchampton commented on [Wed Nov 13 2019](https://github.com/eclipse/codewind-installer/issues/43#issuecomment-553447261)

@josephca Is this still relevant? If so, can this be moved to a codewind?(better visability). If not, can it be closed?

**Comment by josephca** [comment]
This is already done. Closing it now.
