### ISSUE TITLE
Initial template selector should appear more often, but when?

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#1227]
Right now the prompt that forces a user to select a template repository initially appears once, ever. This made sense when we had just the one local connection. 

Now, we have to consider how this design should work with remote connections - should we see this prompt every time we create a new connection, or will that get annoying?

**Comment by johnmcollier** [comment]
Adding on - It's not really clear that when I select one of these options when creating a project, that it'll disable the other project types and I'll have to manually go into "Manage Template Sources" to re-enable the others

![Screen Shot 2019-11-25 at 5 26 30 PM](https://user-images.githubusercontent.com/6880023/69592285-7b4e7480-0fc3-11ea-9ca0-02f064f44ccd.png)

**Comment by tetchel** [comment]
I improved the message for you, John. as for the original question, we are adding a button to open the manage sources page to the connection settings, which should suffice.
