### ISSUE TITLE
Improve user feedback when deleting project

### ISSUE THREAD

**Issue by rajivnathan** [eclipse/codewind#1229]
**Codewind version:** latest
**OS:** Mac OSX

**Che version:** 7.3.1
**IDE extension version:** latest
**IDE version:** 7.3.1
**Kubernetes cluster:** OKD 3.1.1

**Description:**
Removing a project takes a long time (> 20s) and there is no indication of what's happening on the UI. To the user it looks like the remove did not take effect.

**Steps to reproduce:**
Create a microprofile project using Che and remove it.

**Workaround:** 

N/A

**Comment by johnmcollier** [comment]
+1 seeing this, especially for larger projects.

**Comment by tetchel** [comment]
is slowness the delay between the IDE issuing the deletion request, and the projectDeletion event, or is it removing the files?

**Comment by rajivnathan** [comment]
@tetchel I see turbine started the removal process pretty much immediatly so I believe the latter.

**Comment by tetchel** [comment]
it is the former

**Comment by tetchel** [comment]
to summarize from my pov, the current behaviour is:

1. issue deletion request
(there is a delay while pfe cleans up)
2. receive deletion event, project disappears from codewind view
4. delete files from user disk if applicable (this shows progress)

the confusion is between steps 1 and 2
