### ISSUE TITLE
Modify index.json format and update template repositories API

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#123]
The current template repository index.json format is just an array of templates. However, we have some data we want to be per-template-repository, which should be provided by the user in this file. Specifically, we want to add a `name` and `description` field. The templates themselves don't have to be changed (though we should update them to include `projectStyle`).

So our `index.json` (slimmed down to one template) would look like:

```
{
    "name": "Standard Codewind Templates",
    "description": "Description of Codewind templates (ask design for these)",
    "templates": [{
        "displayName": "Java MicroProfile template",
        "description": "Cloud Microservice Starter for Java - MicroProfile / Java EE",
        "language": "java",
        "projectType": "liberty",
        "projectStyle": "Codewind",
        "location": "https://github.com/microclimate-dev2ops/javaMicroProfileTemplate",
        "links": {
            "self": "/devfiles/javaMicroProfileTemplate/devfile.yaml"
        }
    }]
}
```

and when I GET `/templates/repositories`, the name and description should be available to me.

In turn, providing a `description` to POST `/templates/repositories` should be removed, because it is instead given in this file. The user should only have to enter their `index.json` url.

**Comment by tetchel** [comment]
This may also be a good time to revisit https://github.com/eclipse/codewind/issues/123

**Comment by tetchel** [comment]
@makandre pointed out that our index.json format is taken from che's devfile registry format, like [this](https://che-devfile-registry.openshift.io/devfiles/index.json). So we shouldn't make this change.

We will have to come up with another way to have the template repository maintainer declare a name and description.

**Comment by tetchel** [comment]
The best proposed solutino so far is to have a second file in the template repository, something like `templates.json` which contains: 
- a name field
- a description field
- any other repository-specific fields we like (none others so far)
- a link to the `index.json` - I don't know how this would work for appsody.
eg for the codewind templates it would be

https://github.com/kabanero-io/codewind-templates/blob/master/devfiles/templates.json:
```
{
    "name": "Standard Codewind templates",
    "description": "Description of standard Codewind templates",
    "url": "https://github.com/kabanero-io/codewind-templates/blob/master/devfiles/index.json"
}
```

**Comment by deboer-tim** [comment]
FWIW, Appsody uses a similar index that also doesn't allow for name or description: https://github.com/appsody/stacks/blob/master/index.yaml

I don't have a better suggestion than the one above, but I don't like the descriptor including a relative URL to the index. IMHO the URL that users see should be to the repo itself (i.e. base URL) and then we should assume relative paths to both the index and the descriptor (which would contain no index URL). If we keep index.json in the repo URL then descriptor should just be a peer URL that we pick up if it's there.

This is a wild one, but I'm assuming there is no good path where we look for a README.md and pull out the first line and first paragraph as the name and description respectively...

**Comment by tobespc** [comment]
this is now implemented and the codewind repo has this change in 
https://github.com/kabanero-io/codewind-templates/blob/master/devfiles/templates.json

**Comment by jopit** [comment]
I believe the PR for this is https://github.com/eclipse/codewind/pull/426
