### ISSUE TITLE
Notify Users on Project Import Progress

### ISSUE THREAD

**Issue by maysunfaisal** [eclipse/codewind#1230]
**Codewind version:** 0.6.0
**OS:**

**Che version:** 7.3.1
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:** OKD 3.11

**Description of the enhancement:**

As part of exercise https://github.com/eclipse/codewind/issues/1222, when I imported Rogue Cloud to Che CW 0.6.0, project sync to almost 23s for me.

In these 23s, I had no idea what was happening. The CW extension view did not show the project not was any message shown that import was in progress.

If a user didn't see the PFE/CW log, they'd have no idea if a sync is in progress and most probably they'd try importing again

**Proposed solution:**

**Comment by johnmcollier** [comment]
We need it for delete too https://github.com/eclipse/codewind/issues/1229

**Comment by tetchel** [comment]
@maysunfaisal should be better now

**Comment by maysunfaisal** [comment]
better, thx.

dont know if this should be kept open for master

**Comment by tetchel** [comment]
the fix was ported from master, it's good there.
