### ISSUE TITLE
Appsody Kitura project doesn't start 

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind#1236]
**Codewind version:** 0.6.0
**OS:** macOS Catalina

**IDE extension version:** vscode codewind-0.6.0-201911202129.vsix

I created an appsody kitura project, which built successfully, but never went into the started state.  When I opened the application endpoint in the chrome browser, I go an error page
```
This page isn’t working
127.0.0.1 didn’t send any data.
ERR_EMPTY_RESPONSE
```
Here's the PFE log
[pfe.txt](https://github.com/eclipse/codewind/files/3875739/pfe.txt)

**Comment by makandre** [comment]
That support is in 0.7.0 (master)... https://github.com/eclipse/codewind-appsody-extension/pull/61

It is quite easy to backport

**Comment by jopit** [comment]
With the fix, the project does start.  However the project status goes from [Starting] to [Stopped], then after quite a while, it goes to [Running], which at first had me thinking it was still broken.

Here's the PFE log
[pfe.txt](https://github.com/eclipse/codewind/files/3877045/pfe.txt)

I don't know if this is still stop-ship, we discuss tomorrow.

**Comment by makandre** [comment]
That happens when an app takes a long time to start, and Turbine gives up pinging after 10 tries and assume the app is stopped.  But it will re-ping it at some point, and finds out it started.

**Comment by jopit** [comment]
Closing as the original problem is fixed. Opened #1247 to track the status problem.
