### ISSUE TITLE
Turbine functional tests need to detect iterative development performance regressions

### ISSUE THREAD

**Issue by rajivnathan** [eclipse/codewind#1245]
**Description of the enhancement:**

The functional tests currently cover creation and update of each of the supported project types. However, it currently cannot detect if performance has degraded. As long a test's project builds and runs the test will pass.

In issue #1222 we saw that on Windows a bug changed the behaviour such that a mvn package was done instead of a mvn compile and this impacted performance severely.

**Proposed solution:** 

A few options:
1. Adjust timeouts to some pre-determined minimum bar for test steps if they're granular enough. This may not be viable depending on variation of test environments (eg. machines with SSD vs without)
2. Monitor the pfe container logs while the tests run and validate that specific messages that indicate the correct code path is being followed and result in a test error otherwise.
3. Write performance focused tests
4. Other options?

**Comment by rajivnathan** [comment]
Discussed this in the Iterative-dev meeting. We'll go with option 1 and capture timings for steps within the existing functional tests. Once we have enough data points we can decide on timeout values on a case by case basis.

**Comment by elsony** [comment]
The other thing that has mentioned is to keep the record of the performance data on each GA release, our benchmark on the test will be based on the data of the last shipped release.

**Comment by ssh24** [comment]
We now have a full suite of Performance Tests working. Closing this as done

/close
