### ISSUE TITLE
Appsody Kitura project status goes from Starting -> Stopped -> Running

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind#1247]
**Codewind version:** 0.6.0
**OS:** macOS Catalina

When I create an Appsody Ki project status goes from [Starting] to [Stopped], then after quite a while, it goes to [Running].

Here's the PFE log
[pfe.txt](https://github.com/eclipse/codewind/files/3879930/pfe.txt)

**Comment by makandre** [comment]
This is related to #1236 right?

See https://github.com/eclipse/codewind/issues/1236#issuecomment-557380449

**Comment by makandre** [comment]
This happens for any project that takes a long time to start, e.g. the microprofile stack will always exhibit this behaviour.

**Comment by makandre** [comment]
This is going to be addressed by https://github.com/eclipse/codewind/issues/1246

**Comment by sghung** [comment]
Closing on behalf of John, as this was fixed on #1246.
