### ISSUE TITLE
A broken link in 0.6.0 docs

### ISSUE THREAD

**Issue by sghung** [eclipse/codewind#1249]
Running the `build.sh` gives two errors:

The first error can be ignored, since it is a VScode specific URL for launching the app. We may want Travis to exclude that so we don't have errors showing up when calling `buid.sh`

The second error is the new page, referencing a URL that doesn't exist for open API.

URL        `vscode:extension/IBM.codewind'
Name       `this link'
Parent URL http://localhost:8765/codewind/mdt-vsc-getting-started.html, line 615, col 36
Base       http://localhost:8765/codewind/
Real URL   vscode:extension/IBM.codewind
Info       The URL is outside of the domain filter, checked only
           syntax.
Result     Error: URL is unrecognized or has invalid syntax

URL        `codewind-openapi-vscode.html#generating-and-building-client-and-server-stubs-by-using-the-openapi-tools'
Name       `manual steps to expose the API endpoints'
Parent URL http://localhost:8765/codewind/news06.html, line 236, col 363
Base       http://localhost:8765/codewind/
Real URL   http://localhost:8765/codewind/codewind-openapi-vscode.html#generating-and-building-client-and-server-stubs-by-using-the-openapi-tools
Check time 4.424 seconds
Size       196B
Result     Error: 404 Not Found

**Comment by sishida** [comment]
@sghung I see that we have merged my PR for updating the master branch and merged your PR for updating the 0.6.0 branch. I am closing this issue. :)
