### ISSUE TITLE
Add mechanism in IDEs to set log level for PFE

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#1251]
Currently, if a user needs to change the default log level (such as trace) in Codewind/PFE, they have to exec into the container and run:
```
> curl --header "Content-Type: application/json" --request PUT --data '{"level":"<level>"}' http://127.0.0.1:10000/api/v1/logging
```

This is unintuitive for the user (and also undocumented!). There needs to be a better way for users to configure the log level in PFE, especially to assist with problem determination.

Would it be possible to add something to the IDEs to allow the user to configure the log level for a Codewind instance?

**Comment by johnmcollier** [comment]
Adding just the IDE tags for now since I don't think this will require a change on the Portal side.

**Comment by eharris369** [comment]
Same as: https://github.com/eclipse/codewind-eclipse/issues/73

**Comment by johnmcollier** [comment]
Reopening as we still need this for VS Code and Theia

**Comment by tetchel** [comment]
curious where you'd want this

**Comment by tetchel** [comment]
it would be added as a command with no 'regular' UI in VS Code

**Comment by johnmcollier** [comment]
What about also when you right click on the connection?

**Comment by tetchel** [comment]
I don't really want to clutter the UI with something so niche

**Comment by johnmcollier** [comment]
I understand the point about not wanting to clutter things up, but is enabling verbose logging niche though?

**Comment by tetchel** [comment]
It should be, if it's not, shouldn't we make the default logging more useful?

**Comment by johnmcollier** [comment]
That’s fair. I’m fine with having just a simple command then.

**Comment by eharris369** [comment]
In Eclipse I will add a preference to enable support features.  If the preference is enabled then the menus will include setting PFE log level items.

**Comment by jgwest** [comment]
Now the cwctl is (more) easily accessible by the user -- since we copy it under `~/.codewind` -- an alternative to adding this mechanism to the IDE would be to add a `cwctl logging` command. 

IIRC when we initially discussed adding this mechanism to the IDE, cwctl was not (yet) something we were making it easy for the user to access, whereas now it is in a fixed location.

**Comment by jgwest** [comment]
Howard has added a `cwctl loglevels` command that does the above:  https://github.com/eclipse/codewind-installer/pull/336

**Comment by tetchel** [comment]
How's `Set Codewind Server Logging Level` as a command name (to make clear i'm not talking about the plugin's logging level)

**Comment by johnmcollier** [comment]
That works for me.

**Comment by tetchel** [comment]
done in vscode

**Comment by eharris369** [comment]
Done in Eclipse: https://github.com/eclipse/codewind-eclipse/pull/537.  You must first go in to the preferences for Codewind to enable support features and then the menu item will appear on the connection.

**Comment by malincoln** [comment]
@johnmcollier  pls verify and close. Thanks

**Comment by sishida** [comment]
Discussed this issue with @beccabau and @tetchel. We can document this issue in https://www.eclipse.org/codewind/troubleshooting.html.

**Comment by sishida** [comment]
Documentation is complete with this issue (https://github.com/eclipse/codewind/issues/2227) and this PR (https://github.com/eclipse/codewind-docs/pull/408).
