### ISSUE TITLE
Appsody apps stuck in starting state need to be added back into the troubleshooting section

### ISSUE THREAD

**Issue by sghung** [eclipse/codewind#1256]
In this commit: https://github.com/eclipse/codewind-docs/commit/568829295263a3e17f182df03d40197b07ab7d03#diff-c4a13baec8ab45c0c64c7e646b183acd it shows the section:

## Node.js and Swift templates remain in the starting state

This section needs to be reverted back to the commit above because the fix to have it going to the stopped state has been reverted in codewind via: https://github.com/eclipse/codewind/pull/1255

**Comment by sghung** [comment]
Keeping open until the fix is added to master too

**Comment by j-c-berger** [comment]
@sishida , please assign this issue to me now that it is complete
