### ISSUE TITLE
SVT: Codewind stop and start does not refresh projects list.

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#1257]
**Codewind version:** 0.6
**OS:** WIndows

**Che version:**
**IDE extension version:** 0.6
**IDE version:** VSCode 1.40.1
**Kubernetes cluster:**

**Description:**

On Windows Codewind intermittently does not refresh project list after Codewind restarts from stop.  User has to manually refresh to get the projects in the list. 

**Steps to reproduce:**

1. Install Codewind 0.6 release.
2. Stop and Start codewind.
3. After restart, project list is not refreshed.
 

**Workaround:** 
User has to manually "Refresh" Codewind to get the projects in the Codewind explorer view.

**Comment by sujeilyfonseca** [comment]
**Codewind version:** 0.6.0
**OS:** VM with Windows 10

**IDE extension version:** 0.6.0
**IDE version:** VS Code 1.40.1

I also had the same problem using my Windows VM. I could reproduce it consistently at first, but then I couldn't reproduce it. Therefore, I agree that this problem could be intermittent.

**Comment by jopit** [comment]
I was able to reproduce this with VSCode on macOS. Here's the relevant part of the vscode log file

[vscode-log.txt](https://github.com/eclipse/codewind/files/3881803/vscode-log.txt)

To me, it looks like PFE opened it's websocket before the REST API routes were up, and so when vscode called the API to get the list of projects, it got a 404 error.  If so, I think the proper fix is in PFE, but maybe there's a simpler workaround in vscode if we want to fix this for 0.6.0.  I'd like to see what @tetchel thinks.

**Comment by tetchel** [comment]
As part of the remote connection work (in master, not 0.6) I made a change to wait for codewind to be 'ready' before trying to connect the socket. So that should resolve this timing issue.

**Comment by tetchel** [comment]
i see how this could happen, i don't see why we never saw this earlier 🙃

**Comment by tetchel** [comment]
it happens if the socket connects before pfe is ready. the fix is to also populate the projects list after pfe is ready. I can put it into 0.6

**Comment by jopit** [comment]
If it's a simple fix, I think it should go into 0.6.0

**Comment by jagraj** [comment]
I agree, if it is simple fix we should deliver into 0.6 release. This will definitely improve user experience  and we see this issue on both Windows and Mac.

**Comment by jopit** [comment]
We discussed this on the release call, we won't hold up 0.6.0 for it, but it's a candidate for a potential ifix.

**Comment by tetchel** [comment]
https://github.com/eclipse/codewind-vscode/pull/308

**Comment by jopit** [comment]
Reopening so it can be verified.

**Comment by jagraj** [comment]
Looks good to me. Thanks for the fix. Closing this now.
