### ISSUE TITLE
SVT:[Windows]:CLI failed to uninstall codewind when "performance" container failed to stop

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#1259]
**Codewind version:** 0.6.0
**OS:** Windows

**Che version:**
**IDE extension version:** 0.6.0
**IDE version:** Eclipse 2019-09
**Kubernetes cluster:**

**Description:**
CLI installer is in bad state, I tried to stop codewind and it failed to stop "performance" container and the status says in  IDE "codewind stopped" and I tried to "Uninstall" and it failed to uninstall with this message (```There was a problem trying to uninstall Codewind: 2019/11/25 09:43:53 REMOVE_IMAGE_ERROR[105]: exit status 1. Failed to remove image - Please make sure all containers are stopped```)

This state should reflect to the user "partial start" and provide option to the user "stop" codewind even then it is failed to stop we should provide option to the user do you want to do "Force stop codewind" 

This should give option to the user force stop and they can uninstall codewind.  

We should better error handling in CLI, if the installer is failed to start or stop codewind for any docker issues. 

**Steps to reproduce:**
1. After stopping codewind it stopped PFE container but not performance container.
2. In IDE status says Codewind "stopped" and there is option to "Uninstall" but that does not work cause performance container still running but user does not have option to stop option to "Stop" or "Force stop" 

Here are the logs and screenshot of this problem.

```
docker ps
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS              PORTS                      NAMES
3b7532a3007b        codewind-performance-amd64:0.6.0   "docker-entrypoint.s…"   2 days ago          Up 2 days           127.0.0.1:9095->9095/tcp   codewind-performance
```

![image](https://user-images.githubusercontent.com/713849/69550734-883e7a00-0f69-11ea-8d8d-fd4ce79b8830.png)

[.log](https://github.com/eclipse/codewind/files/3887204/default.log)

**Workaround:**

**Comment by tobespc** [comment]
how are you stopping codewind ?

**Comment by tetchel** [comment]
I see stopping fail one time in a few, due to the codewind_network still being in use. running the stop command again always resolves it. Maybe the stop command could have some retry logic built in

**Comment by jagraj** [comment]
@tobespc 
Stopping codewind from one of the option from eclipse menu item.

**Comment by liamchampton** [comment]
@tetchel i have also previously had that issue and that has occurred because of this change https://github.com/eclipse/codewind-installer/pull/172. @jagraj did it fail to stop any other containers or just the performance container? Were there any containers in an exited state? - seen by doing `docker ps -a`

**Comment by jagraj** [comment]
To continue my test effort yesterday, I did `docker system prune -a` to install latest 0.6 release builds.
 I had only this container up and running.

```
docker ps
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS              PORTS                      NAMES
3b7532a3007b        codewind-performance-amd64:0.6.0   "docker-entrypoint.s…"   2 days ago          Up 2 days           127.0.0.1:9095->9095/tcp   codewind-performance
```

**Comment by liamchampton** [comment]
@jagraj please can this be verified/closed? I don't think this is going to be an issue anymore since we are using `docker-compose down` in 0.8.0

**Comment by tobespc** [comment]
moving to verify as per comment above

**Comment by malincoln** [comment]
@jagraj pls verify and close.  Thanks

**Comment by jagraj** [comment]
I no longer see this problem in 0.8.0. Closing this issue.
