### ISSUE TITLE
SVT: [Che] Missing ODO Template Source

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#1262]
**Codewind version:** 0.6.0 
**OS:** Red Hat Enterprise Linux 7 (64 bit)

**Che version:** 7.3.1
**Openshift version:** 
```
oc v3.11.0+62803d0-1
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://sfonseca-okd-codewind.rtp.raleigh.ibm.com:8443
openshift v3.11.0+82a43f6-231
kubernetes v1.11.0+d4cacc0
```
**Kubernetes cluster:** OKD/Openshift

**Description:** Missing ODO Template Source

<img width="1675" alt="Screen Shot 2019-11-25 at 11 40 45 AM" src="https://user-images.githubusercontent.com/49531960/69560642-0dca2600-0f7a-11ea-90c8-f6cc3ac87603.png">

**Logs:**
[codewind.txt](https://github.com/eclipse/codewind/files/3887767/codewind.txt)
[codewind-workspacecpmq5c3xksxr4p1e-f47866cb6-nfnhw.txt](https://github.com/eclipse/codewind/files/3887769/codewind-workspacecpmq5c3xksxr4p1e-f47866cb6-nfnhw.txt)

@jagraj

**Comment by jagraj** [comment]
I also see same problem on my cluster where ODO projects source missing. 
![Screen Shot 2019-11-25 at 11 48 42 AM](https://user-images.githubusercontent.com/713849/69561019-b082a480-0f7a-11ea-8051-9b156dc145a4.png)

**Comment by elsony** [comment]
@GeekArthur Please take a look.

**Comment by GeekArthur** [comment]
Sure
/assign

**Comment by GeekArthur** [comment]
@sujeilyfonseca Can you check if your have odo extension in your PFE container, it's located at /codewind-workspace/.extensions/codewind-odo-extension inside PFE container. Basically the templates are fetched via this function `getRepositories`, I wanna check the issue is from caller or callee.

**Comment by lentheivendra** [comment]
Just tried a fresh install of a 0.6.0 workspace on my OKD cluster v3.11.0+0cbc58b with Che 7.3.1 (Nov 13 install), and can see ODO in the Template Source Manager, as well the ODO templates when creating new projects

**Comment by jagraj** [comment]
I just verified on my cluster, the ODO extension is missing from the pfe.

```
drwxr-sr-x.  4 root 2002 4096 Nov 21 20:53 codewind-appsody-extension
drwxrwsr-x.  3 root 2002 4096 Nov 25 16:47 .
drwxrwsr-x. 12 root 2002 4096 Nov 25 17:05 ..
```

**Comment by sujeilyfonseca** [comment]
I don't see the ODO extension inside PFE container:
```
[root@codewind-workspacecpmq5c3xksxr4p1e-f47866cb6-nfnhw .extensions]# ls -ltr
total 0
drwxr-xr-x. 4 root root 231 Nov 21 20:53 codewind-appsody-extension
```

**Comment by GeekArthur** [comment]
@jagraj @sujeilyfonseca That's why, `getRepositories` can't be called without odo extension, then no templates can be displayed from IDE, it works for Len, let me give a try using the latest 0.6.0

**Comment by jagraj** [comment]
Who ever is trying to reproduce this problem, please use brand new volume not with leftover files or workspace contents.

**Comment by lentheivendra** [comment]
Ya I ensured I cleaned up all PVs and PVCs before installing a new 0.6.0 worskspace, per usual. Not sure if my Che 7.3.1 from Nov13 could be a factor in it working for me? I'm also on vanilla OKD.

**Comment by jagraj** [comment]
My Che installed 4 days back and created workspace just now.

```
che-7d7654485b-rchlr                                              1/1       Running   0          4d
che-operator-58b5f759bd-wdfxq                                     1/1       Running   0          4d
codewind-performance-workspace5v6ccatr2o8vmy9o-6c7bcfd97d-rxp5f   1/1       Running   0          33m
codewind-workspace5v6ccatr2o8vmy9o-6b79f64f85-7smc9               1/1       Running   0          33m
cw-gocw06svt-ad339200-0fa5-11ea-99c6-68fff8b789-q2vgj             1/1       Running   0          14m
cw-lagomcw06svt-b8ae42b0-0fa5-11ea-99c6-56576b79f7-sjckp          1/1       Running   0          10m
cw-nodejscw06svt-c83728a0-0fa5-11ea-99c6-99bc7d978-mgxrk          1/1       Running   0          11m
cw-olcw06svt-d94946a0-0fa5-11ea-99c6-5768b68c68-ll7cq             1/1       Running   2          11m
devfile-registry-55bccb8bcc-d8mv7                                 1/1       Running   0          4d
keycloak-7fc4f5cd48-pzhmk                                         1/1       Running   0          4d
plugin-registry-648b6f8647-wgzqz                                  1/1       Running   0          4d
postgres-7679d7d9b9-xhvqb                                         1/1       Running   0          4d
tiller-deploy-57bcbcbbc8-kfrr7                                    1/1       Running   0          4d
workspace5v6ccatr2o8vmy9o.che-jwtproxy-6f7cddd887-jcsg2           1/1       Running   0          33m
workspace5v6ccatr2o8vmy9o.che-workspace-pod-fcddd4745-75t2m       3/3       Running   0          33m
```

**Comment by ssh24** [comment]
FWIW, I was not able to reproduce this as well with a new workspace created on 0.6.0:

0.6.0 SHA: `sha256:373be2c6269ed6a716c5aab89a1d3105139ac5f76f96d7ea8922d4e582d7d7d3`
![Screen Shot 2019-11-25 at 12 21 58 PM](https://user-images.githubusercontent.com/15173354/69563017-54ba1a80-0f7e-11ea-8c90-7fcd9b634dc0.png)

**Comment by GeekArthur** [comment]
The issue shouldn't related with Che version since odo extension installer is from PFE. I just give a try and it works for me, I am using the latest 0.6.0 image which is SHA is `373be2c6269ed6a716c5aab89a1d3105139ac5f76f96d7ea8922d4e582d7d7d3`. FVT folks, can you guys verify if the PFE image SHA is good by running `oc get po --selector=app=codewind-pfe -o jsonpath='{.items[*].status.containerStatuses[*].imageID}'`?


![Screen Shot 2019-11-25 at 12 21 51 PM](https://user-images.githubusercontent.com/15131537/69563000-4ec43980-0f7e-11ea-9486-7ca630b09d68.png)

**Comment by lentheivendra** [comment]
@jagraj @sujeilyfonseca looking at your `.extensions/` dir, wondering why the appsody one is from Nov 21, but worksapace current `.` directories are Nov 25

**Comment by jagraj** [comment]
```
oc get po --selector=app=codewind-pfe -o jsonpath='{.items[*].status.containerStatuses[*].imageID}'

docker-pullable://docker.io/eclipse/codewind-pfe-amd64@sha256:d38b3bd21ab893d85876c92f22040732c41d382915929983ebf0c9adb58e5ac3
```

**Comment by GeekArthur** [comment]
@jagraj Your PFE image is not the latest 0.6.0, latest 0.6.0 image is : `373be2c6269ed6a716c5aab89a1d3105139ac5f76f96d7ea8922d4e582d7d7d3`: https://hub.docker.com/layers/eclipse/codewind-pfe-amd64/0.6/images/sha256-373be2c6269ed6a716c5aab89a1d3105139ac5f76f96d7ea8922d4e582d7d7d3

**Comment by sujeilyfonseca** [comment]
I created a new workspace with another OKD cluster, and I can see the ODO templates:

<img width="1678" alt="Screen Shot 2019-11-25 at 12 41 21 PM" src="https://user-images.githubusercontent.com/49531960/69564372-e9be1300-0f80-11ea-878f-80650459f501.png">

```
[root@sfonseca-okd-glusterfs che-operator]# oc get pods
NAME                                                              READY     STATUS    RESTARTS   AGE
che-75f5c887-s45mn                                                1/1       Running   0          9m
che-operator-5f9d64466-t6g8t                                      1/1       Running   0          14m
codewind-performance-workspaceunhysmlpzuyhnfnv-79f49678c6-zfz75   1/1       Running   0          2m
codewind-workspaceunhysmlpzuyhnfnv-7fcffc95-qd5gv                 1/1       Running   0          2m
devfile-registry-54974f5486-svdxf                                 1/1       Running   0          9m
keycloak-85bfbc89c5-fgl5z                                         1/1       Running   0          12m
plugin-registry-5f8cddb958-vhlgp                                  1/1       Running   0          9m
postgres-5dd6df5447-b8jsv                                         1/1       Running   0          14m
tiller-deploy-57bcbcbbc8-4pvxb                                    1/1       Running   0          1m
workspaceunhysmlpzuyhnfnv.che-jwtproxy-f9bd6b9d9-6gqpf            1/1       Running   0          2m
workspaceunhysmlpzuyhnfnv.che-workspace-pod-75b95b4f44-b5hxz      3/3       Running   0          2m
```

However, I wonder why they are not present in my other cluster. I only deleted my workspace, where I previously had ODO templates, and deployed a new one. After that, I no longer see the ODO templates.

```
[root@sfonseca-okd-codewind ~]# oc get pods
NAME                                                              READY     STATUS    RESTARTS   AGE
che-86d5489c57-kzbvn                                              1/1       Running   0          9h
che-operator-58b5f759bd-7b47m                                     1/1       Running   0          9h
codewind-performance-workspacecpmq5c3xksxr4p1e-7bbcf6b498-fw66n   1/1       Running   0          1h
codewind-workspacecpmq5c3xksxr4p1e-f47866cb6-nfnhw                1/1       Running   0          1h
cw-cwdefaultnode-0b16db20-0fa1-11ea-8aa9-b75cb45b4-7czkh          1/1       Running   0          1h
devfile-registry-54974f5486-2q7r2                                 1/1       Running   0          9h
keycloak-7b77cf9d9-bqh4f                                          1/1       Running   0          9h
plugin-registry-5f8cddb958-54q7z                                  1/1       Running   0          9h
postgres-6dbb68c6f5-xmpp8                                         1/1       Running   0          9h
tiller-deploy-57bcbcbbc8-q9cj7                                    1/1       Running   1          5h
workspacecpmq5c3xksxr4p1e.che-jwtproxy-945fc545d-qj6vv            1/1       Running   0          1h
workspacecpmq5c3xksxr4p1e.che-workspace-pod-6557bfd6dd-4dbgw      3/3       Running   0          1h
```

**Comment by GeekArthur** [comment]
@lentheivendra That's good point.
@sujeilyfonseca I think this could be related with volume issue on your cluster, like volume attached to /codewind-workspace/.extensions is old or new files can't not write to the volume. So seems like both the latest appsody extension and latest odo extension can't install to your cluster's volume or write to your cluster's volume, that's why you have `Nov 21` appsody extension not the `Nov 25`. Once the cluster's volume issue has been resolved by itself, both latest appsody extension and latest odo extension can be installed successfully.

**Comment by jagraj** [comment]
@GeekArthur 
I created brand new workspace and that should have pulled new image right.?
We don't have pull policy Always.?

**Comment by jagraj** [comment]
I am running with GlusterFS as storage on this cluster. 
@sujeilyfonseca 
Can you confirm your storage is GlusterFS or NFS.?

**Comment by GeekArthur** [comment]
@jagraj Yes, it should. If you use this devfile: https://raw.githubusercontent.com/eclipse/codewind-che-plugin/master/devfiles/0.6.0/devfile.yaml, it should pull the latest 0.6.0

**Comment by johnmcollier** [comment]
@jagraj We do set it to `Always`: https://github.com/eclipse/codewind-che-plugin/blob/5b65744336b4612c07529fdc892593f6a2087e35/codewind-che-sidecar/deploy-pfe/pkg/constants/defaults.go#L28

**Comment by jagraj** [comment]
This is confusing to me..., How this can be possible.?

```
kubectl describe pod codewind-workspace5v6ccatr2o8vmy9o-6b79f64f85-7smc9

Name:               codewind-workspace5v6ccatr2o8vmy9o-6b79f64f85-7smc9
Namespace:          che
Priority:           0
PriorityClassName:  <none>
Node:               devexokdw2b/9.42.9.42
Start Time:         Mon, 25 Nov 2019 11:47:00 -0500
Labels:             app=codewind-pfe
                    codewindWorkspace=workspace5v6ccatr2o8vmy9o
                    pod-template-hash=2635920941
Annotations:        openshift.io/scc=privileged
Status:             Running
IP:                 10.129.0.72
Controlled By:      ReplicaSet/codewind-workspace5v6ccatr2o8vmy9o-6b79f64f85
Containers:
  codewind:
    Container ID:   docker://24aa1730638fac37c9d9822a6acfb8579eda7c37b628402751c5262085150924
    Image:          eclipse/codewind-pfe-amd64:0.6
    Image ID:       docker-pullable://docker.io/eclipse/codewind-pfe-amd64@sha256:d38b3bd21ab893d85876c92f22040732c41d382915929983ebf0c9adb58e5ac3

	
	

docker images | grep codewind-pfe

docker.io/eclipse/codewind-pfe-amd64                                                           0.6                 85e3c860e735        2 hours ago         730 MB
docker.io/eclipse/codewind-pfe-amd64                                                           <none>              731b85bead58        4 days ago          744 MB
docker.io/eclipse/codewind-pfe-amd64                                                           <none>              8395bb4f4881        5 days ago          744 MB
docker.io/eclipse/codewind-pfe-amd64                                                           <none>              032e5e432da4        6 days ago          744 MB
docker.io/eclipse/codewind-pfe-amd64                                                           latest              c641dd7f23b7        2 weeks ago         781 MB
docker.io/eclipse/codewind-pfe-amd64                                                           <none>              8390e419db81        2 weeks ago         781 MB
docker.io/eclipse/codewind-pfe-amd64                                                           0.5                 2d69386eb07a        4 weeks ago         709 MB
docker.io/eclipse/codewind-pfe-amd64                                                           <none>              6a5c9e28c9d8        6 weeks ago         717 MB
docker.io/eclipse/codewind-pfe-amd64                                                           <none>              c7f0a8e50ee1        7 weeks ago         717 MB
docker.io/eclipse/codewind-pfe-amd64                                                           0.4                 224a9df6df08        2 months ago        706 MB
docker.io/eclipse/codewind-pfe-amd64                                                           <none>              07ac00c09713        2 months ago        702 MB
docker.io/eclipse/codewind-pfe-amd64                                                           <none>              8a28ceb70762        2 months ago        702 MB
docker.io/eclipse/codewind-pfe-amd64                                                           0.3                 85454babe8c5        2 months ago        696 MB
docker.io/eclipse/codewind-pfe-amd64                                                           0.3.1               82bd1488701d        2 months ago        696 MB
docker.io/eclipse/codewind-pfe-amd64                                                           <none>              f220ff2321c7        3 months ago        696 MB
```

**Comment by sujeilyfonseca** [comment]
@jagraj, my OKD cluster with the problem has NFS storage.

The second cluster I mentioned has Gluster FS.

In both scenarios, I used:
https://raw.githubusercontent.com/eclipse/codewind-che-plugin/master/devfiles/0.6.0/devfile.yaml

**Comment by ssh24** [comment]
@jagraj Those docker images are from local?

**Comment by jagraj** [comment]
@ssh24 
No, they are from OKD cluster. 

I am using this devfile.
https://raw.githubusercontent.com/eclipse/codewind-che-plugin/master/devfiles/0.6.0/devfile.yaml

**Comment by GeekArthur** [comment]
@jagraj See your image pull timestamp: `Mon, 25 Nov 2019 11:47:00 -0500`, but the latest one is one hour ago: https://hub.docker.com/layers/eclipse/codewind-pfe-amd64/0.6/images/sha256-373be2c6269ed6a716c5aab89a1d3105139ac5f76f96d7ea8922d4e582d7d7d3. So you pull your image a little bit early than the latest one, that's why you don't have the latest PFE 0.6.0 image.

**Comment by GeekArthur** [comment]
This is related with SVT cluster’s volume (NFS/GlusterFS), you can either investigate the volume setup or that could be a  intermittent environment issue (eg. cluster or network), remote stop ship tag
/remove-priority stopstop

**Comment by jgwest** [comment]
@GeekArthur: Those labels are not set on the issue: priority/stopstop<details>


In response to [this](https://github.com/eclipse/codewind/issues/1262#issuecomment-558290970):
> remove-priority stopstop
</details>

**Comment by jagraj** [comment]
I just deleted workspace which was cerated 2 hrs back and created new one again and started seeing ODO template source part of the repo list. Is this fixed in latest codewind image.?

![Screen Shot 2019-11-25 at 1 54 28 PM](https://user-images.githubusercontent.com/713849/69569191-1ecf6300-0f8b-11ea-9e77-7df58305f2d8.png)


```
kubectl describe pod codewind-workspaceqtude74fk834jtwr-7cb4d7ccc5-t8qft
Name:               codewind-workspaceqtude74fk834jtwr-7cb4d7ccc5-t8qft
Namespace:          che
Priority:           0
PriorityClassName:  <none>
Node:               devexokdw2c/9.42.9.239
Start Time:         Mon, 25 Nov 2019 13:43:27 -0500
Labels:             app=codewind-pfe
                    codewindWorkspace=workspaceqtude74fk834jtwr
                    pod-template-hash=3760837771
Annotations:        openshift.io/scc=privileged
Status:             Running
IP:                 10.130.0.118
Controlled By:      ReplicaSet/codewind-workspaceqtude74fk834jtwr-7cb4d7ccc5
Containers:
  codewind:
    Container ID:   docker://b09c5df206cf5077fdd32b9a565e46720038de4c44fad25eb3a111af402ddc0d
    Image:          eclipse/codewind-pfe-amd64:0.6
    Image ID:       docker-pullable://docker.io/eclipse/codewind-pfe-amd64@sha256:373be2c6269ed6a716c5aab89a1d3105139ac5f76f96d7ea8922d4e582d7d7d3
    Port:           9191/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Mon, 25 Nov 2019 13:43:54 -0500
    Ready:          True

docker images | grep codewind-pfe
docker.io/eclipse/codewind-pfe-amd64                                                          0.6                 f0a05f836fe6        About an hour ago   744 MB
docker.io/eclipse/codewind-pfe-amd64                                                          <none>              731b85bead58        5 days ago          744 MB
docker.io/eclipse/codewind-pfe-amd64                                                          <none>              8395bb4f4881        5 days ago          744 MB
docker.io/eclipse/codewind-pfe-amd64                                                          <none>              032e5e432da4        6 days ago          744 MB
docker.io/eclipse/codewind-pfe-amd64                                                          <none>              c5d2896bcd68        7 days ago          744 MB
docker.io/eclipse/codewind-pfe-amd64                                                          <none>              ee0a930bf4fc        9 days ago          744 MB
docker.io/eclipse/codewind-pfe-amd64                                                          <none>              24efb4371340        2 weeks ago         744 MB
docker.io/eclipse/codewind-pfe-amd64                                                          0.4                 8a28ceb70762        2 months ago        702 MB
docker.io/eclipse/codewind-pfe-amd64                                                          0.3.1               85454babe8c5        2 months ago        696 MB
docker.io/eclipse/codewind-pfe-amd64                                                          latest              f220ff2321c7        3 months ago        696 MB

**Comment by GeekArthur** [comment]
@jagraj We don't have specific fix for this templates source since I don't think we hit this issue before. But in order to avoid side effects of other PRs, we just use the latest image to reproduce, if you can see the templates, you volume on the cluster is resolved as well.

**Comment by jagraj** [comment]
Well, I got into issue with GlusterFS and Sujeily got into issue with NFS storage. When I delete and create new workspace on my GlusterFS cluster, I get brand new volume and volume claim. I doubt this is storage issue. Some how this is fixed with the latest codewind image.

**Comment by GeekArthur** [comment]
@sujeilyfonseca Using the latest image resolves the volume issue, can you verify this? If it's good please close this issue.

**Comment by GeekArthur** [comment]
Also the improvement of this issue is we can add more logs into extension installer code on Portal side so that next time if we hit the same issue, we can easily find where is the issue from (either from volume or extension installer).

**Comment by elsony** [comment]
Marking this to verify to verify with latest image.

**Comment by sujeilyfonseca** [comment]
Thank you all for verifying this issue! I agree with your suggestion, @GeekArthur.
I can no longer reproduce this problem with the latest images, so I will proceed to close this GitHub problem.
