### ISSUE TITLE
Provide users a way to uninstall and upgrade Hybrid Codewind

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#1263]
After a `cwctl install remote`, how is a user meant to uninstall? And, more importantly, what is the user story for upgrading to eg. 0.8 when the time comes?

We need a way to uninstall and reinstall/upgrade without losing all our project metadata (and template sources etc).

**Comment by tetchel** [comment]
cc @markcor11

**Comment by johnmcollier** [comment]
Codewind on Che handles upgrades by recreating all of the Codewind resources **except** for the Codewind persistent volumes. When the upgraded Codewind is deployed, it attaches onto that existing volume and reuses it. `Cwctl` could probably do the same.

**Note:** This approach will only work if the PersistentVolumeClaim spec for Codewind doesn't change from release to release.

**Comment by tobespc** [comment]
so project files shouldn't need to persist across upgrades as in a hybrid scenario, its only the building and running that are performed remotely.  Master source is still on the users machine.  For the other artifacts like custom template repositories etc, the upgrade should behave (from a users pov) exactly as it does for upgrading a locally installed codewind and those artrifacts persist.  Will scope out a design for this and add it to the docs for review

**Comment by markcor11** [comment]
We do need to be able to un-install PFE,  Gatekeeper, secrets, configmaps and other Kube resources that were created during initial deployment.  Keycloak is a bit tricky since that may be shared by other remote installations in the same or other namespaces.

**Comment by tetchel** [comment]
> so project files shouldn't need to persist across upgrades as in a hybrid scenario, its only the building and running that are performed remotely

sorry, i meant inf files, as in I shouldn't have to rebind all my projects whenever I upgrade

**Comment by tobespc** [comment]
so there shouldn't be the concept of upgrade for projects anymore, an upgrade will just be updating the images for pfe etc.   As long as the volume is not blown away, all the artifacts will persist

**Comment by tetchel** [comment]
https://github.com/eclipse/codewind/issues/1263
