### ISSUE TITLE
Can't create appsody projects - possibly related to the change to pull files from git 

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#127]
I can't create appsody projects after updating to the latest codewind. I am getting this error in the log file:

[Error] The current directory is not a valid appsody project. Run appsody init <stack> to create one. Run appsody list to see the available stacks.

Possibly related to https://github.com/eclipse/codewind/commit/d9d85309eb47a59697ed8e8fce2e8600c096e9e4#diff-8a0ecce0840fc29db0bdb8acdf825a6c using mv which does not move hidden files.

**Comment by makandre** [comment]
This affects all project types but to a lesser degree. For example, you can still create node projects, but if you look inside the project, the template's .dockerignore file is missing.

In appsody's case, .appsody-config.yaml is needed for project creation

**Comment by makandre** [comment]
@hhellyer

**Comment by tobespc** [comment]
this is now fixed
