### ISSUE TITLE
deleted projects reappearing after docker prune volumes (0.6.0)

### ISSUE THREAD

**Issue by AndyRWatson** [eclipse/codewind#1281]
**Codewind version:**. 0.6.0
**OS:**. MacOS 10.15

**Che version:**
**IDE extension version:**. 0.6.0
**IDE version:**.  VSCode 1.39.1
**Kubernetes cluster:**.  N/A

**Description:**

existing deleted codewind projects reappear in codewind after issuing a docker system prune -a

Whilst testing the new documentation and twitter comment around the impact of performing a docker system prune -a --volumes with 0.6.0 I noticed a migrated project that I had subsequently deleted using 0.6.0 reappeared and rebuilt within codewind.     I guess that after the docker system prune and subsequent re-download of images we perform the migration again as the codewind-workspace still existed on my filesystem.    This was a little frustrating as I'd lost my recent projects created in 0.6.0 (as documented) but now had a project I'd actually deleted.

ideally I would have seen the same list of projects I had before the prune,  or if I lose projects I should lose all of them, including migrated ones ?   The experience is not as I'd have expected as a user.  Should we consider only ever running migration once ?

**Steps to reproduce:**

- create project abc  in codewind 0.5 (codewind-workspace)
- upgrade to codewind 0.6 (and migrate projects)
- delete project abc in codewind 0.6 (though not directory)
- create new project in 0.6
- stop codewind
- docker system prune -a --volumes
- restart codewind

**Workaround:**

**Comment by tetchel** [comment]
yes, the migration will run each time you install and then start 0.6. to be clear, it will not run when upgrading from 0.6 eg to 0.6.1. 

_maybe_ we could store in the IDE that the migration has already run, but it seems a bit late since 0.6 is already out there. we didn't consider the "reinstall" scenario you've outlined here.

**Comment by tetchel** [comment]
you can also work around this by removing `~/codewind-workspace` then it will not have any old projects to migrate

**Comment by jopit** [comment]
Another solution would be for the cwctl to remove the project .inf files from the workspace for projects that migrated successfully.

**Comment by tobespc** [comment]
so should we be fixing this for 0.6.1 or 0.7.0 ?

**Comment by stalleyj** [comment]
I've added a deletion of the inf file https://github.com/eclipse/codewind-installer/pull/315

**Comment by malincoln** [comment]
@AndyRWatson pls verify and close if resolved.  Thanks
