### ISSUE TITLE
Maximum call stack size exceeded in PFE logs on Codewind

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#1284]
I'm seeing the following in the PFE logs (latest images) when running on Che just after a docker build and push finishes for Generic docker projects:

```
[26/11/19 22:11:31 FileWatcher.js] [ERROR] RangeError: Maximum call stack size exceeded
    at Function.[Symbol.hasInstance] (<anonymous>)
    at Function.isBuffer (buffer.js:430:12)
    at hasBinary (/portal/node_modules/has-binary2/index.js:44:66)
    at hasBinary (/portal/node_modules/has-binary2/index.js:58:59)
    at hasBinary (/portal/node_modules/has-binary2/index.js:58:59)
    at hasBinary (/portal/node_modules/has-binary2/index.js:58:59)
    at hasBinary (/portal/node_modules/has-binary2/index.js:58:59)
    at hasBinary (/portal/node_modules/has-binary2/index.js:58:59)
    at hasBinary (/portal/node_modules/has-binary2/index.js:58:59)
    at hasBinary (/portal/node_modules/has-binary2/index.js:58:59)
```

It also appears to cause PFE to hang, as it prevented the app and build status from updating. Despite the build finishing and the app deploying, it was stuck in `Building - Creating Image`.

**Comment by johnmcollier** [comment]
PFE Logs: 
[pfe.txt](https://github.com/eclipse/codewind/files/3894270/pfe.txt)

**Comment by johnmcollier** [comment]
Looking through the logs, it seems each error is preceeded by a `projectStatusChanged` event

**Comment by johnmcollier** [comment]
We spoke about this on slack earlier in the week. From the logs the error's coming from FileWatcher.js in Portal and that it tends to usually follow a `projectStatusChanged` event from FW:
```
[32m[26/11/19 22:22:21 gogogtestdg] [INFO][39m Emitting event 
 message: projectStatusChanged
 data: {
  "projectID": "0c101fa0-109b-11ea-a51d-2145ab4d6b60",
  "appStatus": "starting",
  "appErrorStatus": " "
}
[91m[26/11/19 22:22:21 FileWatcher.js] [ERROR][39m RangeError: Maximum call stack size exceeded
    at Function.[Symbol.hasInstance] (<anonymous>)
    at Function.isBuffer (buffer.js:430:12)
    at hasBinary (/portal/node_modules/has-binary2/index.js:44:66)
    at hasBinary (/portal/node_modules/has-binary2/index.js:58:59)
    at hasBinary (/portal/node_modules/has-binary2/index.js:58:59)
    at hasBinary (/portal/node_modules/has-binary2/index.js:58:59)
    at hasBinary (/portal/node_modules/has-binary2/index.js:58:59)
    at hasBinary (/portal/node_modules/has-binary2/index.js:58:59)
    at hasBinary (/portal/node_modules/has-binary2/index.js:58:59)
    at hasBinary (/portal/node_modules/has-binary2/index.js:58:59)
```

From mine and @rajivnathan's investigation on our side, it looks like PFE is emitting the socket event fine, but something's going wrong on the Portal when it's processing it because it's never emitting the event to the IDEs (https://github.com/eclipse/codewind/blob/86a4b097a1010117aa6aee68cd63142bfddcd52f/src/pfe/portal/modules/FileWatcher.js#L501)

Adding the Portal label to this issue so that they can investigate further.

**Comment by makandre** [comment]
I see this locally as well, not just on Che

**Comment by jgwest** [comment]
Googling the error message strongly suggests that it's due to socket.io not allow you to `emit` JavaScript objects with cyclical references.

**Comment by makandre** [comment]
Should this be stop ship?

**Comment by elsony** [comment]
Do you always see this problem or it only happens under certain condition, e.g. after X number of projects running at the same time? And if the user see this, any workaround, e.g. increase memory?

**Comment by johnmcollier** [comment]
It's definitely intermittent, but it's quite disruptive when it happens, and the number of projects or memory available doesn't affect things (i.e. I've had it happen on a fresh install, on a new cluster with only one project).

**Comment by makandre** [comment]
Seeing this quite often.  I refresh the Codewind connection and that'll get the app/build state updated.

I also find number of projects is not the issue; I've seen it with less than 5 projects.

**Comment by johnmcollier** [comment]
I should also note that refreshing the page or Codewind connection will update the status, but it won't fix the error. The user would need to refresh **each time** a status update occurs.

**Comment by elsony** [comment]
Marking this as stopship for 0.7.0 given that we haven't seen this problem on 0.6.x and the problem happens fairly often.

**Comment by malincoln** [comment]
@tobespc pls review and assign.  Thanks

**Comment by tobespc** [comment]
assigning now

**Comment by jcockbain** [comment]
I've not been able to recreate so far on local.  

@makandre, is refreshing the connection referring to clicking 'refresh' on Codewind through VSCode? 

Does anyone have any more info on their environment when seeing this? Types of projects/how they've been modified etc...

**Comment by makandre** [comment]
Yes, refresh using the action on the connection in VSCode.   I typically create appsody projects and I see it happen quite regularly (just ran into it on remote Che and hybrid this morning; have not tested local recently)

**Comment by jcockbain** [comment]
Thanks, I'll have a look using remote next.

I agree it seems to be an issue with the object sent over the socket (has-binary-2 is a dependant of socket.io). That should just be a project object + a result/error string, investigating now if in some scenario we have a circular reference in there.

**Comment by johnmcollier** [comment]
I should also note: Test on OCP4 on Fyre if you can, I've seen it there the most

**Comment by makandre** [comment]
It looks like the error happens at https://github.com/eclipse/codewind/blob/master/src/pfe/portal/modules/FileWatcher.js#L501

I can see that `updatedProject` has a reference to a `WorkspaceFileLogstream` which itself has a reference the the project; hence the circular reference.

<img width="428" alt="image" src="https://user-images.githubusercontent.com/17596240/70357800-c7ac7680-1845-11ea-9c36-8552f7636328.png">

I usually open the logs on my projects so I think that's required to reproduce this problem

**Comment by jcockbain** [comment]
@makandre thanks!

That's the case for me too, I get the error as soon as I show logs for an appsody project.

I have the same project reference inside appsody.log of that project, looking now into where that is being created.

**Comment by jcockbain** [comment]
So, as far as I can see this can happen for any project type, when selecting `view logs`. The offending project object is being created at https://github.com/eclipse/codewind/blob/86a4b097a1010117aa6aee68cd63142bfddcd52f/src/pfe/portal/modules/LogStream.js#L65. 

Speaking to @hhellyer, the ui socket doesn't require the logstreams object. So, my plan is to remove this when we copy the project into the object that's sent over the socket.
