### ISSUE TITLE
Provide a way to uninstall Codewind remote

### ISSUE THREAD

**Issue by markcor11** [eclipse/codewind#1287]
**Codewind version:** Latest
**Kubernetes cluster:** . All 
**Description of the enhancement:**

Provide a way to uninstall a Hybrid remote deployment through cwctl 

**Proposed solution:** 

* Remove any installed Codewind resources that were provisioned during remote install (using a common workspace ID) 

* Provide status on any resources that can not (should not) be removed eg:  
 -- Cluster roles which might be shared with other deployments on the same cluster
 -- Keycloak which may be used by other deployments

**Comment by tetchel** [comment]
see john's comment for persisting pfe data. https://github.com/eclipse/codewind/issues/1263#issuecomment-558301584
