### ISSUE TITLE
File rename is not handled correctly by sync

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#1289]
**Codewind version:** master
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**

When a file is renamed, inside PFE the file with the new name is created along-side the file with the old name; the old file is not deleted.

**Steps to reproduce:**

1. rename a file in a project (I used VS code)
2. look inside the project inside `codewind-pfe:/codewind-workspace`, you'll see both old and new file there

**Workaround:**

**Comment by tobespc** [comment]
interesting, the logic we have in there should prevent this happening

**Comment by james-wallis** [comment]
Recreated using `cwctl` bind and then the VSCode extension to do the sync. Looks like when I delete files they're not being deleted either so I suspect its a problem with the deleting.
