### ISSUE TITLE
Empty project created

### ISSUE THREAD

**Issue by mdh69-github** [eclipse/codewind#129]
**Codewind version: 0.2.0**
**OS: Win10**

**Che version:**
**IDE extension version:**
**IDE version: VSCode 1.36.1**
**Kubernetes cluster: 1.14**

**Description of the bug:**
 The project creation does not import project template files

**Workaround:**

**Comment by rajivnathan** [comment]
@mdh69-github We're not aware of any current issues with project creation on Windows. Can you provide more details please? Are you seeing this problem with a specific project type or all projects? You mentioned Win10 but also a Kubernetes cluster version, can you add more details about your environment?

**Comment by jcockbain96** [comment]
@mdh69-github - is this still relevant? Do you more details about the environment if so?

**Comment by tobespc** [comment]
closing as no longer an issue
