### ISSUE TITLE
Add api for enabling/disabling injection of metrics

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#1290]
For 0.7.0 we have the ability to inject monitoring metrics into the application automatically.  However, a user may not want this so need to provide the option to enable/disable.

We will add a new api to portal

`/api/v1/projects/<id>/metrics/inject` with a body of `{enable : boolean}`

The implementation in pfe of this api will result in the project.inf having the setting updated.  A build is also triggered to straight away reflect the change.

IDE's will need changing to add a new checkbox to enable/disable injection
![Screenshot 2019-12-02 at 15 50 40](https://user-images.githubusercontent.com/13151286/69973609-b39e0780-151b-11ea-8932-3b1fa366cb1b.png)

**Comment by jopit** [comment]
@deboer-tim I'm going to prioritize this below the hybrid work unless you say otherwise

**Comment by jgwest** [comment]
@tobespc: GitHub didn't allow me to assign the following users: james-wallis

Note that only org members, repo collaborators and people who have commented on this issue/PR can be assigned.

**Comment by rwalle61** [comment]
FYI @tobespc wrote a design here https://github.com/codewind-resources/design-documentation/blob/master/codewindServer/metricsInjection.md

**Comment by micgibso** [comment]
Document the enabling/disabling injection of metrics toggle switch (`Auto inject metrics`) in https://www.eclipse.org/codewind/mdt-vsc-commands-project.html and https://www.eclipse.org/codewind/mdteclipsemanagingprojects.html

**Comment by tobespc** [comment]
the work to add the check box to eclipse is still in progress

**Comment by james-wallis** [comment]
I've split the eclipse plugin implementation out to issue https://github.com/eclipse/codewind/issues/1406

**Comment by james-wallis** [comment]
The work for the Eclipse plugin has now landed.

**Comment by micgibso** [comment]
Docs PR approved and merged: https://github.com/eclipse/codewind-docs/pull/253

**Comment by tobespc** [comment]
this has now finished and can be closed

**Comment by rwalle61** [comment]
I believe this is done on PFE's end. 

@james-wallis can you confirm if the checkbox is done? 

Then @micgibso can close this when docs are done

**Comment by james-wallis** [comment]
My checkbox is done.

**Comment by malincoln** [comment]
> I believe this is done on PFE's end.
> 
> @james-wallis can you confirm if the checkbox is done?
> 
> Then @micgibso can close this when docs are done

@micgibso can you close this one now?  Thanks

**Comment by micgibso** [comment]
@malincoln Closing...
