### ISSUE TITLE
Add 'cwctl project remove' to the CLI

### ISSUE THREAD

**Issue by stalleyj** [eclipse/codewind#1291]
**Description of the enhancement:**

The IDE's are currently calling unbind on a project by directly calling the rest  API in PFE.  They then need to call a command to remove the project connection. Adding this to the cli will makes it easier to remove a project from a codewind connection.

**Proposed solution:** 

Add cwctl project remove -id,-i <value>

This implementation will lookup the connection for the project and then call /api/v1/projects/{id}/unbind. After that it will remove the json file from .codewind/config/connections

**Comment by tetchel** [comment]
it should have an option to delete the files from the user disk too

**Comment by stalleyj** [comment]
PR for this https://github.com/eclipse/codewind-installer/pull/263
@tetchel I added a -d flag to delete the source

**Comment by malincoln** [comment]
@stalleyj can you verify and close or we need someone else to verify?  Thanks

**Comment by stalleyj** [comment]
The function is in, working and ready to be used by the IDEs.
