### ISSUE TITLE
Where does the user/administrator get cwctl from in order to install remotely for hybrid?

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind#1295]
Do we

1. Provide a download link from the landing page
2. Have the IDEs automatically copy it to some accessible location on install.
3. Have the IDEs provide the ability to copy it somewhere on demand.
4. ???

We may need a tactical solution for 0.7.0 and a better solution for follow-on releases.

**Comment by elsony** [comment]
It will be nice if the user can have access to the download as part of the connection setup flow, e.g. on the place where user input the connection information, we have info and link to download cwctl and doc associated with it.

**Comment by jopit** [comment]
Bear in mind that the installation of codwind onto a remote cluster is likely something done by the cluster administrator, not by the individual developer.

**Comment by johnmcollier** [comment]
@jopit Yes, but that won't necessarily always be the case. We also need something easy and straightforward if the cluster administrator **is** the developer as well (like how all of us are generally cluster-admins of the clusters we develop on)

**Comment by jopit** [comment]
Conclusion from tech-topics call

- For 0.7.0
  - IDEs will copy cwctl into `~/.codewind/0.7.0/ ` folder on startup
  - IDEs will add a link from the 'create remote connection' page to the documentation for remote connections
  - Docs will contain information about where the cwctl executable is and how to run it.

**Comment by tetchel** [comment]
sorry shouldn't have closed this. I should add that in vs code, the first line in the "codewind" output view will be the user-friendly location of cwctl.

**Comment by jopit** [comment]
I actually think this can be closed, the code is in and it's been doc'd.
