### ISSUE TITLE
Re-struct the projectStatusChanged event to have more info in the detailedAppStatus

### ISSUE THREAD

**Issue by yangcao77** [eclipse/codewind#1297]
We want to re-struct the `projectStatusChanged` event and include more info in the `detailedAppStatus`. 
The `detailedAppStatus` will be changed from string to a json formatted as:

```
detailedAppStatus: {
  "severity": "INFO" | "WARN" | "ERROR",
  "message": string,
  "notify": boolean
}
```

The boolean value `notify` is to indicate whether to notify user on the message. 

This issue also requires changes in IDE.

**Comment by tetchel** [comment]
done in backend, opened https://github.com/eclipse/codewind/issues/1391 for vs code followup
