### ISSUE TITLE
Codewind repositories - add descriptions and tags

### ISSUE THREAD

**Issue by ericdylanpeters2** [eclipse/codewind#13]
Add descriptions, websites, and tags to ALL eclipse codewind repos, this makes them easier to discover through GitHub’s ‘explore’ feature, and makes them look nicer. Only the repo admin can do it, so we will have to ask the eclipse webmaster.

today we have (e.g.);
https://github.com/eclipse/codewind
No description, website, or topics provided. 

better (e.g.);
https://github.com/microclimate-dev2ops/microclimate-vscode-tools
![image](https://user-images.githubusercontent.com/48959948/60818606-f5dd3b80-a16b-11e9-8539-e493506ee8a5.png)

Checklist 
- [x] codewind-che-plugin
- [x] codewind-filewatchers
- [x] codewind-installer
- [x] codewind-java-profiler
- [x] codewind-node-profiler
- [x] codewind-docs
- [x] codewind-eclipse
- [x] codewind-vscode
- [x] codewind-openapi-eclipse
- [x] codewind
- [x] codewind-openapi-vscode
- [x] codewind-appsody-extension (added on July 25, 2019)

**Amalgamated information:** 

1. codewind-che-plugin

- Description: The official plugin for Codewind on Eclipse Che
- Website: https://codewind.dev
- Topics: che cloud codewind container eclipse kubernetes openshift plugin

2. codewind-filewatchers
- Description: File change notification clients that recursively monitor project directories and notify the Codewind server of file changes
- Website: https://codewind.dev
- Topics:  cloud codewind container eclipse file-change-notifications file-monitoring inotify kubernetes openshift

3. codewind-installer
- Description: The installation package for installing Codewind into an editor
- Website: https://codewind.dev
- Topics:  che cloud codewind container eclipse install kubernetes openshift vscode

4. codewind-java-profiler
- Description: Provides automatic code highlighting of 'hot' java methods
- Website: https://codewind.dev
- Topics:  cloud codewind container eclipse kubernetes performance plugin openshift vscode
 
5. codewind-node-profiler
- Description: Provides automatic code highlighting of 'hot' node.js methods
- Website: https://codewind.dev
- Topics:  eclipse cloud codewind container kubernetesvscode node.js openshift performance plugin 
 
6. codewind-docs
- Description: Codewind project documentation
- Website: https://codewind.dev
- Topics:  cloud codewind container documentation eclipse kubernetes openshift
 
7. codewind-eclipse
- Description:  Plugin for developing cloud-native, containerized applications from Eclipse IDE
- Website: https://codewind.dev
- Topics:  cloud codewind container eclipse kubernetes openshift

8. codewind-vscode
- Description:  Extension for developing cloud-native, containerized applications from VS Code
- Website: https://codewind.dev
- Topics:  codewind cloud container eclipse kubernetes openshift vscode vscode-extension typescript
 
9. codewind-openapi-eclipse
- Description: Extension for using OpenAPI Tools in the Eclipse IDE
- Website: https://codewind.dev
- Topics: cloud codewind container eclipse java kubernetes openapi openshift
 
10. codewind
- Description: The official repository of the Eclipse Codewind project
- Website: https://codewind.dev
- Topics: codewind container cloud docker eclipse java kubernetes node.js openshift swift
 
11. codewind-openapi-vscode
- Description: Extension for using OpenAPI Tools in VS Code
- Website: https://codewind.dev
- Topics:  cloud codewind container eclipse kubernetes vscode vscode-extension typescript openapi openshift

12. codewind-appsody-extension
- Description: Extension to Codewind providing support for Appsody projects
- Website: https://codewind.dev
- Topics:  appsody cloud codewind container eclipse vscode

**Comment by josephca** [comment]
@elsony @tobespc @jopit @sghung Can you provide the description of the repositories that you're working on? then I'll open an Eclipse bug to have them updated together by Eclipse webmaster.

**Comment by jopit** [comment]
https://github.com/eclipse/codewind-vscode
    Extension for developing cloud-native, containerized applications from VS Code

https://github.com/eclipse/codewind-eclipse
    Plugin for developing cloud-native, containerized applications from Eclipse IDE

**Comment by tetchel** [comment]
imo, everything should be tagged with:
kubernetes, container, cloud, eclipse, codewind
at the very least.

in addition, for vs code plugin in the past I had
vscode, vscode-extension, typescript

**Comment by sghung** [comment]
https://github.com/eclipse/codewind-docs
Description: Codewind project documentation 
Tags: kubernetes, container, cloud, eclipse, codewind, documentation

https://github.com/eclipse/codewind-openapi-vscode
Extension for using OpenAPI Tools in VS Code
Tags: codewind, vscode, openapi, vscode-extension, typescript

https://github.com/eclipse/codewind-openapi-eclipse
Extension for using OpenAPI Tools in the Eclipse IDE
Tags: codewind, eclipse, openapi, java

**Comment by jgwest** [comment]
https://github.com/eclipse/codewind-filewatchers
Description: File change notification clients that recursively monitor project directories and notify the Codewind server of file changes.
Tags: codewind, file monitoring, inotify, file change notifications

**Comment by johnmcollier** [comment]
https://github.com/eclipse/codewind-che-plugin
Description: The official plugin for Codewind on Eclipse Che
Tags: codewind, che, kubernetes, openshift, plugin

**Comment by deboer-tim** [comment]
Joseph, please add a link to codewind.dev in every description, e.g. at the end.

**Comment by tetchel** [comment]
^ That should go into the "website" section, you can see `microclimate.dev` in the description's screenshot

**Comment by deboer-tim** [comment]
Sorry, my bad - forgot it was two fields. We should make sure all the websites go to codewind.dev, but not duplicate in the description.

**Comment by ericdylanpeters2** [comment]
@tobespc can you or someone on your team provide descriptions for remaining repos?

**Comment by ericdylanpeters2** [comment]
@tobespc @sghung figure it makes sense to cover what we've got at kabanero as well - https://github.com/kabanero-io?utf8=%E2%9C%93&q=codewind&type=&language=

**Comment by tobespc** [comment]
https://github.com/eclipse/codewind-installer
Description: The installation package for installing Codewind into an editor
Tags: codewind, che, install, vscode, eclipse

**Comment by tobespc** [comment]
https://github.com/eclipse/codewind-java-profiler
Description: Provides automatic code highlighting of 'hot' java methods
Tags: codewind, eclipse, vscode, performance,plugin

**Comment by tobespc** [comment]
https://github.com/eclipse/codewind-node-profiler
Description: Provides automatic code highlighting of 'hot' node.js methods
Tags: codewind, eclipse, vscode, performance ,plugin, node.js

**Comment by tobespc** [comment]
https://github.com/eclipse/codewind
Description: The official repository of the Eclipse Codewind project
Tags: codewind, eclipse, kubernetes, openshift, docker, java, node.js, swift

**Comment by tetchel** [comment]
`openshift` is a good one for all of them.

**Comment by makandre** [comment]
https://github.com/eclipse/codewind-appsody-extension
Description: Extension to Codewind providing support for Appsody projects
Tags: codewind, appsody

**Comment by josephca** [comment]
Opened a bugzilla ticket : https://bugs.eclipse.org/bugs/show_bug.cgi?id=549574

**Comment by josephca** [comment]
I was given the maintainer role and updated descriptions and websites. However, when adding Topics it just shows the loading icon 
![image](https://user-images.githubusercontent.com/25185698/62150189-507d3980-b2cb-11e9-8f2a-c0d84786613f.png)

Will try again later.

**Comment by josephca** [comment]
Adding topics are currently blocked. It seems to be a Github issue rather than Eclipse issue. Hope this issue goes away when Eclipse upgrades the Github.
Closing it for now.
