### ISSUE TITLE
Remote PFE: application route/ingress is not working

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#1307]
**Codewind version:** master
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:** OCP 4.2

**Description:**

Created an app against a remote PFE connection.  Codewind exposes the app on URL that looks something like:

http://cw-cwnode03-85ab9fb0-1212-11ea--apps.makandre42.os.fyre.ibm.com/

But cannot access the application using that.  Tried both Codewind and Appsody projects

**Steps to reproduce:**

**Workaround:**

**Comment by makandre** [comment]
The route's def

[route-cw-cwnode03-85ab9fb0-1212-11ea-95b1-6tgvv.txt](https://github.com/eclipse/codewind/files/3902970/route-cw-cwnode03-85ab9fb0-1212-11ea-95b1-6tgvv.txt)

**Comment by makandre** [comment]
Don't know if this is relevant but I see these env vars in PFE:

```
sh-4.2# env | grep INGRESS
INGRESS_PREFIX=apps.makandre42.os.fyre.ibm.com
CHE_INGRESS_HOST=-k3izxjil.apps.makandre42.os.fyre.ibm.com
```

**Comment by johnmcollier** [comment]
Adding a Portal label to this since the issue may be with how the ingress is being retrieved. On Mattermost, Andrew noted the namespace is missing from the route url prefix (Like `codewind.apps.makandre42.os.fyre.ibm.com`), and this _could_ be causing the OpenShift router to reject the URL.

**Comment by makandre** [comment]
It worked if I changed the `Ingress` object's host to:

```
cw-cwnode03-85ab9fb0-1212-11ea-eclipse-codewind.apps.makandre42.os.fyre.ibm.com
```

Note the namespace part added: `eclipse-codewind.`

**Comment by makandre** [comment]
So I think we need to set the `INGRESS_PREFIX` var to `<namespace>.<ingressdomain>`, since Turbine is using it like so: https://github.com/eclipse/codewind/blob/master/src/pfe/file-watcher/server/src/utils/kubeutil.ts#L430

Aside: why is it called the prefix when it's appended as a suffix?

**Comment by johnmcollier** [comment]
It should absolutely be called `INGRESS_SUFFIX`.

**Comment by markcor11** [comment]
So whilst I'm in this code, the Keycloak and Gatekeeper Ingress URLs do not include the namespace right now and are built up to look like :

```
 codewind-gatekeeper-k3jwx9hj.apps.mycluster.x.x.x.x.nip.io
                             ^ inject namespace here ?
```

Would it make sense to insert a `.namespace.` here too ?  We are already using a unique name here given the inclusion of the WorkspaceID (the k3jwx9hj part) so not sure that adding additional length will provide any additional value.  

Additionally, the CHE_INGRESS_HOST should probably be updated too.  Right now that one points to `-k3jwx9hj.apps.mycluster.x.x.x.x.nip.io and should probably be the Gatekeeper URL.

**Comment by makandre** [comment]
If I changed ingress host to `cw-apnode02-a4632980-1205-11ea-k3izxjil.apps.makandre42.os.fyre.ibm.com` it also works.

I guess it just needs to be something infront of the ingress domain but doesn't necessarily
have to be the namespace.  Using the workspace ID would make it consistent with gatekeeper and keycloak

**Comment by makandre** [comment]
Verified with the latest `cwctl` that this is working now
