### ISSUE TITLE
[Filewatcherd] Filewatcher unable to connect to secure PFE (via HTTP/WebSocket) without using an auth token acquired through CWCTL

### ISSUE THREAD

**Issue by jgwest** [eclipse/codewind#1309]
Filewatcher will use a simple IDE interface to share the auth token with the IDE. See the comments below for details.

This work will need to be implemented in 2 of the 3 filewatchers (Java and TS; the Go filewatcher is already running in a cluster and thus I presume does not support remote connections.)

## Original issue text

Below was my thinking behind how this could originally be implemented. This can be ignored; the new designed described in the comments below is better.

```
In order for Filewatcherd (FWd) to connect to the remote PFE in the 'true hybrid' scenario, FWd will need to run cwctl to create a connection, acquire a token, provide those credentials in HTTP/WS requests, and correctly refresh the token

This scenario will look like this:
1) IDE will now need provide additional credentials to FWd (I think this would be, at least, the values for `--kdevuser` and `--kdevpassword`?), when the FWd constructor is first invoked. 
2) FWd will need to then invoke cwctl, using these credentials, to create a connection and then acquire the dev token. 
3) This token would then be passed as an `Authorization` header for the HTTP requests, and as the first WebSocket message for WebSockets.
4) I also need to implement token refresh, using the refresh token, at which ever interval is indicated by the auth response.
```

**Comment by tetchel** [comment]
IDEs know the auth token, and at least in the vs code case, can give it to the filewatcher instance.

**Comment by jgwest** [comment]
re: IDEs knowing the token and providing it to the filewatcher - at first I thought this would not work, because the Go Filewatcher does not have an IDE to integrate with (and thus if I am implementing manually calling cwctl for Go I may as well implement it everywhere), but since the Go filewatcher won't support 'true hybrid' remote for this release, then your idea (and Erin suggested the same thing) may actually work after all 🤔 🤔 🤔

**Comment by jgwest** [comment]
@eharris369  @tetchel - Does this sound do-able? Any obvious (or not so obvious) issues?

A new interface (Java pseudocode, TS would be equiv) for providing the auth token to FWd:
```Java
public interface IAuthTokenProvider {
	
	// Return the latest auth token; return null if an auth token is not available.
	// This method should be non-blocking (eg I would prefer it return null or stale data, rather then block on issuing a new I/O or CWCTL request to acquire a new token.)
	String getLatestAuthToken();

	// Inform the IDE that the server told us that our current token is invalid, at which point the IDE should then re-acquire/refresh it on a separate thread.
	// Once refreshed, I would expect the new value to be available to the FWd via a call to getLatestAuthToken() after some short period of time.
	//     
	// Filewatcher to call `informReceivedInvalidAuthToken(...)` ONLY ONCE for a given invalid token (eg NOT every time the server informs us.)
	void informReceivedInvalidAuthToken(String badToken);

	// (feel free to use better/more idiomatic method names, if you don't like mine)
}
```

The IDEs would then implement an instance of this object and pass the object to the filewatcher constructor.


#### Java:
```Java
IAuthTokenProvider authTokenProvider = new IAuthTokenProvider() { (...)  };

new CodewindFilewatcherdConnection( (existing values), authTokenProvider );


public CodewindFilewatcherdConnection( (existing params), IAuthTokenProvider authTokenProvider) {

	// ...

	this.fileWatcher = new Filewatcher( (existing params), authTokenProvider);
}
```

#### TS:
```Typescript

createWatcher( (existing params) , authTokenProvider);

export default async function createWatcher( (existing params), authTokenProvider : IAuthTokenProvider) { ... }                                            }
```

Each method implementation would be non-blocking; so for example `informReceivedInvalidAuthToken(...)` should immediately return (eg without blocking on a network I/O request or cwctl call to replace the token) and `getLatestAuthToken()` should just return the latest auth token (eg it shouldn't block if the current data is old, or not yet available). 

You can expect that FWd may call the `getLatestAuthToken()` multiple times per second in situations where we are waiting for a new token.

**Comment by eharris369** [comment]
You say that after you call informReceivedInvalidAuthToken you may call getLatestAuthToken several times before the new token may be ready.  Will you call informReceivedInvalidAuthToken after each one of those calls if it does not work again?

**Comment by tetchel** [comment]
In TS, `getLatestAuthToken` should return a `Promise<string>` not string. That gets around the caveat Erin mentioned above, since that function won't return until it's ready.

**Comment by tetchel** [comment]
Also, do we prefer returning null/undefined if the token lookup fails, or throwing an error/exception?

**Comment by jgwest** [comment]
>You say that after you call informReceivedInvalidAuthToken you may call getLatestAuthToken several times before the new token may be ready. Will you call informReceivedInvalidAuthToken after each one of those calls if it does not work again?

My plan would be only to inform once for a single token value, something like this:
```java
Map<String /* auth token*/,  ( some value) > informedIDEOfFailure = new HashMap<>();

onTokenFail(String badToken) {

    if(informedIDEOfFailure.containsKey(badToken)) { return; }
    else {
        informedIDEOfFailure.put(badToken, (some value) );
        informReceivedInvalidAuthToken(badToken);
    }
}

// It would be slightly more complex as I would need to eventually evict some of the previous tokens seen, but that's an implementation detail on my side.
```

> It would be possible in TS for getLatestAuthToken to return a Promise<string> not string. That gets around the caveat Erin mentioned above, since that function won't return until it's ready.
I'd probably prefer a null when it's not ready.

> Also, do we prefer returning null/undefined if the token lookup fails, or throwing an error/exception?
I would probably just say null: I don't think the specific reason that it failed would be especially useful to FWd, since FWd doesn't have a UI with which to communicates errors to the user (just the log output), and presumably if y'all weren't able to acquire an auth token you would already have informed the user via the UI.

**Comment by jgwest** [comment]
Actually, I may be thinking about this wrong: are y'all acquiring a token once across the entire IDE, and then reusing it over and over again? This was my assumption for what you were doing, and that the FWd would just use that. 

Eg I had thought of this interface as a way for FWd to just get access to the IDE's token, not to acquire a new one specifically for the FWd.

**Comment by tetchel** [comment]
Yes there is only one token per codewind connection

**Comment by jgwest** [comment]
Ah, perfect, the API I mentioned above then would just be able getting that value (and sometimes it might be stale or null, and that's OK on the FWd end)

**Comment by jgwest** [comment]
[Portal folks have not yet secured the WebSocket endpoint used by filewatchers for project notifications](https://github.com/eclipse/codewind/issues/1342), so there is no need to include that in the FW PRs for this release.

**Comment by jgwest** [comment]
Filewatcher PRs have been merged. As described above, the next step is for the IDEs to pass an instance of `IAuthTokenProvider` to the Filewatcher constructor, which the Filewatcher will use to request the token at the appropriate times.

In VS Code, see [here for the constructor](https://github.com/eclipse/codewind-filewatchers/blob/5d73c5f3a44cb04bd2b8d2c171fc33e860e12451/Filewatcherd-TypeScript/src/lib/client.ts#L33).
In Eclipse, see [here](https://github.com/eclipse/codewind-eclipse/blob/dfb6d69e3c90898181e7aea5df7f05f8c1e57df1/dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnection.java#L131) for the location to create and pass the provider interface. 

And in parallel, we will need https://github.com/eclipse/codewind/issues/1367 to be fixed, as without this the Filewatcher will not be informed of new/deleted/changed projects in a timely fashion.

**Comment by eharris369** [comment]
PR for Eclipse IDE: https://github.com/eclipse/codewind-eclipse/pull/456

**Comment by jopit** [comment]
Is there more work do do for this issue, or can it be closed?
