### ISSUE TITLE
[Filewatcherd] Remote PFE will need to provide a local absolute pathToMonitor value to a local Filewatcher

### ISSUE THREAD

**Issue by jgwest** [eclipse/codewind#1311]
Currently, the WebSocket endpoint `(PFE URL)/websockets/file-changes/v1` and HTTP GET `(PFE URL)/api/v1/projects/watchlist` APIs that are used by filewatcher are returning a list of project directories for filewatcher to watch:
```
{
  "type": "watchChanged",
  "projects": [
    {
      "changeType" : "add/update", 
      "projectId": "191911",
      "pathToMonitor": "/C/tempest-1907/tempest-workspace/myproject", <---- FWd will ask the OS to watch this dir
      "ignoredPaths": "[ ... ]",
      "ignoredFilenames": "[ ... ]",
      "projectWatchStateId" : "[...]",
    }
  ]
}
(example is from a WebSocket message)
```

However, note the `pathToMonitor` field is _a local absolute path to a directory on the user's machine_. Thus, with true hybrid where FWd will be connecting to a remote PFE, that remote PFE will still need to provide absolute paths on the user's local machine. My guess is that local cwctl can provide information to the remote PFE (eg on bind) in order to provide this information back, but UK folks would know better than I here...

**Comment by tobespc** [comment]
We already do this @jgwest, when a project is added to codewind, regardless of where codewind is running the pathToMonitor value should be the absolute local path each time

**Comment by jgwest** [comment]
Sweet, closing as already done, as per above.
