### ISSUE TITLE
User can remove injected metrics collector from their project

### ISSUE THREAD

**Issue by rwalle61** [eclipse/codewind#1315]
**Codewind version:** latest
**OS:** all

**Description of the enhancement:**
After our metrics injection work goes in, users will be able to click a button in the IDE, and see their projects rebuild and expose a `/metrics` endpoint.

As a user, I will then want to be able to click another button and see my project rebuild and no longer have a `/metrics` endpoint.

**Proposed solution:** 
1. Modify an API endpoint in PFE (`POST /api/v1/projects/:id/metrics/inject`) such that passing a request body of `{ enable: false }` will attempt to remove any injected metrics collector from the project.
2. Make the IDE able to trigger that endpoint in that way (maybe through `cwctl`)

**Comment by rwalle61** [comment]
part of https://github.com/eclipse/codewind/issues/1290

**Comment by rwalle61** [comment]
@mattcolegate now that your change to inject metrics collector into Spring projects is in, can you verify that we can remove injected metrics collectors from them too? If we have that functionality then this issue will be resolved so please close this issue

**Comment by mattcolegate** [comment]
Tested this morning and both metrics injection and withdrawal is performed successfully with Spring projects. @rwalle61 I'm not sure this issue can be closed though, as it states 'users will be able to click a button in the IDE' - do you know where that work is being done?

**Comment by rwalle61** [comment]
https://github.com/eclipse/codewind-vscode/pull/317 completed this work
