### ISSUE TITLE
Remote install can break local install

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind#1316]
If I don't have the codewind docker images on my machine, and I do a remote install of codewind into my desktop docker minikube, my machine will then have the images with the 'fully qualified' names, i.e. the name with the 'eclipse' prefix, but won't have the ones without the 'eclipse' prefix.
```
% docker images | grep codewind
eclipse/codewind-gatekeeper-amd64                                latest              297ec1f227b7        47 hours ago        89.5MB
eclipse/codewind-keycloak-amd64                                  latest              01a33124caa4        47 hours ago        648MB
eclipse/codewind-performance-amd64                               latest              a0c43a46a7dd        47 hours ago        90.8MB
eclipse/codewind-pfe-amd64                                       latest              c38d1e0e6296        47 hours ago        743MB
```
Then `cwctl status` will return that codewind is installed
```
% ./cwctl status
Codewind is installed but not running
```
so the IDEs will think it's installed, but I will get an error when I try to start it.
```
% ./cwctl start                
Debug: false
Stopping Codewind and Project containers
Removing Codewind docker networks..
Removing docker network: codewind_network... ==> created file /Users/jsp/codewind/codewind-docker-compose.yaml
==> environment structure written to codewind-docker-compose.yaml
System architecture is:  amd64
Host operating system is:  darwin
Attempting to find available port
Port 10000 Available
Please wait whilst containers initialize...  
Creating network "codewind_network" with the default driver
Pulling codewind-performance (codewind-performance-amd64:latest)...
The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]pull access denied for codewind-performance-amd64, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```
We should fix this for 0.7.0

**Comment by liamchampton** [comment]
We dont need to re-tag the images from `eclipse/codewind-pfe-amd64` -> `codewind-pfe-amd64` once downloaded anymore. Removing this re-tag will allow us to pick up any images with the prefix `eclipse/codewind-`

**Comment by liamchampton** [comment]
@jopit Please can you verify this is still an issue. We have changed from `docker apis` -> `docker-compose` which should handle this issue.

**Comment by jopit** [comment]
It's now broken in a different way.

When codewind is running in docker-desktop minikube, the local version of cwctl detects this, and reports a strange version is started
```
% ./cwctl --json --insecure status
{"status":"started","url":"http://:","installed-versions":["latest"],"started":["66cc008e0e63b99605c0664d90b12cba3a445de8a417d0f941144b6b1f2d70f8","c472b397906cd283900feaffd553fcc45c9dba7cb60c6d82ce1bd5d4fbcccf36"]}
```` 
and so the IDEs think codewind needs to be upgraded

![image](https://user-images.githubusercontent.com/29612372/72273355-3674b080-35f8-11ea-9def-25f0b8e8d750.png)

**Comment by tobespc** [comment]
from 0.8.0, we don't have the short name anymore, it should all be fully qualified

**Comment by tobespc** [comment]
@jcockbain can you test and fix/close please

**Comment by liamchampton** [comment]
Can confirm this is still a problem. We currently have a search that matches both install scenarios. One image has a readable tag (local install), the remote install on desktop-kube does not, which is seen above. I will work on fixing the search criteria to exclude remote installations when running a local install status command.

**Comment by liamchampton** [comment]
@jopit please can you verify this is now fixed?

**Comment by malincoln** [comment]
@jopit pls verify and close. Thanks
