### ISSUE TITLE
[Hybrid] Appsody projects won't build if there is no push registry

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#1317]
Create a connection to Codewind running in Kube and then try creating an appsody project.  It fails to build with a message saying it needs a deployment registry but appsody projects should not need a deployment registry.

![image](https://user-images.githubusercontent.com/9484320/69882599-b3dd9f00-129e-11ea-8d2e-7dd4416b93bd.png)

**Comment by makandre** [comment]
This may address it https://github.com/eclipse/codewind/issues/1266

**Comment by eharris369** [comment]
Right now there is no registry support in Eclipse.  It does not ask the user to provide a registry for any project type.  This is a problem for Codewind style projects but Appsody projects should work without a registry.  The message is coming from PFE not from the IDE.  I think 1266 is for VSCode which asks the user for a registry regardless of the project type.

**Comment by jopit** [comment]
No #1266 is an IDE level issue, this build failure message is coming from PFE.

**Comment by jopit** [comment]
I'm going to guess the build failure message is coming from turbine, so tagging this as iterative-dev.

**Comment by elsony** [comment]
This issue is originally a dup of #1266. Originally, #1266 is supposed for both IDE and iterative dev changes. The original plan was to do changes on both IDE and iterative side. Based on https://github.com/eclipse/codewind/issues/1266#issuecomment-558330766, the iterative dev work is dropped. Given that we have separate item now, I'll keep this item for the iter dev only work.

**Comment by rajivnathan** [comment]
@makandre @eharris369 I've dropped a fix for this. Can one of you please verify?

**Comment by rajivnathan** [comment]
I tested the fix for codewind, appsody and odo type projects.

@makandre appsody project failed to deploy but I think that's an appsody bug because it failed after the check so seems unrelated to the change

**Comment by makandre** [comment]
@rajivnathan What is the deploy error you saw?  There was an issue we discovered yesterday and a fix went in.

**Comment by eharris369** [comment]
Tested this with local kubernetes and it is working.

**Comment by rajivnathan** [comment]
Sorry for the late reply. I don't have the error but I had talked to Steven that day and he mentioned there was a fix that you had recently put in so I'm assuming that's the one. Either way, if you've tested appsody with this fix we're all good.
