### ISSUE TITLE
Appsody projects stuck in Building: Calculating difference state

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#132]
If I create a new appsody project, disable auto build, make a change and then enable auto build, the project gets stuck in `Building: Calculating difference` state.

If changing the auto build setting is not supported for appsody projects then a capability should be added for auto build so that the IDEs know to disable it.  If no capability is added then the projects should not get stuck in this state.

**Comment by tetchel** [comment]
@makandre

**Comment by makandre** [comment]
What stack?    Right, auto-build is not supported.  I know we had discussed about hiding the auto-build option for appsody but I'm unsure if we actually raised that as an issue.  @sghung might know.

**Comment by rajivnathan** [comment]
I just saw this happen with a Microprofile project so doesn't appear to be specific to appsody.

Steps to reproduce:
1. Clone https://github.com/microclimate-dev2ops/javaMicroProfileTemplate to the codewind workspace (Do not create using Codewind)
2. Delete the Dockerfile-build file
3. Add the project to Codewind using the "Add existing project" action
4. It should fail to build, state will be [Stopped] with a build failure status
5. Without making any other changes just try a manual build again.

Result:
You end up stuck in [Stopped] [Building - Calculating difference] state.

**Comment by yangcao77** [comment]
The fix for microprofile project is PR https://github.com/eclipse/codewind/pull/199

For appsody project,  if the update failed. it should return an exit code as well. So our code can caught the error and set the build status correctly.

**Comment by makandre** [comment]
@yangcao77 could you open an appsody issue with the details at https://github.com/eclipse/codewind-appsody-extension/issues?

**Comment by makandre** [comment]
Actually I've identified the problem on appsody side and the cause is slightly different

**Comment by yangcao77** [comment]
Is any code change required in Turbine to get appsody project issue fixed? @makandre I'm glad to help out if there's any.

**Comment by makandre** [comment]
Thanks @yangcao77 I've a fix https://github.com/eclipse/codewind-appsody-extension/pull/6; it does not require Turbine changes.

**Comment by sghung** [comment]
Re-opened since https://github.com/eclipse/codewind/pull/199 is not in yet

**Comment by rajivnathan** [comment]
@sghung can this be closed now?

**Comment by sghung** [comment]
Yes, this can be closed now
