### ISSUE TITLE
Error notification when deleting project

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind#1321]
I successfully installed codewind into a ROKS cluster, connected using vscode, and created an appsody project called `appsody-node`.  I then deleted the project, and vscode showed an error notification `Error deleting appsody-node`.  The project's pod was actually deleted from the cluster, but there are errors in the PFE logs

[pfe.txt](https://github.com/eclipse/codewind/files/3911709/pfe.txt)

**Comment by makandre** [comment]
I think you're seeing #1304

**Comment by jopit** [comment]
Thanks @makandre, closing as a dup of #1304
