### ISSUE TITLE
Link to docs in Eclipse IDE results in 404 not found in browser

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#1322]
The Eclipse IDE has a link to this page from one of the dialogs but it is giving a file not found now: https://www.eclipse.org/codewind/mdteclipseusingadifferenttemplate.html.

All of the doc links in the Eclipse IDE can be found here: https://github.com/eclipse/codewind-eclipse/blob/master/dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/UIConstants.java

**Comment by sishida** [comment]
@eharris369 It appears that the name of the file changed.

Here's the PR where the change was made: https://github.com/eclipse/codewind-docs/commit/8fab380e7263a3f64a73cf692f5a06514d5a1bba

And here's the page itself with its new name/URL on the Codewind website: https://www.eclipse.org/codewind/mdteclipseworkingwithtemplates.html

**Comment by eharris369** [comment]
@tetchel It looks like the VSCode link is out of date too: `TEMPLATE_MANAGEMENT = "mdt-vsc-usingadifferenttemplate.html",`.

**Comment by eharris369** [comment]
Eclipse PR: https://github.com/eclipse/codewind-eclipse/pull/443

**Comment by sishida** [comment]
@tetchel It looks like the same change was made for the VS Code documentation with this PR: https://github.com/eclipse/codewind-docs/commit/4b6572d8cb2810f392901d4c86cc62ac260c73a5

And here is the new/renamed file as it appears on the Codewind website: https://www.eclipse.org/codewind/mdt-vsc-workingwithtemplates.html
