### ISSUE TITLE
Violation of logo usage on website

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind#1329]
The Codewind website has altered logos that need to be reverted back to their original state: https://www.eclipse.org/codewind/

https://www.youtube.com/about/brand-resources/#logos-icons-colors

> Do not Use any colors other than red, almost black, or white

https://github.com/logos

> do not Change the colors, dimensions or add your own text/images

https://mattermost.org/brand-guidelines/

> Do not distort or alter the Mattermost logo.

https://about.twitter.com/content/dam/about-twitter/company/brand-resources/en_us/Twitter_Brand_Guidelines_V2_0.pdf

> Only show the logo in Twitter blue or white. • Don’t alter, rotate, or modify the logo

**Comment by jgwest** [comment]
FWIW I think we are consistent with the spirit of these brand guidelines: all of the logos are presented in a dark monochrome colour, which is consistent with how other sites handle this.

https://openwhisk.apache.org/
https://appsody.dev/
https://kabanero.io/
