### ISSUE TITLE
Getting error for watchedFiles when updating the .cw-settings contextRoot

### ISSUE THREAD

**Issue by hhellyer** [eclipse/codewind#133]
**Codewind version: master**
**OS:**

**Description of the bug:**
Given the default .cw-settings file, if I change the value for contextRoot and save it, a projectSettingsChanged event is sent with the following:

{"operationId":"0f7b0c358b4ce74496a0392e9831025e","error":"BAD_REQUEST: watchedFiles is not a configurable setting.","projectID":"d84658a0-b94d-11e9-b317-d19b82183890","status":"failed"}

The context root does get updated in spite of the error.

The watchedFiles is included in the default .cw-settings file for the project, I did not add it.

{
  "contextRoot": "",
  "internalPort": "",
  "healthCheck": "",
  "ignoredPaths": [
    ""
  ],
  "watchedFiles": {
    "includeFiles": [
      ""
    ],
    "excludeFiles": [
      ""
    ]
  }
}

I think this is because watchedFiles isn't in the list of settings that can be changed: https://github.com/eclipse/codewind/blob/b08fdc38fe86a25bb77b821c4f78fe1cde1711f9/src/pfe/file-watcher/server/src/projects/projectSpecifications.ts#L772

**Comment by yangcao77** [comment]
The `watchedFiles` fie;d was for the old file watching logic. The field has been removed from Turbine after filewatcher was introduced. 

The entire `watchedFiles` object should be removed from all `.cw-settings` files.

**Comment by rajivnathan** [comment]
I misunderstood, thought an old cw-settings file was being used but Stephanie believes the template on the portal side hasn't been changed so reopening. `watchedFiles` should have been removed from the template at the same time the validation code was modified but likely a communication breakdown on our part. (sorry!)

@hhellyer James Cockbain previously managed the cw-settings changes on the portal side, don't see him listed on github but if it's quick and easy for him to make the change that'd be great. If not Stephanie mentioned she can look into it.

**Comment by rajivnathan** [comment]
@hhellyer Please verify and close when you have a chance

**Comment by eharris369** [comment]
Built the latest and verified that the problem is resolved.
