### ISSUE TITLE
Update Turbine Kube Tests for Registry Secrets API

### ISSUE THREAD

**Issue by maysunfaisal** [eclipse/codewind#1337]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**
When #665 is consumed by the IDE, Functional tests need to set the Registry Secrets via the PFE API rather than thru the Che dashboard.

**Steps to reproduce:**

**Workaround:**

**Comment by malincoln** [comment]
@maysunfaisal pls verify and close if resolved. Thanks
