### ISSUE TITLE
Cleanup license property in package.jsons

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#1344]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**

These files are showing the wrong license value (there maybe other files):

https://github.com/eclipse/codewind/blob/master/src/pfe/portal/package.json#L16
https://github.com/eclipse/codewind/blob/master/src/pfe/file-watcher/server/package.json#L39

**Steps to reproduce:**

**Workaround:**

**Comment by hhellyer** [comment]
@makandre - I've updated the package.json files, can this be closed?

**Comment by makandre** [comment]
Thx
