### ISSUE TITLE
Hybrid: projects build but won't start - error when pulling image

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#1346]
If I create a new project it builds and pushes the image to the registry I have set but when it tries to pull it, it fails with the following message (from kubectl get events):
```
Failed to pull image "docker.io/eharris/cw-go1-0aba3be0-15e6-11ea-946f:latest": json: cannot unmarshal array into Go struct field DockerConfigJson.auths of type string
```
I have no problems doing a docker pull on my local machine for the same image.  It runs fine as well.

**Comment by eharris369** [comment]
The PFE logs have:
```
[[91m[03/12/19 16:00:55 go1] [ERROR]^[[39m The pod for helm release cw-go1-0aba3be0-15e6-11ea-946f has failed to start, with reason: ErrImagePull
^[[32m[03/12/19 16:00:55 go1] [INFO]^[[39m Application state changed for project: 0aba3be0-15e6-11ea-946f-cfa1d4e9b1a7 from: starting, to: stopped
^[[32m[03/12/19 16:00:55 go1] [INFO]^[[39m Emitting event
 message: projectStatusChanged
 data: {
  "projectID": "0aba3be0-15e6-11ea-946f-cfa1d4e9b1a7",
  "appStatus": "stopped",
  "appErrorStatus": "Pod for Helm release go1 failed to start."
}
^[[32m[03/12/19 16:00:55 go1] [INFO]^[[39m Printing Helm release
^[[32m[03/12/19 16:00:55 go1] [INFO]^[[39m Running helm command: helm status,cw-go1-0aba3be0-15e6-11ea-946f
^[[32m[03/12/19 16:00:56 go1] [INFO]^[[39m LAST DEPLOYED: Tue Dec  3 16:00:53 2019
NAMESPACE: cw
STATUS: DEPLOYED

RESOURCES:
==> v1/Service
NAME                            TYPE      CLUSTER-IP  EXTERNAL-IP  PORT(S)         AGE
cw-go1-0aba3be0-15e6-11ea-946f  NodePort  10.98.9.21  <none>       8000:32306/TCP  3s

==> v1beta1/Deployment
NAME                            DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
cw-go1-0aba3be0-15e6-11ea-946f  1        1        1           0          3s

==> v1/Pod(related)
NAME                                            READY  STATUS        RESTARTS  AGE
cw-go1-0aba3be0-15e6-11ea-946f-59df8b785-8mdfd  0/1    ErrImagePull  0         3s
```

**Comment by johnmcollier** [comment]
@eharris369 How were the docker registry credentials being set?

The error `cannot unmarshal array into Go struct field DockerConfigJson.auths of type string` indicates that Kube was given an invalid dockerconfigjson in its struct. But without seeing how the credentials were created by you, it's hard to say why it's invalid

@maysunfaisal FYI

**Comment by maysunfaisal** [comment]
also pls do `kubectl get secrets` and `kubectl describe sa che-workspace`

**Comment by eharris369** [comment]
If it can push to the registry then aren't the credentials working properly?

**Comment by eharris369** [comment]
```
gabriels-imac:codewind wdt$ kubectl get secrets -n cw
NAME                                  TYPE                                  DATA   AGE
codewind-k3pzvirb-docker-registries   kubernetes.io/dockerconfigjson        1      4h4m
codewind-k3pzvirb-token-xgrh2         kubernetes.io/service-account-token   3      4h21m
default-token-jfwvc                   kubernetes.io/service-account-token   3      4h21m
secret-codewind-client-k3pzvirb       Opaque                                1      4h20m
secret-codewind-session-k3pzvirb      Opaque                                1      4h20m
secret-codewind-tls-k3pzvirb          Opaque                                2      4h20m
secret-keycloak-tls-k3pzvirb          Opaque                                2      4h21m
secret-keycloak-user-k3pzvirb         Opaque                                2      4h21m
```

**Comment by johnmcollier** [comment]
@eharris369 Not necessarily. The credentials used to push to the registry with buildah and the credentials used to allow Kube to pull from that registry are in separate locations:
- Push credentials: Stored on PFE under `~/.docker/`
- Kube pull credentials: Stored in a Kubernetes secret (codewind-k3pzvirb-docker-registries in your case)

It could be either that the .dockerconfigjson is malformed, and buildah doesn't reject it (but Kube does) or something else went wrong

How did you create the registry secret?

**Comment by maysunfaisal** [comment]
@eharris369 If you created through the API, pls post the PFE log during API calls

also can you pls make this change 
https://github.com/eclipse/codewind-che-plugin/pull/106/files#diff-4e628246b2e3018c70bf46bdf74f5ec5R33

I suspect your namespace does not have delete permission, so thats why the API may be crapping out

**Comment by eharris369** [comment]
I figured it out.  It is a bug in my code.  I'm still confused by the push working though.

**Comment by maysunfaisal** [comment]
`registrysecrets` does two things on kube: 
1. create the docker config at `/root/.docker/config.json`
2. create a Kube secret with the encoded file from point 1, and patch the Service account with the new secret

- buildah/docker only looks at the docker config at `/root/.docker/config.json` for pushing.
- kubectl pod pulls looks at the service account to pull images.

**Comment by eharris369** [comment]
Fixed by PR https://github.com/eclipse/codewind-eclipse/pull/449
