### ISSUE TITLE
Hybrid: applications will not open in the Eclipse internal browser

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#1365]
Trying to open an application in the Eclipse internal browser results in a popup with the following message:

```
http://cw-go2-5c8b0ae0-1612-11ea-946f-cw.10.107.179.184.nip.io/

Page load failed with error: The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.
```

If I manually change the URL that PFE sends to be https instead of http I get the popup below.  Checking *Always trust* and clicking on *Continue* just pops up the dialog again.

![image](https://user-images.githubusercontent.com/9484320/70150093-68990700-1677-11ea-964d-279291696172.png)

The applications can be loaded by Chrome and Safari without any changes to the URL though they do prefix the URL with Not Secure.

**Comment by eharris369** [comment]
@jopit - Can you check if you can reproduce this?

**Comment by jopit** [comment]
From my mac I am able to access the app using http.

**Comment by eharris369** [comment]
I only see this problem when self-hosting so closing.
