### ISSUE TITLE
Cwctl install remote can't find kubeconfig on Windows

### ISSUE THREAD

**Issue by jgwest** [eclipse/codewind#1366]
**Description:**
It appears that the `cwctl install` command isn't able to locate the `.kube/config` file on Windows. 

When running `cwctl install remote` I'm getting the following error: `Unable to retrieve Kubernetes Config FindFirstFile .kube\\config: The system cannot find the path specified.\n"`

The code in question appears to look for a `HOME` environment variable, which is not present on Windows:
https://github.com/eclipse/codewind-installer/blob/71e6dbc44ad40a02ec09f0c3fb99f0d2a8c7a1a6/pkg/remote/deploy.go#L62

Output:
```
C:\Codewind\Git\codewind-eclipse\dev\org.eclipse.codewind.core\binaries\windows>.\cwctl --insecure install remote --namespace eclipse-codewind --kadminuser ocadmin --kadminpass ocadmin --krealm codewind --kclient codewind --kdevuser developer --kdevpass developer --ingress (ingress )
time="2019-12-04T10:32:13-05:00" level=info msg="Unable to retrieve Kubernetes Config FindFirstFile .kube\\config: The system cannot find the path specified.\n"
time="2019-12-04T10:32:13-05:00" level=error msg="Error: rem_not_found - FindFirstFile .kube\\config: The system cannot find the path specified.\n"
```

**Steps to reproduce:**

Run a standard `cwctl install remote` command on Windows

**Solution**:
Use the Windows alternatives, see below.

**Comment by jgwest** [comment]
On Windows, use the concatenation of these two env vars instead:  `%SystemDrive%%HOMEPATH%`

See below for their format and for proof they are proper env vars and therefore are accessible to Go.

```
C:\Users\JONATHANWest>echo %HOMEDRIVE%
C:

C:\Users\JONATHANWest>echo %HOMEPATH%
\Users\JONATHANWest

C:\Users\JONATHANWest>set | find /i "systemdrive"
SystemDrive=C:

C:\Users\JONATHANWest>set | find /i "homepath"
HOMEPATH=\Users\JONATHANWest

C:\Users\JONATHANWest>echo %SystemDrive%%HOMEPATH%
C:\Users\JONATHANWest
```

([source](https://stackoverflow.com/questions/9228950/what-is-the-alternative-for-users-home-directory-on-windows-command-prompt))

**Comment by jgwest** [comment]
Seemingly this was temporarily fixed and then reverted, but there is no corresponding issue that I could see:
https://github.com/eclipse/codewind-installer/pull/257

**Comment by markcor11** [comment]
/pipeline Verify

This should be resolved now

**Comment by markcor11** [comment]
This should be resolved now since  HOME path is being determined by GOOS. Moving to verify

/pipeline Verify

**Comment by jgwest** [comment]
Verified, thanks!
