### ISSUE TITLE
[odo] Hybrid support for odo extension

### ISSUE THREAD

**Issue by GeekArthur** [eclipse/codewind#1375]
Since the remote support is almost done, IIRC only major feature left is project settings (https://github.com/eclipse/codewind/issues/1374), so we can start to test, investigate and implement corresponding changes for hybrid support.

**Comment by malincoln** [comment]
@GeekArthur can you verify and close?  Thanks

**Comment by GeekArthur** [comment]
I move this issue to `In Progress` and change release to `0.8.0` since hybrid case is not blocker of `0.7.0`, and we still need to implement script to bind roles to dynamic service account and ensure no regression for che case and may decide if we want to move the binding roles step to `cwctl` (think that depends on what specific roles we need to bind). Also we need to ensure corresponding instructions are documented well after merging the changes.

**Comment by GeekArthur** [comment]
Currently I am focusing on `0.7.0` and make the che case stable for odo project type.

**Comment by GeekArthur** [comment]
We may need to dynamically get the service account name of hybrid Codewind, then apply additional rules to the specific service account name for supporting odo.

**Comment by GeekArthur** [comment]
Verified, close the issue.
