### ISSUE TITLE
[Eclipse IDE] Add a icon for creating a new connection to the toolbar

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#1387]
The Codewind item in the view should have a label on it to tell users how to create new connections.  Something like:
- Right click to create a connection to a remote Codewind instance

**Comment by eharris369** [comment]
@sishida Hi Sarah.  What would you recommend for this?  It would go on the top level Codewind element in the view, similar to how the Local element tells users how to create a project I want to tell users how to create a remote connection.

![image](https://user-images.githubusercontent.com/9484320/70331767-281fc180-180e-11ea-8204-55bcdff72e5d.png)

**Comment by sishida** [comment]
@eharris369 I looked at the UI design for VS Code. We've got things like, "Click here to set up your connection" and "Click here to create a project".

Your suggestion should work--please just add a hyphen to "Right-click." ;) Thanks!

**Comment by jopit** [comment]
@jopit create an icon for this

**Comment by eharris369** [comment]
We discussed this and rather than adding a message next to the Codewind element which might be confusing to users (they might think they have to create a remote connection in order to use Codewind), an icon will be added to the toolbar for creating a connection.  The icon will be enabled at all times (not dependent on the selection).

**Comment by eharris369** [comment]
master PR: https://github.com/eclipse/codewind-eclipse/pull/471
0.7.0 PR: https://github.com/eclipse/codewind-eclipse/pull/474

**Comment by eharris369** [comment]
This is fixed now.
