### ISSUE TITLE
cwctl stop-all does not stop appsody container if the image name not prefixed with appsody

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#1388]
**Codewind version:** master
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**

I have an appsody project whose base stack image is `makandre/nodejs-expres:0.2`.  `cwctl stop-all` does not stop this container, because it is looking only for containers whose image name starts with a known list of prefixes.

https://github.com/eclipse/codewind-installer/blob/5a740b5a7b85becf0c26c102e16fdead503e1515/pkg/actions/stop-all.go#L35

**Steps to reproduce:**

**Workaround:**

**Comment by tobespc** [comment]
can take a look at this from portal side, be next week though

**Comment by james-wallis** [comment]
PR is up for this: https://github.com/eclipse/codewind-installer/pull/283/

Also fixed in that PR is the dynamic removing of Docker containers based on their `AutoRemove` setting.

**Comment by jgwest** [comment]
(Guessing this should be verify rather than closed, feel free to close again if I'm incorrect)

**Comment by makandre** [comment]
Verified this on 0.7.0 and master.  Thanks for the fix.
