### ISSUE TITLE
Update Codewind MicroProfile project template to MicroProfile 3.0

### ISSUE THREAD

**Issue by keithchong** [eclipse/codewind#1395]
**Codewind version:** latest

**Description of the enhancement:**
The current MicroProfile template is at 1.2 and is old:  https://github.com/codewind-resources/javaMicroProfileTemplate

3.0 is available.

**Comment by tobespc** [comment]
I've updated to 3.2 under this PR

https://github.com/codewind-resources/javaMicroProfileTemplate/pull/1

**Comment by tobespc** [comment]
re opening as codewind is not able to build new template

**Comment by malincoln** [comment]
@keithchong pls verify and close. Thanks

**Comment by keithchong** [comment]
I see the changes from this PR https://github.com/codewind-resources/javaMicroProfileTemplate/pull/5

Closing.
