### ISSUE TITLE
UI doc review and More Info file for Hybrid/Remote + Container Registry Scenario

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind#1397]
To Do:
- Doc review for strings and messages in the remote UI.
- Create documentation for the "More info" links in the remote UI.

This issue touched on the following issues:
- Allow user to specify multiple docker registry credentials: https://github.com/eclipse/codewind/issues/1178
- Create docker registry secret in Codewind: https://github.com/eclipse/codewind/issues/665
- Only require a user to set a docker / deployment registry for project types that require it: https://github.com/eclipse/codewind/issues/1266
- [Hybrid] Appsody projects won't build if there is no push registry: https://github.com/eclipse/codewind/issues/1317
- IDE support for Kube: https://github.com/eclipse/codewind/issues/839

Notes:
Info from meeting with Guy:
- Need a section for what happens when you test the push registry credentials by deploying a Hello World image to an address.
- We also need to note message boxes from the UI. Two variables: User adds custom source (requires optional pull registries) or Codewind style templates (requires custom push registry).

**Comment by sishida** [comment]
Added comments to UI designs in InVision.

**Comment by sishida** [comment]
@micgibso recommends linking "More info" to this page: https://github.com/eclipse/codewind-docs/blob/9a919f5d29babc13dc23317dfe6e489b70e308a9/docs/_documentations/remote-overview.md

We might want to add a section that centers around the UI more, but this is a start for conceptual info! :)

**Comment by sishida** [comment]
Jake's file might be the best file to link from the Image Registry Manager page: https://github.com/eclipse/codewind-docs/pull/251

**Comment by maysunfaisal** [comment]
@sishida has #665 doc made it or is it in progress?

**Comment by sishida** [comment]
#665 doc has made it in! Closing this issue now. :)
