### ISSUE TITLE
Google search related: Old links in Eclipse Codewind project proposal 

### ISSUE THREAD

**Issue by spoole167** [eclipse/codewind#14]
I dont know where else to report this as I couldn't find a repo for the website.   

The proposal project for Codewind on Eclipse Foundation [website](https://projects.eclipse.org/proposals/eclipse-codewind) points to the old microclimate repos not the new CodeWind versions. 

This is confusing for anyone googling for "Eclipse CodeWind"  since the top hit is the link above and not to the new repos.

**Comment by rtaniwa** [comment]
@deboer-tim is this something you can fix as the project proposal owner?

**Comment by deboer-tim** [comment]
Fixed title: this is not the Codewind main page, it's the original project proposal. The main page is codewind.dev and the Eclipse project page is https://projects.eclipse.org/projects/ecd.codewind.

It's also normal that the project proposal points to the original code to be donated to Eclipse, e.g. see https://projects.eclipse.org/proposals/eclipse-jakarta-ee-platform.

This original proposal was not even picked up by google last last month, and over time it should go away again, but maybe we can use this bug to help promote the main page instead.

**Comment by deboer-tim** [comment]
Joseph, could you see if there's some SEO or other changes we can make to ensure that codewind.dev is the first link that people get in queries?

**Comment by josephca** [comment]
According to https://support.google.com/webmasters/answer/7451184?hl=en Google suggested to use the "description" meta tag and https://www.eclipse.org/codewind/ already use  **<meta name="description" content="Eclipse Codewind">** 

The codewind.dev is listed as the rank_#2 and I believe it will become rank_#1 as time goes by.

**Comment by josephca** [comment]
> According to https://support.google.com/webmasters/answer/7451184?hl=en Google suggested to use the "description" meta tag and https://www.eclipse.org/codewind/ already use
> 
> The codewind.dev is listed as the rank_#2 and I believe it will become rank_#1 as time goes by.

I think there's nothing much we can do. Closing the issue for now.

**Comment by josephca** [comment]
Now **codewind.dev** link appears as the first link. :)
