### ISSUE TITLE
Appsody extension should pass env to Appsody CLI via --docker-options

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#1401]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description of the enhancement:**

Appsody CLI supports passing `--docker-options` to it.  Codewind should use that for passing environment, either using `--env` or `--env-file` (TBD) to Appsody

**Proposed solution:**

**Comment by makandre** [comment]
One other thing needed is for Codewind to re-build the project (i.e. re-invoke `appsody run`) when the `env.list` file changes.  But currently `detectChangeByExtension = true` for `ShellExtensionProject` means that this does not happen.  This would need to be enhanced to allow certain files to trigger Codewind re-build.

https://github.com/eclipse/codewind/blob/master/src/pfe/file-watcher/server/src/projects/ShellExtensionProject.ts#L88

**Comment by makandre** [comment]
Discuss with appsody team; they made `-e`/`--env` flag take effect on local and k8s, however it's preferable for us to use `--env-file` (PR https://github.com/eclipse/codewind-appsody-extension/pull/73 passes `--env-file`)

Opened followup issue https://github.com/appsody/appsody/issues/784 on appsody

**Comment by micgibso** [comment]
Epic #934 , this not yet ready for doc

**Comment by makandre** [comment]
The name of the file is being changed from `env.list` to `env.properties`.  See https://github.com/eclipse/codewind/issues/1692

**Comment by sghung** [comment]
TODO: draft up the content for ID to pick up. TBD by Sarah as to where this content will be placed.

Remember to add note to not check this into a repository. May want to put example of what an env.properties file looks like.

**Comment by makandre** [comment]
Draft doc: @sishida 

### Defining Environment Variables for Appsody Projects

To define environment variables that would take effect in an appsody application:

1.  Create a file named `env.properties` in the root of the appsody project
2. Define your envirnoment variables in this file using standard properties format, i.e. one `name=value` entry per line
3. If autobuild is enabled, Codewind will automatically rebuild the project to pick up the environment values.  Otherwise, the new values will take effect the next time the project is rebuilt.

> Note: You should avoid committing the `env.properties` file to your source repository if it contains sensitive information such as passwords

**Comment by sishida** [comment]
@makandre Could you please review this PR and add your approval if it looks good to go? I just added some edits to the content that you originally provided. Thank you! :)

**Comment by sishida** [comment]
File changed in the master branch: https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/importing-existing-projects.md

Files changed in 0.8.0:
1️⃣ https://github.com/eclipse/codewind-docs/blob/0.8.0/docs/_documentations/mdt-vsc-importedprojects.md
2️⃣ https://github.com/eclipse/codewind-docs/blob/0.8.0/docs/_documentations/mdt-eclipse-importedprojects.md

**Comment by sishida** [comment]
ID content is merged. Closing this issue.
