### ISSUE TITLE
Cwctl not updating pre-existing roles when installing Codewind

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#1402]
Currently when Cwctl installs Codewind onto Kubernetes, it creates a cluster role named `eclipse-codewind-x.x.dev`, where `x.x.dev` is the corresponding version (like 0.7.0). However, if that role already exists, Cwctl doesn't re-create or update the existing role, it just re-uses it.

That would be fine, except for when the cluster role changes (most likely during development, it's unlikely the role will change within a release), Cwctl won't update the role and the old roles will be used instead, potentially causing issues.

There's two possible solutions to this:
- Create a namespaced, per-workspace role for each Codewind instance (involves switching from `ClusterRole` to `Role` and giving each role a unique name)
- If Cwctl finds that a cluster role already exists when installing Codewind, it should update it, to ensure the proper rights are given to Codewind

**Comment by markcor11** [comment]
I prefer option 2 (update the existing cluster roles rather than create namespaced Roles because all deployments of that version will be able to inherit the same role set in one hit (if we release a role patch) without having to patch each deployment in each namespace separately.

**Comment by johnmcollier** [comment]
@markcor11 That sounds good to me

**Comment by malincoln** [comment]
@johnmcollier pls verify and close.  Thanks

**Comment by malincoln** [comment]
@johnmcollier pls verify and close. Thanks

**Comment by johnmcollier** [comment]
Verified in the last release, and fixed.
