### ISSUE TITLE
[Eclipse IDE] User is prompted to install docker containers before creating remote projects

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#1403]
I've got Codewind installed on OCP4, with the Eclipse IDE plugin connected to it. I do not have local Codewind running on my machine. When I go to create a project, it tells me that `Codewind requires the installation of Docker containers to run`, if I hit no, it does not let me create a project 
<img width="533" alt="Screen Shot 2019-12-05 at 5 14 24 PM" src="https://user-images.githubusercontent.com/6880023/70278839-04636980-1783-11ea-8de4-a98d366d1387.png">

Video: https://ibm.box.com/s/1ditw4zjmnr0ny7a3uowbj3et6p7oqha

Marking this as a bug and hot since I shouldn't need local Codewind running in order to create projects against a remote Codewind

**Comment by johnmcollier** [comment]
If local Codewind is installed, then `Stopped` then projects can be created fine.

But you also can't create projects for remote connections while local Codewind is starting or stopping.

**Comment by eharris369** [comment]
I think I already fixed this with #1393.

**Comment by johnmcollier** [comment]
@eharris369 I pulled down the latest Eclipse plugin as of 4pm yesterday, so that should've had the fix in it, but let me pull down the latest again to double check

**Comment by johnmcollier** [comment]
@eharris369 I can't reproduce on the latest driver now, so closing. Thanks!
