### ISSUE TITLE
[Eclipse IDE] Users able to create/build Codewind-style projects without setting a push registry

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#1405]
**Codewind version:** latest
**OS:** macOS

**IDE extension version:** latest
**IDE version:** Eclipse IDE 4.13
**Kubernetes cluster:** OpenShift 4.2

**Description:**
I've installed Codewind on OCP4.2 and pointed the Eclipse plugin for Codewind at it. If I create a Codewind style project without first designated a `Push Registry` in the `Manage Container Registries` view, I will get prompted with:
<img width="525" alt="Screen Shot 2019-12-05 at 6 09 11 PM" src="https://user-images.githubusercontent.com/6880023/70282067-c23e2600-178a-11ea-9d2f-4ad9a9ce1f1b.png">

However, if I click `No`, the project still gets created and the build fails because no push registry was set up. We should instead prevent any Codewind-style projects from getting created until there's a designated push registry for it.

**Steps to reproduce:**
1. Install the latest Codewind Eclipse plugin and use `cwctl` to install Codewind on Kubernetes
2. Create a remote Codewind-style project (e.g. Go) without adding a container registry and designating a push registry
3. You will get prompted saying a `Push registry` is needed. Click no
4. The project will still get created and built.

**Comment by eharris369** [comment]
I thought users would be able to create a push registry later and rebuild but it turns out they can't!!  They have to remove the project from the connection, create the push registry and add it again which is horrible so I will force them to create the push registry or cancel - not create the project at all.

**Comment by eharris369** [comment]
Fixed by: https://github.com/eclipse/codewind-eclipse/pull/460

**Comment by malincoln** [comment]
@johnmcollier pls verify and close. Thanks
