### ISSUE TITLE
cwctl project sync command is crashing on HTTP Post in remote scenario

### ISSUE THREAD

**Issue by jgwest** [eclipse/codewind#1411]
In the Codewind remote scenario, using the latest images/tools, the `cwctl project sync` command is crashing when it is called by the filewatcher (stack trace below).

Fortunately, from looking at the cwctl sync.go code and the stack trace, it appears to be due to the HTTP Post request attempting to validate the HTTPS certificate/hostname and failing (and consequently panicing). The specific line is here:
https://github.com/eclipse/codewind-installer/blob/master/pkg/project/sync.go#L207

**EDIT**: It looks like the PUT request needs to be fixed as well, and there may be others HTTP requests that need to be updated: https://github.com/eclipse/codewind-installer/blob/master/pkg/project/sync.go#L168

This should be easy to fix, we just need to update the HTTP(S) code in sync.go to disable cert checking AND hostname checking (in Java, at least, these two had to be done separately). I had to do this for the [Node.js filewatcher](https://github.com/jgwest/codewind-filewatchers/blob/master/Filewatcherd-TypeScript/src/lib/HttpGetStatusThread.ts#L78) and the [Java filewatcher](https://github.com/eclipse/codewind-eclipse/blob/master/dev/org.eclipse.codewind.filewatchers.core/src/org/eclipse/codewind/filewatchers/core/internal/HttpUtil.java#L240), and likewise the IDE folks had to make the same changes on their side. 

Stack trace:
```
[December 6, 10:20:24.392] [113.145] ! ERROR !  Error running 'project sync' installer command panic: Post https://codewind-gatekeeper-k3uadv1t.apps.makandre42.os.fyre.ibm.com/api/v1/projects/e8799280-183b-11ea-a905-4b8bb8b8111c/upload/end: x509: certificate is valid for localhost, not codewind-gatekeeper-k3uadv1t.apps.makandre42.os.fyre.ibm.com
goroutine 1 [running]:
github.com/eclipse/codewind-installer/pkg/project.completeUpload(0x7ffeefbff85a, 0x24, 0xc0004a9d00, 0x8, 0x8, 0x0, 0x0, 0x0, 0xc000042690, 0x44, ...)
    /home/jenkins/agent/src/github.com/eclipse/codewind-installer/pkg/project/sync.go:207 +0x280
github.com/eclipse/codewind-installer/pkg/project.SyncProject(0xc0002d5760, 0x21c31d1, 0x4)
    /home/jenkins/agent/src/github.com/eclipse/codewind-installer/pkg/project/sync.go:98 +0x5dc
github.com/eclipse/codewind-installer/pkg/actions.ProjectSync(0xc0002d5760)
    /home/jenkins/agent/src/github.com/eclipse/codewind-installer/pkg/actions/project.go:46 +0x74
github.com/eclipse/codewind-installer/pkg/actions.Commands.func4(0xc0002d5760, 0x0, 0xc00021c8d0)
    /home/jenkins/agent/src/github.com/eclipse/codewind-installer/pkg/actions/commands.go:118 +0x2b
github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli.HandleAction(0x1fbe760, 0x225d4d0, 0xc0002d5760, 0xc0002d5760, 0x0)
    /home/jenkins/agent/src/github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli/app.go:514 +0xbe
github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli.Command.Run(0x21c3329, 0x4, 0x0, 0x0, 0xc0001ea030, 0x1, 0x1, 0x22131dd, 0x42, 0x0, ...)
    /home/jenkins/agent/src/github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli/command.go:171 +0x4a4
github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc000218000, 0xc0002d54a0, 0x0, 0x0)
    /home/jenkins/agent/src/github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli/app.go:395 +0x877
github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli.Command.startApp(0x21c4f3e, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x21d6a14, 0x18, 0x0, ...)
    /home/jenkins/agent/src/github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli/command.go:383 +0x808
github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli.Command.Run(0x21c4f3e, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x21d6a14, 0x18, 0x0, ...)
    /home/jenkins/agent/src/github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli/command.go:103 +0x8ef
github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli.(*App).Run(0xc0002e5dc0, 0xc000038090, 0x9, 0x9, 0x0, 0x0)
    /home/jenkins/agent/src/github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli/app.go:265 +0x70b
github.com/eclipse/codewind-installer/pkg/actions.Commands()
    /home/jenkins/agent/src/github.com/eclipse/codewind-installer/pkg/actions/commands.go:849 +0x77d3
main.main()
    /home/jenkins/agent/src/github.com/eclipse/codewind-installer/cmd/cli/main.go:26 +0x2c
```

Full FW log:
[filewatcherd-1(1).log](https://github.com/eclipse/codewind/files/3932975/filewatcherd-1.1.log)

**Comment by jopit** [comment]
So without this being fixed, files don't sync at all, right?

**Comment by jgwest** [comment]
The actual file upload is done by a PUT request (not the POST that is crashing), but that PUT request just buries it's errors without logging them, so it's likely that the actual file transfer is failing too, it's  just not being logged.

So:
- No files being transferred (no logging of these errors)
- And likewise sync is not informing PFE that the transfer is complete (this is the part that is actually crashing)

**Comment by johnmcollier** [comment]
There's something else wrong going on with the sync. I did a quick test change that added `InsecureSkipVerify` setting to sync.go, and while it got rid of any errors in the logs and it seemed the sync command ran fine, they still weren't getting synced to PFE:
```
[December 6, 13:31:06.552] [382.601] Calling cwctl project sync with: { [project] [sync] [-p] [/Users/johncollier/codewind-workspace/gogogogo] [-i] [de50de70-1855-11ea-a7bf-c1d85e939f8a] [-t] [1575656874215] }
[December 6, 13:31:07.963] [384.012] Successfully ran installer command: [project] [sync] [-p] [/Users/johncollier/codewind-workspace/gogogogo] [-i] [de50de70-1855-11ea-a7bf-c1d85e939f8a] [-t] [1575656874215]
[December 6, 13:31:07.964] [384.013] Output:Status: 200 OK

[December 6, 13:31:07.964] [384.013] Updating timestamp to latest: 1575657066553
```

**Comment by tobespc** [comment]
have recreated and now working on a solution

**Comment by stalleyj** [comment]
@jgwest The first fix required is for the various flavours of FW daemon to call cwctl with the global --insecure flag. The files are then uploaded successfully but the upload/end is not working correctly, continuing to investigate this.

**Comment by tobespc** [comment]
issue with cwctl is that we weren't calling the upload/end with the necessary security.  Have a fix going into the installer to resolver this

**Comment by stalleyj** [comment]
Also made a fix to PFE to check for undefined modifiedFiles/deletedFiles https://github.com/eclipse/codewind/pull/1432, https://github.com/eclipse/codewind/pull/1433

**Comment by jgwest** [comment]
As described above, next step is for me (in the Filewatchers) to add `--insecure` flag whenever we are invoking `cwctl project sync`. PRs incoming...

**Comment by malincoln** [comment]
@jgwest does anyone else need to verify?
