### ISSUE TITLE
Fix registrysecrets API error handling

### ISSUE THREAD

**Issue by maysunfaisal** [eclipse/codewind#1412]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**
When service account patch fails, GET API returns the new list from Docker Config which it should not because the Codewind Secret create and/or Service Account patch failed.

Revert changes to the Docker config when this happens.

Applies to POST and DELETE.

![image (6)](https://user-images.githubusercontent.com/31771087/70337609-71c1d980-1819-11ea-90a2-515f1b843aaa.png)

@tetchel 

**Steps to reproduce:**

**Workaround:**

**Comment by jgwest** [comment]
@maysunfaisal: Could not find label: kind/hot

**Comment by tetchel** [comment]
well, it should return the new list, but the new list should equal the old list because we failed to modify it :P

**Comment by maysunfaisal** [comment]
@tetchel changes have been merged

**Comment by tetchel** [comment]
neato

**Comment by malincoln** [comment]
@tetchel @maysunfaisal can you verify and close?  Thanks
