### ISSUE TITLE
[VS Code/Hybrid] I only get prompted once to enter an image push registry

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#1423]
**Codewind version:** latest
**OS:** Mac OS

**IDE extension version:** latest
**IDE version:**  1.40.2
**Kubernetes cluster:** OCP 4

**Description:**
When I go to create a project for the first time, without having entered an image push registry, I'll get prompted by VS Code:
![Screen Shot 2019-12-06 at 5 30 57 PM](https://user-images.githubusercontent.com/6880023/70361019-3392dd00-184e-11ea-8de9-e4fc59c4c115.png)

However, if I don't end up setting up a registry (or hit the `x` button to dismiss), the next time I go to create a Codewind-style project I won't be prompted and the project will get created and fail to deploy, as no registry is set.

Video: https://ibm.box.com/s/m3vvicnrxkkkjjd8sxvybc5t72sng40k

**Steps to reproduce:**
1. Connect Codewind for VS Code to a remote install of Codewind
2. Go to create a Codewind-style project, you'll get prompted by the IDE to set a registry.
3. Dismiss the dialog
4. Create another Codewind-style project. You won't get prompted this time.

**Workaround:** 
Right click on the connection and select `Image Registry Manager` and add your registry there.

**Comment by tetchel** [comment]
that's not right
