### ISSUE TITLE
SVT: [Che] Strange behavior in the command palette when writing or deleting values ​​to add a new Image Registry

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#1424]
**Codewind version:** [0.7.0](https://raw.githubusercontent.com/eclipse/codewind-che-plugin/0.7.0/devfiles/0.7.0/devfile.yaml)
**OS:** Red Hat Enterprise Linux 7 (64 bit)

**Che version:** 7.3.1
**Kubernetes cluster:** OKD/Openshift

**Description:** Strange behavior in the command palette when writing or deleting values ​​to add a new Image Registry. Here is a video as a demonstration:

[Screen Recording 2019-12-08 at 11.09.16 AM.mov.zip](https://github.com/eclipse/codewind/files/3936522/Screen.Recording.2019-12-08.at.11.09.16.AM.mov.zip)

**Steps to reproduce the problem:**
1. Install Eclipse Che
2. Deploy a Codewind workspace
3. Right click on "Projects"
4. Click on "Image Registry Manager"
5. Add a new Image Registry

@jagraj

**Comment by tetchel** [comment]
this is a theia UI bug, I'm not sure if there's anything I can do, which browser are you using?

**Comment by sujeilyfonseca** [comment]
Google Chrome

**Comment by tetchel** [comment]
I opened a theia issue https://github.com/eclipse-theia/theia/issues/6886 so hopefully they can reproduce and look into this.
