### ISSUE TITLE
Enhancement/Request : PPC64LE version of cwctl

### ISSUE THREAD

**Issue by hhellyer** [eclipse/codewind#1426]
@vrushaliinamdar commented on [Mon Dec 09 2019](https://github.com/eclipse/codewind-installer/issues/271)

Hi Team,

Recently, I have built the "ppc64le" architecture specific version of cwctl binary. Please let me know if it is possible to make this binary available for download.

The steps I followed to build are:
**OS : rhel7.7 / ppc64le**

1. Install dep
2. Clone codewind-installer source code
3. cd into the codewind-installer directory
4. run the command `dep ensure -v`
5. Check if you have a vendor folder within your project
6. run the command `GOOS=linux GOARCH=ppc64le go build -o cwctl-ppc64le cmd/cli/main.go`

This successfully generated the cwctl binary and I have also validated and used in the "start.sh" script under eclipse/codewind repository.

Please let me know the feasibility and also let me know if I can help in some way.

Regards,
Vrushali

**Comment by vrushaliinamdar** [comment]
@hhellyer @tetchel Any updates on this ?

**Comment by vrushaliinamdar** [comment]
Hi Folks,

Is it possible to get PPC64LE version of cwctl this week? Please let me know if you need any help.

**Comment by hhellyer** [comment]
@vrushaliinamdar - I've added a PPC64LE build to the Jenkins file. You can now find a ppc64le build in the binaries produced here:

https://download.eclipse.org/codewind/codewind-installer/master/

(The first build with the binary in is 50.)

Please let us know if it works on your environment. If it does can you close this issue?

**Comment by hhellyer** [comment]
@vrushaliinamdar has confirmed the PPC binaries worked and we can close this issue.
