### ISSUE TITLE
Projects left running over the weekend on open shift will not load

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#1435]
I left 2 go projects running over the weekend on openshift and now they will not load anymore unless I rebuild them.  When I try to load them I get this:

![image](https://user-images.githubusercontent.com/9484320/70450981-9cf33580-1a72-11ea-9667-dc91d7cffb8f.png)

The pod is running and it does not look like it went down:

![image](https://user-images.githubusercontent.com/9484320/70451072-c318d580-1a72-11ea-9f0a-342e93351b06.png)

I tried refreshing the project just to be sure all of the project information was up to date but it did not change anything.

**Comment by makandre** [comment]
Is the route still up?

**Comment by eharris369** [comment]
I rebuilt it so I can't check now.  I will leave some projects running over a couple of days again.

**Comment by jopit** [comment]
I am seeing the same thing, my project running on OpenShift that had a route late last week no longer has a route today.  After rebuilding it, the route shows up again.

**Comment by makandre** [comment]
Was it a properly configured and working route?  While working on Appsody, I noticed my routes disappeared but at the time the route wasn't working properly yet (so I thought that broken routes got garbage collected).  I have not seen my routes disappear recently.

(btw is this hybrid or in Che?)

**Comment by eharris369** [comment]
I could load the applications in the browser fine before.  I left the same projects running overnight and the routes are gone again.  I had rebuilt them yesterday and they were loading fine after the rebuild and now they don't load again this morning.

I rebuilt one of them and the route was restored:
![image](https://user-images.githubusercontent.com/9484320/70534328-d0909700-1b28-11ea-8e2c-92119ff8497d.png)

**Comment by eharris369** [comment]
This is hybrid connecting to Codewind on OpenShift.  I have not seen the same problem connecting to Codewind running on a local Kubernetes (on MAC).

**Comment by markcor11** [comment]
Unable to reproduce this,  I tried with some projects that have been running for 11 days (Openshift 3.11) and 3 days (Openshift 4).  On loading the IDE it reconnects to the cluster and the project status all show as running.

**Comment by tobespc** [comment]
unable to recreate and not been seen since December.  Please feel free to open a new issue if this is still occuring
