### ISSUE TITLE
Cwctl deploying non-PFE deployments as privileged

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#1437]
It appears that `cwctl` is deploying Keycloak, Performance, and Gatekeeper as privileged when only PFE needs to be deployed as privileged. This is because `generateDeployment` is used to create deployments for each of those containers, and it directly hard codes `Privileged`: https://github.com/eclipse/codewind-installer/blob/master/pkg/remote/util.go#L125

We should update `generateDeployment` so that it takes in a boolean indicating whether or not to create a privileged deployment, rather than blindly creating privileged deployments for each container.

**Comment by johnmcollier** [comment]
PR up at https://github.com/eclipse/codewind-installer/pull/277

**Comment by james-wallis** [comment]
@johnmcollier as the PR is in can this be closed?

**Comment by johnmcollier** [comment]
@james-wallis Yup, thanks. Closing this one out.
