### ISSUE TITLE
DELETE /api/v1/imagepushregistry should also remove the image push registry when user deletes from the UI

### ISSUE THREAD

**Issue by maysunfaisal** [eclipse/codewind#1440]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**
Should delete the imagepushregistry defined at `/codewind-workspace/.config/settings.json`

**Comment by rajivnathan** [comment]
Closing this as a dupe of https://github.com/eclipse/codewind/issues/1746
