### ISSUE TITLE
Upgrade kubernetes-client version in Portal and Turbine

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#1441]
Portal and Turbine currently use kubernetes-client 6.11.0, which has a max supported API version of Kube 1.10. 

If we move up to a newer version of `kubernetes-client`, its Kube 1.13 client comes with typings for typescript, allowing for a **much** better developing experience for Turbine (which up to this point has had no typings for `kubernetes-client`). Moving up to a higher Kube API version also allows us to (eventually) make use of resources that are only available on newer Kuberntes versions (such as ephemeral containers in Kube 1.16)

If we move Turbine's kubeclient up, we should also move the corresponding kubeclient in Portal up too, just to ensure things are common between the two.

**Comment by tobespc** [comment]
this has now been done
