### ISSUE TITLE
Image Registries panelling design doesn't seem right (vscode)

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#1451]
I'm using the vscode Image Registries page and the font being used looks really out of place with the rest of codewind.  The font is very large and seems to be in bold.

**Comment by tetchel** [comment]
can you post a screenshot, it should look exactly like the Template Sources page

**Comment by tetchel** [comment]
![image](https://user-images.githubusercontent.com/8888438/70543341-3fc1b780-1b38-11ea-9324-f36d69c7308d.png)

**Comment by tobespc** [comment]
verified, all ok
