### ISSUE TITLE
make cwctl project create consistent, more user friendly and reliable 

### ISSUE THREAD

**Issue by stalleyj** [eclipse/codewind#1452]
**Description:**
The CLI command to create a project is inconsistent in usage with the rest of the CLI making it difficult to use and maintain. The command and it's various parameters needs to be fixed and the documentation/tests updated to reflect the changes. 
For example, the path to put the project is not passed as --path VALUE but just assumed to be the first parameter, the documentation is incomplete, etc 

**Steps to reproduce:**

**Workaround:**

**Comment by stalleyj** [comment]
This issue could be fixed as part of this https://github.com/eclipse/codewind/issues/1475

**Comment by maysunfaisal** [comment]
FYI, This PR has broken https://github.com/eclipse/codewind/issues/1829

**Comment by jcockbain** [comment]
Yes, my bad sorry. I missed adding projectValidate back inside the create command here https://github.com/eclipse/codewind-installer/pull/317/files#diff-d1f23fab5d9fe727381fb63db537dcbdL77. Mark is making the change. Thanks for picking that up.
