### ISSUE TITLE
Add a proper version to cwctl

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#1454]
cwctl had a version in 0.6.1, but is still `x.x.dev` in 0.7. 

That's the same version returned in the environment in codewind-on-kube, and it's used in the kube metadata too. We need to version it 0.7.0 before we ship so that we don't have production installs that use the dev version

**Comment by tobespc** [comment]
installer changed

**Comment by malincoln** [comment]
@tetchel pls verify and close.  Thanks
