### ISSUE TITLE
cwctl install remote still pulls "latest" images instead of versioned ones

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#1455]
When you install codewind on kube with cwctl 0.7.0, you get the latest images. If you have the 0.7.0 cwctl, you should get the 0.7.0 images.

This may be related to / resolved by #1454

**Comment by tobespc** [comment]
fixed by the change to #1454

**Comment by malincoln** [comment]
@tetchel pls verify and close.  Thanks
