### ISSUE TITLE
On Windows, the 'file-changes` path is incorrect with project created via Eclipse (preventing auto build)

### ISSUE THREAD

**Issue by jgwest** [eclipse/codewind#1458]
After creating a Java project in Eclipse, and targeting a remote PFE, I noticed that auto-build wasn't working. 

I checked the filewatcher log, and noticed the following error:
```
Dec 10 11:00:45.791 AM [1361.032] ! ERROR ! Unable to issue get request to https://codewind-gatekeeper-k400t1o6.9.30.147.24.nip.io java.lang.IllegalArgumentException: This function does not support Windows-style paths.
```

This is due to PFE `watchlist` endpoint returning the filewatcher a `pathToMonitor` path in an invalid format. Here is the GET request received by the filewatcher:
```json
{
  "projects": [
    {
      "pathToMonitor": "C:\\delme\\asda8s09d8a90d8a09s8d09a8d4\\MyJavaProj2", <--- This is the invalid path
      "projectID": "8a958b30-1b63-11ea-be5d-872903c28db6",
      "ignoredPaths": [
        "/.project",
        "/Dockerfile-tools",
        "/target",
        "/mc-target",
        "/cli-config.yml",
        "/README.md",
        "/Jenkinsfile",
        "/.cfignore",
        "/load-test*",
        "*/node_modules*",
        "*/.git/*",
        "*/.DS_Store",
        "*/*.swp",
        "*/*.swx",
        "*/4913",
        "*/.dockerignore",
        "*/.gitignore",
        "*/*~",
        "/.settings",
        "/localm2cache.zip",
        "/libertyrepocache.zip"
      ],
      "projectWatchStateId": "532a893a9262bb1ca4effd9fd4397dd1"
    }
  ]
}
```

The `pathToMonitor` field should always use Unix-style paths for this field (while preserving the Windows drive letter). So on Windows, the pathToMonitor field should be: `/c/delme/asda8s09d8a90d8a09s8d09a8d4/MyJavaProj2`.  (This has always been the format for this field since the inception of the filewatcher)

Reproduced on master (12/10) Eclipse/CWCTL,/PFE. Remote cluster was Fyre-hosted OCP4.2.

#### Steps to reproduce:
(I had a local PFE installed, but not running.)
1. Setup a remote connection in Eclipse. Right click on remote connection and select `Create New Project`.
2. Create a WebSphere Liberty Microprofile project. Wait for it to import and build.
3. Open the filewatcher log, under `(eclipse workspace directory)/.metadata/filewatcherd-1.log`.

You will see the following error message in the logs repeated every ~5 seconds:
```
Dec 10 11:00:45.791 AM [1361.032] GET request completed, for https://codewind-gatekeeper-k400t1o6.9.30.147.24.nip.io/api/v1/projects/watchlist. Response: {  "projects": [    {      "pathToMonitor": "C:\\delme\\asda8s09d8a90d8a09s8d09a8d4\\MyProj3",      "projectID": "20154360-1b66-11ea-be5d-872903c28db6",      "ignoredPaths": [        "/.project",        "/Dockerfile-tools",        "/target",        "/mc-target",        "/cli-config.yml",        "/README.md",        "/Jenkinsfile",        "/.cfignore",        "/load-test*",        "*/node_modules*",        "*/.git/*",        "*/.DS_Store",        "*/*.swp",        "*/*.swx",        "*/4913",        "*/.dockerignore",        "*/.gitignore",        "*/*~",        "/.settings",        "/localm2cache.zip",        "/libertyrepocache.zip"      ],      "projectWatchStateId": "865b0b7366d8fe96df4e15ec028a81ce"    }  ]}
Dec 10 11:00:45.791 AM [1361.032] ! ERROR ! Unable to issue get request to https://codewind-gatekeeper-k400t1o6.9.30.147.24.nip.io java.lang.IllegalArgumentException: This function does not support Windows-style paths.
        at org.eclipse.codewind.filewatchers.core.PathUtils.normalizeDriveLetter(PathUtils.java:54)
        at org.eclipse.codewind.filewatchers.core.ProjectToWatch.<init>(ProjectToWatch.java:64)
        at org.eclipse.codewind.filewatchers.core.internal.HttpGetStatusThread.doHttpRequest(HttpGetStatusThread.java:259)
        at org.eclipse.codewind.filewatchers.core.internal.HttpGetStatusThread.innerLoop(HttpGetStatusThread.java:160)
        at org.eclipse.codewind.filewatchers.core.internal.HttpGetStatusThread.run(HttpGetStatusThread.java:84)
```

**Comment by malincoln** [comment]
@jopit @eharris369 can you review today to see if anything is needed from Eclipse?  @tobespc can review tomorrow.  Thanks

**Comment by eharris369** [comment]
There shouldn't be anything needed on the Eclipse side if the path format is fixed on the portal side.

**Comment by james-wallis** [comment]
Debugging this on a mac so I'm working on assumptions but I believe that 
```
project.pathToMonitor = projFile.locOnDisk;
//project.pathToMonitor = path.join(projFile.workspace, projFile.directory);
if (process.env.HOST_OS === "windows") {
    project.pathToMonitor = cwUtils.convertFromWindowsDriveLetter(project.pathToMonitor);
}
```
Won't be "windows" in a host environment so the path is not being converted. I've seen that a `isWindowsAbsolutePath` has been added to `sharedFunctions.js` so I'm going to use instead of checking for windows. This will ensure that filewatcher always gets a linux type path.

[project.pathToMonitor](https://github.com/eclipse/codewind/blob/master/src/pfe/portal/modules/User.js#L233)
[isWindowsAbsolutePath](https://github.com/eclipse/codewind/blob/master/src/pfe/portal/modules/utils/sharedFunctions.js#L153)

**Comment by james-wallis** [comment]
PR opened https://github.com/eclipse/codewind/pull/1500. Need someone with a windows machine to test it.

**Comment by malincoln** [comment]
@jgwest are you or someone else with a Windows machine able to test?

**Comment by james-wallis** [comment]
@jgwest looks like my `fixes` message in the PR has caused this to close. Pasting your message from our Slack conversation as it indicates it can stay closed.
```
Jonathan West: 4:58 PM
yep, your steps are good to ensure it is no longer reproducible, and I have approved... do you need me to merge it?
```

**Comment by malincoln** [comment]
@jgwest if you've verified, can you close it?  Thanks

**Comment by jgwest** [comment]
It looks like the Codewind build failed that contained the PR for this fix, but as soon as that is in I will verify. But AFAICT the steps that @james-wallis already tested on his own Windows VM means it should just be a formality.

**Comment by josephca** [comment]
The master build went fine with the PR and fix.  
https://ci.eclipse.org/codewind/job/Codewind/job/codewind/job/master/349/

**Comment by jgwest** [comment]
Moving from Verify back to In Progress as a subset of the problem still occurs:

Happy to report that the `GET /watchlist` endpoint now output the `pathToMonitor` in the correct format 🎉 , but unfortunately looks like the WebSocket `/file-changes` endpoint is still using the old form.

#### Filewatcher Log:
```json
# Dec 13 2:27:11.027 PM [226.565] Received watch change message from WebSocket: 
{
  "type": "watchChanged",
  "projects": [
    {
      "changeType": "add",
      "projectWatchStateId": "065ae007d5de7dc1ed6917851078bcc1",
      "projectID": "89217d40-1dde-11ea-8b95-216413b89bfe",
      "pathToMonitor": "C:\\delme\\asd8sa9d8sa098d09sada2\\MyJavaProj2", <--- problem still occurs in the WebSocket
      "ignoredPaths": [
        "/.project",
        "/Dockerfile-tools",
        "/target",
        "/mc-target",
        "/cli-config.yml",
        "/README.md",
        "/Jenkinsfile",
        "/.cfignore",
        "/load-test*",
        "*/node_modules*",
        "*/.git/*",
        "*/.DS_Store",
        "*/*.swp",
        "*/*.swx",
        "*/4913",
        "*/.dockerignore",
        "*/.gitignore",
        "*/*~",
        "/.settings",
        "/localm2cache.zip",
        "/libertyrepocache.zip"
      ],
      "projectCreationTime": 1576265221615
    }
  ]
}
# Dec 13 2:27:11.028 PM [226.566] !!! SEVERE !!! WebSocket onError throwable: java.lang.IllegalArgumentException: This function does not support Windows-style paths. for url: wss://codewind-gatekeeper-k44j7r0p.9.30.180.118.nip.io/websockets/file-changes/v1
```

#### Full Log:
```
Dec 13 2:25:41.340 PM [136.879] Updating timestamp to latest: 1576265140084
Dec 13 2:26:44.212 PM [199.750] Initiating GET request to https://codewind-gatekeeper-k44j7r0p.9.30.180.118.nip.io/api/v1/projects/watchlist
Dec 13 2:26:44.212 PM [199.750] IDE returned a new security token to filewatcher: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAi
Dec 13 2:26:44.540 PM [200.078] GET request completed, for https://codewind-gatekeeper-k44j7r0p.9.30.180.118.nip.io/api/v1/projects/watchlist. Response: {  "projects": [    {      "pathToMonitor": "/c/delme/asd8sa9d8sa098d09sada2/MyJavaProj",      "projectID": "2b504ed0-1dde-11ea-8b95-216413b89bfe",      "ignoredPaths": [        "/.project",        "/Dockerfile-tools",        "/target",        "/mc-target",        "/cli-config.yml",        "/README.md",        "/Jenkinsfile",        "/.cfignore",        "/load-test*",        "*/node_modules*",        "*/.git/*",        "*/.DS_Store",        "*/*.swp",        "*/*.swx",        "*/4913",        "*/.dockerignore",        "*/.gitignore",        "*/*~",        "/.settings",        "/localm2cache.zip",        "/libertyrepocache.zip"      ],      "projectWatchStateId": "657d5680ae96c6ce24c3dfa35dda3e0d",      "lastSyncTime": 1576265064214    }  ]}
Dec 13 2:26:44.540 PM [200.078] Examining received file watch state, from GET request
Dec 13 2:26:44.540 PM [200.078] The project watch state has not changed for project 2b504ed0-1dde-11ea-8b95-216413b89bfe based on the project watch state id.
Dec 13 2:27:11.027 PM [226.565] Received watch change message from WebSocket: {"type":"watchChanged","projects":[{"changeType":"add","projectWatchStateId":"065ae007d5de7dc1ed6917851078bcc1","projectID":"89217d40-1dde-11ea-8b95-216413b89bfe","pathToMonitor":"C:\\delme\\asd8sa9d8sa098d09sada2\\MyJavaProj2","ignoredPaths":["/.project","/Dockerfile-tools","/target","/mc-target","/cli-config.yml","/README.md","/Jenkinsfile","/.cfignore","/load-test*","*/node_modules*","*/.git/*","*/.DS_Store","*/*.swp","*/*.swx","*/4913","*/.dockerignore","*/.gitignore","*/*~","/.settings","/localm2cache.zip","/libertyrepocache.zip"],"projectCreationTime":1576265221615}]}
Dec 13 2:27:11.028 PM [226.566] !!! SEVERE !!! WebSocket onError throwable: java.lang.IllegalArgumentException: This function does not support Windows-style paths. for url: wss://codewind-gatekeeper-k44j7r0p.9.30.180.118.nip.io/websockets/file-changes/v1
Dec 13 2:27:11.032 PM [226.570] WebSocket connection closed with reason: 1006 This function does not support Windows-style paths., for url: wss://codewind-gatekeeper-k44j7r0p.9.30.180.118.nip.io/websockets/file-changes/v1
```

**Comment by malincoln** [comment]
@james-wallis this was moved back to In progress.  Please review.

**Comment by tobespc** [comment]
` but unfortunately looks like the WebSocket /file-changes ` we don't use this anymore ?

**Comment by james-wallis** [comment]
The only other lines that are dependent on Windows are:
https://github.com/eclipse/codewind/blob/master/src/pfe/portal/modules/FileWatcher.js#L418
https://github.com/eclipse/codewind/blob/master/src/pfe/portal/modules/FileWatcher.js#L452

If we're having problems with `pathToMonitor` elsewhere it will be better to ensure that `project.pathToMonitor` is only set once.

**Comment by malincoln** [comment]
Discussion with @tobespc on checkpoint.  @stalleyj fix should land today.

**Comment by stalleyj** [comment]
I've created a PR for the 0.7.0 branch that takes @james-wallis changes and also fixes the content of the socket messages to FW daemon. This is just being tested on a windows machine. Will put a more robust fix in master that sets the pathToMonitor at project creation time.

**Comment by tobespc** [comment]
fix is in

**Comment by malincoln** [comment]
@jopit who can verify the fix (believe Jonathan is out now)?

**Comment by jopit** [comment]
@elsony does Jonathan have a backup who can verify this fix?

**Comment by elsony** [comment]
@lentheivendra will be verifying this.

**Comment by lentheivendra** [comment]
Verified on latest 0.7.0 Codewind (eclipse on Windows 10) + OKD 3.11 remote.  The filewatcherd log shows the correct paths being used.

**Comment by elsony** [comment]
Closing this off based on the previous comment from Len.
