### ISSUE TITLE
sync is not working on vscode with latest filewatcher demon

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#1459]
project sync appears to be broken on the latest filewatcher demon in vscode.  From my testing, I can see that the inital upload and bind works but the gatekeeper is never called when a sync should happen.  Will investigate cwctl but @jgwest could you check the filewatcher is ok please.   I can't find the filewatcher log on my machine to check that

**Comment by malincoln** [comment]
@tetchel can you help investigate?  Thanks

**Comment by malincoln** [comment]
@tobespc says this is working fine now.
