### ISSUE TITLE
Unstyled (Times New Roman) text in the Codewind Connection settings page on Windows

### ISSUE THREAD

**Issue by jgwest** [eclipse/codewind#1463]
With latest Codewind VSCode (self-hosted, in this case), on Windows, the remote connection info page seems to use non-styled (eg Times New Roman) text, which I strongly presume is not intentional. In contrast, the project info page looks fine.

See screenshot for details:

![it-was-the-best-of-times-new-roman](https://user-images.githubusercontent.com/7594762/70555632-71914900-1b4d-11ea-94ea-8e9b31df9e5d.png)

Specifically the text "Fill in the fields", "Codewind Gatekeeper URL", "Username, "Password" etc

**Comment by johnmcollier** [comment]
Same as on Linux (though I chalked this up to being on a quite back level VS Code version)
<img width="892" alt="Screen Shot 2019-12-10 at 1 42 25 PM" src="https://user-images.githubusercontent.com/6880023/70558461-efa41e80-1b52-11ea-89c6-f6b781345763.png">

**Comment by jgwest** [comment]
Verified, thanks Tim!

Button overflows slightly on the top RHS panel but thats for another day:
![image](https://user-images.githubusercontent.com/7594762/70783743-277bb380-1d57-11ea-8704-dba70b0048c2.png)
