### ISSUE TITLE
Image registry password prompt considers certain characters to be illegal

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind#1464]
I tried to set up a new image registry for docker.io.  When I pasted my password into the password prompt, it gives me an error telling me the input contains illegal characters.  It also displays the "invalid" password, which is not good from a security point of view.

**Comment by tetchel** [comment]
Lol, ouch

**Comment by jopit** [comment]
Reopening because this isn't in the 0.7.0 branch yet

**Comment by tetchel** [comment]
Fixed in both branches now https://github.com/eclipse/codewind-vscode/pull/345
