### ISSUE TITLE
[Hybrid] Make it easier to uninstall remote Codewind with cwctl

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#1465]
With https://github.com/eclipse/codewind/issues/1287, we added a command to cwctl to uninstall remote Codewind on Kube.

Currently, the command to uninstall Codewind from cwctl is:
```
cwctl remove remote \
    --namespace <namespace> \
    --workspace <workspaceID>
```

And then to remove keycloak
```
cwctl remove keycloak \
    --namespace <namespace> \
    --workspace <workspaceID>
```

The problem is that there isn't any easy way for the person uninstalling Codewind to look up the workspace ID. They have to do the following to uninstall:
1. Run `kubectl get pods --show-labels --namespace <namespace>` to show the labels for all of the pods in some given namespace
2. Find the workspace ID that matches the remote Codewind instance that they want to uninstall. 
3. Run the `cwctl remove remote --namespace <namespace> --workspace <workspaceID>` to uninstall codewind
4. (Optional) Run `cwctl remove keycloak --namespace <namespace> --workspace <workspaceID>` to uninstall keycloak

There should be a way for the user to easily retrieve the workspace IDs for all given Codewind (and Keycloak) installs with `cwctl`. Something like a `cwctl remote list` command that displays the following:
```
$ cwctl remote list
Workspace ID     Namespace       Version      Date Installed
k3ugr236         codewind        0.7.0        2019-12-06
k8dcg253         default         master       2019-12-10
```

**Comment by johnmcollier** [comment]
This issue could be alternately titled: `Add cwctl command to list remote installs`

**Comment by GeekArthur** [comment]
You can use `oc get po --selector=app=codewind-pfe -o jsonpath='{.items[*].metadata.labels.codewindWorkspace}'` to get the workspace ID, probably `cwctl` can wrap it and display it to user.

**Comment by johnmcollier** [comment]
We could wrap the call to `oc`/`kubectl`, but I'd rather we call out to client-go from `cwctl`.

**Comment by GeekArthur** [comment]
Yeah, that's better than wrapper.

**Comment by markcor11** [comment]
The gatekeeper environment API shows the workspace ID. However I like the idea of being able to scan the cluster (or scope it to a namespace) and have cwctl report what it finds.

**Comment by tobespc** [comment]
> This issue could be alternately titled: `Add cwctl command to list remote installs`

Lets go with this solution for now.  As we move to use operators, this is likely to all change anyway
