### ISSUE TITLE
cwctl project create can fail if the path parameter is not an empty directory

### ISSUE THREAD

**Issue by stalleyj** [eclipse/codewind#1475]
**Codewind version:**
0.7.0.
**OS:**
Mac

**Description:**
cwctl project create will fail in a fairly spectacular fashion if the path value passed is not an empty directory. The process is eventually killed by the os because under the covers we are walking the entire directory, attempting to replace the PROJ_NAME_PLACEHOLDER.

**Steps to reproduce:**
 ./cwctl project create /Users/stalleyj --url https://github.com/microclimate-dev2ops/nodeExpressTemplate

A possible solution is to require the path to be an empty directory and fail if it is not.

**Comment by jcockbain** [comment]
@stalleyj this should be fixed now - could you verify?

**Comment by stalleyj** [comment]
@jcockbain I can verify that the problem is fixed but the error message doesn't make sense - "Non empty project at given path". I would suggest this is updated to "Non empty directory provided", can you push a change into https://github.com/eclipse/codewind-installer/pull/317/files ?

**Comment by jcockbain** [comment]
I agree, change pushed

**Comment by stalleyj** [comment]
Verified that new message appears so closing
