### ISSUE TITLE
Add labels to the Docker Project containers started by PFE/Turbine

### ISSUE THREAD

**Issue by james-wallis** [eclipse/codewind#1476]
*This may have been raised before but I couldn't find anything*

**Description of the enhancement:**

Currently in local Docker our project containers start with a `cw-` prefix before their container name (`cw-projectname-123-123-123`). 
The CLI (and potentially other parts) use this to perform queries on the container, for example the `cwctl stop-all` command which stops and removes all the project containers. In this example we search for all the containers with a container name that starts with `cw-` and will remove it, this hasn't caused a problem so far but has the potential to remove a non-codewind project which just happens to start with the prefix.

**Proposed solution:** 

The created projects should have a Docker label added to them so that they can be identified by external service as started/owned by Codewind. 
A couple of ideas could be:
* `Codewind`
* `StartedBy=Codewind`
* `CodewindProject={PROJECT_ID}`

**Implementation details**
* Add the label to the `docker run` rather than appending to a users Dockerfile.
* Use `--label-file` to keep labels consistent and remove the need to manually add individual labels to each `docker run` in Turbine.
  * Using a file also means that if we need to change or add a label to each project container we can do that in a single place.
  * [Docker docs for labels](https://docs.docker.com/engine/reference/commandline/run/#set-metadata-on-container--l---label---label-file)

**Appsody Projects**
Appsody projects have a `--docker-options` flag on the `appsody run` command which should allow us to add the `--label-file` flag when we start up appsody projects.

**Extensions**
For extensions in the future I cannot guarantee that labels can be added to them but neither can we guarantee that we can specify the container name so using labels should make no difference.

**Advantages**
* `cwctl stop-all` can add a filter to use the labels to remove projects.
  * the command can start to use the labels as they are implemented but carry on using `cw-` until they're fully implemented.
* Using labels would mean that in the future we could remove the need to for the long container name we use at the moment and we could allow Docker to assign the names (don't specify a `--name` parameter).

**Comment by johnmcollier** [comment]
@james-wallis We're doing something similar with projects deployed on Kube. We're adding the `projectID=<projectID>` label to all of the Kube resources that are created.

IMO, we should keep things consistent. I'm fine with either `projectID=<projectID>` or `CodewindProject=<projectID>` as the label

**Comment by james-wallis** [comment]
Think `CodewindProject` would be best as it explicitly says that its "ours". Can always have more than one label so both `projectID=<projectID>` and `CodewindProject` so we have consistency with Kube?

**Comment by james-wallis** [comment]
I've just noticed that `docker build` has a `--label` tag (no `--label-file` tag).

I'd now propose that we have :
`docker build --label BuiltBy=Codewind --label projectID=<projectID>`
and
`docker run --label RunBy=Codewind  --label projectID=<projectID>` (Can still use `--label-file` for this part)

Meaning we can track that an image is created by us and separately a container is created by us.

@johnmcollier what are your thoughts on this?

**Comment by elsony** [comment]
Adding a label sounds fine to me.  We already have a specific label for Kube resources that we create so it is good to have the same for the local docker case as well.  We should probably consider to use the same label to make it consistent across the two scenarios.  But with the label value "Codewind" look fine to me.

**Comment by james-wallis** [comment]
I'm only talking about the local Docker environment in this issue, isn't ODO just in Kubernetes environments? Would be good to have labels for them but probably a different issue.

**Comment by elsony** [comment]
ok

**Comment by GeekArthur** [comment]
@james-wallis Yes, odo only supports Kube env (more specifically only OpenShift or OKD). @elsony I think we are able to inject labels by using `kubectl patch` to the kube resources that we want and deployed by odo.

**Comment by elsony** [comment]
@GeekArthur I have created https://github.com/eclipse/codewind/issues/1506 to keep track on the odo scenario on Kube given that this item is for local docker case only.

**Comment by johnmcollier** [comment]
@james-wallis I'm good on that approach: `BuiltBy=Codewind` and  `projectID=<projectID>` sound good to me.

**Comment by james-wallis** [comment]
stale
