### ISSUE TITLE
Fix "More Info" First Install PFE Popup Notification

### ISSUE THREAD

**Issue by thisguy-1** [eclipse/codewind#148]
@tetchel
@sishida 

- [x] "More Info" in PFE Popup doesn't link to an actual page.

- [x] Install PFE Popup must remain after user comes back from "more info" page. If not possible, then a notification must appear or second popup.

**Comment by tetchel** [comment]
second item is https://github.com/eclipse/codewind-vscode/issues/142

**Comment by thisguy-1** [comment]
related to https://github.com/eclipse/codewind/issues/149

**Comment by tetchel** [comment]
this was done a couple weeks back
