### ISSUE TITLE
Can no longer use run.sh to start Codewind

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#1480]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**

After https://github.com/eclipse/codewind-installer/pull/147 was merged, developers can no longer use the `run.sh` script to build and start Codewind for development and debugging.  They'll get this error:

```
CHECKING FOR EXISTING CODEWIND APPS 
Stopping Codewind and Project containers
Removing Codewind docker networks..
Cannot find Codewind images, try running install to pull them
```

The reason is the images built are `codewind-*`, but `cwctl start` now checks for existence of `eclipse/codewind-*` images

**Steps to reproduce:**

**Workaround:**

**Comment by makandre** [comment]
/portal

FYI @jcockbain

**Comment by tobespc** [comment]
so `cwctl install` followed by `cwctl start` works ok

**Comment by tobespc** [comment]
run.sh has never done the install, it builds and runs the code locally

**Comment by makandre** [comment]
If we run `cwctl` install`, I'm guessing that would just pull down images from docker rather than use the images I just built

**Comment by jcockbain** [comment]
I've made https://github.com/eclipse/codewind-installer/pull/288 to revert, as it's the end of the day here and I don't want this to hold up dev for others. All committers have left over here so will need someone else to merge if we need it fixed.

**Comment by jcockbain** [comment]
I'll be working on a solution for #462 tomorrow that works for images both pulled from dockerhub, and built with run.sh.

**Comment by jcockbain** [comment]
PR is merged and I can use run.sh now, @makandre can you verify and close if fixed?

**Comment by makandre** [comment]
Yes, can verify working once again after the revert was merged
