### ISSUE TITLE
SVT: Design for Image Registries' management needs some improvements

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#1483]
**Codewind version:** [0.7.0](https://raw.githubusercontent.com/eclipse/codewind-che-plugin/0.7.0/devfiles/0.7.0/devfile.yaml)
**OS:** Red Hat Enterprise Linux 7 (64 bit)

**Che version:** 7.3.1
**Kubernetes cluster:** OKD/Openshift

**Description:** Design for Image Registries' management needs some improvements:
1. If the namespace is incorrectly selected, projects will not start, and no messages are indicating that the reason why projects are not starting is an incorrect image registry:

<img width="1637" alt="Screen Shot 2019-12-11 at 10 17 17 AM" src="https://user-images.githubusercontent.com/49531960/70640229-a367e580-1c09-11ea-9004-d1510aff8cd6.png">

2. If, after an incorrect registry creation, you try to delete your current registry, it cannot be deleted. This eventually produces an error when trying to create a new registry:

<img width="1109" alt="Screen Shot 2019-12-11 at 11 24 31 AM" src="https://user-images.githubusercontent.com/49531960/70640248-abc02080-1c09-11ea-902c-071cf2e54d19.png">

<img width="1680" alt="Screen Shot 2019-12-11 at 11 23 27 AM" src="https://user-images.githubusercontent.com/49531960/70640250-ae227a80-1c09-11ea-885a-614999b6206a.png">

<img width="1637" alt="Screen Shot 2019-12-11 at 11 17 32 AM" src="https://user-images.githubusercontent.com/49531960/70640264-b2e72e80-1c09-11ea-93f1-84e184fb34b9.png">

3. As @jagraj noted, you cannot add more than one Image Registry with the same address:

<img width="1675" alt="Screen Shot 2019-12-11 at 11 18 35 AM" src="https://user-images.githubusercontent.com/49531960/70640282-b7134c00-1c09-11ea-9a2b-30401a77a06b.png">

@jagraj

**Comment by tetchel** [comment]
3 is by design, a restriction from how container registries work.

I will split 1 and 2 into separate issues.

**Comment by tetchel** [comment]
can we see the pfe logs?

**Comment by tetchel** [comment]
For 2, have you applied the most recent clusterrole yaml? We had to add the permission to delete secrets.

https://github.com/eclipse/codewind-che-plugin/blob/master/setup/install_che/codewind-clusterrole.yaml

**Comment by johnmcollier** [comment]
To elaborate on why 3. is by design: The docker API doesn't support specifying more than one set of credentials for a registry server.

**Comment by sujeilyfonseca** [comment]
Thanks, @tetchel!

[codewind-workspaced1t3j4r0747qrmr5-6948db558-8s9kr.txt](https://github.com/eclipse/codewind/files/3952092/codewind-workspaced1t3j4r0747qrmr5-6948db558-8s9kr.txt)

For #2, the problem was related to the `codewind-clusterrole.yaml`.

**Comment by tetchel** [comment]
kk, so since 2 and 3 are resolved, and 1 is #1484 we can close this one I think

**Comment by sujeilyfonseca** [comment]
Thanks for the explanation, @johnmcollier!

I will proceed to close this GitHub issue since No. 1 is being tracked with https://github.com/eclipse/codewind/issues/1484.
