### ISSUE TITLE
PFE does not update pushregistry if pushregistry namespace is the empty string

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#1486]
Pushregistry namespace needs to be allowed to be `""` because not all registry providers use namespaces

POST /imagepushregistry
`{ operation: "set", address: "docker.io", namespace: "" }`
--> appears to succeed
GET /imagepushregistry
`{ imagePushRegistry: false }`

There is a condition in PFE which basically checks `if (namespace)` which fails if the namespace is the empty string, it needs to be `if (namespace != null)`

And if the namespace is missing, it should respond 400 since the request is missing required fields

**Comment by jagraj** [comment]
SVT also into similar issue.

**Comment by maysunfaisal** [comment]
Dont think its a stopship since its a special case but i have a PR up for it

**Comment by malincoln** [comment]
fix is ready; will go ahead and merge and have @hhellyer review on Monday

**Comment by malincoln** [comment]
@tetchel the fix has been merged into 0.7.0 branch.  Can you test and verify?  Thanks

**Comment by tetchel** [comment]
❤️
