### ISSUE TITLE
SVT:[0.7.0]:Need doc updates for che install.

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#1488]
**Codewind version:** 0.7.0
**OS:** 

**Che version:** 0.7.0
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**
OKD

**Description:**

**Cluster roles**
We need update to doc to apply new cluster roles and also get all config files from 0.7.0 release branch.

https://www.eclipse.org/codewind/mdt-che-installinfo.html#prerequisites
https://www.eclipse.org/codewind/mdt-che-installinfo.html#installing-che-with-chectl
   1. Download the **codewind-che checluster yaml** file to your machine. (This should point to 0.7.0 release).

**Image Registries**

We need to update Che install docs for Image registry feature. User does not have to create registry in "Che" administration page. User has to create new push registry for default projects to work. 

Changes needed in these sections.
https://www.eclipse.org/codewind/mdt-che-installinfo.html#adding-registries-in-che
https://www.eclipse.org/codewind/mdt-che-installinfo.html#confirm-the-docker-registry-secrets

Need new instructions here for the user.
https://www.eclipse.org/codewind/mdt-che-installinfo.html#setting-the-docker-registry

**Steps to reproduce:**

**Workaround:**

**Comment by tetchel** [comment]
should be covered by https://github.com/eclipse/codewind/issues/1178

**Comment by johnmcollier** [comment]
For the items not covered by #1178, I've opened https://github.com/eclipse/codewind-docs/pull/259 to fix

**Comment by maysunfaisal** [comment]
https://www.eclipse.org/codewind/openshiftregistry.html

needs to be modified.

With PR https://github.com/eclipse/codewind-docs/pull/261 changing docs, we need to update this as well. We can remove the screenshots containing Administration tab and Set Deployment Registry and merge the two sets of instructions to fit together.

**Comment by maysunfaisal** [comment]
^ FYI @j-c-berger

**Comment by johnmcollier** [comment]
We also need to update the openshift registry doc to say to use `image-registry.openshift-image-registry.svc:5000` on OCP4

**Comment by j-c-berger** [comment]
@maysunfaisal and @johnmcollier, thanks for the input. Since 1178 is wrapping up, I can start to work on this issue, removing the current screenshots, adding the new one, and making all necessary changes to content. 

Feel free to assign to me.

**Comment by j-c-berger** [comment]
@maysunfaisal, I just had a conversation with ID and Plugin team, and we talked about how quickly this screenshot will become antiquated. So we thought about holding off on screenshot changes for 1488 (focusing only on doc content) and saving the screenshots changes for a later release where they will be more permanent. What do you think?

**Comment by maysunfaisal** [comment]
@j-c-berger sounds good

**Comment by j-c-berger** [comment]
@maysunfaisal, think this doc would still benefit from getting new screenshots?

**Comment by maysunfaisal** [comment]
@j-c-berger I think this doc could do with screenshots rather than putting them in https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/openshiftregistry.md

**Comment by j-c-berger** [comment]
@maysunfaisal, thanks for letting me know. ID has an iteration meeting tomorrow where we'll determine when we can begin work on this issue. I'll update here tomorrow.

**Comment by j-c-berger** [comment]
@maysunfaisal ID discussed screenshots and we want to be careful with them given how quickly they become outdated. If we have so many docs with screenshots that we'll need to continually revisit, it will be easy to forget about screenshots and then unintentionally deliver antiquated, untrue information to users.

**Comment by sishida** [comment]
Screenshots for this documentation weren't deemed essential. Closing this issue.
