### ISSUE TITLE
Codewind.dev Docs - Create "PFE" More Info Page

### ISSUE THREAD

**Issue by thisguy-1** [eclipse/codewind#149]
Work with @thisguy-1, @tetchel, and @sishida to create a page that will link from CW VS Code IDE.

- [x] Explain what is being downloaded by Codewind when they accept the second part of the installation.

- [x]  Must include instructions on how to make the pop-up notification visible again.

- [x]  Provide guidance as to next steps, AFTER PFE is installed (eg. as simple as links)

- [x]  Explore correct terminology for the acronym "PFE" that will make sense to the user

**Comment by tetchel** [comment]
what does pfe have to do with this? it's supposed to abstracted away from the user

**Comment by thisguy-1** [comment]
I'm just referring to figuring out what information is included in the "more info page". What's actually going to be there? If we don't mention PFE, what are we going to say? Also, when a user chacks out whats going on in docker, they do see something called PFE, so we might want to mention that. (some users like to see what's going on in the backend). Not really dictating the terminology that will be in this page, just using PFE as a stand in for whatever we will explain in the page.

**Comment by sishida** [comment]
I can help with the writing of the more info page.

**Comment by thisguy-1** [comment]
https://github.ibm.com/dev-ex/landing-pages/issues/1112

**Comment by sishida** [comment]
Rough draft of text:
"The Codewind installation includes two parts. The first part installs when you Install Codewind from the VS Code Marketplace or when you install by searching in the VS Code Extensions view. The second part installs when you click Install when you are prompted by the dialog box.

After you click Install, the necessary images are downloaded from the internet. Your IDE displays a progress meter to indicate that the installation is being performed as well as messages that state which pieces, such as individual containers, are being installed. When the installation is complete, the extension starts."

**Comment by sishida** [comment]
I have created this PR for Codewind installation info pages: https://github.com/eclipse/codewind-docs/pull/55.

To do:
- In both new files, we need to add the list of images installed.
- If needed, we need to add a section in the Troubleshooting page for PFE info.
- In step 3 "Complete the installation" of the Readme pages for both VS Code and Eclipse, add the link to these new installation info pages.

**Comment by tetchel** [comment]
so i suppose the new pages with permalinks `mdt-eclipse-installinfo` / `mdt-vsc-installinfo.md` added in https://github.com/eclipse/codewind-docs/pull/55 should be linked to from the "more info" buttons?

**Comment by thisguy-1** [comment]
yes, i believe this the page that sarah made which contains the information regarding the the installation of the pfe.

**Comment by thisguy-1** [comment]
Yes. I think that it's in the troubleshooting that we mention the name "PFE". We should also mention how to bring up the install if for some reason they missed all the notifications. Some steps to reset like "you can uninstall and install again". And what to do if they are not prompted immediately to open a workspace.

**Comment by sishida** [comment]
@thisguy-1 We only mention PFE when we tell them to enter the command:
```
## Imported project never builds or starts
To view the status of the imported project, enter the following command:
docker logs codewind-pfe
```
Thus, I don't think we need to define "PFE" in the Troubleshooting doc.

However, I will mention somewhere, maybe in the install info page itself, how to bring up the install if they miss notifications, how to reset the install, and what to do without the prompt. Thanks!

**Comment by sishida** [comment]
@thisguy-1 and @tetchel I have created a PR with more info about troubleshooting specific to installation: https://github.com/eclipse/codewind-docs/pull/116

Could someone please check the accuracy of the update and provide more details for the "Installing the Codewind containers without a prompt" section? Thank you!

**Comment by sishida** [comment]
Removed the "Installing the Codewind containers without a prompt" section.

Merged https://github.com/eclipse/codewind-docs/pull/116.

@tetchel I think this issue is good to close! If so, could you please close it? Thanks! :)
