### ISSUE TITLE
Initial 'templates repos get' is very slow on kube

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#1491]
```
[INFO: 17:22:56.171 CLIWrapper.js:129]: Running CLI command: cwctl --json --insecure templates repos list --conid K41SXS5Z
<a bunch of other stuff happens>
[DBUG: 17:23:18.907 CLIWrapper.js:192]: Successfully ran CLI command cwctl --json --insecure templates repos list --conid K41SXS5Z, Output was:
[
	{
		"description": "Codewind project templates help you create containerized projects for various runtimes.",
		"url": "https://raw.githubusercontent.com/codewind-resources/codewind-templates/master/devfiles/index.json",
		"name": "Default templates",
		"id": "",
		"enabled": true,
		"protected": true,
		"projectStyles": [
			"Codewind"
		]
	},
	{
		"description": "The set of templates for new OpenShift projects in Codewind.",
		"url": "file:///codewind-workspace/.extensions/codewind-odo-extension/templates/index.json",
		"name": "OpenShift templates",
		"id": "",
		"enabled": true,
		"protected": true,
		"projectStyles": [
			"OpenShift"
		]
	},
	{
		"description": "Use Appsody in Codewind to develop applications with sharable technology stacks.",
		"url": "https://github.com/appsody/stacks/releases/latest/download/incubator-index.json",
		"name": "Appsody Stacks - incubator",
		"id": "incubator",
		"enabled": true,
		"protected": true,
		"projectStyles": [
			"Appsody"
		]
	}
]
```

You can see the initial templates sources GET took 22 seconds!

**Comment by tetchel** [comment]
Applies to che too

**Comment by tobespc** [comment]
The initial pull is always slow, but is that a bug, a lot of git queries are happening at that point?  I think we should use this to investigate the reasons why it's slow.   It does seem a lot of the time that local infrastructure has a huge impact on this first pull.  Lots of things are slow on the first startup of codewind ;-)

Moving this to investigate task

**Comment by tetchel** [comment]
it looks like a bug to a user, maybe it could be done as soon as the server starts instead of the first time we GET /templates/repositories

**Comment by jopit** [comment]
We can debate whether this is a bug or not, but it is a bad user experience.  @tobespc can you assign someone to investigate how we can improve it?

**Comment by tobespc** [comment]
From my testing against a local kube install, it would seem that its not kube but the infrastructure of our cloud is the issue.   One thing we could do is rather than wait for the user to call the api, we pre cache the call on codewind startup

**Comment by hhellyer** [comment]
I've fixed our caching of the repssitories, we were actually caching them on startup *but* the call to do so was before we loaded the extensions which then invalidated the cache. (I've moved the caching to after we've loaded extensions.)

See: https://github.com/eclipse/codewind/pull/1705 - please feel free to pull and test with that branch if you want to verify the performance on your systems before this is merged. I've verified the changes improve performance locally but getting the repository data only takes a second or two locally compared with the 20+ you have been seeing on your systems.

**Comment by tetchel** [comment]
Can we put this into 0.8?

**Comment by hhellyer** [comment]
I checked with @tobespc it's too late for this to go into 0.8.0.

**Comment by tetchel** [comment]
Really fast now :+1:
