### ISSUE TITLE
Uninstalling codewind from vscode does not remove extension from disk

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#1497]
I've just uninstalled codewind from vscode and found that there is still an entry for it under 

`cd ~/.vscode/extensions/ibm.codewind-0.7.0`

Should this be cleared as well when uninstalling codewind ?

**Comment by tetchel** [comment]
I can't control that :(

**Comment by tetchel** [comment]
I tried it with another extension and it seems this is just vscode's behaviour 🤷‍♂
