### ISSUE TITLE
Error (timing related) starting codewind plugin

### ISSUE THREAD

**Issue by rtaniwa** [eclipse/codewind#15]
I am on W10, running codewind in VS Code. I have a python and Java microprofile project already created. I stop codewind, and then start it up again and the Java project surfaces the following error (while it is still starting):

![Capture](https://user-images.githubusercontent.com/26257153/60977581-bd6d6700-a2fd-11e9-8f76-6265c7faefb9.PNG)

It eventually starts up fine.

**Comment by tetchel** [comment]
yea, i have seen this too. 

it is because FileWatcher has yet had the chance to build the project, so when Portal asks FW for the logs list, FW responds with a 404 project not found (which is then turned into a 500, for some reason)

**Comment by GeekArthur** [comment]
If it only happens on Java microprofile project log, may related with this issue: https://github.com/eclipse/codewind/issues/7

**Comment by GeekArthur** [comment]
Not sure if we can paste internal repo link here, but for tracking purpose, internal Portal repo issue 1093 will track and fix this issue.

**Comment by tetchel** [comment]
Still a bug

**Comment by tobespc** [comment]
this is no longer an issue on master so closing
