### ISSUE TITLE
Improve Writing of Codewind Extension Readme

### ISSUE THREAD

**Issue by thisguy-1** [eclipse/codewind#150]
![Codewind Install Button](https://user-images.githubusercontent.com/52169824/62892872-428dd680-bd17-11e9-96d6-d95af3a4ecc1.png)

Think of this page as a get started page that also highlights some features. On this page, which exists in VS Code and the VS Code marketplace, a user is guided to getting set up and opening up their first project.

- [ ] Must include getting started GIF > @thisguy-1
- [ ] Must include link to Codewind Docs < Guy to verify this has been completed.
- [ ] Must outline Features with the explicit command pallet names and possibly links, as well as explain relationship to make them aware of their existence with links to specific docs. 
- [ ] Point out location of Extension (also in GIF) and relationship to the workspace. Include link to Workspace Welcome Page. 

@tetchel, @sishida

**Comment by sishida** [comment]
I can help with the writing improvements.

**Comment by thisguy-1** [comment]
@eharris369

**Comment by tetchel** [comment]
Don't forget that the user can also encounter this readme at https://github.com/eclipse/codewind-vscode

So they are not necessarily already past step 1.

But all the other changes I certainly agree with

**Comment by jopit** [comment]
This is complete for VSCode.  We're going to open a new issue for the Eclipse work

**Comment by jopit** [comment]
New issue to track the work for Eclipse is https://github.com/eclipse/codewind/issues/368
