### ISSUE TITLE
Hybrid: VSCode: new connection page doesn't reflow to fit a smaller window

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind#1505]
![image](https://user-images.githubusercontent.com/29612372/70729485-50596580-1cd1-11ea-9df6-28275e5e96a3.png)

**Comment by tetchel** [comment]
@laven26

**Comment by tetchel** [comment]
it's improved but the lower card shouldn't have the padding to the left, and the buttons should be stacked some other way
![image](https://user-images.githubusercontent.com/8888438/71693962-c5bdd080-2d7b-11ea-8803-b470c6a4bf1e.png)

**Comment by tetchel** [comment]
https://github.com/eclipse/codewind-vscode/pull/369

**Comment by tetchel** [comment]
@jopit can you verify?

**Comment by jopit** [comment]
Currently the second card attaches to the right side of the window if it won't fit side-by-side with the first card, and it moves leftward as I make the window smaller.  I'd prefer if it would line up under the first card and not move around as the window is made smaller.

![image](https://user-images.githubusercontent.com/29612372/72187537-f29a6500-33c5-11ea-8ac8-3757cea64a20.png)

**Comment by malincoln** [comment]
@tetchel I see this is still in progress and labeled for 0.8.0 which has past.  I'll remove the release label for now.  Once it is targeted, pls add new release.  Thanks

**Comment by tetchel** [comment]
it should be fixed now

**Comment by malincoln** [comment]
@jopit pls verify and close.  Thanks

**Comment by jopit** [comment]
Verified
