### ISSUE TITLE
SVT:[OCP 4.2]:Performance tests are not available in history to compare results

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#1508]
**Codewind version:** 0.7.0
**OS:** CoreOS

**Che version:** 0.7.0
**IDE extension version:** 0.7.0
**IDE version:**  Theia 7.3.1
**Kubernetes cluster:**
OKD 4.2 cluster

**Description:**
Performance tests results are not stored after running tests for Node.js default project. 
History section does not show any of the test results.

**Steps to reproduce:**
1. Install OKD 4.2 cluster.
2. Install Eclipse che.
3. Create codewind 0.7 workspace
4. Create Node.js project from default templates.
5. Run performance tests.
6. Test results history is blank.

![image](https://user-images.githubusercontent.com/713849/70731462-babfd500-1cd4-11ea-8bdf-a6a4b9fb9d96.png)

![image](https://user-images.githubusercontent.com/713849/70731361-93690800-1cd4-11ea-9021-3a1505a8094c.png)

PFE and Performance logs..

[performance.txt](https://github.com/eclipse/codewind/files/3956904/performance.txt)
[pfe.txt](https://github.com/eclipse/codewind/files/3956905/pfe.txt)

**Workaround:**

**Comment by jagraj** [comment]
I see same problem with appsody projects as well.

**Comment by markcor11** [comment]
I've tried testing the 0.7.0 branch of PFE/Performance/Theia in Che and was unable to reproduce this.  

From the performance container logs, I can see the 3 x 20sec loadtest ran.  All 3 completed but none of the requests were serviced by the project each time:   

**Performance pod reports :** 

```
  totalRequests: 1958, totalErrors: 1958,
  totalRequests: 1966, totalErrors: 1966,
  totalRequests: 1947,  totalErrors: 1947,
```

**PFE pod reports :** 

```
[91m[12/12/19 16:33:35 LoadRunner.js] [ERROR][39m createCollection: Error in function createCollection
[91m[12/12/19 16:33:35 LoadRunner.js] [ERROR][39m { Error: connect ECONNREFUSED 9.30.204.147:30377
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '9.30.204.147',
  port: 30377 }
```

Was the project responding to browser requests ok between load runs ? 

It seems that the project was not any accepting connections. One request, (createCollection) happens right before load is applied and is responsible for creating the bucket to hold metrics inside the project container.  I had a look at the code for this and can see that if the request to create the collection  for the load run fails (per this case), loadrunner continues to start up with pressure being applied to the project. That does not sound right. Codewind should probably throw an error back to the user to say "Your project has stopped responding" or something similar.

**Comment by jagraj** [comment]
After debugging with Mark this morning, we found out that we are not using ingress endpoint to make a call for performance request and we are appending "Nodeport" to ingress endpoint and that is why calls are failing. The other issue we found is, we should use private ip and internal port to drive the load rather running load with application ingress endpoint which is not best practice.

**Comment by malincoln** [comment]
Requires further work for the single master node for 0.8.0.  Doc current usecase for 0.7.0

**Comment by DavidG1011** [comment]
Seeing possibly related behavior on my 4.2 cluster with 3 masters, 3 workers.

Upon running a load test, it gets stuck on "preparing", then produces this error:
![Screen Shot 2019-12-16 at 10 27 53 AM (3)](https://user-images.githubusercontent.com/30476587/70926254-c96efa80-1ffa-11ea-9349-f45aa5b1ef5a.png)


Logs:
[pfe.txt](https://github.com/eclipse/codewind/files/3969214/pfe.txt)
[performance.txt](https://github.com/eclipse/codewind/files/3969216/performance.txt)

**Comment by johnmcollier** [comment]
I can reproduce on an HA (3 masters) OCP 4.2 cluster. I can also reproduce on both 0.6.1 and 0.7.0

The root issue is due to differences in load balancing and how HA Proxy is used on OCP4 vs. OCP/OKD 3.x. On OCP4.x, it's no longer valid to access a NodePort over an ingress (which is why we delivered ingress support in https://github.com/eclipse/codewind/issues/459 for applications).

As Jag mentions, we the Performance dashboard needs to be using the project's service name (or cluster IP, either will work) and the internal port. The project's ingress should not be used either for performance testing, as that should only be used for external access (some managed Kubes will charge users based on the traffic over the ingress, and we want to minimize that)

**Comment by jagraj** [comment]
We agree now, this is not related to single vs multiple master nodes and I changed problem description that this is specific to OCP 4.2 support is missing for performance tests.

**Comment by markcor11** [comment]
I'm coding up a way for PFE to use the internal cluster network for applying load pressure and controlling metrics gathering from the project (pfe direct to pod) rather than the external ingress address.

**Comment by malincoln** [comment]
agreed to move to 0.8.0

**Comment by jagraj** [comment]
Changing title to reflect OCP 4.2. support.

**Comment by markcor11** [comment]
I have made changes :

1. PFE - In Kube, discover endpoints using project service
2. PFE - In Kube make LoadRunner apply load pressure to project directly rather than ingress
3. PFE - In Kube make metrics controller gather metrics from project directly rather than ingress
4. PerfDash - When PFE is secured, send authentication token to access the protected UISocket
5. Built test images for Jag to try on his cluster

**Comment by sishida** [comment]
@markcor11 Hello! I see that this issue has the `docs` label. Do we still need to update the docs, or should we remove that label? Thank you!

**Comment by malincoln** [comment]
@jagraj pls verify fix resolves problem.  Thanks

**Comment by markcor11** [comment]
@sishida the docs label can be removed since with the fix its business as usual.

**Comment by sishida** [comment]
Thanks! I've removed the docs label.

**Comment by jagraj** [comment]
This has been verified on latest 0.8.0 release. Thanks for the fix.
