### ISSUE TITLE
Inject metrics not available for openliberty project

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#1509]
The 2 stories we want to focus on are  

"Developer brings their OpenLiberty (or Java or Node.js) application to codewind and they don't have any type of metrics.  We can inject metrics as OpenLiberty is a  application with a pom.xml and we support injection for that"

"Developer brings their OpenLiberty (or Java or Node.js)  application to codewind and they already have data on a /metrics endpoint (mpmetrics for example).  We should display our dashboards plotting as much as possible from that data but.... also allow additional metrics to be injected to fill in any blanks that there data might have"

The simple fix would be to say that if a project is of language Java, we always allow injection and a link to our performance dashboard.   If they don't have /metrics and don't choose to inject, then the dashboard will have empty graphs (this is different to previous releases where a 404 would return when no monitoring available).

**Comment by tetchel** [comment]
the short-term fix is to update https://github.com/eclipse/codewind-vscode/blob/master/dev/src/codewind/project/ProjectType.ts#L139 to check against the list of supported languages instead. ie

```
return [
    "java", "nodejs", "swift",
].includes(this.language.toLowerCase());

**Comment by rwalle61** [comment]
I think this is 2 user stories/ pieces of functionality, which can be completed independently of each other:
1. user with open liberty project can inject metrics
2. user with open liberty project with `/metrics` endpoint can click `open app monitor` and see their metrics graphed (on our app monitor dashboard hosted on our performance container)

For 1, @tetchel's suggestion enables this in VSCode, then we need to make PFE able to inject into open liberty projects.



For 2, quick fixes include https://github.com/eclipse/codewind-vscode/pull/355 and https://github.com/eclipse/codewind-eclipse/pull/493. These show the `open app monitor` button for all java projects, whether they actually have a `/metrics` endpoint or not. 

Moving forwards on 2, we should properly (i) check whether they actually have a `/metrics` endpoint, and (ii) report this to the IDEs. Perhaps we should rename `metricsAvailable` to `doesProjectHostMetricsDash`, and then use a new boolean `doesProjectHaveMetricsEndpoint`

**Comment by rwalle61** [comment]
Part of part 2: https://github.com/eclipse/codewind/pull/1544

**Comment by rwalle61** [comment]
Also part of part 2: https://github.com/eclipse/codewind/pull/1543

**Comment by tobespc** [comment]
as part of this, need to update our template to be a lot simpler - I can do this

**Comment by mattcolegate** [comment]
Open Liberty Injection now delivered through the three PRs above and can be verified.
/pipeline Verify

**Comment by mattcolegate** [comment]
@tobespc I think this can be closed

**Comment by mattcolegate** [comment]
@tobespc Please close this.

**Comment by jgwest** [comment]
@mattcolegate Looks like 'closed' isn't an actual ZenHub pipeline (despite the fact it appears as one in the web UI 🤔 )...  you can use `/close` for this (and in the mean time I will have the bot use `/close` whenever `/pipeline closed` is detected)
