### ISSUE TITLE
Additional "Open Workspace" Notification

### ISSUE THREAD

**Issue by thisguy-1** [eclipse/codewind#151]
- [ ] If a user gets to start a project without having opened a Codewind workspace, then they must be notified to open a workspace after they have created a project. 

- [ ] This one doesn't have to be a persistent popup

@tetchel

**Comment by thisguy-1** [comment]
<img width="695" alt="Screen Shot 2019-08-23 at 1 29 08 PM" src="https://user-images.githubusercontent.com/52169824/63611524-06c1ff00-c5aa-11e9-9cb2-9a27d9435768.png">
@tetchel

**Comment by thisguy-1** [comment]
@sishida, please review writing of the notification and where "more info" should point to.

**Comment by tetchel** [comment]
I fixed this by adding an Open Workspace button to the already existing "Created/Added project" messages, which is shown only if the user is not already in a codewind workspace/project.
![image](https://user-images.githubusercontent.com/8888438/64290351-f14abe80-cf33-11e9-9b42-a5e90d5ac123.png)
