### ISSUE TITLE
Hybrid: 0.7.0: remote configuration doc doesn't mention need to enable privileged and root containers to run

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind#1512]
When I install codewind remotely into an OpenShift cluster, I need to grant it permission to run privileged and root containers.  This information should go into the documentation for remote configuration, under the `Configuring other cloud deployments` section.  It should say something like

```
Codewind is required to run as privileged and as root because it
builds container images. If your cluster is running OpenShift, run the
following commands where <namespace> is the namespace into which you
plan to install Codewind:

To enable privileged containers, enter
    oc adm policy add-scc-to-group privileged system:serviceaccounts:<namespace>
To enable containers to run as root, enter
    oc adm policy add-scc-to-group anyuid system:serviceaccounts:<namespace>
```
(Stolen from here: https://www.eclipse.org/codewind/mdt-che-installinfo.html#enabling-privileged-and-root-containers-to-run)

@johnmcollier any feedback on this?

**Comment by malincoln** [comment]
@sishida @micgibso pls assign.  Thanks

**Comment by johnmcollier** [comment]
@jopit Yeah, that text sounds good to me.

**Comment by sishida** [comment]
The PR to add the text update has been merged. Closing this issue.
