### ISSUE TITLE
SVT:[Doc]:Hybrid:OpenShift:Need instructions for the user to create a project first before making client remote call.

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#1513]
**Codewind version:** 0.7.0
**OS:** CoreOS

**Che version:** 7.3.1
**IDE extension version:** 0.7.0
**IDE version:** Their 7.3.1
**Kubernetes cluster:**
OpenShift 4.2 cluster

**Description:**
We need instructions to the user to create OpenShift project first and then configure remote "Codewind" from codewind CLI. 

I do not see these steps listed in this doc.
https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/remote-configuring.md

**Steps to reproduce:**

**Workaround:**

**Comment by jagraj** [comment]
/area docs
/priority stopship

@markcor11 @micgibso

**Comment by markcor11** [comment]
@jagraj CWCTL in 0.7.0 makes use of the --namespace flag to check and use an existing or create a new OC project / Kube namespace of that name. An early prereq of creating the namespace before running cwctl is no longer required.

**Comment by micgibso** [comment]
@jagraj This was in an early draft of the docs, but as Mark says above, it's no longer required;  removing the `area/docs` label.

**Comment by malincoln** [comment]
@jagraj can this defect be closed?

**Comment by malincoln** [comment]
Jag agreed to close
