### ISSUE TITLE
SVT:[Hybrid]:Missing cluster login as prereq before setting up remote codewind

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#1515]
**Codewind version:** 0.7.0
**OS:** Windows

**Che version:** 7.3.1
**IDE extension version:** 0.7.0
**IDE version:**  Theia 7.3.1
**Kubernetes cluster:**

Openshift 4.2 cluster.

**Description:**
Missing Cluster login as prereq for `cwctl`  remote codewind deployment.

https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/remote-configuring.md

I get into this issue...

```
.\cwctl.exe install remote --namespace codewind  --kadminuser admin --kadminpass passw0rd --krealm codewind --kclient codewind --kdevuser developer --kdevpass passw0rd --ingress "apps.leith.os.fyre.ibm.com"
time="2019-12-12T17:22:04-05:00" level=info msg="Checking namespace codewind exists\n"
time="2019-12-12T17:22:07-05:00" level=info msg="Creating codewind namespace\n"
time="2019-12-12T17:22:09-05:00" level=error msg="Unable to create codewind namespace: Post https://localhost:6445/api/v1/namespaces: dial tcp [::1]:6445: connectex: No connection could be made because the target machine actively refused it."
time="2019-12-12T17:22:09-05:00" level=error msg="Error: rem_create_namespace - Post https://localhost:6445/api/v1/namespaces: dial tcp [::1]:6445: connectex: No connection could be made because the target machine actively refused it.\n"
```

**Steps to reproduce:**

**Workaround:**

**Comment by jagraj** [comment]
/area docs
/priority stopship

@micgibso @markcor11

**Comment by markcor11** [comment]
Agreed,  to deploy a remote Codewind environment the operator needs to be logged into the cluster  (using, for example `oc login`). We should call that out in our guides.

**Comment by micgibso** [comment]
`oc` commands documented on PR https://github.com/eclipse/codewind-docs/pull/265/

**Comment by jagraj** [comment]
Looks like this issue has been closed for wrong PR. I do not see PR 265 added prerequisite
for cluster login.

/reopen

**Comment by johnmcollier** [comment]
Given Codewind should be Kube generic and that logging into a cluster can not only vary between Kube providers, but even different versions of the same Kube (e.g. logging in on OCP 3.x is slightly different than on 4.x), can we just provide something generic like:

```
Please ensure you have an active Kubernetes context pointing to your cluster
```

**Comment by jagraj** [comment]
Thanks @johnmcollier and @sishida

**Comment by sishida** [comment]
Hi, team, Please see line 21 in the PR update: https://github.com/eclipse/codewind-docs/pull/269

As soon as we get a committer approval, we can merge. :)

**Comment by sishida** [comment]
Pull request https://github.com/eclipse/codewind-docs/pull/269 has been merged. Closing this issue.
