### ISSUE TITLE
Permanent & More Obvious "Open Workspace" Notification

### ISSUE THREAD

**Issue by thisguy-1** [eclipse/codewind#152]
- [ ] Must Be Permanent
- [ ] Probably will need to be a top popup
@tetchel

**Comment by thisguy-1** [comment]
![Install: PFE Installed](https://user-images.githubusercontent.com/52169824/63453547-e6157000-c416-11e9-88e6-8ce8a2f82b47.png)

@sishida Hi sarah, can you take a look at the notification and see what doc the more info could link to and if we need a specific page it should go to? 
@tetchel can you add the appropriate ID label?

**Comment by sishida** [comment]
Does this notification really need a "More info" link? At the moment, I don't think we have a doc that focuses solely on workspaces.

For the notification text, maybe...
```
Do you want to open your Codewind workspace folder now?

To open a folder in the Codewind explorer view, right-click and select “Open Folder as Workspace.”
```

**Comment by thisguy-1** [comment]
> Does this notification really need a "More info" link? At the moment, I don't think we have a doc that focuses solely on workspaces.
> 
> For the notification text, maybe...
> 
> ```
> Do you want to open your Codewind workspace folder now?
> 
> To open a folder in the Codewind explorer view, right-click and select “Open Folder as Workspace.”
> ```
> 
> I'm not sure if it's possible, but it would be great if we could get "Open Folder as Workspace" to appear in bold instead of using the quotation marks.

There isn't any place where we talk about workspaces? If not, this is something that needs to be created because it is one of the more confusing parts of Codewind and will also be a part of the new welcome page.

**Comment by sishida** [comment]
@thisguy-1 What if we placed the workspace info on the page that gives more info about installing? https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/mdt-vsc-installinfo.md

We could add a new section called "Understanding workspaces" or something. @tetchel Could you help provide details?

**Comment by sishida** [comment]
Text from John that I will add to a PR:
```
The Codewind workspace is a folder on your system where  Codewind expects to find your projects, and where Codewind stores it meta-data.  On macOS and Linux, the folder used is ~/codewind-workspace, while on Windows, it is C:\codewind-workspace.  When Codewind creates a new project, it will be created in the Codewind workspace.  If you want to add an existing project to Codewind, you must copy it into the Codewind workspace first.
```
