### ISSUE TITLE
SVT:[OCP:4.2]:Application monitor returns blank page for remote apps

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#1520]
**Codewind version:** 0.7.0
**OS:** Windows/CoreOS

**Che version:** 0.7.0
**IDE extension version:** Theia 0.7.0
**IDE version:** Theia 7.3.1
**Kubernetes cluster:**
OS 4.2 cluster

**Description:**
Performance monitor returns blank page for all supported applications. I have eclipse plugin installed on Windows and connected to remote OpenShift cluster.

![image](https://user-images.githubusercontent.com/713849/70796040-4a19c680-1d6f-11ea-9c6b-44dffaeb08c2.png)

![image](https://user-images.githubusercontent.com/713849/70796099-72092a00-1d6f-11ea-9a9c-61613999bfee.png)

Here are the logs from remote codewind and local IDE logs.
[.log](https://github.com/eclipse/codewind/files/3960464/default.log)
[gatekeeper.txt](https://github.com/eclipse/codewind/files/3960466/gatekeeper.txt)
[keycloak.txt](https://github.com/eclipse/codewind/files/3960467/keycloak.txt)
[performance.txt](https://github.com/eclipse/codewind/files/3960468/performance.txt)
[pfe.txt](https://github.com/eclipse/codewind/files/3960469/pfe.txt)

**Steps to reproduce:**
1. Install codewind from eclipse ide.
2. Configure remote codewind.
3. Create projects on remote.
4. Supported Application monitor does not work for most of the projects.

**Workaround:**

**Comment by rwalle61** [comment]
Hi @jagraj I'm looking at this

**Comment by malincoln** [comment]
will review again on Monday to see if we have possible fix.

**Comment by malincoln** [comment]
agreed to move to 0.8.0

**Comment by malincoln** [comment]
@tobespc just confirming this is still on target for 0.8.0 (dcut tomorrow)?

**Comment by tobespc** [comment]
confirmed this is working ok

**Comment by malincoln** [comment]
@jagraj pls verify and close.  Thanks

**Comment by jagraj** [comment]
After resolving all my cluster issues on fyre, I tried to verify this issue. I still see the endpoint is using nodeport not ingress or route. Here is the endpoint it is using.

http://codewind-gatekeeper-k5p9o6aj.apps.grease.os.fyre.ibm.com:31353/appmetrics-dash/?theme=dark

![Screen Shot 2020-01-22 at 7 33 58 AM](https://user-images.githubusercontent.com/713849/72894866-36f10380-3cea-11ea-841c-f22592e08f8c.png)

**Comment by markcor11** [comment]
Tested this out with 0.8.0 images of PFE / Performance.  I was able to reproduce this using Eclipse 0.8.0.  When launching the Applications Monitor the page opened showed the Gatekeeper URL rather than the appBaseURL as seen from /api/v1/projects.    When launching the Application Monitor UI from VSCode (0.8.0) this worked correctly.  The app metrics page loaded with the URL to the project ingress rather than gatekeeper.

**Comment by eharris369** [comment]
PR for 0.8.0 is merged: https://github.com/eclipse/codewind-eclipse/pull/544

**Comment by jagraj** [comment]
@eharris369 @josephca 

I do not see new plugin updated with the fix. Is there a build issue someone can take a look what is going on.?

```
<site>
<feature id="org.eclipse.codewind" url="features/org.eclipse.codewind_0.8.0.v202001221842.jar" version="0.8.0.v202001221842">
<category name="Codewind"/>
</feature>
<category-def label="Codewind" name="Codewind">
<description>
Tools for working with Codewind applications in Eclipse
</description>
</category-def>
</site>```

**Comment by josephca** [comment]
> @eharris369 @josephca
> 
> I do not see new plugin updated with the fix. Is there a build issue someone can take a look what is going on.?
> 
> ```
> <site>
> <feature id="org.eclipse.codewind" url="features/org.eclipse.codewind_0.8.0.v202001221842.jar" version="0.8.0.v202001221842">
> <category name="Codewind"/>
> </feature>
> <category-def label="Codewind" name="Codewind">
> <description>
> Tools for working with Codewind applications in Eclipse
> </description>
> </category-def>
> </site>```
> ```

I will take a look
