### ISSUE TITLE
SVT:[OCP 4.2]:Application performance returns "Unable to fetch metrics from API" error on performance page.

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#1521]
**Codewind version:** 0.7.0
**OS:** Windows/CoreOS

**Che version:** 
**IDE extension version:** 0.7.0
**IDE version:** Theia 7.3.1
**Kubernetes cluster:** OpenShift 4.2

**Description:**
Application performance returns this message for all supported applications. 
"Unable to fetch metrics from API reason: Error: 403"

**Steps to reproduce:**
1. Install codewind from eclipse plugin.
2. Install remote codewind.
3. Create bunch of projects from default and appsody sources.
4. Click on  "Performance dashboard" then you get this message.

![image](https://user-images.githubusercontent.com/713849/70797351-54898f80-1d72-11ea-9f31-26e63b548963.png)

Logs.
[gatekeeper.txt](https://github.com/eclipse/codewind/files/3960533/gatekeeper.txt)
[keycloak.txt](https://github.com/eclipse/codewind/files/3960534/keycloak.txt)
[performance.txt](https://github.com/eclipse/codewind/files/3960535/performance.txt)
[pfe.txt](https://github.com/eclipse/codewind/files/3960536/pfe.txt)
[.log](https://github.com/eclipse/codewind/files/3960540/default.log)

**Workaround:**

**Comment by malincoln** [comment]
@tobespc we will review on Monday to see if we have possible fix.

**Comment by malincoln** [comment]
agreed to move to 0.8.0

**Comment by tobespc** [comment]
With the changes that have gone in for #1588 , this is now ok

**Comment by malincoln** [comment]
@jagraj pls verify fix resolves problem.  Thanks

**Comment by jagraj** [comment]
After resolving my cluster issues, I tried to verify this issue with my OCP 4.2 cluster and I still see this problem. 

![Screen Shot 2020-01-22 at 7 50 56 AM](https://user-images.githubusercontent.com/713849/72895689-f09ca400-3ceb-11ea-8660-2ab6040304af.png)

**Comment by jagraj** [comment]
This issue is resolved closing it now.
