### ISSUE TITLE
Hybrid: Project overview should show the name of the namespace and pod associated with the application

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind#1525]
This kind of information would be needed to be provided by the developer to the cluster admin/support if they are having network or infrastructure problems working with the application.

We should identify if here's other info that would be needed for this kind of situation.

**Comment by tetchel** [comment]
This would have to be provided by portal/turbine in GET /projects

**Comment by maysunfaisal** [comment]
@tetchel looks project.inf already has the `podName`, you just need to consume it:
```
[root@codewind-workspacelb0ws6gz8jerb32y-67db66fc47-nx4tb .projects]# cat b0c234b0-46d4-11ea-8a96-093af02bb03e.inf 
{
  "projectID": "b0c234b0-46d4-11ea-8a96-093af02bb03e",
  "name": "maygo1234",
  "codewindVersion": "x.x.dev",
  "language": "go",
  "creationTime": 1580768990423,
  "locOnDisk": "/projects/maygo1234",
  "pathToMonitor": "/projects/maygo1234",
  "host": "codewind-workspacelb0ws6gz8jerb32y-che-che.9.37.222.212.nip.io",
  "ports": {
    "exposedPort": "31111",
    "internalPort": "8000"
  },
  "workspace": "/codewind-workspace/",
  "directory": "maygo1234",
  "infLockFlag": true,
  "loadTestPath": "/codewind-workspace/maygo1234/load-test",
  "projectType": "docker",
  "buildLogPath": "/codewind-workspace/.logs/maygo1234-b0c234b0-46d4-11ea-8a96-093af02bb03e/docker.build.log",
  "state": "open",
  "autoBuild": true,
  "injectMetrics": false,
  "workspaceDir": "/codewind-workspace/maygo1234",
  "startMode": "run",
  "buildStatus": "success",
  "detailedBuildStatus": " ",
  "projectWatchStateId": "a4f3b807d8f731e1ffdd6287dcd1db7d",
  "ignoredPaths": [
    "/.project",
    "*/node_modules*",
    "*/.git/*",
    "*/.DS_Store",
    "*/*.swp",
    "*/*.swx",
    "*/4913",
    "/load-test*",
    "*/.dockerignore",
    "*/.gitignore",
    "*/*~",
    "/.settings"
  ],
  "metricsAvailable": false,
  "appImageLastBuild": "1580769025460",
  "lastbuild": 1580769032171,
  "location": "/codewind-workspace/maygo1234",
  "validationStatus": "success",
  "validationResults": [],
  "appStatus": "started",
  "isHttps": false,
  "podName": "cw-maygo1234-b0c234b0-46d4-11ea-8a96-685b5c4c49-m9bg8",
  "logs": {
    "build": [
      {
        "origin": "workspace",
        "files": [
          "/codewind-workspace/.logs/maygo1234-b0c234b0-46d4-11ea-8a96-093af02bb03e/docker.build.log"
        ]
      }
    ],
    "app": [
      {
        "origin": "workspace",
        "files": [
          "/codewind-workspace/.logs/maygo1234-b0c234b0-46d4-11ea-8a96-093af02bb03e/app.log"
        ]
      }
    ]
  },
  "appBaseURL": "http://1xa6-maygo1234-che-che.9.37.222.212.nip.io"
}
[root@codewind-workspacelb0ws6gz8jerb32y-67db66fc47-nx4tb .projects]# cat b0c234b0-46d4-11ea-8a96-093af02bb03e.inf | grep podName
  "podName": "cw-maygo1234-b0c234b0-46d4-11ea-8a96-685b5c4c49-m9bg8",
```

As for local, we are already displaying containerID, I think that is the most accurate representation of which container it is, and think we should keep it that way

**Comment by tetchel** [comment]
can we get the project / codewind instance's namespace too? it's annoying to know the pod name without the namespace

**Comment by maysunfaisal** [comment]
@tetchel yeah looks like we already have an env var for namespace in PFE, let me look if Hybrid PFE also has this env var, then I can just emit it along with project operations

**Comment by tetchel** [comment]
If you could add the namespace to /api/v1/environment too that would be great

**Comment by tetchel** [comment]
maybe pfe (and performance?) podname too while we're at it...

**Comment by eharris369** [comment]
Eclipse IDE PR: https://github.com/eclipse/codewind-eclipse/pull/590

**Comment by maysunfaisal** [comment]
The PFE work is done and merged, so I have been unassigned. @eharris369 @tetchel pls assign yourselves if you're working on the issue, thx

**Comment by eharris369** [comment]
I think this is done now in both IDEs (master only) so moving to verify.

/pipeline verify

**Comment by malincoln** [comment]
It looks like this was completed for this release so changing release to 0.9.0

**Comment by malincoln** [comment]
@jopit pls verify and close. Thanks

**Comment by jopit** [comment]
This isn't in the 0.9.0 release.

**Comment by malincoln** [comment]
should this move back to In Progress?

**Comment by tetchel** [comment]
I'm closing this because it's done for eclipse and vs code. I opened a separate issue for IntelliJ because hybrid is some way away for that.

**Comment by eharris369** [comment]
It is delivered in master so should stay in verify state. See https://github.com/eclipse/codewind/issues/1525#issuecomment-587465259.
