### ISSUE TITLE
"Codewind Welcome Page" in VS Code

### ISSUE THREAD

**Issue by thisguy-1** [eclipse/codewind#153]
When a user clicks on "open workspace" notification, s/he usually is a bit disoriented s/he is taken to the explorer page and is presented with the VScode welcome page, and rarely understands the relationship between the workspace and codewind. Having a "Codewind Welcome Page" will help orient them, and extend the readme they saw when they were installing codewind.

- [ ] Must explain dynamic between workspace and codewind
- [x] Must include link learning guides, setting. Almost like a map to finding what they need. Think an extension of the readme with some overlap. 
- [ ] Intro to Source Preferences (Kabanero, Appsody, Ibm templates, etc)
- [x] Can be disabled, but also easily found again.

@thisguy-1, @tetchel , @sishida

**Comment by sishida** [comment]
I can help with the writing of this page.

**Comment by MelHopper** [comment]
Consider where to reference this new Open Workspace topic in the following topics (which reference the workspace but do not explain the relationship between workspace and Codewind):
1. Getting Started
2. Tutorial
3. Installing Codewind - note that this topic does contain the following subheading content on Workspaces:

![Screenshot 2019-09-09 at 13 09 49](https://user-images.githubusercontent.com/13365734/64529572-2889e880-d303-11e9-9cf8-2eae4a11d13c.png)

**Comment by thisguy-1** [comment]
@thisguy-1 must update this issue to reflect the new "as is" and the mural with the pain points done with the devs.

**Comment by thisguy-1** [comment]
@tetchel 

Deliverables: 
<img width="1210" alt="Screen Shot 2020-01-28 at 5 05 43 PM" src="https://user-images.githubusercontent.com/52169824/73311650-03840c80-41f5-11ea-8950-cab395986dd4.png">
<img width="1209" alt="Screen Shot 2020-01-28 at 5 05 53 PM" src="https://user-images.githubusercontent.com/52169824/73309914-33c9ac00-41f1-11ea-8728-f3fd9ec11d9a.png">
[Home Page Specs v2.zip](https://github.com/eclipse/codewind/files/4125072/Home.Page.Specs.v2.zip)
<img width="1164" alt="Screen Shot 2020-01-28 at 5 24 25 PM" src="https://user-images.githubusercontent.com/52169824/73310849-13025600-41f3-11ea-86b7-c10f223eb49f.png">
[Home Page Assets.zip](https://github.com/eclipse/codewind/files/4124990/Home.Page.Assets.zip)

INVISION:
https://ibm.invisionapp.com/share/4UNZIGVGEB7

**Comment by thisguy-1** [comment]
@thisguy-1 still needs to deliver:

- [ ] Dark theme icons
- [ ] Improved graphic
- [ ] Links in invision

**Comment by thisguy-1** [comment]
![screenshot2_hiRes](https://user-images.githubusercontent.com/52169824/73686880-da50f980-4696-11ea-81df-7f0fe2e1e602.png)

New screen shot

**Comment by thisguy-1** [comment]
reference invision for dimensions and placement

**Comment by thisguy-1** [comment]
New version on invsion:
<img width="961" alt="Screen Shot 2020-02-03 at 5 02 52 PM" src="https://user-images.githubusercontent.com/52169824/73695646-8b13c480-46a8-11ea-9d7f-ebea8fea21e9.png">
<img width="961" alt="Screen Shot 2020-02-03 at 5 00 31 PM" src="https://user-images.githubusercontent.com/52169824/73695647-8b13c480-46a8-11ea-861d-a3428e62f6ce.png">

**Comment by tetchel** [comment]
https://github.com/eclipse/codewind-vscode/pull/429

**Comment by tetchel** [comment]
the vs code welcome page is in now,

we still have https://github.com/eclipse/codewind/issues/2169 for eclipse
and https://github.com/eclipse/codewind/issues/1984 for Che
