### ISSUE TITLE
Turbine test autoamtion should test if dangling kube resoureces exist

### ISSUE THREAD

**Issue by GeekArthur** [eclipse/codewind#1530]
Currently Turbine test automation doesn't have capabilities of testing if dangling kube resources (eg. all kube resources deployed by Turbine like deploy, svc, pvc, etc) still exist after project deletion, we should add the capabilities when testing project deletion.

**Comment by jgwest** [comment]
@ssh24: Unable to locate pipeline with name: `in-progress`
