### ISSUE TITLE
Consider versioning the index.json for Codewind-style projects

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#1532]
The current index.json that we're using for Codewind style projects is https://raw.githubusercontent.com/codewind-resources/codewind-templates/master/devfiles/index.json, which points to the master branch of the index.json (and the master branch for each of the templates). This index.json (and the corresponding project templates) will be the same for **all** Codewind versions right now.

This means that if changes need to be delivered to the templates to accommodate a future Codewind release (such as https://github.com/eclipse/codewind/issues/622), those changes would be reflected across **all** Codewind versions. This has the potential to cause regressions on those versions, if those changes aren't compatible with past Codewind releases.

Could we instead version both the Codewind-style index.json file and the corresponding projects that it points to? For example, for a `0.x.y` release of Codewind, the index.json would be https://raw.githubusercontent.com/codewind-resources/codewind-templates/0.x.y/devfiles/index.json, and all of the projects would be checked out on the 0.x.y branch.

**Comment by johnmcollier** [comment]
Adding the techtopics label so that we can discuss this as a whole

**Comment by tobespc** [comment]
makes sense to me to version it

**Comment by deboer-tim** [comment]
Discussed on tech topics call. We won't change the current codewind template repo, but we do need to fix this in any new templates going forward: template repo should be versioned along with each template, and these won't have the same version/release as the tools.
