### ISSUE TITLE
SVT: [Hybrid][Docs] There are no instructions on how to configure Tekton Dashboard in hybrid scenarios, but the option is available

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#1536]
**Codewind version:** 0.7.0
**IDE extension version:** 0.7.0
**IDE version:** Code 1.40.2

**Description:** There are no instructions on how to configure Tekton Dashboard in hybrid scenarios, but the option is available.

<img width="559" alt="Screen Shot 2019-12-13 at 4 21 07 PM" src="https://user-images.githubusercontent.com/49531960/70833055-c985b500-1dc4-11ea-8be0-11b7bd47beba.png">

https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/remote-configuring.md
https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/remote-connection-ui.md
https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/remote-overview.md

**Comment by tetchel** [comment]
the instructions should be the same for hybrid as they are for che, but I agree it would be nice to link to the tekton doc from one of the 'remote' pages.

https://www.eclipse.org/codewind/codewindandtektonpipelines.html

**Comment by sishida** [comment]
Since issue #1542 indicates that we'd ideally like to remove the Tekton links from having their own file and since this issue #1536 indicates we'd like to link the Tekton info to one of the "remote" pages...
1️⃣ I'm going to try to find a place for the Tekton info on one of the remote pages and then
2️⃣ delete the `codewindandtektonpipelines.html` file.

**Comment by sishida** [comment]
Hi, team, I have made changes in this PR: https://github.com/eclipse/codewind-docs/pull/280

**Comment by micgibso** [comment]
See my review on the PR. Discussing with the team here, there are no instructions to configure the Tekton Dashboard in hybrid scenarios because none are required.  Suggest closing this issue.

**Comment by sujeilyfonseca** [comment]
I will proceed to close this issue since a generic bullet was added to refer to the "Open Tekton Dashboard" option: https://github.com/eclipse/codewind-docs/pull/280
