### ISSUE TITLE
Shouldn't reference "Tekton" in our Open Dashboard menu item

### ISSUE THREAD

**Issue by rtaniwa** [eclipse/codewind#1542]
We currently have a menu option to Open Tekton Dashboard. We shouldn't reference the technology underneath. It should just be something to indicate they can view the build dashboard or something to that affect. Let's get design pulled in and figure out what the proper menu option would be.

**Comment by tetchel** [comment]
The docs call it 'tekton' too https://www.eclipse.org/codewind/codewindandtektonpipelines.html

**Comment by sishida** [comment]
@rtaniwa Should we remove the https://www.eclipse.org/codewind/codewindandtektonpipelines.html page? Right now, it just links to the Tekton content.

**Comment by rtaniwa** [comment]
@sishida I never really understood why we had that standalone topic tbh. So not sure if we need to remove it, but somewhere in the docs we should have some reference to what the menu item actually does. And as part of that perhaps we should also ensure the docs match the new change as well. So theoretically, if we went with something like "View build/depoy dashboard" (or something better than that), then the doc topic should have the same. And it shouldn't be it's own top level topic....there isn't enough content to warrant it.

**Comment by sishida** [comment]
OK, I have added the docs label to this issue so that ID can track it. As development/design change the "Open Tekton Dashboard" menu option, ID will update the docs accordingly.

Tagging @thisguy-1 for designer awareness.

**Comment by micgibso** [comment]
See my review on the PR. Discussing with the team here, there are no instructions to configure the Tekton Dashboard in hybrid scenarios because none are required. Suggest closing issue #1536.

**Comment by sishida** [comment]
What about "Open Pipeline Dashboard" to replace "Open Tekton Dashboard"?

**Comment by thisguy-1** [comment]
@mii-w

**Comment by thisguy-1** [comment]
@kimholmes

**Comment by elsony** [comment]
Currently, the only pipeline that we support is the Tekton pipeline.  If we use a generic "Open Pipeline Dashboard", people may be using other pipelines and when they click on that, it doesn't show up the pipeline that they have setup.  Given that our support is specific to one particular technology, is there any reason why we need to change that label now instead of using Tekton as is and change to a more generic name when we support more than just Tekton?

**Comment by micgibso** [comment]
For docs for 0.9.0, have moved the occurrence of Tekton, which was upfront and central in the menu on the left hand side, to a much lower level from where it was so you now have to navigate to a specific document to find it.
