### ISSUE TITLE
Improve Codewind View Icons

### ISSUE THREAD

**Issue by thisguy-1** [eclipse/codewind#155]
- [x] Switch "+" to the tight of  "add new".
- [x] Design new Icon for "add new"
- [x] Remove on/off from toggle

Complete lis of Icon deliverables for 0.6.0 release due Nov 5:

- [x] Separator Icon (dark theme)(light theme)
- [x] Remote Connection Settings - Gear (dark theme)(light theme) 
- [x] Build Icon - Hammer (dark theme)(light theme) 
- [x] Remote Connection Status Icon - Connected Cloud (dark them) (light theme)
- [x] Remote Connection Status Icon - Disconnected Cloud (dark them) (light theme) 
- [x] Create New Remote Connection Icon - Cloud + (dark them) (light theme) 
- [x] Generic Project Icon for when Codewind can't get the standard icons  
- [x] Add Existing Project Icon
- [x] Local Connection Status Connected - Folder with checkmark (Dark theme)(light theme)
- [x] Local Connection Status Disconnected - Folder w/ error (Dark theme)(light theme)

* - [x] need a neutral color version that works with both light and dark theme in eclipse

@thisguy-1 , @tetchel, @laven26, @kimholmes

**Comment by kimholmes** [comment]
Adding myself.

**Comment by thisguy-1** [comment]
we also might need an icon that labels Connection different from the icon we have for Local. Might be it isnt necessary, depending on where we locate the icon I created on the right side.

**Comment by kimholmes** [comment]
Here are the enclosed svg icons:
- Bind existing project
- Hybrid Connected
-Hybrid Disconnected
- Pipeline
- Create New Remote Connection

[IDE_Icons.zip](https://github.com/eclipse/codewind/files/3730903/IDE_Icons.zip)

**Comment by kimholmes** [comment]
Adding an svg of the "add" icon for consistency:
[VSCode_Add.svg.zip](https://github.com/eclipse/codewind/files/3731443/VSCode_Add.svg.zip)

**Comment by jopit** [comment]
We'll need icons for Eclipse as well.  Since Eclipse doesn't support separate icons for dark and light themes, we'll need icons that work in both.  If you provide .svg files for the Eclipse icons, I can generate the required .png files for both normal and high-DPI displays.

**Comment by kimholmes** [comment]
Zip file:
[CodewindVScodeIcons.zip](https://github.com/eclipse/codewind/files/3785092/CodewindVScodeIcons.zip)

I'm unable to use the check boxes in the description, so I've copied and pasted here with what I have:

Remote Connection Settings - Gear (dark theme)(light theme)
![image](https://user-images.githubusercontent.com/21316329/67769724-5fd76480-fa2b-11e9-9004-67560e73a7ba.png)

Build Icon - Hammer (dark theme)(light theme)
![image](https://user-images.githubusercontent.com/21316329/67769874-9c0ac500-fa2b-11e9-947d-b83697804e84.png)

Remote Connection Status Icon - Connected Cloud (dark them) (light theme)
![image](https://user-images.githubusercontent.com/21316329/67770034-ee4be600-fa2b-11e9-92d0-7aff80c12208.png)
Remote Connection Status Icon - Disconnected Cloud (dark them) (light theme)
![image](https://user-images.githubusercontent.com/21316329/67790123-991fcc80-fa4b-11e9-89c2-30e11eddc34f.png)

Create New Remote Connection Icon - Cloud + (dark them) (light theme)
![image](https://user-images.githubusercontent.com/21316329/67794594-43e7b900-fa53-11e9-9d6b-4a62aee85367.png)

Generic Project Icon for when Codewind can't get the standard icons
![image](https://user-images.githubusercontent.com/21316329/67793208-cc188f00-fa50-11e9-9c40-738cb4d5a1a3.png)

Add Existing Project Icon
![image](https://user-images.githubusercontent.com/21316329/67794878-cc665980-fa53-11e9-8141-6a4fe53fbb9f.png)

Local Connection (connected and disconnected)(light and dark theme)
![image](https://user-images.githubusercontent.com/21316329/67795533-c7ee7080-fa54-11e9-8ff7-f12fd84dd188.png)

**Comment by kimholmes** [comment]
Here are some tweaks based on how the icons appear in VS Code.
[VSCode_iconTweak.zip](https://github.com/eclipse/codewind/files/3806283/VSCode_iconTweak.zip)

**Comment by thisguy-1** [comment]
@tetchel @jopit What do we still need from this? I think there are a few that are needed for Eclipse. Can you list them out? If not, can we close?

**Comment by jopit** [comment]
@thisguy-1 Could you please work with @eharris369 on the icons required for Eclipse?  I think at a minimum we would want remote and local connection icons with both connected and disconnected variants.  We may also want icons for creating new projects and adding existing projects.

**Comment by eharris369** [comment]
Adding from issue #1503:

Most of the context menu items for the Eclipse IDE do not have icons or are overusing the Codewind icon. Icons for Eclipse need to be visible in dark mode and light mode (Eclipse does not support separate icons for each mode).

Context menu for local connection:

![image](https://user-images.githubusercontent.com/9484320/72013425-d06cdf80-322b-11ea-8396-762df6f4c127.png)


Context menu for remote connection (the disconnect item is a toggle - if connected it shows disconnect, if not connected it shows connect):

![image](https://user-images.githubusercontent.com/9484320/72013449-dcf13800-322b-11ea-963c-270b09e9d369.png)


Context menu for project (Disable/Enable Auto Build, Disable/Enable Inject Metrics, Disable/Enable Project are all toggle items):

![image](https://user-images.githubusercontent.com/9484320/72013468-ea0e2700-322b-11ea-9076-5c7c975b6121.png)

**Comment by eharris369** [comment]
@thisguy-1 From the above and John's comment I think we need:
- local connection icon (could have variants for uninstalled, installed, started, unsupported version - but I think this is too much)
- remote connection icon with connected and disconnected variants
- create new project
- add existing project
- manage image registries
- manage template sources
- it would be nice to also have icons for the various Open actions (Open Project Overview, Open Application Monitor, Open Performance Dashboard, etc.) especially since they all start with "Open".
- the rest are not necessary - not all actions need an icon

Just a reminder that Eclipse icons must work in both light and dark mode - it does not support separate icons for the 2 modes.

**Comment by jopit** [comment]
Also a reminder, in order to support high definition display's we need two versions of each .png file, one that's 16x16 and one that's 32x32, named similarly to the following: `xyz.png` and `xyz@2x.png`

For the other images which must work for both dark and light modes, we have been using the codewind blue color: #0083CA

**Comment by thisguy-1** [comment]
> @thisguy-1 From the above and John's comment I think we need:
> 
> * local connection icon (could have variants for uninstalled, installed, started, unsupported version - but I think this is too much)
> * remote connection icon with connected and disconnected variants
> * create new project
> * add existing project
> * manage image registries
> * manage template sources
> * it would be nice to also have icons for the various Open actions (Open Project Overview, Open Application Monitor, Open Performance Dashboard, etc.) especially since they all start with "Open".
> * the rest are not necessary - not all actions need an icon
> 
> Just a reminder that Eclipse icons must work in both light and dark mode - it does not support separate icons for the 2 modes.

**Comment by thisguy-1** [comment]
@eharris369, my comments bellow each item:
> @thisguy-1 From the above and John's comment I think we need:
> 
> * local connection icon (could have variants for uninstalled, installed, started, unsupported version - but I think this is too much)
> * remote connection icon with connected and disconnected variants
> * create new project
> * add existing project
> * manage image registries

**We never made one for this. Why do we need it? It seems like the only place in the context menu, but there is never an occasion we would see this icon on its own...**
> * manage template sources

**Same comment for this one.**
> * it would be nice to also have icons for the various Open actions (Open Project Overview, Open Application Monitor, Open Performance Dashboard, etc.) especially since they all start with "Open".

**Usually I try to limit the design of icons to actions for which we need visual representation- as in if there will be a menu without words. Do any of these have that? We might also consider, if the concern is that its a lot of actions that start with "Open", to just limit the action title to what it is (e.g. "Application Monitor" instead of "Open Application Monitor") (what do you think @sishida).** 

> * the rest are not necessary - not all actions need an icon
> 
> Just a reminder that Eclipse icons must work in both light and dark mode - it does not support separate icons for the 2 modes.

**Comment by eharris369** [comment]
For manage template sources and manage image registries if we don't have an icon for them for VS code then we don't need one for Eclipse.

**Comment by thisguy-1** [comment]
@eharris369 I think I got them all, and I added some replace the ones youv'e been using already to make them more cohesive. If I've included it, then it should replace what you've been using even if it looks similar, since I might have made some tweaks. Please let me know if there are any problems. If not please comment and close. Thanks!
[Eclipse Icons.zip](https://github.com/eclipse/codewind/files/4047744/Eclipse.Icons.zip)

**Comment by eharris369** [comment]
Some comments/questions:
- I am not sure we should replace the Eclipse standard run and debug icons
- I don't see a disconnect icon
- What are the LocalProjectFail and LocalProjectSuccessful icons for? Currently we show the project type icon next to a project.

**Comment by thisguy-1** [comment]
> Some comments/questions:
> 
> * I am not sure we should replace the Eclipse standard run and debug icons

**If it is standard to eclipse then dont change it. If this debug is particular to codewind then we should.**
> * I don't see a disconnect icon

**We don't have one. We just use a toggle i've included it here**
![toggle pill off](https://user-images.githubusercontent.com/52169824/72271129-5609da00-35f4-11ea-8ee5-c6381e0eef35.png)
![toggle pill](https://user-images.githubusercontent.com/52169824/72271130-5609da00-35f4-11ea-8fc6-8a5e650dc0fe.png)
![toggle pills off@2](https://user-images.githubusercontent.com/52169824/72271131-5609da00-35f4-11ea-9f99-d92c9cd60774.png)
![toggle pills@2](https://user-images.githubusercontent.com/52169824/72271132-56a27080-35f4-11ea-8d58-09426ca2df11.png)


> * What are the LocalProjectFail and LocalProjectSuccessful icons for? Currently we show the project type icon next to a project.

**For the sake of consistency, we have the local icon also have a connected and disconnected status**

<img width="369" alt="Screen Shot 2020-01-13 at 10 31 18 AM" src="https://user-images.githubusercontent.com/52169824/72268536-fa3d5200-35ef-11ea-8f3c-3074574b4af4.png">

**Comment by thisguy-1** [comment]
<img width="465" alt="Screen Shot 2020-01-13 at 11 23 22 AM" src="https://user-images.githubusercontent.com/52169824/72272737-214b5200-35f7-11ea-9de6-0ff6a2d40c85.png">
