### ISSUE TITLE
Draw more attention to Stopped Codewind item

### ISSUE THREAD

**Issue by thisguy-1** [eclipse/codewind#156]
It's a good attention grabber. @tetchel

**Comment by tetchel** [comment]
This is a limitation of the VS Code treeview API, inline buttons only show when the item is selected. We can force focus but that would hijack keyboard focus which would be very annoying for the user. I'm not sure what else I could do

**Comment by thisguy-1** [comment]
Hijacking would not be good. If it cant be done it cant be done.

**Comment by thisguy-1** [comment]
Can this at least happen the first time a person click on "open workspace"? It does feel logical that you would want to go there.

**Comment by tetchel** [comment]
For starters, I opened https://github.com/microsoft/vscode/issues/78829

I can see about selecting it just once, but since users are generally clicking a lot of the time anyway I'm not sure they would even notice the selection (since it would be lost as soon as they click).

**Comment by thisguy-1** [comment]
Gotcha. Then lets not do this. Hopefully with it opening up, that will be sufficient. When it is open, is possible for the entire tree line be extended as well? (showing the the projects icon, and the click here to create...)?

**Comment by tetchel** [comment]
> When it is open, is possible for the entire tree line be extended as well?

It does do that once CW is started. What would it show if it's stopped?

**Comment by thisguy-1** [comment]
Projects (Connecting)>(Local)>(Disconnected)?
Something like that? Any ideaS @sishida ?

Or maybe just show the Projects Icon. Though it would be weird without anything in () and then getting the local status.

**Comment by sishida** [comment]
I'd have to see this in action to get a better idea of context, but if we want to show how a project is connecting, able to be used locally, and then disconnected, then I think that @thisguy-1's suggestion works.

**Comment by tetchel** [comment]
We can't make this change, but I will change the Stopped tree item to say `Stopped` on it which should draw some more attention to it to Start things.
