### ISSUE TITLE
Improve directory deletion when syncing changes

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#1560]
Currently, when syncing files to pfe, we don't do anything specfic for directories.  As such, if a directory has been removed, we individually delete each file rather than just `rm -fr` on the directory.

**Comment by james-wallis** [comment]
For this piece of work I'll need to make changes in 3 different places:
* Change the `/api/v1/projects/:id/upload/end` API to take a `directoryList` parameter.
* Modify `cwctl` to send a directoryList on the above API call.
* Modify PFE to delete by directory.
  * Delete directories
  * Rescan file system to get updated file system
  * Delete by individual file

**Comment by james-wallis** [comment]
PR raised for CLI https://github.com/eclipse/codewind-installer/pull/301/

**Comment by james-wallis** [comment]
PR raised for PFE https://github.com/eclipse/codewind/pull/1582

**Comment by james-wallis** [comment]
CLI PR merged.
