### ISSUE TITLE
Ensure build queue applies to all builds, not just restart of Codewind

### ISSUE THREAD

**Issue by rajivnathan** [eclipse/codewind#1563]
**Description of the enhancement:**

Related to #1383. There can be significant load when a user creates or updates many projects in a short period of time.

**Proposed solution:** 

The build queue should limit the number of builds that can run at any time. Any type of build (create/update)

**Comment by ssh24** [comment]
Not sure I understand the enhancement properly. What are you proposing?

**Comment by rajivnathan** [comment]
As the proposed solution says "Any type of build (create/update)". The build queue was original implemented for restart scenarios. It currently does not handle update builds. That may be related to the problems seen in #1383

**Comment by ssh24** [comment]
Ah, I see. So currently the build queue logic is for create/recreate scenarios. You are proposing for it to be extended to update scenarios as well
