### ISSUE TITLE
Use cwctl to remove projects

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#1565]
https://github.com/eclipse/codewind/issues/1291

**Comment by eharris369** [comment]
I checked the remove command and it is looking up the connection id based on the project id. Are all project ids unique even across connections?

**Comment by tetchel** [comment]
I asked that question a few months ago and the response was 'yes', I think it's not explicitly checked but given that there are 2^128 possible project IDs, the chance of a collision is basically impossible.

https://en.wikipedia.org/wiki/Universally_unique_identifier#Collisions

**Comment by jopit** [comment]
Done for IntelliJ: https://github.com/eclipse/codewind-intellij/pull/10

**Comment by tetchel** [comment]
I went to do this but I see https://github.com/eclipse/codewind/issues/2193 too
