### ISSUE TITLE
Remote changes gets detected after a long time

### ISSUE THREAD

**Issue by maysunfaisal** [eclipse/codewind#1569]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**
- Download 0.7.0 Codewind VS Code extension
- deploy remote CW using cwctl (I used the one under `~/.codewind/0.7.0`
- create remote connection and a project
- make changes to the local project

The changes gets picked up after >30s. This is bad UX.

/priority hot

**Comment by maysunfaisal** [comment]
could be related to #1570

**Comment by stalleyj** [comment]
@maysunfaisal Hi Maysun, could you provide a few more details please, what kind of project did you create ? How did you measure that it took 30s to pick up the changes ?  Was a build in progress when you edited the project ?

The FW should notify the cwctl immediately of the changes which will then call to sync files across and build. If there is a build in progress, the sync doesn't happen until this has finished.

**Comment by maysunfaisal** [comment]
@stalleyj it didnt matter what project type it was, saw it for pretty much any project type i tried.
There were no builds in progress, just the single file that i was editing. It was before the holidays, I am not sure if FW detected changes after 30s or if installer detected after 30s, but i think it is the latter. As for how i knew it was 30s, i used a stop watch to count the average time taken.

**Comment by stalleyj** [comment]
@maysunfaisal I didn't mean how did you measure the time, rather what exactly are you measuring ? 30 seconds from file save to what exactly ???

**Comment by tobespc** [comment]
closing this, we added timing info and its not being reported by anyone else
