### ISSUE TITLE
Tekton Pipeline Link and Icon

### ISSUE THREAD

**Issue by thisguy-1** [eclipse/codewind#157]
- [x] Design Pipeline Icon 
- [ ] Decide from where is will go (eg. command pallet, project info page, right click, and an icon on the hover).
@thisguy-1 @tetchel

**Comment by tetchel** [comment]
this is done, but with a crappy icon. It's not in the project info page, I'm not sure it makes sense to go there because there is no per-project feature.

https://github.com/eclipse/codewind-vscode/pull/144

**Comment by kimholmes** [comment]
Pipeline icon:
[pipeline.svg.zip](https://github.com/eclipse/codewind/files/3730923/pipeline.svg.zip)

**Comment by thisguy-1** [comment]
the pipeline icon is done. What's being discussed is what to call it, now that the name tekton won't be included, right? @deboer-tim

**Comment by tetchel** [comment]
yea #1542

**Comment by tetchel** [comment]
i think we can close this particular issue, the open tekton dashboard action has been available for months now
