### ISSUE TITLE
[0.7.0] Losing Remote connection frequently

### ISSUE THREAD

**Issue by maysunfaisal** [eclipse/codewind#1570]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**
I have a remote connection to my remote PFE from 0.7.0 VS Code extension

Every now and then I keep losing connection

![Screen Shot 2019-12-17 at 12 19 21 PM](https://user-images.githubusercontent.com/31771087/71019047-a8c0a680-20c7-11ea-9d3f-696c63f24ca2.png)

I have to refresh the view to get it back.

/priority hot

**Comment by tetchel** [comment]
Something is blocking the event loop (maybe calling a sync version of some `fs` function) causing the socket connection to go down

**Comment by jopit** [comment]
Do you have the logs from PFE?

**Comment by stalleyj** [comment]
I've tested this today and cannot recreate the issue which we are pretty sure was fixed by https://github.com/eclipse/codewind/pull/1582 @maysunfaisal please can you verify ?
