### ISSUE TITLE
SVT: VSCode: Linux: Default Java Microprofile and Java Spring projects failing to build on Ubuntu.

### ISSUE THREAD

**Issue by DavidG1011** [eclipse/codewind#1576]
**Codewind version:** 0.7.0
**OS:** Ubuntu 18.04.3 LTS

**Description:** Java Microprofile and Java Spring projects are failing to build in VSCode on Ubuntu.

**Steps to reproduce:**
1. Build a default Microprofile or Spring project:
<img width="403" alt="Screen Shot 2019-12-17 at 3 55 44 PM" src="https://user-images.githubusercontent.com/30476587/71033644-bdac3280-20e5-11ea-88f6-dbc24c27e395.png">

Log:
[pfe.txt](https://github.com/eclipse/codewind/files/3975472/pfe.txt)

FYI: @jagraj

**Comment by ssh24** [comment]
Looks like the failure is on:
```
[91m[17/12/19 20:31:48 javamicro] [ERROR][39m executeBuildScript : 399 | docker: Error response from daemon: error while creating mount source path '/codewind-workspace/.logs/javamicro-fb1fe5f0-210b-11ea-b1a1-7f531288df6f': mkdir /codewind-workspace: read-only file system.
```

**Comment by ssh24** [comment]
@DavidG1011 Did you make sure to start VSCode as a root user in Ubuntu?

**Comment by DavidG1011** [comment]
Running as root as far as I know

**Comment by jagraj** [comment]
I am trying on my linux system now with eclipse plugin. Will post the results here.

**Comment by jagraj** [comment]
Looks good on my RHEL 7.2 machine, both default Java and Spring projects built fine. I think this might be related to mount issue with the permissions.

![Screen Shot 2019-12-17 at 4 46 08 PM](https://user-images.githubusercontent.com/713849/71037181-306cdc00-20ed-11ea-9311-b70c5c56d0a6.png)

**Comment by DavidG1011** [comment]
I had a leftover `/codewind-workspace` directory, so I tried removing it. Still running into the same issue:
[pfe_2.txt](https://github.com/eclipse/codewind/files/3975690/pfe_2.txt)

**Comment by ssh24** [comment]
@DavidG1011 Could you please verify this on master?

**Comment by DavidG1011** [comment]
Sorry for the delay. This is fixed on master.
