### ISSUE TITLE
Create a mustgather script for Codewind

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#1579]
We currently have no mustgather script that we can ask users to run when they open bugs related to Codewind. Given that not every user of Codewind will be entirely familiar with Docker or Kubernetes, it might be useful to have a simple, easy to run script that does the following, on both local Codewind and Codewind on Kube (Che or Hybrid):
- Determines Docker and/or Kubernetes version, and if it's running on an OpenShift cluster
- Determines Codewind version (and/or image hashes)
- Retrieves the logs for all of the Codewind containers: PFE, Performance, Che sidecar, Keycloak, and Gatekeeper (latter three where applicable)
- Gets the pods and services running in Codewind's namespace
- Anything else?

**Note:** We had a similar must gather script back in the Microclimate days that did similar things: https://github.com/microclimate-dev2ops/serviceability

**Comment by johnmcollier** [comment]
Some kind of `must gather` command in the IDEs would also work fine here.

**Comment by jopit** [comment]
Portal team to investigate

**Comment by tobespc** [comment]
@stalleyj Can you look at this alongside the uninstall work.  My thinking is that whilst looking at all the things to remove, we can build the list of all the things to gather info from.   Adding it to cwctl would mean its easier to run from the IDE's

**Comment by mattcolegate** [comment]
Discussion doc and first pass design
[MustGather.zip](https://github.com/eclipse/codewind/files/4349882/MustGather.zip)

**Comment by mattcolegate** [comment]
### Proposed first pass

* Single script
* Local only
* Gathers: 
  * Container logs for Codewind
  * Container logs for Apps
  * IDE log for either Eclipse or VSCode
  * Codewind files from PFE (.project)
  * CWCTL version info
  * Docker inspect Codewind containers
  * Docker compose file (Codewind home)

**Comment by mattcolegate** [comment]
First pass script is available on branch https://github.com/mattcolegate/codewind/tree/mustGatherScriptV1. It has become clear during development that integration with the CWCTL CLI is the preferred delivery vehicle, so I am proceeding with that.

**Comment by mattcolegate** [comment]
Code for the CLI version of mustgather (inc. the code used for the playback demo) is available at https://github.com/mattcolegate/codewind-installer/tree/mustgatherCli

As of today, it collects (Local only):
* Codewind container inspection and logs
* Project container inspection and logs
* Docker-compose.yaml
* CWCTL version.

Mustgather file location: .codewind/mustdather/${DATETIME}/

Still to do:
* Collect Ide logs (VSCode, Eclipse)
* Collect Codewind PFE workspace
* Quiet mode for IDE usage (no output to sysout)
* Make Project container collection optional
* Automatic zipping if available

**Comment by mattcolegate** [comment]
All local content now available at https://github.com/mattcolegate/codewind-installer/tree/mustgatherCli - will need testing on Mac, as I've only developed on Windows. I should also probably work out how to write tests, but (as ever) the current testing package doesn't work on Windows. Next job will be working out how to gather this stuff from Remote connections.

**Comment by mattcolegate** [comment]
/label area/docs
Docs, hopefully there's enough info in the readme and the usage to get you going on this, but do write here if there's anything non-obvious @micgibso

**Comment by james-wallis** [comment]
I've tested the `cwctl mustgather` multiple times on Mac, using the `--quiet` and `--projects` flags.
I can confirm that I get PFE and performance container's `inspect` and `log` files and when given the `--projects` flag I get an `inspect` and `log` file for each project.
Nice work.

**Comment by mattcolegate** [comment]
Hi @johnmcollier @tobespc , given this works on Windows and Mac we're keen to put the Local-only solution out to the master branch so the team can use it and comment on it rather than hang on until remote is done - are you happy for us to do that?

**Comment by tobespc** [comment]
please release this for local

**Comment by mattcolegate** [comment]
Feedback from Scrum demo
* add `--nozip` option that will leave the individual files and not create a zip. default behavior should be to just have a zip file and delete the gathered files.
* collect docker version and browser versions
* create an extra 'environment' file that will contain key information for 'at-a-glance' views. @tobespc will list the contents of that file below.

**Comment by tobespc** [comment]
So what I would like to see is all the version information that is contained within each of the artifacts collected and pulled into a separate file.   This file could also contain the OS version, docker version (kube for remote) and the browser versions.

Then, can we have a 
```
cwctl -mg -clean
```

function that will remove all local mustgather zip files

**Comment by AndyRWatson** [comment]
Some additional thoughts for useful info for the environment/summary file

- Local os and version
- Local system summary information (if available.  CPU/Memory ) 
- IDE version
- docker registry links 
- configured template source(s)

**Comment by mattcolegate** [comment]
@tobespc Clarification on the `-clean` option - do you just want the zip files removed or all files? (with the `--nozip` option collected individual files will remain on disk)

**Comment by tobespc** [comment]
all mustgather files (directories as well).   So its like we were never there.....

**Comment by mattcolegate** [comment]
`--nozip` and `--clean` options pushed up to https://github.com/eclipse/codewind-installer/pull/436, as well as collection of codewind container versions. Working on rest of list for summary file

**Comment by jopit** [comment]
See this article for info on where the IntelliJ logs may be found: https://intellij-support.jetbrains.com/hc/en-us/articles/206544519

**Comment by mattcolegate** [comment]
Local mustgather now delivered through https://github.com/eclipse/codewind-installer/pull/436. Now working on remote gathering. Will update when first remote statistic can be gathered.

**Comment by mattcolegate** [comment]
mustgather code for Remote gathering of Codewind Pods is now available at https://github.com/mattcolegate/codewind-installer/tree/mustgatherRemote for trial purposes. To use this, one must have their Kubectl connection to the remote cluster configured. 
`./cwctl mg --conid connectionID/connectionLabel`

**Comment by mattcolegate** [comment]
PR for remote gather of Codewind & Project logs & description https://github.com/eclipse/codewind-installer/pull/444

**Comment by mattcolegate** [comment]
@micgibso Please note the above for docs, starting to put remote mustgather into the codebase - let me know if you have any questions or want a demo

**Comment by mattcolegate** [comment]
New requirement from @stalleyj via https://github.com/eclipse/codewind-installer/pull/444 - allow mustgather to gather from all connections in one go

**Comment by mattcolegate** [comment]
@tobespc Yesterday you expressed concern that I was gathering the whole of the codewind-workspace - can you please reply to this issue stating which parts of the workspace should be gathered?

**Comment by tobespc** [comment]
not the source code

**Comment by mattcolegate** [comment]
Going to sum up this issue now and deal with the oustanding work via separate issues.
`cwctl diagnostics` has been delivered into the codebase able to gather the following:
* Local
  * Codewind container logs & inspection
  * Project container logs & inspection
  * Codewind versions collection (cwctl version, pfe version, performance version)
  * Eclipse log collection
  * VSCode log collection
  * Docker-compose.yaml collection
  * PFE Codewind-workspace collection
* Remote
  * Codewind container logs & description
  * Project container logs & description
`--json` support for the IDEs is also present.

The outstanding issues for diagnostics are:
https://github.com/eclipse/codewind/issues/2767
https://github.com/eclipse/codewind/issues/2793
https://github.com/eclipse/codewind/issues/2794
https://github.com/eclipse/codewind/issues/2795
https://github.com/eclipse/codewind/issues/2796
https://github.com/eclipse/codewind/issues/2797
https://github.com/eclipse/codewind/issues/2800

This issue can now be closed.
/pipeline verify

**Comment by mattcolegate** [comment]
@johnmcollier are you able to verify this issue please?
