### ISSUE TITLE
Improve Notification For Create Project

### ISSUE THREAD

**Issue by thisguy-1** [eclipse/codewind#158]
Users are confused by what is happening after they create new project and it is building.
- [ ] Add a building notification with progress bar (or whatever VScode calls that moving blue bar)

@tetchel 
@thisguy-1

**Comment by tetchel** [comment]
do we want to do this just on the initial build?

**Comment by thisguy-1** [comment]
Yes. Let's only do it on the initial build for now.

**Comment by thisguy-1** [comment]
It makes sense because this is the longest one.

**Comment by tetchel** [comment]
Do we need this _and_ #161 ? They seem to have the same goal

**Comment by thisguy-1** [comment]
Once we have the improved one, probably not, but until we have the 161 implemented, this at least will work somewhat.

**Comment by tetchel** [comment]
I think this flow has been improved a lot, do we still need this issue?
