### ISSUE TITLE
Move docker registry topic

### ISSUE THREAD

**Issue by micgibso** [eclipse/codewind#1585]
The dockerregistry.md topic is no longer Che specific so move into each IDE section by having multiple copies of the same file located under each of the IDE specific-help.

For more info, see https://github.com/eclipse/codewind-docs/pull/261

20/12 Also see PR https://github.com/eclipse/codewind-docs/pull/274

---
02/01 Looking at this today, we have two identical files in our source with different filenames: dockerregistry.md and image-registry-credentials.md. The latter isn't linked from anywhere in our doc source, @jopit @jingfuwang can you check it isn't linked anywhere from the UI please?

Assuming it isn't, have created this PR to remove it: https://github.com/eclipse/codewind-docs/pull/277

Next up, will move this topic and intentionally duplicate it across the different IDEs with IDE specific file names, as we have done before for with, for example, the Working with templates topic.

**Comment by jopit** [comment]
The `image-registry-credentials.md` page is referred to by the IDEs, so should not be removed.

**Comment by micgibso** [comment]
Duplicate topic removed, topic move superseded by help restructure. Closing...
