### ISSUE TITLE
Repurpose Performance Monitoring topic into a guide

### ISSUE THREAD

**Issue by MelHopper** [eclipse/codewind#1586]
The performance monitoring content in the table of contents topic tree was originally written as a Guide. Now that we will have a Guides section on our new Docs Landing Page, we can repurpose this content back into a performance monitoring Guide.

Current content is located at: 
https://www.eclipse.org/codewind/guide_performance.html

Time Estimate: 1 full day

**Comment by j-c-berger** [comment]
Assign to me, please!

**Comment by micgibso** [comment]
ID to revisit post 0.8.0 release
