### ISSUE TITLE
Repurpose the Kabanero.io Getting Started with Codewind Guide for the Codewind website

### ISSUE THREAD

**Issue by MelHopper** [eclipse/codewind#1587]
Guides are to be created in 2020 for the codewind.dev website.

The first Guide to be created is a Getting Started guide.

Getting Started on Codewind content currently exists as a guide on kabanero.io: 
https://kabanero.io/guides/guide-codewind/

This task is to duplicate and repurpose this kabanero.io guide content so that it is suitable to be used as a Codewind guide on the Codewind.dev website.

Time Estimate: 1 week

**Comment by j-c-berger** [comment]
Assign to me, please!

**Comment by micgibso** [comment]
ID to revisit post 0.8.0 release

**Comment by micgibso** [comment]
@j-c-berger @MelHopper to follow up.
