### ISSUE TITLE
No message when add template source fails

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#1597]
**Codewind version:** master
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**

This was on VS code.  If I add a template source and it fails (e.g. trying to add URL that already in Codewind), it will just silently do nothing.

**Steps to reproduce:**

1. Add https://raw.githubusercontent.com/codewind-resources/codewind-templates/master/devfiles/index.json; nothing happens
2. Add https://github.com/appsody/stacks/releases/latest/download/experimental-index.json; nothing happens
   - (this fails because the experimental repo is already pre-configured in the appsody CLI, however the appsody extension hides the experimental repo from Codewind)

**Workaround:**

**Comment by makandre** [comment]
On Eclipse, it will appear as if the add was successful; it will get added to the list, but when you re-open the template manager, the new repo won't be in the list.

**Comment by jopit** [comment]
The problem is that cwctl is reporting the error back to the IDEs in plain text, not JSON as requested.  You can see this by issuing the same cwctl command from the terminal:
```
% ./cwctl --json --insecure templates repos add --conid local --url https://raw.githubusercontent.com/codewind-resources/codewind-templates/master/devfiles/index.json --name Testing --description testing
2019/12/19 12:47:53 Error adding template repo: "Error: PFE responded with status code 400"
```
I also think PFE/cwctl need to return a more useful error message.

**Comment by nastacio** [comment]
VS-Code still fails, but now returns this cryptic message: "Error adding new template source: Error: PFE responded with status code 400"

On a related note about error messages meant for end-users, they would not know what a "PFE" is.

**Comment by stalleyj** [comment]
This has been fixed with a sensible error message for users @makandre Can you verify please.
./cwctl --json --insecure templates repos add --conid local --url https://raw.githubusercontent.com/codewind-resources/codewind-templates/master/devfiles/index.json --name Testing --description testing
{"error":"ADD_REPO_ERROR","error_description":"Error: Bad Request - https://raw.githubusercontent.com/codewind-resources/codewind-templates/master/devfiles/index.json is already a template repository"}

![Screenshot 2020-04-23 at 12 04 18](https://user-images.githubusercontent.com/13417476/80092367-931e2a80-855a-11ea-94a1-8f7e0dc02b92.png)

**Comment by makandre** [comment]
Verified for VSCode.

On Eclipse, I still got the same silent behaviour when adding https://raw.githubusercontent.com/codewind-resources/codewind-templates/master/devfiles/index.json

(I got the error when adding https://github.com/appsody/stacks/releases/latest/download/experimental-index.json)

@stalleyj @eharris369

**Comment by eharris369** [comment]
Looks like an issue with how Eclipse is checking for changes once the user clicks ok. Because that url already exists it thinks there is no change.

**Comment by eharris369** [comment]
Eclipse is fixed now: https://github.com/eclipse/codewind-eclipse/pull/709

**Comment by makandre** [comment]
Verified Eclipse, thanks.
