### ISSUE TITLE
Latest installer failing to start PFE

### ISSUE THREAD

**Issue by ssh24** [eclipse/codewind#1599]
I am seeing this on windows with latest installer pulled in this morning:
```
$ ./cwctl start
Debug: false
==> created file C:\/C:\Users\Administrator/.codewind/docker-compose.yaml
==> environment structure written to C:\Users\Administrator/.codewind/docker-compose.yaml
System architecture is:  amd64
Host operating system is:  windows
Attempting to find available port
Port 10000 Available
Please wait whilst containers initialize...
2019/12/19 11:17:42 DOCKER_COMPOSE_ERROR[101]: exit status 1. docker-compose command failed to execute correctly
```

**Comment by liamchampton** [comment]
@ssh24 `created file C:\/C:\Users\...` this home directory looks a bit funky. 
1) Are you getting this every time?
2) What is the value of your environment var `USERPROFILE`?

**Comment by ssh24** [comment]
Yes, it was happening everytime
```
Administrator@tb-win-test MINGW64 /c
$ echo $USERPROFILE
C:\Users\Administrator
```

**Comment by ssh24** [comment]
So this issue seems intermittent. I just tried it again on the test windows and it worked. One thing to note, the test windows machine does pull down the latest installer everytime, so maybe sometimes the installer executable is not pulled properly?

**Comment by ssh24** [comment]
Closing for now. Will reopen if seen again
