### ISSUE TITLE
New Project Info Page Pops Up after Create New Project & Add Existing...

### ISSUE THREAD

**Issue by thisguy-1** [eclipse/codewind#160]
User should also have a the ability to disable if s/he chooses. 
@tetchel @thisguy-1

**Comment by deboer-tim** [comment]
Are you talking about the project's readme here? Is the usability of seeing and closing it that bad since project creation is not that frequent?

I ask because template creators often want to show a quick summary of what's in the project the user just created to help them get started, and I've heard from another group that wants to expand on this.

**Comment by tetchel** [comment]
he is referring to the Project Overview page. The README makes sense too, iff the project has one.

**Comment by deboer-tim** [comment]
Ah. Maybe we should have a discussion or there is more detail elsewhere, but which Codewind concepts do we want to introduce them to, and couldn't we do that as part of the initial welcome? I'm a little anxious about showing two pages for different reasons and just want to make sure we have a plan for how this fit together in a clean flow.

**Comment by thisguy-1** [comment]
@deboer-tim  
I'm not familiar with the difference between project readme and the project overview. I am referring to this:
<img width="1662" alt="Screen Shot 2019-08-12 at 5 11 43 PM" src="https://user-images.githubusercontent.com/52169824/62898857-84714980-bd24-11e9-9390-f68a292fcb94.png">
Im guessing the readme is this:
<img width="1677" alt="Screen Shot 2019-08-12 at 5 12 30 PM" src="https://user-images.githubusercontent.com/52169824/62898885-905d0b80-bd24-11e9-82e8-e5c0478edf9e.png">

There are several advantages to having the overview (the first image) pop up after they make their first project (and these are just some ideas):
- Increase learnability by having buttons to contextual functions that otherwise they'd have to discover via the palette or by right-clicking, something we have found in the study users do not automatically do (eg. Open App button)
- Better understand the statuses
- It could potentially link to Kabanero, IBM, Appsody etc, where they could better learn about the different stacks.
- It could contain more information on the template itself.

The problem with the Readme would be that they would be tasked with finding it, assuming they would even go looking for it. They have to stumble on it. Considering the difficulty they already have with understanding the relationship between the codewind explorer and the codewind-workspace, I think for now our best bet is using the overview page.

**Comment by thisguy-1** [comment]
Based on our conversation, I will mock up a Project Overview page with collapsable information that doesn't have to be seen and a section for the readme.

**Comment by thisguy-1** [comment]
As an edit to the above, having a "readme section" is not possible, so the readme will popup next to the overview, and a link to the readme file will be in the overview.

**Comment by thisguy-1** [comment]
Work in progress, need feedback @jopit @elsony @tetchel @deboer-tim :
<img width="731" alt="Screen Shot 2019-08-23 at 2 04 34 PM" src="https://user-images.githubusercontent.com/52169824/63613524-f82a1680-c5ae-11e9-9b0e-533489bb127e.png">

**Comment by tetchel** [comment]
The overview page is opened on create/add now, but i think we are still considering the new overview page for future

**Comment by thisguy-1** [comment]
Yes, for now we have kept the old version, but I have designed a new one which I hope will be implemented. If you like, we can close this one and open a new one that reflects the redesign of the overview page.

**Comment by thisguy-1** [comment]
in fact we have that already: https://github.com/eclipse/codewind/issues/161
