### ISSUE TITLE
Host Blog content directly on codewind.dev

### ISSUE THREAD

**Issue by AndyRWatson** [eclipse/codewind#1601]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description of the enhancement:**

There have been some discussion on which blogging sites we should be using / linking from our landing page, particularly around people potentially leaving our site to read the blogs.   Currently we link to Medium and we are also considering other alternatives such as eclipse (especially as we are an eclipse project).

The current requested option is to follow other projects, such as Kabanero.io (who are consuming codewind in their project) who host their blog content and RSS feeds on their pages directly.   Opening this issue to track/discuss furher

**Proposed solution:** 
Implement direct blog capability within the codewind.dev site

**Comment by jgwest** [comment]
Adding area tags, feel free to remove if not applicable.

**Comment by travis1111** [comment]
we also need design input

**Comment by MelHopper** [comment]
Mel taking this. In Discussion with Kim re. final details of Docs LP design.

**Comment by sghung** [comment]
Can this be brought up to Rob and Tim? Since we are an eclipse open source project, it is nice to have our site in the eclipse domain. In addition to having good search engine optimization from being in the eclipse.org domain, the hosted site is similar to what Eclipse che uses.

**Comment by AndyRWatson** [comment]
Bringing the discussion up again as we need to close out on how best to ensure blog posts remain within the scope of codewind.dev rather than a 3rd party site such as medium

**Comment by sghung** [comment]
My prototype based on Kabanero.io's blogs. I took their CSS and their blog posts and put them into our repo. I created a new blog layout that displays our contents. The PR: https://github.com/eclipse/codewind-docs/pull/463

![image](https://user-images.githubusercontent.com/7843164/76027997-a66c2c80-5eff-11ea-8c97-4ee6792c8d98.png)
![image](https://user-images.githubusercontent.com/7843164/76028002-abc97700-5eff-11ea-9ac3-510926e3a2f3.png)
![image](https://user-images.githubusercontent.com/7843164/76028005-ad933a80-5eff-11ea-92bf-629eb9957e24.png)

**Comment by micgibso** [comment]
Is this now complete? Can it be closed?
