### ISSUE TITLE
'inject metrics' could be clearer for Users, in 0.7.0 release news 

### ISSUE THREAD

**Issue by NikCanvin** [eclipse/codewind#1603]
re: https://www.eclipse.org/codewind/news07.html

I installed 0.7.0, looked at the news article and wanted to try the new features. The first fully ready feature (Remote is labelled 'Tech Prev') was 'inject metrics'. As a pre-exisintg User (I used 0.6.0 a lot) I could not figure out what the feature would do for me (I already had metrics working, so why would I ever want to 'inject metrics'. 

I drilled into the first link and found a 'deisgn document' which provided no help for me (https://github.com/codewind-resources/design-documentation/blob/master/codewindServer/metricsInjection.md).. 

I then drilled into the second link and found an Implementation issue which was also not for User consumption (https://github.com/eclipse/codewind/issues/1290).

So I played with the feature in VSCode and tripped over a bug (I have now raised https://github.com/eclipse/codewind/issues/1602), which added to my confusion. While trying to figure this bug out, I unproductively experimented with OpenLiberty..  I subsequently heard (from Jag) that OpenLiberty is not supported, but the news item stated 'Liberty' is supported.
..
Also, I attempted to find an online section in the docs for 'application monitoring', but found none (I only found 'Peformance Monitoring').. 
..
I hope this feedback might lead to a rewrite of the releated news bullet + some clearer doc for the actual feature.

**Comment by micgibso** [comment]
Issue https://github.com/eclipse/codewind/issues/1607 raised for missing app monitoring section.
@beccabau, @sishida fyi.

**Comment by sishida** [comment]
@beccabau, Would you like to work on this? If so, please add a comment so I can assign you.

I should also have the bandwidth to help with news needs this release--please just let me know. Thanks!

**Comment by beccabau** [comment]
Yeah @sishida - let's work on this together.

**Comment by sishida** [comment]
@tobespc Hi, Toby!
Becca and I were looking at this issue, and we were wondering if the Codewind website should have instructions on injecting metrics and application monitoring?

We're aware of the design doc here https://github.com/codewind-resources/design-documentation/blob/master/codewindServer/metricsInjection.md, but perhaps we should also include instructions on Codewind.dev?

Thank you!

**Comment by sishida** [comment]
Clarification for the word "Liberty" added with these PRs:
1️⃣ Edits to master branch: https://github.com/eclipse/codewind-docs/pull/283
2️⃣ Edits to 0.8.0 release branch: https://github.com/eclipse/codewind-docs/pull/291

**Comment by sishida** [comment]
- Here is the issue for adding injection metrics documentation to the Codewind website: https://github.com/eclipse/codewind/issues/1763#event-2950567005.
- Here is the link to the video: https://youtu.be/LsjmnMCuBxo
- Because the video was not ready by the time we published the 0.7.0 news, and because the docs don't exist yet, I think it's best to leave the 0.7.0 news as it is. The news page is marked with a date and shows what we had at that time.
- I think it would be better to highlight significant doc changes in a future news page instead of going back and trying to update old news pages. Thus, I am closing this issue.
