### ISSUE TITLE
Update CHE installation instructions to include codewind-checluster.yaml

### ISSUE THREAD

**Issue by AndyRWatson** [eclipse/codewind#1605]
**Codewind version:** 0.7
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description of the enhancement:**

In the current codewind che installation instructions we make reference to downloading the codewind-checluster.yaml (typo on page which references 'codewind-che checluster yaml' )  and then in the following paragraph we reference the file in the chectl command as  <codewind-che.yaml file>.   

```
Install Che:
    On OpenShift, run the following command: chectl server:start --platform=openshift --installer=operator --che-operator-cr-yaml=<codewind-che.yaml file> --che-operator-image=quay.io/eclipse/che-operator:7.3.1
    On Kubernetes, run the following command: chectl server:start --platform=k8s --installer=operator --domain=<ingress-domain> --che-operator-cr-yaml=<codewind-che.yaml file> --che-operator-image=quay.io/eclipse/che-operator:7.3.1
```
I'd like to request we update the example to include the actual file name we just asked the user to download.

**Proposed solution:** 

correct example to reference file as 'codewind-checluster.yaml'

```
Install Che:
    On OpenShift, run the following command: chectl server:start --platform=openshift --installer=operator --che-operator-cr-yaml=codewind-checluster.yaml --che-operator-image=quay.io/eclipse/che-operator:7.3.1
    On Kubernetes, run the following command: chectl server:start --platform=k8s --installer=operator --domain=<ingress-domain> --che-operator-cr-yaml=codewind-checluster.yaml --che-operator-image=quay.io/eclipse/che-operator:7.3.1
```

**Comment by johnmcollier** [comment]
Yeah, that's a fair request. I'll update the docs.

@sishida Any thoughts/concerns?

**Comment by AndyRWatson** [comment]
Thanks @johnmcollier

**Comment by micgibso** [comment]
@AndyRWatson @johnmcollier Changes on above PR, please review.
