### ISSUE TITLE
Application Monitoring document on web is missing

### ISSUE THREAD

**Issue by NikCanvin** [eclipse/codewind#1607]
The online docs: https://www.eclipse.org/codewind/gettingstarted.html
no longer has section for application monitoring 
(if fact has no mention of application monitoring, except from the 0.7.0 news article)
..
I chatted with Toby, he verified some doc for 'application monitoring' used to be there, but is no longer.

**Comment by micgibso** [comment]
Application monitoring is at the IDE level, see https://www.eclipse.org/codewind/mdteclipsemanagingprojects.html and https://www.eclipse.org/codewind/mdt-vsc-commands-project.html.  

We do have a topic that isn't currently in our toc: https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/appmetrics.md. Is this the one that you chatted to Toby about?

**Comment by micgibso** [comment]
Confirmed as https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/appmetrics.md
Restored for 0.9.0, see https://github.com/eclipse/codewind-docs/blob/master/docs/_data/docstoc.yml
