### ISSUE TITLE
Ensure all 'kubectl' commands in our Kube tests have the namespace flag

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#1614]
It looks like some of our Kubectl commands in the Codewind-che and codewind functional tests are missing the `-n <namespace>` flag. If the oc and kubectl clients are configured to point to a different namespace than where the tests are running, this could cause test failures. E.g:
- https://github.com/eclipse/codewind-che-plugin/blob/master/codewind-che-sidecar/tests/testutil.bash#L103
- https://github.com/eclipse/codewind/blob/master/src/pfe/file-watcher/server/test/scripts/exec.sh#L93

We need to make sure every `kubectl` and `oc` command in our tests that interacts with namespaced resources (pods, services, roles, etc) has the `-n <namespace>` flag, where `<namespace>` is the namespace where the tests (and Codewind) are running.

**Comment by ssh24** [comment]
We don't need it for https://github.com/eclipse/codewind/blob/master/src/pfe/file-watcher/server/test/scripts/exec.sh#L93 because the functional test does do `oc project $NAMESPACE` before going to that step.

However, it is needed for sidecar tests

**Comment by ssh24** [comment]
Looks like we do it for SC as well:
https://github.com/eclipse/codewind-che-plugin/blob/master/codewind-che-sidecar/tests/sidecarfvt.bats#L38
https://github.com/eclipse/codewind-che-plugin/blob/master/codewind-che-sidecar/tests/cronjob-sidecar.sh#L54
I think this issue can be closed.

**Comment by johnmcollier** [comment]
IMO, we should be adding the flag to the kubectl and oc commands to be safe, and **not** relying on an implicit `oc project` command
