### ISSUE TITLE
Explore right click use for codewind- workspace

### ISSUE THREAD

**Issue by thisguy-1** [eclipse/codewind#162]
Is it as simple as having the same right click menu as projects?
@tetchel

**Comment by tetchel** [comment]
Sorry, I don't understand this one

**Comment by thisguy-1** [comment]
Remember when i presented, that I pointed out that most people tried clicking around the worskspace rather than the extension. For example, if I said to try and open their app in the browser, they either thought they needed to do it through the terminal or through the workspace.

**Comment by thisguy-1** [comment]
Not sure if it will be useful with all the other changes we are making, but worth exploring.

**Comment by tetchel** [comment]
We can only do that if we are OK with all the Codewind actions appearing on _all_ folders in the Explorer view, regardless of what folders are open (codewind or otherwise). The extension API is very limited in this.

**Comment by sishida** [comment]
@tetchel @thisguy-1 
Hi, team, I noticed this issue when looking for another issue. Is this issue still relevant, or could we close it? If we want to keep it open, are there actions that we can start taking to make progress toward closing it? Thank you!
