### ISSUE TITLE
SVT: If the creation of an image registry is canceled in the namespace step, it will create the registry anyway

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#1621]
**Codewind version:** Latest
**OS:** Red Hat Enterprise Linux 7 (64 bit)

**Che version:** 7.3.1
**Kubernetes cluster:** OKD/Openshift 

**Description:** If the creation of an image registry is canceled in the `namespace` step, using the `ESC` key, it will create the registry anyway. That doesn't happen in the previous steps.

I know you can create a registry using a blank namespace, and that's why Codewind is allowing creation. However, if a user makes a mistake and wishes to create the appropriate registry, the current action cannot be canceled. It should be good to allow the user to cancel the action since the registries cannot be edited once they are created: https://github.com/eclipse/codewind/issues/1523

<img width="1678" alt="Screen Shot 2020-01-02 at 12 52 59 PM" src="https://user-images.githubusercontent.com/49531960/71682844-dad83680-2d5e-11ea-8886-9cb0766bee8a.png">

<img width="1675" alt="Screen Shot 2020-01-02 at 12 54 12 PM" src="https://user-images.githubusercontent.com/49531960/71682898-04915d80-2d5f-11ea-8c66-fd24e32b0573.png">

@jagraj

**Comment by tetchel** [comment]
so, you want an additional confirmation step after everything is entered, before creating?

it seems like this could be fixed by edit support ie https://github.com/eclipse/codewind/issues/1523

**Comment by sujeilyfonseca** [comment]
No, it is not an extra step. It is just that the action is not canceled if the user wishes to cancel it. In previous steps, a user can cancel the creation action without any problem.

**Comment by tetchel** [comment]
i guess esc could cancel the whole process.

**Comment by malincoln** [comment]
@sujeilyfonseca pls verify and close if resolved.  Thanks

**Comment by sujeilyfonseca** [comment]
I can still reproduce the problem. If you press `ESC` for the first time, it does nothing. If you press `ESC` a second time, it create the registry anyway.

<img width="1666" alt="Screen Shot 2020-01-07 at 4 11 19 PM" src="https://user-images.githubusercontent.com/49531960/71930707-33963d80-316a-11ea-8f8c-1fd2c10c2837.png">

**Comment by tetchel** [comment]
@sujeilyfonseca can you confirm if this is fixed in your 0.8 testing?

**Comment by sujeilyfonseca** [comment]
I have tried to test this issue with Codewind 0.8.0 and Eclipse Che 7.5.1, but I cannot execute this scenario yet since I still see the following issue: https://github.com/eclipse/codewind/issues/1665:

<img width="1348" alt="Screen Shot 2020-01-11 at 12 43 54 AM" src="https://user-images.githubusercontent.com/49531960/72199543-80e50a00-340b-11ea-98a0-1123ee4568c5.png">

**Comment by sujeilyfonseca** [comment]
I have tried to test this problem with Codewind 0.8.0 and Eclipse Che 7.5.1, but I still can't run this scenario yet because I still see the following problem.

**Comment by sujeilyfonseca** [comment]
I have tested this scenario with Codewind 0.8.0 and Eclipse Che 7.5.1, and Codewind still creates the registry even when creation is canceled using the `ESC` key:

<img width="1428" alt="Screen Shot 2020-01-14 at 9 42 34 AM" src="https://user-images.githubusercontent.com/49531960/72353534-39cc7280-36b2-11ea-8fdc-db3d1015901b.png">


If a user creates a registry with a namespace and then deletes it, Codewind will use the old namespace if the user tries to create a new registry and cancel the action in the `namespace` step:

<img width="1479" alt="Screen Shot 2020-01-14 at 9 15 56 AM" src="https://user-images.githubusercontent.com/49531960/72353558-45b83480-36b2-11ea-8192-50f2c1c2ef81.png">

<img width="1490" alt="Screen Shot 2020-01-14 at 9 16 27 AM" src="https://user-images.githubusercontent.com/49531960/72353577-48b32500-36b2-11ea-810a-da94ef67bae4.png">

**Comment by tetchel** [comment]
hmm. It works as it should on VS Code but I will have to test Che again.

> If a user creates a registry with a namespace and then deletes it, Codewind will use the old namespace if the user tries to create a new registry and cancel the action in the namespace step

That's a separate issue https://github.com/eclipse/codewind/issues/1440

**Comment by tetchel** [comment]
Try again

**Comment by malincoln** [comment]
@sujeilyfonseca are you able to verify the fix?

**Comment by sujeilyfonseca** [comment]
I verified this issue with the latest Codewind 0.8.0, and I no longer see the problem.
