### ISSUE TITLE
Need cli-pull.sh to be updated to download ppc64le specific binary

### ISSUE THREAD

**Issue by vrushaliinamdar** [eclipse/codewind#1623]
**Codewind version: 0.7.0**
**OS: RHEL 7.7 PPC64LE **

**Description of the enhancement:**
There is a "cwctl-ppc64le" binary download available at http://download.eclipse.org/codewind/codewind-installer/master/latest/cwctl-ppc64le. But to make this download happen automatically, the "cli-pull.sh" needs to be updated to use ppc64le as a platform.

**Comment by tetchel** [comment]
in your scenario who is running the cli-pull script? is it for development, or are we trying to run the plugins on ppc64le platforms now?

**Comment by vrushaliinamdar** [comment]
@tetchel  Yes, it is getting downloaded as part of start.sh

**Comment by tetchel** [comment]
What does `uname -m` output?

**Comment by tetchel** [comment]
@vrushaliinamdar can you try it now? run `export export CW_CLI_PLATFORM=ppc64le` before `start.sh` (README)[https://github.com/eclipse/codewind-vscode/tree/master/dev/bin).
