### ISSUE TITLE
Performance Dashboard Design Enhancements and Bug Fixes - User Feedback

### ISSUE THREAD

**Issue by thisguy-1** [eclipse/codewind#164]
Run Load test needs to have its settings set the first time is set
- [ ] What the setting were for each run load test needs to be able to be looked up
- [ ] The colors associated with each measurement needs to be more obvious
- [ ]  What the setting were for the latest run test needs to be on screen
- [x] Solve the issue of when to lines overlap in the graph
- [x] "Unable to render" error
        - Fix bug
       - Trouble shoot instructions or link
        - Add refresh button

@tobespc @thisguy-1

**Comment by markcor11** [comment]
PR: https://github.com/eclipse/codewind/pull/202

**Comment by kimholmes** [comment]
@tobespc

**Comment by mii-w** [comment]
In Progress Wire Frames for tomorrow's meeting reference
<img width="908" alt="Screen Shot 2019-12-09 at 4 32 40 PM" src="https://media.github.ibm.com/user/207956/files/b2338880-1aa1-11ea-88ac-194b9bd24ffc">
<img width="718" alt="Screen Shot 2019-12-09 at 4 32 49 PM" src="https://media.github.ibm.com/user/207956/files/b3fd4c00-1aa1-11ea-9480-1b3ca85bb4c6">
<img width="729" alt="Screen Shot 2019-12-09 at 4 32 56 PM" src="https://media.github.ibm.com/user/207956/files/b65fa600-1aa1-11ea-8915-710cf8a2f6e3">
<img width="728" alt="Screen Shot 2019-12-09 at 4 33 01 PM" src="https://media.github.ibm.com/user/207956/files/b8296980-1aa1-11ea-875a-fd59aab1f1ab">
<img width="723" alt="Screen Shot 2019-12-09 at 4 33 08 PM" src="https://media.github.ibm.com/user/207956/files/bb245a00-1aa1-11ea-807a-3ea4320211cd">
<img width="843" alt="Screen Shot 2019-12-09 at 4 33 18 PM" src="https://media.github.ibm.com/user/207956/files/bd86b400-1aa1-11ea-9e30-0dfa20001cad">
<img width="842" alt="Screen Shot 2019-12-09 at 4 33 26 PM" src="https://media.github.ibm.com/user/207956/files/bf507780-1aa1-11ea-81e1-4fa18344efd1">
<img width="845" alt="Screen Shot 2019-12-09 at 4 33 34 PM" src="https://media.github.ibm.com/user/207956/files/c1b2d180-1aa1-11ea-8e20-ed4042c4dc10">

**Comment by mii-w** [comment]
Design changes/feedback from the meeting:
- removing default/custom toggle
     - erasing field would automatically turn field back to default, empty field = default values
- checkboxes are kind of odd
- need ID team on wording for header "Getting Started" (ex. Profile Configuration, Create New Test, etc.)
- passing wireframes to Carrie for Hi-fis
- there will be preset Test Profiles with values/fields already filled in so the user has options to choose from

**Comment by kimholmes** [comment]
**Thanks @mii-w Other thoughts/notes:**
- Michelle will remove the link to add to Description - Description will be surfaced in the form as optional.

- For the left list of tests, do we want to include a "collapse all" and "expand all?"

- Toby has pointed out that the profiles form and the dropdown will be pre-populated with existing endpoints and the user might not even be aware of them. How will we convey that to the user? Work with ID?

- Guy and Toby discussed link to Hello World

**Comment by thisguy-1** [comment]
@mii-w and @kimholmes can we close this yet? Is there another issue for this?

**Comment by kimholmes** [comment]
@tobespc and @markcor11 are still working with us on this. Toby, Mark, are you still using this issue? I am tracking design work in our design repo but can add it over here as well. Please let me know if this is the appropriate issue.

**Comment by kimholmes** [comment]
Latest and greatest:
![PM_Dashboard4_3](https://user-images.githubusercontent.com/21316329/78381497-73bb5f80-75a3-11ea-90a5-d0acea6b2356.png)

**Comment by kimholmes** [comment]
Latest and greatest:
![PM_Dashboard4_3](https://user-images.githubusercontent.com/21316329/78383071-cc8bf780-75a5-11ea-93dd-a921a70dd7aa.png)

**Comment by tobespc** [comment]
we don't need to track it here as well, we can follow in the design issue
