### ISSUE TITLE
VScode error with remote connection created by Eclipse plugin

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind#1641]
I created a remote connection using Eclipse, then shut down Eclipse and started VSCode.  VSCode displayed the following error notification
![image](https://user-images.githubusercontent.com/29612372/71910018-1f891680-313f-11ea-8930-48c6db8ed347.png)
and the connection was not displayed in the codewind view.

**Comment by jopit** [comment]
When in this state, I can't use VSCode to create another connection to the same remote kube, nor can I use VSCode to delete the existing connection.  I have to use Eclipse to delete the connection, or edit the connection.json file manually.

**Comment by tetchel** [comment]
I did not consider that scenario. I will fix it
