### ISSUE TITLE
Edit message from "whilst" to "while"

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind#1643]
Change this message from cwctl so that "whilst" becomes "while:"
<img width="501" alt="Screen Shot 2020-01-07 at 10 24 04 AM" src="https://user-images.githubusercontent.com/21180723/71910280-9cb48b80-313f-11ea-9979-006f49c6e335.png">

Here is the Acrolinx feedback for "whilst," which is considered archaic:
<img width="275" alt="Screen Shot 2020-01-07 at 10 53 06 AM" src="https://user-images.githubusercontent.com/21180723/71910532-0e8cd500-3140-11ea-81bf-d27e0e31fef3.png">

**Comment by sishida** [comment]
@tobespc Could we please assign someone on the Portal team to this issue? Thanks!

**Comment by hhellyer** [comment]
The text was coming from the installer, I've raised a PR to fix it.

(I must use `whilst` more in conversation.)

**Comment by hhellyer** [comment]
@sishida - This should be done. Can you verify and close?

**Comment by jopit** [comment]
TimE just verified the change
