### ISSUE TITLE
SVT: An Internal Error occurred during "Installing Codewind"

### ISSUE THREAD

**Issue by naveenkaratekid** [eclipse/codewind#1647]
**Codewind version:0.7.0**
**OS:MacOS 10.14 Mojave**

**IDE extension version:0.7.0**
**IDE version: Eclipse 2019-06 (4.12.0)**

**Description:**
The Codewind plugin is able to install in the Eclipse IDE, but Eclipse will not start up Codewind. It tries to download the images but after the progress bar on the bottom right hits 99%, it throws an error saying ```Internal Error Occurred```

When I run ```docker images``` and ```docker ps -a```, the images show up in the output:

```
naveens-mbp:~ naveenk@ibm.com$ docker images
REPOSITORY                           TAG                    IMAGE ID            CREATED             SIZE
liberty-app-cache                    latest                 8520630d3317        16 seconds ago      874MB
spring-app-cache                     latest                 306d57542c4e        43 seconds ago      414MB
ibmjava                              8-sfj                  8cb423df11a5        2 weeks ago         167MB
eclipse/codewind-performance-amd64   0.7.0                  da2fc38a4124        2 weeks ago         111MB
codewind-performance-amd64           0.7.0                  da2fc38a4124        2 weeks ago         111MB
eclipse/codewind-pfe-amd64           0.7.0                  8ea8208e6713        2 weeks ago         759MB
codewind-pfe-amd64                   0.7.0                  8ea8208e6713        2 weeks ago         759MB
k8s.gcr.io/kube-apiserver            v1.14.8                1e94481e8f30        2 months ago        209MB
k8s.gcr.io/kube-controller-manager   v1.14.8                36a8001a79fd        2 months ago        158MB
k8s.gcr.io/kube-proxy                v1.14.8                849af609e0c6        2 months ago        82.1MB
k8s.gcr.io/kube-scheduler            v1.14.8                f1e3e5f9f93e        2 months ago        81.6MB
websphere-liberty                    19.0.0.3-webProfile7   c6892fcebf3c        4 months ago        460MB
docker/kube-compose-controller       v0.4.23                a8c3d87a58e7        7 months ago        35.3MB
docker/kube-compose-api-server       v0.4.23                f3591b2cb223        7 months ago        49.9MB
k8s.gcr.io/coredns                   1.3.1                  eb516548c180        11 months ago       40.3MB
k8s.gcr.io/etcd                      3.3.10                 2c4adeb21b4f        13 months ago       258MB
k8s.gcr.io/pause                     3.1                    da86e6ba6ca1        2 years ago         742kB
```

```
naveens-mbp:~ naveenk@ibm.com$ docker ps -a
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS              PORTS                       NAMES
b0c48af67d03        codewind-pfe-amd64:0.7.0           "sh -c ' /file-watch…"   3 minutes ago       Up 3 minutes        127.0.0.1:10000->9090/tcp   codewind-pfe
ca1808c9e0f6        codewind-performance-amd64:0.7.0   "docker-entrypoint.s…"   3 minutes ago       Up 3 minutes        127.0.0.1:9095->9095/tcp    codewind-performance
```

Screenshot of error

![image](https://user-images.githubusercontent.com/19738071/71930936-a56e8700-316a-11ea-96f7-7c7cfcf4055f.png)

There are no log files available since this is coming from the IDE itself.

**Steps to reproduce:**
1. In Eclipse IDE, uninstall Codewind
2. Do a docker system prune -a to remove the dangling images
3. Open Eclipse, and re install the Codewind plugin.
4. After you show the Codewind Explorer, double click the ```Local [Installation Incomplete]``` to install Codewind. Wait for it to hit 99%, and then the error pops up.

@jagraj

**Comment by malincoln** [comment]
@tobespc says this is fixed and he'll confirm.

**Comment by jagraj** [comment]
@naveenkaratekid 
Can you please provide IDE and PFE logs for this issue.?

**Comment by jagraj** [comment]
@naveenkaratekid 
Could you please try to reproduce this problem with the latest as well and capture all the logs and post to this issue.

**Comment by naveenkaratekid** [comment]
@jagraj. I was able to reproduce the issue with the latest.

![image](https://user-images.githubusercontent.com/19738071/71985746-27a58c80-31f9-11ea-87b7-a9f7e2cec808.png)

```
naveens-mbp:~ naveenk@ibm.com$ docker ps -a
CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS              PORTS                       NAMES
47f83a48f1c2        eclipse/codewind-pfe-amd64:latest           "sh -c ' /file-watch…"   22 minutes ago      Up 22 minutes       127.0.0.1:10000->9090/tcp   codewind-pfe
3e639f2ac994        eclipse/codewind-performance-amd64:latest   "docker-entrypoint.s…"   22 minutes ago      Up 22 minutes       127.0.0.1:9095->9095/tcp    codewind-performance
```

```
naveens-mbp:~ naveenk@ibm.com$ docker images
REPOSITORY                           TAG                    IMAGE ID            CREATED             SIZE
liberty-app-cache                    latest                 0c4353fe3106        19 minutes ago      874MB
spring-app-cache                     latest                 5e74c51b6f78        20 minutes ago      414MB
eclipse/codewind-performance-amd64   latest                 da6c0a5ca5e2        About an hour ago   100MB
eclipse/codewind-pfe-amd64           latest                 5d3a79840aa7        About an hour ago   766MB
ibmjava                              8-sfj                  8cb423df11a5        2 weeks ago         167MB
k8s.gcr.io/kube-apiserver            v1.14.8                1e94481e8f30        2 months ago        209MB
k8s.gcr.io/kube-controller-manager   v1.14.8                36a8001a79fd        2 months ago        158MB
k8s.gcr.io/kube-scheduler            v1.14.8                f1e3e5f9f93e        2 months ago        81.6MB
k8s.gcr.io/kube-proxy                v1.14.8                849af609e0c6        2 months ago        82.1MB
websphere-liberty                    19.0.0.3-webProfile7   c6892fcebf3c        4 months ago        460MB
docker/kube-compose-controller       v0.4.23                a8c3d87a58e7        7 months ago        35.3MB
docker/kube-compose-api-server       v0.4.23                f3591b2cb223        7 months ago        49.9MB
k8s.gcr.io/coredns                   1.3.1                  eb516548c180        12 months ago       40.3MB
k8s.gcr.io/etcd                      3.3.10                 2c4adeb21b4f        13 months ago       258MB
k8s.gcr.io/pause                     3.1                    da86e6ba6ca1        2 years ago         742kB
```

**Comment by james-wallis** [comment]
Haven't been able to reproduce on latest.

Steps taken to reproduce:
* Using the development steps for the `codewind-eclipse` project - https://github.com/eclipse/codewind-eclipse/#developing-codewind-for-eclipse.
* Updated `codewind-eclipse` to latest master.
* `docker system prune -a`
* Started plugin via the Eclipse `debug configurations`.
* Double click the `Local [installation incomplete] ...`
* Codewind starts fine, doesn't error after 99%

**Comment by tetchel** [comment]
I'm not sure where that websocket library comes from, but if it's bundled with eclipse, the bug will likely depend on your eclipse version.

It looks like we require 4.13 [doc](https://www.eclipse.org/codewind/mdteclipsegettingstarted.html) but @naveenkaratekid is on 4.12. Naveen, can you reproduce on a supported Eclipse version?

**Comment by naveenkaratekid** [comment]
I also tried the same steps on Windows, and I couldn't reproduce this issue.

I tried the following steps as Jag suggested, and I am still getting the same error message:

1. In the Mac terminal, go to the folder of Eclipse: ```/Applications/Eclipse.app/Contents/MacOS```

2. Run ```./eclipse -clean```

3. Uninstall Codewind from Eclipse

4. run docker ps -a, and remove the processes using docker rm -f.

5. Run docker system prune -a

6. Quit eclipse, and re open it using terminal and run ```./eclipse -clean```.

7. Re-install codewind

Here is the screenshot I get
![image](https://user-images.githubusercontent.com/19738071/71990553-95ee4d00-3201-11ea-86b5-581dd9c0e560.png)

**Comment by jopit** [comment]
I see this in the eclipse log:
```
!ENTRY org.eclipse.core.jobs 4 2 2020-01-08 10:32:53.754
!MESSAGE An internal error occurred during: "Restoring connections".
!STACK 0
java.util.ServiceConfigurationError: org.eclipse.jetty.websocket.api.extensions.Extension: Provider org.eclipse.jetty.websocket.common.extensions.identity.IdentityExtension not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.eclipse.jetty.websocket.api.extensions.ExtensionFactory.<init>(ExtensionFactory.java:41)
	at org.eclipse.jetty.websocket.common.extensions.WebSocketExtensionFactory.<init>(WebSocketExtensionFactory.java:53)
	at org.eclipse.jetty.websocket.client.WebSocketClient.<init>(WebSocketClient.java:251)
	at org.eclipse.jetty.websocket.client.WebSocketClient.<init>(WebSocketClient.java:166)
	at org.eclipse.jetty.websocket.client.WebSocketClient.<init>(WebSocketClient.java:206)
	at org.eclipse.jetty.websocket.client.WebSocketClient.<init>(WebSocketClient.java:192)
	at org.eclipse.jetty.websocket.client.WebSocketClient.<init>(WebSocketClient.java:124)
	at org.eclipse.codewind.filewatchers.core.internal.WebSocketManagerThread.<init>(WebSocketManagerThread.java:149)
	at org.eclipse.codewind.filewatchers.core.Filewatcher.<init>(Filewatcher.java:127)
	at org.eclipse.codewind.filewatchers.eclipse.CodewindFilewatcherdConnection.<init>(CodewindFilewatcherdConnection.java:92)
	at org.eclipse.codewind.core.internal.connection.CodewindConnection.connect(CodewindConnection.java:128)
	at org.eclipse.codewind.core.internal.CodewindManager.refreshInstallStatus(CodewindManager.java:75)
	at org.eclipse.codewind.core.internal.connection.CodewindConnectionManager$1.run(CodewindConnectionManager.java:177)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
We bundle the Jetty websocket jars inside the filewatcher plugin.

@jgwest can you please take a look?

**Comment by naveenkaratekid** [comment]
@tetchel According to the Codewind Docs:

```However, the earliest supported version of the Eclipse IDE is Version 2019-03 (4.11).```

I have 2019-06 (4.12), and it does not work on my MacOS, but works fine on Windows. I moved to the 2019-12 version of Eclipse, and now Codewind works just fine.

**Comment by malincoln** [comment]
@naveenkaratekid can you update title to append "SVT" so we're aware it's an SVT scenario?  Thanks

**Comment by jopit** [comment]
@jgwest can you confirm that the jetty websocket code used by the filewatcher plugins requires Eclipse 2019-12 and we should pre-req that version?

**Comment by eharris369** [comment]
I didn't see any issues with jetty in the eclipse .log file using 1906 on MAC.  If I try to do the install from the command line on Windows or MAC I get:

```
C:\Users\ERINHarris\.codewind\0.8.0>cwctl install --tag 0.8.0
time="2020-01-09T09:32:50-05:00" level=error msg="Error response from daemon: manifest unknown: manifest unknown"
time="2020-01-09T09:32:51-05:00" level=error msg="Error response from daemon: manifest unknown: manifest unknown"
Image Install Successful
```

The if tag is `latest` then it works.  Same if I set the CW_TAG environment variable to `latest` before starting Eclipse then the install works.

**Comment by eharris369** [comment]
I missed that this is for 0.7.0.  I tried with 0.7.0 and did not have any problems.  After Joseph's announcement about 0.8.0 being ready for SVT I tried it as well and no issues.  Both using Eclipse 1906.

**Comment by jgwest** [comment]
I just tried Eclipse 19.03 with Codewind 0.7.0, and also Eclipse 19.03 with Codewind 0.8.0 (latest), and both worked fine for me, so I am unable to reproduce. And as Erin mentioned above, she was likewise able to install fine in 19.06. 

Likewise, since the Jetty jars are packaged directly into the Codewind Filewatcher Core plugin ([using `Bundle-Classpath`](https://github.com/eclipse/codewind-eclipse/blob/master/dev/org.eclipse.codewind.filewatchers.core/META-INF/MANIFEST.MF)) eg they are not consumed from as Eclipse workbench OSGi bundles, I would not expect any issues with the Eclipse IDE having different versions of these packages.

**Comment by elsony** [comment]
Removing the stopship flag based on the discussion with SVT.  Given that this problem only happens on a specific version 2019-06 of Eclipse on a particular machine, we do not consider this is a general problem based on the current understanding on the problem.

**Comment by eharris369** [comment]
I believe that this message `java.util.ServiceConfigurationError: org.eclipse.jetty.websocket.api.extensions.Extension: Provider org.eclipse.jetty.websocket.common.extensions.identity.IdentityExtension not a subtype` means that there is more than one version of jetty loaded and the classes are getting mismatched.

**Comment by jgwest** [comment]
@eharris369 True, good point... 🤔 . ServiceLoader, used by the Jetty WebSocket code, is a wildcard which can easily make a mess out of OSGi classloading and resolution. There is some OSGi support for working around ServiceLoader, but it looks like more trouble than it's worth.

I'm now looking at dumping Jetty and switching to the OkHttp's WebSocket support (this will be the THIRD WebSocket client library I have had to use, after Tyrus and Jetty 😛 ).

**Comment by naveenkaratekid** [comment]
With help from @eharris369, here are the steps I took to resolve this issue:

1. Uninstall Eclipse 1906.
2. Reinstall it.
3. Install Codewind 0.7.0 from Eclipse Marketplace.

Now Codewind starts up in Eclipse successfully.

**Comment by jgwest** [comment]
Fix has been delivered for the behaviour described in this bug, which prevents this issue on Eclipse configurations that are more prone to seeing it.
