### ISSUE TITLE
Eclipse plugin contains unusable OS package

### ISSUE THREAD

**Issue by NikCanvin** [eclipse/codewind#1652]
To @eharris369 
while improving Java OS dependency automation for 0.8.0, I discovered:
1. org.json_1.0.0.v201011060100.jar is used by the Eclipse plug-in
2. Eclipse IP reject requests to use this package, see (it includes work-around suggestions): https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20330
..
ideally this should be fixed in 0.8.0, should that not be realistic then we should get approval from Codewind leadership (Rob or Tim) to allow it to defer.

**Comment by jgwest** [comment]
@NikCanvin The version of this package we use in Codewind Eclipse is bundled as part of Orbit and therefore approved for use by Eclipse: https://download.eclipse.org/tools/orbit/downloads/drops/R20190827152740/

**Comment by jopit** [comment]
As Jonathan said, we are using the version of this jar that comes from the Eclipse Orbit site and is approved for use in Eclipse projects, see https://dev.eclipse.org/ipzilla/show_bug.cgi?id=3603

**Comment by NikCanvin** [comment]
after further investigation, I raised: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21382
..
I expect our code need not change (so this issue should remain closed), but I raised a usage CQ to check the 'later' version of the package we now use is still OK for us to use

**Comment by jopit** [comment]
@NikCanvin we already have approval for a piggyback CQ for this: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=19943
