### ISSUE TITLE
Enhance the help by implementing tabs

### ISSUE THREAD

**Issue by micgibso** [eclipse/codewind#1653]
Implement tabs in our docs pages similar to what Docker do on their website, for example, see https://docs.docker.com/compose/install/.  Under **Install Compose** the help splits into tabs for the different operating systems, which would be very useful for our various installs and so on. 

Docs here: https://www.eclipse.org/codewind/gettingstarted.html

**Comment by travis1111** [comment]
Thanks.  Please assign it to me :-)

**Comment by sghung** [comment]
Closing since Travis gave Michael the instructions

**Comment by micgibso** [comment]
Those instructions are great, but it would be really useful to have a particular implementation of tabs for install in cloud. For example, in the remote-overview.html topic, it would be nice to have tabs under Prerequisites so the user can select which cloud they're installing into, so for example, OpenShift, IBM Public Cloud etc. 

Is this possible?

**Comment by sghung** [comment]
@travis1111 can you comment on the feasibility?

**Comment by travis1111** [comment]
I am suggesting to do it via HTML, easier than creating something via jekyll.

**Comment by sghung** [comment]
@micgibso can you see if Travis' response is okay and then close it? Thank you

**Comment by micgibso** [comment]
@travis1111 HTML is fine, do we need different HTML to that which you've given me though? We don't need to autodetect the operating system, rather we just want a number of tabs which the user can click depending on their choices. 
@sghung Not ready to close this just yet, thanks.

**Comment by travis1111** [comment]
@micgibso just sent you the sample html

**Comment by micgibso** [comment]
@travis1111 Received the sample, just ran it up locally to check how it looks and it's just what we're after, thank you!
