### ISSUE TITLE
New and noteworthy for 0.8.0

### ISSUE THREAD

**Issue by beccabau** [eclipse/codewind#1659]
Need to add a news page to the Codewind.dev website for 0.8.0.

**Comment by beccabau** [comment]
@sishida @micgibso can someone add area/docs label, please? Thanks

**Comment by sishida** [comment]
Hi, Becca, I have added the label and assigned the issue to you. :)

**Comment by micgibso** [comment]
This isn't a bug, this is normal wip, so removing the kind/bug label  :)
