### ISSUE TITLE
Project Build Failed - Unable to push image to deploy registry

### ISSUE THREAD

**Issue by naveenkaratekid** [eclipse/codewind#166]
Codewind version 0.3.0:
MacOS Mojave 10.14.6:

Che-Theia@4ef1d89 using Theia@4ef1d89
Kubernetes cluster: 1.14.3

**Issue:**

I am unable to build my Codewind project in Eclipse Che. I keep getting an error saying that it is unable to push an image to the Docker registry. I have configured the Docker registry correctly with my username and password. To verify that my registry is valid, I logged into Docker's registry with my credentials, and it worked just fine.

**Steps to reproduce issue:**
1. Create a new project in Eclipse Che using the Codewind templates.

2. Once the project is created, click the "i" icon on the right side of the screen to open the project overview. Click the "Build" button. 

3. The following error message comes on my end: **Build Failed - Codewind was unable to push an image to the Deployment Registry. Please make sure it is a valid Deployment Registry with the appropriate permissions**.

I have attached a screenshot of the error message

I have also included a link to the log files from eclipse che: **https://github.com/naveenkaratekid/che-codewind-logs**

<img width="1017" alt="Screen Shot 2019-08-10 at 12 00 22 PM" src="https://user-images.githubusercontent.com/19738071/62824258-42e86f00-bb69-11e9-8282-e132926f28a3.png">

**Comment by ssh24** [comment]
Hi @naveenkaratekid, did you add the docker registry login credentials under `Administration` in che? The address will be https://index.docker.io/v1/ and your docker login/password.

**Comment by naveenkaratekid** [comment]
Thank you for your response. Yes, I did add my docker credentials under the Administration menu in Eclipse Che. I verified that the credentials were correct because I logged into docker hub with those same credentials and it logged me in successfully.

Naveen K
510-304-8025

________________________________

**Comment by johnmcollier** [comment]
Spoke with @naveenkaratekid on slack. We suspect the failure was due to the deployment registry name that was entered in.

`index.docker.io/v1/<username>` should be `docker.io/<username>` instead.

**Comment by rajivnathan** [comment]
@naveenkaratekid can this be closed?

**Comment by naveenkaratekid** [comment]
Yes. It can be closed.
