### ISSUE TITLE
Pick up appsody 0.5.4 release

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#1666]
**Codewind version:** 0.8.0
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description of the enhancement:**

New release: https://github.com/appsody/appsody/releases/tag/0.5.4

**Proposed solution:**

**Comment by jgwest** [comment]
@makandre: Unexpected command format: area appsody vscode-ide eclipse-ide<details>


In response to [this](https://github.com/eclipse/codewind/issues/1666#issuecomment-572196717):
> area appsody vscode-ide eclipse-ide
</details>

**Comment by makandre** [comment]
Done
