### ISSUE TITLE
Codewind Uninstall story

### ISSUE THREAD

**Issue by stalleyj** [eclipse/codewind#1672]
Currently, when we uninstall the VSCode plugin all Codewind artifacts are left untouched. Projects and codewind containers are left running, information stored in the docker volume remains and anything placed in .codewind is left behind. I haven't looked at eclipse or che but presume the behaviour is the same.

What should the behaviour be ?  Local / Remote / Che ?

**Comment by jopit** [comment]
VSCode don't provide an uninstall hook, so we can't run any code at uninstall time.  Eclipse does provide such a hook.

Implement a `cwctl uninstall` command.

**Comment by jgwest** [comment]
As a partial workaround, we could implement a keep-alive from the IDE to Codewind server:
- Every X minutes/hours, the IDE sends a message to the Codewind server indicating that the user has an active IDE running, with an active Codewind entry defined.
- If the Codewind server does not receive such a keep-alive entry within X minutes/hours, it is assumed the workbench is closed, and Codewind and it's app containers are shut down by PFE.

This handles shutting down containers, but doesn't handle image removal, volumes, or `.codewind` dir.

**Comment by stalleyj** [comment]
- Enhance the behaviour of cwctl remove remote. This will call unbind for each project to ensure that projects are shut down and not left orphaned (related to a connection that no longer exists). Need to consider what behaviour we expect when not connected to the remote.

- Implement an uninstall command that uses the connection list to call remove on each connection.  Keycloak will not be removed. 

- After removing all connections, the .codewind/config/connections.json will be removed

- What won't be removed as these are owned by the IDE - .codewind/version/appsody/cwctl

**Comment by malincoln** [comment]
@tobespc is this being targeted for 0.10.0.  I'm removing the 0.9.0 release tag as that released is completed.

**Comment by stalleyj** [comment]
The most important thing we need to do for this feature is https://github.com/eclipse/codewind/issues/568

This will ensure that kubernetes garbage collection will take care of project resources when the operator is used to remove Codewind.

**Comment by tobespc** [comment]
with 568 raised and in progress, can this now be resolved ?

**Comment by tobespc** [comment]
closing as issues are covered
