### ISSUE TITLE
SVT: [odo] Codewind ODO setup instructions failing

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#1675]
**Codewind version:** 0.7.0
**OS:** RHEL

**Che version:** 7.3.1
**IDE extension version:**  0.7.0
**IDE version:**
**Kubernetes cluster:**

OCP 4.2

**Description:**

Codewind ODO instructions are failing to apply cluster roles for the user. Here is more information.
We need to clone per release and configure cluster roles and  role bindings. 

https://www.eclipse.org/codewind/mdt-che-odo-support.html#adding-rules-and-importing-java-image-stream

```
git clone https://github.com/eclipse/codewind-odo-extension &&\
> cd ./codewind-odo-extension/setup &&\
> kubectl apply -f codewind-odoclusterrole.yaml &&\
> kubectl apply -f codewind-odoclusterrolebinding.yaml &&\
> ./odo-addbuilder.sh &&\
> cd - &&\
> rm -rf codewind-odo-extension
Cloning into 'codewind-odo-extension'...
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 219 (delta 7), reused 9 (delta 3), pack-reused 199
Receiving objects: 100% (219/219), 67.35 KiB | 0 bytes/s, done.
Resolving deltas: 100% (116/116), done.
clusterrole.rbac.authorization.k8s.io/codewind-odoclusterrole unchanged
error: the path "codewind-odoclusterrolebinding.yaml" does not exist
```

**Steps to reproduce:**

**Workaround:**

**Comment by johnmcollier** [comment]
Looks like the script from the repo has already been updated, so just the docs need to be updated with the 0.8.0 branch and be refreshed upon release.

PR: https://github.com/eclipse/codewind-docs/pull/281

**Comment by johnmcollier** [comment]
@jagraj I've updated the docs for this issue, can you try the instructions from https://github.com/eclipse/codewind-docs/blob/0.8.0/docs/_documentations/mdt-che-odo-support.md and verify? Thanks!

**Comment by jagraj** [comment]
I tried this on my RedHat machine and the scripts failed. Please move this to "In progress". I notified @jingfuwang on this issue.

**Comment by jagraj** [comment]
```
git clone https://github.com/eclipse/codewind-odo-extension &&\
cd ./codewind-odo-extension/setup &&\
./setup.sh
cd - &&\
rm -rf codewind-odo-extension
4:09 PM
git clone https://github.com/eclipse/codewind-odo-extension &&\
> cd ./codewind-odo-extension/setup &&\
> ./setup.sh
Cloning into 'codewind-odo-extension'...
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 223 (delta 9), reused 7 (delta 2), pack-reused 199
Receiving objects: 100% (223/223), 82.29 KiB | 0 bytes/s, done.
Resolving deltas: 100% (118/118), done.
Bind (rolebinding) additional cluster roles to Codewind service account: che-workspace
sed: can't read s/<serviceaccount>/che-workspace/g: No such file or directory
clusterrole.rbac.authorization.k8s.io/codewind-odoclusterrole created
The RoleBinding "codewind-odorolebinding" is invalid: subjects[0].name: Invalid value: "<serviceaccount>": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
imagestream.image.openshift.io/codewind-odo-openjdk18 imported
```

**Comment by GeekArthur** [comment]
Moved to "In progress", I opened an new issue https://github.com/eclipse/codewind/issues/1787 yesterday for making odo setup script fully support all platforms

**Comment by johnmcollier** [comment]
@GeekArthur Did you want me to assign this to you?

**Comment by GeekArthur** [comment]
@johnmcollier Thanks for reminding, I just assigned this to me

**Comment by GeekArthur** [comment]
@johnmcollier Can you help review/approve/merge this PR: https://github.com/eclipse/codewind-odo-extension/pull/50?

**Comment by GeekArthur** [comment]
@jagraj All PRs are merged, you can verify the setup script on your machine for both 0.8.0 and master.

**Comment by jagraj** [comment]
Thanks for the fix. This issue has been verified, closing the issue now.
