### ISSUE TITLE
Restructure the TOC

### ISSUE THREAD

**Issue by micgibso** [eclipse/codewind#1679]
Restructure the TOC, with particular focus on the Getting started experience.  Use Toby and Mark's fork, to be merged into https://github.com/eclipse/codewind-docs master tomorrow, as baseline and work with them to refine. 
Author all topics refining the content, checking the links, and confirming the user journey.

**Comment by j-c-berger** [comment]
feel free to add me, @micgibso

**Comment by MelHopper** [comment]
commenting so I can be added.

**Comment by micgibso** [comment]
Toc now merged to master

**Comment by micgibso** [comment]
Closing now each section has its own issue.
