### ISSUE TITLE
Unable to install Codewind on visual studio

### ISSUE THREAD

**Issue by oiricaud** [eclipse/codewind#1682]
**Codewind version:** v0.7.0
**OS:** Mac OS 
**Docker:** 19.03.5 

**Che version:** n/a
**IDE extension version:** 0.7.0
**IDE version:**1.41.1
**Kubernetes cluster:** n/a

**Description:**
Trying to install Codewind onto visual studio but when I click install I get error installing.

`cwctl is available at /Users/Oscar.Ricaud@ibm.com/.codewind/0.7.0/cwctl
==> Run cwctl --json --insecure connections list
{"schemaversion":1,"connections":[{"id":"local","label":"Codewind local connection","url":"","auth":"","realm":"","clientid":"","username":""}]}
==> End cwctl --json --insecure connections list
==> Run cwctl --json --insecure status
{"status":"uninstalled"}
==> End cwctl --json --insecure status
==> Run cwctl --json --insecure status
{"status":"uninstalled"}
==> End cwctl --json --insecure status
==> Run cwctl --json --insecure status
{"status":"uninstalled"}
==> End cwctl --json --insecure status
==> Run cwctl --json install -t 0.7.0
<Output hidden>
2020/01/09 10:14:35 IMAGE_TAGGING_ERROR[102]: exec: "docker": executable file not found in $PATH. Image Tagging Failed
==> End cwctl --json install -t 0.7.0
==> Run cwctl --json --insecure status
{"status":"uninstalled"}
==> End cwctl --json --insecure status
==> Run cwctl --json --insecure status
==> Run cwctl --json --insecure status
{"status":"uninstalled"}
==> End cwctl --json --insecure status
{"status":"uninstalled"}
==> End cwctl --json --insecure status
==> Run cwctl --json --insecure status
{"status":"uninstalled"}
==> End cwctl --json --insecure status
==> Run cwctl --json install -t 0.7.0
<Output hidden>
2020/01/09 10:16:23 IMAGE_TAGGING_ERROR[102]: exec: "docker": executable file not found in $PATH. Image Tagging Failed
==> End cwctl --json install -t 0.7.0
==> Run cwctl --json --insecure status
2020/01/09 10:18:22 CONTAINER_LIST_ERROR[107]: Error response from daemon: dial unix docker.raw.sock: connect: connection refused. 
==> End cwctl --json --insecure status
==> Run cwctl --json --insecure status
{"status":"uninstalled"}
==> End cwctl --json --insecure status
==> Run cwctl --json --insecure status
{"status":"uninstalled"}
==> End cwctl --json --insecure status
==> Run cwctl --json install -t 0.7.0
<Output hidden>
2020/01/09 10:19:20 IMAGE_TAGGING_ERROR[102]: exec: "docker": executable file not found in $PATH. Image Tagging Failed
==> End cwctl --json install -t 0.7.0
==> Run cwctl --json --insecure status
{"status":"uninstalled"}
==> End cwctl --json --insecure status
==> Run cwctl --json --insecure status
{"status":"uninstalled"}
==> End cwctl --json --insecure status
`
**Steps to reproduce:**
1) Find Codewind for VS Code in the VS Code Marketplace or by searching for Codewind in the VS Code Extensions view.

2) Open the Codewind view in the Explorer view group or enter Focus on Codewind View into the Command Palette. If you do not see Codewind in either the Explorer view or the Command Palette, the extension did not install correctly.

3) Choose Install when prompted to complete the installation of additional Docker images that Codewind requires to run. The installation may take a few minutes to complete.

**Workaround:** 
n/a at the moment.

**Comment by rtaniwa** [comment]
Hi Oscar,

Do you have Docker installed locally on your Mac? Docker is a prereq, and it appears as though we aren't locating it on your machine.

**Comment by oiricaud** [comment]
@rtaniwa yep I got docker installed.

**Comment by rtaniwa** [comment]
@tobespc @tetchel either of you seen anything similar? Looks like cwctl is failing to find docker.

**Comment by oiricaud** [comment]
I have docker installed... i have reset my docker. Uninstalling and reinstalling visual code to see if it makes a difference.

**Comment by tetchel** [comment]
it could be that VS Code is using a different PATH than the shell you ran `docker -v` from. can you try launching VS Code from that shell? 

1. Add VS Code it to your PATH https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line
2. Reload your shell and run `code`

**Comment by oiricaud** [comment]
I reinstalled visual studio and made no difference. 

I added VS Code it to my PATH https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line and it made no difference. I am still having this issue.
 
<img width="1680" alt="Screen Shot 2020-01-09 at 10 57 08 AM" src="https://user-images.githubusercontent.com/11867058/72087865-ca7c0a80-32ce-11ea-84af-f89a9d1bf258.png">

**Comment by tetchel** [comment]
to clarify the steps above, you have to close all instances of VS Code and then run `code` from outside of VS Code (ie in a regular terminal).

Could you also post the output of:
`echo $PATH`

from both your normal terminal and from your VS Code terminal.

**Comment by oiricaud** [comment]
Thanks @tetchel I redid the steps on your previous comment and it works. 

`Add VS Code it to your PATH https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line
Reload your shell and run code
try and run the Codewind install action again`

**Comment by tetchel** [comment]
Nice, I'm not sure why VS Code may be using a different PATH, but you may have to always launch VS Code from the terminal to work around it.

**Comment by tetchel** [comment]
can you close the issue if you're satisfied?
