### ISSUE TITLE
Create a guide for using Codewind with Local Kubernetes (Minikube, CodeReady containers)

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#1691]
Codewind can run on local Kubernetes, and we have [some instructions in our docs](https://www.eclipse.org/codewind/remoteconfiguring.html#configuring-kubernetes-for-docker-desktop), telling users how to deploy Codewind on a local Kube, but we don't have any end-end instructions or guides showing users what to do, and it can be confusing at times.

Given that local Kubernetes (such as Minikube, Docker Desktop Kube, CodeReadyContainers) is fast and easy to try out, they may be the first point where users try out Codewind on Kube, and so we should have an end-end guide showing users how to deploy Codewind and deploy a project on local Kube. **I've found on a number of other open source projects that a number of users will disregard a project if it's not easily usable (or installable) on local Kube.**

Che had a [similar guide for local Kube](https://che.eclipse.org/running-eclipse-che-on-kubernetes-using-docker-desktop-for-mac-5d972ed511e1), that a number of us found useful when we were first looking at Che. 

Rough outline (maybe have two separate guides, one for Minikube, one for CRC?):
- Starting the local Kube 
- How to install and setup prerequisites
    - In this case, likely just ingress
- How to get the ingress IP needed for Codewind
- Installing Codewind
    - Guide could focus on either Che, Hybrid or both.
- Deploying a sample project and making changes
    - Maybe use Appsody-on-Kube for the sample project?

**Comment by j-c-berger** [comment]
@sishida and/or @micgibso maybe assign to me. We can discuss at our next iteration since a guide is a big endeavor.

**Comment by sishida** [comment]
@j-c-berger I have assigned this issue to you. I think it'd be good to bring this issue up in the iteration planning meeting.

From reading the initial comment, I'm thinking that this local Kubernetes content might fit the new "tutorial" format that the team talked about instead of something like an Open Liberty guide, assuming that most of the existing Codewind content is going to be in the tutorial format.

**Comment by johnmcollier** [comment]
@sishida I'm flexible with the completion date, maybe in time for 0.9.0 to give us time to prepare it? No other guides/tutorials that I'm aware of at the moment.

I can work with @j-c-berger to get the technical details sorted out.

**Comment by j-c-berger** [comment]
@sishida, thank you for assigning me. Yes, we'll discuss it at our iteration meeting, and from there, we can better determine an end date for it. We can also talk more about format, whether it will adhere to guide standards or the "tutorial" format we've been discussing. 

@johnmcollier, thank you for being willing to work with me on the technical details. I recently put together a proposal, including steps to take to start and complete a guide. I'll share that Box Note with you so you can understand my approach to guides. From there, we can discuss if my understanding and approach towards guides matches your vision for this `Codewind with Local Kubernetes` guide.  I am happy to talk over Webex about this guide. If that appeals to you, I can schedule a meeting for us next week. Thanks and looking forward to working on this!

**Comment by johnmcollier** [comment]
Super early draft (and admittedly boring) doc here. Just the setup right now:

**To Do:**
- Screenshots
- Creating a project, etc?
- More instructions for some of the steps

# Hybrid Codewind on Minikube

## Prerequisites
- A Mac, Windows, or Linux host
- Minikube: See https://kubernetes.io/docs/tasks/tools/install-minikube/ for install instructions
- At least 8Gb RAM (Minikube will need at least 4Gb of RAM for this tutorial)

## Setup

### Preparing Minikube

1) Start Minikube on your machine: `minikube start --memory=4096`
  - This will create a single-node Kubernetes cluster with 4GB of RAM available to it
  - If this command fails, refer to the Minikube installation docs (https://kubernetes.io/docs/tasks/tools/install-minikube) and ensure you have enough memory on your system
2) Codewind makes use of [Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/) to expose its endpoints. Run the `minikube addons enable ingress` command to install ingress on Minikube
3) Run `minikube ip` in your terminal to determine the ingress ip:
   ```
   johns-mbp-3:~ johncollier$ minikube ip
   192.168.64.46
   ```
   Save this value for later.
   
### Installing Codewind

1) Install the Codewind extension into your IDE
  - Follow our install instructions for Eclipse IDE, or VS Code for this step

2) Once the extension is installed, locate the `cwctl` CLI. On Mac and Linux this will be at `~/.codewind/<version>/cwctl`. On Windows it will be located at:
  
3) Run the following command to install cwctl:
   ```
   ./cwctl --insecure install remote \
       --namespace codewind \
       --kadminuser admin \
       --kadminpass admin \
       --krealm codewind \
       --kclient codewind \
       --kdevuser developer \
       --kdevpass developer \
       --ingress <ingress-ip>.nip.io
   ```
   The `ingress-ip` value is the value you found in Step 3 of `Preparing Minikube`.
   
   This command will install codewind into the `codewind` namespace with the default credentials

4) Open the Codewind view in your editor, select "New Codewind Connection" and enter the following details:
   - **Codewind Gatekeeper URL:** Gatekeeper URL given by cwctl in previous step
   - **Username:** Developer username given to cwctl in the previous step (the value of `kdevuser`)
   - **Password:** Developer password given to cwctl in the previous step (the value of `kdevpass`)
   
   Click `Save` to save and create the connection to the Codewind instance on Minikube

**Comment by j-c-berger** [comment]
This issue was opened to make a tutorial on Minikube. Since we've decided to make a quick guide for Minikube, I say we close this issue. 

See issue [#2407](https://github.com/eclipse/codewind/issues/2407) for work on Minikube quick guide and other quick guides. The work can be found in PR [#487](https://github.com/eclipse/codewind-docs/pull/487)

**Comment by sishida** [comment]
I am closing this issue based on the comment from @j-c-berger. Please feel free to reopen the issue if necessary. Thank you!
