### ISSUE TITLE
Setup JIPP slave to build docker images for Codewind

### ISSUE THREAD

**Issue by ericdylanpeters2** [eclipse/codewind#17]
In order to be able to build docker images on a build agent, administration rights to the Codewind JIPP is required.

Requested admin right here:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=549121

**Comment by josephca** [comment]
The title of the Eclipse bug has been updated : **Provision VPS and add it as an external dedicated agent to Codewind JIPP**. Thus, instead of getting admin right, Eclipse VPS will serve as a slave for docker builds.

**Comment by josephca** [comment]
Update on **ETA** from Eclipse: early week of July 15, 2019.

**Comment by josephca** [comment]
Provisioned a VPS for Codewind today.
