### ISSUE TITLE
Kabanero source description missing space

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#1706]
![image](https://user-images.githubusercontent.com/8888438/72172657-b0602c00-33a3-11ea-8e5d-3417304a2598.png)

**Comment by tetchel** [comment]
https://github.com/eclipse/codewind/blob/master/src/pfe/portal/modules/Templates.js#L32

**Comment by stalleyj** [comment]
Fixed https://github.com/eclipse/codewind/pull/1715
