### ISSUE TITLE
Appsody project capabilities should report "debug" mode instead of "debugNoInit"

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#1708]
The Microprofile/Liberty Appsody stack actually does always wait for init, so the capabilities should report `debug` mode but not `debugNoInit`. However, since Codewind doesn't know which stack each project uses, we can't change the capabilities per-stack.

So currently the IDEs are asking for `debugNoInit` but actually receiving `debug`, which causes problems when restarting, debugging projects fail to attach the debugger. It is "safer" for the IDEs to ask for `debug` mode and actually receive `debugNoInit`. 

So can we switch the capabilities for appsody projects to report `debug` mode instead?

**Comment by sghung** [comment]
Waiting on Tim E, once ready PR can be put in
