### ISSUE TITLE
Don't show "enable inject metrics" action if the project already has metrics

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#1710]

**Comment by tetchel** [comment]
@eharris369 I fixed this in the linked commits, not sure if you still need/want to action this for Eclipse

**Comment by eharris369** [comment]
Eclipse IDE PRs:
- 0.9.0: https://github.com/eclipse/codewind-eclipse/pull/583
- master: https://github.com/eclipse/codewind-eclipse/pull/581
