### ISSUE TITLE
Remove "Open" from menu items

### ISSUE THREAD

**Issue by thisguy-1** [eclipse/codewind#1711]
**Codewind version:** Latest

**Description of the enhancement:**

The right click menus are hard to navigate becasue so many of the items start with "Open" ( as seen bellow) Except for Open App and Open Container shell, I do not see why we shouldnt remove the "Open" from the names, since it would be understood that by clicking on the item, it would take you to that feature. 

@sishida @eharris369 @tetchel, what do you think?

<img width="487" alt="Screen Shot 2020-01-10 at 2 55 34 PM" src="https://user-images.githubusercontent.com/52169824/72182522-a6492800-33b9-11ea-9bcc-e817646710cc.png">
<img width="411" alt="Screen Shot 2020-01-10 at 2 38 04 PM" src="https://user-images.githubusercontent.com/52169824/72182528-a9dcaf00-33b9-11ea-898a-75e10b30b52c.png">

**Comment by tetchel** [comment]
I think that's fine

**Comment by sishida** [comment]
I think it's good, too.

We also don't want users to get confused with "open" as in "open source" if they see the word "open" in the menu items. 😅

**Comment by thisguy-1** [comment]
Cool, I know @eharris369 wanted to do this, so let's go ahead and do it for all the IDE's. Please comment when done and post a screenshot of the menu. Thank you!

**Comment by eharris369** [comment]
![image](https://user-images.githubusercontent.com/9484320/72187717-718f9d80-33c6-11ea-956d-945b56a13d51.png)

**Comment by tetchel** [comment]
![image](https://user-images.githubusercontent.com/8888438/72300630-52954380-3632-11ea-8d73-5391a96312c7.png)
