### ISSUE TITLE
Unskip PFE API tests that involve projects on PR builds

### ISSUE THREAD

**Issue by rwalle61** [eclipse/codewind#1716]
**Codewind version:** Latest

The PFE API tests that involve projects are important to test, but they are skipped:
![image](https://user-images.githubusercontent.com/18170169/72253282-1abdda00-35f9-11ea-9527-c14bc95b669e.png)

See a typical PR build in Jenkins https://ci.eclipse.org/codewind/job/Codewind/job/codewind/job/PR-1714/1/console

In order of simplicity, the tests to unskip/add are:
- [x] remote bind
- [x] project list
- [x] sync
- [x] ~~lifecycle~~ (see below)
- [x] ~~etc~~ (see below)

**Comment by tobespc** [comment]
please raise a separate issue for each area left and then we can close this off. Thanks

**Comment by rwalle61** [comment]
Ok I will raise separate issues. Here is some overall info:

Here is the current coverage of PFE API tests, PFE unit tests, and FW unit tests combined (source https://github.com/eclipse/codewind/pull/1882):
![image](https://user-images.githubusercontent.com/18170169/73177786-c7bf4900-4107-11ea-9b88-be6a631af74f.png)

The key part to improve in PFE is coverage of the /projects routes:
![image](https://user-images.githubusercontent.com/18170169/73177852-f3423380-4107-11ea-8006-d3579e92c50e.png)

I think the best way to cover our most important code is to:
- [ ] add a basic lifecycle test
- [ ] test the /metrics routes
- [ ] test fail cases of the other routes
- [ ] test /open and /close
- [ ] flesh out the lifecyle test with key features, e.g. metricsInjection and load testing

I will raise issues for these

**Comment by rwalle61** [comment]
as discussed with @stalleyj, if we can cover code with unit tests instead of api tests (for now), that is preferable because our unit tests run quickly and consistently, whereas our project API tests can fail intermittently when PFE is stressed.

The projects routes that involve FileWatcher cannot be unit tested entirely in PFE unless we mock FileWatcher. However, some of those routes can still be partially unit tested. These look to be:
- [ ] loadtest
- [ ] metrics
- [ ] open
- [ ] close

Project routes that can be tested entirely look to be:
- [ ] watchlist
- [ ] extensions
- [ ] registrySecretList

That is my initial assessment, things will get clearer as we complete those tests

**Comment by rwalle61** [comment]
In summary, the plan of action is to raise our test coverage score by 10%+ by the end of the week. Therefore Tuesday and Wednesday I will add/unskip as many (quick running and consistently passing) API tests as possible, then decide whether to continue with API tests or switch to unit tests

**Comment by rwalle61** [comment]
After 1 week PFE's overall test coverage has gone up 11% from 55% to 66%:
![image](https://user-images.githubusercontent.com/18170169/73544661-98734980-4431-11ea-8925-594d83321128.png)

Coverage of /projects routes has gone up 31% from 40% to 71%:
![image](https://user-images.githubusercontent.com/18170169/73544721-b476eb00-4431-11ea-9ac1-e571db96292d.png)

**Comment by rwalle61** [comment]
I will open issues for the remaining 2 /projects routes not yet covered:
- [ ] compare (metrics)
- [ ] logStream

Increasing our test coverage has exposed several small bugs and lots of discrepancies with our OpenAPI docs. I have linked our tests to our docs where possible, using `reqValidator` in our route code and `res.should.satisfyApiSpec` in our tests.

Code covered by tests can still fail - for example, our tests for the project build API invoke `await user.buildProject(project, action);` but do not verify whether that works.

So moving forwards I recommend:
- [ ] adding `reqValidator` in any routes that don't have it yet
- [ ] adding unit tests to properly test key behaviour such as loadtest and Filewatcher stuff
- [ ] adding basic project lifecycle tests that could run overnight

**Comment by rwalle61** [comment]
For reference, coverage of portal modules is 59% (this shows where unit tests are needed):
![image](https://user-images.githubusercontent.com/18170169/73545984-4ed82e00-4434-11ea-808d-7b3ccb1a64c1.png)

And coverage of portal non-project routes is 69% (2 routes untested):
![image](https://user-images.githubusercontent.com/18170169/73546046-6b746600-4434-11ea-9a85-fbd3da6bac04.png)
