### ISSUE TITLE
SVT: [Che] Codewind for Eclipse Che cannot be accessed using a Google Chrome browser

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#1718]
**Codewind version:** 0.8.0
**OS:** Red Hat Enterprise Linux 7 (64 bit)

**Che version:** 7.5.1
**Kubernetes cluster:** OKD/Openshift 

**Description:** Codewind for Eclipse Che cannot be accessed using a Google Chrome browser, although it must be a compatible platform. I can successfully access Codewind using another browser (i.e., Mozilla Firefox).

*Google Chrome:*
<img width="1576" alt="Screen Shot 2020-01-13 at 8 11 33 AM" src="https://user-images.githubusercontent.com/49531960/72258819-023fc680-35dd-11ea-8921-2c6733354b68.png">

*Mozilla Firefox:*
<img width="1581" alt="Screen Shot 2020-01-13 at 8 21 21 AM" src="https://user-images.githubusercontent.com/49531960/72259147-bb060580-35dd-11ea-896c-181be7197915.png">

@jagraj

**Comment by tetchel** [comment]
looks like we have to open a che issue. The browser's console may have some helpful output

**Comment by johnmcollier** [comment]
Yes, @tetchel is correct.

For any Che issues, please open an issue in our repo, as well as a corresponding issue in the Che repo.

**Comment by sujeilyfonseca** [comment]
Thanks, @tetchel and @johnmcollier!

**Google Chrome Version:** Latest - 79.0.3945.117 (Official Build) (64-bit)
**Console Error:**

<img width="1280" alt="Screen Shot 2020-01-13 at 11 27 33 AM" src="https://user-images.githubusercontent.com/49531960/72273084-bc442c00-35f7-11ea-849f-a6bcb1f26d94.png">

**Comment by johnmcollier** [comment]
@sujeilyfonseca I'm unable to reproduce on Chrome on Che 7.5.1

Can you try reinstalling? And could you also verify which Che version is installed, by going to the Che dashboard and looking at the bottom:
<img width="1680" alt="Screen Shot 2020-01-14 at 11 56 53 AM" src="https://user-images.githubusercontent.com/6880023/72364751-ff200580-36c4-11ea-9dac-12368bd50f89.png">

**Comment by sujeilyfonseca** [comment]
**Google Chrome version:**
![Screen Shot 2020-01-16 at 9 13 16 AM](https://user-images.githubusercontent.com/49531960/72531934-7af28d00-3840-11ea-9563-7e6a97bfc3d2.png)
</br>
**Eclipse Che version:**
![Screen Shot 2020-01-16 at 9 12 37 AM](https://user-images.githubusercontent.com/49531960/72531931-7928c980-3840-11ea-873c-446c949ad577.png)

</br>
I verified the issue again with my existing installation and kept seeing the problem. However, after reinstalling Google Chrome 79.0.3945.117 and Eclipse Che 7.5.1, I no longer see the problem:

![Screen Shot 2020-01-16 at 9 17 51 AM](https://user-images.githubusercontent.com/49531960/72532292-24d21980-3841-11ea-84f3-46171dea4ee4.png)

**Comment by tetchel** [comment]
can you still see this? also since it is a che issue i am removing the vs code tag.

**Comment by sujeilyfonseca** [comment]
I can no longer reproduce this problem. I'll proceed to close this problem.
