### ISSUE TITLE
OS Detection in the Get Started Page

### ISSUE THREAD

**Issue by thisguy-1** [eclipse/codewind#173]
There is too much text for this page. A user should only see what is relevant to them. OS detection would help with this issue. A Mac OS user should only have to see what is relevant to them. If for some reason they need to see the instructions for a different platform, they could see a link that says "Need a different platform?". 

https://www.eclipse.org/codewind/installlocally.html

- [ ] OS detection that hides instructions regarding irrelevant platforms.
- [ ] Link to other platform instruction: "Need a different platform?"

![Codewind Install Instructions](https://user-images.githubusercontent.com/52169824/62888731-e8d4de80-bd0d-11e9-9b8c-693b93b1d62c.png)

**Comment by sishida** [comment]
@travis1111 Hi, Travis, I know the topic of OS detection has come up in the past, and I just thought I'd bring this to your attention. Maybe we could discuss the feasibility of OS detection or plan to add it for a future iteration?

**Comment by travis1111** [comment]
@sishida sure, please assign to me and I will take a look :-)

**Comment by travis1111** [comment]
@sishida we don't have this MD file linked on our landing page anymore, do we still need this?

**Comment by sishida** [comment]
@travis1111 I think the general question of the OS detection for the entirety of Codewind.dev still stands--do we know how easy/difficult or how feasible that would be?

**Comment by travis1111** [comment]
It is not hard, but not 100% accurate.  Do we have any docs that need this at this moment?

**Comment by sishida** [comment]
@thisguy-1 I'm going to close this issue because the "Get started" page file is no longer in use in the table of contents. If we have another file that needs OS detection, let's open a new issue then.
