### ISSUE TITLE
0.8.0: cwctl  install remote pulls images tagged 'latest'

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind#1734]
Using the 0.8.0 version of cwctl, I installed a remote codewind on an OpenShift cluster.  When I examine which image was installed for pfe, kubectl reports it is 'latest'
```
Containers:
  codewind-pfe:
    Container ID:   cri-o://fbe0174fbc2eb6689f2a9038563614ee7fff319b2f930103b5d97569eb3090b3
    Image:          eclipse/codewind-pfe-amd64:latest
    Image ID:       docker.io/eclipse/codewind-pfe-amd64@sha256:3fe1c72d283feb5063eb5cb4bec9eb2343395abb980b4372fc9b66d5e7216ea3
    Port:           9191/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Mon, 13 Jan 2020 13:42:21 -0500
 ```

Note that the 0.8.0 version of cwctl reports it's own version as `x.x.dev` -- this needs to be updated as well.

**Comment by johnmcollier** [comment]
To avoid having to fix this each release, it'd be nice if we could somehow integrate this into the CLIs build so that it's automatic, based on the release branch it's on.

**Comment by malincoln** [comment]
@tobespc ^^^

**Comment by tobespc** [comment]
this is supposed to be done as part of the dcut process, I'll do it now

**Comment by malincoln** [comment]
> this is supposed to be done as part of the dcut process, I'll do it now

@josephca do we need to update the release process for this?

**Comment by malincoln** [comment]
@jopit pls verify and close.  Thanks

**Comment by jopit** [comment]
Verified
