### ISSUE TITLE
Allow use of cwctl sectoken/seckeyring commands if there is no system keyring (and/or add an 'insecure keyring mode' environment variable)

### ISSUE THREAD

**Issue by jgwest** [eclipse/codewind#1735]
On a Linux system I am using, I've been unable to connect to a remote Codewind install, due to the following message from Codewind Eclipse during remote connect:

```
!ENTRY org.eclipse.codewind.core 4 0 2020-01-13 09:39:15.377
!MESSAGE [ERROR AuthUtil.genAuthToken:48] Seckeyring update failed with rc: 1 and error: {"error":"sec_keyring","error_description":"failed to unlock correct collection '/org/freedesktop/secrets/aliases/default'"}

!ENTRY org.eclipse.codewind.ui 4 0 2020-01-13 09:39:15.390
!MESSAGE An error occurred while trying to connect the jgw1 connection.
!STACK 0
java.io.IOException: {"error":"sec_keyring","error_description":"failed to unlock correct collection '/org/freedesktop/secrets/aliases/default'"}

	at org.eclipse.codewind.core.internal.cli.AuthUtil.genAuthToken(AuthUtil.java:49)
	at org.eclipse.codewind.ui.internal.wizards.CodewindConnectionComposite.createConnection(CodewindConnectionComposite.java:225)
	at org.eclipse.codewind.ui.internal.wizards.NewCodewindConnectionPage.createConnection(NewCodewindConnectionPage.java:62)
	at org.eclipse.codewind.ui.internal.wizards.NewCodewindConnectionWizard$1.run(NewCodewindConnectionWizard.java:64)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

This is likely a configuration issue specific to the Linux system I am using (so no need for y'all to try to reproduce), but, in general it may be beneficial to: 
- support a keyring-less system
- perhaps only supporting it behind a debug environment variable like `ALLOW_INSECURE_KEYING`, that would just store the keyring information in a simple text file in `.codewind`.

I'm not sure if anyone else has hit this issue, but it's definitely something I have hit on a few different Linux VMs (but again, it's probably always due to the specific configuration I am using)

**Codewind version:** Seen on 0.7, 0.8, and latest
**OS:** Linux

**IDE extension version:** Seen on 0.7, 0.8, and latest

**Comment by jgwest** [comment]
BTW it's not an IDE issue specific issue, I've also seen it from VSCode... thought I'd paste the exception I get there for reference:
```
[ERRO: 21:17:13.317 CLIWrapper.js:170]: Error running cwctl --json --insecure seckeyring update --conid K40UDKGG --username developer --password *********
Logger.js:140
[ERRO: 21:17:13.317 CLIWrapper.js:171]: Stdout: {"error":"sec_keyring","error_description":"failed to unlock correct collection '/org/freedesktop/secrets/aliases/default'"}
Logger.js:137
[INFO: 21:17:13.318 RemoteConnection.js:179]: Finished updating keyring credentials

------

[DBUG: 21:17:13.226 Connection.js.setState():109]: moo22 is now Auth Error
Logger.js:140
[DBUG: 21:17:13.242 Connection.js.setState():109]: moo22 is now Auth Error
Logger.js:140
[ERRO: 21:17:13.248 Connection.js:98]: Error initializing moo22: Error running cwctl sectoken get: failed to unlock correct collection '/org/freedesktop/secrets/aliases/default'
Logger.js:137
[DBUG: 21:17:13.256 ConnectionMemento.js:119]: Saved memento for connection K40UDKGG
Logger.js:137
Object
[DBUG: 21:17:13.258 RemoteConnection.js:172]: Refreshing access token after credentials update
Logger.js:140
[INFO: 21:17:13.259 CLIWrapper.js:129]: Running CLI command: cwctl --json --insecure seckeyring update --conid K40UDKGG --username developer --password *********
Logger.js:140
[ERRO: 21:17:13.317 CLIWrapper.js:170]: Error running cwctl --json --insecure seckeyring update --conid K40UDKGG --username developer --password *********
Logger.js:140
[ERRO: 21:17:13.317 CLIWrapper.js:171]: Stdout: {"error":"sec_keyring","error_description":"failed to unlock correct collection '/org/freedesktop/secrets/aliases/default'"}
Logger.js:137
[INFO: 21:17:13.318 RemoteConnection.js:179]: Finished updating keyring credentials
```

**Comment by johnmcollier** [comment]
I've hit this in two separate scenarios:
- My RHEL 7.x dev VM
- The Theia container in Che

I think this might be a useful thing to have, especially for systems where it's not possible / easy to setup a keyring.

Slightly related: My other big concern right now is that our docs don't even highlight that a keyring is needed for cwctl

**Comment by tobespc** [comment]
we should doc this as a pre req to have keychain on mac, credential store on windows and 'secret service' on linux

**Comment by micgibso** [comment]
Doc updates are complete, see above PR.

**Comment by tobespc** [comment]
closing as docs complete

**Comment by jgwest** [comment]
Reopening as this enhancement was opened to track a requested code change, not a doc update.

**Comment by malincoln** [comment]
@tobespc I removed the 0.8.0 release label. Pls update once targeted release is known.  Thanks

**Comment by AndyRWatson** [comment]
This is a prereq to being able to use codewind as part of the skills network labs which will form the basis of quicklabs for future conferences in 2020.    @johnmcollier can you confirm based on the  work you did with @bsteinfeld

**Comment by johnmcollier** [comment]
@AndyRWatson I can confirm that this is a requirement for the work that @bsteinfeld has been looking at

**Comment by tobespc** [comment]
Having a "developer" or "debug" mode where (as per comment above)

 ```perhaps only supporting it behind a debug environment variable like ALLOW_INSECURE_KEYING, that would just store the keyring information in a simple text file in .codewind.```

is worth looking into

**Comment by rwalle61** [comment]
@jgwest @johnmcollier so cwctl will provide a debug mode where we store the keyring info in a simple text file in .codewind. There are 2 options:

1. the IDEs tell cwctl which keyring mechanism to use by calling cwctl with a flag such as `--allow-insecure-keyring`.
2. IDEs don't tell cwctl which keyring mechanism to use. Cwctl tries to use the secure keyring by default. If that fails, cwctl will fall back to the insecure mechanism and inform the user. However, this increases the risk that a user does not realise that their secrets are stored insecurely

So we will go for option 1, unless anyone objects

**Comment by bsteinfeld** [comment]
I like option 1. Would be nice if this _also_ could be defaulted via an environment variable (e.g. `ALLOW_INSECURE_KEYRING=true`

**Comment by rwalle61** [comment]
just to clarify, you mean defaulted via an environment variable *in the IDE*, right?

**Comment by bsteinfeld** [comment]
I mean via any process (_IDE_ included) that will call `cwctl`. To be specific I'd like all the following to work:

No IDE
```
export ALLOW_INSECURE_KEYRING=true
cwctl templates list --conid $CONID
```

No IDE
```
cwctl --use-insecure-keyring templates list --conid $CONID
```

IDE (e.g. theia)
```
export ALLOW_INSECURE_KEYRING=true
yarn theia start /home/project --hostname=0.0.0.0
# ide should now leverage this envVar when running cwctl
```

**Comment by rwalle61** [comment]
both 
```
cwctl --insecureKeyring templates list --conid $CONID
```
and
```
export INSECURE_KEYRING=true
cwctl templates list --conid $CONID
```
should work now

**Comment by malincoln** [comment]
@jgwest pls verify and close. Thanks

**Comment by jgwest** [comment]
Happy to report it works great on the keychain-less Linux environment that previously caused issues 🎉 👍  

(I tested with the `export INSECURE_KEYRING=true` method listed above).
