### ISSUE TITLE
SVT:Websphere liberty default project fails to start on codewind che

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#1740]
**Codewind version:** 0.8.0
**OS:** CoreOS

**Che version:** 7.5.1
**IDE extension version:** 0.8.0
**IDE version:** 7.5.1
**Kubernetes cluster:**
 OCP 4.2

**Description:**
Websphere liberty default project fails to start on Codewind che. The status says "Starting" all the time. Some times build fails too and then I have to restart the build.  Here I am posting screenshots and logs for this issue.

**Steps to reproduce:**
1. Install codewind on eclipse che 7.5.1
2. Create Websphere liberty project.
3. Project status will get stuck in "Starting" and sometimes build failed too then I need to restart the build.

![image](https://user-images.githubusercontent.com/713849/72298956-87eb6280-362d-11ea-86b5-3414dc83e328.png)

[libertyapp-log.txt](https://github.com/eclipse/codewind/files/4056377/libertyapp-log.txt)
[pfe.txt](https://github.com/eclipse/codewind/files/4056378/pfe.txt)

**Workaround:**

**Comment by tobespc** [comment]
I updated the liberty template yesterday to move to microprofile 3.2

**Comment by tobespc** [comment]
I've reverted the template and this fixes this issue.  I will work on a separate issue to re update it

**Comment by tobespc** [comment]
https://github.com/eclipse/codewind/issues/1395

**Comment by jagraj** [comment]
This issue has been resolved after reverting the template version. Issue 1395 will address latest version. Closing this issue now. Thx for the fix.
