### ISSUE TITLE
Overview topic: Add url to Templates overview when it is created

### ISSUE THREAD

**Issue by MelHopper** [eclipse/codewind#1744]
Currently, we do not have a suitable topic to link to when describing Codewind's pre-supplied project templates. 

Creation of Template overview topic is in plan for 0.8 or 0.9.

Add a link to the new Template overview topic to:
1. the 'Access to pre-configured, containerized project templates' bullet point description 
2. The subheading content "What pre-configured containerized projects does Codewind provide?"

once the new Template Overview topic is available.

**Comment by micgibso** [comment]
@MelHopper Pls take a look, thx.

**Comment by MelHopper** [comment]
Blocking https://github.com/eclipse/codewind/issues/1106

**Comment by MelHopper** [comment]
Completed as part of PR https://github.com/eclipse/codewind-docs/pull/351
