### ISSUE TITLE
SVT: [VS Code] Codewind allows creating default/standard projects without having an Image Registry, which eventually leads to a build failure

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#1746]
**Codewind version:** 0.8.0
**OS:** Mac OS Mojave 10.14.6

**IDE extension version:** 0.8.0
**IDE version:** 1.41.1

**Description:** Codewind allows creating default/standard projects without having an Image Registry, which eventually leads to a build failure. We must inform the user that he/she needs to define an Image Registry. The current error message indicates that the user needs to verify that the Image Registry is valid and that it has the appropriate permissions. Still, this message doesn't mention the root cause of not having defined a registry:

<img width="1516" alt="Screen Shot 2020-01-14 at 9 34 38 AM" src="https://user-images.githubusercontent.com/49531960/72353910-cf680200-36b2-11ea-8fae-555acc37c2e7.png">

Eclipse Che has a notification for this scenario:

<img width="496" alt="Screen Shot 2020-01-14 at 9 49 48 AM" src="https://user-images.githubusercontent.com/49531960/72354768-510c5f80-36b4-11ea-9052-7e293bf90b87.png">

**Steps to reproduce:**</br>
*First Scenario:*
1. Install and start Codewind 0.8.0
2. Configure a new remote connection ([remote-configuring.md](https://github.com/eclipse/codewind-docs/blob/0.8.0/docs/_documentations/remote-configuring.md))
3. Create a new remote connection using Codewind for VS Code  ([remote-connection-ui.md](https://github.com/eclipse/codewind-docs/blob/0.8.0/docs/_documentations/remote-connection-ui.md))
4. Define/create a new push registry
5. Create a Codewind style project (optional)
6. Delete the push registry using Codewind for VS Code
7. Delete the remote connection using Codewind for VS Code
8. Uninstall Codewind
9. Install and start Codewind 0.8.0
10. Create a new remote connection using the previous configuration
11. Create a Codewind style project without defining an Image Registry

*Second Scenario:*
1. Install and start Codewind 0.8.0
2. Configure a new remote connection ([remote-configuring.md](https://github.com/eclipse/codewind-docs/blob/0.8.0/docs/_documentations/remote-configuring.md))
3. Create a new remote connection using Codewind for VS Code ([remote-connection-ui.md](https://github.com/eclipse/codewind-docs/blob/0.8.0/docs/_documentations/remote-connection-ui.md))
4. Define/create a new push registry
5. Create a Codewind style project (optional)
6. Delete the push registry using Codewind for VS Code
7. Create a Codewind style project without defining an Image Registry 

@jagraj

**Comment by tetchel** [comment]
It works for me:
![image](https://user-images.githubusercontent.com/8888438/72368607-69887400-36cc-11ea-93a4-43a341a651f5.png)


did you, by any chance, previously have an image registry on that install, and then delete it?

**Comment by sujeilyfonseca** [comment]
I have verified this problem again. Everything works as expected with a new Codewind installation and remote connection. However, you will see the error above:

- If the remote connection existed previously and contained a push registry, and both were deleted from Codewind, but the same remote connection is used in another installation.
- If a push registry is deleted in the current installation and then the user tries to create a Codewind style project.

**Comment by tetchel** [comment]
ok makes sense. this is a symptom of https://github.com/eclipse/codewind/issues/1440

**Comment by rajivnathan** [comment]
@sujeilyfonseca can you please update the detailed steps to reproduce for both of the scenarios you mentioned in comment https://github.com/eclipse/codewind/issues/1746#issuecomment-574309918?

**Comment by sujeilyfonseca** [comment]
@rajivnathan, I've updated the detailed steps to reproduce the problem. 

Note: I only used Codewind for VS Code.

**Comment by malincoln** [comment]
@sujeilyfonseca pls verify and close.  Thanks

**Comment by sujeilyfonseca** [comment]
I verified this issue with the latest Codewind, and I still see the problem.

If I have a clean installation, I can still see a message warning me that I haven't set up an Image Registry for Codewind style projects:

![Screen Shot 2020-01-27 at 11 04 37 AM](https://user-images.githubusercontent.com/49531960/73197647-a8242280-40ff-11ea-8efa-d567adcf3352.png)

However, I can still reproduce the scenarios indicated in the issue description: 

![Screen Shot 2020-01-27 at 11 42 51 AM](https://user-images.githubusercontent.com/49531960/73197724-d144b300-40ff-11ea-8e1a-8032ed581dcd.png)

**Comment by maysunfaisal** [comment]
This hasnt been implemented yet in the UI, so the fix cant be tested.

**Comment by malincoln** [comment]
> This hasnt been implemented yet in the UI, so the fix cant be tested.

Not sure why it was moved to verify.  Who's working on the UI piece is that being tracked by a separate issue or as part of this issue?

**Comment by tetchel** [comment]
should work in vs code now

**Comment by malincoln** [comment]
@rajivnathan is this ready to verify or should be moved back to in progress?

**Comment by tetchel** [comment]
still needs to be fixed in eclipse

**Comment by eharris369** [comment]
Eclipse IDE PR: https://github.com/eclipse/codewind-eclipse/pull/558

**Comment by malincoln** [comment]
I see the Eclipse fix is merged.  Any other fixes required?

**Comment by sujeilyfonseca** [comment]
I verified this issue with the latest Codewind and I no longer see the problem.

However, Eclipse asks the user to configure an image registry every time an attempt is made to create a Codewind-style project. On the other hand, VS Code asks the user to create the image registry the first time, but if the user creates an image registry and deletes it, he/she will no longer receive the notification. Eventually, a new Codewind-style project will be created without a registry but will fail due to the missing image registry. Therefore, there is a different behavior for the same action between the two IDEs. Even so, the error message in VS Code is now more reasonable and allows the user to understand what he/she did wrong.


**Eclipse:**
<img width="511" alt="Screen Shot 2020-02-03 at 12 28 39 PM" src="https://user-images.githubusercontent.com/49531960/73675868-432d7700-4681-11ea-8f07-75256e3a87c5.png">

<img width="361" alt="Screen Shot 2020-02-03 at 12 31 09 PM" src="https://user-images.githubusercontent.com/49531960/73675885-4d4f7580-4681-11ea-9c0a-85d90547d93d.png">

</br>

**VS Code:**
<img width="1678" alt="Screen Shot 2020-02-03 at 12 08 13 PM" src="https://user-images.githubusercontent.com/49531960/73675972-72dc7f00-4681-11ea-9e5e-cc78904e730d.png">

<img width="1675" alt="Screen Shot 2020-02-03 at 12 19 47 PM" src="https://user-images.githubusercontent.com/49531960/73675939-62c49f80-4681-11ea-9091-645265323a5a.png">

<img width="1675" alt="Screen Shot 2020-02-03 at 12 22 08 PM 3" src="https://user-images.githubusercontent.com/49531960/73675983-7a038d00-4681-11ea-94cc-2e5f2c469fc2.png">

<img width="1287" alt="Screen Shot 2020-02-03 at 12 21 55 PM" src="https://user-images.githubusercontent.com/49531960/73676812-0498bc00-4683-11ea-8f58-931bf1141a73.png">

**Comment by tetchel** [comment]
When you remove the push registry you get a pretty in-your-face warning that codewind projects will fail to build until a new push registry is selected, which is why I didn't bother blocking the user after that.

**Comment by sujeilyfonseca** [comment]
That's true and the error message is now better. I'll proceed to close this issue.
