### ISSUE TITLE
adding existing project with jpeg or png files fails to copy into codewind-data folder

### ISSUE THREAD

**Issue by patricktiu** [eclipse/codewind#1749]
**Codewind version:** 0.7.0
**OS:** macox
**vscode version:** 1.41.0

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:** 
Adding existing project from codewind dashbroad in vscode with codewind extension fails to copy all the jpeg or png files into the `~/codewind-data` folder

**Steps to reproduce:**
1. mkdir ~/projects
2. cd ~/projects
3. git clone https://github.com/philibm/kmodsrc
4. open vscode and add existing project from ~/projects/kmodsrc into codewind
5. diff -R ~/projects/kmodsrc/src ~/codewind-data/kmodsrc/src

***You will see differences in these two folders.  I would expect them to be the same***

**Workaround:**

**Comment by jagraj** [comment]
@sghung @makandre 
I have been working with Patrick on this problem this morning. We found during debugging from the browser where partial image has been rendered into browser. Making this as stopship for 0.8.0 release.

**Comment by makandre** [comment]
Looking into it now... something's up with the project sync...

**Comment by makandre** [comment]
We're hitting a `413 payload too large` on the upload API, so the larger image binaries are being skipped.

![image](https://user-images.githubusercontent.com/17596240/72375898-f20e1100-36da-11ea-9d8f-f18ce2e72db0.png)

**Comment by makandre** [comment]
Also, binary files are increasing in size (contributing to hitting the payload limit).  This I suspect is because the sync/upload code is marshalling/unmarshalling the contents to `json`?

- https://github.com/eclipse/codewind-installer/blob/master/pkg/project/sync.go#L157
- https://github.com/eclipse/codewind/blob/master/src/pfe/portal/routes/projects/remoteBind.route.js#L178

**Comment by tobespc** [comment]
its the http upload limit that causes this issue, not sync.  Will need to look at maybe multi part uploads/compression

**Comment by tobespc** [comment]
increasing the limit fixes the file sync, however I now have a new issue as a result whereby .jpg and .png files are almost doubling in size after the copy

**Comment by malincoln** [comment]
@patricktiu pls verify and close.  Thanks

**Comment by patricktiu** [comment]
do you have the instruction to get the latest driver?

**Comment by patricktiu** [comment]
It is verified with 0.8.0 codewind.vsix driver from https://download.eclipse.org/codewind/codewind-vscode/0.8.0/latest/
