### ISSUE TITLE
Deploying Codewind from the Che Plugin Registry fails

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#1750]
If we add Codewind to the Che plugin registry, the deployment of Codewind from there fails as we're unable to retrieve any pods on this line: https://github.com/eclipse/codewind-che-plugin/blob/e3b6a5bd1ca48700ad19edf1234152dff0adeb61/codewind-che-sidecar/src/deploy-pfe/pkg/che/che.go#L86

The solution is to remove the label selector for `che.original_name=che-workspace-pod`, as it's not applicable in this situation. Removing it is also safe, as we don't need the additional label any more, as we only need the owner reference for **one** Che workspace pod, it doesn't matter which one.

**Comment by johnmcollier** [comment]
Adding to the 0.9.0 release

**Comment by malincoln** [comment]
@johnmcollier just confirming this is still on target for 0.9.0 that dcut on Wednesday?

**Comment by johnmcollier** [comment]
@malincoln Yup, getting a PR up later today for this.
