### ISSUE TITLE
A new source directory in an Appsody Liberty project is not compiled in Codewind

### ISSUE THREAD

**Issue by keithchong** [eclipse/codewind#1753]
**Codewind version:** 0.8.0
**OS:** Mac 

**IDE extension version:** VS Code or Eclipse 0.8.0
**IDE version:** VS Code 1.41.1 or Eclipse 2019.03 or later
**Kubernetes cluster:** Local

**Description:** 
An entire, newly created source directory in an Appsody Open Liberty project is not compiled in Codewind - The .class files are missing in the app container.  I reproduced this using an Appsody Open Liberty project, but it is not reproducible using a Codewind Open Liberty project. 

**Steps to reproduce:**
1. Create a new Appsody Open Liberty project
2. Add a new source tree directory, eg. `src/xyz/java` by updating the pom.xml and creating the folder structure.
3. Create a Java package `foo` in this source tree directory
4. Create one or more .java files in this `foo` folder/package and add some methods.  (Can use the contents from the existing StarterResource.java) 
5. Build
6. Check the app container.   
--> The source and package folders are present in the new source tree and so are the pom.xml updates. However, in the target folder, the .class files are not present.  (The new source was not compiled)

Of note, using the local (Eclipse) IDE maven m2e build, the source files are compiled and the .class files exist in the local target folder.  So this is not a Maven configuration issue. 

Although there is no issue using the Codewind Open Liberty template, this may be an Appsody stack and/or Portal issue?
 
Another synchronization problem:
If I created a new package and Java file into the existing `src/main/java` directory, the class is compiled successfully (check app container).  However, if I move this file (and folder/package) to the new source directory, there are actually two copies in the app container: Portal does not remove the original copy from the app container. 

**Workaround:** 
No acceptable workaround

**Comment by jgwest** [comment]
Under 'Another synchronization problem', Keith notes another issue he has seen with renaming java classes, where the source of the rename operation is never removed. I have intermittently seen this as well, with non-Appsody Microprofile projects.

**Comment by stalleyj** [comment]
I've checked that the source is getting to the right place so I think it must an appsody issue that it is not being compiled. @jgwest @keithchong Can you raise other synchronisation problems separately please.

**Comment by scottkurz** [comment]
@keithchong as a maintainer of the **java-openliberty** appsody stack I'd like to help.  Can you please share the pom.xml you used to point to **src/xyz/java** and I can take a look ?  (I'd first look outside of Codewind).  Thanks.

**Comment by keithchong** [comment]
@scottkurz , add this to your build plugins:
```
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <version>1.9.1</version>
        <executions>
          <execution>
            <id>add-source</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>add-source</goal>
            </goals>
            <configuration>
              <sources>
                <source>src/xyz/java</source>
              </sources>
            </configuration>
          </execution>
        </executions>
      </plugin>
```

**Comment by scottkurz** [comment]
@keithchong, the java-openliberty appsody stack is built on top of the "dev mode" of the liberty-maven-plugin.  This goal implements its own "lifecycle"-like workflow to provide a much quicker update upon source changes.  To do this, however, it does not support binding any generic plugin to any lifecycle phase, and this plugin goal is not supported.     

It's possible we could open a new issue on the [liberty-maven-plugin](https://github.com/OpenLiberty/ci.maven), and/or something with the java-openliberty appsody stack..

But before we do either of those, can you give any more detail about your use case and why you want to use more than **src/main/java**?

**Comment by hhellyer** [comment]
@keithchong - I'm going to close this as it's an actual error in the source that's being built rather than an issue in Codewind itself. (Codewind isn't really doing anything wrong as far as I can tell from the write up above.)
Please feel free to open if you think there is a codewind problem here.
