### ISSUE TITLE
VS Code content on Docs Landing Page

### ISSUE THREAD

**Issue by micgibso** [eclipse/codewind#1756]
**Description of the enhancement:**
Enhance the new content of the VS Code section of the landing page on the master branch. The new section comprises three topics:
- Installing Codewind for VS Code
- Creating your first project
- Making a code change

**Proposed solution:** 
Edit these topics so the information flows, is grammatically correct, and conforms to standards.

**Comment by j-c-berger** [comment]
@micgibso and/or @sishida, please assign me--thanks.

**Comment by micgibso** [comment]
@j-c-berger Is this complete? Thx.

**Comment by j-c-berger** [comment]
@micgibso, yes sir! All PRs for VS Code restructure has been merged. Let's round it out, thanks!
