### ISSUE TITLE
Eclipse content on Docs Landing Page

### ISSUE THREAD

**Issue by micgibso** [eclipse/codewind#1757]
**Description of the enhancement:**
Enhance the new content of the Eclipse section of the landing page on the master branch. The new section comprises three topics:

- Installing Codewind for Eclipse
- Creating your first project
- Making a code change

**Proposed solution:**
Edit these topics so the information flows, is grammatically correct, and conforms to standards.

**Comment by j-c-berger** [comment]
@micgibso and/or @sishida, please assign me--thanks.
