### ISSUE TITLE
Templates content on Docs Landing Page

### ISSUE THREAD

**Issue by micgibso** [eclipse/codewind#1761]
**Description of the enhancement:**
Enhance the new content of the Templates section of the landing page on the master branch. The new section comprises one topic.

**Proposed solution:**
Edit this topic so the information flows, is grammatically correct, and conforms to standards.

**Comment by micgibso** [comment]
The Working with Templates topic is now the only occurrence of this subject matter in the doc set. Previously, this content was duplicated under topics: `mdt-eclipse-workingwithtemplates.md` and `mdt-vsc-workingwithtemplates,md` which have been removed from master under a separate PR. 

The Working with Templates topic content is unchanged and it sits nicely in our TOC at the appropriate place. Spun it up locally checked all links, everything works as it should. 
Afaik, no further changes are required.

**Comment by micgibso** [comment]
@j-c-berger Please review http://codewind-docs.rtp.raleigh.ibm.com:4321/codewind/workingwithtemplates.html

**Comment by j-c-berger** [comment]
@micgibso, will do, and please assign to me. Thanks.

**Comment by MelHopper** [comment]
@micgibso are you able to add the following line in the appropriate location to your Templates topic? (aligns with the Overview content):

"Codewind provides pre-configured, Docker-containerized project templates covering several languages including [Node.js](https://nodejs.dev/), [Java](https://www.java.com/), [Python](https://www.python.org/) and [Swift](https://swift.org/), and several frameworks such as [Express](https://expressjs.com/), [Spring Boot](https://spring.io/projects/spring-boot) and [Open Liberty](https://openliberty.io/). [Quickly create and deploy microservices](https://www.youtube.com/watch?v=zKMggp10gq4&t=12s) in languages and frameworks that you're familiar with. Modify the pre-configured projects to develop your customised microservice."

**Comment by micgibso** [comment]
@MelHopper Mel, yes, will take a look.

**Comment by j-c-berger** [comment]
@micgibso, Sarah and I were going to close this issue yesterday, because the PR has been merged, but we wanted to wait until Mel's comment was addressed. If Mel's comment is now applied to #333, is this issue good to close?

**Comment by micgibso** [comment]
@j-c-berger Not quite; a few more comments from Sarah on PR #333 for her to approve.
