### ISSUE TITLE
Developing projects content on Docs Landing Page

### ISSUE THREAD

**Issue by micgibso** [eclipse/codewind#1762]
**Description of the enhancement:**
Enhance the new content of the Developing projects section of the landing page on the master branch. The new section currently comprises two topics:

- Importing existing projects
- Build logs

**Proposed solution:** 
Edit this topic so the information flows, is grammatically correct, and conforms to standards.

**Comment by j-c-berger** [comment]
@micgibso and/or @sishida, please assign me--thanks.

**Comment by micgibso** [comment]
Updates made, closing.
