### ISSUE TITLE
Performance monitoring content on Docs Landing Page

### ISSUE THREAD

**Issue by micgibso** [eclipse/codewind#1763]
Description of the enhancement:
Enhance the new content of the Performance monitoring section of the landing page on the master branch. The new section currently comprises two topics:

- Application metrics
- Performance

Proposed solution:
Edit this topic so the information flows, is grammatically correct, and conforms to standards.

**Comment by sishida** [comment]
We need to add step by step walkthrough instructions for injection metrics. We currently do not have this info in the existing files.

However, we currently have a feature under a minute video here: https://youtu.be/LsjmnMCuBxo

**Comment by micgibso** [comment]
Auto-inject metrics checkbox instructions currently here: https://www.eclipse.org/codewind/mdteclipsemanagingprojects.html and here https://www.eclipse.org/codewind/mdt-vsc-commands-project.html for 0.8.0.
