### ISSUE TITLE
SVT: Timeout popups for server less projects in the list

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#1777]
**Codewind version:** 0.8.0
**OS:** Windows/Mac

**Che version:** 
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**
We are getting timeout popups if we have projects created with no web servers. We keep getting these popups for every refresh and we did not see this problem in the previous release.

**Steps to reproduce:**
1. Install Codewind from eclipse plugin.
2. Create Appsody Kitura, Bash, Nodejs default and any serverless projects.
3. We keep getting these popups.

![Screen Shot 2020-01-15 at 2 33 12 PM](https://user-images.githubusercontent.com/713849/72464797-fbaf7b80-37a3-11ea-9ccb-40a861d7a1df.png)
![Screen Shot 2020-01-15 at 2 23 01 PM](https://user-images.githubusercontent.com/713849/72464798-fbaf7b80-37a3-11ea-8cbe-e4154931330a.png)
![Screen Shot 2020-01-15 at 2 15 29 PM](https://user-images.githubusercontent.com/713849/72464799-fbaf7b80-37a3-11ea-8b99-d172e9554a1a.png)

**Workaround:**

**Comment by jagraj** [comment]
For every project that I create after creating those projects with no web servers then I get all these timeout popups once. :(

![Screen Shot 2020-01-15 at 2 59 45 PM](https://user-images.githubusercontent.com/713849/72466969-f6ecc680-37a7-11ea-93d7-6758e0d116e3.png)

**Comment by makandre** [comment]
#1269 has some notes and discussions on a long term solution.  But looks like we'll need an interim solution for 0.8.0

**Comment by sghung** [comment]
TODO: open issue against appsody to add description about serverless apps, so the user is aware

**Comment by malincoln** [comment]
@sghung will we get the fix from Appsody in time to get this included in 0.8.0?

**Comment by makandre** [comment]
Re TODO: opened https://github.com/appsody/stacks/issues/602

@malincoln We discussed with iterative-dev team and the fix would be in Turbine; there's no fix in appsody extension.

**Comment by elsony** [comment]
During the iterative dev meeting, SVT has agreed that this is not a stopship but we'll still put a temporary fix on it for 0.8.0 and properly fix it on 0.9.0. It is actually correct to show the error dialog to the user.  Due to the risk for putting -1 port setting on 0.8.0 is too risky, we'll temporarily disable the timeout event for Appsody projects only (i.e. to bring it back to the same behaviour as 0.7.0).

**Comment by malincoln** [comment]
@jagraj the temp fix PR has been merged for 0.8.0.  Pls verify.
@elsony mentioned he will use same issue for proper fix in 0.9.0

**Comment by sghung** [comment]
For appsody types only, code was reverted back to the previous 0.7.0 behaviour, so the timeout popup will not show up for appsody types.

**Comment by rajivnathan** [comment]
Spoke to Elson about this yesterday. We'll handle the changes for 0.9.0 as part of issue https://github.com/eclipse/codewind/issues/1269 so will move this issue to verify state.

@jagraj can you please close this issue once you have verified?

**Comment by jagraj** [comment]
The partial fix has been verified with the latest 0.8.0 images and I no longer see the issue with the appsody projects. Closing this issue now.
