### ISSUE TITLE
Numbered lists in markdown don't replicate in built help

### ISSUE THREAD

**Issue by micgibso** [eclipse/codewind#1791]
**Description:**
I have a numbered list in markdown, however when I build the help locally, the numbering defaults to 1:
![image](https://user-images.githubusercontent.com/7224752/72621420-1ebf6400-3939-11ea-894a-06522471bbb6.png)

**Workaround:** 
Not ideal, but for now, remove the numbering.

**Comment by tetchel** [comment]
Michael, you can try this:
https://meta.stackoverflow.com/a/289013

**Comment by tetchel** [comment]
Since there's a blank line between steps, markdown treats the next step as the start of the new list, which is why it goes back to 1

**Comment by travis1111** [comment]
Yes, you have extra empty line which caused the problem

**Comment by micgibso** [comment]
@tetchel @travis1111 Thanks both, will give your suggestion a try Tim.

**Comment by micgibso** [comment]
@tetchel @travis1111 Tim, your suggestion - https://meta.stackoverflow.com/a/289013 - works like a charm, thx, closing.,..

**Comment by micgibso** [comment]
![image](https://user-images.githubusercontent.com/7224752/72737455-84109080-3b97-11ea-9c8b-0ea1fbce1800.png)
