### ISSUE TITLE
Node and Java profiling story for Codewind currently broken

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#1792]
Since moving to the new codewind architecture, the Node and Java profilers no longer work.   Main issue is that without the volume mount, the plugins are unable to see the results of the profiling run.

The data is generated as follows - 

 - Performance container triggers a load run
 - Profiling data (.hcd for example) is created in the app container
 
This data needs to make its way back to the local workspace for the profilers to access.

We have a number of stories that we can work through to solve all scenarios.

**Story 1 - Fully local environment**

Here we could use ```docker cp``` to copy the file from the app container to the local workspace

**Story 2 - Fully hosted**

Can do something similar to story 1

**Story 3 - Remote connection part 1**

To get the file back we would need to make use of the same http solution we have for syncing files, however these .hcd files can be large

**Story 4 - Remote connection part 2**

Work on improving story 3 - move all the processing of the data server side

**Comment by liamchampton** [comment]
Linking this ticket as it covers the node profiling issue https://github.com/eclipse/codewind/issues/1742

**Comment by rtaniwa** [comment]
Curious why this is labelled an enhancement? For the other issue referenced (https://github.com/eclipse/codewind/issues/533), if we want to claim appsody wasn't supported then I think that is fine to label an enhancement. That being said, given appsody needs first class support this is a gap that needs to get closed reasonable soon. But for this issue, if our extension are currently broken for all other project types because of the re-architecture, then this should be a high priority bug and not an enhancement given that is a regression.

**Comment by tobespc** [comment]
@ebuckle can you assign this to you as well please

**Comment by malincoln** [comment]
@tobespc you mentioned this is now done.  Does it need to move to verify?

**Comment by tobespc** [comment]
just waiting to land changes for remote

**Comment by malincoln** [comment]
@tobespc do we need SVT to verify?

**Comment by sujeilyfonseca** [comment]
I verified this issue with the latest Codewind 0.10.0, using the Codewind Node and Java Profilers. I was able to get the profiling data for Java and Node JS projects. The `.json` and `.hcd` files were created on my machines.

**Comment by malincoln** [comment]
> Moreover, I tested remote scenarios with Codewind for VS Code, but I was not able to retrieve load test results.

@tetchel @tobespc ^^^

**Comment by tobespc** [comment]
Closing as this is all fixed now
