### ISSUE TITLE
Autobuild is broken - 400 Bad Request output on sync

### ISSUE THREAD

**Issue by keithchong** [eclipse/codewind#1795]
**Codewind version:** Master (0.8.0 is fine)
**OS:** Mac

**Che version:** Local
**IDE extension version:** Eclipse latest master from download
**IDE version:** Eclipse 2019.03 or later
**Kubernetes cluster:** Local

**Description:** Autobuild is broken.  Create a MP project and make a change in application src/main/java/rest/v1/Example.java and wait --> app does not compile

Got 400 Bad Request calling `cwctl project sync`

Log:
```
Jan. 16 3:01:18.046 p.m. [2700.392] Batch change summary for c95bf170-3895-11ea-a2f3-c74c88626769@ 1579204876985: [ >Example.java ]
Jan. 16 3:01:18.760 p.m. [2701.105] Calling cwctl project sync with: [c95bf170-3895-11ea-a2f3-c74c88626769] { [/Users/kchong/.codewind/latest/cwctl] [--insecure] [project] [sync] [-p] [/Users/kchong/w/2019.03-cw/wsDev/cwMp01] [-i] [c95bf170-3895-11ea-a2f3-c74c88626769] [-t] [1579203207962] }
Jan. 16 3:01:18.932 p.m. [2701.278] Cwctl call completed, elapsed time of cwctl call: 172
Jan. 16 3:01:18.932 p.m. [2701.278] Successfully ran installer command: [/Users/kchong/.codewind/latest/cwctl] [--insecure] [project] [sync] [-p] [/Users/kchong/w/2019.03-cw/wsDev/cwMp01] [-i] [c95bf170-3895-11ea-a2f3-c74c88626769] [-t] [1579203207962] 
Jan. 16 3:01:18.932 p.m. [2701.278] Output:Status: 400 Bad Request
Jan. 16 3:01:18.932 p.m. [2701.278] Updating timestamp to latest: 1579204878760
Jan. 16 3:01:48.995 p.m. [2731.339] Initiating GET request to http://127.0.0.1:10000/api/v1/projects/watchlist
Jan. 16 3:01:48.995 p.m. [2731.340] Requested a secure token from the IDE but got a null

```

**Comment by jgwest** [comment]
I saw the same thing after refreshing my environment from scratch (prune image, prune volume, delete .codewind, ensure my cwctl is up to date, get latest eclipse source as I'm self-hosting).

Java/Eclipse Filewatcher correctly detects the change and calls `cwctl project sync`, but `cwctl` only outputs `400 Bad Request` to stdout.

**Comment by tobespc** [comment]
thanks, will take a look

**Comment by rwalle61** [comment]
I broke it with this https://github.com/eclipse/codewind/pull/1745/files#diff-b73b1946195409164e2ccc8a3b7fe79cL207

The fix is in this PR https://github.com/eclipse/codewind/pull/1790/files#diff-2210d4bf0af7416f78b3cb8692501fc3L1728

But that PR has other changes in as well so I will raise another PR with just the fix

**Comment by rwalle61** [comment]
@keithchong would you mind confirming whether my fix fixed your issue?

**Comment by malincoln** [comment]
@keithchong pls verify and close. Thanks

**Comment by stalleyj** [comment]
This is complete.
