### ISSUE TITLE
SVT : Appsody Node Red project updates ignored 

### ISSUE THREAD

**Issue by mmulholl** [eclipse/codewind#1800]
**Codewind version:**   Codewind tech preview	0.8.0.v202001161954	
**OS:**. Mac, Windows

**Che version:**
**IDE extension version:**
**IDE version:** Eclispe and VSCode
**Kubernetes cluster:**

**Description:**
Modifications to the flow.json file are not picked up by codewind even after a manual re-biuld of the project. To get the changes to be picked up you need to remove and re-import the project.

**Steps to reproduce:**
1. Create an appsody node red project
2. Modify flow.json for example change "Hello World!" to "Hello big wide World!"
3. wait for project to restart automatically but it doesn't. 
4. Rebuild the project manually, wait for running.
5. Open the application view but it still outputs "Hello World!"
6. Remove the project but leave on disk.
7. Import the project and wait for running 
8. Open the application and it now outputs "Hello big wide World!

Have seen this in Eclipse on Mac and Windows, also in VScode on Mac.

**Workaround:**

**Comment by stalleyj** [comment]
Fix for 0.8.0 here https://github.com/eclipse/codewind/pull/1810

**Comment by stalleyj** [comment]
Fix for master https://github.com/eclipse/codewind/pull/1811

**Comment by mmulholl** [comment]
Confirmed this works in the latest driver. Thank you.
