### ISSUE TITLE
[Eclipse IDE] Add existing project to remote connection results in error from cwctl project validate

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#1801]
When I try to add an existing project I get the following error from cwctl project validate:

2020/01/17 15:20:31 There was a problem retrieving extensions data
2020/01/17 15:20:31 WRITE_FILE_ERROR[203]: Hostname or port for PFE not found.

It looks like the conid is needed on the validate command after all (see https://github.com/eclipse/codewind-eclipse/pull/516).  If I add it back then everything works fine.

**Comment by eharris369** [comment]
Fixed by PR: https://github.com/eclipse/codewind-eclipse/pull/536

**Comment by tetchel** [comment]
https://github.com/eclipse/codewind-vscode/commit/1377be6103252cc829cbd0c520dde8e20bf4d2cc
