### ISSUE TITLE
SVT : Eclipse : Windows : Appsody Kitura Project doesn't start

### ISSUE THREAD

**Issue by mmulholl** [eclipse/codewind#1805]
**Codewind version:**   Codewind tech preview	0.8.0.v202001161954	
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:** Eclipse 2019-09
**Kubernetes cluster:**

**Description:**
Appsody Kitura project do not start on Windows but they do start on Mac. This is the project logs:

Running development environment...
Pulling docker image docker.io/appsody/kitura:0.2
Running command: docker pull docker.io/appsody/kitura:0.2
0.2: Pulling from appsody/kitura
Digest: sha256:f8e2cd1244ddf6703924c629c7bf8d96505edfc5df5847cf2293473e252f85cc
Status: Image is up to date for appsody/kitura:0.2
Running command: docker run --rm -P --name cw-appsodykitura008-dbc7ccd0-3976-11ea-9a21-93ab3d2d0be8 --network codewind_network -v /C/codewind-data/AppsodyKitura008/:/project/user-app -v appsodykitura008-deps:/project/user-app/.build -v appsody-controller-0.3.3:/.appsody -t --entrypoint /.appsody/appsody-controller docker.io/appsody/kitura:0.2 --mode=run
[Container] Running APPSODY_PREP command: if [ -n "$(diff -rq /project/deps /project/user-app/.appsody)" ]; then rm -rf /project/user-app/.appsody && cp -R -p /project/deps /project/user-app/.appsody; fi
[Container] diff: /project/user-app/.appsody: No such file or directory
[Container] Running command:  swift run
[Container] Running command:  swift run
[Container] Wait received error on APPSODY_RUN/DEBUG/TEST signal: interrupt
[Container] [31m[1merror: [0mError Domain=NSCocoaErrorDomain Code=260 "The file doesn’t exist."
[Container] [Warning] Wait Received error starting process of type APPSODY_RUN/DEBUG/TEST_ON_CHANGE while running command: swift run error received was: exit status 1

**Steps to reproduce:**

**Workaround:**

**Comment by makandre** [comment]
`.appsody` is a folder in the project and it's not being synced across to PFE.  Investigating...

**Comment by makandre** [comment]
It appears to be related to https://github.com/eclipse/codewind-installer/pull/317 and associated changes in the IDEs; this is affecting master branch only I believe.

In 317 the project validation part of the `project create` command is split out into a separate `project validate` command.  But I don't see the IDEs calling `project validate` when creating an appsody project.  Without project validation, the `appsody init` command is not called hence the `.appsody` folder is not created.

cc @jcockbain @tetchel @eharris369

**Comment by jcockbain** [comment]
That PR was only made into master branch yes. 

The changes that went into the IDE's to go with it were https://github.com/eclipse/codewind-eclipse/pull/516 and https://github.com/eclipse/codewind-vscode/pull/383.

**Comment by tetchel** [comment]
> In 317 the project validation part of the project create command is split out into a separate project validate command

ok, so we have to run `validate` for appsody after `create` but before `bind`? if there's some extra step to run on appsody creation shouldn't it be run in `create` ?

**Comment by makandre** [comment]
That project validation part (and the part that calls `appsody init`) needs to be run when binding an existing project to Codewind too.  That's why it was previously a separate function in the go code, but ran within the `project create` command.

**Comment by tetchel** [comment]
So we should add back running `appsody init` in the CLI during create/bind

**Comment by makandre** [comment]
Opened https://github.com/eclipse/codewind/issues/1825 specifically for Che case

**Comment by jcockbain** [comment]
This CLI [change](https://github.com/eclipse/codewind-installer/pull/342) for #1892 adds the validate step back into create, and so I think should fix this.

**Comment by makandre** [comment]
@jcockbain I would think that connection ID is required for `validate` (looks to be optional in the PR); as `cwctl` needs to call on PFE `extensions` API to find out whether additional commands, such as `appsody init` for appsody projects, are to be run.

And if `validate` is run as part of `create`, that would make connection ID required on `create` as well.

Are there IDE changes to go along with your changes as well?

**Comment by tetchel** [comment]
Andrew is correct, `validate` and `create` both need to **require** connection ID.

**Comment by jcockbain** [comment]
The reason for leaving it optional is for the local use-case. If no `conid` is given, cwctl will default to calling local PFE. Testing now, creating a project without a `conid` is successful and gets the extensions from PFE as expected.

**Comment by makandre** [comment]
@jcockbain fair enough but I think the previous IDE PRs had removed passing `conid` completely, so that will need to be fixed.

**Comment by jcockbain** [comment]
That's a good point @makandre. There's a PR up for [eclipse](https://github.com/eclipse/codewind-eclipse/pull/548), the same will be needed for vs-code.

**Comment by tetchel** [comment]
We added that parameter back, now we need cwctl to require it

**Comment by makandre** [comment]
Based on what @jcockbain said I think it's ok now as long as `cwctl` accepts the `conid`.  If it's omitted it defaults to the local connection (but it's irrelevant for IDE since it will always pass it)

**Comment by tetchel** [comment]
we have to keep users/team members who call the CLI directly in mind too, though https://github.com/eclipse/codewind/issues/1923

**Comment by maysunfaisal** [comment]
thanks @tetchel, since Appsody or extensions require it, it would have been nice to have a flag for those project types rather than all project types requiring a conn. 

This has broken us on #1923 like posted above

**Comment by jcockbain** [comment]
All projectTypes require a PFE when validating, due to the API calls described in #1923. 

At the moment, in the cases on commands with a conid flag to call an API on a specific PFE, where one isn't given we default to local PFE. If a local PFE isn't up, we output the error seen in #1923 (which I agree could be clearer).

**Comment by tobespc** [comment]
So, is this still an issue ?  Can someone who has been involved in this summarise what the requirement is now please ?

**Comment by tetchel** [comment]
Change `--conid` from an optional parameter to a required one for `cwctl create` and `validate`

**Comment by makandre** [comment]
@tetchel I thought `--conid` being optional is ok, see https://github.com/eclipse/codewind/issues/1805#issuecomment-579801736

**Comment by tobespc** [comment]
moving to verify as I believe (from the comments above) this is now resolved

**Comment by malincoln** [comment]
@mmulholl pls verify and close. Thanks

**Comment by malincoln** [comment]
@mmulholl have you been able to verify this one?

**Comment by mmulholl** [comment]
Fixed
