### ISSUE TITLE
SVT:Che failed to install on ROKS 2nd time with default namespace on IBM Cloud

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#1806]
**Codewind version:**  0.8.0
**OS:** CoreOS

**Che version:** 7.5.1
**IDE extension version:** 0.8.0
**IDE version:** Theia 7.5.1
**Kubernetes cluster:**

OCP 4.2

**Description:**
I installed Codewind with default namespace "Che" using Eclipse Che 7.5.1 version on IBM Cloud using ROKS (OCP 4.3). After uninstalling che from default namespace che then I can no longer install Codewind on default che namespace even though I executed `chectl server:delete` and also deleted `che`. Here is the failure that I am getting into.

```
 ✔ Create Che Cluster eclipse-che in namespace che...done.
  ❯ ✅  Post installation checklist
    ❯ PostgreSQL pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✖ starting
        → ERR_TIMEOUT: Timeout set to pod ready timeout 130000
```
```
oc get pods
NAME                            READY   STATUS             RESTARTS   AGE
che-operator-6c97449579-7d928   1/1     Running            0          20m
postgres-6d46b47766-4ddhf       0/1     CrashLoopBackOff   8          19m
```

```
kubectl logs postgres-6d46b47766-4ddhf
mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied
```

**Steps to reproduce:**

1. Start Codewind workspace from  Eclipse che installed with default namespace `che` on ROKS with OCP 4.3 version.
2. Uninstall Codewind and Eclipse che.
3. Install Codewind again on same default namespace then it fails with above failure. 

**Workaround:** 

The workaround here is installing codewind on other than default namespace.

**Comment by johnmcollier** [comment]
Discussed with Jag on Friday:
- Looks to be an issue with Chectl (confirming w/ IBM Cloud storage team on Monday that it's not an issue on their end)
- Installing in namespaces other than `che` is fine
- Will open an issue on the Che side on Monday after confirming with the IBM Cloud folks

**Comment by micgibso** [comment]
@johnmcollier Does this still need doc for 0.8.0? Are you happy to open PR as you've suggested above? Thx.

**Comment by johnmcollier** [comment]
Doc PR: https://github.com/eclipse/codewind-docs/pull/311

**Comment by micgibso** [comment]
@jagraj Is this complete now?

**Comment by malincoln** [comment]
@johnmcollier has a Che issue been opened yet?

**Comment by johnmcollier** [comment]
@malincoln We've determined it to not be an issue with Chectl, and that our install docs need to be updated for Che. I'll remove the `external dependency` label from this issue and add the docs label to it.

I'll aim to get a docs PR open by this afternoon
