### ISSUE TITLE
Provide users with a link to docs for help with project status problems

### ISSUE THREAD

**Issue by rajivnathan** [eclipse/codewind#1812]
**Description of the enhancement:**

As part of https://github.com/eclipse/codewind/issues/1732 we discussed creating a troubleshooting doc for project status issues (eg. Why is my app stuck in starting state?). It would also be good to include a link to this doc from the IDEs in some cases. (eg. when the project status timeout has exceeded)

May need to consolidate with existing docs. For example, I found this:
https://www.eclipse.org/codewind/mdteclipsetroubleshooting.html#application-stuck-in-starting-state

Issue for the new doc: https://github.com/eclipse/codewind/issues/2117

**Proposed code changes**

This is currently what the timeout dialog looks like in the VSCode extension:
![image](https://user-images.githubusercontent.com/20015929/72941541-39ca1380-3d3f-11ea-95e1-24ff67a31f42.png)

We could have a general property that indicates to the IDEs that they should display a link. The new property could be included in the timeout event or other events.
eg.
```
"linkLabel": "Troubleshooting status"
"link": "https://www.eclipse.org/codewind/troubleshooting.html#checking-the-application-and-build-statuses",
```

The current event is:
```
message: projectStatusChanged
 data: {
  "projectID": "80d46e00-3d68-11ea-a131-75340c3788ad",
  "appStatus": "starting",
  "detailedAppStatus": {
    "severity": "WARN",
    "message": "Timeout: Pinging http://172.22.0.4:8080/health and http://172.22.0.4:8080/. The application is taking longer than expected to start. Please check the application logs for problems and ensure the project's 'healthCheck' setting is correct. Last error message received: Pinging http://172.22.0.4:8080/health and http://172.22.0.4:8080/",
    "notify": true
  }
}
```

An updated event with the `linkLabel` and `link` properties included would look like:
```
message: projectStatusChanged
 data: {
  "projectID": "80d46e00-3d68-11ea-a131-75340c3788ad",
  "appStatus": "starting",
  "detailedAppStatus": {
    "severity": "WARN",
    "message": "Timeout: Pinging http://172.22.0.4:8080/health and http://172.22.0.4:8080/. The application is taking longer than expected to start. Please check the application logs for problems and ensure the project's 'healthCheck' setting is correct. Last error message received: Pinging http://172.22.0.4:8080/health and http://172.22.0.4:8080/",
    "notify": true,
    "linkLabel": "Troubleshoot status",
    "link": "https://www.eclipse.org/codewind/troubleshooting.html#checking-the-application-and-build-statuses"
  }
}
```

**Comment by eharris369** [comment]
The only thing I can think of is that the linkLabel should be translated according to the locale of the machine where the IDE is running. However it does not sound like we are going to translate any time soon. And we could handle this in the future by having the IDEs pass the locale to PFE.

**Comment by lentheivendra** [comment]
I'll take a look at this one for the pfe side

**Comment by rajivnathan** [comment]
@eharris369 PFE has locale settings so when the IDE connects it can set the locale. Not sure whether the locale API is currently exposed but that would be trivial if/when we need it.

**Comment by micgibso** [comment]
Currently considering the following issues, discussing with our Content Strategist, Mel Hopper about the best place to put them, and the best way to surface them. 
- Why is my project stuck in starting state?
- How can I stop notifications about my project not running?

**Comment by elsony** [comment]
After discussing with the IDE team, we think we'll still need a way for the IDE to track if they have displayed the specific notification to the user before or not. Therefore, here is the extra that we need to do:
1. Add a new field, e.g. notificaitonID, to the status message. The notificationID is specific to the instance of the problem. When the app status changes, e.g. from starting to started/stopped, we'll clear that notification.  If the same problem happens again, the new message will be shown with a different notificationID.
2. We'll deprecate the existing boolean "notification" field since it is redundant with the new notificationID
3. IDE will use this new field to decided to prevent the same message to keep showing to the user.

**Comment by eharris369** [comment]
Can the link label be more descriptive like `Application status troubleshooting information` instead of `Troubleshooting status`?

**Comment by lentheivendra** [comment]
> 
> 
> Can the link label be more descriptive like `Application status troubleshooting information` instead of `Troubleshooting status`?

Agreed, will change

**Comment by lentheivendra** [comment]
Some details on implementation discussions for adding notification ID per problem instance:
1) Use current ProjectState app status map in projectStatusController.ts and add a list of notification IDs paired to a "problem ID" (IDs to internally differentiate between different kinds of status problems i.e. ping count limit exceeded during app start, or app went from starting to stopped, etc). Though currently it might be impossible for *both* the current known problems to exist at the same time for a given app state, it could be possible in the future
2) When the app status transitions, the notification IDs are all cleared if any exist
3) For any app status, if a known problem is hit, and a notifcation ID doesn't already exist for that specific problem: then generate a new ID
4) On detailed app status event json, emit all notification IDs as a json array. The IDEs can then cross check these with the IDs they're already tracking to decide if user needs notification or not.
5) For now, keep the the existing 'notify:' boolean in event json?
6) After 'notify:' is removed (post 0.9.0?), if a 'notificationID:' exists in the json then that's like the old 'notify: true', if it doesn't exist then no need for IDE to notify

@rajivnathan @elsony let me know if  I missed something or corrections are needed.
@eharris369 please provide any thoughts , esp on 4), 5) & 6)

**Comment by eharris369** [comment]
I am confused about the array of notification IDs in the detailed app status.  Will there be different messages for each id?  Otherwise, how does the IDE know which id goes with the current message?

**Comment by micgibso** [comment]
@thisguy1 See above for IDE status request

**Comment by lentheivendra** [comment]
@eharris369 I'll talk to @rajivnathan  some more and confirm soon, but  I believe to handle the "multiple problems occurring when app is in same state" case, we can handle it internally, and as far as the events the IDE sees are concerned, it could just be one event per problem, with one notification ID and message/link/etc.

**Comment by elsony** [comment]
@lentheivendra  As discussed, each notification event that we send to the IDE will only has one notification ID associate with it.  The array is only used internally within Turbine to track the unique IDs.  That's just internal implementation.

**Comment by tetchel** [comment]
do we have new doc coming for 0.9 for this? it looks like the link is:
http://codewind-docs.rtp.raleigh.ibm.com:4321/codewind/troubleshooting.html#checking-the-application-and-build-statuses

which has very little info:
![image](https://user-images.githubusercontent.com/8888438/73874014-bd483200-4820-11ea-9082-50ff4d5b4bb1.png)

**Comment by sishida** [comment]
@tetchel Hi, Tim, I just checked our doc pull requests and currently don't see a PR for updating this doc. @micgibso is out of the office for the rest of the week, but please let Jake or I know if we can help with anything! Thank you!

**Comment by tetchel** [comment]
looks like it is https://github.com/eclipse/codewind/issues/1269

**Comment by rajivnathan** [comment]
@sishida @tetchel Yes, that doc was only meant to be linked temporarily until we have the new doc referenced in the description of this issue that should cover troubleshooting of app status in general. @sishida Spoke to Jake during the iterative-dev call and @ssh24 can help out with technical details.

**Comment by j-c-berger** [comment]
@sishida, please assign this issue to me as well, thanks!

**Comment by elsony** [comment]
The remaining iterative dev work is tracked on the PR https://github.com/eclipse/codewind/pull/2042. Once that is in, the remaining work will be on the IDE side to use the new notificationID field.

**Comment by rajivnathan** [comment]
@j-c-berger @sishida can we determine what the link for the new doc will be now so that we can make the change in the code? The doc doesn't need to be done, just a consensus on what the link is going to be.

**Comment by malincoln** [comment]
> The remaining iterative dev work is tracked on the PR #2042. Once that is in, the remaining work will be on the IDE side to use the new notificationID field.

@eharris369 @tetchel  cc: @jopit 
just making sure you're aware of the IDE changes required.

**Comment by j-c-berger** [comment]
@rajivnathan, I propose the link for the new doc be: https://www.eclipse.org/codewind/troubleshooting.html#projects-stuck-in-starting-or-stopped-state

We can update this section of the troubleshooting to include instructions to help users if their project is: 
1)  stuck in starting state
2) they need to stop notifications about my project not running

**Comment by tetchel** [comment]
The new button title looks way too long, I liked the more concise one a lot better 
![image](https://user-images.githubusercontent.com/8888438/74052217-88b2b280-49a7-11ea-98e6-305da97f2914.png)

**Comment by j-c-berger** [comment]
@tetchel, or maybe even `application troubleshooting` or `status troubleshooting`

**Comment by lentheivendra** [comment]
Note https://github.com/eclipse/codewind/issues/1812#issuecomment-581443933

**Comment by tetchel** [comment]
https://github.com/eclipse/codewind-vscode/pull/447

**Comment by eharris369** [comment]
Eclipse IDE PRs:
- **0.9.0**: https://github.com/eclipse/codewind-eclipse/pull/578
- **master**: https://github.com/eclipse/codewind-eclipse/pull/579

**Comment by rajivnathan** [comment]
For 0.9.0 we'll make a change to the existing doc https://www.eclipse.org/codewind/mdteclipsetroubleshooting.html#application-stuck-in-starting-state
PR for that change: https://github.com/eclipse/codewind-docs/pull/353

Post 0.9.0 we'll create a new doc with more general information, see https://github.com/eclipse/codewind/issues/2117

**Comment by tetchel** [comment]
it looks like all the 0.9 work is done so with #2117 open can we close this one?
