### ISSUE TITLE
SVT:[Hybrid]:Codewind CLI failed to install remote codewind successfully using 0.8.0 docs.

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#1814]
**Codewind version:** 0.8.0
**OS:** 

CLI - WIndows
Remote cluster - OCP 4.2 

CLI version 0.8.0

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**
OCP 4.2

**Description:**
Codewind remote install failing to install on my OCP 4.2 cluster. After doing more debugging with @hhellyer and we found the docs are missing the changes we delivered for 0.7.0 release. 

Here are  the issues opened during 0.7.0 release and they have been addressed in the current docs but missing in 0.8.0 release. 

https://github.com/eclipse/codewind/issues/1515
https://github.com/eclipse/codewind/issues/1536

7.0 docs.
https://www.eclipse.org/codewind/remoteconfiguring.html

0.8.0
https://github.com/eclipse/codewind-docs/tree/0.8.0

**Steps to reproduce:**

**Workaround:**

**Comment by malincoln** [comment]
@micgibso @sishida pls review.  Thanks

**Comment by sishida** [comment]
I think that these changes might be a result of the documentation reorganization that the info development team is currently working on. File renaming and moving content is happening. Please see https://github.com/eclipse/codewind-docs/commits/master/docs/_data/docstoc.yml for a record of changes to the table of contents.

I am also going to see if I can find more info about the changes to the specific files that Jag mentioned...

**Comment by sishida** [comment]
For https://www.eclipse.org/codewind/remoteconfiguring.html, both files look the same in both `master` and `0.8.0`:
- master: https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/remote-configuring.md
- 0.8.0: https://github.com/eclipse/codewind-docs/blob/0.8.0/docs/_documentations/remote-configuring.md

**Comment by sishida** [comment]
@jagraj, @micgibso I noticed the `0.8.0` branch has only 4 files with "remote" in the name, but the `master` branch has 8 files with "remote" in the name. Jag, was this part of your concern/question?

Looking at the file history, I notice @markcor11 added remotedeploy-combo.md, remotedeploy-eclipse.md, remotedeploy-single.md, and remotedeploy-vscode.md, which I'm assuming is part of the overall doc restructure. Thanks for all your work on this, Mark!

If any of us has questions or concerns about where information is located--or where it will be located--maybe we can open a group chat or virtual meeting?

**Comment by micgibso** [comment]
@jagraj The 0.8.0 URL you've quoted above (http://9.42.27.84:4321/codewind/remotedeploy-combo.html) isn't 0.8.0, that's our 0.9.0 release.  We've branched already for 0.8.0, Sarah's quoted the 0.8.0 URL above, here it is again for clarity: 
https://github.com/eclipse/codewind-docs/blob/0.8.0/docs/_documentations/remote-configuring.md.

I too have checked and 0.8.0 is identical to Master: https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/remote-configuring.md

#1515 Missing cluster login is in both the above:
https://github.com/eclipse/codewind-docs/blob/0.8.0/docs/_documentations/remote-configuring.md#configuring-other-cloud-deployments Step 3.
and
https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/remote-configuring.md#configuring-other-cloud-deployments Step 3.

#1536 The text for this has been moved on PR https://github.com/eclipse/codewind-docs/pull/280 to:
https://github.com/eclipse/codewind-docs/blob/0.8.0/docs/_documentations/mdt-eclipse-managingprojects.md
and 
https://github.com/eclipse/codewind-docs/blob/0.8.0/docs/_documentations/mdt-vsc-commands-project.md

All present and correct. I'm looking at the 0.9.0 docs later this week, stopship label for 0.8.0 can be removed, let's keep this issue open as a reminder for me to check the new content has these essential steps, have assigned myself.

**Comment by micgibso** [comment]
For 0.9.0, check:
- Step 3, cluster login, exists in new content
- `Open Tekton Dashboard: This option is available to you only if you installed pipelines. Use this option to open the dashboard.` text exists in new content.

**Comment by jagraj** [comment]
@micgibso @sishida @markcor11 
Thanks for clarifying on these files. For 0.8.0, I am going to remove "stopship" label. Once we have all the changes done for 0.9.0 release then I will validate these docs again. 

@micgibso 
We have staging docs for master and it will be nice to have for current release (0.8.0) as well and our team can test these docs.

**Comment by jgwest** [comment]
@jagraj: Those labels are not set on the issue: kind/priority<details>


In response to [this](https://github.com/eclipse/codewind/issues/1814#issuecomment-576664495):
> remove-kind priority
</details>

**Comment by jgwest** [comment]
@jagraj: Command 'remove-priority' requires at least one parameter.<details>


In response to [this](https://github.com/eclipse/codewind/issues/1814#issuecomment-576664951):
> remove-priority
</details>

**Comment by jgwest** [comment]
@jagraj: Those labels are not set on the issue: priority/priority/stopship<details>


In response to [this](https://github.com/eclipse/codewind/issues/1814#issuecomment-576670240):
> remove-priority priority/stopship
</details>

**Comment by micgibso** [comment]
@jagraj See new remote install topics: remotedeploy-combo.html and remotedeploy-single.html

**Comment by malincoln** [comment]
@jagraj pls review updates and provide approval.  Thanks

**Comment by jagraj** [comment]
The latest updates in 0.9.0 docs looks good. Thanks. Closing this now.
