### ISSUE TITLE
Provide more information to IDEs about projects' metrics statuses

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#1815]
The current IDE logic is confusing for when to show the app monitor / perf dashboard options. The original backend design was just for normal projects which Codewind could inspect to see if they had appmetrics installed. Then Appsody was added which Codewind couldn't inspect, and more recently, metrics injection was added. Now, even we are not really clear on when those two features should and should not be enabled, and this caused https://github.com/eclipse/codewind/issues/1804.

We'd like the existing `api/v1/projects/<id>/metrics` endpoint to be replaced by a new endpoint with more information, so the IDEs have enough info to know when the app monitor / perf dashboard will work. It should return an object with the following boolean fields:

1. metrics are installed by user (existing /metrics. Ideally we'd be able to detect this for appsody so we don't have to ping it as introduced in https://github.com/eclipse/codewind/issues/258)
2. metrics-dash is installed by user OR is being hosted in the performance container (as seems to be the case for node and java projects)
3. metrics can be injected by codewind
4. metrics are currently injected by codewind

then, in the IDEs:
If 1 or 4, show perf dashboard
If 2 or 4, show app monitor
if 3 and not 4, show inject metrics
if 3 and 4, show un-inject metrics

Does that make sense, and meet the requirements?

**Comment by tetchel** [comment]
ideally portal would tell us the app monitor URL or have it undefined, but IIRC that's not possible

**Comment by tobespc** [comment]
the dashboard should now all be hosted on the performance dashboard by default, but, you need to remember that the url information can change at any point.  This means you will need to live ping each time to see whether anything has changes.  We could put the logic in the metrics endpoint but that will still need to be queried each time you want to display the dashboard incase that URL has changed ?  Or, we emit an event if it changes and you listen to that to know when to refresh

**Comment by tetchel** [comment]
> we emit an event if it changes and you listen to that to know when to refresh

Sure, you know the URL? and can put it in a `projectChanged` event? That would be perfect

**Comment by tetchel** [comment]
> the dashboard should now all be hosted on the performance dashboard by default 

This applies to all projects, even appsody?

**Comment by hhellyer** [comment]
We should keep in mind that the user can alter their application and add or remove the dashboards themselves. For that reason we probably need to poll the right endpoints for the type of application to see if it's there anyway. (We shouldn't set in stone that there's no monitoring just because our starter template didn't include it.)

**Comment by jopit** [comment]
Portal to investigate further.

**Comment by tobespc** [comment]
After discussions here we are going to go with the following design

Return new data in the project object containing the following information

```
{
    injection: { 
        injectable: boolean,     // Is injection supported for this project type?
        injected: boolean        // If so, what is the current state
    },
    appMonitor : url,            // URL of the monitoring dashboard
    perfcontainer : url          // URL of the performance container
}
```

**Comment by rwalle61** [comment]
so I've nearly added this information to the `/projects` and `/projects/{id}` APIs. I can merge it to master tomorrow, then @eharris369 and @tetchel you can try it out?

**Comment by eharris369** [comment]
When the request to inject metrics returns (`/api/v1/projects/{id}/metrics/inject`) will the project info be fully updated?

**Comment by tetchel** [comment]
IMO it is easier to just add it to the projectChanged event too.

**Comment by rwalle61** [comment]
@eharris369 yes the project info should be fully updated when you receive the 202 response to `/api/v1/projects/{id}/metrics/inject`

**Comment by rwalle61** [comment]
@tetchel ok I will add it to the projectChanged event

**Comment by rwalle61** [comment]
Update

PFE will add these fields to the project object
```
{
    injection: { 
        injectable: boolean,     // Is injection supported for this project?
        injected: boolean        // If so, what is the current state
    },
    appMonitor: {
        dashboardLocation: string, // either 'project' or 'performanceContainer'
        pathToDashboard: string  // e.g. performance/monitor/dashboard/nodejs?theme=dark&projectID=b68c4c80-475d-11ea-9d44-472c50e07b47
    },
    perfContainer : pathToPerformanceContainer,  // e.g. /performance/charts?project=b68c4c80-475d-11ea-9d44-472c50e07b47
}
```

Then, in the IDEs:
If `perfContainer` is not null, show perf dashboard
If `appMonitor.dashboardLocation` is not null, show app monitor by combining the correct host (project or performance container) with the provided `appMonitor.pathToDashboard`
If `injection.injectable` is true but `injection.injected` false, show inject metrics
If `injection.injectable` is true and `injection.injected` true, show inject metrics

**Comment by rwalle61** [comment]
When that PR is in, we should switch any code that uses `injectMetrics`, `metricsAvailable` over to use these fields, then get rid of the obsolete fields. At that point we can also remove the `canMetricsBeInjected` field I introduced in that PR

**Comment by rwalle61** [comment]
btw we discussed naming our 2 dashboard as follows:
- metrics dashboard = app monitor. Hosted either on our performance container, or the user's project (e.g. through appmetrics-dash, javametrics-dash)
![image](https://user-images.githubusercontent.com/18170169/74057218-5a4eca80-49db-11ea-9932-8d0c3e1e106b.png)

- performance dashboard = load test dashboard
![image](https://user-images.githubusercontent.com/18170169/74057306-8ec28680-49db-11ea-9e67-e74a1ac7fd8e.png)

The API above reflects this new naming. If everyone is happy, we should use these terms in all our code (e.g. rename Application Monitor in the IDEs to Metrics Dashboard)

**Comment by malincoln** [comment]
@tobespc when do you expect this fix to be merged?  I was thinking it was merged today?

**Comment by tetchel** [comment]
ok, we'll have to scrape the documentation to make sure all the instances of 'performance dashboard' are renamed

**Comment by tetchel** [comment]
merged portal change into both branches

**Comment by malincoln** [comment]
Toby confirmed this is now done.  Moving to verify.

**Comment by tetchel** [comment]
It's done, we still should open an issue for the appsody openliberty case though
