### ISSUE TITLE
Remote Connection: "Username" appears as if filled

### ISSUE THREAD

**Issue by thisguy-1** [eclipse/codewind#1819]
Should a darker grey before being filled.

<img width="570" alt="Screen Shot 2020-01-20 at 2 28 29 PM" src="https://user-images.githubusercontent.com/52169824/72752887-6dffd180-3b91-11ea-982d-0e5113abcd34.png">

**Proposed solution:** 

@tetchel

**Comment by tetchel** [comment]
It is filled, that's the default username which most users will use

**Comment by thisguy-1** [comment]
But it should be greyed, same as all suggestions. It would be a bit confusing if I didn't want to use the default. It could say something along the lines (in grey) "most users will use 'developer' as default". IDE should look at this - @sishida

**Comment by tetchel** [comment]
ok, i'll change it to be a placeholder

**Comment by jgwest** [comment]
Yah, FWIW I had the same thought when I first used the UI in the screenshot. 

While I'm here, it also _feels_ odd for the password field to contain anything here; eg either grey or white text, but maybe it's just me. I'm not sure I've seen this particular design pattern (greyed-out password) elsewhere...
