### ISSUE TITLE
SVT: [Docs]: Cloud deployment section is a bit out of order in remote deployment doc.

### ISSUE THREAD

**Issue by DavidG1011** [eclipse/codewind#1824]
In the "Configuring other cloud deployments" section of the remote config doc: https://www.eclipse.org/codewind/remoteconfiguring.html#configuring-other-cloud-deployments

Step 3 mentions using `oc` to enable privileged containers/run as root.

These permissions need to be applied prior to running the `cwctl install remote ... ` command from step 2 or the pods will be stuck in a "pending" state during installation, which could lead to confusion.

**Comment by micgibso** [comment]
@DavidG1011 Hi David, Please see https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/remotedeploy-combo.md for the new version of these instructions. 
Have added the `oc` commands required to impart the correct permissions before the `cwctl install remote` commands. Please verify, thx!

**Comment by DavidG1011** [comment]
Hey @micgibso. Looks good to me. Thank you!
