### ISSUE TITLE
Che: appsody kitura project does not run

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#1825]
**Codewind version:** 0.8.0
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**

On Che, appsody kitura projects fail to run with:

```
[Container] Running APPSODY_PREP command: if [ -n "$(diff -rq /project/deps /project/user-app/.appsody)" ]; then rm -rf /project/user-app/.appsody && cp -R -p /project/deps /project/user-app/.appsody; fi
[Container] diff: /project/user-app/.appsody: No such file or directory
[Container] Running command:  swift run
[Container] error: Error Domain=NSCocoaErrorDomain Code=260 "The file doesn’t exist."
[Container] Wait received error on APPSODY_RUN/DEBUG/TEST exit status 1
```

`.appsody` is a folder created during `appsody init`, which runs in the Theia container; it fails because there's no `buildah` command in that container to pull down the stack image.  Previously with other stacks this does not prevent appsody to run the project later on.  The message from `appsody init` also states the project "should still work":

```
Setting up the development environment
Pulling docker image docker.io/appsody/kitura:0.2
Running command: docker pull docker.io/appsody/kitura:0.2
[Warning] Docker image pull failed: exec: "docker": executable file not found in $PATH
[Warning] Could not run docker image ls -q for the image: appsody/kitura:0.2 error: exec: "docker": executable file not found in $PATH Check to make sure docker is available.
[Warning] The stack init script failed: Could not find the image either in docker hub or locally: docker.io/appsody/kitura:0.2
[Warning] Your local IDE may not build properly, but the Appsody container should still work.
[Warning] To try again, resolve the issue then run `appsody init` with no arguments.
Successfully initialized Appsody project with the  stack and the default template.
```

The behaviour for kitura stack is different and we need determine if it is by design.

**Steps to reproduce:**

**Workaround:**

**Comment by makandre** [comment]
https://github.com/eclipse/codewind/issues/1805 is related to this issue but for master branch

**Comment by makandre** [comment]
Opened an issue with appsody https://github.com/appsody/stacks/issues/610

**Comment by malincoln** [comment]
@makandre are you verifying or we need SVT to verify?

**Comment by makandre** [comment]
I can verify it

**Comment by makandre** [comment]
Verified, problem fixed in newer Kitura stack.
