### ISSUE TITLE
Adding version and date to website documentation

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind#1826]
**Description of the enhancement:**
The Codewind team wants to add more screenshots in the instructional documentation on the Codewind.dev website. Concern has been expressed about screenshots going out of date as Codewind continues to change.

**Proposed solution:** 
Some web pages include a statement such as `last updated on <date>`, perhaps at the bottom of the page like a footnote. What if we included a similar statement on our Codewind.dev documentation pages, perhaps mentioning the Codewind version during which the page was last updated? If any screenshots on the website look different from what users see in the latest version of Codewind itself, a date/version indicator could help explain why.

We are currently unsure if a version/date could be automatically generated.

**Comment by travis1111** [comment]
Please assign to me :-)

**Comment by travis1111** [comment]
PR:

https://github.com/eclipse/codewind-docs/pull/343
