### ISSUE TITLE
cwctl has stopped creating the settings file .cw-settings

### ISSUE THREAD

**Issue by maysunfaisal** [eclipse/codewind#1829]
**Codewind version:** latest jan21
**OS:**

**Che version:**
**IDE extension version:** latest jan21
**IDE version:**
**Kubernetes cluster:**

**Description:**
Install Codewind latest as of Jan 21, cwctl does not create the `.cw-settings` file for a project.

Pls confirm if this is regressed on 0.8.0 as well

/area portal

**Comment by maysunfaisal** [comment]
cc @tobespc FYI

**Comment by makandre** [comment]
`.cw-settings` was created as part out project validation, which got split out from the `project create` command in master; this was discovered in another issue as well:

**Comment by tobespc** [comment]
which project type ?  I just created a Nodejs and a Liberty one and they have one

**Comment by maysunfaisal** [comment]
Turbine tests yesterday reported all the project types, I just tried Spring manually before opening this.

**Comment by markcor11** [comment]
Reproduced

**Comment by markcor11** [comment]
I posted a PR for this https://github.com/eclipse/codewind-installer/pull/342 that ran validate after create in order to re-add the .cw-settings

/pipeline Validate

**Comment by jgwest** [comment]
@markcor11: Unable to locate pipeline with name: `Validate`

**Comment by malincoln** [comment]
@maysunfaisal pls verify and close. Thanks
