### ISSUE TITLE
SVT: [Che] IDE presented notifications stuck in the removal process and project files left after deleting multiple projects at the same time

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#1832]
**Codewind version:** 0.8.0
**OS:** Red Hat Enterprise Linux 7 (64 bit)

**Che version:** 7.5.1
**Kubernetes cluster:** OKD/Openshift 

**Description:** IDE presented notifications stuck in the removal process and project files left after deleting multiple projects at the same time. Projects were removed from Codewind, but their files remained in the IDE. 

This problem arose after finding a solution for [eclipse/codewind#1779](https://github.com/eclipse/codewind/issues/1779). Therefore, be sure to include fix for Codewind 0.9.0 when testing.  

*First Scenario:*

<img width="1675" alt="Screen Shot 2020-01-21 at 9 29 07 AM" src="https://user-images.githubusercontent.com/49531960/72815166-385ff480-3c34-11ea-9836-b91c7efa9bf2.png">

<img width="1675" alt="Screen Shot 2020-01-21 at 9 31 04 AM" src="https://user-images.githubusercontent.com/49531960/72815141-31d17d00-3c34-11ea-930d-d0b7d8d39db4.png">

*Second Scenario*

![Screen Shot 2020-01-21 at 12 23 15 PM](https://user-images.githubusercontent.com/49531960/72836188-22652a80-3c5a-11ea-84f8-04dc5728334f.png)

![Screen Shot 2020-01-21 at 12 30 10 PM](https://user-images.githubusercontent.com/49531960/72836198-2729de80-3c5a-11ea-949e-ea7cabe457c4.png)

*Successful notifications were sent from the File Watcher side:*
```
[21/01/20 17:08:31 cw-default-node-jingfu-img-1] [INFO] Successfully deleted 1cd5aa70-3c70-11ea-8aa0-3573d69dd47d
[21/01/20 17:08:31 Turbine] [INFO] Removing project logs directory
[21/01/20 17:08:32 Turbine] [INFO] No dangling images were found.
[21/01/20 17:08:34 Turbine] [INFO] Log directory removed from: /codewind-workspace/.logs/cw-default-node-jingfu-img-1-1cd5aa70-3c70-11ea-8aa0-3573d69dd47d
[21/01/20 17:08:34 Turbine] [INFO] 1cd5aa70-3c70-11ea-8aa0-3573d69dd47d: Emitting event 
 message: projectDeletion
 data: {
  "operationId": "a9e259e50de8243863ae01714281c2ab",
  "projectID": "1cd5aa70-3c70-11ea-8aa0-3573d69dd47d",
  "status": "success"
}

[21/01/20 17:09:03 cw-appsody-eclipse-mp-jingfu-img-1] [INFO] Successfully deleted 09b5e220-3c70-11ea-8aa0-3573d69dd47d
[21/01/20 17:09:03 Turbine] [INFO] Removing project logs directory
[21/01/20 17:09:03 Turbine] [INFO] Log directory removed from: /codewind-workspace/.logs/cw-appsody-eclipse-mp-jingfu-img-1-09b5e220-3c70-11ea-8aa0-3573d69dd47d
[21/01/20 17:09:03 Turbine] [INFO] 09b5e220-3c70-11ea-8aa0-3573d69dd47d: Emitting event 
 message: projectDeletion
 data: {
  "operationId": "80ed017d78642988e79dbb4111b39ec6",
  "projectID": "09b5e220-3c70-11ea-8aa0-3573d69dd47d",
  "status": "success"
}
```

*Projects were removed from `codewind-workspace` and logs were deleted from `.logs`*:

```
[root@sfonseca-okd-codewind ~]# oc exec -it codewind-workspacedeoqia496daptjm6-dcc499cdf-xb977  /bin/bash
[root@codewind-workspacedeoqia496daptjm6-dcc499cdf-xb977 /]# cd codewind-workspace/
[root@codewind-workspacedeoqia496daptjm6-dcc499cdf-xb977 codewind-workspace]# ls -la
total 4
drwxrwxrwx.  8 root root  101 Jan 21 14:30 .
drwxr-xr-x.  1 root root   71 Jan 21 14:23 ..
drwxr-xr-x.  3 root root   45 Jan 20 16:58 .appsody
drwxrwxr-x.  2 root root   55 Jan 20 16:58 .config
drwxrwxr-x.  6 root root  144 Jan 21 14:23 .extensions
drwxr-xr-x.  2 root root   82 Jan 21 14:30 .logs
drwxrwxr-x.  2 root root    6 Jan 21 14:30 .projects
drwxrwxr-x. 24 root root 4096 Jan 21 14:27 cw-temp

[root@codewind-workspacedeoqia496daptjm6-dcc499cdf-xb977 codewind-workspace]# cd .logs
[root@codewind-workspacedeoqia496daptjm6-dcc499cdf-xb977 .logs]# ls -la
total 664
drwxr-xr-x. 2 root root     82 Jan 21 14:30 .
drwxrwxrwx. 8 root root    101 Jan 21 14:30 ..
-rw-r--r--. 1 root root 668424 Jan 21 14:30 Turbine.log
-rw-r--r--. 1 root root   2020 Jan 21 14:23 liberty-app-cache.log
-rw-r--r--. 1 root root   1718 Jan 21 14:23 spring-app-cache.log
```

From https://github.com/eclipse/codewind/issues/1779#issuecomment-576775336, a possible reason can be that IDE may not handle large delete request simultaneously.

**Logs:**
[codewind-workspace6p4anjukf56ew5g2-65f66dcd96-6r4jj.txt](https://github.com/eclipse/codewind/files/4093274/codewind-workspace6p4anjukf56ew5g2-65f66dcd96-6r4jj.txt)

**Steps to reproduce:**
1. Deploy a new workspace for Codewind for Eclipse Che 
2. Create several projects
3. Wait for the projects to successfully built and start
4. Delete projects at the same time 

**Workaround:** 
Manually delete projects using IDE

@jagraj

**Comment by tetchel** [comment]
I have seen this too.

- The projects are actually still in Codewind but have `action: "deleting"` which causes VS Code to ignore them.
- The first project that gets stuck deleting is always an Appsody project. It then blocks up any subsequent delete requests until the Appsody project is deleted by hand.
- A `projectDeletion` event is never emitted by Codewind. The IDE does not delete the files until it receives this event.

**Comment by tetchel** [comment]
I can reproduce this with my appsody tests added here https://github.com/eclipse/codewind-vscode/pull/413

**Comment by GeekArthur** [comment]
From Sujeily's `First Scenario` above, we can see the project `cw-appsody-eclipse-mp-jingfu-img-1` with project ID `09b5e220-3c70-11ea-8aa0-3573d69dd47d` is a danging project where still have project files on IDE side but already deleted on Turbine layer. For that project I can see `projectDeletion` has been emitted in the log.

```
[21/01/20 17:09:03 Turbine] [INFO] 09b5e220-3c70-11ea-8aa0-3573d69dd47d: Emitting event 
 message: projectDeletion
 data: {
  "operationId": "80ed017d78642988e79dbb4111b39ec6",
  "projectID": "09b5e220-3c70-11ea-8aa0-3573d69dd47d",
  "status": "success"
}
```

@tetchel I think that's the `projectDeletion` event you mean? If so think IDE should delete the corresponding project files on IDE side. From Turbine perspective, I don't see any difference between project that is successfully deleted and project that still have project files on IDE side, it goes through all deletion processes, delete project files on Turbine side and emit `projectDeletion` event.

**Comment by tetchel** [comment]
ok, this is a different bug than i described above. i will check it out

**Comment by rajivnathan** [comment]
We're removing the iterative-dev label for now since it doesn't look like we have any actions to take here. Feel free to add it back if that changes.

**Comment by malincoln** [comment]
@tetchel are you continuing to investigate this one?

**Comment by tetchel** [comment]
didn't mean to close, I changed the way deletion is handled and can't reproduce this any more.

**Comment by malincoln** [comment]
@sujeilyfonseca pls verify and close. Thanks

**Comment by sujeilyfonseca** [comment]
I verified this issue with the latest Codewind 0.9.0, and I no longer reproduce this problem.
