### ISSUE TITLE
UI tweaks

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#1834]
- [x] try and use ibm plex sans
    `<link href="https://fonts.googleapis.com/css?family=IBM+Plex+Sans:300,400,600&amp;display=swap" rel="stylesheet">`

Remote Connection page:
- [x] numbered steps
- [ ] bigger margins to match sketch
- [ ] center the main content and have it adjust
- [ ] move cancel/save to be under the Codewind Connection card so it comes before the sources/registry
- [ ] connection label should be editable
- [ ] Remove button icon can appear on a second line (on high-res screens?)

Registries page:
- [x] don't show "at least one registry is needed for codewind projects" if not using codewind source

Project overview page:
- [x] drive letter should be capitalized on windows

**Comment by tetchel** [comment]
@thisguy1

**Comment by tetchel** [comment]
@thisguy-1

**Comment by thisguy-1** [comment]
<img width="1662" alt="Screen Shot 2020-01-28 at 10 59 45 AM" src="https://user-images.githubusercontent.com/52169824/73395939-6685aa00-42ae-11ea-8fe5-25fd8ab9b5d9.png">
Having issues with this :)

**Comment by tetchel** [comment]
added the Remove Connection icon problem to the issue description
