### ISSUE TITLE
SVT:Windows:Open API fails to generate under META-INF folder

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#1842]
**Codewind version:** 0.8.0
**OS:** WIndows

**Che version:**
**IDE extension version:** 0.8.0
**IDE version:** Eclipse 09-2019
**Kubernetes cluster:**

**Description:**
I tried to generate server code in my "open liberty" default project for petstore sample and it is failed to generate openapi.yaml file in META-INF folder.

**Steps to reproduce:**
1. Install 0.8.0 OpenAPI tools
2.Generate "Server" code in root folder.
3. Failed to generate openapi.yaml file under META-INF folder.

**Workaround:**

**Comment by keithchong** [comment]
This will be in 0.9.0.

**Comment by malincoln** [comment]
@keithchong confirming this is still targeted for 0.9.0, dcut this Wednesday.

**Comment by sghung** [comment]
@malincoln assigning to myself since Keith is working on something else now, I am targeting this for Wednesday

**Comment by sghung** [comment]
The reason why this didn't work, was because this PR was never ported to Eclipse. It was made in vscode only. I will port https://github.com/eclipse/codewind-openapi-vscode/pull/80/files to eclipse.

**Comment by sghung** [comment]
Fixed as part of https://github.com/eclipse/codewind-openapi-eclipse/pull/131

**Comment by malincoln** [comment]
@jagraj pls verify and close. Thanks

**Comment by jagraj** [comment]
This has been verified with the latest build and works fine now. Thanks for the fix. Closing this now.
