### ISSUE TITLE
SVT: Application monitor data is missing for Open Liberty projects

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#1844]
**Codewind version:** 0.8.0
**OS:**  Windows

**Che version:** 7.5.1
**IDE extension version:** 0.8.0
**IDE version:** Theia 7.5.1
**Kubernetes cluster:**
OCP 4.2 

**Description:**
Application monitor data is missing for Websphere Liberty, Open Liberty projects from Codewind che and also for Hybrid Codewind. This all works fine from local but fails on che and hybrid. 
I tried injection option too and it does not work. This works fine for spring projects.

Che ;
![image](https://user-images.githubusercontent.com/713849/72936534-5feab600-3d35-11ea-8901-aa2425d04209.png)

Remote ;
![image](https://user-images.githubusercontent.com/713849/72936599-84469280-3d35-11ea-908c-e1b57502d32d.png)

Local;
![image](https://user-images.githubusercontent.com/713849/72936658-a0e2ca80-3d35-11ea-8d9d-bcfcfeb22a8f.png)

**Steps to reproduce:**

1. Install codewind from che or remote codewind.
2. Create WebSphere Liberty , OpenLiberty projects from default templates.
3. Application monitor does not return any data after project is up and running.

**Workaround:**

**Comment by tobespc** [comment]
looks like we are missing a feature from the template, fixing now

**Comment by tobespc** [comment]
this also fails for me on local as well

**Comment by tobespc** [comment]
I've fixed websphere liberty by modifying the template.  However, open liberty requires a different code change to pfe itself.  Open liberty does work in local mode, its only remote and hosted that is broken

**Comment by tobespc** [comment]
@rwalle61 can you pick this up please

**Comment by malincoln** [comment]
@jagraj pls verify and close. I'll reopen and move to verify.

**Comment by jagraj** [comment]
I am trying to verify this problem, but che workspace failed to create and here is the error from the broker.

```
 oc logs workspacebxiock9c67nyynwo.che-plugin-broker
2020/02/03 14:43:03 Broker configuration
2020/02/03 14:43:03   Push endpoint: ws://che-che.apps.extols.os.fyre.ibm.com/api/websocket
2020/02/03 14:43:03   Auth enabled: true
2020/02/03 14:43:03   Runtime ID:
2020/02/03 14:43:03     Workspace: workspacebxiock9c67nyynwo
2020/02/03 14:43:03     Environment:
2020/02/03 14:43:03     OwnerId: e551f8f1-c46f-4a9c-93bc-3b5e7e9ca904
2020/02/03 14:43:04 Fetching plugin meta.yaml from http://plugin-registry-che.apps.extols.os.fyre.ibm.com/v3/plugins/che-incubator/typescript/latest/meta.yaml
2020/02/03 14:43:04 Fetching plugin meta.yaml from http://plugin-registry-che.apps.extols.os.fyre.ibm.com/v3/plugins/redhat/java11/latest/meta.yaml
2020/02/03 14:43:04 Fetching plugin meta.yaml from http://plugin-registry-che.apps.extols.os.fyre.ibm.com/v3/plugins/eclipse/che-machine-exec-plugin/7.5.1/meta.yaml
2020/02/03 14:43:04 Fetching plugin meta.yaml from http://plugin-registry-che.apps.extols.os.fyre.ibm.com/v3/plugins/eclipse/che-theia/latest/meta.yaml
2020/02/03 14:43:04 Unified Che Plugin Broker
2020/02/03 14:43:04 List of plugins and editors to install
- eclipse/codewind-sidecar/latest - Enables iterative development and deployment in Che
- eclipse/codewind-theia/latest - Codewind Extension for Theia
- che-incubator/typescript/latest - Typescript language features
- redhat/java11/latest - Java Linting, Intellisense, formatting, refactoring, Maven/Gradle support and more...
- eclipse/che-machine-exec-plugin/7.5.1 - Che Plug-in with che-machine-exec service to provide creation terminal or tasks for Eclipse CHE workspace containers.
- eclipse/che-theia/latest - Eclipse Theia
2020/02/03 14:43:04 Starting Che plugins and editor processing
2020/02/03 14:43:04 Starting VS Code and Theia plugins processing
2020/02/03 14:43:04 Started processing plugin ''
2020/02/03 14:43:04 Downloading VS Code extension archive 'http://download.eclipse.org/codewind/codewind-vscode/master/latest/codewind-theia.vsix' for plugin '' to '/tmp/vscode-extension-broker286146855/codewind-theia.vsix'
2020/02/03 14:43:04 Downloading VS Code extension for plugin ''
2020/02/03 14:45:03 Copying VS Code plugin ''
2020/02/03 14:45:03 Copying VS Code extension archive from '/tmp/vscode-extension-broker286146855/codewind-theia.vsix' to '/plugins/eclipse.codewind-theia.latest.luzzncmgkj.codewind-theia.vsix' for plugin ''
2020/02/03 14:45:04 Started processing plugin 'che-incubator/typescript/latest'
2020/02/03 14:45:04 Downloading VS Code extension archive 'https://github.com/che-incubator/ms-code.typescript/releases/download/v1.35.1/che-typescript-language-1.35.1.vsix' for plugin 'che-incubator/typescript/latest' to '/tmp/vscode-extension-broker619498586/che-typescript-language-1.35.1.vsix'
2020/02/03 14:45:04 Trying to send event of type 'broker/log' to closed tunnel 'tunnel-1'
```

**Comment by malincoln** [comment]
@tobespc @rwalle61 ^^^

**Comment by tobespc** [comment]
ummm, not sure what we can do ? looks like che is failing to pull all sorts of things

**Comment by jagraj** [comment]
After resolving my workspace issues, I verified this issue. I do see data in Application monitor now. I got into another issue which is related to App Metrics injection failing and load test failed. 
I will open new issue for this problem and close this issue.
