### ISSUE TITLE
SVT:Eclipse:IDE: Open tekton dashboard does not work for Hybrid connection.

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#1845]
**Codewind version:** 0.8.0
**OS:**  Windows

**Che version:** 
**IDE extension version:** 0.8.0
**IDE version:** 2019-09
**Kubernetes cluster:**

**Description:**
Open Tekton dashboard does not work from eclipse plugin but works from VSCode plugin.
When I click on the link and it does not do anything. Also the menu item has to be at the parent level and not for each project. 

**Steps to reproduce:**
1. Install codewind remote.
2. Create project from eclipse.
3. Try to access Tekton dashboard link and nothing happens.

Log ;
[.log](https://github.com/eclipse/codewind/files/4100263/default.log)

**Workaround:**

**Comment by malincoln** [comment]
@jopit @eharris369 pls investigate.  Thanks

**Comment by eharris369** [comment]
0.8.0 PR: https://github.com/eclipse/codewind-eclipse/pull/546
master PR: https://github.com/eclipse/codewind-eclipse/pull/545

**Comment by malincoln** [comment]
Looks like PRs merged, moving to Verify.

**Comment by malincoln** [comment]
@jagraj pls verify.  Thanks

**Comment by jagraj** [comment]
Fix verified, thanks @eharris369 . Closing this now.
