### ISSUE TITLE
cwctl version incorrectly requires a connection id

### ISSUE THREAD

**Issue by stalleyj** [eclipse/codewind#1848]
**Codewind version:**
0.8.0
**OS:**
Mac

**Description:**
I was trying to find out which version of cwctl I had so attempted to use the version command 'cwctl version' - resulting in the following error 
2020/01/22 14:54:25 APPLICATION_ERROR[300]: Required flag "conid" not set. 

The design doc specifies that the connection id is optional, ie should use local when it's not passed.

I also then discovered that cwctl version didn't tell me the version of itself, rather the version of the Codewind service specified.   cwctl -version will tell me the version of cwctl.

The ideal scenario is for cwctl version to tell me the version of itself and the versions of all Codewind services that it knows about.

**Comment by jcockbain** [comment]
The current output, once a connection is setup is: 
``` 
{
	"CwctlVersion": "x.x.dev",
	"PerformanceVersion": "x.x.dev-20200121-203847",
	"GatekeeperVersion": "x.x.dev-20200121-204537",
	"PFEVersion": "x.x.dev-20200121-202951"
}
```

It was written to support remote only. I agree though, it should also work for local versioning, or at the very least, as a quickfix, return a helpful error (i.e `cwctl version is for a remotely deployed Codewind only.`) + update the design docs to match the code. 

This does then return cwctl version, but only if you have a remote connection setup. It should really be outside of that connection object and hence always present, `conid` or not.

As for returning the details of all known connections, it definitely could. All the connectionID's could be read from the user's connections.json, and then used as the parameters for the existing functions. 

The way I see this could looking (with the `--json` flag set) is:

``` 
	{
		cwctlVersion: "x.x.dev"
		"local": {
			"PFEVersion": "x.x.dev-20200121-202951"
			"PerformanceVersion": "x.x.dev-20200121-203847",
		},
		"connections": { 
			<connID>: { 	
				"PerformanceVersion": "x.x.dev-20200121-203847",
				"GatekeeperVersion": "x.x.dev-20200121-204537",
				"PFEVersion": "x.x.dev-20200121-202951"
			},
			<connID2>: {
				"PerformanceVersion": "x.x.dev-20200121-203847",
				"GatekeeperVersion": "x.x.dev-20200121-204537",
				"PFEVersion": "x.x.dev-20200121-202951"
			},
		}
	},
	
``` 

Might be worth keeping track of the progress on the `remote list` command, as this is serving a similar purpose but wrapping the k8s-client to expose cluster information. If we move forwards with Operators this will develop into the `k get codewinds` command described [here](https://github.com/codewind-resources/design-documentation/blob/master/codewindServer/CodewindOperator.md#deploying-a-new-remote-codewind-deployment).

**Comment by james-wallis** [comment]
I'm going to change the way that `cwctl version` works by making the `--conid` optional like others and defaulting to `local` so by default you'll get:
```
❯ cwctl version                                                                                ⎈ jamesw0001/exact-mongrel-icp-mst-9-20-195-90-nip-io:7443/my-rhel-icp-admin/jamesw0001
{
	"CwctlVersion": "x.x.dev",
	"PerformanceVersion": "x.x.dev-20200129-103123",
	"PFEVersion": "latest-20200129-102849"
}
```
which is the locally running Codewind (so no Gatekeeper).

I'll also add a `cwctl version --all` or something similar which will output all of all of the connections that exist.

**Comment by james-wallis** [comment]
PR raised: https://github.com/eclipse/codewind-installer/pull/351/

**Comment by james-wallis** [comment]
/close
PR has been accepted so closing this issue.
