### ISSUE TITLE
Single occurrence of config topic

### ISSUE THREAD

**Issue by micgibso** [eclipse/codewind#1850]
From Rajiv:
I noticed the contents for these two docs are out of sync:
https://www.eclipse.org/codewind/mdteclipsemanagingprojects.html#project-settings
https://www.eclipse.org/codewind/mdt-vsc-commands-project.html#configuring-project-settings
I think configuring project settings should probably just be a single file to prevent them getting out of sync and VSCode, Eclipse and Che can all have links to that doc in the navigation.

**Comment by j-c-berger** [comment]
@micgibso, feel free to assign me, thanks.
