### ISSUE TITLE
Codewind (VS Code) build/disable/enable buttons look disabled

### ISSUE THREAD

**Issue by travis1111** [eclipse/codewind#1852]
**Codewind version:**
0.7

**OS:**
Mac

**Description:**
This is what it looks like in a white theme:

![image](https://user-images.githubusercontent.com/35569780/72994465-26618b80-3dc5-11ea-81b4-dc752a7b8ede.png)

This is how it looks in a dark theme:

![image](https://user-images.githubusercontent.com/35569780/72994518-3d07e280-3dc5-11ea-8ccc-3165855df2c1.png)

In both themes, Build, Disable/Enable button look disabled, Remove project button looks good.

Can we change the font color to white for these buttons, just like what we have for Remove project button?

**Comment by tetchel** [comment]
ouch, I don't know how I missed this one

**Comment by travis1111** [comment]
Thanks for fixing it!
