### ISSUE TITLE
Run all tests on Jenkins regardless of whether the previous failed (and report failures)

### ISSUE THREAD

**Issue by james-wallis** [eclipse/codewind#1854]
**Description of the enhancement:**

Jenkins runs each test in stages which at the moment are:
1. Portal unit tests
2. Turbine unit tests
3. Docker build
4. API Tests

If a failure occurs in the Portal unit tests the build will exit without running the other tests.

It would be an improvement to this process if we could run all the tests and then report which ones failed.

For example if we have errors in Portal unit and API tests we'd be able to identify that in a single Jenkins run rather than fixing the unit test and then discovering the API test failure.

**Proposed solution:** 

From my brief research Jenkins has ways to have a `try/catch` feature so we could run each test, catch any errors and report them by failing the build.

https://stackoverflow.com/questions/36852310/show-a-jenkins-pipeline-stage-as-failed-without-failing-the-whole-job

```
catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
    sh "exit 1"
}
```

**Comment by jgwest** [comment]
@james-wallis Think that only works if one is using a scripted pipeline, whereas we are using declarative pipelines.
