### ISSUE TITLE
When project is disabled, application information still shows app information

### ISSUE THREAD

**Issue by travis1111** [eclipse/codewind#1855]
**Codewind version:**
0.7

**OS:**
Mac

**Description:**
When the project is disabled, the application information are not applicable anymore.  Maybe we should display `Not available`?

**Steps to reproduce:**

Create any project, then disable it.

![image](https://user-images.githubusercontent.com/35569780/73000003-3a5dbb00-3dce-11ea-870b-3405a9f4534f.png)

**Workaround:**

**Comment by tetchel** [comment]
hmm. i think it used to clear that info, but maybe it changed. i will investigate
