### ISSUE TITLE
SVT : Eclipse : Pop up mania! and rebuild blocked.

### ISSUE THREAD

**Issue by mmulholl** [eclipse/codewind#1856]
**Codewind version:**  Codewind tech preview	0.8.0.v202001202137	
**OS:** MAC

**Che version:**
**IDE extension version:** 
**IDE version:** Eclipse jee 2019-09
**Kubernetes cluster:**

**Description:**
That pop-up to say a project is having trouble starting which was discussed here : https://github.com/eclipse/codewind/issues/1732 often appears when starting an open liberty project. Once the pop-up has appeared I observed this behavior:

1. Hit refresh on the local tree or the project and the pop-up re-appears immediately, no matter how long ago the popup was closed.
2. Hit rebuild on the project and you get 5-6 simultaneous instances of the pop-up and rebuild does not start.

**Steps to reproduce:**
Create a bunch of projects, especially the slow ones, stop and start codewind, odds are you will see the popup - once you have try rebuilding the project it appeared for.

**Workaround:** 

Kill all the pop-ups and be patient - the project does start in the end.

**Comment by malincoln** [comment]
@elsony @rajivnathan can you investigate this?  See last comments in 1732 for reference.  Thanks

**Comment by eharris369** [comment]
The same thing happens in VSCode.  I could not find a way to refresh a project but if I did a build the timeout message flashed about 6 times. 

I am not sure when to put out this message and when not to since it stays in the project info I guess until the app status changes to something else?

**Comment by eharris369** [comment]
@rajivnathan I think the notify flag can only be set to true when the first projectStatusChanged event is sent after the problem occurs and then after that it must be set to false so that we don't pop up the dialogs again.  We still want the message in there because at least for Eclipse if the user selects the project, the message shows in the Eclipse status bar.

**Comment by yangcao77** [comment]
The message is never saved in projectInfo, and the notify flag is never saved.
Turbine only emit the event when it needs to be sent, and only emit once. 

I'm able to reproduce this issue with the first scenario in the description. after the pop-up showed up -> close the message -> click refresh. I'm able to see the message appears again. 
However, in the pfe log, I only saw Turbine emitted the message once, which is when the problem occurs. 
So I think it's because portal have the message in the project .inf file, and ide checks the file to get the project status, which results in it re-appears.

**Comment by yangcao77** [comment]
Also, when manually hit rebuild, Turbine emit events for `buildStatus`. But since the appStatus is saved in project .inf file,  it would send previous `appStatus` saved in the inf file to ide. 
```
      let updatedProject = await this.user.projectList.updateProject(projectUpdate);
      // remove fields which are not required by the UI
      const { logStreams, ...projectInfoForUI } = updatedProject
      this.user.uiSocket.emit(event, { ...results, ...projectInfoForUI })
```

**Comment by yangcao77** [comment]
Suggestion:
Maybe before the for loop, check if the `currentProject` contains key `detailedAppStatus`, and `currentProject["detailedAppStatus"]["notify"] == true` 
If it is, set it to false.  `currentProject["detailedAppStatus"]["notify"] = false` 
https://github.com/eclipse/codewind/blob/21860767fc22b580fb04e254c205a864e718ec41/src/pfe/portal/modules/ProjectList.js#L100-L103

On refresh, I would assume no update to the .inf file, so this suggestion won't work for the refresh case.  So might need ide to handle the refresh case.

**Comment by mmulholl** [comment]
I would expect, once I hit the OK button on the pop-up the timer would be restarted.

**Comment by yangcao77** [comment]
Turbine restarts the timer if the project rebuilds/ the timeout setting has been changed. 

As I mentioned above, this issue has nothing to do with the timer, Turbine only sends out the event once. 
It's portal caches the message in the project.inf file, and sends the message to IDE when it shouldn't be.

**Comment by jgwest** [comment]
@yangcao77: Those labels are not set on the issue: area/iterative-dev<details>


In response to [this](https://github.com/eclipse/codewind/issues/1856#issuecomment-579388985):
> remove-area iterative-dev
</details>

**Comment by stalleyj** [comment]
Removal of detailedAppStatus will be fixed when https://github.com/eclipse/codewind/pull/1941 lands

**Comment by tetchel** [comment]
omitting the detailed app status from the inf file will not affect this behaviour because it will still be saved in RAM

**Comment by tetchel** [comment]
in #1812 we introduced the notification ID which will stop the duplicate pop ups

The detailed app status **should** still be stored in the inf file so that it remains if we restart the IDE

@stalleyj can you add it back?

**Comment by malincoln** [comment]
@stalleyj just confirming this is ready to be verified?

**Comment by stalleyj** [comment]
@tetchel Sorry I missed your comment, I don't think we can persist the detailed app status as wouldn't that be inaccurate if Codewind stops and starts ?

**Comment by tetchel** [comment]
the detailed app status this was fixed with #2140

**Comment by tetchel** [comment]
issue is ready for verification

**Comment by malincoln** [comment]
@mmulholl pls verify and close. Thanks

**Comment by malincoln** [comment]
@mmulholl have you been able to verify this one?

**Comment by tobespc** [comment]
closing as fixed
