### ISSUE TITLE
Codewind (VS code) auto builds project when project is enabled even auto build is off

### ISSUE THREAD

**Issue by travis1111** [eclipse/codewind#1857]
**Codewind version:**
0.7
**OS:**
Mac

**Description:**
If auto build is off, when enabling the project the build should not start.

**Steps to reproduce:**
Any project, uncheck the `auto build` checkbox, then disable the project, after project is disabled, enable it, auto build will start.

![Video-2020-01-23 10 52 36](https://user-images.githubusercontent.com/35569780/73001351-506c7b00-3dd0-11ea-97fe-73373e376180.gif)

**Workaround:**

**Comment by tetchel** [comment]
I think this is the intended behaviour, to build the project **once** after re-enable even if auto-build is off. If you make a code change, does it auto-build?

**Comment by travis1111** [comment]
It does.

I made a change to the source code, saved it, and this is what happened:

![image](https://user-images.githubusercontent.com/35569780/73002362-eb198980-3dd1-11ea-820f-05335378b2b4.png)

**Comment by yangcao77** [comment]
I am able to reproduce the issue. 
Suspect this is an issue with portal. When the project is re-enabled, portal fails to send the `autoBuild` setting to Turbine. 

Checked portal's project.inf file, the `autoBuild` setting is false. 
```
[root@ae32bf6aec86 .projects]# cat 2c979760-3c94-11ea-b840-41a29a962a21.inf 
{
  "projectID": "2c979760-3c94-11ea-b840-41a29a962a21",
  "name": "swift123",
  "codewindVersion": "latest",
  "language": "swift",
  "creationTime": 1580243867561,
  "contextRoot": "/hi",
  "locOnDisk": "/Users/stephanie/Documents/microclimate/swift123",
  "pathToMonitor": "/Users/stephanie/Documents/microclimate/swift123",
  "host": "172.24.0.4",
  "ports": {
    "exposedPort": "32847",
    "internalPort": "8080"
  },
  "workspace": "/codewind-workspace/",
  "directory": "swift123",
  "infLockFlag": true,
  "loadTestPath": "/codewind-workspace/swift123/load-test",
  "projectType": "swift",
  "buildLogPath": "/codewind-workspace/.logs/swift123-2c979760-3c94-11ea-b840-41a29a962a21/docker.build.log",
  "logStreams": {},
  "state": "open",
  "autoBuild": false,
```

But in Turbine's projectInfo, it's still true
```
[root@ae32bf6aec86 2c979760-3c94-11ea-b840-41a29a962a21]# cat 2c979760-3c94-11ea-b840-41a29a962a21.json 
{"projectID":"2c979760-3c94-11ea-b840-41a29a962a21","projectType":"swift","location":"/codewind-workspace/swift123","autoBuildEnabled":true,
```

**Comment by yangcao77** [comment]
The fix is in PR: https://github.com/eclipse/codewind/pull/1912
/pipleline Review/QA

**Comment by rajivnathan** [comment]
@travis1111 can you please verify? The behaviour should be to build the project once after re-enable even if auto-build is off. But if you make a code change it should not trigger further builds.

**Comment by travis1111** [comment]
Thanks I will verify it shortly

**Comment by travis1111** [comment]
Verified.

I downloaded the latest codewind dev build, installed it on my vscode, turn off the autobuild, if I disable it and re-enable it, it builds automatically, this is as design I assume.  Once this auto build is off, codewind does NOT auto build my project after I made changes to the code.  The problem is fixed.  Thanks
