### ISSUE TITLE
Turbine Functional Test for removeImagePushRegistry

### ISSUE THREAD

**Issue by maysunfaisal** [eclipse/codewind#1858]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description of the enhancement:**

Write functional test for new index.ts function as per https://github.com/eclipse/codewind/pull/1846

**Proposed solution:**

**Comment by jgwest** [comment]
@ssh24: Unable to locate pipeline with name: `in-progress`
