### ISSUE TITLE
POST /repositories should validate URLs are reachable and point to template repo index files

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#186]
See the discussion starting at https://github.com/eclipse/codewind/pull/183#issuecomment-520833427

**Comment by tetchel** [comment]
tangentially related, I would the duplicate URL error message to be a little more user-friendly

Currently:
```
https://raw.githubusercontent.com/tetchel/codewind-templates/master/devfiles/index.json is not a unique URL. Repository URLs must be unique
```

How about just:
```
https://raw.githubusercontent.com/tetchel/codewind-templates/master/devfiles/index.json is already a template repository.
```

**Comment by rwalle61** [comment]
sure, I can pick this up

**Comment by rwalle61** [comment]
I've done the work for this, but an earlier templates PR has to be merged first: https://github.com/eclipse/codewind/pull/260. And we've held off merging that while the Jenkins tests aren't running.

So fyi the lack of Jenkins tests is blocking both PRs (unless we merge them anyway)

**Comment by tetchel** [comment]
I don't know if the tests are coming back anytime soon, but would like this change in, can you ask joseph for the status of adding back the tests?
