### ISSUE TITLE
Add overview to Dockerhub

### ISSUE THREAD

**Issue by james-wallis** [eclipse/codewind#1871]
The Docker images we host on Dockerhub don't have an overview so its not at all clear what they're for. 
I'd have thought at least we'd have a link to the Codewind website and a brief overview of what Codewind is?
This is especially the case when Googling `docker codewind` which a potential user may end up doing - they'll likely click onto Dockerhub and see no information about Codewind.

Edit: Complete list of eclipse codewind URLs: 
https://hub.docker.com/r/eclipse/codewind-keycloak-amd64
https://hub.docker.com/r/eclipse/codewind-pfe-amd64
https://hub.docker.com/r/eclipse/codewind-performance-amd64
https://hub.docker.com/r/eclipse/codewind-che-sidecar
https://hub.docker.com/r/eclipse/codewind-initialize-amd64
https://hub.docker.com/r/eclipse/codewind-gatekeeper-amd64
https://hub.docker.com/r/eclipse/codewind-java-profiler-language-server
https://hub.docker.com/r/eclipse/codewind-java-project-cache

**Comment by james-wallis** [comment]
Actually the old initialize image does have an overview, not sure why the others don't.
https://hub.docker.com/r/ibmcom/codewind-initialize-amd64

**Comment by james-wallis** [comment]
Also the `ibmcom` images have the overview

https://hub.docker.com/r/ibmcom/codewind-pfe-amd64
https://hub.docker.com/r/ibmcom/codewind-performance-amd64
https://hub.docker.com/r/ibmcom/codewind-che-sidecar

**Comment by johnmcollier** [comment]
IIRC from the last time we discussed this, the Eclipse webmaster would need to add the descriptions, so I think we'll need to reach out to them on the Eclipse bugzilla to get this done

@josephca is that correct?

**Comment by jgwest** [comment]
Bug was missing area tags, so I took a guess at who should see it...

**Comment by josephca** [comment]
As a committer, I don't have the permission to update the overview (a.k.a. readme) section of 'eclipse/codewind*' docker images. I had a quick chat with @james-wallis and he agreed to collect all the overviews of the 'eclipse/codewind*' docker images and open a Bugzilla bug to get them updated altogether.

**Comment by josephca** [comment]
@james-wallis Please make sure to handle the following missing from the initial list. Thanks, 
https://hub.docker.com/r/eclipse/codewind-java-profiler-language-server
https://hub.docker.com/r/eclipse/codewind-java-project-cache

**Comment by james-wallis** [comment]
/assign 
As @josephca we've spoken I'll create a bugzilla bug tomorrow after going over the overview's with @tobespc.

**Comment by james-wallis** [comment]
![Codewind logo](https://www.eclipse.org/codewind/images/header-logo.svg)

This image is required for Codewind. Codewind provides a development environment that simplifies and enhances development in containers by extending industry standard IDEs with features to write, debug, and deploy cloud-native applications.

## Getting started 
Get started with Codewind at the [Codewind website](https://www.eclipse.org/codewind/).

### Quick links

* **Where to get help:** https://mattermost.eclipse.org/eclipse/channels/eclipse-codewind

* **Where to report issues:** https://github.com/eclipse/codewind/issues

* **Contributing to Codewind:** https://wiki.eclipse.org/Codewind_GitHub_Workflows

## Versioning 
Codewind versions are listed according to version followed by release number and then fix number. For example, in 0.2.0, 0 indicates the version (technology preview), 2 indicates the second release of the technology preview, and 0 indicates that it does not include any fixes. Versions that indicate only two numbers, such as 0.2, include all fixes.

## License 
See the license at [Eclipse Public License - v 2.0](https://www.eclipse.org/legal/epl-2.0/).

**Comment by james-wallis** [comment]
I've opened an issue on Bugzilla to make the readme as above: https://bugs.eclipse.org/bugs/show_bug.cgi?id=559867 

I'll also open another issue for the docs teams specifically so that they can give the overview a work over in due course.

**Comment by james-wallis** [comment]
The Eclipse bug has been closed and the readme's added.
