### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#1875]
Codewind version: master `f60f0cff5c83e9084d55426987879f97851f6272`

I see this throughout my PFE log:
```
[24/01/20 17:54:43 /portal/modules/Project.js] [ERROR] TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at stringify (/portal/node_modules/jsonfile/index.js:86:18)
    at Object.writeFile (/portal/node_modules/jsonfile/index.js:101:11)
    at Promise (/portal/node_modules/universalify/index.js:13:12)
    at new Promise (<anonymous>)
    at Object.writeFile (/portal/node_modules/universalify/index.js:7:14)
    at Project.writeInformationFile (/portal/modules/Project.js:266:16)
```

Looks like something in the structure being written to the inf has a circular reference and can't be stringified. This probably means the inf update fails, so the data stored may be out-of-date.

**Comment by mattcolegate** [comment]
Recreation: take any running project in the IDE and click 'Show all logs'. Subsequent changes that cause the project.inf file to be written to (e.g. a small code change) will have the OP error in the PFE logs.

**Comment by mattcolegate** [comment]
I've raised https://github.com/eclipse/codewind/pull/1925 which fixes the issue by ensuring the offending object never gets written out to project.inf - I've stated my reasoning as to why that was the original intention in the PR. I'd like IDE people to comment on how they're using that part of the project object to make doubly sure that not having it in the project.inf won't break anything.

**Comment by tetchel** [comment]
We are not using `logStreams` directly but this may have an effect on the /logs api which we do use

**Comment by mattcolegate** [comment]
FYI `logStreams` will still exist in the in-memory Project object, it's just not being written out to project.inf and so it's values won't be preserved over PFE restarts.

**Comment by tetchel** [comment]
makes sense to me, afaik all the log streams are turned off when pfe restarts anyway

**Comment by stalleyj** [comment]
Will be fixed when https://github.com/eclipse/codewind/pull/1941 lands.

**Comment by mattcolegate** [comment]
@tetchel PR has landed so this issue is ready for verification please
