### ISSUE TITLE
Debugger disconnects from restarting Spring project because the app stops briefly

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#1877]
Spring projects are misbehaving when restarting into debug mode. When restarting a new project into Debug mode:
1. App state goes stopping -> stopped -> Starting - Debug
2. Restart result success event is emitted
3. Debugger connects (all is ok so far)
4. App goes into Stopping state for some reason
5. Debugger disconnects
6. App starts building for some reason
7. The build finishes and the project goes Starting - Debug -> Started
8. If I attach the debugger now, it works

Things I noticed in the PFE logs:
The line `[24/01/20 17:54:47 sprung] [INFO] Project start for restart was successful` comes way too early (the app is still 'stopped' at this time).
There's this output just before it goes unexpectedly into Stopping, it may be syncing some file that changed on restart, which causes the build.
```
[24/01/20 17:54:48 sprung] [INFO] pingInTransitApplications: Application state error message: Failed to get application status: connect ECONNREFUSED 172.19.0.4:8080
[24/01/20 17:54:59 /portal/routes/projects/remoteBind.route.js] [INFO] Project sprung syncing with build container, projectRoot is /root/app
[24/01/20 17:54:59 FileWatcher.js] [INFO] 0eff2d40-3ed2-11ea-a49c-8dbc3f207517 update start time: 1579888499461
[24/01/20 17:54:59 /portal/routes/projects/remoteBind.route.js] [INFO] Total time to sync project sprung to build container is 0.562 seconds
[24/01/20 17:54:59 sprung] [INFO] Updating container for spring project /codewind-workspace/sprung
```

Also likely related, if I restart the project into Debug mode when it's already Debugging, the restart result event comes almost immediately, which causes the debugger to attach way too early, and then it immediately hangs up as the app stops.

[spring-debug-restart.txt](https://github.com/eclipse/codewind/files/4110022/spring-debug-restart.txt)

Microprofile seems fine

**Comment by tetchel** [comment]
@eharris369

**Comment by eharris369** [comment]
I do not see this behaviour in Eclipse.  It restarts in debug mode and stays in debugging state with the debugger connected.  If I restart in debug mode from debug mode it is fine as well.

**Comment by eharris369** [comment]
I did hit one problem. The project is in debug mode and the debugger is attached. If I modify a file and a build is triggered, it flips states so many times that the debugger does not always reattach.

**Comment by yangcao77** [comment]
When does IDE consider the application restart successfully?

The message `[24/01/20 17:54:47 sprung] [INFO] Project start for restart was successful`
or even this socket event. Only means it successfully triggered the restart process. 
```
[24/01/20 17:54:47 sprung] [INFO] Emitting event 
 message: projectRestartResult
 data: {
  "operationId": "92799427c259370b4de9eac8585e31c4",
  "projectID": "0eff2d40-3ed2-11ea-a49c-8dbc3f207517",
  "status": "success",
  "startMode": "debugNoInit",
  "ports": {
    "exposedPort": "32857",
    "internalPort": "8080",
    "exposedDebugPort": "32858",
    "internalDebugPort": "7777"
  },
  "containerId": "7c34f54156ebf82eefdf71342a6cb00ac9497978be9696b35b6890768657d03d"
}
```

The project is only considered as successfully restarted when you receive the `started` event.

**Comment by tetchel** [comment]
> The project is only considered as successfully restarted when you receive the started event.

This doesn't work for Microprofile because the project won't go into Started state until the debugger attaches. The `projectRestartResult` event has always been taken to mean that the project is ready to be debugged.

**Comment by yangcao77** [comment]
I saw in the log
```
[24/01/20 17:54:59 sprung] [INFO] Detected other file changes, Codewind will build the project
[24/01/20 17:54:59 sprung] [INFO] File change detected. Project will re-build.
```

Looks like some file changes got detected and triggers an rebuilt. 
I will add some log message & try to reproduce to see what files are changed.

**Comment by tetchel** [comment]
It occurred to me that `.vscode/launch.json` would have been modified during the debug-restart which may have been what triggered the app restart, so this may have been fixed by https://github.com/eclipse/codewind/issues/2072

I will see if it works now

**Comment by malincoln** [comment]
@tetchel can this be closed now?  Does anyone else need to verify?

**Comment by tetchel** [comment]
I have to verify it but can't right now because of a problem with my vs code environment, working on it.

**Comment by tetchel** [comment]
indeed it is fixed
