### ISSUE TITLE
cwctl connections add fails with non user friendly error message

### ISSUE THREAD

**Issue by stalleyj** [eclipse/codewind#1892]
**Codewind version:**
0.8.0
**OS:**
Mac

**Description:**
Unhelpful error message given when the wrong url is used to create a connection, "invalid character '<' looking for beginning of value"

**Steps to reproduce:**
Using VSCode, click the icon to create a new Codewind Connection and enter an incorrect url, add username/password and then save. 

Can also be reproduced by directly calling - 
./cwctl --insecure --loglevel trace connections add --label mykube --url https://github.com/eclipse/codewind/issues --username developer

This should return an error indicating that a Codewind Gatekeeper ingress could not be found at the specified url.

**Comment by markcor11** [comment]
Made error message friendly : 

```
$ cwctl connections add \
--label somename \
--url https://www.ibm.com \
--username developer 

ERRO[0001] Bad response received. The URL provided https://www.ibm.com should point to the Codewind Gatekeeper service. Check its route /api/v1/gatekeeper/environment returns valid JSON 
```

with the --json flag : 

```json
{"error":"con_environment","error_description":"Bad response received. The URL provided https://www.ibm.com should point to the Codewind Gatekeeper service. Check its route /api/v1/gatekeeper/environment returns valid JSON"}
```

with --loglevel trace an additional line with root cause :

```
TRAC[0001] Unable to parse response from URL. Bad JSON received: invalid character '<' looking for beginning of value 
```

**Comment by markcor11** [comment]
PR #349 landed 

/pipeline Verify

**Comment by stalleyj** [comment]
Verified that a sensible error message is now returned when the user get's the URL wrong.
