### ISSUE TITLE
Docs animation enhancements

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind#1895]
1️⃣ Brainstorm:
- Adding animation to documentation
- Adding interactivity to documentation
- Examples to refer to include Open Liberty interactive guides and OpenShift documentation.

2️⃣ Implementation/schedule: to be determined.

**Comment by micgibso** [comment]
See https://github.com/eclipse/codewind/issues/1037 for News pages.

**Comment by micgibso** [comment]
The diagrams that Mel and Sarah showed in yesterday's Playback is a good example of the documentation and website improvements that we are aiming for so when these are ready we can close this out.

**Comment by bsbyrd1** [comment]
Exactly! For example, we can animate the diagrams so that arrows are animated to show movement from one widget to another; for example, movement from local to Cloud.
