### ISSUE TITLE
Dockerhub "namespace" note is not in the Dockerhub section

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#1906]
![image](https://user-images.githubusercontent.com/8888438/73302231-44bef100-41e2-11ea-86f6-7ffae61e80ad.png)

Why is it part of the OpenShift section? Shouldn't it be up above?

**Comment by sishida** [comment]
Link to file that needs editing: https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/image-registry-credentials.md

**Comment by tetchel** [comment]
also, instead of "password or token access" it should say "password or access token".

**Comment by sishida** [comment]
@tetchel Hi, Tim, This file is actually part of our restructuring. I addressed your changes in this PR: https://github.com/eclipse/codewind-docs/pull/310. I already took care of the Docker Hub note in the initial commit, but I made a new commit to take care of the access token corrections.

**Comment by sishida** [comment]
Link to updated file on site: https://www.eclipse.org/codewind/mdt-che-setupregistries.html Closing this issue.
