### ISSUE TITLE
SVT: [VS Code] New version required for VS Code must be 1.41 or later

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#1913]
**Codewind version:** Latest 
**OS:** Mac/Windows/Linux

**IDE extension version:** 0.9.0
**IDE version:** Code 1.39.2

**Description:** Our current documentation indicates that the minimum required version for VS Code is "1.38 or later". However, for the latest version (0.9.0), we no longer support Codewind 1.39.2 or an earlier version. If users continue to use VS Code 1.39.2 and try to install Codewind, they will not be able to install it, since the dialog block to click install will never appear.

<img width="1534" alt="Screen Shot 2020-01-28 at 5 01 57 PM" src="https://user-images.githubusercontent.com/49531960/73309320-029cac00-41f0-11ea-916d-4fa5c1687387.png">

@DavidG1011
@jagraj

**Comment by tetchel** [comment]
The engine version required is 1.38 https://github.com/eclipse/codewind-vscode/blob/master/dev/package.json#L8 so I'm not convinced this is a problem with your VS Code version.

The prompt to install doesn't appear until you turn on the local connection, since the installation is not required if you are only using remote connections. This is new behaviour since 0.7.0. Might that be what you're seeing here?

**Comment by sujeilyfonseca** [comment]
The prompt to install doesn't appear even if you turn on the local connection. First, I saw the problem with the automation framework, since my tests were failing because it couldn't get the dialog block to install Codewind. I got another 0.8.0 plugin again, and it worked as expected. Then, I downloaded the latest version for the code-server (1.41.1), and the latest Codewind worked. Therefore, I proceeded to reproduce the scenario by downloading a VS Code 1.39.2 on my machines. I couldn't install Codewind on that version of VS Code. A user cannot obtain the dialog block using the radio button or by right-clicking on the local tree to click on "Start Local Codewind". I asked @DavidG1011 to reproduce the problem and he saw the same behavior. If the minimum engine version is 1.38, then this is a bug with Codewind for VS Code (1.39.2).

**Comment by tetchel** [comment]
I don't have a clue what in that code path could be affected by the VS Code version, but if you're sure of this we can increase the required version to 1.40 to make sure users don't encounter this.

**Comment by tetchel** [comment]
can you provide logs from the failing scenario?

**Comment by sujeilyfonseca** [comment]
![Screen Shot 2020-01-29 at 9 28 31 AM](https://user-images.githubusercontent.com/49531960/73365295-0d038800-427a-11ea-8268-6638656d9ac6.png)


```
[Extension Host] [INFO: 09:18:27.848 StartCodewindCmd.js:36]: Connect Local Codewind Cmd
console.ts:137 [Extension Host] [INFO: 09:18:27.849 CLIWrapper.js:130]: Running CLI command: cwctl --json --insecure status
console.ts:137 [Extension Host] [DBUG: 09:18:27.895 CLIWrapper.js.on():193]: Successfully ran CLI command cwctl --json --insecure status, Output was:
{"status":"uninstalled"}
```

[codewind.log](https://github.com/eclipse/codewind/files/4128531/codewind.log)

**Comment by tetchel** [comment]
hmm... I think we can safely say this is because of the extension version, then... 😵

**Comment by tetchel** [comment]
Docs, pls update the required VS Code version to 1.41

**Comment by sujeilyfonseca** [comment]
In VS Code 1.40, you get the same unsupported extension message:

<img width="553" alt="Screen Shot 2020-01-29 at 9 38 17 AM" src="https://user-images.githubusercontent.com/49531960/73365999-353fb680-427b-11ea-8ec4-62c436182bd1.png">

However, Codewind works:

 <img width="1602" alt="Screen Shot 2020-01-29 at 9 34 08 AM" src="https://user-images.githubusercontent.com/49531960/73365976-2d801200-427b-11ea-8aa7-32e3c392b33f.png">

<img width="1603" alt="Screen Shot 2020-01-29 at 9 38 54 AM" src="https://user-images.githubusercontent.com/49531960/73365982-2fe26c00-427b-11ea-8f60-1ec03feb04a2.png">

**Comment by micgibso** [comment]
Will update the help
