### ISSUE TITLE
cwctl errors out on project create

### ISSUE THREAD

**Issue by maysunfaisal** [eclipse/codewind#1923]
**Codewind version:** latest
**OS:**

**Che version:** 7.5.1
**IDE extension version:** latest
**IDE version:**
**Kubernetes cluster:** OCP 4.2

**Description:**
In Turbine functional tests, we use`cwctl` to create projects before we kick off project create from Turbine. Since this week, we've been seeing issues with `cwctl` failing intermittently on project create:
```
2020/01/26 22:03:09 There was a problem retrieving extensions data
{"error":"project create","error_description":"Hostname or port for PFE not found"}
✖ Failed to created project turbinetest-docker-python.  
```

`cwctl project create --url <url> --path <path>` is what we do. Does this actually require PFE to be up like the error says?

**Comment by liamchampton** [comment]
@maysunfaisal Yes because project create calls project validate in order to create `.cw-settings`
see https://github.com/eclipse/codewind-installer/pull/342 for reference

**Comment by maysunfaisal** [comment]
@liamchampton what else does project validate do that requires PFE to be up?

**Comment by jcockbain** [comment]
Validate calls the PFE /ignored-paths [API] (https://github.com/eclipse/codewind/blob/master/src/pfe/portal/routes/ignoredPaths.route.js) for any project type [here](https://github.com/eclipse/codewind-installer/blob/master/pkg/project/create.go#L328) to get the ignoredPath list to add to .cw-settings. 

It then calls PFE /extensions [here](https://github.com/eclipse/codewind-installer/blob/master/pkg/project/create.go#L328), as @makandre says in #1805.

**Comment by maysunfaisal** [comment]
Chatted with @jcockbain, he explained to me why a conID is required on project create and why we were not seeing it previously - installer changed logic around how it handles connection recently and apparently project create always required conID since some time, but since recently does cwctl make sure we always need a conID. 

Closing this issue as invalid and will workaround the issue to use the conID during project create
