### ISSUE TITLE
Set up an IntelliJ custom plugin repo on the Eclipse download site.

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind#1926]
Similar to the install repository we have for the Eclipse plugins, we should investigate setting up a custom plugin repo for the IntelliJ plugin, so SVT and others don't have to download and install from the zip file.

See https://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/update_plugins_format.html for instructions on what to do.

For this to work, we may or may not need to change the way the plugin version is defined, currently it is automatically set based on the branch name and build time.

**Comment by josephca** [comment]
**How to use the custom plugin repository for tests**:
Refer to https://www.jetbrains.com/help/idea/managing-plugins.html#

1. Add custom repository : 
 https://download.eclipse.org/codewind/codewind-intellij/master/latest/updatePlugins.xml
2. Type 'codewind' to search for codewind-intellij
e.g.
![image](https://user-images.githubusercontent.com/25185698/73776397-a7ba0600-4755-11ea-8003-7878c294f87a.png)
