### ISSUE TITLE
Intermittent Turbine test timeout: PFE - unit test - workspaceSettings module

### ISSUE THREAD

**Issue by rwalle61** [eclipse/codewind#1928]
**Codewind version:** latest
**OS:** mac
Jenkins

**Description:**
On several of my PRs this week the PR build has failed due to a timeout in this test despite my PR not changing any relevant code (e.g. https://github.com/eclipse/codewind/pull/1922). Restarting the build usually passes, but not always. This failure seems to have occured in master too https://ci.eclipse.org/codewind/job/Codewind/job/codewind/job/master/464/console, https://ci.eclipse.org/codewind/job/Codewind/job/codewind/job/master/460/console.

See the logs from the example PR:
```
251 passing (26s)
17:01:56    1 failing
17:01:56  
17:01:56    1) PFE - unit test
17:01:56         workspaceSettings module
17:01:56           combinational testing of readWorkspaceSettings function
17:01:56             combo4 => file: /home/genie.codewind/jenkins-agent/workspace/Codewind_codewind_PR-1922/src/pfe/file-watcher/server/test/resources/.config/settings.json, data: { "registryAddress": "testRegistryAddress", "registryNamespace": "testRegistryNamespace" }:
17:01:56       Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/genie.codewind/jenkins-agent/workspace/Codewind_codewind_PR-1922/src/pfe/file-watcher/server/test/unit-test/unit.test.ts)
```

Other of my PRs that had similar failures: https://ci.eclipse.org/codewind/job/Codewind/job/codewind/job/PR-1893/1/consoleFull, https://ci.eclipse.org/codewind/job/Codewind/job/codewind/job/PR-1893/9/console

We may just need to increase the timeout, or this is exposing an underlying bug

@ssh24 fyi since we discussed this :)

**Comment by ssh24** [comment]
/area iterative-dev
/kind test

Leaving this open to keep an eye out for the failures

**Comment by rwalle61** [comment]
same error https://ci.eclipse.org/codewind/job/Codewind/job/codewind/job/PR-2148/1/console
```
11:27:59    251 passing (25s)
11:27:59    1 failing
11:27:59  
11:27:59    1) PFE - unit test
11:27:59         workspaceSettings module
11:27:59           combinational testing of getWorkspaceSettingsInfo function
11:27:59             combo4 => file: /home/genie.codewind/jenkins-agent/workspace/Codewind_codewind_PR-2148/src/pfe/file-watcher/server/test/resources/.config/settings.json, data: { "registryAddress": "testRegistryAddress", "registryNamespace": "testRegistryNamespace" }:
11:27:59       Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/genie.codewind/jenkins-agent/workspace/Codewind_codewind_PR-2148/src/pfe/file-watcher/server/test/unit-test/unit.test.ts)
```

**Comment by hhellyer** [comment]
It's easy to spot the failures by looking at master to see which builds have a failure in the "Run Turbine unit test suite" column: https://ci.eclipse.org/codewind/job/Codewind/job/codewind/job/master/

@ssh24 @jgwest  - This is impacting PR builds fairly frequently and making it hard to see if PR's are building cleanly or not. Now we've got 0.9.0 branched could this get looked at on master to clean up the failures?

**Comment by ssh24** [comment]
I will take a look into it. Given that it is intermittent and passed 100% during our nightly builds - I think we could just increase the timeout for now

**Comment by hhellyer** [comment]
I'm still seeing an almost identical test failure this morning:
```
16:21:12    1) PFE - unit test
16:21:12         workspaceSettings module
16:21:12           combinational testing of readWorkspaceSettings function
16:21:12             combo5 => file: /home/genie.codewind/jenkins-agent/workspace/Codewind_codewind_master/src/pfe/file-watcher/server/test/resources/.config/settings.json, data: { "registryAddress": "testRegistryAddress", "registryNamespace": "testRegistryNamespace", "watcherChunkTimeout":5000 }:
16:21:12       Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/genie.codewind/jenkins-agent/workspace/Codewind_codewind_master/src/pfe/file-watcher/server/test/unit-test/unit.test.ts)
16:21:12    
```

The timeout was added to the testing of `getWorkspaceSettingsInfo` this failed on `readWorkspaceSettings` further down the file.

**Comment by hhellyer** [comment]
@ssh24 - Could you check https://github.com/eclipse/codewind/pull/2242 looks sane given the changes you've already made?

**Comment by ssh24** [comment]
/close

Closing this as it has been solved. Please reopen if needed.
