### ISSUE TITLE
Create Codewind samples Github org and host code samples and templates there

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#193]
Most of our Codewind templates currently come from https://github.com/microclimate-dev2ops, which is the old Github org we used to host Microclimate resources. We should move off of that repo and into something more specific to Codewind.

Other open source projects like Jenkins-X and Che use a dedicated Github org for project templates (see https://github.com/jenkins-x-quickstarts and https://github.com/che-samples). We could do the same, and create a Github org to host our sample code/projects (perhaps `codewind-templates` or `codewind-samples`?)

In addition to hosting the project samples, our samples/templates Github org could also host a basic devfile registry with an index.json pointing to a number of sample devfiles that users could create Codewind workspaces from. This would be particularly nice once @stalleyj's change to allow multiple devfile registries in Che, https://github.com/eclipse/che/pull/14059, is in. We have a similar devfile registry at https://github.com/kabanero-io/codewind-templates/ currently, but it's associated with Kabanero.

**Comment by johnmcollier** [comment]
As part of the move to the new org, we'd also want to look at pruning any remaining references to `Microclimate` or `IBM Cloud` from the project samples

**Comment by jgwest** [comment]
@johnmcollier Rogue Cloud (which you could think of as a sample) is also hosted in `microclimate-dev2ops`, so a more generic name like `codewind-samples`/`codewind-artifacts`/`codewind-resources` would be favoured over `codewind-templates`.

We could just go with `codewind-samples`, or a more generic word (`codewind-resources`) would allow us to store things that ARENT just templates/sample in there, perhaps avoiding the need to create another org at a later date.

**Comment by johnmcollier** [comment]
@jgwest Agreed! I like the idea of using `codewind-resources` or `codewind-samples`, especially as we have other code samples in the works for Codewind (à la Rogue Cloud)

**Comment by jopit** [comment]
Create a new github org called 'codewind-resources'

**Comment by jopit** [comment]
@elsony can your team take care of creating the new org?

**Comment by jopit** [comment]
@andyrwatson can you take care of this?

**Comment by AndyRWatson** [comment]
created https://github.com/codewind-resources

**Comment by tobespc** [comment]
I believe this can be closed off now, moving to verify

**Comment by malincoln** [comment]
@johnmcollier pls verify and close. Thanks
