### ISSUE TITLE
Problems with Che installation docpage

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#1936]
https://www.eclipse.org/codewind/mdt-che-installinfo.html#after-installing-codewind

This UI doesn't exist anymore; it has been superceded by the Image Registry Manager https://www.eclipse.org/codewind/image-registry-credentials.html

secondly:
https://www.eclipse.org/codewind/mdt-che-installinfo.html#using-codewind-from-the-che-theia-ide

is a bit of a strange section.  Firstly there is no `App Status` command, but mostly I think this section is not that helpful. We could point users to the Codewind commands and Codewind view in general, like how https://github.com/eclipse/codewind-vscode#complete-the-installation does (though steps 1-3 there don't apply to Theia).

**Comment by sishida** [comment]
- The "After installing Codewind" and "Using Codewind from the Che Theia IDE" sections have been removed from the https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/mdt-che-installinfo.md file as part of the Che documentation restructuring.
- Registry info will go in a separate file in the documentation.
- We also aim to make the Che section of the documentation more parallel with the VS Code and Eclipse documentation sections.
- Here's the issue for the first part of the Che restructuring: https://github.com/eclipse/codewind/issues/1758

**Comment by tetchel** [comment]
ok, i think it's fine to close this under 1758 as linked, then.
