### ISSUE TITLE
Need more details in the log on changed files received in Turbine level

### ISSUE THREAD

**Issue by yangcao77** [eclipse/codewind#1939]
Recently we saw some unexpected builds got triggered, with the following message

```
[24/01/20 17:54:59 sprung] [INFO] Detected other file changes, Codewind will build the project
[24/01/20 17:54:59 sprung] [INFO] File change detected. Project will re-build.
```

However, the log is unclear which file, and what type of change triggers the rebuild. It is hard to debug without those information. 

Turbine should log the changed files in the log.

**Comment by yangcao77** [comment]
Will reuse the code in filewatcher to log out at most 256 characters to prevent the log from logging too much info in the case of a large change 
https://github.com/eclipse/codewind-filewatchers/blob/96bfb5d1d839002328d2215bf53f5b2e0ee76a65/Filewatcherd-TypeScript/src/lib/FileChangeEventBatchUtil.ts#L194

**Comment by malincoln** [comment]
@yangcao77 pls verify and close. Thanks

**Comment by yangcao77** [comment]
The change is in. Closing this issue.
