### ISSUE TITLE
Re-enable creating .cw-settings for extension projects on create/bind

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#1943]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description of the enhancement:**

This came out of discussions for https://github.com/eclipse/codewind/issues/1269

Need to investigate if it make sense to re-enable creating `.cw-settings` for  extension projects (Appsody and ODO) on create/bind.  It was disabled via https://github.com/eclipse/codewind/issues/649

cc: @jingfuwang 

**Proposed solution:**

**Comment by jgwest** [comment]
@makandre: GitHub didn't allow me to assign the following users: makandre jingfuwang

Note that only org members, repo collaborators and people who have commented on this issue/PR can be assigned.

**Comment by makandre** [comment]
I tested the various settings in `.cw-settings` with appsody projects and did not encounter any unexpected behaviour.  From appsody perspective we are ok to re-enable the file back in the project.

**Comment by GeekArthur** [comment]
I remember we disable the `.cw-settings` for all extensions before, but I find the odo project type already enabled `.cw-settings` but appsody project type doesn't enable, probably something changes in installer.

<img width="1680" alt="Screen Shot 2020-01-31 at 3 21 00 PM" src="https://user-images.githubusercontent.com/15131537/73571770-4f28f700-443d-11ea-9d1a-a4cfde25cc54.png">

**Comment by makandre** [comment]
@GeekArthur Thanks for checking so looks like we can go ahead then. I'll put up a PR shortly.
