### ISSUE TITLE
Update cwctl usage on Turbine Functional Test

### ISSUE THREAD

**Issue by maysunfaisal** [eclipse/codewind#1947]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**
`cwctl project create` requires a `conID` but they didnt catch it since recently. So with the latest installer change, we now always need a `conID`

Update the tests to reflect this. See issue #1923 for details.

/area iterative-dev
/kind test
/assign

**Comment by jgwest** [comment]
@maysunfaisal: GitHub didn't allow me to assign the following users: ssh24

Note that only org members, repo collaborators and people who have commented on this issue/PR can be assigned.

**Comment by ssh24** [comment]
Hello!
