### ISSUE TITLE
Invalid OpenAPI validation rejects filewatcher PUT request, causing continuous PUT requests to PFE and high CPU/resource usage

### ISSUE THREAD

**Issue by jgwest** [eclipse/codewind#1949]
When starting to watch a new Codewind project, the filewatcher is failing on attempting to report the status to PFE.

In the filewatcher log, the following is repeated over and over again:
```
Jan 30 1:02:19.582 PM [381.628] ! ERROR ! Received bad response code 400 from http://127.0.0.1:10000/api/v1/projects/571ae670-438a-11ea-96c5-21c821ab9c37/file-changes/75d2a314fdf31474e2e1286412d03959/status?clientUuid=58f9234d-3ac0-4771-bea3-aab969e31faa - Error:
Error while validating request: request.query.clientUuid should match pattern "^[0-9a-f]{32}$"
```

Unfortunately there is no rate limiting on this request (which is a FWd bug I will address separately), but the main issue is that this PUT request should not be rejected. 

This bug was introduced here:
https://github.com/eclipse/codewind/pull/1920/files
The format field was changed to a pattern that doesn't support the UUID: https://github.com/rwalle61/codewind/blob/c09f93dc8cc529b48923a954c17920c53e49f058/docs/openapi.yml#L1200

**Comment by jgwest** [comment]
`^[0-9a-f]{32}$` doesn't validate a UUID like `58f9234d-3ac0-4771-bea3-aab969e31faa` because the standard string representation of a UUID is > 32 characters.

**Comment by jopit** [comment]
`^[0-9a-f]{32}$` will also reject UUIDs of that form because it doesn't match the '-' character.

**Comment by rwalle61** [comment]
the form worked for me locally, so the `clientUuid` appears to vary between the filewatchers. PR 1951 weakens the validation to allow both formats. That solves the problem for me locally, but if it persists we can take out  `validateReq` from https://github.com/eclipse/codewind/blob/master/src/pfe/portal/routes/projects/fileChanges.route.js#L28 and skip this test https://github.com/eclipse/codewind/blob/master/test/src/API/projects/watchList-fileChanges.test.js#L82 while I investigate

**Comment by jgwest** [comment]
As Richard notes, the format between the UUID filewatchers is different between implementations, which is not ideal, and I will take responsibility for.

**Comment by jgwest** [comment]
I tested the fix in a self-hosted environment and it appears to be fixed 👍 , I will wait for built images to appear, and verify on those before I close.

**Comment by jgwest** [comment]
Issue for Java filewatcher not rate-limiting it's PUT requests: https://github.com/eclipse/codewind/issues/1952

**Comment by jgwest** [comment]
Verified as fixed 🎉
