### ISSUE TITLE
Eclipse: copy/paste file into project, cwctl does not sync it to PFE

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#1953]
**Codewind version:** master
**OS:**

**Che version:**
**IDE extension version:** Eclipse
**IDE version:**
**Kubernetes cluster:**

**Description:**

It's somewhat intermittent and only reproducible on Eclipse.  Found initially by @jgwest.

**Steps to reproduce:**

1. Copy a file from another project and paste it into the root of a project that's bound to Codewind (the target project)
2. If file is synced into PFE (that's great!), delete the file from the target project, then repeat step 1
3. At some point that file will not be synced into PFE after you paste it into the target project.  

Possibly something weird's going on related to the timestamp?  I've found if I edit the source file each time before the copy/paste, the file does get synced over.

**Workaround:** 

Edit the file in the target project, it will then sync over

**Comment by stalleyj** [comment]
@jgwest If this issue only occurs in Eclipse, is the problem likely to be in the FW daemon ?   I would expect the error to occur in VSCode too if the problem was in the sync logic in cwctl or PFE.

**Comment by jgwest** [comment]
@stalleyj Certainly possible, but I was able to reproduce this issue myself, and every time I reproduced it I was able to verify that the filewatcher was behaviour correctly ([via the filewatcher logs](https://github.com/eclipse/codewind-filewatchers/blob/master/DEVELOPING.md#how-to-view-the-codewind-filewatchers-logs).) 

eg every time the issue occurred, I checked the logs and the Java filewatcher both correctly detected the change, and also correctly called cwctl.

**Comment by tobespc** [comment]
A lot of changes have occurred in this area over the last few months, moving to icebox as unable to recreate

**Comment by stalleyj** [comment]
Closing this as a duplicate of the issue above, working on a solution.
