### ISSUE TITLE
SVT:Remote Codewind install on OpenShift need updates to the docs. 

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#1954]
**Codewind version:** 0.8.0
**OS:** Windows/Mac/Linux

**Che version:** 
**IDE extension version:** 0.8.0
**IDE version:** 2019-09
**Kubernetes cluster:**

**Description:**
I followed these instructions (https://www.eclipse.org/codewind/remoteconfiguring.html#configuring-other-cloud-deployments) to Install Codewind on OpenShift and It failed to install. The doc says user does not need to create "namespace" and changing cluster policies `privileged, anyuid` until we run the install command. We can not install remote codewind until we create namespace and change policies.  We need to change these instructions to the user so that they won't get into this problem. 
Step 3. in here (https://www.eclipse.org/codewind/remoteconfiguring.html#configuring-other-cloud-deployments) must be executed after creating namespace and run the install command.

**Steps to reproduce:**
1. Provision new OCP cluster.
2. Follow these instructions (https://www.eclipse.org/codewind/remoteconfiguring.html#configuring-other-cloud-deployments) to install remote codewind and you get into remote Codewind install failure.

**Workaround:** 

@johnmcollier

**Comment by micgibso** [comment]
See https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/remotedeploy-combo.md for the latest draft of the instructions.

**Comment by jagraj** [comment]
@malincoln @johnmcollier @maysunfaisal 
I reviewed latest 0.9.0 docs couple of days back and we are good now. 
Maysun Got into same issue yesterday with 0.8.0 docs and he also reviewed 0.9.0 doc updates and we are good to close this issue now.
