### ISSUE TITLE
Why is 4913 ignored?

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#1955]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Question synopsis:**

In the default `.cw-settings` file, one of the ignored path is `*/4913`.  What's special about this path?  Why is it ignored?

**Comment by johnmcollier** [comment]
From https://github.com/eclipse/codewind/blob/491c1d55d2c7d8c2eb2aaebcd5a682a34d17c879/src/pfe/file-watcher/server/src/projects/DockerProject.ts#L75:

> * .swp, swx, 4913 files are all temporary files created by vim & vi, need to ignore thoses files

**Comment by tetchel** [comment]
https://vi.stackexchange.com/a/9380 :)

**Comment by johnmcollier** [comment]
> So it will first try 4913, and it will keep increment it with 123 until we find a filename that doesn't exist yet. Why 4913 and not 4912 or 4914? I have no idea. It could be that the number is truly arbitrary.

So ignoring 4913 only helps if 4913 doesn't already exist

**Comment by tetchel** [comment]
i suppose we must also ignore 5036, 5159, 5282, 5405, 5528, 5651, 5774, 5897, 6020, and the rest of them.

**Comment by makandre** [comment]
Guess I should have search the code first.  Case closed!
