### ISSUE TITLE
nodejs project build status stuck and stops processing updates

### ISSUE THREAD

**Issue by rajivnathan** [eclipse/codewind#1956]
**Codewind version:** master branch
**OS:** Mac OS Catalina

**Description:**

**Steps to reproduce:**
1. Create a nodejs project
2. Make a change to the health.js file (The first change takes effect)
  - Notice the status is stuck on `Building - Build started`
3. Make another change to the health.js file. (This one does not take effect)
  - Notice the status is the same as before

![image](https://user-images.githubusercontent.com/20015929/73498360-234d3900-438b-11ea-8c1d-c1bcc71d6106.png)

**Workaround:** 

Disable and re-enable the project

**Comment by elsony** [comment]
@ssh24  Can you take a look at this?
