### ISSUE TITLE
Add reference to doc page in .cw-settings file

### ISSUE THREAD

**Issue by rajivnathan** [eclipse/codewind#196]
**Description of the enhancement:**

Jonathan: Couldn't hurt to reference the doc page in the actual file itself, as a comment, for users coming from the reverse direction (.cw-settings -> doc)

This can be done once https://github.com/eclipse/codewind-docs/issues/53 is complete.

**Comment by jgwest** [comment]
John noted that JSON doesn't support comments 😞 , so are options are:
1) Convert this file to YAML format (which actually is a better format for this sort of thing IMHO, but this is some work)
2) Or, add a JSON non-conformant comment (one that doesn't conform to JSON standard), and strip it out before parsing it (so it doesn't prevent parsing)
3) Give up
4) Another idea?

**Comment by tetchel** [comment]
Alternatively, the user usually will access this file from the IDE plugins' Overview pages. So we can (and plan to) link to this page from there.
