### ISSUE TITLE
Default hybrid mode shouldn't need user defined docker registry

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#1961]
With the new hybrid connection, we need to have a docker registry setup to push images too.   Currently, we are using docker.io and all our personal project etc are filling that up.  This also means we are publishing everything we do to public docker.

Rather than do that, we should default to a temporary 'scratch pad' registry that would be used for all the development builds of applications.  Users can still go and add different registries if they wish but should not be forced to do so.

We can then also use this registry at conferences when demoing codewind and the network is rubbish for pulling images from docker.io

**Comment by johnmcollier** [comment]
I have some concerns about this being installed by default:
- Using a local registry with self-signed certs means that each worker node needs to have that registry whitelisted then be restarted for the changes to take effect. This is **not** possible on most managed Kubernetes offerings like IKS or ROKS
- Greatly increases out storage requirement from 2Gi (1Gi for Keycloak, 1Gi for PFE) to well over 50Gi for the smallest registries

Rather than making this installed by default, can we make it an optional install and document how to set it up and use it with Codewind?

**Comment by tobespc** [comment]
taking the implementation of this aside, I think its a poor user experience that our default behaviour is to require a user to enter docker registry credentials.   If a user is new to docker, this could be a complete blocker to them

**Comment by johnmcollier** [comment]
If there’s concerns around our instructions to the user or causing new users to get confused, I’d rather we improve our instructions in the IDE and docs.

I would also consider the requirements to restart your worker nodes to use the registry to be a bigger blocker than requiring the user have a docker registry account for Codewind projects. I think that requirement alone would shy a lot of users away from Codewind.

**Comment by tobespc** [comment]
I've updated the requirement and removed the proposed implementation to allow us to focus on the requirement rather than the technical implementation

**Comment by johnmcollier** [comment]
@tobespc (and whoever else is interested)

It's relatively straightforward to automate access to the OpenShift registry, the instructions in https://www.eclipse.org/codewind/openshiftregistry.html outline what needs to be done. All of this can be automated with calls to `oc` (and/or via client-go where possible).

The one thing to note is:
- OpenShift 3, the registry hostname is: `docker-registry.default.svc:5000`
- OpenShift 4, the registry hostname is: `image-registry.openshift-image-registry.svc:5000`

**Comment by jcockbain** [comment]
An update on this one - we've been researching and testing deploying a simple default registry into the cluster with Codewind. I've written up some design docs - which are in this [PR](https://github.com/codewind-resources/design-documentation/pull/16). 

As it says there, without user configuration we can add this registry in when we deploy Codewind. Exposing this as a kube service, and posting that service address to the PFE `/api/v1/pushimageregistry` route builds projects and push images to the registry pod.

**Comment by jcockbain** [comment]
Ran into the registry whitelist issue described by @johnmcollier when testing the local registry on an Openshift 4.3 cluster. The projects fail to build, showing a helm install error through the vscode plugin. 

Adding the registry service address as an insecure registry, through modifying the cluster resource (as described [here](https://docs.openshift.com/container-platform/4.3/openshift_images/image-configuration.html) for Openshift), fixes this. However, as John said this requires each worker node to restart which is a long process here.

**Comment by johnmcollier** [comment]
@jcockbain Yeah, that's what I was worried about:
1) The `cluster` resource isn't available on managed OpenShift, so it wouldn't be possible there
2) The implementations of this approach would differ between Kubes:
    - OCP and OKD 3.x: SSH into worker nodes to add it to Docker's whitelist
    - Minishift / Minikube / Docker Desktop: Possible, but not sure how?
    - IKS, ROKS, any managed Kube: Not possible
3) Restarting the worker nodes is disruptive and takes a while 😢

**Comment by jcockbain** [comment]
For Docker Desktop there's the 'insecure registries' panel under preferences -> daemon which then fixed it for me. The others mentioned I haven't tried, apart from OCP 4.

But yes, as you've said, setting an insecure registry would likely always be a manual step which is necessary to use our deployed registry. This is something we could document, for example with a `setting image registry` page in the Codewind docs where we explain what our basic registry is and the ways to set it as insecure in the most common Kube flavours? 

It's then a question though, in trying to replace one tedious user setup step (setting up a registry somewhere) are we introducing another? Will discuss with the Portal squad in our iteration planning this morning and update the issue.

**Comment by jcockbain** [comment]
Takeaway from the meeting was whether we go with the in-cluster registry or not, we can improve our documentation to lessen this pain point for the user. 

@johnmcollier is your preference still improved IDE and Codewind docs?

I'll look into what we can add and work with @micgibso on them.

**Comment by jcockbain** [comment]
Our current docs for this are [vs-code](https://www.eclipse.org/codewind/remotedeploy-vscode.html#adding-a-deployment-registry) and [eclipse](https://www.eclipse.org/codewind/remotedeploy-eclipse.html).

I wonder if its worth adding a section centrally which covers more about our need for a registry, things such as:

- what we use the registry for 
- which type of projects require a registry and which don't
- more example registries, linking to John's instructions for openshift image registry for example

**Comment by micgibso** [comment]
We do have this topic - https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/remote-setupregistries.md - in the new structure for 0.10.0 where `Deploying Codewind remotely` and `Using Codewind remotely` are split in two, the topic appearing under the latter thus: 

Using Codewind remotely
- Overview: Using Codewind remotely
- Connecting your IDE to remote Codewind
- Adding an image registry in remote Codewind   _<-- Here_
- Creating and importing projects 

It does outline various scenarios under which you require an image registry, and I could redraft it to cover the additional points you raise.

**Comment by jcockbain** [comment]
@micgibso that's great, it covers the points I've raised above. Does that mean this page will be going out with the 0.10.0 release?

**Comment by micgibso** [comment]
@jcockbain Hi James, sorry, small misunderstanding here, that page will be published for 0.10.0. Does it require any further changes?

**Comment by jcockbain** [comment]
@micgibso - no problem. I'll have another read though and see

**Comment by tobespc** [comment]
closing as just choosing to document the process
