### ISSUE TITLE
additional mpmetrics data to appear on performance graphs

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#1963]
Currently, our dashboards display a very limited set of data from mpmetrics.   However, some of the data that mpmetrics outputs could well work on our dashboards if we used their labels.   This work it to identify and list all the current metrics available in mpmetrics on the /metrics endpoint and see which ones potentially could be displayed.

Then modify our dashboards to show that data.

**Comment by tobespc** [comment]
@mattcolegate Can you take this one please Matt

**Comment by mattcolegate** [comment]
Here's the list of the currently available metrics on `/metrics` and whether they're being used right now

## Open Liberty
Metric | Description | In use?
--- | --- | ---
base:cpu_system_load_average | system load average for the last minute | yes
base:cpu_process_cpu_load_percent | recent cpu average for the JVM process | yes
base:gc_scavenge_time_seconds | approx. accumulated collection elapsed time in ms. | no
base:gc_global_time_seconds | approx. accumulated collection elapsed time in ms	| yes
base:memory_committed_heap_bytes | amount of memory in bytes that's commited for the JVM | no
base:memory_max_heap_bytes | maximum amount of heap memory in bytes that can be used for memory managemnet | no
base:memory_used_heap_bytes | the amount of used heap memory in bytes | no

## WebSphere Liberty
Metric | Description | In use?
--- | --- | ---
base_cpu_processCpuLoad_percent | recent cpu usage for the JVM process | no
base_cpu_systemLoadAverage | system load average for the last minute | no
base_gc_time_seconds{name="scavenge"} | approx. accumulated collection elapsed time in ms | no
base_gc_time_seconds{name="global"} | approx. accumulated collection elapsed time in ms	| yes
base_memory_maxHeap_bytes | max amount of heap memory that can be used for memory management | no
base_memory_committedHeap_bytes | amount of memory in bytes that's committed for the JVM | no
base_memory_usedHeap_bytes | amount of used heap memory in bytes | no

**Comment by mattcolegate** [comment]
According to https://www.ibm.com/support/knowledgecenter/SSD28V_liberty/com.ibm.websphere.wlp.core.doc/ae/rwlp_monitor_metrics_rest_api.html, adding the `monitor-1.0` feature should also get us some HTTP stats - will look into that

**Comment by mattcolegate** [comment]
Pushed up code to https://github.com/mattcolegate/codewind/tree/moreDefaultMPMetricsOnDash which takes all of the current usable metrics from /metrics for Liberty and graphs it - made sure output is number based (it was coming as strings) and updated the mem pool graph's scale to not be based on total memory, as we only have used heap coming from base metrics. Two items still to address:

1. Some runs still have the CPU system going over 100% - think this might be processer% based rather than total workload, but more investigation needed
1. Inclusion of monitor-1.0 in this item or separate?

**Comment by mattcolegate** [comment]
Raised https://github.com/eclipse/codewind/pull/2084 to push up current code solutions.

**Comment by mattcolegate** [comment]
Awaiting PR review and merge
