### ISSUE TITLE
Default storage permissions in IBM Cloud (IKS and ROKS) block Codewind remote install

### ISSUE THREAD

**Issue by markcor11** [eclipse/codewind#1964]
**Codewind version:** 0.8.0

**Description:**
Unable to deploy Codewind remote into IKS (both Kubernetes and Openshift) - permission issues with storage.

**Steps to reproduce:**

* Set up either a Kubernetes or Openshift cluster in IBM Cloud,  
* Attempt to deploy Codewind Remote
* Persistent storage is not writeable for non-root containers which stops Keycloak starting

**Comment by markcor11** [comment]
Reproduced this in Kubernetes and Openshift on IBM Cloud using `ibmc-block-gold` `ibmc-block-bronze` and `ibmc-file-bronze` storage classes with RWO and RWX.  Looks like non-root containers are unable to write to the storage although the storage does appear bound

**Comment by markcor11** [comment]
Rather than doing a combo all-in install, tried just Keycloak with the `--konly` flag to install only the  Keycloak pod and config.  This worked,  the Keycloak POD deployed, storage bound and it Keycloak was able to create and write out the H2 database using ` ibmc-block-gold` (cluster default).   Next step install remote

**Comment by markcor11** [comment]
After creating a new namespace just for Codewind (leaving the Keycloak one alone) then running the commands : 
```
oc adm policy add-scc-to-group anyuid system:serviceaccounts:<mycodewindnamespace>
oc adm policy add-scc-to-group privileged system:serviceaccounts:<mycodewindnamespace>
cwctl install remote (with the `--kurl` aiming at the previous keycloak install)
```
Codewind started up,  `ibmc-file-bronze` storage was accessible, and the deployment including Gatekeeper ran fine. 

So at this point we can again deploy into ROKS but only if Keycloak and Codewind are in separate namespaces. However, if the `anyuid` and `privileged` policy changes set out above were made codewind-service-account specific that would allow Keycloak and Codewind to co-exist together in the same namespace.  Only issue then would be knowing the service account name BEFORE running `cwctl install remote`.   One way around that would be for cwctl to make the policy changes right when it creates the service account.

**Comment by johnmcollier** [comment]
I vote in favour of having cwctl issue the `oc adm policy` commands for the Codewind service account **provided** our docs outline that we'll be doing that for them

**Comment by markcor11** [comment]
Discussed during iteration kickoff and decided not to make a code change.  Instead we will modify our documentation for IBM Public Cloud deployments outlining that Keycloak and Codewind must be installed in different namespaces.

**Comment by micgibso** [comment]
Docs complete.

**Comment by stalleyj** [comment]
This work is complete.
