### ISSUE TITLE
Change ToC structure to work with user flows from docs landing page

### ISSUE THREAD

**Issue by MelHopper** [eclipse/codewind#1980]
_Note: This github issue blocks the New Landing Page design: #2041_

**Note: this work item is directly affected by:

_Create new topic 'Using Codewind Locally' and add orientation to 'tutorialise'_** https://github.com/eclipse/codewind/issues/2243
_

which create the content for the new topics created in the ToC by this work item 

**ENHANCEMENT**
Change of ToC required as per user flow design for flows from docs landing page to website documentation - see Content Strategy report for more info.

**SOLUTION**

New ToC structure at the top of the tree:

Getting Started
->What is Codewind?
->The 3 Configurations of Codewind
-> VS Code
-->Installing
--> Creating your first project
-->  Making a Code Change
-> Eclipse
-->Installing
--> Creating your first project
-->  Making a Code Change
-> IntelliJ
-->Installing
--> Creating your first project
-->  Making a Code Change

Using Codewind as a hosted application on the cloud
Using Codewind Remotely
Deploying Codewind Remotely
Developing Projects
...
**THE WORK**
1. Create the top level 'Using Codewind as a hosted application on the cloud'.
2. hang the Eclipse Che tree underneath this level.

**Other related work**

Content for this topic will be created under https://github.com/eclipse/codewind/issues/2243

New topics you can see in this new ToC are being created under github issues: 

_Using Codewind Locally_  https://github.com/eclipse/codewind/issues/2243
_The 3 configurations of Codewind_ ADD ISSUE

In addition, see github issue ADD which will sunset the gettingstarted topic and redirect external traffic to the new docs landing page instead.

**Background**

Currently, the left hand navigation (/table of contents(ToC)) of the codewind.dev documentation topics does not:

1. orient the user based on (i) the new tutorials work (ii) the main use cases of our user personas (iii) new terminology for the 3 different ways Codewind can be used (local, remote, broswer-based).

2. work with the user flow work and new Documentation Landing Page design.

**Designing a solution** 

Change to ToC (@micgibso FYI), based on:

1. we cannot use more than 3 levels within the ToC
2. There is a separate link from the docs LP for users of browser-based codewind from the local and remote codewind cards.
3. we no longer need the current the Getting Started topic because we have a new Docs Landing Page.

**Comment by MelHopper** [comment]
Blocked by work to align Eclipse Che topics with framework used for local and remote Codewind configs. https://app.zenhub.com/workspaces/codewind-5d125da643e42a09a0a4a961/issues/eclipse/codewind/1758

**Comment by MelHopper** [comment]
The ToC needs to rearranged thus: [WIP]

What is Codewind?
Getting Started
-> using Codewind Locally
Working with your project
Working with project templates
Performance Monitoring
Integrating with <to be added>
Using Codewind in your cloud environment
-> Using Codewind as a hosted application on Eclipse Che
-> Using Codewind remotely on VS Code, Eclipse or Intellij
-> Optional additional configurations for cloud development using Codewind
Tools
Troubleshooting

**Comment by micgibso** [comment]
That makes sense, will put the changes on PR https://github.com/eclipse/codewind-docs/pull/341 at some point.

**Comment by MelHopper** [comment]
ToC will be modified from above by separating out header topics based on Jane vs Champ use cases. See https://github.com/eclipse/codewind/issues/2151 for work to modify the remote case.

**Comment by MelHopper** [comment]
Depends on https://github.com/eclipse/codewind/issues/2381 **Move Optional topics out of Eclipse Che tutorial block and into it's own block**

**Comment by MelHopper** [comment]
Change to ToC, based on:

1. we cannot use more than 3 levels within the ToC
2. There is a separate link from the docs LP for users of browser-based codewind from the local and remote codewind cards.
3. we no longer need the current the Getting Started topic because we have a new Docs Landing Page.

As such, the following needs to happen:

1. Create a new topic at the top level titled  **_Using Codewind Locally_**. It is linked from the Docs LP 'step-by-step instructions' link for Local and Remote. It needs to explain that Remote also requires local setup as a pre-req. 

2. Create a new topic at the top level titled **The 3 configurations of Codewind**

3. Getting Started topic needs to be sunset and a redirection to the new Docs LP set up.

IMPORTANT: Redirection needs to happen for the codewind.dev/gettingstarted webpage - external pages will be redirected from here to the new Docs Landing Page. Next phase will involve modifying main external links to config tutorials (local, remote or browser-based), where appropriate.

New ToC structure at the top of the tree:

What is Codewind?
The 3 Configurations of Codewind
Using Codewind Locally
Using Codewind as a hosted application on the cloud
Using Codewind Remotely
Deploying Codewind Remotely
Developing Projects
...

**Comment by MelHopper** [comment]
Changes being implemented via PR https://github.com/eclipse/codewind-docs/pull/534
