### ISSUE TITLE
Offline support phase 1: Day to day use

### ISSUE THREAD

**Issue by rtaniwa** [eclipse/codewind#1991]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description of the enhancement:**

Companies often want to use their own hosted or governed repositories for Maven, NPM, container registries, artifactory, etc. We need to walk through using each of these and make sure that Codewind supports (or at least doesn't conflict) with using any of them, and document and/or blog anything relevant.
This is similar to (but not quite the same) as full offline development.

**Proposed solution:**

**Comment by makandre** [comment]
One other scenario we discussed was organizations that require devs to communicate with the outside world through a proxy server.  For this, I was able to determine that configuring the proxy settings of the docker daemon does make the containers spun up via Codewind talk thru the proxy* (and presumably configuring the proxy at the machine/OS level will also work)

One possible problem is if the proxy uses a self-sign cert, we will run into errors about untrusted sources from tools used in builds (such as `npm`).  I'm not sure how likely we would encounter this situation in the real world however.


\* using https://mitmproxy.org/ for my tests

**Comment by makandre** [comment]
Using https://github.com/eclipse/codewind/issues/2444 to document the offline support based on findings (and fixes) from #2078 and #2080

**Comment by j-c-berger** [comment]
@makandre or @sghung,  @sishida made the doc, `offline-codewind.md` do we think this doc could funnel into this Epic? 

I want to determine what docs we'll need for this Epic, and ID's role. We can make additions and revisions to the `offline-codewind.md` as need be. Thanks!

**Comment by sghung** [comment]
@j-c-berger this scenario is using private registries, so I think another .md is needed to avoid confusion.

**Comment by j-c-berger** [comment]
@sghung, that makes sense. Do we have an ideas or vision about what this other .md file would entail? Similar content to the existing one Sarah made?

**Comment by sghung** [comment]
@j-c-berger it is hard to say at the moment, but I think it will be similar. I'd imagine there would be more steps, so probably need a table of contents at the top (just like troubleshooting).

**Comment by sghung** [comment]
Closing this issue as the work has been completed.

Doc changes:
Blog about working with private registries #518 (https://github.com/eclipse/codewind-docs/pull/518)

Some fixes include:
- docker: remove image after build #2402
- swift: remove image after build #2388
- nodejs: remove image after build #2387
- Copy settings.xml for springboot projects #2525
- Copy settings.xml for microprofile projects #2527

**Comment by malincoln** [comment]
@rtaniwa or @deboer-tim pls review and close per Steven's update above.  Thanks

**Comment by rtaniwa** [comment]
Looks like there is still a child story open. If that is done, we should close that one off (it's in verify), and then I think we can close this one off.

**Comment by sghung** [comment]
@rtaniwa I have closed off the remaining issue: https://github.com/eclipse/codewind/issues/2078

**Comment by malincoln** [comment]
Tim gave okay to close.
