### ISSUE TITLE
Useful Extensions Page - VS Code

### ISSUE THREAD

**Issue by thisguy-1** [eclipse/codewind#1992]
<img width="1451" alt="Screen Shot 2020-02-03 at 1 22 40 PM" src="https://user-images.githubusercontent.com/52169824/73679378-4710c780-4688-11ea-8e15-5bc04523d2c0.png">
Link to invision:
https://ibm.invisionapp.com/share/Z4NZODEXAVW

Asset:
[Extenstion Icon.svg.zip](https://github.com/eclipse/codewind/files/4149434/Extenstion.Icon.svg.zip)

@tetchel

**Comment by thisguy-1** [comment]
@sishida please verify that content is correct. Especially the category titles.

**Comment by sishida** [comment]
Comments added in InVision. :)

**Comment by tetchel** [comment]
https://github.com/eclipse/codewind-vscode/pull/445
