### ISSUE TITLE
Can't add new NPM dependency through Codewind

### ISSUE THREAD

**Issue by james-wallis** [eclipse/codewind#1993]
**Codewind version:** Master
**OS:** Mac
**Deployment:** Docker but may happen in K8s - can test tomorrow if needed to.

**Description:**
AFAIK I should be able to modify the dependency object in a Node.js `package.json` and it should pull in the new dependency. Once I make the code change the code isn't being rebuilt. I've tried pressing the `build` button (doesn't do anything) and disabling and enabling the application which appears to make the image rebuild but then it hangs on `Building - Build started` (from the VSCode IDE).

This has happened in three applications:
1. Source code downloaded from a Node.js template over a month ago, looks like a generic express app to me.
2. The Node.js simple express Kabanero template.
3. Appsody Node.js simple express application - couldn't even see the `dependencies` section but I assume this is an Appsody thing (architect vs dev). 
    * On a side note I'm not sure what this brings us within Codewind as I couldn't see a way to pull in the dependencies? Is there additional setup for Appsody with Codewind?

**Steps to reproduce:**
1. Create a Node.js application
2. Wait for it to build and verify its started in the browser
3. Add a new dependency to the `package.json` (I used `"axios": "^0.19.2"` - had to drop out of Codewind and look up the version) and save it.
4. Add some code into your Node application which uses the new package and see if works as you'd expected to.

**Workaround:** 

disable and enable the application.

**Comment by johnmcollier** [comment]
Wonder if this is related to Nodemon? I know we're using it on local for "Codewind-style" projects, and I believe the Appsody node stack also uses Nodemon to check for updates.

**Comment by tetchel** [comment]
I tried it just now but ran `npm install` from the project directory on my disk - instead of editing package.json directly - and it worked

**Comment by tetchel** [comment]
this is probably a cross-squad problem so I will tag both

**Comment by james-wallis** [comment]
Just checked out master again and retried this. Added Axios to the `package.json` `"axios": "^0.19.2"` directly after the two changes described in #2001.
Made my application crash:
```
> node@1.0.0 start /app
> node $npm_package_config_entrypoint

[Tue Feb  4 10:54:37 2020] com.ibm.diagnostics.healthcenter.loader INFO: Node Application Metrics 5.1.1.202002041039 (Agent Core 4.0.5)
[Tue Feb  4 10:54:38 2020] com.ibm.diagnostics.healthcenter.mqtt INFO: Connecting to broker localhost:1883
[2020-02-04T10:54:38.387] [INFO] ibm-cloud-env - Initializing with /app/server/config/mappings.json
[2020-02-04T10:54:38.390] [WARN] ibm-cloud-env - File does not exist /app/server/config/mappings.json
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Server.setupListenHandle (net.js:1360:14)
    at Server._listen2 (/app/node_modules/async-listener/index.js:97:23)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
    at Object.<anonymous> (/app/server/server.js:30:8)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node@1.0.0 start: `node $npm_package_config_entrypoint`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-04T10_54_38_418Z-debug.log
[nodemon] app crashed - waiting for file changes before starting...
```
Marking this as `stopship` as I cannot develop a Node.js application.
/stopship

**Comment by malincoln** [comment]
@elsony @tobespc pls review.  Thanks

**Comment by tobespc** [comment]
@elsony I'm don't see anything from portal causing this, can you check from your side please

**Comment by ssh24** [comment]
I am looking into it

/assign

**Comment by rajivnathan** [comment]
@james-wallis please verify when you have a chance. Thanks

**Comment by ssh24** [comment]
@james-wallis Any update on this?

**Comment by james-wallis** [comment]
Yup it is working now, thanks
