### ISSUE TITLE
SVT: [VS Code] HTML code in notification when there was an error reconnecting to Local Codewind

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#1995]
**Codewind version:** Latest
**OS:** Mac OS Mojave 10.14.6

**IDE extension version:** 0.9.0
**IDE version:** Code 1.41.1

**Description:** HTML code in notification when there was an error reconnecting to Local Codewind

<img width="1324" alt="Screen Shot 2020-02-03 at 11 12 33 AM" src="https://user-images.githubusercontent.com/49531960/73684383-0e75eb80-4692-11ea-9d15-cc640221ab12.png">

@jagraj

**Comment by tetchel** [comment]
the real issue here is the 'cannot get /projects', but there's also no reason to still be serving html in error messages.

**Comment by tobespc** [comment]
@stalleyj can you grab this one please

**Comment by stalleyj** [comment]
It's a strange one but the only way I can see this error happening is if Codewind has been restarted and subsequently, there is a something else running on 127.0.0.1:previousCodewindPort.  If there is a server there (ie a python project), it will respond with an html error page.  When the plugin attempts to refresh/reconnect, does it assume local Codewind will be on the same port ? @tetchel

**Comment by tetchel** [comment]
>  When the plugin attempts to refresh/reconnect, does it assume local Codewind will be on the same port

If you stop/started it through the VS Code UI, then no, it will find the new port
If you stop/started it outside of VS Code (eg cwctl), you have to run the refresh action to get the plugin to know to update the portal.

**Comment by stalleyj** [comment]
A bit more playing and I can now see the problem. When Codewind is starting, it creates an Express server and then configures various routes. If a route is called before it is ready, Express returns the html error. With a number of projects, including Appsody ones, there is a number of seconds before the routes are configured. I can only assume that the /v1/projects is being called too soon.

**Comment by tetchel** [comment]
I found a code path where i will try GET /projects before the connection is 'ready' I will address this
