### ISSUE TITLE
Prevent changes to IntelliJ meta-data files from triggering builds

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind#1996]
IntelliJ stores it's project-related meta-data inside the project directory. We need to stop a build being kicked off by changes to this metadata.

The folder is: `.idea`
The file matches the glob: `*.iml`

**Comment by tetchel** [comment]
I think this is iterative-dev area since they own the ignore list https://github.com/eclipse/codewind/blob/491c1d55d2c7d8c2eb2aaebcd5a682a34d17c879/src/pfe/file-watcher/server/src/projects/DockerProject.ts#L78

**Comment by jopit** [comment]
@jgwest said the changes need to be made here:

Add filter here in cwctl:
https://github.com/eclipse/codewind-installer/blob/9ca68a228b4ce83a30b8951aa39a566d901e2949/pkg/project/sync.go#L359
Add filter here in PFE:
https://github.com/eclipse/codewind/blob/41cad69683fc8c4189a2b0dfd5af0a68a0f30eb0/src/pfe/portal/modules/utils/ignoredPaths.js

**Comment by jopit** [comment]
Maybe it also needs to be added to iterative-dev? @elsony?

**Comment by jopit** [comment]
@rajivnathan wrt Tim's commet https://github.com/eclipse/codewind/issues/1996#issuecomment-581633466, do changes need to be made for Turbine as well?

**Comment by james-wallis** [comment]
PR opened for CLI: https://github.com/eclipse/codewind-installer/pull/363

**Comment by jgwest** [comment]
@rajivnathan can confirm, but looks like there are a few more places to update in Turbine:
See `defaultIgnoredPath` variable `*Project.ts` in https://github.com/eclipse/codewind/tree/491c1d55d2c7d8c2eb2aaebcd5a682a34d17c879/src/pfe/file-watcher/server/src/projects . 

Filewatcherd itself will only watch what it is told by PFE: the filewatchers are designed such that there is no project-type-specific logic at all in its implementation, this comes entirely from the watch API of PFE.

**Comment by james-wallis** [comment]
PR opened for PFE/Portal: https://github.com/eclipse/codewind/pull/2013

**Comment by elsony** [comment]
As long as we control on the portal layer to ensure that those files never get copied into the container, then turbine will never see those file. Therefore, I think we just need to have it on the ignore list so that portal doesn't sync those files, there is nothing needed to be done on the iterative dev side to handle it.

**Comment by rajivnathan** [comment]
As Elson mentioned if cwctl doesn't sync those files then no changes required on the Turbine side. However, looking at the cwctl code we don't appear to be doing anything special for other IDEs? eg. I don't see the `.vscode` folder ignored.

**Comment by jgwest** [comment]
We are ignoring `.project` and `.settings` for Eclipse, so perhaps we should be ignoring the VSCode resources.

**Comment by jopit** [comment]
Probably should also be ignoring `.classpath` for Eclipse.  I've asked Erin and Tim to open a separate issue against portal for the other IDEs.

**Comment by jopit** [comment]
Verified.
