### ISSUE TITLE
Updating pom.xml removes javametrics from an open liberty project.

### ISSUE THREAD

**Issue by hhellyer** [eclipse/codewind#2002]
**Codewind version:**
latest

**Description:**
[04/02/20 11:41:18 /portal/routes/projects/remoteBind.route.js] [WARN] Error: Injection of metrics collector is not supported for projects of type 'docker'
    at Object.injectMetricsCollectorIntoProject (/portal/modules/metricsService/index.js:41:11)
    at uploadEnd (/portal/routes/projects/remoteBind.route.js:274:32)

**Steps to reproduce:**
- Enable metrics injection for an open liberty project.
- Confirm javametrics has been injected into the remote pom.xml file.
- Edit the local pom.xml file and save to sync a new version.
- Examine the remote pom.xml file again, javametrics will have been removed. 

**Workaround:** 
Disabling and enabling metrics injection will restore it after a pom.xml change.

**Comment by mattcolegate** [comment]
This is Open Liberty specific, and is down to where I originally chose to put in some logic to identify Open Liberty projects as being of type Docker with language Java. I put that logic into the metrics.controller but the path Howard has used calls into the utility metrics service from remote.bind, bypassing the metrics.controller. I'm fixing this by moving the Open Liberty logic into the utility metrics service and updating the calls from the various routes that use it.

**Comment by mattcolegate** [comment]
#2006 raised to fix issue.

**Comment by hhellyer** [comment]
I've checked this in master now the fix has been merged, adding a property to pom.xml no longer causes the injected metrics to be removed. The backup file also correctly reflects the latest updates so the right content of pom.xml is restored when metrics injection is disabled.
