### ISSUE TITLE
Codewind does not work with a Node.js project on an alpine image

### ISSUE THREAD

**Issue by james-wallis** [eclipse/codewind#2004]
**Codewind version:** Master
**OS:** MacOS

**Description:**
After raising #2003 I figured I should make sure the same application does work with `npm`.
I changed the commands in the `Dockerfile` to be `npm` instead of `yarn` and deleted the `package.json` and `yarn.lock`. Then I created a new project through `npm init`, saved express into the `package.json`, built the Dockerfile and verified that the changes were good.

Next I imported it into Codewind and found that they project did not start. From what I can see the `Dockerfile` has built fine but other errors have occurred stopping projects coming up. 

Codewind-pfe container logs: [npm-app-pfe-log.txt](https://github.com/eclipse/codewind/files/4153359/npm-app-pfe-log.txt)
Some interesting lines:
```bash
[04/02/20 12:46:42 npm-app] [ERROR] executeBuildScript : 384 | sha256sum: Dockerfile-tools: No such file or directory

[04/02/20 12:46:42 npm-app] [ERROR] executeBuildScript : 384 | sha256sum: nodemon.json: No such file or directory
```

```bash
[04/02/20 12:46:45 npm-app] [ERROR] executeBuildScript : 384 | Error response from daemon: Container fd84b25a837f3df385aa85081cb24308464f60025e581a278df4508777f25b30 is not running

[04/02/20 12:46:45 npm-app] [ERROR] [ File Name: /file-watcher/server/dist/projects/projectUtil.js | Function Name: processManager.spawnDetached | Line Number: 389] Error code: 3 - The container failed to start for application /codewind-workspace/npm-app
```

Project imported into PFE: 
[npm-app.zip](https://github.com/eclipse/codewind/files/4153365/npm-app.zip)

**Steps to reproduce:**
1. Import the app above
2. See it doesn't start 

**Workaround:**

**Comment by james-wallis** [comment]
Found a work around - if I tell VSCode that my application is not a Node.js app (bypass our logic) and run it as the type "other" it builds and runs successfully.

**Comment by james-wallis** [comment]
Decided to come at this issue from a different angle to determine its severity, I looked at the live docs to see if I'd done something wrong.
https://www.eclipse.org/codewind/mdt-vsc-importedprojects.html#nodejs-projects

### No Dockerfile
Based on the link above I copied the `package.json` from the linked place (and gave it a name). Created a `server.js` in the `server` folder, checked it ran locally and imported it into Codewind based on the fact that our docs state:
> A Dockerfile is generated if it does not exist.

Application didn't work, VSCode reporting:

> Build Failed - The build failed because required files are missing. See validation results for details.

And I've verified that no Dockerfile exists in the project directory within the Docker volume.

Project used: 
[eclipse.org-node-project.zip](https://github.com/eclipse/codewind/files/4160906/eclipse.org-node-project.zip)


### With a working Dockerfile

**Comment by james-wallis** [comment]
Got the `With a working Dockerfile` project to fail by changing the Docker `FROM` from `node:8` to `node:8-alpine`, guessing we don't work with Alpine images?

**Comment by james-wallis** [comment]
Centos seems fine (taken from our Dockerfile)
```
FROM centos:8.1.1911
RUN yum -y install nodejs \
    && yum clean all \
    && rm -rf /var/cache/yum
```

**Comment by johnmcollier** [comment]
@james-wallis Are you able to get the logs of any exited containers?

My suspicion is that the docker run for alpine is failing somehow (possibly due to a missing utility in alpine). This is because if the docker run fails (see https://github.com/eclipse/codewind/blob/master/src/pfe/file-watcher/scripts/nodejs-container.sh#L304), we exit with the `Build Failed - Creating image for build failed` error message you're seeing (see https://github.com/eclipse/codewind/blob/master/src/pfe/file-watcher/scripts/nodejs-container.sh#L319)

**Comment by james-wallis** [comment]
I've checked the `docker logs` and yeah its missing bash - (they were not available through the VSCode editor as the container failed to start).
Output:
```
>>> docker logs -f 82b5743e13eb
module.js:550
    throw err;
    ^

Error: Cannot find module '/bin/bash'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

**Comment by johnmcollier** [comment]
@james-wallis Yup, that confirms my suspicions. So, I think there's two things that need to be done here:
1) Update https://github.com/eclipse/codewind/blob/master/src/pfe/file-watcher/scripts/nodejsScripts/noderun.sh to not require bash.
2) Update the failed-to-run status to be something other than `Build Failed - Creating image for build failed`

**Comment by james-wallis** [comment]
@johnmcollier yeah agree, do any other languages require bash? They would need changing too

**Comment by rajivnathan** [comment]
There are a couple places that need to be updated for the nodejs type:
https://github.com/eclipse/codewind/blob/47508c1c56841825846af16da34c8f42c496a13c/src/pfe/file-watcher/scripts/nodejs-container.sh#L273
and
https://github.com/eclipse/codewind/blob/47508c1c56841825846af16da34c8f42c496a13c/src/pfe/file-watcher/scripts/nodejsScripts/noderun.sh#L1

but that doesn't seem to have resolved it. There's likely a few more changes required to the noderun script.

Other project types likely have similar issues. @james-wallis were you looking for a fix for any urgent need? Trying to determine prioritization of the work. We also have significant changes coming with odo in the somewhat near future that would make this potentially throw away work.

cc @elsony

**Comment by james-wallis** [comment]
@rajivnathan it totally depends on whether we want to support Alpine images now or wait until odo comes along?

If its decided not to fix this:
1. The failed-to-run status should be updated to give the user a better error like @johnmcollier suggested
2. The docs should be updated to say that we don't support Alpine (or any container that doesn't have bash installed in it)

**Comment by tobespc** [comment]
I think we should fix this as it is a blocker to developers using Codewind if they are bringing Alpine based projects to us.  @rajivnathan if its ok with you, I would like @james-wallis to investigate and potentially fix this

**Comment by elsony** [comment]
From where do we have the Alpine support based image requirement in the first place?  Do we have specific requirement for supporting Alpine based images out of the box without bash?  

There are different types of images out there and we may have others that doesn't have other prereq that we need.  Alpine images does not have bash installed by default doesn't mean that user can't add a line to their Dockerfile to install bash on it.  Instead of trying to remove bash from the picture, I wonder if we should simply to a simpler approach to document that if your base image does not have bash install, install bash on it on the Dockerfile.

**Comment by tobespc** [comment]
Uur specific requirement should be to make it as easy as possible for any developer to use codewind regardless of there environment.  Now I realise this is an almost impossible task as there are so many combinations but that shouldn't prevent us having that as a target.  

As for how we implement this, adding a section to docs is a solution, as would be us injecting bash for them.  The balance would be how much development time would we want to spend on supporting each new environment and whether we could do simple things that would cover a lot of scenarios (like bash being missing for example).

If its possible, I would like our base requirements to be a little more flexible or if thats not possible, make it very easy for projects being brought to codewind to be modified

**Comment by james-wallis** [comment]
I've been doing some research into the effort for Node.js to work with just `sh` based on @rajivnathan and it seems that its minimal (from my testing), just needed one additional change on top of the others.
See branch: https://github.com/eclipse/codewind/compare/master...james-wallis:investigate-sh-vs-bash?expand=1

**Comment by james-wallis** [comment]
Working on the branch given above I've moved to scanning the `/proc` directory rather than running `ps` commands as alpine linux only container a stripped back `ps` command.

I *think* that it is completely working. I'm only seeing the following error: `executeBuildScript : 385 | + set +x
+ nodemon --exec npm run start`

Have only tested this on local Docker, not sure if the K8s run method runs the file.

**Comment by james-wallis** [comment]
PR merged.
