### ISSUE TITLE
How can a user develop an Appsody project through Codewind  (Node.js in my case)?

### ISSUE THREAD

**Issue by james-wallis** [eclipse/codewind#2005]
**Codewind version:** Master
**OS:** MacOS

**Question synopsis:**

See title. 
I'm trying to develop a Node.js application through Codewind and I cannot see how to take an Appsody template and turn it into my own. 

When I search `node` into our list of templates through VSCode I get essentially three types:
* `Node.js Express` (think its the default one)
* `Appsody`
* `Kabanero`
See image: 
![image](https://user-images.githubusercontent.com/17385115/73747853-3035a800-4750-11ea-9d90-323baf21ad21.png)

After trying one of each type I see that `Kabanero` appears to mean `Appsody` (this is clearer when I visit `/api/v1/templates` as I can see the types.

So I select a `Kabanero` simple express template to develop.
I am presented with no `dependencies` in the `package.json` but can see that `express` must be required somewhere as it is present in the `app.js`. 
If I want to develop this further and add more dependencies is this something that I can do or something that the "stack manager"/"architect" has to do? If so can they do this through Codewind at the moment or is this unsupported?

If the Appsody extension requires an architect to add dependencies but we don't support this through Codewind at the moment, does this mean that a user cannot develop a full Node.js application using the Appsody templates?

**Comment by james-wallis** [comment]
@makandre and @deboer-tim what are your thoughts?

**Comment by deboer-tim** [comment]
The stack architect/creator decides what is provided by default, what is hidden, and what you're allowed to provide (or not), all within the constraints of the language or runtime. In this case express is hardwired in where you can't change it, but you can add other dependencies. Stacks should be useful for many applications; you shouldn't ever need to poke the stack creator unless there was a defect in the stack definition or the stack hadn't been updated recently. Codewind fully supports the use of and development with stacks.

Appsody has command line tools to help the stack creator create new stacks, test them, and push updates. We don't have any equivalent tools in Codewind (yet), but this is a relatively infrequent task and done only by the person who maintains the stack.
