### ISSUE TITLE
SVT:Load test fails to run after App metrics injected to WebSphere and Open Liberty projects.

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#2008]
**Codewind version:** 0.9.0 , latest
**OS:** CoreOS

**Che version:** 7.5.1
**IDE extension version:** 0.9.0 , latest
**IDE version:** Theia 7.5.1
**Kubernetes cluster:**
OCP 4.2

**Description:**
Load tests are failing after App metrics injected into WebSphere liberty and Open liberty projects.
Here are the errors that I am getting into in performance pod.

```
Error: GET http://s5jf-olcw09ocp42svt-che-che.apps.grease.os.fyre.ibm.com/metrics/environment failed: 'Error 404: CWMMC0003I: The environment registry was not found.\n'
    at getResData (/usr/src/app/utils/request.service.js:27:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[04/02/20 13:19:35 /usr/src/app/monitor/route.js] [INFO] Start scraping java project at http://wxbf-lagomcw09ocp42svt-che-che.apps.grease.os.fyre.ibm.com
Error: GET http://wxbf-lagomcw09ocp42svt-che-che.apps.grease.os.fyre.ibm.com/metrics/environment failed: '<!DOCTYPE html>\n<html lang="en">\n    <head>\n        <title>Not Found</title>\n        <style>\n            html, body, pre {\n                margin: 0;\n                padding: 0;\n                font-family: Monaco, \'Lucida Console\', monospace;\n                background: #ECECEC;\n            }\n            h1 {\n                margin: 0;\n                background: #AD632A;\n                padding: 20px 45px;\n                color: #fff;\n                text-shadow: 1px 1px 1px rgba(0,0,0,.3);\n                border-bottom: 1px solid #9F5805;\n                font-size: 28px;\n            }\n            p#detail {\n                margin: 0;\n                padding: 15px 45px;\n                background: #F6A960;\n                border-top: 4px solid #D29052;\n                color: #733512;\n                text-shadow: 1px 1px 1px rgba(255,255,255,.3);\n                font-size: 14px;\n                border-bottom: 1px solid #BA7F5B;\n            }\n        </style>\n    </head>\n    <body>\n        <h1>Not Found</h1>\n\n        <p id="detail">\n            For request \'GET /metrics/environment\'\n        </p>\n\n    </body>\n</html>\n'
    at getResData (/usr/src/app/utils/request.service.js:27:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

```
[04/02/20 13:39:33 /usr/src/app/monitor/route.js] [INFO] Start scraping java project at http://tnku-wlcw09ocp42svt-che-che.apps.grease.os.fyre.ibm.com
Error: GET http://tnku-wlcw09ocp42svt-che-che.apps.grease.os.fyre.ibm.com/metrics/environment failed: 'Error 404: CWMMC0003I: The environment registry was not found.\n'
    at getResData (/usr/src/app/utils/request.service.js:27:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Steps to reproduce:**
1. Install codewind from che workspace.
2. Create WebSphere and Open Liberty projects.
3. Inject App metrics for both the projects.
4. Load tests failed to run.

**logs** 

[performance.txt](https://github.com/eclipse/codewind/files/4153717/performance.txt)
[pfe.txt](https://github.com/eclipse/codewind/files/4153718/pfe.txt)

**Workaround:**

**Comment by tobespc** [comment]
I don't get any crashes but I also don't get any metrics data when running open liberty locally or remotely

**Comment by malincoln** [comment]
@jagraj pls verify and close.  Thanks

**Comment by jagraj** [comment]
@tobespc 
I just tried to verify this issue on 0.9.0 release and I still see this issue. This is what I get from performance logs. May be this fix has been not delivered to 0.9.0 branch.?

```
> performanceserver@1.0.0 start /usr/src/app
> PORT=9095 node server.js

[12/02/20 13:28:52 /usr/src/app/server.js] [INFO] Performance server listening on port 9095!
[12/02/20 13:46:01 /usr/src/app/monitor/route.js] [INFO] Start scraping java project at http://40gs-olchecw09svt-che-che.apps.extols.os.fyre.ibm.com
Error: GET http://40gs-olchecw09svt-che-che.apps.extols.os.fyre.ibm.com/metrics/environment failed: 'Error 404: CWMMC0003I: The environment registry was not found.\n'
    at getResData (/usr/src/app/utils/request.service.js:27:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[12/02/20 13:46:54 /usr/src/app/server.js] [INFO] starting
[12/02/20 13:47:14 /usr/src/app/server.js] [INFO] completed
error: unexpected EOF
```

**Comment by markcor11** [comment]
Had a look at this and saw that load was being applied to the project and metrics were created but the performance container was not displaying the loadrun summary status that it used to do. I added PR 2208 to move the summary output from loglevel debug to loglevel info so that it always appears (this will help confirm with issues like this that load was applied)

In terms of why metrics dont appear,  that appears to be due to JavaMetrics only counting the hit for java project routes.  By default the / route in an OpenLiberty project serves a static HTML page so is not being counted.   When adding a new myroute.java or aiming load at /health or /system the dashboard did apply load at those java endpoints and results were visible in the dashboard. 

The current design of the dashboard is such that the History table only displays data if the metrics report contains at least 1 recorded hit to same route that load was applied to.

**Comment by malincoln** [comment]
@hhellyer is adding the logging debug to 0.9.0 branch and @jagraj will rerun scenario to see what debug details are gathered.

**Comment by hhellyer** [comment]
The error `Error 404: CWMMC0003I: The environment registry was not found` is coming directly from the application when the performance dashboard tries to access `/metrics/environment` on the application. I can reproduce that locally but I'm not sure why it's inaccessible or what we actually use that endpoint for. This will probably need further investigation to see if it's the cause of this error, any more output @jagraj can get will be useful.

**Comment by sujeilyfonseca** [comment]
@hhellyer:

@malincoln and @jagraj asked me to re-run this scenario. I'm doing it with 3.11 and 4.3 clusters. I've also requested @DavidG1011 to reproduce in a 4.2 cluster. We'll update the issue based on our findings.

**Comment by DavidG1011** [comment]
Upon attempting this on my 4.2 cluster, I just receive this, which I assume is the normal output: 
```
> performanceserver@1.0.0 start /usr/src/app
> PORT=9095 node server.js

[14/02/20 16:13:40 /usr/src/app/server.js] [INFO] Performance server listening on port 9095!
[14/02/20 16:44:20 /usr/src/app/server.js] [INFO] starting loadrun with options : {"path":"/","requestsPerSecond":"1","concurrency":"1","maxSeconds":"180","url":"http://172.30.76.30:9080/"}
[14/02/20 16:47:31 /usr/src/app/server.js] [INFO] completed - loadrun summary : { totalRequests: 167,
  totalErrors: 0,
  totalTimeSeconds: 180.00783888299998,
  rps: 1,
  meanLatencyMs: 1349.5,
  maxLatencyMs: 31666,
  minLatencyMs: 5,
  percentiles: { '50': 8, '90': 35, '95': 15173, '99': 31645 },
  errorCodes: {},
  instanceIndex: 0 }
```

**Comment by sujeilyfonseca** [comment]
After re-running this scenario again, here is what I found:

**Before injecting application metrics:**
1) Default Websphere Liberty MicroProfile - Successfully executed a load test
<img width="1395" alt="Screen Shot 2020-02-14 at 12 20 34 PM" src="https://user-images.githubusercontent.com/49531960/74553500-83181800-4f25-11ea-83c2-e7630499243d.png">

2) Default Open Liberty - Cannot get results after running a load test
<img width="1395" alt="Screen Shot 2020-02-14 at 12 20 34 PM" src="https://user-images.githubusercontent.com/49531960/74553500-83181800-4f25-11ea-83c2-e7630499243d.png">

**After injecting application metrics:**
1) Default Websphere Liberty MicroProfile - Successfully executed a load test
<img width="1401" alt="Screen Shot 2020-02-14 at 12 24 18 PM" src="https://user-images.githubusercontent.com/49531960/74553690-dbe7b080-4f25-11ea-8b62-ead5d2f06448.png">

<img width="1402" alt="Screen Shot 2020-02-14 at 12 30 29 PM" src="https://user-images.githubusercontent.com/49531960/74553651-cd00fe00-4f25-11ea-87ab-e21e6d5154a4.png">

2) Default Open Liberty - Cannot get results after running a load test
<img width="1393" alt="Screen Shot 2020-02-14 at 12 24 49 PM" src="https://user-images.githubusercontent.com/49531960/74553701-df7b3780-4f25-11ea-9261-292e891fe0eb.png">

<img width="1399" alt="Screen Shot 2020-02-14 at 12 34 54 PM" src="https://user-images.githubusercontent.com/49531960/74553971-6e884f80-4f26-11ea-8a71-55050df8d610.png">


**Performance Log:**
[root@sfonseca-okd-codewind ~]# oc logs codewind-performance-workspacefcjzobve3polw9pw-9b47588d5-99dsj

> performanceserver@1.0.0 start /usr/src/app
> PORT=9095 node server.js

[14/02/20 17:01:58 /usr/src/app/server.js] [INFO] Performance server listening on port 9095!
[14/02/20 17:12:00 /usr/src/app/server.js] [INFO] starting loadrun with options : {"path":"/","requestsPerSecond":"1","concurrency":"1","maxSeconds":"180","url":"http://172.30.163.34:9080/"}
[14/02/20 17:15:00 /usr/src/app/server.js] [INFO] completed - loadrun summary : { totalRequests: 180,
  totalErrors: 0,
  totalTimeSeconds: 180.005340789,
  rps: 1,
  meanLatencyMs: 12.5,
  maxLatencyMs: 378,
  minLatencyMs: 4,
  percentiles: { '50': 7, '90': 15, '95': 22, '99': 130 },
  errorCodes: {},
  instanceIndex: 0 }

[14/02/20 17:17:11 /usr/src/app/server.js] [INFO] starting loadrun with options : {"path":"/","requestsPerSecond":"1","concurrency":"1","maxSeconds":"180","url":"http://172.30.51.74:9080/"}
[14/02/20 17:20:11 /usr/src/app/server.js] [INFO] completed - loadrun summary : { totalRequests: 180,
  totalErrors: 0,
  totalTimeSeconds: 180.007150435,
  rps: 1,
  meanLatencyMs: 8.2,
  maxLatencyMs: 79,
  minLatencyMs: 5,
  percentiles: { '50': 7, '90': 10, '95': 11, '99': 16 },
  errorCodes: {},
  instanceIndex: 0 }

[14/02/20 17:20:47 /usr/src/app/server.js] [INFO] starting loadrun with options : {"path":"/","requestsPerSecond":"1","concurrency":"1","maxSeconds":"180","url":"http://172.30.163.34:9080/"}
[14/02/20 17:23:47 /usr/src/app/server.js] [INFO] completed - loadrun summary : { totalRequests: 180,
  totalErrors: 0,
  totalTimeSeconds: 180.005797962,
  rps: 1,
  meanLatencyMs: 6.2,
  maxLatencyMs: 33,
  minLatencyMs: 4,
  percentiles: { '50': 5, '90': 7, '95': 9, '99': 16 },
  errorCodes: {},
  instanceIndex: 0 }

[14/02/20 17:26:57 /usr/src/app/server.js] [INFO] starting loadrun with options : {"path":"/","requestsPerSecond":"1","concurrency":"1","maxSeconds":"180","url":"http://172.30.51.74:9080/"}
[14/02/20 17:29:58 /usr/src/app/server.js] [INFO] completed - loadrun summary : { totalRequests: 180,
  totalErrors: 0,
  totalTimeSeconds: 180.01032901300002,
  rps: 1,
  meanLatencyMs: 10.1,
  maxLatencyMs: 213,
  minLatencyMs: 5,
  percentiles: { '50': 7, '90': 13, '95': 16, '99': 28 },
  errorCodes: {},
  instanceIndex: 0 }

[14/02/20 17:31:40 /usr/src/app/server.js] [INFO] starting loadrun with options : {"path":"/","requestsPerSecond":"1","concurrency":"1","maxSeconds":"180","url":"http://172.30.163.34:9080/"}

**Comment by jagraj** [comment]
**Local**

WebSphere Liberty
I just tried after getting latest plugins and images. I do see load test results for WebSphere liberty before and after "Enable Inject Metrics". 

Open Liberty
I need to inject metrics and run load test then I get load test results in the performance monitor window.  By default it is hitting "/health" endpoint on local and getting test results as expected.

**Codewind on Che**
WebSphere Liberty
Both embedded and Inject metrics works fine.

Open Liberty
After injecting metrics when I try to run load test and it fails to generate test results cause it is hitting root endpoint "/" but not "/health" by default on che. Not sure why this is different between local and che. 

**Workaround :**

User has to edit load run settings for "Open Liberty" project to hit "/health" endpoint as displayed in the screenshot below. 

![Screen Shot 2020-02-14 at 2 40 35 PM](https://user-images.githubusercontent.com/713849/74562082-fe82c500-4f37-11ea-81c9-05a68f6fbd7a.png)

 You should see the results in performance pod.

```
[14/02/20 19:18:39 /usr/src/app/server.js] [INFO] starting loadrun with options : {"method":"GET","path":"/health","requestsPerSecond":"1","concurrency":"1","maxSeconds":"180","url":"http://172.30.32.134:9080/health"}

[14/02/20 19:21:39 /usr/src/app/server.js] [INFO] completed - loadrun summary : { totalRequests: 180,
  totalErrors: 0,
  totalTimeSeconds: 180.00816315400002,
  rps: 1,
  meanLatencyMs: 10.7,
  maxLatencyMs: 40,
  minLatencyMs: 6,
  percentiles: { '50': 9, '90': 15, '95': 19, '99': 33 },
  errorCodes: {},
  instanceIndex: 0 }
```

**Comment by sujeilyfonseca** [comment]
I can confirm Jag's comment. From my previous comment, you can see that the Websphere Liberty MicroProfile works as expected. However, for Open Liberty:

**Local (VS Code):**
I was able to get the results after injecting the application metrics. By default, the project is reaching the "/health" endpoint:

<img width="1450" alt="Screen Shot 2020-02-14 at 2 58 49 PM" src="https://user-images.githubusercontent.com/49531960/74563644-3c351d00-4f3b-11ea-9483-4bce9461543e.png">

**Eclipse Che**
I was able to get the results of the load test after injecting the application metrics and editing the settings:

<img width="693" alt="Screen Shot 2020-02-14 at 2 55 53 PM" src="https://user-images.githubusercontent.com/49531960/74563582-19a30400-4f3b-11ea-85b8-d5f5fd27c4b7.png">

<img width="1381" alt="Screen Shot 2020-02-14 at 2 56 07 PM" src="https://user-images.githubusercontent.com/49531960/74563586-1ad43100-4f3b-11ea-965b-b0c1a36b0a4b.png">

**Comment by jagraj** [comment]
> **Local**
> 
> WebSphere Liberty
> I just tried after getting latest plugins and images. I do see load test results for WebSphere liberty before and after "Enable Inject Metrics".
> 
> Open Liberty
> I need to inject metrics and run load test then I get load test results in the performance monitor window. By default it is hitting "/health" endpoint on local and getting test results as expected.
> 
> **Codewind on Che**
> WebSphere Liberty
> Both embedded and Inject metrics works fine.
> 
> Open Liberty
> After injecting metrics when I try to run load test and it fails to generate test results cause it is hitting root endpoint "/" but not "/health" by default on che. Not sure why this is different between local and che.
> 
> **Workaround :**
> 
> User has to edit load run settings for "Open Liberty" project to hit "/health" endpoint as displayed in the screenshot below.
> 
> ![Screen Shot 2020-02-14 at 2 40 35 PM](https://user-images.githubusercontent.com/713849/74562082-fe82c500-4f37-11ea-81c9-05a68f6fbd7a.png)
> 
> You should see the results in performance pod.
> 
> ```
> [14/02/20 19:18:39 /usr/src/app/server.js] [INFO] starting loadrun with options : {"method":"GET","path":"/health","requestsPerSecond":"1","concurrency":"1","maxSeconds":"180","url":"http://172.30.32.134:9080/health"}
> 
> [14/02/20 19:21:39 /usr/src/app/server.js] [INFO] completed - loadrun summary : { totalRequests: 180,
>   totalErrors: 0,
>   totalTimeSeconds: 180.00816315400002,
>   rps: 1,
>   meanLatencyMs: 10.7,
>   maxLatencyMs: 40,
>   minLatencyMs: 6,
>   percentiles: { '50': 9, '90': 15, '95': 19, '99': 33 },
>   errorCodes: {},
>   instanceIndex: 0 }
> ```

As we have workaround now and this is no longer stopship for this release. We need to investigate why by default we are not hitting /health in Codewind che and deliver fix in next release so that user does not have to change the endpoint for load test to work.

**Comment by malincoln** [comment]
will work to deliver fix in 0.10.0

**Comment by malincoln** [comment]
Will work to get changes into 0.11.0

**Comment by malincoln** [comment]
@tobespc just confirming this is still on track for 0.11.0?

**Comment by tobespc** [comment]
yes, still on track

**Comment by stalleyj** [comment]
I believe we should be able to fix this by updating the template to have a .cw-settings file with a contextRoot of health.  The load test config uses the project contextRoot as it's path so this should work. Further testing tomorrow.

**Comment by stalleyj** [comment]
Hmm, so that does work for running load but means that the IDE plugins would also open the /health endpoint when a user chooses to 'Open application' so I think that is a no go.  

My understanding is that we can't get metrics for http requests to '/' on Open Liberty because it is serving a static html page here rather than a servlet.  I'm investigating the option of checking the selected load test endpoint against the metrics gathered and informing the user, prompting them to edit the load test config. @jagraj what do you think ?

**Comment by jagraj** [comment]
@stalleyj 
Yes, that would be nice and user can provide valid endpoint for us to run load test. Thank you.

**Comment by tobespc** [comment]
We are having a new message added to make it clear to the user what is going on.  @markcor11 is providing that

**Comment by markcor11** [comment]
I've modified the info screen to show more information about the load test endpoint and the reason for the chart not showing any data : 

![NoMetrics](https://user-images.githubusercontent.com/28102564/78532224-c59bf980-77de-11ea-9a7b-6328d357755c.png)

Where metrics have been gathered the page now clearly shows the Route path that was tested:

![NoMetrics2](https://user-images.githubusercontent.com/28102564/78532295-e3695e80-77de-11ea-9a58-6e059478682f.png)
 
A changes here also make the Path Name selectable. In the previous version if the URL length exceeded the width of the container frame it would overlap and breach the constraints. The change here keeps the Route on a single line but the user can TAB/Select the text and scroll right/left to see the entire string.  They can also CMD+A to select all characters.

**Comment by markcor11** [comment]
Added a message to the top status panel explaining why there are either no hits for the project route path (at all) or the last load test snapshot does not contain any hit data for the route path:

![noHits](https://user-images.githubusercontent.com/28102564/78570052-5a711800-781c-11ea-858b-2d2857e66623.png)

**Comment by markcor11** [comment]
As a side note, whilst testing this code change out I noticed a difference how hits were being counted between a JavaMetrics and AppMetrics. 

Projects created with the base node template returned a pretty 404 page but with a response code of 200 rather than a 404. Node Appmetrics counted that error page as a valid request and it will contribute to the total hits.  Where as in Java,  a missing page returned a 404 error and is not counted. That might actually be why this issue is scoped at Websphere and OpenLiberty projects only. Either way,  now the user will be told there is no http metrics available rather than just be left hanging.

**Comment by malincoln** [comment]
changing to priority/stopship to track for 0.11.0

**Comment by tobespc** [comment]
We have put a fix in to make it clear to the user why there isn't any data being displayed.  This message appears on the graph itself

**Comment by jagraj** [comment]
I do see the message in the graph now where we tell the user provide valid endpoint for the load test to run.
