### ISSUE TITLE
Can't read the rest of the message in che docker registry manager popdown

### ISSUE THREAD

**Issue by beccabau** [eclipse/codewind#2009]
**Codewind version:** 0.8.0
**OS:** red hat linux

**Che version:** 7.51
**Kubernetes cluster:** open shift

**Description of the enhancement:**
![image](https://user-images.githubusercontent.com/13971834/73755961-d5db1e00-4734-11ea-9e3f-8f19b6a4ec1f.png)

I tried clicking on the message to expand the rest of the text, but it moved the process forward (and I ended up creating a blanket workspace). Is there a way for the user to read the rest of the message?

**Proposed solution:** 

Maybe hover over to read the full message, or click once to load the rest of the message.

**Comment by tetchel** [comment]
this is a theia limitation. I will open an enhancement against them.

You can see the full message in vs codeL

![image](https://user-images.githubusercontent.com/8888438/73756593-d1633500-4735-11ea-8ec4-9838f1546d29.png)

**Comment by beccabau** [comment]
got it. thanks, tim!

**Comment by tetchel** [comment]
https://github.com/eclipse-theia/theia/issues/7090
