### ISSUE TITLE
Project update does not receive changed files list

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#2015]
**Codewind version:** master
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**

The `update` function in the project handler is always getting an undefined `changedFiles` array.

A symptom of this is when you change a value in an `env.properties` file inside an appsody project, the application is not rebuilt to pick up the new environment value.

**Steps to reproduce:**

1. Create an `env.properties` file in any appsody project, put a `key=value` pair in the file
2. Shell into the appsody application container, check the value of the environment variable
3. Change the `value` in the `env.properties` file
4. Shell into the appsody application container again, the environment variable still has the old value since the application was not restarted by Codewind.

**Workaround:**

**Comment by makandre** [comment]
I believe this is related to https://github.com/eclipse/codewind/pull/1620

During debugging, I see:

- update build request is added to the queue 
- the file changes is removed from the changed files map [here](https://github.com/eclipse/codewind/blob/master/src/pfe/file-watcher/server/src/controllers/projectEventsController.ts#L252)
- then the build runs and retrieves the changed files from the map [here](https://github.com/eclipse/codewind/blob/master/src/pfe/file-watcher/server/src/controllers/projectsController.ts#L556) (but it is already removed by the above)

**Comment by ssh24** [comment]
Is it only happening for appsody projects? Can you provide detailed reproduction step?

**Comment by ssh24** [comment]
The file changes is removed from the changed files map should be happening after the build has been kicked off with the retrieved changed files from the map [here](https://github.com/eclipse/codewind/blob/master/src/pfe/file-watcher/server/src/controllers/projectEventsController.ts#L241)

**Comment by makandre** [comment]
@ssh24 Not just happening for appsody projects.  But it appears only appsody project's `ShellExtensionProject.ts` handler is doing anything with the `changedFiles` passed to the `update` function.

**Comment by ssh24** [comment]
Interesting. We did move around how `changedFiles` were getting initiated and manipulated. Let me investigate.

/assign

**Comment by makandre** [comment]
Based on the name [`addProjectToBuildQueue`](https://github.com/eclipse/codewind/blob/master/src/pfe/file-watcher/server/src/controllers/projectEventsController.ts#L241), it adds the build to the queue but doesn't exec the build immediately right?  I think that's why the file changes are removed before the build actually executes.

**Comment by ssh24** [comment]
It adds to the build queue and checks right away if it can trigger the build for it. It is also an async function so it should wait for the return of it before removing the project from the changedFilesMap.

What is the sympton of this issue? I just tried it out and my update worked. Also verified by execing into the app pod and seeing the change

**Comment by rajivnathan** [comment]
@makandre can you please verify and close when you have a chance?

**Comment by makandre** [comment]
Verified on master, works fine now, thank you.
