### ISSUE TITLE
Update terminology in Codewind documentation 

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind#2019]
Remove all mentions of "IBM Cloud Private" in Codewind documentation as well as metadata.

**Comment by sishida** [comment]
Files to edit:
- Metadata: https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/mdt-che-createcodewindworkspace.md
- Metadata: https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/mdt-che-createcodewindworkspace.md
- Metadata: https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/mdt-che-createcodewindworkspace.md
- https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/mdt-che-dockerregistries.md
- https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/mdt-che-setupregistries.md
- https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/mdt-che-tektonpipelines.md
- https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/mdt-che-usingtheia.md

**Comment by micgibso** [comment]
Don't remove the text `IBM Cloud...` from the remote topics, these are very specific.
