### ISSUE TITLE
SVT:Getting this popup intermittently in codewind che workspace

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#2020]
**Codewind version:** 0.9.0
**OS:** CoreOS

**Che version:** 7.5.1
**IDE extension version:**  0.9.0
**IDE version:**  Theia 7.5.1
**Kubernetes cluster:** OCP 4.2 cluster

**Description:**
I am keep getting this popup ("Do you want to overwrite the changes made on the file system.?") intermittently when Codewind che workspace refreshes and I did not notice this popup in the past. 

The file name is launch.json file under .projects folder. 

<img width="542" alt="Screen Shot 2020-02-04 at 10 19 12 AM" src="https://user-images.githubusercontent.com/713849/73787478-616ea200-4769-11ea-9364-0afe335500c4.png">

**Steps to reproduce:**
1. Create codewind workspace on eclipse che.
2. Create bunch of projects from default template source.
3. I get this popup intermittently. 

**Workaround:**

**Comment by tetchel** [comment]
this is probably because of @hhellyer change https://github.com/eclipse/codewind-vscode/pull/416

so now the launch.json is getting modified in Theia too

Howard, is there any reason to do this in Theia? or should we put that line in an `if (!global.isTheia)` branch

**Comment by tetchel** [comment]
should b fixed in latest build

**Comment by malincoln** [comment]
@jagraj pls verify and close. Thanks

**Comment by jagraj** [comment]
I no longer see this popup now. Thanks for the fix.
