### ISSUE TITLE
Fix App Status Timeout Msg

### ISSUE THREAD

**Issue by maysunfaisal** [eclipse/codewind#2024]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**
The hostname is absent. It is `Pinging http://:8089/health and http://:8089/` according to:

![Screen Shot 2020-02-04 at 6 57 07 PM](https://user-images.githubusercontent.com/31771087/73798238-3ba0c780-4780-11ea-9ead-95859ec1ea65.png)

/area iterative-dev

**Comment by tetchel** [comment]
https://github.com/eclipse/codewind/issues/1622
