### ISSUE TITLE
cpu graph plotting data outside of range

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#2027]
I'm monitoring an open liberty application after injecting metrics and can see that the cpu graph is plotting outside the range of the axis
![Screenshot 2020-02-05 at 09 35 53](https://user-images.githubusercontent.com/13151286/73829559-14d3a700-47fb-11ea-806f-905fc1fb04e8.png)

**Comment by tobespc** [comment]
@mattcolegate please pick this up

**Comment by mattcolegate** [comment]
Valid issue.
/pipeline portal backlog

**Comment by stalleyj** [comment]
We also see the GC graph plotting outside the axes.

**Comment by mattcolegate** [comment]
@stalleyj that issue covered separately under https://github.com/eclipse/codewind/issues/2056

**Comment by mattcolegate** [comment]
This seems to be restricted to injected projects only - can't recreate this with normal javametrics

**Comment by mattcolegate** [comment]
The cause of this is down to the data collectors for injected projects using the value of base_cpu_systemLoadAverage from /metrics as input for the system load graph.
```
# HELP base_cpu_systemLoadAverage Displays the system load average for the last minute. The system load average is the sum of the number of runnable entities queued to the available processors and the number of runnable entities running on the available processors averaged over a period of time. The way in which the load average is calculated is operating system specific but is typically a damped time-dependent average.
```
This is why high numbers are registered, depending on the number of entities. It's not a percentage indication of system load.
Will raise PRs to stop the use of that metric for system load.
