### ISSUE TITLE
Change the mapping for help topics in VS Code

### ISSUE THREAD

**Issue by micgibso** [eclipse/codewind#2032]
From the video, the file that you showed Tim for VS Code needs the following updates:
TEMPLATE_MANAGEMENT = "workingwithtemplates.html"
INSTALL_INFO = "mdt-vsc-gettingstarted.html"
PROJECT_SETTINGS = "mdt-vsc-commands-project.html#configuring-project-settings
Does not exist in TOC but source .md files still exist, HTML still produced, so stet. Iterate on this for 0.10.0.
INSTALL_ON_CLOUD = "remote_overview.html"
WORKSPACE_NEWS =  "news06.html etc..."  (<-Look out for new News article for 0.9.0)
REGISTRIES= "image-registry-credentials,html" (<-Stet)
REMOTE_UI = "remote-overview.html"
REMOTE_DEPLOYING = "remotedeploy-combo.html" or remotedeploy-single.html / remotedeploy-vscode.html / remotedeploy-eclipse.html
GETTING_STARTED = "getting_started.html" (<-Stet)
COMMANDS_OVERVIEW = "mdt-vsc-commmands-overview.html"
Does not exist in TOC but source .md files still exist, HTML still produced, so stet. Iterate on this for 0.10.0
PERF_MONITORING = "performance.html" (<-Stet)
FIRST_PROJECT_LOCAL = "mdt-vsc-firstproject.html" (<-Stet)

**Comment by tetchel** [comment]
up-to-date file list
https://github.com/eclipse/codewind-vscode/blob/master/dev/src/constants/CWDocs.ts#L25

**Comment by tetchel** [comment]
for `WORKSPACE_NEWS` I specifically want to link to the 0.6 news because that was when the workspace migration was documented

**Comment by micgibso** [comment]
@tetchel Yes, that's the file I think needs updating.

**Comment by tetchel** [comment]
which ones?

**Comment by micgibso** [comment]
Looks like these need changing to the values shown below:

TEMPLATE_MANAGEMENT = "workingwithtemplates.html"
INSTALL_INFO = "mdt-vsc-gettingstarted.html"
INSTALL_ON_CLOUD = "remote_overview.html"
REMOTE_UI = "remote-overview.html"
REMOTE_DEPLOYING = "remotedeploy-combo.html"

**Comment by tetchel** [comment]
INSTALL_ON_CLOUD is for che install, not remote install, so i'm changing the link to `mdt-che-installinfo.html`

**Comment by malincoln** [comment]
@micgibso pls verify and close. Thanks
