### ISSUE TITLE
Add/Update the Dockerhub overviews to contain more information

### ISSUE THREAD

**Issue by james-wallis** [eclipse/codewind#2034]
**Description of the enhancement:**

In https://github.com/eclipse/codewind/issues/1871 I created a basic overview for all of our Dockerhub images based on the old `ibmcom` ones. 

It was agreed with the ID team in the UK that I'd create the basic one and then later they'd update them to add even more information, perhaps using [the Node Docker image](https://hub.docker.com/_/node/) as inspiration so that we include version data and a better overview - aka fully utilise Dockerhub as another entry point for a new Codewind user.

This issue is for the ID team to track the Dockerhub overview future enhancements. 

**Dockerhub repositories that need overviews:**
https://hub.docker.com/r/eclipse/codewind-keycloak-amd64
https://hub.docker.com/r/eclipse/codewind-pfe-amd64
https://hub.docker.com/r/eclipse/codewind-performance-amd64
https://hub.docker.com/r/eclipse/codewind-che-sidecar
https://hub.docker.com/r/eclipse/codewind-initialize-amd64
https://hub.docker.com/r/eclipse/codewind-gatekeeper-amd64
https://hub.docker.com/r/eclipse/codewind-java-profiler-language-server
https://hub.docker.com/r/eclipse/codewind-java-project-cache

@micgibso @melhopper

**Comment by micgibso** [comment]
Closing as out of scope.
