### ISSUE TITLE
SVT: [IntelliJ] It would be nice to have the project tree open by default

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#2037]
**Codewind version:** Latest
**OS:** Mac OS Mojave 10.14.6

**IDE extension version:** 202002042141
**IDE version:** Version: 2019.3.2 | Build: 193.6015.39 | 20 January 2020

**Description:** It would be nice to have the project tree open by default. If the IDE is reloaded due to new project creation, the project tree will appear closed by default.

<img width="430" alt="Screen Shot 2020-02-05 at 11 57 42 AM" src="https://user-images.githubusercontent.com/49531960/73863870-ba444600-480e-11ea-91ea-0af8a7a6ffdd.png">

<img width="615" alt="Screen Shot 2020-02-05 at 11 32 55 AM" src="https://user-images.githubusercontent.com/49531960/73863880-bfa19080-480e-11ea-81a8-b9ef52c77125.png">

@jagraj

**Comment by keithchong** [comment]
Reference: https://github.com/eclipse/codewind/issues/2560

For some reason, after creating the new project, the new window is refreshed/reloaded which throws a wrinkle when using the solution https://github.com/eclipse/codewind/issues/2560.

**Comment by keithchong** [comment]
@sujeilyfonseca , please verify

**Comment by sujeilyfonseca** [comment]
I verified this issue with the latest Codewind, and now the Codewind view and tree are kept open after creating a new project.
