### ISSUE TITLE
SVT: [IntelliJ] “Performance Dashboard” should only be available in supported projects

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#2038]
**Codewind version:** Latest
**OS:** Mac OS Mojave 10.14.6

**IDE extension version:** 202002042141
**IDE version:** Version: 2019.3.2 | Build: 193.6015.39 | 20 January 2020

**Description:** “Performance Dashboard” should only be available in supported projects. Right now, it is available in all project types. 

<img width="399" alt="Screen Shot 2020-02-05 at 11 21 44 AM" src="https://user-images.githubusercontent.com/49531960/73864176-2f178000-480f-11ea-8165-ea93c9e19aad.png">

@jagraj

**Comment by cccanderson** [comment]
This was "fixed" by https://github.com/eclipse/codewind-intellij/pull/59 .  (Note that recent changes made it so that all project types currently supported by IntelliJ show the Performance Dashboard option... but the code is now in place where, should that change, the action will not be shown.)
