### ISSUE TITLE
SVT: [IntelliJ] "Import project” must not be at the project level

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#2039]
**Codewind version:** Latest
**OS:** Mac OS Mojave 10.14.6

**IDE extension version:** 202002042141
**IDE version:** Version: 2019.3.2 | Build: 193.6015.39 | 20 January 2020

**Description:** "Import project” must not be at the project level. It should be at the local container level.

<img width="399" alt="Screen Shot 2020-02-05 at 11 21 44 AM" src="https://user-images.githubusercontent.com/49531960/73864273-5d955b00-480f-11ea-9b46-0c756c21117b.png">

@jagraj

**Comment by jopit** [comment]
'Import project' should be removed.  Keith is working on 'Add Existing Project', which won't be available by DCUT, but should be available within a couple of days

**Comment by malincoln** [comment]
@sujeilyfonseca pls verify and close. Thanks

**Comment by sujeilyfonseca** [comment]
I verified this issue with the latest Codewind 0.9.0, and I no longer reproduce this problem.
