### ISSUE TITLE
SVT: [IntelliJ] Codewind must update its status continuously

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#2040]
**Codewind version:** Latest
**OS:** Mac OS Mojave 10.14.6

**IDE extension version:** 202002042141
**IDE version:** Version: 2019.3.2 | Build: 193.6015.39 | 20 January 2020

**Description:** Codewind must update its status continuously

1) Users cannot see the updated build/application statuses. If he/she refreshes Codewind, then he/she will see the actual status:

<img width="610" alt="Screen Shot 2020-02-05 at 12 12 49 PM" src="https://user-images.githubusercontent.com/49531960/73866288-9420a500-4812-11ea-9559-6b61d88d629e.png">

<img width="608" alt="Screen Shot 2020-02-05 at 12 12 58 PM" src="https://user-images.githubusercontent.com/49531960/73866302-9b47b300-4812-11ea-9755-551fd135de0c.png">

2) List of projects doesn’t disappear after stopping Codewind. User must click on refresh:

<img width="611" alt="Screen Shot 2020-02-05 at 11 26 40 AM" src="https://user-images.githubusercontent.com/49531960/73864349-7c93ed00-480f-11ea-8a15-4069ae826321.png">

@jagraj

**Comment by jopit** [comment]
This should be fixed by PR https://github.com/eclipse/codewind-intellij/pull/17

**Comment by malincoln** [comment]
@sujeilyfonseca pls verify if above PR resolves problem. Thanks

**Comment by sujeilyfonseca** [comment]
I verified this issue with the latest Codewind 0.9.0, and I no longer reproduce this problem.
