### ISSUE TITLE
[IKS] Cwctl needs to support exported Kube configs

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#2051]
**Codewind version:** latest
**OS:** macOS

**Kubernetes cluster:** IKS / Kube 1.16

**Description:**
IKS clusters provide users a Kube config file that they can export in their terminal when they configure against it (of the form: `export KUBECONFIG=/path/to/some/yaml`). It does **not** place an entry under `~/.kube`, where cwctl looks (see https://github.com/eclipse/codewind-installer/blob/master/pkg/remote/deploy.go#L79).

This means that unless an IKS user uses a third party tool to add the IKS kube config to `~/.kube/config` (or manually adds it there), cwctl will fail to deploy Codewind on IKS. Instead, Cwctl will try to install Codewind on the last-active cluster in `~/.kube/config`:
```
johns-mbp-3:latest johncollier$ ./cwctl --insecure install remote \
>     --namespace keycloak \
>     --kadminuser admin \
>     --kadminpass admin \
>     --krealm codewind \
>     --kclient codewind \
>     --kdevuser developer \
>     --kdevpass developer \
>     --ingress codewind-iks-7674b4bd9abbdeea0be228236d5275c9-0000.us-south.containers.appdomain.cloud
INFO[0000] Checking namespace keycloak exists           
INFO[0030] Creating keycloak namespace                  
ERRO[0060] Unable to create keycloak namespace: Post https://api.crc.testing:6443/api/v1/namespaces: dial tcp 192.168.64.39:6443: i/o timeout 
ERRO[0060] Error: rem_create_namespace - Post https://api.crc.testing:6443/api/v1/namespaces: dial tcp 192.168.64.39:6443: i/o timeout 
```

To fix this, Cwctl should check for a kube config in the `KUBECONFIG` environment variable first, before trying going to `~/.kube/config`.

**Steps to reproduce:**
1. Deploy an IKS cluster.
2. Configure your machine against the cluster and export the Kube config it gives you
3. Set the default storage class to `ibmc-file-bronze/silver/gold-gid`
4. Try to use cwctl to install Codewind. It will either fail or install cwctl on the wrong cluster.

**Comment by bsteinfeld** [comment]
First of all I would *REALLY* appreciate if the environment variable  `KUBECONFIG`  would override the default kubeconfig - I'm experiencing this issue and have needed to make various workarounds to get things working.

Moreover, there seems to be more to this issue. When I try to run `cwctl` from within a k8s pod itself, it does *not* ready the default `$HOME/.kube/config` file, it instead seems to use the pod's serviceaccount credentials. This is a blocking issue for me, and moreover is very confusing.

**Comment by johnmcollier** [comment]
@bsteinfeld Yeah, that's because we currently get the in-cluster config first, then fall back on `$HOME/.kube/config` instead: See https://github.com/eclipse/codewind-installer/blob/master/pkg/remote/deploy.go#L76

We should probably change the ordering around:
1) Check for config under $KUBECONFIG
2) Check for config under `$HOME/.kube/config`
3) Use the 'In-cluster config' if present.

**Comment by bsteinfeld** [comment]
@johnmcollier I agree 100% with your suggested ordering!

**Comment by jgwest** [comment]
I built this from `master` after the PR went in, and tested it on my local cluster (which is only accessible via a KUBECONFIG env config), and am happy to report it works great! 👍 🎉
