### ISSUE TITLE
VSCode bad link on start page

### ISSUE THREAD

**Issue by james-wallis** [eclipse/codewind#2057]
Version: Master

On the startup page there a couple of dead links:
`Docs` -> `Performance Monitoring`:
* Is https://www.eclipse.org/codewind/performance.html which gives 404
* Should be changed to https://www.eclipse.org/codewind/guide_performance.html which is what the docs use

`Quick Start` -> `locally`:
* Is https://www.eclipse.org/codewind/mdt-vsc-firstproject.html
* Maybe should be https://www.eclipse.org/codewind/mdt-vsc-overview.html as `remotely` send me to the remote overview page (I can't find an equivalent for a first project page).

@tetchel

**Comment by james-wallis** [comment]
Could a link to the `Codewind Java Profiler` also be added to the `Useful Extensions` section?
https://marketplace.visualstudio.com/items?itemName=IBM.codewind-java-profiler

**Comment by tetchel** [comment]
Both of these pages exist and haven't been published yet

The Java profiling extension is featured on the Useful Extensions page, i'm just not finished working on that
