### ISSUE TITLE
Import project with the same directory name but different absolute paths

### ISSUE THREAD

**Issue by james-wallis** [eclipse/codewind#2061]
**Codewind version:** Master
**OS:** MacOS
**IDE:** VSCode

**Description of the enhancement:**

I should be able to import two separate projects from different places on disk that happen to have the same directory name.
For example:
`/user/temp/nodejsproject` and `/user/github/nodejsproject`.
Codewind see these and tries to create a project with the name `nodejsproject`.

I also think I should be able to import a project twice if I really want to?

**Proposed solution:** 

Potentially: Give the user the option to change the name for imported projects?

**Comment by james-wallis** [comment]
/kind bug
Not sure if enhancement or bug so I'll add the bug tag too. Feel free to remove any.

**Comment by tetchel** [comment]
So far, project name == project dirname. Is there any reason in portal/turbine why changing this would cause problems?

**Comment by jgwest** [comment]
Proposed solution sounds like it would be at the IDE level, so assigning those areas.

**Comment by tetchel** [comment]
@james-wallis did you fix this? I don't see a PR linked. :stuck_out_tongue_winking_eye:
