### ISSUE TITLE
SVT: [VS Code] "Add Existing Project" feature doesn't work

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#2063]
**Codewind version:** 0.9.0
**OS:** MacOS Mojave 10.14.6

**IDE extension version:** 0.9.0
**IDE version:** Code 1.41.1

**Description:** "Add Existing Project" feature doesn't work

<img width="444" alt="Screen Shot 2020-02-06 at 9 52 48 AM" src="https://user-images.githubusercontent.com/49531960/73948230-b411a080-48c6-11ea-88b5-3054ae862356.png">

**Steps to reproduce:**
1. Install and start Codewind 0.9.0
2. Attempt to import an existing project

@jagraj

**Comment by stalleyj** [comment]
@sujeilyfonseca Can you add a zip of the project you were trying to import please

**Comment by sujeilyfonseca** [comment]
@stalleyj, the error appears immediately after selecting "Add Existing Project". Codewind doesn't even allow me to select the project to import.

**Comment by tetchel** [comment]
Bizarrely, I can't reproduce this. Can you upload a screen recording?

**Comment by tetchel** [comment]
Oh! This may happen if you don't have any workspace folders open. I will fix it

**Comment by sujeilyfonseca** [comment]
@tetchel you're right. The problem occurs if the user doesn't have an open workspace.

![](https://user-images.githubusercontent.com/49531960/73954953-8df0fe00-48d0-11ea-9559-003f589e5e36.gif)

**Comment by sujeilyfonseca** [comment]
I verified this issue with the latest Codewind 0.9.0, and I no longer reproduce this problem.

**Comment by tetchel** [comment]
But I didn't merge the fix yet 😅
