### ISSUE TITLE
SVT: [VS Code] Codewind is allowing to create projects with invalid characters in their names, which eventually leads to a failure in the project creation

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#2064]
**Codewind version:** Latest & 0.9.0 
**OS:** MacOS Mojave 10.14.6

**IDE extension version:** 0.9.0
**IDE version:** 1.41.1

**Description:** Codewind is allowing to create projects with invalid characters in their names, which eventually leads to a failure in the project creation. The error message that appears after the failure is not accurate with the root of the problem.

<img width="1674" alt="Screen Shot 2020-02-06 at 9 31 02 AM" src="https://user-images.githubusercontent.com/49531960/73947267-2f725280-48c5-11ea-9c25-e41fb2dbb61e.png">

<img width="797" alt="Screen Shot 2020-02-06 at 9 33 10 AM" src="https://user-images.githubusercontent.com/49531960/73947286-35683380-48c5-11ea-8634-58488efb3db3.png">

<img width="606" alt="Screen Shot 2020-02-06 at 9 40 18 AM" src="https://user-images.githubusercontent.com/49531960/73947318-4022c880-48c5-11ea-9fdc-fe2319af7a67.png">

<img width="444" alt="Screen Shot 2020-02-06 at 9 33 22 AM" src="https://user-images.githubusercontent.com/49531960/73947301-3ac57e00-48c5-11ea-929d-f118a7c52673.png">

**Steps to reproduce:**
1. Install and start Codewind
2. Start a project creation process
3. Write an invalid project name
4. Select a parent directory 
5. Error "project type is invalid" will appear

@jagraj

**Comment by malincoln** [comment]
@sujeilyfonseca pls verify and close. Thanks

**Comment by sujeilyfonseca** [comment]
I verified this issue with the latest Codewind 0.9.0, and I no longer reproduce this problem.
