### ISSUE TITLE
Something needs to be done about Jenkins PR Merge and Branch Test inconsistency

### ISSUE THREAD

**Issue by maysunfaisal** [eclipse/codewind#2067]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**

I have noticed that our tests have been very intermittent. Sometimes when the PR test `continuous-integration/jenkins/pr-merge` passes, the test after the merge `continuous-integration/jenkins/branch` fails.

Are these running the same test suite? If yes, we should investigate why they're sometimes so inconsistent like this in the screenshot, when all the PR passed but after merging they fail. It doesn't look good when ppl look at commits and see us merging code with red crosses.

/kind test
/priority hot

I am going to assign it hot because otherwise no one is going to take a look at it, as PR tests have been fine and we're merging code.

![Screen Shot 2020-02-06 at 10 34 00 AM](https://user-images.githubusercontent.com/31771087/73952601-29806f80-48cd-11ea-8d48-32b5ca943056.png)

**Comment by stalleyj** [comment]
@maysunfaisal Couldn't agree more that we have a big issue with intermittent tests.  We are working to regain confidence in the pfe unit/api tests. We have several issues raised that are currently being worked on to look at specific tests to get to the bottom of these issues. If you see other failed master builds, please raise an issue with detail of the test that failed and the corresponding logs. 
https://github.com/eclipse/codewind/issues/2219
https://github.com/eclipse/codewind/issues/2190
