### ISSUE TITLE
File watcher should ignore Eclipse/VSCode configuration files and folders

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#2072]
The Eclipse configuration files and folders that should be ignored for a project are:
- The `.project` file
- The `.classpath` file
- The `.options` file
- The `.settings` folder and everything underneath it

**Comment by tetchel** [comment]
how about `.vscode/*` while we're at it

**Comment by jgwest** [comment]
Link to original discussion of where this should be updated:
https://github.com/eclipse/codewind/issues/1996

**Comment by ssh24** [comment]
Should this be portal specific? I thought Turbine deals with file path ignore lists. Anyways, adding hot because of #2075 

/priority hot

**Comment by elsony** [comment]
Marking this as stopship given that this problem is causing the projects to keep on being built. I recommend to add those files to the portal file sync ignore list so we are not syncing those files.

**Comment by malincoln** [comment]
@tobespc pls investigate.  Thanks

**Comment by tobespc** [comment]
yes we can add those files to the ignore lists if that would help.  Are there any other files we should add whilst we are at it that would build issues?

**Comment by stalleyj** [comment]
So this seemed like it would be a straightforward fix but having updated the lists in both cwctl and pfe, I am still seeing the .project file inside of PFE.  The underlying functionality of sync is very complex since the addition of https://github.com/eclipse/codewind-installer/pull/304/files, continuing to investigate.

**Comment by malincoln** [comment]
@eharris369 pls verify and close. Thanks

**Comment by eharris369** [comment]
Looks good now.
