### ISSUE TITLE
Eclipse IDE documentation needs updating

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#2074]
The https://www.eclipse.org/codewind/mdteclipsemanagingprojects.html page needs updating based on changes to the code:

- When a user creates a new project or adds an existing project from the file system to Codewind it automatically imports the project now so this should not be needed anymore: `Once you have a project, the first thing you might want to do is import your project into the Eclipse workspace so you can start editing files. This also makes your source available for debugging.`
- Change `Open Project Overview` to `Project Overview`
- Change `Open Application Monitor` to `Application Monitor`
- Change `Open Performance Dashboard` to `Performance Dashboard`
- Change `Open Tekton Dashboard` to `Tekton Dashboard` - also for this item, it is only available on remote connections but there does not seem to be any mention of remote connections elsewhere in this document. At the top of the page it only refers to the local connection: `To create a new project or import an existing one, use the context menu on the Local Projects item in the Codewind Explorer view.` Also, this is now just called `Local` rather than `Local Projects`.
- I don't see the `Remove` menu item in there. This allows the user to remove the project from Codewind and optionally delete the project contents.

The following changes are needed for https://www.eclipse.org/codewind/mdteclipsedebugproject.html:
- Change all occurrences of `Microprofile/Java EE` to `MicroProfile`

Change the following in https://www.eclipse.org/codewind/mdteclipsetroubleshooting.html:
- Change all occurrences of `Local Projects` to `Local`.  If we are documenting remote then it would be better to say `Try refreshing by right-clicking on your connection in the Codewind Explorer view` (use connection instead of the specific Local connection).

**Comment by micgibso** [comment]
- https://www.eclipse.org/codewind/mdteclipsemanagingprojects.html no longer exists in new structure.
  Restore/create new Project actions file and place in TOC before the Project settings file. Make generic.
- https://www.eclipse.org/codewind/mdteclipsedebugproject.html no longer exists in new structure
  Consider content.
- https://www.eclipse.org/codewind/mdteclipsetroubleshooting.html no longer exists in new structure
  Consider content.

**Comment by micgibso** [comment]
Have put all changes on PR https://github.com/eclipse/codewind-docs/pull/389/files which restores the Project actions topic and makes it generic across all IDEs. 
The remaining two topics no longer exist in our source.
