### ISSUE TITLE
Uninstalling images instructions are not correct

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#2076]
https://www.eclipse.org/codewind/mdt-vsc-uninstall.html

For step 2, there is a command for this. After stopping codewind (step 1) you can then remove the images by right-clicking the same item and clicking `Remove Local Codewind Images`.

The paths are also not correct (they're versioned 0.2.0)! It should be `~/.codewind/<version>/cwctl` (mac/linux) or `%USERPROFILE%\.codewind/<version>/cwctl` (windows). but it's probably better to just direct them to the `Remove Local Codewind Images` command which accomplishes the same thing.

**Comment by sishida** [comment]
@tetchel Thank you for catching this! I have updated the instructions based on your explanation and what I saw in my UI:
<img width="582" alt="Screen Shot 2020-02-06 at 5 39 27 PM" src="https://user-images.githubusercontent.com/21180723/73984977-fe674180-4907-11ea-9515-91932b4a3914.png">

Could you please review the PR? https://github.com/eclipse/codewind-docs/pull/348 Thank you!

**Comment by sishida** [comment]
The PR https://github.com/eclipse/codewind-docs/pull/348 is merged. Closing this issue. 🎉
