### ISSUE TITLE
SVT:Eclipse:After 0.8 to 0.8.1 migration Codewind disabled appsody projects.

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#2082]
**Codewind version:** 0.8.1
**OS:** Windows

**Che version:** 
**IDE extension version:** 0.8.0 to 0.8.1 migration
**IDE version:** Eclipse 2019-09
**Kubernetes cluster:**

**Description:**
I created couple of Appsody projects and 2 projects from default templates and after successful build and running then I did migration from Codewind 0.8.0 to 0.8.1 ifix then appsody projects disabled but default projects built successfully. 

![image](https://user-images.githubusercontent.com/713849/73983235-f4434400-4903-11ea-9aae-cfda9356ff18.png)

**Steps to reproduce:**
1. Install Eclipse 0.8.0 on windows.
2. Create two appsody projects and two projects from default templates.
3. After successful build and running then migrate to 0.8.1.
4. After Codewind 0.8.1 started then appsody projects disabled. 

[pfe.txt](https://github.com/eclipse/codewind/files/4168016/pfe.txt)

**Workaround:**

**Comment by makandre** [comment]
I was not aware we're having a 0.8.1 ifix.  There's no 0.8.1 release of the appsody extension hence the 0.8.1 PFE probably does not have a copy of the extension.  Although the existing 0.8.0 appsody extension installed to the workspace should have still worked, so this will need to be investigated.

**Comment by makandre** [comment]
@jagraj Could you `ls` the contents of `/codewind-workspace/.extensions` inside PFE?

**Comment by tetchel** [comment]
you have to make a 0.8.1 branch for the appsody extension because the jenkins build will look for the matching branch https://github.com/eclipse/codewind/blob/master/Jenkinsfile#L9

**Comment by tetchel** [comment]
I can copy 0.8.0 to 0.8.1 quickly and push it to https://github.com/eclipse/codewind-appsody-extension/ if you like.

**Comment by tetchel** [comment]
The jenkins build expects there to be a matching appsody and odo extension version available, you can see the errors here:
```
15:15:48  [33m[06/02/20 20:12:52 /portal/modules/ExtensionList.js] [WARN][39m Failed to install codewind-appsody-extension-0.8.1.zip
15:15:48  [33m[06/02/20 20:12:52 /portal/modules/ExtensionList.js] [WARN][39m { Error: Command failed: unzip /extensions/codewind-appsody-extension-0.8.1.zip -d /codewind-workspace/.extensions/
15:15:48    End-of-central-directory signature not found.  Either this file is not
15:15:48    a zipfile, or it constitutes one disk of a multi-part archive.  In the
15:15:48    latter case the central directory and zipfile comment will be found on
15:15:48    the last disk(s) of this archive.
15:15:48  unzip:  cannot find zipfile directory in one of /extensions/codewind-appsody-extension-0.8.1.zip or
15:15:48          /extensions/codewind-appsody-extension-0.8.1.zip.zip, and cannot find /extensions/codewind-appsody-extension-0.8.1.zip.ZIP, period.
```

@josephca the curl commands [here](https://github.com/eclipse/codewind/blob/master/Jenkinsfile#L182) should pass the `-f` flag so the command and therefore the build fails if the extensions are not found

**Comment by tetchel** [comment]
There's no ODO extension either @GeekArthur

**Comment by makandre** [comment]
If a corresponding extension version is not found we probably should have packaged the last available version. 

But yes cutting a 0.8.1 appsody extension is a quick way to fix this.

**Comment by tetchel** [comment]
done (for appsody, not yet for odo)

**Comment by makandre** [comment]
@tetchel we should bump the version could you approve and merge https://github.com/eclipse/codewind-appsody-extension/pull/86

**Comment by GeekArthur** [comment]
I don't think we have functional tests (tests for odo and appsody) for any Jenkins build, so currently we can't catch issues for extensions from Jenkins build. Seems like the root cause of this issue is we don't have 0.8.1 release/branch/download site contents for extensions (odo and appsody), @josephca IIRC we have the mechanism of automatically creating release/branch/download site contents for extensions (odo and appsody) with the Codewind iFix, not sure why we don't have those for 0.8.1 (eg. we have those for extensions for 0.6.1). @tetchel Since it's a general issue for extensions, can you do the same thing for odo?

**Comment by tetchel** [comment]
ok, there are builds for both appsody and odo now so hopefully [the next build](https://ci.eclipse.org/codewind/job/Codewind/job/codewind/job/0.8.1/) should be working.

**Comment by josephca** [comment]
> The jenkins build expects there to be a matching appsody and odo extension version available, you can see the errors [here](https://ci.eclipse.org/codewind/job/Codewind/job/codewind/job/0.8.1/5/consoleFull)
> 
> ```
> 15:15:48  �[33m[06/02/20 20:12:52 /portal/modules/ExtensionList.js] [WARN]�[39m Failed to install codewind-appsody-extension-0.8.1.zip
> 15:15:48  �[33m[06/02/20 20:12:52 /portal/modules/ExtensionList.js] [WARN]�[39m { Error: Command failed: unzip /extensions/codewind-appsody-extension-0.8.1.zip -d /codewind-workspace/.extensions/
> 15:15:48    End-of-central-directory signature not found.  Either this file is not
> 15:15:48    a zipfile, or it constitutes one disk of a multi-part archive.  In the
> 15:15:48    latter case the central directory and zipfile comment will be found on
> 15:15:48    the last disk(s) of this archive.
> 15:15:48  unzip:  cannot find zipfile directory in one of /extensions/codewind-appsody-extension-0.8.1.zip or
> 15:15:48          /extensions/codewind-appsody-extension-0.8.1.zip.zip, and cannot find /extensions/codewind-appsody-extension-0.8.1.zip.ZIP, period.
> ```
> 
> @josephca the curl commands [here](https://github.com/eclipse/codewind/blob/master/Jenkinsfile#L182) should pass the `-f` flag so the command and therefore the build fails if the extensions are not found

@tetchel Good catch. Do you mind adding the '-f' flag to the Jenkinsfile?

**Comment by josephca** [comment]
> I don't think we have functional tests (tests for odo and appsody) for any Jenkins build, so currently we can't catch issues for extensions from Jenkins build. Seems like the root cause of this issue is we don't have 0.8.1 release/branch/download site contents for extensions (odo and appsody), @josephca IIRC we have the mechanism of automatically creating release/branch/download site contents for extensions (odo and appsody) with the Codewind iFix, not sure why we don't have those for 0.8.1 (eg. we have those for extensions for 0.6.1). @tetchel Since it's a general issue for extensions, can you do the same thing (copy 0.8.0 to 0.8.1 then push to https://github.com/eclipse/codewind-odo-extension) for odo?

@GeekArthur We should've created '0.8.1' branch manually for 'odo' then the download site will have the corresponding folder (I.e. 0.8.1). It's good to know that we also need rebuilds for extensions for iFix.

**Comment by tetchel** [comment]
@jagraj are you unblocked?

**Comment by sujeilyfonseca** [comment]
We verified this issue with the latest Codewind 0.8.1, and we no longer reproduce this problem.

**Comment by jagraj** [comment]
All good now, closing this now.
