### ISSUE TITLE
Codewind Node Profiler does not work on Windows

### ISSUE THREAD

**Issue by mattcolegate** [eclipse/codewind#2085]
**Codewind version:** latest 07/02/2020
**OS:** Windows 10

**Che version:** N/A
**IDE extension version:** VSCode latest 07/02/2020
**IDE version:** VSCode
**Kubernetes cluster:** N/A

**Description:**
After running performance load againast a Node.js project using VSCode on Windows 10, upon returning to the Explorer view and opening .js source files, no code highlighting has taken place. The Codewind Node.js Profiling logs show the following:
```
hasWorkspaceFolderCapability = true
Workspace project folders are: null
Profiling Toggled On
getCodewindProjectFolders - found folder: { uri: 'file:///c%3A/cw-projs/thurs06Node1', name: 'thurs06Node1' }
Pathname is: /c%3A/cw-projs/thurs06Node1
[Error: ENOENT: no such file or directory, scandir 'c:\c%3A\cw-projs\thurs06Node1'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'c:\\c%3A\\cw-projs\\thurs06Node1'
}
Finding project for: /c%3A/cw-projs/thurs06Node1/server/server.js 
```

**Steps to reproduce:**

1. Create a Node.js default template project using VSCode on Windows 10
1. Open the performance dashboard and run several load tests.
1. Go back to VSCode and open a .js source file (e.g. server/server.js).
1. Observe no code highlighting. Open the Codewind Node.js Profiling logs and observe the above output.

**Workaround:** 

None.

**Comment by mattcolegate** [comment]
This issue is to do with the way that filePaths are being represented inside the code profilier - it seems that the various textDocument.uri and Workspace.uris are mangling both the Windows drive letter and the directory separators. When we try to use them to investigate the file system for directory and file discovery, the paths aren't recognised and errors occur. This error is fairly deep - as well as several references to the underlying file system vs the VSCode representation of it, the tree parsing of the samples the profiler gathers are also indexed by path names! This will require careful coding to ensure the minimal set of changes to make this work on Windows whilst retaining MacOS compatability.

**Comment by tetchel** [comment]
I haven't looked at the implementation or anything, but when you turn a `vscode.Uri` that points to a file into a string, make sure to use `uri.fsPath` not `uri.toString()`.

**Comment by mattcolegate** [comment]
Awaiting PR merge
