### ISSUE TITLE
SVT:got into NPE when creating python project from eclipse plugin

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#209]
**Codewind version:** 0.3
**OS:** WIndows 10

**Che version:**
**IDE extension version:** latest (0.3.0.v201908161735)
**IDE version:** 
Eclipse IDE for Enterprise Java Developers.
Version: 2019-06 (4.12.0)
Build id: 20190614-1200
OS: Windows 10, v.10.0, x86_64 / win32
Java version: 1.8.0_201

**Kubernetes cluster:**

**Description:**
I got into NPE when creating projects from codewind python template.

**Steps to reproduce:**
1. Install Eclipse plugin
2. Create various project types
3. Create python project as well.
4. Got into this exception.

![image](https://user-images.githubusercontent.com/713849/63263100-ac493b80-c255-11e9-9906-de355814d391.png)
[.log](https://github.com/eclipse/codewind/files/3515708/default.log)

**Workaround:** 

@eharris369

**Comment by tetchel** [comment]
From the logs:

```
!ENTRY org.eclipse.ui.ide 4 0 2019-08-19 07:39:02.961
!MESSAGE 
!STACK 0
java.lang.NullPointerException
	at org.eclipse.jst.ws.jaxrs.ui.internal.importer.JaxRsConfigurator.canConfigure(JaxRsConfigurator.java:67)
	at org.eclipse.ui.internal.wizards.datatransfer.SmartImportJob.importProjectAndChildrenRecursively(SmartImportJob.java:506)
	at org.eclipse.ui.internal.wizards.datatransfer.SmartImportJob.run(SmartImportJob.java:255)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

It looks like the Smart Import is trying to import this as a java/jaxrs project, which it obviously is not.

**Comment by eharris369** [comment]
This is exactly the same as https://github.com/eclipse/codewind-eclipse/issues/89

**Comment by beccabau** [comment]
Codewind version: 0.3
OS: MacOS Mojave 

Che version:
IDE extension version: latest (0.3.0.v201908161735)
IDE version:
Eclipse IDE for Enterprise Java Developers.
Version: 2019-06 (4.12.0)
Build id: 20190614-1200
OS: macOS Mojave, Version 10.14.6

Description:
I got into NPE when creating projects from codewind python template on mac local, eclipse.

From Jag's steps to reproduce, I ran into the same problem right after creating Python:

- Install Eclipse plugin
- Create various project types
**- Create python project.**
- immediate hit NPE

seen on mac as well 
![image](https://user-images.githubusercontent.com/13971834/63292917-c9e9c580-c294-11e9-8631-e253447d8edb.png)

**Comment by naveenkaratekid** [comment]
I've also seen this issue locally on Eclipse as well:

Codewind version 0.3
Codewind Extension Version: 0.3.0v201908161735
MacOS Mojave 10.14.6
Eclipse Build 06-2019 Version 4.12.0

Issue: Getting NPE when creating Python projects in Codewind in Eclipse Local on MacOS.

I also followed Jag's reproduce steps:
Install Codewind in Eclipse
Start up Codewind
Create new project, and choose Python template

<img width="362" alt="Screen Shot 2019-08-15 at 11 23 37 AM" src="https://user-images.githubusercontent.com/19738071/63361032-69fb2980-c33d-11e9-9adf-e7090de7ffc6.png">

**Comment by jagraj** [comment]
Looks like this issue is consistent with python projects.

**Comment by jagraj** [comment]
I have seen same problem with swift project as well.  I am also attaching .log file from workspace.
[.log](https://github.com/eclipse/codewind/files/3522061/default.log)


![image](https://user-images.githubusercontent.com/713849/63373773-7f308200-c356-11e9-81db-f2852ffea019.png)

**Comment by naveenkaratekid** [comment]
@jagraj So did I. At times I got NPE when creating a Swift project in Codewind in Eclipse

<img width="362" alt="Screen Shot 2019-08-15 at 11 26 35 AM" src="https://user-images.githubusercontent.com/19738071/63375574-0cc1a100-c35a-11e9-9c45-f2d664a4e942.png">

**Comment by bsbyrd1** [comment]
The next Eclipse build should fix this. Carl will follow up with Keith on this one to find out why it's not closed, since it's been committed already.

**Comment by jgwest** [comment]
Here is a link to the latest development build of Eclipse 2019.09, which should include the fix:
https://hudson.eclipse.org/packaging/job/simrel.epp-tycho-build/526/artifact/org.eclipse.epp.packages/archive/
(look for `eclipse-jee-2019-09-M2-` for your appropriate platform)

This is the relevant commit:
https://github.com/eclipse/webtools.webservices/commit/4880e0e0d243f0ca6bd51bca4bc97e65985a2226

**Comment by cccanderson** [comment]
Keith closed bug 541220 - it was an oversight.

**Comment by eharris369** [comment]
This is fixed in Eclipse 2019-09.

**Comment by jagraj** [comment]
Verified on 2019-09 and I no longer see NPE.
