### ISSUE TITLE
Setup cronjob for turbine performance test

### ISSUE THREAD

**Issue by ssh24** [eclipse/codewind#2091]
**Description of the enhancement:**
We now have a full performance test suite. We should go ahead and set up a cronjob that runs nightly to report us results. There should be two cronjobs:
1. Runs nightly against master and we compare each nights result with the night before to see any performance deterioration
2. Runs when there is a DCUT to compare the current DCUT with the previous DCUT to see any performance deterioration

/area iterative-dev
/kind test

**Comment by rajivnathan** [comment]
In addition to the cronjobs it would be good to have an easy way to compare results between releases.

**Comment by ssh24** [comment]
Created https://github.com/eclipse/codewind/issues/2254 for the above comment
