### ISSUE TITLE
SVT: Default projects are failing on remote (0.8.1)

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#2094]
**Codewind version:** 0.8.1
**OS:** Mac OS Mojave 10.14.6 and VM with Windows 10

**IDE extension version:** 0.8.1
**IDE version:** Code 1.42.0, Code 1.41.1, Eclipse 2019-09 , and Eclipse 2019-06

**Description:** Default projects are failing on remote (0.8.1)

<img width="1674" alt="Screen Shot 2020-02-07 at 10 56 20 AM" src="https://user-images.githubusercontent.com/49531960/74044099-8432cd80-4998-11ea-899a-6434e17f0781.png">

<img width="745" alt="Screen Shot 2020-02-07 at 10 58 21 AM" src="https://user-images.githubusercontent.com/49531960/74044233-c5c37880-4998-11ea-8c0e-ce48609a0282.png">

**Logs:**
[codewind-pfe.txt](https://github.com/eclipse/codewind/files/4171743/codewind-pfe.txt)

```
Helm chart install stage failed for cw-default-gogo
Flag --recreate-pods has been deprecated, functionality will no longer be updated. Consult the documentation for other methods to recreate pods
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Service.metadata.ownerReferences[0]): missing required field "kind" in io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference, ValidationError(Service.metadata.ownerReferences[0]): missing required field "name" in io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference, ValidationError(Service.metadata.ownerReferences[0]): missing required field "uid" in io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference, ValidationError(Service.metadata.ownerReferences[1]): missing required field "apiVersion" in io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference]
```

```
Helm chart install stage failed for remote-op
Flag --recreate-pods has been deprecated, functionality will no longer be updated. Consult the documentation for other methods to recreate pods
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Service.metadata.ownerReferences[0]): missing required field "kind" in io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference, ValidationError(Service.metadata.ownerReferences[0]): missing required field "name" in io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference, ValidationError(Service.metadata.ownerReferences[0]): missing required field "uid" in io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference, ValidationError(Service.metadata.ownerReferences[1]): missing required field "apiVersion" in io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference]
```

@DavidG1011 and @naveenkaratekid also reproduced this problem.
@jagraj

**Comment by tetchel** [comment]
@johnmcollier what is this

**Comment by johnmcollier** [comment]
https://github.com/eclipse/codewind/pull/1976 has to be backported to 0.8.1

**Comment by johnmcollier** [comment]
https://github.com/eclipse/codewind/pull/2097

**Comment by johnmcollier** [comment]
@sujeilyfonseca Can you verify?

**Comment by sujeilyfonseca** [comment]
I verified this issue with the latest Codewind 0.8.1, and I no longer reproduce this problem.

<img width="440" alt="Screen Shot 2020-02-07 at 3 12 27 PM" src="https://user-images.githubusercontent.com/49531960/74062481-5e1f2480-49bc-11ea-8a1c-16aaaf1c7c26.png">
