### ISSUE TITLE
SVT:open application is blank for microprofile java and spring projects

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#210]
**Codewind version:** 0.3
**OS:** WIndows 10

**Che version:**
**IDE extension version:** latest (0.3.0.v201908161735)
**IDE version:** 
Eclipse IDE for Enterprise Java Developers.
Version: 2019-06 (4.12.0)
Build id: 20190614-1200
OS: Windows 10, v.10.0, x86_64 / win32
Java version: 1.8.0_201

**Kubernetes cluster:**

**Description:**
Open application is blank for Java microprofile and spring projects.

**Steps to reproduce:**
1. Install Eclipse plugin
2. Create Java microprofile and spring projects from the templates.
3. Open application displays blank page.

Please mark this issue as "stopship" for codewind 0.3 release.

![image](https://user-images.githubusercontent.com/713849/63265079-b02b8c80-c25a-11e9-8963-be7acf2d871d.png)

**Workaround:** 

No workaround. 

@eharris369 @tobespc

**Comment by tetchel** [comment]
does it work in vs code?

**Comment by eharris369** [comment]
If this is Windows only then it is probably the same as https://github.com/eclipse/codewind-eclipse/issues/126.  If you change the browser to an external browser does it work (Window > Web Browser)?

**Comment by jagraj** [comment]
I copied same link and tried to access in external browser and I still see same problem.

**Comment by jagraj** [comment]
I no longer see this problem with the latest images. I can access both Java and Spring endpoint URLs.

**Comment by tetchel** [comment]
🤔
