### ISSUE TITLE
(metrics) SVT: Performance Dashboard page is not refreshed after performing a load test

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#2101]
**Codewind version:** 0.8.1
**OS:** Mac OS Mojave 10.14.6 and VM with Windows 10

**IDE extension version:** 0.8.1
**IDE version:** Code 1.41.1

**Description:** Performance Dashboard page is not refreshed after performing a load test. Users should refresh the page if they don't see the test result in the history table.

<img width="1404" alt="Screen Shot 2020-02-07 at 2 14 20 PM" src="https://user-images.githubusercontent.com/49531960/74058522-3926b380-49b4-11ea-8d05-09e6ada9393a.png">

<img width="1403" alt="Screen Shot 2020-02-07 at 2 13 52 PM" src="https://user-images.githubusercontent.com/49531960/74058525-3af07700-49b4-11ea-9ec6-5098803c999b.png">

@naveenkaratekid also reproduced the problem.

@jagraj

**Comment by tobespc** [comment]
If this for just the very first run or for every run?

**Comment by jagraj** [comment]
I have seen this mostly with appsody projects so far that I need to refresh the page to get the test results. I tried WebSphere liberty default project and test results displayed fine with out refresh. This looks like intermittent problem.

**Comment by markcor11** [comment]
It could be that the loadrunner and profiling collection have not totally completed. 

PFE Is supposed to send out a socket message to tell the dashboard the metrics data has been collected from the project and been written into PFE.  I suspect this is a timing issue with those socket messages being fired too soon and made worse in Liberty because of the agent attach/detach mechanisms.

**Comment by sujeilyfonseca** [comment]
@tobespc, I can reproduce the problem with the very first run. I don't see it happening for every run.

**Comment by tobespc** [comment]
this is ok for me, please retest

**Comment by markcor11** [comment]
I posted a PR last week to reload metrics after a load run has been completed https://github.com/eclipse/codewind/pull/2806 this was to handle the "completed" emit message rather than the old "idle" emit message

**Comment by sujeilyfonseca** [comment]
Thank you for working on this issue, @tobespc and @markcor11!

I verified this issue with the latest Codewind 0.12.0, and I can no longer reproduce the problem.
