### ISSUE TITLE
[odo] ODO project test failing on setting internal port using project specification

### ISSUE THREAD

**Issue by ssh24** [eclipse/codewind#2112]
**Description:**
Test failure on all types of ODO project
```
[0m  30) PFE - functional test
       Project Specific Suite: odo-python
         project test
           projectSpecification function
             set internalPort to -1 in .cw-settings file to check for serverless app:
[0m[31m     TypeError: Cannot read property 'ip' of undefined[0m[90m
      at Object.getContainerInfo (src/projects/projectUtil.ts:164:66)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```
/area iterative-dev
/kind test

**Comment by GeekArthur** [comment]
Currently odo project doesn't support internal port setting, we can do more investigation under this issue https://github.com/eclipse/codewind/issues/1374 to see if odo CLI has the capability.

**Comment by ssh24** [comment]
Ok, thanks. I will change the config for that test to not run for ODO projects as part of this issue

/assign
/pipeline in progress
