### ISSUE TITLE
SVT: [Che] Users get an error when importing a project if they cancel the action

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#2116]
**Codewind version:** 0.9.0
**OS:** Red Hat Enterprise Linux 7 (64 bit)

**Che version:** 7.5.1
**Kubernetes cluster:** OKD/Openshift 

**Description:** Users get an error when importing a project if they cancel the action

![che-import-error](https://user-images.githubusercontent.com/49531960/74180439-818cde00-4c0d-11ea-9cb9-4cd62528bfb9.gif)

**Steps to reproduce:**
1. Deploy a new Codewind 0.9.0 workspace
2. Click on "Add Existing Project"
3. Cancel the action

@jagraj

**Comment by johnmcollier** [comment]
@tetchel Is there anything that can be done to catch this error? Or is this outside of our control?

**Comment by tetchel** [comment]
it my bug

**Comment by tetchel** [comment]
it looks like when you cancel this wizard in VS Code it returns `undefined` but in Theia it returns `[]`

**Comment by tetchel** [comment]
should b fixed in latest

**Comment by malincoln** [comment]
@sujeilyfonseca pls verify and close. Thanks

**Comment by sujeilyfonseca** [comment]
I verified this issue with the latest Codewind 0.9.0, and I no longer reproduce this problem.
