### ISSUE TITLE
Create a new doc for detailing how application status works

### ISSUE THREAD

**Issue by rajivnathan** [eclipse/codewind#2117]
**Description of the enhancement:**

Understanding project status and working with the tools to resolve issues is a fairly common thing that users will encounter when first starting out with Codewind. For https://github.com/eclipse/codewind/issues/1812, we added some troubleshooting docs that could help users resolve some issues but it would be good to create a new doc that is in a more visible place to users and link to it from docs that talk about adding projects to Codewind.

If some of the information in the troubleshooting section overlaps with the new doc we can consider linking to the new doc from the troubleshooting doc?

**Plan**
- [ ] Create the new doc
- [ ] Update the troubleshooting doc to link to the new doc (if it makes sense)
- [ ] Update the link in the code: https://github.com/eclipse/codewind/blob/397019f11fd5fd1fd7f729cc2574ee38cf34326a/src/pfe/file-watcher/server/src/controllers/projectStatusController.ts#L55

Related issue: https://github.com/eclipse/codewind/issues/1812

**Comment by j-c-berger** [comment]
@rajivnathan and/or @sishida, feel free to assign this issue to me!
