### ISSUE TITLE
SVT:Che:Session already invalidated

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#2126]
**Codewind version:** 0.9.0
**OS:**  CoreOS

**Che version:** 7.5.1
**IDE extension version:** 0.9.0
**IDE version:** Theia 7.5.1
**Kubernetes cluster:**
OCP 4.3

**Description:**
I can not login to Che dashboard if one of the user's (jag) session is invalidated and tried to login again to other user (jag1). It always gives following this error message and I can not login any more. 
I also looked into Che github queue and this seems to be known problem and fix has been targeted for  7.8.0 Milestone release. (https://github.com/eclipse/che/issues/15798). 

I do not see any workaround here when I hit this problem. I just opened this issue to track this issue and close it once codewind start supporting Che 7.8.0 release. 

![image](https://user-images.githubusercontent.com/713849/74242822-9a000580-4cac-11ea-85d0-98957cb9a148.png)

```
HTTP Status 500 – Internal Server Error
java.lang.IllegalStateException: getAttribute: Session already invalidated
```

Here is the full stack from the failure.

```
java.lang.IllegalStateException: getAttribute: Session already invalidated
	org.apache.catalina.session.StandardSession.getAttribute(StandardSession.java:1153)
	org.apache.catalina.session.StandardSessionFacade.getAttribute(StandardSessionFacade.java:103)
	org.eclipse.che.multiuser.api.authentication.commons.filter.MultiUserEnvironmentInitializationFilter.doFilter(MultiUserEnvironmentInitializationFilter.java:117)
	org.eclipse.che.multiuser.keycloak.server.KeycloakEnvironmentInitializationFilter.doFilter(KeycloakEnvironmentInitializationFilter.java:88)
	org.eclipse.che.multiuser.machine.authentication.server.MachineLoginFilter.doFilter(MachineLoginFilter.java:76)
	org.eclipse.che.commons.logback.filter.RequestIdLoggerFilter.doFilter(RequestIdLoggerFilter.java:50)
	com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
	com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
```

**Steps to reproduce:**

**Workaround:**

**Comment by johnmcollier** [comment]
https://github.com/eclipse/codewind/issues/2203 Will block us from moving up to a newer Che version til it's resolved unfortunately.

**Comment by rajivnathan** [comment]
@jagraj John has updated 0.10.0 to use Che 7.9 so this can now be retested.

**Comment by jagraj** [comment]
This has been verified with Che 7.9.0 release. Closing this one.
