### ISSUE TITLE
No load-test files come across to local using the Java profiling on Windows

### ISSUE THREAD

**Issue by mattcolegate** [eclipse/codewind#2129]
**Codewind version:** latest (11/02/2020)
**OS:** Windows 10

**Che version:** N/A
**IDE extension version:** latest (11/02/2020)
**IDE version:** VSCode
**Kubernetes cluster:** N/A

**Description:**
After a load-test run on a Java project, hcd files fail to make it over to the local project workspace, despite them being present in the PFE's /codewind-workspace.

**Steps to reproduce:**

Start latest Codewind locally on Windows machine, connect to it using the latest VSCode plugin. Create and start a WebSphere Liberty Microprofile project. When it comes up, run several load tests against it from the Performance Dashboard. No `load-test` directory appears in the local project workspace.

**Workaround:** 

Manually copy the load-test directory from PFE to the local project directory.

**Comment by mattcolegate** [comment]
[PFELogNoLocalLoadTest.txt](https://github.com/eclipse/codewind/files/4186336/PFELogNoLocalLoadTest.txt)

**Comment by tobespc** [comment]
closing as this is now working
