### ISSUE TITLE
Open logs view when user clicks Show All Logs or adds a log from Manage Logs

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#2134]
**Codewind version:** 0.9.0

**Che version:** 7.5.1
**IDE extension version:** 0.9.0
**IDE version:** Che-Theia 7.5.1
**Kubernetes cluster:** OCP 4.3

**Description:**
After closing the logs view for a project in Che/Theia, it's not possible to re-open the logs view. The Theia logs don't show anything suspicious either:
```
[DBUG: 17:43:36.374 MCLogManager.js:109]: Showing all logs for pytest
[DBUG: 17:43:36.374 Requester.js:496]: Doing POST request to https://localhost:9090/api/v1/projects/3b0b3470-4cf5-11ea-b908-57d1d8facf80/logs
```

The Portal logs don't show any errors or failures either.

However, if I right click on a **new** project, the logs view does show up.

Video: https://ibm.box.com/s/7dxkn55voocutk1jv5gezs0hipgasl2v

**Steps to reproduce:**
1. Deploy Codewind on Che
2. Create a project
3. Click "Show all logs" and then close the logs view
4. Click on "Show all logs" again, no view will open

**Comment by tetchel** [comment]
The plugin is behaving correctly, the logs are already "open" in the logs view, but the logs view is hidden

![image](https://user-images.githubusercontent.com/8888438/74274220-b9fcec80-4cdf-11ea-99a7-ebb14fbd16db.png)

I could probably show that view automatically if you opened a new log or 'showed all', though.

**Comment by johnmcollier** [comment]
I'd say, since Theia doesn't make it clear to the user that they're just hidden, I'm in favour of auto-showing the view if "Show all logs" was pressed.
