### ISSUE TITLE
SVT: Eclipse : Project get into state [Running] [Build Queued: 1/1]

### ISSUE THREAD

**Issue by mmulholl** [eclipse/codewind#2135]
**Codewind version:**   Codewind tech preview	0.9.0.v202002111101	
**OS:** Mac

**Che version:**
**IDE extension version:**
**IDE version:** Eclipse
**Kubernetes cluster:**

**Description:**
Project gets into an inconsistent state: [Running] [Build Queued: 1/1]

The project is running and the application view is available. How the option the build the project is not available. This recurs in the pfe log:

[11/02/20 20:12:57 SVTPythonProject] [INFO] Build state changed for project: 7c6a2670-4d08-11ea-8714-13d6bea9b498 from: queued, to: queued, with message: projectStatusController.buildRank
[11/02/20 20:12:57 SVTPythonProject] [INFO] Emitting event 
 message: projectStatusChanged
 data: {
  "projectID": "7c6a2670-4d08-11ea-8714-13d6bea9b498",
  "buildStatus": "queued",
  "detailedBuildStatus": "Rank 1/1"
}

The overview shows the last build as 2:55:43 which matches with this in the log:

[32m[11/02/20 19:55:43 SVTPythonProject] [INFO][39m Build state changed for project: 7c6a2670-4d08-11ea-8714-13d6bea9b498 from: inProgress, to: success, with message:  
[32m[11/02/20 19:55:43 SVTPythonProject] [INFO][39m Emitting event 
 message: projectStatusChanged
 data: {
  "projectID": "7c6a2670-4d08-11ea-8714-13d6bea9b498",
  "buildStatus": "success",
  "detailedBuildStatus": " ",
  "lastbuild": 1581450943504,
  "appImageLastBuild": "1581450943504"
}

shortly after you see this:

[32m[11/02/20 19:55:44 SVTPythonProject] [INFO][39m Project 7c6a2670-4d08-11ea-8714-13d6bea9b498 file changed
[32m[11/02/20 19:55:44 SVTPythonProject] [INFO][39m Detected other file changes, Codewind will build the project
[32m[11/02/20 19:55:44 SVTPythonProject] [INFO][39m File change detected. Project will re-build.
[32m[11/02/20 19:55:44 SVTPythonProject] [INFO][39m Changed Files: [ >.project ]
[32m[11/02/20 19:55:44 SVTPythonProject] [INFO][39m Received all chunks.
[32m[11/02/20 19:55:44 SVTPythonProject] [INFO][39m Auto build is enabled, build proceeding...
[32m[11/02/20 19:55:44 SVTPythonProject] [INFO][39m Build state changed for project: 7c6a2670-4d08-11ea-8714-13d6bea9b498 from: success, to: inProgress
[32m[11/02/20 19:55:44 SVTPythonProject] [INFO][39m Emitting event 
 message: projectStatusChanged
 data: {
  "projectID": "7c6a2670-4d08-11ea-8714-13d6bea9b498",
  "buildStatus": "inProgress"
}
[32m[11/02/20 19:55:44 SVTPythonProject] [INFO][39m Build state changed for project: 7c6a2670-4d08-11ea-8714-13d6bea9b498 from: inProgress, to: queued, with message: projectStatusController.buildRank
[32m[11/02/20 19:55:44 SVTPythonProject] [INFO][39m Pushing project to build queue
[32m[11/02/20 19:55:44 SVTPythonProject] [INFO][39m Emitting event 
 message: projectStatusChanged
 data: {
  "projectID": "7c6a2670-4d08-11ea-8714-13d6bea9b498",
  "buildStatus": "queued",
  "detailedBuildStatus": "Rank 1/1"
}

The status then never changes. Here is the full log:
[codewindpfe.log](https://github.com/eclipse/codewind/files/4188106/codewindpfe.log)

**Steps to reproduce:**

It happens when I create a lots of projects at he same time.

**Workaround:**

**Comment by mmulholl** [comment]
Just checked and even editing a file does not cause a rebuild from this state so making this a stop shop as the only option seems to be remove the project and re-import.

**Comment by johnmcollier** [comment]
Seems like a dupe of https://github.com/eclipse/codewind/issues/2075, I believe 

CC @ssh24

**Comment by ssh24** [comment]
The actual cause for this is linked to #2072 but yeah it is a dupe of #2075

**Comment by mmulholl** [comment]
There us a test build here which reproduces the issue:

http://devexubdev.rtp.raleigh.ibm.com/opt/travisbuildlogs/26109276/

**Comment by rajivnathan** [comment]
@mmulholl looks like https://github.com/eclipse/codewind/issues/2072 should now be fixed. Can you please retry?

**Comment by mmulholl** [comment]
Ran the test which used to regularly see the issue five times and did not see the issue at all. I did see a project go into [Running] [Build Queued: n/x] but it did not remain in that state. 

Fix verified so closing issue.
