### ISSUE TITLE
SVT: Microclimate related information in Metrics Dashboard & Project Information

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#2137]
**Codewind version:** 0.9.0

**Description:** I reviewed the documentation we plan to release in the future using our internal link: http://codewind-docs.rtp.raleigh.ibm.com:4321/codewind/

In doing so, I found some sections with deprecated information (information related to Microclimate). Sarah and Jag asked me to open this issue to be aware of this problem.

**Understanding Application Metrics: http://codewind-docs.rtp.raleigh.ibm.com:4321/codewind/appmetrics.html**

1. We no longer name this feature "Application Metrics", the new term is "Metrics Dashboard". The menu item also uses this term.
2. There are several places that present old information that belongs to Microclimate. We need to update this document if we plan to use it. For example, the documentation mentions a "Run load" button, but we don't have that in Codewind (Metrics Dashboard). We have that in the Performance Dashboard. Furthermore, our profiling feature is through Java and Node JS Profilers for VS Code.

**Developing projects:**
http://codewind-docs.rtp.raleigh.ibm.com:4321/codewind/projectview.html
http://codewind-docs.rtp.raleigh.ibm.com:4321/codewind/checkingstatuses.html
http://codewind-docs.rtp.raleigh.ibm.com:4321/codewind/importing-existing-projects.html
http://codewind-docs.rtp.raleigh.ibm.com:4321/codewind/referencing-files.html

If we don't plan to use any of the mentioned documents, then we must plan to eliminate them.

@jagraj @sishida 

/priority stopship
/area docs

**Comment by johnmcollier** [comment]
A few of us spoke on slack regarding the `microclimate` references in http://codewind-docs.rtp.raleigh.ibm.com:4321/codewind/importing-existing-projects.html, and they're still needed for that doc.

The maven profile we use in Microprofile projects is still called `microclimate`, and so the import doc section on ensuring that profile is there, is still relevant.

**Comment by micgibso** [comment]
http://codewind-docs.rtp.raleigh.ibm.com:4321/codewind/projectview.html is no longer in the TOC.
http://codewind-docs.rtp.raleigh.ibm.com:4321/codewind/checkingstatuses.html - needs an update.
http://codewind-docs.rtp.raleigh.ibm.com:4321/codewind/importing-existing-projects.html - needs an update, however comment above noted.
http://codewind-docs.rtp.raleigh.ibm.com:4321/codewind/referencing-files.html - needs an update.

**Comment by sujeilyfonseca** [comment]
Thanks for working on this issue, @micgibso!

Here are some comments:

### metrics-dashboard.md (https://github.com/eclipse/codewind-docs/pull/356/files)

**1.	Accessing the Metrics Dashboard** 
o	Click “Metrics Dashboard” in the Codewind project…
<img width="468" alt="image" src="https://user-images.githubusercontent.com/49531960/74343197-ad78a280-4d78-11ea-81ff-5ead05415812.png">

**2.	Clicking the Run load button**
o	We don’t have this option in the Metrics Dashboard (Codewind)
<img width="468" alt="image" src="https://user-images.githubusercontent.com/49531960/74343418-047e7780-4d79-11ea-8108-6359735ba81c.png">

**3.	Viewing metrics information in the Summary tab**
o	“Resource Usage” instead of “Resource usage”
o	“...shows what Codewind…” instead of “...shows what Microclimate…”
<img width="468" alt="image" src="https://user-images.githubusercontent.com/49531960/74343425-09dbc200-4d79-11ea-8220-156e7e58a452.png">

<img width="314" alt="image" src="https://user-images.githubusercontent.com/49531960/74343448-119b6680-4d79-11ea-83fa-7dc59e5752d4.png">

**4.	Profiling Data Support**
o In Codewind, the load test data is obtained by running a load test using the Performance Dashboard. The directory is created in your project directory if Codewind Java Profiler or Codewind Node.js profiler is installed.
o For Java, the extension provides code highlighting showing relative time spent in Java methods based on profiling data collected through the Codewind load test feature. Once you execute a test, an hcd file will be created in `load-test/[timestamp]/xxxx.hcd`.
o For Node.js, the extension provides code highlighting showing relative time spent in JavaScript functions based on profiling data collected through the Codewind load test feature. Once you execute a test, a JSON file will be created in `load-test/[timestamp]/profiling.json`.

<img width="468" alt="image" src="https://user-images.githubusercontent.com/49531960/74343471-1c55fb80-4d79-11ea-9185-b9c5afcffec0.png">

 
o	This section contains references to the Microclimate in several areas, which could lead to incorrect instructions since we don't have some commands mentioned there:
<img width="468" alt="image" src="https://user-images.githubusercontent.com/49531960/74343488-224bdc80-4d79-11ea-94b9-035cf4d8128e.png">

o	We can use “with the Metrics Dashboard”
<img width="468" alt="image" src="https://user-images.githubusercontent.com/49531960/74343499-2677fa00-4d79-11ea-86c9-9ac1f6d2a7f8.png">

---

### http://codewind-docs.rtp.raleigh.ibm.com:4321/codewind/checkingstatuses.html

**1.	Application status**
o	I would suggest not only mention App logs or Build logs because we also have other types of log. As for example, Appsody projects only have `appsody.log`.
<img width="468" alt="image" src="https://user-images.githubusercontent.com/49531960/74343523-342d7f80-4d79-11ea-844f-1dd645d57312.png">

**2. Build status**
o	We need to verify if we still have `MC_MAX_BUILDS`

---

### http://codewind-docs.rtp.raleigh.ibm.com:4321/codewind/performance.html

**1. Prerequisites**
o	We also support the Performance Dashboard in Eclipse Che
<img width="268" alt="image" src="https://user-images.githubusercontent.com/49531960/74343568-44ddf580-4d79-11ea-823c-a0193518e696.png">

**2. “Accessing the Performance Dashboard” instead of “Accessing the performance dashboard” to be consistent with other pages**
o	Select “Performance Dashboard”
<img width="468" alt="image" src="https://user-images.githubusercontent.com/49531960/74344221-43f99380-4d7a-11ea-8a43-34bdfde432b7.png">

**3. Modifying the load test**
o	“Edit load run settings” instead of “Modify Parameters”

**Comment by micgibso** [comment]
Thanks for the comments @sujeilyfonseca . See PR https://github.com/eclipse/codewind-docs/pull/356 for the updated files. Thx!

**Comment by malincoln** [comment]
@sujeilyfonseca pls verify and close. Thanks

**Comment by micgibso** [comment]
@sujeilyfonseca New PR that resolves merge conflicts: https://github.com/eclipse/codewind-docs/pull/373

**Comment by sujeilyfonseca** [comment]
Thanks, @micgibso! I'm reviewing it to provide some final comments.

**Comment by sujeilyfonseca** [comment]
@micgibso, here are some additional comments:

**Profiling Data Support**
Remove my previous explanation for the profilers, as it would be better to keep a separate document to explain the Codewind Java Profiler and Codewind Node.js Profiler (VS Code):

<img width="775" alt="Screen Shot 2020-02-14 at 10 06 17 AM" src="https://user-images.githubusercontent.com/49531960/74542457-a89b2680-4f11-11ea-9412-a0b45c47a91f.png">

In codewind.dev, I previously saw a section to explain the Codewind Node.js Profiler for VS Code. I no longer see that in the internal documents.

---

To avoid confusion about the default profiling feature and profiler extensions, I would suggest adding something to specify that this is a default feature:

<img width="737" alt="Screen Shot 2020-02-14 at 10 08 31 AM" src="https://user-images.githubusercontent.com/49531960/74543102-cb7a0a80-4f12-11ea-9f5c-209f2ec63b34.png">

I’m not sure about the following bullets:
•    Run the load run for a minimum of ---_45 seconds_--- for enough profiling data to be gathered to generate the `profiling.json` file.
•    You can configure the load run time in the `config.json` file in the load-test directory. ---_The default time is 2 minutes_---.

You can retrieve profiling data with less than 45 second. Also, the default time varies in VS Code and Eclipse Che. I’ve seen 20 or 180 seconds.

---

It would be nice to get someone from the profiling dev team to review the remaining content for the Profiling Data Support, as I would like to have the right content for users. I’ve opened an issue for something that doesn’t work properly with this feature, so it doesn’t allow me to verify this content fully.

**Comment by micgibso** [comment]
Will get right on it...

**Comment by hhellyer** [comment]
@sujeilyfonseca - We recently changed the default length of a performance run. It used to be 20 but is now 180 as that was needed to get a good hcd file. We also lowered the number of concurrent requests as that was killing liberty appservers.
See :https://github.com/eclipse/codewind/pull/2186/files

**Comment by micgibso** [comment]
Changes in, have modifed the default to 180 and restored the advice for the time to run the test.

**Comment by micgibso** [comment]
Worked with Howard to complete on PR https://github.com/eclipse/codewind-docs/pull/373.
