### ISSUE TITLE
Scripts for docs on Windows and the linkchecker

### ISSUE THREAD

**Issue by micgibso** [eclipse/codewind#2142]
**Description:**
In the codewind-docs repo, there are two scripts for generating the help: `build.sh` and `serve.sh`. On Windows: 
- `build.sh` opens a window, reports that it's `Fixing file timestamp`, and then the window closes.
- `serve.sh` does the same.

**Steps to reproduce:**
From the command line, go to C:\GitHub\codewind-docs, type `.\build.sh` or `.\serve.sh`

**Workaround:** 
I've been able to build the help to date by using the following command:
`$ docker run --rm -it --volume="$PWD/docs:/srv/jekyll" --volume="$PWD/vendor/bundle:/usr/local/bundle" -p 4321:4321 jekyll/jekyll:3.8.5 jekyll serve --port 4321 --host 0.0.0.0`

...but I've had no joy running `build.sh` and hence cannot run the linkchecker. 

@sghung @travis1111 is this your area?

**Comment by sghung** [comment]
Sorry missed this notification, yes, this is our area. I have added our label

**Comment by sghung** [comment]
The scripts were made in Mac and linux, so there are operating specific utilities being called that are not available on Windows. We'd need to port this code to a Window power shell script to get this functionality working.

**Comment by sghung** [comment]
If you have the codewind website running locally, you can run:

`docker run --network="host" --rm -it linkchecker/linkchecker http://localhost:4321/codewind/ `

This will do the website checking for you in one line. You need to run this in another terminal and ensure your website is running on port 4321

**Comment by sghung** [comment]
I added Windows scripts via https://github.com/eclipse/codewind-docs/pull/462 and updated the README to let people know the limitation with the Windows scripts (it cannot set the "last updated" time correctly). @micgibso please verify and close.

**Comment by micgibso** [comment]
Thanks Steven, have tested them on my machine and they work as described. Closing...
