### ISSUE TITLE
Create suitable topics to be linked from Docs Landing Page

### ISSUE THREAD

**Issue by MelHopper** [eclipse/codewind#2150]
Note: This github issue blocks the New Landing Page design: https://github.com/eclipse/codewind/issues/2041

Note: This issue is related to https://github.com/eclipse/codewind/issues/1980 - ToC Restructure to improve user work flow. 

To ensure good user workflow from the signposting in our new Docs landing page, some overview topics need to be created.

Specifically:

### 1. a new local codewind topic for Jane  - now covered under https://github.com/eclipse/codewind/issues/2243
**'Using Codewind Locally'** 
- Add objectives
- Explain this is a pre-requisite for the Remote case
- Orient the user to the other ways Codewind can be used by signposting to a new topic _'3 configs of Codewind'.

This topic is linked from the docs LP 'step-by-step instructions' link within the download card for Local and Remote.

### 2. new topic for Jane or DevOps or SysAdmin 
**'3 configurations of Codewind'** - Now covered under https://github.com/eclipse/codewind/issues/2589

- Topic is for orienting user to the 3 different ways of using Codewind - local, remote, or as an application hosted on the cloud (Eclipse Che / browser-based).
- Uses diagrams to define the 3 configurations of Codewind.
- Signposts to the different tutorials
- References the different IDEs supported for each config - use IDE logos?

### 3. a new deploy remote codewind topic for Champ/Todd - DONE under a previous Github issue

**'Deploying Codewind Remotely

Linked via the docs LP section: _If you are a sysadmin / Devops, learn [how to deploy Codewind remotely](ADD TOPIC LINK)_

### 4. a new templates topic for Champ: to be actioned under a new Github Issue https://github.com/eclipse/codewind/issues/2842

- link to workingwithtemplates.html for now. 

Linked via the docs LP section: _If you are responsible for defining standards for application and runtime environments such as framework and software levels, see [ADD TOPIC]()_

**Comment by MelHopper** [comment]
Note that issue 'https://github.com/eclipse/codewind/issues/2151' will tick off some of the above topics that need creating.

**Comment by MelHopper** [comment]
Issue https://github.com/eclipse/codewind/issues/2241 will deal with the Champ topics.

**Comment by MelHopper** [comment]
Issue https://github.com/eclipse/codewind/issues/2243 will deal with creating the 'Using Codewind locally' topic.

**Comment by micgibso** [comment]
Hiya Mel, let's discuss before you resume work on this one, thanks.
