### ISSUE TITLE
Investigate/Add Codecov to the repositories

### ISSUE THREAD

**Issue by liamchampton** [eclipse/codewind#2153]
**Description of the enhancement:**
Investigate/Add Codecov to the Codewind repositories. This will show a label at the top of the `readme.md` displaying the % of code coverage from our test.

**Proposed solution/TODO:** 
We have now got the API key into Jenkins as a an environment variable. We need to upload the test collection from the Jenkins build to codecov which will update the label on the repositories.

**Comment by james-wallis** [comment]
/close
I've added Codecov to both `codewind` and `codewind-installer` for our Jenkins builds.
