### ISSUE TITLE
Performance dashboard: plotting multiple variables in the same graph

### ISSUE THREAD

**Issue by rachelwchen** [eclipse/codewind#216]
**Codewind version:** 0.2.0
**OS:** MacOS

**Description of the enhancement:**
During the usability testing of Codewind, we found an issue with the graph in the performance dashboard. Specifically, it was the issue with plotting multiple variables in the same graph. As shown in the screenshot below, when Y-axis represents the CPU, the units and scales of other variables (such as response, measured in ms and ranging from 0 to 2,000+) don't quite map to this Y-axis.

![image](https://user-images.githubusercontent.com/12159451/63292986-cac22d80-c27b-11e9-9d3e-61d62a51ebee.png)

**Proposed solution:** 
Not totally sure. We might have to break up the graph into smaller multiples.

**Comment by markcor11** [comment]
Originally we did have separate charts for each counter type however the behaviour you see is working to the latest design spec.  The Y-Axis labels and scale reflect the most recently selected counter chosen from the check-box list on the right hand side of the page.  If the user were to toggle 'hits', the Y-axis labels should change to show hit count values.

**Comment by rachelwchen** [comment]
Thanks for the explanation @markcor11! I see the merit of both (combining vs. separating). Maybe we can backlog this issue for now and revisit again when we receive more user feedback on this. Out of curiosity, what were some reasons for combining the graphs?

**Comment by markcor11** [comment]
@rachelwchen If I remember correctly,  the main reasons for switching to the single chart design was feedback from users seeing the early multi-chart prototype: 

1.  "I don't want to have to scroll up and down to see the different chart counters"
2.  "I always want to see Response Time first - its the most important counter"
3. "I want to be able to compare different counters eg. Response Time vs Hits or Memory vs CPU -  and be able to change between them quickly.

**Comment by tobespc** [comment]
closing as working as designed
