### ISSUE TITLE
Removing extraneous topics from the _documentations folder

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind#2163]
Remove extraneous topics from the codewind-docs/docs/_documentations folder.

The "Codewind files in-use post restructure 30-01-2020" file provides a list of topics to remove.

**Comment by micgibso** [comment]
I'll do this immediately the 0.9.0 release is out of the door.  Cross reference with https://github.com/eclipse/codewind-docs/wiki/List-of-links-and-files-with-similar-content to ensure nothing is deleted that is called by the UI and isn't in the new TOC.

**Comment by micgibso** [comment]
Two new issues raised on the back of this one:
https://github.com/eclipse/codewind/issues/2303 Topic called from VS Code but not in TOC		
https://github.com/eclipse/codewind/issues/2301 Error `/favicon.ico' not found]

**Comment by micgibso** [comment]
Removal complete, closing.
