### ISSUE TITLE
SVT: IntelliJ: Project fails to build when clicking "Build" on menu bar

### ISSUE THREAD

**Issue by naveenkaratekid** [eclipse/codewind#2166]
**Codewind version:0.9.0**
**OS:Windows**

**Che version:**
**IDE extension version:0.9.0**
**IDE version: IntelliJ IDEA 2019.3.3 (Community Edition)
   Build #IC-193.6494.35, built on February 11, 2020
   Runtime version: 11.0.5+10-b520.38 amd64
   VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
**

**Description:**
In IntelliJ, projects fail to build when you click ```Build Project``` via the menu bar. But they successfully build and run when you build the project via the Codewind view in IntelliJ

Screenshots:
![image](https://user-images.githubusercontent.com/19738071/74369290-1ffe7800-4da3-11ea-9ab2-b1a178410dd1.png)

Error messages from the build in IntelliJ:
```
Information:java: Errors occurred while compiling module 'intellij-apps-sp-def'
Information:javac 11.0.5 was used to compile java sources
Information:2/12/2020 2:20 PM - Build completed with 41 errors and 0 warnings in 9 s 414 ms
C:\codewind-workspace\intellij-apps-sp-def\src\main\java\application\LivenessEndpoint.java
Error:(17, 60) java: package org.springframework.boot.actuate.endpoint.annotation does not exist
Error:(18, 60) java: package org.springframework.boot.actuate.endpoint.annotation does not exist
Error:(19, 38) java: package org.springframework.stereotype does not exist
Error:(22, 2) java: cannot find symbol
  symbol: class Endpoint
Error:(23, 2) java: cannot find symbol
  symbol: class Component
Error:(26, 6) java: cannot find symbol
  symbol:   class ReadOperation
  location: class application.LivenessEndpoint
C:\codewind-workspace\intellij-apps-sp-def\src\main\java\application\Main.java
Error:(3, 32) java: package org.springframework.boot does not exist
Error:(4, 46) java: package org.springframework.boot.autoconfigure does not exist
Error:(6, 2) java: cannot find symbol
  symbol: class SpringBootApplication
Error:(10, 17) java: cannot find symbol
  symbol:   variable SpringApplication
  location: class application.Main
C:\codewind-workspace\intellij-apps-sp-def\src\test\java\application\MainTests.java
Error:(3, 35) java: package org.assertj.core.api does not exist
Error:(3, 1) java: static import only from classes and interfaces
Error:(8, 17) java: package org.junit does not exist
Error:(9, 24) java: package org.junit.runner does not exist
Error:(10, 52) java: package org.springframework.beans.factory.annotation does not exist
Error:(11, 45) java: package org.springframework.boot.test.context does not exist
Error:(12, 60) java: package org.springframework.boot.test.context.SpringBootTest does not exist
Error:(13, 48) java: package org.springframework.boot.test.web.client does not exist
Error:(14, 32) java: package org.springframework.http does not exist
Error:(15, 32) java: package org.springframework.http does not exist
Error:(16, 47) java: package org.springframework.test.context.junit4 does not exist
Error:(18, 2) java: cannot find symbol
  symbol: class RunWith
Error:(19, 2) java: cannot find symbol
  symbol: class SpringBootTest
Error:(23, 13) java: cannot find symbol
  symbol:   class TestRestTemplate
  location: class application.MainTests
Error:(18, 10) java: cannot find symbol
  symbol: class SpringRunner
Error:(19, 34) java: cannot find symbol
  symbol: variable WebEnvironment
Error:(22, 6) java: cannot find symbol
  symbol:   class Autowired
  location: class application.MainTests
Error:(25, 6) java: cannot find symbol
  symbol:   class Test
  location: class application.MainTests
Error:(32, 6) java: cannot find symbol
  symbol:   class Test
  location: class application.MainTests
Error:(39, 6) java: cannot find symbol
  symbol:   class Test
  location: class application.MainTests
Error:(53, 6) java: cannot find symbol
  symbol:   class Test
  location: class application.MainTests
Error:(27, 9) java: cannot find symbol
  symbol:   class ResponseEntity
  location: class application.MainTests
Error:(28, 54) java: cannot find symbol
  symbol:   variable HttpStatus
  location: class application.MainTests
Error:(34, 9) java: cannot find symbol
  symbol:   class ResponseEntity
  location: class application.MainTests
Error:(35, 54) java: cannot find symbol
  symbol:   variable HttpStatus
  location: class application.MainTests
Error:(45, 9) java: cannot find symbol
  symbol:   class ResponseEntity
  location: class application.MainTests
Error:(46, 54) java: cannot find symbol
  symbol:   variable HttpStatus
  location: class application.MainTests
Error:(49, 9) java: cannot find symbol
  symbol:   method assertThat(java.util.Map<java.lang.String,java.lang.Object>)
  location: class application.MainTests
Error:(50, 9) java: cannot find symbol
  symbol:   method assertThat(java.util.List<java.lang.String>)
  location: class application.MainTests
Error:(57, 9) java: cannot find symbol
  symbol:   class ResponseEntity
  location: class application.MainTests
Error:(58, 54) java: cannot find symbol
  symbol:   variable HttpStatus
  location: class application.MainTests

```

**Steps to reproduce:**
1. Create a new Codewind project. The template doesn't matter
2. While Codewind project is building in Codewind window, click on the```build``` button in the menu bar, and click ```Build Project```.
3. The bottom of the screen should display a bunch of build errors.

@jagraj

**Comment by jopit** [comment]
@naveenkaratekid What version of the plugin are you using? (on Windows, go to `File > Settings > Plugins`, then find the Codewind plugin, it should say what version it is.

Also, please attach the log file for intellij: go to `Help > Show Log in Explorer`.

This sounds very much like a bug I fixed yesterday: https://github.com/eclipse/codewind-intellij/pull/26

**Comment by naveenkaratekid** [comment]
@jopit i'm using version 0.9.0-202002111107.

Here is the log file:
[intelliJ log 0.9.0-20200211.txt](https://github.com/eclipse/codewind/files/4194925/intelliJ.log.0.9.0-20200211.txt)

**Comment by jopit** [comment]
@naveenkaratekid in intellij, can you please go to `Help > Show Log in Explorer`, and attach the log file found there?

**Comment by jopit** [comment]
OK, just checked 0.9.0-202002111107 is from before the fix for https://github.com/eclipse/codewind/issues/2090 went in (PR https://github.com/eclipse/codewind-intellij/pull/26).  Please update to a later version of the intellij plugin and retest,.

**Comment by jopit** [comment]
Note that appsody microprofile projects still seem to have a problem with this, but that's because `appsody init` isn't initializing the local maven cache on windows. @makandre

**Comment by jopit** [comment]
The problem with appsody microprofile is an appsody bug: https://github.com/appsody/stacks/issues/538

**Comment by jopit** [comment]
Did you create these projects in IntelliJ, or are they pre-existing projects that you imported?

**Comment by naveenkaratekid** [comment]
@jopit These are projects that I created. I will also try to import existing ones and see what happens

**Comment by jopit** [comment]
Can you attach the IntelliJ log files from when you created the projects? Go to the menu item`Help > Show Log in Explorer`

**Comment by jopit** [comment]
Oh, did you create the projects with the old version of the plugin, then update the plugin while still using those old projects?  Because the bug I fixed affects the project creation.  If the projects were created with the 'bad' plugin version, updating to the fixed version won't fix them.  You'll need to delete and recreate them.

**Comment by jopit** [comment]
I just tried on Windows with new project, and build works for me.

**Comment by naveenkaratekid** [comment]
Here is the log I pulled up from ```Help -> Show Log in Explorer```
[idea.log](https://github.com/eclipse/codewind/files/4200317/idea.log)

Screenshot for Standard Template Websphere MicroProfile (non-Appsody)
![image](https://user-images.githubusercontent.com/19738071/74466675-b5fad700-4e65-11ea-82ae-9d1f1ac12524.png)

**Comment by jopit** [comment]
Can you run the following two commands and post the output?

`dir %USERPROFILE%\.m2`

`dir %USERPROFILE%\.m2\repository\net`

**Comment by naveenkaratekid** [comment]
```
C:\Users\Administrator>dir %USERPROFILE%\.m2
 Volume in drive C has no label.
 Volume Serial Number is 2E0F-96BD

 Directory of C:\Users\Administrator\.m2

12/12/2019  10:16 AM    <DIR>          .
12/12/2019  10:16 AM    <DIR>          ..
08/28/2019  08:09 AM    <DIR>          repository
12/12/2019  10:16 AM    <DIR>          wrapper
               0 File(s)              0 bytes
               4 Dir(s)  114,435,260,416 bytes free
```

```
C:\Users\Administrator>dir %USERPROFILE%\.m2\repository\net
 Volume in drive C has no label.
 Volume Serial Number is 2E0F-96BD

 Directory of C:\Users\Administrator\.m2\repository\net

08/21/2019  02:43 PM    <DIR>          .
08/21/2019  02:43 PM    <DIR>          ..
08/21/2019  02:43 PM    <DIR>          bytebuddy
08/16/2019  05:24 PM    <DIR>          java
08/16/2019  05:25 PM    <DIR>          jodah
08/16/2019  05:28 PM    <DIR>          minidev
08/16/2019  05:24 PM    <DIR>          wasdev
               0 File(s)              0 bytes
               7 Dir(s)  114,435,190,784 bytes free
```

**Comment by jopit** [comment]
Did you add the project as a maven project as per step 7 here: https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/mdt-intellij-getting-started.md#creating-your-first-project-from-a-template?  I don't see the tab for the maven view in the screenshots.

**Comment by naveenkaratekid** [comment]
@jopit Just tried the steps from the link you sent me. I no longer see build errors.
![image](https://user-images.githubusercontent.com/19738071/74537488-34a85080-4f08-11ea-8974-6137622cd58e.png)


I will go ahead and close the issue.
