### ISSUE TITLE
SVT: IntelliJ: Java microprofile projects intermittently failing to build.

### ISSUE THREAD

**Issue by DavidG1011** [eclipse/codewind#2167]
**Codewind version:** 0.9.0
**OS:** Ubuntu 18.04.3 LTS

**IDE extension version:**  codewind-intellij-0.9.0-202002121646
**IDE version:** 
IntelliJ IDEA 2019.3.3 (Community Edition)
Build #IC-193.6494.35, built on February 11, 2020

**Description:** Java microprofile projects are intermittently failing to build. Upon creating a new project, the state will immediately change to "Build failed: Creating image for build failed": 

<img width="634" alt="Screen Shot 2020-02-12 at 2 17 28 PM" src="https://user-images.githubusercontent.com/30476587/74371313-95b81300-4da6-11ea-8476-f91bdc6e2b22.png">

**Workaround:** Selecting "Build" from the project context menu appears to remedy the issue every time.

[idea.log](https://github.com/eclipse/codewind/files/4194756/idea.log)

FYI: @jagraj

**Comment by jopit** [comment]
I don't believe this is a problem with the IDE.  Could you attach the PFE/Turbine logs?

**Comment by DavidG1011** [comment]
Whoops, apologies. Here's the PFE:
[pfe.txt](https://github.com/eclipse/codewind/files/4195328/pfe.txt)

**Comment by jopit** [comment]
I see this in the PFE logs
```
[32m[12/02/20 18:05:26 javamicro] [INFO][39m Emitting event 
 message: projectStatusChanged
 data: {
  "projectID": "3bcfcdd0-4dc2-11ea-9c80-1362945e7357",
  "buildStatus": "inProgress",
  "detailedBuildStatus": "Container image has been built successfully",
  "appImageLastBuild": "1581530726076"
}
[32m[12/02/20 18:05:26 javamicro] [INFO][39m buildlog path:
 [{"origin":"workspace","files":["/codewind-workspace/.logs/javamicro-3bcfcdd0-4dc2-11ea-9c80-1362945e7357/docker.build.log"]}]
[32m[12/02/20 18:05:26 javamicro] [INFO][39m applog path:
[]
[32m[12/02/20 18:05:26 javamicro] [INFO][39m Looking for all log files in container cw-javamicro-3bcfcdd0-4dc2-11ea-9c80-1362945e7357
[91m[12/02/20 18:05:26 javamicro] [ERROR][39m executeBuildScript : 384 | Unable to find image 'cw-javamicro-3bcfcdd0-4dc2-11ea-9c80-1362945e7357:latest' locally

[91m[12/02/20 18:05:26 javamicro] [ERROR][39m executeBuildScript : 384 | See 'docker run --help'.

[91m[12/02/20 18:05:26 javamicro] [ERROR][39m executeBuildScript : 384 | docker: Error response from daemon: pull access denied for cw-javamicro-3bcfcdd0-4dc2-11ea-9c80-1362945e7357, repository does not exist or may require 'docker login'.

[91m[12/02/20 18:05:26 javamicro] [ERROR][39m executeBuildScript : 384 | Start container stage failed: failed to get containerID

[91m[12/02/20 18:05:26 javamicro] [ERROR][39m executeBuildScript : 384 | Unable to start container.

[91m[12/02/20 18:05:26 javamicro] [ERROR][39m [31m[ File Name: /file-watcher/server/dist/projects/projectUtil.js | Function Name: processManager.spawnDetached | Line Number: 389] [39mError code: 3 - The container failed to start for application /codewind-workspace/javamicro
[91m[12/02/20 18:05:26 /portal/modules/FileWatcher.js] [ERROR][39m projectStatusChanged: failed (project: {
  "projectID": "3bcfcdd0-4dc2-11ea-9c80-1362945e7357",
  "buildStatus": "failed",
  "detailedBuildStatus": "Creating image for build failed",
  "lastbuild": 1581530726443
})
```
which isn't an IDE error.  The Turbine team needs to investigate.

**Comment by hhellyer** [comment]
I'd need the docker build log for the project to be sure but the most likely cause is failing to download Java from IBM's DHE download site.

There are already to other defects releated to that:
https://github.com/eclipse/codewind/issues/3009
https://github.com/eclipse/codewind/issues/172

and I have put changes into the MicroProfile template and the Spring template to change how we download Java to make it faster and more reliable:

https://github.com/codewind-resources/springJavaTemplate/pull/4
https://github.com/codewind-resources/javaMicroProfileTemplate/pull/7

@DavidG1011 - Would you be able to retest now those changes are in? They went directly into the templates so they should be picked up by master or 0.14.0 builds, you won't need to create a new Codewind environment *but* you will need to create new projects as they are changes to the project dockerfiles written at project creation time.

**Comment by DavidG1011** [comment]
The builds seem to be a lot more stable. I haven't seen a build failure after building a few new projects. I'll continue to monitor this, but I think this issue could probably be closed for now. Thanks @hhellyer!
