### ISSUE TITLE
Performance dashboard in Che Theia

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#217]
@tetchel commented on [Thu Jul 18 2019](https://github.com/eclipse/codewind-vscode/issues/123)

There will be a change needed in the Theia plugin to launch the performance dashboard on the correct URL

Within the Theia container there will be : 

| VAR       | Value    | 
| :------------- | ---------- |
|  CHE_API | http://namespace.ip.nip.io/api   |
| CHE_WORKSPACE_ID   | workspacehgafq9yutdr9c1qy | 

The plugin will need to open the dashboard at : 

http://codewind-workspacehgafq9yutdr9c1qy-namespace.ip.nip.io

ie:

*  remove protocol and path from CHE_API to get the namespace
*  construct the url using :   concat("http://codewind-", CHE_WORKSPACE_ID, "-",  namespace)

thanks @markcor11

---

@tetchel commented on [Thu Aug 08 2019](https://github.com/eclipse/codewind-vscode/issues/123#issuecomment-512820911)

~blocked by https://github.com/eclipse/codewind-che-plugin/pull/27~

**Comment by tetchel** [comment]
implemented as was requested [here](https://github.com/tetchel/codewind-vscode/tree/theiaDashboard), but I can't get the backend working to verify.

**Comment by tetchel** [comment]
I think this is the error:
```
[19/08/19 20:33:38 server.js] [ERROR] { Error: getaddrinfo ENOTFOUND codewind-performanceworkspacec2ieeo1pyp0lubvv-workspacec2ieeo1pyp0lubvv codewind-performanceworkspacec2ieeo1pyp0lubvv-workspacec2ieeo1pyp0lubvv:9095
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname:
   'codewind-performanceworkspacec2ieeo1pyp0lubvv-workspacec2ieeo1pyp0lubvv',
  host:
   'codewind-performanceworkspacec2ieeo1pyp0lubvv-workspacec2ieeo1pyp0lubvv
```

**Comment by johnmcollier** [comment]
This was my mess-up, a slight typo in the Codewind deployment code:
https://github.com/eclipse/codewind-che-plugin/blob/master/codewind-che-sidecar/deploy-pfe/pkg/codewind/util.go#L103

Should be:
`codewind.PerformancePrefix + "-" + codewind.WorkspaceID`
