### ISSUE TITLE
[Docs] Restructure the "importing existing project" page

### ISSUE THREAD

**Issue by james-wallis** [eclipse/codewind#2182]
**Description of the enhancement:**
The project import page starts by saying "Modifications are usually required to successfully add and deploy projects that have never been run in Codewind before". 
This sounds restrictive and may put a user off as it sounds like we are going to force them to make changes to their underlying source code when really we should, at a minimum, be able to run their project if they just have a Dockerfile.

Further down the page there exists a "Generic docker projects" section which states that the user can "add the project to Codewind by selecting the Other (Basic Container) option as the project type. For the application state detection to work, the Dockerfile needs to include an `EXPOSE` instruction to point to the port that is used to determine whether the project is running."
 https://www.eclipse.org/codewind/mdteclipseimportedprojects.html#generic-docker-projects

**Proposed solution:** 
I think that the page should be restructured to follow the flow (obviously this will all need to be heavily reworded):
1. All you need is a Dockerfile that `EXPOSE`s a port to import your own project into Codewind. 
2. For MicroProfile/Java EE projects, Java Spring projects, Node.js projects and Swift projects we have build "smarts" which mean that your project will rebuild faster? than if it was just a Dockerfile.  These smarts might just be enabled in local Docker rather than in K8s as well - need to check with the Turbine team.
3. Finally Appsody + other extensions?

**Additional thoughts**
Consider for each language changing the layout of the requirements to be file based, Node.js used as an example below:
```
## Node.js projects

**Required files:**
* Dockerfile (For more information see the Dockerfile reference)
    * Must have an `EXPOSE` which has the value of your applications port.
    * Must have the application source files located in the `/app` directory inside the container.
* package.json (Example of a package.json that is supported by Codewind see express application generator):
    * Must be able to be started via `npm start`.
    * Optional: For debugging have a `npm debug` script that runs node with inspect turned on: e.g.`node --inspect=0.0.0.0:9229 server/server.js`.
    * `npm start` or `npm debug` must not run `nodemon` (see auto building section)
 
**Auto building**
If auto-build is enabled,` nodemon` is used to restart your project automatically. `nodemon` calls either the start or debug script on a code change, depending on whether or not the project is debugging. Consequently, neither of these scripts should invoke `nodemon`.

If a problem occurs with either script, the error appears in the Application Logs view in Codewind.
```

@micgibso

**Comment by sishida** [comment]
The link in the original comment, `https://www.eclipse.org/codewind/mdteclipseimportedprojects.html#generic-docker-projects`, no longer functions.

Here is the link to new URL for the "Importing existing projects" page: https://www.eclipse.org/codewind/importing-existing-projects.html

**Comment by micgibso** [comment]
@james-wallis James, looking at this now, the current Microprofile/Java EE project import instructions look particularly complex, and all other imports have their own particular requirements, and yet running the latest Codewind suggests the wizard has been improved considerably. 

I'm now thinking the best approach is to cover off all bases in much the same way as we do for Getting Started, so that's structured subtopics for each scenario with Prereqs / Instructions / What you've achieved / What next, and plenty of screenshots.

**Comment by micgibso** [comment]
Update: see https://github.com/eclipse/codewind/issues/163 and PR https://github.com/eclipse/codewind-docs/pull/496

**Comment by j-c-berger** [comment]
feel free to assign to me!

**Comment by j-c-berger** [comment]
@james-wallis, hey James, I'm taking a closer look at this issue. I see that Sarah already made the changes you suggested for the beginning of the doc in [PR #496](https://github.com/eclipse/codewind-docs/pull/496).

As far as what ID still needs to do: do you want to reorganize the entire doc, or only the ```Generic docker projects``` section?

If you wanted the whole doc, I'm not sure how we'll restructure all the content in the 3 sections you suggested above. 

Thanks!
