### ISSUE TITLE
SVT:IntelliJ:Codewind Uninstall does not work

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#2183]
**Codewind version:** 0.9.0
**OS:** Windows

**Che version:**
**IDE extension version:** 0.9.0
**IDE version:** IntelliJ 2019-3.3
**Kubernetes cluster:**

**Description:**
I tried to uninstall Codewind and it does not remove images and status does not say [In complete - Double click to install Codewind]

```
 docker images
REPOSITORY                           TAG                    IMAGE ID            CREATED             SIZE
<none>                               <none>                 eaaf31c21367        8 hours ago         442MB
<none>                               <none>                 6b6ed2c256b8        8 hours ago         294MB
<none>                               <none>                 0626192973b6        8 hours ago         473MB
liberty-app-cache                    latest                 777c22cd4424        15 hours ago        874MB
spring-app-cache                     latest                 cabef2b984c6        15 hours ago        414MB
eclipse/codewind-performance-amd64   0.9.0                  2cd89a2c56d2        16 hours ago        334MB
eclipse/codewind-pfe-amd64           0.9.0                  6b0193f799cd        16 hours ago        798MB
appsody/java-microprofile            0.2                    cad2a0510eb4        22 hours ago        640MB
appsody/java-spring-boot2            0.3                    1ea6e6ce08b8        2 days ago          422MB
appsody/java-openliberty             0.1                    e44104e134cc        5 days ago          1.13GB
websphere-liberty                    19.0.0.9-webProfile7   2377ac4e61bf        8 days ago          401MB
ibmjava                              8-sfj                  601cc028fbfa        8 days ago          167MB
open-liberty                         latest                 55a69a63ad69        12 days ago         412MB
appsody/init-controller              0.3.4                  1395911a58e4        3 weeks ago         7.5MB
fabric8/java-alpine-openjdk8-jre     latest                 6383f0513235        3 months ago        87.3MB
ibmcom/codewind-java-project-cache   latest                 30c11c49e29d        5 months ago        231MB
websphere-liberty                    19.0.0.3-webProfile7   c6892fcebf3c        5 months ago        460MB
maven                                3.5.4-jdk-8-alpine     fb4bb0d89941        15 months ago       119MB
```

Log file
[idea.log](https://github.com/eclipse/codewind/files/4198285/idea.log)

**Steps to reproduce:**
1. Install IntelliJ
2. Install Codewind.
3. Create few projects.
4. Wait until all projects running.
5. Remove all projects.
6. Uninstall Codewind.
7. Codewind images not removed after uninstall.

**Workaround:**

**Comment by jopit** [comment]
I think the problem is here:
https://github.com/eclipse/codewind-intellij/blob/54ba11b1728418221d622199bbd5e113ef48c395/dev/src/main/java/org/eclipse/codewind/intellij/ui/tasks/UninstallCodewindTask.java#L39

Instead of passing null as the version, it should pass InstallUtil.getVersion()

**Comment by jopit** [comment]
Looks like `UpgradeCodewindTask` might need the same fix.

**Comment by naveenkaratekid** [comment]
@jagraj I too notice that the images in IntelliJ don't get removed after I click ```Uninstall```

![image](https://user-images.githubusercontent.com/19738071/74452079-9310f880-4e4e-11ea-83dd-76b7dc5e0820.png)

**Comment by cccanderson** [comment]
https://github.com/eclipse/codewind-intellij/pull/47 fixes this if there is only one version of Codewind currently installed.  I chatted with Liam about this, and he agrees that
cwctl remove -t 0.7.0, 0.8.0
should be supported to remove more than one version at once.  As such, I will leave my current fix as is, and in a future release of Codewind, multiple versions will automatically be removed (without needing a code change in our IntelliJ support).

**Comment by jagraj** [comment]
Do we really need to uninstall all the versions that user has or just the latest version.? We just don't want to get rid of all the images and this takes lot of time to download all the image layers.

**Comment by malincoln** [comment]
@jagraj pls verify and close. Thanks

**Comment by jagraj** [comment]
This issue has been verified. Thanks for the fix.
