### ISSUE TITLE
VSCode appears to recycle Codewind connection when reloading extension

### ISSUE THREAD

**Issue by mattcolegate** [eclipse/codewind#2192]
**Codewind version:** latest (13/02/2020)
**OS:** Windows 10

**Che version:** N/A
**IDE extension version:** latest (13/02/2020)
**IDE version:** VSCode
**Kubernetes cluster:** N/A

**Description:**
With an empty workspace (stating 'You have not yet added a folder to the workspace") and a running Codewind with projects, right clicking one of them and selecting 'Add project to workspace' causes Codewind to appear as `Stopped` with a red cross, before coming back as before with projects. This also happens if all projects are removed from the workspace.

**Steps to reproduce:**
Scenario 1:
Use VS code and connect to local Codewind, create a project. Once the project is running, ensure that your workspace is empty. Right click the project and select 'Add Project to workspace'.

Scenario 2:
After scenario 1, select the top level project folder in the Workspace and right click. Select 'Remove project from workspace'.

**Workaround:**

**Comment by tetchel** [comment]
When you modify the workspace VS Code reloads all extensions, this is the esxpected behaviour

**Comment by mattcolegate** [comment]
Noted, but does the icon have to go to the red cross with no project listed? Is there any way that you could preserve the existing layout whilst the extension restarts? That way it won't look like the connection has been lost.

**Comment by tetchel** [comment]
No it was has to start from scratch which means it takes a moment to run `cwctl status` and get the Codewind URL to make sure it's started.
