### ISSUE TITLE
Project delete throws error on Eclipse IDE

### ISSUE THREAD

**Issue by ssh24** [eclipse/codewind#2194]
**Description:**
I have seen this across pretty much all project types on the Eclipse IDE. Try deleting a project and it will throw this error:
![Screen Shot 2020-02-13 at 11 41 33 AM](https://user-images.githubusercontent.com/15173354/74457204-ef2b4b00-4e55-11ea-9dcc-081aa26d1f52.png)

The project is deleted regardless but I don't know what this error means or why it is thrown.

/area eclipse-ide

**Comment by tetchel** [comment]
dupe https://github.com/eclipse/codewind/issues/2193

**Comment by tetchel** [comment]
tho looks like you're on Mac so it's not windows-specific

**Comment by eharris369** [comment]
Closing since this is covered by #2193
