### ISSUE TITLE
SVT: [IntelliJ] Missing steps in IntelliJ installation instructions

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#2196]
**Codewind version:** 0.9.0
**OS:** Mac OS Mojave 10.14.6, VM with Windows 10

**IDE extension version:** 20200212-195750
**IDE version:**
<img width="344" alt="Screen Shot 2020-02-13 at 12 46 11 PM" src="https://user-images.githubusercontent.com/49531960/74462839-dd9a7100-4e5e-11ea-930b-4a87c2dd90f1.png">

<img width="319" alt="Screen Shot 2020-02-13 at 12 45 49 PM" src="https://user-images.githubusercontent.com/49531960/74462840-decb9e00-4e5e-11ea-94e6-d09bc4f0d973.png">

**Description:** Missing steps in IntelliJ installation instructions

**1) _Installing Codewind on IntelliJ with the custom plug-in repository:_** There must be a Step 2 saying: Click on **Plugins**

<img width="594" alt="Screen Shot 2020-02-13 at 12 42 01 PM" src="https://user-images.githubusercontent.com/49531960/74463005-1e928580-4e5f-11ea-8fba-425160298012.png">

**2) _Installing Codewind on IntelliJ from the Eclipse Downloads Page:_**  There must be a Step 3 saying: Click on **Plugins**

<img width="618" alt="Screen Shot 2020-02-13 at 12 43 08 PM" src="https://user-images.githubusercontent.com/49531960/74463010-205c4900-4e5f-11ea-92a7-0e83e9636cf7.png">

<img width="976" alt="Screen Shot 2020-02-13 at 12 41 26 PM" src="https://user-images.githubusercontent.com/49531960/74463019-23573980-4e5f-11ea-857f-b91bbfa6cd02.png">

<img width="979" alt="Screen Shot 2020-02-13 at 12 41 37 PM" src="https://user-images.githubusercontent.com/49531960/74463023-25b99380-4e5f-11ea-81b6-287cbb370c3b.png">

@jagraj

**Comment by sishida** [comment]
@sujeilyfonseca Here is the PR to include the steps about clicking **Plugins**: https://github.com/eclipse/codewind-docs/pull/379

@jopit, @micgibso If the changes look good to go, please add your committer approval. Thank you!

**Comment by sujeilyfonseca** [comment]
Thanks, @sishida!  The PR looks good. Once it is merged, this issue can be closed.
