### ISSUE TITLE
SVT: [IntelliJ][Windows] Cannot install Codewind on IntelliJ using a custom plug-in repository

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#2197]
**Codewind version:** 0.9.0
**OS:** VM with Windows 10

**IDE extension version:** 0.9.0-202002121935
**IDE version:** 
<img width="319" alt="Screen Shot 2020-02-13 at 12 45 49 PM" src="https://user-images.githubusercontent.com/49531960/74465119-d07f8100-4e62-11ea-97e0-cf92747c7f8f.png">

**Description:** Cannot install Codewind on IntelliJ using a custom plug-in repository

I can install Codewind using the plugin .zip file:

<img width="618" alt="Screen Shot 2020-02-13 at 12 43 08 PM" src="https://user-images.githubusercontent.com/49531960/74465764-fc4f3680-4e63-11ea-8b31-6cd7cfbd1630.png">

<img width="1382" alt="Screen Shot 2020-02-13 at 1 04 53 PM" src="https://user-images.githubusercontent.com/49531960/74465175-e8ef9b80-4e62-11ea-8de6-408c96064502.png">

However, I can't do the same with a custom plug-in repository: https://download.eclipse.org/codewind/codewind-intellij/0.9.0/latest/updatePlugins.xml

<img width="594" alt="Screen Shot 2020-02-13 at 12 42 01 PM" src="https://user-images.githubusercontent.com/49531960/74465778-02ddae00-4e64-11ea-831a-adbde8c78616.png">

<img width="1381" alt="Screen Shot 2020-02-13 at 1 05 53 PM" src="https://user-images.githubusercontent.com/49531960/74465231-03c21000-4e63-11ea-9093-1cb500c6c1f9.png">

<img width="798" alt="Screen Shot 2020-02-13 at 1 11 13 PM" src="https://user-images.githubusercontent.com/49531960/74465251-0b81b480-4e63-11ea-994b-b0642d53303b.png">

<img width="683" alt="Screen Shot 2020-02-13 at 1 11 25 PM" src="https://user-images.githubusercontent.com/49531960/74465258-0de40e80-4e63-11ea-9556-1dd0affffebd.png">

**IDE Log:**
```
2020-02-13 13:11:16,448 [ 367858]   INFO - .ide.plugins.PluginManagerMain -  
java.net.MalformedURLException: Malformed URL: 
	at com.intellij.util.Urls.newFromEncoded(Urls.kt:63)
	at com.intellij.ide.plugins.RepositoryHelper.loadPlugins(RepositoryHelper.java:113)
	at com.intellij.ide.plugins.RepositoryHelper.loadPlugins(RepositoryHelper.java:96)
	at com.intellij.ide.plugins.PluginManagerConfigurable.loadRepositoryPlugins(PluginManagerConfigurable.java:1527)
	at com.intellij.ide.plugins.PluginManagerConfigurable.access$2300(PluginManagerConfigurable.java:68)
	at com.intellij.ide.plugins.PluginManagerConfigurable$7.lambda$createPluginsPanel$3(PluginManagerConfigurable.java:373)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

@jagraj

**Comment by jopit** [comment]
This looks like a bug in IntelliJ

**Comment by malincoln** [comment]
@jopit pls assign.  Thanks

**Comment by jopit** [comment]
This looks to be a bug in IntelliJ on Windows.  If you paste the URL, then click outside the entry field so that it loses focus, then click OK, it saves the URL correctly.

If you enter the URL, and the click OK without shifting focus from the entry field. it gets saved as a blank entry, and you get the error.

There's nothing we can do in the plugin or in the update site to fix this.  We should probably update the docs to mention this.

**Comment by malincoln** [comment]
@micgibso @sishida ^^^

**Comment by sishida** [comment]
Hi, team, I have made a doc update based on this feedback: https://github.com/eclipse/codewind-docs/pull/375. Could a committer please review it? Please let me know if you'd like any changes. If it's good to merge, please approve it. Thank you!

**Comment by sishida** [comment]
I have merged https://github.com/eclipse/codewind-docs/pull/375. The SVT team will inform us if the issue also occurs with Linux. If so, I will update the doc again so that it mentions both Windows and Linux.

**Comment by jopit** [comment]
I just tried it on a Linux machine, and the problem does occur there too.

**Comment by sishida** [comment]
@jopit Thanks for letting me know! I have added Linux in this PR: https://github.com/eclipse/codewind-docs/pull/377 Please review/approve/merge when ready. Thank you!
