### ISSUE TITLE
SVT: [IntelliJ] There could be a better message when the plug-in is installed, but the images are not yet installed

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#2199]
**Codewind version:** 0.9.0
**OS:** Mac OS Mojave 10.14.6, VM with Windows 10

**IDE extension version:** 20200212-195750, 0.9.0-202002121935
**IDE version:**
<img width="344" alt="Screen Shot 2020-02-13 at 12 46 11 PM" src="https://user-images.githubusercontent.com/49531960/74462839-dd9a7100-4e5e-11ea-930b-4a87c2dd90f1.png">

<img width="319" alt="Screen Shot 2020-02-13 at 12 45 49 PM" src="https://user-images.githubusercontent.com/49531960/74462840-decb9e00-4e5e-11ea-94e6-d09bc4f0d973.png">

**Description:** There could be a better message when the plug-in is installed, but the images are not yet installed 

<img width="450" alt="Screen Shot 2020-02-13 at 1 47 10 PM" src="https://user-images.githubusercontent.com/49531960/74468643-26efbe00-4e69-11ea-89df-0ee15edc4387.png">

@jagraj

**Comment by keithchong** [comment]
@jopit , does this issue apply to the other IDEs, at least, Eclipse?  I see that there is no Error status in the Eclipse plugin.

**Comment by jopit** [comment]
@keithchong no, it's a consequence of how and when the our code gets initialized in IntelliJ vs Eclipse/VSCode.

**Comment by malincoln** [comment]
@sujeilyfonseca pls verify and close.  Thanks

**Comment by sujeilyfonseca** [comment]
I verified this issue, and I no longer see the problem:

<img width="647" alt="Screen Shot 2020-02-25 at 9 23 35 AM" src="https://user-images.githubusercontent.com/49531960/75255847-968e7300-57b0-11ea-90e4-c3ee8cd24cf3.png">
