### ISSUE TITLE
SVT: Swift project not building in vscode, and not building after edits in eclipse/eclipse che

### ISSUE THREAD

**Issue by beccabau** [eclipse/codewind#22]
SVT team is experiencing project build issues with Swift projects.

In Eclipse local:
We can build the default Swift template, but after making changes to the app, the project fails to build. We see warning messages in app.log related to application metrics

In vscode local:
We cannot build the default Swift app at all. It seems to be stuck at the last step.

For both, we see error messages like:
```
[2019-07-16T17:41:22.500Z] [WARNING] [ConfigurationManager.swift:389 load(url:deserializerName:)] Unable to load data from URL /swift-project/config/mappings.json
[Tue Jul 16 17:41:22 2019] com.ibm.diagnostics.healthcenter.loader INFO: Swift Application Metrics
[2019-07-16T17:42:46.915Z] [WARNING] [ConfigurationManager.swift:389 load(url:deserializerName:)] Unable to load data from URL /swift-project/config/mappings.json
[Tue Jul 16 17:42:46 2019] com.ibm.diagnostics.healthcenter.loader INFO: Swift Application Metrics
[2019-07-16T17:44:09.046Z] [WARNING] [ConfigurationManager.swift:389 load(url:deserializerName:)] Unable to load data from URL /swift-project/config/mappings.json
[Tue Jul 16 17:44:09 2019] com.ibm.diagnostics.healthcenter.loader INFO: Swift Application Metrics
[2019-07-16T17:44:09.366Z] [INFO] [Metrics.swift:24 initializeMetrics(router:)] Initialized metrics.
[2019-07-16T17:44:09.380Z] [INFO] [HTTPServer.swift:195 listen(on:)] Listening on port 8080
[2019-07-16T17:45:36.490Z] [WARNING] [ConfigurationManager.swift:389 load(url:deserializerName:)] Unable to load data from URL /swift-project/config/mappings.json
[Tue Jul 16 17:45:36 2019] com.ibm.diagnostics.healthcenter.loader INFO: Swift Application Metrics
```

On Eclipse che:
I can build the swift project, but it fails to build after modifications to the app.
docker.app.log 
[SwiftDockerAppLog.txt](https://github.com/eclipse/codewind/files/3398999/SwiftDockerAppLog.txt)

app log
[SwiftAppLog.txt](https://github.com/eclipse/codewind/files/3399001/SwiftAppLog.txt)

**Comment by maysunfaisal** [comment]
@beccabau can you provide the filewatcher daemon logs (the project watching log)? Want to see if editing project files kicks off OS modify events on those files.

Can you also share the CW PFE log?

**Comment by beccabau** [comment]
pfe log (local) [pfe.txt](https://github.com/eclipse/codewind/files/3402216/pfe.txt)

filewatcher (che) 
[filewatcher-che.txt](https://github.com/eclipse/codewind/files/3402288/filewatcher-che.txt)

**Comment by sujeilyfonseca** [comment]
**Codewind version:** Latest Development Version
![Screen Shot 2019-07-17 at 1 57 32 PM](https://user-images.githubusercontent.com/49531960/61400692-d1394000-a89e-11e9-8eba-d05e33c6c468.png)

![Screen Shot 2019-07-17 at 2 08 33 PM](https://user-images.githubusercontent.com/49531960/61400707-d8f8e480-a89e-11e9-9f44-567d732e6524.png)

![Screen Shot 2019-07-17 at 2 08 13 PM](https://user-images.githubusercontent.com/49531960/61400713-ddbd9880-a89e-11e9-86df-e0575f21efb5.png)


**Eclipse version:** 2019-06 (4.12.0) on Windows 10 and macOS Mojave (10.14.5)
![Screen Shot 2019-07-17 at 2 07 44 PM](https://user-images.githubusercontent.com/49531960/61400673-c2eb2400-a89e-11e9-8390-e8d82fe64443.png)


**VS Code version:** 1.36.1 (1.36.1) on macOS Mojave (10.14.5)
<img width="841" alt="Screen Shot 2019-07-17 at 2 06 28 PM" src="https://user-images.githubusercontent.com/49531960/61400655-ba92e900-a89e-11e9-9f2e-def1ff00d44c.png">


When I tested the latest version for Codewind, I saw the same errors as Becca. I only got a project built in Eclipse once, but after modifying it, it never built again. I saw warning messages in app.log related to application metrics. In latest tests, swift projects are no longer being built. In VS Code, I can not build any swift projects.

Here are the codewind-pfe logs:
[codewind-pfe-eclipse.txt](https://github.com/eclipse/codewind/files/3403308/codewind-pfe-eclipse.txt)
[codewind-pfe-vscode.txt](https://github.com/eclipse/codewind/files/3403309/codewind-pfe-vscode.txt)

**Comment by rajivnathan** [comment]
Initially thought this was a template issue but when I tried to reproduce I saw that the swift project was building endlessly. @maysunfaisal mentioned he can take a look. Thanks Maysun

**Comment by maysunfaisal** [comment]
@beccabau @sujeilyfonseca Hi, pls help verify when you have a chance.

**Comment by sujeilyfonseca** [comment]
I no longer see this problem with Codewind (Windows and Mac Operating Systems).

![Screen Shot 2019-08-19 at 9 01 13 AM](https://user-images.githubusercontent.com/49531960/63267721-adcc3100-c260-11e9-9c0e-9acf7fdfa1bf.png)

![Screen Shot 2019-08-19 at 9 00 52 AM](https://user-images.githubusercontent.com/49531960/63267743-b58bd580-c260-11e9-8100-bc93355bc6c4.png)

![Screen Shot 2019-08-19 at 9 04 47 AM](https://user-images.githubusercontent.com/49531960/63267755-b91f5c80-c260-11e9-8494-88c17060cb95.png)

**Comment by maysunfaisal** [comment]
Thx @sujeilyfonseca
