### ISSUE TITLE
[IntelliJ] generate GA version of 'updatePlugins.xml' for GA

### ISSUE THREAD

**Issue by josephca** [eclipse/codewind#2200]
Update Jenkins project to generate GA version of 'updatePlugins.xml' with a correct GA download area location. Each branch build contains the path to the branch build download area. 

e.g. 
A sample 'upatePlugins.xml'

```
<!--  Build date: 20200212-195750  -->
<plugins>
<plugin id="codewind-intellij" url="https://download.eclipse.org/codewind/codewind-intellij/0.9.0/latest/codewind-intellij.zip" version="20200212-195750">
<idea-version since-build="193.5233.102" until-build="999.*"/>
</plugin>
</plugins>
```

0.9.0 build: https://download.eclipse.org/codewind/codewind-intellij/0.9.0/latest/codewind-intellij.zip
GA build should have: https://download.eclipse.org/codewind/milestone/0.9.0/codewind-intellij-0.9.0.zip

**Comment by jopit** [comment]
We might want to add a `<name>Codewind</name>` element which will fix the name showing up as `codewind-intellj`

**Comment by josephca** [comment]
@jopit I will add the name. Furthermore, we could add a description as well to add more detail. 

[Custom plugin repositories](https://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/update_plugins_format.html): 

![image](https://user-images.githubusercontent.com/25185698/74538338-01ff5780-4f0a-11ea-99b7-b8bb530ffcb5.png)

**Comment by jopit** [comment]
We can use the same description as in the plugin.xml: `Adds support for developing cloud-native, containerized web applications.`

**Comment by josephca** [comment]
@jopit 
I updated the script by adding the name and description. 
Sample:
![image](https://user-images.githubusercontent.com/25185698/74542623-f44dd000-4f11-11ea-99a4-89e62d4cb6c6.png)

**Comment by josephca** [comment]
![image](https://user-images.githubusercontent.com/25185698/74543985-5c9db100-4f14-11ea-98cb-fb5895d5c447.png)

**Comment by josephca** [comment]
The required change has been made in Jenkins. 
A related change for name/description change in 0.9.0 is handled by https://github.com/eclipse/codewind-intellij/pull/53
