### ISSUE TITLE
SVT:IntelliJ:Plugin status does not say "Installed" after install in "Marketplace" section even though it is installed

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#2201]
**Codewind version:** 0.9.0
**OS:** Windows

**Che version:**
**IDE extension version:** 0.9.0
**IDE version:**  IntelliJ 2019-3.3
**Kubernetes cluster:**

**Description:**
After installing Codewind from plugin repo, the status says "Install" rather it is already "Installed". This is misleading to the users. Is it possible to change the status back to "Installed" once it is installed from the plugin after IDE restart. You can see "Kotlin" plugin is already installed and the status says "

Codewind plugin.

![image](https://user-images.githubusercontent.com/713849/74470033-bd24e380-4e6b-11ea-9c01-82a6f573c8b5.png)

Example - Kotlin Plugin.
![image](https://user-images.githubusercontent.com/713849/74469921-8b138180-4e6b-11ea-89ae-ad85c48021c2.png)

**Steps to reproduce:**
1. Install IntelliJ
2. Install Codewind plugin.
3. Status is still says "Install"

**Workaround:**

**Comment by jopit** [comment]
@josephca could you please take a look?  I don't know if there's anything we can do to fix this.  Even if there is, it's not required for 0.9.0.

**Comment by jopit** [comment]
This may be because the version in the `updatePlugins.xml` is different from the actual version of the plugin itself -- for example `20200213-205654` in the updatePlugins.xml vs `0.9.0-20200213-205654` in the plugin itself.

**Comment by josephca** [comment]
Fixed by putting the correct plugin id. The version number seems irrelevant. 
![image](https://user-images.githubusercontent.com/25185698/74549030-e81b4000-4f1c-11ea-9239-9cd22e26ee94.png)

**Comment by jagraj** [comment]
Yes, it is fixed now. Thanks for the fix. 

![Screen Shot 2020-02-14 at 1 34 39 PM](https://user-images.githubusercontent.com/713849/74557731-c6c34f80-4f2e-11ea-9e06-984c02f20855.png)
