### ISSUE TITLE
[IntelliJ] Docs: wrong url on getting started page.

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind#2206]
Just noticed this.

On page https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/mdt-intellij-getting-started.md section **Installing Codewind on IntelliJ with the custom plug-in repository** step 5 says
```
Enter https://download.eclipse.org/codewind/codewind-intellij/0.9.0/latest/updatePlugins.xml and click OK.`
```
The url is incorrect.  It should be 
```
https://download.eclipse.org/codewind/milestone/0.9.0/updatePlugins.xml
```
@josephca please confirm this is the final, correct url.

**Comment by josephca** [comment]
@jopit Confirmed that `https://download.eclipse.org/codewind/milestone/0.9.0/updatePlugins.xml` is correct.

**Comment by sishida** [comment]
@jopit @josephca Could either of you please review/approve/merge if the edit looks good to go? Thank you! https://github.com/eclipse/codewind-docs/pull/374 🎉

**Comment by sishida** [comment]
PR https://github.com/eclipse/codewind-docs/pull/374 has been merged. Closing this issue. 🌮
