### ISSUE TITLE
Increase logging within performance container when running load tests

### ISSUE THREAD

**Issue by markcor11** [eclipse/codewind#2212]
**Codewind version:** latest
**OS:**

**Description:**

When running load the performance container logs show just : 
```
started
completed
```

This is insufficient to troubleshoot load runner problems and was introduced as a result of moving to a new logger in the performance container which categorised this useful output to loglevel=debug. 

**Steps to reproduce:**

**Workaround:**

**Comment by rwalle61** [comment]
I put the change in to put them to debug, not realising that we needed them at level info. We can control the log level via setting LOG_LEVEL in the Performance Dockerfile. It is `info` by default. So to show the log messages by default we can log them as `info` not `debug`, or set LOG_LEVEL to `debug`. 

We could also:

1. make our PFE /logging API control Performance logging too
2. or create a separate /logging API to control Performance logging independently

**Comment by markcor11** [comment]
changes delivered in 2207 and 2208
