### ISSUE TITLE
SVT:Enable Inject Metrics is missing as menu item in 0.9.0 release

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#2213]
**Codewind version:** 0.9.0
**OS:** Windows 

**Che version:**
**IDE extension version:** 0.9.0
**IDE version:** Eclipse IDE - 2019-09
**Kubernetes cluster:**

**Description:**
Enable Inject Metrics menu item is missing as option in 0.9.0 release and it is available in 0.8.1 release.

**Codewind 0.9.0**
![image](https://user-images.githubusercontent.com/713849/74493362-ef503880-4e9f-11ea-8789-206253d5d0fc.png)

**Codewind 0.8.1**
![Screen Shot 2020-02-13 at 5 15 53 PM](https://user-images.githubusercontent.com/713849/74493450-24f52180-4ea0-11ea-877b-d683563ebf24.png)

**Steps to reproduce:**
1. Install Codewind 0.9.0 using Eclipse plugin.
2. Create Websphere liberty  project.
3. Right click in codewind explorer view.
4. Missing "Enable Inject Metrics".

**Workaround:**

**Comment by sujeilyfonseca** [comment]
**Codewind version:** 0.9.0
**OS:** Red Hat Enterprise Linux 7 (64 bit), VM with Windows 10

**Che version:** 7.5.1
**Kubernetes cluster:** OKD/Openshift 

**IDE extension version:** 0.9.0
**IDE version:** Code 1.42.0

I can reproduce this problem in VS Code and Eclipse Che. I created some projects and I no longer see the "Enable Inject Metrics" option.

<img width="1676" alt="Screen Shot 2020-02-13 at 9 12 29 PM" src="https://user-images.githubusercontent.com/49531960/74495637-5d97f980-4ea6-11ea-9d9e-316a26f1e1c9.png">

<img width="1589" alt="Screen Shot 2020-02-13 at 9 14 34 PM" src="https://user-images.githubusercontent.com/49531960/74495638-5ec92680-4ea6-11ea-8298-2f5bcf872f25.png">

**Comment by DavidG1011** [comment]
Codewind version: 0.9.0
OS: Mac

IDE extension version: 0.9.0
IDE version: VSCode 1.42.1


I was able to see this option in VSCode with version 0.8.1 for the following project types:
Java Spring
Java Microprofile
NodeJs

I no longer see this option in 0.9.0 for any of the project types:

![image](https://user-images.githubusercontent.com/30476587/74496100-abf9c800-4ea7-11ea-8fb6-07936cb09ce9.png)


In addition to this, in 0.9.0, clicking the "Inject Appmetrics" toggle on the project overview page produces errors for some project types:

![image](https://user-images.githubusercontent.com/30476587/74496219-06932400-4ea8-11ea-9262-50aa6cfeb756.png)


![image](https://user-images.githubusercontent.com/30476587/74496401-933de200-4ea8-11ea-8106-327283d4f14b.png)

**Comment by eharris369** [comment]
This is on purpose.  If the application already has embedded metrics then there is no point in showing the inject metrics option.

**Comment by eharris369** [comment]
Jag says that some users may want to inject metrics even if metrics are already there as it gives them more features.  @tobespc Is that true?

**Comment by jagraj** [comment]
@tobespc @markcor11 
We are having hard time to understand which projects have embedded metrics and not. This is same issue with open liberty projects as well where this option is missing and we can not inject metrics. You can see the window below where user can edit project settings to enable metrics but it is hard to enable based on Json data that we have for .cw-settings file.

![Screen Shot 2020-02-14 at 7 38 59 AM](https://user-images.githubusercontent.com/713849/74532386-18eb7d00-4efd-11ea-9f7d-a23a9ab5eb68.png)

```


{
  "contextRoot": "",
  "internalPort": "",
  "healthCheck": "",
  "isHttps": false,
  "ignoredPaths": [
    "*/.idea/*",
    "*.iml",
    "/.project",
    "/load-test*",
    "*/*.swp",
    "*/*.swx",
    "*/.gitignore",
    "*/node_modules*",
    "*/4913",
    "*/.git/*",
    "*/.DS_Store",
    "*/.dockerignore",
    "*/*~",
    "/.settings",
    "/.classpath",
    "/.options",
    "/.vscode/*"
  ],
  "statusPingTimeout": ""
}
```

For same project in Eclipse Che where user can enable this with check box but not in local.

![Screen Shot 2020-02-14 at 7 56 09 AM](https://user-images.githubusercontent.com/713849/74533398-7d0f4080-4eff-11ea-83bc-fa8ef869791b.png)

**Comment by jopit** [comment]
Adding the portal tag because we need input from portal on what's the correct behaviour here.

**Comment by rwalle61** [comment]
As far as I know, the desired behaviour is:

Codewind Node.js and Websphere Liberty template projects should come with metrics embedded (appmetrics-dash and javametrics-dash respectively). I'll double check about Appsody and Swift.

.cw-settings does not determine whether we can inject metrics. The logic is in PFE. We should only be able to inject metrics into projects that are:
- type `nodejs`
- type `liberty`
- type `docker` and language `java` (our rough definition of 'open liberty').

**Comment by jopit** [comment]
@eharris369 @tetchel as per Richard's comment, we need to provide the `inject metrics` function for applicable projects even if they have embedded metrics.

**Comment by tetchel** [comment]
We changed this intentionally https://github.com/eclipse/codewind/issues/1710

**Comment by tetchel** [comment]
The errors in https://github.com/eclipse/codewind/issues/2213#issuecomment-586069238 are both for lagom, right? 

Inject metrics is not supported for lagom, but it is shown, because PFE can't tell the difference between lagom and open liberty, and we need to support it for open liberty 🙃

**Comment by naveenkaratekid** [comment]
I too can reproduce this issue. I no longer see the app metrics option in 0.9.0:

0.8.1
![image](https://user-images.githubusercontent.com/19738071/74543827-16485200-4f14-11ea-813e-f1dc4be80cd3.png)

0.9.0
![image](https://user-images.githubusercontent.com/19738071/74543816-11839e00-4f14-11ea-835e-cae30cb0b9b6.png)

**Comment by eharris369** [comment]
Eclipse IDE PRs are merged:
- 0.9.0: https://github.com/eclipse/codewind-eclipse/pull/591
- master: https://github.com/eclipse/codewind-eclipse/pull/592

**Comment by rwalle61** [comment]
To clarify, by
>We should be able to inject metrics into the above projects even if the projects come with metrics embedded

I meant, as John interpreted, that we need to provide the inject metrics function for applicable projects even if they have embedded metrics. We should give users the action (and hopefully we are technically capable of injection)

**Comment by malincoln** [comment]
@jagraj pls verify and close.  Thanks

**Comment by jopit** [comment]
The VSCode build is still running: https://ci.eclipse.org/codewind/job/Codewind/job/codewind-vscode/job/0.9.0/ so Jag can't verify yet.

**Comment by jopit** [comment]
OK, build is done

**Comment by jagraj** [comment]
Looks good. Thanks for the fix. Verified with latest plugins.
