### ISSUE TITLE
SVT:IntelliJ:Double click to update to version 0.9.0 does not trigger any upgrade for codewind install

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#2221]
**Codewind version:** 0.9.0
**OS:** Windows

**Che version:**
**IDE extension version:** 0.9.0 latest
**IDE version:**  IntelliJ 2019-3.3
**Kubernetes cluster:**

**Description:**
With the latest IntelliJ plugin that I can not upgrade with the "Double click" message to the user.
How ever I do see menu item to Update Codewind, after clicking that and the status in the codewind explorer does not reflect and it is doing in the background , I have to go notification panel to see what is going on. Looks like this is not user friendly to the users. 

![image](https://user-images.githubusercontent.com/713849/74535795-9797e880-4f04-11ea-9e6a-d11e2d5d2429.png)

**Steps to reproduce:**
1. Install Codewind 0.8.1 from Eclipse or VSCode.
2. Now user wants to use IntelliJ for 0.9.0 release.
3. Install IntelliJ codewind plugin.
4. Codewind explorer says - "Double click to update Codewind to 0.9.0"
5. Double click does not do anything. 
6. User still can update codewind from Menu item with the right click.
7. After clicking update , the process starts in background and stays silent in explorer view.

**Workaround:**

**Comment by josephca** [comment]
@jagraj I'm wondering if it occurs only on Windows.

**Comment by jagraj** [comment]
@josephca 
I am not sure, let me ask someone from our team if they can reproduce this on MacOS or Linux. 

@sujeilyfonseca @DavidG1011 ^^

**Comment by sujeilyfonseca** [comment]
I'll proceed to verify this issue on MacOS.

**Comment by DavidG1011** [comment]
I see this same behavior on Linux.

**Comment by sujeilyfonseca** [comment]
I see this same behavior on MacOS:

<img width="743" alt="Screen Shot 2020-02-14 at 1 52 30 PM" src="https://user-images.githubusercontent.com/49531960/74558975-4d792c00-4f31-11ea-8168-48c7c7507c7a.png">

**Comment by beccabau** [comment]
I see this behavior on mac, but do not see the option to upgrade at all
![image](https://user-images.githubusercontent.com/13971834/74559387-47d01600-4f32-11ea-8afe-75d6fe0d8989.png)

**Comment by sujeilyfonseca** [comment]
I can see the "Update" menu option on my machine (MacOS): 

<img width="740" alt="Screen Shot 2020-02-14 at 2 27 11 PM" src="https://user-images.githubusercontent.com/49531960/74561333-63d5b680-4f36-11ea-9c19-7bcdc6895538.png">

**Comment by beccabau** [comment]
Workaround was to uninstall, then I double-clicked to install, and seems like it uploaded a recent enough version.

**Comment by cccanderson** [comment]
John Pitman and I worked together to get this fixed for 0.9.0 on Friday.  I still need to get this fixed in master.

**Comment by malincoln** [comment]
@jagraj can you verify the fix that went into 0.9.0 and confirm it's resolved.

**Comment by jopit** [comment]
Moving back to 'in progress' as the fix is in 0.9.0 but not yet in master.

**Comment by jagraj** [comment]
This has been fixed. closing this now.
