### ISSUE TITLE
SVT: VSCode: Toggling Inject Appmetrics for Java Lagom projects produces errors.

### ISSUE THREAD

**Issue by DavidG1011** [eclipse/codewind#2223]
**Codewind version**: 0.9.0
**OS**: Mac

**IDE extension version**: codewind-0.9.0-202002140934
**IDE version**: VSCode 1.42.1

**Description:** Toggling "Inject Appmetrics" for Java Lagom projects in the project overview page produces errors: 

I'm able to reproduce the first error consistently, while the second error I was only able to produce once:
<img width="462" alt="Screen Shot 2020-02-13 at 9 19 17 PM" src="https://user-images.githubusercontent.com/30476587/74549401-90310900-4f1d-11ea-8c1f-5ca170f63fad.png">
<img width="462" alt="Screen Shot 2020-02-13 at 9 32 26 PM" src="https://user-images.githubusercontent.com/30476587/74549396-8dceaf00-4f1d-11ea-9ed0-9ab18d43ae60.png">

**Steps to reproduce:**
1. Create a Java Lagom project.
2. Go to the project overview page.
3. Click the "Inject Appmetrics" toggle:

![Screen Shot 2020-02-14 at 11 35 46 AM](https://user-images.githubusercontent.com/30476587/74549750-29f8b600-4f1e-11ea-9cc6-59083829584e.png)

**Comment by tetchel** [comment]
tagging portal because these are PFE errors

My understanding is that inject metrics is enabled for "docker" projects with the "java" language, so lagom would fall under that category. But it only actually works for open liberty.

**Comment by rwalle61** [comment]
Tim is correct. I don't think this will be a quick fix, because to fix this we need to create a proper detection mechanism, rather than just treating `docker` `java` as open liberty

**Comment by jopit** [comment]
The first error message indicates an internal error occurred (in PFE?).  The second error message doesn't look like it's intended for consumption by a user.  At a minimum we should put up a more meaningful set of messages.

**Comment by rwalle61** [comment]
Both are internal errors occuring in PFE. 

The first is unexpected, so PFE hasn't caught it. It's probably caused by us thinking Lagom projects are Open Liberty projects

The second is the result of PFE catching an error and throwing that one. This behaviour will go away in 0.10.0 because of https://github.com/eclipse/codewind/pull/2132.

**Comment by james-wallis** [comment]
/assign
I'll investigate this and plan to implement a feature to tell if a Docker container is an Open Liberty one.

**Comment by malincoln** [comment]
@DavidG1011 pls verify and close. Thanks

**Comment by DavidG1011** [comment]
Verified: Lagom projects no longer have an "Inject Appmetrics" toggle. Users should not run into this issue.
