### ISSUE TITLE
Unable to connect to remote Codewind via `cwctl` CLI

### ISSUE THREAD

**Issue by bsteinfeld** [eclipse/codewind#2224]
**Codewind version:** Latest dev version `cwctl version x.x.dev` - Pulled Feb. 14, 2020
**OS:** Ubuntu 18.04.3 LTS

**Che version:** n/a - NO CHE installed
**IDE extension version:** n/a
**IDE version:** n/a
**Kubernetes cluster:** IKS `v1.15.8+IKS`

**Description:**
I've installed Codewind remotely via the following commands:

```
> cwctl --insecure install remote \
  --namespace codewind  \
  --kadminuser keycloak \
  --kadminpass <password>  \
  --krealm codewind \
  --kclient codewind  \
  --kdevuser developer \
  --kdevpass <password> \
  --konly \
  --ingress labs-dev-tor01-500955-a45631dc5778dc6371c67d206ba9ae5c-0000.tor01.containers.appdomain.cloud

> cwctl --insecure install remote \
  --namespace codewind  \
  --kadminuser keycloak \
  --kadminpass <password>  \
  --krealm codewind \
  --kclient codewind  \
  --kdevuser developer \
  --kdevpass <password> \
  --kurl https://codewind-keycloak-k6m7nl9l.labs-dev-tor01-500955-a45631dc5778dc6371c67d206ba9ae5c-0000.tor01.containers.appdomain.cloud \
  --ingress labs-dev-tor01-500955-a45631dc5778dc6371c67d206ba9ae5c-0000.tor01.containers.appdomain.cloud
```

From here I use `cwctl` to confirm Codewind install:
```
> cwctl --insecure connections add  --url https://codewind-gatekeeper-k6m82k0i.labs-dev-tor01-500955-a45631dc5778dc6371c67d206ba9ae5c-0000.tor01.containers.appdomain.cloud --username developer --label remote

> conid=$(cwctl connections ls | jq -r '.connections[] | select(.label == "remote").id')

> cwctl --insecure status --conid $conid
Remote Codewind is installed and running
```

Now that everything is looking good I want to start deploying apps and managing projects with Codewind, but I'm not sure where to put the password and run into the following error:

```
> cwctl --insecure project list -conid $conid
ERRO[0000] Unable to find password in keychain
```

I am _assume_ the keychain being referred to is from che (which I'm not using).

How can I set password and proceed using only the CLI?

**Comment by tetchel** [comment]
This is a limitation of cwctl https://github.com/eclipse/codewind/issues/1735

**Comment by tetchel** [comment]
This doesn't have to do with che. This usage of cwctl isn't documented right now, but isn't too hard to figure out. Run:

```
cwctl seckeyring update --conid $conid --username $username --password $password
```

**Comment by bsteinfeld** [comment]
> ```
> cwctl seckeyring update --conid $conid --username $username --password $password
> ```

@tetchel 

Needed to install `dbus-x11` (for `dbus-launch`). After this I hit the following error:

```
cwctl seckeyring update --conid $conid --username $username --password $password
{"error":"sec_keyring","error_description":"The name org.freedesktop.secrets was not provided by any .service files"}
```

**Comment by johnmcollier** [comment]
@bsteinfeld I'm not sure how to do this without a graphical frontend, but the instructions on https://github.com/zalando/go-keyring#linux should resolve that issue. It's expected that the default collection login exists in the keyring

https://github.com/eclipse/codewind/issues/1735 should resolve this issue too, as removing the keychain requirement would enable cwctl to connect

**Comment by bsteinfeld** [comment]
I was able to get things working via the following:

```
apt-get install -y dbus dbus-x11 gnome-keyring

eval "$(dbus-launch --sh-syntax)"
mkdir -p ~/.cache
mkdir -p ~/.local/share/keyrings
eval "$(printf '\n' | gnome-keyring-daemon --unlock)"
eval "$(printf '\n' | /usr/bin/gnome-keyring-daemon --start)"
```

Now updating the seckeyring working, e.g.:

```
> cwctl seckeyring update --conid $conid --username keycloak --password tzDf7jDN85dSETNW
{"status":"OK"}
```

**Comment by stalleyj** [comment]
@bsteinfeld Can this issue be closed now or do you have outstanding problems ?

**Comment by bsteinfeld** [comment]
This issue _can_ be closed. I do have the following notes:

1. The documentation (specifically the [remote connection](https://www.eclipse.org/codewind/remoteconfiguring.html) sections) is incomplete for my use case. Would be good to include:
    - Where/how `cwctl` stores passwords
    - Steps/guide to get `cwctl` setup to _work_ remotely (e.g. steps above for linux)
    - Troubleshooting errors (I ran into a few detailed above)
2. #1735 would be nice to have
3. *Feature Request* (should these go in here?: https://github.com/eclipse/codewind-installer/issues) 
    - Have `cwctl` accept environment variable default for the `conid` parameter (connection id to use)
    - Include build date and better _semantic_ (personal preference) for `cwctl` dev version. Currently it returns `cwctl version x.x.dev` which is a bit ambiguous.

**Comment by stalleyj** [comment]
@bsteinfeld Please raise your feature requests in this repository. The documentation for remote connection is currently being reworked which should address your issues.
