### ISSUE TITLE
SVT:IntelliJ:Multiple projects "Remove" does not remove all projects from the Codewind explorer

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#2225]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**
From IntelliJ Codewind  plugin, When I try to remove all the projects from the explorer window and it removes only one project and not all the projects selected from the explorer menu.

![Screen Shot 2020-02-14 at 1 57 14 PM](https://user-images.githubusercontent.com/713849/74564453-1c065d80-4f3d-11ea-8676-1a01557421c1.png)

**Steps to reproduce:**
1. Install Codewind from IntelliJ plugin.
2. Create projects from Codewind templates.
3. After successful running projects, select all projects and click on "Remove".
4. Only one project removed and not all the projects from Codewind.

**Workaround:**

**Comment by jopit** [comment]
Fixed via PR https://github.com/eclipse/codewind-intellij/pull/62

**Comment by malincoln** [comment]
@jagraj pls verify and close. Thanks

**Comment by jagraj** [comment]
This issue has been fixed. Thanks for the fix.
