### ISSUE TITLE
Docs for "Add mechanism in IDEs to set log level for PFE"

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind#2227]
Document https://github.com/eclipse/codewind/issues/1251.

We can document this issue in https://www.eclipse.org/codewind/troubleshooting.html.

**Comment by micgibso** [comment]
Consider instead adding to new/enhanced log file section, see https://github.com/eclipse/codewind/issues/2141.

**Comment by sishida** [comment]
PR is merged. Closing this issue.
