### ISSUE TITLE
Add tests to the VSCode plugin Jenkinsfile

### ISSUE THREAD

**Issue by stalleyj** [eclipse/codewind#223]
**Description of the enhancement:**

There are currently no tests run during a PR build. 

**Proposed solution:** 

We should add running of the VSCode plugin tests to the PR builds and not upload the results if the tests fail.

**Comment by tetchel** [comment]
helpful links:

- [old travis build with tests run](https://travis-ci.com/microclimate-dev2ops/microclimate-vscode-tools/builds/113808398)
- [old CI scripts](https://github.com/microclimate-dev2ops/microclimate-vscode-tools/tree/master/travis-scripts)
- [new CI scripts](https://github.com/eclipse/codewind-vscode/tree/master/ci-scripts) which I have not really updated

**Comment by tetchel** [comment]
Blocked by https://bugs.eclipse.org/bugs/show_bug.cgi?id=559302

which we're still trying to figure out with the Eclipse team.

**Comment by tetchel** [comment]
The tests are finally running in the build! https://github.com/eclipse/codewind-vscode/pull/539
