### ISSUE TITLE
Display PFE test coverage score on our README.md

### ISSUE THREAD

**Issue by rwalle61** [eclipse/codewind#2231]
**Description of the enhancement:**

We have a decent test coverage score, so we should display it so we can keep an eye on it

**Proposed solution:** 

Display the score as a CodeCov badge on our README.md, like other open source repos e.g. https://github.com/mochajs/mocha

**Further extensions:**
- Display this score on every PR build
- Display a chart of the overall score over time

/kind Test
/area Portal

**Comment by ssh24** [comment]
Could this also include the turbine functional test coverage?

**Comment by rwalle61** [comment]
completed

**Comment by rwalle61** [comment]
part of https://github.com/eclipse/codewind/issues/2291
