### ISSUE TITLE
Increase PFE unit test coverage [Iteration 1]

### ISSUE THREAD

**Issue by rwalle61** [eclipse/codewind#2232]
PFE's current unit test coverage is 32%. PFE's current unit test + API test coverage combined is 68%. That is ok but we should still improve our unit test coverage. 

This is because:
- unit tests are more reliable than API tests, which currently fail intermittently in Jenkins
- unit tests run more quickly than API tests, so we will run them more often during development
- when unit tests fail, they pinpoint where the cause is. When API tests fail, there are many possible causes

We should aim to increase our unit test coverage from 32% to at least 60%.

Here is our unit test coverage:
![image](https://user-images.githubusercontent.com/18170169/74653709-a5f23880-5180-11ea-8005-9723e090b77f.png)

The most important gaps to fill are in `portal/modules`. These are also gaps in our unit test + API test coverage combined:
![image](https://user-images.githubusercontent.com/18170169/74653241-afc76c00-517f-11ea-936f-86bebe0ae64b.png)

So writing these tests will increase both our unit test coverage and our overall coverage.

In `portal/modules`, the most important code to cover is `FileWatcher.js`, `User.js`, and `LoadRunner.js`. Here is our unit test coverage for `portal/modules`:
![image](https://user-images.githubusercontent.com/18170169/74654417-24030f00-5182-11ea-89ad-2fb6864dead4.png)

In addition, we should pull logic out the `routes` files so that we can unit test them. E.g. `projectTypes.route.js`

/area Portal
/kind Test
/assign

**Comment by rwalle61** [comment]
Although `portal/modules/utils` is not well covered, it is not a priority because the key functionality is either already covered or difficult to unit test (e.g. `dockerFunctions.js`):
![image](https://user-images.githubusercontent.com/18170169/74654783-fec2d080-5182-11ea-88be-1dc2e6d93a29.png)

**Comment by rwalle61** [comment]
while doing this, I found and fixed this unexpected behaviour https://github.com/eclipse/codewind/pull/2258

**Comment by rwalle61** [comment]
Results after 2 weeks:
* **unit test coverage overall has risen from 32% to 43%**
* **coverage of `portal/modules` has risen from 33% to 55%** 
* coverage of `User.js` has risen from 0% to 45%
* coverage of `FileWatcher.js` has risen from 0% to 51%
* coverage of `LoadRunner.js` has risen from 0% to 27%
* found and fixed unexpectd behaviour when saving project.inf #2258 
* found and removed some obsolete Portal code #2261 #2311 

Most important unit test gaps remaining:
* test `LoadRunner.js` `runLoad()` properly. We should probably get to ~70% coverage for `LoadRunner.js`
* test `FileWatcher.js` `handleEvents()` properly. We should probably get to ~70% coverage for `FileWatcher.js`
* test remaining bits of `User.js` (get to ~70% coverage)
* add tests for `UserList.js`

More info:

* Current unit test coverage of `portal` overall (rose from 32% to 43%):
![image](https://user-images.githubusercontent.com/18170169/75606877-31f15200-5ae9-11ea-8dfc-80aeb3b31fee.png)


* Current unit test coverage of `portal/modules` (rose from 33% to 55%):
![image](https://user-images.githubusercontent.com/18170169/75606764-0e79d780-5ae8-11ea-8055-6401723003a3.png)

**Comment by rwalle61** [comment]
Prioritised list of gaps in `User.js`:
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by mattcolegate** [comment]
Have raised https://github.com/eclipse/codewind/pull/2410 to deliver on the list of gaps for User.js and to increase coverage to 62.15%

![image](https://user-images.githubusercontent.com/15730986/75987733-4cac3800-5ee8-11ea-9084-ac2b1885d730.png)

**Comment by mattcolegate** [comment]
Have raised https://github.com/eclipse/codewind/pull/2414 to deliver on the list of gaps for Filewatcher.js and to increase coverage to 69.7%

![image](https://user-images.githubusercontent.com/15730986/76000380-88043200-5efb-11ea-90d5-38c88c24ff71.png)

**Comment by mattcolegate** [comment]
Have raised https://github.com/eclipse/codewind/pull/2432 to deliver increased coverage of Loadrunner.js to 60.9%

![image](https://user-images.githubusercontent.com/15730986/76222831-0a019d00-6213-11ea-9e45-a7b24d85ef1f.png)

**Comment by mattcolegate** [comment]
When #2432  is merged, overall unit test coverage will have increased to 67.46% which is enough to close this issue.

/pipeline Review/QA

![image](https://user-images.githubusercontent.com/15730986/76774704-2d40c500-679c-11ea-908a-17726a565207.png)

**Comment by mattcolegate** [comment]
#2432 is now merged. @rwalle61 can this be closed?
/pipeline Verify
