### ISSUE TITLE
Windows Java Profiler is not working if project not in docker share directory

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#2236]
The java profiler attempts to mount a volume back on to the project workspace so that it can see the .hcd file.   If this workspace is not part of docker share, then this will fail.  Need to come up with a solution whereby the hcd can be analysed if not in the share directory

**Comment by hhellyer** [comment]
First though is just to switch it so instead of mounting the project workspace it mounts the docker volume we create for pfe `codewind_cw-workspace` as that will contain the .hcd.

**Comment by mattcolegate** [comment]
Fixing in the above way won't solve the problems remote connection is having, but it will improve the situation for local connections, which @tobespc says will do for now.

**Comment by mattcolegate** [comment]
Awaiting PR review/merge
/pipeline Review/QA
