### ISSUE TITLE
SVT: [Che][Docs] Incorrect title in doc section

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#2238]
**Codewind version:** 0.9.0
**OS:* N/A

**Description:** Incorrect title in doc section (http://codewind-docs.rtp.raleigh.ibm.com:4321/codewind/mdt-che-installinfo.html)

The following section is called "Installing Codewind for Eclipse Che", but the section contains instructions for installing Eclipse Che only.

<img width="1307" alt="Screen Shot 2020-02-17 at 2 40 18 PM" src="https://user-images.githubusercontent.com/49531960/74682445-10f93a80-5194-11ea-8d76-32ec87200536.png">

Codewind is installed using the following instructions: http://codewind-docs.rtp.raleigh.ibm.com:4321/codewind/mdt-che-createcodewindworkspace.html

@jagraj

**Comment by sishida** [comment]
@sujeilyfonseca Here's the PR for the text changes: https://github.com/eclipse/codewind-docs/pull/380

@johnmcollier, @micgibso If the changes look good to go, please add your committer approval. Thank you!

**Comment by sishida** [comment]
Oh, and here's the same title change made to the table of contents along with some other Che table of contents updates: https://github.com/eclipse/codewind-docs/pull/358

@micgibso Is this table of contents PR good to go? I see you already have a table of contents PR open for something else and wasn't sure about merge conflicts there. Thanks!

**Comment by sujeilyfonseca** [comment]
Thanks, @sishida! The title and table of contents look good. Once the PR are merged, this issue can be closed.

**Comment by sishida** [comment]
PR is merged. Closing this issue.
