### ISSUE TITLE
SVT: [IntelliJ] "Connection failed" error if the custom repository url contains an additional space

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#2239]
**Codewind version:** 0.9.0
**OS:** MacOS Mojave 10.14.6, VM with Windows 10

**IDE extension version:** 0.9.0
**IDE version:**
<img width="344" alt="Screen Shot 2020-02-13 at 12 46 11 PM" src="https://user-images.githubusercontent.com/49531960/74462839-dd9a7100-4e5e-11ea-930b-4a87c2dd90f1.png">

<img width="319" alt="Screen Shot 2020-02-13 at 12 45 49 PM" src="https://user-images.githubusercontent.com/49531960/74462840-decb9e00-4e5e-11ea-94e6-d09bc4f0d973.png">

**Description:**  "Connection failed" error if the custom repository link contains an additional space. If users don't realize this, they will never see the Codewind plugin in Marketplace. Also, it might be difficult for them to understand that the error is occurring due to the additional space.

According to @josephca, it seems that IntelliJ doesn't trim the URL for the custom repository. If we cannot do something to avoid this, we must document this to prevent users from having problems installing Codewind for IntelliJ.

<img width="795" alt="Screen Shot 2020-02-17 at 3 01 00 PM" src="https://user-images.githubusercontent.com/49531960/74684255-77348c00-5199-11ea-9971-7d5a0b88a120.png">

![Screen Shot 2020-02-17 at 3 00 29 PM](https://user-images.githubusercontent.com/49531960/74684257-77cd2280-5199-11ea-9b2c-ad1cce4c95b0.png)

@jagraj

**Comment by micgibso** [comment]
Drafted on PR https://github.com/eclipse/codewind-docs/pull/382 as a troubleshooting issue.
@sujeilyfonseca @jgwest @jagraj Please review, thx.

**Comment by sujeilyfonseca** [comment]
The PR was reviewed by @jagraj and me.
