### ISSUE TITLE
Add a PR template to all Codewind repositories

### ISSUE THREAD

**Issue by stalleyj** [eclipse/codewind#2246]
**Description of the enhancement:**

Add a PR template repository to this repository to improve the quality of PRs raised.

**Proposed solution:** 

Add a template file

**Comment by stalleyj** [comment]
@elsony @jopit @sghung Please can you get this PR template into all of the codewind repositories that you own to give us consistency, thanks.

**Comment by rwalle61** [comment]
this ties nicely into https://github.com/eclipse/codewind/issues/2246

**Comment by johnmcollier** [comment]
FYI, codewind-che-plugin already has one, and it's mostly similar to the one added to Codewind, so I'll leave it as-is unless there's a strong desire to make them all the same.

**Comment by rwalle61** [comment]
@stalleyj , are there any repos outstanding without this PR template? (If not we can close this)

**Comment by tetchel** [comment]
I think this is complete

**Comment by stalleyj** [comment]
I still have a few repos to get to, unfortunately this has taken a back seat to fixing Performance dashboard issues...

**Comment by stalleyj** [comment]
This work is now complete.
