### ISSUE TITLE
Java Profiler breaks if another project added to workspace after source view

### ISSUE THREAD

**Issue by mattcolegate** [eclipse/codewind#2248]
**Codewind version:** latest 18/02/2020
**OS:** Windows 10 (but also occurs on Macs)

**Che version:** N/A
**IDE extension version:** VSCode latest 18/02/2020
**IDE version:** VSCode
**Kubernetes cluster:** N/A

**Description:**
The Codewind Java Profiler loads it's workspaces in when it is initialised, in the form of paths related to the source and the mountpoint e.g. `/c/Users/MattColegate/cw_projects/wed12Micro2:/profiling/workspaces/wed12Micro2`. This works if the source being viewed is in the list of known paths. If another project is added to the workspace and it's source is attempted to be viewed, the Profiler doesn't understand the new path and fails to highlight any code. The following is contained in the Profiler log:
```
didOpen: file:///Users/james.wallis1%40ibm.com/weblibtue3/src/main/java/application/rest/v1/Example.java
dockerizeFilePathUsingMountedVolume: /Users/james.wallis1@ibm.com/weblibtue3/src/main/java/application/rest/v1/Example.java
dockerizeFilePathUsingMountedVolume: /Users/james.wallis1@ibm.com/weblibtue3/src/main/java/application/rest/v1/Example.java
Project Path for file: null
```

**Steps to reproduce:**
1. Add a Java project to the workspace which has profiling data and view a source file. Highlighting appears as expected.
2. Add another Java project which has profiling data to the workspace and view a source file. Highlighting fails to appear. Log contains above content.

**Workaround:** 

Restart VSCode after adding the second project. When viewing a source file now, both project workspaces are passed to the profiler and both source files will have correct highlighting applied.

**Comment by hhellyer** [comment]
Unassigning as we're working on improving the whole profiling story.

**Comment by mattcolegate** [comment]
The improvement work on the profiling will make this problem obsolete, so closing.
