### ISSUE TITLE
SVT:Performance load tests failing with error message for WebSphere liberty projects.

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#2252]
**Codewind version:** 0.9.0
**OS:** CoreOS

**Che version:** 7.5.1
**IDE extension version:** 0.9.0
**IDE version:**
**Kubernetes cluster:** OCP 4.3

**Description:**
I am getting `Type Error: Faield to fetch` on the browser window when I try to run load test for WebSphere project once it is start running. If I click ok for the error and close the window and try to open new performance window then i see the results. This was working fine and some how this is broke with the GA sniff tests and with brand new workspace.  This happens only on Che codewind workspace but not for local. 

**Steps to reproduce:**
1. Install Codewind 0.9 workspace on Che 7.5.1
2. Create WebSphere liberty or OpenLiberty project from Codewind workspace.
3. After successful running try to run load test from "Performance monitoring" window.
4. You see following failure.

![image](https://user-images.githubusercontent.com/713849/74764980-ba9e0180-5250-11ea-8248-c8d4abe1a439.png)

After clicking ok and opening new window then I see the results.
![image](https://user-images.githubusercontent.com/713849/74765869-4a907b00-5252-11ea-89e8-8c5da6532e09.png)

Logs 

[performance.txt](https://github.com/eclipse/codewind/files/4220936/performance.txt)
[pfe.txt](https://github.com/eclipse/codewind/files/4220937/pfe.txt)
[theia.txt](https://github.com/eclipse/codewind/files/4220938/theia.txt)

**Workaround:** 

1. Click "ok" to the error dialog.
2. Open new "Performance window" for the project then you will see the results.

**Comment by rajivnathan** [comment]
I wasn't able to reproduce.
Codewind version: 0.9.0
Che version: 7.6
IDE extension version: 0.9.0
IDE version:
Kubernetes cluster: OCP 3.11

**Comment by jagraj** [comment]
**Test 1**

Codewind version: 0.9.0
Che version : 7.5.1
IDE Extension version : 0.9.0
Kubernetes cluster : OCP 4.3
Browser : Chrome Version 80.0.3987.116 (Official Build) (64-bit)

I created new workspace and tried to reproduce this problem again after clearing my browser cache in chrome and I am still hitting this problem. 

<img width="1654" alt="Screen Shot 2020-02-19 at 6 23 25 PM" src="https://user-images.githubusercontent.com/713849/74895658-3f2b7580-5360-11ea-80ae-01f73a0d3de3.png">

**Test 2**

Codewind version: 0.9.0
Che version : 7.5.1
IDE Extension version : 0.9.0
Kubernetes cluster : OCP 4.3
Firefox : Chrome Version 80.0.3987.116 (Official Build) (64-bit)

I tried same from  Firefox browser and I am hitting `Load run already in progress` and we reported this problem in Issue #2253 

<img width="1680" alt="Screen Shot 2020-02-19 at 7 31 06 PM" src="https://user-images.githubusercontent.com/713849/74895921-ed371f80-5360-11ea-9b44-753ee1b8b5f3.png">

**Comment by jagraj** [comment]
**Codewind 0.8.1**

**Test 1**

Codewind version: 0.9.0
Che version : 7.5.1
IDE Extension version : 0.9.0
Kubernetes cluster : OCP 4.3
Browser: Firefox 72.0.2 (64-bit)

I did similar tests with 0.8.1 fix pack workspace and I see same  problem for WebSphere liberty default template project and rest of the projects works fine. I think something changed in WebSphere base image to cause this problem and this is my guess but you can also run more tests from your clusters and also I am sharing my cluster info to @tobespc to reproduce this problem. 

<img width="1680" alt="Screen Shot 2020-02-19 at 11 05 56 PM" src="https://user-images.githubusercontent.com/713849/74905448-33e64300-537c-11ea-8556-ad84250cf451.png">

<img width="1680" alt="Screen Shot 2020-02-19 at 10 54 51 PM" src="https://user-images.githubusercontent.com/713849/74905449-33e64300-537c-11ea-9c7b-5017348bd50b.png">

**Comment by jagraj** [comment]
Fixed in 0.9.0 closing it.
