### ISSUE TITLE
SVT: [Remote] Performance test is failing with an error saying that another load run is in progress

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#2253]
**Codewind version:** 0.9.0
**OS:** MacOS Mojave 10.14.6, VM with Windows 10, and Linux (w. OpenShift 3.11 and 4.2 clusters)

**IDE extension version:** 0.9.0
**IDE version:** VS Code 1.42.0

**Description:** @DavidG1011 and I noticed that performance tests are failing on remote for Websphere Liberty MicroProfile. If you try to run a new test, an error will appear, indicating that a "load run is already in progress".

<img width="1507" alt="Screen Shot 2020-02-18 at 1 30 29 PM" src="https://user-images.githubusercontent.com/49531960/74767425-d60b0b80-5254-11ea-8025-f5d953a994d8.png">

**Steps to reproduce:**
1. Install and start Codewind 0.9.0 
2. Create WebSphere Liberty MicroProfile project 
3. After achieving a "Running" application status, try to run a load test using the Performance Dashboard
4. Error will appear 

**Workaround:** After opening a new window, I can see the results of the previous tests and I can run a new load test without receiving any errors:

<img width="1517" alt="Screen Shot 2020-02-18 at 1 50 30 PM" src="https://user-images.githubusercontent.com/49531960/74767958-c3dd9d00-5255-11ea-9f52-352be9c7057d.png">

<img width="1501" alt="Screen Shot 2020-02-18 at 1 52 27 PM" src="https://user-images.githubusercontent.com/49531960/74768055-ea9bd380-5255-11ea-9e65-46a5a7b530ef.png">

@jagraj

**Comment by johnmcollier** [comment]
Sounds like the same issue as https://github.com/eclipse/codewind/issues/2252?

**Comment by jagraj** [comment]
It could be, but clients are different that is why we are seeing different behavior.

**Comment by jagraj** [comment]
Please take a look at my comments on this issue #2252. 
https://github.com/eclipse/codewind/issues/2252#issuecomment-588581654
https://github.com/eclipse/codewind/issues/2252#issuecomment-588625270

**Comment by sujeilyfonseca** [comment]
I verified this issue with the latest Codewind 0.9.0, and I no longer reproduce this problem.

This issue can be closed once the fix has also been merged into master.

**Comment by malincoln** [comment]
@tobespc @markcor11 has this been merged into master?

**Comment by malincoln** [comment]
@tobespc looks like this was bounced back to in progress. I think it can be closed now that the fix has been merged into master.  @sujeilyfonseca did verify on 0.9.0.
