### ISSUE TITLE
Add tests to the Eclipse plugin Jenkinsfile

### ISSUE THREAD

**Issue by stalleyj** [eclipse/codewind#226]
There are currently no tests run during a PR build.

**Proposed solution:**

We should add running of the Eclipse plugin tests to the PR builds and not upload the results if the tests fail.

**Comment by eharris369** [comment]
Fixed by:
- https://github.com/eclipse/codewind-eclipse/pull/673
- https://github.com/eclipse/codewind-eclipse/pull/682

**Comment by stalleyj** [comment]
Great to see tests in Jenkins, thanks.
