### ISSUE TITLE
Documentation step not quite correct for IntelliJ download

### ISSUE THREAD

**Issue by AndyRWatson** [eclipse/codewind#2260]
**Codewind version:**
**OS:** 0.9

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**

In the IntelliJ doc update,  the documentation implies to follow the link to eclipse download page and select the zip file to download, however the link is already direct to the zip file not the page so automatically downloads the plugin from the link rather than links to the page.
**Steps to reproduce:**

Follow documentation https://www.eclipse.org/codewind/intellijtechpreview.html

Installing Codewind on IntelliJ from the Eclipse Downloads page
Go to the Eclipse Downloads page and click codewind-intellij-0.9.0.zip to download the file.

**Workaround:** 

Plugin still downloads just steps not correct. Suggest changing to download from here ?

**Comment by micgibso** [comment]
@sishida For your awareness

**Comment by sishida** [comment]
@AndyRWatson Thanks for pointing this out. I have created a PR to make the instructions more accurate: https://github.com/eclipse/codewind-docs/pull/392

@micgibso If the changes look good to go, please review/approve/merge. Thank you!

**Comment by sishida** [comment]
PRs have been merged. Closing this issue.

**Comment by sishida** [comment]
See PR https://github.com/eclipse/codewind-docs/pull/396/files
