### ISSUE TITLE
[IntelliJ] IntelliJ on JetBrains Marketplace

### ISSUE THREAD

**Issue by josephca** [eclipse/codewind#2263]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description of the enhancement:**

**Proposed solution:**

**Comment by jopit** [comment]
Documentation on the JetBrains Marketplace: https://plugins.jetbrains.com/docs/marketplace/

**Comment by josephca** [comment]
It seems there is no existing IBM org yet in JenBrains Marketplace. 
Here are the required inputs in order to create one. 

![image](https://user-images.githubusercontent.com/25185698/74848779-02329500-5306-11ea-9ffe-e7d23c4952af.png)

**Comment by josephca** [comment]
In order to publish a new plugin, we need to fill out this form. 

![image](https://user-images.githubusercontent.com/25185698/74849034-42921300-5306-11ea-9626-07eaa972e87a.png)

**Comment by jasperchui** [comment]
@josephca please followup with @malincoln for the status of the legal discussion. We already got approval.
