### ISSUE TITLE
Add section for using Appsody stacks images to intellij_tech_preview

### ISSUE THREAD

**Issue by sghung** [eclipse/codewind#2264]
By EOD Thursday Feb 20, we need the appsody stack info into the troubleshooting section because the kabanero-io team needs the documentation to be public.

The PR we need into that branch is: https://github.com/eclipse/codewind-docs/pull/363

**Comment by sishida** [comment]
OK, I will merge the change to the `intelllij_tech_preview` branch.

**Comment by sishida** [comment]
@sghung Hi, Steven, Thanks for opening this issue. Here's the PR to update the Troubleshooting file: https://github.com/eclipse/codewind-docs/pull/391
