### ISSUE TITLE
[IntelliJ] Use notifications to indicate that content of a log has changed

### ISSUE THREAD

**Issue by keithchong** [eclipse/codewind#2269]
All the logs for a project are listed in a combo box in the Log files tool window.  That means, if a log that isn't currently selected has new content, the user will not know.  Currently there is no visual indicator or notifier to inform the user.

In Eclipse, there is an option to "Show on Content Change".   There is no console view action similar to this in IntelliJ. (It does have scroll to bottom and soft wrap)

**Comment by keithchong** [comment]
Follow-on to original issue: https://github.com/eclipse/codewind/issues/989

**Comment by keithchong** [comment]
<img width="668" alt="Screen Shot 2020-04-16 at 5 26 04 PM" src="https://user-images.githubusercontent.com/7726022/79509050-c3207780-8008-11ea-9af6-9d14c3628711.png">

**Comment by keithchong** [comment]
To turn off the popup notifications, change the combo box value to `No popup`. By default, the Log checkbox should be unchecked. These should not be in the Event Log.

<img width="1126" alt="Screen Shot 2020-04-16 at 5 26 58 PM" src="https://user-images.githubusercontent.com/7726022/79509068-ce73a300-8008-11ea-9de0-c8b5760c043d.png">

**Comment by keithchong** [comment]
@sishida , @jopit, should we document how to turn off these notifications? This is IntelliJ-specific.

**Comment by keithchong** [comment]
Target 0.12.0

**Comment by sishida** [comment]
@keithchong If you turn off all IntelliJ notifications in the same way, I'm thinking we wouldn't need to document the Codewind notifications. But if we're introducing something sort of new or different into IntelliJ, then we should document that.
