### ISSUE TITLE
Add Turbine tests to the Jenkinsfile

### ISSUE THREAD

**Issue by stalleyj** [eclipse/codewind#227]
The Turbine tests are not currently run as part of a PR build. 

**Proposed solution:**

We should add the Turbine functional tests to the PR builds as a step before the API tests and not continue if any of them fail.

**Comment by rajivnathan** [comment]
@stalleyj This appears to be a duplicate of https://github.com/eclipse/codewind/issues/138. Think we can close this one in favour of that

**Comment by stalleyj** [comment]
Closing as duplicate item.
