### ISSUE TITLE
[IntelliJ] Disable 'Add Existing Project' action if Codewind isn't started

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind#2274]
Otherwise when you try to bind and existing project, the wizard doesn't work with no indication of what's wrong.

**Comment by keithchong** [comment]
Enabling/Disabling menus actually is not trivial.  This applies to any of our actions in general, where enable/disable applies depending on some situation.  Eg. the stop and start actions are still enabled even though the actions have already been initiated and in the process of stopping and starting respectively.  In Codewind for Eclipse, during this transition period, the only action available is Refresh.

The logic in the update method on an AnAction to determine the enable/disable states must execute quickly. (It is run on the UI thread). For example, it can't call CLI to execute and wait for a response.

It is better to remove the actions altogether than disable/enable the actions.

**Comment by keithchong** [comment]
<img width="523" alt="Screen Shot 2020-02-27 at 5 27 02 PM" src="https://user-images.githubusercontent.com/7726022/75493319-9dbba980-5987-11ea-94f8-656fac2ea5d4.png">

**Comment by keithchong** [comment]
<img width="529" alt="Screen Shot 2020-02-27 at 5 36 18 PM" src="https://user-images.githubusercontent.com/7726022/75493356-b035e300-5987-11ea-8132-2a4e95471b2a.png">

**Comment by keithchong** [comment]
<img width="525" alt="Screen Shot 2020-02-27 at 5 36 57 PM" src="https://user-images.githubusercontent.com/7726022/75493405-c80d6700-5987-11ea-9428-4e1fdb269df9.png">

**Comment by keithchong** [comment]
<img width="519" alt="Screen Shot 2020-02-27 at 5 37 33 PM" src="https://user-images.githubusercontent.com/7726022/75493437-dd829100-5987-11ea-944f-0bb78d72774f.png">
