### ISSUE TITLE
SVT: Che: Adding an existing template source repository produces an unhelpful error.

### ISSUE THREAD

**Issue by DavidG1011** [eclipse/codewind#2277]
**Codewind version:** 0.9.0

**Che version:** 7.5.1
**IDE extension version:** 0.9.0
**Kubernetes cluster:** OKD 4.2

**Description:** Adding an existing template source repository produces an unhelpful error.

**Steps to reproduce:**
1. Open the Template Source Manager.
1. Add a template source repository.
2. Add another template source repository with the same name.

![image](https://user-images.githubusercontent.com/30476587/74878608-a1bb4c00-5335-11ea-9403-f7acd4340933.png)

It might be better to have the error message specify that a repo with the same name already exists.

**Comment by tetchel** [comment]
i will remove that button, oops

**Comment by tetchel** [comment]
the button which was there mistakenly is being removed here: https://github.com/eclipse/codewind-vscode/pull/472/files#diff-1a0f82d729a69fe49b4e0252baafeda2L120

**Comment by tetchel** [comment]
The same unhelpful message is printed if the URL given is invalid / 404

**Comment by rwalle61** [comment]
thanks, https://github.com/eclipse/codewind-installer/pull/431 should improve all the error messages from adding template sources/repositories

**Comment by DavidG1011** [comment]
This now produces a much better error message:
<img width="454" alt="Screen Shot 2020-04-23 at 1 31 22 PM" src="https://user-images.githubusercontent.com/30476587/80130627-ea29fc80-8566-11ea-9f5c-ca4636f7cf76.png">
Thank you both
