### ISSUE TITLE
Codewind should react to a project being deleted from disk

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#2278]
If I delete a project's entire root directory, Codewind doesn't react to it at all until I do a manual build, even if auto-build is on.

**Comment by tetchel** [comment]
Not sure which area of the sync/auto-build cycle this is part of, so I added both.

**Comment by tobespc** [comment]
Is the filewatcher spotting the directory has been deleted ?

**Comment by tetchel** [comment]
Yes it is, if I `rm -rf /Users/tim/programs/vscode-codewind-workspace/apps-mpp` here are the filewatcherd logs:

```
[March 2, 15:29:43.189] [113.813] Received event [DELETE] /Users/tim/programs/vscode-codewind-workspace/apps-mpp/target/test-classes/it/dev/appsody/starter/HealthEndpointTest.class
[March 2, 15:29:43.196] [113.820] Received event [DELETE] /Users/tim/programs/vscode-codewind-workspace/apps-mpp/target/test-classes/it/dev/appsody/starter
[March 2, 15:29:43.202] [113.826] Received event [DELETE] /Users/tim/programs/vscode-codewind-workspace/apps-mpp/target/test-classes/it/dev/appsody
[March 2, 15:29:43.204] [113.828] Received event [DELETE] /Users/tim/programs/vscode-codewind-workspace/apps-mpp/target/test-classes/it/dev
[March 2, 15:29:43.206] [113.830] Received event [DELETE] /Users/tim/programs/vscode-codewind-workspace/apps-mpp/target/test-classes/it
[March 2, 15:29:43.207] [113.831] Received event [DELETE] /Users/tim/programs/vscode-codewind-workspace/apps-mpp/target/test-classes
[March 2, 15:29:43.634] [114.258] Received event [DELETE] /Users/tim/programs/vscode-codewind-workspace/apps-mpp/target/liberty/wlp/lib/features/l10n/com.ibm.websphere.appserver.appClientSupport-1.0_it.properties
< 2000 lines of deleted files under the deleted directory >
[March 2, 15:29:50.564] [121.188] Received event [DELETE] /Users/tim/programs/vscode-codewind-workspace/apps-mpp
[March 2, 15:29:51.575] [122.199] Batch change summary for c27fe0f0-54f6-11ea-a588-231bd32b0ee5 @ 1583180990564: [ -HealthEndpointTest.class -starter -appsody -dev -it -test-classes -com.ibm.websphere.appserver.appClientSupport-1.0_it.properties -com.ibm.websphere.appserver.kernelCore-1.0.properties -com.ibm.websphere.appserver.appClientSupport-1.0_cs.properties -com.ibm.websphere.appserver.appSecurity-2.0_zh.properties  (...) ]
[March 2, 15:29:51.576] [122.200] Calling cwctl project sync with: { [--insecure] [project] [sync] [-p] [/Users/tim/programs/vscode-codewind-workspace/apps-mpp] [-i] [c27fe0f0-54f6-11ea-a588-231bd32b0ee5] [-t] [1583180880036] }
[March 2, 15:29:51.816] [122.440] ! ERROR !  Error running 'project sync' installer command time="2020-03-02T15:29:51-05:00" level=error msg="stat /Users/tim/programs/vscode-codewind-workspace/apps-mpp: no such file or directory"

[March 2, 15:29:51.816] [122.440] ! ERROR !  Stdout:No output
[March 2, 15:29:51.817] [122.441] ! ERROR !  Stderr:time="2020-03-02T15:29:51-05:00" level=error msg="stat /Users/tim/programs/vscode-codewind-workspace/apps-mpp: no such file or directory"

[March 2, 15:29:51.817] [122.441] !!! SEVERE !!!  Unexpected exception from CLI:
[object Object]
[March 2, 15:29:54.682] [125.306] Initiating GET request to http://127.0.0.1:10000/api/v1/projects/watchlist
[March 2, 15:29:54.720] [125.344] GET response received: {"projects":[{"projectID":"c27fe0f0-54f6-11ea-a588-231bd32b0ee5","projectWatchStateId":"cea8b8efd23ef252b702e84c1e2a6894","pathToMonitor":"/Users/tim/programs/vscode-codewind-workspace/apps-mpp","ignoredPaths":["*/.idea/*","*.iml","/.project","/load-test*","*/*.swp","*/*.swx","*/.gitignore","*/node_modules*","*/4913","*/.git/*","*/.DS_Store","*/.dockerignore","*/*~","/.settings","/.classpath","/.options","/.vscode/*"],"refPaths":[],"projectCreationTime":1583180880067},{"projectID":"39791e00-58c2-11ea-99b8-05c1a3bc112f","projectWatchStateId":"32eef779d71ae6c80693ef97e301f5d6","pathToMonitor":"/Users/tim/programs/vscode-codewind-workspace/appsnode","ignoredPaths":["*/.idea/*","*.iml","/.project","/load-test*","*/*.swp","*/*.swx","*/.gitignore","*/node_modules*","*/4913","*/.git/*","*/.DS_Store","*/.dockerignore","*/*~","/.settings","/.classpath","/.options","/.vscode/*","/run-dev","/run-debug","/package-lock.json*","/nodejs_restclient.log","/nodejs_dc.log","/manifest.yml","/idt.js","/cli-config.yml","/README.md","/Jenkinsfile","/.cfignore"],"refPaths":[],"projectCreationTime":1583180874904}]}
[March 2, 15:29:54.721] [125.345] Examining file watch state from GET request
[March 2, 15:29:54.722] [125.346] The project creation time has changed, when both values were non-null. Old: 1583180280889 New: 1583180880067(Mon Mar 02 2020 15:28:00 GMT-0500 (Eastern Standard Time)), for project c27fe0f0-54f6-11ea-a588-231bd32b0ee5
[March 2, 15:29:54.723] [125.347] The project watch state has not changed for project c27fe0f0-54f6-11ea-a588-231bd32b0ee5
[March 2, 15:29:54.723] [125.347] The project creation time has changed, when both values were non-null. Old: 1583180271547 New: 1583180874904(Mon Mar 02 2020 15:27:54 GMT-0500 (Eastern Standard Time)), for project 39791e00-58c2-11ea-99b8-05c1a3bc112f
[March 2, 15:29:54.724] [125.348] The project watch state has not changed for project 39791e00-58c2-11ea-99b8-05c1a3bc112f
[March 2, 15:29:54.724] [125.348] HttpGetStatus - GET request loop complete.
[March 2, 15:30:00.095] [130.719] IDE returned a new security token to filewatcher: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAi
[March 2, 15:30:00.095] [130.719] Initiating GET request to https://codewind-gatekeeper-k73k7t85.codewind-ide-312685-991fa493e65cfa1b406d26eea92b71a6-0000.tor01.containers.appdomain.cloud/api/v1/projects/watchlist
[March 2, 15:30:00.250] [130.874] GET response received: {"projects":[]}
[March 2, 15:30:00.250] [130.874] HttpGetStatus - GET request loop complete.
[March 2, 15:30:20.569] [151.193] dispose() called on WatchedPath for /Users/tim/programs/vscode-codewind-workspace/apps-mpp
```

**Comment by jgwest** [comment]
The current filewatcherd behaviours appear to be:
- Java (non-Eclipse): Detects the change but does not correctly report it. Fix attached as PR.
- TypeScript: Detects the change and correctly reports it.
- Go: Detects the change but does not report it. Fix attached as PR.
- Java (Eclipse): Detects the change, but I don't see an obvious way to get the path of a deleted project from the IProject API, work continues... 


@tobespc  FYI the output of the filewatcher from Tim's previous comment indicates that cwctl is not correctly handling this case, eg the following is printed by cwctl:
```
time="2020-03-02T15:29:51-05:00" level=error msg="stat /Users/tim/programs/vscode-codewind-workspace/apps-mpp: no such file or directory"
```
It's a bit tough to tell from the log output, but that *is* from cwctl stdout/stderr, and not part of the FWd log statement. I presume cwctl is assuming that the `-p` directory param exists.

**Comment by tobespc** [comment]
if you do delete an entire root delete, what would be the reasoning behind doing that ?  Would you be thinking the project should be deleted from codewind (as in unbind) ?

**Comment by tetchel** [comment]
I don't know, really, but i expected at least something to happen 😅

**Comment by tetchel** [comment]
I guess the reasons to delete the directory would be by accident, to try and move it to another location on disk, or if I wasn't interested in the project any more but didn't know how / forgot to remove it from Codewind first.

**Comment by jgwest** [comment]
My expectation is that if you delete the project directory (for whatever reason), it should remove the project from Codewind (eg delete project files inside the container, delete the application containers, stop tracking its state, remove it from the active projects list, etc).

**Comment by tobespc** [comment]
What should happen (based on current design) is 

  - Project files deleted from disk
  - Filewatcherd detects this and notifies cwctl of file changes
  - cwctl determines that all the files have been deleted
  - files on pfe end are deleted to keep in line with local changes
  - build will fail as no project artifacts
  - ide is notified of failing build

If this is not the case then this should be a bug

**Comment by jgwest** [comment]
Presuming that your definition of 'project files deleted from disk' includes the root project directory, then based on the behaviour we are seeing, the following are currently not true:
- Filewatcherd detects this and notifies cwctl of file changes
- cwctl determines that all the files have been deleted 

So I will convert this item to a bug.

**Comment by tetchel** [comment]
@tobespc the filewatcherd PRs have been merged, so I think the only blocker for this is `cwctl` falling over when the deleted directory doesn't exist

**Comment by jcockbain** [comment]
It's correct that a blocker for cwctl is if a non-existing local dir is passed as the `-p` parameter to sync. I'm assuming that's whats being called by the filewatcher/IDE when the root project dir is deleted? 

The flow seems to work as expected if the entire contents of project is deleted i.e. `rm -rf /workspace/project/*`. Where `cwctl` is erroring is if that local project path doesn't exist (i.e the whole project has been deleted). 

From reading this issue, it seems to me that the call made to `cwctl` after project root dir deletion is the same as normal sync, with the only difference being the path now not existing? So cwctl will need a way to differentiate between a situation where a user has deleted the project (and then sync to remove all files from the project container), and one in which the wrong path has been given (and return a suitable error).

This could be a check against the `locOnDisk` of that project. If the given path matches, sync. If not, return an error.

**Comment by jcockbain** [comment]
An alternative would be to return a proper error (with the relevant projectID) in the situation where sync is attempted with a local path that doesn't exist. The IDEs could then ask the user if they want to remove that project from Codewind. 

That's my preferred option personally.

**Comment by tetchel** [comment]
If you send a `projectDeletion` event over the socket the IDE will delete the project from codewind

**Comment by jgwest** [comment]
> It's correct that a blocker for cwctl is if a non-existing local dir is passed as the -p parameter to sync. I'm assuming that's whats being called by the filewatcher/IDE when the root project dir is deleted?

Yep, the filewatcherd (Node/Go/Java) and the IDE (I believe) is calling cwctl with `-p` pointing to the expected location of the project (which now no longer exists).

> Where cwctl is erroring is if the local project path (-p parameter) doesn't exist (i.e the whole project has been deleted).

Correct.

> From reading this issue, it seems to me that the call made to cwctl after project root dir deletion is the same as with standard sync. The only difference being the path now doesn't exist? 

All correct.

And some of the implementation details depends on how y'all want to handle this scenario: Should we inform the user (via IDE UI socket) and just let the user sort it out? Should we automatically delete the project the from codewind server (and inform the IDE that the project is gone)? etc.

> Having discussed this in the Portal scrum, I was made aware this error is being returned to the filewatchers and will not be seen by the IDEs. 

Yep, it would usually be the filewatchers that notice this, and they have don't have* a direct connection to the IDE. (*the filewatchers and the IDE are treated as separate entities, as, for example, the filewatcher that runs in Che [the Go filewatcher] has no IDE. And so the filewatcher architecture is designed to run with very limited connection to the IDE, if any.)

As I said it's up to you all how this is handled, but I had envisioned it something like:
1) Filewatcher detects that project path is gone and calls cwctl project sync (filewatcher will now correctly do this as of latest patches)
2) cwctl project sync notices the path is gone, and issues an HTTP request to the Codewind server informing it that the path directory no longer exists on disk. (whether via the sync api, or a new api)
3) The codewind server receives that request and removes the project from its internal project list (performing an equivalent to a delete/unbind, I guess?) and then informs the IDE of the change via UI socket
4) IDE does any UI cleanup and/or any user informing

(@jcockbain)

**Comment by jcockbain** [comment]
Thanks @jgwest, @tetchel 

Steps 2 and 3 wouldn't be much extra work to implement. The majority of that logic already exists in the `cwctl project remove` command and the Codewind server `/unbind ` API respectively. 

Our only concerns are around `cwctl` clearing up a project behind the scenes, without the user verifying it. With that flow, if sync is called with a filepath not on a user's filesystem, the project would be deleted, correct? I can also add a check that the given path equals the locOnDisk of the project, but that currently isn't checked and limits syncing to the `locOnDisk` set for the project. 

To allow  a user to verify, a slightly extended flow could be something like this? 

2. `cwctl project sync` called with non-existing dir, this calls the Codewind server to emit a UI socket message (different from `projectDeletion`), stating the local path of the project is missing. 

3. The IDEs present the user with the option to delete the project. If they confirm, `cwctl project remove` or `/unbind` API is called as normal.

**Comment by tetchel** [comment]
To implement 3. you would have to either add a payload to the `projectDeletion` event to indicate a prompt is necessary. also, we'd have to make sure `cwctl project remove` won't error if the directory has already been deleted.

**Comment by jcockbain** [comment]
There's a deleteFiles boolean flag on the delete command I think, which should ignore the local directory if set false.

**Comment by tetchel** [comment]
yeah, i guess the prompt that sets that parameter would be skipped in this scenario, that works.

**Comment by jcockbain** [comment]
@tetchel is there IDE preference be for a modified payload on the `projectDeletion` message, or new message type?

**Comment by tetchel** [comment]
I guess a new message is clearer

**Comment by hhellyer** [comment]
I'm reviewing James's PR's and can't help feeling this is all bit over complicated.
We are essentially adding an API onto PFE that just triggers sending a socket message straight back so the local file-watcher can notify the local IDE that a directory is missing. Sending that message by round tripping it through a REST call and socket message doesn't seem the most straight forward solution.

Given that we are changing both the file-watcher, to spot the directory has been deleted and the IDE plugins to handle a socket message saying the directory has been deleted locally wouldn't it be easier to provide the file-watcher a way to tell the IDE directly?

In the VSCode plugin there is already a callback object it can use to get authentication details, `IAuthTokenProvider ` :
https://github.com/eclipse/codewind-vscode/blob/6991172281d5b5a7956e07a3aa018987c314e2c0/dev/src/codewind/connection/RemoteConnection.ts#L158
providing something similar to that mechanism to handle things like this would make sense. This issue is essentially a local filesystem problem, it seems excessive to handle it going via a REST API call. There's not really any need to involve PFE until the user has decided if they want to delete the project or not.

Outside testing this issue is most likely to occur at startup/connection time if folders or workspaces have been moved/deleted so it would make sense to handle locally, early on. (Also as an aside we should verify the editors cope if multiple projects disappear at once, for example if someone deletes a workspace folder holding 5 projects in sub directories how does the IDE plugin show this?)

**Comment by jgwest** [comment]
I should write this up in full as a design doc, as every time folks encounter the filewatcher they want to connect the IDE to it 😄 

But in short:
- The filewatcher does not have an IDE connected to it in all cases, and thus you cannot presume one is present. For example, when running on Che, the (Go) Filewatcher and Theia are not only not running in the same process, but are running in entirely different containers.
- Every change to the filewatcher has a high implementation cost: that new feature must be implemented in 3 different codebases (Go, Node, and Java), and tested/integrated across 4 IDEs (VSCode, Che, Eclipse, Intellij). 
- This inherent complexity/duplication means the filewatcher is designed to be as simple a standalone microservice as possible, with as few moving parts as possible; by further increasing IDE integration, we add complexity/maintenance burden to both the FWs and the IDEs
- It's true there is limited IDE integration, but that is only through a single interface, `IAuthTokenProvider`, with a [simple, clearly defined "contract"](https://github.com/eclipse/codewind/issues/1309) between the IDE/filewatcher, and no shared state between them. It likely would have been a pain-and-a-half to share the cwctl authtoken via any other mechanism.

And another (probably less convincing) point - the filewatcher architecture was designed to support the headless IDE case, and I'd like not to shut the door on that:
- From the beginning, the filewatcher architecture was designed to support the headless IDE case, which is the case where you are not using a supported IDE (Eclipse IDE/VSCode/Intellij/Theia), but rather are editing source files from the command line (Vim/Emacs/Nano) or in an unsupported IDE (Textmate/Sublime/Atom/etc). 
- This scenario might look like this (pseudo commands), all from the CLI:
```
cwctl create project java  # cwctl creates a project in the current directory and informs PFE container
cwctl watch # cwctl starts the go filewatcher, and the go filewatcher starts listening for file changes, informing the PFE container as needed
# User edits a file in Sublime Text, and hits save, and a build/deploy is automatically triggered.
```
- In this scenario the user would be running w/o an IDE, and yet they can still see their file changes reflected in the running application.
- While we don't currently support this in Codewind, I'd like to leave the door open by not further increasing IDE <-> Filewatcher integration, at least until something else closes it for us :). Though admittedly we were more interested in this use case when Codewind/FW were first created; I've not heard talk of it recently FWIW.

So, the high level is that until we get rid of the Go filewatcher one cannot assume an IDE is present, and even after that I would push back on increasing IDE integration for the reasons described above.

**Comment by hhellyer** [comment]
That helps a little, although now I'm worried about the scenario where we have a standalone file-watcher and the project folder is removed, as you say that's mostly hypothetical at this point though. (What happens to the running filewatcher? How do we make a decision about what to do with the project? How does the file-watcher get shut down? Does it just exit and stop watching that folder?)

I think there's still a pretty high cost, we aren't avoiding altering the filewatcher (there's still a new API it has to call just on PFE instead of the callback) we are still altering all 3 IDEs (to handle the new socket message) and we are also altering PFE but the Che scenario does probably mean we have to do this via PFE and the need to use the VSCode plugin in Che unaltered as much as possible probably means we need to do this.

**Comment by jcockbain** [comment]
@tetchel - the cwctl and PFE PRs have been merged. So now when `cwctl sync` is called with a non-existent path matching the project's `locOnDisk`, it won't error as it did before and a `missingLocalDir` socket message should be emitted with the body `{projectID: <projectid>}`.

This issue was discussed yesterday in Portal's scrum and whilst this way around does seem a bit long winded, there wasn't a clear simpler solution suggested. 

Happy to discus anything else that needs adding/changing from a PFE and cwctl side once the IDEs get a chance to work with this.

**Comment by tetchel** [comment]
ok, i'll open a new issue for the IDE component.

**Comment by tetchel** [comment]
ok, i'll open an issue for the IDE component.
