### ISSUE TITLE
[VSCode] Connecting to remote Codewind prevents user editing connection credentials

### ISSUE THREAD

**Issue by ebuckle** [eclipse/codewind#2279]
**Codewind version:** 0.9
**OS:** macOS

**Che version:** NA
**IDE extension version:** 0.9
**IDE version:** 1.42.1
**Kubernetes cluster:** NA

**Description:**
Starting a connection to a remote PFE prevents a user from editing the credentials for that deployment. The UI window constantly refreshes, causing the input boxes to reset, as shown below:

![out](https://user-images.githubusercontent.com/33088613/74929347-34f68f00-53d3-11ea-8381-0b5b4b8e9130.gif)

**Steps to reproduce:**
- Start connecting to a remote Codewind
- While connecting, press Edit on the connection settings panel
- Try to edit the login details

**Workaround:** 

None found. UI works normally when not connecting to a remote Codewind.

**Comment by tetchel** [comment]
For the connection to get stuck in the "connecting" state like that, the likely cause is that your Codewind instance is down / unreachable. do you know if that was the case?

would blocking (greying out) the "edit" button while it's Connecting / Disconnecting, so that the user knows they have to wait, be an acceptable change?

**Comment by ebuckle** [comment]
Yep, this was caused by having a Codewind instance being restarted while I was trying to connect. My initial thought as a user was that I'd put in the wrong username or password so I tried to change those first.

Yep, I think greying out the buttons and saying that Codewind is trying to connect would stop someone hitting this.

**Comment by tetchel** [comment]
ok, i think a 10s timeout is also generous (no one will wait that long before trying to do something else) so i will shorten it too.
