### ISSUE TITLE
SVT: Container Shell does not work correctly with Java Lagom projects

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#228]
**Codewind version:** 0.3
**OS:** Windows 10 and MacOS Mojave (10.14.5)

**IDE extension version:** latest
**IDE version:** VS Code 1.37.1 and Eclipse 2019-06 (4.12.0)

**Description:** Container Shell does not work correctly with Java Lagom projects.

<img width="1505" alt="Screen Shot 2019-08-20 at 8 58 01 AM" src="https://user-images.githubusercontent.com/49531960/63361486-3c62b000-c33e-11e9-98f3-dd3f6f71a9c3.png">

<img width="1494" alt="Screen Shot 2019-08-20 at 11 33 38 AM" src="https://user-images.githubusercontent.com/49531960/63362382-ba738680-c33f-11e9-8fda-4a1a78c7d498.png">

**Steps to reproduce:**
1. Install Codewind
2. Create a Java Lagom project 
3. Right click on the created project 
4. Click on "Open Container Shell"

@jagraj

**Comment by tetchel** [comment]
I expect this bug will happen in Eclipse too. Can you verify?

**Comment by sujeilyfonseca** [comment]
I asked @naveenkaratekid to verify this problem in Eclipse and the Java Lagom project has the same problem there:

<img width="1252" alt="Screen Shot 2019-08-20 at 11 53 00 AM" src="https://user-images.githubusercontent.com/49531960/63363620-f1e33280-c341-11e9-9ff9-a6222a37e47c.png">

**Comment by tetchel** [comment]
should be fixed in latest drivers; give the eclipse build an hour or so to be uploaded.

**Comment by sujeilyfonseca** [comment]
I tested this problem in VS Code and Eclipse with latest Codewind images, and it doesn't happen anymore:

<img width="1326" alt="Screen Shot 2019-08-22 at 4 43 38 PM" src="https://user-images.githubusercontent.com/49531960/63604323-6cf25600-c599-11e9-8778-baea885fd052.png">

<img width="698" alt="Screen Shot 2019-08-22 at 5 26 02 PM" src="https://user-images.githubusercontent.com/49531960/63604335-71b70a00-c599-11e9-9719-4e97477a17da.png">
