### ISSUE TITLE
Clarify Codewind test coverage status

### ISSUE THREAD

**Issue by rwalle61** [eclipse/codewind#2283]
for https://github.com/eclipse/codewind/issues/2291

We have several repos with different levels of testing. Some tests run during PR builds, others don't. We have different levels of test coverage.

Let's clarify where we all are, so that we know how we could improve it iteratively.

Could each repo answer these questions? (Link issues if needed)
- **team/repository** e.g. Portal
- **what is the current coverage of tests in total?** e.g. 60%. (If unknown, give an honest estimate and say it's an estimate).
- **what is the current coverage of tests running on PR builds?** 40%
- **what gaps in testing are most important to you?** We would like to test our code on Remote
- **what are the largest obstacles to increasing coverage of tests in total?** Features are prioritized at the expense of tests
- **what are the largest obstacles to increasing coverage of tests on PR builds?** Integration tests fail intermittently in PR builds
- **additional comments?** 

Questionnaire (copy and paste)
```
- **team/repository** 
- **what is the current coverage of tests in total?** 
- **what is the current coverage of tests running on PR builds?** 
- **what gaps in testing are most important to you?** 
- **what are the largest obstacles to increasing coverage of tests in total?** 
- **what are the largest obstacles to increasing coverage of tests on PR builds?** 
- **additional comments?**
```

/kind Test
@maysunfaisal

**Comment by rwalle61** [comment]
- [ ] **team** Portal
- [ ] **what is the current coverage of tests in total?** 67%
- [ ] **what is the current coverage of tests running on PR builds?** 67%
- [ ] **what gaps in testing are most important to you?** Unit testing our Loadrunner and Filewatcher logic. Fuller integration tests, e.g. involving built projects, different project types. Tests on Remote
- [ ] **what are the largest obstacles to increasing coverage of tests in total?** We are prioritising tests that behave consistently in PR builds (see below). Also, some tests (e.g. integration tests) take a long time to complete, so would make PR builds annoyingly slow
- [ ] **what are the largest obstacles to increasing coverage of tests on PR builds?** Loadrunner tests and fuller integration tests use asynchronous logic that can behave differently between test runs, leading to intermittent failures on PR builds
- [ ] **additional comments?** If we have tests not run in PR builds, we could run them nightly so they are still run without holding up PRs unecessarily

**Comment by jcockbain** [comment]
- [ ] **repo** cwctl

- [ ] **What is the current coverage of tests in total?** 31.5%

- [ ] **what is the current coverage of tests running on PR builds?** 22.7%

- [ ] **what gaps in testing are most important to you?** 
Facilitating unit tests across the codebase. Structuring the code to allow injections of any dependancy, as has been added for the Docker client.

The Remote package has the least coverage at the moment (~5%). As the package with the most functions this brings down our overall coverage significantly. However, as I understand it this will be deprecated by the operator code. We should make sure this has significant coverage when it goes in, if we want coverage to improve. 

- [ ] **what are the largest obstacles to increasing coverage of tests in total?** 
Parts of the code are written in a way that means adding thorough tests requires a considerable refactor.

- [ ] **what are the largest obstacles to increasing coverage of tests on PR builds?**
The challenges of running PFE inside of a Jenkins environment. If running this isn't feasible we should look at a clear divide between PFE-dependant unit tests and unit ones.

Currently, as is seen in the coverage stats, we have a number of tests that are skipped in Jenkins. Alongside PFE reliance, these are due to dependencies in the connections and authentication logic.

**Comment by rwalle61** [comment]
Hi guys, would you mind filling this out for your repositories by the end of the week please? Some of you have already done so on Box but please do so again here (I would copy your replies across in comments, but then you wouldn't be able to edit them). Thanks

Let's get a status on all these repos https://projects.eclipse.org/projects/ecd.codewind/developer. Then we can prioritise which ones to improve.

/assign @jopit 
/area intellij-ide
- [ ] https://github.com/eclipse/codewind-intellij

/assign @tetchel
/area vscode-ide
- [ ] https://github.com/eclipse/codewind-vscode

/assign @eharris369 
/area eclipse-ide
- [ ] https://github.com/eclipse/codewind-eclipse

/assign @jgwest 
/area iterative-dev
- [ ] https://github.com/eclipse/codewind-filewatchers

/assign @johnmcollier
- [ ] https://github.com/eclipse/codewind-che-plugin

/assign @micgibso 
/area docs
- [ ] https://github.com/eclipse/codewind-docs

I can't assign @jagraj so someone let him know please
- [ ] SVT

Maysun / Turbine
- [ ] https://github.com/eclipse/codewind (Turbine)

Me / Portal:
/area portal
- [x] https://github.com/eclipse/codewind (Portal)
- [x] https://github.com/eclipse/codewind-installer
- [ ] https://github.com/eclipse/codewind-java-profiler
- [ ] https://github.com/eclipse/codewind-node-profiler

/assign @jingfuwang 
- [ ] https://github.com/eclipse/codewind-odo-extension

/assign @makandre 
/area appsody
- [ ] https://github.com/eclipse/codewind-appsody-extension

/assign @keithchong 
/area openapi
- [ ] https://github.com/eclipse/codewind-openapi-vscode
- [ ] https://github.com/eclipse/codewind-openapi-eclipse

**Comment by jgwest** [comment]
**Repo**: 

[Go and Node Filewatchers](https://github.com/eclipse/codewind-filewatchers)
[Java Filewatchers](https://github.com/eclipse/codewind-eclipse)

**What is the current coverage of tests in total?** 

65% Java Filewatcher (others filewatchers should be similar if not higher, but have not measured) 

**What is the current coverage of tests running on PR builds?** 

65% Java Filewatcher (others filewatchers should be similar if not higher, but have not measured) 

**What gaps in testing are most important to you?** 

No obvious gaps.

**What are the largest obstacles to increasing coverage of tests in total?** 

No obstacles.

**What are the largest obstacles to increasing coverage of tests on PR builds?**

None.

**Comment by micgibso** [comment]
**Team/repository** 
Docs - main repo: https://github.com/eclipse/codewind-docs

**What is the current coverage of tests in total?** 
N/A

**What is the current coverage of tests running on PR builds?** 
N/A

**What gaps in testing are most important to you?** 
Manually testing the docs against the product.

**What are the largest obstacles to increasing coverage of tests in total?** 
Would be good to have an automated broken link check report.

**What are the largest obstacles to increasing coverage of tests on PR builds?** 
No obstacles.

**Additional comments?**
None.

**Comment by eharris369** [comment]
**Team/repository** 
Eclipse IDE - main repo: https://github.com/eclipse/codewind-eclipse

**What is the current coverage of tests in total?** 
20% for JUnit tests, probably a lot more if include the SWTBot tests written by SVT

**What is the current coverage of tests running on PR builds?** 
0%

**What gaps in testing are most important to you?** 
Some of these may already be covered by the SWTBot tests written by SVT
- Remote
- Install, uninstall, start, stop of Codewind
- Template management
- Registry management
- Application overview page
- Metrics and perfomance dashboards including inject metrics
- Container shell action
- Add existing project

**What are the largest obstacles to increasing coverage of tests in total?** 
Time

**What are the largest obstacles to increasing coverage of tests on PR builds?** 
Cannot yet run the build as a non-root user

**Additional comments?**
None.

**Comment by makandre** [comment]
WIP

**Team/repository**
appsody - https://github.com/eclipse/codewind-appsody-extension

**What is the current coverage of tests in total?**

**What is the current coverage of tests running on PR builds?**
0%

**What gaps in testing are most important to you?**

**What are the largest obstacles to increasing coverage of tests in total?**

**What are the largest obstacles to increasing coverage of tests on PR builds?**

**Additional comments?**

**Comment by tetchel** [comment]
### team/repository 
CW for VS Code https://github.com/eclipse/codewind-vscode

### what is the current coverage of tests in total? e.g. 60%. (If unknown, give an honest estimate and say it's an estimate).
No idea, but it's low. Much higher if you include SVT's UI tests.

### what is the current coverage of tests running on PR builds?
0

### what gaps in testing are most important to you? 
detecting cwctl/API response regressions / missing fields in output/responses
Everything remote, registry secrets

### what are the largest obstacles to increasing coverage of tests in total?
Writing reliable tests is time-consuming for a one-person team
Need a test remote CW instance for remote testing and maybe a test dockerhub account
Need a way to verify at runtime that cwctl output/pfe response matches expected type

### what are the largest obstacles to increasing coverage of tests on PR builds?
Run build as non root user https://bugs.eclipse.org/bugs/show_bug.cgi?id=559302
have followed up with an email asking for further instructions but no response (yet), not sure what to do next

### additional comments?
please help :)

**Comment by maysunfaisal** [comment]
- **team/repository**  
Turbine

- **what is the current coverage of tests in total?** 
Unit tests: 40%
Functional tests local: 60%
Functional tests kube: 64%

- **what is the current coverage of tests running on PR builds?** 
Unit tests: 40%
Functional tests local: None
Functional tests kube: None

- **what gaps in testing are most important to you?** 
From Turbine's perspective, we would absolutely like to have the functional test suite running on the PR build for Codewind repo

- **what are the largest obstacles to increasing coverage of tests in total?** 
-- Flake tests
-- Identifying which project type to run (cannot expect to run the all the project types in a PR build)
-- Figuring out how to get kube tests running in PR builds ie the kube env

- **what are the largest obstacles to increasing coverage of tests on PR builds?** 
None, from Turbine's perspective I think we have done a decent job of trying to unit test all functions possible and get functional tests for all the pieces

- **additional comments?**
We shall take a look soon how to get functional suite in the PR

**Comment by maysunfaisal** [comment]
#### **team/repository**  
[codewind-che-plugin](https://github.com/eclipse/codewind-che-plugin)

#### **what is the current coverage of tests in total?** 
- Hard to estimate percentage, tests are in bash but it covers all the major steps in bringing up Codewind workspace on Che
- 

#### **what is the current coverage of tests running on PR builds?** 
None

####  **what gaps in testing are most important to you?** 
- To get the sidecar tests running in the PR 
- To automate the Go deployment code

####  **what are the largest obstacles to increasing coverage of tests in total?** 
None atm

####  **what are the largest obstacles to increasing coverage of tests on PR builds?** 
- Need to integrate the Go tests in PR build
- Figuring out how to get kube tests running in PR builds ie the kube env

####  **additional comments?**
Once we figure out how to run PR tests for kube env, this shall be covered as well

**Comment by keithchong** [comment]
- **team/repository** 
https://github.com/eclipse/codewind-openapi-vscode
https://github.com/eclipse/codewind-openapi-eclipse
- **what is the current coverage of tests in total?** 
**VSCode**: 
   Mocha Automated Tests.  10%
   UI Tests. 0%
**Eclipse**: 
   JUnit Automated Tests: 80%
   SWTBot Automated Tests: 70%
- **what is the current coverage of tests running on PR builds?** 
**VSCode**: 
   Mocha Automated Tests.  0%
   UI Tests. 0%
**Eclipse**: 
   JUnit Automated Tests: Of the automated, 100% are running on PR builds
   SWTBot Automated Tests: 0% - will not be run in PR builds

- **what gaps in testing are most important to you?** 
**VSCode**: 
   UI Test coverage is at 0%
**Eclipse**: 
   Add more wizard tests
   Run UI tests on other platforms
- **what are the largest obstacles to increasing coverage of tests in total?** 
  Resource - I'm working on IntelliJ and will not be spending time on these two repositories in the short term.
- **what are the largest obstacles to increasing coverage of tests on PR builds?** 
  None
- **additional comments?**
  None

**Comment by jagraj** [comment]
- **team/repository** 
SVT - UI Automation and Manual integration tests.

Eclipse Che, VSCode - UI automation. 
https://github.ibm.com/dev-ex/codewind-svt/blob/master/README.md

Eclipse plugin
SWTBot - UI automation
https://github.ibm.com/dev-ex/automation-codewind-svt

Here is our Automation matrix progress captured in this box note.
https://ibm.box.com/s/u2qrknn9dl6eylycs7140wspl3f8jy67

- **what is the current coverage of tests in total?** 
VS Code Plugin - 72.22%
Eclipse Che -  84.82%
Eclipse plugin - 73.15%

- **what is the current coverage of tests running on PR builds?** 
Our UI automation tests are not part of PR build process. Our plan is to schedule these tests twice a day and open issues for the failures. Our tests are running in Travis CI and the goal is to open source these integration tests once we have clean path automation completed for all the plugins.

- **what gaps in testing are most important to you?**
OpenAPI
 
- **what are the largest obstacles to increasing coverage of tests in total?** 
No Obstacles, More tests to be planned in future releases and we are running them with manual tests as part of SVT test cycles for every release.

- **what are the largest obstacles to increasing coverage of tests on PR builds?** 
No Obstacles. 

- **additional comments?**

We are currently working on Hybrid/Remote automation tests for both VSCode and Eclipse. Our plan is to complete this UI automation as part of Codewind 0.10 release.

**Comment by GeekArthur** [comment]
**Team/repository**

OpenShift DO (odo) - https://github.com/eclipse/codewind-odo-extension

**What is the current coverage of tests in total?**

Functional tests kube: 64%

**What is the current coverage of tests running on PR builds?**

0% 😭 

**What gaps in testing are most important to you?**

- Increase the testing coverage of odo functional tests
- Enable odo functional tests on PR builds
   Note: Since odo functional tests are part of Turbine functional tests, so odo functional tests should be automatically enabled on PR builds once Turbine functional tests are enabled on PR builds

**What are the largest obstacles to increasing coverage of tests in total?**

Although the testing coverage is not 100% (we didn't test minor functions directly), I think there are no big problems since we already tested the major features that should cover most of the minor functions

**What are the largest obstacles to increasing coverage of tests on PR builds?**

Same as above

**Additional comments?**
None

**Comment by jopit** [comment]
- **team/repository** 
IntelliJ IDE - https://github.com/eclipse/codewind-intellij

- **what is the current coverage of tests in total?** 
0

- **what is the current coverage of tests running on PR builds?** 
0

- **what gaps in testing are most important to you?** 
Initially to get some minimal automated testing.

- **what are the largest obstacles to increasing coverage of tests in total?** 
Lack of automated framework for UI testing
Lack of time, pressure to deliver function

- **what are the largest obstacles to increasing coverage of tests on PR builds?** 
Lack of any automated testing
Cannot yet run the build as a non-root user
