### ISSUE TITLE
SVT [VS Code]: Debugging feature does not work with Spring and MicroProfile projects

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#229]
**Codewind version:** 0.3
**OS:** Windows 10 and MacOS Mojave (10.14.5)

**IDE:** VS Code 
**IDE extension version:** latest
**IDE version:** 1.37.1

**Description:** Debugging feature does not work in VS Code with Spring and MicroProfile projects.

![Screen Shot 2019-08-20 at 11 19 05 AM](https://user-images.githubusercontent.com/49531960/63361458-2c4ad080-c33e-11e9-9cad-66048a9e38c5.png)

![Screen Shot 2019-08-20 at 11 02 04 AM](https://user-images.githubusercontent.com/49531960/63361650-7f248800-c33e-11e9-9c60-63ded497c7de.png)

![Screen Shot 2019-08-20 at 10 59 32 AM](https://user-images.githubusercontent.com/49531960/63361619-75028980-c33e-11e9-9ef9-d1c25e319df2.png)

![Screen Shot 2019-08-20 at 10 59 47 AM](https://user-images.githubusercontent.com/49531960/63361631-78961080-c33e-11e9-8c31-96f9c462ee05.png)

<img width="1500" alt="Screen Shot 2019-08-20 at 11 24 22 AM" src="https://user-images.githubusercontent.com/49531960/63361658-821f7880-c33e-11e9-9246-e3a2689d3fed.png">

<img width="1497" alt="Screen Shot 2019-08-20 at 11 26 45 AM" src="https://user-images.githubusercontent.com/49531960/63361657-821f7880-c33e-11e9-8da6-45e1bcc19c8c.png">

**Steps to reproduce:**
1. Install Codewind
2. Open the Codewind workspace
3. Create a Java Spring or Java MicroProfile project
4. Right click on the created project
5. Click on "Restart in Debug Mode"

**Logs:**
[codewind.log](https://github.com/eclipse/codewind/files/3521413/codewind.log)

@jagraj

**Comment by tetchel** [comment]
It looks like you don't have the `Java Extension Pack` installed. Can you try that?

**Comment by sujeilyfonseca** [comment]
Hi Tim, you were right. I did not have the Java Extension Pack enabled. After installing and enabling it, I was able to debug Java Spring and Java MicroProfile projects. Thanks!
