### ISSUE TITLE
[Che] Codewind ingresses are intermittently going away

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#2292]
**Codewind version:** latest and 0.8.0
**OS:**

**Che version:** CRW 2.0
**IDE extension version:** latest and 0.8.0
**IDE version:** 
**Kubernetes cluster:**

**Description:**
It seems that intermittently, the replicasets belonging to a project may get scaled down and recreated by Kubernetes. This on its own is fine, but since we're tying the Codewind ingress to the replicaset, this means the ingress goes away too and does not get recreated. To fix this, we should be tying the project's ingress to the proejct's deployment, rather than the replicaset. 

**Steps to reproduce:**
1) Deploy Codewind on Che or CRW
2) Create a couple projects and wait
3) Eventually the ingresses for the projects will go away. The projects will remain up though.

To fix this we need to do the following:
1) Update Codewind's ingress creation code to tie the project's ingress to the project's deployment.
2) Update the Codewind cluster roles to add the `finalizer` role to deployment

**Comment by malincoln** [comment]
@johnmcollier pls verify and close.  Do we also need SVT to verify?

**Comment by johnmcollier** [comment]
I verified on my end earlier
