### ISSUE TITLE
SVT: [Che][VS Code] Command Palette option for "Template Source Manager" doesn't match other labels used to refer to the same view

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#2297]
**Codewind version:** Latest
**OS:** Red Hat Enterprise Linux 7 (64 bit)

**Che version:** 7.5.1
**Kubernetes cluster:** OKD/Openshift

**Description:** Command Palette option for "Template Source Manager" doesn't match other labels used to refer to the same view

<img width="634" alt="Screen Shot 2020-02-24 at 9 42 44 AM" src="https://user-images.githubusercontent.com/49531960/75161729-4816a100-56ea-11ea-8b2a-7b56d8e132ee.png">

<img width="343" alt="Screen Shot 2020-02-24 at 9 43 28 AM" src="https://user-images.githubusercontent.com/49531960/75161725-477e0a80-56ea-11ea-8440-000d7cf0cc5b.png">

<img width="1059" alt="Screen Shot 2020-02-24 at 9 43 40 AM" src="https://user-images.githubusercontent.com/49531960/75161719-464cdd80-56ea-11ea-89d0-d0317c26f95f.png">

@jagraj

**Comment by tetchel** [comment]
good catch! this was renamed but I missed that instance.
