### ISSUE TITLE
(metrics) Always enable the performance dashboard action even if the project doesn't have metrics

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#2299]
If `perfDashboardPath` is set on the project, that is all we need to open the performance dashboard. 

This means we can skip the ping test for appsody projects. The perf dashboard will no longer fall over if the project doesn't have metrics.

**Comment by eharris369** [comment]
Eclipse IDE PR: https://github.com/eclipse/codewind-eclipse/pull/596

**Comment by tetchel** [comment]
@jopit does intellij need this change?

**Comment by jopit** [comment]
Yes it does (@cccanderson)

**Comment by tobespc** [comment]
will modify pfe to always return this value

**Comment by malincoln** [comment]
Did part of this ship in 0.10.0 and the remainder will ship in a later release?
