### ISSUE TITLE
Application monitor, lines on graph/key do not match

### ISSUE THREAD

**Issue by stalleyj** [eclipse/codewind#2302]
**Description:**
The graph displaying heap information on the Application Monitor page has lines that do not match the legend. 
![Screenshot 2020-02-25 at 09 22 08](https://user-images.githubusercontent.com/13417476/75233301-8e363800-57b0-11ea-9b95-898d9f8d5731.png)

This problem has been fixed in graphmetrics so we need to update the version in Javametrics, Appmetrics.
**Steps to reproduce:**
Run load against a java microservice and then open the Application Monitor page.

**Workaround:**

**Comment by tobespc** [comment]
believe this is now fixed, will test

**Comment by malincoln** [comment]
@tobespc @stalleyj has this been verified?  If so, pls close.  Thanks

**Comment by malincoln** [comment]
@tobespc I see this was reopened.  Who needs to verify?
