### ISSUE TITLE
Topics called from VS Code but not in TOC

### ISSUE THREAD

**Issue by micgibso** [eclipse/codewind#2303]
**Codewind version:** 0.9.0
**OS:** Windows

**Description:**
The following topics are called from VS Code https://github.com/eclipse/codewind-vscode/blob/master/dev/src/constants/CWDocs.ts but following the rework of the TOC are no longer in it.
mdt-vsc-installinfo.md
mdt-vsc-commands-project.md (link is "mdt-vsc-commands-project.html#configuring-project-settings")
remoteconnectionui.md
mdt-vsc-commands-overview.md

**Workaround:** 
Have left these topics in our source whilst working https://github.com/eclipse/codewind/issues/2163, but the content needs to be considered for the TOC, or worked in, and the links in the code changed to topics that do exist in the TOC. 

@MelHopper fyi

**Comment by sishida** [comment]
Ideas for updated topics:
- Remove `mdt-vsc-installinfo.md`, add `mdt-vsc-getting-started.md`
- Remove `mdt-vsc-commands-project.md` (link is 1mdt-vsc-commands-project.html#configuring-project-settings`), add `project-settings.md`
- Remove `remoteconnectionui.md`, add `remotedeploy-vscode.md`
- Remove `mdt-vsc-commands-overview.md`, add `project-settings.md`? I don't think we currently have a commands overview page to replace the one we removed.

**Comment by sishida** [comment]
Ideas for updated topics:
- Remove `mdt-vsc-installinfo.md`, add `mdt-vsc-getting-started.md`
- Remove `mdt-vsc-commands-project.md` (link is 1mdt-vsc-commands-project.html#configuring-project-settings`), add `project-settings.md`
- Remove `remoteconnectionui.md`, add `remotedeploy-vscode.md`
- Remove `mdt-vsc-commands-overview.md`, add `project-settings.md`? I don't think we currently have a commands overview page to replace the one we removed.

**Comment by tetchel** [comment]
reminder --> https://github.com/eclipse/codewind-vscode/blob/master/dev/src/constants/CWDocs.ts#L25

**Comment by micgibso** [comment]
Also consider `project-actions.md` currently being restored on PR https://github.com/eclipse/codewind-docs/pull/389/files.

**Comment by sishida** [comment]
Link to PR: https://github.com/eclipse/codewind-vscode/pull/478

@tetchel Could you please review when you have a moment? Thank you!

**Comment by sishida** [comment]
Because we have updated the file names in VS Code and deleted the extraneous files, I am closing this issue. :)

**Comment by micgibso** [comment]
Issue appearing in list of Open issues despite being closed. Reopening & closing to see if that fixes it.

**Comment by micgibso** [comment]
Success, issue no longer appears in list of Open issues despite being closed.
