### ISSUE TITLE
[Docs] rename Codewind html files by dropping 'mdt' from the file name

### ISSUE THREAD

**Issue by josephca** [eclipse/codewind#2307]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description of the enhancement:**
There are a number of 'mdt*.html' and better to be renamed by dropping 'mdt' or replaced by 'codewind'

./docs/_site/mdteclipseuninstall.html
./docs/_site/mdt-che-managingprojects.html
./docs/_site/mdt-che-installinfo.html
./docs/_site/mdt-vsc-commands-project.html
./docs/_site/mdt-eclipse-firstproject.html
./docs/_site/mdteclipsemanagingprojects.html
./docs/_site/mdt-vsc-installinfo.html
./docs/_site/mdt-che-debugproject.html
./docs/_site/mdt-vsc-commands-restart-and-debug.html
./docs/_site/mdt-eclipse-getting-started.html
./docs/_site/mdt-che-odo-support.html
./docs/_site/mdt-che-buildproject.html
./docs/_site/mdt-eclipse-codechange.html
./docs/_site/mdteclipsedebugproject.html
./docs/_site/mdt-vsc-firstproject.html
./docs/_site/mdt-che-codechange.html
./docs/_site/mdt-che-setupregistries.html
./docs/_site/mdt-vsc-getting-started.html
./docs/_site/mdt-che-uninstall.html
./docs/_site/mdt-vsc-tutorial.html
./docs/_site/mdt-vsc-troubleshooting.html
./docs/_site/mdt-che-usingtheia.html
./docs/_site/mdt-che-tektonpipelines.html
./docs/_site/mdt-che-troubleshooting.html
./docs/_site/mdt-vsc-uninstall.html
./docs/_site/mdt-vsc-commands-overview.html
./docs/_site/mdt-eclipse-installinfo.html
./docs/_site/mdteclipsetroubleshooting.html
./docs/_site/mdt-vsc-nodejsprofiling.html
./docs/_site/mdt-che-createcodewindworkspace.html
./docs/_site/mdt-intellij-getting-started.html

**Proposed solution:**

**Comment by keithchong** [comment]
@sishida , add ./docs/_site/mdt-intellij-getting-started.html to the list of doc file links that are referenced directly by code.

**Comment by sishida** [comment]
@micgibso Please remember to update the https://github.com/eclipse/codewind-vscode/blob/master/dev/src/constants/CWDocs.ts file for VS Code when you change the names of the codewind-docs files. Thank you!

**Comment by micgibso** [comment]
@sishida And let's not forget the Eclipse variant of the same, see https://github.com/eclipse/codewind-eclipse/pull/570/files, this line:
`CWSETTINGS_INFO_URL = DOC_BASE_URL + "/mdteclipsemanagingprojects.html",`

**Comment by micgibso** [comment]
For VS Code, see PR https://github.com/eclipse/codewind-vscode/pull/481

**Comment by micgibso** [comment]
For Eclipse, no changes necessary, see https://github.com/eclipse/codewind-eclipse/blob/master/dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/UIConstants.java#L20

**Comment by sishida** [comment]
Ran broken link checker. This was the only broken link to fix:
```
URL        `remotedeloy-existingkeycloak'
Name       `Deploying Codewind with an existing keycloak'
Parent URL http://localhost:8765/codewind/remotedeploy-single.html, line 897, col 167
Base       http://localhost:8765/codewind/
Real URL   http://localhost:8765/codewind/remotedeloy-existingkeycloak
Check time 4.385 seconds
Size       196B
Result     Error: 404 Not Found
 2 threads active,     0 links queued,  292 links in 294 URLs checked, runtime 51 seconds
```

**Comment by sishida** [comment]
PR for fixing broken link: https://github.com/eclipse/codewind-docs/pull/422

**Comment by micgibso** [comment]
Rename complete, closing.
