### ISSUE TITLE
Unable to open container shell in Eclipse ide

### ISSUE THREAD

**Issue by stalleyj** [eclipse/codewind#2309]
**Codewind version:**
0.9.0
**OS:**
Mac

**IDE extension version:** 0.9.0
**IDE version:** 2019-09

**Description:**
If I right click on a project to open a container shell, nothing happens. I did not get shown an error but have found one in the log -
!ENTRY org.eclipse.codewind.core 4 0 2020-02-26 10:57:46.690
!MESSAGE [ERROR ContainerShellAction.run:83] ContainerShellAction ran but the terminal service is null

**Steps to reproduce:**
Use Codewind to create a project, once running, use the context menu to "Open Container Shell"

**Workaround:**

**Comment by eharris369** [comment]
I could not reproduce this. Are you sure you are using the right Eclipse package? It needs to be the Eclipse IDE for Enterprise Java Developers. You can check by expanding the Eclipse menu and selecting About Eclipse:

![image](https://user-images.githubusercontent.com/9484320/75461373-b52b7000-5950-11ea-8bf6-92b886153c43.png)

**Comment by stalleyj** [comment]
So I wasn't using the right Eclipse package, guess I just started using the Eclipse that I already had on my machine. To improve the user experience (for other stupid users like me), it would be great if we catch the error and inform the user that they may not be using the correct Eclipse package rather than the menu option doing nothing.

**Comment by eharris369** [comment]
@josephca Do you know if there is some way of failing with a nice message if users try to install Codewind on the wrong Eclipse package?

**Comment by jgwest** [comment]
I presume it's the Eclipse TCF/TM/RSE plugins that are used for this view?
 
#### Some Options:
1) Add dependency on those plugins to our product update site; if they aren't present, they will either be downloaded from eclipse.org, OR the install will fail (with a not nice message). In either case, at least our product will only be used with the plugins installed.
2) If you click the **Open Container Shell** menu item, and the user DOESN'T have those plugins install, we can pop up a warning message for the user indicating that they are required for this view (and how to install them,)

**Comment by eharris369** [comment]
There could be other things that don't work as well so it would be better to add a dependency on the Eclipse JEE package feature (org.eclipse.epp.package.jee.feature). I am testing this out now. Also this is what we test on so we should require it.

**Comment by eharris369** [comment]
It turns out that to depend on a particular feature is not that simple and requires listing all of the required plugins with their versions in a separate feature for each version of Eclipse that is supported. So have just added code to check for the bundles required for the container shell and show a dialog if they are not installed. The message asks the user to check that they are using the Eclipse IDE for Enterprise Java Developers.
See: https://github.com/eclipse/codewind-eclipse/pull/623

**Comment by malincoln** [comment]
@stalleyj pls verify and close. Thanks

**Comment by stalleyj** [comment]
Verified that I can a nice helpful message now when I try to Open a container shell, thanks.
