### ISSUE TITLE
Panic thrown when attempting to move project in vscode

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#2319]
**Codewind version:** latest
**OS:**

![Screenshot 2020-02-26 at 16 27 04](https://user-images.githubusercontent.com/13151286/75365368-0554f480-58b5-11ea-859d-fa7289cd242d.png)

**Comment by hhellyer** [comment]
Looks like the panic is caused by parsing bad JSON. (Obviously there was another problem that caused us to be sent invalid JSON, it's hard to tell what that was.)
This is probably a case the standard API tests should check.

**Comment by hhellyer** [comment]
@tobespc - There are a lot of places that have this bug, I've fixed the one you were seeing. Do you want to address the others under this issue or shall I raise one specifically to clean up our error checking when we unmarshall JSON in cwctl?

**Comment by hhellyer** [comment]
I've added https://github.com/eclipse/codewind/issues/2364 to deal with other occurrences. This issue can now be closed.
