### ISSUE TITLE
Remote install instructions need to include instructions to enable privileged containers

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#2320]
The steps in https://www.eclipse.org/codewind/mdt-che-installinfo.html#enabling-privileged-and-root-containers-to-run

apply to all Codewind-on-OpenShift (NOT all IBM Public Cloud, see John's comment below) installations, not just Che.

So these steps should be in the Prereqs section
https://www.eclipse.org/codewind/remote-overview.html
and also in the all-in-one steps.
https://www.eclipse.org/codewind/remotedeploy-combo.html

They are already included in the 'individual components' page, for some reason.
https://www.eclipse.org/codewind/remotedeploy-single.html

**Comment by tetchel** [comment]
also, from `remotedeploy-single`:

> For Codewind on OpenShift, you must create the namespace first. To do this, enter: oc create namespace <Codewind-namespace>.

This isn't accurate anymore, cwctl will create the namespace if it doesn't exist.

**Comment by johnmcollier** [comment]
Slight nitpick:
```
For both IBM Public Cloud and OpenShift, run the following commands on only the Codewind namespace:
```

To avoid confusion it should only be OpenShift (which includes OpenShift on IBM Cloud). Those commands aren't needed on IKS (and won't work)

**Comment by sishida** [comment]
There has been some reorganization of the files involved in this issue. However, I think I addressed the concerns in this PR: https://github.com/eclipse/codewind-docs/pull/419

The first commit should cover the points in this issue; the second commit is more style and grammar edits.
