### ISSUE TITLE
(metrics) SVT: Users now receive a warning message in the Performance Dashboard, if they are using an old version of AppMetrics

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#2324]
**Codewind version:** Latest
**OS:** MacOS Mojave 10.14.6, Red Hat Enterprise Linux 7 (64 bit)

**Che version:** 7.5.1 
**IDE extension version:** 0.10.0 
**IDE version:** Code 1.42.0
**Kubernetes cluster:** OKD/Openshift

**Description:** Users now receive a warning message in the Performance Dashboard, if they are using an old version of AppMetrics. However, this message is not user-friendly, as it doesn't provide useful information on how users can update their AppMetrics or how to proceed.

<img width="1475" alt="Screen Shot 2020-02-26 at 1 59 07 PM" src="https://user-images.githubusercontent.com/49531960/75377685-560e2280-58a0-11ea-9f1b-01549c8a47ce.png">

Regardless of the message, users can get the result of their load tests.

<img width="1650" alt="Screen Shot 2020-02-26 at 2 03 03 PM" src="https://user-images.githubusercontent.com/49531960/75377925-c1f08b00-58a0-11ea-867c-d31150a2a947.png">

@jagraj

**Comment by tobespc** [comment]
tagging in design for input on a better message

**Comment by tobespc** [comment]
this has been fixed as part of https://github.com/eclipse/codewind/pull/2732
