### ISSUE TITLE
IntelliJ:SVT:Not able to see list of existing projects in specific directory

### ISSUE THREAD

**Issue by naveenkaratekid** [eclipse/codewind#2326]
**Codewind version: master latest**
**OS:Windows**

***IDE***: IntelliJ IDEA
**IDE extension version: latest**
**IDE version: 2019.3.3 Community Edition**

**Description:**
When I try to import an existing project in IntelliJ that isn't under the Codewind explorer, I cannot see a list of projects given a specific directory, but I can see those projects in the Windows Explorer.

**Steps to reproduce:**
1. Under Codewind Explorer, right-click and select ```Add Existing Project```
2. Click ```Browse```
3. Once the popup in windows comes, there is no list of projects for the specified directory

I clicked the Refresh button in that popup and no projects showed up.

![image](https://user-images.githubusercontent.com/19738071/75381137-3974e900-58a6-11ea-9cc4-61fc1375913a.png)

@jagraj

**Comment by sujeilyfonseca** [comment]
**Codewind version:** Latest
**OS:** VM with Windows 10

**IDE extension version:** 
<img width="532" alt="Screen Shot 2020-02-26 at 3 23 01 PM" src="https://user-images.githubusercontent.com/49531960/75385174-48ab6500-58ad-11ea-9a83-ceb61835fc74.png">

**IDE version:**
<img width="319" alt="Screen Shot 2020-02-13 at 12 45 49 PM" src="https://user-images.githubusercontent.com/49531960/74462840-decb9e00-4e5e-11ea-94e6-d09bc4f0d973.png">

I see the same behavior in Codewind for IntelliJ. I was unable to import an existing project using the "Add Existing Project..." feature:

<img width="1629" alt="Screen Shot 2020-02-26 at 3 18 15 PM" src="https://user-images.githubusercontent.com/49531960/75385219-595bdb00-58ad-11ea-9904-1d434741ccb7.png">

**Comment by keithchong** [comment]
This looks like Windows only.  On Mac it is fine. The fix for this is to set, `setShowFileSystemRoots(true)` instead of false.  This apparently has not impact on Mac but the folders will show fine on Windows.

**Comment by keithchong** [comment]
<img width="427" alt="Screen Shot 2020-02-28 at 1 06 00 PM" src="https://user-images.githubusercontent.com/7726022/75573856-b382aa80-5a2b-11ea-961f-748d62af9e4a.png">

**Comment by jopit** [comment]
Reopen so that SVT can verify the fix.

**Comment by malincoln** [comment]
@naveenkaratekid pls verify and close. Thanks

**Comment by naveenkaratekid** [comment]
I can see the list of folders in a directory when importing existing projects.

I was able to import an existing Lagom project into IntelliJ.

I will go ahead and close this issue now.

![image](https://user-images.githubusercontent.com/19738071/75991097-f0cfb800-5ec3-11ea-9ee1-afd49e800849.png)
