### ISSUE TITLE
Why call updateProjectStatus build failed twice?

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#2328]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Question synopsis:**

Came across this code which looked odd:

https://github.com/eclipse/codewind/blob/master/src/pfe/file-watcher/server/src/projects/projectUtil.ts#L479

```
if (result.exitCode == 1) {
    await projectStatusController.updateProjectStatus(STATE_TYPES.buildState, projectID, BuildState.failed, "buildscripts.buildFail");
}

projectInfo.error = errorMsg;
await projectStatusController.updateProjectStatus(STATE_TYPES.buildState, projectID, BuildState.failed, "buildscripts.buildFail");
```

The 2 calls to `updateProjectStatus` are identical, why?  Also if you look at the `if (process.env.IN_K8 === "true")` block above, there's only 1 `updateProjectStatus` there.

**Comment by jgwest** [comment]
The second block was added by https://github.com/eclipse/codewind/pull/199 so a question for @yangcao77

**Comment by yangcao77** [comment]
The second `updateProjectStatus` should be removed.  This will be fixed in https://github.com/eclipse/codewind/pull/2329

**Comment by malincoln** [comment]
@makandre pls verify and close. Thanks

**Comment by makandre** [comment]
Fix looks good.
