### ISSUE TITLE
Vscode loses focus on input box for registry namespace and project name

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#2330]
**Codewind version:** latest
**OS:** all
**IDE extension version:** master

**Description:**
When adding details for an image registry into vscode, focus is automatically given to the input box for the first 3 entries i.e.  docker.io, username, password

For the fourth entry of namespace, the focus gets lost and you have to click back on the box to add the data.  This doesn't happen when running in other editors (che for example)

**Comment by tetchel** [comment]
i've noticed this too, it's really annoying. Input boxes are supposed to take focus by default and there's no way to configure that. I'll see if there is any way I can hack a fix.
