### ISSUE TITLE
Docs: add Intellij section to getting started landing page

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#2332]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description of the enhancement:**

There's no Intellij on this page

![image](https://user-images.githubusercontent.com/17596240/75457789-e6a13d00-594a-11ea-8b1c-7722f2081510.png)

**Proposed solution:**

**Comment by MelHopper** [comment]
This issue has been fixed by reworking the gettingstarted.md file for 0.12.0.

In addition, the new content landing page will replace the Getting Started page.
