### ISSUE TITLE
Deploying Codewind overview, same content in Prerequisites and Planning sections

### ISSUE THREAD

**Issue by hhellyer** [eclipse/codewind#2334]
**Codewind version:**
master

**Description:**

This section of the docs:
http://codewind-docs.rtp.raleigh.ibm.com:4321/codewind/remote-overview.html#prerequisites
and this section:
http://codewind-docs.rtp.raleigh.ibm.com:4321/codewind/remote-overview.html#planning-your-remote-deployment---codewind-and-authentication-services
appear to have exactly the same content.

The next section has the same title as the one before:
http://codewind-docs.rtp.raleigh.ibm.com:4321/codewind/remote-overview.html#planning-your-remote-deployment---codewind-and-authentication-services-1
(but different content this time)

**Comment by micgibso** [comment]
@MelHopper Fyi
