### ISSUE TITLE
Problems in remote deployment docs

### ISSUE THREAD

**Issue by hhellyer** [eclipse/codewind#2337]
On the page http://codewind-docs.rtp.raleigh.ibm.com:4321/codewind/remotedeploy-combo.html

We probably don't want to hardcode 0.8.0 in these locations:
http://codewind-docs.rtp.raleigh.ibm.com:4321/codewind/remotedeploy-combo.html#prerequisites
http://codewind-docs.rtp.raleigh.ibm.com:4321/codewind/remotedeploy-single.html#pre-requisites
Should use <version> like here:
http://codewind-docs.rtp.raleigh.ibm.com:4321/codewind/remote-overview.html#planning-your-remote-deployment---codewind-and-authentication-services

( And here we use {version}:
http://codewind-docs.rtp.raleigh.ibm.com:4321/codewind/remotedeploy-
single.html#objectives )

`oc get namespaces`, `oc get routes -n default` and *any* oc command only works on OpenShift:
Also:
http://codewind-docs.rtp.raleigh.ibm.com:4321/codewind/remotedeploy-combo.html#determine-your-cloud-ingress-domain
and doesn't get an ingress, it gets a route (because OpenShift uses routes instead).
This means there's no instructions on finding the ingress on non-OpenShift environments.

Probably want to fix " AND AND ASSOCIATED KEYCLOAK?," here: 
http://codewind-docs.rtp.raleigh.ibm.com:4321/codewind/remotedeploy-combo.html#run-the-codewind-cli-command

**Comment by hhellyer** [comment]
Notes for: http://codewind-docs.rtp.raleigh.ibm.com:4321/codewind/remotedeploy-single.html

http://codewind-docs.rtp.raleigh.ibm.com:4321/codewind/remotedeploy-single.html#pre-requisites - checking you are logged into your cluster should probably come first.

All the commands use `oc` - that means they're OpenShift specific, we do say we support non-openshift kubernetes here: http://codewind-docs.rtp.raleigh.ibm.com:4321/codewind/remote-overview.html#planning-your-remote-deployment---codewind-and-authentication-services
and other docs do distinguish between OpenShift and plain Kubernetes.

Under:
http://codewind-docs.rtp.raleigh.ibm.com:4321/codewind/remotedeploy-single.html#3-deploy-additional-remote-codewind-services
point "2. Assigning users through role-based acccess control." - I'm not sure what this is, how to do it or whether it's possible. @markcor11 - Do you know what this is?

**Comment by hhellyer** [comment]
Notes for: http://codewind-docs.rtp.raleigh.ibm.com:4321/codewind/remotedeploy-existingkeycloak.html

Same comments as about:
http://codewind-docs.rtp.raleigh.ibm.com:4321/codewind/remotedeploy-single.html#3-deploy-additional-remote-codewind-services with the pre-reqs being in a strange order and only having instructions for `oc` not `kubectl`.


http://codewind-docs.rtp.raleigh.ibm.com:4321/codewind/remotedeploy-single.html#2-deploy-a-remote-codewind-service "LIKE WHAT? WHICH ONES ARE REQUIRED?" (I think the additional option might be --kurl as that specifies the keycloak url to use so it picks up an existing keycloak deployment.)

http://codewind-docs.rtp.raleigh.ibm.com:4321/codewind/remotedeploy-existingkeycloak.html#2-deploy-additional-remote-codewind-services - "WIP" and "SWAP THESE PARAGRAPHS AROUND?", also the same comment about point 2. as on the single deployment page.

**Comment by micgibso** [comment]
@hhellyer @markcor11 
Worked with Mark to complete the remaining sections of this issue in PR 2337 above.
