### ISSUE TITLE
Align Context Menus between IDEs

### ISSUE THREAD

**Issue by mattcolegate** [eclipse/codewind#2338]
**Codewind version:** latest 27/02/2020
**OS:** Windows 10

**Che version:** N/A
**IDE extension version:** latest Eclipse & VSCode plugins 27/02/2020
**IDE version:** VSCode and Eclipse
**Kubernetes cluster:** N/A

**Description of the enhancement:**

The context menus of projects (gained by right-clicking a project in the codewind view) differ in subtle but noticable ways - the grouping of options is different, some menu items are different (e.g. Application Monitor vs Metrics Dashboard) and some of the ordering of groups is different. I believe it would make it easier for end-users, as well as enhancing our continuity, to make naming conventions, ordering and grouping as identical as possible between the IDEs.

**Proposed solution:** 

Re-word, re-order and re-group context menu items to homogenize the experience.

![RClickEclipse](https://user-images.githubusercontent.com/15730986/75463436-bd4dd480-597d-11ea-91f3-eb1cb8cb98ba.JPG)
![RClickVS](https://user-images.githubusercontent.com/15730986/75463439-bde66b00-597d-11ea-92cc-8b8b91f34364.JPG)

**Comment by eharris369** [comment]
PR for Eclipse IDE: https://github.com/eclipse/codewind-eclipse/pull/622
