### ISSUE TITLE
Add link in eclipse-firstproject.md to managing templates documentation

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#2340]
In the eclipse-firstproject.md file it displays the project creation dialog where there is a long list of templates.  It would be nice to have a link to the documentation on managing templates here (workingwithtemplates.md).

**Comment by sishida** [comment]
@eharris369, I have added the link to "Working with templates" in this PR: https://github.com/eclipse/codewind-docs/pull/452. Could you please review/approve/merge if it looks good to go? Thank you!

**Comment by sishida** [comment]
PR merged, closing this issue.
