### ISSUE TITLE
Instructions and image don't match for Eclipse getting started page

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#2341]
In the eclipse-getting-started.md page it says `6. Once complete, you have a Codewind section in the IDE.` but the image shows it as still installing so it is not complete:

![image](https://user-images.githubusercontent.com/9484320/75470089-1d348300-595e-11ea-80fc-173f414ef554.png)

I think it would be better if the image matched the statement and showed Codewind as running:

![image](https://user-images.githubusercontent.com/9484320/75470258-65ec3c00-595e-11ea-9ffe-232c1c0441bb.png)

Also the text should be changed to something like:

Once complete you will have a running Local connection in the Codewind Explorer view.

**Comment by eharris369** [comment]
![image](https://user-images.githubusercontent.com/9484320/75699710-e5d81600-5c7e-11ea-9cd5-ef207c4ed80f.png)

**Comment by sishida** [comment]
The PR for the text and image update has been merged. Closing this issue.
