### ISSUE TITLE
VSCode specific content is under general heading in the docs

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#2342]
The remotedeploy-projects-vscode page is under the general `Connecting your IDE to remote Codewind` heading (see screen capture below). For Eclipse, all of this information is directly in the remotedeploy-eclipse page but for some reason for VSCode it is separated into 2 pages.

![image](https://user-images.githubusercontent.com/9484320/75478817-963ad700-596c-11ea-8e25-0b632c335799.png)

**Comment by eharris369** [comment]
Also the Next Steps link at the bottom of remotedeploy-eclipse takes the user to this VSCode page.

**Comment by j-c-berger** [comment]
@sishida, feel free to assign me, thanks!

**Comment by sishida** [comment]
Options for separating info:
1️⃣Have one page for each IDE (Eclipse and VS Code).
2️⃣Merge pages so we have one page for connecting and creating projects.

📓Also...creating projects should be the same (except for the registry step) in both local and remote. The documentation team needs to discuss how we want to proceed with the structure.

**Comment by micgibso** [comment]
Solution for this is in #2360 .
