### ISSUE TITLE
[Eclipse] [Appsody] Inconsistent content in Project Type Selection page of the Project Bind Wizard

### ISSUE THREAD

**Issue by keithchong** [eclipse/codewind#2344]
**Codewind version:** latest
**OS:** any

**IDE extension version:** latest
**IDE version:** Any supported Eclipse version

**Description:**
Compare the Project Type selection page when you try to bind a Codewind MicroProfile project versus an appsody project.  I'm expecting the list of subtypes for the Appsody project type to still be displayed regardless of the detected type.  This appears to be the current design, where the project language and an extension's (Appsody) subtype is treated the same.  This isn't intuitive and is confusing because I was expecting to be able to pick a specific appsody stack.

See screenshots

<img width="594" alt="Screen Shot 2020-02-27 at 12 54 39 PM" src="https://user-images.githubusercontent.com/7726022/75501871-33166800-599f-11ea-9c67-4ca7057ad4a4.png">

<img width="596" alt="Screen Shot 2020-02-27 at 12 54 15 PM" src="https://user-images.githubusercontent.com/7726022/75501857-2c87f080-599f-11ea-8e2f-cf424045bd2e.png">

**Comment by makandre** [comment]
When you say binding to an Appsody project, I assume you mean it's a project that's already an Appsody project, with a `.appsody-config.yaml` file.  That file already specifies what stack the project is based on, and so when you bind the project to Codewind, you are not supposed to be able to change the stack, hence the list of stack choices is not shown.

**Comment by keithchong** [comment]
Closing.
