### ISSUE TITLE
troubleshooting guide - Codewind-installer reference

### ISSUE THREAD

**Issue by AndyRWatson** [eclipse/codewind#2349]
**Codewind version:**. 0.9
**OS:**. ALL

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**

In out Troubleshooting page we make reference to a project creation error and that it may happen if you run "codewind-installer from the Terminal".  I am not sure running codewind-installer from a terminal was ever documented behaviour so something a user would even know how to do ?  

I think this may have now also been replaced by cwctl and also need to consider whether  this is still a valid troubleshooting issue based on current recommended usage ?

https://www.eclipse.org/codewind/troubleshooting.html#project-creation-on-macos-fails-and-codewind-reports-an-error

**Steps to reproduce:**

**Workaround:**

**Comment by sishida** [comment]
If this section https://www.eclipse.org/codewind/troubleshooting.html#project-creation-on-macos-fails-and-codewind-reports-an-error can be removed, ID will be glad to remove it. We will wait on confirmation from development. Thank you!

**Comment by jgwest** [comment]
@jgwest

**Comment by jgwest** [comment]
@AndyRWatson Liam needs to comment on the issue first before GitHub will let him be an assignee.

**Comment by liamchampton** [comment]
Will take a look at this

**Comment by liamchampton** [comment]
@sishida We don't currently support native use of cwctl (unless its for remote install). I don't think we need the sentence: "You might encounter the same issue if you run codewind-installer from the Terminal." as this could confuse people quite quickly.

**Comment by sishida** [comment]
@liamchampton Thank you for the info! I have opened the PR here to remove the sentence: https://github.com/eclipse/codewind-docs/pull/459

Please let me know if it's good to go and if we can close this issue. If we need changes or other updates for this issue, please let me know what else you'd like to change. Thanks!

**Comment by sishida** [comment]
PR merged, closing this issue. :)
