### ISSUE TITLE
troubleshooting - Update references of Theia to Che

### ISSUE THREAD

**Issue by AndyRWatson** [eclipse/codewind#2351]
**Codewind version:** 0.9
**OS:** All

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**

In the troubleshooting guides we should not make reference to Theia in our titles, but replace with Che as that is the editor we support/document.    I think its ok to reference that the issues is within theia as a dependancy of Che,  but we should referent the issue to our Che (andshortly CodeReadyWorkspace) support as the main editors. 

https://www.eclipse.org/codewind/troubleshooting.html#theia-editor-might-not-work-correctly-in-microsoft-edge

https://www.eclipse.org/codewind/troubleshooting.html#new-projects-sometimes-do-not-show-in-theia-hierarchy-view

https://www.eclipse.org/codewind/troubleshooting.html#context-root--application-endpoint-not-correct

**Steps to reproduce:**

**Workaround:** 

Suggested reword.

**Che** editor might not work correctly withinin Microsoft Edge

Theia, the open source code editor used by Che, currently has limited support for Microsoft Edge. The Theia team is aware of the issue and is working to fix it.

New projects sometimes do not show in **Che** hierarchy view

Sometimes when a new project is created, it doesn’t show up in the hierarchy view within Eclipse Che.

Context Root / Application Endpoint not correct

If you create or bind a project which has a context root set in .cw-settings, such as a project using the Lagom template, the context root is not picked up initially. This also happens after restarting Codewind.

Workaround For Eclipse. add the context root to the URL in your browser. For example, the browser might open with localhost:34567 instead of localhost:34567/mycontextroot so type mycontextroot. For VS Code and **Che**, edit and save the .cw-settings file, and the context root updates.

**Comment by sishida** [comment]
PR merged, closing this issue: https://github.com/eclipse/codewind-docs/pull/456
