### ISSUE TITLE
Nodejs project can't run offline when auto-build is enabled

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#2356]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**

Discovered as part of offline support investigation #2078

When offline and auto-build is enabled, Nodejs projects fail to run and following is in the app log:

```
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! network request to https://registry.npmjs.org/nodemon failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-28T18_59_15_284Z-debug.log
/scripts/noderun.sh: 82: /scripts/noderun.sh: nodemon: not found
```

**Steps to reproduce:**

1. You'll need to workaround #2354 first, otherwise the build fails if you're offline
2. Create a Nodejs project, it will fail to run 

**Workaround:** 

Disable project auto-build

**Comment by makandre** [comment]
When auto-build is on, running the app attempts to install `nodemon` but it will fail since we're offline

https://github.com/eclipse/codewind/blob/master/src/pfe/file-watcher/scripts/nodejsScripts/noderun.sh#L63

**Comment by makandre** [comment]
We could solve this problem by baking `nodemon` into the image at build-time rather than try to install it at run-time.  And we can (should) also control it via a `--build-arg` so `nodemon` is installed only when the project is built in Codewind.

I propose making a change to the template like so: https://github.com/makandre/nodeExpressTemplate/blob/nodemon/Dockerfile#L13

And then we can make a simple change in Turbine to pass in `--build-arg PROD_MODE=false` to build the image here:
https://github.com/eclipse/codewind/blob/master/src/pfe/file-watcher/scripts/nodejs-container.sh#L291

@elsony @rajivnathan what do you think of this idea?

**Comment by rajivnathan** [comment]
@makandre Wouldn't that only work for projects created via the nodejs template? What about existing projects imported by users that don't have that in their Dockerfile?

**Comment by makandre** [comment]
That’s a very good point 😕.  It won’t work for imported projects... in that case there’s still the workaround of disabling auto build. So would still be slightly better than before. I will see if there’s a better solution

**Comment by makandre** [comment]
@rajivnathan I found a better solution for this, using a combination of `npm pack` to pre-download the `nodemon` package and install from it.  I have the changes in PR #2485, could you and @elsony please take a look?

**Comment by makandre** [comment]
https://github.com/eclipse/codewind/pull/2485 merged
