### ISSUE TITLE
Split Creating and Importing Projects into IDE-specific topics. 

### ISSUE THREAD

**Issue by MelHopper** [eclipse/codewind#2360]
1. Currently, the topic 'creating and importing projects' is VS code specific. We do not have an eclipse-specific topic at present.

Actions: 

1. The topic name needs to be titled 'VS Code' and sat underneath the a tree titled 'Creating and Importing Projects' in the ToC:

Using Codewind Remotely
-> Creating and Importing Projects
--> VS Code
--> Eclipse

2. Create an eclipse-specific topic and add to the ToC as above.

3. Ensure the user flow for Eclipse users for this Using Codewind Remotely flow links to this new eclipse topic.

IMPORTANT: The Eclipse content currently lives as steps 3 and 4 of Connecting Eclipse to Remote Codewind topic, so this just needs to be moved into the new eclipse-specific topic from
remotedeploy-eclipse.md

**Comment by j-c-berger** [comment]
@micgibso or @sishida, please feel free to assign me!

**Comment by micgibso** [comment]
#2342 is a duplicate, closed, work to be done under here.

**Comment by eharris369** [comment]
Screen captures for Eclipse IDE getting started page:
![getStartedCreateProject](https://user-images.githubusercontent.com/9484320/83032314-aada4a00-a003-11ea-8495-867cd073a7b9.png)
![getStartedAddExisting](https://user-images.githubusercontent.com/9484320/83032331-b168c180-a003-11ea-979b-77ff1bbeb800.png)
![getStartedAddProjectWizPage1](https://user-images.githubusercontent.com/9484320/83032339-b3328500-a003-11ea-9207-13357cf466cf.png)
![getStartedAddProjectWizPage2](https://user-images.githubusercontent.com/9484320/83032342-b463b200-a003-11ea-859b-86244c2b0be9.png)
![getStartedAddExistingBuild](https://user-images.githubusercontent.com/9484320/83032355-b88fcf80-a003-11ea-9595-aad1e199a3e6.png)
![getStartedAddExistingRunning](https://user-images.githubusercontent.com/9484320/83032360-b9c0fc80-a003-11ea-992b-7debc4ec9676.png)

**Comment by eharris369** [comment]
Should also mention that users can drag and drop projects from one connection to another (this is an Eclipse IDE only feature). Select the project in one connection and drag it onto another connection. The project will be removed from the first connection and added to the second connection.

**Comment by j-c-berger** [comment]
@eharris369, these look great, thank you so much! :)

**Comment by eharris369** [comment]
@j-c-berger I have updated all of the images based on Mel's comments. There is a new image for the Project Already Deployed dialog since that will appear if the user adds a project to the remote connection that is already deployed on the Local connection.

**Comment by j-c-berger** [comment]
@eharris369, thanks! Where are these updated images? Did you edit the images above from 6 days ago to include the new images?

**Comment by sishida** [comment]
@j-c-berger It looks like the images have been added in the above comments. We can download them, upload them to the correct folder, and then add them to the documents.

**Comment by j-c-berger** [comment]
@eharris369, I see the new images are included in the previous comment. I overlooked them because I saw the comment was made 6 days ago. Upon second look, I see you edited the comment, and I see the new images. Sorry for me overlooking that, haha. 

I'll get a new commit up. Thank you for your help and patience on this :)
