### ISSUE TITLE
Fix the content in section 'Deploy Additional Remote Codewind Services'

### ISSUE THREAD

**Issue by MelHopper** [eclipse/codewind#2361]
The content needs work and the CAPITAL LETTERS flagging this work need to be removed before the content is published.

Consider swapping paragraphs 2 and 3 around. 

Add further information link to the bullet 
_2. assigning users through role-based acccess control. This is/can be? set up automatically using/by? the cwctl command_

**Comment by micgibso** [comment]
Resolved by #2337 on PR https://github.com/eclipse/codewind-docs/pull/453
