### ISSUE TITLE
ToC changes: Move remote-removing.md to same level as 'Deploying your Remote Codewind Instance' title

### ISSUE THREAD

**Issue by MelHopper** [eclipse/codewind#2362]
1. Move the remote-removing.md ' titled 'remove a remote deployment' to the correct level in the ToC as follows:

Deploying Codewind Remotely
-> Overview: Deploying Codewind Remotely
->Deploying your remote codewind instance
->Removing a remote deployment

2. rename title from _'remove a remote deployment'_ to _'removing a remote Codewind deployment'_

**Comment by sishida** [comment]
PR merged, closing this issue.
