### ISSUE TITLE
ToC Change: move Creating and Importing Projects to correct level in ToC

### ISSUE THREAD

**Issue by MelHopper** [eclipse/codewind#2363]
**NOTE: This bug needs to be action BEFORE bug https://github.com/eclipse/codewind/issues/2360**

Move the remotedeploy-projects-vscode.md ' titled 'remove a remote deployment' to the correct level in the ToC as follows:
Using Codewind remotely
-> Overview: Using Codewind Remotely
->Connecting your IDE to remote Codewind
--> Connecting VS Code to remote Codewind
--> Connecting Eclipse to remote Codewind
->Creating and Importing Projects

**Comment by sishida** [comment]
PR merged. Closing this issue.
