### ISSUE TITLE
Update links used by VS Code UI and Eclipse UI for using Codewind remotely

### ISSUE THREAD

**Issue by MelHopper** [eclipse/codewind#2365]
The following remote Codewind topic links for the UIs of VS Code and Eclipse need to be altered as a result of reworking/'tutorialising' of remote topics in the documentation at codewind.dev for 0.10:

**VS Code UI:**

REMOTE_UI:              new CWDoc("remotedeploy-vscode.html"),
REMOTE_DEPLOYING:       new CWDoc("remotedeploy-combo.html"),

**Eclipse UI:**
REMOTE_SETUP_URL =  DOC_BASE_URL +"/remotedeploy-eclipse.html";

from files:

https://github.com/eclipse/codewind-eclipse/blob/master/dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/UIConstants.java#L20

https://github.com/eclipse/codewind-vscode/blob/master/dev/src/constants/CWDocs.ts

Details to consider - as of 0.10:

- The ToC has been split into Using Codewind remotely and Deploying Codewind remotely - the choice of which tutorial depends on the role of the user (developer simply wanting to connect to a remote Codewind deployment that has already been set up, vs devops who must deploy Codewind remotely and configure for multiple users).

- For using or deploying Codewind, the Overview topic is the starting point for the user....though the link used for the UI might be able to skip this topic depending on context within the UI.

- There are some bugs in the ToC which need to be fixed before it becomes clear where you want your UI link to go to. 

As such, please get in touch with @melhopper to discuss most appropriate topic links to use in the UI.

**Comment by MelHopper** [comment]
@sishida FYI

**Comment by MelHopper** [comment]
@tetchel FYI

**Comment by MelHopper** [comment]
Related to https://github.com/eclipse/codewind/issues/2395

**Comment by sishida** [comment]
@MelHopper I'm wondering if we could discuss this issue during one of our regularly scheduled meetings, such as the Codewind playback call or a smaller meeting? It sounds like it'd be good for multiple people to understand how these pieces fit together. :)

**Comment by micgibso** [comment]
Also IntelliJ, see full list of IDEs/files here: https://github.com/eclipse/codewind-docs/wiki/Links-to-docs-in-IDEs-and-other-locations

**Comment by micgibso** [comment]
All IDEs updated, closing...
