### ISSUE TITLE
Rename markdown files for remote topics to match splitting into Using and Deploying actions

### ISSUE THREAD

**Issue by MelHopper** [eclipse/codewind#2366]
**Issue**
The remote documentation has now been split into 2 tutorials:

1. 'Deploying Codewind Remotely' - for devops to set up Remote instances of Codewind for their developers

2. 'Using Codewind Remotely' - for developers who simply need to connect to a remote instance of Codewind that Devops has set up for them

The markdown file names do not currently reflect this split and so could lead to some confusion or mistakes.

**TASK**
This issue is for renaming remote topics to better match the user actions associated with them.

In particular, consider using the following prefixes in the relevant markdown file names:

1. remotedeploy-<topicDefinition>
2. remoteuse-<topicDefinition>

**Comment by MelHopper** [comment]
NOTE: consider impact of these name changes - if this will break many links from external sites, reconsider.

**Comment by sishida** [comment]
I would prefer to leave the names as they currently are. It is easy to see how the files are organized by looking at the `docstoc.yml` file.

Also, if we ever need to reorganize the files again or add another category, I would rather not constrain the file names to specify `deploy` and `use`. Having them all include `remote` in their file names should suffice.

**Comment by MelHopper** [comment]
@sishida Agreed, closing this issue.
