### ISSUE TITLE
Designing user workflows based on different user roles

### ISSUE THREAD

**Issue by MelHopper** [eclipse/codewind#2367]
Other products, including IBM products such as IBM Cloud Pak for Applications, split their content based on the users' role.

See for an example: Quick start section on https://cloud.ibm.com/docs

It would be good to split Codewind based on the user role of:

1. Devops - (i) setting up remote instances of Codewind (ii) providing templates that standardise runtime versions etc, for developers to then grab from their IDE.
2. developer - using Codewind locally, remotely or as a hosted application in the cloud to create and develop projects.

**Comment by MelHopper** [comment]
@rachel.chen created a mural showcasing examples of product landing pages, some of which are split based on user role: https://app.mural.co/invitation/mural/ibmappplatform8963/1581621386636?sender=rachelchen6222&key=b407fa58-fed1-4b2f-a07b-13b78d5fe7f0

**Comment by malincoln** [comment]
@micgibso will add estimates.

**Comment by micgibso** [comment]
Following on from today's Backlog sorting meeting, removing Epic label for now for further discussion with Mel.

**Comment by micgibso** [comment]
Discussed with Mel, Mel to discuss with Tim.

**Comment by micgibso** [comment]
Closing due to Codewind going in a different direction; no longer valid.
