### ISSUE TITLE
Hone Keycloak content in Deploying Codewind Remotely topics

### ISSUE THREAD

**Issue by MelHopper** [eclipse/codewind#2368]
Keycloak is referenced multiple times within the Deploying Codewind Remotely topics. 

It is possible that the documentation can be reworked so that this information can be hidden from the user, to reduce Excise.

If not, further information about a Keycloak could be added along with explicit external webpage links to further information on the topic.

@markcor11 made this comment during a demo of the new documentation, so please follow up with him.

**Comment by sishida** [comment]
@markcor11 Hi, Mark! I am available to help with this issue. I'd appreciate a little more info before getting started. :)
- If we want to rework the documentation to hide the Keycloak info, would we be able to meet to discuss it? I looked at the documentation today, and Keycloak seems pretty well ingrained into it.
- On the other hand, if we want to add more info about Keycloak, did you have any particular links in mind to add? I did an internet search and turned up what looked to be a specific project with the same name, and I'm not sure that's the link we wanted here.
Thanks!

**Comment by markcor11** [comment]
To be clear,  I’m not suggesting we hide our dependancy on Keycloak just that we try to avoid reproducing official Keycloak documentation within our Codewind documentation or adding Keycloak detail where it adds more confusion than to be helpful for example when talking to Codewind end users (Jane) who probably don't care what identity and access manager services are being used by Codewind behind the scenes.

Whilst there will be times we need to mention Keycloak when we are asking the cluster administrator (Todd) to deploy the codewind-operator or to register users in Keycloak, the exact recipes they should follow should be in line with the official Keycloak documentation. 

We should refrain from discussing bulk user administration, in depth Keycloak configuration, password policy decisions, backup and restore processes or detailed troubleshooting steps linking instead directly to the Keycloak pages maintained by that project.

Keycloak project website is located at:  https://www.keycloak.org

**Comment by micgibso** [comment]
Have made significant efforts to orient our users since this was raised back in March. The latest documentation in this space gives our users enough Keycloak information to do the particular task in hand, but does not as Mark mentions above, discuss bulk user administration, in depth Keycloak configuration and so on.
