### ISSUE TITLE
Create single diagram defining local, hosted and remote config options for Codewind

### ISSUE THREAD

**Issue by MelHopper** [eclipse/codewind#2369]
### The problem
The distinctions between the different possible configurations for Codewind, along with the IDEs that each supports, is unclear and a big confusion even within the Codewind tribe.

### The solution
A single diagram defining the configurations and how each is related is required, for use both within Overview topics to orient users, and for other content such as Guides etc.

### Details
Diagrams for use within the Codewind documentation, as opposed to more informal content like blog content, needs to use a standard traditional 'boxes with arrows' approach, as is standard across all formal documentation for products in general, including open source products). However, if there is scope to incorporate some of the design ideas from @beccabau 's informal blog diagram that would be great.

### Diagrams
**Draft for formal documentation diagram**

NOTE this is a WIP - before embarking please check with @melhopper that this is the final draft:

![local-hosted-remote single diagram_2 0 001](https://user-images.githubusercontent.com/13365734/75686288-ec24bd00-5c93-11ea-8619-dd83e7c112f3.jpeg)

**Drafts for informal blog diagrams**
For reference, here are the informal blog diagrams, for design ideas:
![Hosted_0 1](https://user-images.githubusercontent.com/13365734/75684447-b92cfa00-5c90-11ea-8171-2f3ccba3d329.png)

**Comment by MelHopper** [comment]
I have created a draft diagram which I will forward to @kholmes for design to use to create a branded diagram.

Note that @beccabau is creating diagrams for use in less formal content types such as Blogs.

**Comment by MelHopper** [comment]
@sishida Hi Sarah, just tagging you FYI as this will be the first of a few diagrams that me, Becca and design will create for using across content including documentation - an FYI re. where you'd like these diagrams put as I know you are dealing with image location in github repo.

**Comment by beccabau** [comment]
Yes, can add my blog designs here (for the less formal blogs/more "fun" things) if requested.

**Comment by beccabau** [comment]
Yep, just let me know if we have a place to put the less formal designs!

**Comment by beccabau** [comment]
![CW-Local-Config](https://user-images.githubusercontent.com/13971834/75687062-39406900-5c6b-11ea-9e06-e8c13c2c9f3b.jpg)
![CW-Hosted-Config](https://user-images.githubusercontent.com/13971834/75687173-62f99000-5c6b-11ea-840d-2cc1c01247ca.jpg)
![CW-Remote-Config](https://user-images.githubusercontent.com/13971834/75687181-65f48080-5c6b-11ea-8fd1-6b8e570a622f.jpg)

@MelHopper - i haven't gotten around to fixing up the cw-remote-config diagram yet. I'm kind of stuck on the idea of keeping it compact (rather than the original long design), so if you have any ideas on how I can make it clearer while maintaining a pretty box, let me know!

**Comment by sishida** [comment]
I have reached out to the design team and asked them about style guidelines for charts/diagrams.

**Comment by sishida** [comment]
Experimenting with Illustrator. It's possible to change anything in these designs.

**Comment by beccabau** [comment]
Hey Sarah -- great start!

For the local machine (the first image), I think let's organize it the way you have it in the other renderings, where the IDE has its own box, and the container platform is outside of the IDE.

![image](https://user-images.githubusercontent.com/13971834/76222387-eaf21380-61f0-11ea-92a8-e6161f934561.png)

vs 
![image](https://user-images.githubusercontent.com/13971834/76222410-f04f5e00-61f0-11ea-8441-783ca4c5e0e5.png)

**Comment by sishida** [comment]
@beccabau Thanks for the feedback! I've changed the Local Configuration image and placed it in my original comment. Please let me know if you'd like any other changes. Thanks!

**Comment by MelHopper** [comment]
@sishida @beccabau just an FYI - moving this task to In Progress as I shall be reviewing the diagrams over the next couple of weeks, ready to use within some content.

**Comment by MelHopper** [comment]
Diagrams look fantastic, thanks Sarah and for reviewing Becca. A couple of requests in the following comments....

**Comment by MelHopper** [comment]
For the 2nd config, the 'browser-based' config, could you:

1. make the arrow coming from the desktop to the cloud a double-ended arrow? - showing data moving to AND from the cloud.

2. remove the arrow coming from the _Eclipse Che on Cloud Environment_ text - this text is a label for the cloud so would be best placed in the same way as the 'Local Machine' label in the Local config diagram - see screenshot below - and that arrow removed.

3. move the wifi symbol to sit on the arrow situated between the desktop and cloud?

4. rename the 'local connection' to 'Desktop'

![Arrows on Browser-based Diagram.png](https://images.zenhubusercontent.com/5d93655ea1bdb00001e54d7b/ba51eedc-f620-4d5b-8ed8-baa9a36da082)

![Local Machine label.png](https://images.zenhubusercontent.com/5d93655ea1bdb00001e54d7b/b2965922-fe4b-4f36-a70d-6de924240dbd)

**Comment by MelHopper** [comment]
For the Local config, please can you:

1. Change the label 'Local Machine' to 'Desktop'

**Comment by MelHopper** [comment]
For the 'hybrid' config, please can you:

1. rename the config to the approved terminology 'Remote config
2. change the label 'cloud hosted' to 'cloud' (as per approved terminology - FYI, cloud-hosted is not used because it is associated with on-prem software
3. rename the label 'local machine' to 'desktop'

(apologies, the original diagram I created was pre-nailing down these terminologies)

**Comment by MelHopper** [comment]
Could you make the titles 'local configuration', 'browser-based configuration' and 'remote configuration' stand out more? ie. currently the text is the same size, styling etc. as the labels 'local machine', 'cloud' etc.

**Comment by kimholmes** [comment]
Where will this diagram live on the site?

**Comment by MelHopper** [comment]
@kimholmes Hi Kim, these diagrams will be used within the website documentation topics whenever needed. e.g. the new topic 'The 3 configurations of Codewind' https://github.com/eclipse/codewind/issues/2589 Also, the relevant diagram of the 3 Sarah has created will be added at the top of each tutorial - Local, Remote, Browser-based (Codewind as a hosted application).

**Comment by sishida** [comment]
Attached are the latest versions of the graphics as png files.

![BrowserBasedConfiguration](https://user-images.githubusercontent.com/21180723/79789691-988c3280-8318-11ea-8e66-639b3ba9d8f7.png)

![LocalConfiguration](https://user-images.githubusercontent.com/21180723/79789705-9e821380-8318-11ea-836d-6440d3abb737.png)

![RemoteConfiguration](https://user-images.githubusercontent.com/21180723/79789718-a346c780-8318-11ea-9e32-715ecc7c5fb0.png)

**Comment by sishida** [comment]
Feedback from the Codewind playback meeting on April 21, 2020:
- Have we shown the diagrams to anyone who doesn't know the Codewind layout already?
- Remote should be on left and have arrow point to right (cloud). Browser based same thing.
- Why is there a wi-fi icon on the arrow in browser-based configuration? Most users would understand you're using network if you're going from local to cloud. The wi-fi icon isn't necessary.
- Suggest having a separate meeting about icons specifically. (To include: Tim D., Mel H., Jasper C., Toby C., myself)

**Comment by MelHopper** [comment]
In response to 'have we shown diagrams to anyone who doesn't know the Codewind layout already?' this will be included in user testing the whole user journey from the documentation landing page to the website docs end points and new tutorial structure in the docs. UX testing to be discussed and instigated (Mel task)

**Comment by MelHopper** [comment]
- Must ensure that all 3 diagrams are consistent - i.e. either:
1. put codewind and containers inside boxes, and label these boxes with icons, OR
2. put codewind and containers inside icons

whichever way, ensure we have consistency.

**Comment by sishida** [comment]
Latest diagrams with this week's suggested changes:

![BrowserBasedConfiguration](https://user-images.githubusercontent.com/21180723/80139999-527fda80-8575-11ea-84a7-17e0be0ddc72.png)
-------------------------------------
![LocalConfiguration](https://user-images.githubusercontent.com/21180723/80139931-3da34700-8575-11ea-990a-6d2e4bb2c4b2.png)
-------------------------------------
![RemoteConfiguration](https://user-images.githubusercontent.com/21180723/80139947-45fb8200-8575-11ea-99af-eeaf0815d908.png)
-------------------------------------

@MelHopper and @beccabau, please let me know if you'd like any other changes and/or if we should meet with the team to discuss further. Thank you!

**Comment by sishida** [comment]
@MelHopper Please see the latest image changes incorporating feedback from Monday, May 18th:

All 3 configuration options in one file:
![ConfigOptions](https://user-images.githubusercontent.com/21180723/82245949-dd07ef80-9911-11ea-84c2-ccf27eb8e0cd.png)
Please let me know if you want to rearrange these.

Local configuration:
![LocalConfiguration](https://user-images.githubusercontent.com/21180723/82245988-eee99280-9911-11ea-8fca-18915cd40e0d.png)

Browser based configuration:
![BrowserBasedConfiguration](https://user-images.githubusercontent.com/21180723/82246097-150f3280-9912-11ea-8879-9333d16c9b71.png)

Remote configuration:
![RemoteConfiguration](https://user-images.githubusercontent.com/21180723/82246150-28ba9900-9912-11ea-93b3-3375ff49ea9f.png)

**Comment by MelHopper** [comment]
Fantastic, thanks Sarah. I need to touch base with a developer to double-check how I've used the boxes on the Browser-based one, I'll get back to you asap on this.

**Comment by markcor11** [comment]
Just a few comments on the diagrams, 

1. Local:  looks ok, 
2. Che (Browser based): Containers are built and run cloud side rather than on the local machine.
3. Remote:  Whilst it is possible for containers to be built and run on the local machine (by way of local Codewind code which has to be installed along side the IDE Plugin) the main feature of remote is that build and run is not done locally but instead done cloud side.

**Comment by MelHopper** [comment]
Hi Sarah, I'm revisiting the diagrams after feedback from Mark (he also spotted a good 'typo'!). Please can you:
1. correct, on browser-based diagram, _containers built and run on local machine_' to '_containers built and run on the cloud'_
2. remove the containers from the local machine in the remote diagram (reasoning: makes it clearer that whilst you CAN run containers on local, this is not the standard use case - gives more clarity)
3. Modify the browser-based diagram as per the photo below.  Key points:
- diagram not vertical but left to right, so that it nicely matches the other 2 diagrams and mimacs the remote one in particular
- local machine on the left hand side, same as for remote _but_ with a Browser box instead of IDE and no containers
- cloud box on the right
- re-label the cloud box from 'Eclipse Che on Cloud Environment' to 'Cloud'
- relabel the 'IDE' label on the internal box to 'Eclipse Che IDE'

![Browser-based diagram](https://user-images.githubusercontent.com/13365734/83668919-a9db8680-a5c8-11ea-8776-cbc508cc6c4b.jpg)

**Comment by sishida** [comment]
@MelHopper, Here are the latest images. Please let me know if we need any further changes:

Edited text, side-by-side orientation, added boxes on left:
![BrowserBasedConfiguration](https://user-images.githubusercontent.com/21180723/84077098-d4508980-a9a4-11ea-94ea-67ead54f9fdf.png)

Removed container icons on the left:
![RemoteConfiguration](https://user-images.githubusercontent.com/21180723/84077144-e3373c00-a9a4-11ea-98bb-f2a919b50992.png)

Unchanged from previous version:
![ConfigOptions](https://user-images.githubusercontent.com/21180723/84077113-d9add400-a9a4-11ea-9c82-a4dca946eab7.png)

**Comment by micgibso** [comment]
Let's discuss in iteration planning.

**Comment by MelHopper** [comment]
Hi Sarah, thanks, these look good to go. Please could you put the images into an appropriate ./images folder and let me know the filepath? Then I'll insert into our documentation.

**Comment by sishida** [comment]
@MelHopper Here's the PR for adding the images: https://github.com/eclipse/codewind-docs/pull/669

The file path will be `docs/images/configs/<file_name>.png`

**Comment by MelHopper** [comment]
Diagrams now completed and available in images folder, so closing this issue.
