### ISSUE TITLE
SVT:Open application monitor does not work for few projects and it has to be disabled in codewind explorer view

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#237]
**Codewind version:** Latest
**OS:** Windows

**Che version:**
**IDE extension version:**   
Codewind tech preview	0.3.0.v201908161735	org.eclipse.codewind.feature.group	IBM

**IDE version:**
Eclipse IDE for Enterprise Java Developers.

Version: 2019-06 (4.12.0)
Build id: 20190614-1200

**Kubernetes cluster:**

**Description:**
Open application monitor does not work for few projects and it has to be disabled in codewind explorer view. 

Appsody: (Does not work)

Eclipse MicroProfile using OpenJ9 and Maven
LoopBack 4 API Framework for Node.js

Express web framework skaffold for Node.js
Serverless runtime for Node.js functions
Runtime for Node.js applications
Quarkus runtime for running Java applications
Spring Boot using OpenJ9 and Maven
Spring Boot kotlin using OpenJ9 and Maven
Spring Boot using OpenJ9, Maven and OpenLiberty
Runtime for Swift applications

Appsody: (Works)
Express web framework for Node.js

**Steps to reproduce:**
1. Install latest codewind.
2. Create new appsody projects with the available project templates.
3. Open application monitor does not work and yet it is available from the menu to the users.

**Workaround:**

**Comment by DavidG1011** [comment]
Noticing similar problems in VSCode on MacOS as well.

Not working for:
- Eclipse MicroProfile using OpenJ9 and Maven
- LoopBack 4 API Framework for Node.js
- Runtime for Node.js applications
- Quarkus runtime for running Java applications
- Spring Boot using OpenJ9 and Maven
- Spring Boot kotlin using OpenJ9 and Maven
- Spring Boot using OpenJ9, Maven and OpenLiberty
- Runtime for Swift applications

Working for:
- Express web framework skaffold for Node.js
- Express web framework for Node.js
- Serverless runtime for Node.js functions

**Comment by bsbyrd1** [comment]
@tobespc Can your squad help investigate this one?

**Comment by tetchel** [comment]
there is a portal API to determine if the project supports metrics:
https://eclipse.github.io/codewind/#/paths/~1api~1v1~1projects~1{id}~1metrics~1status/get

Perhaps it falsely returns `true` for the appsody projects listed above

**Comment by jagraj** [comment]
More info from my investigation, All appsody projects have this variable set to true ("metricsAvailable": true). Based on my understanding this should be set to "false" if we do not support Application metrics.

```
  "metricsAvailable": true,
  "projectWatchStateId": "32ff9a6b0bb864eb67d8379873341042",
  "appStatus": "started",
  "lastbuild": 1566476054746,
  "appImageLastBuild": "1566476053000",
  "location": "/codewind-workspace/appsodynodejsexpskacw03svt",
  "validationStatus": "success",
  "validationResults": [],
  "detailedAppStatus": " ",
  "containerId": "4148e8a3ab6265c2a4b4c5f7d39c5cd26f60684321fb2e70a4020b3fa36702c6"
```

**Comment by tetchel** [comment]
thanks, this is a backend bug, i expect this logic fails for appsody for some reason.

**Comment by tobespc** [comment]
we have to currently assume all appsody projects do have metrics enabled.  The reason being is that due to the way appsody put their stacks together, we can't check the package.json, pom.xml etc to see if they are requiring the appmetrics modules.   So we have gone for assuming they do have it.   Going forwards, we could look to see if the dashboard endpoint exists when the app is running but this would mean we could only find out once we had run the application

**Comment by tetchel** [comment]
opened #258 to track a 0.3 stopgap solution

**Comment by tobespc** [comment]
This is all working correctly now I believe and from my testing it looks ok.  Moving to verify

**Comment by malincoln** [comment]
@jagraj pls verify and close if resolved. Thanks

**Comment by stalleyj** [comment]
This is complete.
