### ISSUE TITLE
SVT : Eclipse : Error deleting project

### ISSUE THREAD

**Issue by mmulholl** [eclipse/codewind#2375]
**Codewind version:*  Codewind tech preview	0.10.0.v202002281957	
**OS:** Mac

**Che version:**
**IDE extension version:**
**IDE version:** Eclipse
**Kubernetes cluster:**

**Description:**

Deleting an appsody open liberty project I see this pop-up although the project does appear to be deleted.

![image](https://user-images.githubusercontent.com/16086270/75723136-b25eb100-5ca9-11ea-9ac3-2a6107673eee.png)

**Steps to reproduce:**

**Workaround:**

**Comment by tetchel** [comment]
https://github.com/eclipse/codewind/issues/2193

**Comment by mmulholl** [comment]
Fixed.
