### ISSUE TITLE
SVT:Codewind does not support appsody Serverless templates and this needs to be documented

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#238]
**Codewind version:** Latest
**OS:** Windows

**Che version:**
**IDE extension version:**   
Codewind tech preview	0.3.0.v201908161735	org.eclipse.codewind.feature.group	IBM

**IDE version:**
Eclipse IDE for Enterprise Java Developers.

Version: 2019-06 (4.12.0)
Build id: 20190614-1200

**Description:**
SVT:Codewind does not support appsody Serverless templates and this needs to be documented.

**Steps to reproduce:**
1. Install latest codewind.
2. Create new serverless projects from appsody templates.

**Workaround:**

**Comment by sghung** [comment]
Closing as it has been documented in https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/troubleshooting.md
