### ISSUE TITLE
Move Optional topics out of Eclipse Che tutorial block and into it's own block

### ISSUE THREAD

**Issue by MelHopper** [eclipse/codewind#2381]
Currently, all topics relevant to Eclipse Che are sitting under the Eclipse Che section of the Getting Started block.
- 🦄 Update link on `mdt-che-createcodewindworkspace.md`.
- Installing Codewind for Eclipse Che
- Adding registries in Che
- Creating the Codewind workspace
- Creating your first project 
- Uninstalling Codewind for Eclipse Che
(🦄 From meeting with John C on March 9th: The above topics are required to install Che.)

************************************
- Setup to use Tekton Pipelines
- OpenShift Do (odo) support in Codewind
- Using the OpenShift Registry
- Support for multiple users (🦄From meeting with John C on March 9th: This topic can be removed.)
- Installing Kibana and filtering logs in IBM Cloud Private (🦄From meeting with John C on March 9th: This topic can be removed.)

The topics below the line of stars defined above need to be moved into their own block 'Optional configurations for Codewind on the cloud' or 'Optional configurations for Codewind on Eclipse Che' <WIP - needs deciding>.

**Comment by sishida** [comment]
I attempted to add child topics to **Getting Started**>**Eclipse Che** with this PR: https://github.com/eclipse/codewind-docs/pull/469.

I ran `./serve.sh`, and got what the screenshot shows here.
- Unlike with the **Eclipse Che** parent, **Optional configurations for Codewind on Eclipse Che** doesn't have the arrow indicating it has children.
- The nested child files nested don't even appear.
<img width="342" alt="CheChildTopics1" src="https://user-images.githubusercontent.com/21180723/76342152-7abcbe00-62d4-11ea-8e3d-eb6f0e8a206a.png">

If you click **Optional configurations for Codewind on Eclipse Che** , you get taken back to the home page:
<img width="1552" alt="CheChildTopics2" src="https://user-images.githubusercontent.com/21180723/76342345-d71fdd80-62d4-11ea-9e77-c1f8a13ed9ae.png">

**Comment by sishida** [comment]
PRs for removing unnecessary files:
1️⃣https://github.com/eclipse/codewind-docs/pull/470
2️⃣ https://github.com/eclipse/codewind-docs/pull/475
3️⃣ https://github.com/eclipse/codewind-docs/pull/478

**Comment by MelHopper** [comment]
The final parts of this issue are being covered as part of https://github.com/eclipse/codewind/issues/2718 - Create content for orientation and signposting in Eclipse Che section and improve user flow

As such, now closing this issue.
