### ISSUE TITLE
(metrics) SVT: Users will not know for which projects we support performance and metrics dashboards

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#2384]
**Codewind version:** 0.9.0 & Latest

**Description:** Users will not know for which projects we support performance and metrics dashboards.

Metrics and performance dashboards must be available in Java, Node JS, and Swift projects. However, projects such as Java Lagom didn't support the mentioned options in previous releases (i.e., before 0.9.0). Therefore, as with other types of projects (Go and Python), they didn't present the "Metrics Dashboard" and "Performance Dashboard" options.

However, recently those options have been enabled for projects such as Java Lagom. Therefore, a user can access the Metrics Dashboard, but without gathering data and can run a load test (Performance Dashboard), but without obtaining results.

I understand that PFE cannot distinguish between a Java Lagom and an Open Liberty project. Therefore, we have some issues, such as: https://github.com/eclipse/codewind/issues/2223.

However, from the user's perspective, they will try to use the metrics and performance dashboards for projects that present that option, such as the case I mentioned with Java Lagom. Besides, this scenario can be reproduced with some Appsody projects. 

So, are we presenting that option even when it is not supported? Or, should we hide that option?

<img width="357" alt="Screen Shot 2020-03-03 at 1 51 20 PM" src="https://user-images.githubusercontent.com/49531960/75809050-18087700-5d56-11ea-9c29-9be49098ef0b.png">

<img width="1668" alt="Screen Shot 2020-03-03 at 1 50 57 PM" src="https://user-images.githubusercontent.com/49531960/75809053-1b036780-5d56-11ea-8b5d-dce0f6051b3a.png">

![Screen Shot 2020-03-03 at 1 50 39 PM](https://user-images.githubusercontent.com/49531960/75809058-1ccd2b00-5d56-11ea-99e1-2d145a5a6dea.png)

**Relevant issues:**
https://github.com/eclipse/codewind/issues/2038
https://github.com/eclipse/codewind/issues/2299

@jagraj @cccanderson

**Comment by sujeilyfonseca** [comment]
/priority stopship

I'm adding this tag after discussing this issue with @jagraj.

**Comment by malincoln** [comment]
@tobespc @eharris369 @tetchel  ^^^

**Comment by tetchel** [comment]
The IDEs are behaving correctly with the information provided, as described in https://github.com/eclipse/codewind/issues/1815#issuecomment-583354048. 

The backend has to provide 'more correct' information such as not saying that lagom projects support the metrics dashboard. Until we have that, there's nothing more we can do.

**Comment by tobespc** [comment]
Whats the justification for this being a stop ship ?  It doesn't prevent the user doing anything.  I realise that the performance dashboard can be displayed for a project type that could never have metrics.  Thats more ugly than broken :-)

**Comment by jagraj** [comment]
Yes, this is more ugly and not user friendly. We should let user know that performance and metrics not supported for the projects that we do not support. Best solution is, IDEs need to know which projects that we support and disable them for the user. If we can not deliver fix in this release and we should document and let user know which projects we support Performance metrics, Metrics dashboard and also "Enable Inject Metrics". Once this is documented then we can lower the severity and deliver actual fix in next release.

**Comment by malincoln** [comment]
@jagraj I'm assuming we need the docs label?  @micgibso @sishida ^^^

**Comment by sishida** [comment]
In this file (here https://www.eclipse.org/codewind/metrics-dashboard.html), we state, "The Metrics Dashboard is available for Java, Node.js, and Swift." Should we clarify this statement in some way?

**Comment by malincoln** [comment]
> In this file (here https://www.eclipse.org/codewind/metrics-dashboard.html), we state, "The Metrics Dashboard is available for Java, Node.js, and Swift." Should we clarify this statement in some way?

@jagraj does this suffice or additional doc is needed?

**Comment by jagraj** [comment]
Yes, this is the doc. We need to doc exactly which projects we support metrics and performance.
We will capture set of projects that we do not support and provide the list here to doc it.

**Comment by sujeilyfonseca** [comment]
I consider we should update both documents that talk about metrics and performance dashboards. As Jag said, we need to update for which projects we support these features:

http://9.21.109.38:4321/codewind/metrics-dashboard.html
http://9.46.86.50:4321/codewind/performance.html

**Comment by tobespc** [comment]
My thinking of this is that we could enhance the performance dashboard to provide the necessary info around why we are not getting metrics.  that way, the IDE's could just always link to the perf dash (which can always be used to run load) and then if we can't display the results, let the user know from there

**Comment by malincoln** [comment]
> My thinking of this is that we could enhance the performance dashboard to provide the necessary info around why we are not getting metrics. that way, the IDE's could just always link to the perf dash (which can always be used to run load) and then if we can't display the results, let the user know from there

@jagraj @tobespc should we open a separate bug for the fix that we track for 0.11.0 and use the current bug for the doc change?

**Comment by sishida** [comment]
If we plan to fix the issue, and thus if the proposed doc update is only going to appear in one release, I would prefer that we refrain from a doc change and instead leave this issue open for everyone to see.

However, if we want a doc change that will need to appear in the docs indefinitely, then let's go forward with the doc change. Thank you!

**Comment by jagraj** [comment]
@sishida 
Sounds good. We will add list of projects that we support in this issue, so that user can get more info from this issue.

**Comment by sujeilyfonseca** [comment]
@jagraj @sishida 
I'm working on the list of projects. I'll post it in a moment.

**Comment by sujeilyfonseca** [comment]
[UPDATE] I was working on the list, but then I got into a blocker. The performance dashboard is very confusing now. I see some projects that should support it without results now. Also, the function gets stuck many times.

@jagraj asked for clarification, so we will wait until an answer is provided to identify the list of projects and if there are any possible new issues.

**Comment by malincoln** [comment]
@tobespc will provide list of projects supported.

**Comment by tobespc** [comment]
lagomTemplate, pythonTemplate and goTemplate do not provide any metrics (load test will run but you would not see any results) and you cannot inject metrics.

nodeExpressTemplate, springJavaTemplate, swiftTemplate, javaMicroProfileTemplate all provide out the box metrics and performance summary data.

openLibertyTemplate provides metrics out the box but requires 'injectMetrics' to give performance summary data.

generic Node.js applications support 'injectMetrics'

generic javaLiberty (both openLiberty and microprofile) support 'injectMetrics'

**Comment by jagraj** [comment]
@tobespc 
How about Appsody templates, which project type we support.?

**Comment by malincoln** [comment]
> @tobespc
> How about Appsody templates, which project type we support.?

@tobespc to add additional projects.  We can then remove the priority/stopship and add priority/hot for code fix to be added in 0.11.0

**Comment by tobespc** [comment]
Appsody projects are not so easy to catagorise as we cannot detect what they support.  It should be possible to display the metrics dashboard for any appsody stack that either
  * Makes use of the mp-metrics module (https://cloud.ibm.com/docs/java?topic=java-mp-metrics)
                or
  * Includes javametrics/appmetrics/swiftmetrics

For the performance dashboard to display information, the appsody project will need to be using 
  *  javametrics/appmetrics/swiftmetrics

**Comment by malincoln** [comment]
@tobespc is this still on track for 0.11.0?

**Comment by malincoln** [comment]
Update from @tobespc: Fix will not make 0.11.0 so moving to 0.12.0

**Comment by tobespc** [comment]
The fix for this is being resolved under #2687 
closing this as and tracking under above issue
