### ISSUE TITLE
[IntelliJ] Support for app metrics -- dashboard and injection

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind#2386]

**Comment by keithchong** [comment]
@sishida , affects docs too.

https://www.eclipse.org/codewind/metrics-dashboard.html

Currently says metrics dashboard is available in VS Code, Eclipse and Che

**Comment by keithchong** [comment]
Here too for performance: https://www.eclipse.org/codewind/performance.html

**Comment by sishida** [comment]
Assigning myself to help with the docs work. :)
