### ISSUE TITLE
Broken URL in Codewind VSCode when adding remote connection

### ISSUE THREAD

**Issue by rachelwchen** [eclipse/codewind#2390]
**Codewind version:** v0.9.0
**IDE:** VSCode
**IDE version:** 1.42.1

**Description:**
In the remote connection settings page on VSCode, the "3. Add Registries (?)" link is broken (see the yellow arrow):
![url](https://user-images.githubusercontent.com/12159451/75822830-7bde7000-5d55-11ea-9a0a-d20925269756.png)

The link takes you to https://www.eclipse.org/codewind/image-registry-credentials.html which shows "404 File not found":
![image](https://user-images.githubusercontent.com/12159451/75822878-8f89d680-5d55-11ea-84fd-2dea69a875bb.png)

**Comment by sishida** [comment]
My guess (based on PR https://github.com/eclipse/codewind-docs/pull/364/files), is that `che-setupregistries` is the update for that broken link, but it specifically talks about Che, not VS Code.

**Comment by MelHopper** [comment]
Hi Sarah, I've been having a similar conversation in parallel with @tetchel. This resulting github issue solves the problem. https://github.com/eclipse/codewind/issues/2382

(The image-registry-credentials file I assume was one of the 3 topics that existed under the Che block in the ToC that got amalgamated: Adding Registries, Docker Registry Guidance, and Setting Docker Registries).

I believe our most up to date list of files that were omitted as part of the Toby and Mark restructure does not include this topic, so I assume that it always just existed in the Eclipse Che section and we are not missing any other information.

In addition, I have checked with Tim, and all the content in the topic in the new che-setupregistries.md file of Che can be copied as a new topic for remote case with just a couple of mods based on the UI itself - see details of the github issue https://github.com/eclipse/codewind/issues/2382

@tetchel many thanks for picking this up.

**Comment by sishida** [comment]
@MelHopper @tetchel 
To see the amalgamation of the image-registry-credentials file, see this PR: https://github.com/eclipse/codewind-docs/pull/364/files

I can start https://github.com/eclipse/codewind/issues/2382 and ask @tetchel for review to help make sure the file conforms to the remote situation if everyone's OK with this plan?

**Comment by micgibso** [comment]
Fixed, closing...
