### ISSUE TITLE
Perform audit and create central document detailing external links to topics

### ISSUE THREAD

**Issue by MelHopper** [eclipse/codewind#2395]
As topics are reworked and overviews added to the website documentation, links from external sites and IDE UIs need to be modified and optimised.

A central document detailing all the external locations that use links to topics is required, to ensure links are updated, the best links are used, and to prevent 404 errors.

**The list includes:**
ICP4A Knowledge Center
Marketplace
Docker
IDE UIs - Eclipse, VS Code, IntelliJ
Blogs
Guides
Videos
<ADD HERE>

**IDE UIs are detailed here** 
https://github.com/eclipse/codewind-docs/wiki/Links-to-docs-in-IDEs-and-other-locations

**related Github issues to do with external links**
- Create orientation and signposting for Eclipse Che YAML file 'download' https://github.com/eclipse/codewind/issues/2568
- Add/Update the Dockerhub overviews to contain more information https://github.com/eclipse/codewind/issues/2034
- Broken Codewind links on other websites https://github.com/eclipse/codewind/issues/2757

**Comment by MelHopper** [comment]
@micgibso FYI creating a spreadsheet for us to use, which will hopefully reduce number of bugs resulting from doc changes.
Please can you assign ID label and assign to me? Many Thanks.

**Comment by MelHopper** [comment]
Related Github Issues: https://github.com/eclipse/codewind/issues/2365

**Comment by sishida** [comment]
Please remember to make sure that this central document is publicly viewable.
As an open source project, we want all users and contributors to have easy access to it. Thanks!

**Comment by MelHopper** [comment]
See https://github.com/eclipse/codewind-docs/wiki/Links-to-docs-in-IDEs-and-other-locations

**Comment by MelHopper** [comment]
Add links from:
1. ICP4A KC
2. Kabanero.io
3. Which other products?

**Comment by micgibso** [comment]
Moving to verify, is this work complete?

**Comment by micgibso** [comment]
Closing as out of scope.

**Comment by micgibso** [comment]
Back in scope, need to check ICPA docs for mentions of Codewind and check they are all valid: 
https://www.ibm.com/support/knowledgecenter/SSCSJL_4.2.x/install-tools.html
And other sections as applicable.

**Comment by micgibso** [comment]
https://www.ibm.com/support/knowledgecenter/SSCSJL_4.2.x/guides/codewind-getting-started-vscode/codewind-getting-started-vscode.html
Developing with VS Code -> Prerequisites -> Installing Codewind for VS Code link is 404.
Needs correcting to https://kabanero.io/docs/ref/general/installation/installing-dev-tools.html#installing-codewind-for-vs-code
in the Kabanero docs. 

Raised as a Discus comment. 

No further broken links found.
