### ISSUE TITLE
codewind says docker not installed even though it is.

### ISSUE THREAD

**Issue by juansuerogit** [eclipse/codewind#24]
Im running CentOS Linux release 7.6.1810 (Core)
with visual studio code code-1.36.1-1562627663.el7.x86_64.rpm
with docker-ce from the yum repository docker-ce-18.06.3.ce-3.el7
with docker-compose from the yum repository docker-compose version 1.24.1, build 4667896

my setup also added a parameter to docker systemd /usr/lib/systemd/system/docker.service
ExecStart=/usr/bin/dockerd --userns-remap=meta
to enable usernamespaces so i didnt have to run all my containers as root.

but then i went to install codewind from visual studio code and the first weird thing was that it told me docker wasnt installed even though it was.
so i clicked ok 

then my original docker-ce-18.06 becomes  Docker version 18.09.7, build 2d0083d
and my systemd settings are wiped out and replaced with
/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock

why do you have to remove my docker if i had one running already and then you cannot connect to it?

my user is in the docker group

**Comment by tetchel** [comment]
This appears to be the same issue as https://github.com/eclipse/codewind-installer/issues/53
