### ISSUE TITLE
Document the steps to create your own template/stack

### ISSUE THREAD

**Issue by AndyRWatson** [eclipse/codewind#2404]
**Codewind version:** 0.9
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description of the enhancement:**

within our documentation for "working with templates" https://www.eclipse.org/codewind/workingwithtemplates.html

there is no documentation on the required template structure or steps on how to create your own repo or add a template of your own.  We document how to configure to point at your own repo but assume the steps on how to create the contents are already know to a user.

**Proposed solution:** 

We should ensure that our documentation adequately describes the steps on how to create your own template source as well as how to add additional application templates.  

As an example it is worth looking at the detail Appsody.dev has to define and guide compared to our 3 steps

https://appsody.dev/docs/stacks/stacks-overview#stack-structure

**Comment by AndyRWatson** [comment]
linking to https://github.com/eclipse/codewind/issues/2241

**Comment by sishida** [comment]
Talked with @micgibso about this issue. It looks very similar to https://github.com/eclipse/codewind/issues/2570. However, please feel free to reopen if needed.
