### ISSUE TITLE
Add support for Code Ready Workspaces IDE (CHE)

### ISSUE THREAD

**Issue by AndyRWatson** [eclipse/codewind#2407]
**Codewind version:** 0.10
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description of the enhancement:**

The kabanero.io project has just announced support for codewind running in RH Code Ready Workspaces (CHE based IDE support).  https://kabanero.io/blog/2020/02/27/WhatsNew060.html

with instructions on how to enable 
https://kabanero.io/docs/ref/general/installation/installing-codeready-and-codewind.html

We do not make any reference to supporting on our main codewind site

**Proposed solution:** 

test and update our own documentation on how to enable codewind within CodeReady Workspaces.

This may be a update to  the current CHE support / instructions or a new IDE ?

**Comment by micgibso** [comment]
See Jake's PR for Code Ready workspaces here: https://github.com/eclipse/codewind-docs/pull/434

**Comment by AndyRWatson** [comment]
Is that a kabanero guide @micgibso  or an update to our own landing pages ?

**Comment by micgibso** [comment]
@AndyRWatson Jake mentions that it's `taken from work that was done for Kabanero` 
@j-c-berger Any more info?

**Comment by j-c-berger** [comment]
@AndyRWatson & @micgibso, Yes, issue #434 is adapted from the content already published here on Kabanero.io (the link Andy included above): https://kabanero.io/docs/ref/general/installation/installing-codeready-and-codewind.html

**Comment by micgibso** [comment]
@johnmcollier Discussing with @j-c-berger , do we want to document anything about CodeReady workspaces in Codewind for 0.10.0?   Or would 0.11.0 be more preferable?

**Comment by johnmcollier** [comment]
We can do 0.11.0

**Comment by AndyRWatson** [comment]
given the short runway now for 0.10 then 0.11 is ok,

**Comment by johnmcollier** [comment]
This got away from me for 0.11.0 due to our work with odo, let's revisit after the 0.11.0 release to determine how exactly we want to state our support for CodeReady Workspaces

CC @j-c-berger

**Comment by micgibso** [comment]
Documented on PR https://github.com/eclipse/codewind-docs/pull/613.
