### ISSUE TITLE
[VSCode IDE] Have to click on entry field to type project name

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#2412]
On Windows 10 using Codewind for VSCode 0.10.0 latest build.

- Click on create a new project
- Type go to search for the project type and click enter
- Try to type a project name and nothing happens, have to click on the field in order to type the project name

**Comment by tetchel** [comment]
it is the same cause as https://github.com/eclipse/codewind/issues/2330 

I'm not sure why the new inputbox sometimes doesn't grab focus.

**Comment by tetchel** [comment]
I plan to fix this but I am folding this specific issue under https://github.com/eclipse/codewind/issues/2330
