### ISSUE TITLE
Improve the Jenkinsfile as per comments in PR 230

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#242]
- [ ] Is there an environment variable for the codewind directory that we can use to change directory instead of relative paths? If not we can create one before cd src/pfe/portal. It'd help make the Jenkinsfile more robust in case other changes are added in between in the future.

- [ ] Check uses of -eq instead of -gt?

- [ ] Think we need the -a flag to find exited containers and in the other uses of docker ps below?

PR: https://github.com/eclipse/codewind/pull/230

**Comment by james-wallis** [comment]
/assign

I'm working on the Jenkinsfile anyway so I'll pick these up.

**Comment by james-wallis** [comment]
I've completed all the items in this issue, @tobespc can you close please.
