### ISSUE TITLE
SVT : Eclipse : After import appsody node projects lose metrics and perf dashboard options

### ISSUE THREAD

**Issue by mmulholl** [eclipse/codewind#2423]
**Codewind version:**  Codewind tech preview	0.10.0.v202003050956	
**OS:** Mac

**Che version:**
**IDE extension version:**
**IDE version:** Eclipse jee 2019-09
**Kubernetes cluster:**

**Description:**
Create an appsody node app, for example NODE RED and once it is started you can open the metics and performance dashboards. Remove the project and re-import it, but now the language has changed from Node.js to javascript and the option to view the metrics dashboard and performance dashboard are no longer available.     

**Steps to reproduce:**
1. Create an appsody node red project
2. Open the metrics and performance dashboards and be in awe of their wonder.
3. Remove the project from codewind but leave on disk.
4. Import the project back into codewind.
5. No option to open the metrics or performance dashboard and no wonder to be in awe of.

**Workaround:**

**Comment by eharris369** [comment]
After creating the node RED project, the project info contains:
```
    "metricsDashboard": {
      "hosting": "project",
      "path": "/appmetrics-dash/?theme=dark"
    },
    "perfDashboardPath": "/performance/charts?project=47592e60-6264-11ea-9bc8-432ac8febdd7",
    "startMode": "run",
    "metricsAvailable": true,
```
and `cwctl --json project validate --path C:\home\work\codewind\eclipse1909\runtime-devtest3\node1` returns:
```
{"status":"success","projectPath":"C:\\home\\work\\codewind\\eclipse1909\\runtime-devtest3\\node1","result":{"language":"javascript","projectType":"appsodyExtension"}}
```

Removing the project and adding it back using the project information from the validate call:
```
cwctl --json project bind --name node1 --language javascript --type appsodyExtension --path C:\home\work\codewind\eclipse1909\runtime-devtest3\node1 --conid local
```
and the project info now contains:
```
    "metricsDashboard": {
      "hosting": null,
      "path": null
    },
    "perfDashboardPath": null,
    "startMode": "run",
    "metricsAvailable": false,
```

**Comment by rajivnathan** [comment]
This looks like it's isolated to cwctl and portal's handling of the project.inf file so removing the iterative-dev label.

**Comment by hhellyer** [comment]
@mmulholl - I think this is a duplicate (or possibly the original) of https://github.com/eclipse/codewind/issues/2548 which should now be resolved. Could you retest this and see if it's fixed for you? (The issue with see the project as `javascript` instead of `nodejs` and therefore not getting the dashboard after import is the same.)
