### ISSUE TITLE
Images are tight cropped on create first project page

### ISSUE THREAD

**Issue by AndyRWatson** [eclipse/codewind#2427]
**Codewind version:** 0.9
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**
On the create first project page 

https://www.eclipse.org/codewind/mdt-vsc-firstproject.html

The image for the "open app" view in a browser has been too tightly cropped so we see no edges to the original screen capture and the image appears in some way to be part of our documentation page itself. (congratulations !  You are .....)

<img width="1333" alt="Screenshot 2020-03-07 at 10 36 30" src="https://user-images.githubusercontent.com/9268814/76141815-aedb7900-605f-11ea-8374-25c1ae39ac43.png">

We should look to ensure our images are correct and aesthetically correct.   

We should maybe also chat with design to see how best to represent and size these types of images too ?   How do we ensure captures don't have personal bookmarks (IBM) etc in the image too ?

**Steps to reproduce:**

as above

**Workaround:**

**Comment by micgibso** [comment]
Discussions ongoing about image standards. Also need to consider dark mode vs. light mode.

**Comment by tetchel** [comment]
You could give it a border, something like this. +1 for hiding your bookmarks before taking a screenshot :)

![image](https://user-images.githubusercontent.com/8888438/76370556-a019ee00-630d-11ea-95dd-3af93f3ad02b.png)

**Comment by sishida** [comment]
I cropped the image and added the border as now shown in the file, `docs/images/runningapp.png` in PR https://github.com/eclipse/codewind-docs/pull/497.

However, when I try to run a local build with `./serve.sh`, the file appears cropped but not with the border. Any ideas why this is happening? Here's what I'm seeing:

<img width="886" alt="Screen Shot 2020-03-19 at 3 25 35 PM" src="https://user-images.githubusercontent.com/21180723/77106757-fe259000-69f5-11ea-93d1-ca9a9513a9c4.png">

**Comment by sishida** [comment]
Also typed up a wiki page about image info: https://github.com/eclipse/codewind-docs/wiki/Images-guidelines-%5BWIP%5D

**Comment by sishida** [comment]
- Cropped the image so that it doesn't show bookmarks and too much extra space.
- Opened https://github.com/eclipse/codewind/issues/2528 to add a border around the image (and other images with white backgrounds) to make them better stand out from the rest of the page.
- Closing this issue.
