### ISSUE TITLE
[Eclipse IDE] Create a test case to test the documentation links

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#2430]
Create a test case that tests the documentation links (and any other links used in the IDE). All are in the UIConstants class.

**Comment by jgwest** [comment]
@eharris369 Food for thought: you might even be able to automate this as a test case... a test case look through each of the URLs:
```java
	// Documentation links
	public static final String 
		DOC_BASE_URL = "https://www.eclipse.org/codewind",
		CWSETTINGS_INFO_URL = DOC_BASE_URL + "/project-settings.html",
		TEMPLATES_INFO_URL = DOC_BASE_URL + "/workingwithtemplates.html",
		REGISTRY_INFO_URL = DOC_BASE_URL + "/remote-setupregistries.html",
		REMOTE_SETUP_URL =  DOC_BASE_URL +"/remotedeploy-eclipse.html";
```
and looks under `https://github.com/eclipse/codewind-docs/tree/master/docs/_documentations` to make sure an `.md` file with the same name exists.
