### ISSUE TITLE
[Investigation] Implementing tabs into codewind docs

### ISSUE THREAD

**Issue by sghung** [eclipse/codewind#2436]
We want tabbed content for certain sections to make it cleaner

**Comment by sghung** [comment]
This file shows how to have a two tabbed navigation within the MD files.

[remotedeploy-combo.md.zip](https://github.com/eclipse/codewind/files/4308110/remotedeploy-combo.md.zip)

For accessibility reasons, I use the "kubernetes" and "openshift" as IDs and aria properties. If you use these tabs elsewhere, you will need to change them as needed.

For the annoying scroll up, I will be investigating that it another issue and fixing it. It is being caused by a javascript file we own, but I need to see if we can safely remove that.

**Comment by sghung** [comment]
Travis had provided some code for implementing tabs, there was just some minor fixes to get it to work. I had investigated whether we can use tabs in Jekyll and it wouldn't work for our case. It would make the tabs complicated since it would need a new layout and each tab source would need to be in its own md file. For the currently requirements, where there are only two sentences for each tab, putting the HTML directly in the MD file is much easier for both the doc writer and to implement.

**Comment by micgibso** [comment]
Closing this due to the requirement for tabs in our content being negated by the new Codewind operator. If we identify further content that might require tabs, we can revisit. @MelHopper fyi.
