### ISSUE TITLE
Codewind webpage scrolls to the top on anchor presses

### ISSUE THREAD

**Issue by sghung** [eclipse/codewind#2437]
When the user clicks on anchors (say a tab), it scrolls to the top all the time, which is very annoying. This functionality needs to be investigated to see:
1. Why was this implemented
2. Can it be removed or fixed?

**Comment by sghung** [comment]
The issue is being caused by this PR: https://github.com/eclipse/codewind-docs/pull/285/files

I am talking to Michael to see if this can be removed, since the "detect OS" function isn't being used anywhere. The regex used to call this function would affect all tabs, so I'd rather remove it since it seems buggy to jump to the top. If the tabs were embedded into the MD, it may not be at the top, so it's incorrect to assume the user would want to jump to the top of the screen anyway.

**Comment by sghung** [comment]
As I dig into this more, I realize that there were a few javascript functions that are causing this problem and its related to the sidebar. I am looking to redo the sidebar in order to remove these problematic functions. Bootstrap have APIs to deal with the sidebar, so we shouldn't need to implement this logic ourselves. This logic is interfering with all anchors.

**Comment by micgibso** [comment]
Have created https://github.com/eclipse/codewind-docs/pull/482 to add tabs to content using the latest code.

**Comment by jcockbain** [comment]
@sghung is this still a problem after your latest sidebar changes? 

I can't recreate but may be misunderstanding the issue. Do you mean clicking on a linked section like https://www.eclipse.org/codewind/troubleshooting.html#cannot-find-codewind-in-marketplace-when-attempting-to-install-in-intelli?

**Comment by sghung** [comment]
Hey James, yes, this was fixed with the sidebar changes, I will close it
