### ISSUE TITLE
Add/remove repository to providers broken by deepClone

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#2439]
**Codewind version:** master
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**

When adding a template repo (an appsody one for example: https://github.com/makandre/testrepo/releases/download/0.1/testrepo-index.json), it is not being added to the corresponding provider in PFE.

Looks like this is recently broken by https://github.com/eclipse/codewind/commit/a80e98cadace6c3b839c1b6b95bd7f16611938f8#diff-395b0c2bf7f52e9b39e91bb2d4991d15R157; it is doing a `deepClone` on the provider objects which is stripping out all functions on the provider

**Steps to reproduce:**

**Workaround:**

**Comment by malincoln** [comment]
@makandre pls verify and close. Thanks

**Comment by makandre** [comment]
Verified it's fixed on master
