### ISSUE TITLE
Appsody should not be installed into kube case

### ISSUE THREAD

**Issue by sghung** [eclipse/codewind#244]
**Codewind version:**
0.3.0
**OS:**

**Description:**
Appsody should check if it is in the kube environment. If it is, do not install it

**Steps to reproduce:**
Start codewind in kube environment.

**Comment by makandre** [comment]
I can take a look at this

**Comment by sghung** [comment]
Thanks Andrew. I started to take a look, I was hoping process.env.IN_K8 could be made available in templateProvider.js in the appsody extension, but it isn't

**Comment by makandre** [comment]
We maybe able to use https://github.com/eclipse/codewind/blob/master/src/pfe/portal/modules/utils/sharedFunctions.js#L19

But the question is when running in k8s, do we:
- don't install the plugin, or
- install but don't load, or
- load but don't return any repos?

**Comment by sghung** [comment]
Gating was done as part of https://github.com/eclipse/codewind-appsody-extension/pull/11 and has been released to https://github.com/eclipse/codewind-appsody-extension/releases/tag/0.3.0. @johnmcollier, can you try this scenario again in the kube case? If it works, I'll close. Thank you

**Comment by sghung** [comment]
I talked with John and he verified the fix worked, closing.
