### ISSUE TITLE
PR checks missing from branches

### ISSUE THREAD

**Issue by stalleyj** [eclipse/codewind#2442]
**Description:**
I was looking at a PR this morning and realised that I would have been able to merge it without it either having a review or the travis build having completed.  The checks need to be applied to all branches. The PR was in the codewind-installer repository. This could easily lead to a PR being merged that does not build.

**Comment by josephca** [comment]
Thanks, @stalleyj for the catch. As we had a chat, it seems to be a bug that needs to be handled by the Eclipse team. 
I re-opened a Bugzilla bug and will close this issue once it gets fixed by the Eclipse team. 

Copying the request:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=550116

```
The branch protection rule seems not working for a double-digit version number. 
It's been working well for a single-digit version i.e. 0.9.0. However, it failed on '0.10.0' and as a result, it allows merging PR without a review. 
Could you revise the branch protection rule to deal with more than 1 digit number? to be safe, protection on 3 digits would be preferred. i.e. 123.456.789. 
Protection on the 'master' branch is still required though. 

```

**Comment by josephca** [comment]
Fixed by the Eclipse team. @stalleyj - please verify. Thanks!

**Comment by josephca** [comment]
Verified with https://github.com/eclipse/codewind-installer/pull/398 which requires a code review in order to get merged. 
![image](https://user-images.githubusercontent.com/25185698/76424121-3128ad80-637e-11ea-8890-ea4a6a8a9b94.png)
