### ISSUE TITLE
Write template descriptions

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind#2443]
For the template sources descriptions in the Codewind UI, complete a full iteration of content, design, and research. Submit it to the Illumi award.

The documentation team will be responsible for the content rewrite while designers will be involved with page design, user testing, and writing and uploading the Illumi award submission.

**Content rewrite**
We need to rewrite the template descriptions & make sure to include the following:
1 - value prop & operational benefits: why/how this template is better suited for certain needs
2 - technical details: what are some technical features that come with the template
3 - link out: link out to documentations so the user can read more about the template
4 - include template preview (optional)

**Comment by sishida** [comment]
**March 18th, 2020: Reached out to the Appsody team on Slack today.**

1. value prop & operational benefits: why/how this template is better suited for certain needs
2. technical details: what are some technical features that come with the template
3. Link to Appsody docs on the Appsody website: https://appsody.dev/docs
4. include template preview (optional)

**Comment by sishida** [comment]
- Default Templates: Create containerized projects for various runtimes with Codewind project templates. If you're new to Codewind or not sure where to start, try a default template. With Codewind, you can develop in containers without feeling like you're developing in containers.
- Appsody Stacks--Incubator: Develop applications with  with Appsody in Codewind. Choose this Appsody template if you want to build and deploy to Kubernetes. This template is also a good choice if you want to share technology stacks on the Appsody Hub repository.

Reading:
- https://www.ibm.com/cloud/blog/codewind-appsody-tekton-means-easier-cloud-native-development
- https://developer.ibm.com/technologies/containers/tutorials/kabanero-introduction-to-modern-microservices-development-for-kubernetes/

**Comment by sishida** [comment]
What are Appsody stacks?
-  Stacks: Container images prebuilt with runtimes and frameworks (https://kabanero.io/developer/cli/)
- Each stack is pre-configured with popular open source technologies to enable rapid development of quality microservice-based applications. Stacks include a base container image and project templates which act as a starting point for your application development. Stacks allow for rapid development whilst giving the stack developer the ability to control the overall applications that are created from it. (https://appsody.dev/docs/stacks/stacks-overview/)
- Appsody provides pre-configured application stacks that enable rapid development of quality microservice-based applications. Stacks include a base container image and project templates, which provide the language runtimes, frameworks, and any additional libraries and tools that you need for local development. Stacks are an easy way to manage consistency and adopt best practices across many applications. (https://appsody.dev/docs/stacks/stacks-overview/)
- How to develop stacks: https://appsody.dev/docs/stacks/develop/

**Comment by sishida** [comment]
As of today, these are the descriptions that we have:
- Codewind Templates: Create containerized projects for various runtimes with Codewind project templates. Fully control the environment as part of your application.
- Appsody Incubator Templates: Build applications with preconfigured application stacks. Then, deploy and manage the applications in Kubernetes.
- Odo Templates: Develop your application with OpenShift templates and deploy to the OpenShift cluster.

**Comment by sishida** [comment]
Templates source manager descriptions should link out to source providers. I will look for suitable links.

**Comment by micgibso** [comment]
@sishida I propose to close this as it's not something we want to be working any more.

**Comment by sishida** [comment]
- To update Codewind templates: https://github.com/codewind-resources/codewind-templates/blob/master/devfiles/templates.json
