### ISSUE TITLE
Document 0.10.0 offline support for default codewind projects

### ISSUE THREAD

**Issue by sghung** [eclipse/codewind#2444]
In 0.10.0 we need to document the support that was added from https://github.com/eclipse/codewind/issues/2078

The default codewind projects supported are:
- Python
- Lagom
- Open Liberty

We need to add this into a new offline section.

Some things we should say:
- What projects are supported
- What scenario we support (i.e. the airplane mode)
- What limitations there are (e.g. can't pull in new dependencies, must have created and built before)

**Comment by sishida** [comment]
@micgibso Hi, Michael, Do we have a specific place in our docs where we'd like to add info about offline support? Right now it looks like we don't have any other issues open or have any other files to cover it. Thanks!

**Comment by micgibso** [comment]
@sishida Good spot, new topic in Developing projects would be a good starting point.

**Comment by sishida** [comment]
@sghung I have started a new file for offline Codewind: https://github.com/eclipse/codewind-docs/pull/467 I image there's more info we could add--could you please let me know in comments on the PR?

Also, how do we access the offline mode? Do we just try to access Codewind when we don't have an internet connection, and it functions as normally as it can? Or do we have to click something to activate the offline mode? Thanks!

**Comment by sishida** [comment]
PRs merged. Closing this issue.
