### ISSUE TITLE
SVT:Theia plugin stuck at "Starting" state if "Codewind" pod has start issues due to volume issues

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#2454]
**Codewind version:** 0.10.0
**OS:** CoreOS

**Che version:** 7.9.0
**IDE extension version:** 0.10.0
**IDE version:** Theia 7.9.0
**Kubernetes cluster:** OCP 4.3

**Description:**
I got into volume issues with the Codewind 0.10 (https://github.com/eclipse/codewind/issues/2441). With this issue Theia plugin is stuck at "Starting" state and did not change status to "Disconnected" state after multiple retries.

Here is more info from the cluster.

[theia.txt](https://github.com/eclipse/codewind/files/4317940/theia.txt)
![image](https://user-images.githubusercontent.com/713849/76412575-367bfd00-636a-11ea-8139-464c834d250d.png)

**Steps to reproduce:**

**Workaround:**

**Comment by tetchel** [comment]
https://github.com/eclipse/codewind-vscode/pull/499
