### ISSUE TITLE
SVT: [VS Code] Extension 'Codewind' failed to update workspace folders: Error: Unable to write into the file because the file is dirty. Please save the file and try again.

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#2460]
**Codewind version:** 0.10.0
**OS:** VM with Windows 10

**IDE extension version:** 0.10.0
**IDE version:** 1.42.0

Build date: 2020-03-11-17:30:50
build_info.url=https://download.eclipse.org/codewind/codewind-vscode/0.10.0/8
build_info.che.SHA-1=7aea24ceb7da2f8c4f1e933fc17e421bfb5446c5
build_info.SHA-1=2de69bbbec6b9823ea79fd0f01872ddd5ce1c326

**Description:** Extension 'Codewind' failed to update workspace folders: Error: Unable to write into the file because the file is dirty. Please save the file and try again.

<img width="1677" alt="Screen Shot 2020-03-11 at 3 41 25 PM" src="https://user-images.githubusercontent.com/49531960/76457317-f25f1b80-63ae-11ea-8a6c-9cf7c57b5cf4.png">

@jagraj

**Comment by tetchel** [comment]
does this happen every new project creation, or just sometimes?

**Comment by tetchel** [comment]
oh it might be a timing issue caused by the extension trying to write the debug configuration at the same time. i think i can fix this

**Comment by sujeilyfonseca** [comment]
It happens sometimes. I've seen the error multiple times, but I'm not sure what triggers it.

**Comment by sujeilyfonseca** [comment]
I've verified this issue with the latest Codewind 0.10.0, and I no longer reproduce the problem.
