### ISSUE TITLE
Mention Hybrid/Kube support in the VS Code tools readme 

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#2461]
We should add our kube support to the [VS Code tools readme](https://github.com/eclipse/codewind-vscode/blob/master/README.md) value propositions.

https://github.com/eclipse/codewind-vscode/pull/338 was the furthest we got previously, but it was closed. I also think we can make it sound a lot more exciting, since it is a great new feature.

Maybe @deboer-tim could help in writing a couple lines

**Comment by sishida** [comment]
I went ahead and re-created the PR for what we had previously: https://github.com/eclipse/codewind-vscode/pull/518

I'll bring this issue up during a meeting to discuss how we can make it sound more exciting.

**Comment by sishida** [comment]
Discussed the update with Tim D. and Rob T. Also got feedback from the Codewind team. Merged the PR and will close the issue.
