### ISSUE TITLE
SVT:IntelliJ:Logs console is not switching for a project that I requested and it stays for previous project all the time

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#2466]
**Codewind version:** 0.10.0
**OS:** Windows

**Che version:** 
**IDE extension version:** 0.10.0
**IDE version:** Intellij 2019-3.3
**Kubernetes cluster:**

**Description:**
I installed Codewind 0.10 from  Intellij plugin and I tried to access log files for  my projects and they are not switching from one project to another project. If I access "Project1" logs and then tried to access logs for "Project2" then we are not switching and displaying the log for "Project2" in the console.

![image](https://user-images.githubusercontent.com/713849/76527734-1457ad00-6446-11ea-881d-ed37d0daa70e.png)

![Screen Shot 2020-03-12 at 9 46 23 AM](https://user-images.githubusercontent.com/713849/76528769-b4620600-6447-11ea-83c1-8d715da5d541.png)
![Screen Shot 2020-03-12 at 9 46 57 AM](https://user-images.githubusercontent.com/713849/76528771-b4fa9c80-6447-11ea-8503-ac1d9c259db3.png)

Idea log:
[idea.log](https://github.com/eclipse/codewind/files/4324526/idea.log)

**Steps to reproduce:**
1. Install Codewind 0.10 from IntelliJ 2019-3.3
2. Create 3 or 4 projects.
3. Try to access logs from the Codewind view for various projects.
4. Logs window is not switching to  project that I requested. 

**Workaround:**

**Comment by keithchong** [comment]
I think this is because the log files are for a different IntelliJ project.  Enforcing the user to open the project into another window or current window should resolve this.

**Comment by naveenkaratekid** [comment]
I notice that issue too in IntelliJ. When I right click on the project and select ```Log files```, it doesn't show the logs. But when I click on the name of the project at the bottom left (highlighted in green), the option for seeing the log files for the other project show up. Then when I click on it, I am then able to see the logs.

![IntelliJ 0 10 0](https://user-images.githubusercontent.com/19738071/76536628-fb092d80-6452-11ea-8388-786b072c27e3.png)

**Comment by keithchong** [comment]
Hey @naveenkaratekid , initially, when you select "Show All" from the context menu of a project in the Codewind view, it appears like nothing happens, but actually, they are added.  There just isn't any feedback.  Yes, then if you select the combo box from the `Log Files` view, you will see them.

Similarly, bit not the exactly the same problem, if a log content changed, you won't get notified.  See https://github.com/eclipse/codewind/issues/2269

I think we should restrict users from showing logs for a project that isn't opened in the current IDE.  This will resolve the issue.

**Comment by keithchong** [comment]
Hi @jagraj , please verify in the latest 0.10.0 build.

**Comment by jagraj** [comment]
This issue has been fixed. Thanks for the fix.
