### ISSUE TITLE
Investigate accessing Codewind default projects via private registries

### ISSUE THREAD

**Issue by sghung** [eclipse/codewind#2469]
For each default codewind project, see how easy it is for its dependencies to be picked up from a or private server. For example, for express, see how we can use a private NPM (e.g. nexus) and a private docker. This will simulate a user who can only connect to internal systems and cannot access public docker, NPM, etc.

**Comment by makandre** [comment]
For using docker images from private registries, it should already be supported on Che/Hybrid scenarios (via #665 and #1178)

For local case, #1306 is needed for persisting credentials.  After that, I would imagine is simply a matter of making the same `Image Registry Manager` we have on Che/Hybrid available on local as well, so users can use it to save their credentials.

**Comment by makandre** [comment]
Using scoped npm packages from a private registry is not too difficult.  Assuming your `.npmrc` is already properly configured for it, we can use the `.cw-refpaths.json` mechanism to copy it into the project root, e.g.

```
{
    "refPaths": [
        {
            "from": "/Users/bob/.npmrc",
            "to": ".npmrc"
        }
    ]
}
```

For Appsody nodejs projects, the above is all you need.  For Codewind default project, you would need to tweak the `Dockerfile` to copy it to the docker build before `npm install` and remove it after, e.g.

```
COPY package.json .npmrc* /app/
RUN cd /app; npm install --production \
    && rm -rf .npmrc*
```

We could actually burn the `Dockerfile` changes right into the nodejs template; notice `*`  is used so the commands succeeds with or without the `.npmrc` file.  Opened #2488.

Aside from that we should probably doc or blog about this usage.

**Comment by makandre** [comment]
For Codewind Maven based projects, we can use the same approach of using the `.cw-refpaths.json` mechanism to copy the necessary configuration into the docker build.  The prereq would be:

- you have added the private repository url to the `pom.xml`
- you have the credentials configured the either the global or user `settings.xml` file

First we create a reference to the `settings.xml` file:

```
{
    "refPaths": [
        {
            "from": "/path_to/settings.xml",
            "to": "settings.xml"
        }
    ]
}
```

Then tweak to the `Dockerfile`, following is a modified section from the Open Liberty template:

```
COPY pom.xml settings.xml* ./
RUN mkdir -p /root/.m2 \
    && mv settings.xml* /root/.m2/ 2>/dev/null || true \
    && mvn dependency:go-offline package
COPY src src/
RUN mvn install -DskipTests --offline \
    && rm -rf /root/.m2/settings.xml*
```

This has been tested to work and again we can burn it right into the template.  We should be able to make similar changes to the other Maven based projects as well. 

This would not work for Appsody projects

**Comment by makandre** [comment]
PRs have been open for `Open Liberty` and `Lagom` projects.

For `Spring Boot` and `MicroProfile` projects, the maven build is done in a different way by scripts in Codewind, and not as part of the Docker build.  That said, the approach of referencing and copying the `settings.xml` file still works.  PRs:

- https://github.com/eclipse/codewind/pull/2525 for `Spring Boot` projects

**Comment by makandre** [comment]
### Summary

Following project types have changes made to their `Dockerfiles` in the template, allowing config files to be referenced and used during the build to fetch from private `npm/maven` registries:

- `Node.js Express` https://github.com/eclipse/codewind/issues/2488
- `Lagom` https://github.com/codewind-resources/lagomJavaTemplate/pull/3
- `Open Liberty` https://github.com/codewind-resources/openLibertyTemplate/pull/3

Following project types can also use the same approach, but the build is done by scripts in Turbine and changes are required there; these won't be reviewed in time for `0.11.0`:

- `Springboot` https://github.com/eclipse/codewind/pull/2525
- `Microprofile` https://github.com/eclipse/codewind/pull/2527

Additionally I looked into how `Go` and `Python` installs private packages.  Both seems to leverage installing the packages hosted on `git`-based repositories, such as GitHub or Gitlab, etc.  The problem with this is it typically requires the use of SSH; its support in docker is still experimental and it's not clear if this would also work with `buildah`.  I think at the moment `Go` and `Python` projects and private registry use is out of reach for Codewind.

**Comment by makandre** [comment]
Regarding documenting some of this stuff, I think this is probably another new topic under `Developing Projects` > `Using packages from private registries` perhaps?  I can get this started if it sounds right to you

@sishida

**Comment by sishida** [comment]
@makandre Thanks for pulling the docs team in on this! 😃 
1️⃣ In the title, if possible, I would prefer a more descriptive word instead of "Using". Maybe "Referencing"?

2️⃣ As for placement, "Developing Projects" sounds as good to me! However, I know @micgibso and @MelHopper have done a lot with the table of contents. Michael and Mel, are you OK with putting the new topic here?

**Comment by makandre** [comment]
@sishida I think it’s more than “referencing” since these are packages that would be downloaded when building the application; it’s code that the application depends on to run

**Comment by sishida** [comment]
OK, we can go with "Using" for now and just edit it later if anything better comes up. :)

**Comment by j-c-berger** [comment]
@sishida, please assign this issue to me as well, thanks!

**Comment by sishida** [comment]
Andrew is currently working on a blog. We can close this issue after the blog is complete.
