### ISSUE TITLE
SVT: IntelliJ: Highlight problem in Codewind Explorer when creating new project

### ISSUE THREAD

**Issue by naveenkaratekid** [eclipse/codewind#2475]
**Codewind version:** 0.10
**OS:**Windows

**IDE version:** IntelliJ 2019.3.3

**Description:**
The Codewind explorer does not seem to highlight when the user creates a new project. The Codewind tree doesn't show up when the user creates a project 

**Steps to reproduce:**
1. Create a new Codewind project of any template
2. When the Open Project wizard pops up, click ```This Window```.
![image](https://user-images.githubusercontent.com/19738071/76624650-15531200-650c-11ea-9767-e4ddbe1d06ea.png)

3. Once selected, the window refreshes. But the Codewind explorer does not show up. The user has to click it and then re-expand the list under the Codewind tree to see their project show up.

![image](https://user-images.githubusercontent.com/19738071/76624581-ef2d7200-650b-11ea-8cd3-88da67d63b89.png)

@jagraj

**Comment by sujeilyfonseca** [comment]
I consider this is a similar issue: https://github.com/eclipse/codewind/issues/2037

**Comment by sujeilyfonseca** [comment]
I verified and closed issue #2037. 

Now the Codewind view and tree are kept open after creating a new project. Thus, this issue can also be closed.
