### ISSUE TITLE
SVT: Load test can no longer run after canceling an unsuccessful load test request

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#2479]
**Codewind version:** 0.10.0
**OS:** VM with Windows 10, Mac OS Mojave 10.14.6, and Red Hat Enterprise Linux 7 (64 bit)

**Che version:** Che 7.5.1 & 7.9.0
**IDE extension version:** 0.10.0
**IDE version:** Code 1.42.0
**Kubernetes cluster:** OKD/OpenShift

**Description:** Load test can no longer run after canceling an unsuccessful load test request.

I was executing load tests on different types of projects. I got successful results in projects which supported the Performance Dashboard. However, after trying to run a load test on a project that is not supported now and/or the dashboard is stuck on "Requested", I no longer get results on any project after canceling the failed request. 

**_VS Code:_**

I successfully ran some load tests, but then I tested a load test with an Appsody Eclipse MicroProfile project. After that, all new requests get stuck on "Requested":

<img width="272" alt="Screen Shot 2020-03-13 at 10 57 57 AM" src="https://user-images.githubusercontent.com/49531960/76633837-bbf2df00-651b-11ea-9b61-42ca02373cb6.png">

Here is an example of a project that got results before getting into the issue:

<img width="1619" alt="Screen Shot 2020-03-13 at 10 57 53 AM" src="https://user-images.githubusercontent.com/49531960/76633862-c44b1a00-651b-11ea-8740-6ddea6829a40.png">

[vscode-codewind-performance.txt](https://github.com/eclipse/codewind/files/4330265/vscode-codewind-performance.txt)
[vscode-codewind-pfe.txt](https://github.com/eclipse/codewind/files/4330296/vscode-codewind-pfe.txt)

**_Eclipse Che:_**

I successfully ran the load tests, but then tested an unsuccessful load test. After that, all new requests get stuck on requested:

<img width="272" alt="Screen Shot 2020-03-13 at 10 57 57 AM" src="https://user-images.githubusercontent.com/49531960/76633918-dfb62500-651b-11ea-90ea-3a4a2ba27a78.png">

Here is an example of a project that got results before getting into the issue:

<img width="1488" alt="Screen Shot 2020-03-13 at 11 03 20 AM" src="https://user-images.githubusercontent.com/49531960/76633932-e6dd3300-651b-11ea-9620-0d82599319e2.png">

[che-codewind-performance-workspacesfkuxpsc871fv55d-76fb5546b9-r7dlf.txt](https://github.com/eclipse/codewind/files/4330264/che-codewind-performance-workspacesfkuxpsc871fv55d-76fb5546b9-r7dlf.txt)
[che-codewind-workspacesfkuxpsc871fv55d-55c7dbdddb-w6xkm.txt](https://github.com/eclipse/codewind/files/4330298/che-codewind-workspacesfkuxpsc871fv55d-55c7dbdddb-w6xkm.txt)

@jagraj

**Comment by sujeilyfonseca** [comment]
I can't reproduce the same scenario in our previous release (0.9.0). I tested VS Code and Eclipse Che, but I'm able to get load test results after running a load test that couldn't produce results.

**Comment by jagraj** [comment]
Looks like this is regression and we can not reproduce in 0.9.0 release. Marking this one as "stopship" for 0.10 release.

/priority stopship

**Comment by malincoln** [comment]
@tobespc pls assign.  Thanks

**Comment by malincoln** [comment]
expected fix to land UK EOD today.

**Comment by malincoln** [comment]
@tobespc @ebuckle just confirming the fix will land today (target day for all merged fixes)?

**Comment by sujeilyfonseca** [comment]
I tested this scenario with the latest images on local (VS Code) and cloud (Eclipse Che) scenarios. I still see the same behavior described in the issue.

I created some projects. Then, I successfully executed load tests with Default Spring and Node JS projects. After that, I tried a load test with an Appsody MicroProfile (the original issue mentions that project). The request failed and didn't cancel. Now, I can't longer run load tests.

<img width="412" alt="Screen Shot 2020-03-17 at 7 06 54 PM" src="https://user-images.githubusercontent.com/49531960/76912639-fd241f80-688a-11ea-9ec4-c75c17b8134a.png">

<img width="1328" alt="Screen Shot 2020-03-17 at 7 00 21 PM" src="https://user-images.githubusercontent.com/49531960/76912743-52603100-688b-11ea-85b7-6bbb3ce0a4ae.png">

<img width="1591" alt="Screen Shot 2020-03-17 at 7 01 56 PM" src="https://user-images.githubusercontent.com/49531960/76912755-61df7a00-688b-11ea-9e52-d637ff5d92ae.png">

Every new load test gets stuck in "Requested" and doesn't cancel. Furthermore, any opened windows (even when they belong to different projects) present the same "Cancelling" status:

<img width="272" alt="76633837-bbf2df00-651b-11ea-9b61-42ca02373cb6" src="https://user-images.githubusercontent.com/49531960/76913380-33fb3500-688d-11ea-8bf1-f675c5b8fb62.png">

<img width="1335" alt="Screen Shot 2020-03-17 at 7 12 38 PM" src="https://user-images.githubusercontent.com/49531960/76912853-b1be4100-688b-11ea-8f64-4d04dc06b160.png">

<img width="1311" alt="Screen Shot 2020-03-17 at 8 25 29 PM" src="https://user-images.githubusercontent.com/49531960/76913485-7d4b8480-688d-11ea-8609-02bb71f979bc.png">

[codewind-performance.txt](https://github.com/eclipse/codewind/files/4346340/codewind-performance.txt)

**Note:** This error may happen with other projects. Once you achieve a failure scenario, it will prevent you from using the Performance Dashboard for any project.

**Comment by jagraj** [comment]
With the latest images, I also tried this scenario along with Sujeily and I got into same problem.
Once we hit the problem with failed project (Appsody Node.js Express scaffold) and it always fails for other working projects. You can see here in the screen the spring project load test status goes into canceling state always.

<img width="1649" alt="image" src="https://user-images.githubusercontent.com/713849/76922680-d2948f80-68a7-11ea-83bf-7cdeeff3a3ca.png">

**Comment by sujeilyfonseca** [comment]
I can reproduce this problem using remote (VS Code):

<img width="623" alt="Screen Shot 2020-03-18 at 6 31 24 PM" src="https://user-images.githubusercontent.com/49531960/77013858-5baed380-6947-11ea-939c-a12b91e6bffe.png">

<img width="615" alt="Screen Shot 2020-03-18 at 6 36 26 PM" src="https://user-images.githubusercontent.com/49531960/77013871-649fa500-6947-11ea-8da2-511f8d617694.png">

**Comment by tobespc** [comment]
@ebuckle please look at this asap, thanks

**Comment by ebuckle** [comment]
Using these project types on the most recent 0.10.0 images I can't recreate his issue on remote.

Would it be possible to get the PFE logs for these failing load tests?

**Comment by sujeilyfonseca** [comment]
@ebuckle, here are the logs for remote:

[vscode-codewind-pfe.txt](https://github.com/eclipse/codewind/files/4354679/vscode-codewind-pfe.txt)
[vscode-remote-codewind-pfe.txt](https://github.com/eclipse/codewind/files/4354681/vscode-remote-codewind-pfe.txt)
[vscode-remote-codewind-performance.txt](https://github.com/eclipse/codewind/files/4354680/vscode-remote-codewind-performance.txt)

Let me know if you need any additional information.

**Comment by jopit** [comment]
My understanding of the fix for this is that the performance container will emit a periodic heartbeat status event on the UI socket.  The claim is that this should not affect the IDEs.  What does this event actually look like?

**Comment by ebuckle** [comment]
The events will look exactly the same as the current socket messages, they'll just be emitted in two second intervals instead of once.

So each of the current socket events ('starting', 'preparing', 'cancelling' etc) will remain completely unchanged.

**Comment by sujeilyfonseca** [comment]
@jagraj and I tested this issue with the latest Codewind 0.10.0, and we no longer reproduce the problem. Even if we get an unsuccessful load test request, we can create new requests with other projects.

**Comment by tobespc** [comment]
moving to verify as this has can no longer recreate, @sujeilyfonseca please close if you have completed your testing
