### ISSUE TITLE
Improve the Codewind-java-profiler README

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind#248]
The `codewind-java-profiler` repository README file could use an update: https://github.com/eclipse/codewind-java-profiler/blob/master/README.md

**Comment by micgibso** [comment]
Readme last updated 31 October 2019

**Comment by sishida** [comment]
I am closing this `Codewind-java-profiler` issue because we have this broader issue instead: https://github.com/eclipse/codewind/issues/2649
