### ISSUE TITLE
Option to generate csharp-netcore clients is missing from Codewind OpenAPI Tools for Visual Code

### ISSUE THREAD

**Issue by BinaryWizard904** [eclipse/codewind#2481]
**Affects:** [Codewind OpenAPI Tools for Visual Code](https://github.com/eclipse/codewind-vscode) version 0.9.0

The OpenAPI Generator underlying this extension supports generating a csharp-netcore client but the option is missing from the Codewind OpenAPI Tools for Visual Code extension.

This bug is caused by the omission of the option in the [codewind-openapi-vscode/dev/src/constants/Constants.ts](https://github.com/eclipse/codewind-openapi-vscode/blob/master/dev/src/constants/Constants.ts) file, line 154: `['C#', ['csharp', 'csharp-dotnet2', 'csharp-refactor']],`.  It seems that while the client was listed in the commented list of client generators earlier in that file, it was never actually added to code.

Replacing line 154 with `['C#', ['csharp', 'csharp-dotnet2', 'csharp-refactor', 'csharp-netcore']],` resolved the issue when I tested it on my install.

**Comment by ssh24** [comment]
Hi @BinaryWizard904 , thanks for the feature request! Since you already have found an enhancement solution for it, could you please open a PR and have it reviewed by us? Thank you for using codewind!

/area openapi
/kind bug

**Comment by keithchong** [comment]
Hi @BinaryWizard904 , thanks for reporting this.  I know that the static list can get outdated.  However, we will try to update it when we update the generator version.  Ideally, the quick pick list should be provided dynamically.  The Eclipse version needs to be updated too:

[org.eclipse.codewind.openapi.ui/src/org/eclipse/codewind/openapi/ui/Constants.java](https://github.com/eclipse/codewind-openapi-eclipse/blob/98e1317a868a72b288c87422fb01c32a0ef0e845/dev/org.eclipse.codewind.openapi.ui/src/org/eclipse/codewind/openapi/ui/Constants.java#L53)

**Comment by BinaryWizard904** [comment]
Amended the commits in my push requests to include the missing sign-offs.  First time working with Eclipse projects and I somehow managed to miss that requirement.

**Comment by keithchong** [comment]
Thanks @BinaryWizard904 for updating the Eclipse plugin too.  I'll have a look at the PRs.

**Comment by keithchong** [comment]
Both PRs have been merged to master.

**Comment by keithchong** [comment]
Hi @BinaryWizard904 , thanks again for providing both PRs and quickly setting up the Eclipse environment to provide the change.  Curious, are you open to collaborating/contributing?  For example, we can move forward with the VS Code extension and Eclipse plugin further and provide enhancements and bug fixes.  One of the more trivial things we have to do each release is bump up the version number.  Let me know if you are interested in contributing.  Perhaps you can eventually become a commiter.  See the second step describing the committer election process from https://waynebeaton.wordpress.com/2018/02/08/the-eclipse-committer-election-workflow/
