### ISSUE TITLE
Containers are brought down when making a source change for Project Extensions

### ISSUE THREAD

**Issue by keithchong** [eclipse/codewind#249]
**Codewind version:** latest
**OS:** Mac OS

**IDE extension version:** Eclipse latest
**IDE version:** 2019.06

**Description:** See https://github.com/eclipse/codewind-appsody-extension/issues/12
Found this out testing extension projects running in debug mode.  @sghung found out when testing it in normal run mode.

**Workaround:** 
No reasonable workaround is available.  Must fix.

**Comment by makandre** [comment]
I'll take this one

**Comment by makandre** [comment]
This was cased by https://github.com/eclipse/codewind-appsody-extension/pull/6
