### ISSUE TITLE
Include intellij on gettingstarted graphic for 0.10

### ISSUE THREAD

**Issue by AndyRWatson** [eclipse/codewind#2503]
**Codewind version:** 0.9
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**

The getting started pages on codewind.dev https://www.eclipse.org/codewind/gettingstarted.html shows intelliJ alongside vscode/eclipse/che in the sidebar but there is no icon/graphic in the "Select your IDE to continue" frame.

Propose adding an intelliJ selection in the "select your ide to continue" frame/list to be consistant for 0.10

**Steps to reproduce:**

**Workaround:**

**Comment by sishida** [comment]
- Tagging designers @kimholmes and @thisguy-1.
- Also tagging @jopit and @sghung for awareness.

**Comment by kimholmes** [comment]
I think we can certainly add a graphic in the interim, but this page will soon be replaced with the work happening here:
https://github.com/eclipse/codewind/issues/2041

**Comment by keithchong** [comment]
Note that the Codewind for IntelliJ extension has help links to:

https://www.eclipse.org/codewind/mdt-intellij-getting-started.html

If you want it to be changed to 

https://www.eclipse.org/codewind/gettingstarted.html 

it will require a code change to the extension for 0.10.0.

**Comment by AndyRWatson** [comment]
Thanks @kimholmes that will be fine and understand there will be replaced at some point

**Comment by AndyRWatson** [comment]
@keithchong  is that not fixed via work related to https://github.com/eclipse/codewind/issues/2372 ?

**Comment by AndyRWatson** [comment]
@keithchong i think plugin going direct to IntelliJ link is fine ?

**Comment by keithchong** [comment]
@AndyRWatson, yes, it's fine. No URLs should change.

**Comment by sghung** [comment]
@kimholmes any update on the graphic? If one is available, can we attach it here?

**Comment by MelHopper** [comment]
This issue has been fixed in 0.12.0 by reworking the Getting Started page.
