### ISSUE TITLE
Old screen captures in Eclipse creating your first project page

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#2504]
This page: https://www.eclipse.org/codewind/mdt-eclipse-firstproject.html contains some old screen captures where the table background is white. This bug was fixed so the screen captures should be updated.

**Comment by jopit** [comment]
Here's the updated screen capture for `2. Creating a new project displays the project creation screen.`

<img width="688" alt="Screen Shot 2020-03-17 at 3 32 34 PM" src="https://user-images.githubusercontent.com/29612372/76894752-1ade8e00-6865-11ea-93ed-6fe80c538360.png">

**Comment by jopit** [comment]
Here's the updated screen capture for `3. Enter a name for the project and change the location if you want. Scroll through the list of templates until you see Node.js Express.`

<img width="659" alt="Screen Shot 2020-03-17 at 3 34 49 PM" src="https://user-images.githubusercontent.com/29612372/76894875-58dbb200-6865-11ea-84c4-31268e775602.png">
