### ISSUE TITLE
SVT: [Che] Node JS projects are failing to build

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#2513]
**Codewind version:** 0.10.0
**OS:** Red Hat Enterprise Linux 7 (64 bit)

**Che version:** 7.9.0
**Kubernetes cluster:** Fyre Cluster with OCP 4.3

**Description:** Node JS projects are failing to build

<img width="1637" alt="Screen Shot 2020-03-18 at 11 07 03 AM" src="https://user-images.githubusercontent.com/49531960/76975217-a1987700-6908-11ea-9d0a-a4de4b079db9.png">

```
STEP 4: COPY package.json .npmrc* /app/
error building at STEP "COPY package.json .npmrc* /app/": no files found matching "/codewind-workspace/cw-default-node/.npmrc*": no such file or directory
```

**Stepts to reproduce:**
1. Create a Fyre cluster with OCP 4.3
2. Install Che 
3. Deploy a new Codewind workspace (0.10.0)
4. Create Node JS projects

**Logs:**
[cw-default-node.txt](https://github.com/eclipse/codewind/files/4349680/cw-default-node.txt)
[cw-default-node-p2.txt](https://github.com/eclipse/codewind/files/4349682/cw-default-node-p2.txt)
[cw-default-node-p3.txt](https://github.com/eclipse/codewind/files/4349683/cw-default-node-p3.txt)

@jagraj

**Comment by johnmcollier** [comment]
@makandre This looks to be related to the template changes you made in https://github.com/codewind-resources/nodeExpressTemplate, can you take a look?

**Comment by johnmcollier** [comment]
Also marking as stopship since one of our core templates is broken on Kube

**Comment by makandre** [comment]
I will revert my change with https://github.com/codewind-resources/nodeExpressTemplate/pull/7  @johnmcollier could you review and merge?

**Comment by johnmcollier** [comment]
@makandre Merged.

@sujeilyfonseca Can you verify? Thanks!

**Comment by sujeilyfonseca** [comment]
Thanks for working to solve this issue, @makandre and @johnmcollier!

I've verified this issue with the latest Codewind 0.10.0, and I no longer reproduce the problem.

<img width="1411" alt="Screen Shot 2020-03-18 at 12 46 13 PM" src="https://user-images.githubusercontent.com/49531960/76985453-9e0bec80-6916-11ea-9336-e08e86ded6a2.png">

**Comment by malincoln** [comment]
Thanks @makandre @johnmcollier for quick turnaround on the fix!!!
