### ISSUE TITLE
SVT:Che:User has to hide project logs to see the logs again if they already open with "Show logs" option for all projects

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#2517]
**Codewind version:** 0.9.0 and 0.10.0
**OS:**

**Che version:**  7.5.1 and 7.9.0
**IDE extension version:**  Codewind 0.9 and Codewind 0.10.0
**IDE version:**  7.5.1 and 7.9.0
**Kubernetes cluster:** OKD 4.3

**Description:**
Once we click on option "Show all logs" for all the projects in the workspace and we can not see the logs for the same project. User has to click on "Hide all logs" and then click on "Show all logs" to get to the logs. 

You can see all logs browsed once in the screenshot below.
![image](https://user-images.githubusercontent.com/713849/77002444-e71d6a00-6931-11ea-95e5-0e55e839d6d4.png)

 User has to click on "Hide all logs" for specific project to see the logs again.
![image](https://user-images.githubusercontent.com/713849/77002640-3499d700-6932-11ea-9e39-6d7f739b7176.png)

**Steps to reproduce:**
1. Install Codewind 0.9 or 0.10.0 on Eclipse Che.
2. Create few projects from the templates.
3. Browse all the logs with "Show all logs" option for all projects.
4. Highlight one of the project in the workspace again and click "Show all logs"
5. At this point you can not get to the logs. User has to manually select logs from "Output"  window logs list.

**Workaround:**

**Comment by tetchel** [comment]
how is this different from #2514, which apparently was not reproducible on 0.9 (but this one is?)

**Comment by jagraj** [comment]
Looks like this problem exist in CW 0.9.0 with Theia 7.5.1 release. Issue #2514 is different problem where logs are not displaying automatically in the "Output" view. This issue displays all the logs for all projects in the workspace once. If I want to view logs again for the same project then I have to click on "Hide all logs" and then click on "Show all logs"

**Comment by tetchel** [comment]
Sorry, I still don't understand the difference. The logs are displaying in both issues, they are just not toggling to become the active log, right?

**Comment by jagraj** [comment]
Once che issue is resolved for issue #2514 should address this problem as well. I verified CW 0.10.0 on Che 7.5.1 and I do not see this problem.
