### ISSUE TITLE
Incorrectly formatted message in vscode plugin

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#2518]
**Codewind version:**
latest
**OS:**
mac

**Che version:**
**IDE extension version:**
**IDE version:**
latest
**Kubernetes cluster:**

**Description:**
Stopping and starting my local connection from within vscode showed the following message
![Screenshot 2020-03-19 at 11 13 17](https://user-images.githubusercontent.com/13151286/77061917-ed175780-69d2-11ea-9730-cff562a90813.png)

Strange ```[1B``` characters at start of message

**Comment by tetchel** [comment]
I think it's a terminal colour reset character, since the text just before that line is green.

![image](https://user-images.githubusercontent.com/8888438/77078280-be967e00-69cc-11ea-8d32-ec1aefc1718a.png)

I guess I can try and find-and-replace it out.
