### ISSUE TITLE
Jenkins builds always use master cwctl regardless of branch.

### ISSUE THREAD

**Issue by hhellyer** [eclipse/codewind#2523]
**Codewind version:**
N/A - This is an issue to do with mixing versions.
**OS:**
Jenkins build image.

**Description:**
When we start cwctl in the Jenkins builds we use cwctl. However we always pull cwctl from master. This is a problem as e.g. 0.10.0 builds are using the master build and required an extra setting to avoid using the system keychain which isn't available in our Jenkins image.

Various places in the Jenkins file look at the branch, we need to make sure the right branch name is in the `$CW_CLI_BRANCH` before we call start.sh so that `cli_pull.sh` pulls the right version of cwctl.

**Workaround:** 
We have merged the same fix we made on master to use the insecure keyring feature:
https://github.com/eclipse/codewind/pull/2522
so that 0.10.0 can build.

From the 0.10.0 build logs:
```
00:49:03.131  Downloading latest Codewind CLI built from master for platforms: linux
00:49:03.131  Downloading https://download.eclipse.org/codewind/codewind-installer/master/latest/build_info.properties
00:49:03.509  Latest cli master build is https://download.eclipse.org/codewind/codewind-installer/master/66
00:49:03.509  Downloading https://download.eclipse.org/codewind/codewind-installer/master/latest/cwctl-linux
00:49:05.888  renamed 'cwctl-linux' -> 'linux/cwctl'
00:49:05.888  Successfully pulled Codewind CLI for linux
00:49:05.888  /home/genie.codewind/jenkins-agent/workspace/Codewind_codewind_0.10.0
00:49:05.888  Setting image tag to test
```

**Comment by tetchel** [comment]
Here is the logic in the VS Code plugin which checks if there's a matching cwctl version for the current build branch, and downloads it if it exists.

https://github.com/eclipse/codewind-vscode/blob/0.10.0/Jenkinsfile#L48

**Comment by malincoln** [comment]
@hhellyer @tobespc is this on track for 0.11.0?

**Comment by jagraj** [comment]
With the latest Codewind 0.10 builds we have been testing cwctl implicitly. Once we are done with the Codewind 0.10 release and then we will verify Codewind 0.11 fix.

**Comment by hhellyer** [comment]
I've looked at the latest 0.11.0 build, this was branched from master and didn't have the fix checked into it directly. It is correctly pulling the 0.11.0 cwctl to launch codewind for API testing so this can be closed.
```
00:16:40.387  Creating codewind-workspace
00:16:40.387  PFE Image: 324debb0079f
00:16:40.387  cwctl branch to be used: 0.11.0
00:16:40.387  
00:16:40.387  
00:16:40.387  [0;36mRunning 'start.sh' to start codewind. [0m
00:16:40.387  
00:16:40.387  
00:16:40.387  [0;36mCREATING CODEWIND-WORKSPACE IF IT DOESN'T EXIST[0m
00:16:40.387  
00:16:40.387  [0;32mDownloading cwctl to start Codewind containers [0m
00:16:40.387  [1;33mSet CW_CLI_BRANCH={branch} to override the branch used to pull cwctl [0m
00:16:40.736  /home/genie.codewind/jenkins-agent/workspace/Codewind_codewind_0.11.0/start.sh: 41: [: Linux: unexpected operator
00:16:40.736  /home/genie.codewind/jenkins-agent/workspace/Codewind_codewind_0.11.0/start.sh: 49: [: x86_64: unexpected operator
00:16:40.736  Else condition hit, only downloading Linux CWCTL
00:16:40.736  
00:16:40.736  Downloading latest Codewind CLI built from 0.11.0 for platforms: linux
00:16:40.736  Downloading https://download.eclipse.org/codewind/codewind-installer/0.11.0/latest/build_info.properties
00:16:40.736  Latest cli 0.11.0 build is https://download.eclipse.org/codewind/codewind-installer/0.11.0/1
00:16:40.736  Downloading https://download.eclipse.org/codewind/codewind-installer/0.11.0/latest/cwctl-linux
00:16:43.087  renamed 'cwctl-linux' -> 'linux/cwctl'
00:16:43.087  Successfully pulled Codewind CLI for linux
00:16:43.087  /home/genie.codewind/jenkins-agent/workspace/Codewind_codewind_0.11.0
00:16:43.087  Setting image tag to test
```
