### ISSUE TITLE
[IntelliJ] Finalize icons for Debugger tab

### ISSUE THREAD

**Issue by keithchong** [eclipse/codewind#2530]
Child enhancement to:

https://github.com/eclipse/codewind/issues/990

Here is where the icons will appear.  The current language-based icon indicators are 16x16 but typically, for toolwindow tabs, they are 13x13.

<img width="449" alt="Screen Shot 2020-03-20 at 4 32 03 PM" src="https://user-images.githubusercontent.com/7726022/77204229-ae63c900-6ac8-11ea-878d-6efa59a78934.png">

<img width="296" alt="Screen Shot 2020-03-20 at 4 31 18 PM" src="https://user-images.githubusercontent.com/7726022/77204350-eff47400-6ac8-11ea-8164-4ce5253f4655.png">

Note the decorator/overlay green circle 'icon' that represents the process is running.  Here it is when the process has terminated

<img width="472" alt="Screen Shot 2020-03-20 at 4 38 23 PM" src="https://user-images.githubusercontent.com/7726022/77204611-7b6e0500-6ac9-11ea-9200-90fd91dceb26.png">

Compare with 13x13 codewind icon:

<img width="432" alt="Screen Shot 2020-03-20 at 4 18 25 PM" src="https://user-images.githubusercontent.com/7726022/77204443-1b775e80-6ac9-11ea-9a08-54bf91905c0c.png">

Another option would be to have a 'bug' icon instead regardless of the project type

Considerations: the green circle overlay will be added by the platform.

**Comment by keithchong** [comment]
We can only use one icon, regardless of the project type.  The launch config template has the same template as the instance.  And it's only defined in the configuration type.  There is no way to override it dynamically.  We can use the existing icon for Remote Debug.

<img width="770" alt="Screen Shot 2020-03-20 at 8 09 05 PM" src="https://user-images.githubusercontent.com/7726022/77214856-6902c400-6ae7-11ea-9aa7-d5e064c70e30.png">

<img width="665" alt="Screen Shot 2020-03-20 at 7 57 32 PM" src="https://user-images.githubusercontent.com/7726022/77214861-70c26880-6ae7-11ea-89ab-5b1036d1adf3.png">

**Comment by thisguy-1** [comment]
> We can only use one icon, regardless of the project type. The launch config template has the same icon as the instance. And it's only defined in the configuration type. There is no way to override it dynamically. We can use the existing icon for Remote Debug instead of the Codewind icon.
> 
> <img alt="Screen Shot 2020-03-20 at 8 09 05 PM" width="770" src="https://user-images.githubusercontent.com/7726022/77214856-6902c400-6ae7-11ea-9aa7-d5e064c70e30.png">
> 
> <img alt="Screen Shot 2020-03-20 at 7 57 32 PM" width="665" src="https://user-images.githubusercontent.com/7726022/77214861-70c26880-6ae7-11ea-89ab-5b1036d1adf3.png">

I would just stick with the codewind logo as an icon. It already says "debug:".

**Comment by keithchong** [comment]
Thanks @thisguy-1 for your comments and feedback.  This change is included in https://github.com/eclipse/codewind-intellij/pull/91

Closing.
