### ISSUE TITLE
Error during install of codewind 0.9.0 on VSCode

### ISSUE THREAD

**Issue by balajikadambi** [eclipse/codewind#2532]
**Codewind version:**  0.9.0
**OS:**  Mac

**Che version:** Visual Studio
**IDE extension version:** 1.43.1

**IDE version:**
**Kubernetes cluster:**

**Description:**
I had an earlier version of Visual Studio and Code wind on Mac. I had uninstalled it. I tried to install the latest version of VisualStudio and codewind 0.9.0.
When I tried to start codewind, it said that the current version is 0.5.0(not sure why) and has to be updated to 0.9.0.
When I chose to update, it gave an error:
Please wait whilst images are removed... 
.FileNotFoundError: [Errno 2] No such file or directory: '/Users/**/.codewind/docker-compose.yaml'

**Steps to reproduce:**
Described above.

**Workaround:** 

No.

**Comment by tetchel** [comment]
hi, you can work around this by removing the old codewind images by hand.

the images are `eclipse/codewind-performance-amd64` and `eclipse/codewind-pfe-amd64` and will have the `0.5.0` tag.

So you can remove them with this command:
`docker rmi $(docker images | grep eclipse/codewind | awk '{ print $3 }')`

**Comment by balajikadambi** [comment]
@tetchel thanks. that error is sorted now. I am getting another error now when I try to start codewind:
==> Run cwctl --json start -t 0.9.0
Debug: false
==> created file /Users/**/.codewind/0.9.0/Users/**/.codewind/docker-compose.yaml
==> environment structure written to /Users/**/.codewind/docker-compose.yaml
System architecture is:  amd64
Host operating system is:  darwin
Attempting to find available port
Port 10000 Available
{"error":"DOCKER_COMPOSE_START_ERROR","error_description":"exec: \"docker-compose\": executable file not found in $PATH"}
Would you know the cause here?

**Comment by tetchel** [comment]
I think it is the same issue seen here https://github.com/eclipse/codewind/issues/1682 where `docker` is not on the path VS Code is using. 

Can you try following [these steps](https://github.com/eclipse/codewind/issues/1682#issuecomment-572649328) from that issue?

**Comment by tetchel** [comment]
hi @balajikadambi did you get it working?

**Comment by balajikadambi** [comment]
@tetchel I have not been able to try it out. I will try and revert back to you by tomorrow. thanks for your prompt response and follow up.

**Comment by balajikadambi** [comment]
@tetchel I finally got it working :)   Thanks for your help here.

I followed all the steps and started VSCode from the terminal. I got a new error:
=========
Please wait while containers initialize...  
Network "codewind_network" needs to be recreated - option "com.docker.network.bridge.host_binding_ipv4" has changed
{"error":"DOCKER_COMPOSE_START_ERROR","error_description":"exit status 1"}
=========

I removed the codewind_network and tried again. Then I got the below error:
Continue with the new image? [yN]no such image: sha256:09ac0adfa6b5e7b31801fa687fe3fa591a82584c8fda330b55b434508cad3d01: No such image: sha256:09ac0adfa6b5e7b31801fa687fe3fa591a82584c8fda330b55b434508cad3d01
{"error":"DOCKER_COMPOSE_START_ERROR","error_description":"exit status 1"}
==> End cwctl --json start -t 0.9.0

I followed the instructions(docker reset part) at https://github.com/eclipse/codewind-installer/issues/35. Then reinstalled codewind with images again. 
It worked!
