### ISSUE TITLE
cwctl registrysecrets list doesn't work for remote connections

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#2535]
```
[ /programs/codewind-vscode/dev ] 55 (cwctlRegistries) $ cwctl registrysecrets list --conid K7W26PN8
ERRO[0001] {"error":"tx_failed","error_description":"No other methods left to try"} 
```

**Comment by tetchel** [comment]
@eharris369 reported seeing the same problem, so while Eclipse is using `registrysecrets` it is using it only for the local connection (https://github.com/eclipse/codewind-eclipse/pull/625)

**Comment by jcockbain** [comment]
`--insecure` flag? I just tried it with an openshift connection and it returned the expected list.

**Comment by tetchel** [comment]
oh yeah, it worked. that error message is pretty unhelpful though

**Comment by jcockbain** [comment]
Yeah agreed, the one I got was the one that should be returned. Can leave the issue open to investigate?

**Comment by tetchel** [comment]
https://github.com/eclipse/codewind/issues/2536
