### ISSUE TITLE
Add a new command to the codewind cli to set/get url of codewind server

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#254]
As part of the work to let the cli communicate with the codewind server, the cli will need to know the url of where the codewind server is running.   Would like to have getters and setters on the cli for the location of the codewind server

**Comment by markcor11** [comment]
I have a branch working with a new deployments command:

```
USAGE:
   Codewind Installer deployments command [command options] [arguments...]

COMMANDS:
   add, a      Add a new deployment to the list
   remove, rm  Remove a deployment from the list
   target, t   Show/Change the current target deployment
   list, ls    List known deployments
   reset       Resets the deployments list
```

**Comment by tobespc** [comment]
this is done and delivered
