### ISSUE TITLE
Appsody node-express stack unable to show performance dashboard

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#2548]
Creating an Appsody Node.js simple Express project from within Codewind will correctly setup a link to the performance dashboard.

However, if you create the same stack using 
```appsody init nodejs-express``` 
and then import that project, the dashboard link is not set correctly.

Looking at the project.inf files for both projects, I can see that for the one created in codewind we have this set for "metricsDashboard"
```
    "hosting": "project",
    "path": "/appmetrics-dash/?theme=dark"
```
but for the one created by appsody that we import, we have this  
```
    "hosting": null,
    "path": null
```

**Codewind version:**
0.10.0 and latest

**Comment by makandre** [comment]
For create, the language is `nodejs` and `isMetricsAvailable` returns `true` here:

https://github.com/eclipse/codewind/blob/master/src/pfe/portal/modules/Project.js#L204

But for import, the language is `javascript` so it doesn't return `true`
