### ISSUE TITLE
Doc for private registries 

### ISSUE THREAD

**Issue by j-c-berger** [eclipse/codewind#2550]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description of the enhancement:**
Create a new doc since the scenario uses private registries 

**Proposed solution:** 
See the current doc, ```offline-codewind.md``` for help getting started

**Comment by makandre** [comment]
Is this meant for https://github.com/eclipse/codewind/issues/2469?

I have a draft started for that https://github.com/eclipse/codewind-docs/pull/501

**Comment by j-c-berger** [comment]
@makandre, this issue was made so ID has an issue to work on for Epic #1991  

does #2469 pertain to 1991 as well? If so, yes we can use your draft.

**Comment by makandre** [comment]
Ah I see.

#2469 is somewhat related.  In some organizations the user may not have access to the Internet, or otherwise restricted from accessing public registries.  And in that case they likely would have some internal private registry setup which they would use instead.

**Comment by j-c-berger** [comment]
Since what you've made is for offline support, yes, let's bring your existing doc to this issue. I'll see what you have and make a PR for this issue or #2469 soon. 

Thanks for jumping in with the good suggestion!

**Comment by j-c-berger** [comment]
Closing because this issue was resolved with PR [#506](https://github.com/eclipse/codewind-docs/pull/506)
