### ISSUE TITLE
No documentation on how to update version of a remote codewind install

### ISSUE THREAD

**Issue by AndyRWatson** [eclipse/codewind#2556]
**Codewind version:**  0.x
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**

I am currently running codewind 0.8 on my Openshift cluster running on IBM Cloud and want to move to the latest version. On our landing page we do not document the steps required to update a remote codewind once a newer release is available

**Steps to reproduce:**
 

**Workaround:**

**Comment by tetchel** [comment]
I agree we should doc this but there is no 'upgrade' path available in cwctl / the operator right now. You have to delete the old instance and create a new one

**Comment by micgibso** [comment]
Upgrade path will be covered when I've finished documenting the new remote operator on https://github.com/eclipse/codewind-docs/pull/502.

**Comment by micgibso** [comment]
Discussed with Mark Cornaia earlier this week, no technical path yet, tbc.

**Comment by micgibso** [comment]
Discussed with @markcor11, decision has been taken that for upgrades, you must delete your current deployments and set up new ones. For more information, see `Any special notes for your reviewer` on PR https://github.com/eclipse/codewind-operator/pull/56.
