### ISSUE TITLE
Codewind remote install docs needs to be fixed

### ISSUE THREAD

**Issue by maysunfaisal** [eclipse/codewind#2567]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**
If you follow the instructions on https://www.eclipse.org/codewind/remotedeploy-combo.html

Codewind-installer times out and the Codewind pod never comes up!

```
INFO[0057] Adding 'codewind-tekton-rolebinding-k8endiu2' role binding 
INFO[0058] Creating and setting Codewind PVC codewind-pfe-pvc-k8endiu2 to 1Gi  
INFO[0058] Deploying Codewind Service                   
INFO[0058] Waiting for pod: codewind-pfe-k8endiu2       
WARN[0088] Watch for Pod codewind-pfe-k8endiu2 ended. Timeout or connection error. 
INFO[0088] Waiting for pod: codewind-pfe-k8endiu2       
WARN[0119] Watch for Pod codewind-pfe-k8endiu2 ended. Timeout or connection error. 
INFO[0119] Waiting for pod: codewind-pfe-k8endiu2       
WARN[0149] Watch for Pod codewind-pfe-k8endiu2 ended. Timeout or connection error. 
INFO[0149] Waiting for pod: codewind-pfe-k8endiu2       
WARN[0179] Watch for Pod codewind-pfe-k8endiu2 ended. Timeout or connection error. 
```

You need to add
```
oc adm policy add-scc-to-group privileged system:serviceaccounts:<Codewind-namespace>
oc adm policy add-scc-to-group anyuid system:serviceaccounts:<Codewind-namespace>
```

which is described in the other link https://www.eclipse.org/codewind/remotedeploy-single.html|

This needs to be fixed on the current version(0.9.0) and next version (0.10.0)

Marking this as stopship. Please do not remove stopship until addressed.

/area portal
/area docs

**Comment by tetchel** [comment]
yeah, this wasn't fixed with https://github.com/eclipse/codewind/issues/2320

**Comment by malincoln** [comment]
@maysunfaisal pls verify and close. Thanks

**Comment by sishida** [comment]
The documentation for deploying Codewind remotely has changed significantly. The `remotedeploy-combo.md` file has been replaced. See this PR for changes: https://github.com/eclipse/codewind-docs/pull/517. Closing this issue.
