### ISSUE TITLE
Need to document how to create own templates

### ISSUE THREAD

**Issue by AndyRWatson** [eclipse/codewind#2570]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**
Our landing page document still does not document how a user creates/modifies their own templates.  We document how to point to your own template repo (via template source repo) but provide no guidance on the steps required to create your own repo or more importantly how to create your own new templates within that repo.  

we have previous issues which have been closed

https://github.com/eclipse/codewind/issues/559
https://github.com/eclipse/codewind/issues/713 (dupe)

We should look to document 

- cloning the https://github.com/Codewind-resources repo (so you can edit/modify the samples. a user will not be able to modify our samples at https://github.com/codewind-resources)
- the repo structure and the files that need to exist and can be updated
- how to create a new template (all files require) and add it to your own repo list

A good example is how the appsody project document their stack creation,  we should ensure that codewind documentation covers the same for our own template format. We should also probably  refer to the appsody pages for users wishing to use appsody stack formats. https://appsody.dev/docs/stacks/stacks-overview

**Steps to reproduce:**

**Workaround:**

**Comment by sishida** [comment]
Looks like we currently have this file for templates: https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/workingwithtemplates.md

**Comment by sishida** [comment]
- Template sources adds GitHub repo that contains an existing set of templates, one or many.
- Each template consists of two parts: entry in the template source repo (an index of templates) and typically its own Git repository as well. 
- Our template source: https://github.com/codewind-resources/codewind-templates
- Links to actual templates: https://github.com/codewind-resources/codewind-templates/tree/master/devfiles. Each template file contains a devfile and meta file like Che templates so we can use templates in Che.
   - https://github.com/codewind-resources/codewind-templates/blob/master/devfiles/goTemplate/devfile.yaml
   - Che understands the metadata file as well.
- This json file is generated from templates and contains link to repo that we clone if you choose a template: https://github.com/codewind-resources/codewind-templates/blob/master/devfiles/index.json. Codewind uses this data.

**Comment by sishida** [comment]
PRs merged.
