### ISSUE TITLE
[IDE] [Remote debug] Write correct debug configuration (e.g. in launch.json)

### ISSUE THREAD

**Issue by rwalle61** [eclipse/codewind#2573]
**Codewind version:** 0.11
**OS:**

**Description of the enhancement:**

In https://github.com/eclipse/codewind/issues/1990, the user wants to debug their remote project. When they click "Restart in Debug Mode" or "Attach debugger", we need to have the correct VSCode `launch.json` configuration (or equivalent in other IDEs). The configuration we need to debug local projects is different to the config we need to debug remote projects.

Config needed to debug local node projects:
```
{
            "type": "node",
            "name": "Debug node2",
            "request": "attach",
            "address": "127.0.0.1",
            "localRoot": "/Users/richard.waller@ibm.com/codewind-workspace/node2",
            "remoteRoot": "/app",
            "restart": true
        },
```

Config needed to debug remote node projects:
```
{
            "type": "node",
            "name": "Debug node2",
            "request": "attach",
            "port": "XXXX",
            "localRoot": "/Users/richard.waller@ibm.com/codewind-workspace/node2",
            "remoteRoot": "/app",
            "restart": true
        },
```

Where XXXX is whichever port `cwctl` forwards the container's internal debug port to - see https://github.com/eclipse/codewind-installer/pull/415.

**Proposed solution:** 

Currently, the code in the IDEs that generates debug configs executes the same logic for local and remote projects. E.g. it generates this for remote node projects:
```
{
            "type": "node",
            "name": "Debug node2",
            "request": "attach",
            "address": "codewind-gatekeeper-k67tomz3.apps.exact-mongrel-icp-mst.9.20.195.90.nip.io",
            "localRoot": "/Users/richard.waller@ibm.com/codewind-workspace/node2",
            "remoteRoot": "/app",
            "restart": true
        },
```

We should change the IDE code to generate different config for local or remote projects

How would the IDEs know which port `cwctl` forwards the container's internal debug port to? Options:
1. IDEs ask `cwctl` to find and use an available port, and return to the IDEs which port it used
2. IDEs tell `cwctl` which port to use. If that port is already occupied, `cwctl` finds and uses an available port, and returns to the IDEs which port it used
3. IDEs tell `cwctl` which port to use. If that port is already occupied, then `cwctl` returns an error. The IDEs can then try a different port
4. IDEs ask `cwctl` which ports are available, then tells `cwctl` which port to use

My preference is 3 because then we can ask the user which port they would like to use, so they are in control and aware of which port we are using. When asking them which port to use, we could also do 4 and show them what ports are available, saving them from picking one that clashes

**Comment by jopit** [comment]
My preference is for option 1.  I don't believe we should put the burden of choosing a port on the user.
@eharris369 @tetchel what do you think?

**Comment by hhellyer** [comment]
I'd vote 1. Port numbers aren't particularly interesting to the end user. This is something we can handle automatically and not a particularly useful choice.

**Comment by rwalle61** [comment]
so @jcockbain will make `cwctl` work for option 1, and could the IDE code-owners connect with that when it's ready please

**Comment by jcockbain** [comment]
My installer PR should now port-forward to a local port that's available. https://github.com/eclipse/codewind-installer/pull/415

**Comment by jopit** [comment]
The https://github.com/eclipse/codewind-installer/pull/415 PR adds a new command `cwctl project port-forward` -- is the expected flow that the IDEs call (paraphrased) 'cwctl restart debug' followed by 'cwctl project port-forward <internal-port>', and the json output of the port-forward command contains the local port to use?  What's the exact format of the returned json?

**Comment by jopit** [comment]
And what was wrong with doing the port-forward as part of the restart, as was originally proposed: https://github.com/eclipse/codewind/issues/1990#issuecomment-600529181

**Comment by eharris369** [comment]
If the port is returned in the restart result then the IDEs would need a way to get it again if they were restarted. Also in this case I am wondering what the IDEs should do if they don't support debugging that project type. I assume that they should always make sure port forwarding is set up if a project is debugging so the user can attach a debugger if they want to (maybe using some other extension to Eclipse or VSCode).

**Comment by jcockbain** [comment]
@jopit - I moved `port-forward` to a separate command as it kept the outputs clearer and easier to follow. With a single command, within the `cwctl code` it's calling restart logic then forward logic. Was discussed in Portal scrum and @tobespc's preference was the one `restart` command too. I'm happy to revert to how it was if that's the consensus. 

There currently isn't a json output, as it stands it's the same output format as `kubectl port-forward` (in PR description). Moving the PR back to WIP whilst I work on moving it back to a single command and adding json output with the local port.
