### ISSUE TITLE
CS: Define correct terminology for Remote Tutorials

### ISSUE THREAD

**Issue by MelHopper** [eclipse/codewind#2576]
_This issue has come out of work done to tutorialise the Remote content: https://github.com/eclipse/codewind/issues/2151_

_This issue is related to work item: CS: Research terminology and propose improvements to reflect functionality https://github.com/eclipse/codewind/issues/2587_

**The Problem**

Better terminology needs to be defined for content. In particular, this issue is concerned with terminology used within the 2 remote tutorials:

1. Deploying Codewind remotely
2. Using Codewind remotely.

**Further Details**
Terms that need to be defined and/or replaced include:

- [x] install
- [ ] config
- [x] deploy - CONSENSUS: only to be used in context of deploying the 'Codewind engine' onto the cloud, in the remote case.
- [ ] creating and moving projects - to the user, it's about where the project is, not about moving it. 
- [ ] project - ensure difference between a Codewind project and a standard project is made clear
- [ ] use of 'cloud' and 'remote' within the Remote Tutorial documentation is confusing - re-consider labelling the 3 config of Codewind as 'Remote Codewind', 'Local Codewind', 'Browser-based Codewind'.

From @markcor11 : _it[install vs deploy terminology] means something specific in cloud terms,  installing suggests I have to go to a node,  install software,  where as deploy means use kube mechanics to schedule and let Kube create the objects in the cluster_

**Comment by MelHopper** [comment]
@deboer-tim FYI

**Comment by MelHopper** [comment]
@micgibso @kimholmes @thisguy-1 @sishida @j-c-berger FYI

**Comment by micgibso** [comment]
Terminology has settled, please verify this is done.

**Comment by micgibso** [comment]
Closing as complete.
