### ISSUE TITLE
[Docs] Add documentation for debug support in Codewind

### ISSUE THREAD

**Issue by keithchong** [eclipse/codewind#2581]
**Codewind version:** 0.11.0
**OS:** any
**IDE extension version:** latest
**IDE version:** any

**Description of the enhancement:**
From the Codewind docs link 
https://www.eclipse.org/codewind/overview.html
There isn't much documentation on how to debug a Codewind application.

Under the section "Developing projects", will it make sense to cover the important aspects of the Edit, Build/Compile and Run/Debug 'cycle', at least for the local case?

From https://www.eclipse.org/codewind/project-settings.html
```
If the project is already in debug mode, restart the project in debug mode in order to pick up the new debug port.
If the project is in run mode, the next restart picks up and uses the new debug port and completes a debug mode.
```
This is fine, but perhaps, the debug related content should be moved into its own section?  The section should also describe how to enable debug from the Codewind view.  That way, a Codewind beginner user can look up this information if necessary.  We contribute three actions to this view: `Restart in Debug Mode`, `Restart in Run Mode`, and `Attach Debugger`.

Similarly, from:  https://www.eclipse.org/codewind/checkingstatuses.html
we talk about the application status and the build status, but we don't talk about debug specifically.

Edit 2020/04/07 - Codewind specific steps to enable debug in Codewind apps.
- In the Codewind view, the user must select `Restart in Debug Mode` context menu action of a project/application
- Wait for the state to switch to `Debugging`.  The first time this is done, the debugger is attached.  However, the user should select `Attach Debugger`, if later on, the debug process is detached or terminated.
- Then proceed with 'regular' debugging actions as normal in the specific IDE that the user is using
- User can switch back to normal run mode if desired, by selecting `Restart in Run Mode`

Note the topics/areas of interest that the above steps touch upon:  Codewind view; Three Context menu actions; Run states (Aside from Starting/Stopped/etc. states, but specifically, `Running` and `Debugging` states)
End of edit 2020/04/07

Note, we do not have to document the _platform-provided_ specific features of debug, like the Debug window/view, the debug toolbar, or the Run/Debug launch configurations that are created.  For example, the user can re-use the launch configuration to attach and detach the debugger, but this is non-Codewind specific

**Comment by keithchong** [comment]
@sishida , I added more detail to this issue, based on our 'previous discussion'.  These initial steps can serve as an outline.

**Comment by sishida** [comment]
@keithchong Hi, Keith, I have merged the PR. 🎉Is this issue good to close now?

**Comment by keithchong** [comment]
@sishida , closing.  The content looks good.
