### ISSUE TITLE
Documenting debugging

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind#2585]
The docs currently do not include a page for debugging.
- We propose 1 debugging page for all IDEs.
- Although an IDE might have a debugging action that users of the IDE might already be familiar with, it could still be useful to point out Codewind's debugger.
- Remote debug should look similar but might be on a different page.

**Comment by micgibso** [comment]
@sishida Discussed with Toby this morning, we are not expected to instruct devs how to debug using their preferred IDE, same applies for remote debug.

**Comment by micgibso** [comment]
This work now covered by https://github.com/eclipse/codewind/issues/2581
