### ISSUE TITLE
CS: Research terminology and propose improvements to reflect functionality

### ISSUE THREAD

**Issue by MelHopper** [eclipse/codewind#2587]
**Enhancement**

Some terms and labels used within both content and UI design sometimes could be improved by using terms that reflect function.

This github issue is for researching our terminology and proposing improvements.

**Further Details**
Starting point: Previous work into terminology has resulted in the following definitions:

Codewind Terminology: https://ibm.ent.box.com/notes/539884590107

Codewind Plugin user interface labels and terminology: https://ibm.ent.box.com/notes/532783668595

**Comment by MelHopper** [comment]
FYI @deboer-tim

**Comment by sishida** [comment]
Hi, @MelHopper, The Box links aren't visible to everyone, but I have started this "Terminology" page in the `codewind-docs` wiki, where we can specify terms for everyone to see: https://github.com/eclipse/codewind-docs/wiki/Terminology

At the time of posting this comment, it is very small, but please let me know if you'd like any particular changes/updates. Thank you!

**Comment by micgibso** [comment]
Terminology as per wiki.
