### ISSUE TITLE
Content Security Policy problem in Che causes images to not load

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#2590]
Environment: Che on OCP 4.3.1. Using https

![image](https://user-images.githubusercontent.com/8888438/78167130-f0233680-741b-11ea-9c56-67bfb0e319e0.png)

What could be different about this environment? che with https isn't new

**Comment by tetchel** [comment]
So, this is not a problem with the CSP or with my extension at all. Some investigation with @pdfruth revealed that he has the same issue with *all* webviews, not just the Codewind ones (eg, the Che welcome page). 

![image](https://user-images.githubusercontent.com/8888438/78291596-a9a10b00-74f3-11ea-896d-b40e004fb9bd.png)

He is on OCS 4.3.1 and Che 7.10.0

**Comment by johnmcollier** [comment]
@pdfruth Che is very finicky with FF (especially older FF versions), recommend trying Chrome

**Comment by tetchel** [comment]
Solution: Use Chrome, or a newer version of firefox (ESR is too outdated!)

**Comment by pdfruth** [comment]
Just a quick update, in case others come should come looking, and find this issue.
The problem appears to be resolved after I updated Firefox to the latest version available (68.6.0esr) via the RHEL 8 repositories.
I'm also able to successfully use Chrome Version 80.0.3987.163 on same RHEL 8 system.
