### ISSUE TITLE
Remove the existing getting started page and redirect to the overview

### ISSUE THREAD

**Issue by sghung** [eclipse/codewind#2591]
In the future, we will use this redirection to point to the new page we're working on. In the short term, we're redirecting to overview.html (https://www.eclipse.org/codewind/overview.html). The existing getting started page doesn't have intellij shown plus it causes navigation issues in the sidebar (it is the only item that expands and goes to a link, usually it's one or the other, not both)

**Comment by MelHopper** [comment]
Change of plan to redirection: 
1. existing getting started page will be renamed gettingstarted.md -> gettingstarted-overview.md and remain in the Getting Started section of the ToC, to be reworked or replaced at a later date.
2. gettingstarted.md page removed and a redirect to the new Content Landing Page implemented.

@jcockbain FYI

**Comment by MelHopper** [comment]
step 1, renaming of gettingstarted.md, delivered via PR: https://github.com/eclipse/codewind-docs/pull/606

**Comment by jcockbain** [comment]
Implemented as part of New Landing Page #611

**Comment by MelHopper** [comment]
Verified by me - redirect working correctly on the published site.

**Comment by micgibso** [comment]
Closing as complete.
