### ISSUE TITLE
Implement new Codewind Landing Page

### ISSUE THREAD

**Issue by sghung** [eclipse/codewind#2594]
Implement the design from https://github.com/eclipse/codewind/issues/2041

**Comment by jcockbain** [comment]
I've deployed my version so far to https://jcockbain.github.io/codewind-docs/gettingstarted.html for feedback.

**Comment by MelHopper** [comment]
Looks great James. A few points:
- error  in Browser-based card copy "Download to develop, and run entirely on the cloud" -> 'Download to develop, **build** and run entirely on the cloud"
- Eclipse Che download button not working
- missing links in the Getting Started copy.
- Is there a way to make it obvious that page is scrollable?
- link incorrect from Developer card. Currently points to vsc-getting-started.html. Needs to point to gettingstarted.html
- error in Solution Architect card copy: "If you are a sysadmin DevOps engineer, learn how to deploy Codewind remotely." Change to "If you are a sysadmin or DevOps engineer, learn how to deploy Codewind remotely"
-Media: split into 'Blogs' and 'Guides'. See the next comment for the particular Design input that we need.

**Comment by MelHopper** [comment]
Design input required: @holmesk 

1. How do we get users to want to click a'button' to find more blogs? / go the blogs page? A link to '...more blogs' currently exists, but I suggest we link Blogs from the 'Blogs' section title, and this is coloured blue to indicate it is a clickable item..? Same question for Guides and Video section.
2. Please can we have an update on status of the IDE-specific designs for https://github.com/eclipse/codewind/issues/2041#issuecomment-620639770:
- step-by-step-instructions in the Desktop/Remote card.
- _If you are a developer, learn how to set up and start using Codewind on your IDE_ in the 'Get Started by Job Role -> Developer' card

Many thanks.

**Comment by MelHopper** [comment]
@jcockbain can we link to a blog whose image is not a screenshot? - so that it can be distinguished better from the Youtube videos which have screenshots as an image? eg. sneak-peek-remote-development-with-codewind.html

Moving forward, we can discuss how perhaps bloggers can start using images that are not screenshots, if suitable and gets the message across better.

**Comment by jcockbain** [comment]
Thanks @MelHopper, I've sorted most of the errors. This is the only stuff I'm not sure on:

-  what is the link for the Eclipse Che download? I didn't add that one as I wasn't sure where the download page was. 

- at the moment this page is at `/getting-started.html`, so the link in the developer card would not go anywhere. Is this page supposed to be at a different URL, and are we then keeping the current `getting-started` page? 

With the blogs, I've written it dynamically to show the most recent, with a `title_img` coded into the metadata of that blog. I can make it show whichever blog we like. I can also have it show a stock image if the blog doesn't have a `title_img` attached.

**Comment by MelHopper** [comment]
Blog copy under the blog title on the landing page is the author. can you replace the author text with the beginning of the blog? e.g. "Need a specific capability in your application? Chances are there’s a code library or package..." - however many words fit nicely on the screen.

**Comment by MelHopper** [comment]
...and same for the video - it displays the beginning of the video description.

**Comment by MelHopper** [comment]
Link to step-by-step instructions on the Eclipse Che card are not included: 
_Download to develop and run entirely on your cloud_ [step-by-step instructions](eclipse.org/codewind/che-installinfo.html)

**Comment by MelHopper** [comment]
TASK: @MelHopper to ensure we have signposting within the YAML File to the installation instructions on the website.

**Comment by jcockbain** [comment]
For the blogs, no problem as we already have the `blog_description` on each blog. The words will be the same as is seen in the `blogs` page. 

Videos will be a bit trickier as we are linking off to Youtube and don't store the descriptions. I'll have a play and see if I can use the Youtube API to get descriptions.

**Comment by kimholmes** [comment]
@MelHopper Just want to make sure I’ve answered these questions in full.
You asked:
_Design: @holmesk How do we get users to want to click a’button’ to find more blogs? / go the blogs page? Link to ‘...more blogs’ exists, does link to Blogs page need to be more prominent e.g. with the title of the section also linking to the Blogs page? Asking Design. Same question for Guides and Video section._

1. The blogs and videos. There are 3 different ways the user is directed there on the landing page.
We can link the titles to the blogs landing page as you’ve suggested. In James’ current version, there is a title that reads Media. So, we would need to remove that and give blogs and videos their own individual titles that link to the respective pages.
![image](https://user-images.githubusercontent.com/21316329/82466288-3563fc00-9a8e-11ea-84f7-a131c697cb82.png)
2. They can click on the title of the blog or video that is featured.
3. They can click the “more” link.
Do you plan to include left nav items for guides, blogs and videos?

Your second question:
_Design: @holmesk Where are we with the IDE-specific designs for https://github.com/eclipse/codewind/issues/2041#issuecomment-620639770:
step-by-step-instructions in the Desktop/Remote section
_If you are a developer, learn how to set up and start using Codewind on your IDE_ in the ‘Get Started by Job Role -> Developer’ card_

For number 1. James has put a solution in his version of the page:
![image (1)](https://user-images.githubusercontent.com/21316329/82466570-968bcf80-9a8e-11ea-8f48-13e56757c869.png)
Each individual IDE links to the installation instructions. I’m actually questioning whether or not the buttons should link to the instructions as well. Right now they are linking directly to the installation.
For number 2 - by job role, James has done the same. Each are linking directly to individual IDE.
![image (2)](https://user-images.githubusercontent.com/21316329/82466756-cb982200-9a8e-11ea-8059-a85c5bcbfe1d.png)
Looks like we’re missing Che though.

**Comment by jcockbain** [comment]
@kimholmes @MelHopper - I've made the suggested updates, PRed my branch, and redeployed to the same link https://jcockbain.github.io/codewind-docs/learn.html.

**Comment by MelHopper** [comment]
This work will be delivered via PR #611 https://github.com/eclipse/codewind-docs/pull/611

**Comment by MelHopper** [comment]
<img width="722" alt="Screenshot 2020-05-26 at 10 31 08" src="https://user-images.githubusercontent.com/13365734/82886074-ead6f980-9f3d-11ea-95e9-60db77c0da1c.png">

'Callout with Header
This is an HTML element'

The PR with this change can be seen on the test website https://jcockbain.github.io/codewind-docs/learn.html.

**Comment by MelHopper** [comment]
Landing page is now published. @micgibso please can you close this issue?
