### ISSUE TITLE
SVT:Appsody project create failed and I can not create same project any more

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#2601]
**Codewind version:** 0.11
**OS:** Windows

**Che version:** 
**IDE extension version:**  Eclipse 0.11
**IDE version:** Eclipse 2019-09
**Kubernetes cluster:**

**Description:**
I created one of appsody project from (Appsody Node.js Loop Back Template) and for some reason it is failed and after that I can not create same project with the same name. I can not find the actual folder of the project "appsodynodejslbcw011svt" in my workspace and it still compmains "Non empty Directory" provided. As a user what can I do to get rid of this project so that I can import same project again. 

![image](https://user-images.githubusercontent.com/713849/78271546-4656af00-74da-11ea-9179-4eab43ec5f91.png)

![image](https://user-images.githubusercontent.com/713849/78271656-65edd780-74da-11ea-8655-a383f70ffb0e.png)

Logs

[performance.txt](https://github.com/eclipse/codewind/files/4422201/performance.txt)
[pfe.txt](https://github.com/eclipse/codewind/files/4422202/pfe.txt)
[.log](https://github.com/eclipse/codewind/files/4422209/default.log)

```
[root@e120ea52b3cd codewind-workspace]# ls -lart
total 68
drwxr-xr-x  1 root root 4096 Apr  2 12:06 ..
drwxrwxr-x  3 root root 4096 Apr  2 12:06 .extensions
drwxr-xr-x  3 root root 4096 Apr  2 12:06 .appsody
drwxrwxr-x  2 root root 4096 Apr  2 12:06 .config
drwxrwxr-x  3 root root 4096 Apr  2 12:55 gocw011svt
drwxrwxr-x  5 root root 4096 Apr  2 12:56 lagomcw011svt
drwxrwxr-x  7 root root 4096 Apr  2 12:56 nodejscw011svt
drwxrwxr-x  3 root root 4096 Apr  2 12:58 pythoncw011svt
drwxrwxr-x  4 root root 4096 Apr  2 12:59 springcw011svt
drwxrwxr-x  6 root root 4096 Apr  2 13:02 olcw011svt
drwxrwxrwx 17 root root 4096 Apr  2 13:12 .
drwxrwxr-x  4 root root 4096 Apr  2 13:12 .idc
drwxrwxr-x  6 1001 root 4096 Apr  2 13:14 wlcw011svt
drwxrwxr-x  6 root root 4096 Apr  2 13:17 swiftcw011svt
drwxrwxr-x  2 root root 4096 Apr  2 13:20 .projects
drwxrwxr-x 12 root root 4096 Apr  2 13:20 cw-temp
drwxrwxr-x 12 1001 root 4096 Apr  2 13:20 .logs
```

```
[root@e120ea52b3cd cw-temp]# ls -lrt
total 40
drwxrwxr-x 3 root root 4096 Apr  2 12:55 gocw011svt
drwxrwxr-x 5 root root 4096 Apr  2 12:56 lagomcw011svt
drwxrwxr-x 7 root root 4096 Apr  2 12:56 nodejscw011svt
drwxrwxr-x 3 root root 4096 Apr  2 12:58 pythoncw011svt
drwxrwxr-x 4 root root 4096 Apr  2 12:59 springcw011svt
drwxrwxr-x 5 root root 4096 Apr  2 13:01 swiftcw011svt
drwxrwxr-x 6 root root 4096 Apr  2 13:01 olcw011svt
drwxrwxr-x 5 root root 4096 Apr  2 13:13 wlcw011svt
drwxrwxr-x 3 root root 4096 Apr  2 13:17 appsodyempcw011svt
drwxrwxr-x 4 root root 4096 Apr  2 13:20 appsodyswiftkitcw011svt
```

**Steps to reproduce:**
1. Create bunch of projects with Appsody and Default templates.
2. During project ceration one of the project failed to cerate and I can not create same project again with the same name.

**Workaround:**

**Comment by makandre** [comment]
For appsody projects, you have to ls /mounted-workspace in pfe (which is bind mounted to your local codewind-data dir)

**Comment by sghung** [comment]
Jag and I did some debugging on his machine and as far as Jag and I could see, none of the directories with his project name exist in the pfe container anymore.

In https://github.com/eclipse/codewind-installer/blob/master/pkg/project/create.go#L217

It should be returning the non empty error there, is there a way to see if this API is behaving incorrectly? Is there a way we can check what directory its actually checking with?

**Comment by makandre** [comment]
If the error comes from `cwctl`, which runs locally, then we should check the local file system where we're trying to create the project rather than inside PFE

**Comment by hhellyer** [comment]
The error comes from here:

https://github.com/eclipse/codewind-installer/blob/1405623131abd7b8c7e2ea9c8146025a411f37a0/pkg/project/create.go#L229-L232

and is triggered by `cwctl` detecting that the directory already exists. If you have a look on the local disk in the directory the project was supposed to be created in there will be a folder with the name `appsodynodejslbcw011svt` that was probably created by the initial failure.

The initial failure from the Eclipse log (section below) seems to be at 09:21:17.964, then we get the non empty directory error at 09:24:46.187.

It looks like the Eclipse plugin decided to kill `cwctl` because it was taking too long to create the appsody project (I'd guess a slow download but that's only a guess) at which point the directory would have been created but by killing `cwctl` there's no way it could have cleaned up after itself. On the second run it can't know if a directory is safe to delete, overwrite or update so quitting with an error is probably the right choice.

I'm going to pass this to the UI team, I don't think `cwctl` can clean up after another process kills it by due to a timeout. The plugin is the only component that can know it's safe to delete that directory and was in control when it killed the long running `cwctl` process.

```
!ENTRY org.eclipse.codewind.core 4 0 2020-04-02 09:21:17.964
!MESSAGE [ERROR NewCodewindProjectWizard$1.run:202] An error occured trying to create a project with type: https://github.com/appsody/stacks/releases/download/nodejs-loopback-v0.3.0/incubator.nodejs-loopback.v0.3.0.templates.scaffold.tar.gz, and name: appsodynodejslbcw011svt
!STACK 0
java.util.concurrent.TimeoutException: Process did not complete and had to be terminated
	at org.eclipse.codewind.core.internal.ProcessHelper.waitForProcess(ProcessHelper.java:125)
	at org.eclipse.codewind.core.internal.cli.ProjectUtil.createProject(ProjectUtil.java:50)
	at org.eclipse.codewind.ui.internal.wizards.NewCodewindProjectWizard$1.run(NewCodewindProjectWizard.java:173)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.eclipse.codewind.ui 4 0 2020-04-02 09:21:17.975
!MESSAGE An error occurred trying to create Codewind project appsodynodejslbcw011svt
!STACK 0
java.util.concurrent.TimeoutException: Process did not complete and had to be terminated
	at org.eclipse.codewind.core.internal.ProcessHelper.waitForProcess(ProcessHelper.java:125)
	at org.eclipse.codewind.core.internal.cli.ProjectUtil.createProject(ProjectUtil.java:50)
	at org.eclipse.codewind.ui.internal.wizards.NewCodewindProjectWizard$1.run(NewCodewindProjectWizard.java:173)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.eclipse.codewind.core 4 0 2020-04-02 09:24:46.185
!MESSAGE [ERROR CLIUtil.checkResult:199] The cwctl 'project create' command failed with error: Non empty directory provided

!ENTRY org.eclipse.codewind.core 4 0 2020-04-02 09:24:46.187
!MESSAGE [ERROR NewCodewindProjectWizard$1.run:202] An error occured trying to create a project with type: https://github.com/appsody/stacks/releases/download/nodejs-loopback-v0.3.0/incubator.nodejs-loopback.v0.3.0.templates.scaffold.tar.gz, and name: appsodynodejslbcw011svt
!STACK 0
java.io.IOException: Non empty directory provided
	at org.eclipse.codewind.core.internal.cli.CLIUtil.checkResult(CLIUtil.java:200)
	at org.eclipse.codewind.core.internal.cli.ProjectUtil.createProject(ProjectUtil.java:51)
	at org.eclipse.codewind.ui.internal.wizards.NewCodewindProjectWizard$1.run(NewCodewindProjectWizard.java:173)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by eharris369** [comment]
Fixed by PR: https://github.com/eclipse/codewind-eclipse/pull/690

**Comment by eharris369** [comment]
@jagraj - Please wait for a new master build

**Comment by jagraj** [comment]
@eharris369 
Can it be merged to Codewind 0.11 branch as well.? I have seen this issue with Codewind 0.11 release.

**Comment by eharris369** [comment]
I have created a PR for 0.11.0: https://github.com/eclipse/codewind-eclipse/pull/691

**Comment by jagraj** [comment]
This issue has been fixed.
