### ISSUE TITLE
Fix or document upgrade path from versions < 0.9

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#2604]
We have had 3 users contact us in the last 2 weeks (eg #2532) getting stuck trying to upgrade Codewind from 0.4, 0.5, and 0.8.1 to latest production (0.9). They see the following error:

```
==> Run cwctl --json remove -t 0.8.1
Removing Codewind docker images..
System architecture is:  amd64
Host operating system is:  darwin
Please wait whilst images are removed...  
.FileNotFoundError: [Errno 2] No such file or directory: '/Users/stephenkinder/.codewind/docker-compose.yaml'
{"error":"IMAGE_REMOVE_ERROR","error_description":"exit status 1"}
```

They can resolve this error by removing the images by hand or (on mac/linux) using the one liner in https://github.com/eclipse/codewind/issues/2532#issuecomment-602079463.

Then, they have to remove the codewind_network (`docker network rm codewind_network`) https://github.com/eclipse/codewind/issues/2532#issuecomment-605445168.

After this codewind starts, unless you hit the "no such image" problem, in which case you have to (?) do the system prune.

This issue will go away once all users are on 0.9 or greater, when we introduced the docker-compose.yaml. But in the meantime, we should fix this bug if it is a reasonable amount of effort, or at least document the workaround above.

**Comment by tobespc** [comment]
I'm not sure what we can fix in the code on this.  If they failure is to get to 0.9 then we would have to make changes to 0.9 which is not something we plan to do.   I suggest we document then required steps.

Once we have 0.11 live then then this will all change again when upgrading. 

@micgibso Can you review what we have in the docs for upgrade support and look to add in the steps above please

**Comment by micgibso** [comment]
@tobespc Sure, will take a look.

**Comment by tetchel** [comment]
> Once we have 0.11 live then then this will all change again when upgrading.

Did the upgrade path change again in 0.11 ? else wouldn't they see the same issue going from < 0.9 to 0.11 ?

**Comment by micgibso** [comment]
We do not document upgrade paths anywhere in the docs. Will add a new Troubleshooting issue on a PR for your review.
