### ISSUE TITLE
Report build-info.properties download more obviously

### ISSUE THREAD

**Issue by rajivnathan** [eclipse/codewind#2610]
**Codewind version:** master
**OS:** MacOS

**Description:**
Wanted to verify something so downloaded the latest vscode extension from http://download.eclipse.org/codewind/codewind-vscode/master/latest/codewind.vsix. It appears the new one is small so the download was very fast but then it was stuck "Setting up" for way too long. I'm assuming the cwctl is being downloaded? Either way, users would have no idea what's going on. I'd suggest more detailed progress but I'm not sure it'd help if the download source is just very slow. A speed test clocked my connection at 250 Mbps down so the issue isn't on my end. I was unable to do anything with the extension either, just saw a message saying "Please wait for the extension to finish setting up."  I got tired of waiting and uninstalled.

Considering it is the latest from master, I'm not sure if this is just a point in time thing so feel free to close the issue if it is.

**Comment by tetchel** [comment]
It isn't stuck downloading (ie not caused by slow network / download site) because the download shows an obvious progress bar in a notification. Probably it failed at some step before the download even started. Is there anything in the Codewind output view? Otherwise, I would have to see the logs.

I was worried there may be some issues with this new 'risky' download flow that would be platform/environment dependent.

**Comment by rwalle61** [comment]
@jcockbain 's vscode was stuck "Setting up" after pulling master, don't know if it is related to this

**Comment by tetchel** [comment]
https://github.com/eclipse/codewind-vscode/commit/107fc1d43cbffefcac919de70a1fa4f1d67ffb36 added a more obvious error message is something catastrophic happens here

**Comment by tetchel** [comment]
it may have gotten stuck fetching the build properties, which is supposed to be really fast but it just took 22s for me. I'll add better progress for that step.

![image](https://user-images.githubusercontent.com/8888438/79901392-c38c8a00-83dd-11ea-8bef-8e69335ad851.png)
