### ISSUE TITLE
Update the Troubleshooting topic for 0.12.0

### ISSUE THREAD

**Issue by micgibso** [eclipse/codewind#2613]
**Codewind version:** 0.12.0

Check https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/troubleshooting.md for any issues that are no longer valid, or add new issues or corrections.

**Comment by eharris369** [comment]
I think the workaround here needs to be more clear, especially since for Eclipse when the user is asked if the project type is correct they don't select No, rather they select Next to go to the next page in the wizard.

How about:
Workaround: Bind the existing project again but this time, don't accept the detected type (click No for VSCode, Next for Eclipse) and then choose **Other (Codewind Basic Container)** for the project type.

```
Adding an existing Open Liberty project fails to build because of missing files

An Open Liberty project fails to build after it is added into Codewind with the Add Existing Project action, and the project fails to build because of missing files.

Workaround: Bind the existing project again and click No followed by Other for the project type.
```

Not sure how to adapt it to Eclipse. What is the user being asked when they are supposed to select No? Also, to match what

**Comment by eharris369** [comment]
For the following workaround, with Eclipse the user can edit the URL in the browser but this is temporary. If they want the change to be permanent then they can edit the .cw-settings file and save it. I would assume the same is true for VSCode and Che - that the user can do one or the other? @tetchel 

```
Context Root / Application Endpoint not correct

If you create or bind a project that has a context root set in .cw-settings, such as a project using the Lagom template, the context root is not picked up initially. This also happens after restarting Codewind.

Workaround For Eclipse, add the context root to the URL in your browser. For example, the browser might open with localhost:34567 instead of localhost:34567/mycontextroot, so type mycontextroot. For VS Code and Che, edit and save the .cw-settings file, and the context root updates.
```

**Comment by eharris369** [comment]
Is the following true? I tried it on Eclipse and after disabling auto build and making a change it did not pick it up unless I did a manual build. For Node I thought when disabling auto build it stopped using nodemon? @elsony 

```
Turning off auto build has no effect for Node.js projects when you run Codewind locally

If you turn off auto build for a Node.js project when you run Codewind locally, it has no effect. Changes you make to your code automatically start or restart a build even though auto build is disabled.
```

**Comment by tetchel** [comment]
For the contextroot one, there shouldn't be a special section for vs code and che. Like erin said, you should edit .cw-settings in all 3 scenarios, and the change will be permanent.

**Comment by micgibso** [comment]
@eharris369 @tetchel See PR https://github.com/eclipse/codewind-docs/pull/528/files for the changes. For the first, have clarified the workaround, for the second have reordered the text to put the permanent fix first, the temporary fix for Eclipse second.  Will await Elson's response for the third.

**Comment by sishida** [comment]
@micgibso Here is a PR for a troubleshooting page update about "Executable file not found on PATH in VS Code": https://github.com/eclipse/codewind-docs/pull/525

**Comment by micgibso** [comment]
Changes on PR https://github.com/eclipse/codewind-docs/pull/528 for all above except Erin's third comment: https://github.com/eclipse/codewind/issues/2613#issuecomment-610471583
