### ISSUE TITLE
SVT: [Local] Metric Dashboard content is missing for some projects even after injecting application metrics

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#2616]
**Codewind version:** 0.11.0 
**OS:** VM with Windows 10

**IDE extension version:** 0.11.0
**IDE version:** Code 1.43.2

**Description:** Metric Dashboard content is missing for some projects even after injecting application metrics.

![Screen Shot 2020-04-06 at 9 23 46 AM](https://user-images.githubusercontent.com/49531960/78563689-6099d100-77e9-11ea-96aa-b2652126f1ad.png)

<img width="1676" alt="Screen Shot 2020-04-06 at 9 20 56 AM" src="https://user-images.githubusercontent.com/49531960/78563653-54157880-77e9-11ea-9979-09344b3cabbb.png">

**Steps to reproduce:**
1. Install and start Codewind 0.11.0
2. Create a Default Open Liberty project
3. Wait for the project to be in "Running" state
4. Right-click on the project and select  "Metrics Dashboard"
5. Verify if there are any metrics
6. Right-click on the project and select  "Enable Inject Appmetrics"
7. Verify if there are any metrics

**Log:**
[codewind-pfe.txt](https://github.com/eclipse/codewind/files/4438630/codewind-pfe.txt)

**Comment by sujeilyfonseca** [comment]
For some projects (i.e., Default WebShere Liberty MicroProfile), I retrieved the application metrics the first time, but I don't see them after enabling "Inject Appmetrics". 

_Before injecting application metrics:_
![Screen Shot 2020-04-06 at 9 25 42 AM](https://user-images.githubusercontent.com/49531960/78565609-2847c200-77ec-11ea-8b3d-67cead3fb95f.png)

_After injecting application metrics:_
![Screen Shot 2020-04-06 at 9 53 16 AM](https://user-images.githubusercontent.com/49531960/78565899-82488780-77ec-11ea-87bf-acc1ba95dae7.png)

**Note:** Either the view name changed or the wrong view is present for the same project.

**Comment by jagraj** [comment]
I am also noticing same problem with appsody projects where metrics data is missing for "Appsody Eclipse Microprofile, Appsody Open Liberty, Appsody Spring Kotlin" projects. I do see metrics data for swift, nodejs appsody projects but not for Appsody  Java projects.

For default projects, Sujeily provided more information in above comments. We are not sure if this same problem or not. If this is different problem with Appsody then we will open separate issue.

![image](https://user-images.githubusercontent.com/713849/78566619-81642580-77ed-11ea-9127-83a6a482bae7.png)

![image](https://user-images.githubusercontent.com/713849/78566780-b83a3b80-77ed-11ea-8b67-acff1007f641.png)

 
[pfe.txt](https://github.com/eclipse/codewind/files/4438840/pfe.txt)

**Comment by malincoln** [comment]
@tobespc pls assign.  Thanks

**Comment by tobespc** [comment]
this is all part of the work we are doing to resolve the perf dashboard issues that prevented us shipping 0.10.0

Until we have fully finished with #2284 and #2008 (should be today) then please hold off anymore perf dashboard testing

**Comment by tobespc** [comment]
now the changes are all in, I'll run the test scenarios above

**Comment by jagraj** [comment]
@tobespc 
With the latest 0.11 images, looks like we still have issues with the Metrics dashboard where it does not work after injecting metrics for default  WebSphere liberty and also for Open Liberty projects. 
I see same behavior with these projects ("Appsody Eclipse Microprofile, Appsody Open Liberty, Appsody Spring Kotlin"). 

![image](https://user-images.githubusercontent.com/713849/78714389-ce2d2680-78e9-11ea-956d-e5e8a3a794b3.png)


[performance.txt](https://github.com/eclipse/codewind/files/4446778/performance.txt)
[pfe.txt](https://github.com/eclipse/codewind/files/4446779/pfe.txt)

**Comment by tobespc** [comment]
so easy recreate, create an openliberty project, inject metrics, then run load and open the metrics dashboard. No data will be shown. If you go to
http://127.0.0.1:32809/javametrics/api/v1/collections
you can see that the injection has worked
but no dashboard data

**Comment by markcor11** [comment]
I do see the dashboard requesting data every few seconds,  but I also see that no data was returned only : HTTP 200 content-length:0 bytes.   However,  if I access the project directly using http://127.0.0.1:{projectport}/metrics/codewind I do see data being served up which suggests injection has worked in the project container. Investigating why the data is not making its way back up through the reverse proxy.

**Comment by markcor11** [comment]
Posted PR #2636 which should hopefully address this, was caused by a recent switch from the security advisory deprecating the `request`NodeJS module and migration to the newer `got` nodeJS module. The new got module needs special handling for writable streams.

**Comment by jagraj** [comment]
@markcor11 
Thanks, we do get Metrics Dashboard results now for both WebSphere Liberty, Open Liberty projects. I do not see data for Appsody Eclipse Microprofile, Appsody Open Liberty  and Appsody Spring Kotlin projects. When you get a chance, could you please try with appsody projects.?

![image](https://user-images.githubusercontent.com/713849/78860156-6c5ee080-79ff-11ea-8ed7-a3f5c80fd428.png)
[performance.txt](https://github.com/eclipse/codewind/files/4454141/performance.txt)
[pfe.txt](https://github.com/eclipse/codewind/files/4454142/pfe.txt)

**Comment by markcor11** [comment]
@jagraj we do not currently support live metrics in Appsody project types.  There is an open issue to request this functionality: https://github.com/eclipse/codewind/issues/1361

**Comment by sujeilyfonseca** [comment]
I verified this issue with the latest Codewind 0.11.0, and I was able to see metrics for the default projects before and after injecting application metrics.

<img width="1667" alt="Screen Shot 2020-04-09 at 1 01 44 PM" src="https://user-images.githubusercontent.com/49531960/78921664-3c492900-7a63-11ea-92ce-9ab384764bc8.png">

However, I see the same behavior as Jag. I don't see application metrics for some Appsody projects. I was looking at issue #1361, and it mentions that metrics injection doesn't work for Appsody projects. So should it work before the user injects the application metrics, or does the Metrics Dashboard not work at all for Appsody?

**Comment by tobespc** [comment]
Metrics will only work for appsody projects that are making use of either our appmetrics modules, or mp-profile.  Without those we don't get anything.   For the next release, we are working on making the dashboard very clear as to what/why you can/cannot see data and the steps to take if they can be enabled.

**Comment by tobespc** [comment]
Appsody also does not support inject metrics at the moment

**Comment by tobespc** [comment]
I believe this PR can be closed now with the comments and fixes that have already been made.  Moving to verify

**Comment by sujeilyfonseca** [comment]
Thank you very much for working to solve this issue, @tobespc and @markcor11!

I verified this issue with the latest Codewind 0.11.0, and I no longer reproduce the problem with default projects. I was not able to get metrics with the previously mentioned projects:
 
Appsody Eclipse Microprofile
Appsody Open Liberty 
Appsody Spring Boot Default
Appsody Spring Boot Kotlin

However, we have another issue to track compatibility (https://github.com/eclipse/codewind/issues/2384). Therefore, as @tobespc suggested, I'll proceed to close this issue with the comments made.
