### ISSUE TITLE
No proper error message if invalid credentials are given for registry secret

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#2619]
When adding a registry to the local connection, and therefore doing a `docker login`:

```
11:29:58  [INFO: 15:29:56.439 CLIWrapper.ts:136]: Running CLI command: cwctl --json --insecure registrysecrets add --conid local --address fakedomain0553.io --username fake-user --password *********
11:29:58  
11:29:58  [ERRO: 15:29:56.745 CLIWrapper.ts:183]: Error running cwctl --json --insecure registrysecrets add --conid local --address fakedomain0553.io --username fake-user --password *********
11:29:58  
11:29:58  [ERRO: 15:29:56.746 CLIWrapper.ts:185]: Stdout: {"error":"DOCKER_CREDENTIAL_ERROR","error_description":"exit status 1"}
```

So all the user will see is "Failed to run cwctl registrysecrets add: exit status 1".

Can we add an `error_description` to this output that says something like,
```
Docker login to <domain> as <username> failed. Address, username or password is incorrect.
```
(I doubt we can determine if the domain is valid so that's the best we can do).

**Comment by tetchel** [comment]
I'm converting this to a hot bug because it looks like a bug even though the user just has to fix their credentials

**Comment by jcockbain** [comment]
Looking at this now, it's this error that's being hit: https://github.com/eclipse/codewind-installer/blob/master/pkg/docker/docker.go#L634. 

If called without the `--json` flag, the description that's set by us (currently `Error executing 'docker login'`) is returned. 

However, with `--json` set, the error description is the error returned from the exec command (based on format I'm thinking it's from the `os/exec` package and not a the return from the docker command). 

So we could create a new custom error when the login command errors, with the message above, and return that. As long as that doesn't hide helpful information coming back from the docker command. @hhellyer - what do you think?
