### ISSUE TITLE
How to recreate the project container

### ISSUE THREAD

**Issue by MirtoBusico** [eclipse/codewind#2622]
**Codewind version:** 1.5.2
**OS:** Ubuntu 18.04

**Che version:**
**IDE extension version:**
**IDE version:** Eclipse 4.15.0
**Kubernetes cluster:**

**Question synopsis:** I deleted the project container and I cannot recreate it

I created a test project using the nodejs template and everything worked.

Then I tried to push / delete / pull in a local docker registry and I deleted the container image

Now, from Eclipse I'm not able to force the creation of a new container.

What can I do?

**Comment by tetchel** [comment]
Hi, 

You can get Codewind to recreate the container:

1. Right-click the project in the Codewind explorer and select `Disable Project`
2. Wait for the project to be Disabled
3. Right-click the project and select Enable Project
4. The image build will proceed, and the container will be run again once the build finishes.

**Comment by MirtoBusico** [comment]
Thansk. Worked.
