### ISSUE TITLE
Terminology: When to use "project" or "namespace"?

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind#2628]
In OpenShift, "project" is the preferred term over "namespace." See conversation in eclipse/codewind-docs#508 and then the closed PR eclipse/codewind-docs#513.

Should we add a note to address this info in the `codewind-operator` README: https://github.com/eclipse/codewind-operator/blob/master/README.md?

**Comment by johnmcollier** [comment]
In my opinion, our docs should be consistent and Kube generic, so we should use namespace over project where possible. 

Branching off for openshift and mentioning project doesn’t make things any easier for the user in my opinion, so we should leave it as-is

**Comment by AndyRWatson** [comment]
I think I agree @johnmcollier , we should remain lube generic and that openshift admins will know enough to know that they refer to namespaces as projects

**Comment by sishida** [comment]
I have updated the terminology wiki page: https://github.com/eclipse/codewind-docs/wiki/Terminology. Closing this issue.
