### ISSUE TITLE
Perf dashboard shows "old appmetrics..." message when no appmetrics installed

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#2631]
**Codewind version:** latest
**OS:** macos

**Description:**

Running the performance dashboard against a vanilla open liberty template gives the warning message
```
An old version of Appmetrics has been detected. Results may be inaccurate until you update Appmetrics within your project.
```

However, upon checking the pom.xml for my project I found I didn't have any appmetrics/javametrics etc being used.  We should give a better message in this case to say something like 

```
no appmetrics package has been found, you need to inject metrics
```

**Comment by markcor11** [comment]
Code merged into master

/close
