### ISSUE TITLE
Revisit IDE specific troubleshooting topics

### ISSUE THREAD

**Issue by micgibso** [eclipse/codewind#2633]
**Codewind version:** 0.12.0

**Description of the enhancement:**
Docs. The IDE specific help files mdt-eclipse-troubleshooting.md & mdt-vsc-troubleshooting.md have been iterated out. 

**Proposed solution:** 
Revisit these topics and check the contents, if applicable reinstate in the current troubleshooting topic.

**Comment by tetchel** [comment]
The reason I asked if these pages were still around was for https://github.com/eclipse/codewind-docs/pull/525

**Comment by micgibso** [comment]
Will check the old pages and see if there's any more valid content.

**Comment by micgibso** [comment]
Old pages are in this zip: 
[VS Code & Eclipse ts topics.zip](https://github.com/eclipse/codewind/files/4556798/VS.Code.Eclipse.ts.topics.zip)

**Comment by micgibso** [comment]
Completed.
