### ISSUE TITLE
SVT: Need windows support for remote operator install. 

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#2646]
**Codewind version:** Codewind 0.11
**OS:** Windows

**Che version:** 
**IDE extension version:** Eclipse, VSCode
**IDE version:** Codewind 0.11
**Kubernetes cluster:**

**Description:**
Jane as a developer working on Windows platform should be able to install operator from the scripts provided in the docs.  Looks like we have shell script ./install.sh and we need similar script for Windows users.

Instructions are here..

https://github.com/eclipse/codewind-operator

**Steps to reproduce:**
1. Install Codewind remote Operator. 

**Workaround:**

**Comment by rtaniwa** [comment]
/priority stopship

I think we should be looking hard at this for 0.11.

**Comment by malincoln** [comment]
Andy said he would take a look at this too

**Comment by AndyRWatson** [comment]
Raised pull request to update install.sh to support Windows. 

Should not cause stop ship as codewind-operator is independent of GA release code, as separate install process using git clone of codewind-operator repo, so could be updated independently of a codewind release if require extra testing on windows.

**Comment by tobespc** [comment]
The install script is merely a helper script to wrap the documented kubectl steps, it does not in anyway prevent the operator being installed on windows as the steps listed in the git repo are correct for windows.

I agree with @AndyRWatson that this shouldn't be stop ship but we will work on adding a script for windows

**Comment by jagraj** [comment]
I followed instructions from the docs on windows with the latest install.sh script on Windows.
When I try to execute install.sh script which opens "GitBash" shell window and closes it cause it is shell script. Looks like windows powershell by default runs the bash script in git bash. Once it closes, when I try to get the ingress endpoint for keycloak service this is what I get and it is not valid.

```
PS C:\MyData\dev-exp\codewind\hybrid\operator\codewind-operator\deploy> .\install.sh operator -i apps.extols.os.fyre.ibm.com
PS C:\MyData\dev-exp\codewind\hybrid\operator\codewind-operator\deploy> oc get pods
NAME                                          READY   STATUS              RESTARTS   AGE
codewind-keycloak-devex001-65b55d4ff7-l7djk   0/1     ContainerCreating   0          17s
codewind-operator-777d5d94b6-mdwk7            1/1     Running             0          71s
```
```
oc get routes
NAME                         HOST/PORT                                              PATH   SERVICES                     PORT   TERMINATION     WILDCARD
codewind-keycloak-devex001   codewind-keycloak-devex001.codewind.apps-crc.testing          codewind-keycloak-devex001   8080   edge/Redirect   None
```

Looks like ingress endpoint is not replaced when the script is executed. Git Bash is prereq if we want to use "install.sh" script for windows as well. 

This route (`codewind-keycloak-devex001.codewind.apps-crc.testing`)does not work and I can not access Keycloak service.

**Comment by AndyRWatson** [comment]
@jagraj  can you make sure that you pick up the latest version in Repo as this was an issue I fixed on Friday. https://github.com/eclipse/codewind-operator

**Comment by AndyRWatson** [comment]
also confirm that this is still a shell script so will run from a powershell window

**Comment by jagraj** [comment]
hmm, I cloned this morning and executed the script. Are there any fixes after that.?

**Comment by AndyRWatson** [comment]
the PR for the repo only just merged this afternoon

**Comment by jagraj** [comment]
I verified latest script on windows and I am able to install remote codewind from the operator. 
On windows the script executes in "GitBash" window which is prerequisite. Once script executes in Windows and closes the GitBash popup and user has to get the endpoint from the following command. 

Here are the instructions to retrieve endpoint URLs for KeyCloak and Codewind.

```
kubectl get keycloak -n codewind
NAME       NAMESPACE   AGE    ACCESS
devex001   codewind    122m   https://codewind-keycloak-devex001.<ingress-domain>
```

```
kubectl get codewind -n codewind
NAME       USERNAME   NAMESPACE   AGE    KEYCLOAK   REGISTRATION   ACCESSURL
devex001   jane       codewind    119m   devex001   Complete       https://codewind-gatekeeper-devex001.<ingress-domain>
```

Thanks for the fix. I am closing it for now.
