### ISSUE TITLE
Codewind Repositories Should Have a PR Template

### ISSUE THREAD

**Issue by maysunfaisal** [eclipse/codewind#2650]
For #2291

We have several open source repos which contribute to Codewind

And it would be nice to follow a standard like everyone in the industry where the repos have a PR template. This also helps everyone who is a not an owner of the PR, as well as looking back in history for a PR. 

Could each person assigned create a template PR doc for the repo

PR Template checklist

- **Type of PR?** 
- **What does this PR do?** 
- **Which issue(s) does this PR fix?** 
- **Does this PR require a documentation change? (Link Issue)** 
- **Does this PR require new tests or tests to be updated? (Link Issue, if its not covered with the PR)** 
- **Any special notes for your reviewer?** 

You can have a look at the codewind repo template as an example https://github.com/eclipse/codewind/blob/master/.github/PULL_REQUEST_TEMPLATE.MD (which needs to be updated for the test question)

Please reply back with a link to the PR template for your repository. If there is already one present, share its link.

/kind Test
@rwalle61

**Comment by maysunfaisal** [comment]
/assign @jopit
/area intellij-ide

- [ ] https://github.com/eclipse/codewind-intellij

/assign @tetchel
/area vscode-ide

- [ ] https://github.com/eclipse/codewind-vscode

/assign @eharris369
/area eclipse-ide

- [ ] https://github.com/eclipse/codewind-eclipse

/assign @jgwest
/area iterative-dev

- [ ] https://github.com/eclipse/codewind-filewatchers

/assign @maysunfaisal 

- [ ] https://github.com/eclipse/codewind-che-plugin

/assign @micgibso
/area docs

- [ ] https://github.com/eclipse/codewind-docs

/assign @jagrag
/svt

- [ ] SVT

/assign @maysunfaisal 

- [ ] https://github.com/eclipse/codewind (Turbine)

/assign @rwalle61 
/area portal

- [ ] https://github.com/eclipse/codewind (Portal)
- [ ] https://github.com/eclipse/codewind-installer
- [ ] https://github.com/eclipse/codewind-java-profiler
- [ ] https://github.com/eclipse/codewind-node-profiler
- [ ] https://github.com/eclipse/codewind-operator

/assign @jingfuwang

- [ ] https://github.com/eclipse/codewind-odo-extension

/assign @makandre
/area appsody

- [ ] https://github.com/eclipse/codewind-appsody-extension

/assign @keithchong
/area openapi

- [ ] https://github.com/eclipse/codewind-openapi-vscode
- [ ] https://github.com/eclipse/codewind-openapi-eclipse

**Comment by tetchel** [comment]
https://github.com/eclipse/codewind/issues/2246

**Comment by maysunfaisal** [comment]
@tetchel thx, closing this as dup
