### ISSUE TITLE
[Docs] Add documentation for remote debug support in Codewind

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind#2651]
For this issue, https://github.com/eclipse/codewind/issues/2581, we added a file for debugging.

Now, we need to add remote debug info to the documentation, whether as a part of the existing `debugging.md` file or as a new file.

**Comment by sishida** [comment]
Talked to the IDE team today. Can work on documentation when the remote debug work progresses further in the IDEs.

**Comment by sishida** [comment]
Learned from Michael today that this issue will not be for 0.12.0.

**Comment by sishida** [comment]
To document for 0.12.0:
- Mention port forwarding.
- Need to log in using `kubectl` or `oc`.
- Same for VS Code and Eclipse.

**Comment by eharris369** [comment]
For remote debug:

All is the same as local debug except:

- kubectl or oc must be installed and you must be logged in to your cluster
- After restarting in debug mode, a port forward is automatically set up for the debug port of the application to a port on your local machine. In Eclipse, this port forward process shows in the Debug view along with the debug session itself. If you terminate this port forward it will also terminate the debug session. If you detach the debugger or restart the application in run mode, both the debug session and the port forward will be cleaned up automatically. The one exception is for Node.js applications where a chrome based browser is used for debugging. If you terminate the debug session in your browser you will need to terminate the associated port forwarding process in the Debug view of Eclipse manually.

Did we document opening a container shell for a remote application? It has the same requirement for kubectl or oc to be installed and the user to be logged in to the cluster.

**Comment by sishida** [comment]
From @eharris369:
Account for PR https://github.com/eclipse/codewind-eclipse/pull/722 in the documentation.

The change is that instead of creating a separate port forward launch when debugging remote Java projects, the port forward is added as a process to the debug launch. For Node.js projects the port forward is still a separate launch. 

The top level is the launch and then the 2 process are underneath it, one for the debug session (Debugging spr1 at ...) with all of the threads and one for the port forward (Debug port forward 60340:7777).

**Comment by eharris369** [comment]
Image to go with the above comment:
![remotedebug](https://user-images.githubusercontent.com/9484320/81741613-d5a59980-946c-11ea-9e69-e37a2de7942e.png)
