### ISSUE TITLE
SVT: [Eclipse]: Appsody Quarkus project does not auto restart after edit

### ISSUE THREAD

**Issue by mmulholl** [eclipse/codewind#2657]
**Codewind version:**  Codewind tech preview	0.11.0.v202004030754	
**OS:** Mac

**Che version:**
**IDE extension version:**
**IDE version:** Eclipse jee 2019-06
**Kubernetes cluster:**

**Description:**
Appsody Quarkus project does not restart after file edit.

**Steps to reproduce:**
1. Create a appsody Quarkus project
2. open application and change url to "/hello"  => hello is displayed
3. Modify  src/main/java/org/acme/quickstart/GreetingResource.java so that hello() method returns "othello", and save the file.
4. Application state remains running
5. open application and change url to "/hello"  => "hello" is displayed
6. Manually restart the project, wait for running
7. open application and change url to "/hello"  => "othello" is displayed.

**Workaround:**

**Comment by makandre** [comment]
In general, for appsody projects you would not see the project “restart” in Codewind, since changes are watched by the appsody controller and it rebuilds/restarts the application in place.

**Comment by makandre** [comment]
Btw, I think Quarkus stack is recently promoted to incubator status?  I recall it was experimental previously

**Comment by makandre** [comment]
Changes are synced correctly to PFE, and appear in the appsody application container.  But this is not triggering a hot replace for some reason.

If I shell into the appsody application container directly and make a change, it does trigger a hot replace.

**Comment by makandre** [comment]
Opened https://github.com/appsody/stacks/issues/753 for appsody team to have a look

**Comment by malincoln** [comment]
> Opened [appsody/stacks#753](https://github.com/appsody/stacks/issues/753) for appsody team to have a look

@makandre are you able to mark 753 as urgent/hot/stopship on their end for high priority?

**Comment by makandre** [comment]
@malincoln I can't but I pinged @neeraj-laad

**Comment by makandre** [comment]
A workaround is to manually build the project (from Codewind view, `Build` action on the project).  That would force a rerun of `appsody` to pick up the changes

**Comment by mmulholl** [comment]
Of course manual build works, just not really a workaround for a product which is meant to auto build. A workaround would be a way to rig auto-build.

**Comment by mmulholl** [comment]
As a note, Appsody Eclipse appears to have the same issue

**Comment by makandre** [comment]
In https://github.com/appsody/stacks/issues/753#issuecomment-614239965, it was discovered that when a java source file was changed, it appears we are also syncing over the `pom.xml` to PFE as well..  And this causes problems with Quarkus.

@tobespc @jgwest Are we syncing over files that have not changed for some reason?

**Comment by makandre** [comment]
The reason the `pom.xml` is touched even though it has not changed is because when a file is uploaded, it is written to `cw-temp` first, then the project there (which contains a copy of the pom) is copied to its real location in `/mounted-workspace`

I found that if the copy is done with `preserveTimestamps: true`, this will make Quarkus happy.  I'll put up a PR for this shortly.

**Comment by malincoln** [comment]
@makandre thanks for investigating further.  I guess the next step is to determine if we still need 753 from the Apposdy team or should cancel?

**Comment by makandre** [comment]
@malincoln I think they'll use 753 to track the underlying issue in the Quarkus stack, because if user does make a change to the `pom.xml` file, it crashes.

**Comment by mmulholl** [comment]
This now works in the latest driver.

**Comment by sghung** [comment]
@mmulholl if it works on the latest driver, can this issue be closed?

**Comment by sghung** [comment]
Are we keeping this issue open due to https://github.com/eclipse/codewind/issues/2699 ? I just want to check whether this can be closed due to Martin confirming, or whether we need to redo the PR and verify again

**Comment by makandre** [comment]
@mmulholl Could you re-verify that the new fix for #2699 didn't break Quarkus?  If it's all good then I think we can close this one

**Comment by jagraj** [comment]
We verified this issue during Codewind 0.11.0 release test cycle.This issue has been fixed. Closing it now.

**Comment by malincoln** [comment]
closing after discussion with Jag and as Martin is on vacation.
