### ISSUE TITLE
(metrics) SVT: Users can execute load tests with Default Open Liberty projects without injecting application metrics

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#2658]
**Codewind version:** 0.11.0
**OS:** Red Hat Enterprise Linux 7 (64 bit)

**Che version:** 7.9.0
**Kubernetes cluster:** Fyre Cluster with OCP 4.3

**Description:** Users can execute load tests with Default Open Liberty projects without injecting application metrics. We have been informed that we need to inject application metrics in order to retrieve the test results, if we are using a Default Open Liberty project. However, there is no documentation to support it. 

If users are allowed to do so, they won't see the test results and wonder what happened. If we inform them that they need to inject application metrics with this project type, then they will retrieve test results without having any problem.

<img width="1671" alt="Screen Shot 2020-04-09 at 3 34 44 PM" src="https://user-images.githubusercontent.com/49531960/78933690-af5c9a80-7a77-11ea-9659-cb865f0dad95.png">

https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/performance.md
https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/troubleshooting.md

@jagraj

**Comment by tobespc** [comment]
This is the correct behaviour, you can run load against any project, its whether you get to see the results on the performance page that is the issue (and that is down to whether metrics have been injected).  Load run is simply a case of sending data to an endpoint, something that doesn't require any additional packages.

However, I totally agree that the current scenario is confusing and for 0.12 we are going to add a lot of improvements to the dashboard to make it clear when you would see data and when not.

**Comment by tobespc** [comment]
Closing as this will be fixed by the change for #2687
