### ISSUE TITLE
SVT: Performance Dashboard doesn't work for some projects

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#266]
**Codewind version:** 0.3
**OS:** Windows 10 and MacOS Mojave (10.14.5)

**IDE extension version:** latest
**IDE version:** VS Code 1.37.1 

**Description:** Performance Panel doesn't work for some projects. Although this problem could be solved with the solution to the Application Monitor problem, I opened this to consider or be aware of the Performance Panel problem.

Does not work:
1.	Appsody Eclipse MicroProfile Template (Eclipse MicroProfile on Open Liberty & Open J9 using Maven java)
2.	Appsody Loopback4 Template (Loopback4 API Framework for Node.js)
3.	Appsody Spring Boot Default Template (Spring Boot using OpenJ9 and Maven)
4.	Appsody Spring Boot Kotlin Template (Spring Boot using OpenJ9 and Maven)

Works:
1.	Appsody Node.js Simple Template (Express web framework for Node.js)
2.	Appsody Node.js Scaffold Template (Express web framework for Node.js)

<img width="701" alt="Screen Shot 2019-08-23 at 9 29 31 AM" src="https://user-images.githubusercontent.com/49531960/63596157-9c4c9700-c588-11e9-820d-cd6d105a5ca9.png">

<img width="823" alt="Screen Shot 2019-08-23 at 9 29 54 AM" src="https://user-images.githubusercontent.com/49531960/63596162-9f478780-c588-11e9-8f63-22f9dc652bec.png">

<img width="1298" alt="Screen Shot 2019-08-23 at 9 28 20 AM" src="https://user-images.githubusercontent.com/49531960/63596081-69a29e80-c588-11e9-98fe-672120ee6493.png">

**Steps to reproduce:**
1. Install Codewind
2. Start Codewind
3. Create Appsody projects
4. Right click on the created projects
5. Click on "Open Performance Dashboard"

**Related issues:**
https://github.com/eclipse/codewind/issues/237
https://github.com/eclipse/codewind/issues/258

@jagraj

**Comment by tetchel** [comment]
this will be fixed along with https://github.com/eclipse/codewind/issues/258
