### ISSUE TITLE
SVT: Users are allowed to run more than one test at the same time in remote/hybrid scenarios

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#2660]
**Codewind version:** 0.11.0
**OS:** VM with Windows 10 (w. OKD/Openshift cluster)

**IDE extension version:** 0.11.0
**IDE version:** Code 1.43.2

**Description:** Users are allowed to run more than one test at the same time in remote/hybrid scenarios. This will eventually cause that any new load test gets stuck in "Requested". Once a load test gets stuck in "Requested", the Performance Dashboard feature will not work anymore.

_First scenario:_

![Screen Shot 2020-04-09 at 5 11 57 PM](https://user-images.githubusercontent.com/49531960/78941991-bd65e780-7a86-11ea-88e1-c96cc971193f.png)

![Screen Shot 2020-04-09 at 5 11 08 PM](https://user-images.githubusercontent.com/49531960/78941971-b4751600-7a86-11ea-96eb-2ac81fb1c227.png)

![Screen Shot 2020-04-09 at 5 11 25 PM](https://user-images.githubusercontent.com/49531960/78941982-b8a13380-7a86-11ea-9470-41925a07c115.png)

![Screen Shot 2020-04-09 at 5 12 33 PM](https://user-images.githubusercontent.com/49531960/78941987-ba6af700-7a86-11ea-9a73-72ff1a67a0d9.png)

_Second scenario:_

![Screen Shot 2020-04-09 at 5 53 14 PM](https://user-images.githubusercontent.com/49531960/78944030-01f38200-7a8b-11ea-99e0-58bc31f94161.png)

![Screen Shot 2020-04-09 at 5 48 46 PM](https://user-images.githubusercontent.com/49531960/78944042-061f9f80-7a8b-11ea-8cda-55d941941f1b.png)

![Screen Shot 2020-04-09 at 5 49 43 PM](https://user-images.githubusercontent.com/49531960/78944046-0881f980-7a8b-11ea-94ed-ed40e4877aa7.png)

![Screen Shot 2020-04-09 at 5 50 19 PM](https://user-images.githubusercontent.com/49531960/78944051-0ae45380-7a8b-11ea-9eb4-7379133c3c24.png)

**Steps to reproduce:**
1. Install and start Codewind 0.11.0
2. Use the recently installed 0.11.0 cwctl to deploy Codewind remotely
3. Create a new remote connection
4. Create a new image registry
5. Create some projects 
6. Wait until at least two projects are in "Running" state
7. Run a load test
8. Run a load test with another project while the previous load test is in progress

**Logs:**
[remote-codewind-pfe-1.txt](https://github.com/eclipse/codewind/files/4458826/remote-codewind-pfe-1.txt)
[remote-codewind-pfe-2.txt](https://github.com/eclipse/codewind/files/4458827/remote-codewind-pfe-2.txt)

@jagraj

**Comment by malincoln** [comment]
@tobespc pls assign when you return.  Thanks

**Comment by tobespc** [comment]
Changes have gone into 0.11.0 today to fix this, please retest with the latest changes.  Thanks

**Comment by sujeilyfonseca** [comment]
I verified this issue with the latest Codewind 0.11.0, and I no longer reproduce the problem.

![Screen Shot 2020-04-15 at 11 01 47 AM](https://user-images.githubusercontent.com/49531960/79353111-9f760800-7f08-11ea-8117-7ebc693e5344.png)
