### ISSUE TITLE
SVT: [VS Code] Projects are not being removed automatically from the VS Code workspace

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#2662]
**Codewind version:** 0.11.0
**OS:** VM with Windows 10

**IDE extension version:** 0.11.0
**IDE version:** Code 1.43.2

**Description:** Projects are not being removed automatically from the VS Code workspace. If I create a new project, it automatically is being added to the workspace, but if I remove the same project, it will remain in my workspace even after deleting the project files.

![Screen Shot 2020-04-09 at 5 58 07 PM](https://user-images.githubusercontent.com/49531960/78945738-07eb6200-7a8f-11ea-8abd-45c78ae036cb.png)

![Screen Shot 2020-04-09 at 6 20 37 PM](https://user-images.githubusercontent.com/49531960/78945740-09b52580-7a8f-11ea-81df-948d3289e664.png)

**Steps to reproduce:**
1. Install and start Codewind 0.11.0
2. Create a workspace, if not exists 
3. Create some projects
4. Projects will automatically be added to your workspace
5. Remove the previously created projects
6. Directories from the removed projects will remain in the workspace

@jagraj

**Comment by tetchel** [comment]
It's always been like this if you use a multi-root workspace but I agree the project folder should be removed when the project is deleted.

**Comment by sujeilyfonseca** [comment]
Thank you very much for addressing this issue, @tetchel!

I can no longer reproduce the problem with the latest Codewind.
