### ISSUE TITLE
(metrics) Local metrics and performance dashboards missing for appsody nodejs-express

### ISSUE THREAD

**Issue by csantanapr** [eclipse/codewind#2664]
**Codewind version:*0.9.0*
**OS:*MacOs*
**IDE version:*VSCode*

**Description:**
Create a new appsody using appsody 0.6.0 using nodejs-expresjs, add existing project, and when I right click on the application under "Local" metrics or performance dashboard shows up

**Steps to reproduce:**
appsody repo add kabanero https://github.com/kabanero-io/collections/releases/download/0.3.5/kabanero-index.yaml
mkdir ~/foo/nodejs_sample_application
cd ~/foo/nodejs_sample_application
appsody init kabanero/nodejs-express
appsody build

Select Codewind view, right Local, add existing Project
Apps runs fine and is "Running" state.

But I right click on the application and no option in the menu to select metrics or performance dashboards.

**Comment by tetchel** [comment]
This is a known issue https://github.com/eclipse/codewind/issues/2548 https://github.com/eclipse/codewind/issues/2423 which looks like it will be fixed in the next release.

**Comment by tobespc** [comment]
@csantanapr For the next release, we are going to be improving the way the dashboard provides feedback on what data is available for what project types, and also why some project types do not give any results.  Right now, there is an element of confusion around this whole area.

For your specific case, that is a known issue and we will be working to fix it for the next release

**Comment by tobespc** [comment]
retested this this morning following the recreate steps above and this is now resolved.  The fix will be in the 0.12 release
<img width="1185" alt="Screenshot 2020-04-28 at 09 53 20" src="https://user-images.githubusercontent.com/13151286/80467755-32b23300-8936-11ea-806e-a33cea909329.png">
<img width="1257" alt="Screenshot 2020-04-28 at 09 53 55" src="https://user-images.githubusercontent.com/13151286/80467780-39d94100-8936-11ea-92e4-12cca9a87900.png">
