### ISSUE TITLE
SVT: Appsody Spring Boot projects have several error messages in appsody.log

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#267]
**Codewind version:** 0.3
**OS:** Windows 10 and MacOS Mojave (10.14.5)

**IDE extension version:** latest
**IDE version:** VS Code 1.37.1 

**Description:** Appsody Spring Boot projects have several error messages in appsody.log

`` 
[Container] 2019-08-23 13:37:39.518  INFO 161 --- [io-8080-exec-58] i.j.internal.reporters.LoggingReporter   : Span reported: 4df12176ff52405d:be73254be59f98a0:4df12176ff52405d:1 – error
``
<img width="700" alt="Screen Shot 2019-08-23 at 10 03 19 AM" src="https://user-images.githubusercontent.com/49531960/63598336-56de9880-c58d-11e9-8d55-95472158ff17.png">

<img width="1624" alt="Screen Shot 2019-08-23 at 10 02 56 AM" src="https://user-images.githubusercontent.com/49531960/63598338-59d98900-c58d-11e9-88b0-b8acd5f50fbc.png">

<img width="823" alt="Screen Shot 2019-08-23 at 9 29 54 AM" src="https://user-images.githubusercontent.com/49531960/63596940-585a9180-c58a-11e9-8f39-a8bfa3c64400.png">

<img width="1571" alt="Screen Shot 2019-08-23 at 9 39 35 AM" src="https://user-images.githubusercontent.com/49531960/63596959-63152680-c58a-11e9-8502-b26da748abee.png">

**Steps to reproduce:**
1. Install Codewind
2. Start Codewind
3. Create Appsody Spring Boot projects
4. Right click on the created projects
5. Click on "Show all logs"

**Logs:**
Windows 10:
[cw-appsody-springboot-default_appsody.log](https://github.com/eclipse/codewind/files/3534844/cw-appsody-springboot-default_appsody.log)
[cw-appsody-springboot-kotlin_appsody.log](https://github.com/eclipse/codewind/files/3534845/cw-appsody-springboot-kotlin_appsody.log)

MacOS:
[cw-appsody-springboot-default_appsody.log](https://github.com/eclipse/codewind/files/3534872/cw-appsody-springboot-default_appsody.log)
[cw-appsody-springboot-kotlin_appsody.log](https://github.com/eclipse/codewind/files/3534869/cw-appsody-springboot-kotlin_appsody.log)

@jagraj

**Comment by sghung** [comment]
We'll take a look and most likely open an issue against appsody. Those messages don't seem to be codewind related and is specific to that appsody app.

**Comment by laven26** [comment]
I can work on this issue

**Comment by makandre** [comment]
Can we close on this old issue?  I don't think the messages from the springboot app has any affect on the functionality
