### ISSUE TITLE
SVT [IntelliJ] ArrayIndexOutOfBoundsException when creating project

### ISSUE THREAD

**Issue by naveenkaratekid** [eclipse/codewind#2674]
**Codewind version:**0.11
**OS:**Windows

**IDE extension version:**0.11
**IDE version:**IntelliJ Community 2019-3-3

**Description:**
When I created an Appsody Open Liberty project in IntelliJ, the project successfully creates, but I got this popup saying ```ArrayOutOfBoundsException```. The exception seems to be coming from the codewind plugin itself.

This seems to happen at random occurrences. When I created another project of the same template type, the error message didn't come back.

**Steps to reproduce:**
1. Create a new Appsody open liberty project in IntelliJ

Screnshot
<img width="1384" alt="Screen Shot 2020-04-14 at 12 36 12 PM" src="https://user-images.githubusercontent.com/19738071/79251627-68432080-7e4e-11ea-83b5-681a6ea7137f.png">

@jagraj

**Comment by keithchong** [comment]
This is a dup of https://github.com/eclipse/codewind/issues/2578 which we just fixed in master.  You will get this if the newly added project is the last node in the tree.

**Comment by jopit** [comment]
Maybe we should also put the fix into the 0.11.0 branch.

**Comment by keithchong** [comment]
Ok, will target 0.11.0

**Comment by keithchong** [comment]
Hi @naveenkaratekid , could you please verify and close this?  Thanks in advance.

**Comment by naveenkaratekid** [comment]
@keithchong I have just verified and I no longer see the ArrayOutOfBoundsException when I create a project. I will proceed and close this issue. Thanks Keith!
