### ISSUE TITLE
(metrics) SVT:[OCP 4.4]:Performance dashboard returns "Application is not available"

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#2679]
**Codewind version:** 0.11.0
**OS:** CoreOS

**Che version:** 7.9.2
**IDE extension version:** 0.11.0
**IDE version:** 7.9.2
**Kubernetes cluster:**
OCP 4.4 RC6 on VMWare and also OCP 4.4 RC8 on AWS.

**Description:**
I tried Codewind 0.11.0 relese images on OpenShift 4.4 RC6 installed on VMWare and also on OpenShift 4.4 RC8 installed on AWS. I created bunch of projects and most of the features work fine but some how performance dashboard page is not getting served and I am getting following message on the browser window (Application is not available).  I tried in both the environments and I am getting same result.

I will share these environments with DM to investigate this problem.

![image](https://user-images.githubusercontent.com/713849/79311886-1640e000-7ecc-11ea-80a8-e07de4037919.png)

Logs:

[performance.txt](https://github.com/eclipse/codewind/files/4479785/performance.txt)
[pfe.txt](https://github.com/eclipse/codewind/files/4479786/pfe.txt)

**Steps to reproduce:**
1. Install codewind 0.11.0 on OCP 4.4 
2. Create bunch of projects.
3. Open performance dashboard and I get blank page saying application not available.

**Workaround:**

**Comment by tobespc** [comment]
@malincoln should we be holding up 0.11 for this ?  I thought we were supporting 4.3 for 0.11 as 4.4 is not released yet? We can't even get a 4.4 driver on Public cloud to test with.  It's good to run a test to see if things work but any issues should be dealt with after we release 0.11.

**Comment by tobespc** [comment]
After testing with @jagraj this morning, we are able to get this to work from both mine and @markcor11 machines and for Jag using a private browser session.  Looks to be an issue with certificates.  

Removing the stop-ship label

**Comment by jagraj** [comment]
We tried to debug this morning and we are seeing these 503 errors mostly from Chrome browser and not from FireFox. We hit this problem even with OpenShift 4.4 RC8 console as well. At this point most likely this is not Codewind issue and we need to keep testing with future OCP 4.4 release candidates and see if we can reproduce the problem.

**Comment by johnmcollier** [comment]
I spun up the nightly OCP 4.4 driver individually and could reproduce as well 
<img width="1792" alt="Screen Shot 2020-04-15 at 6 01 45 PM" src="https://user-images.githubusercontent.com/6880023/79393395-4081b480-7f43-11ea-86a1-0c2acbfca6e9.png">

My guess is something in the OpenShift router changed such that the router config we're using for the performance dashboard is no longer valid.

**Comment by malincoln** [comment]
@tobespc @markcor11 we should target this release since this issue is on OCP 4.4 and get this in as soon as possible.

**Comment by tobespc** [comment]
currently there is not anywork to do for Portal. This is with @jagraj to retest with newer images as we were able to connect to the machine in question successfully using other browsers

**Comment by jagraj** [comment]
I moved to OCP 4.4 GA and verified bsic scenarios and all looking good. I am closiong this issue now.
Thanks for all your help in debugging these issues.
