### ISSUE TITLE
SVT: Cannot use old project names, even though they no longer exist

### ISSUE THREAD

**Issue by beccabau** [eclipse/codewind#268]
**Codewind version:** 0.3.0.v201908201823
**OS:** macOS Mojave Version 10.14.6

Eclipse/IDE Environment: Eclipse IDE for Enterprise Java Developers.
Version: 2019-06 (4.12.0)
Build id: 20190614-1200

**Description:**
I cannot reuse names I've used in previous installs of codewind on eclipse, even though they don't exist in the codewind-workspace folder (and .projects is empty, too)

ex:
![image](https://user-images.githubusercontent.com/13971834/63596926-51cc1a00-c58a-11e9-8068-ee5f98515fee.png)

![image](https://user-images.githubusercontent.com/13971834/63596955-614b6300-c58a-11e9-8457-5795616eeebe.png)

![image](https://user-images.githubusercontent.com/13971834/63599536-cfdeef80-c58f-11e9-91b9-57e60c4d285b.png)

**Steps to reproduce:**
I have performed as clean a reinstall as I could get (to my knowledge)--

- install Codewind (new software)
- Create projects
- uninstall codewind plugin from eclipse (but i didn't delete/stop the projects)
- uninstall codewind software from eclipse (make sure all the images go away in terminal)
- docker system prune -a (make sure all the images go away)
- delete codewind-workspace folder loclly
- (empty trash)
- get the latest codewind.zip
- in terminal, `export INSTALL_VERSION=latest`
- in terminal, `open /Applications/eclipse.app`
- Install latest codewind
- try to create project using a previously used name (but should no longer exist in your directory)

**Workaround:** 

- Create projects with names that have never been used before.

**Comment by tetchel** [comment]
can you reproduce this in vs code?

**Comment by eharris369** [comment]
Do the projects still exist in the Eclipse Project Explorer view?  If they do then this is normal for Eclipse.  You need to delete the projects in Eclipse as well.  Normally a user would delete the projects using Eclipse (right click on the project in the Codewind Explorer view and select remove, it will ask you if you also want to delete the project).  If deleted using Eclipse then this will not happen.
