### ISSUE TITLE
(metrics) Create helper function to identify project capabilities

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#2686]
We currently don't have a good way of determining for a project whether it
  - supports metrics (either with appmetrics or by using a /metrics endpoint)
  - performance data (needs appmetrics)
  - metrics injection (this should then give metrics and performance data)
  - ...

What we need it a function that if we send it a project, it can analyse the various parts of the source code to establish what it supports and whether injection could be done to improve things.

This is going to be complicated by the fact that some of the project styles (a style is now appsody style, codewind style, odo2 style, its not related to language at all) will have different ways of identifying its capabilities. Styles will be the way templates are grouped together

In its basic form, the function can be something as ugly as...

```
If (style is codewind) {
        if (language = xxx) {
            if (type = xxx) {
                Look for artifacts ?? in files ??
            }
        }
}
if (style is blah) repeat....
```

This function can then be used throughout codewind whenever we need to report back to the UI status on capabilities and why certain function are supported

**Comment by jcockbain** [comment]
## Kabanero templates

- [ ] **kabanero-node-express-scaffold**

- [ ] `/metrics`
- [ ] appmetrics endpoint

- [ ] **kabanero-node-express-simple**

- [ ] `/metrics`
- [ ] appmetrics endpoint

- [ ] **kabanero-node**

- [ ] `/metrics`
- [ ] appmetrics endpoint

- [ ] **kabanero-eclipse-microprofile**
- [ ] `/metrics`
- [ ] appmetrics endpoint

- [ ] **kabanero-open-liberty**

- [ ] `/metrics`
- [ ] appmetrics endpoint

- [ ] **kabanero-spring-boot-default**

- [ ] `/metrics`
- [ ] appmetrics endpoint

- [ ] **kabanero-spring-boot-kotlin**

- [ ] `/metrics`
- [ ] appmetrics endpoint

**Comment by james-wallis** [comment]
In summary:
We've been able to determine that most projects have a `/metrics` endpoint but Swift ones have `/actuator/metrics` instead. Additionally, some have `appmetrics-dash`, `javametrics-dash` or `swiftmetrics-dash`.

**Comment by james-wallis** [comment]
I've created a function in PFE that will perform a GET request on the known metric endpoints above. It currently returns an object that shows which metrics endpoints are active:
For example for an Appsody Node.js Express Scaffold Template
```javascript
{
  "/metrics": true,
  "/appmetrics-dash": true,
  "/javametrics-dash": false,
  "/swiftmetrics-dash": false,
  "/actuator/prometheus": false
}
```

The function pings the endpoints to determine whether they are available and also checks whether the `appmetrics-dash` endpoints are `appmetrics` ones and that the `/metrics` and `/actuator/prometheus` endpoints are valid prometheus endpoints.

Next step is to discuss with Toby how this is intended to be used (currently I've made an API) and the next steps.

**Comment by james-wallis** [comment]
I'll be changing the way the dashboard host is detected, currently we use a mixture of:
* Have metrics been injected?
* Is the app an Appsody one (if yes assume dashboard)
* Is the app an Open Liberty one
Which means that as we add more projectTypes we need to update the logic.

Instead we will ping all known dashboard endpoints and determine the dashboard based on this. The call to this function could happen when we receive a `projectStatusChanged` socket event from FileWatcher that shows the app as running so that each time the app re-starts we can update the dashboard list.

Two functions will change in Project.js, but their output will be the same:
```
getMetricsDashHost
getMetricsDashPath
```

**Comment by james-wallis** [comment]
@tobespc has reviewed and merged the PR for this.
In addition to the features described above a `/metrics/status` api was added so the performance dashboard could get the metricsCapabilities itself.
Further details in https://github.com/eclipse/codewind/pull/2748
/close
