### ISSUE TITLE
(metrics) Performance Dashboard needs to make it clear to users on supported capabilities

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#2687]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description of the enhancement:**

**Proposed solution:**

**Comment by sishida** [comment]
Adding the docs label and assigning myself to help with doc work.

**Comment by tobespc** [comment]
this is now implemented, removing portal and enhancement tags

**Comment by sishida** [comment]
Met with Toby. Closing this issue.
