### ISSUE TITLE
Blog page links don't work on the live site

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind#2688]
When I run the `./build.sh` script on macOS, it reports broken links for the `blog.html` page. 
- However, when you run `./serve.sh` and copy and paste the generated URL, the links to the blogs on the `blog.html` page work.
- Also, `linkchecker.bat` on Windows doesn't report the broken links from the blog page.

That said, though, the links are actually broken when you view them on the live site: https://www.eclipse.org/codewind/. If you attempt to click a blog page, a 404 appears instead.

This is a mystery for more than one reason:
1️⃣ How can we fix the broken links on the live site?
2️⃣ Why do the blog links work on the URL from `./serve.sh` but not on the live site?
3️⃣ Why do the `./serve.sh` script and the `linkchecker.bat` script differ?

**Comment by micgibso** [comment]
Fwiw, the Windows script that I ran this morning gave me five broken links on this PR: https://github.com/eclipse/codewind-docs/pull/532.

**Comment by AndyRWatson** [comment]
Please can we get the live blog link back to Pointing to medium until we know the underlying blog links are working. Thanks

**Comment by sghung** [comment]
I will look at this on Monday, one thing I did notice was:

https://www.eclipse.org/codewind/a-technical-autopsy-of-a-containerized-node-js-dependency-insights-microservice-application.html 

Does work. It could be eclipse.org requiring a *.html ending and does not allow pages to end without it

**Comment by sghung** [comment]
I believe when we run it on Jekyll, they do some redirect magic similar to .htaccess files. You can redirect pages to not have .html endings. However, eclipse.org doesn't allow that. This problem is hidden when running on Jekyll. To prevent this in the future, the `build.sh` script is the proper one to run. Further investigation needs to be done to compare the difference between `build.sh` and the `linkchecker.sh`

**Comment by sishida** [comment]
The blog links are now fixed, so I'm closing this issue.

I have opened this new issue https://github.com/eclipse/codewind/issues/2727 for investigating how to make the serve.sh script better match the Codewind website.
