### ISSUE TITLE
Importing existing projects docs easily misleading

### ISSUE THREAD

**Issue by deboer-tim** [eclipse/codewind#2689]
The documentation for importing existing projects at https://www.eclipse.org/codewind/importing-existing-projects.html is technically correct, but very easily misleading and confusing.

As an example we had a user with problems on Appsody Microprofile. Starting at the top of the page they looked at "What kind of projects can I add?" and it was far too easy to jump to the section on Microprofile (for Codewind style) without looking farther down the list to see that Appsody projects are called out separately.

IMHO this is a case where we need to explicitly call out the styles/patterns we support at the top level (Codewind, Appsody, odo) and drive users to the correct section for the one they're using. Maybe even on separate pages so that people won't accidentally scroll to the wrong one.

Many users aren't even going to understand which pattern they're using, so we may need to remind them at the top or link to other information on how to tell. Likewise they'll be coming here when they're having problems and trying to quickly find the right docs

This will usually be a page that people come to when they're having problems, and hence scanning quickly to find the right info, so brevity and clarity at the top is essential along with making it more obvious than normal when you're in the wrong place.

**Comment by j-c-berger** [comment]
I'll take this one, thanks!

**Comment by micgibso** [comment]
Closing as complete.
