### ISSUE TITLE
Enable HTTPS application support on Codewind

### ISSUE THREAD

**Issue by maysunfaisal** [eclipse/codewind#269]
**Codewind version:** latest
**OS:** Local/Kube

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:** OKD

**Description of the enhancement:**

Codewind needs to be able to ping an https application and support it. Currently, if a user brings in an https application; Codewind never is able to fully support it by detecting its health/endpoint.

**Proposed solution:** 

Introduce a `isHttps` setting that tells if an application is https enabled or not. Codewind will then be able to ping the appropriate www protocol.

**Comment by maysunfaisal** [comment]
@rajivnathan can you pls assign me the issue along with the iterative-dev label and docs label? I have to update the doc for the new setting that has been introduced.

**Comment by rajivnathan** [comment]
Waiting on https://github.com/eclipse/codewind/issues/404 before putting this one in.

**Comment by sishida** [comment]
@maysunfaisal and @rajivnathan Is this issue good to close?

I suppose there are no links to add since we have decided to move PR https://github.com/eclipse/codewind-docs/pull/139 into an article instead. :)
