### ISSUE TITLE
Codewind operator instructions don't mention privileged and anyuid requirements for OpenShift

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#2690]
**Description:**
The [installation instructions](https://github.com/eclipse/codewind-operator/blob/master/README.md) for the Codewind operator don't mention that Codewind needs to run as root and as privileged currently, and without running:
1. `oc adm policy add-scc-to-user privileged <codewind-service-account>`
2. `oc adm policy add-scc-to-user anyuid <codewind-service-account>`

Codewind will not deploy on OpenShift

**Comment by hhellyer** [comment]
@johnmcollier - Would you be able to raise a PR against the readme for this? Without having an OpenShift cluster it's hard to know where in the instructions to put this.

Does this apply to all levels of OpenShift or just 3.11/4.x?

Does this need to go into the 0.11.0 release, if you raise a PR against master I'm happy to do the merge to 0.11.0 if required.

**Comment by markcor11** [comment]
Codewind will deploy on OpenShift 3.11, 4, CRC and ROKS using the operator without the need to do those two commands anymore.

**Comment by johnmcollier** [comment]
@markcor11 Ahhhh, okay. That's a lot more intuitive then! My misunderstanding, so this can be closed.
