### ISSUE TITLE
SVT: PFE container died after creating several projects

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#2692]
**Codewind version:** 0.9.0
**OS:** MacOS

**IDE extension version:** 0.9.0
**IDE version:** 1.44.0

**Description:** I installed Codewind 0.9.0 on VS Code because I wanted to perform a migration scenario. I created several projects, and suddenly the connection was lost: 

<img width="1669" alt="Screen Shot 2020-04-13 at 2 23 53 PM" src="https://user-images.githubusercontent.com/49531960/79148860-39687400-7d94-11ea-9377-e278f58e80c8.png">

I tried a refresh, but it didn't work:

<img width="1669" alt="Screen Shot 2020-04-13 at 2 25 42 PM" src="https://user-images.githubusercontent.com/49531960/79148867-3c636480-7d94-11ea-8578-8f5618724c08.png">

I verified the running pods, and the `codewind-pfe` was no longer running:

```
(base) Sujeilys-MBP:IBM.codewind sfonseca$ docker ps
CONTAINER ID        IMAGE                                                     COMMAND             CREATED             STATUS              PORTS                       NAMES
e9895c9fe0f4        cw-cwdefaultpython-c1732160-7db2-11ea-b3c6-e746faddb2be   "python app.py"     13 minutes ago      Up 13 minutes       127.0.0.1:32776->5000/tcp   cw-cwdefaultpython-c1732160-7db2-11ea-b3c6-e746faddb2be
f23fc0102afc        eclipse/codewind-performance-amd64:0.9.0                  "npm start"         21 minutes ago      Up 21 minutes       127.0.0.1:9095->9095/tcp    codewind-performance
```

Following @jgwest comment on issue https://github.com/eclipse/codewind/issues/2640#issuecomment-613595594, it looks like PFE container died with the following message:

```
[13/04/20 18:23:22 /portal/modules/LoadRunner.js] [INFO] Loadrunner has disconnected
/portal/modules/LoadRunner.js:428
      this.project.loadInProgress = false; 
                                  ^

TypeError: Cannot set property 'loadInProgress' of null
    at Socket.socket.on (/portal/modules/LoadRunner.js:428:35)
    at Socket.Emitter.emit (/portal/node_modules/component-emitter/index.js:133:20)
    at Socket.emit (/portal/node_modules/socket.io-client/lib/socket.js:138:10)
    at Socket.onclose (/portal/node_modules/socket.io-client/lib/socket.js:214:8)
    at Manager.<anonymous> (/portal/node_modules/component-bind/index.js:21:15)
    at Manager.Emitter.emit (/portal/node_modules/component-emitter/index.js:133:20)
    at Manager.onclose (/portal/node_modules/socket.io-client/lib/manager.js:502:8)
    at Socket.<anonymous> (/portal/node_modules/component-bind/index.js:21:15)
    at Socket.Emitter.emit (/portal/node_modules/component-emitter/index.js:133:20)
    at Socket.onClose (/portal/node_modules/engine.io-client/lib/socket.js:725:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! codewind-portal@1.0.0 prod: `node server.js`
npm ERR! Exit status 1
```

**Logs:**

[codewind.log](https://github.com/eclipse/codewind/files/4471159/codewind.log)
[codewind-pfe.txt](https://github.com/eclipse/codewind/files/4471160/codewind-pfe.txt)
[filewatcherd-1.log](https://github.com/eclipse/codewind/files/4471161/filewatcherd-1.log)

**Workaround:** Stopping/Starting Codewind again should re-establish the connection.

@jagraj

**Comment by hhellyer** [comment]
This is occurring in 0.9.0 and we've restructured the code a lot since then. It does look like it's still possible though so I'm going to take a look and see if there's a way we can make this more robust when `project` may be null.

**Comment by sujeilyfonseca** [comment]
Thank you very much for working on this issue, @hhellyer!

I have not been able to reproduce the problem again with the latest 0.12.0 images. I'll proceed to close the issue.
