### ISSUE TITLE
SVT: [VS Code] Codewind's home page is not working properly on Linux

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#2698]
**Codewind version:** 0.11.0
**OS:** Linux

**IDE extension version:** 0.11.0
**IDE version:** 1.44.0

**Description:** Codewind's home page is not working properly on Linux

![Screen Shot 2020-04-16 at 1 16 43 PM](https://user-images.githubusercontent.com/49531960/79486996-90b15300-7fe5-11ea-85da-93cf80a8924f.png)

@jagraj

**Comment by tetchel** [comment]
Please post a screenshot of the developer tools' console

**Comment by sujeilyfonseca** [comment]
I tried to reproduce the problem to take a screenshot of the developer tools console, but the problem seems to be intermittent. Besides, the page eventually loads as expected. Therefore, I'll proceed to close this issue.

**Comment by tetchel** [comment]
Still let me know if you can reproduce it, because this is the last thing we want users seeing on their first startup!
