### ISSUE TITLE
[Eclipse] Unexpected radio button default on Project selection panel after choosing local file system folder

### ISSUE THREAD

**Issue by mattcolegate** [eclipse/codewind#2704]
**Codewind version:** latest 17/04/2020
**OS:** Windows 10

**Che version:** N/A
**IDE extension version:** latest Eclipse 17/04/2020 (from source)
**IDE version:** Eclipse 2019-06 (4.12.0)
**Kubernetes cluster:** N/A

**Description:** On the Add existing project to Codewind: Project Selection panel, if a user selects an existing project from the file system and uses the Browse button to select the project folder, when focus returns to the panel the radio button resets to selecting the project from the workspace. The user must re-select existing project from the file system radio button to proceed.

**Steps to reproduce:**

1. Start Codewind
1. Right click Local (Running), select Add Existing Project....
1. Choose the radio button 'Select a project from the file system'
1. Use the Browse button to select a valid project folder and click 'Select Folder'.
1. Note that the radio button selection is now on 'Select a project from the workspace' and the Path: field is greyed out.

**Workaround:** 

None

**Comment by eharris369** [comment]
Thank you for catching this!

**Comment by eharris369** [comment]
Fixed by PR: https://github.com/eclipse/codewind-eclipse/pull/707

**Comment by mattcolegate** [comment]
Verified - selection now remains with Select from File system.
