### ISSUE TITLE
Can't build Codewind Spring project on Open Shift

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#2708]
Trying to build a Codewind style Spring project on Open Shift results in the following error:

`pod for helm release cw-spring1-8864d7c0-80a9-11ea-967c failed to start`

Here is the log with log level set to trace: 
[spring1log.txt](https://github.com/eclipse/codewind/files/4493534/spring1log.txt)

And the build log: 
[docker.build.log](https://github.com/eclipse/codewind/files/4493037/docker.build.log)

I created a new instance of Codewind this morning so should be the latest.

**Comment by markcor11** [comment]
Could you confirm that the cluster was prepared with :

```
$ oc adm policy add-scc-to-group privileged system:serviceaccounts:<CodewindNamespace>
$ oc adm policy add-scc-to-group anyuid system:serviceaccounts:< CodewindNamespace>
```

These two commands are required for the old way of installing Codewind via cwctl granting the pods in the namespace the required permissions. (These commands are not required by the codewind-operator)

**Comment by eharris369** [comment]
Closing as duplicate of https://github.com/eclipse/codewind/issues/2709
