### ISSUE TITLE
Codewind node.js project stuck in starting state on Open Shift

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#2709]
I created a Codewind style node.js project on Open Shift and it is stuck in starting state:

```
Timeout: Pinging http://:3000/health and http://:3000/. The application is taking longer than expected to start. Please check the application logs for problems and ensure the project's 'healthCheck' setting is correct. Last error message received: Failed to get application status: connect ECONNREFUSED 172.21.250.107:3000
```

Logs with log level set to trace: 
[node1log.txt](https://github.com/eclipse/codewind/files/4493587/node1log.txt)

docker.build.log: 
[docker.build.log](https://github.com/eclipse/codewind/files/4493130/docker.build.log)

Also the app.log appears to be cut off: 
[app.log](https://github.com/eclipse/codewind/files/4493133/app.log)

Created a new instance of Codewind this morning so it should be the latest.

**Comment by eharris369** [comment]
Found this in the log:

```
7/04/20 14:41:36 node1] [ERROR]^[[39m executeBuildScript : 295 | tar: scripts: Cannot mkdir: Permission denied
ipts/noderun.sh: Cannot open: No such file or directory
ting with failure status due to previous errors

7/04/20 14:41:36 node1] [ERROR]^[[39m executeBuildScript : 295 | command terminated with exit code 2

7/04/20 14:41:36 node1] [ERROR]^[[39m executeBuildScript : 295 | exec failed: container_linux.go:345: starting container
7/04/20 14:41:36 node1] [ERROR]^[[39m executeBuildScript : 295 | command terminated with exit code 1
```

**Comment by eharris369** [comment]
Adding iterative-dev given the error message.

**Comment by eharris369** [comment]
If I do a kubectl exec into the container from the command line I am not logged in as root but as some other user and cannot create /scripts dir either.

**Comment by eharris369** [comment]
Looks like something similar for Appsody node.js projects though the behaviour is a little different where it goes to stopped state instead of getting stuck in starting state. Seems like a permission issue as well though:
```
Running development environment...
Pulling docker image docker.io/appsody/nodejs-express:0.4
Running command: buildah pull docker.io/appsody/nodejs-express:0.4
e5c3fb843a70dc522d00e80f7c67aabe8b08c2bfd16ddb4440bbc49556a50976
Successfully added your project to /codewind-workspace/.appsody/project.yaml
Attempting to apply resource in Kubernetes ...
Running command: kubectl apply -f /codewind-workspace/nodeA1/app-deploy.yaml
Attempting to apply resource in Kubernetes ...
Running command: kubectl apply -f /codewind-workspace/nodeA1/app-service.yaml
Getting the logs ...
Running command: kubectl logs deployment/cw-nodea1-da235c40-830f-11ea-b705 -f "--pod-running-timeout=2m"
[Container] Error from server (BadRequest): container "cw-nodea1-da235c40-830f-11ea-b705" in pod "cw-nodea1-da235c40-830f-11ea-b705-56fc54898-6d9fg" is waiting to start: PodInitializing
Getting the logs ...
Running command: kubectl logs deployment/cw-nodea1-da235c40-830f-11ea-b705 -f "--pod-running-timeout=2m"
[Container] Running APPSODY_PREP command: npm install --prefix user-app
[Container] npm ERR! correctMkdir failed to make directory /.npm/_locks
[Container] npm ERR! code EACCES
[Container] npm ERR! syscall mkdir
[Container] npm ERR! path /.npm
[Container] npm ERR! errno -13
[Container] npm ERR! 
[Container] npm ERR! Your cache folder contains root-owned files, due to a bug in
[Container] npm ERR! previous versions of npm which has since been addressed.
[Container] npm ERR! 
[Container] npm ERR! To permanently fix this problem, please run:
[Container] npm ERR!   sudo chown -R 1000560000:0 "/.npm"
[Container] [Error] FATAL error APPSODY_PREP command received an error.  The controller is exiting: exit status 243
```

**Comment by eharris369** [comment]
Possibly a similar issue with Appsody Spring projects:
```
[Warning] Could not stat mount path: /root/.m2/repository
[Warning] Could not mount /root/.m2/repository:/mvn/repository because the local file was not found.
[Warning] The stack image does not contain APPSODY_DEPS
[Warning] Could not stat mount path: /root/.m2/repository
[Warning] Could not mount /root/.m2/repository:/mvn/repository because the local file was not found.
```

The full log does not say anything about sharing so it does not look the same as: https://github.com/eclipse/codewind/issues/1690
[appsody.log](https://github.com/eclipse/codewind/files/4504068/appsody.log)

**Comment by eharris369** [comment]
Regarding the app.log being cut off, looking at the inspect output for the pod it has:
    Args:
      tail
      -F
      /app/package.json

**Comment by eharris369** [comment]
If I use the Codewind operator then I have no problem creating node.js, Spring or MicroProfile projects. I don't think it is because it is a different version of Codewind because the remote projects have debug in their capabilities. @tobespc Should we not use cwctl to create Codewind instances anymore?

**Comment by markcor11** [comment]
Could you confirm that the cluster was prepared with : 

```
$ oc adm policy add-scc-to-group privileged system:serviceaccounts:<CodewindNamespace>
$ oc adm policy add-scc-to-group anyuid system:serviceaccounts:< CodewindNamespace>
```

These two commands are required for the old way of installing Codewind via cwctl granting the pods in the namespace the required permissions. (These commands are not required by the codewind-operator)

**Comment by eharris369** [comment]
Yes I run these before creating a new Codewind instance (not sure if I really need to run them every time but I do it just in case):
```
    oc adm policy add-scc-to-group anyuid system:serviceaccounts:codewind
    oc adm policy add-scc-to-group privileged system:serviceaccounts:codewind
```
And then use this to create the Codewind instance:
```
  cwctl --insecure install remote \
  --namespace {your_namespace}  \
  --kadminuser admin \
  --kadminpass <keycloakPassword>  \
  --krealm codewind \
  --kclient codewind  \
  --kdevuser developer \
  --kdevpass  <userPassword>
  --ingress <ingress domain - the cluster domain should work>
```

I just tried it again and got the same problem.

**Comment by eharris369** [comment]
Closed #2708 and #2710 as duplicates of this one so that we don't have to put comments in all 3 of them.

**Comment by markcor11** [comment]
One of the rules for deploying into OpenShift using cwctl are that Keycloak and Codewind should not be installed into the same namespace, All-In-One install should not be used for OpenShift. Our docs mention using the cwctl commands with the flags `--konly` to install the Keycloak deployment and `--kurl` to aim a new Codewind deployment to an existing Keycloak deployment. 

Just for testing, could you try creating a new deployment of Codewind using the same Keycloak you already have, but create the Openshift namespace first, run the policy adm commands then run cwctl with the --kurl flag.

Finally, which version of Openshift and Codewind are you using ?

**Comment by eharris369** [comment]
The OpenShift version is 4.3.12. Codewind should be the latest development build. I want to do some work on debug and then I will get back to this.

**Comment by eharris369** [comment]
I have it working now. Thanks for all of your help!
