### ISSUE TITLE
Build fails for Codewind microprofile project on Open Shift

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#2710]
The build fails for a Codewind style microprofile project on Open Shift with error:

`Application build failed. Please check the log in the build log view for more details.`

Logs with log level set to trace: 
[mp1log.txt](https://github.com/eclipse/codewind/files/4493690/mp1log.txt)

docker.build.log: 
[docker.build.log](https://github.com/eclipse/codewind/files/4493304/docker.build.log)

I created a new Codewind instance this morning so it should be the latest.

**Comment by markcor11** [comment]
Could you confirm that the cluster was prepared with :

```
$ oc adm policy add-scc-to-group privileged system:serviceaccounts:<CodewindNamespace>
$ oc adm policy add-scc-to-group anyuid system:serviceaccounts:< CodewindNamespace>
```

These two commands are required for the old way of installing Codewind via cwctl granting the pods in the namespace the required permissions. (These commands are not required by the codewind-operator)

**Comment by eharris369** [comment]
Closing as duplicate of https://github.com/eclipse/codewind/issues/2709
