### ISSUE TITLE
(metrics) Provide ability to disable authentication for open metrics

### ISSUE THREAD

**Issue by scottkurz** [eclipse/codewind#2712]
In: https://github.com/eclipse/codewind/issues/1804  it was discussed how to use the MP Metrics endpoint to populate dashboard info rather than the earlier option.

As I pointed out in [this](https://github.com/eclipse/codewind/issues/1804#issuecomment-595320738) comment, the java-openliberty stack protects this endpoint with a generated password.

One option would be for codewind to look into the container and dig out the password following [this](https://github.com/appsody/stacks/blob/master/incubator/java-openliberty/README.md#metrics-password) approach.   

I recognize, though, that this would not be preferred from the codewind point of view, since codewind doesn't want to have to have much knowledge of particular stacks details.

**Comment by tobespc** [comment]
This can be taken off tech topic as a solution is in progress

**Comment by tobespc** [comment]
A couple of things I'm looking at right now as options

  * Codewind could actually add into the server.xml the html to turn authentication off when developing 
  * The injection of javametrics that we already support in openliberty (non appsody) is expanded out to appsody stacks (this is something we want to do anyway)

**Comment by tobespc** [comment]
After discussions with @scottkurz and various members of the cloud team, the solution we will put in place is for codewind to offer the ability to developers to remove authentication for mpmetrics when codewind builds/run the project.  This is a very similar concept to the existing inject metrics function.  This will require a new check box (not necessarily on the IDE, could be on perf dash) to let users select to remove authentication.  We would then modify the server.xml of the project to add in the line
 ```
<mpMetrics authentication="false"/>
```

**Comment by tobespc** [comment]
For this to work, rather than modify the current server.xml at build time to add in the 
```<mpMetrics authentication="false"/>```, its more typical for Open Liberty to put that in a separate file.  

This means someone looking within the container has a better idea of what came from where.

We can have a file with a name like:  configDropins/defaults/cw-disable-mpmetrics-auth.xml
with contents of:

```
<server>
 <mpMetrics authentication="false"/>  
</server>
```
That would be placed into the target dir at runtime

**Comment by markcor11** [comment]
I'm working on the UI part,  James is working on the API part

**Comment by tobespc** [comment]
rather than target dir, we could add this into cw-temp like we do for inject metrics

**Comment by james-wallis** [comment]
As I understand it this issue needs to be fixed for both Codewind style Open Liberty applications and Appsody ones.

**Codewind style**
The Open Liberty template comes with metrics authentication disabled by default so we shouldn't run into the issue described.
I've been looking into it incase we do in the future and it seems that the Dockerfile provided ignores the `configDropins` directory as its not added into the generated zip file when `mvn` install is run. 
This means we need to both:
* Change the Dockerfile to add in `configDropins` if it exists (we'll have to ensure it always does once we've added this line).
* Add the `configDropins/defaults/cw-disable-mpmetrics-auth.xml` Toby described above in `cw-temp`.

As the template has authentication off by default I am not sure we want to invest time in adding this feature when it won't be used.

**Appsody**
Appsody doesn't use `cw-temp` for syncing and instead creates a docker volume that the users code is kept in, this means adding a file to the container will add it to the users file system.
The only way, however, to make changes to the users code and disable authentication is to:
* Have PFE perform a `docker cp` of the `configDropins/defaults/cw-disable-mpmetrics-auth.xml` into the `user-app` directory of the Open Liberty container.

In the past we've said we shouldn't do anything extension specific and this solution would be doing something very specific for Appsody. Do we want to add this or just explain how the user can change this?

**Comment by makandre** [comment]
@james-wallis For Appsody, `cw-temp` is still used.  Files from user project is sync to PFE and written first to `cw-temp` just like other Codewind projects.  The difference comes next as to where the project is then copied to: for Codewind projects they are copied to `/codewind-workspace`.  For Appsody they are copied to `/mounted-workspace` (this is bind-mounted to `~/codewind-data`)

**Comment by james-wallis** [comment]
@scottkurz I'm having trouble with the `mvn liberty:dev` hot-reload as it is missing the creation of the disable authentication file. 
I've created some simple code that creates an `overrides` directory and then a file with the authentication set to false which is working to fix this issue. In this case it does not see the authentication file be created and the server does not restart. 
When the `overrides` directory already exists, it does see the file creation. 

Is this a bug with the `mvn liberty:dev` hot-reload where is does not see a file created straight after a directory?

**Comment by markcor11** [comment]
Dashboard part is done - PR https://github.com/eclipse/codewind/pull/2868 has the new capabilities panel with the revised UX.  We will need a followup dashboard PR to activate the action button to call the new `disable authentication` API once it becomes available. 

The capabilities panel will now appear at top of Dashboard on launch and can be collapsed or expanded using the action button in the top right corner of the page.  Here's how it would appear with the button visible eg: 

![Screenshot 2020-05-07 at 09 26 54](https://user-images.githubusercontent.com/28102564/81275982-4e11f200-904a-11ea-982e-518c55ee002f.png)

**Comment by scottkurz** [comment]
> @scottkurz I'm having trouble with the `mvn liberty:dev` hot-reload as it is missing the creation of the disable authentication file.

@james-wallis  - that's interesting.   I just tried myself and couldn't recreate the problem, either inside an appsody container or outside (just running `mvn liberty:dev` on my laptop host system).
I tried a few variants... the only time I had problems was once when I accidentally named the "overrides" directory just "override" (no 's') and then tried to 'mv' it to the correct name (I had to "nudge"it to get the dropin file detected). 

We have had some problems before with dev mode detecting changes from inside the container, when the changes happen to bind mounted files, especially on Windows.

Do you see the same problem if you run outside the container (just `mvn liberty:dev`) ?

You are using path:  **src/main/liberty/config/configDropins/overrides** right?

If you can recreate this, please add your OS + Docker engine versions and maybe we should open an issue on the liberty-maven-plugin.

**Comment by james-wallis** [comment]
> and then tried to 'mv' it to the correct name (I had to "nudge"it to get the dropin file detected)

@scottkurz That seems to describe what is happening in the container but I'm getting it just by creating the directory and file not by renaming it.

I've tested it locally outside the container by
1. `mv`ing the file into the `src/main/liberty/config/configDropins/overrides` directory, the file change is picked up fine so no issues.
2. Creating an empty file in the `src/main/liberty/config/configDropins/overrides` directory and then populating it. Still no issue.
3. Created some dummy Node.js code that creates the overrides directory and the file (taken this from our disable auth code). Using this method I am able to recreate the issue.

**Node code:**
```javascript
const fs = require('fs-extra');
const path = require('path');

async function doStuff() {
  const overridesDir = path.join(__dirname, 'src/main/liberty/config/configDropins/overrides');
  const contents = '<server>\n\t<mpMetrics authentication="false"/>\n</server>\n';
  const fileName = 'codewind-override-disable-mpmetrics-auth.xml';
  const filePath = path.join(overridesDir, fileName);
  await fs.ensureDir(overridesDir);
  await fs.writeFile(filePath, contents);
}
doStuff().catch(err => console.error(err));
```
Recreate steps:
```bash
git clone https://github.com/OpenLiberty/sample-getting-started.git
cd sample-getting-started
touch app.js (and copy the code above into it)
npm install fs-extra
mvn liberty:dev

# From a separate terminal run to keep the liberty server running
node app.js
```
As you said in your comment above, I'm able to nudge the file (in my case by opening it in VSCode and saving it), the liberty server then picks up the file change and disables the metrics auth.
Am running `MacOS Mojave 10.14.6`.

**Comment by james-wallis** [comment]
/pipeline verify
In addition, the PR has been merged for this issue (uses a rebuild rather than just adding the file to guarantee the metrics auth has been disabled).

**Comment by james-wallis** [comment]
/pipeline in progress
The UI part of this is still in progress

**Comment by markcor11** [comment]
Not happy with the UX.  The project needs to be restarted to pick up the changes but the capabilities panel does not show the current project status suggesting the project is still running at all times.

Reworked the feature so that the panel now closes after the /metrics/status API accepts the request to disable authentication.  Notifications then provide commentary on project bounce status.

**Comment by scottkurz** [comment]
Tagging @uberskigeek to verify (though last comment suggests it's not ready yet).

**Comment by tobespc** [comment]
not quite ready, have tested it and it does work but needs changes

**Comment by scottkurz** [comment]
@james-wallis I can't think why it would matter that you were using `node` to write the override XML.   In any case, I did test your recreate instructions (outside a container, since you didn't mention appsody) and it continues to work fine for me on Win 10.   

Not sure it's worth opening an issue on https://github.com/OpenLiberty/ci.maven  if it's not more recreatable, but it's an option.

**Comment by micgibso** [comment]
Docs: current metrics dashboard topic needs updating to include new panel at top: https://www.eclipse.org/codewind/metrics-dashboard.html

**Comment by markcor11** [comment]
@micgibso we should probably explain what the capabilities panel is and does, its part of the performance dashboard so it should probably go somewhere on here : https://www.eclipse.org/codewind/performance.html

**Comment by micgibso** [comment]
Use Playback call demo from May 19, https://ibm.ent.box.com/v/codewindplayback/file/667477144246
30 minutes 10 seconds in to document the panel.

**Comment by scottkurz** [comment]
@tobespc @james-wallis can you please confirm the version of codewind to use to verify (and any other prereqs)?   Thx.

**Comment by scottkurz** [comment]
v0.13.0?

**Comment by tobespc** [comment]
yes, 0.13
