### ISSUE TITLE
Add Codewind logos and media to a repo

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind#272]
We need to upload our logo and media images to a Codewind repo.

Should we put the content in a "Media" or "devAdvocacy" folder in the existing Eclipse/Codewind repo, or should we create a new Codewind-media or Codewind-devAdvocacy repo?

We'll look at other repositories and projects to see how they have organized their content.

**Comment by sishida** [comment]
Today I looked at other open source projects and noticed folders for logos/artwork in the main repos of the projects. I don't think we need a separate repo for media. Rather, a media folder in the main `codewind` repo should be good.

**Comment by beccabau** [comment]
Yes, this is something we are discussing! Please assign to me.

**Comment by micgibso** [comment]
@sishida Something else to consider for your folders work perhaps?
