### ISSUE TITLE
Codewind operator install and setup instructions did not work

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#2720]
I was trying to install the Codewind operator using the instructions here: https://www.eclipse.org/codewind/remote-deploying-codewind.html but ran in to the following problems:

- In Add a new user to Keycloak, Step 1 says to copy the url into a browser and then Step 2 says to click on Users but first the user needs to click on **Administration Console**.
- After they click on **Administration Console** then need to log in. The default login is _admin_ with password _admin_. The instructions should also tell the user to change the password and re-login.

Here is the relevant information from the Codewind operator readme:

```
    Click Administration Console from the link provided.
    Log in to Keycloak using the Keycloak admin credentials.
        username: admin
        password: admin

IMPORTANT: After you log in, change the admin password by clicking the Admin link on the page. Then choose Manage Account / Password and set a new replacement administrator password.

    Switch back to the admin console using the link or log out and log back in to Keycloak as the admin user with your new admin password.
```

**Comment by sishida** [comment]
PR merged. Closing the issue.
