### ISSUE TITLE
Confusing error message from Codewind operator install.sh script

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#2721]
I created a user using my intranet id `myname@ca.ibm.com` and then tried to create a Codewind instance `./install.sh codewind -n cweh0420b -u myname@ca.ibm.com`
but got this error message:

```
The Codewind "cweh0420b" is invalid: spec.username: Invalid value: "": spec.username in body should match '^[A-Za-z0-9/-]*$'
```

Even though it complains that the name (cweh0420b) is invalid it is really the user name that it did not like.

**Comment by markcor11** [comment]
That message comes directly from the Kubernetes API.  It's saying the Codewind Custom Resource you are trying to create called "cweh0420b" is invalid because the username field contains invalid characters.

**Comment by eharris369** [comment]
It would be nice if it filled in the invalid value `Invalid value: ""`.
