### ISSUE TITLE
update cwctl to recognise DOCKER_HOST config

### ISSUE THREAD

**Issue by AndyRWatson** [eclipse/codewind#2724]
**Codewind version:**  0.11.0
**OS:**   ALL local

**Che version:**    n/a
**IDE extension version:**   0.11.0
**IDE version:**    vscode/eclipse/intellij
**Kubernetes cluster:** n/a (?)

**Description of the enhancement:**

From working with @bsteinfeld for the SNL project,  we identified an issue where local codewind was not honouring alternative docker configurations,  specifically around $DOCKER_HOST environment variables vs current default behaviour using /var/run/docker.sock

Working with @johnmcollier and @hhellyer it looks like we should update cwctl to recognise alternate configurations.  

**Proposed solution:** 

Update codewind local to recognise alterate docker configurations via $DOCKER_HOST

**Comment by AndyRWatson** [comment]
/ assign @hhellyer

**Comment by hhellyer** [comment]
I've put a branch of hacks (that should not be merged) here: https://github.com/hhellyer/codewind-installer/tree/docker_client_opts_dev
The changes seem to be enough to get codewind started and a project created. I will work on productising them more and put up a proper branch.

**Comment by AndyRWatson** [comment]
Looks good
