### ISSUE TITLE
Create Guides webpage to host all guides and quick guides

### ISSUE THREAD

**Issue by MelHopper** [eclipse/codewind#2725]
**Issue**
Create a webpage to host all guides and quick guides, in the same way that we have a codewind.dev/blogs page to host all blogs.

**solution**

- [ ] create a webpage to host all guides and quick guides, using the same CSS as used for the blogs page at codewind.dev/blogs

- [ ] Add a button to the Codewind.dev website header, titled 'Guides', that links to the new Guides webpage

**To note**

- This issue will be actioned via a PR that will NOT be merged until a guide is created and ready to be published. At this stage, the PR can be merged (target: 0.12.0)
- The new branch will contain the new webpage, ready to be tested with a guide by @sishida, @j-c-berger and @MelHopper

**Variables**
- URL: https://www.eclipse.org/codewind/guides.html
- Location of markdown files: https://github.com/eclipse/codewind-docs/tree/master/docs/_guides
- Location of images used in guides: codewind-docs/docs/images/guides
- Location of Guides link on website header: next to 'blogs' so the header reads: 'docs', 'news', 'blog', 'guides'

**Comment by sishida** [comment]
The folder for the guide Markdown files, https://github.com/eclipse/codewind-docs/tree/master/docs/_guides, is merged and ready to have files added to it. 👍

**Comment by sghung** [comment]
I created the guides PR here: https://github.com/eclipse/codewind-docs/pull/553 

- The guides link is on the top menu
- I add a sample guide that follows the required format
- The guides page will behave the same as the blog page

We can make changes once we have a guide ready

**Comment by jcockbain** [comment]
/pipeline verify

@MelHopper - would you say this issue is complete now?

**Comment by MelHopper** [comment]
Verified. @micgibso please can you close this issue? Thanks.
