### ISSUE TITLE
Topic 'making a code change' for the Eclipse Che tutorial does not exist in the ToC

### ISSUE THREAD

**Issue by MelHopper** [eclipse/codewind#2735]
The topic che-codechange.md is linked from the penultimate step of the Eclipse Che tutorial, che-createcodewindworkspace.md

However, this topic does not show up in the ToC.

Solution: Add the topic che-codechange.md into the ToC after createcodewindworkspace.md

**Comment by sishida** [comment]
PR merged. Closing this issue.
