### ISSUE TITLE
VSCode extension fails to start on Ubuntu

### ISSUE THREAD

**Issue by BethGriggs** [eclipse/codewind#2738]
**Codewind version:** 0.11.0
**OS:** Linux Ubuntu

**IDE extension version:** 0.11.0
**IDE version:** VSCode 1.41.1

**Description:**

I cannot start the VSCode extension once it is installed. It fails to start with the following error:

```
==> created file /home/ibmuser/.codewind/0.11.0/home/ibmuser/.codewind/docker-compose.yaml
==> environment structure written to /home/ibmuser/.codewind/docker-compose.yaml
System architecture is:  amd64
Host operating system is:  linux
Attempting to find available port
Port 10000 Available
Please wait while containers initialize...  
Version in "/home/ibmuser/.codewind/docker-compose.yaml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
{"error":"DOCKER_COMPOSE_START_ERROR","error_description":"exit status 1"}
==> End cwctl --json start -t 0.11.0
```

The file `/home/ibmuser/.codewind/docker-compose.yaml` does not exist. The path `/home/ibmuser/.codewind/0.11.0/home/ibmuser/.codewind/docker-compose.yaml` quoted in the error also does not exist. 

I am also prevented from removing the Codewind images via the VSCode extension UI:

```
Removing Codewind docker images..
System architecture is:  amd64
Host operating system is:  linux
Please wait whilst images are removed...  
.IOError: [Errno 2] No such file or directory: '/home/ibmuser/.codewind/docker-compose.yaml'
{"error":"IMAGE_REMOVE_ERROR","error_description":"exit status 1"}
==> End cwctl --json remove local -t 0.11.0
```

I have tried the following and all result in the same error:
 - manually removing the `.codewind` directory and reinstalling
 - manually removing all Codewind images and reinstalling
 - manually removing both of the above and installing 0.9.0
   - This still appeared to try and download 0.11.0 images - is that expected?

I have an easily accessible VM if anyone needs access to the environment to reproduce the error.

**Comment by hhellyer** [comment]
@BethGriggs - What level of docker are you running? We should work with docker 17.06 and above.
https://www.eclipse.org/codewind/vsc-getting-started.html

**Comment by tetchel** [comment]
Hi Beth, I believe you have this issue:

https://www.eclipse.org/codewind/troubleshooting.html#error-upgrading-codewind-to-the-latest

Can you try those steps?

**Comment by tetchel** [comment]
Although, `/home/ibmuser/.codewind/0.11.0/home/ibmuser/.codewind/docker-compose.yaml` is a strange-looking path for it to be trying to use (two home directories?)

**Comment by BethGriggs** [comment]
Docker version is `Docker version 19.03.8, build afacb8b7f0`

```
ibmuser@userver:~$ echo $HOME
/home/ibmuser
```

```
ibmuser@userver:~$ cd .codewind
ibmuser@userver:~/.codewind$ ls
0.11.0  config  dockerconfig
ibmuser@userver:~/.codewind$ ls -al
total 4
drwxrwxr-x  4 ibmuser ibmuser   54 Apr 22 15:42 .
drwxr-xr-x 24 ibmuser ibmuser 4096 Apr 22 15:40 ..
drwxrwxr-x  2 ibmuser ibmuser   34 Apr 22 15:41 0.11.0
drwxrwxr-x  2 ibmuser ibmuser   30 Apr 22 15:41 config
-rw-------  1 ibmuser ibmuser    0 Apr 22 15:42 dockerconfig
```

**Comment by tetchel** [comment]
Tagging as portal because of the clearly incorrect `.codewind` path

`==> created file /home/ibmuser/.codewind/0.11.0/home/ibmuser/.codewind/docker-compose.yaml`

**Comment by BethGriggs** [comment]
I am also seeing the odd path on my personal development machine (macOS 10.15).

```
==> created file /Users/bethgriggs/.codewind/0.11.0/Users/bethgriggs/.codewind/docker-compose.yaml
==> environment structure written to /Users/bethgriggs/.codewind/docker-compose.yaml
```

**Comment by BethGriggs** [comment]
The _think_ the first issue on the Ubuntu VM was due to the `docker-compose` version installed.  I updated to `docker-compose 1.25.5`, and Codewind successfully started. The VM was previously on `docker-compose 1.8.0`. 

I am still seeing issues on my local macOS machine, and that is already on the latest Docker for Desktop (which includes `docker-compose 1.25.4`). I'll try manually updating docker-compose to 1.25.5 on my local machine to see if that fixes the issue there.

**Comment by hhellyer** [comment]
This message:
```
==> created file /Users/bethgriggs/.codewind/0.11.0/Users/bethgriggs/.codewind/docker-compose.yaml
```
is in our latest release, 0.11.0, but was removed by a recent changed to master.

It was only ever displayed the first time we created a docker compose file, it was not very interesting to the user and (as it turns out) it was wrong. The docker compose file is created in the right location.

See: https://github.com/eclipse/codewind-installer/commit/18d4b2bd1087017b0957ec07932f38e66db578cc#diff-e4d6dec85a05773800e99ed74bdf3c2d

**Comment by hhellyer** [comment]
The docker compose problem has hit our build machines (on Ubuntu) and @BethGriggs. It sounds like docker being back level compared to docker itself might be a common problem. I'm going to tag this with docs as well to see if we can add something to the troubleshooting guide.

**Comment by BethGriggs** [comment]
Fixed on both my Ubuntu VM and local macOS:

- Ubuntu VM was fixed by updating the `docker-compose` version from `1.8.0` to `1.25.5`, and then completely uninstalling and reinstalling Codewind.
- macOS problem was fixed by removing a Codewind container that was only showing with `docker ps --all`, and reinstalling from scratch. 

In both cases the main symptom was that there was no `~/codewind/docker-compose.yaml` created when installing Codewind.

**Comment by tobespc** [comment]
removing portal as this needs to be doc'ed in the troubleshooting guide as a fix
