### ISSUE TITLE
Report when a load test is running in the VS Code UI

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#2739]
From the code the VS Code extension currently has to handle writing out the load test results to a file, it should be pretty straightforward to report the current load runner status for a project in the UI. 

The statuses of interest are
1. preparing to run load (`connecting`)
2. running load (`running`)
3. retrieving load test results (the download step after `hcdReady`/`profilingReady`).

we could show the progress in:
- a notification
- the status bar
- the codewind view (if we update the required VS Code version to 1.44) 
  - which also shows a message in the status bar
- the project info page

i would personally lean towards the codewind view and project info page.

**Comment by tobespc** [comment]
we can do that easy enough if needed

**Comment by markcor11** [comment]
I agree, should be straight forward as all of the status values listed in the requirements are currently available and sent to the IDEs over the existing default UI socket channel eventType:`runloadStatusChanged`.

**Comment by tobespc** [comment]
We can't commit this for 0.12 though @tetchel , we are working on defects this sprint and keeping new features to a minimum

**Comment by tetchel** [comment]
I can handle it
