### ISSUE TITLE
Blog improvements (repository and publishing)

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind#2741]
Ideas for blog improvements:
- Priority No. 1: Release blogs on daily or weekly schedule. Enable Andy/Becca to publish.
- Establish review process for blogs
- Invite community participation by allowing readers to post comments on the blog, share on social media, etc.

Open Liberty blog repo for reference: https://github.com/OpenLiberty/blogs

**Comment by sishida** [comment]
Ideas for review process:
- Anyone can draft a blog. Create a blog as a PR in the GitHub repo.
- Before the PR is merged, request review from 1️⃣a developer or tester for technical accuracy and 2️⃣a documentation team member for grammar, spelling, and style.
- When both 1️⃣and 2️⃣have added their approval, merge the PR.

**Comment by sishida** [comment]
Steven presented this idea today:

**GitHub actions**
-Kick off actions after you merge a PR to a certain branch. In Git Lab, you can specify which branch could kick off a specific action. For example, you could specify a branch and, after a PR is merged, automate tests and publishing to the live site.
- This automated process could also be applied to publishing the live site.
- Would still require merging to master and 0.12.0.
- Wouldn't want to make the GitHub actions activate when merging on the `master` branch but rather on other branches.

**Git Lab environments**
Also, Git Lab has self-contained environment. Clone live site and publish, then the environment disappears.

**Comment by micgibso** [comment]
We'll move the relevant parts of this issue to the wiki, and then close it.

**Comment by sishida** [comment]
I am OK with closing this issue if the rest of the team is OK with closing it.
