### ISSUE TITLE
Support JSON output in cwctl mustgather

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#2751]
For the IDEs to use the mustgather command, they have to be able to report the mustgather result's location to the user. So, when `--json` is passed it should output an object with the output file's location. I'm not sure if there is any other info that may be useful to report, but if so it should be included in the object. As always, any error output must also be JSON-parsable.

As an aside, I would personally like an option to output both the zip and the non-zipped contents, rather than having to pick just one. That way I can both inspect the mustgather and upload it without having to zip it myself.

**Comment by tobespc** [comment]
so is the location of the mustgather output file the only thing the IDE's will need ?

**Comment by tetchel** [comment]
as far as I can tell, since that's the only output / result of running that command.

**Comment by mattcolegate** [comment]
@tetchel For your aside, would you accept the ability to manually unzip the created zip on your filesystem to meet your requirement?

**Comment by mattcolegate** [comment]
Sample output:
`{"outputdir":"C:\\Users\\MattColegate\\.codewind\\mustgather\\20200428155550"}`

**Comment by tetchel** [comment]
This is in but see https://github.com/eclipse/codewind/issues/2815
