### ISSUE TITLE
Nits with operator install instructions

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#2753]
- not all windows users use git bash as their unix-like terminal. One of the first steps should be something like,
```
If you use windows, use a Unix-like shell such as Windows Subsystem for Linux, Git Bash, or MinGW to run the operator installer shell script.
```
- `cd deploy` should explicitly be present in the first code block, for people like me who skim through the text and just run the commands
- `install.sh` doesn't work. It has to be `./install.sh`, or you get `install.sh: command not found`. So:
```
$ install.sh operator -i <ingress_domain>
```
should be
```
$ ./install.sh operator -i <ingress_domain>
```

All commands that start with `install.sh` like this must be updated.

- Should it mention the default keycloak credentials? Step 3 doesn't mention that you have to log in, but you do.
- The docs should mention that, if the 'temporary password' option is used (Step 3.4), then the Jane user who is to use that account must go to the deployed codewind gatekeeper route and log in to change the password, before s/he can connect to the remote Codewind instance. Otherwise, you get a message that says 'account is not fully set up'.

**Comment by tetchel** [comment]
Also, should it mention that the default keycloak login is `admin`/`admin` ? Step 3 doesn't mention that you have to log in, but you do.

**Comment by tetchel** [comment]
this isn't really a docs issue, but i'd also like to know if the operator supports install into another namespace.

**Comment by markcor11** [comment]
In this initial release of the operator it must be installed into the "codewind" namespace and has watches for just that namespace. All the example yaml files provided in the deploy director and docs are set up that way but as we prepare for Operator Hub that restriction and the install.sh script will be removed.
