### ISSUE TITLE
[IntelliJ] Improve Logging support of IDE-specific messages

### ISSUE THREAD

**Issue by keithchong** [eclipse/codewind#2754]
**Codewind version:** latest
**OS:** any

**IDE extension version:** latest
**IDE version:** 2019.3 

**Description of the enhancement:**
Improve log support of our Codewind Intellij plugin
Currently we log our INFO level messages to the IntelliJ log file (eg. idea.log) and we are inundating it with our messages, including entire JSON responses from turbine/portal.  We need to add debug and trace level flags that need to be turned on in order for the messages to be logged to the log file.

**Comment by sishida** [comment]
Assigning myself to help with docs work! 🖊️

**Comment by keithchong** [comment]
The existing methods will continue to use the class-specific logger category

Logger.log(...) - should be used sparingly since by default INFO messages get written to the log
Logger.logWarning(...) - writes message to log and to console output 

The following methods will be added and they will use the generic `org.eclipse.codewind` category.  This category will serve as the 'flag' that the user has to turn on from the Debug Log Settings dialog (or IDE-wide via VM settings) in order for the messages to be written to the log.  eg. `#org.eclipse.codewind` to turn on debug level messages and `#org.eclipse.codewind:trace` to turn on trace level messages.

Logger.logDebug(...)
Logger.logTrace(...)


Sample debug message: (Note DEBUG level).  This particular message change will be included in this PR.

```
2020-04-24 10:53:01,769 [  10366]  DEBUG -          #org.eclipse.codewind - org.eclipse.codewind.intellij.core.CodewindApplicationFactory - [
  {
    "projectID": "13a796c0-831a-11ea-8d0a-fbbaa43527c8",
    "name": "cwGo01",
    "codewindVersion": "0.11.0",
    "language": "go",
    "creationTime": 1587739659654,
    ....
    ....
      ]
    }
  }
] 

```

The current INFO messages look like this
`
2020-04-24 11:15:27,562 [  74276]   INFO - ellij.core.CodewindApplication - Set HTTP port for null to 32781  `

These should be changed to debug or trace level messages and should not be shown in production.  These should be changed in a separate PR.

**Comment by tetchel** [comment]
this section can use a quick update to mention intellij https://www.eclipse.org/codewind/troubleshooting.html#setting-codewind-server-log-levels

**Comment by keithchong** [comment]
Closing.  Follow-up issue is: https://github.com/eclipse/codewind/issues/2819
