### ISSUE TITLE
Broken Codewind links on other websites

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind#2757]
Other websites link to Codewind files. Here are the broken files:

:one: mdt-vsc-getting-started.html
:two: mdt-eclipse-getting-started.html
:three: mdt-vsc-commands-project.html
:four: mdteclipsemanagingprojects.html
:five: mdt-che-setupregistries.html
:six: mdt-che-installinfo.html

**Comment by sishida** [comment]
Here are the updated files:
:one: vsc-getting-started.html
:two: eclipse-getting-started.html
:three: vsc-commands-project.html
:four: eclipse-firstproject.html OR project-actions.html OR project-settings.html
:five: che-setupregistries.html

**Comment by sishida** [comment]
:one: On the page, https://www.ibm.com/support/knowledgecenter/SSCSJL_4.1.x/guides/guide-codewind-getting-started-vscode/README.html, the broken link "Review project commands for Codewind for VS Code External link" can be replaced with https://www.eclipse.org/codewind/vsc-codechange.html.
:two: On the page, https://www.ibm.com/support/knowledgecenter/SSCSJL_4.1.x/guides/guide-codewind-getting-started-eclipse/README.html, the broken link in "Review managing Codewind projects for Eclipse External link" can be replaced with  https://www.eclipse.org/codewind/eclipse-codechange.html.

**Comment by jcockbain** [comment]
Hi @sishida, 

I was going to add redirection with the new Landing Page, as we want to redirect from `/gettingstarted` to `/learn` (with the new landing page). 

At the moment, on my branch I've used `jekyll-redirect-from` (https://github.com/jekyll/jekyll-redirect-from. Which means in the frontmatter of each file you can define the routes you want to redirect to that page. Would it be help with this in future if we used that for this? i.e  you'd have: 

```
___
layout: docs
title: "Installing Codewind for VS Code"
redirect_from: "mdt-vsc-getting-started"
permalink: "vsc-getting-started"
...
___
```

**Comment by sishida** [comment]
@jcockbain Redirection would be useful! I think it sounds like a good idea! 👍 

Also, please open an issue for the redirection work if there's not already one open for it. 😄Thank you!

**Comment by micgibso** [comment]
@sishida Can this be closed?

**Comment by sishida** [comment]
1️⃣ @j-c-berger, Did we confirm that the links on the other websites were fixed? I remember we talked about who would make the changes, but I don't recall confirmation that they got fixed. If we're good to go on that front, or if the fixes are no longer required (such as if the links were removed altogether), I'm good with closing the issue.

2️⃣ If future file names change, @jcockbain implemented redirection links with https://github.com/eclipse/codewind-docs/pull/651. We don't need to backtrack and add redirections for the files mentioned in this issue, but redirections can be added in the future if needed.

**Comment by jcockbain** [comment]
@sishida - if you'd like me to I can raise an issue to redirect these links too? It would be a small job and demonstrate more clearly how redirection can be added in future.

**Comment by j-c-berger** [comment]
@sishida, ICPA ID writers handled the broken links since the broken links were on their docs. They have fixed the broken links, so don't let that hold you back from closing the issue.

**Comment by sishida** [comment]
@jcockbain If you would like to open a PR, I have no objections. 👍 However, since @j-c-berger let us know that the broken links are already fixed, adding redirections aren't a must-have. I'm thinking it might be easiest to leave them alone?

**Comment by micgibso** [comment]
Closing as complete.
