### ISSUE TITLE
SVT:Need docs how to install latest codewind from eclipse and vscode tools

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#276]
Version: 2019-06 (4.12.0)
Build id: 20190614-1200

**Description:**
We need docs to the codewind users how to install latest codewind from Eclipse and VScode plugins.

These instructions need to address for both Windows, MacOS and Linux operating systems.

Users have to set this variable from command line/Terminal before starting eclipse/vscode tools.

Windows : 
`set CW_TAG=latest`

MacOS/Linux : 
`export CW_TAG=latest`

**Steps to reproduce:**
1. This is documentation request for the users to install codewind with the latest images.

**Workaround:**

**Comment by sishida** [comment]
@jagraj I remember adding instructions for how to update the Eclipse and VS Code plug-ins. Is the variable that you mentioned in this issue something that needs to be added to these instructions here?
- Link to updating the Codewind plugin for Eclipse: https://www.eclipse.org/codewind/mdt-eclipse-installinfo.html#updating-the-codewind-plug-in
- Link to updating the Codewind plugin for VS Code: https://www.eclipse.org/codewind/mdt-vsc-installinfo.html#updating-the-codewind-plug-in
Thanks!

**Comment by jagraj** [comment]
@tetchel 
Do you know if the user still has to export the `CW_TAG=latest` tag to install latest version of codewind.? Is this automatic now users does not have to do this if they are installing latest plugins from master.?

**Comment by tetchel** [comment]
yes you still have to do that if you want to use the development images

**Comment by jagraj** [comment]
@tetchel @sishida 
The above doc is for external customers and not to codewind committers. Do we need to document for external customers as well how to install latest codewind.?

Sarah is working on other set of docs how to build codewind images for codewind repo. 
Do you think it makes sense to send the developers/users to here (https://github.com/eclipse/codewind-vscode#developing) who wants to use latest images and plugins.?

**Comment by sishida** [comment]
@jagraj, I think that you are correct in sending users here (https://github.com/eclipse/codewind-vscode#developing) for building Codewind in VS Code. And I think this section (https://chrome.google.com/webstore/detail/cisco-webex-extension/jlhmfgmfgeifomenelglieieghnjghma) applies to Eclipse. @tetchel and @eharris369, please correct me if I'm mistaken.

Also, Jag, do we still need to add `set CW_TAG=latest` and `export CW_TAG=latest` to the linked instructions?

Thanks!

**Comment by eharris369** [comment]
Yes this should be covered in the readmes and not in the documentation as it is only for people developing Codewind.  Users should not have to set CW_TAG.  For Eclipse the link is https://github.com/eclipse/codewind-eclipse#developing-codewind-for-eclipse and it already mentions setting the CW_TAG.

**Comment by tetchel** [comment]
vs code also has a bullet for this in the readme https://github.com/eclipse/codewind-vscode#developing

**Comment by sishida** [comment]
Thanks for the clarifications, @eharris369 and @tetchel!

@jagraj, I think that this issue is good to close? Did you have any other questions for us? If not, I will go ahead and close the issue! Please let us know. Thank you!

**Comment by jagraj** [comment]
Hi Sarah,
We are good now, thank you.
