### ISSUE TITLE
Remote Node project app logs broken

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#2761]
I have seen this problem with new Node projects on my minikube cluster as well as my OCP one. The app logs contain the last 10 lines of `package.json` and nothing else. Sometimes, it has those 10 lines multiple times.

![image](https://user-images.githubusercontent.com/8888438/80393419-75b0cf80-887e-11ea-9c2e-0cc1d2bddb77.png)

I can't get the logs to show anything else. The build logs seem OK.

Here's the content of the `log-update` event:

```
{
    logName:"app.log"
    logPath:"/codewind-workspace/.logs/nodemk-0de98700-889e-11ea-a602-53da96b7af34"
    logs:"    "express-pino-logger": "^4.0.0",
        "pino": "^5.16.0"
    },
    "devDependencies": {},
    "nodemonConfig": {
        "env": {
        "NODE_HEAPDUMP_OPTIONS": "nosignal"
        }
    }
    }
        "express-pino-logger": "^4.0.0",
        "pino": "^5.16.0"
    },
    "devDependencies": {},
    "nodemonConfig": {
        "env": {
        "NODE_HEAPDUMP_OPTIONS": "nosignal"
        }
    }
    }
        "express-pino-logger": "^4.0.0",
        "pino": "^5.16.0"
    },
    "devDependencies": {},
    "nodemonConfig": {
        "env": {
        "NODE_HEAPDUMP_OPTIONS": "nosignal"
        }
    }
    }
    "
}
```

The contents of that file within PFE do match the `logs` in that object.

Tagging both backend areas because i'm not sure which one to start with.

**Comment by sujeilyfonseca** [comment]
**Codewind version:** Latest
**OS:** Mac OS Mojave 10.14.6 (w. OCP 4.3), VM with Windows 10 (w. OCP 3.11)

**IDE extension version:** 0.12.0
**IDE version:** Code 1.44.0

I encountered the same problem on Friday. The `app.log` only presented a few lines from the `package.json` when creating new Node JS projects in remote scenarios. I didn't see that when creating Node JS projects in local scenarios.

<img width="1677" alt="Screen Shot 2020-04-27 at 3 40 16 PM" src="https://user-images.githubusercontent.com/49531960/80413430-7311a280-889d-11ea-92d5-bdc00777e6ce.png">

```
[root@codewind-pfe-k9ehncev-685467f4f7-bbjrx cw-remote-node-express-3efecf90-88bb-11ea-97b2-713b959fb2cd]# cat app.log
    "express-pino-logger": "^4.0.0",
    "pino": "^5.16.0"
  },
  "devDependencies": {},
  "nodemonConfig": {
    "env": {
      "NODE_HEAPDUMP_OPTIONS": "nosignal"
    }
  }
}
```

**Comment by stalleyj** [comment]
This problem is a result of the changes made for https://github.com/eclipse/codewind/issues/1990. Investigating a solution

**Comment by jopit** [comment]
Two solutions

1. Allow Kube to restart the pod
2. Tail the same file we do in the local case.

Investigate doing 2 for 0.12, and 1 for 0.13

**Comment by rwalle61** [comment]
#2812 implements solution 1 for 0.12

**Comment by tobespc** [comment]
this needs resolving by turbine as to the best way of preventing a pod from restarting by kube

**Comment by malincoln** [comment]
@elsony ^^^

**Comment by malincoln** [comment]
Jag and SVT to verify fix made for 0.12.0
We can then remove "priority/stopship" and change to "priority/hot" and make remaining fix for 0.13.0 (next release).

**Comment by elsony** [comment]
To fix this problem, the node implementation can just follow what we did on the spring application support by overriding the entry point to tail a log file. And the log file is generated by redirecting the output of the node server start to the file.

**Comment by johnmcollier** [comment]
To add to what Elson mentioned, here are the scripts that we use to do the same in Spring:
Entrypoint: https://github.com/eclipse/codewind/blob/master/src/pfe/file-watcher/scripts/springScripts/new_entrypoint.sh
Server start: https://github.com/eclipse/codewind/blob/master/src/pfe/file-watcher/scripts/springScripts/spring-start.sh

**Comment by tobespc** [comment]
we can pick this work for 0.13

**Comment by elsony** [comment]
Removing iterative-dev label since portal team has agreed to pick this up. (Thanks Toby!)

**Comment by sujeilyfonseca** [comment]
Thanks for implementing a solution for Codewind 0.12.0!

I verified this issue with the latest Codewind 0.12.0, and I can see the logs files in Node projects when using a remote connection:

<img width="1157" alt="Screen Shot 2020-05-13 at 4 59 51 PM" src="https://user-images.githubusercontent.com/49531960/81866345-935c8500-955e-11ea-8a16-338c671e9f30.png">

**Comment by hhellyer** [comment]
This should be fixed in master, moving to verify.
