### ISSUE TITLE
Pickup new Appsody for 0.12.0

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#2764]
**Codewind version:** 0.12.0
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description of the enhancement:**

Pickup new appsody when it's available this week

**Proposed solution:**

**Comment by tetchel** [comment]
fyi because I am annoying, I moved the appsody version again.

https://github.com/eclipse/codewind-vscode/blob/master/dev/package.json#L7
