### ISSUE TITLE
Auto-build not working on my minikube cluster

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#2785]
I was fixing some clean up that was not being done when a connection was removed from VS Code. After recreating the connection to the same cluster, auto-build no longer works.

With each code change, I see a message in the filewatcher logs:
```
[April 29, 11:27:08.073] [53.746] Received event [MODIFY] /Users/tim/vscode-codewind-workspace/nodemk/server/routers/codewind.js
[April 29, 11:27:09.076] [54.749] Batch change summary for 0de98700-889e-11ea-a602-53da96b7af34 @ 1588174028073: [ >codewind.js ]
[April 29, 11:27:09.076] [54.749] Calling cwctl project sync with: { [--insecure] [project] [sync] [-p] [/Users/tim/vscode-codewind-workspace/nodemk] [-i] [0de98700-889e-11ea-a602-53da96b7af34] [-t] [1588123052888] }
[April 29, 11:27:09.111] [54.784] ! ERROR !  Error running 'project sync' installer command time="2020-04-29T11:27:09-04:00" level=error msg="Connection K9INGI57 not found"

[April 29, 11:27:09.113] [54.785] ! ERROR !  Stdout:No output
[April 29, 11:27:09.114] [54.787] ! ERROR !  Stderr:time="2020-04-29T11:27:09-04:00" level=error msg="Connection K9INGI57 not found"

[April 29, 11:27:09.114] [54.787] !!! SEVERE !!!  Unexpected exception from CLI:
[object Object]
```

The error message is accurate; there is no K9IN connection:
```
[ /Users/tim ] 25 $ cwctl connections ls
{
    "schemaversion": 1,
    "connections": [{
        "id": "local",
        "label": "Codewind local connection",
        "url": "",
        "auth": "",
        "realm": "",
        "clientid": "",
        "username": ""
    }, {
        "id": "K9LHSL5N",
        "label": "minikube3",
        "url": "https://codewind-gatekeeper-k9inbn8c.192.168.64.2.nip.io",
        "auth": "https://codewind-keycloak-k9inbn8c.192.168.64.2.nip.io",
        "realm": "codewind",
        "clientid": "codewind-k9inbn8c",
        "username": "developer"
    }]
}
```
But the connection's URL does contain that connection ID. So maybe cwctl is mapping my projects to the wrong (no longer existing) connection. I have removed and recreated the connection multiple times but still have the same error.

**Comment by jgwest** [comment]
It's tough to tell [because the filewatcherd log format for this error is bad](https://github.com/eclipse/codewind/issues/2778), but the following is the output from `cwctl project sync` (eg this message is NOT from filewatcherd; and in fact FWd never deals with connection IDs):
```
command time="2020-04-29T11:27:09-04:00" level=error msg="Connection K9INGI57 not found"
```

**Comment by tobespc** [comment]
A change went in last night that should resolve this problem.  @stalleyj Can you check to see if your change would have resolved this ?

**Comment by stalleyj** [comment]
Yes, this problem will absolutely be solved by my PR https://github.com/eclipse/codewind-installer/pull/450.

Any project command that takes a projectID will now dynamically work out the connectionID (by looking at the projects on each connection) rather than looking for the json file. I have also raised an enhancement to add the ability to pass the connectionID in to cwctl project commands https://github.com/eclipse/codewind/issues/2799

**Comment by jgwest** [comment]
Reopened as it needs to be verified by bug originator.

**Comment by tetchel** [comment]
This is fixed but it looks like it has introduced a new problem https://github.com/eclipse/codewind/issues/2807
