### ISSUE TITLE
Allow PFE to enable/disable template extensions (e.g. Appsody)

### ISSUE THREAD

**Issue by rwalle61** [eclipse/codewind#279]
**Description of the enhancement:**
The Appsody extension to Codewind is enabled by default, so users by default have to see Appsody templates. However, some users want to be able to disable/hide them.

**Proposed solution:** 
We can currently enable and disable individual template repositories. We could add similar APIs so that we can also enable and disable template _extensions_, such as Appsody. (This would only disable the Appsody extension's ability to provide PFE templates; it doesn't touch the rest of the Appsody extension's functionality)

I.e., in addition to
`GET templates/repositories`
`POST templates/repositories`
`DELETE templates/repositories`
`PATCH templates/repositories`

add

`GET templates/extensions` (returns `200` and a list of extensions names/ids)
`PATCH templates/extensions` (like `PATCH templates/repositories`, takes enable/disable operations, and returns `207` and a list of subresponses.

To store state about which template extensions are enabled/disabled, we would write to a `template_extensions.json`, similar to our `repository_list.json`. `template_extensions.json` would look like:
```
[
    'appsodyExtension': {
        enabled: 'true',
    },
    <etc>
]

```

**Comment by rwalle61** [comment]
I see we also have `providers` in `Templates.js`. So shall I combine `providers` and `repositories` into `sources`?

**Comment by makandre** [comment]
Nothing really wrong with the design, but I'm not keen about introducing yet another API endpoint, esp when the operations are doing almost the same thing as operations on `templates/repositories`.  Also having both `/api/v1/templates/extensions` and `/api/v1/extensions` seems confusing.

In one of the previous meetings, it was discussed that we should treat each "repository entry" as a "repository source" instead.  So under this line of thinking, we could have different source types in `repository_list.json`: url types that gives back 1 url, or extension types that gives back 1 or more urls.

i.e. maybe it looks like this:

```json
[
    {
        "description": "Default code templates",
        "url": "https://raw.githubusercontent.com/kabanero-io/codewind-templates/master/devfiles/index.json"
    },
    {
        "description": "Appsody templates",
        "url": "extension://appsodyExtension"
    }
]
```

Then everything can be handled same-ish with the existing APIs (tho maybe the endpoint should be renamed to `templates/sources`) and we stick with having 1 metadata file

**Comment by makandre** [comment]
Alternatively, maybe whether an extension provides templates or not, should be a property (e.g. `enableTemplates`) on the extension resource at the `extensions` endpoint.  Then, we could use the `GET/PATCH extensions` API to set this property to true/false on the resource.

In this case I think we would need that separate json file to track this property (thus an extension resource would be a combination of properties from the `codewind.yaml` and the `enableTemplates` from the json)

Anyways, just tossing around some thoughts.

**Comment by deboer-tim** [comment]
The design that we're working on from an IDE standpoint is to push the user to pick one devfile repo the first time they go to create a project (i.e. disable all but one), and then only show the templates from that repo. The user could also access full repo management at any time to add/remove/enable/disable individual repos.
IMHO if we proceed with this design there should be no need for this issue since the only thing required from portal is enable/disable which is already covered elsewhere.

**Comment by makandre** [comment]
But I think currently portal can only enable/disable things that are persisted in `repository_list.json`, which anything coming from an extension won't be in there.  So this issue is meant to cover that?

**Comment by deboer-tim** [comment]
I'm good if we want to use it for that. We should chat if we think we need to keep in sync with changes to the repo list in the external cli, but either way they should probably be added to the repository list so that they can be enabled/disabled like any other repo.

**Comment by rwalle61** [comment]
so to clarify:

1.  we don't want to disable/enable template extensions, 
2.  we do want to disable/enable templates from extensions?

**Comment by deboer-tim** [comment]
Well, it's more complicated than that :) but the best balance we've found from a usability perspective between what the user understands the first time in, what they want, and simplicity is handling this by enabling/disabling repos.

**Comment by rwalle61** [comment]
Okay, sounds like we can park this for now. We can already enable/disable individual repos, except those that come from the Appsody extension. 

So the way forwards is to allow PFE to enable/disable those repos individually, rather than enabling/disabling all/no repos from the Appsody extension (which was this issue)

**Comment by makandre** [comment]
This seems to be opposite of what was discussed in one of the tech-topic meeting (I'll try to dig up the issue) where we said we are not going to enable/disable individual repos that come from an extension, but to enable/disable sources of repos instead (where an extension is a source of repositories)

**Comment by rtaniwa** [comment]
I wasn't involved in the discussion, but to me we need a quick fix for this as currently the appsody templates are taking over the menu. So if we are doing this in baby steps the first step is allowing a user to filter what is displayed based on selecting a source repo. In the future we can perhaps decide if we want to allow more granular hide and show in the IDE.

**Comment by rajivnathan** [comment]
Agreed with Rob, the Appsody types have taken over and these aren't currently in a state where we'd want them front and centre because they don't have optimized iterative development or debug capability yet.

What the new project list looks like right now:
![image](https://user-images.githubusercontent.com/20015929/64282389-534ef800-cf23-11e9-9bae-fa5536d1d060.png)

Think it's worth re-opening this issue for it to gain some attention. If there's another issue that should cover the quick fix work Rob mentioned then feel free to link and close.

**Comment by tobespc** [comment]
closing as this is done
