### ISSUE TITLE
Debug port forward connection refused by remote appsody project

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#2792]
From https://github.com/eclipse/codewind/issues/2786#issuecomment-621466804

```
> Executing task: kubectl port-forward -n eclipse-codewind cw-rmapnode01-1a8462e0-8a4d-11ea-a583-5fd774698c-rpltx 5000:9229 <
Forwarding from 127.0.0.1:5000 -> 9229
Forwarding from [::1]:5000 -> 9229
Handling connection for 5000
E0429 16:57:33.017238   52132 portforward.go:400] an error occurred forwarding 5000 -> 9229: error forwarding port 9229 to pod d7df49cc5c65e90510f09f45dba78d0be87caf1e8c222cbe0a92f48c418a6367, uid : exit status 1: 2020/04/29 20:57:33 socat[107257] E connect(5, AF=2 127.0.0.1:9229, 16): Connection refused
```

I am not sure what may be causing it to refuse the connection if 9229 is the correct debug port, which is appears to be. 

Waiting to see if Eclipse has the same problem

**Comment by makandre** [comment]
Not sure if the pod need to expose the ports in a certain way. In Appsody's case it's the CLI that's bringing up the pod. Attaching the app-deploy.yaml they generate.

[app-deploy.yaml.txt](https://github.com/eclipse/codewind/files/4554662/app-deploy.yaml.txt)

**Comment by makandre** [comment]
May also be relevant

![image](https://user-images.githubusercontent.com/17596240/80649348-da675800-8a3f-11ea-946c-e94b8f154b71.png)

**Comment by makandre** [comment]
If I took out port 9229 from the kube service, I still wasn't able to attach.

During the investigation I noticed the ingress/route is lost after the restart.  Unsure if this is related but I'm testing out a potential fix for it.

**Comment by jopit** [comment]
We believe the problem is that appsody is exposing the debug port, solution is for them to stop it.
Andrew will test this by removing the service from appsody yaml
Andrew will open issues to stop appsody exposing the port, and for the missing ingress.

**Comment by makandre** [comment]
Removing port 9229 from both appsody deploy and service yamls, I can at least see that `kubectl port-forward` works.

We would need appsody CLI to stop exposing the debug port, opened https://github.com/appsody/appsody/issues/993 for this.

@neeraj-laad for your attention

**Comment by jopit** [comment]
Would stopping exposing the debug port break local debug for appsody?

**Comment by tetchel** [comment]
we want to stop exposing it through the service, specifically in kube. local behaviour should not change (we still want `EXPOSE <port>` in the dockerfile)

**Comment by makandre** [comment]
I was testing a potential fix for https://github.com/appsody/appsody/issues/993.

The fix stopped exposing the debug port and I believe the port-forward works now, but the connection is still refused because the appsody app isn't actually listening on the debug port.  A new issue is opened for this: https://github.com/appsody/appsody/issues/999

**Comment by makandre** [comment]
The fix from appsody https://github.com/appsody/appsody/pull/1000 works. With it I can attach local vscode debugger to remote appsody project.

We'll pick up new appsody CLI with the fix via #2995.  However, that alone will not fully make remote debug work because the appsody stacks themselves will need to be updated with a new variable, and that will take time for all the stacks.

**Comment by makandre** [comment]
#2995 is closed so this is ready to be verified... however, it needs to be verified against updated stacks that have `APPSODY_DEBUG_PORT` defined and none of official stacks have this yet.

So here's how to verify against a custom stack I built:

1. create a `nodejs-express` project
2. change the image in its `.appsody-config.yaml` to `docker.io/makandre/nodejs-express-debug:latest`
3. restart the project

/verify

**Comment by makandre** [comment]
Update: It seems we may have been wrong about the exposing of the debug port as the thing that prevented us to attach, as we've discovered that the attach now works even on current stacks that have not been updated (appsody has fix other things along the way making this possible now)

**Comment by tetchel** [comment]
yes, this works now
