### ISSUE TITLE
codewind-workspace created by root

### ISSUE THREAD

**Issue by mjwhale** [eclipse/codewind#28]
https://www.eclipse.org/codewind/mdt-vsc-getting-started.html

using vscode 1.3.61 on ubuntu

codewind appears to create the codewind-workspace as root user, is this expected?  

Is it ok to change the ownership back to the logged in user?

Thanks

**Comment by tobespc** [comment]
By default we do run as root when running locally, the current design is built around that.  Having said that, we are working on a solution that should remove this restriction

**Comment by tetchel** [comment]
should we convert this to an enhancement, then?

**Comment by tobespc** [comment]
we can do, this will be indirectly fixed so wouldn't want this to be picked up and worked on independently though

**Comment by mjwhale** [comment]
is it ok to change ownership (chown -R) of the codewind-workspace back to the logged in user or do I really need to login and run as root?

**Comment by tobespc** [comment]
closing as fixed in latest
