### ISSUE TITLE
Eclipse Plugin allows Uninstall where it would cause errors

### ISSUE THREAD

**Issue by mattcolegate** [eclipse/codewind#280]
**Codewind version:**   `latest`
**OS:** Windows 10

**Che version:** N/A
**IDE extension version:** 0.3.0.v201908262000
**IDE version:** Eclipse 2019-06 (4.12.0)
**Kubernetes cluster:** N/A

**Description:**
The Eclipse plugin allows `Uninstall` to be selected in the Codewind Explorer context menu when it would cause errors:
1. When projects are building
1. When Codewind is stopped but the user has chosen to leave their application containers running.

Either this is a bug in the Eclipse plugin and the context menu options should be removed, or this is a bug in the uninstallation code that doesn't adequately check the running status of application containers before attempting uninstallation.

**Steps to reproduce:**
Scenario 1: 
1. Install Codewind into Eclipse IDE
1. Create some projects
1. When the first project is running and others are building, choose `Uninstall` from the context menu

Scenario 2:
1. Install Codewind into Eclipse IDE
1. Create some projects
1. Wait for all project to be running
1. Select `Stop` from the context menu. 
1. Select `No` from the Stopping Codewind popup box
1. Wait for Codewind to stop
1. Select `Uninstall` from the context menu

**Workaround:** 
Don't uninstall Codewind whilst there are running images.

**Comment by eharris369** [comment]
Can this be closed now?  The PR: eclipse/codewind-eclipse#240 was delivered a while ago.  I tested both scenarios and they work (user do not have a choice to leave their apps running on stop anymore).

**Comment by eharris369** [comment]
@mattcolegate Please verify this issue.

**Comment by mattcolegate** [comment]
Verified.
