### ISSUE TITLE
Performance Dashboard - Test history does not appear until load run settings edited.

### ISSUE THREAD

**Issue by hhellyer** [eclipse/codewind#2804]
**Codewind version:**
master
**OS:**
MacOS

**Description:**
I am not seeing previous load run results appear when I load or refresh the perfomance dashboard until I edit and save the load run config. (Saving without changing it may be enough.)

**Steps to reproduce:**
- Create a project
- Perform a load test against it.
- The load run should not be added to the test history.
- Edit the load run config and save.
- The previous load run should appear in the history.

**Workaround:**

**Comment by markcor11** [comment]
reproduced

/assign

**Comment by hhellyer** [comment]
Fixes have been merged into 0.12.0 and master. I've checked the dashboard now updates correctly. Closing.
