### ISSUE TITLE
cwctl --json diagnostics gives invalid output if pfe isn't running locally

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#2815]
```
[ /Users/tim ] 38 $ cwctl --json diagnostics
{"error":"config_connection_notfound","error_description":"Hostname or port for PFE not found"}
{"outputdir":"/Users/tim/.codewind/diagnostics/20200430113825"}
```
This is not valid JSON, there can only be one top-level object. I don't know if the diagnostics command should fail in this case, or if it should "succeed with errors".

Also, this problem has been seen in the past with a number of cwctl commands - where multiple objects are output as errors occur, but the process doesn't exit after the error. Please, see if there is some way to funnel cwctl JSON output through a function to can ensure only one object is output.

**Comment by mattcolegate** [comment]
/pipeline In Progress
(as per @tobespc request)
