### ISSUE TITLE
Disabled remote connections should stay disabled after VS Code restart

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#2823]
1. Disable a remote connection, eg because the cluster is behind a proxy you don't have right now
2. Restart VS Code
3. It's enabled again, oh no

**Comment by eharris369** [comment]
Eclipse has the same problem.

**Comment by jopit** [comment]
Reopen since the fix for the Eclipse plugin isn't in yet.

**Comment by eharris369** [comment]
Fixed in Eclipse IDE by PR: https://github.com/eclipse/codewind-eclipse/pull/720

**Comment by tetchel** [comment]
:+1:
