### ISSUE TITLE
SVT:[Hybrid]:Codewind gatekeeper pod keep terminating and restarting

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#2827]
**Codewind version:** 0.11.0
**OS:**  Windows/Eclipse --> OCP 4.3 Cluster

**Che version:** 
**IDE extension version:** 0.11.0
**IDE version:** 2019-09
**Kubernetes cluster:** OCP 4.3

**Description:**
I installed Codewind on remote ICP 4.3 cluster through operator and created connection in Eclipse which is running on Windows. I created bunch of projects and let it running for after 0.11.0 GA and I see gatekeeper pod keep restarting and IDE is loosing connection due to this. The gatekeeper pod status says "Error"  and Terminated.

```

NAME                                                              READY   STATUS    RESTARTS   AGE
codewind-gatekeeper-devex001-d8b897dd6-7w6p9                      1/1     Running   15         15d
codewind-keycloak-devex001-7cb7597cf8-bj4cf                       1/1     Running   0          12d
codewind-operator-c697fbb4f-qgwcn                                 1/1     Running   0          15d
codewind-performance-devex001-66887f5894-gvfk4                    1/1     Running   0          12d
codewind-pfe-devex001-7669f999d4-blrmz                            1/1     Running   0          3d16h
cw-appsodyemphybocp43cw011-d335f080-80cd-11ea-a7a7-5d98d484qq2q   1/1     Running   0          13d
cw-appsodynoderedhybocp43c-2015a850-80ce-11ea-a7a7-5776b69f2fwx   1/1     Running   0          3d19h
cw-wlhybocp43cw011svt-7344abc0-80ce-11ea-a7a7-56cd74667d-chzx2    1/1     Running   0          13d

```

```
    State:          Running
      Started:      Mon, 27 Apr 2020 14:00:11 -0700
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 27 Apr 2020 13:54:49 -0700
      Finished:     Mon, 27 Apr 2020 13:54:57 -0700
    Ready:          True
    Restart Count:  15
```

*Logs* 

[gate-keeper.txt](https://github.com/eclipse/codewind/files/4564247/gate-keeper.txt)
[keycloak.txt](https://github.com/eclipse/codewind/files/4564248/keycloak.txt)
[operator.txt](https://github.com/eclipse/codewind/files/4564249/operator.txt)
[pfe.txt](https://github.com/eclipse/codewind/files/4564250/pfe.txt)

**Steps to reproduce:**
1. Install Codewind on remote cluster.
2. Create connection from Eclipse plugin.
3. Create few projects and let it running for long time.
4. Look for gatekeeper pod it is terminating and restarting.

**Workaround:**

**Comment by markcor11** [comment]
The gatekeeper restart is because portal is too busy building projects and has stops responding to network connections.  When that happens Gatekeeper thinks the connection has dropped and restarts in order to re-establish a connection. Not a gatekeeper defect.

**Comment by markcor11** [comment]
Had a look at the code for gatekeeper and found some places where we could add some additional error checking just incase the backend (pfe) goes down or is unresponsive.  eg :  

https://github.com/eclipse/codewind/blob/8ee1f6757066499de29aaefa1ad421edeeac32ae/src/gatekeeper/server.js#L153

and 

https://github.com/eclipse/codewind/blob/8ee1f6757066499de29aaefa1ad421edeeac32ae/src/gatekeeper/server.js#L161


https://github.com/eclipse/codewind/blob/8ee1f6757066499de29aaefa1ad421edeeac32ae/src/gatekeeper/server.js#L170

and 

https://github.com/eclipse/codewind/blob/8ee1f6757066499de29aaefa1ad421edeeac32ae/src/gatekeeper/server.js#L179

and 

https://github.com/eclipse/codewind/blob/8ee1f6757066499de29aaefa1ad421edeeac32ae/src/gatekeeper/server.js#L192

**Comment by markcor11** [comment]
The gatekeeper logs look ok,  would be good to get the previous container logs although likely too late now if the pod has been deleted: 

`kubectl logs --previous ${POD_NAME} ${CONTAINER_NAME} -n ${NAMESPACE}`

**Comment by markcor11** [comment]
Please let us know if you are able to gather a new set of logs from the failed pod.   

Moving to verify.

/verify

**Comment by markcor11** [comment]
I was able to catch the Gatekeeper logs just now at a point where Gatekeeper was up and being pinged by the IDE but the connection to PFE was not responding : 


```
Added environment route to : /api/v1/gatekeeper/environment
Gatekeeper listening on port 9096!
Proxy: websocket connect 'upgrade'
/socket.io/* - req.originalUrl = /socket.io/?EIO=3&transport=polling&t=N85dQm0&b64=1
/socket.io/* - req.originalUrl = /socket.io/?EIO=3&transport=polling&t=N85dTCL&b64=1
/usr/src/app/node_modules/http-proxy/lib/http-proxy/index.js:120
    throw err;
    ^

Error: connect ETIMEDOUT 172.21.191.81:9191
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatekeeper@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gatekeeper@1.0.0 start script.
```

So I think I will go ahead and add the additional error handing around these proxied routes per my previous comment : https://github.com/eclipse/codewind/issues/2827#issuecomment-624646361
