### ISSUE TITLE
0.12 cwctl still installing latest images (again!)

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#2831]
https://github.com/eclipse/codewind-installer/blob/0.12.0/pkg/remote/defaults.go#L45

Please, figure out a process for updating this automatically or immediately after DCUT. [vs code does this](https://github.com/eclipse/codewind-vscode/blob/master/Jenkinsfile#L94), intellij has something similar

**Comment by jgwest** [comment]
For example, a test case (or build script addition) that fails the build if they don't match.

**Comment by tetchel** [comment]
Or add a command-line arg for image tag to `install remote` which defaults to `latest`, and then tell the user they have to pass the tag 🤷

**Comment by malincoln** [comment]
@tobespc pls help investigate.  Thanks

**Comment by tobespc** [comment]
@josephca I thought you were doing this as part of the release process ?

**Comment by josephca** [comment]
> @josephca I thought you were doing this as part of the release process when you created the branch?

@tobespc The current release process doesn't cover this. However, I think it's reasonable to update the version when we create a release branch (i.e. 0.13.0). I will cover it from the next release.  Thanks,

**Comment by tetchel** [comment]
Fixed
