### ISSUE TITLE
Run UX testing of Getting Started user flows within website documentation

### ISSUE THREAD

**Issue by MelHopper** [eclipse/codewind#2841]
**Overview:**

This exercise is for user flow rather than checking the accuracy of the instructions...though do feel free to check this at the same time, time permitting.
Note: the Eclipse Che pages are currently being reworked quite substantially, so do not test these out.

**Instructions**

1. Download codewind-docs/master branch to your local machine. 
2. Navigate to codewind-docs folder and run the serve.sh script to serve up the web pages that you will be testing.
3. Select a 'user hat' from the 4 options below and try out the pages listed for that user.

For each 'user hat' you wear, answer the following questions within your section:

- Are you able to easily find the information you are looking for?
- Do you understand where you are with the process of Getting Started?
- Do you understand the information you are reading?
- Are you confident that you are getting started with Codewind in a way that you want to? - e.g. you want to understand how you can use Codewind in the cloud? or you want to get up and running with Codewind as quickly as possible so you can have a play with it?

**I am a user with no prior knowledge of Codewind, who has reached this page after clicking from either the Codewind IDE extension / marketplace, or Codewind's new docs landing page (coming soon!).** I want to understand more about Codewind and try it out.

/codewind/gettingstarted.html
/codewind/vsc-getting-started.html

**2. I am a user with no prior knowledge of Codewind, who has reached this page after a Google search. I want to understand more about Codewind and try it out.**

/codewind/eclipse-firstproject.html
/codewind/overview.html
/codewind/gettingstarted.html

**3. I am a user with no prior knowledge of Codewind, who has reached this page from a blog on Codewind templates / using Codewind remotely. I want to understand more about Codewind and try it out.**

/codewind/workingwithtemplates.html
/codewind/remote-codewind-overview.html

**4. I am a user revisiting this page after reading about Codewind and deciding I would like to try it out.**

/codewind/eclipse-getting-started.html
/codewind/remote-codewind-overview.html
/codewind.overview.html

**Comment by micgibso** [comment]
Moving to verify; this is UX testing.
