### ISSUE TITLE
[SVT][VSCode] 2 broken links in VSCode welcome page.

### ISSUE THREAD

**Issue by DavidG1011** [eclipse/codewind#2843]
**Codewind version:** 0.12
**OS:** MacOS

**Description:** 
2 links in the welcome page are broken:

- Hyperlink "remotely" under the Quick Start section.
- Hyperlink "Deploying Codewind Remotely" under Learn > Docs.

Both of these link to
https://codewind.dev/remotedeploy-combo.html, which results in an Eclipse 404 page.

**Comment by tetchel** [comment]
it looks like the right link is https://www.eclipse.org/codewind/remote-deploying-codewind.html

**Comment by DavidG1011** [comment]
Fixed. Thanks, @tetchel!
