### ISSUE TITLE
Provide ability to run the 'diagnostics' function from within the IDE's

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#2851]
We have now have a new diagnostics function 
```
cwctl --json dg
```
That returns a json object with the location of the zip file it has created
```
{"outputdir":"/Users/tobes/.codewind/diagnostics/20200505145612"}
```
This file contains logs etc from Codewind and its projects.   This needs to be triggered from within the IDE's to enable use by codewind users rather than having to drop to the command line.

**Comment by eharris369** [comment]
Eclipse IDE PR: https://github.com/eclipse/codewind-eclipse/pull/713

**Comment by eharris369** [comment]
Eclipse IDE accessibility testing for this feature complete. No issues found.

**Comment by tetchel** [comment]
@sishida for docs, the section https://www.eclipse.org/codewind/troubleshooting.html#collecting-log-files-and-environment-data should be amended to mention you can do this in VS Code and Eclipse now.

In VS Code, it's accessed through the `Codewind: Capture Diagnostics` command.

**Comment by eharris369** [comment]
@sishida 
For Eclipse it is similar to changing the Codewind server log level. First the user must enable support features in the Codewind preferences:
![image](https://user-images.githubusercontent.com/9484320/82599363-2195c400-9b7a-11ea-8c6a-ded87e09eaa4.png)
And then they can right-click on the connection and select Collect Diagnostics:
![image](https://user-images.githubusercontent.com/9484320/82599584-95d06780-9b7a-11ea-98b9-54c46452a702.png)
