### ISSUE TITLE
cwctl diagnostics should not create projects folder 

### ISSUE THREAD

**Issue by stalleyj** [eclipse/codewind#2856]
**Description:**
cwctl diagnostics creates a folder called projects when it has not been asked to collect projects.  This is confusing as an empty directory makes it look like the collection failed.

It should only create the folder when collecting project diagnostics.

**Steps to reproduce:**
run ./cwctl diagnostics
There will be a directory /local and /projects in that but no project information.

**Comment by mattcolegate** [comment]
PR ready for review https://github.com/eclipse/codewind-installer/pull/479

**Comment by mattcolegate** [comment]
PR Merged
/pipeline Verify
