### ISSUE TITLE
cwctl diagnostics should only attempt collection of IDE logs when the flag is specified

### ISSUE THREAD

**Issue by stalleyj** [eclipse/codewind#2857]
**Description:**
cwctl diagnostics flags for IDE logs are confusing. The information in the README is confusing as it suggests that there is a default value of "" for eclipse/intelliJ log locations but there is not. 

Also if the user does not specify the flag, we should not attempt to collect the log file. We currently tell the user "Unable to collect Eclipse logs - workspace not specified" which they know as they did not specify it. 

Simply move the check of the flag to before the function call to gatherCodewindEclipseLogs and similar for intelliJ. 

**Steps to reproduce:**

**Workaround:**

**Comment by mattcolegate** [comment]
How would you see this working for IntelliJ, as there is a default log directory we can check but the user can specify it to be anywhere?

**Comment by mattcolegate** [comment]
PR ready for review https://github.com/eclipse/codewind-installer/pull/478

**Comment by mattcolegate** [comment]
Commits made to PR to address comments: PR ready for re-review eclipse/codewind-installer#478

**Comment by mattcolegate** [comment]
PR merged
/pipeline Verify

**Comment by mattcolegate** [comment]
@stalleyj Please can you verify that the code is working as expected?

**Comment by stalleyj** [comment]
Working as expected.
