### ISSUE TITLE
SVT:Hybrid:Failed to connect to remote codewind 0.12.0  instance

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#2863]
**Codewind version:** 0.12.0
**OS:** Windows/OS 4.3.18

**Che version:**
**IDE extension version:** Codewind 0.12.0
**IDE version:** Eclipse 2019-09
**Kubernetes cluster:** OCP 4.3.18

**Description:**
With the Codewind 0.12.0 hybrid operator install failed to connect to remote codewind. The error says "Account is not fully set up". I do not see same problem with the master branch operator which is deploying codewind latest.

```
An error occurred while trying to connect the ocp43-cavlier connection.
{"error":"invalid_grant","error_description":"Account is not fully set up"}
```

![image](https://user-images.githubusercontent.com/713849/81207058-f9fc0480-8f9a-11ea-84c4-01253f2b90ad.png)

**Steps to reproduce:**
1. Install remote codewind 0.12.0 operator.
2. Create codewind instance.
3. Connect from eclipse workspace and it fails with the above failure.

**Workaround:**

**Comment by malincoln** [comment]
@tobespc pls review and assign.  Thanks

**Comment by tetchel** [comment]
this happens if you use the 'temporary password' option, see my last bullet in https://github.com/eclipse/codewind/issues/2753#issue-605736053

**Comment by jagraj** [comment]
I did disable temporary password and I still see same problem with 0.12.0 branch. I can connect to master fine. 

```
java.io.IOException: {"error":"invalid_grant","error_description":"Account is not fully set up"}

	at org.eclipse.codewind.core.internal.cli.AuthUtil.getAuthToken(AuthUtil.java:79)
	at org.eclipse.codewind.core.internal.cli.AuthUtil.genAuthToken(AuthUtil.java:63)
	at org.eclipse.codewind.ui.internal.wizards.CodewindConnectionComposite.createConnection(CodewindConnectionComposite.java:235)
	at org.eclipse.codewind.ui.internal.wizards.NewCodewindConnectionPage.createConnection(NewCodewindConnectionPage.java:80)
	at org.eclipse.codewind.ui.internal.wizards.NewCodewindConnectionWizard$1.run(NewCodewindConnectionWizard.java:64)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by tobespc** [comment]
I installed this last night and it went through fine @jagraj

**Comment by tobespc** [comment]
If you have set a temporary password, the user will need to log in to keycloak to set a new one.  That message you are seeing is coming back from keycloak.

https://www.keycloak.org/docs/5.0/server_admin/#changing-passwords

From a codewind UX, we could have the IDE detect this message and inform the user to log in and change their password.  But this will require some thought.  ]

I don't believe this is stop ship tag as its a setup issue where 'jane' has not been setup correctly before attempting to use codewind

**Comment by tobespc** [comment]
This would be a perfect candidate for the troubleshooting guide in docs

**Comment by jagraj** [comment]
Ok, more info from this failure. First time this has been failed due to temp password `on`. This failed as expected from the IDE. I went to Keycloak and deleted credentials to the user and created new credentials with temp off option. I tried to connect to codewind after that and it still fails from IDE with the same error reported above. The only option here to make it to work , delete codewind instance and delete the user and recreate same user with "temp password" off. After this , I recreated codewind instance for same user then it worked. Looks like we need to doc this for the users. I agree this is best candidate for troubleshooting and fix can be delivered in future releases to detect temp password requirement and let user change it and proceed with the connection after that to remote codewind.

Once we doc troubleshooting this then we can make this as "hot" to deliver better fix.

**Comment by malincoln** [comment]
@sishida @micgibso ^^^

**Comment by sishida** [comment]
If a fix will be delivered in future releases, will it suffice to leave information for users in this issue and forego the troubleshooting documentation update?

**Comment by malincoln** [comment]
@tobespc @jagraj can this now be closed as Michael has completed the troubleshooting update?

**Comment by jagraj** [comment]
@micgibso 
Thanks for the doc. We are good now. Closing this issue now.
