### ISSUE TITLE
DeprecationWarning: crypto.Credentials is deprecated.

### ISSUE THREAD

**Issue by josephca** [eclipse/codewind#2864]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description of the enhancement:**

Fix DeprecationWarnings appeared in test.

10:03:19 (node:9442) [DEP0091] DeprecationWarning: crypto.DEFAULT_ENCODING is deprecated.
10:03:19 (node:9442) [DEP0010] DeprecationWarning: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
10:03:19 (node:9442) [DEP0011] DeprecationWarning: crypto.Credentials is deprecated. Use tls.SecureContext instead.
10:03:19 PFE - unit test

**Proposed solution:** 

Change import statments
from
import * as crypto from "crypto"
to 
import crypto from "crypto"

**Comment by jgwest** [comment]
Adding iterative-dev as next step is for me to review the PR.

**Comment by jgwest** [comment]
@josephca Sorry for the delay, I have approved, and thanks for tackling this!

**Comment by josephca** [comment]
Closing it without any code change.
