### ISSUE TITLE
SVT : Eclipse : Mac : Appsody Quarkus Kafka project does not start

### ISSUE THREAD

**Issue by mmulholl** [eclipse/codewind#2873]
**Codewind version:** 0.12.0
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:** Eclispe jee 2019-09
**Kubernetes cluster:**

**Description:**
Not sure of this is expected but my Appsody Quarkus Kafka project does not start.

[pfe.log](https://github.com/eclipse/codewind/files/4593883/pfe.log)
[quarkuskafka.log](https://github.com/eclipse/codewind/files/4593884/quarkuskafka.log)

**Steps to reproduce:**

**Workaround:**

**Comment by makandre** [comment]
Similar to #2874, this particular template appears to require a Kafka instance.  Will check with appsody folks.

/area appsody

**Comment by mmulholl** [comment]
Closing this issue, these project are not expected to start
