### ISSUE TITLE
SVT : Eclipse : Mac : Appsody Spring Boot Kafka project does not start

### ISSUE THREAD

**Issue by mmulholl** [eclipse/codewind#2874]
**Codewind version:**0.12.0
**OS:**Mac

**Che version:**
**IDE extension version:**Eclipse jee 2019-09
**IDE version:**
**Kubernetes cluster:**

**Description:**
Not sure if this is as expected but Appsody Spring Boot Quarkus project does not start

[pfe.log](https://github.com/eclipse/codewind/files/4593916/pfe.log)
[springkafka.log](https://github.com/eclipse/codewind/files/4593917/springkafka.log)

**Steps to reproduce:**

**Workaround:**

**Comment by makandre** [comment]
It looks like this particular template doesn't start without a Kafka instance configured... will need to check with the appsody folks on this one.  

/area appsody

**Comment by makandre** [comment]
btw this is Spring Boot **Kafka** and not Spring Boot **Quarkus** right? @mmulholl

**Comment by mmulholl** [comment]
Oops, updated to kafka, thx

**Comment by mmulholl** [comment]
Closing, these projects are not expected to start.
