### ISSUE TITLE
Update documentation to include Intellij

### ISSUE THREAD

**Issue by jasperchui** [eclipse/codewind#2879]
**Description:**
Update docs to include Intellij:
https://www.eclipse.org/codewind/overview.html#what-integrated-development-environments-ides-do-codewind-support
Codewind is available as a desktop IDE extension for VS Code and Eclipse and as a cloud-based IDE extension for Eclipse Che.

**Comment by jasperchui** [comment]
also: 
https://www.eclipse.org/codewind/remote-deploying-codewind.html#prerequisites
stall your preferred IDE on your local machine. For more information about installing Eclipse, see Getting started with Codewind for Eclipse, or for more information about installing VS Code, see Getting started with Codewind for VS Code.

**Comment by sishida** [comment]
Updates:
1️⃣ PR for the overview topic: https://github.com/eclipse/codewind-docs/pull/578
2️⃣ IntelliJ is added to the IDE list in the Markdown file: https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/remote-deploying-codewind.md#prerequisites. The update should appear with the next release.

**Comment by jasperchui** [comment]
Another one: 
https://www.eclipse.org/codewind/remote-codewind-overview.html#prerequisites
Install your preferred IDE on your local machine. For more information about installing Eclipse, see Getting started with Codewind for Eclipse, or for more information about installing VS Code, see Getting started with Codewind for VS Code.

**Comment by jasperchui** [comment]
template manager: 
https://www.eclipse.org/codewind/workingwithtemplates.html#managing-templates
Note: Template Source Manager is the name used in VS Code. Eclipse uses the name Manage Template Sources.

**Comment by jasperchui** [comment]
This section should be reviewed too. "Use the Template Source Manager to perform the following actions"

**Comment by jasperchui** [comment]
And this section: 
https://www.eclipse.org/codewind/workingwithtemplates.html#adding-your-template-sources-to-codewind

**Comment by jasperchui** [comment]
Metrics dashboard Prereqs:  https://www.eclipse.org/codewind/metrics-dashboard.html#prerequisites
Should it include Intellij @jopit @keithchong @cccanderson could you confirm if this function is available? Thanks.

**Comment by jopit** [comment]
Metrics dashboard is not yet available in IntelliJ.  Performance dashboard is available.

**Comment by jopit** [comment]
Metrics dashboard will be available for 0.12.

**Comment by sishida** [comment]
Comment from @stalleyj: "I noticed that the main landing page has a section for IDE support that doesn't currently mention IntelliJ" (Originally here: https://github.com/eclipse/codewind/issues/2982#issuecomment-631997200)

**Comment by sishida** [comment]
These files now include mention of IntelliJ. Please note that the updates might not appear on Codewind.dev until after 0.13.0 GAs. However, if you look at the Markdown files, you can see the mention of IntelliJ included.
- `overview.html#what-integrated-development-environments-ides-do-codewind-support`
- `remote-deploying-codewind.html#prerequisites`
- `performance.md`
- `metrics-dashboard.md`

This PR https://github.com/eclipse/codewind-docs/pull/618 adds IntelliJ to https://www.eclipse.org/codewind/workingwithtemplates.html#managing-templates.

This PR https://github.com/eclipse/codewind-docs/pull/619 adds IntelliJ to the main home page, https://www.eclipse.org/codewind/.

**Comment by sishida** [comment]
- Reached out to Jasper and informed him of the update.
- PR #618 can be tracked under eclipse/codewind#3023 or eclipse/codewind#985 instead.
- Closing this issue.
