### ISSUE TITLE
Should this include IBM Cloud Kubernetes Service

### ISSUE THREAD

**Issue by jasperchui** [eclipse/codewind#2882]
**Description:**
https://www.eclipse.org/codewind/remote-deploying-codewind.html#prerequisites
Have an active Kubernetes context and log in to the cluster. Codewind can run in OpenShift 3.11, OpenShift 4.3, OpenShift in IBM Public Cloud, standalone Kubernetes, and Kubernetes in Docker.

**Comment by johnmcollier** [comment]
Here's my 2 cents:

IMO, since we're Kube-generic, I'm not crazy on listing specific distributions of Kube that we should support. I'd almost rather we list the requirements we have on Kube (Kube version, ingress, storage, etc), then saying "OpenShift 3.11, OpenShift 4.x, ..."

**Comment by rtaniwa** [comment]
I kind of agree with you @johnmcollier to keep it simple for us. I do however wonder...will doing so make it more difficult for our users (especially those that may be newer to Kube) to be able to determine what version of those distributions suits their needs for prerequisites? Just curious if a meet in the middle approach makes sense where we list the version requirements for the various components, but then have something that states what distributions we have tested on? Curious what other tools similar to ours do?

**Comment by jasperchui** [comment]
I agree with the meet in the middle.  For those who know Kubernetes the version information will be sufficient and for those working with specific Cloud providers they will have confidence this has been tested against it. 

I found Coder (https://coder.com/docs/installation).  For their installation they have:
Kubernetes Node Requirements
Coder Enterprise runs on any Kubernetes cluster that supports the following requirements.

We require that you run at least Kubernetes version 1.13.7 with the following extensions enabled:

apps/v1
rbac.authorization.k8s.io/v1
metrics.k8s.io
storage.k8s.io/v1
networking.k8s.io/v1
extensions/v1beta1
We recommend at least 2 cores and 4GB of RAM for the basic control services. A disk as small as 20GB will suffice.

The following throughput is recommended:

read: 3000 IOPS at 50MB/s
write: 3000 IOPS at 50MB/s
Furthermore, for each active developer we require 1 core, 1 GB of RAM, and 10 GB of storage.

We’re happy to look into support for different versions and configurations.

And deployment guides for Amazon Elastic Kubernetes Engine (EKS) and Google Kubernetes Engine (GKE).

**Comment by johnmcollier** [comment]
Yeah, agreed on a middle approach. What about something like:

```
We’ve validated Codewind on these Kubernetes distributions
- OpenShift 4.3
- IKS
- ...

However, Codewind should be able to run on any Kubernetes distribution that meets the following requirements:
- Kube 1.11
- Support for RWX volumes
- ...
```

**Comment by jgwest** [comment]
My two cents:
- It's fine if we include IKS as long as we include one other service to imply our cloud-vendor agnosticism (at least one from the list of AKS, EKS, GKE)
- In the same breath, include a note saying PRs are welcome if other vendors want to test and document support for their cloud in our repo.

This guidance would also apply if we wanted to include specific step-by-step instructions on how to install to IKS on the Codewind pages (equivalent to [what Che has for AWS/Azure](https://www.eclipse.org/che/docs/che-7/deploying-che-on-kubernetes-on-aws/))

**Comment by sishida** [comment]
For updates based on feedback in this issue, please see the PR, https://github.com/eclipse/codewind-docs/pull/623.

@johnmcollier, @jgwest, Could you please check the list of Kubernetes distributions and see if we're missing anything?

I'm also not sure if this is the best place for the contribution link...it almost feels like an ad in the  midst of the doc. 😅If this is an accepted practice in open source communities, though, we can leave it. 😄

**Comment by jgwest** [comment]
@sishida 

It's fairly common for open source components (that can be hosted in the cloud) to include references to an inexhaustive set of specific public clouds they support, and/or to provide quick start guidelines that use those clouds.

Below are some examples of that I have seen recently, but let us know if it feels like from your perspective that we are crossing a line from helpful, slightly self-interested user guidance, into blatant, shameless self-promotion 😄 .

JenkinX:
https://jenkins-x.io/docs/getting-started/ (GCP and AWS)

Che:
https://www.eclipse.org/che/docs/che-7/hosted-che/  (OpenShift Online, AWS, Azure)

Theia:
https://theia-ide.org/ (GitPod, their pay service)

OpenShift: 
https://www.openshift.com/  (Azure, IKS, Dedicated on AWS/GCE)

Mongo:
https://www.mongodb.com/cloud/atlas/pricing 

Kubeflow: 
https://www.kubeflow.org/docs/started/getting-started/ (AWS, Azure, GCP, IKS, OpenSHift)

**Comment by sishida** [comment]
@jgwest Thank you for clarifying that the list doesn't have to be exhaustive. I think we're good to go if we're following standard conventions and practices of the wider community. :)

**Comment by sishida** [comment]
PR merged! Closing this issue. 👍
