### ISSUE TITLE
Missing instructions for other ides (Eclipse and Intellij)

### ISSUE THREAD

**Issue by jasperchui** [eclipse/codewind#2887]
**Description:**
Code highlighting for profiling data (https://www.eclipse.org/codewind/metrics-dashboard.html#code-highlighting-for-profiling-data)
This section has instructions to install the appropriate VS Code extension VSCode however does not include instructions for the other IDEs.

**Comment by tetchel** [comment]
There is no profiling extension for those other two IDEs. This section should be explicitly marked as VS Code only.

**Comment by sishida** [comment]
Merged PR. Confirmed with Jasper we're good to close this issue.
