### ISSUE TITLE
Reference to microclimate

### ISSUE THREAD

**Issue by jasperchui** [eclipse/codewind#2888]
**Description:**
The screenshot has reference to microclimate.
https://www.eclipse.org/codewind/metrics-dashboard.html#interpreting-the-annotation-tooltip

**Comment by tetchel** [comment]
it's also applicable to VS Code and theia, not just Theia

**Comment by sishida** [comment]
PR for this issue replaces the text content of the screenshot with Markdown text: https://github.com/eclipse/codewind-docs/pull/636
