### ISSUE TITLE
Screenshot says Eclipse document says Intellij in troubleshooting doc

### ISSUE THREAD

**Issue by jasperchui** [eclipse/codewind#2889]
**Description:**
For this entry in the troubleshooting doc: https://www.eclipse.org/codewind/troubleshooting.html#cannot-find-codewind-in-marketplace-when-attempting-to-install-in-intellij
the section references intellij but the screenshot shows eclipse.

**Comment by sishida** [comment]
Created PR to remove the screenshot: https://github.com/eclipse/codewind-docs/pull/637

**Comment by sishida** [comment]
I learned from John that the whole section where the screenshot appeared is now obsolete. I have removed the whole section. Closing this issue.
