### ISSUE TITLE
Default Node template doesn't have up-to-date appmetrics?

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#2890]
`master` branch

I see this message with a new Node project:
![image](https://user-images.githubusercontent.com/8888438/81441229-657ed700-913f-11ea-8a3d-cc9507c73f7a.png)

I don't think our templates should generate any warnings out-of-the-box. Can we update the appmetrics version in the package.json?

**Comment by tetchel** [comment]
I also still see this warning after enabling Inject Appmetrics and letting the project restart.

**Comment by tobespc** [comment]
you are using an old version of codewind performance, that no longer appears on latest master
