### ISSUE TITLE
New Spring project is missing metrics capabilities

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#2891]
`master` branch. 0.12 seems OK.

My new Spring project reports it doesn't have the capabilities to support the metrics dash or performance dash.

Snippet from the .inf:

```
  "canMetricsBeInjected": true,
  "buildLogPath": "/codewind-workspace/.logs/springb-6d713fc0-9149-11ea-9131-c331b4533cef/docker.build.log",
  "state": "open",
  "autoBuild": true,
  "injectMetrics": false,
  "metricsAvailable": false,
  "metricsDashboard": {
    "hosting": null,
    "path": null
  },
  "metricsCapabilities": {
    "liveMetricsAvailable": false,
    "metricsEndpoint": false,
    "appmetricsEndpoint": false,
    "microprofilePackageFoundInBuildFile": false,
    "appmetricsPackageFoundInBuildFile": true
  },
  "links": {
    "_links": [],
    "fileName": ".codewind-project-links.env",
    "filePath": "/codewind-workspace/springb/.codewind-project-links.env"
  },
  "workspaceDir": "/codewind-workspace/springb",
  "injection": {
    "injectable": true,
    "injected": false
  },
  "perfDashboardPath": null,
```

(also, maybe we could remove the `injectMetrics` and `metricsAvailable` deprecated since https://github.com/eclipse/codewind/issues/1815)

**Comment by tetchel** [comment]
after a restart, now my microprofile project and node project are missing the perf dashboard too

![image](https://user-images.githubusercontent.com/8888438/81450403-5a807280-9150-11ea-9079-be256d29cdc9.png)
![image](https://user-images.githubusercontent.com/8888438/81450415-5f452680-9150-11ea-940c-2c8f9dc2d102.png)

**Comment by tobespc** [comment]
we also see this a lot and I've been trying to narrow it down to whether the project.inf has missing data or whether a socket message is being missed

**Comment by james-wallis** [comment]
/assign

From looking at this we just need to change the endpoints to have a trailing slash.

**Comment by james-wallis** [comment]
/pipeline verify
PR has been merged for this issue, @tetchel can you please verify.

**Comment by tetchel** [comment]
👍
