### ISSUE TITLE
Error creating Codewind project node-js.app

### ISSUE THREAD

**Issue by naveenkaratekid** [eclipse/codewind#29]
Currently running MacOS Mojave 10.14.5
with Eclipse IDE for Enterprise Java Developers Version: 2019-06 (4.12.0)

When I try to create a project from the available templates in Codewind, I keep getting an error message similar to the one below:

'Creating Codewind project: node-js-app' has encountered a problem.
An error occurred trying to create Codewind project node-js-app

Expanded Error Message:

An error occurred trying to create Codewind project node-js-app
Received bad response code 400 for uri http://localhost:9090/api/v1/projects with error message Error while validating request: request.body should have required property 'url'

**Comment by tetchel** [comment]
You get that error if your Codewind backend version is outdated compared to your Codewind tools (plugin) verison. What are the versions of each?

**Comment by naveenkaratekid** [comment]
On Eclipse and VSCode, I have version 0.2.0. In my mac, I have the Codewind executable file, and when I run it, it shows the version I have is 0.2.0 as well.

**Comment by tetchel** [comment]
Don't run it, let the tools manage the version for you.

**Comment by naveenkaratekid** [comment]
Codewind works fine in VSCode, but some reason, Eclipse throws an error. I was able to make the python app I demoed this morning in VSCode, but in Eclipse, I have gotten the same error message.

**Comment by tetchel** [comment]
try a more recent version of the eclipse plugin, https://download.eclipse.org/codewind/codewind-eclipse/master/latest/?d

**Comment by naveenkaratekid** [comment]
I just uninstalled the plugin from eclipse, and then re-imported it from the zip archive I got from the link you sent me. However, I am still getting this error message:

An error occurred trying to create Codewind project my-node-project
Received bad response code 400 for uri http://localhost:9090/api/v1/projects with error message Error while validating request: request.body should have required property 'url'

**Comment by eharris369** [comment]
You need to make sure any Codewind container images are uninstalled first.  I am wondering if you have a version installed already from when you were using VSCode?  From Eclipse, right click on **Codewind** and select **Uninstall**.  When it is uninstalled delete the codewind-workspace folder from your home directory.  The best way to make sure everything works is to install the Codewind plugin from the Eclipse marketplace rather than a development one (otherwise you need to set some environment variables to get the latest development container images).  Once that is installed double click on Codewind in the Codewind Explorer view to install the Codewind.

**Comment by tetchel** [comment]
@naveenkaratekid have you resolved this?

**Comment by naveenkaratekid** [comment]
I have uninstalled the Codewind plugin and then re-installed it from the public marketplace as @eharris369 suggested. When I tried to make a new project again, I got the exact same error as before

**Comment by tetchel** [comment]
also make sure you stop all your docker containers and do a system prune so that the plugin may install the correct version of the codewind backend

**Comment by naveenkaratekid** [comment]
I have killed the running docker images on my system to free up space. Then I restarted Codewind plugin in VScode. then I opened Eclipse and attempted to make a new project using Codewind's plug-in, and I get the exact same error as before.

**Comment by tetchel** [comment]
I really don't know what more we can offer; it works for our users

**Comment by naveenkaratekid** [comment]
Let me try that. Thanks @tetchel and @eharris369! I appreciate your help

**Comment by eharris369** [comment]
Also, please install Codewind using Eclipse and not VSCode.  Better not to start VSCode at all.

**Comment by tetchel** [comment]
yes, one or the other if you are encountering such issues (though the two of them should install the same backend version...)

**Comment by naveenkaratekid** [comment]
Got it. Codewind is installed in both VSCode and Eclipse.

Naveen K
510-304-8025

________________________________

**Comment by jopit** [comment]
@naveenkaratekid are you still encountering this problem?  Is there a way we can reproduce it?

**Comment by naveenkaratekid** [comment]
I’ve fixed it. I uninstalled Codewind from vs code and installed it in eclipse. It’s been fixed. You can close this issue. Thank you!

Naveen K
510-304-8025

________________________________
