### ISSUE TITLE
incorrect status on performance capability panel

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#2900]
**Codewind version:** Latest
**OS:** Mac

**Che version:** Latest
**IDE extension version:** Latest
**IDE version:** Latest
**Kubernetes cluster:**

**Description:**
I'm testing the performance dashboard for the new capabilities panel and have found that the status is incorrect.

Create a websphere liberty microprofile app and then open the performance container.  The initial status should so everything as green.   Then run a few load tests through and recheck the panelling.  It now says that benchmarking is unavailable.
![image](https://user-images.githubusercontent.com/13151286/81562087-2beedb80-938c-11ea-924c-883dc8d8efa7.png)

Checking the JSON returned from the /api/v1/projects/{id}/metrics/status calls shows the api is incorrectly returning the value for appmetrics

```
{
  "liveMetricsAvailable": true,
  "metricsEndpoint": "/metrics",
  "appmetricsEndpoint": false,
  "microprofilePackageFoundInBuildFile": true,
  "appmetricsPackageFoundInBuildFile": true,
  "hasTimedMetrics": false,
  "canMetricsBeInjected": true,
  "projectRunning": true
}
```
I can get to the /javametrics-dash endpoint so "appmetricsEndpoint" should be true

**Comment by tobespc** [comment]
This is also incorrect for node apps
```

liveMetricsAvailable | false
-- | --
metricsEndpoint | false
appmetricsEndpoint | false
microprofilePackageFoundInBuildFile | false
appmetricsPackageFoundInBuildFile | true
hasTimedMetrics | false
canMetricsBeInjected | true
projectRunning | true

```
with appmetricsEndpoint not detecting correctly

**Comment by tobespc** [comment]
this looks ok on 0.12.0 so could be just an issue with master

**Comment by markcor11** [comment]
Investigating,  The status of appmetricsEndpoint does change before during and after a load run or when the project is being built. I was watching it and saw it switch between a string and a boolean. It seems that the first time through it look ok (shows the "/javametrics-dash" string) then after running a 2nd or 3rd load test (which restarts the project) it goes to false and stays there. The only way out of that is to disable the project and re-enable it.


eg: 


After project start : 
```json
{
  "liveMetricsAvailable": true,
  "metricsEndpoint": "/metrics",
  "appmetricsEndpoint": "/javametrics-dash",
  "microprofilePackageFoundInBuildFile": true,
  "appmetricsPackageFoundInBuildFile": true,
  "hasTimedMetrics": true,
  "canMetricsBeInjected": true,
  "projectRunning": true
}
```

Preparing to start a load run:
 
```json
{
  "liveMetricsAvailable": false,
  "metricsEndpoint": false,
  "appmetricsEndpoint": false,
  "microprofilePackageFoundInBuildFile": true,
  "appmetricsPackageFoundInBuildFile": true,
  "hasTimedMetrics": false,
  "canMetricsBeInjected": true,
  "projectRunning": false
}
```

During the load run

```json
{
  "liveMetricsAvailable": true,
  "metricsEndpoint": "/metrics",
  "appmetricsEndpoint": "/javametrics-dash",
  "microprofilePackageFoundInBuildFile": true,
  "appmetricsPackageFoundInBuildFile": true,
  "hasTimedMetrics": true,
  "canMetricsBeInjected": true,
  "projectRunning": true
}
```

after the load run: 

```json
{
  "liveMetricsAvailable": true,
  "metricsEndpoint": "/metrics",
  "appmetricsEndpoint": false,
  "microprofilePackageFoundInBuildFile": true,
  "appmetricsPackageFoundInBuildFile": true,
  "hasTimedMetrics": false,
  "canMetricsBeInjected": true,
  "projectRunning": true
}

**Comment by james-wallis** [comment]
From looking at the logs, when we make a loadrun request Turbine sends multiple `starting` and a `started` socket messages so its possible that the `setMetricsAvailability` function is overwriting itself. I have raised a PR to only run the `setMetricsAvailability` function when the project is either `started` (the endpoints should be available) and `stopped` (the endpoints most likely will not be available).

**Comment by james-wallis** [comment]
/close
PR merged for this. Given that @tobespc reviewed it, I'll close this issue.
