### ISSUE TITLE
codewind templates makes references to IBM Box

### ISSUE THREAD

**Issue by AndyRWatson** [eclipse/codewind#2902]
**Codewind version:** 0.11
**OS:**  ALL

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**

Looking at the default codewind templates (aleit referenced at https://github.com/codewind-resources) I can see that that https://raw.githubusercontent.com/codewind-resources/codewind-templates/master/devfiles/index.json references icon files stored in https://ibm.box.com/shared/static

These files are likely unavailable without authentication so I assume this effects user experience?

**Steps to reproduce:**

**Workaround:** 

Fix to ensure any templates only reference content publically available, preferrablt within the codewind-resources repo

**Comment by tobespc** [comment]
We put those files there after we found that referencing them on git was not working.  I agree thats not the best place for them long term though

**Comment by mattcolegate** [comment]
So as far as I understand the issue, we can't host the icons on Github, as there's rendering issues between browsers if we do that, and we can't store the images in Box, because even if we can get around needing to authenticate, Box links expire and we can't see them anymore. We could also do with an offline/airgapped solution (which Git would have provided).

**Comment by jgwest** [comment]
@mattcolegate if it's only icons you are using, you can embed them in the HTML as base 64 URL strings:

**Comment by mattcolegate** [comment]
I now have a Che instance with Codewind - I'll be testing to see if Che can use embedded base64 URL strings from the JSON.

**Comment by mattcolegate** [comment]
The Che instance I had was unable to help me as I was unable to create projects. Tried again with two other che instances provided by team members and was similarly unsuccessful. There seems to be a problem with Codewind on the latest Che. I'm back to hunting for a Codewind on Che instance with the ability to create projects.

**Comment by tobespc** [comment]
I'll setup tobes-ocp to work (I need that done anyway)

**Comment by mattcolegate** [comment]
Putting this back - I still can't get access to any of the Codewind on Che instances in a way that lets me work on this, I'm hitting problems that others are not having.
/unassign
/pipeline portal backlog

**Comment by tobespc** [comment]
have everything deployed and running and can see the icons don't work

**Comment by tobespc** [comment]
all fixed and running 
![Screenshot 2020-06-16 at 11 34 55](https://user-images.githubusercontent.com/13151286/84764333-73890880-afc5-11ea-90f3-1af43e1edbfc.png)
