### ISSUE TITLE
(master) cwctl project create broken

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#2903]
Since this morning, I can't create projects anymore. I can reproduce it locally too. It looks like the json output of `project create` is the empty string.

https://ci.eclipse.org/codewind/job/Codewind/job/codewind-vscode/job/master/131/console

```
[INFO: 11:33:40.949 CLIWrapper.ts:156]: Running CLI command: cwctl --json --insecure project create --conid local --path /Users/tim/vscode-codewind-workspace/noode --url https://github.com/codewind-resources/nodeExpressTemplate
[DBUG: 11:33:42.311 CLIWrapper.ts:234]: Successfully ran CLI command cwctl --json --insecure project create --conid local --path /Users/tim/vscode-codewind-workspace/noode --url https://github.com/codewind-resources/nodeExpressTemplate
[ERRO: 11:33:42.315 CLIWrapper.ts:241]: Missing expected JSON output from CLI command, output was ""
[ERRO: 11:33:42.317 CreateUserProjectCmd.ts:104]: Error creating new project:  Error: Unknown error creating noode at /Users/tim/vscode-codewind-workspace/noode
    at /Users/tim/programs/codewind-vscode-2/dev/src/command/connection/CreateUserProjectCmd.ts:404:19
    at Generator.next (<anonymous>)
    at fulfilled (/Users/tim/programs/codewind-vscode-2/dev/out/command/connection/CreateUserProjectCmd.js:15:58)
```

**Comment by tetchel** [comment]
Looks like https://github.com/eclipse/codewind-installer/pull/464 is the culprit so fyi @stalleyj @mattcolegate

**Comment by tetchel** [comment]
https://github.com/eclipse/codewind-installer/pull/464/files#diff-fa96b9d5a42d1b81fc84841647707879R82 ?

**Comment by mattcolegate** [comment]
Hi @tetchel , do you happen to know what the expected output should be?

**Comment by tetchel** [comment]
the `validate` output, eg
```
{"status":"success","projectPath":"/home/genie.codewind/workspace/Codewind_codewind-vscode_master/dev/codewind-workspace/test-node-js-express-1177","result":{"language":"javascript","projectType":"nodejs"}}
```

**Comment by mattcolegate** [comment]
Curiously I get that on latest if `--json` isn't specified, but not if it is! Debugging now.

**Comment by mattcolegate** [comment]
OK, I see the problem - I'll have a PR up in a jiffy

**Comment by tetchel** [comment]
Please add a test case too

**Comment by mattcolegate** [comment]
@tetchel https://github.com/eclipse/codewind-installer/pull/470 ready for review

**Comment by tetchel** [comment]
Looks good thanks

**Comment by mattcolegate** [comment]
Test case added via PR https://github.com/eclipse/codewind-installer/pull/471
