### ISSUE TITLE
Update codewind.dev landing page image to include IntelliJ

### ISSUE THREAD

**Issue by AndyRWatson** [eclipse/codewind#2913]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description of the enhancement:**

With our support for IntelliJ, we should also look to update our main codewind.dev landing page initial image to include IntelliJ (Currently we show VSCode/Eclipse/Che)

**Proposed solution:**

**Comment by AndyRWatson** [comment]
linking to https://github.com/eclipse/codewind/issues/2908

**Comment by micgibso** [comment]
Significant signposting and user orientation improvements made, and the initial image quoted above has now gone, replaced with a list. See https://www.eclipse.org/codewind/gettingstarted.html
@MelHopper fyi...

**Comment by jopit** [comment]
There is a hero image for IntelliJ: https://github.com/eclipse/codewind-docs/blob/master/docs/images/hero-intellij.png

**Comment by sishida** [comment]
Here is the IntelliJ image from John P. to use for the home page: https://github.com/eclipse/codewind-docs/blob/master/docs/images/hero-intellij.png

**Comment by jcockbain** [comment]
@AndyRWatson is this https://www.eclipse.org/codewind/ or https://www.eclipse.org/codewind/gettingstarted.html?

**Comment by sishida** [comment]
IntelliJ screenshot from @jopit: https://github.com/eclipse/codewind-docs/blob/master/docs/images/hero-intellij.png

**Comment by micgibso** [comment]
Closing as complete.
