### ISSUE TITLE
Documentation style guidelines

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind#2914]
- Here are current style guidelines in the Codewind-docs wiki: https://github.com/eclipse/codewind-docs/wiki/Writing-style-guidelines
- Here is an issue that includes feedback that pertains to style: https://github.com/eclipse/codewind/issues/2136

**Comment by MelHopper** [comment]
TASK: With respect to increasing the use of bold to also call out 'asides' to the user (see e.g. vsc-getting-started.html), @melanieh to investigate whether we can improve styling in topics to have e.g:
- a bar added like Docker https://docs.docker.com/get-started/part2/ 
- a box like Open Liberty

**Comment by MelHopper** [comment]
TASK: bullets and numbering: Can we use HTML inside markdown to get around the limitation in markdown of not being able to use ordered lists for sub-bullets?

**Comment by MelHopper** [comment]
Style guide to be embedded as much as possible into Acrolinx by ID team.

**Comment by sishida** [comment]
Other style guide considerations:
- Introductory sentences, such as those that come after titles/headings and those that precede lists, can be redundant and repeat info in the title/heading instead of providing more information to the user. How can we make them more useful?
- Clarify "username" vs. "user name." The "username" version is what Acrolinx suggests.

**Comment by micgibso** [comment]
Closing, if required, pls move to Box note.
