### ISSUE TITLE
Tile shortcut needed for IntelliJ Docs

### ISSUE THREAD

**Issue by maysunfaisal** [eclipse/codewind#2923]
<img width="1675" alt="Screen Shot 2020-05-12 at 3 46 18 PM" src="https://user-images.githubusercontent.com/31771087/81738523-d25bdf00-9467-11ea-85c1-69b41b64924c.png">

Can we pls have a tile shortcut for IntelliJ like the other IDE/platforms?

/area website

**Comment by AndyRWatson** [comment]
Potential dupe ? https://github.com/eclipse/codewind/issues/2503

**Comment by sishida** [comment]
Closing as duplicate.
