### ISSUE TITLE
Fix Codewind operator docs for remote install

### ISSUE THREAD

**Issue by maysunfaisal** [eclipse/codewind#2926]
**Description:**

I found various issues when trying to deploy Codewind remotely using the new Operator docs. IMO the docs are not user friendly, and we will be pinged for detailed explanation or missing steps from a novice user.

I am outlining some of the nits and fixes I would recommed:
- [ ] Add more details to adding user to Keycloak https://www.eclipse.org/codewind/remote-deploying-codewind.html#3-add-a-new-user-to-keycloak The doc doesn't mention about user needing to log in to the Administrative Console and the credentials needed to log in
- [ ] Incomplete and/or wrong information about the gatekeeper url in https://www.eclipse.org/codewind/remote-deploying-codewind.html#4-deploy-a-codewind-instance The doc mentions about `Your Codewind instance is deployed. Access it by copying and pasting the Access URL returned by the script into a browser.`  Logging in just says `OK`, not sure what to do with this information! Mention what this information means or remove the line altogether.. <img width="705" alt="Screen Shot 2020-05-12 at 5 38 58 PM" src="https://user-images.githubusercontent.com/31771087/81748330-b4967600-9477-11ea-9e79-2b8c9f868d9a.png">
- [ ] Section https://www.eclipse.org/codewind/remote-codewind-overview.html#overview-using-codewind-remotely has the same info as https://www.eclipse.org/codewind/remote-deploying-codewind.html#deploying-codewind-remotely
- [ ] Section https://www.eclipse.org/codewind/remote-codewind-overview.html#what-you-will-learn has overlapping info as https://www.eclipse.org/codewind/remote-deploying-codewind.html#what-you-will-learn
- [ ] Pls mention where and how we got the gatekeeper url, username and password in section https://www.eclipse.org/codewind/remotedeploy-vscode.html and https://www.eclipse.org/codewind/remotedeploy-eclipse.html i.e.; link to the Codewind operator installation doc

/area portal
/area docs

Marking this as hot, as I think we should prioritize this for the current/next release. Not necessary a stopship, because a user can get it working after struggling and fiddling around for ages!
/priority hot

**Comment by markcor11** [comment]
" fiddling around for ages!" - that's not good...

**Comment by maysunfaisal** [comment]
@markcor11 yes sir. I have been getting Slack DMs from novice Docker/Kube users around Codewind installation docs in general.

I am also doing a session about Codewind and will be touching how to install Codewind remotely. So I would like to get these docs updated because someone new will struggle to navigate around these docs.

**Comment by tobespc** [comment]
@micgibso Could you pick this up asap please and try a walkthrough.   If they are not clear we need to fix asap as we don't want the users first experience of using the operator to be anything less than perfect

**Comment by AndyRWatson** [comment]
I agree we could add some clarify and examples around the install processes steps and adding a new user

**Comment by MelHopper** [comment]
Re:

- [ ] Section https://www.eclipse.org/codewind/remote-codewind-overview.html#overview-using-codewind-remotely has the same info as https://www.eclipse.org/codewind/remote-deploying-codewind.html#deploying-codewind-remotely

- [ ]  Section https://www.eclipse.org/codewind/remote-codewind-overview.html#what-you-will-learn has overlapping info as https://www.eclipse.org/codewind/remote-deploying-codewind.html#what-you-will-learn

Fixes were merged a couple of weeks ago and are sitting on master, ready to be published in 0.12.0.

**Comment by micgibso** [comment]
https://github.com/eclipse/codewind/issues/2957 also impacts this and will help signpost users further, will liaise with Mark. (fyi @markcor11)

**Comment by micgibso** [comment]
Extensive modifications, including user orientation and extra steps, added as a result of testing the instructions.  Looking back through the description again today, just the last bullet needs addressing now for VS Code and Eclipse.

**Comment by micgibso** [comment]
Fixed remaining comment.
