### ISSUE TITLE
The codewind plugins on VSCode market place say "IBM" not "Eclipse".

### ISSUE THREAD

**Issue by gruffwizard** [eclipse/codewind#2928]
I think thats pretty clear.

The codewind plugins on VSCode market place say "IBM" not "Eclipse".   

![image](https://user-images.githubusercontent.com/9293028/81789096-67f47e80-94fb-11ea-80ce-bdd866e68ee1.png)

**Comment by jopit** [comment]
The plugins are published to the VSCode market place by IBM, not by Eclipse, so the entries are in fact correct.

**Comment by tetchel** [comment]
Here's the background: https://github.com/eclipse/codewind/issues/12

**Comment by gruffwizard** [comment]
@tetchel  thanks.  Well that's sucky!
