### ISSUE TITLE
Improve the design of the Guides pages

### ISSUE THREAD

**Issue by MelHopper** [eclipse/codewind#2929]
The current Guides design is based on the kabanero-io blog design. Design of the guides pages needs to be enhanced.

**Guides Page**
- add ability to click the guide title on the list of guides at Codewind.dev/guides to navigate to the guide, in addition to the current link 'read more'
- consider adding the objectives and image metadata to the individual guide boxes when this metadata becomes available.

**Page displaying a single guide**
- Add the description of the guide to the top of the guide 
- Add the image associated with the guide (metadata) to the guide. (Current status: image metadata not yet available).
-remove repetition the title of the Guide when it is displayed
- 'read more' is not a good link to have from an SEO point of view. UX input needed.
- show the guide titles as clickable entities by changing the colour to match the blue used by Design to show clickable entities in their content landing page design. 

**Feedback on blogs pages**
Some of the feedback from the blog design, identified in https://github.com/eclipse/codewind/issues/2575 , also applies here: 

- Show more preview posts on the blog.html. Right now it shows 3, but it would be nice to have some tiles to show more
- Show an optional preview photo to grab people's attention in the blog preview post page
- Allow tags and search to be enabled for easy blog post finding

**Comment by jcockbain** [comment]
@MelHopper I noticed the title repetition and am about to make a PR for that.

**Comment by jcockbain** [comment]
> add ability to click the guide title on the list of guides at Codewind.dev/guides to navigate to the guide, in addition to the current link 'read more'

Is this not already the case? I'm able to click the guide title to get to the guide on master.

**Comment by MelHopper** [comment]
> > add ability to click the guide title on the list of guides at Codewind.dev/guides to navigate to the guide, in addition to the current link 'read more'
> 
> Is this not already the case? I'm able to click the guide title to get to the guide on master.

It's not  obvious that you can click the title...other clickable entities e.g. on the content landing page are coloured in blue, so it would be good to change the colour of the guide titles to this blue whilst we await design input, if possible.

**Comment by alif-munim** [comment]
I'd like to take this on! If someone could assign me, it would be greatly appreciated 😁

**Comment by alif-munim** [comment]
@MelHopper I've combined a few different bootstrap components to enhance the cards on the guides page. What do you think of the following layout?

![guide-design-02](https://user-images.githubusercontent.com/59207653/83429477-16f0ef80-a402-11ea-82ce-8b488a84a552.PNG)

Here's the mobile view:
![guide-design-02-responsive](https://user-images.githubusercontent.com/59207653/83429493-1b1d0d00-a402-11ea-8bc8-247e8f2eec06.PNG)

**Comment by MelHopper** [comment]
Hi Alif, thanks for picking this issue up. Can you describe the interaction with the boxes? - my instinctive reaction is to think that they are clickable, rather than simply showcasing the list of objectives that are covered in the guide?...but I'd suggest touching base with @kimholmes Design to ensure your design aligns with user interaction best practice and rules.

**Comment by alif-munim** [comment]
Hey Mel, happy to lend a hand. The boxes are more so meant to lay out the objective list in a responsive way than provide interactivity. However, they could potentially link to different sections of the page depending on how the markdown is laid out.

**Comment by alif-munim** [comment]
Updates:
* Added header for objectives section
* Opted for normal list layout for each objective
* Removed "View Guide" button to eliminate redundancy

![image](https://user-images.githubusercontent.com/59207653/83558136-8fc67900-a4e0-11ea-8948-2835b9816a43.png)

Going to make a PR for this by the end of the day 👍

**Comment by micgibso** [comment]
Closing as complete.
