### ISSUE TITLE
[Codewind binary bundling] A way to sync appsody binaries given their two week releases 

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#293]
**Codewind version:** 0.3.0
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description of the enhancement:**

To prevent appsody binaries from being stale, we should work with appsody team to figure out a way to update our binaries through some automated way

**Proposed solution:**

**Comment by tobespc** [comment]
Can we look to add a stage to install of codewind so that it pulls a blessed version of appsody at install rather than ship a version ?  That way we would be able to install the latest tested codewind ready of appsody without having to release a new codewind

**Comment by laven26** [comment]
I can work on this issue

**Comment by sghung** [comment]
Closing as Laven had created a script to help get the specific version. The script is now in use via https://github.com/eclipse/codewind-appsody-extension/blob/master/bin/pull.sh
