### ISSUE TITLE
cwctl dg --clean should be a subcommand

### ISSUE THREAD

**Issue by stalleyj** [eclipse/codewind#2930]
**Description:**
cwctl dg has been implemented to have a --clean flag that does not collect any diagnostic information but deletes any found on the users machine. This should be a subcommand and not a flag.  We will need to change things to be cwctl dg collect (perhaps) and I would suggest cwctl dg remove as we have used remove for projects, connections etc. Will need to update all documentation accordingly.

**Steps to reproduce:**

**Workaround:**

**Comment by micgibso** [comment]
For docs, ensure `cwctl dg` command help in Troubleshooting is up to date: https://www.eclipse.org/codewind/troubleshooting.html#collecting-log-files-and-environment-data for James' PR.

**Comment by james-wallis** [comment]
@micgibso raised here: https://github.com/eclipse/codewind-docs/pull/605

**Comment by james-wallis** [comment]
/close
Closing as PR merged.
