### ISSUE TITLE
Che : URL to codewind-che.vsix should be updated to 'archive' site

### ISSUE THREAD

**Issue by josephca** [eclipse/codewind#2933]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**
https://github.com/eclipse/codewind-che-plugin/blob/f921854d049a32e0500f4b33a0310e0664cbad2f/plugins/codewind/codewind-theia/0.12.0/meta.yaml#L27
The URL is broken and it needs to be updated from 'download' to 'archive' site. 
i.e. https://archive.eclipse.org/codewind/codewind-vscode/0.12.0/latest/codewind-che.vsix

**Steps to reproduce:**

**Workaround:**

**Comment by tetchel** [comment]
I forgot about this when we moved to the archive; hopefully the downloads don't time out and regress https://github.com/eclipse/codewind/issues/2068 but the extension is less than 2MB now so even a poor connection should still be 'fast enough'.

**Comment by josephca** [comment]
Fixed by https://github.com/eclipse/codewind-che-plugin/pull/179

**Comment by jgwest** [comment]
Yah, I'm slightly surprised we're using archive.eclipse.org for proper releases, rather than pre-release build artifacts, but guess as long as it works with acceptable wall-clock download time it's fine.
