### ISSUE TITLE
SVT: [Che] Metrics Dashboard intermittently missing for all other Codewind-style projects

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#2937]
**Codewind version:** 0.12.0
**OS:**  Red Hat Enterprise Linux 7 (64 bit)

**Che version:** 7.9.2
**Kubernetes cluster:** OCP 4.3

**Description:** Metrics Dashboard view is missing for Java Spring projects, and intermittently missing for all other Codewind-style projects.

I encountered the problem with our Travis integration when executing an end-to-end test with a Java Spring project. Also, I reproduced the problem manually and obtained a few additional details.

At first, I created one of each available Codewind-style projects, and I couldn't access the Metrics Dashboard on any of them after they went to "Running". While in a call with Jag, I was able to see the option in all of them, except Spring, after a re-build. But eventually, the option disappeared again for some projects, such as the example shown below with Open Liberty.

![thread_1-screenshot-on-error-13 05 2020_12 08 34-ID_0](https://user-images.githubusercontent.com/49531960/81838481-29b78900-9514-11ea-8970-31c34ddccff1.png)

<img width="621" alt="Screen Shot 2020-05-13 at 12 21 07 PM" src="https://user-images.githubusercontent.com/49531960/81838628-608d9f00-9514-11ea-968a-447d1a0a629f.png">

<img width="629" alt="Screen Shot 2020-05-13 at 12 22 55 PM" src="https://user-images.githubusercontent.com/49531960/81838706-7dc26d80-9514-11ea-8cae-aaa2cd6ebe69.png">

<img width="621" alt="Screen Shot 2020-05-13 at 12 27 21 PM" src="https://user-images.githubusercontent.com/49531960/81839118-1d7ffb80-9515-11ea-9c17-815e1cebf008.png">

<img width="612" alt="Screen Shot 2020-05-13 at 12 36 33 PM" src="https://user-images.githubusercontent.com/49531960/81840067-71d7ab00-9516-11ea-9cd4-f952fc67f555.png">

<img width="621" alt="Screen Shot 2020-05-13 at 12 36 44 PM" src="https://user-images.githubusercontent.com/49531960/81840077-7308d800-9516-11ea-824f-038b4b88e420.png">

**Log:** [codewind-workspacea17hnjxprh4apphi-757cddd74d-4f5ls.txt](https://github.com/eclipse/codewind/files/4623333/codewind-workspacea17hnjxprh4apphi-757cddd74d-4f5ls.txt)

**Note:** Jag also reproduced the same behavior in his cluster.

**Workaround (After fix: https://github.com/eclipse/codewind/issues/2937#issuecomment-628455549):**
Re-building seems to work often, but not with Swift and Liberty, which seems to lose the option after a moment.

@jagraj

**Comment by tetchel** [comment]
this looks like https://github.com/eclipse/codewind/issues/2891 though I only saw it on master

**Comment by malincoln** [comment]
Thanks @tetchel for helping to investigate.  It looks like they may not have seen the issue on 0.12.0 but test is seeing it.   @tobespc pls help investigate.  Thanks

**Comment by tobespc** [comment]
I've ported the fix for spring projects from master to 0.12.0

The intermittent issue is something that has been seen occasionally across previous releases so will investigate that outside of this stop ship issue

**Comment by sujeilyfonseca** [comment]
/remove-priority stopship
/priority hot

Thank you very much for working on this issue, @tobespc!

I verified this issue with the latest Codewind 0.12.0. Most Codewind-style projects didn't present the "Metric Dashboard" option when I created them. After a re-build, they seem to display the feature again. Sometimes the option may disappear after appearing with re-build in Swift and Liberty projects. 

Spring projects now behave the same as others. Thus, I'll proceed to lower the priority of the issue. Also, I'll add a workaround for the users.

**Note:** The intermittent issue seems to be reproduced more often with Eclipse Che. If there is another issue to track it, we can close this one. Otherwise, we can let this issue open, and I can help to verify the solution.

**Comment by jagraj** [comment]
@tobespc 

More information from my local install. Spring project is fine that I do see Metrics feature available after build. This time Node project does not have this "Metrics dashboard" enabled. I navigated to project inf file and it says false. 

```
  "metricsCapabilities": {
    "liveMetricsAvailable": false,
    "metricsEndpoint": false,
    "appmetricsEndpoint": false,
    "microprofilePackageFoundInBuildFile": false,
    "appmetricsPackageFoundInBuildFile": true,
    "hasTimedMetrics": false
  },
```

Same project after rebuild, we see it is enabled and the option is available.

```
 "metricsCapabilities": {
    "liveMetricsAvailable": true,
    "metricsEndpoint": false,
    "appmetricsEndpoint": "/appmetrics-dash",
    "microprofilePackageFoundInBuildFile": false,
    "appmetricsPackageFoundInBuildFile": true,
    "hasTimedMetrics": false
  },
```

**Comment by tobespc** [comment]
so it seems our identification code still needs work. @james-wallis

**Comment by james-wallis** [comment]
/assign
Haven't been able to recreate on local, am currently getting my OpenShift instance set to version 12 to attempt to recreate there.

**Comment by james-wallis** [comment]
Recreated it on OpenShift.
Think this issue is related https://github.com/eclipse/codewind/issues/2900 and there is a fix in master.
I've `cherry-picked` that commit on top of `0.12.0` and am have not seen the issue. I'll raise a PR with this commit.

**Comment by sujeilyfonseca** [comment]
Thank you so much for working to resolve this issue, @james-wallis!

So far, I have not been able to reproduce this problem with the latest Codewind 0.13.0 or master. Therefore, I will proceed to close this issue.
