### ISSUE TITLE
Pod failed to start for Codewind style Spring project on OpenShift

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#2940]
Creating a Codewind style Spring project on an operator installed instance of Codewind on OpenShift gives the following error:

pod for helm release cw-spr1-c06b09a0-953f-11ea-beac failed to start

PFE log with trace enabled: 
[pfelog.txt](https://github.com/eclipse/codewind/files/4623742/pfelog.txt)

**Comment by tetchel** [comment]
I have the same problem; I can't get a Spring project to start.

**Comment by eharris369** [comment]
@tetchel A spring project built fine for me this morning. Can you still reproduce?

**Comment by tetchel** [comment]
yep. Weird

**Comment by eharris369** [comment]
Closing. Can re-open if it happens again.
