### ISSUE TITLE
Documentation needs updating because dropping support for Eclipse 4.11 (2019-03) 

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#2953]
The new tooltip feature for common navigator views was added in Eclipse 4.12 (2019-06). This is being used to improve usability when there are errors or other problems with projects and connections (see #655). The documentation will need to be updated to reflect this including:

- Codewind documentation
- Eclipse Codewind marketplace page
- Readme

**Comment by sishida** [comment]
List of files in which we should update the Eclipse version:
- eclipse-getting-started.md
- codewind-openapi-eclipse.md

**Comment by sishida** [comment]
Followed up with Erin about the status of this issue. We think everything's good to go with the exception of the **[Eclipse Codewind marketplace page](https://marketplace.eclipse.org/content/codewind)**, which I'll update after 0.13.0 is released.

**Comment by eharris369** [comment]
I have removed support for Eclipse 2019-03 from the marketplace page: https://marketplace.eclipse.org/content/codewind

**Comment by eharris369** [comment]
Verified that the marketplace, docs and readme are updated.
