### ISSUE TITLE
cwctl diagnostic --quiet flag is not required

### ISSUE THREAD

**Issue by stalleyj** [eclipse/codewind#2959]
**Description:**
cwctl dg has a --quiet flag but this is not required. We should be observing the --json flag to only output a single json object or output messages. Update any documentation accordingly.

**Comment by mattcolegate** [comment]
PR ready for review https://github.com/eclipse/codewind-installer/pull/480

**Comment by mattcolegate** [comment]
PR merged
/pipeline verify
