### ISSUE TITLE
Create odo 2 extension by cloning/amending https://github.com/eclipse/codewind-odo-extension

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#2965]
**Codewind version:** latest
**OS:** all

**Che version:** n/a
**IDE extension version:** n/a
**IDE version:** n/a
**Kubernetes cluster:** n/a

**Description of the enhancement:**
To get started with supporting odo2, we can take the structure of the current https://github.com/eclipse/codewind-odo-extension and create a new extension based from that.  Will need to modify the cli being used to be odo2 and not odo

**Comment by tobespc** [comment]
@james-wallis @rwalle61 Can you assign yourselves to this please and track progress here.  thanks

**Comment by james-wallis** [comment]
@markcor11 
We added some permissions to the `odo-extension-devfile` cluster roles could the following be added to the operator?
[Cluster roles added to setup script in extension repo](https://github.com/eclipse/codewind-odo-extension/commit/e92d74e8c4419ceedc4b5e2c736caa009dac23ee#diff-5c159d6fcd64a16783d747949ea310fa)

Roles to add:
* `deletecollection ` added to `deployments`
* `update` added to `services`

**Comment by james-wallis** [comment]
PR's merged for this feature
/pipeline verify
