### ISSUE TITLE
Determine process for ensuring topic link updates are actioned for priority external links

### ISSUE THREAD

**Issue by MelHopper** [eclipse/codewind#2966]
**This work item depends on github issue:**

_Create Central Document detailing external links to topics_ https://github.com/eclipse/codewind/issues/2395

**Description**
As topics are reworked and overviews added to the website documentation, links from external sites and IDE UIs need to be modified and optimised.

A process is required to ensure priority external links are updated, the best links are used, and to prevent 404 errors.

The list includes:
Marketplace
Docker
IDE UIs - Eclipse, VS Code, IntelliJ
Blogs
Guides
Videos
Related products such as Kabanero

**Comment by micgibso** [comment]
Process is documented in the https://github.com/eclipse/codewind-docs/wiki, we run linkchecker, and we manually test. We no longer change topic names or topic permalinks.
