### ISSUE TITLE
Problems with Eclipse quick guide

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#2973]
Problems found in the `Getting Started with Codewind in Eclipse` guide:
- At the top it talks about running apps on Kubernetes but then all of the instructions are for a locally installed Codewind.
- `The Codewind backend containers install after you click Install. Clicking Install downloads the Codewind backend containers, ~1GB.`
   Change to:
`To install the Codewind backend containers double click the Local entry in the Codewind Explorer view or right-click on it and select Install. This will download the Codewind backend containers, ~1GB.`
- `Click the Codewind tab.`
     Change to:
   `Open the Codewind Explorer view`
- `Select Appsody Stacks - incubator.`
     Change to (Appsody Stacks - incubator is usually enabled by default):
   `Make sure Appsody Stacks - incubator checkbox is selected`
- `Right-click Local [Running] under Codewind in the Codewind tab.`
     Change to:
  `Right-click Local [Running] under Codewind in the Codewind Explorer view.`
- `Note: Make sure Docker is running. Otherwise, you get an error.`
     Get rid of this. If Docker was not running then Codewind would not be running and there would be no Local [Running] in the view.
- `Go to your project’s workspace under the Project Explorer tab.`
      Change to:
  `Go to your project in the Project Explorer view.`

**Comment by j-c-berger** [comment]
Thank you. I will take up this issue. I'll see if the VS Coe quick guide needs similar changes. If so, I'll make a PR for that quick guide as well.
