### ISSUE TITLE
Split Eclipse Che section into instructions for sysadmin/DevOps and instructions for a developer

### ISSUE THREAD

**Issue by MelHopper** [eclipse/codewind#2974]
Currently, the Eclipse Che instructions for installing Codewind for Eclipse Che and using Eclipse Che are all in a single section.

Ideally, the instructions are split based on whether the user is:

- Installing Codewind for Eclipse Che onto the cluster - DevOps or sysadmin
- Connecting to Codewind for Eclipse Che from their browser - developers

in a similar way to how the Codewind for Remote use has been split. 

**Further detail**

In terms of setting up certificates, this is done by the Devops or Sysadmin role. As such, the developer instructions do not need to include much information on certificates, if any at all, as these decisions should be within the DevOps/Sysadmin instructions. 

In practical terms, the developer simply needs to work with the cluster that has been set up, which in practical terms means:
- if the cluster has been set up with self-signed or no certifictes, then when connecting to the cluster, the developer knows to tick the 'yes trust the server' thanks to instructions from their DevOps/ sysadmin. 
- Else, the developer is not exposed at all to certificates steps. 

The Devops/Sysadmin role user is the user that requires instructions on certificates. However, this only needs to include information on
- cautions for when self-signed or no certs are not good
- signposting to Eclipse Che external pages for further detail on setting up with certificates. 

NOTE: bear in mind that currently, the install instructions steer the user to installing with self-signed certificates. We need to decide whether this is the default we want to show, or to just give the user the options for them to decide.

**Comment by MelHopper** [comment]
Ensure the 'Sysadmin or Devops' Card also points the user to 'Installing Codewind on Eclipse Che' / Deploying Codewind on Eclipse Che' once this content exists.

**Comment by micgibso** [comment]
We're never going to do this.
