### ISSUE TITLE
Unable to start codewind containers on Power (ppc64le)

### ISSUE THREAD

**Issue by snehlatamohite** [eclipse/codewind#2978]
**Codewind version:*0.12.0* , *0.11.0*
**OS:*RHEL*

**Question synopsis:**

We could build v0.11.0 and v0.12.0 versions of codewind on Power successfully with some changes in ppc64le dockerfiles. We will raise PR soon once we complete testing of containers successfully. 
while executing test.sh script, it was not able to launch the containers due to below error which is with due to cwctl-ppc64le binary (https://download.eclipse.org/codewind/codewind-installer/master/latest/cwctl-ppc64le).
However I have built the 0.9.0 version of codewind-installer locally and used it for running tests and starting container, it was able to start codewind ppc64le containers and also test execution started.

Logs and Error - 
Downloading latest Codewind CLI built from master for platforms: ppc64le
Downloading https://download.eclipse.org/codewind/codewind-installer/master/latest/build_info.properties
Latest cli master build is https://archive.eclipse.org/codewind/codewind-installer/master/33
Downloading https://download.eclipse.org/codewind/codewind-installer/master/latest/cwctl-ppc64le
‘cwctl-ppc64le’ -> ‘ppc64le/cwctl’
Successfully pulled Codewind CLI for ppc64le
/root/go/src/github.com/eclipse/codewind
[root@codewind]# ./cwctl-ppc64le --loglevel on start debug eclipse/codewind-pfe-ppc64le
Debug: false
ERRO[0240] Failed to activate service 'org.freedesktop.secrets': timed out

**Steps to reproduce:**
run ./start.sh script

**Workaround:** 
I have built the 0.9.0 version of codewind-installer locally and used it for running tests, it was able to start codewind ppc64le 
containers and also test execution started.
Install Dep - 
 1006  go get -d -u github.com/golang/dep
 1007  cd $(go env GOPATH)/src/github.com/golang/dep
 1008  DEP_LATEST=$(git describe --abbrev=0 --tags)
 1009  git checkout $DEP_LATEST
 1010  go install -ldflags="-X main.version=$DEP_LATEST" ./cmd/dep
 
Build cwtcl v0.9.0 from source and try using it while running tests - 

 go get github.com/eclipse/codewind-installer
 cd codewind-installer
 git checkout v0.9.0
 dep ensure -v
 GOOS=linux GOARCH=ppc64le go build -o cwctl-ppc64le cmd/cli/main.go

[root codewind-installer]# ./cwctl-ppc start debug eclipse/codewind-pfe-ppc64le
Debug: false
==> environment structure written to /root/.codewind/docker-compose.yaml
System architecture is:  ppc64le
Host operating system is:  linux
Attempting to find available port
Port 10000 Available
Please wait while containers initialize...
Creating network "codewind_network" with the default driver
Creating volume "codewind_cw-workspace" with default driver
Creating codewind-performance ... done
Creating codewind-pfe         ... done
Waiting for Codewind to start
..................................
HTTP Response Status: 200 OK
Codewind successfully started on http://127.0.0.1:10000

Please do let me know if you need any additional information. 

Thanks,
Snehlata Mohite.

**Comment by tetchel** [comment]
It's because `cwctl start` fails now if your system doesn't have a keychain installed https://github.com/eclipse/codewind/issues/2520

You could leave a comment there that this is preventing starting on PPC

**Comment by tobespc** [comment]
https://www.eclipse.org/codewind/troubleshooting.html#without-a-keychain-or-keyring-codewind-fails-to-run-certain-commands

this has details of the current workaround but to summarise
```
Enabling insecure keychain mode If you cannot install a keychain, enable insecure
 keychain mode. If you enable this mode, your credentials are stored in a JSON text file 
in the .codewind directory in your user home directory. The credentials are base64 encoded,
and anyone who has access to that file can decode the credentials.

If you use cwctl directly, use the --insecure-keyring command line argument or set 
INSECURE_KEYRING=true in the environment. To get the IDE plug-ins to use the insecure 
keyring, set INSECURE_KEYRING=true in the environment before launching the IDE from that 
same environment.
```

**Comment by snehlatamohite** [comment]
Thanks for pointers. I will try out given fix and will share findings here soon.

**Comment by snehlatamohite** [comment]
Hi All,

It works  with below flag , will also try installing keychain and then will try without flag.   I will add line in above mentioned defect as well. 

[root@p006vm32 codewind]# ./cwctl-ppc64le --insecureKeyring start eclipse/codewind-pfe-ppc64le
Debug: false
==> environment structure written to /root/.codewind/docker-compose.yaml
System architecture is:  ppc64le
Host operating system is:  linux
Attempting to find available port
Port 10000 Available
Please wait while containers initialize...
Creating network "codewind_network" with the default driver
Creating codewind-performance ... done
Creating codewind-pfe         ... done
Waiting for Codewind to start
..
HTTP Response Status: 200 OK
Codewind successfully started on http://127.0.0.1:10000

Thanks,
Snehlata Mohite.

**Comment by hhellyer** [comment]
The containers are now starting, we have a separate issue open for test failures against them when they do but that means this issue can now be closed.
