### ISSUE TITLE
SVT:Open liberty template failed to deploy from codewind che

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#298]
**Codewind version:** 0.3
**OS:** WIndows 10

**Che version:** 7.0
**IDE extension version:** latest 
**IDE version:** 0.3

**Kubernetes cluster:**

Openshift

**Description:**
Open liberty template failed to deploy from codewind che. I do not see helm chart defined for this template.

**Steps to reproduce:**
1. Install Openshift
2. Install Codewind che with the latest images.
3. Create open liberty project.
4. Failed to deploy application.

**Workaround:**

**Comment by johnmcollier** [comment]
Fixed in https://github.com/microclimate-dev2ops/openLibertyTemplate/pull/2
