### ISSUE TITLE
Add link to Guides page, Blog page and Video page from LH nav on website

### ISSUE THREAD

**Issue by MelHopper** [eclipse/codewind#2984]
**ENHANCEMENT**
In the current design, the user only access the Guides, Blog and video Youtube) pages using:

1. links on the website header
2. links within the Content landing page codewind.dev/Learn

From a UX perspective, links from the documentation LH nav would be benficual.

**SOLUTION**
Add a link to the Guides page, blogs page and Youtube page (?) from the LH nav (aka ToC).

**Comment by jcockbain** [comment]
@MelHopper - is something like this the idea? 

![image](https://user-images.githubusercontent.com/31372187/84511760-eab95680-acbe-11ea-9903-a837085ff667.png)

Personally, I'm not sure what the added UX benefit is. It adds noise to the docs sidebar, and all the pages linked to (videos aside) can be accessed through the the top nav bar at all times anyway.

**Comment by MelHopper** [comment]
@kimholmes your call - see above.

**Comment by kimholmes** [comment]
I don't have an opinion either way.

**Comment by micgibso** [comment]
Agee with you on this one James for all the reasons you mention, I'm not keen, suggest we close.

**Comment by micgibso** [comment]
Discussed again, can't see the benefits, closing.
