### ISSUE TITLE
Can't link to disabled project

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#2985]
```
[ /programs/codewind-vscode/dev ] 05 (master) $ cwctl project ls
PROJECT ID                              NAME            LANGUAGE        APP STATUS      LOCATION ON DISK
2f5b5920-9566-11ea-9177-6f3595a04f35    micro-pro-file  java            Unknown         /Users/tim/vscode-codewind-workspace/micro-pro-file
a68a9b80-96da-11ea-9b57-65584f1d7d8b    nodep           javascript      Unknown         /Users/tim/vscode-codewind-workspace/nodep
ef7fc6f0-96bf-11ea-9b57-65584f1d7d8b    p               python          Started         /Users/tim/vscode-codewind-workspace/p
[ /programs/codewind-vscode/dev ] 06 (master) $ cwctl --json project link c -i 2f5b5920-9566-11ea-9177-6f3595a04f35 -t a68a9b80-96da-11ea-9b57-65584f1d7d8b -e abc
{"error":"proj_response","error_description":"target project not found on Codewind server"}
```
`nodep` (the target project) is disabled. it doesn't seem to matter if the source project is disabled.

**Comment by tobespc** [comment]
why do you want to link to a disabled project ?  The project needs to be running so that all the information can be setup for the link to work.

**Comment by james-wallis** [comment]
We can't link to a disabled project as:
* Locally we use the container name (which Turbine generates but is always the same), so we need that container to be running. I didn't want to add code into Portal to generate this just incase changes in the future.
* In K8 we use the service name, but as that is generated by Turbine (iirc) we can get that from them too.

To allow us to add links while the project is disabled we'd need to be able to workout/generate the exact address that the project will be reachable at, potentially we could:
1. Make Portal tell Turbine the container/service name to use
2. Add a function to Turbine that can return us the generated container/service name (less of a change)

**Comment by tetchel** [comment]
OK I think I was mostly confused by the error message; if this is expected behaviour it can be closed.
