### ISSUE TITLE
Projects not disabling in Codewind Appsody VSCode Windows after building

### ISSUE THREAD

**Issue by naveenkaratekid** [eclipse/codewind#299]
**Codewind version: 0.3.0**
**OS: Windows 10**
**IDE: Visual Studio Code**

**IDE extension version: 0.3.0**
**IDE version: 1.37.1**

**Description:**
Project templates won't disable when I try to disable it after building it. The project stays at the "Build Succeeded", "Running", or "Starting" stages. This applies to these Appsody templates:
- Loopback 4
- Node JS
- Microprofile
- Node JS Express Simple
- Node JS Express Skaffold
- Swift
- Springboot Default
- Springboot Kotlin
- Swift

**Steps to reproduce:**
1. Install Codewind in VSCode
2. Create a project using the Appsody Template.
3. Right click on the project, and click "Build"
4. Wait a few seconds, and then right-click on the project, and select "Disable project".

For some reason, if I follow the same steps to reproduce on MacOS using those same templates, they seem to disable much faster than Windows, and it doesn't require me to restart Codewind in MacOS.

**Workaround:** 
Restart Codewind in VSCode. Once it restarts, immediately right-click on the project you're trying to disable, and then click "Disable project". Then after a moment, it says "Disabled"

**Comment by tetchel** [comment]
is this still valid?

**Comment by makandre** [comment]
I think this old issue is no longer valid
