### ISSUE TITLE
cwctl diagnostics remove failed

### ISSUE THREAD

**Issue by stalleyj** [eclipse/codewind#2990]
**Description:**
cwctl diagnostics remove failed on Mac with the following output:-

./cwctl diagnostics remove
Deleting all collected diagnostics files ... 2020/05/21 09:55:43 DELETE_FILE_ERROR[206]: unlinkat /Users/stalleyj/.codewind/diagnostics: directory not empty. 
done

Inspecting the directory afterwards
➜  diagnostics ls -al
total 64
drwxr-xr-x   3 stalleyj  staff     96 21 May 09:55 .
drwxrwxrwx  10 stalleyj  staff    320  7 May 11:33 ..
-rw-r--r--@  1 stalleyj  staff  28676 21 May 09:55 .DS_Store

I did have a large number of directories inside .codewind/diagnostic  

**Steps to reproduce:**
Running again afterwards, succeeded.
I attempted recreation by running the collect command a number of times but I was unable to recreate the problem.

**Workaround:**

**Comment by mattcolegate** [comment]
Actually, this problem should be looked at by someone with a Mac - I remember trying this out at the time and I couldn't get it to happen on my Windows box
/unassign
/pipeline portal backlog

**Comment by jcockbain** [comment]
With 55, on mac, it worked fine for me. Will try a few more times.

![image](https://user-images.githubusercontent.com/31372187/84504070-37973000-acb3-11ea-85c0-d556eabe47f2.png)

**Comment by jcockbain** [comment]
2 more tries, with 90 and then 50 diagnostics dirs, and no problems.

**Comment by jcockbain** [comment]
The "directory not empty" error is coming from the os.RemoveAll call here https://github.com/eclipse/codewind-installer/blob/master/pkg/actions/diagnostics.go#L180. 

There's a few past issues raised against Go for this error on very large dirs: 

- https://github.com/golang/go/issues/23452
- https://github.com/golang/go/issues/20841

Looking through them now to see what the advice is.

**Comment by jcockbain** [comment]
I can't see anything concrete about reasons for this happening, and I've not been able to recreate by fiddling with the `diagnostics` folder.

**Comment by stalleyj** [comment]
The investigation shows that if this does occur, the problem is in the go library. I'm happy to close this and reopen if it ever happens again.
