### ISSUE TITLE
ClosedConnectionException when trying to debug certain Appsody templates in VSCode Windows

### ISSUE THREAD

**Issue by naveenkaratekid** [eclipse/codewind#300]
**Codewind version: 0.3.0**
**OS: Windows 10**
**IDE version:1.37.1**

**Description:**
Error being thrown when I attempt to debug any of the following Appsody templates:

- **Springboot Default**
- **Microprofile**
- **Springboot Kotlin**

Whenever I try to debug any of the templates I listed above, after a few moments, I get a popup that says 

**"Failed to attach to remote debuggee VM. Reason: com.jdi.spi.ClosedConnectionException**

![VSCode debug failed ClosedConnectionException](https://user-images.githubusercontent.com/19738071/63806830-76a5f180-c8ea-11e9-94e9-5ed9f232695f.PNG)

**Steps to reproduce:**
1. Create a project from one of the Appsody templates mentioned above
2. Once it's created, right click the project, and then select "Restart in Debug Mode"

launch.json
@jagraj

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Appsody: Attach java debugger",
            "type": "java",
            "request": "attach",
            "hostName": "localhost",
            "port": 5005
        }
    ]
}
```

**Comment by naveenkaratekid** [comment]
After verifying the issue in Mac and Windows, myself, @DavidG1011, and @sujeilyfonseca got the issue fixed using the workaround that was provided to us. In Windows, there is a different workaround we discovered: start by entering debug mode. Let the process finish, and expect it to fail (already documented that it will fail the first time). Wait for the restart notification on the bottom bar to fade away. Then, manually set the debugger.

**Comment by makandre** [comment]
Can this be closed?

**Comment by naveenkaratekid** [comment]
Yes.
