### ISSUE TITLE
Project Link - Send "From" links in the project/links GET request

### ISSUE THREAD

**Issue by james-wallis** [eclipse/codewind#3004]
Copied from Mattermost:
`@tobycorbin` and `@james-wallis` we were talking about the implementation details of the project linking, and it would save us a lot of work if the links "to" a project were included in the project information, as well as the links "from" a project as we have currently. 
I know we said we can get the frontends working with just the "from" links, but we are wondering if it's possible for it to be done in the backend to save the 3 IDEs from duplicating the work of managing and storing the "to" links.

**Description of the enhancement:**

Add the "From" links into the `/api/v1/projects/:id/links` GET request so that the IDEs can more easily show which projects are linked to what.

From discussions with @tobespc we decided that we don't want to keep this information stored in the project objects and would rather iterate through the `ProjectList` array to work out what projects are linked to a given project at the time of the GET request.

**Proposed solution:** 

The current GET request returns an array of all the projects a project is linked "to".
E.g.: (Where the project `f9577d30-9b79-11ea-af12-c9991ef498dd` has name `PROJECTA`
```
GET https://codewind-pfe/api/v1/projects/f9577d30-9b79-11ea-af12-c9991ef498dd/links
[
  {
    "projectID": "e2587350-9b83-11ea-af12-c9991ef498dd",
    "projectName": "mynodddyapp",
    "envName": "LINK1",
    "projectURL": "cw-mynodddyapp-e2587350-9b83-11ea-af12-service:3000"
  }
]
```

This could potentially be changed to be (not saying this is what it should be):
```
{
linksTo: [
  {
    "projectID": "e2587350-9b83-11ea-af12-c9991ef498dd",
    "projectName": "mynodddyapp",
    "envName": "LINK1",
    "projectURL": "cw-mynodddyapp-e2587350-9b83-11ea-af12-service:3000"
  }
],
linksFrom: [
  {
    "projectID": "completely-different-project-id",
    "projectName": "myjavaapp",
    "envName": "DATABASE",
    "projectURL": "cw-javaapp-23424345:3000"
  }
],
}
```
Where:
`PROJECTA` *links to*  `mynodddyapp`
`myjavaapp` *links to* `PROJECTA`

**Comment by tetchel** [comment]
> we decided that we don't want to keep this information stored in the project objects and would rather iterate through the ProjectList array to work out what projects are linked to a given project at the time of the GET request.

that's fine as long as, when A is linked to B, a `projectChanged` event is sent
1. for the new FROM link in A
2. for the new TO link in B

**Comment by jopit** [comment]
Hi @tobespc could we get this prioritized for 0.14 please?

**Comment by tetchel** [comment]
reading over this now, the IDEs currently get all Portal project info (ie, everything except capabilities and logs) from `api/v1/projects`. if this info is only available at `api/v1/projects/:id/links` it adds some complexity because we have to fetch the links separately from everything else. 

so, it would be best if this info is available when we get all the project info at once at `api/v1/projects`. this also saves making separate API calls for each project. but if there are problems with that we can do the links request separately.

**Comment by james-wallis** [comment]
You can access the current links data from the `api/v1/projects` endpoint in the data returns, in `links.links`.

```
[
  {
    "projectID": "8dc76ae0-aa55-11ea-a2bf-9bf2d1f07f44",
    "name": "newproject",
    "workspace": "/codewind-workspace/",
    "links": {
      "_links": [],
      "fileName": ".codewind-project-links.env",
      "filePath": "/codewind-workspace/newproject/.codewind-project-links.env"
    },
  },
]
```

For this issue, the `linksFrom` can be added into the returned project objects dynamically when the project is retrieved from the `ProjectList` https://github.com/eclipse/codewind/blob/master/src/pfe/portal/modules/ProjectList.js#L83-L93. Perhaps the links object inside the project object should be changed to be more like:
```javascript
[
  {
    "projectID": "8dc76ae0-aa55-11ea-a2bf-9bf2d1f07f44",
    "name": "newproject",
    "workspace": "/codewind-workspace/",
    "links": {
      "to": [], // replaces _links
      "from": [], // dynamically added when the API is called
      "fileName": ".codewind-project-links.env",
      "filePath": "/codewind-workspace/newproject/.codewind-project-links.env"
    },
  },
]
```

**Comment by james-wallis** [comment]
Spoke with @tetchel and @eharris369 and it sounds like this doesn't need to be implemented on the PFE side.
