### ISSUE TITLE
SVT:Che install failing with the latest chectl version on OpenShift 4.3.18 cluster

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#3005]
**Codewind version:** 0.12.0
**OS:** CoreOS/RHEL

**Che version:** 7.9.2
**IDE extension version:** 0.12.0
**IDE version:** 7.9.2
**Kubernetes cluster:**
OCP 4.3.18

**Description:**
With the latest Chectl version ```(chectl/7.13.0 linux-x64 node-v10.20.1)``` and OC version (4.3.19 client, OCP 4.3.18 server) Che install is failing with the following error. But even with this failure, I do see all pods up and running. But install reporting as failure with this error message.

```
  ✖ Retrieving Keycloak admin credentials
    → Cannot read property 'spec' of undefined
 ›   Error: TypeError: Cannot read property 'spec' of undefined
 ›   Installation failed, check logs in '/tmp/chectl-logs/1589819387710'

```

chectl version:
```chectl/7.13.0 linux-x64 node-v10.20.1```

### Eclipse Che Logs

Install Logs:
[che-install.zip](https://github.com/eclipse/che/files/4646124/che-install.zip)

After Che Install from `chectl server:logs` command
[che.zip](https://github.com/eclipse/che/files/4646085/che.zip)

**Steps to reproduce:**
Install Che 7.9.2 version  on OCP 4.3.18 version using OC client 4.3.19.
You will get this error from console.

**Workaround:**

**Comment by jagraj** [comment]
This issue has been fixed in future release of `chectl` and here is the issue in che repository which has more information. https://github.com/eclipse/che/issues/16966

**Comment by jagraj** [comment]
When user get into this error, they can ignore this failure and this should not affect Che and Codewind functionality. This error is fixed in future release of `chectl`.

**Comment by micgibso** [comment]
In discussion with jagraj, no docs reqd for this, removing label.

**Comment by jagraj** [comment]
This issue has been fixed latest chectl releases. Closing this issue now.
