### ISSUE TITLE
SVT: Codewind failed to create the image for default Spring Boot projects

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#3009]
**Codewind version:** Latest 
**OS:** Red Hat Enterprise Linux 7 (64 bit)

**Che version:** 7.9.2
**Kubernetes cluster:** OCP 4.3

**Description:** Codewind failed to create the image for default Spring Boot projects. I encountered this problem first with our Travis integration, but I can reproduce it manually in local and cloud scenarios.

<img width="315" alt="Screen Shot 2020-05-24 at 5 50 35 PM" src="https://user-images.githubusercontent.com/49531960/82765723-18f5f580-9de7-11ea-93ec-131df3ad59fb.png">

<img width="542" alt="Screen Shot 2020-05-24 at 5 50 28 PM" src="https://user-images.githubusercontent.com/49531960/82765725-1abfb900-9de7-11ea-9a0d-b73268338de5.png">

**Logs:**
[che-spring-docker-build-log.txt](https://github.com/eclipse/codewind/files/4674468/che-spring-docker-build-log.txt)
[vscode-spring-docker-build-log.txt](https://github.com/eclipse/codewind/files/4674467/vscode-spring-docker-build-log.txt)

@jagraj

**Comment by johnmcollier** [comment]
@sujeilyfonseca are you able to consistently reproduce? From the logs, it looks like it’s issue with the DHE server used to download the JDK. So need to figure if this was a one off issue, or if the link is dead.

**Comment by tetchel** [comment]
I really think we should try shifting the Spring template to use an openjdk instead of the IBM one for this reason. It makes the builds much slower and occasionally fail due to the DHE download.

**Comment by tobespc** [comment]
yep, makes sense @tetchel , will take care of that

**Comment by hhellyer** [comment]
I managed to replace all the logic to download an SDK from dhe with this:
```
COPY --from=ibmjava:8-sdk /opt/ibm/java /root/java
```
in a local copy of `Dockerfile-build`. That worked pretty quickly as docker itself handles caching that image.

However I'm not sure exactly where turbine picks up `Dockerfile-build` from because when I switched to using a custom template repo with my changes in `Dockerfile-build` didn't actually appear. (Neither the original or my modified version.)

**Comment by hhellyer** [comment]
I have verified that this pattern works when building on openshift via buildah.
I've raised a PR here:
https://github.com/codewind-resources/springJavaTemplate/pull/4

**Comment by hhellyer** [comment]
I've raised a similar PR for the Java MicroProfile template since that was also downloading from DHE:
https://github.com/codewind-resources/javaMicroProfileTemplate/pull/7

**Comment by sujeilyfonseca** [comment]
Thank you for working to solve this issue! 

I verified this issue with the latest Codewind 0.14.0, and I no longer reproduce the problem. Besides, Travis no longer sees the problem.
