### ISSUE TITLE
Codewind landing page: image overlap, covering "Get Started" button and VSCode image

### ISSUE THREAD

**Issue by rachelwchen** [eclipse/codewind#301]
**Description:** on https://www.eclipse.org/codewind/, the building image covers the "Get Started" button and the VSCode image.
![image](https://user-images.githubusercontent.com/12159451/63808515-f9bc4d00-c8d4-11e9-8fcc-fad0f8568f1b.png)

**Steps to reproduce:** I'm viewing the landing page on a bigger monitor (3840x2160 resolution).

**Comment by micgibso** [comment]
Resolved by #2451.
