### ISSUE TITLE
Managing Templates in IntelliJ

### ISSUE THREAD

**Issue by jasperchui** [eclipse/codewind#3023]
**Description:**
Created from: #2879
https://www.eclipse.org/codewind/workingwithtemplates.html#managing-templates
"Use the Template Source Manager to perform the following actions" should be reviewed to determine if doc needs to include Intellij.

**Comment by tetchel** [comment]
We do not have this feature in intellij yet https://github.com/eclipse/codewind/issues/985

**Comment by keithchong** [comment]
@jopit.  The last action on the remote connection object that needs to be hooked in is the manage template action.  So, all the manage template source work should be done first.

**Comment by keithchong** [comment]
I was going to hook it in after Manage Image Registries is done.

<img width="232" alt="Screen Shot 2020-05-28 at 10 16 03 AM" src="https://user-images.githubusercontent.com/7726022/83152941-5f3fa300-a0cc-11ea-9f31-8d76aa40b79a.png">

**Comment by jopit** [comment]
This will be covered under #985
