### ISSUE TITLE
Installing Che using codewind doc gives error from server

### ISSUE THREAD

**Issue by AndyRWatson** [eclipse/codewind#3025]
**Codewind version:**. 0.12
**OS:**.     macOS

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**.   OCP 4.3.18_1522 (on IBM Public Cloud)

**Description:**

When following the codewind.dev install instructions for che on OCP 4.3 I hit the following error that namespace "che" not found 
```
kubectl apply -f https://raw.githubusercontent.com/eclipse/codewind-che-plugin/0.12.0/setup/install_che/codewind-clusterrole.yaml
clusterrole.rbac.authorization.k8s.io/eclipse-codewind unchanged
Error from server (NotFound): error when creating "https://raw.githubusercontent.com/eclipse/codewind-che-plugin/0.12.0/setup/install_che/codewind-clusterrole.yaml": namespaces "che" not found
```

we should add the   creation of the che namespace to the prerequisites instructions

**Steps to reproduce:**

**Workaround:**

**Comment by sishida** [comment]
@AndyRWatson Hi, Andy!

The Codewind for Eclipse Che installation doc (https://www.eclipse.org/codewind/che-installinfo.html) now contains...
1️⃣ A prerequisite step about creating the Che namespace.
2️⃣ An updated command: `$ kubectl apply -f https://raw.githubusercontent.com/eclipse/codewind-che-plugin/0.13.0/setup/install_che/codewind-clusterrole.yaml -n $NAMESPACE`.

Will these suffice to close this issue? Please let us know. Thank you! 😃

**Comment by AndyRWatson** [comment]
as we now call out the Che namespace as a prereq,   we probably dont need it as a step slight lower down for Installing with Kubernetes

**Comment by sishida** [comment]
Hi, @AndyRWatson!
This PR removes the duplicate step and has been merged: https://github.com/eclipse/codewind-docs/pull/665.
I will go ahead and close this issue. :)
