### ISSUE TITLE
Microclimate appears in Maven profile for Codewind

### ISSUE THREAD

**Issue by micgibso** [eclipse/codewind#3026]
**Codewind version:** 0.12.0
**Description:**
The word `Microclimate` occurs four times in https://www.eclipse.org/codewind/importing-existing-projects.html#pre-import-instructions. 

Three occurrences are in the code sample, one in the text. 

Check with dev for a suitable replacement.

**Comment by tobespc** [comment]
looks like Turbine still use the 'microclimate' value in a lot of there scripts so I doubt we can just swap this out for 'codewind' in the example
