### ISSUE TITLE
Che install / configure flow steps not correct

### ISSUE THREAD

**Issue by AndyRWatson** [eclipse/codewind#3027]
**Codewind version:**
**OS:**. 0.12

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**

In the codewind.dev che install instructions flow , there are a couple of minor issues with the sidebar flow ordering compared to the "next steps" in the documentation flow itself.

<img width="1363" alt="Screenshot 2020-05-27 at 09 43 36" src="https://user-images.githubusercontent.com/9268814/82997866-da3a8800-9ffe-11ea-872c-c39d0969dd49.png">

We should ensure that the sidebar steps are in the correct order,  and that the next steps in each of the documentation steps also follow the same flow
 
**Steps to reproduce:**

**Workaround:**

**Comment by AndyRWatson** [comment]
/area/docs

**Comment by MelHopper** [comment]
Eclipse che structure and flow improvements are being delivered in 0.13.0.
Additional enhancements to Eclipse che section are being undertaken via: https://github.com/eclipse/codewind/issues/2718

**Comment by MelHopper** [comment]
@AndyRWatson Given the changes in 0.13.0 are you happy to close this defect?

**Comment by AndyRWatson** [comment]
Yes this looks better in the preview for 0.13.  Thanks
