### ISSUE TITLE
Performance dashboard incorrectly gives benchmark status for websphere liberty

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#3028]
**Codewind version:** latest
**OS:** N/A

**Che version:** N/A
**IDE extension version:** latest
**IDE version:** latest
**Kubernetes cluster:** N/A

**Description:**
Running performance tests against a websphere liberty project initially will correctly show that benchmarks are available.  However, after running a load test and cancelling it, the benchmark is now reported as red

![Screenshot 2020-05-27 at 11 29 16](https://user-images.githubusercontent.com/13151286/83008622-59cf5380-a00d-11ea-9bf6-96c0776b43e5.png)

**Comment by james-wallis** [comment]
Unable to recreate this - potentially fixed in:
https://github.com/eclipse/codewind/pull/3076 (only update metrics status when the project is started)
https://github.com/eclipse/codewind/pull/3059 (always perform a live lookup on the `metrics/status` API)
