### ISSUE TITLE
Improve the message for when a user tries to start Codewind without Docker running

### ISSUE THREAD

**Issue by rachelwchen** [eclipse/codewind#303]
**Codewind version:** 0.2.0
**OS:** MacOS Mojave 10.14.6
**IDE version:** VSCode 1.37.1

**Description of the enhancement:**

When a user tries to run Codewind, in the VSCode Codewind Workspace, an error message reads: "Cannot connect to the Docker daemon at .... Is the docker daemon running?" During the usability study, we found that this message could be improved, since the latter part ("Is the docker daemon running?") doesn't provide the user with concrete instructions on what to do.

![Docker running](https://user-images.githubusercontent.com/12159451/63810819-90d7d380-c8da-11e9-96ac-f3d48809cad8.png)

**Proposed solution:** 

Rewrite the message to include two elements:
1- What's happening: "Cannot connect to the Docker daemon at..." (which is what it currently has)
2- How to resolve it: "Run Docker daemon first, then start Codewind" (actionable instruction)

**Comment by thisguy-1** [comment]
@tetchel & @rachelwchen  did we find a solution to this? Having trouble checking it on my VScode.

**Comment by tetchel** [comment]
resolved in above PR
