### ISSUE TITLE
Error installing latest VSCode plugin

### ISSUE THREAD

**Issue by stalleyj** [eclipse/codewind#3034]
**Codewind version:**
Latest vsix downloaded.
**OS:**
Mac

**Description:**
I attempted to install the plugin into VSCode and got the following error:-
![Screenshot 2020-05-27 at 12 32 49](https://user-images.githubusercontent.com/13417476/83014484-b5eaa580-a016-11ea-8719-61e9d7dffeff.png)

I did not have a previous version of the plugin installed as I've been using Eclipse. 

In .vscode/extensions/   I have ibm.codewind-0.13.0 folder
In .codewind I have a latest folder but it is empty 
**Steps to reproduce:**

**Workaround:**

**Comment by stalleyj** [comment]
Tried again and got this 
![Screenshot 2020-05-27 at 12 45 34](https://user-images.githubusercontent.com/13417476/83015239-08789180-a018-11ea-9eec-95d3467b4e11.png)

**Comment by tetchel** [comment]
ouch, can you post the extension logs?

**Comment by tetchel** [comment]
nvm, found the bug

**Comment by tetchel** [comment]
Please `rm -rf ~/.codewind/latest` before installing the latest plugin in case it did something funky to that directory.

**Comment by stalleyj** [comment]
Latest plugin installed successfully, thanks
