### ISSUE TITLE
Incorrect capabilities status being returned when testing various projects

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#3036]
**Codewind version:** latest
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**
The capabilities panel in the perf dashboard that shows the features available for the project show different values before and after a load run

![Screenshot 2020-05-27 at 14 01 23](https://user-images.githubusercontent.com/13151286/83021939-aa9d7700-a022-11ea-8fe7-df49f2b05b45.png)
![Screenshot 2020-05-27 at 14 01 35](https://user-images.githubusercontent.com/13151286/83021949-af622b00-a022-11ea-80a1-adfe654f3e3e.png)

**Steps to reproduce:**
create a websphere project, open perf dashboard, see the status, run a load, when the load completes the status changes

**Comment by stalleyj** [comment]
I see some really weird results here too, 'Your project is not running" - yes it is and the load is in progresss.
![Screenshot 2020-05-28 at 10 21 49](https://user-images.githubusercontent.com/13417476/83123975-7b900f80-a0cd-11ea-88a0-c25f8c44e9bd.png)

**Comment by tobespc** [comment]
start a load running against a websphere project and the hit cancel when its in the preparing state to recreate

**Comment by tobespc** [comment]
```{
  "liveMetricsAvailable": true,
  "metricsEndpoint": "/metrics",
  "appmetricsEndpoint": false,
  "microprofilePackageFoundInBuildFile": true,
  "appmetricsPackageFoundInBuildFile": true,
  "hasTimedMetrics": false,
  "microprofilePackageAuthenticationDisabled": false,
  "canMetricsBeInjected": true,
  "projectRunning": true
}```

```
{
  "liveMetricsAvailable": true,
  "metricsEndpoint": "/metrics",
  "appmetricsEndpoint": "/javametrics-dash/",
  "microprofilePackageFoundInBuildFile": true,
  "appmetricsPackageFoundInBuildFile": true,
  "hasTimedMetrics": true,
  "microprofilePackageAuthenticationDisabled": false,
  "canMetricsBeInjected": true,
  "projectRunning": true
}
```

**Comment by stalleyj** [comment]
Also seeing incorrect information for a running Node Express app, {
  "liveMetricsAvailable": false,
  "metricsEndpoint": false,
  "appmetricsEndpoint": false,
  "microprofilePackageFoundInBuildFile": false,
  "appmetricsPackageFoundInBuildFile": true,
  "hasTimedMetrics": false,
  "microprofilePackageAuthenticationDisabled": false,
  "canMetricsBeInjected": true,
  "projectRunning": true
}

**Comment by stalleyj** [comment]
Spring project, after I've injected and should have timed metrics
{
  "liveMetricsAvailable": true,
  "metricsEndpoint": false,
  "appmetricsEndpoint": "/javametrics-dash/",
  "microprofilePackageFoundInBuildFile": false,
  "appmetricsPackageFoundInBuildFile": true,
  "hasTimedMetrics": false,
  "microprofilePackageAuthenticationDisabled": false,
  "canMetricsBeInjected": true,
  "projectRunning": true
}
