### ISSUE TITLE
Can't restart remote appsody project in debug mode if capitals in project name

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#3042]
Using the latest Codewind and appsody 0.6.2. If I create an Appsody Node.js Express simple template project named `appsodyNode1` and try to restart it in debug mode the restart fails with the error below. If there are no capital letters in the name then everything is fine.

```
 message: projectRestartResult
 data: {
  "operationId": "7320f19f5f9359a6f14c8467724c3fea",
  "projectID": "237f0e80-a03d-11ea-a4d1-a7e54db40681",
  "status": "failed",
  "errorMsg": "Ingress.extensions \"cw-appsodynode1-237f0e80-a03d-11ea-a4d1-service\" is invalid: spec.rules[0].host: Invalid value: \"akss-appsodyNode1-cw0527.10.103.107.152.nip.io\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')"
```

Full PFE log:
[logs.txt](https://github.com/eclipse/codewind/files/4690710/logs.txt)

**Comment by makandre** [comment]
![image](https://user-images.githubusercontent.com/17596240/83053453-b9822a80-a01e-11ea-9f8b-3fa1a41c4db6.png)

**Comment by makandre** [comment]
I'm surprised the first ingress creation works but fails when recreating the ingress after restart.

Anyways I think maybe we just need to lowercase the project name here https://github.com/eclipse/codewind/blob/master/src/pfe/file-watcher/server/src/utils/kubeutil.ts#L453

@johnmcollier Do you see any problem with that?

**Comment by johnmcollier** [comment]
Works for me.

**Comment by malincoln** [comment]
@makandre is this ready to be verified?  I can move it to either In Progress or Verify.

**Comment by makandre** [comment]
Oh yes, should be.

/verify

**Comment by malincoln** [comment]
@eharris369 this is now ready for for you to verify.  Thanks

**Comment by eharris369** [comment]
This is fixed now.
