### ISSUE TITLE
Performance dashboard: test history disappearance for running different endpoints

### ISSUE THREAD

**Issue by rachelwchen** [eclipse/codewind#305]
**Codewind version:** 0.2.0
**OS:** MacOS Mojave 10.14.6
**IDE version:** VSCode 1.37.1

**Description:** When we looked at the Performance Dashboard with usability study participants, we noticed an issue with test history disappearance. Specifically, in the "Test history" table, details associated with endpoint A disappear as soon as a test with endpoint B is run. 
![image](https://user-images.githubusercontent.com/12159451/63812907-b7990880-c8e0-11e9-9a09-7a793acac30b.png)

**Steps to reproduce:**
1. Open the "Performance Dashboard" for a project
2. Run a test on endpoint A
3. Run a test on endpoint B 
4. See test history disappearance
![Test history](https://user-images.githubusercontent.com/12159451/63813768-5fafd100-c8e3-11e9-8399-67a29aea1670.png)

**Comment by markcor11** [comment]
This problem has been fixed in PR225  :  https://github.com/eclipse/codewind/pull/225 that is currently queued to be merged .

**Comment by rachelwchen** [comment]
Perfect, thanks @markcor11! Sorry didn't see that PR earlier. We'll check out the new design and keep iterating :)

**Comment by tobespc** [comment]
closing as this is resolved
