### ISSUE TITLE
SVT:Image registry manager page is not loaded in right format with Che 7.13.1 version.

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#3064]
**Codewind version:** 0.13.0
**OS:** RHEL

**Che version:** 7.13.1
**IDE extension version:** 0.13.0
**IDE version:** Theia 7.13.1
**Kubernetes cluster:**
ROKS 4.3.19

**Description:**
After creating Codewind 0.13.0 workspace on IBM ROKS 4.3.19 cluster with Che 7.13.1 version, Image registry manager page view presented with wrong format. Please find the screenshots below for both Chrome and Firefox.

**Logs**
[pfe.txt](https://github.com/eclipse/codewind/files/4697538/pfe.txt)
[theia-logs.txt](https://github.com/eclipse/codewind/files/4697539/theia-logs.txt)

**Chrome**
![image](https://user-images.githubusercontent.com/713849/83178554-a9d21700-a0ee-11ea-8700-2b75038243d5.png)

**Firefox**
![image](https://user-images.githubusercontent.com/713849/83179839-8f993880-a0f0-11ea-8992-204d8f722da9.png)

**Steps to reproduce:**
1. Install Codewind 0.13.0 on Che 7.13.1 version.
2.Create Image Registry from Image registry manager. 
3. The Page is loaded with wrong style on Chrome browser. 
4. Different behavior on Firefox where Image registry manager is blank.

**Workaround:**

**Comment by jagraj** [comment]
With the above style, It does allow me to create registry but I am still having problem when creating project. Nothing happens when I try to create new project. 

I can reproduce these problems on both on-premise and ROKS clusters that I provisioned.

**Comment by tetchel** [comment]
Wow! I don't think I changed anything in this area. Can you try and figure out what Che/Theia version introduced the problem?

**Comment by malincoln** [comment]
@johnmcollier is this ready to be moved to verify?

**Comment by johnmcollier** [comment]
Keeping this open and tagged as hot as this will still require fixing when we move to Che 7.13 or higher

**Comment by jagraj** [comment]
I just tried to install Che 7.12.2 on another OCP 4.4 cluster and I see same issue. Earlier I noticed this issue on 7.13.2 but some how I see same problem on 7.12.2 as well. We need to investigate why we see this different behavior intermittently.

**Comment by johnmcollier** [comment]
@jagraj I'm unable to reproduce on Che 7.12.0, can you try again and also collect the logs and image tags of the pods?

**Comment by tetchel** [comment]
The browser console logs would likely contain the error that causes the styles to not load.

**Comment by jagraj** [comment]
@johnmcollier @tetchel 
Here is the info you requested for this issue. Looks like, this cluster is installed with 7.13.2 tags except operator image. I think I did not refresh my codewind-che-plugin repo. This might be useful to debug actual issue for 7.13.2. Let me capture all this info for 7.12.2 install as well.

**Console messages from the browser when I try to access Image registry or Template source options.**

```
root INFO [6d86ee1c-1f4c-4570-97d6-632f3b1f267b][vscode.git]: Started plugin.
theia.eaf08a0fb8b833c76c2c.js:1 root INFO [6d86ee1c-1f4c-4570-97d6-632f3b1f267b][ms-vscode.references-view]: Started plugin.
theia.eaf08a0fb8b833c76c2c.js:1 root INFO [6d86ee1c-1f4c-4570-97d6-632f3b1f267b] Start of 73 plugins took: 4534.9 ms
VM329 main.js:469 Unrecognized Content-Security-Policy directive 'style-src-elem:'.

(anonymous) @ VM329 main.js:469
12Refused to load the stylesheet '<URL>' because it violates the following Content Security Policy directive: "style-src vscode-resource: 'unsafe-inline'". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.

theia.eaf08a0fb8b833c76c2c.js:1 root INFO >>> Storing the layout...
theia.eaf08a0fb8b833c76c2c.js:1 root INFO <<< The layout has been successfully stored.
DevTools failed to load SourceMap: Could not parse content for https://che-che.apps.jagraj4.4.4.purple-mystic-butterfly.com/min-maps/vs/loader.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not load content for https://static.developers.redhat.com/che/theia_artifacts/theia.eaf08a0fb8b833c76c2c.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://static.developers.redhat.com/che/theia_artifacts/vendors.7dedacf50c1da5d07381.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://static.developers.redhat.com/che/theia_artifacts/che.ea6fcf359c6123739a0e.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
VM338 main.js:469 Unrecognized Content-Security-Policy directive 'style-src-elem:'.

(anonymous) @ VM338 main.js:469
setTimeout (async)
(anonymous) @ VM338 main.js:466
theia.eaf08a0fb8b833c76c2c.js:1 root INFO >>> Storing the layout...
theia.eaf08a0fb8b833c76c2c.js:1 root INFO <<< The layout has been successfully stored.
service-worker.js:198 Could not find inner client for request
processResourceRequest @ service-worker.js:198
async function (async)
processResourceRequest @ service-worker.js:196
(anonymous) @ service-worker.js:177
theia.eaf08a0fb8b833c76c2c.js:1 root INFO >>> Storing the layout...
theia.eaf08a0fb8b833c76c2c.js:1 root INFO <<< The layout has been successfully stored.
keycloak.js:456 [KEYCLOAK] Refreshing token: token expired
keycloak.js:484 [KEYCLOAK] Token refreshed
keycloak.js:831 [KEYCLOAK] Estimated time difference between browser and server is 0 seconds
theia.eaf08a0fb8b833c76c2c.js:1 root INFO >>> Storing the layout...
theia.eaf08a0fb8b833c76c2c.js:1 root INFO <<< The layout has been successfully stored.
theia.eaf08a0fb8b833c76c2c.js:1 root INFO >>> Storing the layout...
theia.eaf08a0fb8b833c76c2c.js:1 root INFO <<< The layout has been successfully stored.
main.js:469 Unrecognized Content-Security-Policy directive 'style-src-elem:'.

(anonymous) @ main.js:469
setTimeout (async)
(anonymous) @ main.js:466
theia.eaf08a0fb8b833c76c2c.js:1 root INFO >>> Storing the layout...
theia.eaf08a0fb8b833c76c2c.js:1 root INFO <<< The layout has been successfully stored.
theia.eaf08a0fb8b833c76c2c.js:1 root INFO >>> Storing the layout...
theia.eaf08a0fb8b833c76c2c.js:1 root INFO <<< The layout has been successfully stored.
```

**Logs and pods info.**

[cssErrors.zip](https://github.com/eclipse/codewind/files/4730405/cssErrors.zip)

**Comment by tetchel** [comment]
https://github.com/eclipse/codewind-vscode/pull/634
https://github.com/eclipse/codewind-vscode/pull/635

**Comment by jagraj** [comment]
Thanks for the fix, I no longer see this problem with the Che 7.14.3 version. Closing this issue now.
