### ISSUE TITLE
SVT : Eclipse : Node.js Express error pop-up after install.

### ISSUE THREAD

**Issue by mmulholl** [eclipse/codewind#3066]
**Codewind version:** 0.13.0
**OS:** Mac

**Che version:**
**IDE extension version:**
**IDE version:** Eclipse jee 2020-02
**Kubernetes cluster:**

**Description:**

After installing new codewind images the first creation of a Node.js Express project gets an error:

<img width="741" alt="Screen Shot 2020-05-28 at 2 39 03 PM" src="https://user-images.githubusercontent.com/16086270/83182893-0afce900-a0f5-11ea-83d0-aa0873168fd2.png">

**Steps to reproduce:**

**Workaround:**

**Comment by jopit** [comment]
@eharris369 is this coming from the new base Eclipse support for node?

**Comment by eharris369** [comment]
@jopit Yes. The version of node installed on the machine needs to be updated. I just hit this on my Linux machine which had an old version.

**Comment by jgwest** [comment]
Yes, WTP now does this because it includes [Wild Web Developer](https://projects.eclipse.org/projects/tools.wildwebdeveloper), I've had to work around it in WDT automated tests 😛

**Comment by eharris369** [comment]
@mmulholl This is just a new feature of Eclipse. It would happen if you imported that project into Eclipse without Codewind installed (see Jonathan's comment above).

**Comment by mmulholl** [comment]
@eharris369, I am OK with that, I also notice it comes out shortly after install whether I create a node project or not, once it added code to spot it and hit OK, everything was fine.

**Comment by mmulholl** [comment]
Will close the issue.
