### ISSUE TITLE
Codewind test case failure on ppc64le

### ISSUE THREAD

**Issue by akhileshbhople** [eclipse/codewind#307]
**Codewind version: Master branch**
**OS: RHEL 7.6 (arch : ppc64le)**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Question synopsis:**

I have successfully ported the codewind components (initialize, performance & pfe) to work with IBM POWER (arch : ppc64le). I am running unit test cases, for which I have set up the codewind via available docker-compose.yaml file. However, on running the unit test cases using **npm run test** command, I see around 20 test case failures most of which are due to timeout issue and some are due to incorrect API responses. Any help on test fixes would be appreciated. Attaching failure logs for reference.
[codewind-test-results.txt](https://github.com/eclipse/codewind/files/3550384/codewind-test-results.txt)

**Comment by akhileshbhople** [comment]
Hi @johnmcollier please find the attached logs.
[codewind-test-results.txt](https://github.com/eclipse/codewind/files/3553760/codewind-test-results.txt)

**Comment by johnmcollier** [comment]
@akhileshbhople Thanks for sharing the logs. Would you be able to share the branch with your changes? And what kind of PPC environment did you build and test this on (RHEL, Ubuntu, etc)

@tobespc FYA, this seems to be for Power/PPC porting and seems to be mostly Portal tests failing:
```
  1) Rebuild after file change tests
       "after all" hook in "Rebuild after file change tests":
     Error: Timeout of 240000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/root/codewind/test/src/integration/rebuildOnChange.test.js)


  2) Bind Tests
       "before all" hook in "Bind Tests":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/root/codewind/test/src/projects/creation/bind.test.js)


  3) Project Creation Tests (POST /projects)
       "before all" hook in "Project Creation Tests (POST /projects)":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/root/codewind/test/src/projects/creation/createFromTemplate.test.js)


  4) Project Lifecycle Tests
       "before all" hook in "Project Lifecycle Tests":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/root/codewind/test/src/projects/creation/lifecycle.test.js)


  5) Load Runner Tests
       runLoad Tests
         "after all" hook for "should fail (with status 404) to cancel load that isn't being run":
     Error: Timeout of 240000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/root/codewind/test/src/projects/loadtest.test.js)
```

**Comment by vrushaliinamdar** [comment]
Hi @johnmcollier ,

This is Vrushali. I am Akhilesh's colleague. PFA the container logs for pfe container. 
[logs_17_sept.log](https://github.com/eclipse/codewind/files/3620245/logs_17_sept.log)

The changes which we made for ppc64le are present in the below fork:
https://github.com/vrushaliinamdar/codewind

Please let me know if you need more details.

**Comment by vrushaliinamdar** [comment]
@johnmcollier,

Did you get a chance to look into the information given? Please let me know if you need more details / inputs.

**Comment by johnmcollier** [comment]
@vrushaliinamdar Changes look okay to me, so I'm not sure on the errors. 

@tobespc and his team will need to look at the test failures, as its their tests that are failing.

**Comment by vrushaliinamdar** [comment]
@tobespc could you please help?

**Comment by tobespc** [comment]
this is really old code and almost all those tests have been re written as obsolete.  Can you pull the latest code please

**Comment by vrushaliinamdar** [comment]
@tobespc I have taken the latest code and started working on it. 
It seems for pfe, it is now using version 1.11.2 for buildah. For ppc64le, buildah 1.11.1 rpm is available but needs some additional dependencies to be installed. However, the version 1.9.0 doesnt need these dependencies. Hence, currently I am using version 1.9.0 of Buildah.

I will update you on my findings, soon.

**Comment by vrushaliinamdar** [comment]
@tobespc I was able to build latest code on ppc64le using all latest versions of dependencies except buildah. For Buildah, I am still using 1.9.0.
But when I run the tests using **npm run test** command, I am getting following error:
  11 passing (194ms)
  39 pending
  1 failing

  1) Project Types API tests
       should return expected list of project types:

      AssertionError: expected [] to be a superset of [ Array(6) ]
      + expected - actual

      -[]
      +[
      +  "liberty"
      +  "nodejs"
      +  "spring"
      +  "swift"
      +  "docker"
      +  "appsodyExtension"
      +]

      at Context.<anonymous> (src/API/projectTypes.test.js:33:27)
      at process._tickCallback (internal/process/next_tick.js:68:7)



Tests finished at 2019-10-30_16:35:59
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! codewind-test@1.0.0 test: `scripts/mocha.sh src/API`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the codewind-test@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/[2019-10-30T11_05_59_257Z-debug.log]

[2019-10-30T11_05_59_257Z-debug.log](https://github.com/eclipse/codewind/files/3788556/2019-10-30T11_05_59_257Z-debug.log)

Please let me know if I am missing something.

~Vrushali

**Comment by james-wallis** [comment]
Spoke to @vrushaliinamdar and as the PPC work has been delivered this can be closed.
