### ISSUE TITLE
SVT: Error 404: Unable to delete load test

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#3088]
**Codewind version:** 0.13.0 
**OS:** Mac OS Mojave 10.14.6, Ubuntu, and Red Hat Enterprise Linux 7 (64 bit)

**Che version:** Che 7.12.1
**IDE extension version:** 0.13.0
**IDE version:** Code 1.45.1 
**Kubernetes cluster:** OCP 4.3

**Description:** Error 404: Unable to delete load test

![thread_1-screenshot-on-error-02 06 2020_20 30 25-ID_0](https://user-images.githubusercontent.com/49531960/83567844-43833500-a4f0-11ea-8796-686756ccce68.png)

![thread_1-screenshot-on-error-02 06 2020_20 36 22-ID_2](https://user-images.githubusercontent.com/49531960/83568785-91e50380-a4f1-11ea-89a4-836e65928f4a.png)

<img width="1602" alt="Screen Shot 2020-06-02 at 4 42 50 PM" src="https://user-images.githubusercontent.com/49531960/83567848-454cf880-a4f0-11ea-9889-160ac70cbecc.png">

**Logs:**
[vscode-codewind-performance.txt](https://github.com/eclipse/codewind/files/4719623/vscode-codewind-performance.txt)
[vscode-codewind-pfe.txt](https://github.com/eclipse/codewind/files/4719624/vscode-codewind-pfe.txt)
[che-codewind-performance-workspace6tfe2rk0fy7ydvmk-68bc977d47-llscr.txt](https://github.com/eclipse/codewind/files/4719625/che-codewind-performance-workspace6tfe2rk0fy7ydvmk-68bc977d47-llscr.txt)
[che-codewind-workspace6tfe2rk0fy7ydvmk-66d59b7b8-r7555.txt](https://github.com/eclipse/codewind/files/4719626/che-codewind-workspace6tfe2rk0fy7ydvmk-66d59b7b8-r7555.txt)

@jagraj

**Comment by markcor11** [comment]
reproduced working on a fix

**Comment by sujeilyfonseca** [comment]
I verified this problem with the latest Codewind 0.13.0, and I no longer reproduce the problem.
