### ISSUE TITLE
Adding numbering to topics in LH nav has broken subtree function

### ISSUE THREAD

**Issue by MelHopper** [eclipse/codewind#3092]
Adding numbers with a full stop to a topic in the LH nav that has children prevents the child tree from opening in the LH nav.

This defect was introduced by https://github.com/eclipse/codewind-docs/pull/640

![Screenshot 2020-06-03 at 10 26 24](https://user-images.githubusercontent.com/13365734/83636325-aed71080-a59d-11ea-9a66-559ecd803428.png)

**Comment by MelHopper** [comment]
https://github.com/eclipse/codewind-docs/pull/643 PR removes the offending numbering until a proper fix is merged.

**Comment by MelHopper** [comment]
/ assign @jcockbain

**Comment by jgwest** [comment]
@MelHopper Due to the way the Eclipse webmasters have set up the eclipse GitHub org, @jcockbain needs to comment on the issue before he can be assigned, FYI

**Comment by jcockbain** [comment]
Related to this https://stackoverflow.com/questions/54311361/bootstrap-accordion-not-working-if-id-is-number

**Comment by MelHopper** [comment]
@melhopper TASK: add numbering back into remote once PR 648 has been merged.
