### ISSUE TITLE
Summary calls out Openshift & steps also incorrect for the remotedeploy-projects topics

### ISSUE THREAD

**Issue by MelHopper** [eclipse/codewind#3096]
**Description:**
The summary of what the user has achieved for the Getting Started user flow for Using Codewind Remotely is incorrect. 

**Fix**

Rewrite the Next Steps Section for:

- remotedeploy-projects-vscode.html
- remotedeploy-projects-eclipse.html

i.e. the end of the Using Codewind Remotely workflow to match the overview instructions in remote-codewind-overview.html. i.e:

_You have now:
 
1. Configured your local IDE’s Codewind extension to connect to Codewind in the cloud
2. Registered all necessary security parameters
3. Created a project that builds and runs in the cloud
4. Built and run an existing project in the cloud

**Note:**This update needs to be patched onto both the VS Code and Eclipse pages.

**Comment by micgibso** [comment]
PR approved and merged, closing.
