### ISSUE TITLE
Documenting access to secure template repositories

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind#3102]
- Corresponding epic: https://github.com/eclipse/codewind/issues/2647
- File to edit: https://www.eclipse.org/codewind/workingwithtemplates.html
- Text to update:
    - Enter the URL and any other information.
       - VS Code: Enter the URL to your template source index file and click Enter to confirm.
       - Eclipse and IntelliJ: Fill in the fields for URL, Name, and Description. Click OK when you’re done.

**Comment by j-c-berger** [comment]
@sishida, please assign me, thanks!

**Comment by sishida** [comment]
Doc changes needed:
- For VS Code: https://github.com/eclipse/codewind/issues/2647#issuecomment-648846934
- For Eclipse: https://github.com/eclipse/codewind/issues/2647#issuecomment-648843113

**Comment by sishida** [comment]
PR merged. Closing this issue.
