### ISSUE TITLE
SVT:Hybrid operator still installing latest for CW 0.13.0 release.

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#3103]
**Codewind version:** 0.13.0
**OS:**
CoreOS

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**
OCP 4.4

**Description:**
Looks like Codewind 0.13.0 operator still installing Codewind latest images and operator too.
Could you please deliver changes to 0.13.0 branch so that we can install 0.13.0 version rather latest development version.?

```
Pulling image "eclipse/codewind-operator-amd64:latest"
Pulling image "eclipse/codewind-pfe-amd64:latest"
```

**Steps to reproduce:**

**Workaround:**

**Comment by malincoln** [comment]
@tobespc pls help investigate.  Thanks

**Comment by jagraj** [comment]
This issue has been fixed. Closing now. Thanks for the fix.
