### ISSUE TITLE
[SVT][VSCode] Error when running Capture Diagnostics command

### ISSUE THREAD

**Issue by DavidG1011** [eclipse/codewind#3111]
**Codewind version:** 0.13
**OS:** MacOS

**IDE extension version:** 0.13
**IDE version:** VSCode 1.45.1

**Description:**
Running the `Codewind: Capture Diagnostics` command produces an error saying "Error collecting diagnostics":
<img width="1114" alt="Screen Shot 2020-06-08 at 12 53 15 PM" src="https://user-images.githubusercontent.com/30476587/84058545-647fd600-a987-11ea-9dda-1098d987a00c.png">

**Steps to reproduce:**
1. Run `Codewind: Capture Diagnostics`
2. Click `Continue`
3. Click either `Don't include projects` or `Include projects`.

`Don't include projects` produces:
```
==> Run cwctl --json --insecure diagnostics --all  |  13:01:31.169
Incorrect Usage. flag provided but not defined: -all

NAME:
   cwctl diagnostics - Collect and remove diagnostic reports on Codewind errors

USAGE:
   cwctl diagnostics command [command options] [arguments...]

COMMANDS:
   collect  Gathers logs and project files to aid diagnosis of Codewind errors
   remove   Removes the diagnostics directory and all its contents from the Codewind home directory

OPTIONS:
   --help, -h  show help
   
2020/06/08 13:01:31 APPLICATION_ERROR[300]: flag provided but not defined: -all. 
==> End cwctl --json --insecure diagnostics --all  |  13:01:31.194 (Took 25ms)
```

`Include projects` produces:
```
==> Run cwctl --json --insecure diagnostics --projects --all  |  13:02:51.077
Incorrect Usage. flag provided but not defined: -projects

NAME:
   cwctl diagnostics - Collect and remove diagnostic reports on Codewind errors

USAGE:
   cwctl diagnostics command [command options] [arguments...]

COMMANDS:
   collect  Gathers logs and project files to aid diagnosis of Codewind errors
   remove   Removes the diagnostics directory and all its contents from the Codewind home directory

OPTIONS:
   --help, -h  show help
   
2020/06/08 13:02:51 APPLICATION_ERROR[300]: flag provided but not defined: -projects. 
==> End cwctl --json --insecure diagnostics --projects --all  |  13:02:51.101 (Took 24ms)
```

/area vscode-ide

**Comment by tetchel** [comment]
it looks like the diagnostics command has changed since I added this integration, to require the argument `collect`.

**Comment by eharris369** [comment]
Eclipse IDE PRs:
- master: https://github.com/eclipse/codewind-eclipse/pull/758
- 0.13.0: https://github.com/eclipse/codewind-eclipse/pull/759

**Comment by DavidG1011** [comment]
This is working now on VSCode and Eclipse. Thanks @tetchel and @eharris369!
