### ISSUE TITLE
Website navigation overlap with Codewind logo

### ISSUE THREAD

**Issue by alif-munim** [eclipse/codewind#3112]
**Codewind version:**
**OS:** 

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**
Site navigation overlaps with Codewind logo with smaller window and screen sizes.
![image](https://user-images.githubusercontent.com/59207653/84165795-17ad0580-aa42-11ea-86aa-3df26570adb8.png)

**Steps to reproduce:**
Resize your browser window to around 900px; links will begin to overlap with the Codewind logo.

**Workaround:** 
 Proposed workaround: collapse navbar earlier.

**Comment by jcockbain** [comment]
/pipeline icebox

I'd say for this one wait for https://github.com/eclipse/codewind-docs/pull/612/files to be merged, as how the topbar resizes depends on the search bar being present. 

I had a go on top of the branch, and there is a few different options possible.

**Comment by MelHopper** [comment]
Review: approved. @micgibso ready to close.
