### ISSUE TITLE
Add uninstall topics back into ToC and fix description element

### ISSUE THREAD

**Issue by MelHopper** [eclipse/codewind#3115]
There are 8 md files (as of June 9th 2020) missing from the ToC but that have not been deleted. 

This includes:

- vsc-uninstall.md 
- eclipse-uninstall.md

Solution:
1. Reinstate vsc-uninstall and eclipse-uninstall currently missing from the ToC into the appropriate location in the ToC.
2. Fix formatting of description element (add '"'s around the text)
3. Amend description to a proper description rather than a copy of the title of the piece - bear in mind this description content will show up when the new search function in instigated soon.

**Comment by micgibso** [comment]
Closing as complete.
