### ISSUE TITLE
[SVT][Eclipse] Nodejs remote debugging disconnects intermittently.

### ISSUE THREAD

**Issue by DavidG1011** [eclipse/codewind#3118]
**Codewind version:** 0.13
**OS:** MacOS

**IDE extension version:** codewind-0.13.0-202006091352
**IDE version:** Eclipse Version: 2020-03 (4.15.0) Build id: 20200313-1211
**Kubernetes cluster:** OCP 4.2

**Description:**
When debugging Node.js projects remotely, the connection is lost:
<img width="1330" alt="Screen Shot 2020-06-10 at 10 40 38 AM" src="https://user-images.githubusercontent.com/30476587/84284500-468eae80-ab0a-11ea-8a2c-546ce22f6801.png">

There is also another related issue where the "Debug Inspector URL" popup specifies the link for accessing the chrome devtools:
<img width="590" alt="Screen Shot 2020-06-10 at 10 39 43 AM" src="https://user-images.githubusercontent.com/30476587/84284548-57d7bb00-ab0a-11ea-9eb9-fdd09314d00b.png">

The URL for the inspector recently changed from 
`chrome-devtools://devtools/bundled/inspector.html` ... 
to just
`devtools://devtools/bundled/inspector.html`...

Pasting the link from the "Debug Inspector URL" will currently start a search query.

**Steps to reproduce**:
1. Create remote connection.
2. Create Nodejs project in remote, wait for project to be in running state.
3. Restart project in debug mode.
4. Copy URL from "Debug Inspector URL" popup, change `chrome-devtools://`... to `devtools://`...
5. Occasionally the socket will disconnect.

[diagnostics.20200610104345.zip](https://github.com/eclipse/codewind/files/4759526/diagnostics.20200610104345.zip)

**Comment by eharris369** [comment]
Post describing the same issue with chrome-devtools: https://stackoverflow.com/questions/62066780/chrome-devtools-opens-as-a-search-rather-then-the-dev-tools-themselves

**Comment by eharris369** [comment]
How to solve the disconnect problem:

If the remote debugger disconnects, reconnect by right-clicking on the project and selecting Attach Debugger.
If the remote debugger is disconnecting too frequently, modify the streaming-connection-idle-timeout parameter on the kubelet.
Information on setting kubelet parameters using the config file: https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/
Information on the streaming-connection-idle-timeout parameter: https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/

**Comment by sishida** [comment]
PR for doc update here: https://github.com/eclipse/codewind-docs/pull/656

**Comment by sishida** [comment]
@DavidG1011, @eharris369, With the doc update in place, is this issue good to close?

**Comment by eharris369** [comment]
@sishida Yes. I moved it to verify.
@DavidG1011 Please verify.

**Comment by DavidG1011** [comment]
Good to close. Thanks @sishida, @eharris369!
