### ISSUE TITLE
Node project error pages link to codewind.dev

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#3120]
![image](https://user-images.githubusercontent.com/8888438/84291631-5eb6fb80-ab13-11ea-8e6b-50c03cb07989.png)

I don't know why this would link to our landing page; I'm not sure what "overview page" is supposed to be but if anything it should link to the project's root endpoint.

**Comment by rwalle61** [comment]
Shall we just get rid of the link? It doesn't add anything

![image](https://user-images.githubusercontent.com/18170169/84387168-7ad99c00-abea-11ea-8204-033ba1802e2f.png)

**Comment by tetchel** [comment]
i think that's fine, I have seen sites provide a link to the root/home page from their 404 page though.
