### ISSUE TITLE
Unable to update .cw-settings for non-debugable project

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#3121]
**Codewind version:** 0.13.0. (But 0.12.0 is broken as well)
**OS:** macOS

**IDE extension version:** 0.13.0
**IDE version:** VS Code 1.46.0

**Description:**
I tried importing the following microservice into Codewind: https://github.com/sqshq/piggymetrics/tree/master/statistics-service

Since the project is required to be built manually, outside of the Docker build, I ran a `mvn package` before importing it into Codewind. Once I imported the project into Codewind (**Generic Docker, Java**), I tried to update the `.cw-settings` file so that the `target/` folder could be synced (so that the built jar could be picked up by the docker build in Codewind). 

However, when I saved the file, I was shown the following error:
<img width="458" alt="Screen Shot 2020-06-10 at 4 28 35 PM" src="https://user-images.githubusercontent.com/6880023/84315302-799b6700-ab37-11ea-8d5a-ae777d20a0f9.png">

**Steps to reproduce:**
1. Git clone https://github.com/sqshq/piggymetrics
2. cd into `statistics-service` and run `mvn package`
3. Import the `statistics-service` folder into Codewind as a Generic Docker, Java project **not** Spring)
4. Build will fail
5. Modify `.cw-settings` to remove the `target/` folder from the list of ignored paths. You will get the error I screenshotted above

**Workaround:** 
Importing the project as a Codewind spring project didn't show that error, but then I hit other issues, since this microservice isn't formatted to work with the Codewind spring template.

**Comment by tobespc** [comment]
we've not introduced this issue in 0.13 so would hold off calling it a stop ship.   Also, we don't sync the /target directory as the assumption is that pfe will build the project

**Comment by stalleyj** [comment]
There are quite a few problems here:-
  - The creation of cw-settings happens on the validate call when we attempt to determine the project type. As this project is determined to be a Spring project, the file has values for that type and not what the user selects. 
  - The update to cw-settings is triggering updates to all of the settings rather than just any changed settings.
  - cwctl has it's own list of directories to ignore which it appends any user specifications to. This includes /target so it's impossible for a user to get that aross.

**Comment by tobespc** [comment]
so should we be allowing /target to be uploaded ?   Problem with current design is that /target will get overwritten in pfe when it builds so I don't think any files would persist anyway

**Comment by johnmcollier** [comment]
It's not so much that we should allow it, but rather the user should be able to configure which files and folders are and aren't synced to PFE.

**Comment by tobespc** [comment]
Why do we have a hardcoded list as well as a list in .cw-settings ?

**Comment by stalleyj** [comment]
I've raised the issues above to cover my 2nd/3rd bullet points and this issue can focus on the problem of creating .cw-settings based on the validation steps.

**Comment by james-wallis** [comment]
Some things I noticed:
* In VSCode the file-watcher seems to be ignoring changes to `.cw-settings`, so the only way I can reproduce this is by changing another file. I'd have thought that a change to `.cw-settings` would trigger a sync? Or is it expected to be updated some other way?
* If I add to the `ignoredPaths` list in `.cw-settings` (for example add `src`), change the Dockerfile to force and update and then remove `src` from the `ignoredPaths` list (and force update), and then go to the `/api/v1/projects/watchlist` API I still see the `src` directory in the `ignoredPaths` list. I have seen `cwctl` re-sync the `src` directory so I know its not being ignored.

**Comment by james-wallis** [comment]
Using the example project given above, when `sync`ing the `target` directory into PFE I get the following error twice:
```
[30/06/20 12:18:43 /portal/middleware/errorHandler.js] [ERROR] { PayloadTooLargeError: request entity too large
    at readStream (/portal/node_modules/raw-body/index.js:155:17)
    at getRawBody (/portal/node_modules/raw-body/index.js:108:12)
    at read (/portal/node_modules/body-parser/lib/read.js:77:3)
    at jsonParser (/portal/node_modules/body-parser/lib/types/json.js:135:5)
    at newFn (/portal/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/portal/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/portal/node_modules/express/lib/router/index.js:317:13)
    at /portal/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/portal/node_modules/express/lib/router/index.js:335:12)
    at next (/portal/node_modules/express/lib/router/index.js:275:10)
  message: 'request entity too large',
  expected: 65396809,
  length: 65396809,
  limit: 31457280,
  type: 'entity.too.large' }
```
I believe at least one of these errors corresponds to the `statistics-service.jar` as its not in the `target` directory in PFE. This file is required by the `Dockerfile` to be able to build the image.

So we have another bug: "Unable to sync large files into PFE"

**Comment by james-wallis** [comment]
I've raised [a PR](https://github.com/eclipse/codewind/pull/3191) to stop the error described in this issue - it allows `.cw-settings` to be updated for a non-debugable project. However the details outlined above show that we won't be able to use the demo project you've given that:
1. `cwctl sync` won't sync the `target` directory for some reason
2. The `.jar` produced by `mvn package` is too large to be `synced` to PFE
