### ISSUE TITLE
Metrics tests fail if run in a different timezone

### ISSUE THREAD

**Issue by hhellyer** [eclipse/codewind#3126]
**Codewind version:**
master

**Description:**
If you the metrics tests in a different timezone then they will fail due to issues converting the timestamps to date strings.

**Steps to reproduce:**
Run:
```
TZ=EST npm run apitest
```
(Optionally use `.only()` to just run the tests in `test/src/API/projects/metrics.test.js`)

It looks like the tests expect the converted timestamp to match the directory name containing the results. However we return that in the `container` field on the metrics objects returned contains that and we should probably use that instead. 

**Workaround:** 
Using TZ to set the timezone to the UTC should work.

**Comment by rwalle61** [comment]
pipeline In Progress

**Comment by rwalle61** [comment]
verified https://github.com/eclipse/codewind/issues/3016#issuecomment-643323622
