### ISSUE TITLE
Update to ignoredPaths in .cw-settings triggers updates to all properties 

### ISSUE THREAD

**Issue by stalleyj** [eclipse/codewind#3139]
**Description:**
If the user makes a change to a property in .cw-settings (ie ignoredPaths), it triggers updates to all properties and not just what has changed. 

**Steps to reproduce:**
See steps in https://github.com/eclipse/codewind/issues/3121 to reproduce

**Comment by james-wallis** [comment]
![image](https://user-images.githubusercontent.com/17385115/86129657-f8524700-bada-11ea-8db5-c1239d9923b3.png)

AFAIK this isn't a bug, its just how its been implemented. The original error comes from the `internalDebugPort` going from `undefined` to the value in a default `.cw-settings` file which is an empty string. I'll put a PR up which blocks against this happening.
