### ISSUE TITLE
Incorrect numbering/indentation in website table of contents

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind#3146]
<img width="339" alt="Screen Shot 2020-06-11 at 3 31 59 PM" src="https://user-images.githubusercontent.com/21180723/84777031-11bda400-afaf-11ea-93b3-523e718555a6.png">

- 2a should be indented under 2.
- Because 2a is the only child topic under 2, I also propose that we indent but don't number 2a.

**Comment by micgibso** [comment]
Consider renumbering step 2b to be number 3 instead so the list is more uniform, steps 1 to 7.

**Comment by MelHopper** [comment]
> Consider renumbering step 2b to be number 3 instead so the list is more uniform, steps 1 to 7, in which case this step 1 requires changing:
> 
> Follow the instructions to get started with using Codewind as an application hosted on the cloud, which guides you through:
> 
> ```
> Installing Eclipse Che to use with Codewind or installing Codewind onto an existing Eclipse Che cluster
> Adding an image registry in Eclipse Che (optional)
> Creating a Codewind workspace in Eclipse Che
> Creating your first Codewind project with Codewind for Eclipse Che
> Making a code change to try out the inner loop experience
> ```

The thing is, step 2a is optional and is a sub-step of 2. So I would caution against numbering in that way.

**Comment by sishida** [comment]
@MelHopper A parent title cannot link to its own page and have a child topic at the same time. (I think this has been a limitation of the website from the beginning.)

<img width="347" alt="Screen Shot 2020-06-16 at 1 38 12 PM" src="https://user-images.githubusercontent.com/21180723/84808470-b8696b00-afd6-11ea-8638-468e2ff1ea50.png">
This screenshot shows my local change to the table of contents. We can no longer click "2. Adding an image registry in Codewind on Eclipse Che" and go to the page. When we click it now, it only opens the twistie to reveal "2a. Adding the OpenShift internal registry with Codewind," which we then can click to go to its page.

**Comment by sishida** [comment]
I opened this PR as a compromise to work around the limitation but also omit the potential confusion between "2" and "2a:" https://github.com/eclipse/codewind-docs/pull/664

**Comment by micgibso** [comment]
Checked and merged the PR lgtm.
