### ISSUE TITLE
Confusing error message if project link target has not successfully built

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#3149]
![image](https://user-images.githubusercontent.com/8888438/84790378-49cce300-afbf-11ea-8a0a-f94030131cf3.png)

I guess the problem is that turbine isn't aware of the project because it hasn't had a container start. 

Right now I let the user select any enabled project, but do we have to prevent linking to a project that hasn't built yet, too? Or is there a way to figure this out in PFE

**Comment by tobespc** [comment]
@james-wallis Can you pick this up please and provide an answer ?

**Comment by james-wallis** [comment]
So `cwctl` is swallowing the error returned in the HTTP request. I'll make a change to clear this up - will have it in for 0.14 decut.

https://github.com/eclipse/codewind-installer/blob/9fb96a23c29a0456934a9499be5b066155b39b45/pkg/project/link.go#L129

**Comment by james-wallis** [comment]
Have made a small change for `pfe` to tweak the `NOT_FOUND` error to distinguish when the target project has not been found and a link cannot be found.
Also made the changes to `cwctl` to output the `pfe` error where possible.

cwctl outputs:
```bash
# target project does not exist
cwctl project link create --targetID eb089bb0-aef2-11ea-0000-d30358c43d67 --id 431f1320-ab1e-11ea-b980-239ffa75dbf8 --env DATABASENEW

ERRO[0000] The target project 'eb089bb0-aef2-11ea-0000-d30358c43d67' cannot be found on the Codewind server
exit status 1

--json
{"error":"proj_response","error_description":"The target project 'eb089bb0-aef2-11ea-0000-d30358c43d67' cannot be found on the Codewind server"}


# target project has not started (no url available)
cwctl project link create --targetID 0aa6d8a0-b610-11ea-a7a9-1b78afc1527e --id 431f1320-ab1e-11ea-b980-239ffa75dbf8 --env DATABASENEW

ERRO[0000] The container for project '0aa6d8a0-b610-11ea-a7a9-1b78afc1527e' cannot be found
exit status 1

--json
{"error":"proj_response","error_description":"The container for project '0aa6d8a0-b610-11ea-a7a9-1b78afc1527e' cannot be found"}
exit status 1
```

**Comment by james-wallis** [comment]
PFE pr: [Project Link - specific error for when target project does not exist](https://github.com/eclipse/codewind/pull/3176)

**Comment by james-wallis** [comment]
cwctl pr: https://github.com/eclipse/codewind-installer/pull/501

**Comment by james-wallis** [comment]
PRs merged into master and 0.14 for the PFE work.
/pipeline verify

**Comment by tetchel** [comment]
I'm not sure this is fixed; I got this just now trying to link to a project that was just enabled for the first time:

```
[ERRO: 14:35:09.223 CLIWrapper.ts:218]: Error running cwctl --json --insecure project link create --id a5b7a820-ab33-11ea-8ad2-eb74e1101224 --targetID cebb6320-a4e3-11ea-8082-c797878e9d28 --env f
Logger.ts:129
[ERRO: 14:35:09.224 CLIWrapper.ts:220]: Stdout: {"error":"proj_response","error_description":""}
Logger.ts:126
[ERRO: 14:35:09.226 LinkProjectCmd.ts:92]: Error linking gogo to noode Error running cwctl project link
```

**Comment by james-wallis** [comment]
Thanks for testing this fix.

Just did some testing with master (Codewind + cwctl):

Linking to a disabled project:
```
cwctl --json project link create --id 0ddad510-b6c1-11ea-afa9-f9c81d8cddac --targetID 74f90540-a1b9-11ea-a908-e9eab46209af --env f
{"error":"proj_response","error_description":"The container for project '74f90540-a1b9-11ea-a908-e9eab46209af' cannot be found"}
```
If I enable that project (but don't wait for it to start) I get the same.

Could you retry or provide more details please? Thanks.
