### ISSUE TITLE
Add Turbine functional test README

### ISSUE THREAD

**Issue by ssh24** [eclipse/codewind#315]
**Description of the enhancement:**
Now since we have Turbine functional test for the docker project types working, we should add documentation on how to run the tests. This story can be used to add the readme.

**Proposed solution:** 
The read me can be under: `src/pfe/file-watcher/server/test/functional-test` and should provide list of functions being tested, list of projects being tested and how to run the tests.

**Comment by rajivnathan** [comment]
@maysunfaisal FYI

**Comment by maysunfaisal** [comment]
@rajivnathan thx

/assign me

**Comment by maysunfaisal** [comment]
@rajivnathan can you move this to in progress
