### ISSUE TITLE
Add Turbine unit test README

### ISSUE THREAD

**Issue by ssh24** [eclipse/codewind#316]
**Description of the enhancement:**
Now since we have Turbine unit test working, we should add documentation on how to run the tests. This story can be used to add the readme.

**Proposed solution:** 
The read me can be under: `src/pfe/file-watcher/server/test/unit-test` and should provide list of functions being tested and how to run the tests.

**Comment by maysunfaisal** [comment]
@rajivnathan can you move this to in progress
