### ISSUE TITLE
update cwctl diagnostics collect help to include --all for remote

### ISSUE THREAD

**Issue by AndyRWatson** [eclipse/codewind#3160]
**Codewind version:**. 0.13
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**.   OCP 4.3 (IBM Cloud)

**Description:**

When collecting diagnostic information for a codewind setup configure for remote,  I only seem to see local data collected.  @stalleyj confirmed I also need to include the **_--all_** flag to collect diagnostics from all configured connections.

We should update the cwctl help to include the **_--all_** flag 

```./cwctl diagnostics
NAME:
   cwctl diagnostics - Collect and remove diagnostic reports on Codewind errors

USAGE:
   cwctl diagnostics command [command options] [arguments...]

COMMANDS:
   collect  Gathers logs and project files to aid diagnosis of Codewind errors
   remove   Removes the diagnostics directory and all its contents from the Codewind home directory

OPTIONS:
   --help, -h  show help
```

**Steps to reproduce:**

**Workaround:**

**Comment by stalleyj** [comment]
--all is a flag to the collect subcommand of diagnostics so is not part of the help for the diagnostics command itself. It is however already part of the subcommand help shown below.

➜  latest ./cwctl diagnostics collect --help
NAME:
   cwctl diagnostics collect - Gathers logs and project files to aid diagnosis of Codewind errors

USAGE:
   cwctl diagnostics collect [command options] [arguments...]

OPTIONS:
   --conid remote                                 Triggers diagnostics collection for the remote codewind instance (_must_ have currently configured Kubectl connection!) (default: "local")
   --eclipseWorkspaceDir directory, -e directory  The location of your Eclipse workspace directory if using the Eclipse IDE
   --intellijLogsDir directory, -i directory      The location of your IntelliJ logs directory if using the IntelliJ IDE
   --all, -a                                      Collects diagnostics for all defined connections, remote and local
   --projects, -p                                 Collect project containers information
   --nozip, -n                                    Does not create collection zip and leaves individual collected files in place

**Comment by AndyRWatson** [comment]
Take your point Julie,  but I would have had to know there were two steps to the help command to identify how to use this for remote mode.  Not obvious
