### ISSUE TITLE
SVT: Users are being prompted to select one of the template sources present in the Command Palette, even after manually editing them in the Template Source Manager

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#3165]
**Codewind version:** 0.13.0 & Latest
**OS:** Red Hat Enterprise Linux 7 (64 bit)

**Che version:** 7.9.2 & 7.12.0
**Kubernetes cluster:** OCP 4.3

**Description:** Users are being prompted to select one of the template sources present in the Command Palette, even after manually editing them in the Template Source Manager

<img width="1678" alt="Screen Shot 2020-06-18 at 12 54 13 PM" src="https://user-images.githubusercontent.com/49531960/85050826-b0d7cc80-b164-11ea-9c0a-aede52d7eca7.png">

<img width="1673" alt="Screen Shot 2020-06-18 at 12 54 27 PM" src="https://user-images.githubusercontent.com/49531960/85050831-b3d2bd00-b164-11ea-86d9-897906bce43f.png">

**Steps to reproduce the problem:**
1. Install Che 
2. Deploy a new Codewind workspace
3. Right-click on "Projects"
4. Select "Template Source Manager"
5. Modify the template sources
6. You will still get the prompt to select one of the template sources present in the Command Palette when attempting to create a project

@jagraj

**Comment by tetchel** [comment]
this is the same behaviour as always but i agree it doesn't make sense if you do it in this order

**Comment by sujeilyfonseca** [comment]
Thank you for working to solve this issue, @tetchel! 

I verified this issue and I no longer reproduce the problem.
