### ISSUE TITLE
Docs: Add new Codewind Operator workspace ID and behaviour changes

### ISSUE THREAD

**Issue by micgibso** [eclipse/codewind#3168]
**Codewind version:** 0.14.0 
**OS:**

**Description of the enhancement:**
Update landing page documentation to refect the latest enhancements and changes in behaviour to the Codewind Operator.

**Proposed solution:** 
Demo'd in Codewind Playback call, 16/06/2020, starts 00:07:35 in.

- Add new workspace detail (workspace ID) AND amend remote deployment text to use the namespace in the access URL. 
- Document what to do for 0.14.0 to regenerate the connections to the deployments.
	- Drop the namespace 
	- Create all deployments again, then wire them up to the IDEs
- Document what to do to delete the Codewind namespace:
	- Finaliser gets set on the resource.
	- Finaliser blocks the resource, so must be allowed to complete. 
	- Change in behaviour required: before you delete the codewind namespace, you have to delete the deployments first.
- Add a Troubleshooting issue, if you forget to delete the deployments first, how do you get around this?

- The codewind-operator readme has been updated so look there first.

**Comment by markcor11** [comment]
In the case where you need to clear the finaliser manually you can run : 

```
kubectl patch codewind {codewindName}  -p '{"metadata":{"finalizers": []}}' --type=merge
```

on each pending codewind deployment where  {codewindName}  would be something like "jane1"

**Comment by micgibso** [comment]
PR approved and merged.
