### ISSUE TITLE
SVT: [Docs] Inform our users that we don't support versions older than Che 7.12.0 and fix utterance that still mentions Codewind 0.12.0

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#3169]
**Codewind version:** 0.13.0 & Latest
**OS:** Red Hat Enterprise Linux 7 (64 bit)

**Che version:** 7.9.2 
**Kubernetes cluster:** OCP 4.3

**Description:** Inform our users that we don't support versions older than Che 7.12.0 and fix utterance that still mentions Codewind 0.12.0:

https://www.eclipse.org/codewind/che-installinfo.html#installing-codewind-onto-an-existing-eclipse-che-cluster

Our docs still mention Codewind 0.12.0 in one line:

`Download the [codewind-checluster.yaml]https://raw.githubusercontent.com/eclipse/codewind-che-plugin/0.12.0/setup/install_che/che-operator/codewind-checluster.yaml) file.`

And provide the command with Che 7.12.0, but doesn’t say that previous versions are not supported:

`$ chectl server:start --platform=openshift --installer=operator --che-operator-cr-yaml=codewind-checluster.yaml --che-operator-image=quay.io/eclipse/che-operator:7.12.2`

If we use an old Che version, we cannot create Codewind projects:
https://github.com/eclipse/codewind/issues/3166

@jagraj

**Comment by sishida** [comment]
- PR for change on the master branch: https://github.com/eclipse/codewind-docs/pull/673
- PR for change on the 0.13.0 release branch: https://github.com/eclipse/codewind-docs/pull/674

**Comment by sishida** [comment]
Fix appears live: https://www.eclipse.org/codewind/che-installinfo.html
Closing this issue.
