### ISSUE TITLE
Integrate appsody test automation as part of builds

### ISSUE THREAD

**Issue by sghung** [eclipse/codewind#317]
**Codewind version:** 0.3.0
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description of the enhancement:**
Test automation is in progress, but once it is complete, we should see how it would be integrated into PR builds.

**Proposed solution:**

**Comment by malincoln** [comment]
@sghung pls set the release to 0.5.0.  Thanks

**Comment by josephca** [comment]
@sghung I believe we can close this. Please reopen otherwise.
