### ISSUE TITLE
[Eclipse IDE] Update the learn more link in Manage Project Links dialog

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#3170]
The manage project links dialog has a learn more link that should point to the documentation for project linking. It needs to be updated once the url for that document is available.

**Comment by tetchel** [comment]
doc issue https://github.com/eclipse/codewind/issues/3070

**Comment by micgibso** [comment]
New topic -  linking-your-projects.md  (linking-your-projects.html) - created on the above PR.

**Comment by sishida** [comment]
@micgibso Are you adding the content in this comment https://github.com/eclipse/codewind/issues/2852#issuecomment-648855628 to the docs as part of this issue 3170?

**Comment by tetchel** [comment]
In VS Code the links are managed through the Project Overview page > Links tab. They can also be created through the Link Project command which is available in the project right-click menu or the command palette.

**Comment by micgibso** [comment]
@sishida Thanks for the link to the comment, yes, will deal.

**Comment by eharris369** [comment]
Eclipse IDE PRs:
- master: eclipse/codewind-eclipse#773
- 0.14.0: eclipse/codewind-eclipse#776
