### ISSUE TITLE
Add link to the Getting Started Overview topic from the content landing page

### ISSUE THREAD

**Issue by MelHopper** [eclipse/codewind#3171]
At the moment, the codewind.dev/learn landing page references local, remote and browser-based configurations, but does not link to information detailing these 3 different configs.

**Solution:**
Add a line to the download cards on the Learn page, linking to the gettingstarted-overview.html topic. FYI the gettingstarted-overview topic topic:

- introduces user to the 3 different configs
- details how to decide which configuration suits your SWDL
- signposts to instructions for getting started for each config

**Use this copy:**

LOCAL AND REMOTE CARD
Download to develop, build and run on your desktop, or to develop on your desktop but build and run on the cloud. Follow step-by-step instructions for VS Code, Eclipse, or IntelliJ. [Read more](gettingstarted.overview.html) about local, remote, and browser-based configurations.

BROWSER-BASED
Download to develop, build and run entirely on the cloud. Follow [step-by-step instructions] for Eclipse Che. [Read more](gettingstarted.overview.html) about local, remote, and browser-based configurations.

**Comment by alif-munim** [comment]
@jcockbain please assign me

**Comment by micgibso** [comment]
Amended the above copy to include the Oxford comma after 'remote':  "Read more about local, remote, and browser-based configurations."

**Comment by micgibso** [comment]
@MelHopper Please check and close if done.

**Comment by MelHopper** [comment]
Reviewing: 
Browser-based Card copy is not quite right - the PR does not match the copy in the above description for this issue. 
@micgibso good spot on oxford comma!
@alif-munim can I also make a change to the copy - now that I see it on the page, I think the link location for the gettingstarted-overview.html topic needs to change.

So, updated copy:

LOCAL AND REMOTE CARD
Download to develop, build and run on your desktop, or to develop on your desktop but build and run on the cloud. Follow step-by-step instructions for [VS Code], [Eclipse], or [IntelliJ]. Read more about [local, remote, and browser-based configurations.](./gettingstarted-overview.html)

BROWSER-BASED
Download to develop, build and run entirely on the cloud. Follow [step-by-step instructions] for Eclipse Che. Read more about [local, remote, and browser-based configurations](./gettingstarted-overview.html).

**Comment by alif-munim** [comment]
@MelHopper that's right, the original copy was correct. I must have missed it when making the edit; thanks for the catch @micgibso!

I've created a new PR to relocate the link to `gettingstarted-overview.html` please review and let me know if there any more changes to be made :)

**Comment by micgibso** [comment]
PR reviewed, approved, and merged.
