### ISSUE TITLE
When viewing on mobile or reducing width of window, LH nav does not retract 

### ISSUE THREAD

**Issue by MelHopper** [eclipse/codewind#3172]
**Problem**

When viewing codewind.dev/learn on a mobile or as a smaller window, the LH nav of topics does not retract.

As such, when visiting the codewind/learn webpage, it looks like it doesn't exist as you just see a menu of topics. To access the content landing page, you have to scroll down the LH nav i.e. all the high level topics first.

**Solution:**

1. Retract the LH nav for codewind/learn

2. Consider also retracting the LH nav when viewing any  documentation topics (Design input needed).

**Comment by jcockbain** [comment]
@MelHopper I have deployed my branch with a retractable sidebar to https://jcockbain.github.io/codewind-docs/learn.html.

If you have any UX feedback that'd be great. 

I'd imagine we want the Table of Contents hidden by default at lower breakpoints (where it's on top), and shown by default for larger screens. I can make that change, but wanted to get this up for feedback as soon I could.

**Comment by MelHopper** [comment]
@kimholmes please could you advise on the best solution to this defect? 

@jcockbain Retractable side bar works well. Is your proposal to automatically retract the sidebar when resizing the window / for mobile viewing, with the 'contents' arrow still showing to indicate the ToC is there and able to be reinstated with a click of that 'content's arrow?

**Comment by jcockbain** [comment]
@MelHopper yes exactly - as it is now but defaulting to sidebar hidden for mobile,  and sidebar shown for wider screens.

**Comment by kimholmes** [comment]
Typically, the hamburger menu is used to reveal the nav for mobile. It's being used here to show the menu items that are in the header though (Learn, News, Blogs, Guides) and that seems a little odd.

Yes, I agree the nav should be hidden by default for mobile (and accessible via the hamburger icon as I mention above). I've never seen the use of the tab (the one that reads "content"). We don't need that tab on the web page (viewable on desktop), the nav should just collapse when the user contracts the page. 

Other common usecases for the mobile nav is to use the hamburger icon to overlay the page or push it over. What we have, where the nav just appears at the top is acceptable too.
![image](https://user-images.githubusercontent.com/21316329/85777997-20fbca80-b6f0-11ea-9228-40ca01d0088e.png)

**Comment by jcockbain** [comment]
Thanks @kimholmes, that's very helpful. Having had a look around it seems the most popular method is as you say naturally hiding by default and using a hamburger/other icon to toggle the dropdown... 

Examples

https://kubernetes.io/docs/home/

https://getbootstrap.com/docs/4.5/getting-started/introduction/

https://docs.aws.amazon.com/ec2/?id=docs_gateway

https://cloud.google.com/docs uses this with the up/down chevron. Will get on a v2 today, removing the toggle from desktop and adjusting to fit closer to these examples.

**Comment by jcockbain** [comment]
I've updated the deployment (https://jcockbain.github.io/codewind-docs/learn.html) and PR with a new version, @kimholmes let me know what you think when you get a chance.

**Comment by kimholmes** [comment]
Thanks @jcockbain Looks good!

**Comment by micgibso** [comment]
Remaining PR merged, closing as complete.
