### ISSUE TITLE
SVT:Failed to  create new project from Che 7.14.3 version 

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#3190]
**Codewind version:** 0.14.0
**OS:** OCP 4.3

**Che version:** 7.14.3
**IDE extension version:**  0.14.0
**IDE version:**  7.14.3
**Kubernetes cluster:**
OCP 4.3.18

**Description:**
I am not able to cerate new project from Che 7.14.3 version after CSS issues resolved by issue (https://github.com/eclipse/codewind/issues/3064). I am not getting input field to take project name.
Here are the logs from the pods.

[pfe.txt](https://github.com/eclipse/codewind/files/4847334/pfe.txt)
[theia.txt](https://github.com/eclipse/codewind/files/4847335/theia.txt)

**Steps to reproduce:**
1. Create codewind 0.14.0 workspace with Che 7.14.3 version.
2. Create new project from any of the template and I do not get input field to provide project name. 

**Workaround:**

**Comment by johnmcollier** [comment]
@tetchel Any thoughts on this?

**Comment by naveenkaratekid** [comment]
@jagraj I too can reproduce this issue as well. When I click on a project template, for example, the standard Go template, I don't get any sort of input field to enter the name of the project.

Here is the log from the codewind-workspace pod:
[codewind014log.txt](https://github.com/eclipse/codewind/files/4848064/codewind014log.txt)

**Comment by tetchel** [comment]
Is this only a problem on che 7.14? I can't reproduce this on any Theia version so it may be che specific

**Comment by jagraj** [comment]
I just moved to 7.15.0 release,  I still see same problem where I can not create project due to input field for project name is not getting displayed.

**Comment by tetchel** [comment]
I have a fix for this. Similarly to the inputbox flickering text issue I see this issue in che but not in local theia, which is bizarre.

**Comment by jagraj** [comment]
I got the fix and verified with Che 7.15.0. 
@johnmcollier 
Shall we move to 7.15.0 release or we can stay with 7.14.3 for 0.14.0 release and move to 7.15.x for 0.14.1 release.?

**Comment by elsony** [comment]
Is this problem fixed by Che 7.15.0 at all? Based on https://github.com/eclipse/codewind/issues/3190#issuecomment-651920038, it looks like the fix is on Codewind VSCode extension. Do we need to update to Che 7.15.0 to get this fixed?  Also, it sounds like the nature of the problem is failing to create a project, if we can consistently reproduce it, I don't think we should ship 0.14.0 without fixing it; otherwise, users can't even create a project.

**Comment by tetchel** [comment]
i did my testing on che 7.15 but I expect it should be fine on 7.14.3 too.

**Comment by jagraj** [comment]
I did my testing with 7.15.0 as well and no issues found so far. 

@johnmcollier 
Should we move to latest 7.15.x version for 0.14.0 release or stay with 7.14.3 version.?
We can move to 7.15.x version for 0.14.1 fixpack release. Let us know what do you think.

The actual issue is fixed with this issue and I am closing this now. Thanks Tim for the fixing this issue.
