### ISSUE TITLE
[SVT][Docs]: Broken link for installing chectl

### ISSUE THREAD

**Issue by DavidG1011** [eclipse/codewind#3196]
In our docs, under: 
https://www.eclipse.org/codewind/che-installinfo.html#installing-eclipse-che-to-use-with-codewind 
we have a link to install chectl:

`1. Install the chectl CLI tool. See Installing the chectl management tool.` which links to: https://www.eclipse.org/che/docs/che-7/installing-the-chectl-management-tool/ (404)

This page appears to have relocated to: https://www.eclipse.org/che/docs/che-7/using-the-chectl-management-tool/

/area docs

**Comment by micgibso** [comment]
Link verified as fixed.
