### ISSUE TITLE
SVT:Che:Failed to create ODO Java project 

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#3197]
**Codewind version:** 0.14.0
**OS:** RHEL, CoreOS

**Che version:** 7.15.0
**IDE extension version:** 0.14.0
**IDE version:** 7.15.0
**Kubernetes cluster:**
OCP 4.3

**Description:**
ODO Java project failed to create on Codewind hosted IDE. Here is the error that I am getting.

```
Error creating new project: Error running cwctl project create: File download failed for https://codeload.github.com/spring-projects/spring-petclinic/legacy.zip/master, status code 404

```

Logs:
[pfe.txt](https://github.com/eclipse/codewind/files/4859946/pfe.txt)
[theia.txt](https://github.com/eclipse/codewind/files/4859947/theia.txt)

![image](https://user-images.githubusercontent.com/713849/86281415-7aaa3c00-bbab-11ea-9cda-8f3ba82c09bc.png)

**Steps to reproduce:**

1. Create Codewind 0.14.0 workspace on Che 7.14.3 version.
2. Create ODO Java project and we get above failure.

**Workaround:**

**Comment by tobespc** [comment]
We can take a look at this one @jagraj

**Comment by hhellyer** [comment]
@tobes - There's no `master` branch here anymore: https://github.com/spring-projects/spring-petclinic/ - it's called `main` now.

**Comment by hhellyer** [comment]
I think the petclinic project is referenced here: https://github.com/eclipse/codewind-odo-extension/blob/master/templates/master-index.json but that points directly to the project.

It's the download code in `cwctl` that assumes there will always be a master branch here:
https://github.com/eclipse/codewind-installer/blob/e7926eb2a03f648bb249c64d3fa2159a2295bd21/pkg/utils/download.go#L155

Changing this is tricky especially if all repositories don't standardise on the same branch names. (Assuming there would always be a `master` branch was always unsafe.) I'm not sure if the template format includes a way to specify branches.

**Comment by jagraj** [comment]
This issue has been verified with the latest release images. Thanks for the fix. Closing this issue now.
