### ISSUE TITLE
IDE support for configuring template repositories

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind#32]
- The first time you bind or create a project we will need to prompt the user to pick between "Codewind standard" (will find a better name) and Appsody project types, and potentially others in the future. This choice can be simple, but needs a description so that the user can understand the difference. This setting will filter the list of templates and bind options that they get back.
- The setting will be persisted at IDE or workspace level (tbd) across bind & create, and the user has a way to clear or switch it.

**Comment by tetchel** [comment]
This is mostly there in VS Code. We have some tweaks to do which depend on: 
https://github.com/eclipse/codewind/issues/179
https://github.com/eclipse/codewind/issues/186
https://github.com/eclipse/codewind/issues/123

**Comment by sishida** [comment]
Drafting content for new file:

Use Codewind to help manage templates.
- Right-click "Projects (Local)" and select "Manage Template Sources". The "Template Source Manager" page opens.
- Click "Add New" to add a new repository source.
- Enable or Disable a repository type to view the repositories of that type in the wizard.
- See the Description field to understand the key differentiators among the different repositories:
  - Standard Codewind templates: 
  - Appsody Stacks - appsodyhub:

**Comment by jopit** [comment]
@jagraj can this be closed please?

**Comment by jagraj** [comment]
SVT complete for this story during 0.4 release. This can be closed if there are no open items from other squads.
