### ISSUE TITLE
Virtual assistant to improve the experience of Codewind users 

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#3212]
**Codewind version:** Latest & 0.14.1
**OS:** N/A

**Description of the enhancement:**
Include a virtual assistant to improve the experience of Codewind users by providing immediate attention to their questions. The chatbot could be available in our Codewind Dev Page.

**Proposed solution:** 
You can see the details of the proposed solution here: https://github.com/eclipse/codewind-docs/pull/698

/assign

**Comment by naveenkaratekid** [comment]
So far the chatbot looks like its working properly. 

As I was testing it, I did notice one small thing:
For example, if I search for “che” in the chatbot, it says that it couldn’t find anything related to che. But if I enter “eclipse che” then its able to understand that I am referring to Eclipse Che.

![image](https://user-images.githubusercontent.com/19738071/89209642-b2cae300-d58c-11ea-84b0-f1f05a174a7d.png)

**Comment by sujeilyfonseca** [comment]
Thank you for testing the chatbot from the user perspective, @naveenkaratekid! 

The variations in the IDE name for Eclipse Che were present in the virtual assistant. However, I noticed what caused the answer you found and fixed it.

**Comment by DavidG1011** [comment]
Bree-Z seems effective for its purposes:

Answer common questions related to Codewind / Provide an overview and redirect people to the right place in our documentation:
<img width="336" alt="Screen Shot 2020-08-03 at 2 51 08 PM" src="https://user-images.githubusercontent.com/30476587/89217230-d21c3d00-d599-11ea-8d35-f6e9d065e1ea.png">
<img width="334" alt="Screen Shot 2020-08-03 at 2 54 04 PM" src="https://user-images.githubusercontent.com/30476587/89217260-dcd6d200-d599-11ea-82cd-476e4e9b4a35.png">

Guide you to answer some questions and generate a template for a bug or question type issue, and link you to where the issue can be added:
<img width="345" alt="Screen Shot 2020-08-03 at 2 34 22 PM" src="https://user-images.githubusercontent.com/30476587/89217416-29baa880-d59a-11ea-8ba3-c2a80d4bc9eb.png">

When the dialog tree is not capable of answer the user question or the confidence is lower than 50%, it will try to use search skill to gather info among GitHub, Codewind Dev Page, and Medium:
<img width="340" alt="Screen Shot 2020-08-03 at 2 40 13 PM" src="https://user-images.githubusercontent.com/30476587/89217461-3b03b500-d59a-11ea-84f0-e8dac1c0c071.png">

Tell jokes, understand some common phrases, etc:
<img width="339" alt="Screen Shot 2020-08-03 at 2 38 55 PM" src="https://user-images.githubusercontent.com/30476587/89217520-566ec000-d59a-11ea-83e7-304d878b3fbc.png">

**Comment by sujeilyfonseca** [comment]
Thank you very much, @DavidG1011! I appreciate you sharing your experience using the chatbot.
