### ISSUE TITLE
Unable to start Codewind containers on Windows 10

### ISSUE THREAD

**Issue by raju-valivarthi** [eclipse/codewind#3214]
here is the error I'm getting while launching new local project in codewind.

Full Codewind log is at "c:\Users\raju4\AppData\Roaming\Code\logs\20200725T093417\exthost1\IBM.codewind\codewind.log"

C:\Users\raju4\.codewind\0.14.0 exists
cwctl is available at C:\Users\raju4\.codewind\0.14.0\cwctl.exe
appsody 0.6.4 is available at C:\Users\raju4\.codewind\0.14.0\appsody.exe
==> Run cwctl.exe --json --insecure connections list  |  09:55:04.203
{"schemaversion":1,"connections":[{"id":"local","label":"Codewind local connection","url":"","auth":"","realm":"","clientid":"","username":""}]}
==> End cwctl.exe --json --insecure connections list  |  09:55:04.491 (Took 288ms)
==> Run cwctl.exe --json --insecure status  |  09:55:04.494
{"status":"stopped","installed-versions":["latest","0.14.0"]}
==> End cwctl.exe --json --insecure status  |  09:55:04.812 (Took 318ms)
==> Run cwctl.exe --json --insecure status  |  09:55:56.647
{"status":"stopped","installed-versions":["latest","0.14.0"]}
==> End cwctl.exe --json --insecure status  |  09:55:56.772 (Took 125ms)
==> Run cwctl.exe --json --insecure status  |  09:55:56.778
{"status":"stopped","installed-versions":["latest","0.14.0"]}
==> End cwctl.exe --json --insecure status  |  09:55:56.884 (Took 106ms)
==> Run cwctl.exe --json start -t 0.14.0  |  09:55:56.893
Debug: false
==> environment structure written to C:/Users/raju4/.codewind/docker-compose.yaml
System architecture is:  amd64
Host operating system is:  windows
Attempting to find available port
Port 10000 Available
Please wait while containers initialize...  
Recreating codewind-performance ... 

[1A[2K
Recreating codewind-performance ... [32mdone[0m
[1BCreating codewind-pfe           ... 

[1A[2K
Creating codewind-pfe           ... [31merror[0m
[1B
ERROR: for codewind-pfe  Cannot create container for service codewind-pfe: invalid mount config for type "bind": invalid mount path: 'C:/dev/null' mount path must be absolute

ERROR: for codewind-pfe  Cannot create container for service codewind-pfe: invalid mount config for type "bind": invalid mount path: 'C:/dev/null' mount path must be absolute
Encountered errors while bringing up the project.
{"error":"DOCKER_COMPOSE_START_ERROR","error_description":"exit status 1"}
==> End cwctl.exe --json start -t 0.14.0  |  09:56:00.995 (Took 4102ms)
==> Run cwctl.exe --json --insecure status  |  10:33:17.771
{"status":"stopped","installed-versions":["0.14.0","latest"]}
==> End cwctl.exe --json --insecure status  |  10:33:18.258 (Took 487ms)
==> Run cwctl.exe --json --insecure status  |  10:33:18.261
{"status":"stopped","installed-versions":["latest","0.14.0"]}
==> End cwctl.exe --json --insecure status  |  10:33:18.375 (Took 114ms)
==> Run cwctl.exe --json start -t 0.14.0  |  10:33:18.386
Debug: false
==> environment structure written to C:/Users/raju4/.codewind/docker-compose.yaml
System architecture is:  amd64
Host operating system is:  windows
Attempting to find available port
Port 10000 Available
Please wait while containers initialize...  
Recreating codewind-performance ... 

[1A[2K
Recreating codewind-performance ... [32mdone[0m
[1BCreating codewind-pfe           ... 

[1A[2K
Creating codewind-pfe           ... [31merror[0m
[1B
ERROR: for codewind-pfe  Cannot create container for service codewind-pfe: invalid mount config for type "bind": invalid mount path: 'C:/dev/null' mount path must be absolute

ERROR: for codewind-pfe  Cannot create container for service codewind-pfe: invalid mount config for type "bind": invalid mount path: 'C:/dev/null' mount path must be absolute
Encountered errors while bringing up the project.
{"error":"DOCKER_COMPOSE_START_ERROR","error_description":"exit status 1"}
==> End cwctl.exe --json start -t 0.14.0  |  10:49:21.508 (Took 5178ms)

using all latest version. appreciate if someone can help on this issue

**Comment by jagraj** [comment]
@raju-valivarthi 
Here is the update for this issue(https://github.com/eclipse/codewind/issues/910#issuecomment-664536880). 
Let us use this issue as we closed #910 .

**Comment by raju-valivarthi** [comment]
Thank you Jagraj for the details. 

I will try enabling Hyper-V on my Windows 10 Home OS and reinstall docker.  will post the status in couple of days.

**Comment by raju-valivarthi** [comment]
I'm reinstalled Docker bye following the steps mentioned on https://docs.docker.com/docker-for-windows/install-windows-home/#install-docker-desktop-on-windows-10-home .  Code-wind containers started successfully on Windows Home. 

Thank you for the guidance. we can close this issue.
