### ISSUE TITLE
[SVT]: odo Open Liberty and Nodejs Express Web projects failing to build in remote.

### ISSUE THREAD

**Issue by DavidG1011** [eclipse/codewind#3220]
**Codewind version:** 0.14.1
**OS:** MacOS

**IDE version:** VSCode 1.47.2
**Kubernetes cluster:** OCP 4.3 (Remote)

**Description:**
Projects using the `OpenShift Devfiles NodeJS Express Web Application` and `OpenShift Devfiles Open Liberty` templates are failing to build.

From the NodeJs Express Web logs:
```
Executing devfile commands for component cw-odonodejsexpressweb
 •  Executing devbuild command "npm install"  ...
 ✗  
Unable to exec command [/bin/sh -c cd ${CHE_PROJECTS_ROOT}/nodejs-web-app/app && npm install]: 
/bin/sh: line 0: cd: /projects/nodejs-web-app/app: No such file or directory

 ✗  Executing devbuild command "npm install" [129ms]
 ✗  Failed to start component with name cw-odonodejsexpressweb. Error: Failed to create the component: unable to execute the build command: error while streaming command: command terminated with exit code 1
- Failed to build and deploy odo component: cw-odonodejsexpressweb
```

From the Open Liberty logs:

```
 ✓  Executing devinit command "echo \"moving liberty\" && mkdir -p /projects/user-app/target/liberty && mv /opt/ol/wlp /projects/user-app/target/liberty" [791ms]
 •  Executing devbuild command "if [ -e /projects/user-app/.disable-bld-cmd ]; then echo \"found the disable file\" && echo \"devBuild command will not run\" && exit 0; else echo \"will run the devBuild command\" && mvn -Dmaven.repo.local=/mvn/repository package && touch ./.disable-bld-cmd; fi"  ...
 ✗  
Unable to exec command [/bin/sh -c cd /projects/user-app && if [ -e /projects/user-app/.disable-bld-cmd ]; then echo "found the disable file" && echo "devBuild command will not run" && exit 0; else echo "will run the devBuild command" && mvn -Dmaven.repo.local=/mvn/repository package && touch ./.disable-bld-cmd; fi]: 
will run the devBuild command
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.196 s
[INFO] Finished at: 2020-07-30T20:16:03Z
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/projects/user-app). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException

 ✗  Executing devbuild command "if [ -e /projects/user-app/.disable-bld-cmd ]; then echo \"found the disable file\" && echo \"devBuild command will not run\" && exit 0; else echo \"will run the devBuild command\" && mvn -Dmaven.repo.local=/mvn/repository package && touch ./.disable-bld-cmd; fi" [3s]
 ✗  Failed to start component with name cw-odojavaopenlib. Error: Failed to create the component: unable to execute the build command: error while streaming command: command terminated with exit code 1
- Failed to build and deploy odo component: cw-odojavaopenlib
```

**Comment by johnmcollier** [comment]
It appears that the odo extension is using a cached / older nodejs devfile (and I assume the same for spring):

The error: `Unable to exec command [/bin/sh -c cd ${CHE_PROJECTS_ROOT}/nodejs-web-app/app && npm install]:` is referencing `CHE_PROJECTS_ROOT`, which is not present in the current [nodejs devfile](https://github.com/odo-devfiles/registry/blob/master/devfiles/nodejs/devfile.yaml).

**Comment by johnmcollier** [comment]
FYI, it seems the issue was due to the 0.14.1 image tag not getting refreshed with James changes last week (merge build failed so it didn't get pushed up), so I restarted the build and the images got refreshed.

I can now deploy odo2 projects on Che.

@jagraj @DavidG1011 Can you verify?

**Comment by jagraj** [comment]
I tried to verify all odo projects, liberty odo project still fails and it does not build.

**Comment by johnmcollier** [comment]
@jagraj Can you include the logs?

**Comment by johnmcollier** [comment]
Found the cause of the issue, opened https://github.com/odo-devfiles/registry/pull/30 to resolve this.

**Comment by johnmcollier** [comment]
While my registry PR did fix the OL issues on the odo side, they're still not working on the codewind side. It seems it's not pulling down the right sample project?

This is because the odo extension doesn't honor the `sparseCheckoutDir` field in the [OL devfile](https://github.com/odo-devfiles/registry/blob/master/devfiles/java-openliberty/devfile.yaml). So instead of checking out `/templates/default` from https://github.com/OpenLiberty/application-stack.git (as odo does), it instead just checks out https://github.com/OpenLiberty/application-stack.git which causes the build to fail.

**Comment by johnmcollier** [comment]
Tagging this as a Portal issue since it'll require a fix to either Codewind or the odo extension.

**Comment by james-wallis** [comment]
So `cwctl` does the git clone of the project and doesn't support cloning a repository using a directory underneath that as the project source code, it'd be an enhancement to support this feature.

For 0.14.1 we can just blacklist the open-liberty template or any that have the sparseCheckoutDir field? Or we could supply our own git repository to clone from?
@johnmcollier what do you think about having our own git repo?

**Comment by tobespc** [comment]
Any enhancement right now we should be very careful with.  However, if we black list it there may not be another release for a while and so we would be adding a permanent restriction.

@james-wallis what do you think the sizing would be to add support ?

**Comment by james-wallis** [comment]
Spoke to @tobespc this morning, for this release I'll make the extension ignore any `devfiles` with the `sparseCheckoutDir` field as it cannot be supported by `cwctl` at this time.

If we want to add support for it, we can do it in another release.

**Comment by james-wallis** [comment]
PRs accepted into the repository.
/assign 
/pipeline verify

**Comment by james-wallis** [comment]
/pipeline in progress

After speaking to @tobespc and Andy it was decided that we should support Open Liberty. I'm enhancing PFE and the ODO Devfile extension to add the `sparseCheckoutDir` onto the project directory inside the project inf so file-watcher uses that path to build.

**Comment by AndyRWatson** [comment]
@james-wallis do you have an outlook ?   When we discussed yesterday it could be a couple of day ?

**Comment by james-wallis** [comment]
At the moment it's looking like it should be code complete by tomorrow midday.

**Comment by james-wallis** [comment]
Have had issues with the development cluster I was using today - it was taking 5 minutes to do the initial codewind setup and not building the test project. I've switched cluster but I won't make the midday target.

Issues I'm having:
* Refactoring the method turbine uses to work out the projectName as the Open Liberty project will have the child directory `default`. At the moment every project I create is incorrectly being called `default`.
* Open Liberty project not starting - this might go away when the previous issue is fixed.
* On previous cluster on a successful start the Route was not being created.

**Comment by james-wallis** [comment]
Using the changes in the PR linked, I've been able to create an ODO Devfile Open Liberty project and run it (can be accessed and state changes to `started`).

I haven't been able to test:
* Using an IDE (mine wasn't playing nice with the dev environment)
* On Che but I expect it should be the same

**Comment by jagraj** [comment]
My ODO Open liberty project built successfully on Che. 

![image](https://user-images.githubusercontent.com/713849/90072032-ae0cda00-dcc4-11ea-94bd-8ba6ecfdf895.png)

**Comment by DavidG1011** [comment]
All odo projects are now building fine in remote:
<img width="487" alt="Screen Shot 2020-08-13 at 10 30 47 AM" src="https://user-images.githubusercontent.com/30476587/90149241-47360200-dd52-11ea-8e28-57aac603b441.png">

I think this can be closed. Thank you to everyone for your hard work!
