### ISSUE TITLE
Build failed during  test suite stage

### ISSUE THREAD

**Issue by josephca** [eclipse/codewind#327]
Test suite failed with the following message. 
Jenkins build: https://ci.eclipse.org/codewind/job/Codewind/job/codewind/job/0.3.0/2/console

11:10:09   message: projectDeletion
11:10:09   data: {
11:10:09    "operationId": "c059a69ba63d1894bb63ce2b8516364f",
11:10:09    "projectID": "cc829ed0-c9a5-11e9-adc5-df8cb98ef6c2",
11:10:09    "status": "success"
11:10:09  }
11:10:09  [91m[28/08/19 15:09:46 server.js] [ERROR][39m portal/server.js: Origin host  does not match expected host naughtywebsite.com
11:10:09  [91m[28/08/19 15:09:46 server.js] [ERROR][39m portal/server.js: Origin host  does not match expected host naughtywebsite.com
11:10:09  [91m[28/08/19 15:09:46 server.js] [ERROR][39m portal/server.js: Origin host  does not match expected host naughtywebsite.com
11:10:09  [91m[28/08/19 15:09:46 server.js] [ERROR][39m portal/server.js: Origin host  does not match expected host naughtywebsite.com
11:10:09  [91m[28/08/19 15:09:46 /portal/middleware/errorHandler.js] [ERROR][39m { error:
11:10:09     { name: 'ValidationError',
11:10:09       message:
11:10:09        'Error while validating request: request.body should have required property \'projectName\'' } }
11:10:09  [91m[28/08/19 15:09:46 /portal/middleware/errorHandler.js] [ERROR][39m { error:
11:10:09     { name: 'ValidationError',
11:10:09       message:
11:10:09        'Error while validating request: request.body should have required property \'projectName\'' } }
11:10:09  Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
11:10:09      at ServerResponse.setHeader (_http_outgoing.js:470:11)
11:10:09      at ServerResponse.header (/portal/node_modules/express/lib/response.js:771:10)
11:10:09      at ServerResponse.contentType (/portal/node_modules/express/lib/response.js:599:15)
11:10:09      at ServerResponse.send (/portal/node_modules/express/lib/response.js:145:14)
11:10:09      at handleErrors (/portal/middleware/errorHandler.js:8:26)
11:10:09      at newFn (/portal/node_modules/express-async-errors/index.js:16:20)
11:10:09      at Layer.handle_error (/portal/node_modules/express/lib/router/layer.js:71:5)
11:10:09      at trim_prefix (/portal/node_modules/express/lib/router/index.js:315:13)
11:10:09      at /portal/node_modules/express/lib/router/index.js:284:7
11:10:09      at Function.process_params (/portal/node_modules/express/lib/router/index.js:335:12)
11:10:09  Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
11:10:09      at ServerResponse.setHeader (_http_outgoing.js:470:11)
11:10:09      at ServerResponse.header (/portal/node_modules/express/lib/response.js:771:10)
11:10:09      at ServerResponse.contentType (/portal/node_modules/express/lib/response.js:599:15)
11:10:09      at ServerResponse.send (/portal/node_modules/express/lib/response.js:145:14)
11:10:09      at handleErrors (/portal/middleware/errorHandler.js:8:26)
11:10:09      at newFn (/portal/node_modules/express-async-errors/index.js:16:20)
11:10:09      at Layer.handle_error (/portal/node_modules/express/lib/router/layer.js:71:5)
11:10:09      at trim_prefix (/portal/node_modules/express/lib/router/index.js:315:13)
11:10:09      at /portal/node_modules/express/lib/router/index.js:284:7
11:10:09      at Function.process_params (/portal/node_modules/express/lib/router/index.js:335:12)
11:10:09  [32m[28/08/19 15:09:46 Turbine] [INFO][39m The current log level is debug
11:10:09  [32m[28/08/19 15:09:46 /portal/routes/logging.route.js] [INFO][39m logging level set to debug
11:10:09  [36m[28/08/19 15:09:46 server.js] [DEBUG][39m GET /api/v1/templates/repositories called
11:10:09  [36m[28/08/19 15:09:46 server.js] [DEBUG][39m PATCH /api/v1/batch/templates/repositories called
11:10:09  [32m[28/08/19 15:09:46 Templates.js] [INFO][39m Repository list updated.
11:10:09  [36m[28/08/19 15:09:46 server.js] [DEBUG][39m GET /api/v1/templates/repositories called
11:10:09  [36m[28/08/19 15:09:46 server.js] [DEBUG][39m DELETE /api/v1/templates/repositories called
11:10:09  [32m[28/08/19 15:09:46 Templates.js] [INFO][39m Repository list updated.
11:10:09  [36m[28/08/19 15:09:46 server.js] [DEBUG][39m POST /api/v1/templates/repositories called
11:10:09  [32m[28/08/19 15:09:46 Templates.js] [INFO][39m Repository list updated.
11:10:09  [36m[28/08/19 15:09:46 server.js] [DEBUG][39m GET /api/v1/templates/repositories called
11:10:09  [36m[28/08/19 15:09:46 server.js] [DEBUG][39m PATCH /api/v1/batch/templates/repositories called
11:10:09  [32m[28/08/19 15:09:46 Templates.js] [INFO][39m Repository list updated.
11:10:09  [36m[28/08/19 15:09:46 server.js] [DEBUG][39m GET /api/v1/templates/repositories called
11:10:09  [36m[28/08/19 15:09:46 server.js] [DEBUG][39m DELETE /api/v1/templates/repositories called
11:10:09  [32m[28/08/19 15:09:46 Templates.js] [INFO][39m Repository list updated.
11:10:09  [36m[28/08/19 15:09:46 server.js] [DEBUG][39m POST /api/v1/templates/repositories called
11:10:09  [32m[28/08/19 15:09:46 Templates.js] [INFO][39m Repository list updated.
11:10:09  [36m[28/08/19 15:09:46 server.js] [DEBUG][39m GET /api/v1/templates/repositories called
11:10:09  [36m[28/08/19 15:09:46 server.js] [DEBUG][39m PATCH /api/v1/batch/templates/repositories called
11:10:09  [32m[28/08/19 15:09:46 Templates.js] [INFO][39m Repository list updated.
11:10:09  [36m[28/08/19 15:09:46 server.js] [DEBUG][39m GET /api/v1/templates/repositories called
11:10:09  [36m[28/08/19 15:09:46 server.js] [DEBUG][39m DELETE /api/v1/templates/repositories called
11:10:09  [32m[28/08/19 15:09:46 Templates.js] [INFO][39m Repository list updated.
11:10:09  [36m[28/08/19 15:09:46 server.js] [DEBUG][39m POST /api/v1/templates/repositories called
11:10:09  [32m[28/08/19 15:09:46 Templates.js] [INFO][39m Repository list updated.
11:10:09  [36m[28/08/19 15:09:46 server.js] [DEBUG][39m GET /api/v1/templates/repositories called
11:10:09  [36m[28/08/19 15:09:46 server.js] [DEBUG][39m PATCH /api/v1/batch/templates/repositories called
11:10:09  [32m[28/08/19 15:09:46 Templates.js] [INFO][39m Repository list updated.
11:10:09  [36m[28/08/19 15:09:46 server.js] [DEBUG][39m GET /api/v1/templates/repositories called
11:10:09  [36m[28/08/19 15:09:46 server.js] [DEBUG][39m DELETE /api/v1/templates/repositories called
11:10:09  [32m[28/08/19 15:09:46 Templates.js] [INFO][39m Repository list updated.
11:10:09  [36m[28/08/19 15:09:46 server.js] [DEBUG][39m POST /api/v1/templates/repositories called
11:10:09  [32m[28/08/19 15:09:46 Templates.js] [INFO][39m Repository list updated.
11:10:09  [36m[28/08/19 15:09:46 server.js] [DEBUG][39m GET /api/v1/templates/styles called
11:10:09  
11:10:09  Stopping and removing Codewind Docker containers.
11:10:09  
11:10:09  Stopping all running containers
11:10:11  d175b26f8b94
11:10:11  d6966255c944
11:10:11  
11:10:11  Successfully removed containers
11:10:11  
11:10:11  SUCCESSFULLY REMOVED CONTAINERS
11:10:11  
11:10:11  ERROR: THERE ARE NO CONTAINERS TO REMOVE 
11:10:11  
11:10:11  Removing docker network
11:10:11  codewind_network
11:10:11  
11:10:11  Successfully removed docker network 
11:10:11  
11:10:11  Removing docker network
11:10:11  Error: No such network: codewind_default
11:10:11  
11:10:11  Error removing docker network

**Comment by stalleyj** [comment]
@josephca Do you remember the actual test failure as the link is dead and the output you have included is just the end of the log ? There are many errors in the log because we test error cases so it's difficult to identify unexpected issues.

**Comment by josephca** [comment]
@stalleyj Sorry, the build was removed by the scheduled clean. Here is a PR build to show the same error. https://ci.eclipse.org/codewind/job/Codewind/job/codewind/view/change-requests/job/PR-322/1/console

**Comment by stalleyj** [comment]
Looks like our Project Lifecycle tests are timing out. I think the best solution is to separate these out to a separate step in the Jenkinsfile. You could skip them as a quick fix and i can get the work done to separate next week.

**Comment by josephca** [comment]
> Looks like our Project Lifecycle tests are timing out. I think the best solution is to separate these out to a separate step in the Jenkinsfile. You could skip them as a quick fix and i can get the work done to separate next week.

Sure, I'll comment the test suite run for now.

**Comment by josephca** [comment]
Please enable test suite run once you get a fix. Please refer to #339. Thanks,

**Comment by josephca** [comment]
As a reminder, please refer to https://bugs.eclipse.org/bugs/show_bug.cgi?id=550488#c3 while fixing the test suite. 

Copying https://bugs.eclipse.org/bugs/show_bug.cgi?id=550488#c3 :
I've notice something else: all the workspace files are owned by root, as they are eventually written by the docker daemon. This prevents files to be removed later on by the Jenkins agent process (a standard user).

You should use the -u parameter to map the user id properly whenever you call docker:

-u $(getent passwd genie.codewind | cut -d: -f3):$(getent passwd genie.codewind | cut -d: -f4)

**Comment by tobespc** [comment]
test suite has been re enabled now

**Comment by tobespc** [comment]
closing as this is now all running
