### ISSUE TITLE
Use -u parameter to map the user id properly when you call docker in Jenkins

### ISSUE THREAD

**Issue by josephca** [eclipse/codewind#328]
JIPP docker build agent experienced a disk space issue and the agent was cleaned manually by Eclipse team.  When calling docker command we should use -u parameter. 

Bugzilla ticket: https://bugs.eclipse.org/bugs/show_bug.cgi?id=550488

Copying the response from Eclipse team : 

I've notice something else: all the workspace files are owned by root, as they are eventually written by the docker daemon. This prevents files to be removed later on by the Jenkins agent process (a standard user).

You should use the -u parameter to map the user id properly whenever you call docker:

-u $(getent passwd genie.codewind | cut -d: -f3):$(getent passwd genie.codewind | cut -d: -f4)

**Comment by josephca** [comment]
@johnmcollier @tobespc can you consider this as a higher priority? this is rather urgent. Unless we fix this, the docker agent will experience space issue again and PR build cannot be restarted as it cannot remove workspaces.

**Comment by johnmcollier** [comment]
@josephca You're probably more familliar with Jenkins and the Docker VPS than I am though

**Comment by johnmcollier** [comment]
@josephca I should also note that the Codewind Che Plugin docker build isn't creating or writing to any files on the workspace, so I don't think this will help with the storage issues (though it may for the Codewind repo)

**Comment by stalleyj** [comment]
@josephca It is not possible to run Codewind passing in the user as it is currently a requirement for it to run as root. We therefore can't re-enable the tests at the moment. Once the new architecture (for hybrid mode) is delivered, the pfe container will not mount the filesystem and not run as root which should eliminate any deletion issues.

**Comment by tobespc** [comment]
we don't have tests right now that test creating projects.   Closing this as its not applicable right now
