### ISSUE TITLE
appsody deploy case sensitive project failure 

### ISSUE THREAD

**Issue by mjwhale** [eclipse/codewind#33]
appsody deploy fails because the project name is converted to lower case.   libertyTest becomes libertytest:

Running appsody extract results in:

> appsody extract
Extracting project from development environment
Running command: docker[pull appsody/java-microprofile:0.2.2]
Running command: docker[create --name libertyTest-extract -v /home/mike/codewind-workspace/libertyTest/src:/project/user-app/src -v /home/mike/codewind-workspace/libertyTest/pom.xml:/project/user-app/pom.xml appsody/java-microprofile:0.2.2]
Running command: docker[cp libertyTest-extract:/project /home/mike/.appsody/extract/libertyTest]
Running command: docker[rm libertyTest-extract -f]
Project extracted to /home/mike/.appsody/extract/**libertyTest**

running appsody deploy results in failure because libertyTest becomes libertytest:

> appsody deploy
Extracting project from development environment
Running command: docker[pull appsody/java-microprofile:0.2.2]
Running command: docker[create --name libertyTest-extract -v /home/mike/codewind-workspace/libertyTest/src:/project/user-app/src -v /home/mike/codewind-workspace/libertyTest/pom.xml:/project/user-app/pom.xml appsody/java-microprofile:0.2.2]
Running command: docker[cp libertyTest-extract:/project /home/mike/.appsody/extract/libertyTest]
Running command: docker[rm libertyTest-extract -f]
Project extracted to /home/mike/.appsody/extract/libertyTest
Running command: docker[build -t libertytest -f /home/mike/.appsody/extract/libertytest/Dockerfile /home/mike/.appsody/extract/libertytest]
[Docker] unable to prepare context: path "/home/mike/.appsody/extract/**libertytest" not found**
[Error] Error running docker command: exit status 1
mike@devmachine:~/codewind-workspace/libertyTest$

**Comment by makandre** [comment]
This is possibly related to appsody bug https://github.com/appsody/appsody/issues/73 (it says build in the summary but affects deploy as well)

**Comment by makandre** [comment]
@mjwhale Could you try your scenario with a newer release of the appsodyExtension? Replace your copy with this: https://github.com/kabanero-io/appsodyExtension/releases/tag/0.2.2

Be sure to restart Codewind so it picks up the newer release

**Comment by makandre** [comment]
Oh, you should also make sure your local install of appsody is version 0.2.5 which contains fix for https://github.com/appsody/appsody/issues/73

**Comment by mjwhale** [comment]
my versions already appear compliant, from ~/codewind-workspace/.extensions/appsodyExtension/README.md:

> # appsodyExtension

This repository is an extension to Codewind that adds support for [Appsody](https://appsody.dev) projects.

- appsody version: [0.2.5](https://github.com/appsody/appsody/releases/tag/0.2.5)
- appsody controller version: [0.2.1](https://github.com/appsody/controller/releases/tag/0.2.1)

**Comment by makandre** [comment]
How about your local install of appsody CLI?  From your description it looks like you're running appsody CLI directly.

**Comment by mjwhale** [comment]
I have installed appsody_0.2.5_amd64 for ubuntu and then applied the appsody extension in the codewind workspace extensions directory by cloning the following:

https://github.com/kabanero-io/appsodyExtension

resulting in the following directory:
~/codewind-workspace/.extensions/appsodyExtension

**Comment by kylegc** [comment]
We found the issue in Appsody and are working on a fix. Apologies that this wasn't thoroughly fixed in 0.2.5
If all goes well, the fix will be included in a new release (probably 0.2.8) of Appsody later today.

**Comment by kylegc** [comment]
Appsody 0.2.8 is now released and this issue should be fixed.

**Comment by mjwhale** [comment]
Excellent, that works now.  Thanks!

**Comment by makandre** [comment]
Thanks @kylegc.  @mjwhale Please close issue if there are no other problems, thanks.
