### ISSUE TITLE
SVT:Open liberty and Lagom projects failed to build on RHEL7

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#343]
**Codewind version:** 0.3
**OS:**  RedHat Linux 7

**Che version:** 
**IDE extension version:**  eclipse-plugin 0.3
**IDE version:** Eclipse 2019-06
**Kubernetes cluster:**

**Description:**
Open liberty and Lagom projects failed to build on RHEL7.  Both of these projects have multi stage build files. 

```
Sending build context to Docker daemon  83.97kB

Step 1/15 : FROM maven:3.5.4-jdk-8-alpine AS builder
Error parsing reference: "maven:3.5.4-jdk-8-alpine AS builder" is not a valid repository/tag: invalid reference format
```

Dockerfile ...

```
FROM maven:3.5.4-jdk-8-alpine AS builder
```

**Steps to reproduce:**
1. Install codewind from eclipse plugin on RedHat EL 7.
2. Create Open liberty and Lagom projects.
3. They both are failing to build.

```
Sending build context to Docker daemon  83.97kB

Step 1/15 : FROM maven:3.5.4-jdk-8-alpine AS builder
Error parsing reference: "maven:3.5.4-jdk-8-alpine AS builder" is not a valid repository/tag: invalid reference format
```

**Workaround:**

**Comment by rajivnathan** [comment]
@jagraj can you please add the docker version on the RHEL 7 machine you reproduced this on?

**Comment by jagraj** [comment]
Here is my docker version...

```
docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-103.git7f2769b.el7.x86_64
 Go version:      go1.10.8
 Git commit:      7f2769b/1.13.1
 Built:           Fri Aug  2 10:19:53 2019
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-103.git7f2769b.el7.x86_64
 Go version:      go1.10.8
 Git commit:      7f2769b/1.13.1
 Built:           Fri Aug  2 10:19:53 2019
 OS/Arch:         linux/amd64
 Experimental:    false
```

**Comment by johnmcollier** [comment]
Multi-stage docker builds weren't introduced until Docker 17.05 and RHEL by default uses Docker Enterprise 1.13.1, which is based on an older version of Docker without support for multi-stage builds. As such, this behaviour is expected.

@jagraj As mentioned on the call, since our [docs](https://www.eclipse.org/codewind/installlocally.html) say that Docker 17.06 or higher is needed, can we close out this issue?

**Comment by jagraj** [comment]
Thanks John, closing the issue now.
