### ISSUE TITLE
SVT: Intermittently Open liberty project fails on codewind che

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#344]
**Codewind version:** 0.3
**OS:** RHEL

**Che version:** 0.3
**IDE extension version:** Theia 0.3
**IDE version:** Theia - RC4
**Kubernetes cluster:**  OpenShift

**Description:**
Open liberty project intermittently fails to build from Codewind che.  It tries to use lagom projects maven cache and fails to build. 

```
"projectID": "38d7b5b0-caab-11e9-ba5f-493060042e75",
  "appStatus": "stopped"
}
^[[91m[29/08/19 22:20:51 cw-olcc03svt-38d7b5b0-caab-11e9-ba5f] [ERROR]^[[39m ^[[31m[ File Name: /file-watcher/server/dist/projects/projectUtil.js | Function Name: containerBuildAndRun | Line Number: 1294] ^[[39mBuild image stage failed for olcc03svt
^[[91m[29/08/19 22:20:51 cw-olcc03svt-38d7b5b0-caab-11e9-ba5f] [ERROR]^[[39m ^[[31m[ File Name: /file-watcher/server/dist/projects/projectUtil.js | Function Name: containerBuildAndRun | Line Number: 1295] ^[[39m[object Object]
^[[91m[29/08/19 22:20:51 FileWatcher.js] [ERROR]^[[39m projectStatusChanged: failed (project: {
  "projectID": "38d7b5b0-caab-11e9-ba5f-493060042e75",
  "buildStatus": "failed",
  "detailedBuildStatus": "Creating image for build failed",
  "lastbuild": 1567117251564
})
^[[91m[29/08/19 22:20:51 olcc03svt] [ERROR]^[[39m containerBuildAndRun : 1287 | | The command /file-watcher/scripts/dockerScripts/docker-build.sh bud --format docker --layers --label builtBy=codewind -t cw-olcc03svt-38d7b5b0-caab-11e9-ba5f,/codewind-workspace/olcc03svt,/codewind-workspace/.logs/olcc03svt-38d7b5b0-caab-11e9-ba5f-493060042e75/docker.build.log,38d7b5b0-caab-11e9-ba5f-493060042e75 failed with exit code 1
^[[32m[29/08/19 22:20:51 olcc03svt] [INFO]^[[39m Build state changed for project: 38d7b5b0-caab-11e9-ba5f-493060042e75 from: inProgress, to: failed, with message: buildscripts.buildFail
^[[32m[29/08/19 22:20:51 olcc03svt] [INFO]^[[39m Emitting event
 message: projectStatusChanged
 data: {
  "projectID": "38d7b5b0-caab-11e9-ba5f-493060042e75",
  "buildStatus": "failed",
  "detailedBuildStatus": "Creating image for build failed",
  "lastbuild": 1567117251564
}
^[[32m[29/08/19 22:20:51 olcc03svt] [INFO]^[[39m Kicking off validation for project: 38d7b5b0-caab-11e9-ba5f-493060042e75
^[[32m[29/08/19 22:20:51 olcc03svt] [INFO]^[[39m Validating project using operationId: 97fd67b8a676ebacbdaa10d47ebccfd2
^[[32m[29/08/19 22:20:51 olcc03svt] [INFO]^[[39m Checking for required files
^[[32m[29/08/19 22:20:51 olcc03svt] [INFO]^[[39m Checking for required file /Dockerfile
^[[32m[29/08/19 22:20:51 olcc03svt] [INFO]^[[39m Sending validation result
^[[91m[29/08/19 22:20:51 olcc03svt] [ERROR]^[[39m ^[[31m[ File Name: /file-watcher/server/dist/projects/projectUtil.js | Function Name: buildAndRun | Line Number: 1101] ^[[39mThe container failed to start fo```


**Steps to reproduce:**

1. Install codewind che on OpenShift.
2. Create OpenLiberty project.
3. Intermittently  Build fails with above failure.


**Workaround:** 
<!-- Did you find a way to work around the bug? If so, please describe how you worked around it.-->

**Comment by jagraj** [comment]
Here is the log from codewind.
[codewind.txt](https://github.com/eclipse/codewind/files/3560156/codewind.txt)

**Comment by johnmcollier** [comment]
@jagraj Can you upload the project's docker.build.log too?

This is certainly odd. 

Looking at the logs, the only thing that stands out to me is:
```
[91m[29/08/19 22:20:51 olcc03svt] [ERROR][39m containerBuildAndRun : 1287 | | The command /file-watcher/scripts/dockerScripts/docker-build.sh bud --format docker --layers --label builtBy=codewind -t cw-olcc03svt-38d7b5b0-caab-11e9-ba5f,/codewind-workspace/olcc03svt,/codewind-workspace/.logs/olcc03svt-38d7b5b0-caab-11e9-ba5f-493060042e75/docker.build.log,38d7b5b0-caab-11e9-ba5f-493060042e75 failed with exit code 1

```

Looking at [docker-build.sh](https://github.com/eclipse/codewind/blob/master/src/pfe/file-watcher/scripts/dockerScripts/docker-build.sh#L19), I'm wondering if we're not properly sanitizing the arguments? And thus, the wrong project is getting built?

**Comment by DavidG1011** [comment]
Logs from my attempt:
[docker.build.log.txt](https://github.com/eclipse/codewind/files/3560216/docker.build.log.txt)
[codewind.txt](https://github.com/eclipse/codewind/files/3560224/codewind.txt)

**Comment by johnmcollier** [comment]
I've been able to reproduce this, by doing the following:
- Create and deploy a Lagom project. It _should_ build fine without issue
- Create an Open Liberty project. It will build the Open Liberty dockerfile **but** use the Lagom pom.xml, causing the build to fail

Or by doing the following:
- Create and deploy an Open Liberty project. It _should_ build fine without issue
- Create a Lagom project. It will build the Lagom dockerfile **but** use the Open Liberty pom.xml, causing the build to fail

Other generic docker projects don't affect cause this, it's only when Open Liberty and Lagom are used together.

**Comment by johnmcollier** [comment]
I've done some more investigation, this seems to be a bug with buildah when using the `--layers` flag, rather than Codewind.

I'll be opening a bug against Buildah for this, but outside of removing the `--layers` flag from builds (which will slow down the builds a fair bit), there's not much we can in Codewind.

**Comment by johnmcollier** [comment]
Buildah issue: https://github.com/containers/buildah/issues/1830

**Comment by elsony** [comment]
For this issue, we'll workaround the existing buildah problem by removing the --layer flag when we build for docker project type with language of java as a temporarily solution for the ifix until we have got a proper fix from buildah.

**Comment by rajivnathan** [comment]
Jag has verified
