### ISSUE TITLE
Add docs showing users how to build and run Codewind from source

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#350]
I’ve noticed that a lot of our repos (well, mainly https://github.com/eclipse/codewind) are missing any sort of docs telling users how to build Codewind and actually run development/custom builds.

As an open source project I feel this is a really important step in getting external users to contribute to us. If users can’t figure out how to even build and run their builds of Codewind, how can we expect them to contribute to us?

**Comment by sishida** [comment]
ID will help draft something up for this issue!

**Comment by sishida** [comment]
@eharris369 @johnmcollier @tetchel

Hi, team,
Erin suggested that we place the "building from source" instructions in the IDE Readme files for each IDE. Eclipse already has its instructions in its own Readme--which I hadn't even realized! 😅 

So I created https://github.com/eclipse/codewind-vscode/pull/215 to add the "building from source" instructions to the VS Code Readme.

And then I edited the main Codewind Readme to put links to the Readme files in both `codewind-vscode` and `codewind-eclipse`: https://github.com/eclipse/codewind-vscode/pull/215

What do we all think of these updates? Good to go? 😃

**Comment by eharris369** [comment]
Actually, I was just suggesting that the instructions for building the IDEs from source should be in the IDE Readmes and this should just cover building Codewind from source and then point to the IDE instructions.

**Comment by sishida** [comment]
Would these be the instructions for just the Codewind part?
1. Clone the `codewind` repository.
2. Run the `./script/build.sh` script to run the Codewind build, or run the `./run.sh` script to build and start Codewind.

**Comment by eharris369** [comment]
Yes

**Comment by sishida** [comment]
Cool. I just added the two-step instructions to the `Codewind` repo Readme file in my latest commit. I left the links to the IDE Readme files.

**Comment by sishida** [comment]
See these README files for the instructions:
🌯 Codewind: https://github.com/eclipse/codewind/blob/master/README.md
🍣 Codewind VS Code: https://github.com/eclipse/codewind-vscode
🍛 Codewind Eclipse: https://github.com/eclipse/codewind-eclipse/blob/master/README.md
Closing this issue.
