### ISSUE TITLE
Theia testing on RHOS IKS

### ISSUE THREAD

**Issue by elsony** [eclipse/codewind#359]
Testing to make sure all VSCode function works on RHOS IKS

**Comment by jopit** [comment]
@elsony Please confirm, this is for testing the VSCode plugin running in Theia in Che on IKS, correct?

**Comment by tetchel** [comment]
#360 is for eclipse (which of course does not run in the cloud), so this might be for hybrid?

**Comment by johnmcollier** [comment]
@tetchel @jopit Yeah, this is for validating Hybrid mode with vscode against RHOS on IKS

**Comment by elsony** [comment]
Yes

**Comment by tetchel** [comment]
:+1:
