### ISSUE TITLE
Appsody python debug does not work and its option should be removed

### ISSUE THREAD

**Issue by sghung** [eclipse/codewind#363]
**Codewind version:** 0.3.1
**OS:** Mac

**Description:**
Appsody added the python stack. For the debug scenario, debugging is not supported on python and its capabilities will need to be removed as part of https://github.com/eclipse/codewind/pull/367. The user can still restart in debug mode, but debugging will not actually work.

https://github.com/eclipse/codewind-appsody-extension/pull/20 was to set the debug and app port for the newly added python project, so the app would be detected as started. 

**Steps to reproduce:**
Create the python template, restart in debug mode, and debugging does not work

**Workaround:** 
None

**Comment by makandre** [comment]
I have a PR for this

**Comment by makandre** [comment]
When you restart in debug mode, you will get a message similar to this:

`Failed to attach debugger to <project>. No debug type available for project of type Extension.`
