### ISSUE TITLE
Extend Turbine PFE Functional Tests - Swift Projects

### ISSUE THREAD

**Issue by rajivnathan** [eclipse/codewind#365]
Description of the enhancement: Once #48 has been completed for the docker projects, we can go ahead and extend the PFE functional tests for swift project types.

Proposed solution: The extended functional tests for swift project types should comply with the following list of functions (can change if new functions are added, check index.ts under src/pfe/file-watcher/server/src/) and work for both local and hybrid cases.

- [x] createProject
- [x] deleteProject
- [x] setLocale
- [x] setLoggingLevel
- [x] readWorkspaceSettings
- [x] testDeploymentRegistry
- [x] deploymentRegistryStatus
- [x] registerListener
- [x] getProjectTypes
- [x] getProjectCapabilities
- [x] projectAction
- [x] projectSpecification
- [x] logs
- [x] shutdown
- [x] updateStatus
- [x] checkNewLogFile
- [x] updateProjectForNewChange

**Comment by yangcao77** [comment]
Can assign this to me.

**Comment by yangcao77** [comment]
Local 100% passed, saw 2 failures on Kube. 
changeInternalAppPort  & rebuild
Suspecting the same issue as https://github.com/eclipse/codewind/issues/397

**Comment by ssh24** [comment]
@rajivnathan I am looking into this on the stablization work. Could you please assign me to this?
