### ISSUE TITLE
Improve Writing of Eclipse Codewind Extension Readme

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind#368]
We have already completed the VS Code tools improvements (https://github.com/eclipse/codewind/issues/150), and now we need to add the equivalent Eclipse tools updates.

To include:
- Must include link to Codewind Docs.
- Must outline Features with the explicit command pallet names and possibly links, as well as explain relationship to make them aware of their existence with links to specific docs. 
- Point out location of Extension and relationship to the workspace. Include link to Workspace Welcome Page.

See the PR https://github.com/eclipse/codewind-vscode/pull/152 for VS Code update details.

**Comment by sishida** [comment]
@eharris369 Hi, Erin, I have included your feedback in my latest commit: https://github.com/eclipse/codewind-eclipse/pull/291/commits/7b6daa8ef18416f41debc12cc3a8d3e5cb507399

I also realized that your feedback also applies to the `mdt-eclipse-managingprojects.md` file in the `codewind-docs` repo, so I created a separate PR for updating that file: https://github.com/eclipse/codewind-docs/pull/140

Thanks for all of your helpful info! :)

**Comment by eharris369** [comment]
Hi Sarah.  I had one additional comment that applies to both.  Otherwise it looks good.

**Comment by sishida** [comment]
@eharris369 Thanks for the feedback! I have updated both PRs.
