### ISSUE TITLE
Codewind Sidecar functional tests

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#37]
Tests the following:

- [ ] Deployment of PFE
- [ ] Check if FilewatcherD is started correctly

**Comment by lentheivendra** [comment]
I'll be taking a look at this

**Comment by lentheivendra** [comment]
Scenarios tested:
- Create Che workspace from Codewind dev file
- Verify Codewind workspace pod is running
- Verify sidecar container is running and ready, nginx & filewatcherd processed, and Codewind service successfully deployed
- Verify filewatcher daemon is up & running
- Verify filewatcher daemon restarts after kill
- Verify sidecar container restarts after nginx kill
- Stop and delete the Codewind Che workspace

**Comment by johnmcollier** [comment]
Sidecar functional tests have been delivered, closing this item out in favour of https://github.com/eclipse/codewind/issues/233
