### ISSUE TITLE
Call the codewind CLI for project creation in the IDEs

### ISSUE THREAD

**Issue by sghung** [eclipse/codewind#371]
**Description of the enhancement:**
Once the codewind project creation is moved out of the docker container and into the codewind CLI, we need both the Eclipse and VSCode codewind extensions to call the CLI instead of the REST service inside the codewind docker container. 

There are extensions such as Appsody, which need to run natively on the OS (instead of the docker container) to avoid docker issues that have resulted in binding paths in the OS.

**Proposed solution:** 
When the CLI for project creation is available, call that instead of the existing project creation REST from the codewind docker container.

**Comment by tobespc** [comment]
We have made the changes for vscode to call the CLI for project creation but not for eclipse yet

**Comment by eharris369** [comment]
Eclipse PR merged: https://github.com/eclipse/codewind-eclipse/pull/262

**Comment by sghung** [comment]
Closing as it has been implemented
