### ISSUE TITLE
Codewind support for OCP 4

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#372]
Out of curiousity, I attempted to stand up Codewind and Che on OCP4 with three separate clusters: 
   - Two existing ones running remotely 
   - One running locally on my laptop with [CodeReady Containers](https://github.com/code-ready/crc)

I hit the following issues:
- Che doesn't start on some OCP 4 clusters https://github.com/eclipse/che/issues/14426 
    - Not our issue, but something to keep an eye on, as we use Che
- When Che does start:
    - Codewind almost always fails to start due to us mounting the RWO Che workspace volume.
    - With [CodeReady Containers](https://github.com/code-ready/crc), Codewind _does_ start, but we're hit with tons of `Permission denied` errors, so Codewind still isn't usable.

~I should also note that OCP 4 doesn't support NFS or GlusterFS, which are the two main storage types that we support on Kube currently.~ Edit: NFS now works on newer OCP 4 builds

**We need to get Codewind running on OCP 4:**

The following issues need to be addressed in order to get Codewind running
- [ ] Fix volume issues preventing Codewind from starting most of the time
    - I didn't investigate too much, but likely need to move away from the RWO volume that the Che workspace uses. 
   - **Best case:** We _may_ be able to fix this by setting `CHE_INFRA_KUBERNETES_PVC_ACCESS__MODE` to `ReadWriteMany` when installing Che
  - **Worst case:** We only support NFS for volumes
  - ToDo: Investigate RedHat OpenShift Container storage
- [ ] Fix permissions issues preventing Codewind from functioning properly when it does start
    - Note: Not applicable on NFS installs, as the permissions are set properly
- [ ] Expose projects over ingress/routes: https://github.com/eclipse/codewind/issues/459
   - Can no longer assume we can access the NodePort services for projects

**Comment by johnmcollier** [comment]
https://github.com/eclipse/codewind/issues/459 needs to be addressed too

**Comment by elsony** [comment]
Add doc label to describe the restriction on OCP 4 that Codewind needs to run using NFS.

**Comment by johnmcollier** [comment]
@sishida FYI, I'll work with you later this week on this. Should be a small addition to our install docs.

**Comment by sishida** [comment]
- Delivering OpenShift 4
- Add ID update to this page in the "Prerequisites" section: https://www.eclipse.org/codewind/installoncloud.html
- Add a new bullet point under "Set up the PersistentVolume (PV) with either Network File System (NFS) or GlusterFS." Say something like, "Codewind uses RWX (ReadWriteMany) volumes to provide persistent storage. Because of this, on OpenShift 4, NFS (Network File System) must be used for storage”

**Comment by johnmcollier** [comment]
Closing as OCP4 support has been delivered for Codewind and we have documented that OCP 4 requires NFS

**Comment by elsony** [comment]
Iterative dev item for ingress: https://github.com/eclipse/codewind/issues/590 - done
