### ISSUE TITLE
Check if the correct appsody is installed on the OS in codewind-installer

### ISSUE THREAD

**Issue by sghung** [eclipse/codewind#383]
**Codewind version:** master
**OS:** any

**Description of the enhancement:**
- Check if appsody is installed on the OS
- Check if the version is compatible (we may need to discuss this further on what version to check for and what to tell the user)
- Return an error to the user (with info to point to the troubleshooting docs)
- Make changes in https://github.com/eclipse/codewind-installer

**Comment by sghung** [comment]
- determine if GO has a way to detect exit status for running appsody. If it doesn't exist, see if there's an error code that is not OS specific
- see if we can throw an error that the IDE can eventually get. See if it is standard error or output
- give IDE team a title or message that they can display generically

**Comment by laven26** [comment]
@laven26

**Comment by sghung** [comment]
No longer applicable since we are packaging up the appsody binaries.
