### ISSUE TITLE
Display certain Codewind CLI errors to the user in the IDE

### ISSUE THREAD

**Issue by sghung** [eclipse/codewind#384]
**Codewind version:** master
**OS:** any

**Description of the enhancement:**
For appsody, we'd like to the one in the operating system. If the CLI detects that appsody isn't installed, it will return back an error (CLI work to be done on https://github.com/eclipse/codewind/issues/383). We want to bubble up this message to the user in the IDE so they know to read the documentation on how to install appsody on their OS.

**Comment by jgwest** [comment]
@sghung Does the user need to have Appsody installed, in order to use Codewind? Or will they only get the error when trying to create/import an Appsody project?

**Comment by sghung** [comment]
@jgwest I talked with Tim deBoer on this and he wants appsody to be included as part of our install so the user can avoid this. He saw adding appsody as a pre-req would be a regression. We are currently looking into getting appsody installed by packaging up the binaries to get past this install dependency. As a result, I am closing this.
