### ISSUE TITLE
SVT:After codewind restart few appsody projects are not running but build is successful.

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#391]
**Codewind version:** 0.3.1
**OS:** WIndows

**Che version:**
**IDE extension version:** 0.3.1
**IDE version:** Eclipse 2019-06
**Kubernetes cluster:**

**Description:**
I migrated to codewind 0.3.1 version from eclipse plugin. After restart some of my appsody projects are not in running state even though build status says successful.

Project types having this issue :

1. Eclipse Microprofile project.
2. Appsody nodejs default project.
3. Appsody NodeJS Simple 
4. Appsody Spring Default 
5. Appsody Swift.

PFE log file..
[pfe.txt](https://github.com/eclipse/codewind/files/3581429/pfe.txt)

![appsodyprojectsnotstarted](https://user-images.githubusercontent.com/713849/64387091-f75e9f00-d008-11e9-925b-686fa775958c.JPG)

```
(node:51) [DEP0091] DeprecationWarning: crypto.DEFAULT_ENCODING is deprecated.
(node:51) [DEP0010] DeprecationWarning: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
(node:51) [DEP0011] DeprecationWarning: crypto.Credentials is deprecated. Use tls.SecureContext instead.
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments:
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 21:28 5 Sep, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (/file-watcher/server/node_modules/moment/moment.js:320:98)
    at configFromString (/file-watcher/server/node_modules/moment/moment.js:2385:15)
    at configFromInput (/file-watcher/server/node_modules/moment/moment.js:2611:13)
    at prepareConfig (/file-watcher/server/node_modules/moment/moment.js:2594:13)
    at createFromConfig (/file-watcher/server/node_modules/moment/moment.js:2561:44)
    at createLocalOrUTC (/file-watcher/server/node_modules/moment/moment.js:2648:16)
    at createLocal (/file-watcher/server/node_modules/moment/moment.js:2652:16)
    at Object.hooks [as default] (/file-watcher/server/node_modules/moment/moment.js:12:29)
    at Object.getFilesInContainerWithTimestamp (/file-watcher/server/dist/utils/dockerutil.js:300:117)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

Appsody logs...

[appsody.log](https://github.com/eclipse/codewind/files/3581436/appsody.log)
[appsody.log](https://github.com/eclipse/codewind/files/3581437/appsody.log)
[appsody.log](https://github.com/eclipse/codewind/files/3581440/appsody.log)
[appsody.log](https://github.com/eclipse/codewind/files/3581443/appsody.log)

**Steps to reproduce:**
1. Create all project types in 0.3 version.
2. Upgrade to Codewind 0.3.1 version.
3. After all projects built and I see above projects failed to run. 

**Workaround:**

**Comment by makandre** [comment]
Remember that plain node and swift projects don't have listening server and are expected to be stopped

**Comment by jagraj** [comment]
Thanks, do you need any other information from my environment to debug for other failures.?

**Comment by makandre** [comment]
Of the attached appsody logs:

1) Java Microprofile, appsody stopped with following error

```
[Container] Project is missing required parent:
[Container]   <parent>
[Container]     <groupId>dev.appsody</groupId>
[Container]     <artifactId>java-microprofile</artifactId>
[Container]     <version>0.2.11</version>
[Container]   </parent>
[Container] [Error] FATAL error APPSODY_PREP command received an error.  The controller is exiting: exit status 1
[Error] Error waiting in 'appsody run' exit status 1
```

We've seen this kind of error before that seemed to occasionally pop up, especially when a new version of the stack is released.

2) Plain node, expected to be stopped

3) Spring project, log shows nothing out of the ordinary and that the spring project started.  Note that if a project takes a long time to start up, Codewind may think the project is stopped (a timeout was put in, I believe it gives up after 10 pings)

4) Swift, expected to be stopped


I would suggest trying to restart or to disable/enable the projects to see if they go to start.  I don't believe these are persistent problems we're seeing here.

**Comment by jagraj** [comment]
Hmm, I can not stop due to installer issue to try this again. It will always fail saying container missing.

But the Microprofile project is up and running and we don't poll for status change after 10 retries.?

**Comment by makandre** [comment]
@yangcao77 will know more about what Codewind does when the polling times out

**Comment by yangcao77** [comment]
If the project stucks in `starting` state after 10 retries. and we will consider the project as `stopped`.

**Comment by jagraj** [comment]
Ok, got more info on Java Microprofile project failure. Looks like 0.3.0 version of Appsody Java Microprofile project fails to build on 0.3.1 version of Codewind which is due to parent  change in pom.xml to new version. 

Looks like existing projects has to be migrated or supported in latest Appsody/Codewind 0.3.1 release. 

Codewind 0.3.0 appsody project

```
    <parent>
        <groupId>dev.appsody</groupId>
        <artifactId>java-microprofile</artifactId>
        <version>0.2.10</version>
    </parent>
```

Codewind 0.3.1 appsody project

```
    <parent>
        <groupId>dev.appsody</groupId>
        <artifactId>java-microprofile</artifactId>
        <version>0.2.11</version>
    </parent>
```

Is this the problem with the Codewind/Appsody.? , May be codewind should use previous version of Java Microprofile stack and build in 0.3.1 release rather with the latest Appsody stack.?

**Comment by makandre** [comment]
This actually does not have anything to do with our version 0.3.0 vs 0.3.1.  We simply pickup whatever is the latest stack version that appsody publishes.   As we've seen before I think whenever the stack gets updated, we see this sort of error.  I recall seeing some activity in appsody slack channel regarding this and how they were switching to version ranges.  We can keep this issue open and I can followup with appsody team.  But I don't think this is a Codewind issue that should keep up the release.

**Comment by jagraj** [comment]
I am fine with that, do we have to document this or does Appsody team already has doc for this.?

**Comment by makandre** [comment]
Re the parent pom error, found out from appsody team that to resolve the problem, you have to edit the `pom.xml` and change the parent pom version to match the version it's looking for in the error message.

They are also rolling out version range support that should reduce the need to make this manual edit.

Can we close this issue?  Codewind does not need to react to this, when the stacks update we'll automatically get this support.

**Comment by makandre** [comment]
@jagraj can we close this?

**Comment by jagraj** [comment]
Sure, thanks. Closing it now.
