### ISSUE TITLE
[Che] Project creation is broken on master due to missing installer

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#395]
**Codewind version:** latest

**Che version:** 7.0.0
**IDE extension version:** latest
**IDE version:** Che Theia 7
**Kubernetes cluster:** OpenShift 3.11 on IKS

**Description:**
Project creation from the Theia extension is now broken on Che. When I go to create a project, the Theia extension spits out an error saying: `Error creating new project: spawn /tmp/codewind-installer ENOENT`. 

<img width="1392" alt="Screen Shot 2019-09-08 at 4 30 27 PM" src="https://user-images.githubusercontent.com/6880023/64494117-ca073080-d256-11e9-8aca-115b9f7bf33d.png">

It seems to be related to this PR: https://github.com/eclipse/codewind-vscode/pull/170, which updated the VSCode and Theia extensions to use the Codewind CLI for project creation and validation.

Despite the changes to add the installer to the Theia extension, the binary is not located at `/tmp/codewind-installer`. Looking in the Theia container, I see that the binary is at a different directory instead:
```
/ $ find /tmp -name 'codewind-installer'
/tmp/vscode-unpacked/eclipse.codewind-plugin.latest.kqqhddpsbw.codewind-theia.vsix/extension/bin/installer/macos/codewind-installer
/tmp/vscode-unpacked/eclipse.codewind-plugin.latest.kqqhddpsbw.codewind-theia.vsix/extension/bin/installer/linux/codewind-installer
```

However, moving the binary back to `/tmp/codewind-installer` won't fix everything. The codewind-installer binary still can't be called:
```
/tmp/vscode-unpacked/eclipse.codewind-plugin.latest.kqqhddpsbw.codewind-theia.vsix/extension/bin/installer/linux $ ls -al
total 10036
drwxr-xr-x    2 theia    root          4096 Sep  8 20:45 .
drwxr-xr-x    5 theia    root          4096 Sep  8 20:45 ..
-rwxr-xr-x    1 theia    root      10267896 Sep  6 18:56 codewind-installer
/tmp/vscode-unpacked/eclipse.codewind-plugin.latest.kqqhddpsbw.codewind-theia.vsix/extension/bin/installer/linux $ ./codewind-installer 
/bin/sh: ./codewind-installer: not found
```

This is because the Theia container doesn't have glibc installed and the `codewind-installer` binary statically links to it, which means the binary can't currently be called.

To work around this, the installer needs to be built with `CGO_ENABLED=0` to disable `cgo`:
```
CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o codewind-installer-linux
```

I also see that both the macOS and Linux binaries are bundled in the Theia extension, when only the Linux version needs to be.

**Steps to reproduce:**
1. Create a Codewind workspace in Che from the [latest Devfile](https://raw.githubusercontent.com/eclipse/codewind-che-plugin/master/devfiles/latest/devfile.yaml)
2. Create a project using the Theia extension
3. The Theia extension will report the above error

**Comment by johnmcollier** [comment]
Tagging both the Portal and IDE squads as there's things both teams need to do:
1. Unpack the codewind-installer to the proper directory (`/tmp/codewind-installer`)
2. Only package the Linux binary of `codewind-installer`
3. Build `codewind-installer` with `CGO_ENABLED=0`

**Comment by tetchel** [comment]
Good detective work John

**Comment by hhellyer** [comment]
I built the statically compiled binary, this ran but in the theia container hit issues with the docker socket being unavailable. I've raised a PR to fix those here: https://github.com/eclipse/codewind-installer/pull/111

Once that's landed I will get a statically compiled binary into the plugin.

**Comment by johnmcollier** [comment]
Adding stopship to ensure the DCUT isn't declared until this is fixed.

**Comment by johnmcollier** [comment]
Verified on master, fixed. Thanks @hhellyer!
