### ISSUE TITLE
[Turbine Functional Test] Node Project Settings afterhook failing

### ISSUE THREAD

**Issue by maysunfaisal** [eclipse/codewind#397]
Looks like the afterhook of the Node project settings fails consistently:

```
#2 "after all" hook: after hook: internalPort settings test | Internal Port Test After Hook: Projects with single exposed port for "config project specification settings internalPort"
```

Log:
[kubefunctional_sept9.log](https://github.com/eclipse/codewind/files/3591035/kubefunctional_sept9.log)

**Comment by ssh24** [comment]
I am taking a look at this. @rajivnathan Could you please assign me to it?

**Comment by maysunfaisal** [comment]
seeing it today again - Sept 16

**Comment by ssh24** [comment]
@maysunfaisal Could you verify and close this issue?
