### ISSUE TITLE
Unable to open app for project with context root in VS-Code plugin

### ISSUE THREAD

**Issue by stalleyj** [eclipse/codewind#399]
**Codewind version:** 
0.3.1
**OS:** 
Mac

**Description:**
When creating a new project that has a context root set, I'm not able to open the app initially.  If I then do some other stuff, I am then able to open the app.  It seems that the context root is not set initially so the plugin attempts to open '/'.

**Steps to reproduce:**
Create a lagom project and attempt to open the app once it is running.

**Comment by johnmcollier** [comment]
Adding `area/iterative-dev` since this may be a timing issue in Turbine

**Comment by stalleyj** [comment]
I think it's more likely to be a timing issue in VScode as it works fine in Eclipse.

**Comment by maysunfaisal** [comment]
@stalleyj is this because of issue https://github.com/eclipse/codewind/issues/404?

Since its fine on Eclipse and not on VS Code?

**Comment by tetchel** [comment]
i think it is my bug, let me see

**Comment by tetchel** [comment]
indeed it is my problem, sorry for not giving it a better look earlier
