### ISSUE TITLE
Docker projects emit projectCreation event upon rebuild in kube

### ISSUE THREAD

**Issue by ssh24** [eclipse/codewind#400]
**Description:** I have noticed that docker projects emit a different event compared to other projects upon a rebuild in kube scenarios. It emits the `projectCreation` event where other project types emit `projectChanged`. The latter (i.e `projectChanged`) is a more reasonable event emit for a project rebuild, so the bug is in the case of docker projects emitting `projectCreation` in kube.

**Note:** Docker projects on local is fine. It emits `projectChanged` like other projects upon a rebuild.

**Comment by maysunfaisal** [comment]
I can fix this, 

i made the change for local here 
https://github.com/eclipse/codewind/blob/master/src/pfe/file-watcher/server/src/projects/projectUtil.ts#L1176

but Kube is emitting from here https://github.com/eclipse/codewind/blob/master/src/pfe/file-watcher/server/src/projects/projectUtil.ts#L1779

**Comment by ssh24** [comment]
**Verified**
