### ISSUE TITLE
Hybrid - deliver hybrid mode into master

### ISSUE THREAD

**Issue by jcockbain96** [eclipse/codewind#403]
**Description of the enhancement:**

Allow for the codewind PFE container to be switched between `remote` and `local`, driven by a setting in the plugins.

**Proposed solution:** 

Read an env-variable in plugin (e.g `CW_MODE='REMOTE'`). Then call the CLI `start` command with a `remote` flag (if the mode is remote). 
 
Then, in the CLI, start up the PFE container with a `remote` env-var. The PFE container will then use the remote routes over the local ones. 

Also, use a docker volume for the codewind-workspace, in the docker-compose, so that projects won't be lost when we restart PFE in remote mode.

**Comment by deboer-tim** [comment]
Can we not just set an environment var outside the IDE that the PFE can pick up? This is temporary until we can get the plugins to drive a per-project remote, so trying to keep it as simple as possible.

**Comment by hhellyer** [comment]
@deboer-tim The plugins need to know the pfe container is in remote mode as well when they create a connection to it so they can call the remote-bind API to create projects. Hopefully soon all projects will be remote (effectively) and the setting will go away.

**Comment by tobespc** [comment]
as we are now no longer shipping this for Q3, lets drop the flip mode and deliver this into the master branch as the 'only' mode

**Comment by tobespc** [comment]
closing as this is not needed now
