### ISSUE TITLE
.cw-settings default value not being initialized correctly

### ISSUE THREAD

**Issue by maysunfaisal** [eclipse/codewind#404]
**Codewind version:** latest
**OS:** Mac

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**
The default setting `internalDebugPort` in .cw-settings for a non debuggable project says null and seems like https://github.com/eclipse/codewind/blob/master/src/initialize/src/controllers/cwSettingsController.ts#L44 is not working? 

This is also blocking me from merging PR https://github.com/eclipse/codewind/pull/208 as it introduces a new setting. This prevents my new setting to show up as well.

When I created the PR two weeks ago, I can confirm that the default setting values were correct for all project types ie they were initialized to `""`

Non debuggable project has null:
![Screen Shot 2019-09-10 at 10 18 03 AM](https://user-images.githubusercontent.com/31771087/64622468-66474980-d3b5-11e9-839a-685deb3d9f47.png)

**Steps to reproduce:**
Create a new docker project to see the issue from Codewind latest

**Workaround:**

**Comment by stalleyj** [comment]
@maysunfaisal The initialize pod is no longer creating projects (via VS-Code) but Eclipse is still using it so it hasn't been removed yet. The bug is therefore in the cli which is doing the creation.

**Comment by tobespc** [comment]
https://github.com/eclipse/codewind-installer/pull/113

**Comment by maysunfaisal** [comment]
@tobespc @stalleyj I built the installer from the repo using https://github.com/eclipse/codewind-installer#building-and-deploying-locally-on-macos; how do I use the CLI to create projs using my Codewind which is using my code from the Codewind repo?

I have tried the Readme projects command but cant seem to get it run?

**Comment by rajivnathan** [comment]
@maysunfaisal https://github.com/eclipse/codewind-installer/pull/113 appears to be delivered. Can you please verify and close?

**Comment by maysunfaisal** [comment]
verified with the CLI
