### ISSUE TITLE
Turbine testing on Windows

### ISSUE THREAD

**Issue by elsony** [eclipse/codewind#407]
Setup nightly run of Turbine testing on windows

**Comment by rajivnathan** [comment]
This is now complete. See #506 for details

**Comment by maysunfaisal** [comment]
Just posting a screenshot of the task scheduler for reference.

<img width="1053" alt="Screen Shot 2020-05-21 at 10 46 31 AM" src="https://user-images.githubusercontent.com/31771087/82571389-e59a3900-9b50-11ea-8dc1-9a554a002430.png">
