### ISSUE TITLE
SVT : Eclipse plugin: Appsody project create fails

### ISSUE THREAD

**Issue by mmulholl** [eclipse/codewind#410]
**Codewind version:**     Codewind Base	1.1.4.v201909102036	
**OS:** Mac and Linix

**Che version:**
**IDE extension version:**
**IDE version:** Eclispe Eclipse IDE for Eclipse Committers Version: 2019-06 (4.12.0)
**Kubernetes cluster:**

**Description:**

Cannot create appsody projects on latest driver:

Lunux: 
An error occurred trying to create Codewind project AppsodyMicro
Project create failed for project: AppsodyMicro with output: {“status”:“failed”,“projectPath”:“/root/codewind-workspace/AppsodyMicro”,“result”:“exec: \“appsody\“: executable file not found in $PATH”}

Mac:
An error occurred trying to create Codewind project AppsodyLoopBack4
2019/09/11 08:33:35 Get https://github.com/appsody/stacks/releases/download/nodejs-loopback-v0.1.4/incubator.nodejs-loopback.templates.scaffold.tar.gz: net/http: TLS handshake timeout

**Steps to reproduce:**

Create an appsody project.

**Workaround:**

**Comment by mmulholl** [comment]
@jagraj

**Comment by makandre** [comment]
At the moment you need to install appsody CLI on your local system and it has to be on your system path.

A couple of changes are going in installer, vscode and eclipse to bundle the CLI but they are not all there yet

**Comment by makandre** [comment]
All above PRs are merged so it should be working now even without a local install of appsody.

**Comment by mmulholl** [comment]
Linus works.
For Mac I opened as issue for tracking: https://github.com/eclipse/codewind/issues/477
