### ISSUE TITLE
Appsody templates missing from list of new project templates.

### ISSUE THREAD

**Issue by hhellyer** [eclipse/codewind#413]
**Description:**
The appsody templates are now missing from the templates list when I try to create a new project from a template.

**Steps to reproduce:**
Start the latest master build of codewind, connect the VSCode plugin and try to create an new project from a template. The appsody templates will be missing.

**Workaround:** 
I backed off https://github.com/eclipse/codewind/pull/394 by checking out the previous commit `a73988fe` and the templates reappeared in the list of templates I could create a project from.

**Comment by makandre** [comment]
I'll take a look
