### ISSUE TITLE
Add a git issue template to redirect codewind-docs issues to the codewind repo

### ISSUE THREAD

**Issue by sghung** [eclipse/codewind#417]
Please add a template similar to what was done in the codewind-appsody-extension into the codewind-docs repo: https://github.com/eclipse/codewind-appsody-extension/commit/9a06f9630a0055c7ea832b06f67a66032e193b67

For the line: "This repository is not used for issue tracking of the Codewind Appsody extension" replace it with codwind docs and put a period at the end...so somehting like "This repository is not used for issue tracking for Codewind Docs."

**Comment by sishida** [comment]
I am closing this issue because it appears to have already been taking care of. 😃 

When I go to the `codewind-docs` issues, a notification appears that says to open issues in the main `codewind` repo: https://github.com/eclipse/codewind-docs/issues/new/choose
