### ISSUE TITLE
.cw-settings not indented correctly anymore

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#418]
the default cw-settings is now:

```
{
"contextRoot": "",
"internalPort": "",
"healthCheck": "",
"internalDebugPort": "",
"isHttps": true,
"ignoredPaths": [
""
]
}
```

bring back the indentation!

**Comment by jgwest** [comment]
Well this is `stopship` obviously 😄 *jk*

**Comment by tetchel** [comment]
technically, it is a regression 🤔

**Comment by jgwest** [comment]
🤔 🤔 🤔 🤔

**Comment by jcockbain96** [comment]
@tobes, I'll take this

**Comment by jcockbain96** [comment]
https://github.com/eclipse/codewind-installer/pull/127

**Comment by tetchel** [comment]
@jcockbain96 is this fixed

**Comment by jcockbain96** [comment]
Yes, is fixed in master of the cli.
