### ISSUE TITLE
codewind-installer does not have version

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#422]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**

`codewind-installer --version` doesn't actually give back a version:

```
andrews-mbp:Downloads andrewmak$ ./codewind-installer --version
codewind-installer version x.x.dev
```

**Steps to reproduce:**

**Workaround:**

**Comment by tobespc** [comment]
x.x.dev is the tag we give it for the master branch to show its in development.  The release branch will have the correct tag

**Comment by makandre** [comment]
I downloaded the release from https://download.eclipse.org/codewind/codewind-installer/0.4.0/latest/ and there's no version either

**Comment by tobespc** [comment]
ok, then thats needs to be updated for the release.  @josephca we need to make sure this step is added to the steps when we branch the code
