### ISSUE TITLE
Unknown error Starting Codewind $tag$

### ISSUE THREAD

**Issue by erpenbach** [eclipse/codewind#433]
**Codewind version:** 0.3.1
**OS:** macOS

**Che version:**
**IDE extension version:** 0.3.1
**IDE version:** 1.38.1
**Kubernetes cluster:**

**Description:**  Codewind fails to start fully.  When selecting Manage Extension gear, the message is:

"Error starting Codewind: Unknown error Starting Codewind $tag$"

**Steps to reproduce:**
Installed VS Code into /Applications folder.  
Installed Codewind plugin from Marketplace
From the Command Palette, select Codewind: Create New Project.

The command fails and the Manage Extension window reports: 

"Error starting Codewind: Unknown error Starting Codewind $tag$"

Subsequent attempts to create a new project report:

"The tools have not yet connected to Codewind. Ensure Codewind is started."

**Workaround:** 
No

**Comment by tetchel** [comment]
since this issue is getting some attention from the team, please also see https://github.com/eclipse/codewind/issues/411

**Comment by tetchel** [comment]
since we have #436 for docs i'm going to close this in favour of #411 which has a little more info.
