### ISSUE TITLE
Learn More (about template sources) button

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#434]
when we have docs for https://github.com/eclipse/codewind/issues/32, we have to update the Learn More button to open them.

If we don't get those docs in time, we have to remove the Learn More button

**Comment by sishida** [comment]
@tetchel This is the link where the new content will appear for the "More Info" button: https://www.eclipse.org/codewind/mdt-vsc-usingadifferenttemplate.html

**Comment by tetchel** [comment]
Links from IDEs have been updated, just awaiting docs PR linked
