### ISSUE TITLE
Update troubleshooting page for installation/starting issues

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind#436]
Add troubleshooting for the general issue of when Codewind installation/starting fails. This is usually resolved by stopping Codewind containers and doing a Docker system prune.

https://github.com/eclipse/codewind/issues/411
https://github.com/eclipse/codewind/issues/433

**Comment by sishida** [comment]
With all the a Docker system prune removes, it could cause unintentional setbacks:
```
docker system prune -a
WARNING! This will remove:
 - all stopped containers
 - all networks not used by at least one container
 - all images without at least one container associated to them
 - all build cache
Are you sure you want to continue? [y/N] y
```
Ideally, Codewind should have a more targeted solution even though the prune is likely to resolve the issues.

**Comment by tetchel** [comment]
another one: https://github.com/eclipse/codewind/issues/575

**Comment by tetchel** [comment]
why was this closed, do we have new doc?

**Comment by sishida** [comment]
@tetchel Closed based on a Slack post. Looking at it again, however, I have reopened the issue.

**Comment by jopit** [comment]
- Add additional diagnostic gathering to cwctl for this case
- Investigate if there's some less destructive way of recovering -- what is `prune -a` doing that restarting the docker engine isn't.
- Can we create a script that does the equivalent of `prune` but only for the codewind images and network?
- Create must-gather instruction or script or command.

**Comment by rtaniwa** [comment]
Do we know what aspect of the prune resolves the issue? I seem to remember someone trying to go in and manually remove all the Codewind images, and that didn't work. I agree, it would be more ideal to have a workaround that has a smaller blast radius.

**Comment by sishida** [comment]
@tetchel provided workarounds that users can try before they try Docker system prune.
We have also included a caution note about Docker system prune as well as info on how to preserve items that Docker system prune removes.

The PR has been merged: https://github.com/eclipse/codewind-docs/pull/233. Closing this issue.
