### ISSUE TITLE
Eclipse internal browser does not like Microprofile/Java EE root page

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#438]
**Codewind version:** 0.4.0
**OS:** Windows 10

**Che version:**
**IDE extension version:** Codewind for Eclipse 0.4.0
**IDE version:** Eclipse 2019-03
**Kubernetes cluster:**

**Description:**
If I create a new Microprofile/Java EE project from the template and then try to open it in Eclipse using the Eclipse internal browser I get a pop up asking me if I want to save the json to a file. I am not sure why the internal browser does not open the index.html page like an external browser does but it would be nice if all of the templates worked using the internal browser in Eclipse. If I remove the listResources method from the RootEndpoint class then the internal Eclipse browser also opens up the index.html page.

**Steps to reproduce:**
Create a new Microprofile/Java EE project from the Codewind template
When the project is running, double click on it in the Codewind explorer view to open it in the browser

**Workaround:** 
If I remove the listResources method from the RootEndpoint class then the internal Eclipse browser also opens up the index.html page.

**Comment by markcor11** [comment]
I tried this out on Mac with Codewind Plugin 0.7.0 and latest templates (This issue says it happens on Windows 10 so still need to determine if it can be reproduced there), however I was not able to reproduce on MAC.  When I double clicked on the running project from the Codewind Explorer,  the application root page opened in the embedder browser as expected : 

![Screenshot 2020-01-06 at 13 39 04](https://user-images.githubusercontent.com/28102564/71821379-ea6ebc80-3089-11ea-94b3-e9222b226385.png)

**Comment by tobespc** [comment]
closing as this is working ok

**Comment by eharris369** [comment]
I can still reproduce this on Windows.  It looks like the SVT team is running into it as well: https://github.com/eclipse/codewind/issues/1552.

**Comment by mattcolegate** [comment]
Tested on Windows 10 with Eclipse latest plugin 20200225. Can confirm issue is fixed. @tobespc please close.

**Comment by mattcolegate** [comment]
(close as I can get)
/pipeline verify

**Comment by malincoln** [comment]
@eharris369 pls verify and close. Thanks

**Comment by eharris369** [comment]
I have been trying but have not been able to get a microprofile project to build on Windows lately.

**Comment by eharris369** [comment]
Verified with 0.10.0 and master.
