### ISSUE TITLE
Odo project type extension implementation

### ISSUE THREAD

**Issue by elsony** [eclipse/codewind#446]
Add implementation for Odo project type extension including functions for:
create, first time app build, app update, app delete

**Comment by GeekArthur** [comment]
You can assign this issue to me.

**Comment by GeekArthur** [comment]
Currently we already finished `create`, `update`, `delete` user scenarios. We propose to create new repository called `codewind-odo-extension` under GitHub to host the source code of odo extension implementation.

**Comment by GeekArthur** [comment]
#447

**Comment by GeekArthur** [comment]
Implementation has been merged and verified, we can close this.
