### ISSUE TITLE
Odo project type extension shell into container

### ISSUE THREAD

**Issue by elsony** [eclipse/codewind#447]
Shell into container function for odo project type extension

**Comment by GeekArthur** [comment]
You can assign this issue to me.

**Comment by GeekArthur** [comment]
I figure out that for each odo component it has the label `deploymentconfig=$COMPONENT_NAME-$APP_NAME`, so we can still use `kubectl` to get the pod name to let the user shell into the container, the full `kubectl` command would be `kubectl get po -o name --selector=deploymentconfig=$COMPONENT_NAME-$APP_NAME`.

Also I check odo source code, odo also use this way to get the pod name: https://github.com/openshift/odo/blob/d8deed83a27b3a378669f85bbab1ff011c5d95f7/tests/helper/helper_oc.go#L313, so it would be safe for us to use.

**Comment by GeekArthur** [comment]
@elsony Confirmed with TimE, currently we don't have option to let user shell into application container on Kube, on our side, we are able to provide the API to send container name back to support the feature, but product doesn't have the feature for now.

**Comment by GeekArthur** [comment]
And the reason is IDE doesn't have access to `kubectl`

**Comment by GeekArthur** [comment]
I think we may close this issue due to the limitation above.

**Comment by elsony** [comment]
Closing due to current limitation on Codewind with no Kube shell into container support.
