### ISSUE TITLE
Auto install on odo project type extension on OpenShift

### ISSUE THREAD

**Issue by elsony** [eclipse/codewind#451]
Auto install on odo project type extension on OpenShift in Che.

**Comment by GeekArthur** [comment]
You can assign this issue to me.

**Comment by johnmcollier** [comment]
When deploying Codewind in Che, [we're already detecting if it's on OpenShift](https://github.com/eclipse/codewind-che-plugin/blob/master/codewind-che-sidecar/deploy-pfe/pkg/kube/kube.go#L36), so it should be relatively trivial to pass in an environment var to PFE, something like `ON_OPENSHIFT=true`.

**Comment by GeekArthur** [comment]
@johnmcollier Nice to know that, it makes this issue easier because we don't need to do extra check for OpenShift detection.

**Comment by GeekArthur** [comment]
The auto install work can be divided into three parts:
- Build phase:
Download extension zip file from odo extension release
- PFE startup phase:
If `ON_OPENSHIFT` is set to `true` then do the following actions:
Unzip the extension zip file
Download the odo latest/stable binary

**Comment by lentheivendra** [comment]
I'll be looking at this

**Comment by GeekArthur** [comment]
I will take look at this and Len will keep working on generating templates and ensure everything of `IDE -> Portal` works fine. Please assign this issue to me.

**Comment by rajivnathan** [comment]
This is done
