### ISSUE TITLE
Provide scripts to apply odo RBAC automatically for odo project extension

### ISSUE THREAD

**Issue by elsony** [eclipse/codewind#452]
Script to apply odo RBAC (role based authentication) automatically for odo project extension so assign the correct permission to preform the odo project support functions. Only available for OpenShift Che scenario.

**Comment by GeekArthur** [comment]
You can assign this issue to me.

**Comment by GeekArthur** [comment]
Already crated role and role binding to add additional rules into service account for supporting odo extension, we can either document the steps for user or automate the steps for applying those rules.

**Comment by GeekArthur** [comment]
ODO documentation: https://github.com/eclipse/codewind/issues/605

**Comment by rajivnathan** [comment]
This is now done
