### ISSUE TITLE
Performance Dashboard fades in too slow

### ISSUE THREAD

**Issue by deboer-tim** [eclipse/codewind#454]
**Codewind version: 0.3**
**OS: Mac**

**Description:**
When I open the performance dashboard it has a really nice fade-in effect of the data, but it takes too long for everything to appear and for a split second I always second guess whether it's actually opening or not. Or, if I'm trying to look at something quickly like a daily user I get impatient. IMHO we just need to speed things up a touch, i.e. make the delays or fade-ins 40% faster so that it has the same effect but doesn't impede usability.

**Comment by sishida** [comment]
Tagging @kimholmes to be notified of this issue with a design tag.

**Comment by tobespc** [comment]
not sure this is a bug is it ?  Its designed like that

**Comment by deboer-tim** [comment]
Usability issue vs bug? I've removed the label if that helps.

**Comment by kimholmes** [comment]
This is a dev bug. Shouldn't need design. But I do like the fade in effect. :-)

**Comment by tobespc** [comment]
verified
