### ISSUE TITLE
Give better error message when project path or name is already in use

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#463]
![image](https://user-images.githubusercontent.com/8888438/64989353-563ed680-d89b-11e9-9168-f6eb38e25026.png)

[this message](https://github.com/eclipse/codewind/blob/cde48d8308a9f04a500535445658c67a9958cd17/src/pfe/portal/routes/projects/binding.route.js#L64) and the similar one below it

should be made user-friendly. Something like:

"A Codewind project already exits at \<path\>."
"The project name \<name\> is already in use. Enter a new project name."

**Comment by ebuckle** [comment]
Looking into this. Seems like a good change, pr will be in soon
