### ISSUE TITLE
Increase code coverage of unit tests

### ISSUE THREAD

**Issue by rajivnathan** [eclipse/codewind#47]
Determine what functions make sense to be covered by unit tests and create follow up issues for implementation of groups of unit tests.

The unit tests refer to the tests under https://github.com/eclipse/codewind/tree/master/src/pfe/file-watcher/server/test/unit-test

**Comment by GeekArthur** [comment]
@rajivnathan You can assign this issue to me

**Comment by yangcao77** [comment]
@maysunfaisal  and I will work on this issue.

**Comment by maysunfaisal** [comment]
Hey @rajivnathan you can assign it to me as well

**Comment by yangcao77** [comment]
Turbine module requires unit tests:

- [ ] projectsController

- [ ] projectStatusController

- [ ] projectExtensions

- [ ] action

- [ ] DockerProjects

- [ ] Libertyprojects:

- [ ] LibertyValidator:

- [ ] logHelper: (Already covered)

- [ ] nodejsProjects:

- [ ] projectSpecifications: (Maysun)

- [ ] projectUtil:

- [ ] ShellExtensionProjects:

- [ ] Locale: (Stephanie - dev-ex/tempest#470)

- [ ] springProjects:

- [ ] SpringValidator:

- [ ] swiftProjects:

- [ ] Validator:

- [ ] logger:

- [ ] Socket:

- [ ] utils: (Stephanie - already coverred)

- [ ] WorkspaceSettings: (Stephanie)
