### ISSUE TITLE
Improve readability of documentation topics by improving design and styling

### ISSUE THREAD

**Issue by MelHopper** [eclipse/codewind#472]
**Codewind version:**  Codewind-docs folder as per 16th September 2019
**OS:** n/a

**Che version:** n/a
**IDE extension version:** n/a
**IDE version:** n/a
**Kubernetes cluster:** n/a

**Description of the enhancement:**

Readability of topic content in table of contents/ manual documentation, e.g. topic https://www.eclipse.org/codewind/mdt-vsc-getting-started.html

For example, It is not obvious that the text next to each step number is an overview, that the sub-bullets will tell you HOW to action the step, and which content is 'further detail' / 'aside' content.

**Proposed solution:** 

Discuss designing/stylising the topic pages with the Design team. 

See the following examples of good design:

https://docs.docker.com/get-started/part2/

Make more use of headings, sub-headings, graphics to show 'asides', code snippets, screenshots, tabs for navigation inside the topic or guide.

**Comment by sishida** [comment]
This issue is a little too broad to be dealt with all at once. We will continue to work with @MelHopper to open new issues that are in smaller scope.

**Comment by MelHopper** [comment]
Github issue https://github.com/eclipse/codewind/issues/512 deals with part of this.
