### ISSUE TITLE
Add 'overview' and 'next steps' sections to topics in ToC/Manual

### ISSUE THREAD

**Issue by MelHopper** [eclipse/codewind#473]
**Codewind version:** codewind-docs as per 16th Sept 2019
**OS:** n/a

**Che version:** n/a
**IDE extension version:** n/a
**IDE version:** n/a
**Kubernetes cluster:** n/a

**Description of the enhancement:**

Readability and user-friendliness of the documentation could be improved by giving context, explaining concepts and linking to the next topic(s) of interest for the user journey.

** For best-practice, look at Docker's content in the following topic: https://docs.docker.com/get-started/part4/ **

**Proposed solution:** 

Add:

1. Add 'objectives' paragraphs:
(i) at the top of the topic, to define specifically what the user will learn/achieve by working through the topic
(ii) also at the beginning of tasks to describe what the user will be doing next, why, how etc.

2. Add 'next steps' links to other topics. e.g. in Getting Started topic, link to a relevant Tutorial (the next step for an entry-level user to take).

3. Add links to relevant Guides

This is especially important for Getting Started, Tutorial and Scenario/Guide pages.

**Comment by kimholmes** [comment]
This Doc page just won a design award:
https://ibm.github.io/event-streams/

**Comment by micgibso** [comment]
@sishida I'll take this one please Sarah.

**Comment by micgibso** [comment]
Getting started with VS Code and Eclipse enhanced under issue #523 referenced above.

**Comment by MelHopper** [comment]
See the new topic blocks / tutorials 'Using Codewind Remotely' and 'Deploying Codewind Remotely' for a template of how to do this.

**Comment by MelHopper** [comment]
This github issue is being done during user flow work for:
- remote: DONE as of 0.11.0
- local: DONE as of 0.12.0
- Eclipse Che: In progress  https://github.com/eclipse/codewind/issues/2718

So closing this issue.
