### ISSUE TITLE
Docs: Recommend Eclipse 19.09 to users

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#474]
Because of the following Eclipse issue we want to recommend users install Eclipse 19.09 (which is scheduled to be released today):

https://bugs.eclipse.org/bugs/show_bug.cgi?id=541220 (fixed in Eclipse 19.09)

The recommendation should be added anywhere in the docs where we are telling the user to install Eclipse.

**Comment by eharris369** [comment]
Eclipse 2019-09 R (4.13.0) has just been released.

**Comment by sishida** [comment]
Notes from meeting on Sept. 18th:
- You can use earlier versions of Eclipse, but to avoid this bug, you need 19.09. Thus, we recommend using 19.09.
- Mention "Eclipse 19.09 and later."
- The bug brings up a dialog window although it doesn't actually cause importing problems.
- Add a link to the bug.

**Comment by eharris369** [comment]
If you want more details:  When creating a new Codewind project an error dialog may pop up about a java.lang.NullPointerException.  This is a problem with the smart import in Eclipse.  The project will import properly so there is no functional issue but the dialog can be confusing and make users think that there is a problem.

**Comment by sishida** [comment]
List of locations we need to update:
1️⃣ The `codewind-eclipse` README: https://github.com/eclipse/codewind-eclipse/blob/master/README.md
2️⃣ https://www.eclipse.org/codewind/mdteclipsegettingstarted.html

**Comment by j-c-berger** [comment]
I'll update the README
