### ISSUE TITLE
SVT: [Windows 10] Enable/Disable buttons in Template Source Manager Windows are broken if they are clicked

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#476]
**Codewind version:** 0.4.0 and Latest Development Version (Master)
**OS:** Windows 10 

**IDE extension version:** 0.4.0
**IDE version:** VS Code 1.38.1 

**Description:** Enable/Disable buttons in Template Source Manager Windows are broken if they are clicked.

![Screen Shot 2019-09-18 at 10 05 18 AM](https://user-images.githubusercontent.com/49531960/65156011-4b4f8780-d9fc-11e9-9eec-bdf994a9daf3.png)

![Screen Shot 2019-09-18 at 10 05 24 AM](https://user-images.githubusercontent.com/49531960/65156016-4d194b00-d9fc-11e9-9422-bdfc2ed43c29.png)

![Screen Shot 2019-09-18 at 10 05 30 AM](https://user-images.githubusercontent.com/49531960/65156021-4ee30e80-d9fc-11e9-827a-c5773863c07a.png)

**Steps to reproduce:**
1. Install Codewind
2. Start Codewind
3. Right click on "Projects"
4. Click on "Manage Template Source"
5. Enable/Disable a template

@jagraj

**Comment by tetchel** [comment]
I can reproduce, this is super bizarre. Refresh fixes the images, too.

**Comment by tetchel** [comment]
should be fixed in 0.4 now

**Comment by sujeilyfonseca** [comment]
I tested this issue on 2019-09-19 and I no longer see the problem.
