### ISSUE TITLE
Mac : Creating project fails :  net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by mmulholl** [eclipse/codewind#477]
**Codewind version:**  Codewind tech preview 0.4.0.v201909161757
**OS:** Mac

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**
Creating projects on Mac fails and codewind reports an error:
net/http: TLS handshake timeout

Running the codewind-installer from the command resulted in the same issue, but running the same curl command that is used by the installer worked.

Building my own version of the codewind-installer also worked. 

**Steps to reproduce:**

**Workaround:** 
I found this report of a similar issue:
https://discussions.agilebits.com/discussion/99219/error-net-http-tls-handshake-timeout

and in this case the solution was to delete all certificates from the keychain.

In my case I had a lot of certificates so I deleted some which were clearly redundant and it fixed the issue.

**Comment by jgwest** [comment]
@mmulholl Do you think it would be beneficial if the installer error message outputted the URL it was timing out on? I'm guessing the install folks could add that without too much trouble...

**Comment by sishida** [comment]
ID will add this info to the "Creating a new project" section of the Troubleshooting page.

**Comment by sishida** [comment]
The PR to update the Troubleshooting page is merged. Closing this issue.
