### ISSUE TITLE
Increase code coverage of functional tests

### ISSUE THREAD

**Issue by rajivnathan** [eclipse/codewind#48]
Functional testing will cover the Turbine module functions in index.ts
https://github.com/eclipse/codewind/blob/master/src/pfe/file-watcher/server/src/index.ts

The functional tests refer to the tests under https://github.com/eclipse/codewind/tree/master/src/pfe/file-watcher/server/test/functional-test

**Comment by GeekArthur** [comment]
@rajivnathan You can assign this issue to me

**Comment by ssh24** [comment]
**Functions to be tested**
- [x] createProject
- [x] deleteProject
- [x] setLocale
- [ ] setLoggingLevel
- [ ] readWorkspaceSettings
- [ ] testDeploymentRegistry
- [ ] registerListener
- [ ] getProjectTypes
- [ ] getProjectCapabilities
- [ ] projectAction
- [ ] projectSpecification
- [ ] logs
- [ ] shutdown;
- [ ] deleteProject
- [ ] updateStatus
- [ ] deploymentRegistryStatus
- [ ] checkNewLogFile
- [ ] updateProjectForNewChange
