### ISSUE TITLE
Let users know that Open API Tools is not supported in Che

### ISSUE THREAD

**Issue by sghung** [eclipse/codewind#482]
**Codewind version:** 0.4.0 and before
**OS:** any

**Description of the enhancement:**
Open API Tools on che is still being worked on: https://github.com/eclipse/codewind/issues/78 as a result, there is no support for Open API Tools on kube or che.

**Proposed solution:** 
I think this restriction should be mentioned in installoncloud.html. If there are other places that you think makes sense, I am fine with that too.

**Comment by sishida** [comment]
@sghung It sounds like we are eventually going to include OpenAPI tools on Che, so we can leave this issue open until we have it ready. However, I prefer not to add the info to the landing pages because then we'll just have to remove it later.

**Comment by sghung** [comment]
Closing as the feature is covered by https://github.com/eclipse/codewind/issues/78
