### ISSUE TITLE
SVT : Eclipse IDE set incorrect project type when importing appsody projects

### ISSUE THREAD

**Issue by mmulholl** [eclipse/codewind#487]
**Codewind version:**  Codewind tech preview	0.4.0.v201909162044	
**OS:** Macos

**Che version:**
**IDE extension version:**
**IDE version:** Eclipse 2019-06
**Kubernetes cluster:**

**Description:**

If create an appsody project and try importing it again the wizard does not set the project type to "appsody" but the value it would be if the project was not an appsody project.

For example when importing an existing Appsody Node Skaffold project, by default the type is set to "Node.js" - if i install that way it will not build. However, If I change the type to appsody and language to Node.js all is fine.

This is a regression and stop/ship.

**Steps to reproduce:**

**Workaround:** 

Manually set the correct values.

**Comment by mmulholl** [comment]
@jagraj

**Comment by tetchel** [comment]
this may be fixed by https://github.com/eclipse/codewind-eclipse/pull/309

**Comment by sujeilyfonseca** [comment]
This is the problem that I mentioned in the IDE channel. In VS Code, users are asked to confirm the type and language of the project to be imported. However, the types are always incorrect in Appsody projects. As Martin said, if the project type is manually selected for appsodyExtension, the project builds fine. However, if not, the project will not be built. Here are some examples:

<img width="415" alt="Screen Shot 2019-09-18 at 5 00 44 PM" src="https://user-images.githubusercontent.com/49531960/65207560-f9404d80-da5f-11e9-88d6-5034fe0119d9.png">
<img width="417" alt="Screen Shot 2019-09-18 at 5 05 56 PM" src="https://user-images.githubusercontent.com/49531960/65207564-fba2a780-da5f-11e9-9b81-59acd472ad1c.png">
<img width="413" alt="Screen Shot 2019-09-18 at 5 08 12 PM" src="https://user-images.githubusercontent.com/49531960/65207566-fcd3d480-da5f-11e9-89c3-7100f10da4e0.png">
<img width="418" alt="Screen Shot 2019-09-18 at 5 08 53 PM" src="https://user-images.githubusercontent.com/49531960/65207567-fd6c6b00-da5f-11e9-9d07-4f912792ff68.png">
<img width="414" alt="Screen Shot 2019-09-18 at 9 57 56 PM" src="https://user-images.githubusercontent.com/49531960/65207571-01988880-da60-11e9-94ab-d31d7f36d2d3.png">
<img width="415" alt="Screen Shot 2019-09-18 at 10 03 40 PM" src="https://user-images.githubusercontent.com/49531960/65207651-4ae8d800-da60-11e9-80e5-3a1b41e2e5f3.png">
<img width="415" alt="Screen Shot 2019-09-18 at 9 58 26 PM" src="https://user-images.githubusercontent.com/49531960/65207572-02c9b580-da60-11e9-9b92-3f6920ccc878.png">

All project types in previous images must be Appsody. Therefore, it would be good to include the area/vscode-ide label.

**Comment by eharris369** [comment]
This is fixed by eclipse/codewind-eclipse#309.  The problem of the project type being detected as Appsody is covered in https://github.com/eclipse/codewind/issues/445.

**Comment by eharris369** [comment]
This is a duplicate of 2 other issues:
- eclipse/codewind-eclipse#309
- #445

**Comment by mmulholl** [comment]
all good now.
