### ISSUE TITLE
SVT: Missing files error when importing some Appsody projects (VS code)

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#488]
**Codewind version:** 0.4.0
**OS:** Windows 10 and MacOS Mojave (10.14.6)

**IDE extension version:** 0.4.0
**IDE version:** 1.38.1

**Description:** In VS Code, users are requested to confirm the type and language of the project to be imported. However, the types are always incorrect and if the user selects “yes”, the import will fail due to missing files. This error occurs with all Appsody projects, except Appsody Eclipse MicroProfile and Appsody Python Flask. These latest templates currently do not automatically detect any information from the imported project.

<img width="415" alt="Screen Shot 2019-09-18 at 5 00 44 PM" src="https://user-images.githubusercontent.com/49531960/65208527-65708080-da63-11e9-81c0-b55b94c246c6.png">
<img width="447" alt="Screen Shot 2019-09-18 at 5 00 56 PM" src="https://user-images.githubusercontent.com/49531960/65208531-67d2da80-da63-11e9-8337-196531db88ed.png">

<img width="417" alt="Screen Shot 2019-09-18 at 5 05 56 PM" src="https://user-images.githubusercontent.com/49531960/65208546-6dc8bb80-da63-11e9-9a0f-70958a8885f6.png">
<img width="445" alt="Screen Shot 2019-09-18 at 5 06 19 PM" src="https://user-images.githubusercontent.com/49531960/65208549-6f927f00-da63-11e9-8686-dd3f05a59cdb.png">

<img width="413" alt="Screen Shot 2019-09-18 at 5 08 12 PM" src="https://user-images.githubusercontent.com/49531960/65208560-75886000-da63-11e9-99c4-98b86447ccf8.png">
<img width="445" alt="Screen Shot 2019-09-18 at 5 08 21 PM" src="https://user-images.githubusercontent.com/49531960/65208563-77eaba00-da63-11e9-9acb-2d064d64b90d.png">

<img width="418" alt="Screen Shot 2019-09-18 at 5 08 53 PM" src="https://user-images.githubusercontent.com/49531960/65208567-7ae5aa80-da63-11e9-954d-f42288a23e5a.png">
<img width="450" alt="Screen Shot 2019-09-18 at 5 09 05 PM" src="https://user-images.githubusercontent.com/49531960/65208570-7d480480-da63-11e9-9a29-92c6265d54f6.png">

<img width="415" alt="Screen Shot 2019-09-18 at 10 03 40 PM" src="https://user-images.githubusercontent.com/49531960/65208676-d6179d00-da63-11e9-8f54-7412025b70a5.png">
<img width="447" alt="Screen Shot 2019-09-18 at 10 28 30 PM" src="https://user-images.githubusercontent.com/49531960/65209001-b2088b80-da64-11e9-9763-b043fb3d29d3.png">

<img width="414" alt="Screen Shot 2019-09-18 at 10 33 28 PM" src="https://user-images.githubusercontent.com/49531960/65208917-7c63a280-da64-11e9-813f-2a6f799a6df1.png">
<img width="447" alt="Screen Shot 2019-09-18 at 10 31 56 PM" src="https://user-images.githubusercontent.com/49531960/65208936-84234700-da64-11e9-9450-f72750b675e4.png">

<img width="414" alt="Screen Shot 2019-09-18 at 9 57 56 PM" src="https://user-images.githubusercontent.com/49531960/65208940-871e3780-da64-11e9-8cf4-19cf5650daf0.png">
<img width="445" alt="Screen Shot 2019-09-18 at 10 29 28 PM" src="https://user-images.githubusercontent.com/49531960/65208945-8d141880-da64-11e9-9311-d7ade24677ac.png">

**Steps:**
1. Install Codewind
2. Start Codewind
3. Create an Appsody project
4. Remove the created project from Codewind
5. Import the project

**Workaround:** Manually change the project type to appsodyExtension.

@jagraj

**Comment by makandre** [comment]
This is basically same as #445 (for which there is a PR to fix)

**Comment by tetchel** [comment]
The vs code behaviour is correct; portal is providing bad info, and the user will likely not know better than to override it (by selecting "No, this is not the correct type" and then selecting Appsody)

**Comment by sujeilyfonseca** [comment]
I tested this problem on 2019-09-19. Users may not encounter this problem frequently, as Appsody projects are now being detected correctly. However, if the user selects "No" in the confirmation window and then enters the same type and language, he/she will get the error presented above regarding the missing files. For example, if the project type appears in the confirmation window as "appsodyExtension" and the project language as "java", and you enter the exact information manually, you will get the missing files error.

**Comment by makandre** [comment]
@tetchel there were some language selection bug in IDE that was fixed I believe?

**Comment by tetchel** [comment]
yes, that was #486 

Sujeily, If the user chooses to ignore the autodetection, and then selects the wrong type, it is expected that the project will misbehave. I consider this issue fixed

**Comment by tetchel** [comment]
I expect it has something to do with the installer tracking `isAppsody` separately in its detection logic, ie `isAppsody` is not necessarily the same as `projectType == "appsodyExtension"` ? but I just took a quick look at that code

**Comment by makandre** [comment]
`isApposdy` was only used inside the installer to keep track of whether they need to run init.  It's not returned to IDE (and it's going away post-0.4)

**Comment by tetchel** [comment]
ok, if this behaviour is changing in 0.5 i think we should consider this issue good for now (since it doesn't make much sense for a user to ignore the correct autodetection), and verify the new behaviour when it's in?

**Comment by makandre** [comment]
This has been fixed for a while.  Can we close?
