### ISSUE TITLE
Add documentation on start/stop of codewind

### ISSUE THREAD

**Issue by henrynash** [eclipse/codewind#49]
If you add a codewind extension (e.g. appsody) then you need to restart the codewind docker container. Restarting, for instance, VScode is not enough. We should perhaps have a general section on codewind extensions (i.e. the concept), plus the start/stop commands.

**Comment by tetchel** [comment]
Yes, you may restart codewind through the Codewind view in VS Code. 

However, we are changing the extension behaviour so you won't have to restart after adding one.

**Comment by sghung** [comment]
For the doc team, please reach out to me or Andrew if you need more clarification for general codewind extension install, since we can provide some verification.

**Comment by micgibso** [comment]
Thanks, will be in touch.

**Comment by MelHopper** [comment]
For entry-level users, in the Installation and Tutorial topics I think we could also do with stating:
1. That Docker needs to be started
2. HOW to check that Codewind is started. At the moment, the tutorial step 1 states: _First, ensure that Codewind is installed and running. For more information, see the Getting started: Codewind for VS Code page._ But the Getting Started page does not refer to start/stop commands or UI buttons.

**Comment by sishida** [comment]
I will try to create a PR for this file: https://www.eclipse.org/codewind/mdt-vsc-tutorial.html

**Comment by sishida** [comment]
Hi, @tetchel! I know that the VS Code extension has evolved since this issue has been opened. Is this issue still relevant?

I have created at PR based on the feedback I'm seeing in the issue, but please feel free to approve/remove as you see fit: https://github.com/eclipse/codewind/issues/49 

Thank you!

**Comment by tetchel** [comment]
this issue is outdated; we have UI for this now.

**Comment by henrynash** [comment]
So just for clarity, the issue I raises was specifically about the lack of documentation for the case when you install an extension into Codewind (e.g. Appsody) - and the fact that to make it active you had (at least in the version at the time) to cause the code wind docker container to be restarted. There was UI to do the restart...just no documentation to remind you to do this.

So just like to confirm that either:
a) You no longer need to restart the Codewind Docker container after installing an extension (e.g. AppsodyApplication), or
b) There is now documentation on when to use the restart command

**Comment by deboer-tim** [comment]
Current behaviour: if you install a new extension after Codewind has been started, you'll need to restart it. You can do this directly through the IDE, and the extension documentation would tell you how to do this.

OTOH, the Appsody extension is installed by default now so you wouldn't even need to know that it was built as an extension.

**Comment by sishida** [comment]
Since this issue is closed, I have closed my PR for this issue.

**Comment by henrynash** [comment]
So at the risk of flogging a dead horse....Is there general documentation and description of the extensions concept within the Codewind docs? I kind of imaged there would be a section on this, that talked about what is and isn't possible, explained that you had to restart Codewind after installing a new extension. It just seems a bit odd to leave it to the individual extensions docs to explain these concepts (as opposed to the specifics of each extension).

**Comment by sishida** [comment]
@deboer-tim @henrynash @tetchel 

What if we added extension info, such as explaining the overall extensions concept, to this file?
https://www.eclipse.org/codewind/gettingstarted.html

If this sounds good, I will open a new issue. Please let me know. Thank you!

**Comment by tetchel** [comment]
The reason we don't have documentation for extensions in general is that the Appsody extension, and the new extension we are developing, are meant to be included in Codewind - not installed by users. Having the users install the Appsody extension by hand was temporary and has not been the case since I believe our 0.3 release. 

At this time, extensions (and certainly their install process) are meant to abstracted away from the user, so I don't think it is worth documenting.

**Comment by henrynash** [comment]
Ah, right! That's the bit of info I didn't have....agreed, therefore, that no doc changes are required.
