### ISSUE TITLE
Upgrade story for 0.6 where codewind-workspace will not be mounted

### ISSUE THREAD

**Issue by stalleyj** [eclipse/codewind#491]
The remote architecture removes the requirement for codewind-workspace to be mounted in docker and replaces this with a docker volume which means that users existing projects will not appear in codewind. Anything that pfe currently stores in the workspace (project inf files, logs, metrics data, repository settings etc) will also be gone. 

A user would need to copy the contents into the pfe container for codewind to pick these up. We could provide a script or possibly automate this ?

**Comment by tobespc** [comment]
This might actually be simpler than we through.   The load test metrics will already exist in the projects workspace so when we bind the project, we need to send those files to the remote server along with the src code.  For logs, I'm not too worried if logs don't persist through an upgrade but that is up for debate.  The only real problem will be with the project.inf file, that will need to be recreated on the remote end.   Should we autobind the project for users ?

**Comment by jopit** [comment]
I find the idea of storing the "master" copy of Codewind metadata in a docker volume a little worrying.  If the docker volume gets deleted (because the user reinstalled docker or because they pruned all volumes to free up disk space for example) the metadata is lost.

I would be happier if the "master" copy of the metadata was always on the filesystem, and was changed first on the filesystem and then copied into the PFE container.

**Comment by deboer-tim** [comment]
Discussed on tech topics:
 - We'll start using Users/<user>/.codewind for the '.' files
 - On upgrade (if workspace exists and .codewind doesn't), the cli will move '.' files over

**Comment by stalleyj** [comment]
I've added an 'upgrade" command to the cli which can be called to move your projects.  
upgrade -ws /Users/myuser/codewind-workspace

It will read the project inf files from the old workspace, parse the relevant information and called bind for each of them

**Comment by jopit** [comment]
Does the 'upgrade' command do the right thing for Appsody projects, which still need to be in a location that is mounted into the container?

**Comment by tobespc** [comment]
not sure for appsody, it should work as we are not actually moving any source code around, just rebinding it

**Comment by makandre** [comment]
If we're just re-binding the existing appsody projects (which btw can be located anywhere on user disk just like other codewind projects), it should work

(project is synced over to PFE during the bind I assume?)

**Comment by tobespc** [comment]
closing as this is done
