### ISSUE TITLE
Article about enabling HTTPS

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind#496]
@elsony recommends that we include the content from the pull request https://github.com/eclipse/codewind-docs/pull/139 into an article.

From Elson: Although this is a useful piece of information, this is just example on how to enable https and those steps are not specific to the templates that we provide. Therefore, I suggest to turn this to an article instead of putting that as part of the Codewind documentation. When we put that to an article, we should also add the step for changing the https settings in Codewind to tie that back to Codewind instead.

Tagging @rajivnathan and @maysunfaisal for their awareness.
Also linking to the issue https://github.com/eclipse/codewind/issues/269 for reference.

❓ I like the idea of an article...but my main question is where are we going to place it? Will it be a new tab on Codewind.dev or in a different location?

**Comment by sishida** [comment]
Here is the content to go into the article:
---
layout: docs
title: Converting an application from HTTP to HTTPS
description: Converting an application from HTTP to HTTPS
keywords: https, http, python, microprofile, application, applications, codewind
duration: 1 minute
permalink: convertingtohttps
type: document
---

# Converting an application from HTTP to HTTPS

You can convert Codewind applications from HTTP to HTTPS. These examples feature a Python and a MicroProfile application.

**Caution:** Use these examples for development but not for production applications. The self-signed certificate and steps in these examples might not comply with the security policy and usage policy of your project.

## Converting a Python application from HTTP to HTTPS
1. Generate a private key.
 ```
 openssl genrsa -des3 -out server.key 1024
 ```
2. Generate a certificate signing request.
 ```
 openssl req -new -key server.key -out server.csr
 ```
3. Remove the passphrase from the key.
 ```
 cp server.key server.key.org
 openssl rsa -in server.key.org -out server.key
 ```
4. Generate a self-signed certificate.
 ```
 openssl x509 -req -days 365 -in server.csr -signkey server.key -out server.crt
 ```
5. In your Python application `app.py` file, use the certificate and the key.
 ```
 app.run(host="0.0.0.0", port=5000, ssl_context=('/tmp/server.crt', '/tmp/server.key'))
 ```
6. Update your Python application Dockerfile to include the certificate and the key.
 ```
 # Copy the Certificate and the Key
 ADD server.crt /tmp/server.crt
 ADD server.key /tmp/server.key
 ```

## Converting a MicroProfile application from HTTP to HTTPS
1. Generate a keystore with the Java `keytool` command.
 ```
 keytool -genkey -alias <alias>
     -keystore <path to save keystore.pfx>
     -storetype PKCS12
     -keyalg RSA
     -storepass <password>
     -validity 730
     -keysize 2048
 ```
2. Install the Liberty SSL feature in the application `server.xml` file.
 ```
 <featureManager>
   <feature>ssl-1.0</feature>
 </featureManager>
 ```
3. Use the keystore in the Liberty `server.xml` file by entering the same path and password from when you generated a keystore with the Java `keytool` command.
 ```
 <keyStore id="defaultKeyStore" location="/home/default/keystore.pfx" password="<password>" type="PKCS12"/>
 ```
4. Update your MicroProfile application Dockerfile to include the keystore.
 ```
 # Copy the Keystore
 COPY keystore.pfx /home/default/keystore.pfx
 ```

For more information, see [Configuring SSL for Liberty profile](https://www.ibm.com/support/knowledgecenter/SSHSCD_6.3.0/com.ibm.worklight.installconfig.doc/appcenter/t_ac_ssl_lib.html).

**Note:** To run the Python and MicroProfile HTTPS application on Kubernetes, update the chart `deployment.yaml` file to include the `scheme: HTTPS` value for the `livenessProbe` and `readinessProbe` probes.
```
livenessProbe:
    httpGet:
        path: /
        port: {{ .Values.service.servicePort }}
        scheme: HTTPS

```
```
readinessProbe:
    httpGet:
        path: /
        port: {{ .Values.service.servicePort }}
        scheme: HTTPS
```

**Comment by maysunfaisal** [comment]
@sishida you can assign it to me

**Comment by sishida** [comment]
@AndyRWatson Hi, Andy,

Today the ID team discussed a location for sharing articles like this one. Medium and Developer.ibm.com came up as potential places, but we think that the fastest/easiest place would be to add it to Codewind.dev as a new tab along with "Docs" and "News."

Does this sound good to you? If you'd prefer a place like Medium instead, could you please let us know the Codewind account to post under? Thank you!

**Comment by maysunfaisal** [comment]
@sishida any updates on this?

cc: @johnmcollier

**Comment by sishida** [comment]
@maysunfaisal I have posted in Slack and tagged Andy and Becca asking where we should place this article. :)

**Comment by beccabau** [comment]
Are you thinking like a "Codewind in the News" sort of thing? 

I took a quick glance at the Eclipse website, and I kind of like the Planet Eclipse tab they have (under Community) - https://planeteclipse.org/planet/
![image](https://user-images.githubusercontent.com/13971834/68408077-b727b400-0152-11ea-965b-6f72820cae3d.png)

This may warrant John's input, but maybe we could start populating a Community or `Codewind Blogs` tab with content that we think could be useful for developers but may not directly fit with other documentation.

Maybe we could even allow community members to submit their helpful hints/tips/tricks, and that kind of thing could drive community engagement..? 
![image](https://user-images.githubusercontent.com/13971834/68408308-1f769580-0153-11ea-8bc3-b17dff871647.png)

Either way, let me know where it ends up and I'll tweet it out.

**Comment by AndyRWatson** [comment]
sorry @sishida somehow missed the previous comment that tagged me in.    Medium sounds like a good starting point and as @beccabau mentioned we can look at other options as well.

If we go for the  medium blog (medium.com/codewind) can we add some extra personalisation information, as a user of codewind and by default the template used HTTP and the steps you needed to go through to change to HTTPS.      This may also lead nicely into a secondary blog on how to then create a HTTPS version as a template in your own repo.

**Comment by NikCanvin** [comment]
nice

**Comment by beccabau** [comment]
```
Why HTTPS

HTTPS is becoming increasingly common as the internet shifts to an HTTPS-only environment. In an unencrypted HTTP session, data is transferred in clear text, meaning anyone can eavesdrop on your actions over the web. Also, you don't have any additional verification to ensure you've connected to the correct website. You might be on a compromised network that could mine your information by directing you to imposter services. HTTPS, on the other hand, verifies that you have established a secure connection to your intended service by encrypting your sessions and checking certificates.

We want to help you protect the integrity of the applications and services you create with Codewind. To help you keep your applications and services secure, check out these examples to see how you can convert your Codewind applications from HTTP to HTTPS.
```

Unfortunately, couldn't get inline code chunks within a numbered list on Medium, so I had to use bullet points. Maybe this is something I can change once I play around with Medium more (I think I could use gist or something, but would rather get this out the door sooner, so that might be a future experiment).

Posted on medium (and tweeted) > https://medium.com/codewind/enabling-https-in-your-codewind-application-4a3c20562003
