### ISSUE TITLE
[ICP] Changes to any created project not being saved.

### ISSUE THREAD

**Issue by DavidG1011** [eclipse/codewind#5]
Platform: Che on ICP

Reproduce:
1. Create python project from "Hello World" template in Codewind.
2. Edit .py file.
3. Save using File > Save or shortcut (both reproduce this behavior).

Result: Project changes do not save.

Note: 

Upon closing the file, user is prompted to save. Selecting "Save" on this prompt does not save changes either.

**Comment by DavidG1011** [comment]
As far as I can tell, the issue is only occurring with python projects. Changes to the file just do not save, so new versions of the app can't be built. I created a python project from the "Hello World" template included with Codewind. It seems like any file changed within the project folder doesn't save (Dockerfile, app.py).

**Comment by rajivnathan** [comment]
When the files are created they need to be assigned with owner set to uid 1724 because that is the UID the theia container in the Che workspace pod is given. I verified changing the owner uid to that in pfe allows deletion from the theia container.

**Comment by tobespc** [comment]
@rajivnathan Thanks Rajiv, will look asap

**Comment by maysunfaisal** [comment]
This is not only affecting  python, but any projects created from template on Che and hence a stopship.

After a git clone of the template, we would need to give permission to the group for the project dir like `chmod -R g=rwx myproject/` so Theia can edit the projects in the Theia container on Che

**Comment by ssh24** [comment]
Also seeing this on all project types created on theia as a new project, i.e from the template.

**Comment by tobespc** [comment]
have recreated locally, working on a fix now

**Comment by rajivnathan** [comment]
@DavidG1011 The fix for this should be in now, can you give it another try?

**Comment by ericdylanpeters2** [comment]
@tobespc @DavidG1011 is this fixed now as per Rajiv's comments?

**Comment by tobespc** [comment]
this is now fixed and delivered
