### ISSUE TITLE
Hybrid issues in Che

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#504]
Devfile (internal domain): http://time-nix.rtp.raleigh.ibm.com/devfile-hybrid.yaml

Issues:
- [ ] Since `.config` is not mounted out of the PFE container anymore, the plugin cannot write to `.config/settings.json`. So the deployment registry code has to be updated.
  - This also means that if the PFE container restarts, the data in this file and similarly `repository_list.json` is lost and the user will have to re-enter it
- [ ] Remove Che workspace volume mount from PFE
  - Sounds like it's not needed any more and won't work with the current hybrid architecture?
- [ ] Create separate, RWX volume for PFE (and the projects that require it, i.e Liberty & spring)
   - Liberty and Spring projects would need to mount this volume instead
- [ ] Concerns about network latency and NFS
   - Worried about performance if the NFS server is running outside of the cluster or has bad latency.

**Comment by johnmcollier** [comment]
@hhellyer @tobespc 

Not entirely issues or bugs, but things that need to be done or checked for Che with the hybrid changes
```
Hybrid and Che:
- Remove Che workspace volume mount from PFE??
  - Sounds like it's not needed any more and won't work with the current hybrid architecture
- Create separate, RWX volume for PFE (and the projects that require it, i.e Liberty & spring)
  - Liberty and Spring projects would need to mount this volume instead
- API needed to ensure the docker registry and repository list are set in PFE
- Concerns about network latency and NFS
  - Not necessarily a todo, but need to see how well the hybrid changes handle when NFS is used
```

**Comment by tetchel** [comment]
linking to the local issue https://github.com/eclipse/codewind/issues/483

**Comment by tobespc** [comment]
closing as these have been addressed in other issues
