### ISSUE TITLE
Remove sections of the appsody troubleshooting now that appsody is locally installed

### ISSUE THREAD

**Issue by sghung** [eclipse/codewind#511]
For 0.4.0, we bundle the appsody binary as part of the codewind install and call it from the local OS when doing appsody init (instead of in the docker container). There are a few troubleshooting sections in appsody that can be removed. However, let the appsody codewind team verify these are okay before removing. Not all the troubleshooting has been fixed, just certain parts. The appsody codwind team will do the initial assessment before assigning to ID.

**Comment by sishida** [comment]
@sghung Could you please let me know which of the following sections need to be removed from Appsody Troubleshooting (https://www.eclipse.org/codewind/troubleshooting.html#appsody-with-codewind)?
- Node.js and Swift templates go from the starting state and then to the stopped state by default
- A project build error appears after you create an initial project
- An Unknown error appears on line one of the pom.xml file
- Classpath warnings appear or the application classes are not on the classpath
- Starting in debug mode results in failure to attach the debugger
- Appsody mount errors on Windows Enterprise
-  Attempts fail to attach the debugger
Thank you!

**Comment by sghung** [comment]
After researching "Appsody mount errors on Windows Enterprise" some more, this section cannot be removed, as it can still happen. As a result, it looks like none of these sections can be removed so I will close this issue. In the future, when appsody removes the mounting, the Windows case may be resolved and I will open a new issue to remove that doc item then.
