### ISSUE TITLE
Ensure topic <Codewind on VS Code - Tutorials> is up to date

### ISSUE THREAD

**Issue by MelHopper** [eclipse/codewind#516]
The codewind extension UI has been modified since the original content for the topic was developed. 

Update the tutorial to align with the updated Codewind extension UI.

**Comment by micgibso** [comment]
@sishida I'll take this please

**Comment by micgibso** [comment]
[vsc-tutorial.zip](https://github.com/eclipse/codewind/files/4287049/vsc-tutorial.zip)

Topic no longer in TOC, but was in source. Attached and removed from source.
