### ISSUE TITLE
Clarifications to "Setting up a Codewind-ready install of Che" file

### ISSUE THREAD

**Issue by beccabau** [eclipse/codewind#518]
"Setting up a Codewind-ready install of Che" (https://www.eclipse.org/codewind/installoncloud.html) could benefit from clarifications:

- Are the PV/NFS prereqs on OpenShift the same as on ICP?
- Should we link from the Codewind doc to these docs? https://docs.openshift.com/enterprise/3.1/install_config/persistent_storage/persistent_storage_nfs.html (NFS)
https://docs.openshift.com/enterprise/3.1/install_config/persistent_storage/persistent_storage_glusterfs.html (glusterfs)

It might make sense to remove "set up the ClusterRole" section from the Prereqs, since it's only applicable to ICP as a prereq (OpenShift requires it at a later step). 
Having helm already installed would be a good thing to include in Prereqs, though. It's not automatic on ICP, and I don't think OpenShift includes it in the initial install, either. 

We also have all these headers:
- Setting up OKD and OpenShift
- Setting up other Kubernetes
-IBM Cloud Private: Set the ClusterImagePolicy

But we only talk about how to set up on ICP and OKD/OpenShift. Are keeping "other Kubernetes" (and ICP below) for AWS/Google Cloud, etc? It seems weird to have it now, since we only talk about the two types for now.

fyi @sishida

**Comment by johnmcollier** [comment]
@beccabau FYI, I went through and updated the install docs to be simpler / more Kube generic, hopefully that addresses most of your concerns

**Comment by sishida** [comment]
@beccabau Becca, when you get the chance, could you please look at John's updated doc at https://www.eclipse.org/codewind/installoncloud.html and let us know if this issue is good to close or if you'd like any more changes? Thank you!

**Comment by beccabau** [comment]
Yep, the flow of the docs makes sense and it's much simpler. Thanks!
