### ISSUE TITLE
Review new Rogue Cloud doc updates: adding support for Codewind to Rogue Cloud

### ISSUE THREAD

**Issue by jgwest** [eclipse/codewind#519]
I have updated Rogue Cloud to support Codewind, with most of that work being updates to the Rogue Cloud documentation. Just like with Microclimate, I have written up step-by-step instructions on how to import the game client into Codewind.

If you are interested in reviewing the documentation updates, here are the changes:

#### Documentation can be found in:
https://github.com/microclimate-dev2ops/rogue-cloud/tree/master/docs

#### New files:
Developing-Eclipse-on-Codewind.md 
Developing-VisualStudioCode-on-Codewind.md

#### Minor tweaks to existing files:
Developing-CodingNextSteps.md 
Developing-LibertyDevTools.md
Developing-Text-Editor.md
GettingStarted.md
README.md
Updating-To-Latest-Client-Code.md

#### PR where the documentation changes were made:
https://github.com/microclimate-dev2ops/rogue-cloud/pull/33

**Comment by sishida** [comment]
@jgwest I have reviewed the Rogue Cloud changes and created the following pull requests:

- For Developing-CodingNextSteps.md: https://github.com/microclimate-dev2ops/rogue-cloud/pull/37
- For Developing-Text-Editor.md: https://github.com/microclimate-dev2ops/rogue-cloud/pull/38
- For Updating-To-Latest-Client-Code.md: https://github.com/microclimate-dev2ops/rogue-cloud/pull/39
- For GettingStarted.md: https://github.com/microclimate-dev2ops/rogue-cloud/pull/40
- For Developing-LibertyDevTools.md: https://github.com/microclimate-dev2ops/rogue-cloud/pull/41
-

**Comment by jgwest** [comment]
Thanks Sarah, looks great! I have merged all PRs, and taken a couple additional action items based on comments in the PRs.

**Comment by sishida** [comment]
Thanks a bunch, @jgwest! It's nice to have this big issue closed! 😄
