### ISSUE TITLE
Codewind Guides: Develop Microservices in Docker with customizable templates

### ISSUE THREAD

**Issue by micgibso** [eclipse/codewind#524]
Develop Microservices in Docker with customizable templates

- (use Rogue Cloud in samples in each section of guide)
- Tell the story around developing microservices using manually created templates

From Tim: Is the purpose of this to talk about how you can customize the new project templates to share with the team. i.e. what the enterprise architect Champ personna does? If so that's fine, but I don't think it should be one of our first few guides - we should start by getting out several for developers first.

**Comment by j-c-berger** [comment]
@sishida I can work on this one, thanks!

**Comment by micgibso** [comment]
This has been superseded; new guides and guide proposals are meeting this requirement, closing.
