### ISSUE TITLE
Codewind Landing Page: Assess and action recommendations from review July 2019

### ISSUE THREAD

**Issue by MelHopper** [eclipse/codewind#526]
Summary: As a team of Design and ID, assess the review of the codewind.dev Landing page and decide which recommendations need actioning.

A review of the Codewind Landing Page codewind.dev was instigated in July 2019. 

This issue will track assessment of the review and any actions coming out of the internal review. 

See the following internal IBM Epic for the review document, playback and takeaways from the 1st review meeting https://github.ibm.com/dev-ex/dev-ex-planning/issues/936_

**Comment by micgibso** [comment]
@sishida I'll take this please
