### ISSUE TITLE
Codewind Guides: Develop applications in Docker containers for Kubernetes

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind#527]
**Note:** I am moving this issue from another repo to this repo. I have copied information and comments from the previous repo here:

**Originally posted in the previous issue by @micgibso on June 10, 2019:**

Develop applications in Docker containers for Kubernetes
- What is container & inner loop development?
- Getting started
- Create a new project
- Create an application template 
- Build your applications and check build status
- Commit your project to GitHub

**Originally posted in the previous issue by @bsgantt on June 11, 2019:**

I'm adding notes from an email discussion to this issue so that the feedback doesn't get lost. Here's the outline for developing applications in docker containers:

Develop applications in Docker containers for Kubernetes

Develop applications in Docker containers for Kubernetes
What is container & inner loop development?
Getting started
Create a new project from a template 
Build your applications and check build status
Commit your project to GitHub

Here's feedback on the outline from above:

- some of the high-level steps should likely be changed, e.g. not clear why there are two 'create' sections, and 'build and check status' doesn't sounds like a top-level section to me.

- we could also include developing containerized apps, starting with an existing app. this task is related enough that we could include this content in this guide, especially because sections within guides are self contained.

- debugging is a broad topic. but are there easy, debugging tips that we can provide that novice developers might encounter?

**Originally posted in the previous issue by @micgibso on June 20, 2019:**

Link to current draft of guide: https://github.ibm.com/dev-ex/landing-pages/blob/master/docs/codewind/Developing%20applications%20in%20Docker%20containers%20for%20Kubernetes.md

**Comment by j-c-berger** [comment]
I can take this issue.

**Comment by j-c-berger** [comment]
@micgibso Given that this issue was opened in June, is it obsolete? In the past several weeks, we've changed directions and generated new ideas for Codewind guides, so I wanted to confirm if this issue were still relevant before beginning much work on it.

**Comment by micgibso** [comment]
@j-c-berger Yes, this issue is obsolete and can now be closed. 
@sishida If you could do the honours and close it out, that would be great, thank you.
