### ISSUE TITLE
'Installing and Using Codewind on Kubernetes' prerequisites and tag tweaks

### ISSUE THREAD

**Issue by jgwest** [eclipse/codewind#528]
John C agreed to handle this one. 

The 'Installing and Using Codewind on Kubernetes' page (https://www.eclipse.org/codewind/installoncloud.html) needs a few tweaks:
- Under prerequisites, we are referencing IBM Cloud Private (and I _believe_ all the numbered steps should have 'Set up the Cluster Role as a parent', rather than the OpenShift note)
- Steps that ask the user to clone the `codewind-che-plugin` repo should instead have them clone the tag of the most recent release (0.2), since changes are going into c-c-p for newer releases.
- I think the following should be a link? `Alternatively, the install script at https://github.com/eclipse/codewind-che-plugin/tree/master/setup/install_che can be used instead.` (and presumably this also needs to target a specific tag)

**Comment by johnmcollier** [comment]
@jgwest I've gone through and updated the install docs for Codewind on Che to be simpler and more Kube-generic, can you go through it and see if you have any more concerns?
