### ISSUE TITLE
Unable to use Nodejs profiler with appsody applications in vscode

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#533]
From https://github.com/eclipse/codewind-node-profiler/issues/5

@csantanapr commented on [Mon Sep 23 2019](https://github.com/eclipse/codewind-node-profiler/issues/5)

Using VSCode Codewind node.js profiler with appsody app it doesn't highlights the code with profiling metadata

Steps to reproduce:
- create appsody app
```
appsody init nodejs-express
```
- Add app to codewind workspace
- Right click on app select `Open Performance Dashboard`
- Run a Load Test
- Verify files are generated in root directory
```
tree load-test                                 
load-test
├── 20190923221512
│   ├── metrics.json
│   └── profiling.json
├── 20190923221649
│   ├── metrics.json
│   └── profiling.json
└── config.json
```
- Open `app.js` go to line 3 and 4
```
const app = require('express')()

app.get('/', (req, res) => {
  res.send("Hello from Appsody!");
});

module.exports.app = app;
```

Problem:
No performance/profiling metada shows up

I think it doesn't work because the profile file `load-test/###/profiling.json` has the file path starting in `/project/user-app/app.js` and the `/parent/user-app` doesn't exist in the appsody root directory for the app locally in vscode
```
      {
        "self": 1702,
        "parent": 1701,
        "file": "/project/user-app/app.js",
        "name": "app.get",
        "line": 3,
        "count": 3
      },
```
The root of the appsody app only contains `app.js` and `package.json`

---

@csantanapr commented on [Mon Sep 23 2019](https://github.com/eclipse/codewind-node-profiler/issues/5#issuecomment-534333689)

I tried replacing `/project/user-app/app.js` with `/app.js` in all the `profiling.json` files, and I still don't get any metadata when open app.js and hover the mouse or put the cursor on lines 3 or 4

**Comment by tobespc** [comment]
This has never been tested with appsody.  Its only been tested with vanilla node apps as it was written before appsody came along.

**Comment by seabaylea** [comment]
I've hit the same problem. 

Essentially it looks like the issue for appsody apps is that the profiler assumes that the project runs in the `/app` directory inside the container (so it strips off `/app` from the start of all of the file urls in the profiling data). In appsody the directory it runs in is more variable. For the `Nodejs-express` stack it runs in `/project/user-app`.

If I go through the profiling data and replace `/app` with `/project/user-app` it works (interesting I had to replace all the path entries for given file).

Note as a side issue, after profiling and opening the `profiling.json` fileI found I had to restart VS Code to get any highlighting to work.

**Comment by csantanapr** [comment]
Ah restarting VSCode, I didn’t try that after I replaced the paths

**Comment by hhellyer** [comment]
The problem is here:
https://github.com/microclimate-dev2ops/microclimate-ls-node-prof/blob/master/server/src/modules/ProfilingManager.ts#L78
We have to map the path of the profiled file in the container to the path of the same file in the users source tree. Previously we assumed the container path would always be `/app` based on the non-appsody NodeJs template.

We need to know where the source code ends up inside the container. This is a problem the debugger has as well and inside the generated appsody express project we have a `.vscode/launch.json` file which contains:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Appsody: Attach node debugger",
            "type": "node",
            "request": "attach",
            "port": 9229,
            "remoteRoot": "/project/user-app",
            "localRoot": "${workspaceFolder}",
            "protocol": "inspector"
        }
    ]
}
```
This provides the information the debugger needs to correctly map between source files inside and outside the container set in the remoteRoot and localRoot fields. Using the debugger configuration might be an acceptable solution when displaying the profile data inside VSCode.

**Comment by tobespc** [comment]
removing the bug label as this is an enhancement as appsody is currently unsupported in node-profiler

**Comment by malincoln** [comment]
@tetchel pls verify and close. Thanks

**Comment by tetchel** [comment]
works now, neato
