### ISSUE TITLE
Codewind CLI commands fail if not run in a specific order

### ISSUE THREAD

**Issue by stalleyj** [eclipse/codewind#539]
**Description:**
As we develop the installer into a cli, it has become apparent that some of the Codewind CLI commands require you to run install and start before they can be run successfully.  It doesn't seem right for a CLI to behave this way and I don't think we should be chaining commands together. We should return a sensible message informing the user of this. 

**Steps to reproduce:**
For example:-
codewind-installer templates ls gives
2019/09/25 14:15:12 Error getting templates: "Get http:///api/v1/templates?projectStyle=Codewind&showEnabledOnly=false: http: no Host in request URL"

**Comment by tetchel** [comment]
same as https://github.com/eclipse/codewind/issues/462

**Comment by jcockbain96** [comment]
Yes, #462 is one of the examples of this. I'd imagine the one that will be hit most. I am about to PR against the CLI for that one specifically, but then this suggests we should give proper instructions for any command run without having a PFE container running.

**Comment by jcockbain96** [comment]
Looking at the commands as-is I can see the following requirements:

- Catch the above case and others that require a pfe backend to be up. i.e `Codewind is not running, call install and then start` 

- #462 handles start without the tagged images installed.

- `Stop` & `stop-all` currently will reply `stopping containers` even if none exist. This could be `No Codewind containers running`. 

- `remove` will likewise reply 'Removing cw images` if none are there.

**Comment by stalleyj** [comment]
I'm closing this issue as we have fixed some of the commands and will raise separate items for anything left to do.
