### ISSUE TITLE
Use template source name and description coming from templates.json file

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind#541]
See issue #123 and PR #426

**Comment by tetchel** [comment]
Out of the 3 default repositories, only one has a `name`. Do we want to make this change without those?

```
  {
    "url": "https://raw.githubusercontent.com/kabanero-io/codewind-templates/master/devfiles/index.json",
    "description": "The default set of templates for new projects in Codewind.",
    "enabled": true,
    "protected": true,
    "projectStyles": [
      "Codewind"
    ],
    "name": "Default templates"
  },
  {
    "url": "https://github.com/kabanero-io/collections/releases/download/v0.1.2/kabanero-index.json",
    "description": "Kabanero Collections",
    "enabled": false,
    "projectStyles": [
      "Appsody"
    ]
  },
  {
    "description": "Appsody Stacks - appsodyhub",
    "url": "https://github.com/appsody/stacks/releases/latest/download/incubator-index.json",
    "enabled": true,
    "protected": true,
    "projectStyles": [
      "Appsody"
    ]
  },
```

**Comment by jopit** [comment]
Why couldn't we use the name and description if it exists, else do what we currently do?

**Comment by tetchel** [comment]
what do we put in the "name" column of the table for the ones that don't have names

**Comment by jopit** [comment]
@makandre are you going to be able to update the data provided by the appsody extension to include a name and a better description.

**Comment by jopit** [comment]
@tetchel We either put the description or we put something indicating there is no name.

**Comment by jopit** [comment]
Maybe we should open a PR against https://github.com/kabanero-io/collections to provide a templates.json file

**Comment by makandre** [comment]
I can try to bring it up with appsody team.  But they would need to understand why we need them to host another file. They had expressed concerns before about hosting non-appsody related files (such as devfiles).  Can you post a screenshot for where the information in templates.json is used?

I was also under the impression that templates.json was optional and things work without one.

**Comment by jopit** [comment]
@makandre where does the current description come from?  Presumably the name should come from the same "place"

**Comment by makandre** [comment]
@jopit here: https://github.com/eclipse/codewind-appsody-extension/blob/master/templatesProvider.js#L55

**Comment by jopit** [comment]
@makandre so if the description is provided by the appsody extension, then the extension should also provide the name, and it's up to the extension as to where the name comes from.

**Comment by makandre** [comment]
I see. Ok, maybe I got confused and thought that the name/description had to come from a templates.json file.  If that's not a requirement, then I could easily change it to be:

```js
repos.push({
  name,
  description: `Appsody Stacks - ${name}`,
  url: url
});
```

`name` is what we get back from appsody CLI's output:
```
NAME       	URL                                                                            
*appsodyhub	https://github.com/appsody/stacks/releases/latest/download/incubator-index.yaml
```

Or some variation of that, but basically I only have `NAME` and `URL` from the CLI to work with

**Comment by jopit** [comment]
@makandre  would it make sense if part of the description could point the user to https://appsody.dev/ ?

**Comment by tetchel** [comment]
[kabanero data](https://github.com/eclipse/codewind/blob/master/src/pfe/portal/modules/Templates.js#L32)

**Comment by tetchel** [comment]
https://github.com/eclipse/codewind/issues/552 related

**Comment by tetchel** [comment]
Right now if a user adds their own template source, they will be prompted to enter a description, but not a name, for it. The [backend code](https://github.com/eclipse/codewind/blob/master/src/pfe/portal/routes/templates.route.js#L49) won't accept a `name`. How should we deal with this?

1. Allow that POST endpoint to accept a `name` too, and prompt the user for a name and optionally a description
2. Remove the description prompt, and accept that all user sources will have no name or description (!)
3. Leave it as-is, and accept that all user sources will have a description, but no name
4. Do 2, but also write up proper documentation telling the user how to create a `templates.json` alongside their `index.json` so that they can have both a name and description but never have to enter anything into the IDE.

**Comment by deboer-tim** [comment]
IMHO the ideal flow would be something like:
 - User enters a URL
 - We automatically pick up the name and description from there (if it has them)
 - We allow the user the option to edit or add any missing info before saving

To me this keeps a simple/fast default flow, allows the user to enter any missing info/supports repos that don't include the info, and still allows them to give a more meaningful local name if they want.

**Comment by malincoln** [comment]
@jopit @tetchel pls set release to "0.5.0".  Thanks
