### ISSUE TITLE
Generated client test doesn't follow integration test conventions

### ISSUE THREAD

**Issue by NottyCode** [eclipse/codewind#549]
The generated test client is called `src/test/java/org/openapitools/api/DefaultApiTest.java` however it is not a unit test, it is an integration test which means that it needs a running server to work. These should be run by the failsafe plugin, not surefile and its convention standard convention to name the feature so it would be called `src/test/java/org/openapitools/api/DefaultAPiIT.java`

**Comment by keithchong** [comment]
The test name and its contents are created based on their templates.  Looks like for this one, the class name is:

public class {{classname}}Test

The Codewind extension does not control the name or the test contents.  (The Java test looks bare and has several TODOs.   The user needs to do some coding to get the tests running and with a running server).

@sghung, please return this as as-designed.   

Note the default org.openapitools.* Java package CAN be customized via a codegen option.   But that option is not currently supported by the Codewind Eclipse wizard or VS Code extension, and it should be treated as an enhancement.
