### ISSUE TITLE
Improve Codewind template source metadata

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#552]
Currently:
```
    "description": "The default set of templates for new projects in Codewind.",
    "name": "Default templates"
```

Current proposals for 0.5.0:
- Codewind
  - Name: Codewind templates
  - Description: Use Codewind to create projects in your choice of IDE.
- Appsody (from Appsody tech lead)
  - Description: Use Appsody to rapidly develop cloud ready applications built on the best practices of sharable technology stacks.
- Kabanero
  - Description: Kabanero, an open source project, brings together open source technologies into a microservices-based framework. Kabanero builds cloud native applications ready for deployment onto Kubernetes and Knative.

@thisguy-1 @sishida @deboer-tim

**Comment by tetchel** [comment]
These strings are sourced from:
https://github.com/kabanero-io/codewind-templates/blob/master/devfiles/templates.json

**Comment by sishida** [comment]
@tetchel: Thanks for bringing this to our awareness. ID should be reviewing all strings, messages, etc.

**Comment by tetchel** [comment]
We need a description for the Appsody and Kabanero template repositories too

**Comment by sishida** [comment]
@j-c-berger Could you please contact someone from the Kabanero team to provide the Kabanero description? If you would like to see more of the context for where this description will be used, just let me know. 👍 

I will see if I can find someone to contact for the Appsody description.

**Comment by j-c-berger** [comment]
Thanks @sishida I'll get to it.

**Comment by sishida** [comment]
@tetchel What is the deadline for this work? Do we want this work done by 0.5.0 or a different time? Thanks! 👍

**Comment by tetchel** [comment]
It would be good to have this done for 0.5

**Comment by sishida** [comment]
Reached out to an Appsody tech lead today to get more info about the Appsody template source description.

**Comment by j-c-berger** [comment]
Please see my description below for the Kabanero source template. I am happy to make any changes if anyone sees fit. Just let me know, thanks:

Kabanero, an open source project, brings together open source technologies into a microservices-based framework. Kabanero builds cloud native applications ready for deployment onto Kubernetes and Knative.

**Comment by sishida** [comment]
@makandre Here's the short description for the Appsody source template:
Use Appsody in Codewind to develop applications with sharable technology stacks.

What do you think? I remember you mentioned stacks are an important point, so I was sure to mention those. Please let me know if you have suggestions for additions/changes. I'll also send the description to Kyle C. Thanks!

**Comment by makandre** [comment]
@sishida It sounds ok to me, thanks.

**Comment by thisguy-1** [comment]
> Please see my description below for the Kabanero source template. I am happy to make any changes if anyone sees fit. Just let me know, thanks:
> 
> Kabanero, an open source project, brings together open source technologies into a microservices-based framework. Kabanero builds cloud native applications ready for deployment onto Kubernetes and Knative.

I think it should include something about end to end. Like that it includes Tekton Pipeline runs. Also what is it opptomized for? Like what is the value add? If it's sitting next to appsody source and the ODO source, how am I reassured that I made the right choice, or why my Champ picked this over other collections. We dont have to go into detail. But couldnt what is said above be said about any other source/style?

**Comment by j-c-berger** [comment]
@thisguy-1 thanks for the suggestions. I'll work on revising it and implementing your feedback.

**Comment by tetchel** [comment]
I see that Jake is working on the kabanero description, and Sarah has helped source an Appsody one, but how about Codewind as in the original issue description? :)

**Comment by sishida** [comment]
@tetchel Thanks for reminding us that we need a Codewind description, too. 😆Other than Codewind being the default set of templates, is there anything else we want to highlight about it or say about it to set it apart from the others?

Right now I'd just say something like, "Use the default Codewind templates to create projects in Codewind."

**Comment by thisguy-1** [comment]
I'm not sure we are supposed to use the word default. Because technically these are IBM stacks, that would show favoritism towards one technology over another... can anyone confirm?

**Comment by j-c-berger** [comment]
Revised Kabanero description, and I'm happy to change it again. However many times it takes!: 

Use Kabanero to generate Appsody stacks that provide frameworks for Codewind to develop code, then Tekton pipelines to deploy this code onto OpenShift cloud. Kabanero ensures a smooth end-to-end process among Appsody, Codewind, and Tekton. 

@sishida if we don't want to use "default" maybe it could be something like, "Use the Codewind plugin to create projects in your choice of IDE"?

**Comment by sishida** [comment]
Instead of "default"...would it be fair/valid to say that the Codewind templates would be good for those just starting out or new?

For example..."Use Codewind to create projects with an IDE. If you're not sure where to start, check out the Codewind templates." ?

**Comment by deboer-tim** [comment]
I've been trying to respond to this for an hour, but keep getting interrupted and there are more comments to respond to. :)

The Codewind templates were mostly created by IBMers (us) and match the pattern used by the IBM public cloud, but we've done our best to remove IBM runtimes and have a variety of open source runtimes & content. We support multiple styles and don't want to play favourites or default to these, nor are these significantly better for new users.

For Kabanero, I'd lean toward the fact that they are governed/curated collections that include end-to-end support including Appsody stack and Tekton pipeline for deployment on OpenShift.

I don't love each description starting with 'Use X to ...'. It would also help to see all of these together to ensure they're similar - maybe we could iterate in a box note?

**Comment by sishida** [comment]
Iterating for source descriptions in Box note: https://ibm.box.com/s/xwzsg4qpcje7v0ylftzg5sfqn89vdh47

**Comment by malincoln** [comment]
@sishida @j-c-berger just confirming this will complete by Thurs?  Thanks

**Comment by sishida** [comment]
@malincoln The work is completed for 0.5.0. However, we plan to continue to work on the issue beyond 0.5.0 and would prefer not to close the issue until we come up with a more permanent solution. Thank you!

**Comment by malincoln** [comment]
@sishida that sounds good.  I saw the release set to 0.5.0 so just wanted to confirm.  Thanks!

**Comment by j-c-berger** [comment]
Sarah and I were working more on the templates for Appsody, Codewind, and Kabanero. Here's what we came up with. We all can discuss these more in our Plugin meeting tomorrow, Oct. 30th. 

**Appsody**
Shareable technology stacks for development of cloud ready applications. 

**Codewind**
Extension to develop in containers with an IDE or language of your choice. 

**Kabanero**
Curated collections with end-to-end support, including Appsody stacks and Tekton pipelines, for deployment on OpenShift.

**Comment by thisguy-1** [comment]
It's looking better. For Codewind, however, you're describing the extension, not the project templates. All of these sources provide the same thing (plus or minus features) only that they are executed differently and optimized for different purposes. 

In an ideal world we'd be able to describe these different sources like we do Cars or Computers. For example (my bad attempt at this analogy) :

COMPUTER (a machine that computes) = PROJECT TEMPLATE (technology that does... what?)
APPLE = STYLE (Appsody does that in what way and is different from other styles why?)
LAPTOPS, DESKTOPS = SUBTYPE (NodeJS)
MONITOR, MOUSE, UNLIMITED WARRANTY = Tekton Pipeline, App Nav, End to end support

Something like that. Point I'm tryin to make is that if I would to have a Dell Source and an Apple source, I can still compare and understand what I prefer. Might say APPLE source has COMPUTERS optimized for editing film, designing and developing software and come as LAPTOPS and DESKTOPS and includes unlimited warranty and a mouse, but not monitors.

**Comment by sishida** [comment]
See https://github.com/eclipse/codewind/pull/620#event-2767943488 for descriptions that went into 0.6.0.
