### ISSUE TITLE
Intermittent build failures due to automated tests

### ISSUE THREAD

**Issue by rajivnathan** [eclipse/codewind#553]
**Description:**
The PR tests run as part of the Jenkins build are failing intermittently.

master build:
https://ci.eclipse.org/codewind/job/Codewind/job/codewind/job/master/111/console

PR build:
https://ci.eclipse.org/codewind/job/Codewind/job/codewind/job/PR-544/2/console

**Comment by ssh24** [comment]
I have also been seeing this intermittently on some of my PRs.

**Comment by tobespc** [comment]
first failure is this


18:35:14  
18:35:14    29 passing (47s)
18:35:14    15 pending
18:35:14    1 failing
18:35:14  
18:35:14    1) Batch enabling repositories
18:35:14         1 repo
18:35:14           "before all" hook for "returns 207 and sub-status 200 for each subrequest when batch disabling 1 repos":
18:35:14       Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/genie.codewind/jenkins-agent/workspace/Codewind_codewind_master/test/src/API/templates/enableRepo.test.js)
18:35:14

**Comment by tobespc** [comment]
2nd failure

 1) Batch enabling repositories
16:55:53         1 repo
16:55:53           "before all" hook for "returns 207 and sub-status 200 for each subrequest when batch disabling 1 repos":
16:55:53       Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/genie.codewind/jenkins-agent/workspace/Codewind_codewind_PR-544/test/src/API/templates/enableRepo.test.js)
16:55:53    
16:55:53  
16:55:53    2) Batch enabling repositories
16:55:53         multiple repos
16:55:53           "before all" hook for "returns 207 and sub-status 200 for each subrequest when batch disabling 2 repos":
16:55:53       Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/genie.codewind/jenkins-agent/workspace/Codewind_codewind_PR-544/test/src/API/templates/enableRepo.test.js)
16:55:53    
16:55:53  
16:55:53    3) Template API tests
16:55:53         GET /api/v1/templates
16:55:53           ?showEnabledOnly=
16:55:53             true
16:55:53               should return only templates from enabled repos:
16:55:53  
16:55:53        AssertionError: expected 26 to equal 17
16:55:53        + expected - actual
16:55:53  
16:55:53        -26
16:55:53        +17
16:55:53        
16:55:53        at Context.<anonymous> (src/API/templates/templates.test.js:101:44)
16:55:53        at process._tickCallback (internal/process/next_tick.js:68:7)
16:55:53

**Comment by tobespc** [comment]
with the change in to increaase the timeouts of the tests, the stability has been improved

**Comment by ssh24** [comment]
@tobespc I don't think the stability improved. The last builds in master has failing consistently and blocking the latest image to be pushed up to dockerhub https://ci.eclipse.org/codewind/job/Codewind/job/codewind/job/master/

**Comment by rajivnathan** [comment]
Seeing this again on master and PR builds

eg.
https://ci.eclipse.org/codewind/job/Codewind/job/codewind/job/master/159/consoleFull

**Comment by rwalle61** [comment]
Related to https://github.com/eclipse/codewind/issues/1611

@james-wallis @jcockbain you're more up to date on this than I am - I know we've skipped a lot of failing tests, so is the build still failing?

**Comment by james-wallis** [comment]
The API template tests should have been refactored to prevent this from happening - they should set which repositories to use in the tests rather than relying on what is set in PFE. I think this issue can be closed. 

If we have an issue again it would be good to have a new issue as all the Jenkins links are dead.

**Comment by tobespc** [comment]
as of today, we do not have intermittent failures to closing
