### ISSUE TITLE
Provide user-friendly directions for adding own templates or template index

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#559]
https://github.com/eclipse/codewind/issues/540#issuecomment-535492577

We have to provide proper directions to walk users through adding their own templates.

**Comment by sishida** [comment]
Note: We are not aiming to get this completed by 0.5.0.

**Comment by sishida** [comment]
I'm just trying to wrap my head around this issue...

I'm thinking we could update this page with the instructions for adding your own templates/template index? https://www.eclipse.org/codewind/mdt-vsc-usingadifferenttemplate.html

New section title: Adding your own Codewind templates
New section brief description: Create your own template to use Codewind with the framework of your choice.

1. Create a folder for your template in the [`codewind-templates/devfiles` repository](https://github.com/kabanero-io/codewind-templates/tree/master/devfiles). Include the name of the framework in the name of the new folder.
2. Add `devfile.yaml` and a `meta.yaml` files.
    - The `devfile.yaml` file needs to include...
    - The `meta.yaml` file needs to include...
3. Also update the `codewind-templates/devfiles/index.json` file with information about your new template. Include the following information:
```
  "displayName":"The name of the framework that the template applies to",
  "description":"A description of the template",
  "language":"The programming language used for the template",
  "projectType":"",
  "location":"The GitHub URL of the folder where your template resides",
  "links": {"self":"The URL of the devfile.yaml of your template" }
```

Do the templates/template index instructions connect to the Template Source Manager page? What do we need to do on this page for the new template?
1. In the Codewind view project tree, right-click **Projects (Local)**. A menu appears.
2. Click **Manage Template Sources**. The **Template Source Manager** appears.
3. Click **Add New**.

**Comment by micgibso** [comment]
@sishida I'll take this please.

**Comment by micgibso** [comment]
For Eclipse, https://www.eclipse.org/codewind/mdteclipseusingadifferenttemplate.html

**Comment by micgibso** [comment]
@sishida Work completed and approved on PR #208 above, please close this issue, thx!
