### ISSUE TITLE
lodash needs to be at least 4.17.13

### ISSUE THREAD

**Issue by cccanderson** [eclipse/codewind#56]
The GitHub Security assessment is reporting that there are 4 places where an older (and vulnerable) version of lodash are specified:

 src/pfe/portal/package-lock.json 
src/performance/dashboard/package-lock.json 
src/pfe/file-watcher/server/package-lock.json 
src/initialize/package-lock.json

These need to be moved up to at least 4.17.13.  (But note that lodash is not directly pulled in, so other prereqs that require lodash need to have their versions raised too).

**Comment by tobespc** [comment]
closing as now resolved
