### ISSUE TITLE
Buildah RPMs get removed every 3-6 weeks

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#566]
The version of buildah that's bundled with CentOS is too low for us to use (bugs with certain docker builds, no way to log in to a registry, etc), so we pull down an RPM to install instead (from https://download-ib01.fedoraproject.org/pub/fedora/linux/updates/30/Everything/x86_64/Packages/b/). This allows us to install a newer version of buildah onto CentOS

The problem is that the mirror (and other RPM mirrors I've found), remove the buildah RPM whenever a new version is released, causing our builds to fail until we update the PFE dockerfile to pull down the newer RPM. This tends to happen roughly every 4-6 weeks, and can be fairly disruptive. This has happened 3 times since we've opened sourced (and twice before that):
- https://github.com/eclipse/codewind/pull/565
- https://github.com/eclipse/codewind/pull/93
- https://github.com/eclipse/codewind/pull/214

Do we want to instead host a mirror of the buildah RPM that we want to use (perhaps on the Eclipse site?) and download it from there instead to avoid this issue? And then only update the buildah RPM say every quarter? Would there be any issues hosting our own mirror of the RPM?

Other alternatives:
- Add logic to the PFE Dockerfile to parse and find the latest buildah RPM, and always use it
    - Reduces reproducibility and makes it hard to say at a glance what version of buildah we're using
- Switch from CentOS to Fedora:
    - Fedora has a much newer buildah version than CentOS, and we could just install it with `dnf install buildah ...` without dealing with RPM mirrors
    - Fedora is the upstream source of RHEL/CentOS so should be relatively easy to switch

**Comment by johnmcollier** [comment]
Another alternative is to base PFE off of the `quay.io/buildah/stable:v1.11.1` docker image. It's based on fedora and would give us a consistent, official, and easy-to-upgrade version of buildah.

**Comment by jopit** [comment]
JohnC to investigate basing on quay.io/buildah/stable:v1.11.1
- is there anything in the buildah image that we don't want
- how frequently are new images created for new versions of buildah
- which fedora version is the image based on

**Comment by maysunfaisal** [comment]
Happened again on Oct 15 😭 

see
https://github.com/eclipse/codewind/pull/678
https://github.com/eclipse/codewind/issues/690

This needs to be higher on the priority list IMO

**Comment by maysunfaisal** [comment]
I think codewind-workspace6ab2ca0thh2gbdjh-6fbf4ddf5c-b7lmd is a much more stable repo and has a history of all the buildah rpms.

I was notified of this repo by the buildah folks. I have since switched to it on Master and 0.5.0 branch

**Comment by johnmcollier** [comment]
@maysunfaisal Can this be closed? I don't think we've had any issues with buildah since you switched the RPM url.
