### ISSUE TITLE
Make project deployments 'owned' by their direct PFE parent deployment.

### ISSUE THREAD

**Issue by hhellyer** [eclipse/codewind#568]
At the moment when projects are deployed in kubernetes environments (currently just che) their deployments are modified to add an 'ownerReferences' section that references the che deployment. This has to be passed through in an environment variables so that the PFE container can set it on the deployments it creates. The PFE deployment also references the Che deployment. This is all done so that when Che is removed PFE and the project deployments are cleaned up.

In remote (hybrid) mode we won't necessarily have a Che deployment. For this reason it would be better if the project deployments referenced the PFE deployment and the PFE deployment in turn referenced the Che deployment - if one exists.

This will remove the need to pass through different owner references to the projects depending on how they are deployed. The script that sets the owner references should be able to find the name and UID for it's own deployment at runtime so we won't need the env vars. This will also simplify the deployment code in `codewind-che-sidecar/deploy-pfe`.

The script that modifies the project deployments can be found here:
https://github.com/eclipse/codewind/blob/0566c58713087a6db4a9c19ff4e870faeb902295/src/pfe/file-watcher/scripts/kubeScripts/modify-helm-chart.sh#L28

**Comment by johnmcollier** [comment]
I can tackle this.

Should be a small change to `modify-helm-chart.sh` and the deploy-pfe code to accommodate this, and will work for both Che and Hybrid.

**Comment by tobespc** [comment]
@johnmcollier @elsony Can this be picked back up to work on?  It would complete the uninstall story

**Comment by johnmcollier** [comment]
@hhellyer @markcor11 In hybrid, is the PFE deployment labeled with a unique ID? In Che, we use `codewindWorkspace`. We need to be able to look up the parent deployment with a unique ID, in case there are multiple Codewind deployments in one namespace.

**Comment by markcor11** [comment]
yes they still include the workspaceID label.  The operator uses the NAME of the deployment which should be unique in the namespace.

**Comment by johnmcollier** [comment]
@markcor11 Would the Codewind resource PFE UID change if the pod is restarted? I don't have an instance up right now, so can't quickly check

**Comment by markcor11** [comment]
Yes it does change : 

```
$ kubectl get pods -l app=codewind-pfe,codewindWorkspace=jane1 -o jsonpath='{.items[0].metadata.uid}'
0d82b52e-c753-49af-acff-fc47f30e4d7a                                                                              

$ kubectl delete pod -l app=codewind-pfe,codewindWorkspace=jane1 
pod "codewind-pfe-jane1-675bf84bb5-j4xxp" deleted

$ kubectl get pods -l app=codewind-pfe,codewindWorkspace=jane1 -o jsonpath='{.items[0].metadata.uid}'
657a5542-ac75-4650-80dc-f3b2f5528c90                                                                             
```

**Comment by markcor11** [comment]
I just ran through the owner chain from a project pod to see who owns what. 

Results of the owner chain are : 

```
project pod -> 
  project replica set -> 
    project deployment -> 
      codewind PFE deployment 
```

As a sanity check I deleted the codewind-pfe deployment and saw the projects do terminate: 

```
$ k delete deployment codewind-pfe-jane1 
deployment.extensions "codewind-pfe-jane1" deleted
$ k get pods
NAME                                                        READY   STATUS        RESTARTS   AGE
codewind-gatekeeper-jane1-b8bb585cd-pghhf                   1/1     Running       0          6h12m
codewind-keycloak-devex001-84d96dc688-t8sb8                 1/1     Running       0          3d9h
codewind-operator-598b9b659-6bmjm                           1/1     Running       0          3d9h
codewind-performance-jane1-78c99bb78d-ktsnm                 1/1     Running       0          6h14m
codewind-pfe-jane1-675bf84bb5-mmpbs                         1/1     Terminating   0          37h
cw-appsodyopenlib-56d61e80-9a6c-11ea-852e-f9497b4fd-sb4gd   1/1     Terminating   0          36h
```

That also means if a user were to do `$ kubectl delete codewind jane1` that would will remove the codewind deployment, all codewind pods and also the projects in the same way so I think our owner chains are good.

When the operator deploys a new Codewind it still sets the OWNER_REF_UID and OWNER_REF_NAME environment variables however the difference is : 

Che : OWNER_REF_UID and OWNER_REF_NAME point to Che controlled workspace
Codewind-Operator: OWNER_REF_UID and OWNER_REF_NAME point to the operator controlled Codewind deployment 

@hhellyer @stalleyj are we ok to close this given that Kube does appear to be able to garbage collect projects in both codewind-operator and che environments ?

**Comment by stalleyj** [comment]
All working as expected so closing.
