### ISSUE TITLE
Disambiguate similar templates from different repos

### ISSUE THREAD

**Issue by deboer-tim** [eclipse/codewind#570]
**Codewind version:** 0.4
**OS:** Mac

**Description of the enhancement:**
When you have two or more repos configured, sometimes they have very similar template names, sometimes even duplicate (or near-duplicate) ones. We should include the repo name in these cases to help distinguish them.

**Proposed solution:** 
I've seen a more elaborate design from Guy, but the simpler initial fix is to add the template repo name to the template list. IMHO we should only do this when it is needed to keep things clean and simple in the default case - e.g. repo name is only included when there are two identical names or when you have more than one repository configured.

**Comment by tetchel** [comment]
This data would have to be provided by the backend, first. The source name is not included in the current response from the /templates endpoint.

```
  {
    "label": "Appsody Eclipse MicroProfile® template",
    "description": "Eclipse MicroProfile on Open Liberty & OpenJ9 using Maven",
    "language": "java",
    "url": "https://github.com/kabanero-io/collections/releases/download/v0.1.2/incubator.java-microprofile.v0.2.11.templates.default.tar.gz",
    "projectType": "appsodyExtension",
    "projectStyle": "Appsody"
  },
```

**Comment by jopit** [comment]
Opened #608 for the portal work

**Comment by jopit** [comment]
This item is complete
