### ISSUE TITLE
Clean up plugin providers

### ISSUE THREAD

**Issue by deboer-tim** [eclipse/codewind#571]
**Codewind version:** 0.4
**OS:** Mac

**Description:**
Some of the plugins still list IBM as a provider, and on 0.3 at least one plugin (filewatcher) didn't have a valid name. Worth checking all the feature + plugin manifests to make sure they're clean and consistent.

**Comment by eharris369** [comment]
This was fixed a while ago so closing.  Please re-open if you disagree.
