### ISSUE TITLE
Error starting Codewind 0.4 on Eclipse 4.13.0

### ISSUE THREAD

**Issue by muralidharchavan** [eclipse/codewind#575]
**Codewind version:** 0.4
**OS:** Mac Mojave 10.14.6

**Che version:**
**IDE extension version:**
**IDE version:** 4.13.0
**Kubernetes cluster:**

**Description:**
After upgrade from Codewind 0.3 to 0.4, Codewind does not start and throws up the error as shown in the image.
<img width="362" alt="Error" src="https://user-images.githubusercontent.com/25784779/65742552-454d5b00-e10e-11e9-90ca-3776aecc9351.png">

**Steps to reproduce:**
- Upgrade Codewind version from 0.3 to 0.4
- Update Eclipse IDE version from 4.11 to 4.13

**Workaround:**

**Comment by tetchel** [comment]
Hi, it looks like Docker has mismatched the identifier for your codewind_network. Can you:

1. Run `docker network remove codewind_network` in a terminal
2. Right-click Codewind in the Codewind Explorer view  and select Uninstall.
3. Right-click the Codewind item again and select Start. This will recreate the network and reinstall the images.

**Comment by muralidharchavan** [comment]
Hi @tetchel . Thanks for responding. I followed the steps you mentioned but I am still getting the same message.

**Comment by tetchel** [comment]
That's frustrating - At that point I would restart the Docker engine (the "Restart" menu item), and if that still failed, I would have to do a system prune `docker system prune -a`. Be warned that the system prune will delete all your stopped containers, images, networks, and similar (read the output before confirming).

**Comment by muralidharchavan** [comment]
@tetchel Thank you very much for the fix. After doing a system prune, Codewind 0.4 is working fine on my Eclipse IDE. We can close this issue now.
