### ISSUE TITLE
Debugging in Appsody MicroProfile template not working

### ISSUE THREAD

**Issue by naveenkaratekid** [eclipse/codewind#577]
**Codewind version**:0.4.0 Build 201909191538
**OS: MacOS Mojave 10.14.6 and Windows 10**

**IDE extension version:0.4.0**
**IDE version: VSCode 1.38.1**

**Description:**
Debugging does not work for Appsody MicroProfile template in VSCode in Mac or Windows. Getting error saying 
```
Failed to attach debugger to appsody-mp.
```
![unable to attach debugger for appsody microprofile VSCode](https://user-images.githubusercontent.com/19738071/65791665-3081bf00-e130-11e9-84f8-2f80110fa60c.PNG)

**Steps to reproduce:**
1. Create new Appsody Microprofile project
2. Build the project
3. Once project status shows ```Running [Build succeeded]```, right-click on the project, and click ```Restart in Debug Mode```.
4. After a short while, project throws an error saying it cannot attach the debugger

**Comment by tetchel** [comment]
https://github.com/eclipse/codewind/issues/300 ?

**Comment by naveenkaratekid** [comment]
Oh yea, my bad @tetchel. Thanks for reminding me.
