### ISSUE TITLE
Can project name be asked before project type ?

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#580]
When creating a new project, I am invariably forgetting to select the type first but instead start typing in the name of the project I want to create first ?   Is there a reason why the flow is project type - project name and not project name - project type ?

This is using vscode

**Comment by tetchel** [comment]
I like having the message in the project name box say "enter a name for your new \<type\> project", but other than that i have no real preference about this

**Comment by tetchel** [comment]
@thisguy-1 what do you think

**Comment by thisguy-1** [comment]
I don't think we should change this. My best guess is that a user would want to know what they are doing before they decide to name it. In user testing, there hasn't been any mention of this being confusing.
