### ISSUE TITLE
Appsody: docker volume mount for m2 cache

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#583]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description of the enhancement:**

Because of https://github.com/eclipse/codewind-appsody-extension/pull/24 appsody projects are not mounting host's m2 cache anymore.  The downside of this is when we restart the project container, we are essentially starting with a blank cache

**Proposed solution:** 

Appsody CLI added a [`--docker-options`](https://appsody.dev/docs/using-appsody/cli-commands/#appsody-run) flag.  Can it be leveraged to run appsody projects with a docker volume mount to `/mvn/repository`?

**Comment by richard-trotter** [comment]
+1 When developing a new library and testing with a sample app, the library may be installed to the local maven repo for test. When run from command line, appsody includes a '-v' parameter to mount '$USER/.m2' as '/mvn'. Codewind does not, and the library is not accessible from within the container.

**Comment by jgwest** [comment]
FWIW mounting the Maven cache (using a bind mount with `-v` ) into the Appsody container is [inherently unsafe](https://github.com/eclipse/codewind-appsody-extension/issues/2#issuecomment-521890329)  and [breaks enterprise Windows users](https://github.com/appsody/appsody/issues/24).

**Comment by richard-trotter** [comment]
As a naive user, it seems strange to me that I get different behavior running Appsody from Codewind than from command line. 

If there is a concern about this for Codewind users, how is it not also a concern for those using Appsody from command line?

However that concern is addressed, the solution shouldn't break users trying to test a library under development.

**Comment by jgwest** [comment]
Yes, I have brought up both issues with the Appsody folks (on the linked issues); I would argue that this is ALSO an issue with the way they are implementing their CLI, eg anytime you are sharing Maven M2 cache between two independent build processes (eg IDE and CLI container), you will hit issues of m2 cache corruption.

(Opinions are my own and do not necessarily reflect the views of either the Appsody team or the Codewind Appsody folks 😄 )

**Comment by ebullient** [comment]
We have worked through the IDE/CLI thing with .m2 directories -- it is a vanishingly slim usecase, as we are not (in most of the project operations) publishing back to the maven repository (most operations are mvn verify, test, or package, not mvn install).

Sharing the m2 repository across all projects you're working on is _normal_ for any person using maven or gradle over the last gazillion years. The single potential source of conflicts would be over native-compiled binaries... which is much more common with node than with Java.

**Comment by jgwest** [comment]
> We have worked through the IDE/CLI thing with .m2 directories -- it is a vanishingly slim usecase, as we are not (in most of the project operations) publishing back to the maven repository (most operations are mvn verify, test, or package, not mvn install).

As per the original linked comment, I don't think this is only limited to install. The three scenarios I originally identified as cases where this would be an issue: initial source file changes of a project and/or initial build, invocations of mvn commands causing arbitrary plugin download, and changes to dependencies in pom.xml. All would trigger an `mvn` process call in both the Appsody container and in the IDE.

> The Liberty runtime is capable of similar change detection, which means we could pursue codewind launching the java appsody containers in a way that avoids them invoking maven operations when changes are detected, which is a better way to resolve the problem than removing the host mount

For this case, you mainly need a way to prevent _the IDE_ from building (in the Codewind case: Eclipse, VSCode, and soon IntelliJ) at the same time as Appsody, as that is what is calling the Maven process. In Eclipse we may be able to do this with a workbench lock that blocks m2e, not sure on the others. (But I _think_ @eharris369 investigated this on another issue and found it to be infeasible).

> Sharing the m2 repository across all projects you're working on is normal for any person using maven or gradle over the last gazillion years. 

Sharing the m2 repository _is_ old (hence why the bugs we flagged in that original issue were many years old), but what is NOT old is having two independent build processes (IDE, and Appsody) both calling different independent Maven processes, with both triggering at the same time. In a traditional development setup, one is only using one build tool at a time: eg they are EITHER delegating the build to the IDE, OR they are running `mvn package` from the CLI, not both, and not both simultaneously.

(@ebullient)

**Comment by ebullient** [comment]
We had talked w/ the appsody team about an option to suppress the on-change action. IMO, it is easier to launch appsody with a command line option than it is to mess with the IDE. Just let existing tools do what they do, and make sure appsody can behave well in the flow.
