### ISSUE TITLE
Add 'name' attribute to POST /template/repositories

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#586]
See https://github.com/eclipse/codewind/issues/541#issuecomment-535591155 and https://github.com/eclipse/codewind/issues/541#issuecomment-535658027

We want the user to able to set a `name` attribute on their template sources, outside of the `templates.json`, just like they can currently with `description`.

Also, both `name` and `description` should be optional, since they can be fetched from `templates.json` instead.

**Comment by jcockbain96** [comment]
Taking this, could I be assigned?

**Comment by jcockbain96** [comment]
Is this to follow that second comment? So we read the name from the template.json, and then allow a user to edit the name. 

Or do we just want to allow a 'name' parameter in the body of the API which will then be overwritten if a name does exist in the template.json?

**Comment by tetchel** [comment]
I suppose if a name or description is set in the `repository_list`, then it should override the one in `templates.json` for that user.
