### ISSUE TITLE
[ODO] Expose ingress/route for applications

### ISSUE THREAD

**Issue by GeekArthur** [eclipse/codewind#590]
Currently the IDE gets the application endpoint by using code here: https://github.com/eclipse/codewind-vscode/blob/c74b24924aae167eb5b3f0b6b9dbb24a4329c839/dev/src/codewind/project/Project.ts#L529. This logic won't work for odo project since odo project uses odo cli to build not our codewind build engine, it will return ingress something like http://odotest-app-eclipse-che.9.42.10.79.nip.io (ingress pattern would be http://<component name>-<application name>-<host>/<context-root>) to let user access the odo project. In order to make it consistent for all project types and support future udo, we can expose an ingress/route for both odo apps, and all other apps.

Proposed solution:

We already discussed the design in Turbine team meeting:

Turbine side:
Get the project ingress then add the ingress as appBaseURL field to the <project ID>.inf when creating the project. The sample appBaseURL field would be something like this:

"appBaseURL": "http://cw-odotest-app-eclipse-che.9.42.10.79.nip.io"

IDE side:
Calls Portal API the get the content of <project ID>.inf then parse the content to get the value of appBaseURL, then append context root to the appBaseURL value to form the full URL to access the project in the browser.
Note: If appBaseURL field doesn't exist then IDE still goes to the same logic as before to access the project in the browser so that this change won't affect other project types. (Currently this change only applies to odo project type, other projects type may migrate to this design soon)

**Comment by johnmcollier** [comment]
@jingfuwang I believe https://github.com/eclipse/codewind/issues/459 covers this issue

**Comment by GeekArthur** [comment]
@johnmcollier Yes, can make this issue as sub-issue for reference. I can make this one more about odo, but odo and udo can share the same idea.

**Comment by GeekArthur** [comment]
#459

**Comment by tetchel** [comment]
> then append context root to the appURL value to form the full URL to access the project in the browser.

turbine knows the contextroot, should turbine add the context root so the app url is one that will actually work?

Otherwise, perhaps we should name it to `appBaseURL`.

**Comment by GeekArthur** [comment]
We decide not to add context root since context root can be updated by user, so we can name it to `appBaseURL`, let me update the design above

**Comment by eharris369** [comment]
Eclipse PR: https://github.com/eclipse/codewind-eclipse/pull/334

**Comment by GeekArthur** [comment]
Turbine PR: https://github.com/eclipse/codewind/pull/601
ODO extension PR: https://github.com/eclipse/codewind-odo-extension/pull/4

I test the change on Turbine side, `appBaseURL` is successfully added as new field in the <project ID>.inf file.
```
[root@codewind-workspacelbxixnzo5l5ot71g-7d9948745c-dx5gs .projects]# cat d72ea940-e54e-11e9-863f-19f06cdf2c2c.inf 
{
  "projectID": "d72ea940-e54e-11e9-863f-19f06cdf2c2c",
  "name": "odotest",
  "language": "nodejs",
  "extension": {
    "name": "odoExtension",
    "path": "/codewind-workspace/.extensions/codewind-odo-extension",
    "version": "0.4.0",
    "description": "odo extension for Codewind",
    "projectType": "odo",
    "commands": [],
    "detection": ".odo",
    "templates": null,
    "config": {}
  },
  "host": "codewind-workspacelbxixnzo5l5ot71g-che-eclipse-che.9.42.10.79.nip.io",
  "ports": {
    "exposedPort": "undefined",
    "internalPort": "8080"
  },
  "workspace": "/projects/",
  "directory": "odotest",
  "infLockFlag": true,
  "locOnDisk": "/codewind-workspace/odotest",
  "loadTestPath": "/codewind-workspace/odotest/load-test",
  "projectType": "odo",
  "buildLogPath": "/codewind-workspace/.logs/odotest-d72ea940-e54e-11e9-863f-19f06cdf2c2c/docker.build.log",
  "state": "open",
  "autoBuild": true,
  "buildStatus": "success",
  "detailedBuildStatus": " ",
  "projectWatchStateId": "c43a1fcaea337e6205cc6be05bb86d3f",
  "logs": {
    "build": {
      "origin": "workspace",
      "files": [
        "/codewind-workspace/.logs/odotest-d72ea940-e54e-11e9-863f-19f06cdf2c2c/odo.build.log"
      ]
    },
    "app": {
      "origin": "workspace",
      "files": [
        "/codewind-workspace/.logs/odotest-d72ea940-e54e-11e9-863f-19f06cdf2c2c/odo.app.log"
      ]
    }
  },
  "metricsAvailable": false,
  "appStatus": "started",
  "lastbuild": 1570046262976,
  "location": "/codewind-workspace/odotest",
  "validationStatus": "success",
  "validationResults": [],
  "isHttps": false,
  "podName": "cw-odotest-app-1-hqv6l",
  "appBaseURL": "http://cw-odotest-app-eclipse-che.9.42.10.79.nip.io",
  "detailedAppStatus": "Pinging http://:8080/health and http://:8080/",
  "appErrorStatus": "Failed to ping application due to timeout."
}
```

**Comment by GeekArthur** [comment]
Verified, access app through ingress works perfect! Thanks IDE team.
