### ISSUE TITLE
Enable a sub-topic on the Getting started

### ISSUE THREAD

**Issue by micgibso** [eclipse/codewind#591]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description of the enhancement:**

Enable a sub-topic immediately beneath the Getting Started page. Current behaviour under test is that you cannot navigate directly back to the tiled GS page without clicking back in the browser. 

(Travis, one for you)

**Comment by travis1111** [comment]
Thanks I will look into it
