### ISSUE TITLE
Improve write-ups for Codewind marketplace entries

### ISSUE THREAD

**Issue by rtaniwa** [eclipse/codewind#596]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description of the enhancement:**

The Codewind marketplace entries should highlight the value props and feature/function that Codewind provides at the top of the marketplace entries. Our Eclipse marketplace entry has more of this, but less overall content (no screen shots, install information, prereqs etc). VS Code has more supplementary information, but is light on a solid description of what benefits you would get from using Codewind. 

**Proposed solution:**

**Comment by sishida** [comment]
Joseph Kim updates both Eclipse and VS Code pages. An ID writer should work with him to make the page updates.

**Comment by tetchel** [comment]
The VS Code page is the README which you are already familiar with, Sarah. It updates on the marketplace whenever we release.

https://github.com/eclipse/codewind-vscode/blob/master/README.md

**Comment by sishida** [comment]
@tetchel Thank you for the clarification! I see the README content in the marketplace now.

**Comment by sishida** [comment]
Maybe pull in some of the content from the https://www.eclipse.org/codewind/ home page that addresses the Codewind benefits?

**Comment by sishida** [comment]
@rtaniwa Hi, Rob, I brought up this issue in the Plugins/IDEs/Editors meeting today, and the team and I were wondering if you could please let us know more details about what you'd like the updated marketplace pages to look like/what sort of content to include?

For example, would you like more marketing-like content, such as how on the Codewind.dev home page we highlight Codewind benefits but not necessarily instructions?

Or have you seen an existing marketplace page that you really liked that we could use as a reference? Thank you!

**Comment by j-c-berger** [comment]
@sishida I can work on the Eclipse part of this issue.

**Comment by bsbyrd1** [comment]
@rtaniwa What specific marketplace pages were you thinking of in your original feedback? For example, are these the marketplace pages that need to be updated:

Eclipse: https://marketplace.eclipse.org/content/codewind
VS Code: https://marketplace.visualstudio.com/items?itemName=IBM.codewind

**Comment by rtaniwa** [comment]
@bsbyrd1 yes those are the ones I am referring to. 

@sishida I suppose to start with we should probably have some consistency across Codewind extensions. The Eclipse marketplace entry for Codewind has a nice write-up right at the top that talks about the value props and then follows with a list of features. I think that is important, because if you think of how someone might find the plugin...it could just be from a search on the marketplace. So if they happen to find us that route, there should be something that draws them in to wanting to use our tools. The VS Code extension write up is a bit sparse...but as mentioned maybe we can steal from our Eclipse writeup.  A few nice examples of other plugins are https://marketplace.visualstudio.com/items?itemName=GoogleCloudTools.cloudcode or https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack

Ideally our write-ups would be almost the same, with possibly some small adds for IDE specific characteristics (ie. VS Code command palette). When we get to IntelliJ we will have another marketplace, so I think getting some consistent look and feel for all of them makes sense.

**Comment by sishida** [comment]
@rtaniwa, Thank you for your reply and clarifications. :)

ID team, It sounds like a good place to start would be to update the introduction of the VS Code Marketplace page to be more like the Eclipse page. We can update the VS Code Marketplace page by updating the `codewind-vscode` repo README: https://github.com/eclipse/codewind-vscode/blob/master/README.md.

**Comment by sishida** [comment]
I have created https://github.com/eclipse/codewind-vscode/pull/274 to make the VS Code Readme/Marketplace page look more like the Eclipse page. Would @rtaniwa and @tetchel please review?

**Comment by sishida** [comment]
**Update:** The VS Code README improvements are merged: https://github.com/eclipse/codewind-vscode/pull/274#pullrequestreview-320183955

**Comment by sishida** [comment]
@rtaniwa, @josephca, @eharris369, What do you think of this writeup for the Eclipse Marketplace page (https://marketplace.eclipse.org/content/codewind#group-details)?

# Codewind for Eclipse
Codewind for Eclipse provides tools to help build cloud-native, containerized applications from Eclipse, regardless of which runtime or language you use. Rapidly create an application from a template project and launch, update, test, and debug in Docker containers on the desktop.

For more information, see [the Codewind website](https://www.eclipse.org/codewind/).

## Why use Codewind?
- Get started with templates or samples that you can use to quickly create and deploy applications that run in containers.
- Create containerized applications in languages that you're already familiar with. Codewind supports popular runtimes.
- Pull in your existing applications and use Codewind to help get them cloud ready.
- See code changes reflected in your containerized application almost instantaneously. The Codewind advanced inner loop manages your application updates efficiently.
- Develop in containers without feeling like you're developing in containers. Development flow within the IDE feels the same as traditional application development.

## Features
- Create new containerized projects or add existing ones.
- View your containerized projects, including the application and build status.
- Debug Microprofile/Java EE, Node.js, and Spring applications.
- Access application, build, and container logs in the Output view.
- See validation errors in the Problems view.
- Open a shell session into an application container.
- Toggle the project auto build setting and manually initiate project builds.
- Open your application or the application monitor in a browser.

## Getting started with Codewind
For more information, see [Getting started with Codewind for Eclipse](https://www.eclipse.org/codewind/mdteclipsegettingstarted.htmll).

## Contributing
Submit issues and contributions:
- [Submitting issues](https://github.com/eclipse/codewind/issues)
- [Contributing](https://github.com/eclipse/codewind-eclipse/blob/master/CONTRIBUTING.md)
- `[Development Builds](need link)`
- `[Jenkins](need link)`

## Developing
To develop and debug Codewind for Eclipse, see [Developing Codewind for Eclipse](https://github.com/eclipse/codewind-eclipse/blob/master/README.md#developing-codewind-for-eclipse).

**Comment by tetchel** [comment]
we're going to have to update both marketplace entries for 0.7 with the new remote features, btw.

**Comment by sishida** [comment]
@tetchel I think I'll create a separate issue for 0.7.0 marketplace updates. I would like to close this issue soon instead of making it bigger to encompass more and more things. :)

**Comment by rtaniwa** [comment]
This looks good @sishida. Agree we should get this work done, and then look at add content for remote as that will impact both marketplace entries as well as the landing page. I think that is a value prop we will want to call out directly on the main page.

**Comment by eharris369** [comment]
Looks good.  I can add some screenshots as well.  We only get 4.

**Comment by sishida** [comment]
Brought this issue up during the Plugins/IDEs/Editors meeting today. Erin might be able to make the updates to the Eclipse marketplace page itself. We'll keep checking in as we progress.

I also opened this issue for adding the 0.7.0 remote updates to both of the marketplace pages: https://github.com/eclipse/codewind/issues/1336

**Comment by sishida** [comment]
@josephca and @j-c-berger to work on updating the Eclipse marketplace page.

**Comment by sishida** [comment]
I have updated the Eclipse Marketplace page: https://marketplace.eclipse.org/content/codewind

Now that both Eclipse and VS Code pages are updated, I will close this issue.

@eharris369 If you would like me to add the screenshots for Eclipse, please feel free to send me the images when you are ready. I will then open a new issue just for adding those. 😃

**Comment by eharris369** [comment]
@sishida I can add them myself but thanks for offering!
