### ISSUE TITLE
Doc: Support odo project style via extension

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind#605]
Documentation for odo.

**Comment by GeekArthur** [comment]
Need documentation to let user add additional rules for accessing OpenShift resources to support ODO extension feature.
Reference issue: https://github.com/eclipse/codewind/issues/452

**Comment by GeekArthur** [comment]
I draft up a simple instruction for adding additional rules for accessing OpenShift resources to support ODO extension feature, we can polish this later for users.

Steps to add additional rules:
1 In your home directory, run the following command to clone the ODO extension repository
```
git clone https://github.com/eclipse/codewind-odo-extension
```
2 Login to your OpenShift/OKD cluster
3 Go into `~/codewind-odo-extension/odo-RBAC` then run the following commands to add additional rules for ODO extension
```
kubectl apply -f codewind-odoclusterrole.yaml
kubectl apply -f codewind-odoclusterrolebinding.yaml
```

**Comment by GeekArthur** [comment]
@sishida Please let me know the usual documents/places that need to be documented when we release new feature, we can work on that together, thanks

**Comment by j-c-berger** [comment]
I'm happy to work on this issue, thanks!

**Comment by sishida** [comment]
ODO is a CLI like Appsody. I don't know if we want to add a new doc section for CLIs or what, but here's where Appsody is mentioned in our doc files so far:
- https://www.eclipse.org/codewind/mdt-vsc-overview.html
- https://www.eclipse.org/codewind/troubleshooting.html

**Comment by j-c-berger** [comment]
@GeekArthur thank you for including the steps you've written. You mentioned " adding additional rules" for accessing OpenShift resources. Are there additional steps I should I include? If so, are they written somewhere for me to access? 

Do you or your team also have an idea as to where these steps will be published? Thanks!

**Comment by GeekArthur** [comment]
@j-c-berger No additional steps, but we may polish the instruction later on (eg. grammar, terminology, etc). Currently it's only under this issue, from Sarah's Appsody list, seems like we can publish the instruction I wrote in ODO extension repository: https://github.com/eclipse/codewind-odo-extension.

General idea regarding documentation locations:
- Since ODO extension only supports Kube case, we need add ODO extension specific stuff here: https://www.eclipse.org/codewind/installoncloud.html
- Need to add troubleshooting for ODO extension here: https://www.eclipse.org/codewind/troubleshooting.html

**Comment by GeekArthur** [comment]
@sishida I think same idea as Appsody, we don't need add a new doc section

**Comment by j-c-berger** [comment]
@GeekArthur , thank you for getting back to me. I'll revise the ODO extension repo's README and include the instructions there. I'll have these changes done by early next week, before the release  on the 17th. 

Also, do you want ID to make changes or fixes to the troubleshooting page?

**Comment by GeekArthur** [comment]
@j-c-berger This is the latest update from me:
Need to update three places:
- [ ] Codewind for Eclipse Che section on Landing Page (Need ID team enhance this section then add ODO extension introduction content there, enhancement issue against ID team is here: https://github.com/eclipse/codewind/issues/646)
- [ ] Troubleshooting section on Landing Page (Currently no troubles, will come back to this once we have troubles)
- [ ] ODO extension repository (I can finish that today or tomorrow, will let ID team review once it's finished)

**Comment by GeekArthur** [comment]
@j-c-berger Also you can monitor `ODO Extension Status Report` here: https://ibm.box.com/s/ropq993qfmc7yqu8kz78lig9jtlrayw4, let me know if you have access issue

**Comment by j-c-berger** [comment]
@GeekArthur , thank you. No, I cannot access the `ODO Extension Status Report` When I click the link, I am told the file is unavailable to me. 

I will review the extension repo once you have finished it, and once I have access to the extension status report, I'll use that to keep myself up to date. 

I'll also work on the ODO extension introduction (#646)

**Comment by j-c-berger** [comment]
@GeekArthur , to confirm, this issue is for 0.5.0 release whereas #646 is for 0.6.0, correct?

**Comment by GeekArthur** [comment]
ID team tag #646 to 0.6.0, but it would be best ID team can finish #646 in 0.5.0 then we can easily add ODO extension/project as our introduction feature to the landing page. Otherwise we can't add our ODO content into the Overview section.

**Comment by j-c-berger** [comment]
@GeekArthur , understood, thank you!
