### ISSUE TITLE
Include template source name in response from the /templates endpoint

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind#608]
This is needed to support https://github.com/eclipse/codewind/issues/570 where @deboer-tim wants us to allow the user to distinguish between templates with the same name that come from different sources.

**Comment by jcockbain96** [comment]
Picking this up, could you assign me @tobespc?

**Comment by jcockbain96** [comment]
I've added this as part of that PR, it will return `source: {repoName}` if a repoName exists in the repository list. https://github.com/eclipse/codewind/pull/602/files#diff-395b0c2bf7f52e9b39e91bb2d4991d15R379
