### ISSUE TITLE
Provide name for Kabanero template source

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind#609]
Now that we have names as well as descriptions for template repositories, we need the name attribute added to the kabanero repo information returned by portal from here:
https://github.com/eclipse/codewind/blob/master/src/pfe/portal/modules/Templates.js#L32

The simplest thing is to change what is currently the description to the name and then provide a better description.

This is needed to complete issue #541

**Comment by jopit** [comment]
Doc involvement is to provide a better description for the description attribute, not to document this issue in the codewind docs.

**Comment by jcockbain96** [comment]
Picking this up, could you assign me @tobespc?

**Comment by jcockbain96** [comment]
I've updated that default list - https://github.com/eclipse/codewind/pull/602/files#diff-395b0c2bf7f52e9b39e91bb2d4991d15R34.

**Comment by tetchel** [comment]
Looks like it is done here https://github.com/eclipse/codewind/issues/552#issuecomment-537899836

**Comment by tetchel** [comment]
We are supposed to use the description from [here](https://github.com/eclipse/codewind/issues/552#issuecomment-537899836), not `The default set of templates from Kabanero Collections`

**Comment by jcockbain96** [comment]
Cool, that was my placeholder so can raise another PR

**Comment by micgibso** [comment]
Related to #552, same content will resolve both.
