### ISSUE TITLE
Express Node.js template/vanilla app fails, on fresh Codewind 0.4.0 vscode install

### ISSUE THREAD

**Issue by NikCanvin** [eclipse/codewind#611]
**Codewind version:** 0.4.0
**OS:** Mac

**Che version:** n/a
**IDE extension version:** 0.4.0
**IDE version:** vscode 1.38.1
**Kubernetes cluster:** n/a

**Description:**
I did a clean install of Codewind, via the vscode plugin
Click to create vanilla Express Node.js App from template 
> the app builds, runs, I can see it running in 'docker ps'
> but the app won't dsiplay in the brower (note: the port number for the App in 'docker ps' does not match the port number shown in VSCode for the app)

**Steps to reproduce:**
1. fresh install of codewind 0.4.0 in VSCode on Mac
2. click to create Express Node.js App

**Workaround:** 
> click to create a Open Liberty App (that works)
> after creating a Liberty App, then new Node.js Apps start working!

**Comment by tobespc** [comment]
this also happens on master branch, setting to stop ship

**Comment by markcor11** [comment]
I was able to reproduce this (only with NodeJS).  After stopping "myFirstNodeApp" and doing a new rebuild, the newly rebuilt container and port matched.

**Comment by maysunfaisal** [comment]
![Screen Shot 2019-10-09 at 12 28 59 PM](https://user-images.githubusercontent.com/31771087/66500962-80497a00-ea90-11e9-9c4a-333ab09d88ef.png)
![Screen Shot 2019-10-09 at 12 30 36 PM](https://user-images.githubusercontent.com/31771087/66501025-9ce5b200-ea90-11e9-979c-a474cd378d9c.png)


I dont see it on latest master

**Comment by yangcao77** [comment]
I could not reproduce it on 0.4.0 or latest master.

**Comment by rajivnathan** [comment]
@markcor11 @tobespc Any idea how we can reproduce this?
@elsony FYI

**Comment by NikCanvin** [comment]
Andy Watson also could NOT reproduce this ... however, he has a theory..

Could be that when the Network is TOO SLOW, then when creating Node.js project for the first time in a new Codewind install, all the packages MAY NOT BE FULLY downloaded before Codewind attempts to start/run the app in a container. We suspect the container is healthy enough to run, but the app stack in it may be incomplete.

Andy says he's seen other/similar unusal behaviour when DEMO'ind Codewind at conferences, where network speeds are poor.

**Comment by yangcao77** [comment]
If the network is too slow to start the app, then the status should be `stopped`, instead of showing a wrong port in the UI. 

I will take a look into the Turbine code to see if there is any code could potentially causing this issue. 
In the mean time, @NikCanvin can you switch the logging level to `trace` and attach the pfe log? So we can investigate more on this issue. 
```
PUT

http://localhost:9090/api/v1/logging

{
  "level":"trace"
}
```

**Comment by yangcao77** [comment]
@NikCanvin A couple more questions, are you using VSCode to open the app? 
What is the app status shown in VSCode? is it `running` or `stopped`?
Have you tried using the port numebr shown in `docker ps`? Are you able to connect to the app?

**Comment by NikCanvin** [comment]
I used vscode to open the app in my browser (using the port number shown in docker ps)
in VSCode it shows as running
docker ps appears normal, the app container + port number all look normal

**Comment by AndyRWatson** [comment]
Just reproduced this on new machine/build and verified by @tobespc .   

The app appears to be bound to localhost and not to 127.0.0.1.    

In my scenario codewind reports my app running on 127.0.0.1:32768 and the docker ps output also confirms.   If I access the app from a browser using localhost:32768 all is working as expected, but not when using 127.0.0.1:32768

**Comment by maysunfaisal** [comment]
@AndyRWatson can you check your `/etc/hosts` file? Probably `127.0.0.1:` is not mapped to `localhost`..

**Comment by yangcao77** [comment]
@NikCanvin If you use browser to open the app with the port number shown in `docker ps`, can you open the app?

Since some of us has trouble reproducing the issue, do you agree do remove the `stopship` label? We can mark it as a hot issue instead.

**Comment by malincoln** [comment]
@NikCanvin pls confirm whether this is still stopship.  Thanks

**Comment by NikCanvin** [comment]
Agree not stop ship, as this is not a REGRESSION in this release ..
.. however, we need to understand fix this, it is HOT

3 Hursley people have reproduced this, and it's a first out-the-box experience for codewind + Express/node app .. so we could lose new users at the first hurdle!

@yangcao77 .. I tried the port number from 'docker ps', issue remained
will aim to reproduce and get logs..

**Comment by NikCanvin** [comment]
spoke with Toby again today ..

here's evidence of the Node issue:
![Screenshot 2019-10-17 at 09 53 57](https://user-images.githubusercontent.com/16120163/67001207-1dc82d80-f0d1-11e9-9028-4b2c75585db9.png)

here's my /etc/hosts file:
<img width="536" alt="etc:hosts" src="https://user-images.githubusercontent.com/16120163/67001251-2fa9d080-f0d1-11e9-9dc5-bcf27f1f3a00.png">

here's evidence of me manually swapping 127.0.0.1 to localhost:
![Screenshot 2019-10-17 at 09 54 27](https://user-images.githubusercontent.com/16120163/67001280-418b7380-f0d1-11e9-9765-6bb93f361826.png)

here's an app log (in case it helps)
[create-first-node-app.docx](https://github.com/eclipse/codewind/files/3738714/create-first-node-app.docx)

..
I manually edited /etc/hosts, to remove the second mention of 127.0.0.1, and rebooted, hoping that it would fix the issue, but after re-boot the /etc/hosts was changed back again.. I'm guessing Docker does this on my machine at start-up..
..
Note this ISSUE does not happen on OpenLiberty/Java apps, so it's not a generic system level issue!

**Comment by yangcao77** [comment]
If I understand it correctly, the initial issue (port number shown in UI does not match the number in docker ps) does not persist any more.
The current issue is 127.0.0.1 cannot be resolved as localhost, is that correct?

**Comment by yangcao77** [comment]
From the screenshot, it looks like the `internalApplicationPort` 3000 and `internalDebugPort` 9229 are somehow map to the same exposed port. 
Turbine runs  same`docker run` cmd for all projects, it uses `-p 127.0.0.1::$DebugPort`, and `-P` will use `0.0.0.0` and the expose port in dockerfile by default. docker will dynamically bind the exposed ports. 
In my machine, it binds to different exposed port. Not sure why docker schedules same host port for different internal port & ip. And not sure why other projects works differently from node. 
```
CONTAINER ID        IMAGE                                              COMMAND                  CREATED             STATUS              PORTS                                                NAMES
f1ff12bba778        cw-testnode-24a3dc00-f110-11e9-a1c7-0395789bccfc   "docker-entrypoint.s…"   About an hour ago   Up About an hour    0.0.0.0:33391->3000/tcp, 127.0.0.1:32972->9229/tcp   cw-testnode-24a3dc00-f110-11e9-a1c7-0395789bccfc
```

**Comment by AndyRWatson** [comment]
I can confirm I have reproduced this issue and my /etc/host looks ok.  other project containers are working ok using 127.0.0.1 so not convinced its an /etc/host issue

**Comment by yangcao77** [comment]
Confirmed that I'm also seeing this issue after update to latest docker (2.1.0.3)

**Comment by yangcao77** [comment]
This is not a Codewind issue. 
I can reproduce this issue with any types of project (tried nodejs and spring) with docker cli. 
`docker build` and `docker run` with both `-p` and `-P`. 

I have created an issue under docker cli git repo: https://github.com/docker/cli/issues/2148

**Comment by rajivnathan** [comment]
Since the issue is with Docker assigning ports for us and there isn't much movement on the issue we're going to investigate setting ports ourselves because this applies to all project types and is likely to be a problem for anyone with newer versions of docker.

**Comment by jgwest** [comment]
I don't believe this is a Docker bug. Docker can listen on the same host port, as long the host port is used by different host network interfaces. So for example (depending on networking configuration), you can listen on localhost and your external IP simultaneously, because these represent different networks from the perspective of the OS.

For example, on Linux, to reproduce,  I wrote a quick app to listen on port 10000 and port 10001 inside a container, then wrapped that app in an image. I then ran the container using this:
```
docker run -p 9.23.20.69:20000:10000  -p 127.0.0.1:20000:10001  -it --rm
```
(where 9.x.x.x is my machine eth0 IP address)

After running this command, I was able to access both internal ports 10000 and 10001, depending on which host network connection I connected to (eg either to 9.x.x.x IP, or localhost):
-  Connecting to 9.x.x.x on port 20000 would connect me to container port 10000
- Connecting to 127.0.0.1 on port 20000 would connect me to container port 10001.

(@yangcao77)

**Comment by rajivnathan** [comment]
@jgwest True, I suppose not technically a bug. But I think the issue for us is we use `127.0.0.1` intentionally so it's not reachable from outside of your local machine but when we allow Docker to decide the mapping with `-P` Docker uses the `0.0.0.0` IP by default. Not sure if we can configure that to be `127.0.0.1` somehow. If we can't then think we'd need to start setting the port mappings ourselves.

**Comment by AndyRWatson** [comment]
I also question its docker as was working for other Projects language templates but failing on node on the same machine

**Comment by yangcao77** [comment]
I tested with spring, it also has the same issue. 
In addition, I was testing use docker cli. So codewind is not involved at all. I'm still seeing the same issue.

**Comment by yangcao77** [comment]
@rajivnathan Do we need the app url to be exposed externally? ( Is `0.0.0.0` required? )
If not, we can use `-p 127.0.0.1::$DEBUG_PORT  -p 127.0.0.1::$APP_PORT`. I would expect docker will allocate different ports since these two `-p` are with same ip.

**Comment by rajivnathan** [comment]
@yangcao77 When port mapping was discussed a while ago we didn't want 0.0.0.0 by default because it'd be reachable from outside of your local machine by default. Your suggestion sounds okay to me.

**Comment by hhellyer** [comment]
@yangcao77 - The change looks like the right thing to do as it should mean any port we open is only accessible locally but when I ran Codewind locally after the merge I got this message:
```
RUNNING DOCKER-COMPOSE IN: /Users/hhellyer/work/codewind/tempest.git 
ERROR: Network "codewind_network" needs to be recreated - option "com.docker.network.bridge.host_binding_ipv4" has changed
```
I had to run `docker network rm codewind_network` before I could start Codewind. This might cause issues when users upgrade. (Should be cleaning up our docker network when we shutdown anyway?)

**Comment by rajivnathan** [comment]
Installer and run.sh changes are now merged. Closing

**Comment by NikCanvin** [comment]
I have not verified this but I can't reopen it (I recommend we keep it open for now)
..
also could/should we change the link in Codewind to app to be 'localhost:<port number>' rather than <ip address>:<port number> ??? 
.. I saw in the docs tutorial it showed 'localhost' not 'ip address' here: https://www.eclipse.org/codewind/mdt-vsc-tutorial.html

**Comment by rajivnathan** [comment]
Reopened. @NikCanvin Can you please verify?

**Comment by NikCanvin** [comment]
trying to verify ... taking latest VSCode extension build ... but so far I can't get a Node app to run on that latest 0.6.0 level .. I'm investigating

**Comment by yangcao77** [comment]
It's because of the difference between `run.sh` and `cwctl`:https://github.com/eclipse/codewind/issues/972#issuecomment-550013575

**Comment by NikCanvin** [comment]
verified this morning, with 172 build
