### ISSUE TITLE
Portal/IDE should handle github redirects for project template repo URLs

### ISSUE THREAD

**Issue by lentheivendra** [eclipse/codewind#614]
**Description:**
When creating a project and choosing a template, if the github repo the template points to has moved (and therefore github redirects to the new url), the Codewind IDE shows error blow, and the indicator for the project creation wizard/process stays up:
Error creating new project: 2019/10/03 17:30:05 unexpected status code: 301 Moved Permanently

Codewind should be able to handle github redirects in this situation.

cc @tetchel

**Comment by tetchel** [comment]
I think it's the installer that has to follow the redirect to the new repo when it downloads the code.

**Comment by tetchel** [comment]
It looks like template sources will have the same problem; 200 only is expected, and the option to follow redirects is not used.

https://github.com/eclipse/codewind/blob/master/src/pfe/portal/modules/Templates.js#L327

`asyncHttpRequest` does not follow redirects, though `asyncHttpDownload` does.

**Comment by jcockbain96** [comment]
Taking this on the CLI side, can I be assigned please?

**Comment by jcockbain96** [comment]
Update on this one: the installer is hitting the `301` status here https://github.com/eclipse/codewind-installer/blob/master/utils/filesystem.go#L123, where it gets the zip URL to download the repo code from. 

There's an open issue on the `go-github` package we use, to include a follow redirects option. https://github.com/google/go-github/issues/1248.

**Comment by jcockbain** [comment]
We're aiming to have this issue resolved for 0.7.0, at the moment waiting to discuss my changes with the github package maintainers.

**Comment by jcockbain** [comment]
My PR has been merged (https://github.com/google/go-github/pull/1336), working on integrating this into `cwctl` now.
