### ISSUE TITLE
Keeping track of links and docs

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind#615]
**Description of the enhancement:**
It would be good to keep track of where we link files. For example, we not only link Codewind Markdown files to other Codewind Markdown files on Codewind.dev, but we also link from the VS Code Codewind extension UI to docs pages on Codewind.dev. If we delete or update a file, it'd be good to know where it's been linked from so that we can remove or edit the link to match.

In addition, it would be good to keep track of files with the same/similar content so that if content is updated in one location, such as Codewind.dev, it is also updated in its corresponding location, such as Kabanero.io.

**Proposed solution:** 
- A spreadsheet/Box Note file?
- Does a tool or program exist that helps organize links?

**Comment by tetchel** [comment]
here's the list of doc pages that VS Code links out to: https://github.com/eclipse/codewind-vscode/blob/master/dev/src/constants/Constants.ts#L21

**Comment by sishida** [comment]
Just a thought: I want everyone to be able to see this list of links, so a Box Note or an attached spreadsheet probably won't be ideal. At the moment, I am leaning towards creating a wiki page in the `codewind-docs` repository. Although tables don't look the best in Markdown, perhaps a list will work...

**Comment by sishida** [comment]
Created wiki page: https://github.com/eclipse/codewind-docs/wiki/List-of-links-and-files-with-similar-content

**Comment by sishida** [comment]
Because we have the wiki page, I am closing this issue.
