### ISSUE TITLE
[odo] [Iterative Dev]Turbine ODO Unit Tests

### ISSUE THREAD

**Issue by maysunfaisal** [eclipse/codewind#619]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description of the enhancement:**

There needs to be unit tests for the ODO Extensions in Turbine for any new functions introduced.

**Proposed solution:**

**Comment by maysunfaisal** [comment]
cc @jingfuwang @lentheivendra

**Comment by GeekArthur** [comment]
Already discussed with @lentheivendra and @ssh24, we only need functional tests for odo and share the unit tests. Close this issue.
