### ISSUE TITLE
Appsody template source is no longer available initially

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#621]
The dynamic Appsody template source is no longer available on a fresh Codewind startup, if `repository_list.json` did not exist or did not contain Appsody previously.

On Codewind startup, the Codewind Default and Kabanero Collections sources are in the repository_list, but Appsody is not, so it does not appear in the initial Template Source Selection prompt, or in the Template Source Manager. (these source their data from `/templates/repositories`).

When the user tries to create a new project, `/templates` is called to fetch the list of templates, which appears to cause the Appsody source to be added, and it is found in the repository_list after that.

Calling `/templates/repositories` should also add the appsody source; not just `/templates`. Either of these may be called before the other, depending on the user actions.

**Comment by makandre** [comment]
I'll take this
