### ISSUE TITLE
Error running status on Windows with latest CLI

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#625]
When I try to run status with the latest CLI on Windows I get:

C:\tmp>cwctl-win.exe status
2019/10/04 16:04:57 {"error":"sec_schema","error_description":"Target deployment not found"}

C:\tmp>echo %errorlevel%
1

Buildinfo for installer I pulled down is:
```
# Build date: 2019-10-04-15:48:31
build_info.url=https://download.eclipse.org/codewind/codewind-installer/master/10
build_info.linux.SHA-1=b8dff94ae0c34b10bee12598c6be75c75bcd4fca
build_info.macos.SHA-1=36ef0885769d4983f2241960077841984e6c0a9a
build_info.win.SHA-1=b46290e00b9322a29936b98cbddbaf6bb9c07e5d
```

Note that I had nothing installed when I ran it (docker images returns empty list).

**Comment by eharris369** [comment]
I forgot to remove deployments.json so this is probably a dup of another issue.

**Comment by tetchel** [comment]
sujeily said she couldn't reproduce this anymore, does it work for you now?

**Comment by eharris369** [comment]
I can still reproduce this.  If I install and start 0.4.0 with the old 0.4.0 installer and then run the new installer I get:
C:\tmp>cwctl-win-2019-10-09-0837.exe status -j
2019/10/09 10:46:43 {"error":"dep_not_found","error_description":"Target deployment not found"}

**Comment by eharris369** [comment]
Zip of the .codewind\config dir which includes the deployment.json:
[config.zip](https://github.com/eclipse/codewind/files/3707995/config.zip)

**Comment by eharris369** [comment]
I installed 0.4.0 using 0.4.0 installer and then ran a 0.5.0 CLI that I knew was broken to make sure the problem was reproduceable this way but apparently that is what causes the problem so the latest installer also failed. Tried again deleting the bad deployments.json and installing a fresh copy of 0.4.0 and then ran latest 0.5.0 CLI and it worked so closing this.
