### ISSUE TITLE
SVT: Runtime error in latest Codewind for VS Code

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#628]
**Codewind version:** 0.5.0
**OS:** macOS Mojave (10.14.6)

**IDE extension version:** 0.5.0
**IDE version:** 1.38.1

**Description:** Runtime error in latest Codewind for VS Code

<img width="443" alt="Screen Shot 2019-10-07 at 10 38 35 AM" src="https://user-images.githubusercontent.com/49531960/66322625-6c671200-e8f0-11e9-9570-3db23c07f632.png">

**Steps to reproduce:**
On Friday, I got the latest Codewind for VS Code (until that date). This morning, I uninstalled that plugin and deleted all the Codewind images from my machine. After that, I proceed to install the latest Codewind for VS Code [(codewind-0.5.0-201910071348.vsix)](https://download.eclipse.org/codewind/codewind-vscode/master/latest/). That was when I received the panic runtime error. After this error appeared, Codewind went into a bad state in the machine and there was no way to recover.

@jagraj

**Comment by jopit** [comment]
As a workaround, try deleting ~/.codewind/config/deployments.json

**Comment by tetchel** [comment]
https://github.com/eclipse/codewind/issues/625 ?

**Comment by sujeilyfonseca** [comment]
I downloaded the latest Codewind today and did not reach this error either on Mac or Windows.
