### ISSUE TITLE
SVT: Fatal error when starting Appsody Eclipse MicroProfile projects

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#630]
**Codewind version:** 0.5.0
**OS:** macOS Mojave (10.14.6)

**IDE extension version:** 0.5.0
**IDE version:** 1.38.1

**Description:** Fatal error when starting Appsody Eclipse MicroProfile projects
```
[Container] [Error] FATAL error APPSODY_PREP command received an error.  The controller is exiting: exit status 1
[Error] Error waiting in 'appsody run' exit status 1
```

**Steps to reproduce:**
1. Install Codewind
2. Start Codewind
3. Create an Appsody Eclipse MicroProfile project

**Logs:**
[appsody.log](https://github.com/eclipse/codewind/files/3699250/appsody.log)

@jagraj

**Comment by makandre** [comment]
Probably a point-in-time error?  We've since updated the appsody CLI we bundle.  Do we still see this?

**Comment by sujeilyfonseca** [comment]
I no longer see this error with the latest Codewind.
