### ISSUE TITLE
Retagging makes it look like Codewind is twice as big

### ISSUE THREAD

**Issue by deboer-tim** [eclipse/codewind#631]
When people run 'docker images' they see two copies of every image in Codewind, one with and one without the eclipse prefix:
   eclipse/codewind-pfe-amd64     0.4.0            224a9df6df08  ...
   codewind-pfe-amd64             0.4.0            224a9df6df08 ...

First, this looks a bit cluttered and it takes a second to notice the image id and realize that they're the same thing. Second, a couple users who didn't notice the image id have assumed that we're double the download/disk size than we actually are.

Can we remove the duplication? The core problem appears to be the retagging we're doing here, although I don't know why or what the correct solution is:
https://github.com/eclipse/codewind-installer/blob/3720bedca0cf25f9246bcd8dd50384317bc4af32/utils/docker.go#L177

**Comment by deboer-tim** [comment]
https://github.com/eclipse/codewind-installer/blob/3720bedca0cf25f9246bcd8dd50384317bc4af32/actions/install.go#L22

**Comment by ebuckle** [comment]
This has been resolved, the CLI no longer re-tags these images so only one copy shows up with `docker images`

![image](https://user-images.githubusercontent.com/33088613/71821871-34a46d80-308b-11ea-97de-b9d1c06ea337.png)

![image](https://user-images.githubusercontent.com/33088613/71821881-39692180-308b-11ea-8911-6ae105b628ec.png)

**Comment by liamchampton** [comment]
Can confirm this has been resolved in PR here https://github.com/eclipse/codewind-installer/pull/294. This was part of the `docker api` -> `docker-compose` conversion.
