### ISSUE TITLE
Project Types API tests failing on master

### ISSUE THREAD

**Issue by hhellyer** [eclipse/codewind#635]
The project types API test is failing on master:

https://ci.eclipse.org/codewind/job/Codewind/job/codewind/job/master/128/console

it seems to be because of the project type `appsodyExtension` in the list of project types.

**Comment by rajivnathan** [comment]
Is this a dupe of #621?

**Comment by makandre** [comment]
There was a bug in the appsody extension, which is now fixed with https://github.com/eclipse/codewind-appsody-extension/pull/35

Tests should pass if you rerun them now.  Sorry for the inconvenience.

**Comment by hhellyer** [comment]
This is resolved now.
