### ISSUE TITLE
Missing space in Codewind for VS Code page title

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#641]
![image](https://user-images.githubusercontent.com/8888438/66431927-fdbaaf00-e9ea-11e9-85e4-7ba34d802a51.png)

`Codewindfor VS Code`

**Comment by micgibso** [comment]
@tetchel Is this a docs issue? It's not in our source, appears to be in the UI?

**Comment by tetchel** [comment]
it's a typo in the title. https://github.com/eclipse/codewind-docs/blame/master/docs/_documentations/mdt-vsc-overview.md#L3

**Comment by micgibso** [comment]
@tetchel Sorry, should've searched the files before typing...will fix and put on a PR.
