### ISSUE TITLE
Codewind for Eclipse Che Overview Section Enhancement

### ISSUE THREAD

**Issue by GeekArthur** [eclipse/codewind#646]
**Description of the enhancement:**

In the landing page, currently Overview section of Codewind for Eclipse Che includes lots of stuffs (eg. Prerequisites, Installing, Setup, etc).

**Proposed solution:** 

I think it would be better in the Overview section we only have generic overview like features introduction, then create separate sections for Prerequisites, Installing, Setup, etc. So that we will make our Overview section of Codewind for Eclipse Che (https://www.eclipse.org/codewind/installoncloud.html) consistent with other Overview sections (eg. Codewind for VS Code Overview section: https://www.eclipse.org/codewind/mdt-vsc-overview.html).

**Comment by j-c-berger** [comment]
@sishida would you please assign this issue to me since I also am working on #605 
Thanks
