### ISSUE TITLE
Disable project settings (.cw-settings) for extensions (Appsody and ODO) 

### ISSUE THREAD

**Issue by GeekArthur** [eclipse/codewind#649]
**Description:**
Currently for extensions:

If we emit a projectSettingsChanged event with eg:
```
{ status: "failure", "error": "internalPort cannot be configured for an odo project" }
```
Theia will show it in an error message but actually it's not an error it's because we don't support project settings for extensions. Discussed with @makandre, we propose to disable project settings for extensions (Appsody and ODO) so that to reduce the confusion for user.

**Comment by makandre** [comment]
I can handle this one

**Comment by makandre** [comment]
I can make CLI not write the `.cw-settings` for extension type projects easily (https://github.com/eclipse/codewind-installer/pull/148)

However, the IDEs still show controls to edit the settings, and it will complain that the file doesn't exist.  So maybe we need some changes in IDEs?

@tetchel @eharris369 what do you think?

**Comment by tetchel** [comment]
we can block the opening of the file if it does not exist.

**Comment by eharris369** [comment]
Or not show the button at all if the file does not exist.

**Comment by tetchel** [comment]
true, otherwise if the message says ".cw-settings is missing", users may try to create it or something.

I guess I will disable (with the 🚫 cursor) the "edit" buttons.

**Comment by tetchel** [comment]
fix is in in all 3 of installer, vs code, and eclipse
