### ISSUE TITLE
SVT: Landing page renders incorrectly once it gets past certain dimensions

### ISSUE THREAD

**Issue by beccabau** [eclipse/codewind#652]
*Web browser:* Chrome

**Description:**
I have a widescreen monitor and when I open the codewind homepage, the banner does not render correctly ("Get started" button and the vs code/eclipse/che screenshots get hidden behind the silhouette, and the screenshots also pop into a different orientation):

![image](https://user-images.githubusercontent.com/13971834/66572765-89455480-eb3f-11e9-9c8b-910219eb870a.png)

**Workaround:** 

But if I were to narrow the window, it looks better:

![image](https://user-images.githubusercontent.com/13971834/66572856-b560d580-eb3f-11e9-870a-b18b0bfac54d.png)

Solution: change where the silhouette is prioritized as a layer? (so it goes behind the 'Get started' button and the main text?) Or it could get shorter/sink into the bottom of the banner...

**Comment by sishida** [comment]
@travis1111 Hi, Travis, Could you please take a look at this website issue? Thank you!

**Comment by travis1111** [comment]
please assign to me @sishida

**Comment by deboer-tim** [comment]
FWIW, this issue was randomly mentioned to me by someone from EclipseSource last night, so others are also noticing this problem on larger monitors.

**Comment by travis1111** [comment]
I will take a look

**Comment by travis1111** [comment]
@sghung do we have any wide screen monitor?

**Comment by jgwest** [comment]
@travis1111 On Firefox or Chrome, load codewind.dev and just hit `CTRL-Minus` (or the Mac equivalent)  until the text and screenshot are behind the buildings.

**Comment by travis1111** [comment]
thanks I will try that
