### ISSUE TITLE
Adding a new section in the table of contents

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind#656]
The doc content for these three issues looks like it could use its own section in the website table of contents:
- Appsody: https://github.com/eclipse/codewind/issues/292
- ODO: https://github.com/eclipse/codewind/issues/605, https://github.com/eclipse/codewind/issues/646

I'm thinking we could have either...
:one: a new parent topic that appears below the "Developing with Codewind" section and that contains Appsody and ODO child topics or...
:two: Appsody and ODO child topics at the same level as the Codewind for Eclipse/Codewind for VS Code/Codewind for Eclipse Che topics.

As for what to name the new section, something with "build types" or "project styles" seems to be suitable.

**Comment by j-c-berger** [comment]
@sishida I looked into this and worked on it as necessary. Thanks.
