### ISSUE TITLE
Codewind Getting Started pages don't list prereqs for Docker/Docker Compose

### ISSUE THREAD

**Issue by rtaniwa** [eclipse/codewind#659]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**
The Getting Started pages don't reference the prereqs required for local use (Eclipse and VS Code). It should list that it requires Docker/Docker Compose. 

**Steps to reproduce:**

**Workaround:**

**Comment by johnmcollier** [comment]
We should also list the versions of each required, especially as we require Docker 17.05 or higher (and some RHEL systems package a lower Docker version, see https://github.com/eclipse/codewind/issues/343)

**Comment by tetchel** [comment]
hmm... it definitely used to.

**Comment by jgwest** [comment]
Oddly enough:
* Markdown in `codewind-docs` DOES include reference to compose:
https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/mdt-eclipse-getting-started.md <--
* Actual Eclipse HTML does not: https://www.eclipse.org/codewind/mdteclipsegettingstarted.html

**Comment by micgibso** [comment]
Realised the Docker/Docker compose prereqs were missing so added them back in for both VS Code and Eclipse, step 2 in each, visible here:
https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/mdt-vsc-getting-started.md
and here:
https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/mdt-eclipse-getting-started.md

**Comment by micgibso** [comment]
Now published. @sishida please close.
