### ISSUE TITLE
Create docker registry secret in Codewind

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#665]
The user should not have to do step 1) of https://github.com/tetchel/codewind-without-che#install-steps

We should create the secret for the user when they set their docker registry credentials.

This could be done in PFE upon POST /registry.

This could also be done using a cwctl command, if the cwctl had access to the current cluster context (which it should).

**Comment by tobespc** [comment]
The docs in that link are not valid anymore with the work Mark has done, rather than go through tech topics lets just have a chat when you get in to sort this out

**Comment by jopit** [comment]
TODO: iterative-dev to investigate if this could be done in PFE upon POST /registry.

**Comment by maysunfaisal** [comment]
I can take a look at this.

Even tho this is tagged as iterative-dev; this issue will need new sets of Portal API for setting up docker registries.

I have already laid the foundation of the new API in my branch, will update this issue with API info tomorrow.

**Comment by maysunfaisal** [comment]
cc: @tetchel @jopit

**Comment by maysunfaisal** [comment]
POST `/api/v1/dockerregisrty` will take `url`,`username`,`password` in it's body
GET `/api/v1/dockerregisrty` will return the list of created Docker registry - `url` and `username`
DELETE `/api/v1/dockerregisrty` will take `url` as the input and delete the docker registry from PFE

**Comment by rajivnathan** [comment]
Talked to Maysun and Elson, given we're working on shutdown we'll defer this to the next tech-topic call.

**Comment by maysunfaisal** [comment]
To use the docker registries on Kube/Che, we will need to enter information regarding our docker registries like we do in Che:

![Screen Shot 2019-11-06 at 7 02 10 PM](https://user-images.githubusercontent.com/31771087/68348485-f5c45c80-00c7-11ea-9ba6-5516cf3a1152.png)


## Existing Logic

### PFE Mount from Che secret

- When deploying PFE on Che, we mount the Che secret to `/tmp/secret` https://github.com/eclipse/codewind-che-plugin/blob/master/codewind-che-sidecar/deploy-pfe/pkg/codewind/util.go#L176
- The secrets are then copied over from the PFE mount to the appropriate place like either `/root/.docker/config.json` or `/root/.dockercfg` during PFE startup in `root-watcher.sh` https://github.com/eclipse/codewind/blob/master/src/pfe/file-watcher/scripts/root-watcher.sh#L95

## Proposed APIs

The proposed APIs will do things similar(almost exactly) to what Che currently does

### POST /api/v1/dockerregistry {url, username, password}
- will create the `/root/.docker/config.json` with the information provided above. This creation of JSON object will follow the convention docker expects like JSON file to be in. If it's a new registry, the information will be appended.
- will create a Kubernetes secret with the base64 encoded value of the file `/root/.docker/config.json` created above (like the Che secret in the previous section which Che was creating during Codewind workspace creation) 
- Patch the Codewind Service Account with the above newly created secret

### GET /api/v1/dockerregistry 
- will return the list of docker registries created in PFE (url and username)

### DELETE /api/v1/dockerregistry {url}
- will delete the docker registry from `/root/.docker/config.json` file
- update the Kubernetes secret with the base64 encoded value of the updated file `/root/.docker/config.json`
- Patch the Codewind Service Account with the above updated secret

## POST /api/v1/registry

- will still be used to select the deployment registry after creating the registries above

**Comment by maysunfaisal** [comment]
Looked at how Che is storing their registry credentials. They're essentially storing a base64 encoded value of object
```
let credentials = {};
    credentials[registryUrl] = {
    username: userName,
    password: userPassword
};
```

So maybe our POST can instead send a base64 encoded string of a similar object instead of passing in url, username and password as string parameters

Here is the info:

### 1. On Registry Dialog `Add` button, Che calls the `addRegistry` function
**Add button** - https://github.com/eclipse/che/blob/490413cd482f61878050accec0bf2d9ad094456d/dashboard/src/app/administration/docker-registry/docker-registry-list/edit-registry/edit-registry.html#L37
**Event Handler** - https://github.com/eclipse/che/blob/490413cd482f61878050accec0bf2d9ad094456d/dashboard/src/app/administration/docker-registry/docker-registry-list/edit-registry/edit-registry.controller.ts#L61
**addRegistry** - https://github.com/eclipse/che/blob/490413cd482f61878050accec0bf2d9ad094456d/dashboard/src/components/api/che-preferences.factory.ts#L121

### 2. `addRegistry` calls `remotePreferencesAPI.save` and stores it in `javax.persistence.EntityManager`
**save** - https://github.com/eclipse/che/blob/490413cd482f61878050accec0bf2d9ad094456d/wsmaster/che-core-api-user/src/main/java/org/eclipse/che/api/user/server/PreferencesService.java#L86
**setPreference** - https://github.com/eclipse/che/blob/490413cd482f61878050accec0bf2d9ad094456d/wsmaster/che-core-api-user/src/main/java/org/eclipse/che/api/user/server/jpa/JpaPreferenceDao.java#L39

**Comment by maysunfaisal** [comment]
@malincoln A new npm package has been introduced with PR https://github.com/eclipse/codewind/pull/1118

Can we proceed with the legal clearance for it?

**Comment by malincoln** [comment]
@maysunfaisal just confirming this is for 0.7.0 (release is set to this) and not 0.6.0.
Nik normally pull these in when he run the auto scripts so please confirm with him on mattermost.

**Comment by maysunfaisal** [comment]
yes this is for `0.7.0`

**Comment by tetchel** [comment]
https://github.com/eclipse/codewind/issues/1211 is required in order to be able to use the registry secrets

**Comment by johnmcollier** [comment]
Renaming as this affects Codewind on Che as well

**Comment by makandre** [comment]
I gave the API a try for the appsody case (local and on kube), I tested against a private repo I set up on dockerhub: `makandre/nodejs-express:0.2` (a copy of the appsody stack)

On kube, I can post the secret with`url: "https://index.docker.io/v1/"` or `url: "docker.io"`.  In both cases `buildah pull` can pull the image down.

On local, I can **only** post the secret with `url: "https://index.docker.io/v1/"`.  If I posted with `url: "docker.io"`, the `docker pull` still complains that access is denied.

**Comment by maysunfaisal** [comment]
TODO 
- [ ] On local, if a user enters `docker.io`; API to convert it to `https://index.docker.io/v1/` 
- [ ] Discussion on persistence of API values for local case

Also there are some changes to `/api/v1/registry` as per Issue https://github.com/eclipse/codewind/issues/1300

**Comment by maysunfaisal** [comment]
From tech talk about persistence, we have opened two new issues - https://github.com/eclipse/codewind/issues/1305 and https://github.com/eclipse/codewind/issues/1306

**Comment by maysunfaisal** [comment]
/verify

This can be moved to verify.

sub-issues have been opened.

**Comment by micgibso** [comment]
@maysunfaisal Does this still need doc? I've been working with Mark on PR https://github.com/eclipse/codewind-docs/pull/204 to document remote, is it part of that?

**Comment by tetchel** [comment]
here's the frontend issue, which has the doc label, so i'll remove it from this one. https://github.com/eclipse/codewind/issues/1178
