### ISSUE TITLE
Creating a new project within Che does not show files until refreshing navigator

### ISSUE THREAD

**Issue by markcor11** [eclipse/codewind#67]
When creating a new project in Codewind running on Che the project source files are not immediately visible. 

The template files are downloaded and the project will start to build but the project navigator does not show the downloaded source files until after a refreshed eg : 

<img width="1064" alt="Screenshot 2019-07-31 at 08 28 18" src="https://user-images.githubusercontent.com/28102564/62192329-50ce1100-b36d-11e9-8c18-e389121c3484.png">

After collapsing and expanding the "Projects" category the project appears : 

<img width="1050" alt="Screenshot 2019-07-31 at 08 30 17" src="https://user-images.githubusercontent.com/28102564/62192806-39435800-b36e-11e9-876e-88bfbcdb99e3.png">

**Comment by rajivnathan** [comment]
@tetchel Not sure whether this is a problem with Theia or if the Codewind extension should refresh the explorer view (if possible) after project creation is complete.

**Comment by tetchel** [comment]
interesting, I always saw them show up. I will see if there is anything I can do from my end

**Comment by tetchel** [comment]
https://github.com/theia-ide/theia/issues/5885

**Comment by tetchel** [comment]
@markcor11 theia hasn't made the change yet that would allow me to refresh manually, but I'm wondering if you still ever see this, because I do not

**Comment by malincoln** [comment]
@markcor11 pls verify and close. Thanks

**Comment by markcor11** [comment]
Tried this out again with latest code on a new ROKS cluster and was unable to reproduce it. 

![Screenshot 2020-03-09 at 14 40 47](https://user-images.githubusercontent.com/28102564/76225282-2fdb7180-6214-11ea-9084-6d28dceae072.png)

Closing
