### ISSUE TITLE
SVT:Show all logs does not work for ODO projects from codewind che workspace

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#673]
**Codewind version:** 0.5.0
**OS:** RHEL

**Che version:** 7.2.0
**IDE extension version:** 0.5.0
**IDE version:**7.2.0
**Kubernetes cluster:**
OKD Cluster

**Description:**
Show all logs does not work for ODO projects. I need to manually switch in "Output" view.
I can get to logs for default template projects but not for ODO projects.

![Screen Shot 2019-10-14 at 1 36 55 PM](https://user-images.githubusercontent.com/713849/66771993-a48ac980-ee89-11e9-8983-b8651506171d.png)

**Steps to reproduce:**
1. Install Eclipse che on OKD cluster.
2. Create Codewind 0.5.0 workspace.
3. Create ODO projects, "Right click" on the project from Codewind explorer and click on "Show all logs".
4. View is not getting switched to Log for for the ODO project.
5. I do not see same problem with the default template projects.

**Workaround:**

**Comment by lentheivendra** [comment]
I'll take a look at this

**Comment by jagraj** [comment]
Hi Len,

This is happening intermittently, sometimes it bring up the logs view and sometimes the log for previous project stays in the view when I selected "Show all logs" for different project.

**Comment by GeekArthur** [comment]
Me and Len can't reproduce this issue, sometimes it does have glitch from IDE for displaying logs (not from ODO project but from random project), think the issue is not from `iterative-dev` probably from `Theia`

**Comment by jagraj** [comment]
Ok, Thanks. Looks like Theia plugin has been moved to 7.1.0 for another issue. I will give it a try with the latest 0.5.0 devfile.

**Comment by rajivnathan** [comment]
Moved to vscdoe-ide area based on comments it's not specific behaviour to odo projects.

**Comment by tetchel** [comment]
@jagraj do you still see this? looks like I missed this one

**Comment by jopit** [comment]
@jagraj do you still see this?
