### ISSUE TITLE
SVT: Skaffold or Scaffold?

### ISSUE THREAD

**Issue by mmulholl** [eclipse/codewind#674]
**Codewind version:**  Codewind tech preview	0.5.0.v201910112029	
**OS:** MacOS

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**
The appsody Node.js Express Skaffold templete is now spelling Skaffold with a "c"

"Appsody Node.js Express scaffold template"

The karbanero version is using "skaffold"

**Steps to reproduce:**

**Workaround:**

**Comment by mmulholl** [comment]
@jagraj fyi

**Comment by makandre** [comment]
The spelling comes straight from the index that appsody team generate and host at https://github.com/appsody/stacks/releases

And it's due to this change https://github.com/appsody/stacks/pull/388 on their side.

**Comment by mmulholl** [comment]
So what is the correct spelling?

**Comment by makandre** [comment]
Probably whatever Appsody team has decided on (they must've changed the spelling for a reason).

In any case since we're getting this text straight from them, there's not really anything we can do on our side

**Comment by rtaniwa** [comment]
Let's check with them to understand if this is a proper name, or not. Seems to me either way, they should be consistent with the Kabanero collection.

**Comment by deboer-tim** [comment]
We should just transfer the issue across since it's not IDE related. I'm pretty sure it should be Skaffold and someone 'fixed' the spelling accidentally.

**Comment by makandre** [comment]
I just posed a question on appsody slack channel.

**Comment by makandre** [comment]
Kabanero renamed too: https://github.com/kabanero-io/collections/tree/master/incubator/nodejs-express/templates/scaffold

**Comment by makandre** [comment]
We established the name is "scaffold".  Can this be closed?

**Comment by sghung** [comment]
Closing on behalf of Martin since this has been opened a long time and has been resolved by appsody + kabanero to make it consistent
