### ISSUE TITLE
SVT: ODO projects can't be deleted during "building" stage

### ISSUE THREAD

**Issue by DavidG1011** [eclipse/codewind#677]
**Codewind version:** Latest
**OS:** RHEL 7

**Che version:** 7.2.0
**Kubernetes cluster:** OKD/OpenShift

**Description:** ODO projects can't be deleted during "building" stage

**Steps to reproduce:**

1. Create a project using an OpenShift template.
2. Remove project and delete directory while project is in "building" stage.

Result: Project is removed from Codewind, but not deleted:

![Screen Shot 2019-10-14 at 4 04 52 PM](https://user-images.githubusercontent.com/30476587/66779732-f7ba4780-ee9c-11e9-99ca-5551635dc329.png)

Manual attempt:

![Screen Shot 2019-10-14 at 4 11 58 PM](https://user-images.githubusercontent.com/30476587/66779898-68616400-ee9d-11e9-9063-432a881729f4.png)

fyi: @jagraj

**Comment by GeekArthur** [comment]
Please assign this to me as well. I can drop a PR to fix this.

**Comment by GeekArthur** [comment]
Fixed has been merged, @rajivnathan This one can be closed.
