### ISSUE TITLE
Update Iterative-Dev Turbine & SC test scripts for Che 7.2.0

### ISSUE THREAD

**Issue by maysunfaisal** [eclipse/codewind#680]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description of the enhancement:**

The Che APIs needs to be updated for Che 7.2.0 multi user. The curl command will now include a access token for authentication.

**Proposed solution:**

**Comment by lentheivendra** [comment]
I'll update the SC tests for this
