### ISSUE TITLE
Investigate console and messages log for Liberty projects - Hybrid Change

### ISSUE THREAD

**Issue by ssh24** [eclipse/codewind#682]
**Description:**

We also need to investigate a way to be able stream console and message logs for Liberty projects which is stored under the app folder.

Could possibly be fixed by https://github.com/eclipse/codewind/issues/681

**Comment by ssh24** [comment]
@rajivnathan With #681 this should also be fixed. You can assign me to it

**Comment by rajivnathan** [comment]
Closing as this is a subset of #681
