### ISSUE TITLE
Appsody broken on master branch

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#683]
**Codewind version:** master
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**

Currently appsody is broken on master branch.  When you you create an appsody project, in the log you'll see:

```
unning docker command: docker run --rm -P --name cw-knpython-1682c9c0-ef6b-11e9-ae96-1d0b6deac20e --network codewind_network -v /codewind-workspace/knpython/:/project/userapp -v knpython-deps:/project/deps -v /codewind-workspace/.extensions/codewind-appsody-extension/bin/appsody-controller:/appsody/appsody-controller -t --entrypoint /appsody/appsody-controller appsody/python-flask:0.1 --mode=run
[Container] docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/appsody/appsody-controller\": permission denied": unknown.
[Error] Error in 'appsody run': exit status 126
```

I think it's related to the code below, which is not being guarded by the `--remote` flag:

https://github.com/eclipse/codewind/commit/abe12b535cd345a5e677af066d0e38dd7d3ca754#diff-7597df0b79304bd2be18940009414316R58

**Steps to reproduce:**

**Workaround:**

**Comment by tobespc** [comment]
@ssh24 Could you take a look at this please ?   I've stepped through the code and can't see why its not building

**Comment by ssh24** [comment]
@makandre Any idea where the docker run command is being triggered from? Searched the appsody extension but couldn't find it there
`docker run --rm -P --name cw-knpython-1682c9c0-ef6b-11e9-ae96-1d0b6deac20e --network codewind_network -v /codewind-workspace/knpython/:/project/userapp -v knpython-deps:/project/deps -v /codewind-workspace/.extensions/codewind-appsody-extension/bin/appsody-controller:/appsody/appsody-controller -t --entrypoint /appsody/appsody-controller appsody/python-flask:0.1 --mode=run`

**Comment by makandre** [comment]
It fails because `LOCAL_WORKSPACE` in the file `projectUtils.ts` used to be the host system path to `codewind-workspace` (for example, `/opt/Repos/Tempest/codewind/codewind-workspace`)

Appsody CLI needs to mount the project folder into their container using this path (they issue the docker command that @ssh24 posted above).  So, where it says `-v /codewind-workspace/knpython/:/project/userapp` above, it should have been `-v /opt/Repos/Tempest/codewind/codewind-workspace/knpython/:/project/userapp`

Anything that starts with `/codewind-workspace` is not going to work because that's a PFE relative path, but Appsody talks to the host docker daemon and can only mount using host system paths.

**Comment by makandre** [comment]
Verified this is ok now.  Thanks.
