### ISSUE TITLE
SVT:ODO projects are not deleted after workspace is deleted and old projects deployments still exist

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#692]
**Codewind version:** 0.5.0
**OS:** RHEL

**Che version:** 7.2.0
**IDE extension version:** 0.5.0
**IDE version:**7.1.0
**Kubernetes cluster:**
OKD Cluster

**Description:**
I created ODO projects and I deleted workspace. All the ODO projects deployments they still exist even though I deleted my entire workspace. I do not see same behavior with the Codeweind default projects. All the projects created from default codewind templates are deleted when I delete my workspace. 

**Steps to reproduce:**
1. Install Codewind che with 0.5.0 devfile.
2. Create ODO projects.
3. Delete codewind workspace .
4. Create new workspace and I still see previously created ODO projects deployments.

Here is more info from my cluster.

```
 kubectl get pods
NAME                                 READY     STATUS    RESTARTS   AGE
che-7fbd6b89b4-5m9vn                 1/1       Running   0          1d
che-operator-6f59664648-j5qlp        1/1       Running   0          1d
cw-dotnetokdcw05svt-app-1-hjpnr      1/1       Running   0          1d
cw-httpdokdcw05svt-app-1-bmbks       1/1       Running   0          1d
cw-pythonodookdcw05svt-app-1-dx4jf   1/1       Running   0          1d
devfile-registry-5c774759b5-q8zpt    1/1       Running   0          1d
keycloak-66c74b7599-snk7v            1/1       Running   0          1d
plugin-registry-69765c8c79-j6d95     1/1       Running   0          1d
postgres-864b695569-nhs8q            1/1       Running   0          1d
tiller-deploy-57bcbcbbc8-m7hjw       1/1       Running   0          1d
```

```
kubectl get pods
NAME                                                              READY     STATUS    RESTARTS   AGE
che-7fbd6b89b4-5m9vn                                              1/1       Running   0          1d
che-operator-6f59664648-j5qlp                                     1/1       Running   0          1d
codewind-performance-workspace0emel7m7jo6o1l57-67446df96c-7md22   1/1       Running   0          1h
codewind-workspace0emel7m7jo6o1l57-656767fbf-txvb5                1/1       Running   0          1h
cw-dotnetokdcw05svt-app-1-hjpnr                                   1/1       Running   0          1d
cw-httpdokdcw05svt-app-1-bmbks                                    1/1       Running   0          1d
cw-odonodejscw05svt-app-1-bl4pg                                   1/1       Running   0          12m
cw-pythonodookdcw05svt-app-1-dx4jf                                1/1       Running   0          1d
devfile-registry-5c774759b5-q8zpt                                 1/1       Running   0          1d
keycloak-66c74b7599-snk7v                                         1/1       Running   0          1d
plugin-registry-69765c8c79-j6d95                                  1/1       Running   0          1d
postgres-864b695569-nhs8q                                         1/1       Running   0          1d
tiller-deploy-57bcbcbbc8-m7hjw                                    1/1       Running   0          1d
workspace0emel7m7jo6o1l57.che-jwtproxy-657bb89bbd-x4pph           1/1       Running   0          1h
workspace0emel7m7jo6o1l57.che-workspace-pod-59c78954b8-qt9x2      3/3       Running   0          1h
```

**Workaround:**

**Comment by GeekArthur** [comment]
I can investigate this issue.

Would like to confirm one thing, you delete the codewind workspace from Che IDE?

**Comment by jagraj** [comment]
Yes, I deleted workspace from the Che dashboard.

**Comment by jagraj** [comment]
I tried to delete my ODO projects from the PFE and they failed to delete and ODO cli  is expecting ODO modules to delete the projects but my modules are deleted when I deleted my workspace. 

Making this as "hot" for now and we need to find a way how user can delete these projects.

**Comment by GeekArthur** [comment]
I will investigate this issue, please assign this to me.

**Comment by GeekArthur** [comment]
For deleting the ODO project, we can shell into the ODO application pod then go into the folder includes `.odo`, then run `odo delete --all -f`, all the corresponding resources will be removed by the ODO CLI command.

However, we should find a way to removing all ODO related resources and not relying on Kube garbage collector (if it doesn't work properly for ODO case).

**Comment by sujeilyfonseca** [comment]
**Codewind version:** [0.5.0](https://raw.githubusercontent.com/eclipse/codewind-che-plugin/master/devfiles/0.5.0/devfile.yaml)  
**OS:** Red Hat Enterprise Linux 7 (64 bit)

**Che version:** 7.2.0
**Kubernetes cluster:** OKD/Openshift

I also see this problem with Codewind for Eclipse Che.

**Comment by GeekArthur** [comment]
@sujeilyfonseca Yes, this problem is not intermittent, once we catch that on one cluster, it will happen on all clusters.

**Comment by jagraj** [comment]
After meeting with Jingfu and we came up with instructions how to delete orphaned ODO projects when workspace is deleted. This has to be documented to the users so that they can delete them with the manual instructions. 

If user has "NFS" as a storage for the cluster, user can go to projects folders and delete ODO project resources with the following commands.

```
curl -L https://github.com/openshift/odo/releases/latest/download/odo-linux-amd64 -o /usr/local/bin/odo && chmod +x /usr/local/bin/odo
```
```
odo delete --all -f
```

If user has GlusterFS as a storage, then user has to copy resources under ".odo" from ODO pod up and running.

```
kubectl cp cw-dotnetokdcw05svt-app-1-hjpnr:/opt/app-root/src/.odo .

```

```
mkdir .odo
mv odo-file-index.json  .odo/
mv config.yaml .odo/
odo delete --all -f
```

**Comment by GeekArthur** [comment]
I think for "NFS" user they will also face the same permission issue so they have to use the same instruction as "GlusterFS". So the generic instruction would be:

User has to copy resources under ".odo" from ODO pod up and running and install ODO CLI locally, then remove odo component by the following steps:
1. Login to OKD/OpenShift Cluster
2. Download ODO CLI locally using this instruction: https://github.com/openshift/odo#procedure
3. Run the following commands:
```
kubectl cp <ODO component pod name>:<path to folder that includes .odo>/.odo .
mkdir .odo
mv odo-file-index.json .odo/
mv config.yaml .odo/
odo delete --all -f
```

**Comment by rajivnathan** [comment]
I think they can accomplish the same without the need to download odo and copy files.

The following should work:
1. Login to OKD/OpenShift cluster
2. Change to the project where the resources are: `oc project <project name>`
3. Run the following command: `oc delete svc,route,dc,pvc -l=app.kubernetes.io/name=app`

If they had other odo components in the same namespace they can remove individual components by using this command instead:
`oc delete svc,route,dc,pvc -l=app.kubernetes.io/component-name=<component name>`

**Comment by GeekArthur** [comment]
@rajivnathan I don’t think ODO specific resources have the correct label that can let us do the generic delete
```
jingfus-mbp:~ jingfuwang$ k describe svc cw-nodejsjs-app
Name:              cw-nodejsjs-app
Namespace:         che
Labels:            app=app
                   app.kubernetes.io/instance=cw-nodejsjs
                   app.kubernetes.io/name=nodejs
                   app.kubernetes.io/part-of=app
                   app.openshift.io/runtime-version=latest
Annotations:       app.kubernetes.io/component-source-type=local
                   app.openshift.io/vcs-uri=file://./
Selector:          deploymentconfig=cw-nodejsjs-app
Type:              ClusterIP
IP:                172.30.81.109
Port:              8080-tcp  8080/TCP
TargetPort:        8080/TCP
Endpoints:         10.129.1.227:8080
Session Affinity:  None
Events:            <none>
```
So it doesn’t have resource label for <component>-<app>, user may fail to delete or delete wrong resource by using the instruction you post

**Comment by rajivnathan** [comment]
My bad, I was using an older version of the odo cli. With the newer ones I see the labels you do. But still think it's better to delete using oc commands than the alternative.

The command to delete would be
`oc delete svc,route,dc,pvc,is -l=app.kubernetes.io/part-of=app`

Or for individual components
`oc delete svc,route,dc,pvc,is -l=app.kubernetes.io/instance=<component>`

**Comment by GeekArthur** [comment]
@rajivnathan Yea, you cleanup method should work for this ODO release, but problems are we don’t know how many kube resources that ODO project creates for each ODO release, and we also don’t know if ODO changes the label for each ODO release. Either ODO adds more kube resources or ODO changes the label will break the cleanup method.

However if we are relying on .odo (download odo and copy files), we don’t need to always update our instruction to accommodate changes on ODO side.

**Comment by micgibso** [comment]
Have documented this on https://github.com/eclipse/codewind-docs/pull/184 please assign me.
