### ISSUE TITLE
Che setup commands should be copy-pasteable

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#708]
https://www.eclipse.org/codewind/installoncloud.html#prerequisites

I strongly prefer when terminal commands such as these can be easily copy-pasted in one step. I would write these directions as one step, as follows:

```
git clone https://github.com/eclipse/codewind-che-plugin.git && \
    kubectl apply -f codewind-che-plugin/setup/install_che/codewind-clusterrole.yaml && \
    kubectl apply -f codewind-che-plugin/setup/install_che/codewind-rolebinding.yaml
```

The explanation text would be along the lines of, 
"Clone the `codewind-che-plugin` repository, create the ClusterRole with the required permissions, and bind that ClusterRole to the Che workspace ServiceAccount."

**Comment by sishida** [comment]
Hi, @tetchel, Thank you for this feedback. I have created a PR for your changes: https://github.com/eclipse/codewind-docs/pull/187

Also, could you please take a look at the link in line 26? The original link didn't make a whole lot of sense to me, so I hoped to improve it, but please let me know if another link is better. Thank you!

**Comment by sishida** [comment]
PR merged. Closing this issue.
