### ISSUE TITLE
Add more news for 0.5.0

### ISSUE THREAD

**Issue by micgibso** [eclipse/codewind#709]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description of the enhancement:**

@elsony @GeekArthur This is a continuation of Sarah's work on https://github.com/eclipse/codewind/issues/647

More updates to the News article:
@elsony 18 hours ago Member
Can we add a link to our doc on the odo support in here?
![image](https://user-images.githubusercontent.com/7224752/66994179-c1f7a780-f0c4-11e9-86bd-3e4e8239897c.png)

@GeekArthur
GeekArthur 18 hours ago

Agree with Elson, seems like the 0.5.0 news doc doesn't include any information related with ODO extension which is a new feature that we introduce in 0.5.0. Do we consider create a new section for ODO (same as Appsody), then add all new ODO related features there? Under that section we can add a instruction link to our ODO extension repository (https://github.com/eclipse/codewind-odo-extension), user can see the specific instruction/setup/limitation from the link, but if users just want to take a look ODO features overview, they can just check ODO section.
@elsony
elsony 18 hours ago •
Member

That's a good point. The title can probably be changed to OpenShift project type instead of Che. Also, instead of pointing to the codewind-odo-extension repo, may be we can point to the odo related doc in the Codewind documentation instead.

@GeekArthur
GeekArthur 18 hours ago
Submit my review for my previous comment.

@GeekArthur
GeekArthur 17 hours ago
Yea, we can point to Codewind documentation once Jake finishes that documentation.

**Comment by tetchel** [comment]
also see https://github.com/eclipse/codewind/issues/712
