### ISSUE TITLE
Improve Appsody binding news

### ISSUE THREAD

**Issue by deboer-tim** [eclipse/codewind#712]
**Codewind version: 0.5**

**Description of the enhancement:**
The news for 0.5 includes the item: "Appsody binding support is available for VS Code and Eclipse." Although this is 100% correct, most new users aren't going to know what 'binding' is and why they should care.

**Proposed solution:** 
We should describe things in user terms, e.g. something like "You can now easily import existing Appsody projects into Codewind, or convert projects to use Appsody during import."

For this item (but really in general for several of the items in each news update) it would be great to start including small screen caps or animated gifs to show the feature. This is both easier to read and understand and shows the user where the change is. See https://code.visualstudio.com/updates/v1_39 as an example.

**Comment by micgibso** [comment]
Taken care of in part by wording better and linking to the topics. Also changed the ODO link to point to the readme instead of the issue. See mods for new05.md on PR https://github.com/eclipse/codewind-docs/pull/183

Small screen caps or animated gifs to show the feature remain not done yet.

**Comment by j-c-berger** [comment]
@sishida I can help with this, thanks.

**Comment by sishida** [comment]
@j-c-berger Will work on graphics.
@micgibso Has worked on text.

**Comment by j-c-berger** [comment]
@micgibso made PR #207 for a screenshot of Appsody projects to add to your content. Let me know what you think.

**Comment by sishida** [comment]
Closing this issue because the ID portion is complete. I have opened https://github.com/eclipse/codewind/issues/1037 for the screen capture/gif portion.
