### ISSUE TITLE
Documenting how to create your own template

### ISSUE THREAD

**Issue by AndyRWatson** [eclipse/codewind#713]
**Codewind version:** 0.5+
**OS:**  ALL

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description of the enhancement:**

The documentation makes a reference how to use alternative template sources (https://www.eclipse.org/codewind/mdt-vsc-usingadifferenttemplate.html)   but no reference to why and also no instructions on the steps required to add/create your own templates within such a repo.

Without this documentation the feature to select an alternative source is kinda redundant

**Proposed solution:** 

Document how to create a template within a template repo/source

**Comment by micgibso** [comment]
I'll take this one.

**Comment by tetchel** [comment]
dupe #559
