### ISSUE TITLE
SVT: [Windows 10] There is no name for the Appsody Template Source

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#718]
**Codewind version:** [codewind-0.5.0-201910161808.vsix](https://download.eclipse.org/codewind/codewind-vscode/0.5.0/latest/)
**OS:** VM with Windows 10

**IDE extension version:** 0.5.0
**IDE version:** 1.39.0

**Description:** There is no name for the Appsody Template Source

![Screen Shot 2019-10-17 at 9 37 34 AM](https://user-images.githubusercontent.com/49531960/67017718-29fbbd00-f0c8-11e9-8fc1-fd0c99bd14ca.png)

![Screen Shot 2019-10-17 at 10 22 57 AM](https://user-images.githubusercontent.com/49531960/67017710-28ca9000-f0c8-11e9-9ed7-1ca01027556d.png)

@jagraj

**Comment by tetchel** [comment]
does this work on non-windows?

**Comment by tetchel** [comment]
i wonder if the windows machine just already had `codewind-workspace/.config/repository_list.json` and that is being used

**Comment by sujeilyfonseca** [comment]
I verified my machine and there is a `codewind-workspace/.config/repository_list.json` from a previous installation.

**Comment by tetchel** [comment]
then users will hit this problem

**Comment by tetchel** [comment]
is the kabanero repo missing (in the original issue description screenshot) too?

**Comment by sujeilyfonseca** [comment]
Yes, the kabanero repo is missing.

**Comment by tetchel** [comment]
fwiw, users can work around this by deleting `codewind-workspace/.config/repository_list.json` and restarting codewind.

**Comment by stalleyj** [comment]
I don't think there is anything we can really do to cope with an old/corrupt repository_list.json, however this has made us ask a few questions around the management of that file so I've raised an enhancement to look at this separately
