### ISSUE TITLE
SVT: Appsody Starter Sample Stack projects never start

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#719]
**Codewind version:** [codewind-0.5.0-201910161808.vsix](https://download.eclipse.org/codewind/codewind-vscode/0.5.0/latest/)
**OS:** VM with Windows 10 and MacOS Mojave 10.14.6

**IDE extension version:** 0.5.0
**IDE version:** 1.39.0 and 1.39.2

**Description:** Appsody Starter Sample Stack projects never start

![Screen Shot 2019-10-17 at 10 27 35 AM](https://user-images.githubusercontent.com/49531960/67018276-fec59d80-f0c8-11e9-872a-3df0cd56d75a.png)

**Steps to reproduce:**
1. Install Codewind
2. Start Codewind 
3. Create an Appsody Starter Sample Stack project

**Log:**
[cw-appsody-starter-sample-stack.log](https://github.com/eclipse/codewind/files/3739800/cw-appsody-starter-sample-stack.log)

@jagraj

**Comment by sghung** [comment]
Looking at the logs, this is expected since no server is implemented. Similar to the nodejs and swift appsody stacks, the user needs to implement the server for the status to show up.
