### ISSUE TITLE
OpenAPI: Cannot find folders in the workspace

### ISSUE THREAD

**Issue by keithchong** [eclipse/codewind#72]
Thanks Rob T. for pointing this out/directing me to this issue.

There is an issue with one of the dockerode APIs (run) on Windows, but it is fine on Mac.  I tried using a different variation of the API which works on both Windows and Mac.

Need to use Path.fsPath also.

This is a must-fix.

https://github.com/eclipse/codewind-openapi-vscode/issues/29

**Comment by tobespc** [comment]
Can you provide some more information please. Recreatre scenario, impact ?

**Comment by keithchong** [comment]
This is for the VS Code Open API extension only.  The user launches any of the Generator commands, but is blocked from selecting an OpenAPI definition.

**Comment by keithchong** [comment]
This is fixed.  Closing.
