### ISSUE TITLE
Docs: replace issue links with doc links in News

### ISSUE THREAD

**Issue by micgibso** [eclipse/codewind#722]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description of the enhancement:**
As per title, the News articles link to issues instead of to pages, would be better to link to pages. Update News articles accordingly.

**Comment by GeekArthur** [comment]
Agree with Elson, the linking pages should be done by this PR: https://github.com/eclipse/codewind-docs/pull/180, once the PR is merged then we can update the link to pages instead of issues.

**Comment by micgibso** [comment]
Have doc'd this on https://github.com/eclipse/codewind-docs/pull/183, please assign me

**Comment by beccabau** [comment]
I like having links to issues for users who want to know more context of the things we're releasing, etc, but this is something we can further discuss.

**Comment by beccabau** [comment]
For our developers, it may also make more sense that they can easily access the original issues that are being discussed in the release notes so they feel that they are more of the process. Thoughts?

**Comment by micgibso** [comment]
Improvements made, PRs merged, have heard no more comments about this, closing...
