### ISSUE TITLE
Move codewind-templates to new org and cleanup

### ISSUE THREAD

**Issue by AndyRWatson** [eclipse/codewind#727]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description of the enhancement:**

codewind currently defaults its templates URL to https://github.com/kabanero-io/codewind-templates/ which itself references many existing templates in the microclimate-dev2ops org (e.g https://github.com/microclimate-dev2ops/nodeExpressTemplate ).  Move default templates to the 
https://github.com/codewind-resources org ( which was created in https://github.com/eclipse/codewind/issues/193 ) and ensure it only contains links to open source related templates 

IDE plugins will need updating to default to https://github.com/codewind-resources/codewind-templates

**Proposed solution:**

**Comment by tobespc** [comment]
Node is done 

https://github.com/codewind-resources/nodeExpressTemplate

**Comment by tobespc** [comment]
https://raw.githubusercontent.com/codewind-resources/codewind-templates/master/devfiles/index.json

**Comment by micgibso** [comment]
@sishida I'll look at the docs for this, thanks!

**Comment by tobespc** [comment]
shouldn't be any doc changes for this, its an internal change.


All repos created

**Comment by malincoln** [comment]
@AndyRWatson pls verify and have committer close if resolved.  Thanks

**Comment by AndyRWatson** [comment]
LGTM
