### ISSUE TITLE
Document codewind + appsody + nexus repository integration

### ISSUE THREAD

**Issue by sghung** [eclipse/codewind#728]
Investigate whether nexus repository can be used with codewind

**Comment by sghung** [comment]
Did the investigation and create the steps for a tutorial to handle the Maven and NPM proxy scenario. Tim deBoer wrote the intro and background. I could not get the docker proxy scenario to work, so keeping this open for that.

[Nexus Repository Integration with Appsody.pdf](https://github.com/eclipse/codewind/files/3923706/Nexus.Repository.Integration.with.Appsody.pdf)

**Comment by sghung** [comment]
The kabanero-io issue is here: https://github.com/kabanero-io/docs/issues/233

Currently the PR is under review: https://github.com/kabanero-io/draft-guide-nexus-repository-integration-with-appsody/pull/1

**Comment by j-c-berger** [comment]
@sghung, I'm happy to begin to work on this. I was wondering what iteration you wanted this complete by?

**Comment by malincoln** [comment]
@j-c-berger are the doc updates complete?
@sghung is this ready for you to verify and close?  Thanks

**Comment by j-c-berger** [comment]
@malincoln, no, doc updates aren't complete, and ID has yet to get involved with this issue. This issue is not for 0.9.0 though. 

Steven and I can reassess this issue after 0.9.0's GA, when the business dies down some. Thanks for the follow up.

**Comment by sghung** [comment]
@j-c-berger the guide has been published here: https://kabanero.io/guides/nexus-repository-integration-with-appsody/

The guide is generated from here: https://github.com/kabanero-io/guide-nexus-repository-integration

If there are edits you'd like to make, you can create a PR in https://github.com/kabanero-io/guide-nexus-repository-integration

**Comment by j-c-berger** [comment]
@sghung, from my read-through of the guide, it looks good! 

@sishida, please fell free to close. Thanks!

**Comment by sghung** [comment]
@j-c-berger thanks for taking a look and reviewing!
