### ISSUE TITLE
Add additional logging during Portal launch

### ISSUE THREAD

**Issue by markcor11** [eclipse/codewind#729]
**Codewind version:** 0.5

**Description of the enhancement:**
When diagnosing startup problems there is insufficient data in the default logs to check progress of the launch. Attempting to increase logging via the api/v1/logging api failed since the route was not yet available. 

**Proposed solution:** 
Add additional log output during Portal server startup sequence and possibly add an environment variable to change default log level for cases where the logging API is not accessible.

**Comment by rajivnathan** [comment]
Added the hot label because this issue was opened directly from https://github.com/eclipse/codewind/issues/657 which was a hot issue. We haven't seen https://github.com/eclipse/codewind/issues/657 in a while but if problems like that occur we'd need better logs for investigation.

**Comment by hhellyer** [comment]
I've merged https://github.com/eclipse/codewind/pull/1721 which simply gets PFE to initialise its logging level from an env var. This is enough to enable start up logging in Kubernetes cluster by editing the deployment to add a new env var "LOG_LEVEL" with the required logging level. The PFE pod for the deployment will then be restarted and come up with the correct logging level.

It was still difficult to set the logging level at startup on desktop as cwctl invokes `docker compose` I've added https://github.com/eclipse/codewind-installer/pull/335 This allows the log level to be set to the same level as cwctl's logging on container start when running in local docker by using (for example) `cwctl -loglevel trace start -t latest`.

I am going to raise one last PR to add a `loglevels` command to cwtcl to display or set the log level for a PFE at runtime. It is possible to do this currently with `curl` but if PFE is authenticated it is very difficult to do remotely. Adding a command will simplify this.

**Comment by hhellyer** [comment]
We've now merged https://github.com/eclipse/codewind-installer/pull/336 so that log levels from PFE can be easily adjusted via cwctl.

**Comment by hhellyer** [comment]
Now we can use it I've raised a PR to add some additional logging at the debug level to PFE startup here:
https://github.com/eclipse/codewind/pull/1789

**Comment by hhellyer** [comment]
@markcor11 - I'll talk through all the changes for this at the Tuesday playback but are you happy this can be closed now?

**Comment by markcor11** [comment]
Verified - Closing
