### ISSUE TITLE
Specify required Docker API version in cwctl

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#731]
we got this error when running cwctl on an old version of Docker

`2019/10/17 14:46:51 CONTAINER_LIST_ERROR[107]: Error response from daemon: client version 1.40 is too new. Maximum supported API version is 1.39. `

cwctl does not appear to specify a docker API version to use, so it defaults to latest (1.40). we should specify the earliest API version that has all the features we need, like this:
https://stackoverflow.com/questions/51028784/can-i-pin-docker-api-version-client-version-1-38-is-too-new-maximum-supported

so that we can document our required docker version.

**Comment by tetchel** [comment]
labeling as bug because cw should be able to run in this situation

**Comment by tetchel** [comment]
other team members have hit it so increasing priority

**Comment by tetchel** [comment]
we also need to document whatever docker version we require, in our getting started / setup docs

**Comment by johnmcollier** [comment]
For the CLI, we can set a minimum version of 1.30, as it looks like v1.30 of the API corresponds to 17.06 https://docs.docker.com/engine/api/v1.30/

Our system requirements for Microclimate also had 17.06, and I don’t think it would’ve changed since then. https://microclimate.dev/installlocally#installing-on-linux-or-macos

**Comment by johnmcollier** [comment]
I think the fix for this is just changing:
https://github.com/eclipse/codewind-installer/blob/207305c7a542b27e20d7f69917a7671418a1c1b9/pkg/utils/docker.go#L170

```
cli, err := client.NewEnvClient()
```

to:
```
cli, err := client.NewClientWithOpts(client.WithVersion("1.30"))
```

**Comment by johnmcollier** [comment]
Reopening as this still needs to be backported to 0.6.0

**Comment by malincoln** [comment]
@tetchel looks like this one will be ready to verify soon.

**Comment by tetchel** [comment]
this is done, opened https://github.com/eclipse/codewind/issues/1146 for the docs
