### ISSUE TITLE
Eclipse dark mode: create project and project overview have some white background

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind#732]
**Codewind version:** 0.4.0
**OS:** macOS 10.14.6
**Eclipse version:** 2019-09

**Description:**
Using Eclipse in 2019-09 dark mode, there's some black text on white background in the new project dialog and in the project overview page

![image](https://user-images.githubusercontent.com/29612372/67040191-eec1b400-f0f0-11e9-86b7-f78c9afa06d4.png)

![image](https://user-images.githubusercontent.com/29612372/67040203-f97c4900-f0f0-11e9-9c6d-5a80c556f824.png)

**Comment by jopit** [comment]
In the project overview page, when the application endpoint is not available, the text `Not Available` still has a white background.  Otherwise it all looks good

![image](https://user-images.githubusercontent.com/29612372/72285387-fff75f80-3610-11ea-91fd-ba18fa8e0318.png)

**Comment by eharris369** [comment]
Looks fine on Windows so must be MAC specific.

**Comment by eharris369** [comment]
Fixed by:
https://github.com/eclipse/codewind-eclipse/pull/522
https://github.com/eclipse/codewind-eclipse/pull/512
Please verify.

**Comment by malincoln** [comment]
@jopit pls verify and close. Thanks

**Comment by jopit** [comment]
Verified
