### ISSUE TITLE
SVT: Plugin runtime crashed unexpectedly, all plugins are not working, please reload ...

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#733]
**Codewind version:** 0.5.0
**OS:** RHEL

**Che version:** 7.2.0
**IDE extension version:** 0.5.0
**IDE version:** 7.1.0
**Kubernetes cluster:** OKD/Openshift

**Description:**
With the latest Eclipse che 7.2 version user might notice this error message **Plugin runtime crashed unexpectedly, all plugins are not working, please reload ...**  when the user session is expired for Eclipse che workspace. 

When this happens user has to go to Che workspace dashboard, logout and login again to che workspace and then try to access codewind workspace again.

**Steps to reproduce:**

1. Install Eclipse che on OKD cluster.
2. Create codewind workspace from this devfile (https://raw.githubusercontent.com/eclipse/codewind-che-plugin/master/devfiles/0.5.0/devfile.yaml)
3. After session is expired we see following "Crash" message in the codewind workspace.

![image](https://user-images.githubusercontent.com/713849/67045719-dce60e00-f0fc-11e9-90b6-13c9d3891288.png)

**Workaround:** 

1. Go to Eclipse che workspace "Dashboard"
2. Logout user from workspace.
3. Login again.
4. Try to access codewind workspace again.

This will help user to come out of this crash state.

**Comment by micgibso** [comment]
I'll take this, please assign to me
