### ISSUE TITLE
license file in wrong place - codewind-performance

### ISSUE THREAD

**Issue by AndyRWatson** [eclipse/codewind#737]
**Codewind version:** 0.4 +
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**
The codewind-performance container does not have the license file in the default/home user directory.   Unlike pfe it appears to be in / instead.  I would expect to be able to find easily (or in a \license directory off the main directory)

**Steps to reproduce:**

> docker exec -it codewind-performance ls -al

drwxr-xr-x    1 root     root          4096 Sep 19 15:51 .
drwxr-xr-x    1 root     root          4096 Sep 19 15:51 ..
drwxr-xr-x    3 root     root          4096 Sep 19 15:51 dashboard
drwxr-xr-x    1 root     root          4096 Sep 19 15:51 node_modules
-rw-rw-r--    1 root     root         29626 Sep 11 20:34 package-lock.json
-rw-rw-r--    1 root     root           387 Sep 11 20:34 package.json
-rwxrwxr-x    1 root     root          1061 Sep 11 20:34 runload.js

if I run against codewind-pfe I get the expected result

-rw-rw-r--   1 root root   82797 Sep 19 15:39 LICENSE

I would expect the following  to work on all containers for anyone wanting to verify our licenses after installation

> docker exec -it codewind-pfe cat LICENSE

**Workaround:**

**Comment by tetchel** [comment]
https://github.com/eclipse/codewind/blob/master/src/performance/Dockerfile_x86_64#L43

**Comment by markcor11** [comment]
The performance container has a different WORKDIR to PFE :

Performance uses :  /usr/src/app
PFE uses: /

For  `docker exec -it codewind-performance cat LICENSE` to work the license needs be moved to /usr/src/app/

**Comment by tobespc** [comment]
closing as fixed
