### ISSUE TITLE
Add deployment id to cwctl commands

### ISSUE THREAD

**Issue by markcor11** [eclipse/codewind#739]
**Codewind version:**  master

**Description of the enhancement:**
The current deployment target command is no longer required as we are preparing to move to a more flexible model a deployment per project rather than a single deployment for all projects. 

We then need to add a new (optional) depid to each cwctl xommand

**Proposed solution:** 
1. Remove the deployment target sub-command 
2. If the depid is not passed in, set default to be the "Local" deployment
3. If passed the depid, we need to look up the details from the the deployments.json file to know where to direct the call

for the design of the per project deployments we have this in place from the cwctl
1) cwctl needs to be called to add a deployment
NAME:
  cwctl deployments add - Add a new deployment to the configuration file
USAGE:
  cwctl deployments add [command options] [arguments...]
OPTIONS:
  --id value        A reference name
  --label value     A displayable name
  --url value       The ingress URL of the PFE instance
  --auth value      URL of Keycloak service eg: https://mykeycloak.test:8443
  --realm value     Security realm eg: codewind or che
  --clientid value  Security client_id to connect as eg: codewind_ctl or che-public
2) Then, associate a project with a depoloyment
NAME:
  cwctl project deployment add - Add a deployment target
USAGE:
  cwctl project deployment add [command options] [arguments...]
OPTIONS:
  --id value, -i value     Project ID
  --depid value, -d value  Deployment ID
3) All cwctl calls now take in an options 'depid' value which you can use if you want that cli to talk to anything other than localhost

**Comment by jcockbain96** [comment]
Could I be assigned please @tobespc ?

**Comment by jcockbain96** [comment]
This has almost been completed, we are now using `projectID` to associate a project to a `depID`. We then use this `depID` to get the `depURL` from the `/doployments.json, and use this as the API host for the project.

Moving forwards, we should look at the most reusable way to call this logic. It will be called at the start of every CLI command that wraps a `project` pfe API, that gets added as part of https://github.com/eclipse/codewind/issues/842.

I'll raise a PR to remove the target sub-commands as the final part of this issue.

**Comment by jcockbain96** [comment]
@tobespc, @markcor11 can this one be closed now? And future issues raised for per project connection work going forwards

**Comment by markcor11** [comment]
Yes thanks @jcockbain96
