### ISSUE TITLE
Update ODO extension installer to accommodate ODO latest release format change

### ISSUE THREAD

**Issue by GeekArthur** [eclipse/codewind#757]
Currently ODO store the binaries into the OpenShift mirrors, we need to update the ODO extension installer to accommodate the changes.

**Comment by GeekArthur** [comment]
Please assign this issue to me.

**Comment by GeekArthur** [comment]
Download location before the change on ODO side:
```
https://github.com/openshift/odo/releases/latest/download/odo-linux-amd64
```

Download location after the change on ODO side:
```
https://mirror.openshift.com/pub/openshift-v4/clients/odo/latest/
```

**Comment by rajivnathan** [comment]
Fix has been merged to 0.5.0

**Comment by GeekArthur** [comment]
Verified, fix worked.

**Comment by rajivnathan** [comment]
Reopening this one so that the fix can be ported to master as well.

**Comment by GeekArthur** [comment]
We discuss the odo binary version today, we will use the latest version for odo binary on Codewind master branch, but will try to move it to build stage so that we don't need to specify version for each release.
