### ISSUE TITLE
Codewind's odo cli binary should be immutable

### ISSUE THREAD

**Issue by rajivnathan** [eclipse/codewind#758]
**Description:**
With https://github.com/eclipse/codewind/issues/757 the odo download url changed and broke Codewind's odo functionality. The odo binary should not change for a particular Codewind release. This can be achieved by packaging it with Codewind images like we do for buildah but it seems the current design doesn't allow for that. We'll need to figure out a solution for this because the current method means that a url change or if there's a breaking change in a newer version of odo, Codewind's odo functionality would be broken.

**Comment by GeekArthur** [comment]
Please assign this to me, this will be fixed by this PR: https://github.com/eclipse/codewind/pull/815.
