### ISSUE TITLE
OpenAPI: Eclipse: Add content type for Open API Definition files

### ISSUE THREAD

**Issue by keithchong** [eclipse/codewind#76]
This is an enhancement

This is to properly support spec files with any arbitrary name

**Comment by tobespc** [comment]
Can you provide some more information on this please so that it can be picked up.  What spec files are you referring to ?

**Comment by keithchong** [comment]
In Eclipse, there is a content type extension point that allows plugins to identify or classify specific file types, regardless of the file name.   So, for example, the suggested name for an OpenAPI definition is openapi.yaml or openapi.json, but users typically would use other file names, like, petstore.yaml.   We need to add this so that the context menu for the OpenAPI generator actions will appear correctly for all OpenAPI definition files, for JSON and for YAML.   Currently, it is based on the filename, which is restrictive.

**Comment by keithchong** [comment]
Cleanup.  Closing this - it was delivered in 0.5.0.
