### ISSUE TITLE
VSCODE - Local Path is incorrect (remote architecture)

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#766]
**Codewind version:** latest
**OS:** Macos

**IDE extension version:** vscode (hybrid)

The Local Path on the project overview is incorrect.  It shows as being /codewind-workspace/.... rather then the actual location on disk.  This info is being sent back from PFE so need to check where its failing.   It should be the LocOnDisk value but on checking this is not set correctly

**Comment by tetchel** [comment]
a while back locOnDisk was wrong so i switched `projectInfo.locOnDisk` to `path.join(projectInfo.workspace, projectInfo.directory)` but i can switch it back

**Comment by tobespc** [comment]
can you switch this back please, locOnDisk is now correct . @tetchel

**Comment by tetchel** [comment]
it's fixed now
