### ISSUE TITLE
VSCODE needs to call 'cwctl bind' rather than directly call the pfe endpoint (remote architecture)

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#767]
The cwctl has a bind option that is to replace calling the /remote-bind/ endpoint directly

cwctl project bind
NAME:
   cwctl project bind - bind a project to codewind for building and running

USAGE:
   cwctl project bind [command options] [arguments...]

OPTIONS:
   --name value, -n value      the name of the project
   --language value, -l value  the project language
   --type value, -t value      the type of the project
   --path value, -p value      the path to the project

**Comment by tetchel** [comment]
blocked by https://github.com/eclipse/codewind/issues/830

**Comment by tetchel** [comment]
also blocked by `bind` not accepting a deployment ID

**Comment by tobespc** [comment]
we don't need a deployment id - we are going to take care of that @tetchel

**Comment by tetchel** [comment]
What do you mean, then how does it know which Codewind instance to bind the new project to

**Comment by tetchel** [comment]
https://github.com/eclipse/codewind/issues/894
