### ISSUE TITLE
ECLIPSE IDE needs to call cwctl bind rather than directly call the endpoint (remote architecture)

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#768]
The cwctl has a bind option that is to replace calling the /remote-bind/ endpoint directly

cwctl project bind
NAME:
cwctl project bind - bind a project to codewind for building and running

USAGE:
cwctl project bind [command options] [arguments...]

OPTIONS:
--name value, -n value the name of the project
--language value, -l value the project language
--type value, -t value the type of the project
--path value, -p value the path to the project

**Comment by jopit** [comment]
Change was made via PR https://github.com/eclipse/codewind-eclipse/pull/388
