### ISSUE TITLE
Manually triggering a build (IDE's) does not build with latest code (remote architecture)

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#770]
When manually triggering builds through the IDE's, the code is not being updated to the build/run container and so the build doesn't do anything.   Need to change the IDE's to call 'cwctl project sync' when a manual build is requested rather than call the remote api endpoint

**Comment by tetchel** [comment]
this is fixed in vs code, we are doing the sync now

**Comment by tobespc** [comment]
The proposed solution above may not be the best solution- apologies @tetchel  if you spent a long time on this.

If the filewatcherd tells cwctl of a file change (regardless of the state of autobuild), then we will sync that up to pfe.  What we need to do in pfe is not build if autobuild is off and then add a new cwcrl project build command

**Comment by tetchel** [comment]
so, i should remove the manual call to `sync` when user clicks build?

**Comment by tobespc** [comment]
yes please Tim, will give you a new cwctl to call shortly

**Comment by tobespc** [comment]
this is working ok at the moment as the old api is being called.  Adding a pass though to to put build on the cli is an enhancement, so adjusting this issue accordingly
