### ISSUE TITLE
`GET /projects`, locOnDisk is `codewind-version/undefined` (remote architecture)

### ISSUE THREAD

**Issue by jcockbain96** [eclipse/codewind#771]
**Codewind version:** latest

**IDE extension version:** Hybrid branch

**Description:**

Creating projects with the new remote architecture, when I then call `GET /api/v1/projects` I get `locOnDisk = codewind-workspace/undefined`. I don't know if this field is required anymore, as there's similar looking fields alongside it. 

![Screenshot 2019-10-22 at 11 01 02](https://user-images.githubusercontent.com/31372187/67276177-0962a700-f4bc-11e9-97f8-fe73a7cb3f12.png)

**Comment by tobespc** [comment]
fixed by this PR https://github.com/eclipse/codewind/pull/800
