### ISSUE TITLE
Eclipse panel help doesn't work

### ISSUE THREAD

**Issue by mattcolegate** [eclipse/codewind#773]
**Codewind version:** latest hybrid
**OS:** Windows 10

**Che version:** N/A
**IDE extension version:** 0.5.0v201910171920
**IDE version:** Eclipse 2019-06
**Kubernetes cluster:** N/A

**Description:** The Help ? icon on the following panels, when pressed, does nothing.
- New Codewind connection
- Add Existing Project to Codewind - Project Selection
- Add Existing Project to Codewind - Confirm Project Type
- Add Existing Project to Codewind - Project Type Selection

**Steps to reproduce:** Navigate to one of the above panels. Click the ? icon in the bottom left of the panel. Nothing occurs.

**Workaround:** N/A

**Comment by eharris369** [comment]
There is no integrated help for Codewind Eclipse because Eclipse has its own help system and it would be some work to write new documentation specifically for it.  I can look into removing the icons on the dialogs and wizards.

**Comment by eharris369** [comment]
I tried but could not get rid of the info button in dialogs and wizards.  There is a static `setDialogHelpAvailable` which will disable help on all Eclipse dialogs and wizards if false unless they explicitly call `setHelpAvailable`.  It would not be a good idea to change this.  Calling `setHelpAvailable(false)` if `setDialogHelpAvailable` is true has no effect.  The best solution is probably to have a single help page that points to the Codewind documentation and use this for all wizards and dialogs.

**Comment by eharris369** [comment]
PR for adding generic help: https://github.com/eclipse/codewind-eclipse/pull/667

**Comment by mattcolegate** [comment]
Verified - the help icon on the above pages, when clicked, opens generic help.
