### ISSUE TITLE
`PayloadTooLargeError` on repeat after importing a project (remote architecture)

### ISSUE THREAD

**Issue by jcockbain96** [eclipse/codewind#774]
**Codewind version:** Latest
**OS:** MacOs

**IDE extension version:** Hybrid Branch (Latest as of issue being raised)

**Description:**
The error displayed every few seconds in the logs of the PFE container, and interacting with the vsCode plugin felt slower (creating / deleting projects etc...)

**Steps to reproduce:**
1. Imported a relatively large Node.js project (but not with any out of the ordinary massive files). 
2. Project didn't build. PFE logs display the following error indefinitely, even after project is removed.

<img width="1680" alt="Screenshot 2019-10-22 at 11 20 47" src="https://user-images.githubusercontent.com/31372187/67277125-0a94d380-f4be-11e9-8892-f69f5baf5d60.png">

**Comment by stalleyj** [comment]
I'll pick this one up
