### ISSUE TITLE
VSCode plugin allows projects with the same name and displays the same projectID with all projects

### ISSUE THREAD

**Issue by james-wallis** [eclipse/codewind#775]
**Codewind version:** Latest local (remote)
**OS:** MacOS

**Description:**
I created a project with the name `noddy2` in my `codewind-workspace` which built and ran fine. Then I imported the same project into Codewind using the file selector import. Worked fine twice.
![image](https://user-images.githubusercontent.com/17385115/67276980-b1c53b00-f4bd-11e9-8b82-48721bf59e58.png)

The project ID for each of the `noddy2` projects is displaying the same in VSCode whereas when I exec into the PFE container I can see 3 distinct inf and projectIDs for each of the `noddy2` projects.

**Steps to reproduce:**
Create new Node.js app.
Import the same app from its location on the file system.

**Workaround:**

**Comment by tetchel** [comment]
ok, so the bug here is there should be a message like 'a project already exists at this location' ?

**Comment by cccanderson** [comment]
Is this unique to VS Code?  Or can you reproduce in Eclipse?

**Comment by tetchel** [comment]
this has been fixed with the shift to cwctl bind
