### ISSUE TITLE
2 default template repos missing a name (remote architecture)

### ISSUE THREAD

**Issue by jcockbain96** [eclipse/codewind#777]
**Codewind version:** Latest
**OS:** MacOs
**VScode:** Hybrid branch 

**Description:**

`No name available` for the second two default template repos.

**Steps to reproduce:**

Go to template source manager, I see the following table. 

![Screenshot 2019-10-22 at 11 26 24](https://user-images.githubusercontent.com/31372187/67277506-d1a92e80-f4be-11e9-8821-45b9b1f93ff1.png)

**Comment by tetchel** [comment]
i think it happens if repository_list.json already existed

https://github.com/eclipse/codewind/issues/718

**Comment by jcockbain96** [comment]
Ok, I'll close this one as there's already discussion on that issue.
