### ISSUE TITLE
Unclear delete message when removing project from Codewind (VSCode)

### ISSUE THREAD

**Issue by james-wallis** [eclipse/codewind#778]
**Codewind version:** Master
**OS:** MacOS

**Question synopsis:**

When removing a project from Codewind the VSCode plugin it asks whether we want to delete the files from the workspace (dialog box shown below).
![image](https://user-images.githubusercontent.com/17385115/67277554-f4d3de00-f4be-11e9-9ddf-aa96cf2d9421.png)

I think that having "cancel" to say no to deleting is confusing as it may give the impression that the delete process has already started. I'd suggest changing "cancel" to "no".

This probably needs some design input @tobespc.

**Comment by tetchel** [comment]
Agreed for sure that cancel is confusing here. 

But this is a limitation of this API - Cancel is always present in these dialogs. Delete Directory is the only button I provide. 

I could do No, Cancel, Delete Directory, but I think that's even worse.
