### ISSUE TITLE
Files not being removed from disk after project is removed (remote architecture)

### ISSUE THREAD

**Issue by liamchampton** [eclipse/codewind#779]
**Codewind version:** latest
**OS:** Macos
**IDE extension version:** vscode (hybrid)

**Description:**
Files not being deleted from disk after project is removed

**Steps to reproduce:**
1) Create a project locally, 
2) Wait for it to build and run
3) Remove the project

This will remove the project from the IDE but the files will still be left on disk. This _could_ be a result from https://github.com/eclipse/codewind/issues/766

**Comment by tetchel** [comment]
this is fixed now because vscode was using the wrong path from portal but it has been corrected

**Comment by makandre** [comment]
Files maybe removed from local disk now but the project files still lives in PFE's volume.  #819 tracks that problem.
