### ISSUE TITLE
VS Code Node.js vs Nodejs

### ISSUE THREAD

**Issue by jcockbain** [eclipse/codewind#784]
**Codewind version:** latest
**OS:** MacOs

**IDE version:** latest

**Question synopsis:**
This is a minor nit, but at the moment we display the following the information panel for a node project. Could language and projectType be made consistent? 

![Screenshot 2019-10-22 at 10 45 48](https://user-images.githubusercontent.com/31372187/67278960-fc48b680-f4c1-11e9-8b2f-787d25807a9f.png)

**Comment by tetchel** [comment]
`Node.js` project type is hard-coded into vs code tools, `nodejs` is the language as fetched from the project info (from the template). I would rather fix the latter because it is the one that is not correct

though the best fix would be the make the language `javascript` since that's the actual language

**Comment by tetchel** [comment]
going through old issues, are we going to action this? I think it has to be fixed from the portal/template side.

**Comment by jcockbain** [comment]
Trying to get this done now (to language=javascript), changing the field [here](https://github.com/kabanero-io/codewind-templates/blob/master/devfiles/index.json#L29) changes it for projects created from templates, and changing the what's set in cwctl does so for projects from local.

The projects are then building successfully, as its buildType mainly that matters internally. However, we do have a few places in PFE where we're still checking the language (e.g. some metrics things). Going through now and making sure we don't lose any functionality for a `javascript` project.
