### ISSUE TITLE
Failing to add project to workspace using the plugin (remote architecture)

### ISSUE THREAD

**Issue by liamchampton** [eclipse/codewind#786]
**Codewind version:** latest
**OS:** macOS

**IDE extension version:** vscode (hybrid)

**Description:**
Files not being added to vscode workspace if using the drop-down list from the extension and selecting `Add Project to Workspace`

**Steps to reproduce:**
1) Create new project
2) Chose the parent path (anything different to a workspace already open in vscode)
3) Wait for project to be running
4) Right click on the project and select `Add Project to Workspace`
5) The name will appear but no files under it

Possibly related to #766

![Screenshot 2019-10-22 at 11 52 07](https://user-images.githubusercontent.com/42477259/67279201-69f4e280-f4c2-11e9-8dfe-29e1df2d3522.png)

**Comment by tobespc** [comment]
this should be fixed by https://github.com/eclipse/codewind/pull/800

**Comment by cccanderson** [comment]
If this is still occurring, is it unique to VS Code?  Or does it happen in Eclipse, too?

**Comment by jcockbain** [comment]
@liamchampton - this appears fixed for me, can you check again?

**Comment by liamchampton** [comment]
Cannot reproduce, closing.
