### ISSUE TITLE
Eclipse Add Template Source panel: window title incorrect

### ISSUE THREAD

**Issue by mattcolegate** [eclipse/codewind#787]
**Codewind version:** latest hybrid
**OS:**  Windows 10

**Che version:** N/A
**IDE extension version:** 0.5.0v201910171920
**IDE version:** 2019-06
**Kubernetes cluster:** N/A

**Description:** The 'Add Template Source' panel has the window title _Add Repositories_. It should be _Add Template Source_.

**Steps to reproduce:** Start Codewind and right-click Local in the Codewind Explorer view. Select Manage Template Sources... and click the Add button in the resulting panel. Observe window title of new panel.

**Workaround:** N/A

**Comment by mattcolegate** [comment]
![$1635EDF71CAF1F15](https://user-images.githubusercontent.com/15730986/67279401-d07a0080-f4c2-11e9-8707-7b1a1a6ff28a.jpg)

**Comment by eharris369** [comment]
Fixed by PR: https://github.com/eclipse/codewind-eclipse/pull/469

**Comment by mattcolegate** [comment]
Verified.
