### ISSUE TITLE
Project from default Python + Go templates display `language: unknown`

### ISSUE THREAD

**Issue by jcockbain** [eclipse/codewind#789]
**Codewind version:latest**
**OS:MacOs**

**IDE version:latest**

**Description:**
We currently look for `package.json`, `Package.swift`, and `Pom.xml` (and certain snippets therein) to detect Node, Swift and Java project languages and types.

This means creating a Python project from our template is `unknown`. Previously, we read the language and type from the template definition. We may want to look at this again or enhance our detection code. 

**Steps to reproduce:**
1. Create a project from the default python template, in VS code.
2. Project is displayed as `language: Unknown` 

![Screenshot 2019-10-22 at 12 00 37](https://user-images.githubusercontent.com/31372187/67280192-7da14880-f4c4-11e9-8013-954bc83c7123.png)

**Comment by jcockbain96** [comment]
on looking at the `cwctl` code, we do look for a `pipfile`. However, it seems that our template doesn't have this file. https://github.com/eclipse/codewind-installer/blob/master/utils/project.go#L37

**Comment by jcockbain96** [comment]
@makandre - should we have a `pipfile` in our Python template? Seeing it was your change that added the Python detection code.

**Comment by makandre** [comment]
Perhaps... Codewind never detected python as a language, my changed didn't change that behaviour; the `pipfile` detection was added specifically to address a scenario for Appsody.

So we could add one to our template if it fits our model.

**Comment by jcockbain96** [comment]
Ok I understand, this is more about whether we take projectType and language from a templates data when we create a project from it then. 

We did at one point, but reverted to using the type detection code on every project we create. I think it's odd to create a project from our own template and then have `language: unknown`. 

My preference would be to read from the template language and style on the template object, and then fallback to type detection if they don't exist. 

@tobespc can up add a Portal tag as think this is all `cwctl` and `pfe`.

**Comment by tetchel** [comment]
Go has the same problem

**Comment by makandre** [comment]
When binding an existing project, the templates aren't really involved tho

**Comment by jcockbain96** [comment]
Yep, reading from template info wouldn't affect the binding from existing project scenario.

**Comment by ebuckle** [comment]
I'll take a look into this
