### ISSUE TITLE
Error creating new project (CHE)

### ISSUE THREAD

**Issue by markcor11** [eclipse/codewind#792]
**Codewind version:**:  latest

**Description:**

Codewind CWCTL fails to bind a project in Che

When determining PFE target,  cwctl uses http rather than https

https://github.com/eclipse/codewind-installer/blob/33910a4a750b5d1e48f840a2c26c361b924704da/config/config.go#L26

Attempting to run the CLI manually through theia pod : 

```
/projects/importedStuff/micro1 $  /tmp/cwctl project bind  --name micro1 -l  java --type liberty --path /projects/importedStuff/micro1
<html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>nginx/1.16.1</center>
</body>
</html>
```

**Steps to reproduce:**

Set Che and Codewind try to create a project

Error : 

![Screenshot 2019-10-22 at 13 38 39](https://user-images.githubusercontent.com/28102564/67286420-47b69100-f4d1-11e9-98d3-c15b4aec58f8.png)

**Comment by cccanderson** [comment]
We need to be using https: whenever possible!

**Comment by tobespc** [comment]
can't recreate this

**Comment by markcor11** [comment]
can't reproduce this anymore
