### ISSUE TITLE
Spring Boot app.log needs to show exposed port for the localhost EP links

### ISSUE THREAD

**Issue by liamchampton** [eclipse/codewind#795]
**Codewind version:** latest
**OS:** macOS
**IDE extension version:** vscode (hybrid)

**Description:**
In the logs of a Spring project it explicitly states: 
```
2019-10-22 12:28:19.543  INFO 80 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8080 (http)
The following endpoints are available by default :-
  Health        : http://localhost:8080/health
  Application   : http://localhost:8080/v1/
```
which is correct in the context on the `app.log` since it is inside the container. However, to access these application end points it needs to use the exposed port to work. This should be more explicit for the end user

**Steps to reproduce:**
1) Create java spring project
2) Wait for project to be running
3) Right click on project and click `Show all logs`
4) Scroll to bottom to see the log text shown above

**Comment by stalleyj** [comment]
This is true of all project types and an expected consequence of containerised development.  Plus, if they are using Codewind, they don't really need to know/care about the port so there is nothing to fix here.

**Comment by hhellyer** [comment]
Agreed, closing.
