### ISSUE TITLE
Include social feed on our landing page

### ISSUE THREAD

**Issue by AndyRWatson** [eclipse/codewind#797]
**Codewind version: 0.4
MacOS

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description of the enhancement:**
We have a number of social feeds which are linked from our main landing page, but would like to see a live feed of new content on the landing page (similar to that also used  at the bottom of https://Kabanero.io )

**Proposed solution:**

**Comment by sishida** [comment]
Tagging @kimholmes for design and @travis1111 for website content.

**Comment by travis1111** [comment]
Will work on this as soon as I have the design.
