### ISSUE TITLE
Go app state is stuck on 'Starting'

### ISSUE THREAD

**Issue by keithchong** [eclipse/codewind#8]
I have a Go project with a generated OpenAPI server stub running in Codewind.  The image appears ok, and the container is running.  The app seems to be running (I can access the API endpoints) but the state in the two VS Code and Eclipse IDE plugins show "Starting" and doesn't turn to "Running".

Try reproducing with these files:

[zGoProj.zip](https://github.com/eclipse/codewind/files/3339703/zGoProj.zip)

**Comment by keithchong** [comment]
![Screen Shot 2019-06-28 at 10 50 38 AM](https://user-images.githubusercontent.com/7726022/60350922-9d9b8200-9992-11e9-8952-b64be7fa7dd7.png)

For this, see routers.go
![Screen Shot 2019-06-28 at 10 52 24 AM](https://user-images.githubusercontent.com/7726022/60351026-dcc9d300-9992-11e9-9c43-096752465345.png)

**Comment by tetchel** [comment]
is it because the context root is /v1/ instead of / so filewatcher is pinging a 404?

**Comment by keithchong** [comment]
I can try, but are users supposed to know to edit that file?

**Comment by tetchel** [comment]
yes, they are

**Comment by keithchong** [comment]
Ok

**Comment by keithchong** [comment]
Thanks @tetchel , that worked.

**Comment by tetchel** [comment]
awesome

**Comment by keithchong** [comment]
@tetchel , how about a Node.js app?  How is the "Running" state determined?   The Node.js example has the value set to "" and its status is "Running":

![Screen Shot 2019-06-28 at 2 29 03 PM](https://user-images.githubusercontent.com/7726022/60363299-27f2de80-99b1-11e9-8f9c-a8a9c116e100.png)

My OpenAPI nodejs is still stuck on Starting, but the server is actually running.

**Comment by tetchel** [comment]
look at the project overview page and see the "application endpoint", that is what turbine pings to determine started-ness

**Comment by keithchong** [comment]
VSCode IDE-Plugin: Application Endpoint = http://localhost:32954/
Eclipse IDE-Plugin: Application URL = http://localhost:32954/

You guys should sync up these labels ;-)

**Comment by tetchel** [comment]
and in cw-settings, it's `contextroot`. we know :(

**Comment by keithchong** [comment]
"contextRoot": "",

**Comment by keithchong** [comment]
The sample nodejs app that is "Running" has the same/similar contextRoot and URL values

**Comment by keithchong** [comment]
@tetchel, could you clarify, it's `contextroot`

**Comment by tetchel** [comment]
yes, as in `.cw.settings`.

**Comment by keithchong** [comment]
Ok it worked.  I thought I had to change the R to r...
