### ISSUE TITLE
User must set world-readable/writable permissions (777) on their NFS server path in order to use it with Codewind/Che

### ISSUE THREAD

**Issue by jgwest** [eclipse/codewind#80]
In order to use NFS with Codewind/Che, the user is required to set their NFS server path as world readable/writeable, which has significant security connotations, and is also just a bad user experience (it throws a nasty error if you miss this step, and if we can make it work specific user intervention, like setting 777, then we should).

Back in Microclimate, this was reported by a customer as `portal/560` back in October 2018. 

Presuming we want to get rid of the NFS 777 issue, it seems like we would:

1) Ensure that we have Codewind docs which indicating, for each Kube distro we support:
- Any additional configuration needs on the Kube side to make this work
- Any additional configuration needed on the NFS server side, to make this work.

2) Ensure that when you follow those docs, you do not need to 777 your Codewind NFS dirs (and this step might require Codewind/Cheia tweaks)

We currently mention NFS in our docs, here (thought it is limited to the IBM Cloud Private context): https://www.eclipse.org/codewind/installoncloud.html

**Comment by rajivnathan** [comment]
@johnmcollier mentioned he can review whether this is still needed.

**Comment by micgibso** [comment]
@johnmcollier @rajivnathan Is this still needed?
