### ISSUE TITLE
CWCLI: No output from project create anymore

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#803]
The project create command used to have json output that included a status and potentially an error message.  The latest cwcli does not have any output.

**Comment by eharris369** [comment]
@tetchel

**Comment by eharris369** [comment]
Tim noticed that this was working this morning so it is likely PR https://github.com/eclipse/codewind-installer/pull/156/files

**Comment by stalleyj** [comment]
I'll take it

**Comment by stalleyj** [comment]
@eharris369 @tetchel This is now fixed, sorry my refactor caused this issue.https://github.com/eclipse/codewind-installer/pull/161

**Comment by eharris369** [comment]
This is fixed.  Thank you!
