### ISSUE TITLE
url for odo project is only created when project successfully being created

### ISSUE THREAD

**Issue by yangcao77** [eclipse/codewind#806]
**Codewind version:**
**OS:** Mac os

**Che version:** 7.2.0

**Description:**
url for odo project is only created when project successfully being created
If the first time creation failed. The url won't be created for any following build.

**Comment by GeekArthur** [comment]
Please assign this issue to me.

**Comment by GeekArthur** [comment]
Fix has been merged and verified, think we can close this.
