### ISSUE TITLE
Document `bind`, `sync`, and `upgrade` commands in cwctl readme

### ISSUE THREAD

**Issue by jcockbain** [eclipse/codewind#810]
**Codewind version:** Latest
**OS:** Mac

**Description of the enhancement:**
We now offer a command to `bind` an existing local project through `cwctl`, however I cannot see any information on it in the readme for the repo (https://github.com/eclipse/codewind-installer/blob/master/README.md#project). 

**Proposed solution:** 
Add details for the command and its requisite flags.

**Comment by jcockbain96** [comment]
Likewise sync

**Comment by jcockbain96** [comment]
bind and sync were documented as part of https://github.com/eclipse/codewind-installer/commit/aaf2dfb2d4147f6c8fbad9a882517294f893906b, upgrade still needs to be added.

**Comment by jcockbain** [comment]
All in the readme now
