### ISSUE TITLE
add medium link to social tab on landing page

### ISSUE THREAD

**Issue by AndyRWatson** [eclipse/codewind#811]
**Codewind version:**0.4
**OS:** MACOS

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description of the enhancement:**
In addition to youtube,twitter, github we also have a medium.com publication for codewind related blogs.   We should include this in our social links toolbar 

**Proposed solution:** 
add https://medium.com/codewind   link to our social toolbar on https://codewind.dev

**Comment by sishida** [comment]
Tagging @kimholmes for design and @travis1111 for website content.

**Comment by travis1111** [comment]
Will work on this

**Comment by travis1111** [comment]
@kimholmes This is what I came up with, please let me know if design is ok for this.  thanks

![image](https://user-images.githubusercontent.com/35569780/68307831-db639200-0079-11ea-9466-a02a9be083db.png)

I got the logo from Medium's official logo repo.

One thing I noticed, for other branding logos, we changed the color,  I think we should not alter colors:

https://www.youtube.com/about/brand-resources/#logos-icons-colors

> Do not Use any colors other than red, almost black, or white

https://github.com/logos

> do not Change the colors, dimensions or add your own text/images

https://mattermost.org/brand-guidelines/

> Do not distort or alter the Mattermost logo.


https://about.twitter.com/content/dam/about-twitter/company/brand-resources/en_us/Twitter_Brand_Guidelines_V2_0.pdf

> Only show the logo in Twitter blue or white. • Don’t alter, rotate, or modify the logo

@kimholmes  Please take a look.

**Comment by AndyRWatson** [comment]
Do we have an outlook on this. We are keen to ensure all associated link are available on our landing page. This needs to make out next landing page update. Can we ensure it’s labelled accordingly please :-)

**Comment by travis1111** [comment]
@kimholmes could you please let me know if it is OK to just use the black medium logo? also, please double check the logo guidelines for other logos, I do have concerns.

@AndyRWatson I am ready to push the code as soon as I have the agreement from design team.

thanks

**Comment by AndyRWatson** [comment]
thanks @travis1111

**Comment by AndyRWatson** [comment]
If we can not resolve the design before 0.6.  I would like to propose a generic blog log or replace the icon with the word "blog" in blue.  This shouldn't be out of place against the  Docs/News text which is to the left of it (in @travis1111 preview above).

**Comment by thisguy-1** [comment]
@sishida  So I can be assigned

**Comment by malincoln** [comment]
is this still on track for 0.7.0?

**Comment by sishida** [comment]
We are currently linking to the blog with the word "Blog" on the website. I am leaving this issue open if we want to replace the word with the Medium logo later, but it doesn't have to be done for 0.7.0.

**Comment by AndyRWatson** [comment]
I think I am happy to close for now with the blog link.   There are some conversations around whether we should host our own blog on our website ( @kimholmes )  vs uses medium,  so lets close for now

**Comment by kimholmes** [comment]
New design:
![CW_headerNav2](https://user-images.githubusercontent.com/21316329/70646285-913f7480-1c14-11ea-992d-828da89f6a18.png)

[SocialLogos12_11_19.zip](https://github.com/eclipse/codewind/files/3951861/SocialLogos12_11_19.zip)

**Comment by travis1111** [comment]
Thanks I will work on it

**Comment by sishida** [comment]
@kimholmes @travis1111 Please see Andy's comment above. We are not sure if we want to continue using Medium for blogs or not. It might be safest to hold off from adding the logo for now and wait until we get confirmation for how we want to move forward. Thanks!
