### ISSUE TITLE
Extension project types missing from result of project-types API

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#817]
Using the latest PFE pulled and built this morning, if I have all extension repos enabled, the result of project-types API is only showing default Codewind project types.  See attached output from templates/repositories and project-types APIs.

[repos.txt](https://github.com/eclipse/codewind/files/3763103/repos.txt)
[projectTypes.txt](https://github.com/eclipse/codewind/files/3763104/projectTypes.txt)

**Comment by makandre** [comment]
Appsody not showing is possible due to us switching to getting appsody extension from eclipse downloads now, however there's a bug where the bits are getting installed to the wrong place

**Comment by eharris369** [comment]
This is working now.
