### ISSUE TITLE
SVT: ODO Projects failing to build in Che Workspace

### ISSUE THREAD

**Issue by naveenkaratekid** [eclipse/codewind#821]
**Codewind version: 0.5.0**
**OS: RHEL**
**Che version: 7.2**
**IDE extension version: 0.5.0**
**IDE version: 7.1**

**Description:**
ODO templates for Python, NodeJS, and Perl are failing to build.

**Steps to reproduce:**
1. Create new ODO project.
2. Look at the project build status

Python log file:
```
Creating, building and deploying odo application
Step 1 of 4:
- Creating odo component: cw-odo-py
 ✗  this directory already contains a component
- Failed to create odo component: cw-odo-py
```
<img width="1502" alt="Screen Shot 2019-10-23 at 1 43 42 PM" src="https://user-images.githubusercontent.com/19738071/67419703-2fab4400-f59b-11e9-98e4-748187cbe2b5.png">

**Comment by GeekArthur** [comment]
From your log, issue is you have danging project directory includes .odo folder, that blocks you create new project, you can remove the dangling directory then create project again

**Comment by GeekArthur** [comment]
This is the real error: `this directory already contains a component`

**Comment by GeekArthur** [comment]
@mmulholl This one is not stopship, please remove the stopship label. We already guided @naveenkaratekid to make his build work in the meeting with SVT folks, issue is he didn't pull the latest RBAC yaml files to apply for adding additional rules to access OpenShift resource for ODO.

**Comment by GeekArthur** [comment]
Given the step has been documented before here: https://github.com/eclipse/codewind-odo-extension#add-additional-rules-to-support-codewind-odo-extension, and will be published to landing page through this PR: https://github.com/eclipse/codewind-docs/pull/180, think we can close this issue.
