### ISSUE TITLE
Hybrid: use kubectl command to open a shell in the application container

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#822]
So far we have avoided the need to use kubectl in the IDEs so it makes sense to have a command in cwctl that the IDEs can call to set this up.

**Comment by tobespc** [comment]
so to clarify what is needed here is you want cwctl  to wrap running 'kubctl exec -it podID bash' ?
how you will you invoke this ?  Will you run up a terminal, execute this command in the terminal so that the shell appears there ?

**Comment by eharris369** [comment]
Yes, that is what we are looking for and the command will be executed in a terminal.

**Comment by tobespc** [comment]
I think we should stage the delivery for this.  

- Add the shell command to the cwctl but assume all things like context, security, kube is all pre req

- Enhance the cwctl to take care of setting the context etc

**Comment by jopit** [comment]
Do the Go libraries provide a way to easily do this?  Portal to investigate.

**Comment by jopit** [comment]
The IDEs can use kubectl to implement this without needing changes in portal.

**Comment by eharris369** [comment]
Eclipse IDE PR: https://github.com/eclipse/codewind-eclipse/pull/689

**Comment by tetchel** [comment]
This is done so I'm closing it; the intellij component can be considered as part of the overall intellij hybrid work.
