### ISSUE TITLE
Open Container Shell fails if user sets 'git bash' as default shell in vscode

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind#823]
**Codewind version:** 0.4.0
**OS:** Windows

Reported by a Windows user who has Git Bash set as their default shell in vscode

I am going through the "Kabanero Developer Experience - Getting Started" instructions on Windows - have gotten to the codewind development section, specifically to the point of adding new code to the sample app and forcing a code rebuild etc (here: https://github.com/gcharters/kabanero-dev-getting-started#developing-cloud-native-applications---codewind) - as a windows user, trying to open a Container shell to issue the touch to cause dev mode to see the change ... opening the container shell fails with:
```
xxxx@xxxx MINGW64 /c/codewind-workspace/kabanero-mp-project
$ docker exec -it 401ba8a4e332fb7166e10b3bc7cc69bd20e9d9dbf24510c455e58ea1f2b212dd /usr/bin/env sh -c "if type bash > /dev/null; then bash; else sh; fi"
OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "exec: \"C:/Program Files/Git/usr/bin/env\": stat C:/Program Files/Git/usr/bin/env: no
such file or directory": unknown
```
Looks like the codewind 'open container shell' code runs the `docker exec` command using the user's default shell, and git bash does some magic with absolute paths on windows, changing `/usr/bin/env` to `C:/Program Files/Git/usr/bin/env`, before running the command.  Since there is no such file inside the container, the call fails.  See https://github.com/moby/moby/issues/24029

Is there something we can do in the codewind code to prevent this from happening?

**Comment by tetchel** [comment]
we can try [this](https://github.com/moby/moby/issues/24029#issuecomment-250412919)

> Prefixing the path with a double slash (//bin/bash) should prevent this, or you can set MSYS_NO_PATHCONV=1
