### ISSUE TITLE
[odo] SVT: Timeout error with 'deploymentconfig' selector 

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#828]
**Codewind version:** [0.5.0 ](https://raw.githubusercontent.com/eclipse/codewind-che-plugin/master/devfiles/0.5.0/devfile.yaml)
**OS:** Red Hat Enterprise Linux 7 (64 bit)

**Che version:** 7.2.0
**Kubernetes cluster:** OKD/Openshift 

**Description:** There are some timeout errors with the 'deployconfig' selector after creating ODO projects. This is an intermittent error, so it could not be reproduced all the time.

<img width="1676" alt="Screen Shot 2019-10-23 at 4 40 44 PM" src="https://user-images.githubusercontent.com/49531960/67432241-f206e500-f5b3-11e9-9359-1c5e4bfc6c3e.png">

```
Creating, building and deploying odo application
Step 1 of 4:
- Creating odo component: cw-cw-odo-python-1
Warning: python is not fully supported by odo, and it is not guaranteed to work.
 •  Validating component  ...
 ✓  Validating component [13ms]
Please use `odo push` command to create the component with source deployed
- Successfully created odo component: cw-cw-odo-python-1
Step 2 of 4:
- Building and deploying odo component: cw-cw-odo-python-1
Validation
 •  Checking component  ...
 ✓  Checking component [59ms]
Configuration changes
 ✓  Initializing component
 •  Creating component  ...
 ✓  Creating component [105ms]
Pushing to component cw-cw-odo-python-1 of type local
 •  Checking files for pushing  ...
 ✓  Checking files for pushing [86ms]
 •  Waiting for component to start  ...
 ✗  Waiting for component to start [4m]
 ✗  waited 4m0s but couldn't find running pod matching selector: 'deploymentconfig=cw-cw-odo-python-1-app'
- Failed to build and deploy odo component: cw-cw-odo-python-1
```

**Steps to reproduce:**
1. Prepare an OKD Cluster 
2. Install Che 
3. Deploy a Codewind workspace
4. Create an ODO project (i.e., ODO Python)
5. Project will fail: [Stopped] [Build failed - Creating image for build failed]

@jagraj

**Comment by GeekArthur** [comment]
This could be a timing due to performance on vLaunch VMs recently,  `deploymentconfig` label is added by odo build engine instead Codewind, if the label can not be added within 4 mins then we will hit this issue.

**Comment by GeekArthur** [comment]
Performance on vLaunch VMs has been resolved and we don't hit this issue any more, close this.
