### ISSUE TITLE
SVT: [ODO] User must ensure that there is a persistent volume available for each project that will be created

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#829]
**Codewind version:** [0.5.0 ](https://raw.githubusercontent.com/eclipse/codewind-che-plugin/master/devfiles/0.5.0/devfile.yaml)
**OS:** Red Hat Enterprise Linux 7 (64 bit)

**Che version:** 7.2.0
**Kubernetes cluster:** OKD/Openshift 

**Description:** User must ensure that there is a persistent volume available for each project that will be created. Therefore, we must include this information in the documentation.

If the user's cluster does not have persistent volumes available, several errors can occur. For example, projects may get stuck in the "Stopped" state. This is what I saw with the ODO Python and ODO Node JS projects:

<img width="1664" alt="Screen Shot 2019-10-23 at 4 46 06 PM" src="https://user-images.githubusercontent.com/49531960/67432758-d5b77800-f5b4-11e9-976e-4cdd63016d98.png">

```
time="2019-10-23T17:25:09Z" level=info msg="receive a signal to stop all process & exit" signal=terminated 
time="2019-10-23T17:25:09Z" level=info msg="stop the program" program=run 
time="2019-10-23T17:25:09Z" level=info msg="force to kill the program" program=run 
time="2019-10-23T17:25:09Z" level=error msg="program stopped with error:signal: killed" program=run 
time="2019-10-23T17:25:09Z" level=info msg="Stopped by user, don't start it again" program=run 
2019/10/23 17:25:10 [go-init] Main command failed
2019/10/23 17:25:10 [go-init] exit status 255
2019/10/23 17:25:10 [go-init] No post-stop command defined, skip
rpc error: code = Unknown desc = Error: No such container: 17d21409c877c513bfc7845d40b245573fde316263a53a448c1e3dc840dc4e16
```

<img width="1663" alt="Screen Shot 2019-10-23 at 4 45 41 PM" src="https://user-images.githubusercontent.com/49531960/67432815-ed8efc00-f5b4-11e9-8550-83d104ac4e46.png">

```
time="2019-10-23T17:24:37Z" level=debug msg="wait program exit" program=run 
time="2019-10-23T17:25:02Z" level=info msg="receive a signal to stop all process & exit" signal=terminated 
time="2019-10-23T17:25:02Z" level=info msg="stop the program" program=run 
time="2019-10-23T17:25:02Z" level=info msg="force to kill the program" program=run 
time="2019-10-23T17:25:02Z" level=error msg="program stopped with error:signal: killed" program=run 
time="2019-10-23T17:25:02Z" level=info msg="Stopped by user, don't start it again" program=run 
2019/10/23 17:25:03 [go-init] Main command failed
2019/10/23 17:25:03 [go-init] exit status 255
2019/10/23 17:25:03 [go-init] No post-stop command defined, skip
rpc error: code = Unknown desc = Error: No such container: 737917ff39e4fb697ce8d43ce3291c6d29ec9d1358821c1ced9435c8e8a36f31
```

@jagraj

**Comment by sishida** [comment]
ID will defer this update for a refresh early next week if we can't complete it today.

To consider: How does a user configure a persistent volume? The only mention of persistent volume in our docs so far is in https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/mdt-che-roks.md.

**Comment by sishida** [comment]
Update Troubleshooting "Creating a new project" section.

The Problem: You cannot create a project if a PV is unavailable.

Workaround: Check to ensure that a persistent volume is available for each project that you want to create. Run the `kubectl get pv` command.

**Comment by sishida** [comment]
Hi, @jingfuwang, This troubleshooting info now appears on the website: https://www.eclipse.org/codewind/troubleshooting.html#project-creation-fails-if-a-persistent-volume-pv-is-unavailable
Is this issue good to close now? 😃

**Comment by GeekArthur** [comment]
@sishida Yep, it looks good to me. @sujeilyfonseca Can you close this issue since you are the author and this issue should be due to PV is not available.
