### ISSUE TITLE
cwctl bind needs to provide json output in success case

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#830]
The commands the IDE uses have to give JSON output, but it looks like `bind` has json output only in the error case, and rejects the `-j` flag.

Every command which the IDEs consume should accept `-j`, have a `success` status, and an `error` string if the status is not `OK` and/or the exit code is not 0.

```
[ /programs/codewind-vscode/dev ] 46 (master) $ bin/darwin/cwctl project bind --name hi --language test --type docker --path "/Users/tim/codewind-workspace/goo"
Returned projectid 3d387f30-f5d6-11e9-9155-f178ced54441
Upload status:200 OK for file: .cw-settings
Upload status:200 OK for file: Dockerfile
Upload status:200 OK for file: Jenkinsfile
Upload status:200 OK for file: README.md
Upload status:200 OK for file: chart/microclimategotemplate/Chart.yaml
Upload status:200 OK for file: chart/microclimategotemplate/templates/deployment.yaml
Upload status:200 OK for file: chart/microclimategotemplate/templates/service.yaml
Upload status:200 OK for file: chart/microclimategotemplate/values.yaml
Upload status:200 OK for file: main.go
Upload end status:200 OK
[ /programs/codewind-vscode/dev ] 46 (master) $ 
```

the output should minimally be
```
{
  "status": "OK",
  "projectID": "3d387f30-f5d6-11e9-9155-f178ced54441"
}
```

it could have an array of uploaded files too (and their success statuses?), could also have an `upload-status: "OK"` for the "end status".

**Comment by tetchel** [comment]
also `sync`

**Comment by james-wallis** [comment]
@tobespc please assign me

**Comment by tetchel** [comment]
Also the error cases of the `templates repos` commands

**Comment by tetchel** [comment]
added some more detail to issue description

**Comment by tobespc** [comment]
> Also the error cases of the `templates repos` commands

This should be a new work item to cover all error cases

**Comment by james-wallis** [comment]
About to put a PR up which would default to printing the following into the terminal. A further PR would follow enabling a global `--json` flag into the CLI and if it isn't specified the JSON response will be printed in a more readable format.

For `bind`
```
{
        "ProjectID": "15fdace0-f70e-11e9-a235-118bb4d3585f",
        "ResponseStatus": "200 OK",
        "ResponseStatusCode": 200,
        "UploadedFiles": [
                {
                        "FilePath": ".cw-settings",
                        "ResponseStatus": "200 OK",
                        "ResponseStatusCode": 200
                },
                {
                        "FilePath": ".dockerignore",
                        "ResponseStatus": "200 OK",
                        "ResponseStatusCode": 200
                },
                {
                        "FilePath": ".gitignore",
                        "ResponseStatus": "200 OK",
                        "ResponseStatusCode": 200
                },
        ]
}
```

For `sync`
```
{
        "ResponseStatus": "200 OK",
        "ResponseStatusCode": 200,
        "UploadedFiles": [
                {
                        "FilePath": ".cw-settings",
                        "ResponseStatus": "200 OK",
                        "ResponseStatusCode": 200
                },
                {
                        "FilePath": ".dockerignore",
                        "ResponseStatus": "200 OK",
                        "ResponseStatusCode": 200
                },
        ]
}
```

**Comment by james-wallis** [comment]
@tetchel using a global flag will mean that the CLI command will be `cwctl --json project bind -l nodejs -t nodejs -p ~/codewind-workspace/anothernodeapp -n finalapp12`. 

FYI I'll be changing the `status` and `install` commands to use the global `--json` flag but for the moment they will work as normal until the plugins change to use the global. I'm happy to do the work for the plugins to change them.
