### ISSUE TITLE
Return unknown status when a project is being built for the first time

### ISSUE THREAD

**Issue by rajivnathan** [eclipse/codewind#831]
Parent issue: https://github.com/eclipse/codewind/issues/159

**Description of the enhancement:**

Turbine changes required to improve status representation next to projects

**Proposed solution:** 

See https://github.com/eclipse/codewind/issues/159#issuecomment-538069212

**Comment by yangcao77** [comment]
can assign this to me

**Comment by rajivnathan** [comment]
Looks like this change is causing the build step to be skipped. If I revert the change I get the build status back. Sounds like something is missing in the current logic.

**Comment by rajivnathan** [comment]
After looking into this further the build status is being sent to the IDEs. The only difference now is the appStatus: Stopped is no longer being sent on initial project creation.
