### ISSUE TITLE
Level set on how we expect the cwctl to behave and be used

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#834]
At some point, the cwctl will be made production ready . We are not at this point yet

Current status -

The main driver of cwctl (from a users perspective) is still via the IDE's.  A codewind user does not need to know about the cli (ignoring the upcoming security stuff in this comment)

The IDE's call cwctl to trigger actions.  cwctl should return a yes/no on the action completing but any further responses are sent back via the socket communication method. 

For cwctl, responses are output to the command line

cwctl does output messages to the screen but this is really aimed at us right now to help with debugging, its not been designed with any particular output in mind

**Comment by jopit** [comment]
- Return same data as current REST APIs
- Return human-readable output unless JSON requested via -j flag

- Look into glog for logging.

Questions to be resolved
- How to handle stdout/stderr -- what kind of output should go to which stream?
- Best way to document the cwctl API?

**Comment by tobespc** [comment]
this is done, closing
