### ISSUE TITLE
Node.js app fails when Node.js version > 8, due to appmetrics compatibility

### ISSUE THREAD

**Issue by NikCanvin** [eclipse/codewind#836]
**Codewind version:** 0.4.0
**OS:** MacOs

**Che version:** 
**IDE extension version:** 
**IDE version:**
**Kubernetes cluster:**

**Description:**
I'm trying to do this: https://github.ibm.com/dev-ex/devAdvocacy/issues/147
Been chatting to Toby about this issue.
Appmetrics is hardcoded to 4.0.1, when using Express Node.js template
But even when I force appmetrics up to 5.0.5 (which should support up to node12), I still get appmetrics.node compatilibity errors, blocking the app running

**Steps to reproduce:**
1. create new Node.js app from Express template
2. change dockerfile, to "FROM node:12-stretch"

**Workaround:**

**Comment by tobespc** [comment]
This can be fixed by making sure the node_modules is deleted so forcing a rebuild of the image.   This is fixed in the latest version of codewind

**Comment by NikCanvin** [comment]
yeah - I can workaround this issue (until 0.6.0 comes along), as Toby says, a manual flushing of node_modules in the app container
