### ISSUE TITLE
IDE support for Kube

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind#839]
This scenario involves developing locally in the IDE but building and running the application in a kube cluster. We have been calling this hybrid, but hybrid is not a good "official" name for this capability, no-one will understand it without an explanation and without an explanation people may think its something to do with could developing specifically for Hybrid Cloud.

See this design issue for the original basic requirements
- [Design issue for developing locally, building and running in kube (hybrid scenario)](https://github.com/eclipse/codewind/issues/393)

**Comment by sishida** [comment]
IDE issue for hybrid support.

**Comment by micgibso** [comment]
@jopit Is this for 0.6.0?

**Comment by jopit** [comment]
Not for 0.6.0 -- I've changed the release.

**Comment by sishida** [comment]
@jopit Is this issue ready for documentation?

Currently we have remote documentation in this pull request: https://github.com/eclipse/codewind-docs/pull/204/files

But if we need any additional info, please let us know. Thank you!

**Comment by sishida** [comment]
@jopit Hi, John, Is this issue good to close, or should we move the release out to something like 0.9.0? Thanks!

**Comment by sishida** [comment]
Met with John and team today. This issue does not need anymore documentation work. John will close this issue later.

**Comment by malincoln** [comment]
@jopit pls verify and close. Thanks
