### ISSUE TITLE
IDEs should use CLI for template repo management

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#841]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description of the enhancement:**

IDEs should use the CLI's template repo management commands:

```
NAME:
   cwctl templates repos - Manage template repos

USAGE:
   cwctl templates repos command [command options] [arguments...]

COMMANDS:
   list, ls    List available template repos
   add         Add a template repo
   remove, rm  Remove a template repo
```

**Proposed solution:**

**Comment by tetchel** [comment]
https://github.com/eclipse/codewind/issues/847

**Comment by makandre** [comment]
FYI, as part of #564 `cwctl templates repo remove` will require name to be passed to it as well.

**Comment by jopit** [comment]
@makandre are you ok for this issue to be closed?

**Comment by makandre** [comment]
I've verified vscode/theia.  Will close after verifying Eclipse today

**Comment by makandre** [comment]
Good on Eclipse as well
