### ISSUE TITLE
Correcting installoncloud.md

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind#843]
(DONE) 0.5.0 refresh:
1️⃣(@GeekArthur) Beginning with https://github.com/eclipse/codewind-docs/pull/180, we are missing some content. We need to add it back in and edit accordingly.
- We should also maintain the single code block as mentioned in https://github.com/eclipse/codewind/issues/708, and we also need to fix the link so it no longer connects to codewind.dev. See https://github.com/eclipse/codewind-docs/pull/187.

(TO DO) 0.6.0 release:
2️⃣Make sure that mdt-che-overview.md is accurate and up to date. Make it similar in format to https://www.eclipse.org/codewind/mdt-vsc-overview.html.
3️⃣Then, we need to add mdt-che-overview.md into the landing pages. Place it into line 54 of https://github.com/eclipse/codewind-docs/blob/master/docs/_data/docstoc.yml file and remove the installoncloud.md file.
4️⃣Add new file for installing generic Codewind for Eclipse Che.

**Comment by GeekArthur** [comment]
Please assign to me.

**Comment by sishida** [comment]
@elsony Hi, Elson, Jingfu and I have discussed this issue. Could you please add your approval as a committer so that we can merge? Thank you!

**Comment by sishida** [comment]
@GeekArthur Hi, Jingfu, Were you planning to add any further edits/PRs to the installoncloud.md file for 0.6.0? @micgibso needs to edit installoncloud.md for some upcoming changes and can also help with this issue.

**Comment by sishida** [comment]
Thanks for the info, @GeekArthur!

@micgibso, sounds like you can start on this work. Please let me know if you have any questions. Also please add a comment so I can assign it to you. Thank you!

**Comment by micgibso** [comment]
@sishida Please assign me, thx!
