### ISSUE TITLE
Switch Filewatcherd to use absolute time (not relative time) when calling cwctl project sync

### ISSUE THREAD

**Issue by jgwest** [eclipse/codewind#844]
Filewatcherd is currently using relative time across all three filewatchers, but cwctl would like absolute time (in Unix epoch msecs) instead and I am happy to oblige.

**Comment by jgwest** [comment]
All watchers updated.

**Comment by maysunfaisal** [comment]
If all the remove commands are `/remove` should it be `/remove-assign`

**Comment by jgwest** [comment]
This shouldn't work (invalid format), but also shouldn't throw an exception:
/assign me

**Comment by jgwest** [comment]
@maysunfaisal The only supported commands are those I listed in my Slack message, there are no secret commands yet 🕵

**Comment by jgwest** [comment]
Test invalid again: 
/assign me

**Comment by jgwest** [comment]
Let's try this:
/assign @jgwest @maysunfaisal

**Comment by maysunfaisal** [comment]
@jgwest Did i break it again

**Comment by jgwest** [comment]
`/assign me` is not a valid command, but since people will inevitably try it, I will add it.

**Comment by jgwest** [comment]
🤔

**Comment by maysunfaisal** [comment]
tho i miss the prow /woof 😞

**Comment by jgwest** [comment]
🤔 💭

**Comment by jgwest** [comment]
🤔

**Comment by jgwest** [comment]
@jgwest: Unable to find assignee: invalid

**Comment by jgwest** [comment]
@jgwest: GitHub didn't allow me to assign the following users: invalid

Note that only org members, repo collaborators and people who have commented on this issue/PR can be assigned.

**Comment by jgwest** [comment]
@jgwest: Could not find label: kind/invalid2

**Comment by jgwest** [comment]
@jgwest: GitHub didn't allow me to assign the following users: honk

Note that only org members, repo collaborators and people who have commented on this issue/PR can be assigned.

**Comment by jgwest** [comment]
@jgwest: GitHub didn't allow me to assign the following users: asda8s0d8as90d809a8sd09as8d09a8sd908a0s9d8a09s8d09a8sd098ad908asd

Note that only org members, repo collaborators and people who have commented on this issue/PR can be assigned.<details>


In response to [this](https://github.com/eclipse/codewind/issues/844):
> assign asda8s0d8as90d809a8sd09as8d09a8sd908a0s9d8a09s8d09a8sd098ad908asd
</details>

**Comment by jgwest** [comment]
@jgwest: GitHub didn't allow me to assign the following users: as9d8as0d8as908d90as8d09a8s90d8as90d8as09d80a9s8

Note that only org members, repo collaborators and people who have commented on this issue/PR can be assigned.<details>


In response to [this](https://api.github.com/repos/eclipse/codewind/issues/comments/553270470):
> assign as9d8as0d8as908d90as8d09a8s90d8as90d8as09d80a9s8
</details>

**Comment by jgwest** [comment]
@jgwest: GitHub didn't allow me to assign the following users: asd87as98d7a89s7d89as7d98as7d987as98d7as89d789a7d9

Note that only org members, repo collaborators and people who have commented on this issue/PR can be assigned.<details>


In response to [this](https://github.com/eclipse/codewind/issues/844#issuecomment-553271813):
> assign asd87as98d7a89s7d89as7d98as7d987as98d7as89d789a7d9
</details>

**Comment by jgwest** [comment]
@jgwest: GitHub didn't allow me to assign the following users: asd8as09d809as8d90a8d098as09d8as908d0as8d90sa

Note that only org members, repo collaborators and people who have commented on this issue/PR can be assigned.<details>


In response to [this](https://github.com/eclipse/codewind/issues/844#issuecomment-553273531):
> assign asd8as09d809as8d90a8d098as09d8as908d0as8d90sa
</details>

**Comment by jgwest** [comment]
/assign @johnmcollier 
😛

**Comment by jgwest** [comment]
close and reopen seem to be working...

/close
/assign @johnmcollier 
/remove-kind test

**Comment by jgwest** [comment]
@jgwest: Those labels are not set on the issue: kind/test<details>


In response to [this](https://github.com/eclipse/codewind/issues/844#issuecomment-555195051):
> remove-kind test
</details>

**Comment by jgwest** [comment]
@maysunfaisal: Those labels are not set on the issue: priority/all<details>


In response to [this](https://github.com/eclipse/codewind/issues/844#issuecomment-555631705):
> remove-priority all
</details>

**Comment by jgwest** [comment]
@jgwest: Command 'remove-kind' requires at least one parameter.<details>


In response to [this](https://github.com/eclipse/codewind/issues/844#issuecomment-555643317):
> remove-kind
</details>

**Comment by jgwest** [comment]
@johnmcollier Prow doesn't flag invalid commands, and I'm sticking with that behaviour 😛

**Comment by jgwest** [comment]
@jgwest: Command 'reopen' does not support any parameters.<details>


In response to [this](https://github.com/eclipse/codewind/issues/844#issuecomment-555651597):
> reopen too many params
</details>

**Comment by jgwest** [comment]
@jgwest: Unexpected command format: area<details>


In response to [this](https://github.com/eclipse/codewind/issues/844#issuecomment-555653293):
> area
</details>

**Comment by jgwest** [comment]
@jgwest: Unexpected command format: area<details>


In response to [this](https://github.com/eclipse/codewind/issues/844#issuecomment-555653293):
> area
</details>

**Comment by jgwest** [comment]
@jgwest: Cannot move an issue that is in multiple pipelines -  old:5d125da643e42a09a0a4a95b new: Verify

**Comment by jgwest** [comment]
@jgwest: Unable to locate pipeline with name:not a real value

**Comment by jgwest** [comment]
@jgwest: Unable to locate pipeline with name: `not a real value 2`

**Comment by jgwest** [comment]
@jgwest: Unable to move issue to pipeline: review/QA

**Comment by jgwest** [comment]
@jgwest: Unable to locate pipeline with name: `not a real value 2`

**Comment by jgwest** [comment]
@jgwest: Unable to add release: notfound<details>


In response to [this](Optional.empty):
> Optional.empty
</details>

**Comment by jgwest** [comment]
@jgwest: Unable to add release: notfound2

**Comment by jgwest** [comment]
@jgwest: Unable to update release: notfound

**Comment by jgwest** [comment]
@jgwest: Unable to update release: notfound2

**Comment by jgwest** [comment]
/unassign
/kind bug

This should perform incorrectly if I am correct.

**Comment by jgwest** [comment]
Sweet

**Comment by jgwest** [comment]
🎉

**Comment by jgwest** [comment]
@jgwest: Command 'remove-svt' requires at least one parameter.<details>


In response to [this](https://github.com/eclipse/codewind/issues/844#issuecomment-584180990):
> remove-svt
</details>

**Comment by jgwest** [comment]
@jgwest: Those labels are not set on the issue: remove-svt<details>


In response to [this](https://github.com/eclipse/codewind/issues/844#issuecomment-584196197):
> remove-svt
</details>

**Comment by jgwest** [comment]
1
2
/svt
3

**Comment by jgwest** [comment]
1
2
/svt
3
