### ISSUE TITLE
Investigate dynamic registry setup

### ISSUE THREAD

**Issue by rajivnathan** [eclipse/codewind#845]
**Description of the enhancement:**

Related to https://github.com/eclipse/codewind/issues/665

This issue will be used to investigate whether we can set the deployment registry without needing to redeploy PFE.

**Comment by maysunfaisal** [comment]
I can take a look at this

**Comment by maysunfaisal** [comment]
This looks feasible. I had manually tested it out with kubectl cmd in the PFE container and it seemed to work

**Comment by maysunfaisal** [comment]
Another thing to keep in mind:

Docker config does no let me do this:

```
{
    "auths":{
        "docker.io":{
            "username":"maysunfaisal",
            "password":"xxx",
            "email":"maysun.j.faisal@ibm.com",
            "auth":"xxx"
        },
        "docker.io":{
            "username":"codewindtest",
            "password":"xxx",
            "email":"maysun.j.faisal@ibm.com",
            "auth":"xxx"
        }
    }
}
```


it fails for `maysunfaisal` but passes for `codewindtest`
so that is why Che does not allow two `docker.io` registries in the UI. It is one secret per docker server.
