### ISSUE TITLE
Workspace migration for 0.6.0

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind#846]
The new 'remote architecture', which lifts the requirement that user's projects be in the ~/codewind-workspace folder (except for Appsody projects), also requires a migration step in order to preserve Codewind's knowledge of projects created with prior versions.

The cwctl has been enhanced with an 'upgrade' command to do this, see: https://github.com/eclipse/codewind/issues/491

When we prompt the user to update to 0.6.0, we should also inform the user that their workspace data will be migrated as will.

**Comment by sishida** [comment]
Because of remote architecture changes, users need to be able to smoothly move their workspace. Currently unclear what the design, etc. will look like. Need input from design.

Aim for simplicity because 0.6.0 is so close.

**Comment by jopit** [comment]
We're not going ask the user if they want to migrate their workspace, we're going to do it automatically when the accept updating PFE to 0.6.0

**Comment by sishida** [comment]
We need to move internal project metadata that Codewind keeps about projects. Projects themselves won't move. But where Codewind finds its info about the projects will move. Thus, we don't want users to be able to decline migration.

Users should have the `codewind-workspace` folder for existing projects, but `codewind-workspace` won't be a special folder like it is in 0.5.0. Projects can be anywhere, not just in `codewind-workspace` starting in 0.6.0 and beyond.

Thus...the user doesn't need to do anything.

We will add this info to the news.

**Comment by tetchel** [comment]
we should write some user doc for the new workspace behaviour. it can be relatively short, but should mention

- projects are no longer required to be under the codewind-workspace ❗️ 
- users should NOT create projects under the special `~/codewind-data/` directory
- if you want to move an existing project, remove it from codewind (without deleting the files!), and then run the Add Existing Project command to re-add it from its new location
- in vs code, to skip the ‘select a parent directory’ step when creating a project, use the `codewind.alwaysCreateProjectsInWorkspace` setting
- project info is now kept in the `codewind_cw-workspace` docker volume. if this volume is deleted, your projects *will be deleted from Codewind*, though they will still exist on your disk
- project files are synchronized whenever a file changes into this docker volume, whereas previously Codewind did a docker mount of the entire codewind-workspace
- user configuration files are now kept under `~/.codewind/`, or `C:\Users\<user>\.codewind\`

**Comment by eharris369** [comment]
In Eclipse it is the same as above except:

- Moving projects: to add an existing project right click on Local in the Codewind explorer view and select Add Existing Project
- Creating new projects: the default is to create the project in the Eclipse workspace.  The user can enter a different location if they want.

**Comment by tetchel** [comment]
also this can be removed from the [vs code readme](https://github.com/eclipse/codewind-vscode)
`Codewind creates a folder called codewind-workspace within your home directory to contain your projects. On Windows, this is the C:\codewind-workspace directory. When the installation is complete, you can open the codewind-workspace folder or a project within the workspace as your VS Code workspace. The tools offer to open the workspace for you if it’s not open already.`

**Comment by tetchel** [comment]
i want to link to this page from a popup, so i guess we could get text for a notification shown after the migration/upgrade too. something like:

`Codewind workspace migration completed - Projects no longer need to be located under the codewind-workspace.`
With a 'read more' button that links to wherever we put this info.

**Comment by j-c-berger** [comment]
@tetchel thanks for letting me know what you want. I was talking to Toby Corbin yesterday, and he said the only difference users should be made aware of for 0.6.0 is that the restriction to have your projects in 'codewind-workspace` has been lifted. 

With that said, when I delete your recommended content from the README, would you like me to add something along the lines of, "Once you update Codewind to 0.6.0, you no longer are restricted to have your projects in the `codewind-workspace.` 

I can definitely simply omit the content needing omitting, but I thought I'd suggest this in case we wanted to inform users on the big difference with 0.6.0. Thanks!

**Comment by j-c-berger** [comment]
@eharris369, since Tim needed content omitted from VS Code's README, I wanted to see if you wanted anything taken out from Eclipse's README. 

I went through the Eclipse README and didn't find any reference nor mention of codewind-workspaces but wanted to check with you nonetheless. Thanks!

**Comment by tetchel** [comment]
>  "Once you update Codewind to 0.6.0, you no longer are restricted to have your projects in the codewind-workspace.

sure, it makes sense to make that explicit

**Comment by j-c-berger** [comment]
@tetchel sounds good, thanks!

**Comment by eharris369** [comment]
@j-c-berger The Eclipse readme does not mention anything about the codewind-workspace so nothing needs to be removed.

**Comment by j-c-berger** [comment]
@tetchel for the popup that you want, regarding, ```Codewind workspace migration completed - Projects no longer need to be located under the codewind-workspace.```

I'm happy to review anything you want once you make a PR for it. No rush. I'm here whenever you need it reviewed. Thanks.

**Comment by jopit** [comment]
@sishida @j-c-berger 
I searched the landing pages for  where either `codewind-workspace` or `codewind workspace` (with a space, case insensitive) were used.

Here's the result for `codewind-workspace`: 
[codewind-workspace.txt](https://github.com/eclipse/codewind/files/3816814/codewind-workspace.txt)
and here's the result for `codewind workspace`: 
[codewind workspace.txt](https://github.com/eclipse/codewind/files/3816817/codewind.workspace.txt)

We need to be careful about some places where `codewind workspace` is used, because it is still correct to use it in some places the docs about Che according to @johnmcollier 

I also think that the concepts in some sections in the troubleshooting which refer to problems with Docker on Windows are still applicable for Appsody projects, but the exact description needs to be changed, @makandre or @sghung could provide more input.

In general, any changes for this are going to require careful review from the dev teams to make sure they are accurate @elsony @tobespc
