### ISSUE TITLE
Cannot create projects with same names but different localpath

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#857]
In pfe, when we store projects in the workspace volume, we just use the name of the project without any unique value.   This means, if a user binds 2 projects with the same name but 2 completely difference local disk locations, we overwrite the existing project.   Should change this to create directories based on project ID

**Comment by james-wallis** [comment]
@tobespc can you assign me please?

**Comment by james-wallis** [comment]
Track on my branch: https://github.com/james-wallis/codewind/tree/change-directory 
Initially I'm using the `projectID` for the directory name but this looks pretty horrible when debugging. I think I might add the name to the `projectID`?
Might become too long so I'll see if I can get a shortened UUID for the directory.

**Comment by tobespc** [comment]
@deboer-tim @jopit Do we want to allow codewind to deal with projects that have the same name (but with different paths )?  We can deal with it as a cli level but how would the IDE's reflect this ?

We have a PR ready that would enable this... but... is it a requirement ?

**Comment by jopit** [comment]
At this point I'd vote to explicitly not allow it. We can always relax the restriction later if there's a need.

**Comment by tobespc** [comment]
closing this issue as this feature is not being allowed
