### ISSUE TITLE
HTTP error 413 when binding existing microprofile project (remote architecture)

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind#859]
**Codewind version:** latest
**OS:** macOS Catalina

Tried to bind an existing microprofile project (created with 0.4.0) via the eclipse plugin, got a 413 error
```
java.io.IOException: Received bad response code 413 for uri http://127.0.0.1:10000/api/v1/projects/17839120-f730-11e9-865f-3dee9b870a0c/remote-bind/upload with error message request entity too large
```

**Comment by tobespc** [comment]
Will need to check this out, did you run the upgrade script or manually try and re bind it ?

**Comment by jopit** [comment]
I manually tried to rebind it

**Comment by jopit** [comment]
I'm no longer seeing the 413 error.
