### ISSUE TITLE
Send notification on application ping timeout

### ISSUE THREAD

**Issue by elsony** [eclipse/codewind#86]
We are currently pinging the application health check endpoint to decide if application has ben started or not.  Currently, if there is problem on application or user configured the wrong context root. Application will stay on starting state with detailed state message mentioning the corresponding pinging URLs. 

This item is to introduce a timeout on the application pinging to send out a socket notification if the application doesn't change to started when the timeout value is being hit.  When the IDE receives the notification, it can display some meaningful message to the user to inform the user that there maybe something wrong with the application or the setup.

**Comment by yangcao77** [comment]
@tetchel From IDE's perspective, is a simple `updateStatus` event enough?(update app status to stopped & with a message saying it failed to ping)
Or you need another socket event?

**Comment by tetchel** [comment]
so if we want it to show up like the current behaviour `[Starting] [Failed to ping <whatever>]` then the regular status event `projectStatusChanged` is fine. 

We are reworking this as part of https://github.com/eclipse/codewind/issues/159 so maybe we should consider that one a blocker.

**Comment by rajivnathan** [comment]
@tetchel can this one be closed now?

**Comment by tetchel** [comment]
sure, turbine part is done, i have to react to it in vs code though.
