### ISSUE TITLE
Document Vscode requirement (1.26.x too low)

### ISSUE THREAD

**Issue by a-roberts** [eclipse/codewind#860]
While looking to triage https://github.com/tektoncd/dashboard/issues/646 I tried to install Codewind 0.5.0 onto my Mac running the latest version of Mojave. I had version 1.26.1 and noticed this (isn't really a bug by the way)

```
s/codewind-0.6.0.vsix" berts$ code --install-extension "/Users/aroberts/Download
echo 'Installation ended'
Unable to install Extension 'ibm.codewind-0.6.0' as it is not compatible with Code '1.26.1'.
adams-mbp:Downloads aroberts$ echo 'Installation ended'
Installation ended
adams-mbp:Downloads aroberts$

s/IBM.codewind-0.5.0.vsix" s$ code --install-extension "/Users/aroberts/Download
echo 'Installation ended'
Unable to install Extension 'ibm.codewind-0.5.0' as it is not compatible with Code '1.26.1'.
adams-mbp:Downloads aroberts$ echo 'Installation ended'
Installation ended
adams-mbp:Downloads aroberts$
```

I then installed the latest stable vscode (1.39.2). Spoke with @tobespc about this in person, would be useful to:

a) build against the oldest version possible for compatiiblity
b) document a minimum required version

When the install fails it's pretty cryptic (just saw "failed to install ibm.codewind"), but this was definitely the cause and now life is good.

**Comment by tetchel** [comment]
Our minimum version is **1.28.0** which is from September 2018. I didn't expect anyone to be on such an old version because VS Code autoupdates 😅. 

But you're right that we should doc this.

**Comment by micgibso** [comment]
@sishida I can take a look at this. Thanks.

**Comment by micgibso** [comment]
Our VS Code Getting Started topic states this, https://www.eclipse.org/codewind/mdt-vsc-getting-started.html
![image](https://user-images.githubusercontent.com/7224752/68756518-30675100-0602-11ea-8ee4-7476b66fb4ab.png)

Depends on your entry point on whether that's enough I guess. 
@a-roberts where did access the Codewind install link/instructions, was it here: https://www.eclipse.org/codewind/mdt-vsc-installinfo.html, Marketplace: https://marketplace.visualstudio.com/items?itemName=IBM.codewind, or somewhere else?

**Comment by a-roberts** [comment]
> Our VS Code Getting Started topic states this, https://www.eclipse.org/codewind/mdt-vsc-getting-started.html
> ![image](https://user-images.githubusercontent.com/7224752/68756518-30675100-0602-11ea-8ee4-7476b66fb4ab.png)
> 
> Depends on your entry point on whether that's enough I guess.
> @a-roberts where did access the Codewind install link/instructions, was it here: https://www.eclipse.org/codewind/mdt-vsc-installinfo.html, Marketplace: https://marketplace.visualstudio.com/items?itemName=IBM.codewind, or somewhere else?

Hey Michael, in VScode itself which I'm guessing refers to https://marketplace.visualstudio.com/items?itemName=IBM.codewind

**Comment by sishida** [comment]
@micgibso Just wanted to let you know that I made an update about the VS Code requirement in PR https://github.com/eclipse/codewind-vscode/pull/285 as the update applies to this issue.
