### ISSUE TITLE
Rename deployment to be connection (deployment is confusing)

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#861]
Rename the use of deployment (meaning location of pfe) to be connection.   This will require changing cwctl, pfe, docs

This is to clear up confusion over appsody deploy, deploying apps in cloud etc

**Comment by tetchel** [comment]
At the same time, can we make this consistent? I prefer "active" to "target"

![image](https://user-images.githubusercontent.com/8888438/67581161-8d639b80-f715-11e9-8019-d5dfd663e6b6.png)

**Comment by jcockbain96** [comment]
https://github.com/eclipse/codewind-installer/pull/166

**Comment by jcockbain96** [comment]
We're going to remove the obsolete commands (all the target deployment stuff) in  a PR after that one, as it's already pretty massive

**Comment by jcockbain96** [comment]
The change to `connection` should now be complete for `cwctl`. I'm looking at pfe code too, but all references to deployment appear to be for the docker registry deployment which is separate.

**Comment by tobespc** [comment]
closing as done
