### ISSUE TITLE
Cannot disable appsody projects

### ISSUE THREAD

**Issue by ssh24** [eclipse/codewind#865]
**Codewind version:** Master
**OS:** MacOS

**Che version:** None
**IDE extension version:** Master
**IDE version:** Master
**Kubernetes cluster:** None

**Description:**
After creating an appsody project if I try to disable the project, it cannot disable. On the IDE it is stuck on saying that project is being disabled and on the PFE logs no action of project deletion is done. It does not eventually disable either so I just have to prune it and fully delete the project.

**Steps to reproduce:**
1. Create an appsody project - I tried it on an Liberty appsody project
2. Wait for the app to be up.
3. Disable the project.

**Comment by makandre** [comment]
I was able to disable an appsody node project.  Will try Liberty (I assume you meant the java-microprofile stack) next

<img width="849" alt="image" src="https://user-images.githubusercontent.com/17596240/67588807-03233380-f725-11e9-8c26-0187b1d18557.png">

**Comment by ssh24** [comment]
Yup, the eclipse microprofile stack

**Comment by makandre** [comment]
Now I run into this even on the node project... something's up...

**Comment by stalleyj** [comment]
I'll look at this

**Comment by ssh24** [comment]
I was able to disable an appsody project this morning. So looks like the behavior is intermittent. Don't think it is a stopship (unless we can reproduce it more often)

**Comment by makandre** [comment]
@stalleyj which check?

**Comment by stalleyj** [comment]
https://github.com/eclipse/codewind/blob/6ce8133de6277d2e8ff3dbd1e2cdf6b19aa67f8e/src/pfe/portal/modules/User.js#L470

**Comment by stalleyj** [comment]
https://github.com/eclipse/codewind/pull/918

**Comment by makandre** [comment]
Working for me now.  I think we can close this?

**Comment by ssh24** [comment]
**Verified**
