### ISSUE TITLE
Update repository settings to host api docs

### ISSUE THREAD

**Issue by stalleyj** [eclipse/codewind#87]
The codewind public api docs are defined in /docs and need to be hosted.  This requires a repository settings change, under GitHub Pages select the source master branch/docs folder as shown in the picture below. Please update the repository for this.

![githubpages](https://user-images.githubusercontent.com/13417476/62293120-ce724980-b45f-11e9-8dcf-99ac65964f3f.png)

**Comment by stalleyj** [comment]
@josephca Can you get the webmaster to implement please.

**Comment by josephca** [comment]
@stalleyj Opened a bugzilla ticket : https://bugs.eclipse.org/bugs/show_bug.cgi?id=549730

**Comment by josephca** [comment]
Done for 
eclipse/codewind
eclipse/codewind-docs

**Comment by tetchel** [comment]
openapi docs now available --> https://eclipse.github.io/codewind/
