### ISSUE TITLE
Standard news page for the latest version

### ISSUE THREAD

**Issue by rajivnathan** [eclipse/codewind#871]
The News URL is currently https://www.eclipse.org/codewind/news05.html should we make a file that's dedicated to the latest release  eg. https://www.eclipse.org/codewind/news.html so that we can link to the latest news page in blogs, etc.?

**Comment by sishida** [comment]
@travis1111 Hi, Travis, Would this issue fall into your area of expertise?

**Comment by travis1111** [comment]
Yes, please assign it to me
