### ISSUE TITLE
SVT: Codewind unable to access Tekton Dashboard and 403 seen on OpenShift

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#872]
**Codewind version:** 0.5.0 
**OS:** Red Hat Enterprise Linux 7 (64 bit)

**Che version:** 7.2.0
**Kubernetes cluster:** OKD/Openshift

**Tekton Dashboard:** v0.2.0

**Description:** [Issue #646 from tektoncd/dashboard](https://github.com/tektoncd/dashboard/issues/646 )
With the "Install on Openshift" instructions, the Tekton Panel works outside of Codewind, but not within the Codewind workspace.

<img width="496" alt="Screen Shot 2019-10-16 at 3 15 18 PM" src="https://user-images.githubusercontent.com/49531960/66958275-d345a300-f035-11e9-80a6-f594ca623093.png">

<img width="1084" alt="Screen Shot 2019-10-16 at 3 25 36 PM" src="https://user-images.githubusercontent.com/49531960/66958285-d6d92a00-f035-11e9-826f-48359ecff70b.png">

On the other side, with the general instructions, a Forbidden 403 error is obtained when trying to open the dashboard (inside or outside Codewind). 

**Steps to Reproduce the Problem:**
1. Install Tekton Pipelines
2. Install Tekton Dashboard
3. Install Tekton on Codewind / Access the Tekton Dashboard outside Codewind

**Additional Information:**
A month ago, we opened a problem against Codewind, but it was closed: https://github.com/eclipse/codewind/issues/291

After the latest testing efforts, I noticed that the Codewind endpoint URL for Tekton Dashboard no longer works with the latest version of it.

With the help of @tetchel, Adam Roberts (Tekton) was able to reproduce the problem and found the following error:
```
[32m[25/10/19 15:19:24 /portal/modules/TektonUtils.js] [INFO][39m Looking for services in Tekton namespace 'tekton-pipelines'
[91m[25/10/19 15:19:24 /portal/modules/TektonUtils.js] [ERROR][39m Unexpected error determining Tekton API Service: {"code":403,"statusCode":403}
```

Therefore, since the Tekton Dashboard issue was closed because it is a Codewind error, I opened this GitHub issue to continue tracking this problem. 

@jagraj

**Comment by hhellyer** [comment]
@sujeilyfonseca - It looks like your dashboard is running on port 443. That is the port for `https` and we attempt to connect using `http`. This probably explains the 403.

Could you run `kubectl get svc --selector="app=tekton-dashboard" --all-namespaces` and let me know what the output is? I'd like to see if the dashboard has more than one port available.

Also did you do anything to configure your tekton dashboard to listen on `https`?
I'll talk to the dashboard team and check if there is a property on the service (other than the port number) that can tell us whether to connect via http or https? If we can determine which it's trivial to set the right flag when connecting.

**Comment by sujeilyfonseca** [comment]
Thanks for following this issue, @hhellyer!

You're right, my Tekton Dashboard is running on port 443. Here is the requested output:
```
[root@sfonseca-okd-codewind codewind-che-plugin]# kubectl get svc --selector="app=tekton-dashboard" --all-namespaces  
NAMESPACE          NAME               TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
tekton-pipelines   tekton-dashboard   ClusterIP   172.30.42.54   <none>        443/TCP   2m
```

I did nothing to configure my Tekton Dashboard to listen on `https`.

**Comment by tobespc** [comment]
so can this be closed ?

**Comment by rtaniwa** [comment]
Doesn't look like it. Per @hhellyer comment:

_I'll talk to the dashboard team and check if there is a property on the service (other than the port number) that can tell us whether to connect via http or https? If we can determine which it's trivial to set the right flag when connecting._

**Comment by hhellyer** [comment]
@sujeilyfonseca - I installed into docker kube and it was on 9097 and I'd assume that's been the default in other cases otherwise we'd have never had a connection.
```
NAMESPACE          NAME               TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
tekton-pipelines   tekton-dashboard   ClusterIP   10.109.28.124   <none>        9097/TCP   5h8m
```
However on openshift there are two services:
https://github.com/tektoncd/dashboard/blame/1e7c51f81f4d34162b0e7299ed1c326d99530353/config/openshift/openshift-tekton-dashboard.yaml#L197

`tekton-pipelines` is created on 443 (and is https by the look of it) however there is also `tekton-pipelines-internal`. We could probably use either or check for the internal one then switch to the normal one if that isn't found. I'm not sure if there's any authentication when 443 is used.

**Comment by jagraj** [comment]
We are currently broke with the latest "Tekton" release and we need this fix for 0.6 release.

**Comment by tobespc** [comment]
changing to use the tekton-dashboard-internal service name

**Comment by sujeilyfonseca** [comment]
I have tested this issue with the latest release of the Tekton Dashboard (v0.2.1), and I no longer see this problem.

**Comment by malincoln** [comment]
@jagraj looks like @sujeilyfonseca has verified the fix.  If so, pls close.  Thanks

**Comment by jagraj** [comment]
@tobespc 
Thanks for the fix.

@sujeilyfonseca 
Please go ahead and close this issue.
