### ISSUE TITLE
Codewind removes (?) execute permissions from files in appsody stack

### ISSUE THREAD

**Issue by nastacio** [eclipse/codewind#875]
**Codewind version: 0.5.0
**OS:** 
MacOS Mojave

**Che version:**
N/A

**IDE extension version:** 
0.5.0

**IDE version:**
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:00.827Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

**Kubernetes cluster:** 
N/A

**Appsody version:**
0.4.7

**Description:**
When I try to create a project using the "experimental/quarkus" stack, the project directory is initiated, but the run fails because a file in the stack (mvnw) does not have executable permissions.

**Steps to reproduce:**
1. From the codewind tab in the VS-Code workspace, add the template source:
https://github.com/appsody/stacks/releases/latest/download/experimental-index.json
2. Create a new Codewind project with the "Appsody Quarkus template" template.
3. Observe the following output in the application logs:
```
[Container] Running command:  ./mvnw -B compile quarkus:dev
[Container] /bin/bash: ./mvnw: Permission denied
[Container] Wait received error on APPSODY_RUN/DEBUG/TEST exit status 126
```
The applicaton never starts.

If you create the stack from the CLI using solely appsody from the command-line, the file has the correct permissions and `appsody run` works right away.

**Workaround:** 
Go to the command-line and add the missing executable permission:
```
chmod u+x mvnw
```
Then go back to codewind, right-click the application and choose "Restart in Run Mode"

**Comment by tobespc** [comment]
need to investigate this from a portal side - make sure we've not done anything crazy

**Comment by markcor11** [comment]
Reproduced with PFE 2019-11-09 master versions 

```
Status: Image is up to date for appsody/quarkus:0.1
[Warning] Could not mount /root/.m2/repository:/home/$(id -un)/.m2/repository because the local file was not found.
Running docker command: docker run --rm -P --name cw-quarkus2-2e1d1a60-0206-11ea-b489-1b453dcfaa06 --network codewind_network -u 0:0 -e APPSODY_USER=0 -e APPSODY_GROUP=0 -v /Users/.../Documents/GitHub/codewind/codewind-workspace/quarkus2/.:/project/user-app -v /Users/.../Documents/GitHub/codewind/codewind-workspace/.extensions/codewind-appsody-extension/bin/appsody-controller:/appsody/appsody-controller -t --entrypoint /appsody/appsody-controller appsody/quarkus:0.1 --mode=run
[Container] Running command:  ./mvnw -B compile quarkus:dev
[Container] /bin/bash: ./mvnw: Permission denied
[Container] [Error] Wait received error with status code: 126 due to error: exit status 126
[Error] Error in 'appsody run': exit status 126
```

**Comment by markcor11** [comment]
``` 
[root@c1b9db5258f9 quarkus2]# ls -al
total 28
drwxrwxr-x 9 root root  288 Nov  8 09:00 .
drwxr-xr-x 5 root root  160 Nov  8 09:00 ..
-rw-rw-r-- 1 root root   50 Nov  8 09:00 .appsody-config.yaml
drwxrwxr-x 3 root root   96 Nov  8 09:00 .mvn
drwxrwxr-x 3 root root   96 Nov  8 09:00 .vscode
-rw-rw-r-- 1 root root 9892 Nov  8 09:00 mvnw
-rw-rw-r-- 1 root root 6301 Nov  8 09:00 mvnw.cmd
-rw-rw-r-- 1 root root 3773 Nov  8 09:00 pom.xml
drwxrwxr-x 4 root root  128 Nov  8 09:00 src
```

changing it to:

```-rwxrwxr-x 1 root root 9892 Nov  8 09:00 mvnw```

Results in : 

```
Running development environment...
Pulling docker image appsody/quarkus:0.1
Running command: docker pull appsody/quarkus:0.1
0.1: Pulling from appsody/quarkus
Digest: sha256:bce43d6545b795b22de61cb95f9a0a700b2bc4c3d1e4e1c8fdfb8482e27572e7
Status: Image is up to date for appsody/quarkus:0.1
[Warning] Could not mount /root/.m2/repository:/home/$(id -un)/.m2/repository because the local file was not found.
Running docker command: docker run --rm -P --name cw-quarkus2-2e1d1a60-0206-11ea-b489-1b453dcfaa06 --network codewind_network -u 0:0 -e APPSODY_USER=0 -e APPSODY_GROUP=0 -v /Users/..../Documents/GitHub/codewind/codewind-workspace/quarkus2/.:/project/user-app -v /Users/..../Documents/GitHub/codewind/codewind-workspace/.extensions/codewind-appsody-extension/bin/appsody-controller:/appsody/appsody-controller -t --entrypoint /appsody/appsody-controller appsody/quarkus:0.1 --mode=run
[Container] Running command:  ./mvnw -B compile quarkus:dev
[Container] Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain
[Container] [Error] Wait received error with status code: 1 due to error: exit status 1
[Error] Error in 'appsody run': exit status 1
```

**Comment by tobespc** [comment]
@makandre Could you take a look please ?  After forcing the permissions to be correct Mark is then getting build errors which doesn't appear to be portal related.  Thanks

**Comment by nastacio** [comment]
This second problem is a defect in the appsody stack itself:
https://github.com/appsody/stacks/issues/448

**Comment by hhellyer** [comment]
Upload was not sending file permissions, I've raised PR's for that against cwctl and portal
cwctl: https://github.com/eclipse/codewind-installer/pull/201
Portal: https://github.com/eclipse/codewind/pull/1052

This fixes permissions for a simple go project.

When I create a new Quarkus project I'm still seeing the permissions wrong but once changed on the host machine those permissions aren't lost. However I was losing them before I made this change which made me wonder if the files were still being uploaded even though they were also bind mounted into `codewind-pfe`.

@makandre - I think I've fixed *an* issue with portal not setting permissions on uploaded files but there may be more going on here. If we are still uploading files that are also bind mounted then there's a risk of 'weird behaviour' - reading and writing to and from the same file. Did uploading get disabled for Appsody projects?

**Comment by makandre** [comment]
@hhellyer The upload happens for appsody projects as well.

Appsody projects can be created anywhere on the disk just like other Codewind projects.  Its contents are uploaded to PFE the same way.  Then here's the part that's different:  PFE puts Codewind projects under `/codewind-workspace` (docker volume space, not bind mount), but for Appsody projects PFE puts them under `/mounted-workspace` (which is the bind mounted space)

**Comment by hhellyer** [comment]
It looks like preserving the file permissions is one thing but we also don't create the files with the right permissions when we download the project templates. I've raised another bug for that here: https://github.com/eclipse/codewind/issues/1057

**Comment by hhellyer** [comment]
@nastacio - This issue and the follow up I raised should be resolved now. Can you close?

**Comment by nastacio** [comment]
I am now using Codewind 0.7.0 and the recreation steps are not working. When try and add "https://github.com/appsody/stacks/releases/latest/download/experimental-index.json" as a new template source, nothing happens after I complete the "Add New" sequence.

There is no error message on the screen, just nothing happens and the new source never shows up in the "Template Sources" window, even after I restart VS-Code.

**Comment by nastacio** [comment]
I am getting the same problem on Eclipse, the creation dialog closes and the template is not added.

<img width="881" alt="Screen Shot 2020-01-07 at 11 08 37 AM" src="https://user-images.githubusercontent.com/3278623/71909605-5f033300-313e-11ea-8f35-156431295a97.png">

<img width="590" alt="Screen Shot 2020-01-07 at 11 11 08 AM" src="https://user-images.githubusercontent.com/3278623/71909644-6fb3a900-313e-11ea-887c-c0bd0f94477b.png">

**Comment by makandre** [comment]
Hi @nastacio, in 0.7.0 we tightened the rules on what repos you can add.  The experimental repo is built-in but hidden by design, so you can't add it (there's an issue opened for the IDEs not returning an appropriate error to the user #1597 )

You should be able to workaround this by adding this repo url instead: https://github.com/appsody/stacks/releases/download/python-flask-v0.2.0/experimental-index.json

**Comment by nastacio** [comment]
The workaround allowed me to proceed and Codewind created the project with the same original problem:

<img width="1373" alt="Screen Shot 2020-01-07 at 11 30 02 AM" src="https://user-images.githubusercontent.com/3278623/71911093-1a2ccb80-3141-11ea-890f-80e5637bd911.png">


```
ls -la ~/tmp/quarkus-358
total 56
drwxr-xr-x    8 nastacio  staff    256 Jan  7 11:28 .
drwxr-xr-x  853 nastacio  staff  27296 Jan  7 11:26 ..
-rw-r--r--    1 nastacio  staff     53 Jan  7 11:26 .appsody-config.yaml
drwxr-xr-x    3 nastacio  staff     96 Jan  7 11:26 .vscode
-rw-r--r--    1 nastacio  staff   9892 Jan  7 11:26 mvnw
-rw-r--r--    1 nastacio  staff   6301 Jan  7 11:26 mvnw.cmd
-rw-r--r--    1 nastacio  staff   3777 Jan  7 11:26 pom.xml
drwxr-xr-x    4 nastacio  staff    128 Jan  7 11:26 src
```

**Comment by nastacio** [comment]
Using appsody 0.5.3 to confirm this is not a problem with the stack itself, note how `mvnw` has the executable permissions:

```
appsody init experimental/quarkus
...
 ls -la
total 56
drwxr-xr-x  8 nastacio  staff   256 Jan  7 11:31 .
drwxr-xr-x  3 nastacio  staff    96 Jan  7 11:31 ..
-rw-r--r--  1 nastacio  staff    45 Jan  7 11:31 .appsody-config.yaml
drwxr-xr-x  3 nastacio  staff    96 Jan  7 11:31 .vscode
-rwxr-xr-x  1 nastacio  staff  9892 Jan  7 11:31 mvnw
-rwxr-xr-x  1 nastacio  staff  6301 Jan  7 11:31 mvnw.cmd
-rw-r--r--  1 nastacio  staff  3777 Jan  7 11:31 pom.xml
drwxr-xr-x  4 nastacio  staff   128 Jan  7 11:31 src
```

**Comment by malincoln** [comment]
@hhellyer are you investigating?  Should this go back to In progress?

**Comment by malincoln** [comment]
@nastacio if you have verified successfully, can you close this one?  Thanks

**Comment by nastacio** [comment]
Got this trying to start Codewind 0.9.0:

```
Error reconnecting to Local Codewind: "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot GET /api/v1/projects</pre>\n</body>\n</html>\n"
```

Will try and cleanup old .codewind folder, which shouldn't be necessary.

**Comment by nastacio** [comment]
It works now, thanks!
