### ISSUE TITLE
Liberty project created in disabled state

### ISSUE THREAD

**Issue by stalleyj** [eclipse/codewind#876]
**Codewind version:** . 
Latest code, 0.6 version on VSCode plugin

**Description:**
I created a microprofile project and it appears in disabled state. Extract from PFE log file:-

[28/10/19 10:08:18 FileWatcher.js] [ERROR] Error: project update 400 Bad request. projectID, timestamp, chunk, chunk_total and eventArray are required.
    at FileWatcher.projectFileChanged (/portal/modules/FileWatcher.js:395:15)
(node:71) UnhandledPromiseRejectionWarning: Error: Command failed: docker cp /codewind-workspace/berty1/src/main/liberty/config/jvmbx.options undefined:/home/default/app/src/main/liberty/config/jvmbx.options
Error: No such container:path: undefined:/home/default/app/src/main/liberty/config

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)
(node:71) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:71) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Steps to reproduce:**

**Workaround:**

**Comment by ssh24** [comment]
I saw this before but on a bind where portal tries to copy a lot of the files in `mc-target` or `target` dirs and take s a long time and the project is disabled in that period.

**Comment by stalleyj** [comment]
I've found the problem. We create the project in 'closed' state deliberately so that it isn't built until all files are uploaded. We change the state to 'open' before we request it to be built but do not send a socket msg, so the IDE is not notified until something comes through from Turbine.  We can fix it by adding a quick socket msg.

**Comment by stalleyj** [comment]
https://github.com/eclipse/codewind/pull/911

I've added the socket msg but VSCode plugin still shows the state as disabled until it gets updated to be building. @tetchel could you have a look please
