### ISSUE TITLE
Enable Portal ES Linter on PFE Dockerfile build

### ISSUE THREAD

**Issue by maysunfaisal** [eclipse/codewind#881]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description of the enhancement:**

Portal es linter should be executed during PFE Dockerfile build

Sometiems when I make a Portal code change, I find issues with the Portal es linter in the PR Jenkins test. This could be detected much earlier if the es lint is run during dockerfile build 😄 

**Proposed solution:**

**Comment by tobespc** [comment]
this is now done
