### ISSUE TITLE
'Install on Cloud' doc page dev file URL references 0.4 rather than 0.5

### ISSUE THREAD

**Issue by jgwest** [eclipse/codewind#882]
The [Install on Cloud](https://www.eclipse.org/codewind/installoncloud.html) doc page, under [Creating the Codewind workspace with a Devfile](https://www.eclipse.org/codewind/installoncloud.html#creating-the-codewind-workspace-with-a-devfile), asks the user to install Codewind using the 0.4 devfile URL. Since we have recently released 0.5.0, the docs should likely reference the 0.5.0 devfile:  `https://raw.githubusercontent.com/eclipse/codewind-che-plugin/master/devfiles/0.5.0/devfile.yaml`

**Comment by micgibso** [comment]
@sishida I'll take this one please, ta.

**Comment by jgwest** [comment]
Fixed by @GeekArthur  on https://github.com/eclipse/codewind-docs/pull/200
