### ISSUE TITLE
[Hybrid] Client adaptation to new log architecture

### ISSUE THREAD

**Issue by ssh24** [eclipse/codewind#883]
**Description:**
As a result of the hybrid changes the log architecture will change https://github.com/eclipse/codewind/issues/681. Portal will need to adapt to the new log architecture and the new event that will be emitted.

An example of the new project emittion object:
```
{
    "build": [
      {
        "origin": "container",
        "files": [
          "/home/default/logs/maven.build.log"
        ]
      },
      {
        "origin": "workspace",
        "files": [
          "/codewind-workspace/.logs/mylib-abebda90-f69d-11e9-954f-51fd5366b98f/docker.build.log"
        ]
      }
    ],
    "app": [
      {
        "origin": "workspace",
        "files": [
          "/codewind-workspace/.logs/mylib-abebda90-f69d-11e9-954f-51fd5366b98f/app.log"
        ]
      },
      {
        "origin": "container",
        "files": [
          "/home/default/logs/message.log",
          "/home/default/logs/console.log",
        ]
      }
    ]
  }
```

Once, portal fixes their streaming function be able to stream from both container and workspace logs, IDE should be able to show it as well. Though not sure how much work is required from the IDE side to adapt to the new change.

/cc @hhellyer @tetchel

**Comment by tetchel** [comment]
@tobespc 👀

**Comment by tetchel** [comment]
everything seems ok from my testing just now

**Comment by ssh24** [comment]
Yes, I just saw it work after a while as well :\

Is this intermittent behavior from portal or IDE?
