### ISSUE TITLE
CLI cannot reach PFE even with --insecure

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#884]
**Codewind version:** 0.6.0
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:** Openshift 4.2

**Description:**

This is on Che, running from the theia container:

Calling CLI with or without `--insecure` returns null:
```
bash-4.4$ /tmp/cwctl templates repos list
null
bash-4.4$ /tmp/cwctl --insecure templates repos list
null
```

I noticed the line here https://github.com/eclipse/codewind-installer/blob/master/config/config.go#L26 is `http`.  I changed it to `https` and recompiled, the result is better:

```
bash-4.4$ /tmp/codewind-installer --insecure templates repos list
[
	{
		"description": "Standard Codewind templates",
		"url": "https://raw.githubusercontent.com/kabanero-io/codewind-templates/master/devfiles/index.json",
		"name": "Default templates"
	},
	{
		"description": "Use Appsody in Codewind to develop applications with sharable technology stacks.",
		"url": "https://github.com/appsody/stacks/releases/latest/download/incubator-index.json",
		"name": "Appsody Stacks - appsodyhub"
	}
]
```

**Steps to reproduce:**

**Workaround:**

**Comment by makandre** [comment]
This issue is causing Appsody projects to be incorrectly detected as Codewind projects (because the CLI could not retrieve extensions metadata from PFE `/api/v1/extensions` API)

@tobespc @liamchampton

**Comment by johnmcollier** [comment]
Couple things to note here:
1) On Che, Codewind is behind an nginx proxy and can be reached via `https://localhost:9090` from the Theia container (where the CLI is running)
2) The proxy doesn't exist for Hybrid

**Comment by ebuckle** [comment]
Will look into this

**Comment by makandre** [comment]
Was asked to retest this.  I built from latest in `master` and copied it over to my theia container, I'm still getting the same `null` response.

**Comment by markcor11** [comment]
If PFE is running in KUBE it will be running with HTTPs and on port 9191 using a self signed certificate.   For the CLI to successfully connect it will therefore require the --insecure flag since this flag turns off certificate checking.   By default certificate chains are validated so without the --insecure flag REST requests to PFE from the CLI will fail and generate an x509: certificate signed by unknown authority error.

**Comment by markcor11** [comment]
We could detect in CLI if running in KUBE then use https instead of http to determine PFEOrigin

**Comment by jopit** [comment]
When should the IDEs be using --insecure, and when should they be leaving it out?  Or should we be adding it all the time? @markcor11 @tobespc

**Comment by johnmcollier** [comment]
Minimally it'll be needed for Codewind on Che, to communicate with the internal sidecar proxy we've got. (Proxy isn't exposed externally, so not concerned about the `--insecure` flag)

**Comment by jopit** [comment]
There's some comment drift on this issue.  The core problem is that the cli has is hard-coded to use http instead of https, which fails in Che (not sure what happens in true hybrid)

**Comment by markcor11** [comment]
The localhost:9090 proxy in theia is using https protocol with a self signed certificate.  

```
/tmp $ curl  https://localhost:9090/api/v1/environment
curl: (60) SSL certificate problem: self signed certificate
```

We will add a change to the CLI to detect if its running in CHE (and default to using the theia proxy https://localhost:9090) with https protocol as required but there is still the issue of the proxy self signed certificate to deal with.  We'll try switching off certificate checking when the CLI is in CHE then you won't need to provide the --insecure.  Update to follow....
