### ISSUE TITLE
Project overview cannot be opened again after closing it on Che

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#887]
**Codewind version:** 0.6.0
**OS:**

**Che version:** 7.2.0
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:** Openshift 4.2

**Description:**

Browser used: Chrome

After closing a project's overview page, it cannot be opened again; neither the `i` icon or the `Open Project Overview` action works

**Steps to reproduce:**

**Workaround:** 

Switch away from the workspace, e.g. go to Che dashboard, then come back to the workspace

**Comment by tetchel** [comment]
it's a theia bug, i have to update the latest devfile too https://github.com/eclipse/codewind/issues/670

**Comment by tetchel** [comment]
we will be updating to 7.3 shortly which should fix this
