### ISSUE TITLE
Appsody support on kube for 0.6.0

### ISSUE THREAD

**Issue by sghung** [eclipse/codewind#889]
Ensure 0.6.0 has working appsody support

<Link to dev-ex-planning issue: https://github.ibm.com/dev-ex/dev-ex-planning/issues/982>

**Comment by makandre** [comment]
There are a couple bugs we need fixed:
- https://github.com/eclipse/codewind/issues/884
- https://github.com/eclipse/codewind/issues/886

**Comment by sishida** [comment]
@sghung @makandre Just so the ID team understands...this issue is just for the documenting of 2 bugs, https://github.com/eclipse/codewind/issues/884 and https://github.com/eclipse/codewind/issues/886? Or do we have more Appsody support on Kube info that we also need to document?

**Comment by sishida** [comment]
We plan to fix bugs with 0.6.0. Need to document Appsody support on Kube. Might need a new page.

**Comment by sghung** [comment]
In our meeting on November 4th, we are waiting on the appsody team to help us with two issues (talking on slack now, but I have asked for specific issue numbers):

- There is a problem with ingress that needs to be addressed. Otherwise the user cannot open the app properly
- When the che workspace is removed, there is a chance that appsody resources are left behind

**Comment by sghung** [comment]
Regarding debugging, codewind doesn't support it for kube (https://github.com/eclipse/codewind/issues/959) so no documentation needs to be added specifically for appsody

**Comment by sishida** [comment]
Current locations of Appsody content:
- Troubleshooting Appsody section: https://www.eclipse.org/codewind/troubleshooting.html#appsody-with-codewind

**Comment by sishida** [comment]
Merged PR. Closing this issue.
