### ISSUE TITLE
OpenAPI: Update docs for Open API for 0.6.0

### ISSUE THREAD

**Issue by keithchong** [eclipse/codewind#890]
This is for:

https://github.com/eclipse/codewind/issues/79

for Maven-based projects

**Comment by sishida** [comment]
Rough draft of text.
In the meeting recording, Keith's demo starts around the 45 min mark.

# OpenAPI tools usability improvements
After code generation, you would have to tweak to get code to compile. But now you can generate code into an existing Maven project and have it build successfully. You can then customize your client.

### Prerequisites
- Finish building
- Have a Codewind project (In this case, an Open Liberty project)
- Have an OpenAPI document (In this case, the petstore.json file)

1. Right-click your Codewind project and launch the **Generate Server from OpenAPI Definition** wizard.
2. Select your OpenAPI document `.json` file.
3. Select the `jaxrs-spec` server generator type.
4. When you're prompted to select the output folder, project root, the parent of the source folder, is selected by default.
5. Click "Select As Output Folder" to merge the generated `.pom` file with the existing `.pom` file. When prompted with the warning message, click **Yes** to proceed. The files build.
6. Your `src` folder shows the newly generated code complete with `gen` package. Your project state returns to the `[Running]` state.
7. From here, you can customize the application logic.

Spring projects--When generating into a Spring project, you don't want to override the implicitly or explicitly configured main class that comes with the project.
1. To use the generated class, uncomment the main class text in the project `.java` file.
2. To use the current application, copy the packages at the component scan annotation and move them to the `SBApplication.java` file. Then, launch the project.

**Comment by keithchong** [comment]
@sishida , the OpenAPI tools troubleshooting documentation needs to be updated, https://www.eclipse.org/codewind/troubleshooting.html

This does not apply to VS Code any longer.  Modify it so it only applies to Eclipse.

`The following work-around applies to both VS Code and Eclipse. The spring server generator creates invalid source in the OpenAPI2SpringBoot class. Simply implement the methods from the interface and save the file. Also add the configuration element to the pom.xml file, like this:`

**Comment by sishida** [comment]
@keithchong With the close of PR https://github.com/eclipse/codewind-docs/pull/214, this issue is good to close, correct? Just wanted to confirm. Thank you!

**Comment by sghung** [comment]
Keith is away, closing on his behalf. The changes look good in the PR.
