### ISSUE TITLE
VSCode does not call cwctl project bind (calls remote api directly)

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#894]
The vscode plugin is not calling cwtcl project bind which it needs to.   Added more functionality to the bind which needs to be executed.  The plugin is directly calling the api/v1/remote-bind api still

**Comment by tetchel** [comment]
Blocked waiting for a way to deploy gatekeeper, because `connection add` command fails without one

**Comment by jopit** [comment]
Calling cwctl bind for local doesn't require the gatekeeper (at least it didn't last week)

**Comment by tetchel** [comment]
i meant generally, not just local

**Comment by tobespc** [comment]
you don't need to do anything differently for calling bind whether local or remote.  the cli will take care of it
