### ISSUE TITLE
Codewind pod failed to start with new che install on ICP

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#90]
**Environment:**
- **Codewind version:** [Latest](https://raw.githubusercontent.com/eclipse/codewind-che-plugin/master/devfiles/latest/devfile.yaml)
- **ICP version:** 3.2.0
- **OS:** macOS Mojave (10.14.5) 

**Description:**
Codewind pod failed to start with new che install on ICP.

![Screen Shot 2019-08-01 at 9 59 31 AM](https://user-images.githubusercontent.com/49531960/62299514-1636a800-b443-11e9-83b1-2caf4d9662b6.png)

![Screen Shot 2019-08-01 at 9 58 20 AM](https://user-images.githubusercontent.com/49531960/62299463-fe5f2400-b442-11e9-94ee-3163f96589e9.png)

@jagraj

**Comment by jagraj** [comment]
@johnmcollier @rajivnathan 
Looks like we have issue with the helm chart that we are using to install on ICP. As a user if I want to create Codewind-che workspace then we must define at least one registry key in che otherwise it fails to start pod with volume mount problem for the registry key. I defined public registry key then I was able to bring up codewind-che workspace.

Are we going to have same issue with OKD operator as well.?

**Comment by johnmcollier** [comment]
@jagraj @sujeilyfonseca Yes, this is a known limitation right now and our docs currently address that. Currently Codewind requires at least one registry secret to be set in Che prior to starting.

**Comment by rajivnathan** [comment]
@jagraj Can we close this one since Che install is now handled via operator?

**Comment by jagraj** [comment]
I think earlier, we need to create registry first before we start creating workspace. 
Does the operator install address this problem.?

@sujeilyfonseca 
Could you please verify this when you get a chance.?

**Comment by sujeilyfonseca** [comment]
I verified this problem, and the pod no longer fails to start. However, if the registry is not provided before the creation of the Codewind workspace, the registry can no longer be used:

<img width="502" alt="Screen Shot 2019-10-15 at 8 20 15 PM" src="https://user-images.githubusercontent.com/49531960/66881067-99bc5b80-ef93-11e9-94fe-d255d135735e.png">

This is a known limitation and is already documented (installoncloud.html#installing-che-with-chectl); we still need to first create the registry before starting to create the workspace. Thus, I consider that this issue could be closed, despite the mentioned aspect.

**Comment by jagraj** [comment]
Thanks Sujeily, You can go ahead and close this issue. I can not see the close option for me to close.
