### ISSUE TITLE
[Iterative-dev]Update Turbine Win Func Tests

### ISSUE THREAD

**Issue by maysunfaisal** [eclipse/codewind#907]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**
Currently we are using a cwctl installer from ages ago.

To pick up the hybrid/remote changes from the cwctl; we need to download and install a new one during every Turbine Win cronjob..

**Steps to reproduce:**

**Workaround:**

**Comment by jgwest** [comment]
@maysunfaisal In case you hadn't already seen this, you can steal [cli-pull.sh from here](https://github.com/eclipse/codewind-che-plugin/blob/master/codewind-che-sidecar/scripts/cli-pull.sh) to automaticallly download the latest cwctl. No parameters needed, just invoke with `CW_CLI_BRANCH=master ./cli-pull.sh` (env var is optional).

**Comment by maysunfaisal** [comment]
sweet, i did see that change, thx for reminding~

**Comment by ssh24** [comment]
@rajivnathan I am looking into this. Could you please assign this to me?

**Comment by ssh24** [comment]
This is now working. @maysunfaisal Could you close this issue?
