### ISSUE TITLE
Error starting codewind

### ISSUE THREAD

**Issue by aifayed** [eclipse/codewind#909]
I've installed docker and codewind plugin to eclipse and while starting codewind I get below error

There was a problem trying to start Codewind: 2019/10/30 10:58:33 CREATE_FILE_ERROR[201]: open installer-docker-compose.yaml: Access is denied.. 

**OS**
Windows 10

**Codewind version**
Version: 0.4.0

**Comment by liamchampton** [comment]
@aifayed please can you provide more information? - **Codewind version:**/**OS:** etc?

**Comment by aifayed** [comment]
@liamchampton  Updated in main post

**Comment by jopit** [comment]
@aifayed could you please attach the eclipse logs?  You can find them under your workspace, in `.metadata\.log`

**Comment by aifayed** [comment]
@tobespc  I tried the new version and getting the same issue. I got version  0.4.0 from eclipse marketplace few weeks ago.

**Comment by jopit** [comment]
@eharris369 what's the current working directory when we run the cli?  I think that's where the cli tries to write out the yaml file -- maybe the permissions on the directory don't allow the write?

**Comment by eharris369** [comment]
I don't know how go determines the working directory but the cwctl and appsody executables are copied to <user's Eclipse workspace>\.metadata\.plugins\org.eclipse.codewind.core\installerWorkDir and run from there.  The environment for the execution would be the same as the environment eclipse was started in.

**Comment by liamchampton** [comment]
Since its just the binary being called the working directory will be the directory the binary is in. This directory will need read/write/execute permissions to create the `installer-docker-compose.yaml`, write the contents to it and then delete it once `docker-compose` has finished. @aifayed do you have the correct permissions to do this/can you check them for the directory specified above?

**Comment by liamchampton** [comment]
@aifayed is this still a problem or can this issue be closed?

**Comment by tobespc** [comment]
moving to verify as unable to recreate on latest images.  @aifayed please reopen if it still happens for you on latest code
