### ISSUE TITLE
New and noteworthy for 0.6.0

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind#926]
Need to add a news page to the Codewind.dev website for 0.6.0.

**Comment by sishida** [comment]
Perhaps include mention that we no longer have the OpenShift on IBM Cloud for Codewind doc page because it is no longer necessary: https://github.com/eclipse/codewind/issues/962

**Comment by tetchel** [comment]
#846 is news but may merit its own page

**Comment by sishida** [comment]
Merged the PR to add the news for 0.6.0. Closing this issue.
