### ISSUE TITLE
Error of creating directory /codewind-workspace/cw-temp/

### ISSUE THREAD

**Issue by GeekArthur** [eclipse/codewind#927]
Currently if we use the latest Codewind to create project we can see the error below, seems like we should check directory existence of `/codewind-workspace/cw-temp/` before mkdir, otherwise this error will be always there
```
[30/10/19 15:43:31 /portal/routes/projects/remoteBind.route.js] [ERROR] Project creation failed for project gogo. Error: { [Error: EEXIST: file already exists, mkdir '/codewind-workspace/cw-temp/']
  errno: -17,
  code: 'EEXIST',
  syscall: 'mkdir',
  path: '/codewind-workspace/cw-temp/' }
```

Suggest solution:
Use `mkdir -p` instead `mkdir` to create the directory

**Comment by tobespc** [comment]
This has been fixed in a PR that landed last night
