### ISSUE TITLE
Project bind broken in che

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#930]
Moving my comments from #906 into this new issue to not distract from the original sync problem

For some reason the project types do not work in Che. The same command works in local.

```
root INFO [hosted-plugin: 72] [INFO: 19:52:37.385 CLIWrapper.js.on():142]: Successfully ran CLI command cwctl --json --insecure project bind --conid local --name goproj --language go --type docker --path /projects/goproj
[DBUG: 19:52:37.385 CLIWrapper.js.on():148]: CLI object output: {"error":"proj_response","error_description":"project type is invalid"}
```

**Comment by tetchel** [comment]
looking into this, the project-types API appears intact in Che. I omitted most of the output because it's too long but all the expected types are there.

bash-4.4$ curl -sSkL https://localhost:9090/api/v1/project-types
[
  ....
  {
    "projectType": "docker",
    "projectSubtypes": {
      "items": [
        {
          "id": "go",
          "label": "go"
        },
        {
          "id": "java",
          "label": "java"
        },
        {
          "id": "python",
          "label": "python"
        }
      ]
    }
  },
]bash-4.4$

I think the problem is that the cwctl outputs the "invalid type" message for any 400 error.
https://github.com/eclipse/codewind-installer/blob/master/utils/project/bind.go#L112

Perhaps we're getting 400 for a different reason, but the real error is being masked by this one? I don't see anything in the PFE logs.

**Comment by tetchel** [comment]
doing the request by hand worked, so it's not that. something is wrong with the cwctl wrapping of this command.
```
bash-4.4$ curl -X POST -sSkL https://localhost:9090/api/v1/projects/remote-bind/start -H "Content-Type: application/json" -d '{ "name": "goproj", "language": "go", "projectType": "docker", "path": "/projects/goproj" }'
{
  "projectID": "48af3b30-fb5b-11e9-b157-bda9f43e7bcc",
  "name": "goproj",
  "language": "go",
  "locOnDisk": "/projects/goproj",
  "host": "",
  "ports": "",
  "workspace": "/codewind-workspace/",
  "directory": "goproj",
  "infLockFlag": false,
  "loadTestPath": "/codewind-workspace/goproj/load-test",
  "projectType": "docker",
  "buildLogPath": null,
  "state": "closed",
  "autoBuild": true
}bash-4.4$
```

**Comment by ssh24** [comment]
Same issue I saw?
![Screen Shot 2019-10-30 at 4 23 00 PM](https://user-images.githubusercontent.com/15173354/67909722-9f4e9f80-fb56-11e9-8f2e-33c7bae8e736.png)

**Comment by tetchel** [comment]
yes although it should show the message from cwctl now, ie `project type is invalid`

**Comment by tobespc** [comment]
@ebuckle can you take a look please

**Comment by ebuckle** [comment]
Will do

**Comment by tetchel** [comment]
from https://github.com/eclipse/codewind/issues/884 it sounds like the local connection is hardcoded to use http, so this may be caused by that too (note my curls above use https)

**Comment by tobespc** [comment]
we have this fixed :-) .  about to land a change to the installer that resolves this
