### ISSUE TITLE
Refresh in Template Service Manager not working

### ISSUE THREAD

**Issue by gcharters** [eclipse/codewind#933]
**Codewind version: 0.5.0**
**OS: Mac (Catalina**

**Che version: N/A**
**IDE extension version: 0.5.0**
**IDE version:VS Code 1.39**
**Kubernetes cluster:**

**Description:**

"Refresh" doesn't appear to do anything.  If I change the underlying repository_list.json file, no changes are observed.

**Steps to reproduce:**

Modify the repository_list.json file and Click Refresh in the Template Service Manager.

**Workaround:** 
Stopping codewind, shutting down VS Code, starting VS Code, starting Codewind seems to work sometimes.

**Comment by tetchel** [comment]
this is the intended behaviour, but I can see why it would be confusing.

Refresh updates the repository list from the backend, but if you modify the file by hand your changes won't be picked up until Codewind restarts. 

We could put in an enhancement request to have a way to pick up the new file contents without restarting codewind, but I wonder why you are editing the file by hand in the first place?

**Comment by tetchel** [comment]
@tobespc do you think it is worth adding a refresh action in the backend, (eg. `PUT /templates/repositories` with no body) which would reload the repository_list, to support this scenario?

**Comment by tetchel** [comment]
We're not going to action this. If you are hitting issues with adding/removing template sources that are causing you to have to edit the file directly, we can address those.
