### ISSUE TITLE
2 errors (getting capabilities & toggling logs failed) on project create

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#936]
**Codewind version:** master
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**

I'm getting these 2 errors every time I create a new project.

<img width="447" alt="image" src="https://user-images.githubusercontent.com/17596240/67963045-55a49a00-fbd4-11e9-97a3-d3db0fdbc992.png">

Chatted with @tetchel and IDE make calls for capabilities and logs on project creation.  Suspect the calls are happening too early before projects are setup in Turbine, but unsure why it started happening now.

**Steps to reproduce:**

**Workaround:**

**Comment by makandre** [comment]
There's a `projectBind` success socket event at `remote-bind/start` https://github.com/eclipse/codewind/blob/master/src/pfe/portal/routes/projects/remoteBind.route.js#L125

Turbine is not yet involved at this point, possibly why pings for capabilities and logs are coming after this?

(however, this is not new code)

**Comment by makandre** [comment]
Commented out the `projectBind` event line and indeed I don't get the 2 errors anymore (but I don't know what breaks)

**Comment by ssh24** [comment]
I am unable to reproduce this. Appsody projects are emitting the events fine and I can also see them on the IDE
<img width="1621" alt="Screen Shot 2019-10-31 at 3 06 24 PM" src="https://user-images.githubusercontent.com/15173354/67978226-04a29f00-fbf0-11e9-8afa-57d27bb99e8c.png">

**Comment by rajivnathan** [comment]
@makandre Is this appsody projects or other projects?

**Comment by makandre** [comment]
All projects

**Comment by yangcao77** [comment]
Checked the `binding` route, the socket event was sent to ui socket after a build event is sent to Turbine.
https://github.com/eclipse/codewind/blob/a2540865948a54eaf3f70f44b25e6d26dd403424/src/pfe/portal/routes/projects/binding.route.js#L126-L128

However, in the remoteBind, portal does not send any creation request to Turbine before it's sending this success event to ui. So by the time ide requesting capailities& logs, the project has not created in Turbine yet.

**Comment by ssh24** [comment]
So it is an intermittent situation then? https://github.com/eclipse/codewind/issues/883#issuecomment-548035792

**Comment by rajivnathan** [comment]
@stalleyj This sounds like the same issue from https://github.com/eclipse/codewind/pull/354 ?

**Comment by makandre** [comment]
Yes I think it's because now (remote) bind is divided into `start` and `end`.  There's actually a second `projectBind` event emitted at `end`:

https://github.com/eclipse/codewind/blob/master/src/pfe/portal/routes/projects/remoteBind.route.js#L375

**Comment by yangcao77** [comment]
Sounds like a new event name is required for the `bind - start`.

**Comment by makandre** [comment]
Does IDE need to react to a bind start?  If not then maybe just don't emit at that point?

@tetchel

**Comment by tetchel** [comment]
###

**Comment by tetchel** [comment]
We could emit it later, the project will just show up in the IDE UI later.

**Comment by tobespc** [comment]
Yes, so the bind end is when you would expect to then be able to do logs etc not before

**Comment by tetchel** [comment]
isn't the fix still in portal?

**Comment by stalleyj** [comment]
@rajivnathan Yes, this exactly the same symptoms as #354. @tetchel Are you happy with us just removing the socket emit from bind start ?

**Comment by tetchel** [comment]
Makes sense to me

**Comment by stalleyj** [comment]
https://github.com/eclipse/codewind/pull/953

**Comment by makandre** [comment]
Verified that I don't get these errors anymore. Thanks.
