### ISSUE TITLE
Improve CLI output for IDE's

### ISSUE THREAD

**Issue by liamchampton** [eclipse/codewind#937]
**Description of the enhancement:**
IDE's need to consume the CLI output easily. There is currently inconsistency with the return error codes and not all commands return JSON output. To standardise this:
- all commands output JSON as an option
- if an error occurs, exit with error code 1 + description so that the IDE's can easily identify an error
- All logs go to one output file. Should a user encounter an error, they can send a single file containing all logs

**Proposed solution:** 
Introduce logrus package into the CLI. This containers multiple levels of logging, similar to whats seen in PFE. This will print all logs to 1 stream (stdout) and control what logs are printed for each level. If an error occurs then it will throw an obvious error for the IDE to consume. Provides both string and JSON output for both IDE's and user consumption.

**Comment by tetchel** [comment]
here's another,
```
[ /programs/codewind-vscode/dev ] 42 (master) $ bin/darwin/cwctl --json templates repos remove
2019/10/31 13:43:01 Error deleting template repo: "Error: '' is not a valid URL"
```

**Comment by tetchel** [comment]
```
[ /dev/bin/darwin ] 00 (auth) $ ./cwctl --json --insecure project create /Users/tim/programs/codewind-workspace/nodej --url https://github.com/codewind-resources/nodeExpressTemplate
2019/11/09 17:03:16 Downloaded file from 'https://codeload.github.com/codewind-resources/nodeExpressTemplate/legacy.zip/master' to '/var/folders/7m/17bccvdd1zq3b2lvwqv2cknr0000gn/T/_2019-11-09T17-03-16-05-00.zip'
2019/11/09 17:03:16 Extracted file from '/var/folders/7m/17bccvdd1zq3b2lvwqv2cknr0000gn/T/_2019-11-09T17-03-16-05-00.zip' to '/Users/tim/programs/codewind-workspace/nodej'
2019/11/09 17:03:16 There was a problem retrieving extensions data
{"status":"failed","projectPath":"/Users/tim/programs/codewind-workspace/nodej","result":"Get http:///api/v1/extensions: http: no Host in request URL"}
```

for some reason this time the error used the key "result"

**Comment by tobespc** [comment]
closing as we have improved the output.  Further enhancements will have individual items raised

**Comment by stalleyj** [comment]
Reopening this item as we are picking this work back up.  The initial requirement is to ensure that all cwctl commands used by the IDEs return json when the flag is passed.

**Comment by tobespc** [comment]
closing after speaking to @ebuckle
