### ISSUE TITLE
More cwctl commands need to take a connection ID parameter

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#941]
for example, `cwctl templates repos ls` does not take any parameters. so, how am I meant to tell the CLI which connection I want to fetch template repos for? It appears to always return the list from local.

**Comment by jopit** [comment]
Needed for true hybrid scenario

**Comment by tobespc** [comment]
we know we will need this, its not a bug as such as an enhancement feature

**Comment by tetchel** [comment]
also `templates` not just `templates repos`

**Comment by tetchel** [comment]
also `project create`

**Comment by jopit** [comment]
@tobespc to gather the info in one place, we need the following commands to take a connection ID parameter
`templates`
`templates repos`
`project create`

**Comment by james-wallis** [comment]
@tobespc I'll pick this up.

**Comment by james-wallis** [comment]
@tetchel Do we also want the connection ID parameter for the extension and ignorePaths API calls? I think so as they're talking to PFE.

**Comment by tetchel** [comment]
Yes if they are talking to PFE, I don't know those commands though, they are not used (directly) by the IDEs

**Comment by james-wallis** [comment]
Perfect, I'll implement those too.

**Comment by jopit** [comment]
I think the extension and ignorePaths API calls are used by Appsody and Turbine respectively -- @makandre and @elsony should at least be aware of this change.

**Comment by makandre** [comment]
I'm not sure what are the `extension` and `ignorePaths` commands either

**Comment by tetchel** [comment]
I think ignorePaths is filewatcher @jgwest

**Comment by james-wallis** [comment]
PR https://github.com/eclipse/codewind-installer/pull/217 adds the connection ID for all above apart from `project create` as it doesn't call the PFE API.

**Comment by tetchel** [comment]
I don't have the logs available now, but I think `project create` does use PFE to call `api/v1/extensions`

**Comment by makandre** [comment]
Oh you meant the `extensions` API, then yes `project create` does call that

**Comment by james-wallis** [comment]
Understood. I've added the connection ID to the `project create` command for the extensions API call.

**Comment by tetchel** [comment]
looks like the pr is https://github.com/eclipse/codewind-installer/pull/217

**Comment by james-wallis** [comment]
That PR has now been accepted so all the calls discussed have the `--conid` flag. 

I'm now doing the work to [persist the username in the connections.json](https://github.com/eclipse/codewind/issues/1104)

And will finish by completing the work in https://github.com/eclipse/codewind/issues/1143 to use the secure HTTP calls.

**Comment by tetchel** [comment]
verified
