### ISSUE TITLE
SVT: Appsody projects no longer have the option "Show Log Files" in Eclipse 

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#951]
**Codewind version:** 0.5.0
**OS:** Mac OS Mojave 10.14.6

**IDE extension version:** 0.5.0
**IDE version:** Eclipse IDE for Enterprise Java Developers 2019-09 R (4.13.0)

**Description:** Appsody projects no longer have the option "Show Log Files" 

<img width="1251" alt="Screen Shot 2019-11-04 at 8 56 09 AM" src="https://user-images.githubusercontent.com/49531960/68126174-31e99880-fee1-11e9-925a-ef8e3d817277.png">

**Steps to reproduce:**
1. Install and start Codewind 
2. Create an Appsody project
3. Right click on the created project
4. Look for the option "Show Log Files" 

**Note:** VS Code doesn't have the same behavior

@jagraj

**Comment by makandre** [comment]
I wonder if this is related to the new log architecture.

Could you ensure you have the newest codewind appsody extension by opening a shell to the PFE container, removing `/codewind-workspace/.extensions/codewind-appsody-extension`, and then restarting PFE?

cc @ssh24

**Comment by sujeilyfonseca** [comment]
I followed your suggestion and it worked after restarting PFE, but I wonder if a user can experience the same problem with Codewind 0.5.0.

**Comment by makandre** [comment]
For users, they would be getting a newer 0.6.0 of the extension which would overwrite the old 0.5.0.

I suspect you ran into this because you've been testing with newer builds but the version is essentially the same, so the older copy did not get overwritten.

**Comment by ssh24** [comment]
I think if it is Eclipse only it could be IDE related. I recall @tetchel making some changes on the IDE to pick up the new log architecture, but that change could only be VS Code based

**Comment by tetchel** [comment]
I did not make any changes for the new log architecture

**Comment by eharris369** [comment]
It is working now.  Please try again with the latest.

![image](https://user-images.githubusercontent.com/9484320/68307707-b0793e00-0079-11ea-8381-474aa579c60c.png)

**Comment by sujeilyfonseca** [comment]
I tested this GitHub issue with `codewind-0.6.0-201911061859.zip`, and I no longer see the problem:

<img width="687" alt="Screen Shot 2019-11-06 at 4 19 12 PM" src="https://user-images.githubusercontent.com/49531960/68338766-34025180-00b1-11ea-8b54-5cc2ae3c5cd4.png">
