### ISSUE TITLE
Support remote debugging of projects on Codewind on Kube

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#959]
We need to be supporting remote debug on Codewind on Kubernetes, especially as we work to deliver Hybrid support.

Some articles that talk about remote debugging on Kube and may be useful:
- https://dev.to/nheidloff/debugging-microservices-running-in-kubernetes-3f2b
- https://blog.christianposta.com/kubernetes/java-remote-debug-for-applications-running-in-kubernetes/

At a super high level, we may need to:
1) Expose the debugging port in the project's Kubernetes service (depends on framework)
2) Configure the project container to use that port, and/or support restarting in debug mode
3) Configure the local debugger to talk to the exposed debug port on the Kubernetes service

**Comment by johnmcollier** [comment]
As @jgwest noted on slack, we could also achieve remote debugging with SSH tunneling, as was done for Eclipse Tools for Bluemix

**Comment by jgwest** [comment]
I'm not necessarily advocating any specific solution: anything that uses a secure and auth-ed tunnel, rather than merely exposing a fully-open debug port, is fine. 👍

**Comment by tetchel** [comment]
https://github.com/eclipse/codewind/issues/1990
