### ISSUE TITLE
cwctl upgrade --workspace <codewind workspace> does not appear to do anything

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#961]
I installed 0.5.0 version of Codewind and created a go and a python project.  I uninstalled 0.5.0 and ran `cwctl upgrade --workspace <user dir>/codewind-workspace` but it does not appear to do anything except print out `About to upgrade projects`.  If I then install the latest version of codewind and run the API to list the projects the list is empty.  I tried running the upgrade again after installing and starting the latest but still the project list is empty.  I tried this on Windows and Linux (RedHat).

**Comment by tobespc** [comment]
@stalleyj please a look

**Comment by stalleyj** [comment]
@eharris369 The upgrade command has been broken by some of the connection logic, working on a fix.

**Comment by stalleyj** [comment]
pr up https://github.com/eclipse/codewind-installer/pull/190

**Comment by tetchel** [comment]
it still doesn't seem to work, 

```
==> Run cwctl --json --insecure upgrade --ws /Users/tim/codewind-workspace
About to upgrade projects
Calling bind for project plzz,liberty,java
<nil>
==> End cwctl --json --insecure upgrade --ws /Users/tim/codewind-workspace
```

I don't see anything in the PFE logs indicating that the bind API was ever called for that project, and there's no output after [line 64](https://github.com/eclipse/codewind-installer/pull/190/files#diff-b9c476fb866b1309274372b666a7ef6aR62)

**Comment by eharris369** [comment]
It worked for me:
./cwctl upgrade --workspace /root/codewind-workspace
About to upgrade projects
Calling bind for project go1,docker,go
Project ID: eb5cd550-001e-11ea-9379-5f46ae802244
Status: 200 OK
And the upgraded go project builds and run successfully.

**Comment by tetchel** [comment]
ok, i'll try with another workspace then

**Comment by eharris369** [comment]
I can't get it to work on Windows though:
```
cwctl upgrade --workspace C:\codewind-workspace
About to upgrade projects
Calling bind for project go2,docker,go
<nil>
```

**Comment by tetchel** [comment]
in any case, it doesn't look like the error logging is working the way it's supposed to

**Comment by stalleyj** [comment]
I've added some more error handling and messages with this https://github.com/eclipse/codewind-installer/pull/195

I've also figured out why it fails on windows.  To determine the location of the source to pass into the bind command, I use the workspace + name from the inf file and they look wrong like this  "workspace": "/c/codewind-workspace/",

**Comment by eharris369** [comment]
Looks like the docker version of the path. I can pass in the path like that if necessary.

**Comment by stalleyj** [comment]
@eharris369 Good idea, I'll try that

**Comment by stalleyj** [comment]
https://github.com/eclipse/codewind-installer/pull/198 . Should fix upgrade for windows

**Comment by eharris369** [comment]
It is also not always returning a non-zero error code when it fails.  If the workspace is not found then the error code is 1.  If there is a problem with one of the projects then the error code is 0.
```
C:\tmp\test\windows>cwctl --json upgrade --workspace C:\foo
{"error":"proj_path","error_description":"FindFirstFile C:\\foo: The system cannot find the file specified."}

C:\tmp\test\windows>echo %errorLevel%
1
```
```
C:\tmp\test\windows>cwctl --json upgrade --workspace C:\codewind-workspace
About to upgrade projects from C:\codewind-workspace
Looking for projects in C:\codewind-workspace/.projects/
Calling bind for project go1,docker,go in /C/codewind-workspace/go1
{"error":"proj_path","error_description":"FindFirstFile /C/codewind-workspace/go1: The system cannot find the path specified."}

C:\tmp\test\windows>echo %errorLevel%
0
```

**Comment by jopit** [comment]
@eharris369 please verify this is fixed

**Comment by tetchel** [comment]
Also we cannot parse the json error output if there is a bunch of non-json output before it

**Comment by eharris369** [comment]
Windows is working now!!

**Comment by jopit** [comment]
> It is also not always returning a non-zero error code when it fails. If the workspace is not found then the error code is 1. If there is a problem with one of the projects then the error code is 0.

> Also we cannot parse the json error output if there is a bunch of non-json output before it

I think we need these fixed before we can declare this one done.

**Comment by tobespc** [comment]
So in the scenario that 4 projects successfully update but one fails, is that an overall failure scenario ?

**Comment by jopit** [comment]
I'd say yes, but I think the returned json should reflect which ones succeeded and which ones failed.

**Comment by tobespc** [comment]
ok, makes sense, will get that resolved tomorrow

**Comment by tetchel** [comment]
ideally we would be able to parse which project names successfully migrated and which failed

**Comment by malincoln** [comment]
@tobespc @jopit if this one is still being worked, pls move back to In progress.  Thanks

**Comment by tobespc** [comment]
@ebuckle please action

**Comment by ebuckle** [comment]
Will take a look

**Comment by tobespc** [comment]
@ebuckle Can you put a PR up against 0.6.0 as well please

**Comment by malincoln** [comment]
@eharris369 pls verify and close if resolved.  Thanks

**Comment by tetchel** [comment]
not fixed, the new output is not valid JSON:
```
{
    "failed": [
        {
            "error": "project name is already in use",
            "projectName": "mpproj"
        }
    ],
    "migrated": []
}
{"error":"error occurred upgrading projects","error_description":"One or more projects failed to upgrade"}
```

You can only have one top-level object.
Really, the error and error_description are not useful at all for this, since we already know that `one or more projects failed to upgrade` from the `failed` array. Ideally they could just be removed.

I also know I requested we exit with an error code (1) if a project fails to migrate, but I realized it doesn't really make sense, since the migration still executed. I'd rather have it exit with 0, and then generate an error from `failed`. Hopefully that isn't too big of a change to undo.

**Comment by malincoln** [comment]
@jopit can we get this moved back to In Progress so @stalleyj and @ebuckle  can fix?

**Comment by ebuckle** [comment]
Yep, I see what was causing the issue. I was printing off the response object and then checking for errors to also print off. 

- Now no longer returning an error when projects fail to upgrade
- Moved the printing of the response object to be after error checking, meaning the response prints one or the other, see PR

**Comment by liamchampton** [comment]
@ebuckle https://github.com/eclipse/codewind-installer/pull/213 this PR provides a false positive. We want to exit(1) upon failure. The CLI and PFE should be treated as single entity and any failure in API calls should be represented in the CLI output.

**Comment by tetchel** [comment]
liam, it sounds like it's in line with what I requested above at the bottom of https://github.com/eclipse/codewind/issues/961#issuecomment-553581217

**Comment by tetchel** [comment]
I am satisfied, thanks @ebuckle :+1:
