### ISSUE TITLE
Remove doc on setting up OpenShift on IBM Cloud for Codewind

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#962]
We currently have a doc that outlines the steps needed to get OpenShift on IBM Cloud (ROKS) working for Codewind (https://www.eclipse.org/codewind/mdt-che-roks.html).

These steps are no longer needed with the remote architecture changes delivered into Codewind and the Che sidecar over the past week. The setup instructions for Codewind on ROKS are the same as any regular OpenShift install.

**Comment by sishida** [comment]
PR has been merged. Closing this issue.
