### ISSUE TITLE
SVT [landing pages]: Codewind mobile site does not render well

### ISSUE THREAD

**Issue by beccabau** [eclipse/codewind#964]
**Codewind version:** N/A
**OS:** Android version 10

**Description:** Landing pages - home page for codewind.dev does not render well on my phone.

![image](https://user-images.githubusercontent.com/13971834/68152925-92dd9480-ff12-11e9-81a5-04ec3fe70600.png)

**Steps to reproduce:** Hit `codewind.dev` on your phone (really small screen), notice that the example IDE windows do not stack well/stay within the header part. Could still be related to dynamic rendering issue the team is still addressing for regular view of landing pages.

**Workaround:** 

No workaround for mobile view.

**Comment by beccabau** [comment]
![Screenshot_20200107-091315](https://user-images.githubusercontent.com/13971834/71901465-02981780-312e-11ea-9934-075a854d8dff.png)

Looks fixed on my phone now

**Comment by travis1111** [comment]
Thanks!  I delivered a fix in Dec. :-)
