### ISSUE TITLE
[Remote - che] Update for microprofile project does not get reflected

### ISSUE THREAD

**Issue by yangcao77** [eclipse/codewind#966]
**Codewind version:** master
**OS:** macos

**Che version:** 7.2.0
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:** OKD

**Description:**
Update a single java file of a microprofile project, I can see the rebuild has been taken place. However, the change is not reflected in the app. 
![image](https://user-images.githubusercontent.com/22285490/68154100-c5888c80-ff14-11e9-9614-eacb91a11211.png)
![image](https://user-images.githubusercontent.com/22285490/68154126-d46f3f00-ff14-11e9-9400-d33da49fdecb.png)

I have checked the pfe container and the project container, I can see the change. 
```
[root@codewind-workspace07jess4mwuvcvrig-54b5b45d6f-564dn application]# cat HealthEndpoint.java 
package application;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.Application;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;

@Path("health")
public class HealthEndpoint {

    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public Response healthcheck() {
      /*
      if (!healthy) {
        return Response.status(503).entity("{\"status\":\"DOWN\"}").build();
      }
      */
      return Response.ok("{\"status\":\"down\"}").build();
    }

}
```

Manual build also won't pick up the change

**Steps to reproduce:**
1. Create a microprofile project from template
2. Wait till the status becomes `started`
3. Update a single java file, i.e. `/src/main/java/application/HealthEndpoint.java`
4. Wait till the build finished, and check the health Endpoint

**Workaround:**

**Comment by johnmcollier** [comment]
@yangcao77 This is because the Liberty container includes a default health endpoint at `/health` that overrides the one in the code.

Can you try modifying another file (e.g. example.java) and see if it takes effect?

**Comment by yangcao77** [comment]
Confirmed that the update works when modifying another file as suggested by@johnmcollier 
Closing this issue since it's invalid.
