### ISSUE TITLE
Set Deployment registry via CLI

### ISSUE THREAD

**Issue by markcor11** [eclipse/codewind#968]
**Codewind version:** latest

**Description of the enhancement:**

Need a way to set the deployment docker registry of "remote" using the CLI.  When performing a BIND,  if a registry has not been set the project will not build 

**Proposed solution:** 
There is already a PFE API for setting the registry : `POST:  /api/v1/registry` however the CLI should be able to perform this operation and set credentials.

**Comment by tetchel** [comment]
https://github.com/eclipse/codewind/issues/665, https://github.com/eclipse/codewind/issues/845
