### ISSUE TITLE
Remote: - Improve browser experience and impact of Self Signed Certificates

### ISSUE THREAD

**Issue by markcor11** [eclipse/codewind#971]
**Codewind version:** latest

**Description of the enhancement:**
When deploying Codewind remote it is initially deployed with self signed certificates across Codewind Gatekeeper, Keycloak and PFE.  Self signed certificates whilst providing an initial encrypted connection will cause browsers to display the "Not trusted" error message.  The user can accept the certificate in their browser and continue but it is a poor initial user experience. 

**Proposed solution:** 

Openshift provides a few different methods of TLS termination,  Edge, Passthru and Re-encrypt. Currently Codewind uses the Passthru mode which has the TLS termination  occurring in the Gatekeeper pod.

By changing to the Re-encrypt router mode. TLS connections are terminated at the router edge using the router's default certificate. The Openshift router then creates a new internal connection to the Codewind pod inside the cluster using the self signed Codewind certificate.  The end result is that the user sees only the Openshift router certificate (one they have likely already trusted to gain access to the cluster console web ui) rather than have to handle the self signed certificate from Codewind.

**Comment by markcor11** [comment]
Edge termination alone does not support encrypted internal network traffic.  The "re-encrypt" mode will per above terminate the connection first at the router edge but then re-encrypt the connection to the PFE service.  One challenge to be overcome with "re-encrypt" is that the router needs to trust the target PFE TLS certificate. Right now PFE uses a self-signed cert and generates it when the pod is scheduled. This would break the route trusted relationships if the pod re-scheduled and make it unaccessible from outside the cluster - bad. 

What we could do is generate the PFE Key and cert using the CLI at deployment time and send that over to PFE by way of a Kube mounted secret.  That would :  

* give each PFE a unique key and cert generated at deployment time - good, 
* persist the secret across pod restarts - good,    
* use the known certificate within the route at creation during install - good
* provide end to end encryption on both the external and internal cluster networks - good

**Comment by malincoln** [comment]
@tobespc I'm removing 0.7.0 release.  Pls update once you know the target release.  Thanks

**Comment by markcor11** [comment]
All the required PRs are now merged which will ensure the Gatekeeper certificate is reused rather than recreated following a pod restart. That squashes  the unnecessary trust warnings in the browser.  It also makes it much easier now to import a different server key and certificates by way of the Kube TLS secret.

**Comment by markcor11** [comment]
Fixes merged and verified - closing this issue.  We have started considering cluster CA generated alternatives to self-signed certificates.

**Comment by tetchel** [comment]
Right now the IDEs run all cwctl commands with the `--insecure` flag. At some point it would be nice to make a user have to explicitly disable SSL cert checking instead of doing it for them. What will have to be done before we can consider that?

**Comment by tobespc** [comment]
I'll raise a new item to cover that @tetchel

**Comment by tobespc** [comment]
https://github.com/eclipse/codewind/issues/2989
