### ISSUE TITLE
New app monitor dashboard to display prometheus metrics of Codewind projects

### ISSUE THREAD

**Issue by rwalle61** [eclipse/codewind#977]
**Codewind version:** Latest
**OS:** Mac

**Description of the enhancement:**

Appmetrics-dash and javametrics-dash are cool, but users don't want to have to include that code in their projects. It'd be useful to be able to see these metrics dashboard without the user having to change anything about their Codewind projects.

**Proposed solution:** 

It'd be good if the IDEs' `Open App Monitor` button would point to a metrics dashboard on an endpoint not hosted by the project itself, but by Codewind, such as `http://127.0.0.1:34000/performance/codewind-metrics/dashboard/java?theme=dark&projectID=34e06980-fca0-11e9-b7e4-0558a951d35a`.

**Comment by rwalle61** [comment]
@mattcolegate and myself are working on this, with others:
- https://github.com/eclipse/codewind/issues/514
- https://github.com/eclipse/codewind-eclipse/pull/396

**Comment by rwalle61** [comment]
(FYI it will require code changes to the VSCode and Eclipse IDEs, but Matt and I will do the work/ lead the requirements)

**Comment by rwalle61** [comment]
with @tobespc we have decided to merge the `appmetrics-prometheus` and `PFE` changes for 0.6.0, then merge change to the plugins later (probably 0.7.0), when the new PFE dashboard supports Swift as well

**Comment by rwalle61** [comment]
So the PFE changes are in: we can inject metrics into nodejs, liberty and spring projects.

The remaining thing is to have the `open app monitor` button on the IDEs (VSCode, Eclipse and Theia) pointing to:
* `${appOrigin}/appmetrics-dash` if the user has appmetrics as part of the app itself, or
* `${pfeOrigin}/performance/monitor/dashboard?theme=dark&projectID=${projectID}` if the user does not have appmetrics as part of the app itself, and has appmetrics injected (using our new injection mechanism).

Whereas I have previously opened PRs in the IDE repos to manage this logic in the IDEs, I think it it makes more sense to have this logic in PFE instead. This allows the IDEs, as frontends, to simply consume information from PFE, where everything is worked out. 

More specifically, PFE will calculate the app monitor dashboard url, and provide that information on the `GET api/v1/projects/{id}` endpoint. The IDEs will be able to simply ask PFE what the `appMonitorUrl` is for the project.

I'm working on that now

**Comment by jgwest** [comment]
@rwalle61: Unable to locate pipeline with name: `inProgress`

**Comment by jgwest** [comment]
@rwalle61: Unable to locate pipeline with name: `InProgress`

**Comment by rwalle61** [comment]
@eharris369 @tetchel we have nearly finished the work mentioned above: to calculate the app monitor dashboard url in PFE and provide that information on the GET api/v1/projects/{id} endpoint. 

So after we merge that PR, the IDEs will be able to simply ask PFE what the appMonitorUrl is for the project. I've raised a [PR for the VSCode plugin](https://github.com/eclipse/codewind-vscode/pull/329) to illustrate this - please review (but don't merge until that PR is merged and I have checked that it works for Swift, hopefully all happening tomorrow/wednesday).

**Comment by jopit** [comment]
Is this going into 0.7.0?

**Comment by rwalle61** [comment]
@jopit yea. Should land tomorrow

**Comment by rwalle61** [comment]
Change of plan because it turns out that:
1. PFE, when running locally, doesn't seem to know its origin (e.g. `http://localhost:10000`), but the IDE does. This is needed because the appMonitorUrl can point to the dashboard hosted at PFE.
2. PFE sends the IDE project data via both `GET projects` and the `onProjectStatusChange` socket message. This makes it more complicated for PFE to keep the `project.appMonitorUrl` up to date between restarts of PFE (because the port may change).

Therefore we have decided to keep the logic in the IDEs. We will extend the existing `getAppMonitorUrl` function to provide the correct link for the circumstance.

**Comment by rwalle61** [comment]
done - manually tested on master and 0.7.0 branch

**Comment by rwalle61** [comment]
related issue https://github.com/eclipse/codewind/issues/1509
