### ISSUE TITLE
[IntelliJ] Add Project Overview page

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind#984]

**Comment by keithchong** [comment]
@jopit , I'll pick up this low hanging fruit.

**Comment by keithchong** [comment]
@mmulholl this is the project overview enhancement

**Comment by keithchong** [comment]
PR has been created.  I've installed the plugin from the zip:

![Screen Shot 2020-02-04 at 6 01 18 PM](https://user-images.githubusercontent.com/7726022/73795384-730b7600-4778-11ea-9ef9-4ad854c4df14.png)
