### ISSUE TITLE
[IntelliJ] Show project log files

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind#989]

**Comment by keithchong** [comment]
Updates to two console logs from two different IDEs, of the same application.  Here, one of the application's endpoints was used to test the console output (See println), and the HTTP get request was made multiple times.

![Screen Shot 2020-02-12 at 4 20 05 PM](https://user-images.githubusercontent.com/7726022/74378227-91462700-4db3-11ea-850b-90c68201c3db.png)

**Comment by keithchong** [comment]
Context menu
![Screen Shot 2020-02-12 at 5 33 17 PM](https://user-images.githubusercontent.com/7726022/74383760-d1120c00-4dbd-11ea-89e0-d313e19ad6f3.png)

**Comment by keithchong** [comment]
Tool window dropdown showing logs for more than one project

![Screen Shot 2020-02-12 at 5 34 59 PM](https://user-images.githubusercontent.com/7726022/74383867-0cacd600-4dbe-11ea-8fe3-ba53d1ed4744.png)
