### ISSUE TITLE
[SVT] [VSCode] Socket hang up when creating new project.

### ISSUE THREAD

**Issue by DavidG1011** [eclipse/codewind#992]
**Codewind version:** Latest
**OS:** MacOS

**IDE:** VSCode
**IDE extension version:** Latest

**Description:** Socket hang up error when creating new project.

**Steps to reproduce:**
1. Remove codewind entirely from system. images, `.codewind`, `codewind-workspace`, etc.
2. Install latest extension.
3. Create new project.

Result: Project menu displays "fetching available project templates.." and a socket hang up error appears:

<img width="1646" alt="Screen Shot 2019-11-05 at 12 15 01 PM" src="https://user-images.githubusercontent.com/30476587/68229910-160bf280-ffc6-11e9-9a4e-963c5999646f.png">

The PFE container also gets stopped.

**Comment by tetchel** [comment]
please upload the logs, but i am fairly certain it's https://github.com/eclipse/codewind/issues/946

**Comment by DavidG1011** [comment]
Seems to be the same issue:
[pfe.txt](https://github.com/eclipse/codewind/files/3810674/pfe.txt)

```
undefined:2
*
^

SyntaxError: Unexpected token * in JSON at position 1
    at JSON.parse (<anonymous>)
    at exec (/codewind-workspace/.extensions/codewind-appsody-extension/templatesProvider.js:30:35)
    at ChildProcess.exithandler (child_process.js:285:7)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
 ```

**Comment by DavidG1011** [comment]
Fixed by removing the `codewind_cw-workspace` docker volume and refreshing images.
