### ISSUE TITLE
Ensure user specifies full path when creating app in non-default location

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind#995]
**Codewind version:** latest
**OS:** macOS Catalina

When creating an app, I deselected the 'Use default location' checkbox, and typed 'zzz' into the location field.  The application was created inside the Eclipse.app "folder", probably because that's the current folder when running Eclipse.  However, that's not a valid location for apps.  We should ensure that the user enters a full path in the location field

![image](https://user-images.githubusercontent.com/29612372/68236424-24144000-ffd3-11e9-813c-4c261fc7cf8a.png)

**Comment by eharris369** [comment]
Fixed by: https://github.com/eclipse/codewind-eclipse/pull/406.  Please verify.
