### ISSUE TITLE
SVT: [Windows] Appsody projects are in "Disable" state the first time they are created or get stuck in "Starting" state if manual enable is attempted

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#997]
**Codewind version:** codewind-0.6.0-201911051703.vsix
**OS:** VM with Windows 10

**IDE extension version:** 0.6.0
**IDE version:** 1.39.2

**Description:** I got all Appsody projects in “Disable” state the first time they were created. After manually enabling them, they did not start due to:

``` 
[Error] The current directory is not a valid appsody project. Run `appsody init <stack>` to create one. Run `appsody list` to see the available stacks.
```

I deleted all Codewind's images, volumes, and files, and uninstalled and reinstalled the plugin, but I still see the problem. I also tried to remove the Appsody extension from PFE and restart the container.

Here is an example of the problem:
<img width="1633" alt="Screen Shot 2019-11-05 at 4 12 02 PM" src="https://user-images.githubusercontent.com/49531960/68246581-149ef200-ffe7-11e9-8501-661e789fddbb.png">

**Steps to reproduce:**
1. Install and start Codewind 0.6.0
2. Create an Appsody project

Standard templates are working fine on my machine.

@jagraj

**Comment by jopit** [comment]
Maybe another issue due to the REMOTE_MODE flag in PFE?

**Comment by sujeilyfonseca** [comment]
I saw some error messages in codewind.log:

```
[ERRO: 16:13:32.837 CreateUserProjectCmd.js:119]: Error creating new project: 
Error running "cwctl.exe --json --insecure project bind --conid local --name cw-appsody-python --language python --type appsodyExtension
```

[codewind.log](https://github.com/eclipse/codewind/files/3811496/codewind.log)

**Comment by makandre** [comment]
There's a panic from the CLI during `bind/end`

```
[ERRO: 16:13:32.836 CLIWrapper.js.on():149]: Error running "cwctl.exe --json --insecure project bind --conid local --name cw-appsody-python --language python --type appsodyExtension --path c:\CW-0.6.0\cw-appsody-python"
[ERRO: 16:13:32.836 CLIWrapper.js.on():150]: Stdout:

[ERRO: 16:13:32.836 CLIWrapper.js.on():151]: Stderr:
panic: Post http://127.0.0.1:10000/api/v1/projects/d7bd3700-0010-11ea-a7ca-875e6fc99e4a/bind/end: EOF

goroutine 1 [running]:
github.com/eclipse/codewind-installer/pkg/utils/project.completeBind(0xc0002c10b0, 0x24, 0xc0001572c0, 0x1e, 0xc0001572c0, 0x1e, 0x0)
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/pkg/utils/project/bind.go:166 +0x21c
```

**Comment by mattcolegate** [comment]
Taking a look

**Comment by mattcolegate** [comment]
Tested on Windows using VSCode extension https://download.eclipse.org/codewind/codewind-vscode/master/164/ and CW_TAG=latest. Could not recreate - projects came up as expected (apart from the ones that are meant to stop) apart from Appsody Kitura, which had the following in the container log:
```
Running APPSODY_PREP command: if [ -n "$(diff -rq /project/deps /project/user-app/.appsody)" ]; then rm -rf /project/user-app/.appsody && cp -R -p /project/deps /project/user-app/.appsody; fi
diff: /project/user-app/.appsody: No such file or directory
Running command:  swift run
error: Error Domain=NSCocoaErrorDomain Code=260 "The file doesn’t exist."
Wait received error on APPSODY_RUN/DEBUG/TEST exit status 1
```
Disabling and re-enabling the projects did not cause any hanging.

@sujeilyfonseca can you retest on latest again and see if it's still a problem?

**Comment by sujeilyfonseca** [comment]
I tested this GitHub issue with `codewind-0.6.0-201911061850.vsix`, and I no longer see the problem. I also noticed the same error with Appsody Kitura projects:

![Screen Shot 2019-11-06 at 2 50 29 PM](https://user-images.githubusercontent.com/49531960/68332816-5d1ce500-00a5-11ea-998c-b1ffa076a934.png)

![Screen Shot 2019-11-06 at 2 54 34 PM](https://user-images.githubusercontent.com/49531960/68332815-5d1ce500-00a5-11ea-9e23-8330918081e9.png)

**Comment by makandre** [comment]
`kitura` is a new stack we haven't officially added support for: https://github.com/eclipse/codewind/issues/866
