### ISSUE TITLE
Codewind unexpectedly crashed in Windows VSCode

### ISSUE THREAD

**Issue by naveenkaratekid** [eclipse/codewind#998]
**Codewind version: 0.6.0**
**OS: Windows 10**

**IDE extension version: 0.6.0**
**IDE version:1.39.2**

**Description:**
Codewind seems to be randomly restarting itself. The most recent occurrence was when I was looking at log files for the Codewind SpringBoot template. The status of Codewind changed to ```Disconnected```, and after a few seconds or so, all the projects I created show up under the Codewind Explorer.

**Steps to reproduce:**
1. Create a bunch of projects, Appsody or non-Appsody.

@jagraj

**Comment by tetchel** [comment]
please post pfe and extension logs

**Comment by jgwest** [comment]
@naveenkaratekid Do you think this is related to VSCode, or is this just the environment where you saw it? Also I presume it was the actual Codewind server (Docker images) that were restarting, rather than the IDE?

**Comment by naveenkaratekid** [comment]
hey @tetchel. My apologies. Here are the log files from PFE and from VSCode

**Logs from VSCode**
[codewind.log](https://github.com/eclipse/codewind/files/3811404/codewind.log)
[filewatcherd-1.log](https://github.com/eclipse/codewind/files/3811405/filewatcherd-1.log)
[codewind pfe latest log.txt]

**Codewind PFE Log**:
(https://github.com/eclipse/codewind/files/3811406/codewind.pfe.latest.log.txt)

**Comment by naveenkaratekid** [comment]
@jgwest I was running on VSCode in Windows

**Comment by tetchel** [comment]
from the vs code logs,
`[INFO: 16:19:49.902 CLIWrapper.js:134]: Running CLI command: project sync --path c:\codewind-workspace\svt-sp --id 01e2b460-0011-11ea-8972-53db8c708b3f --time 1572988365171`

the `sync` command has been removed (commented out) from the vs code tools as of last week, are you sure your vsix is up to date?
https://github.com/eclipse/codewind-vscode/blob/master/dev/src/codewind/connection/CLICommands.ts#L131

**Comment by jgwest** [comment]
@tetchel Unrelated to this specific issue, but could we automatically embed the build date and/or last GitHub commit ID (at build time) into the build, and have it appear at the top of the VSCode logs?  🤔

**Comment by tetchel** [comment]
yea, i'm thinking of a solution for this now...

**Comment by tetchel** [comment]
@naveenkaratekid can you provide an update and/or close this issue
